Repository ray-project/ray, pull requests merged in 2019-07, with the labels that each got.

#4450 [tune] Change the log syncing behavior
  doc/source/tune-usage.rst
  python/ray/rllib/train.py
  python/ray/tune/config_parser.py
  python/ray/tune/examples/logging_example.py
  python/ray/tune/experiment.py
  python/ray/tune/log_sync.py
  python/ray/tune/logger.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_trial_runner.py
  python/ray/tune/trial.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
Labels: tests ok

#5082 [autoscaler] Add hard kill and monitor commands
  python/ray/autoscaler/commands.py
  python/ray/scripts/scripts.py
Labels: tests ok

#4864 [autoscaler] Small fixes for local cluster usability
  python/ray/autoscaler/local/node_provider.py
  python/ray/autoscaler/updater.py
Labels: tests ok

#4893 Add warning/error if object store memory exceeds available memory
  python/ray/memory_monitor.py
  python/ray/services.py
  python/ray/tests/test_actor.py
  python/ray/tests/test_cython.py
  python/ray/tests/test_stress.py
  python/ray/utils.py
Labels: tests ok

#5101 [rllib] Fix impala stress test
  ci/long_running_tests/README.rst
  ci/long_running_tests/config.yaml
  ci/long_running_tests/start_workloads.sh
  python/ray/rllib/optimizers/aso_aggregator.py
Labels: tests ok

#4868 [tune] Document trainable attributes and enable user-checkpointing
  python/ray/rllib/agents/mock.py
  python/ray/rllib/agents/trainer.py
  python/ray/tune/result.py
  python/ray/tune/tests/test_trial_runner.py
  python/ray/tune/trainable.py
  python/ray/tune/trial_runner.py
Labels: tests ok

#5201 [rllib] Fix rollout.py with tuple action space
  ci/travis/format.sh
  doc/source/rllib-concepts.rst
  python/ray/rllib/evaluation/episode.py
  python/ray/rllib/rollout.py
Labels: tests ok

#5204 [rllib] Remove nested import
  python/ray/rllib/evaluation/metrics.py
  python/ray/rllib/evaluation/sampler.py
Labels: tests ok

#5215 [rllib] MultiCategorical shouldn't return array for kl or entropy
  ci/travis/format.sh
  python/ray/rllib/agents/impala/vtrace_policy.py
  python/ray/rllib/agents/ppo/appo_policy.py
  python/ray/rllib/models/action_dist.py
Labels: tests ok

#5225 Fix two types of eviction hangs
  python/ray/tests/test_actor.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_stress.py
  python/ray/tests/test_unreconstructable_errors.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/reconstruction_policy.cc
  src/ray/raylet/reconstruction_policy.h
  src/ray/raylet/reconstruction_policy_test.cc
Labels: stability-blocker

#5242 [rllib] Port DDPG to the build_tf_policy pattern
  python/ray/rllib/agents/ddpg/ddpg.py
  python/ray/rllib/agents/ddpg/ddpg_model.py
  python/ray/rllib/agents/ddpg/ddpg_policy.py
  python/ray/rllib/agents/ddpg/noop_model.py
  python/ray/rllib/agents/dqn/distributional_q_model.py
  python/ray/rllib/agents/dqn/dqn.py
  python/ray/rllib/agents/dqn/dqn_policy.py
  python/ray/rllib/agents/dqn/simple_q_model.py
  python/ray/rllib/evaluation/rollout_worker.py
  python/ray/rllib/models/catalog.py
  python/ray/rllib/models/modelv2.py
  python/ray/rllib/models/tf/modelv1_compat.py
  python/ray/rllib/models/tf/tf_modelv2.py
  python/ray/rllib/policy/dynamic_tf_policy.py
  python/ray/rllib/policy/tf_policy.py
  python/ray/rllib/policy/tf_policy_template.py
Labels: tests ok

#5249 [rllib] ModelV2 support for pytorch
  doc/source/rllib-models.rst
  python/ray/rllib/agents/a3c/a3c_torch_policy.py
  python/ray/rllib/agents/pg/torch_pg_policy.py
  python/ray/rllib/agents/qmix/model.py
  python/ray/rllib/agents/qmix/qmix_policy.py
  python/ray/rllib/examples/custom_torch_policy.py
  python/ray/rllib/models/catalog.py
  python/ray/rllib/models/fcnet.py
  python/ray/rllib/models/model.py
  python/ray/rllib/models/modelv2.py
  python/ray/rllib/models/tf/modelv1_compat.py
  python/ray/rllib/models/tf/tf_modelv2.py
  python/ray/rllib/models/torch/fcnet.py
  python/ray/rllib/models/torch/model.py
  python/ray/rllib/models/torch/torch_modelv2.py
  python/ray/rllib/models/torch/visionnet.py
  python/ray/rllib/models/visionnet.py
  python/ray/rllib/policy/torch_policy.py
  python/ray/rllib/policy/torch_policy_template.py
  python/ray/rllib/tests/test_nested_spaces.py
Labels: tests ok

#5143 Retry and exception for hang on memory store full
  bazel/ray_deps_setup.bzl
  build.sh
  python/ray/ray_constants.py
  python/ray/tests/test_failure.py
  python/ray/worker.py
Labels: stability-blocker

#5277 [rllib] Document ModelV2 and clean up the models/ directory
  ci/jenkins_tests/run_rllib_tests.sh
  doc/source/rllib-algorithms.rst
  doc/source/rllib-concepts.rst
  doc/source/rllib-examples.rst
  doc/source/rllib-models.rst
  doc/source/rllib.rst
  python/ray/rllib/agents/dqn/dqn_policy.py
  python/ray/rllib/agents/impala/impala.py
  python/ray/rllib/agents/impala/vtrace.py
  python/ray/rllib/agents/impala/vtrace_policy.py
  python/ray/rllib/agents/ppo/appo_policy.py
  python/ray/rllib/agents/ppo/ppo.py
  python/ray/rllib/agents/ppo/test/test.py
  python/ray/rllib/agents/qmix/model.py
  python/ray/rllib/agents/qmix/qmix_policy.py
  python/ray/rllib/agents/trainer.py
  python/ray/rllib/evaluation/sampler.py
  python/ray/rllib/examples/batch_norm_model.py
  python/ray/rllib/examples/custom_env.py
  python/ray/rllib/examples/custom_keras_model.py
  python/ray/rllib/examples/custom_loss.py
  python/ray/rllib/examples/eager_execution.py
  python/ray/rllib/examples/parametric_action_cartpole.py
  python/ray/rllib/models/__init__.py
  python/ray/rllib/models/action_dist.py
  python/ray/rllib/models/catalog.py
  python/ray/rllib/models/model.py
  python/ray/rllib/models/modelv2.py
  python/ray/rllib/models/tf/fcnet_v1.py
  python/ray/rllib/models/tf/fcnet_v2.py
  python/ray/rllib/models/tf/lstm_v1.py
  python/ray/rllib/models/tf/misc.py
  python/ray/rllib/models/tf/modelv1_compat.py
  python/ray/rllib/models/tf/recurrent_tf_modelv2.py
  python/ray/rllib/models/tf/tf_action_dist.py
  python/ray/rllib/models/tf/tf_modelv2.py
  python/ray/rllib/models/tf/visionnet_v1.py
  python/ray/rllib/models/torch/fcnet.py
  python/ray/rllib/models/torch/torch_action_dist.py
  python/ray/rllib/models/torch/torch_modelv2.py
  python/ray/rllib/models/torch/visionnet.py
  python/ray/rllib/optimizers/aso_aggregator.py
  python/ray/rllib/optimizers/aso_learner.py
  python/ray/rllib/optimizers/aso_minibatch_buffer.py
  python/ray/rllib/optimizers/aso_multi_gpu_learner.py
  python/ray/rllib/optimizers/aso_tree_aggregator.py
  python/ray/rllib/optimizers/async_gradients_optimizer.py
  python/ray/rllib/optimizers/async_replay_optimizer.py
  python/ray/rllib/optimizers/multi_gpu_optimizer.py
  python/ray/rllib/optimizers/policy_optimizer.py
  python/ray/rllib/optimizers/rollout.py
  python/ray/rllib/optimizers/sync_batch_replay_optimizer.py
  python/ray/rllib/optimizers/sync_replay_optimizer.py
  python/ray/rllib/policy/policy.py
  python/ray/rllib/policy/rnn_sequencing.py
  python/ray/rllib/policy/tf_policy.py
  python/ray/rllib/tests/test_catalog.py
  python/ray/rllib/tests/test_lstm.py
  python/ray/rllib/tests/test_nested_spaces.py
  python/ray/rllib/tests/test_optimizers.py
Labels: tests ok

#5325 Fix bug in passing large arguments to tasks.
  python/ray/_raylet.pyx
Labels: release/0.7.3

#5327 Lineage cache performance optimization to avoid duplicate GCS requests
  src/ray/raylet/lineage_cache.cc
  src/ray/raylet/lineage_cache.h
Labels: release/0.7.3
