Repository ray-project/ray, pull requests merged in 2019-08, with the labels that each got.

#5336 [rllib] Add rock paper scissors multi-agent example
  doc/source/rllib-api.svg
  doc/source/rllib-concepts.rst
  doc/source/rllib-env.rst
  doc/source/rllib-examples.rst
  doc/source/rllib-training.rst
  doc/source/rllib.rst
  doc/source/rock-paper-scissors.png
  python/ray/rllib/agents/ppo/ppo.py
  python/ray/rllib/examples/rock_paper_scissors_multiagent.py
  python/ray/rllib/models/__init__.py
Labels: tests ok

#5354 `ray stop` sends `SIGKILL` instead of `SIGTERM`
  python/ray/scripts/scripts.py
Labels: release/0.7.3

#5374 Fix the issue of not initializing GLOG
  src/ray/util/logging.cc
Labels: bug

#5392 [rllib] Centralized critic / PPO example on TwoStepGame
  ci/jenkins_tests/run_rllib_tests.sh
  doc/source/rllib-algorithms.rst
  doc/source/rllib-env.rst
  doc/source/rllib-examples.rst
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/impala/vtrace_policy.py
  rllib/evaluation/metrics.py
  rllib/examples/centralized_critic.py
  rllib/examples/centralized_critic_2.py
  rllib/examples/twostep_game.py
  rllib/models/tf/fcnet_v2.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/tf_policy.py
  rllib/policy/tf_policy_template.py
Labels: tests ok

#5421 [rllib] Fix output API when lz4 not installed
  rllib/offline/json_writer.py
  rllib/utils/compression.py
Labels: tests ok

#5304 [rllib] Autoregressive action distributions
  ci/jenkins_tests/run_rllib_tests.sh
  doc/source/rllib-algorithms.rst
  doc/source/rllib-components.svg
  doc/source/rllib-concepts.rst
  doc/source/rllib-env.rst
  doc/source/rllib-models.rst
  doc/source/rllib.rst
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/ars/policies.py
  rllib/agents/dqn/dqn_policy.py
  rllib/agents/dqn/simple_q_policy.py
  rllib/agents/es/policies.py
  rllib/agents/impala/vtrace.py
  rllib/agents/impala/vtrace_policy.py
  rllib/agents/impala/vtrace_test.py
  rllib/agents/marwil/marwil_policy.py
  rllib/agents/pg/torch_pg_policy.py
  rllib/agents/ppo/appo_policy.py
  rllib/agents/ppo/ppo_policy.py
  rllib/examples/autoregressive_action_dist.py
  rllib/examples/centralized_critic.py
  rllib/examples/custom_torch_policy.py
  rllib/keras_policy.py
  rllib/models/action_dist.py
  rllib/models/catalog.py
  rllib/models/tf/tf_action_dist.py
  rllib/models/torch/torch_action_dist.py
  rllib/optimizers/aso_multi_gpu_learner.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
Labels: tests ok

#5430 [rllib] RLlib in 60 seconds documentation
  doc/source/index.rst
  doc/source/multi-flat.svg
  doc/source/rllib-toc.rst
  doc/source/rllib.rst
  rllib/policy/sample_batch.py
Labels: tests ok

#5450 Revert raylet to worker GRPC communication back to asio
  BUILD.bazel
  java/test/src/main/java/org/ray/api/test/BaseTest.java
  java/test/src/main/java/org/ray/api/test/ResourcesManagementTest.java
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/includes/libraylet.pxd
  src/ray/common/grpc_util.h
  src/ray/common/ray_config_def.h
  src/ray/common/task/scheduling_resources.cc
  src/ray/common/task/scheduling_resources.h
  src/ray/common/task/task.h
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/org_ray_runtime_raylet_NativeRayletClient.cc
  src/ray/core_worker/object_interface.h
  src/ray/core_worker/store_provider/local_plasma_provider.h
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/core_worker/task_interface.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/transport/raylet_transport.h
  src/ray/object_manager/object_manager.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/raylet.proto
  src/ray/protobuf/worker.proto
  src/ray/raylet/lib/java/org_ray_runtime_raylet_RayletClientImpl.cc
  src/ray/raylet/lineage_cache_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/raylet.h
  src/ray/raylet/raylet_client.cc
  src/ray/raylet/raylet_client.h
  src/ray/raylet/reconstruction_policy_test.cc
  src/ray/raylet/task_dependency_manager.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/rpc/grpc_server.cc
  src/ray/rpc/grpc_server.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/object_manager/object_manager_client.h
  src/ray/rpc/raylet/raylet_client.cc
  src/ray/rpc/raylet/raylet_server.h
Labels: release-blocker
