Repository ray-project/ray, pull requests merged in 2020-11, with the labels that each got.

#11615 [autoscaler] Flag flip for resource_demand_scheduler should take into account queue
  python/ray/autoscaler/_private/constants.py
  python/ray/monitor.py
  python/ray/tests/test_resource_demand_scheduler.py
  src/ray/common/ray_config_def.h
Labels: @tests-ok

#10776 [cli] Remove the deprecated `old_style` logging calls
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/autoscaler/_private/aws/utils.py
  python/ray/autoscaler/_private/cli_logger.py
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/log_timer.py
  python/ray/autoscaler/_private/updater.py
  python/ray/scripts/scripts.py
  python/ray/tests/aws/test_autoscaler_aws.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_cli_patterns/test_ray_up_record.txt
Labels: @author-action-required

#11758 [autoscaler] Fixing AWS instance types autofill
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/autoscaler/_private/util.py
  python/ray/tests/test_autoscaler_yaml.py
Labels: @author-action-required

#11651 [Dashboard] Memory Page Loading Wheel
  dashboard/client/build/.fakebuild
  dashboard/client/build/static/.fakestatic
  dashboard/client/src/pages/dashboard/memory/Memory.tsx
Labels: @tests-ok, dashboard

#11739 Ray PDB support
  python/ray/_raylet.pyx
  python/ray/experimental/internal_kv.py
  python/ray/scripts/scripts.py
  python/ray/serve/backend_worker.py
  python/ray/tests/BUILD
  python/ray/tests/test_ray_debugger.py
  python/ray/util/__init__.py
  python/ray/util/rpdb.py
Labels: @tests-ok

#11717 [RLlib] Trajectory view API (prep PR for switching on by default across all RLlib; plumbing only)
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/sampler.py
  rllib/models/preprocessors.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_template.py
  rllib/tests/run_regression_tests.py
  rllib/tests/test_io.py
  rllib/tuned_examples/dqn/cartpole-simpleq.yaml
  rllib/utils/tf_ops.py
  rllib/utils/torch_ops.py
  rllib/utils/tracking_dict.py
Labels: @author-action-required

#11793 [Doc] Fix typo in advanced.rst
  doc/source/advanced.rst
Labels: @tests-ok

#11621 [build] Build wheels with manylinux2014
  .bazelrc
  build-docker.sh
  ci/travis/build-docker-images.py
  ci/travis/ci.sh
  ci/travis/install-bazel.sh
  doc/dev/RELEASE_PROCESS.rst
  doc/dev/download_wheels.sh
  doc/examples/newsreader/ray-project/cluster.yaml
  doc/source/development.rst
  doc/source/installation.rst
  python/README-building-wheels.md
  python/build-wheel-manylinux2014.sh
  python/ray/autoscaler/aws/defaults.yaml
  python/ray/autoscaler/aws/example-full.yaml
  python/ray/autoscaler/aws/example-gpu-docker.yaml
  python/ray/autoscaler/aws/example-java.yaml
  python/ray/autoscaler/azure/defaults.yaml
  python/ray/autoscaler/azure/example-full.yaml
  python/ray/autoscaler/azure/example-gpu-docker.yaml
  python/ray/autoscaler/azure/example-gpu.yaml
  python/ray/autoscaler/gcp/defaults.yaml
  python/ray/autoscaler/gcp/example-full.yaml
  python/ray/autoscaler/gcp/example-gpu-docker.yaml
  python/ray/autoscaler/local/example-full.yaml
  python/ray/nightly-wheels.yaml
  python/ray/util/sgd/tf/examples/tf-example-sgd.yaml
  python/ray/util/sgd/torch/examples/example-sgd.yaml
  python/ray/util/sgd/torch/examples/image_models/cluster.yaml
  python/ray/util/sgd/torch/examples/segmentation/example.yaml
  python/ray/util/sgd/torch/examples/sgd-development.yaml
  python/ray/util/sgd/torch/examples/transformers/cluster.yaml
  python/setup.py
  release/long_running_distributed_tests/run.sh
  release/long_running_tests/run.sh
  release/microbenchmark/run.sh
  release/rllib_tests/regression_tests/run.sh
  release/rllib_tests/stress_tests/run.sh
  release/rllib_tests/unit_gpu_tests/run.sh
  release/stress_tests/cluster.yaml
  release/stress_tests/run.sh
Labels: @author-action-required

#11690 [autoscaler] Autoscaler simulator
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/tests/BUILD
  python/ray/tests/test_autoscaling_policy.py
Labels: @tests-ok

#11735 [Core] Fix ray start failure to due to bug of redis address detection
  python/ray/_private/services.py
  python/ray/tests/test_advanced_3.py
Labels: @author-action-required

#11751 [autoscaler] Support legacy cluster configs with the new resource demand scheduler
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/autoscaler/_private/util.py
  python/ray/autoscaler/tags.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_autoscaler_yaml.py
  python/ray/tests/test_cli_patterns/test_ray_attach.txt
  python/ray/tests/test_cli_patterns/test_ray_exec.txt
  python/ray/tests/test_cli_patterns/test_ray_submit.txt
  python/ray/tests/test_cli_patterns/test_ray_up.txt
  python/ray/tests/test_cli_patterns/test_ray_up_config.yaml
  python/ray/tests/test_cli_patterns/test_ray_up_record.txt
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#11771 [SGD] Better support for custom DDP
  doc/source/raysgd/raysgd_pytorch.rst
  python/ray/util/sgd/tests/test_torch.py
  python/ray/util/sgd/torch/distributed_torch_runner.py
  python/ray/util/sgd/torch/examples/image_models/train.py
  python/ray/util/sgd/torch/examples/transformers/transformers_example.py
  python/ray/util/sgd/torch/ptl_operator.py
  python/ray/util/sgd/torch/torch_runner.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/training_operator.py
Labels: @tests-ok

#11769 [Metrics] Implement basic metrics changes
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/redis_context.cc
  src/ray/object_manager/object_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling_queue.cc
  src/ray/raylet/task_dependency_manager.cc
  src/ray/raylet/task_dependency_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/stats/metric_defs.h
  src/ray/stats/metric_exporter_client_test.cc
  src/ray/stats/stats_test.cc
Labels: @author-action-required

#11743 [Serve] add dependency management
  doc/source/serve/advanced.rst
  doc/source/serve/package-ref.rst
  python/ray/serve/__init__.py
  python/ray/serve/api.py
  python/ray/serve/env.py
  python/ray/serve/examples/doc/conda_env.py
  python/ray/serve/tests/test_util.py
  python/ray/serve/utils.py
Labels: @tests-ok

#11817 Fix RAY_ENABLE_NEW_SCHEDULER=1 pytest test_advanced_2.py::test_zero_cpus_actor
  python/ray/tests/BUILD
  python/ray/tests/test_advanced_2.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @author-action-required

#11762 Basic protos for ray client
  BUILD.bazel
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/client_app.py
  python/ray/experimental/client/server.py
  python/ray/experimental/client/worker.py
  python/ray/tests/BUILD
  python/ray/tests/test_experimental_client.py
  src/ray/protobuf/BUILD
  src/ray/protobuf/ray_client.proto
Labels: @author-action-required

#11796 [Object spilling] Queue failed object creation requests until objects have been spilled
  python/ray/tests/test_object_spilling.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/object_manager/common.h
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/plasma/store_runner.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#11805 [serve] Fix long running failure test
  release/long_running_tests/workloads/serve_failure.py
Labels: @tests-ok

#11870 [Dashboard][Bugfix] Fix Error when Actor has no Core Worker
  dashboard/datacenter.py
Labels: bug, dashboard

#11829 [Core] Multi-tenancy: Pass job ID from Raylet to worker via env variable
  src/ray/common/constants.h
  src/ray/common/id.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.h
  streaming/src/test/mock_actor.cc
Labels: @author-action-required

#11844 [core] Add retry for reading session name
  python/ray/node.py
Labels: @tests-ok, P1

#11709 [Serve] Reconfigure backend class at runtime
  doc/source/serve/advanced.rst
  python/ray/serve/api.py
  python/ray/serve/backend_worker.py
  python/ray/serve/config.py
  python/ray/serve/constants.py
  python/ray/serve/controller.py
  python/ray/serve/examples/doc/snippet_reconfigure.py
  python/ray/serve/tests/test_api.py
Labels: @tests-ok

#11838 [serve] Improve DEBUG logging for understanding perf
  python/ray/serve/backend_worker.py
  python/ray/serve/handle.py
  python/ray/serve/http_proxy.py
  python/ray/serve/router.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_backend_worker.py
  python/ray/serve/tests/test_router.py
Labels: @tests-ok

#11820 [autoscaler] Fix semantics of request_resources
  doc/source/cluster/autoscaling.rst
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/autoscaler/sdk.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @author-action-required

#11869 [Core] PushManager for reliable broadcast
  BUILD.bazel
  python/ray/tests/test_object_manager.py
  src/ray/common/ray_config_def.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/test/push_manager_test.cc
  src/ray/raylet/main.cc
Labels: @author-action-required

#11897 [docs] Move all /latest links to /master
  .github/ISSUE_TEMPLATE/bug_report.md
  README.rst
  dashboard/client/src/pages/dashboard/logical-view/ActorDetailsPane.tsx
  dashboard/client/src/pages/dashboard/tune/Tune.tsx
  doc/examples/cython/ray-project/project.yaml
  doc/examples/lbfgs/ray-project/project.yaml
  doc/examples/newsreader/ray-project/project.yaml
  doc/examples/overview.rst
  doc/examples/plot_example-a3c.rst
  doc/examples/plot_hyperparameter.py
  doc/examples/plot_streaming.rst
  doc/site/_posts/2017-05-17-announcing-ray.markdown
  doc/site/_posts/2017-09-30-ray-0.2-release.markdown
  doc/site/_posts/2017-10-15-fast-python-serialization-with-ray-and-arrow.markdown
  doc/site/_posts/2017-11-30-ray-0.3-release.markdown
  doc/site/_posts/2018-03-27-ray-0.4-release.markdown
  doc/site/_posts/2018-07-06-ray-0.5-release.markdown
  doc/site/_posts/2018-07-15-parameter-server-in-fifteen-lines.markdown
  doc/site/get_ray.html
  doc/site/index.html
  doc/source/cluster/cloud.rst
  doc/source/cluster/index.rst
  doc/source/conf.py
  doc/source/debugging.rst
  doc/source/ray-dashboard.rst
  doc/source/rllib-algorithms.rst
  doc/source/rllib-dev.rst
  doc/source/rllib-examples.rst
  doc/source/troubleshooting.rst
  docker/ray/README.md
  python/asv.conf.json
  python/ray/dashboard/client/src/pages/dashboard/logical-view/Actor.tsx
  python/ray/dashboard/client/src/pages/dashboard/tune/Tune.tsx
  python/ray/tune/README.rst
  python/ray/tune/tests/ext_pytorch.py
  python/ray/util/joblib/__init__.py
  python/ray/util/sgd/torch/examples/benchmarks/README.rst
  rllib/README.md
  rllib/agents/pg/README.md
  rllib/agents/sac/README.md
  rllib/agents/sac/sac.py
  rllib/contrib/README.rst
Labels: @tests-ok

#11822 [serve] Rename to use replicas, not workers
  doc/source/serve/advanced.rst
  doc/source/serve/architecture.rst
  doc/source/serve/key-concepts.rst
  doc/source/serve/tutorials/batch.rst
  python/ray/serve/api.py
  python/ray/serve/backend_worker.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/serve/http_proxy.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_backend_worker.py
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/test_router.py
Labels: @tests-ok

#11874 Remove repeat push timeout from object manager
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/tests/test_multinode_failures_2.py
  python/ray/tests/test_object_manager.py
  src/ray/common/ray_config_def.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/push_manager.cc
  src/ray/object_manager/push_manager.h
  src/ray/object_manager/test/push_manager_test.cc
Labels: @author-action-required

#11777 [Autoscaler] simulator placement groups
  python/ray/tests/BUILD
  python/ray/tests/test_autoscaling_policy.py
Labels: @tests-ok

#11599 [GCS]Reduce get operations of worker table
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
Labels: @tests-ok

#11888 [Serialization] Fix buffer alignment issues
  BUILD.bazel
  python/ray/_raylet.pyx
  python/ray/includes/serialization.pxi
  python/ray/tests/test_serialization.py
  src/ray/common/buffer.h
  src/ray/protobuf/serialization.proto
  src/ray/thirdparty/aligned_alloc.c
  src/ray/thirdparty/aligned_alloc.h
Labels: @tests-ok

#11949 Split _get_node_provider_cls off from _get_node_provider
  python/ray/autoscaler/_private/providers.py
Labels: @author-action-required

#11954 [Dashboard][Bug] Fix page broken due to log/err count components
  dashboard/datacenter.py
  dashboard/modules/stats_collector/tests/test_stats_collector.py
Labels: P0, bug, dashboard

#11371 [redis, docs]: Bump redis and docs/Pillow dependencies
  bazel/ray_deps_setup.bzl
  doc/requirements-rtd.txt
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  thirdparty/patches/redis-quiet.patch
Labels: @author-action-required

#11885 [Object Spilling] Introduce SpillWorker & RestoreWorker Pool to avoid IO worker deadlock.
  python/ray/__init__.py
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/ray_constants.py
  python/ray/tests/test_object_spilling.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
  src/ray/core_worker/common.cc
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/common.proto
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/stats/metric_exporter.cc
  src/ray/stats/metric_exporter.h
Labels: @author-action-required

#11894 [Placement Group]Do not really subtract resources, just count
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/test/gcs_node_manager_test.cc
Labels: @tests-ok

#9749 [RLlib] Model Annotations to Torch Models
  rllib/models/catalog.py
  rllib/models/preprocessors.py
  rllib/models/torch/attention_net.py
  rllib/models/torch/fcnet.py
  rllib/models/torch/misc.py
  rllib/models/torch/modules/gru_gate.py
  rllib/models/torch/modules/multi_head_attention.py
  rllib/models/torch/modules/noisy_layer.py
  rllib/models/torch/modules/relative_multi_head_attention.py
  rllib/models/torch/modules/skip_connection.py
  rllib/models/torch/recurrent_net.py
  rllib/models/torch/torch_action_dist.py
  rllib/models/torch/visionnet.py
Labels: @author-action-required

#11747 [RLlib] Trajectory view API: Enable by default for PPO, IMPALA, PG, A3C (tf and torch).
  rllib/agents/a3c/a3c.py
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/dqn/tests/test_simple_q.py
  rllib/agents/impala/impala.py
  rllib/agents/impala/vtrace_torch_policy.py
  rllib/agents/maml/maml_tf_policy.py
  rllib/agents/maml/maml_torch_policy.py
  rllib/agents/pg/pg.py
  rllib/agents/pg/pg_torch_policy.py
  rllib/agents/pg/tests/test_pg.py
  rllib/agents/ppo/appo.py
  rllib/agents/ppo/ddppo.py
  rllib/agents/ppo/ppo.py
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/sac/tests/test_sac.py
  rllib/agents/trainer.py
  rllib/examples/models/rnn_model.py
  rllib/examples/policy/rock_paper_scissors_dummies.py
  rllib/execution/multi_gpu_learner.py
  rllib/execution/train_ops.py
  rllib/models/modelv2.py
  rllib/models/tf/recurrent_net.py
  rllib/models/torch/recurrent_net.py
  rllib/models/torch/torch_action_dist.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_template.py
  rllib/tests/test_io.py
  rllib/tests/test_multi_agent_env.py
  rllib/tests/test_nested_observation_spaces.py
  rllib/utils/exploration/tests/test_curiosity.py
  rllib/utils/tf_ops.py
  rllib/utils/tracking_dict.py
Labels: @author-action-required

#11407 [docker] Support non-root container
  docker/base-deps/Dockerfile
  docker/ray-deps/Dockerfile
  docker/ray-ml/Dockerfile
  docker/ray/Dockerfile
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/_private/constants.py
  python/ray/autoscaler/_private/docker.py
  python/ray/autoscaler/_private/staroid/command_runner.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#11948 [tune] Fix unflatten dict
  python/ray/tune/utils/util.py
  python/ray/tune/utils/util_test.py
Labels: @tests-ok

#11929 [autoscaler/k8s] Preliminary k8s operator
  ci/travis/format.sh
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/util.py
  python/ray/autoscaler/kubernetes/operator_configs/operator_config.yaml
  python/ray/autoscaler/kubernetes/operator_configs/test_cluster_config.yaml
  python/ray/autoscaler/sdk.py
  python/ray/monitor.py
  python/ray/operator.py
  python/ray/tests/test_autoscaler_yaml.py
  python/setup.py
Labels: @tests-ok

#11896 [autoscaler] Fix custom node resources on head
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/commands.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_cli_patterns/test_ray_up_record.txt
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#11832 MBMPO Cartpole
  doc/source/rllib-algorithms.rst
  rllib/agents/mbmpo/model_ensemble.py
  rllib/agents/mbmpo/tests/test_mbmpo.py
  rllib/env/model_vector_env.py
  rllib/examples/env/mbmpo_env.py
  rllib/tuned_examples/mbmpo/cartpole-mbmpo.yaml
Labels: @author-action-required

#11922 [ray_client]: Implement function calls
  BUILD.bazel
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/api.py
  python/ray/experimental/client/client_app.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/core_ray_api.py
  python/ray/experimental/client/server.py
  python/ray/experimental/client/util.py
  python/ray/experimental/client/worker.py
  python/ray/tests/test_experimental_client.py
Labels: @author-action-required

#11337 [RLLib] MAML extension for all models except RNNs
  rllib/BUILD
  rllib/agents/maml/maml_torch_policy.py
  rllib/agents/maml/tests/test_maml.py
  rllib/tuned_examples/maml/cartpole-maml.yaml
Labels: @author-action-required

#11953 [docker] auto-populate shared memory size
  doc/source/installation.rst
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/_private/constants.py
  python/ray/autoscaler/ray-schema.json
  python/ray/ray_constants.py
  python/ray/resource_spec.py
  python/ray/tests/test_autoscaler.py
Labels: @tests-ok

#11827 [RLlib] Trajectory view API: enable by default for SAC, DDPG, DQN, SimpleQ
  rllib/agents/ddpg/ddpg.py
  rllib/agents/dqn/dqn.py
  rllib/agents/dqn/simple_q.py
  rllib/agents/sac/sac.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/policy/dynamic_tf_policy.py
  rllib/tests/run_regression_tests.py
  rllib/tests/test_multi_agent_env.py
  rllib/tuned_examples/dqn/cartpole-dqn.yaml
Labels: @author-action-required

#12038 Fix dashboard agent use incorrect ip
  dashboard/agent.py
  python/ray/_private/services.py
Labels: bug

#11968 [GCS]Open light heartbeat by default
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @tests-ok

#12051 Pin aiohttp to the 3.7.x version
  python/requirements.txt
Labels: @tests-ok

#12054 Lazily initialize the global state accessor in Python workers
  python/ray/state.py
Labels: @author-action-required

#12065 [PlacementGroup]Skip flaky testcase
  python/ray/tests/test_placement_group.py
Labels: @author-action-required

#12076 [C++ API] tests for the C++ API.
  cpp/src/ray/test/cluster/cluster_mode_test.cc
Labels: @tests-ok

#12061 [PlacementGroup]Add gcs placement group manager debug info
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
Labels: @tests-ok

#11989 [CLI] Fix ray commands when RAY_ADDRESS used
  python/ray/_private/services.py
Labels: @tests-ok

#12016 Extract the connection logic to reduce duplication.
  src/ray/gcs/redis_context.cc
Labels: @author-action-required

#12064 [tune] cache checkpoint serialization
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/automl/search_policy.py
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/tests/test_experiment_analysis_mem.py
  python/ray/tune/trial.py
  python/ray/tune/trial_executor.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
  python/ray/tune/utils/serialization.py
Labels: @tests-ok, tune

#12072 [ray client] ray wait() implementation
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/api.py
  python/ray/experimental/client/client_app.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/core_ray_api.py
  python/ray/experimental/client/server.py
  python/ray/experimental/client/worker.py
  python/ray/tests/test_experimental_client.py
  src/ray/protobuf/ray_client.proto
Labels: @tests-ok

#12050 [New Scheduler] Don't start tasks if the owner is dead
  python/ray/tests/test_actor_advanced.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/test/util.h
Labels: @tests-ok

#11923 [core] Add Recursive task cancelation
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_cancel.py
  python/ray/worker.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/protobuf/core_worker.proto
Labels: @tests-ok

#12089 [ray_client] __getattr__ for the API Import interface
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/client_app.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/server/server.py
  python/ray/experimental/client/util.py
  python/ray/tests/test_experimental_client.py
Labels: @author-action-required

#12063 [RLlib] Fix inconsistency wrt batch size in SampleCollector (traj. view API). Makes DD-PPO work with traj. view API.
  rllib/BUILD
  rllib/agents/callbacks.py
  rllib/agents/dqn/tests/test_simple_q.py
  rllib/agents/ppo/appo.py
  rllib/agents/ppo/ddppo.py
  rllib/evaluation/collectors/sample_collector.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/episode.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/custom_eval.py
  rllib/utils/test_utils.py
  rllib/utils/typing.py
Labels: @author-action-required

#12129 [Dashboard] New dashboard view data doesn't exist.
  dashboard/datacenter.py
Labels: @author-action-required

#12095 [rllib] Rrk/12079 custom filters
  rllib/BUILD
  rllib/examples/custom_observation_filters.py
  rllib/utils/filter.py
Labels: @author-action-required

#12096 Enable even more new scheduler tests
  python/ray/scripts/scripts.py
  python/ray/tests/BUILD
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_global_gc.py
  python/ray/tests/test_global_state.py
  python/ray/tests/test_multi_node.py
  python/ray/tests/test_multi_node_2.py
  python/ray/tests/test_multi_tenancy.py
  python/ray/tests/test_reconstruction.py
  python/ray/tests/test_reference_counting.py
Labels: @author-action-required

#12189 [CI] Use Docker image for microbenchmarks
  release/microbenchmark/cluster.yaml
  release/microbenchmark/run.sh
Labels: @tests-ok

#12175 [Serve] Deflake test_router
  python/ray/serve/tests/test_router.py
Labels: @author-action-required

#12158 [RLlib] Bug fix in off-policy estimators (returning log probs instead of probs).
  rllib/offline/off_policy_estimator.py
Labels: @tests-ok

#12177 Support ray.* in remote functions for Ray client
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/api.py
  python/ray/experimental/client/client_app.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/worker.py
  python/ray/tests/test_experimental_client.py
Labels: @author-action-required

#12156 [tune] Add test for infinite trials
  python/ray/tune/tests/test_api.py
Labels: tune

#12234 [Metrics] Skip prom file test on Windows.
  python/ray/tests/test_metrics_agent.py
Labels: @author-action-required

#12001 [Java] support java actor class inheritance
  java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java
  java/runtime/src/test/java/io/ray/runtime/functionmanager/FunctionManagerTest.java
  java/test/src/main/java/io/ray/test/ActorTest.java
Labels: java

#12218 [Core] Force get actor has val
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  python/ray/tests/test_actor_advanced.py
  python/ray/worker.py
Labels: @tests-ok

#12211 [Serve] Remove old report-queue-code
  python/ray/serve/controller.py
Labels: @tests-ok

#12268 Remove deprecated f._submit API
  doc/source/troubleshooting.rst
  python/ray/remote_function.py
  python/ray/tests/test_node_manager.py
Labels: @author-action-required

#12267 Remove unused print_failed_task
  python/ray/worker.py
Labels: @author-action-required

#12270 Remove unused _post_get_hooks
  python/ray/tests/test_advanced_3.py
  python/ray/worker.py
Labels: @author-action-required

#12159 [tune] use default anonymous metric `_metric` if at least a mode is set
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/function_runner.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/result.py
  python/ray/tune/schedulers/async_hyperband.py
  python/ray/tune/schedulers/hyperband.py
  python/ray/tune/schedulers/median_stopping_rule.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/schedulers/trial_scheduler.py
  python/ray/tune/suggest/ax.py
  python/ray/tune/suggest/bayesopt.py
  python/ray/tune/suggest/bohb.py
  python/ray/tune/suggest/dragonfly.py
  python/ray/tune/suggest/hyperopt.py
  python/ray/tune/suggest/nevergrad.py
  python/ray/tune/suggest/optuna.py
  python/ray/tune/suggest/skopt.py
  python/ray/tune/suggest/zoopt.py
  python/ray/tune/tests/test_function_api.py
  python/ray/tune/tests/test_searchers.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/trial_runner.py
Labels: tune

#12022 [minor] Refactor to expose RedisContext::PingPort
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
Labels: @tests-ok

#11890 [GCS] refactor gcs initialization
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_init_data.cc
  src/ray/gcs/gcs_server/gcs_init_data.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_object_manager.cc
  src/ray/gcs/gcs_server/gcs_object_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
Labels: @author-action-required

#12283 [autoscaler/k8s] Handle unavailable k8s API
  python/ray/autoscaler/_private/autoscaler.py
Labels: @tests-ok

#12359 Don't allow 'optional' files in setup.py
  python/setup.py
Labels: @author-action-required

#12097 [GCS]Fill resource fields when re-report heartbeat after gcs restarted
  python/ray/scripts/scripts.py
  python/ray/tests/test_placement_group.py
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: @author-action-required

#12141 [ray_client] Support calling functions from other functions and correct the tests
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/server/__init__.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/server/server.py
  python/ray/tests/test_experimental_client.py
Labels: @author-action-required

#12087 [Object Spilling] Fusion small objects
  python/ray/_raylet.pyx
  python/ray/external_storage.py
  python/ray/includes/libcoreworker.pxd
  python/ray/includes/object_ref.pxi
  python/ray/includes/unique_ids.pxd
  python/ray/includes/unique_ids.pxi
  python/ray/ray_constants.py
  python/ray/tests/test_object_spilling.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/object_manager/common.h
  src/ray/object_manager/plasma/store.cc
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#12358 [Bugfix][Dashboard] Make sure not to iterate over "None" when worker payload not present
  dashboard/datacenter.py
Labels: @tests-ok, bug, dashboard

#12409 [ray client] add metadata and secure options to Worker.
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/worker.py
Labels: @tests-ok

#12396 [RLlib] Torch LR schedule not working. Fix and added test case.
  rllib/agents/ppo/tests/test_ppo.py
  rllib/policy/torch_policy.py
Labels: @author-action-required

#12400 [RLlib] Move pettingzoo into rllib's requirements file (from ray's requirements.txt file).
  python/requirements.txt
  python/requirements_rllib.txt
Labels: @tests-ok

#12344 [Core] zero-copy serializer for pytorch
  python/ray/serialization.py
  python/ray/serialization_addons.py
  python/ray/tests/test_serialization.py
Labels: @tests-ok

#12447 [RLlib] Attention Net prep PR #1: Smaller cleanups.
  rllib/agents/ddpg/ddpg_torch_policy.py
  rllib/agents/dqn/dqn_torch_policy.py
  rllib/agents/marwil/marwil_torch_policy.py
  rllib/agents/ppo/appo_torch_policy.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/ppo/tests/test_appo.py
  rllib/agents/sac/sac_torch_policy.py
  rllib/contrib/maddpg/maddpg_policy.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/policy/episode_env_aware_policy.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/policy/torch_policy.py
  rllib/utils/exploration/exploration.py
  rllib/utils/sgd.py
  rllib/utils/tf_ops.py
Labels: @author-action-required, @tests-ok

#12462 [RLLib] Fix HyperOptSearch tuple to list conversion
  rllib/agents/trainer.py
Labels: @tests-ok

#11945 [RLlib] Curiosity exploration module: tf/tf2.x/tf-eager support.
  rllib/agents/ddpg/ddpg_tf_policy.py
  rllib/execution/multi_gpu_impl.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy_template.py
  rllib/utils/exploration/curiosity.py
  rllib/utils/exploration/exploration.py
  rllib/utils/exploration/tests/test_curiosity.py
  rllib/utils/framework.py
  rllib/utils/tf_ops.py
Labels: @author-action-required

#12471 Actor resource backlog hotfix
  python/ray/tests/test_actor_advanced.py
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
Labels: @author-action-required, @tests-ok

#12484 Allow more fields for object metadata
  java/runtime/src/main/java/io/ray/runtime/object/ObjectSerializer.java
  java/runtime/src/main/java/io/ray/runtime/task/ArgumentsBuilder.java
  python/ray/_raylet.pyx
  python/ray/ray_constants.py
  python/ray/serialization.py
Labels: @author-action-required

#12239 [Core] Remove actor arg from executor to allow users to specify actor…
  python/ray/function_manager.py
Labels: @author-action-required

#12225 [Logging] Fix tensorflow logging issue.
  python/ray/ray_logging.py
  python/ray/workers/default_worker.py
Labels: @author-action-required

#12209 [RLlib] PyBullet Env native support via env str-specifier (if installed).
  ci/travis/install-dependencies.sh
  python/requirements_rllib.txt
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/tuned_examples/sac/cartpole-continuous-pybullet-sac.yaml
Labels: @tests-ok

#12478 Re-Revert "[Core] zero-copy serializer for pytorch (#12344)"
  doc/source/serialization.rst
  python/ray/serialization.py
  python/ray/serialization_addons.py
  python/ray/tests/test_serialization.py
  rllib/tests/test_dependency_torch.py
Labels: @tests-ok
