Repository ray-project/ray, pull requests merged in 2020-09, with the labels that each got.

#10452 Add documentation for Dask-on-Ray
  doc/source/dask-on-ray.rst
  doc/source/index.rst
  doc/source/memory-management.rst
  doc/source/ray-overview/basics.rst
  doc/source/starting-ray.rst
Labels: @author-action-required

#10455 [1.0] Ray whitepaper link and tagline update
  README.rst
  doc/site/_config.yml
  doc/site/index.html
  doc/source/cluster/autoscaling.rst
  doc/source/cluster/launcher.rst
  doc/source/index.rst
  doc/source/ray-overview/basics.rst
  doc/source/ray-overview/involvement.rst
  doc/source/rllib-training.rst
  doc/source/serve/deployment.rst
  doc/source/whitepaper.rst
  java/pom.xml
Labels: @author-action-required

#10368 [docker] Use tmp paths for rsync and fix file_mounts on docker
  python/ray/autoscaler/command_runner.py
  python/ray/autoscaler/commands.py
  python/ray/autoscaler/docker.py
  python/ray/autoscaler/updater.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_command_runner.py
  src/ray/core_worker/lib/java/jni_utils.h
Labels: @tests-ok

#10450 [Autoscaler] Reload config
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/node_launcher.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#10483 [Serve] Refactor RequestMetadata and Query objects
  python/ray/serve/backend_worker.py
  python/ray/serve/endpoint_policy.py
  python/ray/serve/examples/echo.py
  python/ray/serve/handle.py
  python/ray/serve/http_proxy.py
  python/ray/serve/request_params.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_router.py
  python/ray/serve/utils.py
  python/requirements.txt
  python/setup.py
Labels: @tests-ok

#9645 [gcp] Update config.py for safe dir creation
  python/ray/autoscaler/gcp/config.py
Labels: @author-action-required

#10420 [RLlib] PPO, APPO, and DD-PPO code cleanup.
  rllib/agents/impala/vtrace_tf.py
  rllib/agents/maml/maml_tf_policy.py
  rllib/agents/pg/pg_tf_policy.py
  rllib/agents/ppo/README.md
  rllib/agents/ppo/appo.py
  rllib/agents/ppo/appo_tf_policy.py
  rllib/agents/ppo/appo_torch_policy.py
  rllib/agents/ppo/ddppo.py
  rllib/agents/ppo/ppo.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/ppo/tests/test_appo.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/trainer_template.py
  rllib/examples/centralized_critic.py
  rllib/execution/metric_ops.py
  rllib/models/tests/test_distributions.py
  rllib/policy/tf_policy_template.py
  rllib/tests/test_io.py
  rllib/tests/test_rollout.py
  rllib/tests/test_supported_spaces.py
Labels: @author-action-required

#10482 Atomic Placement Group Part 1, Basic Structure.
  .travis.yml
  python/ray/tests/test_placement_group.py
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: @author-action-required

#10504 [docker] Support multiple node types
  doc/source/cluster/autoscaling.rst
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/command_runner.py
  python/ray/autoscaler/ray-schema.json
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#10525 [Streaming] Remove is_direct_call param
  streaming/python/tests/test_direct_transfer.py
Labels: streaming

#10477 [RLlib] Issue 10469: Callbacks should receive env idx ...
  rllib/agents/callbacks.py
  rllib/evaluation/sampler.py
  rllib/evaluation/worker_set.py
  rllib/examples/custom_metrics_and_callbacks.py
  rllib/utils/exploration/curiosity.py
  src/ray/core_worker/lib/java/jni_utils.h
Labels: @author-action-required

#10444 [tune] refactor tune search space
  doc/source/conf.py
  doc/source/tune/api_docs/grid_random.rst
  python/ray/tune/__init__.py
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/examples/ax_example.py
  python/ray/tune/examples/logging_example.py
  python/ray/tune/examples/mnist_pytorch.py
  python/ray/tune/examples/mnist_pytorch_trainable.py
  python/ray/tune/examples/pbt_convnet_example.py
  python/ray/tune/examples/pbt_convnet_function_example.py
  python/ray/tune/examples/pbt_transformers/pbt_transformers.py
  python/ray/tune/experiment.py
  python/ray/tune/sample.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/suggest/ax.py
  python/ray/tune/suggest/bayesopt.py
  python/ray/tune/suggest/hyperopt.py
  python/ray/tune/suggest/nevergrad.py
  python/ray/tune/suggest/optuna.py
  python/ray/tune/suggest/search.py
  python/ray/tune/suggest/search_generator.py
  python/ray/tune/suggest/suggestion.py
  python/ray/tune/suggest/variant_generator.py
  python/ray/tune/tests/example.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_experiment_analysis_mem.py
  python/ray/tune/tests/test_sample.py
  python/ray/tune/tests/test_var.py
  python/ray/tune/tune.py
  python/ray/tune/utils/util.py
  python/ray/util/sgd/tf/examples/tensorflow_train_example.py
Labels: @tests-ok

#10468 Add documentation for Mars on Ray
  doc/source/index.rst
  doc/source/mars-on-ray.rst
Labels: @author-action-required

#10512 Remove unnecessary output when connecting to a cluster.
  python/ray/worker.py
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_gcs_client.cc
  src/ray/gcs/redis_client.cc
  src/ray/gcs/redis_gcs_client.cc
Labels: @author-action-required

#10449 [Core] Added support for submission-time task names.
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/task/invocation_spec.h
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/worker/default_worker.cc
  doc/source/advanced.rst
  doc/source/images/task_name_dashboard.png
  java/api/src/main/java/io/ray/api/call/BaseTaskCaller.java
  java/api/src/main/java/io/ray/api/options/CallOptions.java
  java/test/src/main/java/io/ray/test/TaskNameTest.java
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/test_actor.py
  python/ray/tests/test_advanced_3.py
  src/ray/common/function_descriptor.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/lib/java/jni_init.cc
  src/ray/core_worker/lib/java/jni_utils.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/task_dependency_manager_test.cc
  streaming/src/queue/transport.cc
  streaming/src/test/mock_actor.cc
  streaming/src/test/queue_tests_base.h
Labels: @author-action-required

#10534 [docfix] Explain all errors from ray.cancel
  python/ray/worker.py
Labels: @tests-ok

#10304 [tune] horovod trainable
  .travis.yml
  ci/travis/install-dependencies.sh
  doc/source/conf.py
  doc/source/tune/api_docs/integration.rst
  doc/source/tune/examples/horovod_simple.rst
  doc/source/tune/examples/index.rst
  python/ray/tune/BUILD
  python/ray/tune/examples/horovod_simple.py
  python/ray/tune/integration/horovod.py
  python/ray/tune/integration/pytorch_lightning.py
  python/ray/tune/tests/test_horovod.py
Labels: @tests-ok

#10389 [Serve] Reimplement BackendConfig as pydantic model
  doc/requirements-doc.txt
  doc/source/serve/package-ref.rst
  python/ray/serve/__init__.py
  python/ray/serve/api.py
  python/ray/serve/backend_worker.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_backend_worker.py
  python/ray/serve/tests/test_config.py
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/test_router.py
  python/requirements.txt
  python/setup.py
Labels: @tests-ok

#10535 [Serve] Add Latency and Queue Size Metrics
  python/ray/serve/backend_worker.py
  python/ray/serve/constants.py
  python/ray/serve/router.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_api.py
Labels: @tests-ok

#9722 Multi-agent Algorithm Documentation Updates
  doc/source/rllib-algorithms.rst
  rllib/examples/multi_agent_independent_learning.py
  rllib/examples/multi_agent_parameter_sharing.py
Labels: @author-action-required

#10557 [Placement group] Fix node id print issue.
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
Labels: @author-action-required

#10500 [Core] Multi-tenancy: Worker capping
  python/ray/tests/BUILD
  python/ray/tests/test_multi_tenancy.py
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#10581 [Doc] Add a section for synchronization primitives in Ray
  doc/source/advanced.rst
  doc/source/package-ref.rst
Labels: @author-action-required

#10589 [RLlib] Fix seeding issue
  rllib/evaluation/rollout_worker.py
  rllib/tests/test_rollout_worker.py
Labels: @author-action-required

#10551 [ray 1.0] Make private a few more things
  doc/source/fault-tolerance.rst
  doc/source/package-ref.rst
  python/ray/worker.py
Labels: @author-action-required

#10559 [Serve] Parametrize tests for pydantic backend
  python/ray/serve/tests/test_api.py
Labels: @tests-ok

#10576 [tune] extend search space api docs
  doc/source/tune/api_docs/overview.rst
  doc/source/tune/api_docs/search_space.rst
  doc/source/tune/api_docs/suggestion.rst
  doc/source/tune/key-concepts.rst
  doc/source/tune/user-guide.rst
  python/ray/tune/examples/ax_example.py
  python/ray/tune/examples/bayesopt_example.py
  python/ray/tune/examples/hyperopt_example.py
  python/ray/tune/examples/optuna_example.py
  python/ray/tune/suggest/ax.py
  python/ray/tune/suggest/bayesopt.py
  python/ray/tune/suggest/hyperopt.py
  python/ray/tune/suggest/optuna.py
Labels: P0

#10554 [1.0] move placement groups from experimental to util. Note they are still undocumented.
  python/ray/actor.py
  python/ray/experimental/__init__.py
  python/ray/remote_function.py
  python/ray/tests/test_placement_group.py
  python/ray/util/__init__.py
  python/ray/util/placement_group.py
Labels: @author-action-required

#10062 Java doc: "Starting Ray" page
  doc/source/starting-ray.rst
  doc/source/walkthrough.rst
  java/api/src/main/java/io/ray/api/Ray.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
Labels: java

#10438 Java doc: "Using Actors" page
  doc/source/actors.rst
  doc/source/walkthrough.rst
  java/test/src/main/java/io/ray/docdemo/UsingActorsDemo.java
Labels: java

#10456 [tune] implement shim instantiation
  doc/source/tune/api_docs/schedulers.rst
  doc/source/tune/api_docs/suggestion.rst
  python/ray/tune/__init__.py
  python/ray/tune/schedulers/__init__.py
  python/ray/tune/suggest/__init__.py
  python/ray/tune/tests/test_api.py
Labels: P1

#10579 [core] Disable GCS reconnect
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_multi_node.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
Labels: @author-action-required

#10567 [RLlib] SAC n_step > 1.
  rllib/agents/dqn/dqn_tf_policy.py
  rllib/agents/sac/sac_tf_policy.py
  rllib/agents/sac/sac_torch_policy.py
  rllib/models/tests/test_distributions.py
  rllib/tuned_examples/sac/pendulum-sac.yaml
Labels: @author-action-required, @tests-ok

#10518 [tune] API revamp fix
  doc/source/tune/_tutorials/tune-distributed.rst
  doc/source/tune/api_docs/client.rst
  doc/source/tune/api_docs/execution.rst
  doc/source/tune/user-guide.rst
  python/ray/tune/__init__.py
  python/ray/tune/cluster_info.py
  python/ray/tune/examples/durable_trainable_example.py
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/_test_cluster_interrupt_searcher.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_experiment_analysis_mem.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tests/test_sync.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_tune_server.py
  python/ray/tune/trial_executor.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
  python/ray/tune/utils/__init__.py
  python/ray/tune/utils/util.py
  rllib/examples/custom_metrics_and_callbacks.py
  rllib/examples/custom_metrics_and_callbacks_legacy.py
  rllib/train.py
Labels: P0

#10203 [cli] Support non-interactive logging
  python/ray/autoscaler/aws/utils.py
  python/ray/autoscaler/cli_logger.py
  python/ray/autoscaler/command_runner.py
  python/ray/autoscaler/commands.py
  python/ray/autoscaler/subprocess_output_util.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_cli_patterns/test_ray_up.txt
  python/ray/tests/test_cli_patterns/test_ray_up_record.txt
  python/ray/tests/test_output.py
Labels: P0

#10464 [Autoscaler] Demand autoscaler take into account utilized resources
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/load_metrics.py
  python/ray/autoscaler/resource_demand_scheduler.py
  python/ray/tests/test_multi_node_2.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#10563 [Core] Fix override memory and object_store_memory in decorator
  python/ray/tests/test_basic.py
  python/ray/utils.py
  rllib/evaluation/worker_set.py
Labels: @tests-ok

#10561 [Core] Accelerator type API
  doc/source/advanced.rst
  python/ray/actor.py
  python/ray/cross_language.py
  python/ray/ray_constants.py
  python/ray/remote_function.py
  python/ray/tests/test_advanced_3.py
  python/ray/util/accelerators/__init__.py
  python/ray/util/accelerators/accelerators.py
  python/ray/utils.py
  python/ray/worker.py
Labels: @tests-ok

#10297 [k8s] Broken Command Interactivity
  python/ray/autoscaler/command_runner.py
  python/ray/tests/test_command_runner.py
Labels: @tests-ok, P0, triage

#10621 [tune] Add algorithms for search space conversion
  doc/source/conf.py
  doc/source/tune/api_docs/suggestion.rst
  python/ray/tune/examples/bohb_example.py
  python/ray/tune/examples/dragonfly_example.py
  python/ray/tune/examples/nevergrad_example.py
  python/ray/tune/examples/skopt_example.py
  python/ray/tune/examples/zoopt_example.py
  python/ray/tune/sample.py
  python/ray/tune/suggest/bohb.py
  python/ray/tune/suggest/dragonfly.py
  python/ray/tune/suggest/nevergrad.py
  python/ray/tune/suggest/skopt.py
  python/ray/tune/suggest/zoopt.py
  python/ray/tune/tests/test_sample.py
Labels: @tests-ok

#10593 [Java] Disable the multi-worker feature by default
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/resources/ray.default.conf
  java/test.sh
  java/test/src/main/java/io/ray/test/ClassLoaderTest.java
  java/test/src/main/java/io/ray/test/ExitActorTest.java
  java/test/src/main/java/io/ray/test/FailureTest.java
  java/test/src/main/java/io/ray/test/JobConfigTest.java
  java/test/src/main/java/io/ray/test/KillActorTest.java
  java/test/src/main/java/io/ray/test/MultiThreadingTest.java
  java/test/src/main/java/io/ray/test/TestUtils.java
  python/ray/job_config.py
  src/ray/common/ray_config_def.h
Labels: java

#10365 [tune] More robust resolution/detection of signature
  python/ray/tune/experiment.py
  python/ray/tune/function_runner.py
  python/ray/tune/integration/torch.py
  python/ray/tune/tests/test_experiment.py
  python/ray/tune/utils/__init__.py
  python/ray/tune/utils/util.py
  python/setup.py
Labels: P1

#10624 Promote ray.experimental.queue to ray.util
  doc/source/advanced.rst
  doc/source/package-ref.rst
  python/ray/experimental/queue.py
  python/ray/tests/BUILD
  python/ray/tests/test_queue.py
  python/ray/util/queue.py
Labels: @author-action-required, @tests-ok

#10519 [dask-on-ray] Add Dask-Ray scheduler callbacks.
  doc/source/dask-on-ray.rst
  python/ray/tests/BUILD
  python/ray/tests/test_dask_callback.py
  python/ray/util/dask/__init__.py
  python/ray/util/dask/callbacks.py
  python/ray/util/dask/scheduler.py
Labels: @author-action-required

#10599 [Placement Group] Atomic Creation using 2 phase protocol part 2.
  python/ray/tests/test_placement_group.py
  src/ray/common/task/scheduling_resources.cc
  src/ray/common/task/scheduling_resources.h
  src/ray/common/task/scheduling_resources_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: @author-action-required

#10321 [RaySGD] Simplify Builder Process
  doc/source/raysgd/raysgd.rst
  doc/source/raysgd/raysgd_pytorch.rst
  python/ray/util/sgd/tests/test_torch.py
  python/ray/util/sgd/tests/test_torch_runner.py
  python/ray/util/sgd/torch/__init__.py
  python/ray/util/sgd/torch/distributed_torch_runner.py
  python/ray/util/sgd/torch/examples/benchmarks/benchmark.py
  python/ray/util/sgd/torch/examples/cifar_pytorch_example.py
  python/ray/util/sgd/torch/examples/cifar_pytorch_pbt.py
  python/ray/util/sgd/torch/examples/dcgan.py
  python/ray/util/sgd/torch/examples/image_models/train.py
  python/ray/util/sgd/torch/examples/raysgd_torch_signatures.py
  python/ray/util/sgd/torch/examples/segmentation/train_segmentation.py
  python/ray/util/sgd/torch/examples/train_example.py
  python/ray/util/sgd/torch/examples/transformers/transformers_example.py
  python/ray/util/sgd/torch/examples/transformers/utils.py
  python/ray/util/sgd/torch/examples/tune_example.py
  python/ray/util/sgd/torch/torch_runner.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/training_operator.py
Labels: P0

#10642 [tune] Added `timeout` parameter to `tune.run()`,
  python/ray/tune/experiment.py
  python/ray/tune/stopper.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tune.py
Labels: @tests-ok

#10632 [Core] Make test_warning_for_too_many_nested_tasks less flaky
  python/ray/tests/test_failure.py
Labels: @tests-ok

#10379 [Doc] Use sphinx_book_theme
  doc/requirements-doc.txt
  doc/requirements-rtd.txt
  doc/source/_static/css/custom.css
  doc/source/_static/favicon.ico
  doc/source/conf.py
  doc/source/ray-overview/basics.rst
  doc/source/rllib-algorithms.rst
  doc/source/rllib-toc.rst
  doc/source/rllib.rst
Labels: @tests-ok

#10656 Revert "[Streaming] fix streaming ci (#9675)"
  BUILD.bazel
  src/ray/common/id.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_util.h
  src/ray/core_worker/transport/dependency_resolver.cc
  src/ray/ray_exported_symbols.lds
  src/ray/ray_version_script.lds
  src/ray/streaming/streaming.cc
  src/ray/streaming/streaming.h
  streaming/BUILD.bazel
  streaming/java/streaming-runtime/src/main/java/io/ray/streaming/runtime/util/EnvUtil.java
  streaming/java/streaming-runtime/src/main/java/io/ray/streaming/runtime/util/ResourceUtil.java
  streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/demo/HybridStreamTest.java
  streaming/python/tests/test_hybrid_stream.py
  streaming/src/queue/transport.cc
  streaming/src/queue/transport.h
Labels: release-blocker

#10625 [Core] Logging improvements
  python/ray/node.py
  python/ray/services.py
  src/ray/core_worker/task_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
Labels: @author-action-required

#10594 Remove the '--include-java' option
  java/test.sh
  java/test/src/main/java/io/ray/test/BaseMultiLanguageTest.java
  python/ray/node.py
  python/ray/parameter.py
  python/ray/scripts/scripts.py
  python/ray/services.py
  python/ray/tests/test_cross_language.py
  python/ray/worker.py
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool_test.cc
  streaming/java/streaming-api/src/main/java/io/ray/streaming/api/context/ClusterStarter.java
  streaming/python/examples/wordcount.py
  streaming/python/tests/test_failover.py
  streaming/python/tests/test_hybrid_stream.py
  streaming/python/tests/test_stream.py
  streaming/python/tests/test_union_stream.py
  streaming/python/tests/test_word_count.py
Labels: java

#10672 [hotfix] redis_password -> _redis_password
  python/ray/scripts/scripts.py
Labels: @tests-ok

#10662 [tune] All examples to use ConcurrencyLimiter
  python/ray/tune/examples/bayesopt_example.py
  python/ray/tune/examples/dragonfly_example.py
  python/ray/tune/examples/hyperband_example.py
  python/ray/tune/examples/hyperopt_example.py
  python/ray/tune/examples/lightgbm_example.py
  python/ray/tune/examples/mlflow_example.py
  python/ray/tune/examples/mnist_pytorch.py
  python/ray/tune/examples/nevergrad_example.py
  python/ray/tune/examples/optuna_example.py
  python/ray/tune/examples/skopt_example.py
  python/ray/tune/examples/tune_cifar10_gluon.py
  python/ray/tune/schedulers/async_hyperband.py
  python/ray/tune/suggest/repeater.py
  python/ray/tune/suggest/suggestion.py
Labels: P0

#10453 [Dashboard] Logical View Actor Class Grouping Details
  python/ray/dashboard/client/package-lock.json
  python/ray/dashboard/client/package.json
  python/ray/dashboard/client/src/api.ts
  python/ray/dashboard/client/src/common/LabeledDatum.tsx
  python/ray/dashboard/client/src/common/util.ts
  python/ray/dashboard/client/src/pages/dashboard/logical-view/Actor.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/ActorClassGroup.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/ActorClassGroups.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/ActorDetailsPane.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/ActorStateRepr.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/Actors.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/LogicalView.tsx
  python/ray/dashboard/dashboard.py
  python/ray/dashboard/node_stats.py
  python/ray/tests/test_metrics.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
Labels: dashboard, enhancement, release-blocker

#10703 [autoscaler] Create provider exactly once
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/commands.py
Labels: P0, release-blocker

#10684 [Dashboard] Refresh documentation 1.0.0
  doc/source/ray-dashboard.rst
Labels: dashboard

#10682 Run Serve Tests on Windows
  ci/travis/ci.sh
  python/ray/serve/examples/doc/tutorial_sklearn.py
  python/ray/serve/examples/doc/tutorial_tensorflow.py
Labels: @tests-ok

#10705 [Autoscaler] Cluster sync expand user
  python/ray/autoscaler/updater.py
Labels: P1

#10706 [autoscaler] use default value
  python/ray/autoscaler/autoscaler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: P0, release-blocker

#10723 Remove colorful from ray core
  python/ray/resource_spec.py
  python/ray/services.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  python/ray/tests/test_output.py
Labels: P0, release-blocker

#10726 [cli] Remove extra wording + fix travis
  python/ray/autoscaler/cli_logger.py
  python/ray/autoscaler/commands.py
  python/ray/tests/test_cli_patterns/test_ray_up.txt
  python/ray/tests/test_cli_patterns/test_ray_up_record.txt
Labels: @author-action-required

#10721 [autoscaler] Fix rsync file mounts
  python/ray/autoscaler/commands.py
Labels: @tests-ok, P0, release-blocker

#10728 [Autoscaler] Fix utilization calc
  python/ray/autoscaler/resource_demand_scheduler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: release-blocker

#10725 [hotfix] accelerator_types
  python/ray/util/accelerators/__init__.py
Labels: @author-action-required, release-blocker

#10711 [autoscaler] Don't pin boto version, instead set lower limit on its version
  python/ray/autoscaler/aws/example-full.yaml
Labels: @author-action-required

#10751 [Doc] Add section for threaded actor
  doc/source/actors.rst
  doc/source/async_api.rst
Labels: @author-action-required

#10729 [Java] Support exchange ObjectRef between processes
  java/runtime/src/main/java/io/ray/runtime/object/LocalModeObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/object/NativeObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectRefImpl.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectSerializer.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectStore.java
  java/test/src/main/java/io/ray/test/ObjectRefTransferTest.java
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.h
Labels: java

#10513 [Autoscaler] Unmanaged nodes
  doc/source/cluster/autoscaling.rst
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/resource_demand_scheduler.py
  python/ray/autoscaler/tags.py
  python/ray/tests/test_autoscaler.py
Labels: @tests-ok

#9634 [Java] Attach owner address for pass-by-reference task arguments
  java/runtime/src/main/java/io/ray/runtime/context/LocalModeWorkerContext.java
  java/runtime/src/main/java/io/ray/runtime/context/NativeWorkerContext.java
  java/runtime/src/main/java/io/ray/runtime/context/WorkerContext.java
  java/runtime/src/main/java/io/ray/runtime/object/LocalModeObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/object/NativeObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/task/ArgumentsBuilder.java
  java/runtime/src/main/java/io/ray/runtime/task/FunctionArg.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskSubmitter.java
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_actor_NativeActorHandle.cc
  src/ray/core_worker/lib/java/io_ray_runtime_context_NativeWorkerContext.cc
  src/ray/core_worker/lib/java/io_ray_runtime_context_NativeWorkerContext.h
  src/ray/core_worker/lib/java/io_ray_runtime_metric_NativeMetric.h
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskExecutor.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/lib/java/jni_init.cc
  src/ray/core_worker/lib/java/jni_utils.h
Labels: @author-action-required

#10507 [docker] Detect CPUs in container correctly
  .travis.yml
  doc/source/serve/index.rst
  doc/source/tune/_tutorials/tune-serve-integration-mnist.py
  python/ray/resource_spec.py
  python/ray/serve/examples/doc/quickstart_class.py
  python/ray/serve/examples/doc/quickstart_function.py
  python/ray/serve/examples/doc/snippet_model_composition.py
  python/ray/serve/examples/doc/tutorial_batch.py
  python/ray/serve/examples/doc/tutorial_pytorch.py
  python/ray/serve/examples/doc/tutorial_sklearn.py
  python/ray/serve/examples/doc/tutorial_tensorflow.py
  python/ray/tests/test_memory_scheduling.py
  python/ray/tune/examples/cifar10_pytorch.py
  python/ray/tune/examples/horovod_simple.py
  python/ray/tune/examples/pbt_convnet_example.py
  python/ray/tune/tests/ext_pytorch.py
  python/ray/tune/tests/test_dependency.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tests/test_sync.py
  python/ray/tune/tests/test_track.py
  python/ray/tune/tests/test_trial_runner.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
  python/ray/tune/tests/test_tune_restore.py
  python/ray/tune/tests/test_var.py
  python/ray/util/sgd/BUILD
  python/ray/util/sgd/tf/examples/cifar_tf_example.py
  python/ray/util/sgd/tf/examples/tensorflow_train_example.py
  python/ray/util/sgd/torch/examples/benchmarks/benchmark.py
  python/ray/util/sgd/torch/examples/dcgan.py
  python/ray/util/sgd/torch/examples/image_models/train.py
  python/ray/util/sgd/torch/examples/train_example.py
  python/ray/util/sgd/torch/examples/tune_example.py
  python/ray/utils.py
Labels: @author-action-required, release-blocker

#10569 [Core] Multi-tenancy: Reject worker registration if job has finished
  python/ray/tests/test_multi_tenancy.py
  src/ray/core_worker/core_worker.cc
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @author-action-required

#10780 [docs] Polish community integrations docs
  README.rst
  doc/requirements-rtd.txt
  doc/source/images/classyvision.png
  doc/source/images/dask.png
  doc/source/images/flambe.png
  doc/source/images/horovod.png
  doc/source/images/hugging.png
  doc/source/images/mars.png
  doc/source/images/modin.png
  doc/source/images/pycaret.png
  doc/source/images/seldon.png
  doc/source/images/spacy.png
  doc/source/images/zoo.png
  doc/source/index.rst
  doc/source/multiprocessing.rst
  doc/source/oss-users.rst
  doc/source/pandas_on_ray.rst
  doc/source/ray-overview/basics.rst
Labels: @author-action-required

#10731 Warn when failed to get the exact version of pickle5
  python/ray/__init__.py
Labels: @tests-ok

#10749 [Dashboard] Fix a number of console warnings caused by incorrect usage of react keys
  python/ray/dashboard/client/src/pages/dashboard/logical-view/Actor.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/ActorClassGroup.tsx
  python/ray/dashboard/client/src/pages/dashboard/logical-view/ActorDetailsPane.tsx
  python/ray/dashboard/client/src/pages/dashboard/memory/Memory.tsx
  python/ray/dashboard/client/src/pages/dashboard/memory/MemoryTableRow.tsx
  python/ray/dashboard/client/src/pages/dashboard/node-info/NodeWorkerRow.tsx
  python/ray/dashboard/client/src/pages/dashboard/node-info/TotalRow.tsx
  python/ray/dashboard/tests/test_node_stats.py
Labels: dashboard

#10539 [Ray SGD] use_local flag + Worker group abstraction
  doc/source/raysgd/raysgd_pytorch.rst
  python/ray/tune/integration/torch.py
  python/ray/util/sgd/BUILD
  python/ray/util/sgd/data/dataset.py
  python/ray/util/sgd/tests/test_torch.py
  python/ray/util/sgd/tests/test_torch_failure.py
  python/ray/util/sgd/torch/distributed_torch_runner.py
  python/ray/util/sgd/torch/examples/cifar_pytorch_example.py
  python/ray/util/sgd/torch/examples/raysgd_torch_signatures.py
  python/ray/util/sgd/torch/examples/tune_example.py
  python/ray/util/sgd/torch/torch_runner.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/training_operator.py
  python/ray/util/sgd/torch/utils.py
  python/ray/util/sgd/torch/worker_group.py
Labels: @tests-ok, P0, release-blocker

#10783 [docker] Make python version configurable on docker image
  build-docker.sh
  docker/base-deps/Dockerfile
Labels: @tests-ok

#10462 [Autoscaler] Change poll interval to 5 sec when checking VMs status
  python/ray/autoscaler/commands.py
Labels: @tests-ok

#10801 Java doc: "Configuring Ray" page
  doc/source/configure.rst
  doc/source/cross-language.rst
  doc/source/starting-ray.rst
Labels: java

#10528 [Dashboard] Dashboard node grouping
  dashboard/agent.py
  dashboard/datacenter.py
  dashboard/head.py
  dashboard/modules/log/log_head.py
  dashboard/modules/log/test_log.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/modules/reporter/test_reporter.py
  dashboard/modules/stats_collector/stats_collector_head.py
  dashboard/modules/stats_collector/test_stats_collector.py
  dashboard/tests/test_dashboard.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/worker.py
  src/ray/core_worker/core_worker.h
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/agent_manager.h
  src/ray/raylet/node_manager.cc
Labels: @author-action-required, dashboard

#10555 [docs] Placement group documentation
  doc/source/conf.py
  doc/source/index.rst
  doc/source/package-ref.rst
  doc/source/placement-group.rst
  doc/source/using-ray.rst
  python/ray/state.py
  python/ray/util/placement_group.py
Labels: @author-action-required

#10822 [autoscaler] Enforce CommandRunnerInterface abstractions
  python/ray/autoscaler/command_runner.py
  python/ray/tests/test_command_runner.py
Labels: @author-action-required

#10821 [hotfix] CPU Detection
  python/ray/tests/test_advanced_3.py
  python/ray/utils.py
Labels: release-blocker

#10834 [RLlib] Issue 10833 TorchPolicy GPU.
  rllib/policy/torch_policy.py
Labels: @author-action-required

#10848 Fix push_error_to_driver_through_redis
  python/ray/tests/test_failure.py
  python/ray/utils.py
Labels: @tests-ok

#10820 [autoscaler] Ensure `run_init` happens in all cases
  python/ray/autoscaler/updater.py
  python/ray/tests/test_autoscaler.py
Labels: @tests-ok, P1

#9977 [cpp worker] support cluster mode
  cpp/BUILD.bazel
  cpp/include/ray/api.h
  cpp/include/ray/api/ray_config.h
  cpp/include/ray/api/ray_runtime.h
  cpp/include/ray/experimental/default_worker.h
  cpp/src/example/example_cluster_mode.cc
  cpp/src/ray/api.cc
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/abstract_ray_runtime.h
  cpp/src/ray/runtime/native_ray_runtime.cc
  cpp/src/ray/runtime/task/invocation_spec.h
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/local_mode_task_submitter.h
  cpp/src/ray/runtime/task/native_task_submitter.cc
  cpp/src/ray/runtime/task/native_task_submitter.h
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  cpp/src/ray/runtime/task/task_submitter.h
  cpp/src/ray/test/cluster/cluster_mode_test.cc
  cpp/src/ray/util/address_helper.cc
  cpp/src/ray/util/address_helper.h
  cpp/src/ray/util/function_helper.cc
  cpp/src/ray/util/function_helper.h
  cpp/src/ray/util/process_helper.cc
  cpp/src/ray/util/process_helper.h
  cpp/src/ray/worker/default_worker.cc
  python/ray/services.py
Labels: @author-action-required

#10874 [autoscaler] hotfix calculate_node_resources
  python/ray/autoscaler/resource_demand_scheduler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @author-action-required

#10659 [1.0] Remove args from ray start
  cpp/src/ray/util/process_helper.cc
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  java/test.sh
  java/test/src/main/java/io/ray/test/BaseMultiLanguageTest.java
  python/ray/scripts/scripts.py
  python/ray/tests/test_multi_node.py
  streaming/java/streaming-api/src/main/java/io/ray/streaming/api/context/ClusterStarter.java
Labels: @tests-ok, P0, release-blocker

#10931 [Ray SGD] FP16 Hotfix
  python/ray/util/sgd/torch/training_operator.py
Labels: P0, release-blocker

#10924 [Placement group] Release test
  ci/regression_test/stress_tests/placement_group/test_placement_group.py
  doc/dev/RELEASE_PROCESS.rst
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
Labels: @author-action-required

#10948 [Java Worker]Add a resource checker for java worker creation
  java/api/src/main/java/io/ray/api/options/BaseTaskOptions.java
  java/test/src/main/java/io/ray/test/BaseTaskOptionsTest.java
Labels: java

#10953 [docs][tune] update max_failures kwarg default in tune.run docstring
  python/ray/tune/tune.py
Labels: fix-docs, tune

#10936 [Serve] Only install dataclasses on Python 3.6
  ci/asan_tests/ray-project/requirements.txt
  python/requirements.txt
  python/setup.py
Labels: @tests-ok

#10962 [RLlib] APPO Vtrace Config
  rllib/agents/ppo/appo.py
Labels: @author-action-required

#10964 [Docs] [Ray SGD] Fix example to show in docs
  python/ray/util/sgd/torch/examples/raysgd_torch_signatures.py
Labels: @tests-ok

#10938 [New Scheduler] Refactor cluster resource scheduler
  python/ray/tests/test_basic.py
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/fixed_point.cc
  src/ray/raylet/scheduling/fixed_point.h
Labels: @tests-ok

#10853 [Core] Fix `maximum_startup_concurrency` caused by `AnnounceWorkerPort`
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#10974 [Placement Group]Optimize bundle log
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#10971 [Core] Remove unnecessary if judgment
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#10826 [cli][ray] fix `ray start` should error by default if there`s already…
  python/ray/scripts/scripts.py
  python/ray/services.py
  python/ray/tests/conftest.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_multi_node.py
  python/ray/tests/test_tempfile.py
Labels: @author-action-required, @tests-ok

#10968 [Placement Group] Capture Child Task Part 1
  doc/source/package-ref.rst
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/runtime_context.py
  python/ray/state.py
  python/ray/tests/test_placement_group.py
  python/ray/util/placement_group.py
  python/ray/worker.py
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.h
Labels: @author-action-required

#10972 [tune] strict metric checking
  doc/source/tune/_tutorials/tune-xgboost.rst
  doc/source/tune/user-guide.rst
  python/ray/tune/examples/xgboost_example.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/schedulers/trial_scheduler.py
  python/ray/tune/suggest/search.py
  python/ray/tune/suggest/search_generator.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_sample.py
  python/ray/tune/trial.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
Labels: @tests-ok

#11014 Add a new _available_resources_per_node for state API
  python/ray/state.py
Labels: @author-action-required

#11019 [docs] remove ref to google groups -> github discussions
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  CONTRIBUTING.rst
  README.rst
  doc/source/_help.rst
  doc/source/cluster/kubernetes.rst
  doc/source/cluster/launcher.rst
  doc/source/cluster/yarn.rst
  doc/source/memory-management.rst
  doc/source/ray-overview/involvement.rst
  doc/source/tune/_tutorials/_faq.rst
  doc/source/tune/key-concepts.rst
  doc/source/tune/user-guide.rst
Labels: @author-action-required

#10935 [tests] Blacklist failing win32 tests
  ci/travis/ci.sh
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_command_runner.py
Labels: @tests-ok

#10988 [rllib] Replay buffer size inaccurate with replay_seq_len option
  rllib/execution/replay_buffer.py
  rllib/execution/tests/test_prioritized_replay_buffer.py
Labels: @tests-ok

#11034 [Placement Group] Remove warning msg for placement groups.
  python/ray/tests/test_placement_group.py
  python/ray/util/placement_group.py
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#11001 [tune] Callbacks for tune runs
  doc/source/tune/api_docs/internals.rst
  doc/source/tune/user-guide.rst
  python/ray/tune/BUILD
  python/ray/tune/__init__.py
  python/ray/tune/tests/test_trial_runner_callbacks.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
Labels: @tests-ok

#11055 [GCS]Fix gcs server rpc port bug
  src/ray/gcs/gcs_server/gcs_server_main.cc
Labels: @author-action-required

#11025 [Placement Group] Capture child tasks by default.
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/native_task_submitter.cc
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/cross_language.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/runtime_context.py
  python/ray/tests/BUILD
  python/ray/tests/test_placement_group.py
  python/ray/util/placement_group.py
  python/ray/worker.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/task_dependency_manager_test.cc
Labels: @author-action-required

#11002 [Log] make glog flush and RAY_LOG thread-safe
  bazel/ray_deps_setup.bzl
  python/ray/tests/test_raylet_output.py
  src/ray/util/logging.cc
  thirdparty/patches/glog-suffix-log.patch
Labels: @author-action-required, @tests-ok

#11065 [Java] Enable retry in TestNG
  java/test/src/main/java/io/ray/test/AnnotationTransformer.java
  java/test/src/main/java/io/ray/test/RetryAnalyzer.java
  java/testng.xml
Labels: java

#11066 [RLlib] Curiosity documentation.
  doc/source/rllib-algorithms.rst
  doc/source/rllib-toc.rst
  doc/source/rllib-training.rst
  rllib/utils/exploration/exploration.py
Labels: @tests-ok

#10897 [RLlib] Remove unnecessary copies in `compute_advantages`.
  rllib/evaluation/postprocessing.py
Labels: @author-action-required

#10777 [cli] Updates
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/autoscaler/_private/aws/utils.py
  python/ray/autoscaler/_private/cli_logger.py
  python/ray/autoscaler/_private/cli_logger_demoall.py
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/subprocess_output_util.py
  python/ray/autoscaler/_private/updater.py
  python/ray/scripts/scripts.py
Labels: @author-action-required

#11010 [Dashboard] Add Ray Config API to Reporter Head
  dashboard/modules/reporter/reporter_head.py
Labels: dashboard

#11135 [Java] Upgrade TestNG to 7.3.0
  java/BUILD.bazel
  java/dependencies.bzl
  java/runtime/pom.xml
  java/test/pom.xml
  java/testng.xml
  streaming/java/BUILD.bazel
  streaming/java/dependencies.bzl
  streaming/java/pom.xml
  streaming/java/streaming-api/pom.xml
  streaming/java/streaming-runtime/pom.xml
  streaming/java/streaming-state/pom.xml
  streaming/java/testng.xml
Labels: java

#11097 [Object Spilling] Name IO workers properly.
  python/ray/ray_constants.py
  python/ray/tests/test_object_spilling.py
  python/ray/worker.py
Labels: @author-action-required

#10570 [Core] Multi-tenancy: enable multi-tenancy by default
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  python/ray/test_utils.py
  python/ray/tests/test_advanced_2.py
  python/ray/tests/test_component_failures_2.py
  python/ray/tests/test_job.py
  python/ray/tests/test_multi_tenancy.py
  python/ray/tests/test_multinode_failures.py
  python/ray/tests/test_reconstruction.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: @author-action-required

#11128 [Core] Fix 2 bugs that are randomly found.
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/util/placement_group.py
Labels: @author-action-required

#11143 [Doc] Use different pygments_style
  doc/requirements-doc.txt
  doc/source/conf.py
Labels: @author-action-required

#11086 [autoscaler] Make it more clear NodeProvider and CommandRunner are private APIs
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/providers.py
  python/ray/autoscaler/_private/util.py
  python/ray/autoscaler/command_runner.py
  python/ray/autoscaler/node_provider.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_coordinator_server.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @author-action-required
