Repository ray-project/ray, pull requests merged in 2020-06, with the labels that each got.

#8718 [Serve] Cleanup Router Implementation
  python/ray/serve/policy.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_router.py
Labels: tests ok

#8628 [Core] Randomize and 'Reserve' Port Generated for Node Manager
  python/ray/node.py
  python/ray/services.py
Labels: tests ok

#8393 [rllib] Support for complex / variable-length observation spaces
  doc/source/rllib-models.rst
  doc/source/rllib-toc.rst
  doc/source/struct-tensor.png
  rllib/BUILD
  rllib/examples/complex_struct_space.py
  rllib/examples/env/simple_rpg.py
  rllib/examples/models/simple_rpg_model.py
  rllib/models/modelv2.py
  rllib/models/preprocessors.py
  rllib/models/repeated_values.py
  rllib/tests/test_nested_observation_spaces.py
  rllib/utils/spaces/repeated.py
  rllib/utils/spaces/simplex.py
Labels: tests ok

#8898 [RLlib] Issue 8889: action clipping bug ppo not learning mujoco
  rllib/evaluation/sampler.py
  rllib/tuned_examples/debug_learning_failure_git_bisect.py
Labels: tests ok

#8905 Fix Windows build
  src/ray/rpc/grpc_server.cc
Labels: P0, release-blocker

#8933 Issue 8919 checkpoint at end ignored
  rllib/tests/test_checkpoint_restore.py
  rllib/train.py
Labels: tests ok

#8860 [RLlib] Prototype of a DynaTrainer (for env dynamics learning in upcoming MBMPO algo).
  rllib/BUILD
  rllib/agents/dyna/__init__.py
  rllib/agents/dyna/dyna.py
  rllib/agents/dyna/dyna_torch_model.py
  rllib/agents/dyna/dyna_torch_policy.py
  rllib/agents/dyna/tests/test_dyna.py
  rllib/examples/env/stateless_cartpole.py
  rllib/models/catalog.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_template.py
Labels: tests ok

#8785 [RLlib] Make sure torch and tf behave the same wrt conv2d nets.
  rllib/BUILD
  rllib/models/tf/visionnet.py
  rllib/models/torch/fcnet.py
  rllib/models/torch/misc.py
  rllib/models/torch/visionnet.py
  rllib/rollout.py
  rllib/tests/test_attention_net_learning.py
  rllib/tests/test_supported_spaces.py
  rllib/train.py
  rllib/tuned_examples/ars/cartpole-ars.yaml
  rllib/tuned_examples/es/cartpole-es.yaml
Labels: tests ok

#8862 [rllib] MAML Agent
  rllib/BUILD
  rllib/agents/maml/__init__.py
  rllib/agents/maml/maml.py
  rllib/agents/maml/maml_tf_policy.py
  rllib/agents/maml/tests/test_maml.py
  rllib/agents/registry.py
  rllib/dyna.yaml
  rllib/examples/env/ant_rand_goal.py
  rllib/examples/env/halfcheetah_rand_direc.py
  rllib/examples/env/pendulum_mass.py
  rllib/tuned_examples/maml/ant-rand-goal-maml.yaml
  rllib/tuned_examples/maml/halfcheetah-rand-direc-maml.yaml
  rllib/tuned_examples/maml/pendulum-mass-maml.yaml
Labels: rllib, tests ok

#9097 Fix ray arrow logs
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/dlmalloc.cc
  src/ray/object_manager/plasma/eviction_policy.cc
  src/ray/object_manager/plasma/fling.cc
  src/ray/object_manager/plasma/hash_table_store.cc
  src/ray/object_manager/plasma/hash_table_store.h
  src/ray/object_manager/plasma/io.cc
  src/ray/object_manager/plasma/malloc.cc
  src/ray/object_manager/plasma/plasma.cc
  src/ray/object_manager/plasma/plasma.h
  src/ray/object_manager/plasma/plasma_allocator.cc
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/quota_aware_policy.cc
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store_runner.cc
  src/ray/object_manager/plasma/test/client_tests.cc
  src/ray/object_manager/plasma/test/external_store_tests.cc
  src/ray/object_manager/plasma/test/serialization_tests.cc
  src/ray/object_manager/plasma/test_util.h
  src/ray/plasma/store_exec.cc
Labels: P0

#8885 [Core] Log output from different jobs to different drivers.
  python/ray/_raylet.pyx
  python/ray/node.py
  python/ray/tests/test_tempfile.py
  python/ray/utils.py
  python/ray/worker.py
Labels: core

#8978 [iter] Add .transform() function for arbitrary generator transforms
  python/ray/tests/test_iter.py
  python/ray/util/iter.py
  src/ray/object_manager/plasma/store.cc
Labels: tests ok

#8953 [Core] Log monitor multidriver
  python/ray/log_monitor.py
  python/ray/test_utils.py
  python/ray/tests/test_multi_node.py
  python/ray/utils.py
  python/ray/worker.py
Labels: core

#9139 [RLlib] Issue 8407: RNN sequencing error QMIX
  rllib/agents/qmix/qmix_policy.py
Labels: tests ok

#9142 [RLlib] Issue 8507 (PyTorch does not support custom loss).
  rllib/examples/models/custom_loss_model.py
  rllib/offline/json_reader.py
  rllib/policy/torch_policy.py
Labels: tests ok

#9169 [RLlib] Win10 setup-dev.py fixes.
  doc/source/development.rst
  python/ray/setup-dev.py
Labels: tests ok

#9149 [Core] New scheduler don't double assign actor id
  src/ray/raylet/node_manager.cc
Labels: core
