Repository ray-project/ray, pull requests merged in 2020-10, with the labels that each got.

#11140 [tune][hotfix] comment out test
  python/ray/tune/BUILD
Labels: @author-action-required

#11035 [tune] docker syncer
  doc/source/tune/api_docs/integration.rst
  doc/source/tune/user-guide.rst
  python/ray/tune/BUILD
  python/ray/tune/integration/docker.py
  python/ray/tune/integration/kubernetes.py
  python/ray/tune/tests/test_integration_docker.py
Labels: @tests-ok

#11024 [New Scheduler] Heartbeat
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/fixed_point.cc
  src/ray/raylet/scheduling/fixed_point.h
  src/ray/raylet/scheduling/scheduling_ids.cc
  src/ray/raylet/scheduling/scheduling_ids.h
Labels: @tests-ok

#11125 [Docker] Automagically add "runtime=nvidia"
  doc/source/cluster/autoscaling.rst
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/aws/example-full.yaml
  python/ray/autoscaler/aws/example-gpu-docker.yaml
  python/ray/autoscaler/aws/example-ml.yaml
  python/ray/autoscaler/azure/example-full.yaml
  python/ray/autoscaler/azure/example-gpu-docker.yaml
  python/ray/autoscaler/azure/example-gpu.yaml
  python/ray/autoscaler/gcp/example-gpu-docker.yaml
  python/ray/autoscaler/ray-schema.json
Labels: @tests-ok

#10947 [tune] Fix GPU thread leakage
  python/ray/tune/trainable.py
Labels: @author-action-required

#11042 [Ray SGD] LightningModule integration + MNIST Example
  python/ray/util/sgd/BUILD
  python/ray/util/sgd/tests/test_ptl.py
  python/ray/util/sgd/torch/distributed_torch_runner.py
  python/ray/util/sgd/torch/examples/pytorch-lightning/mnist-ptl.py
  python/ray/util/sgd/torch/ptl_operator.py
  python/ray/util/sgd/torch/torch_runner.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/training_operator.py
  python/ray/util/sgd/torch/worker_group.py
Labels: @tests-ok

#11011 [Dashboard] Add utility functions for actor and memory APIs
  dashboard/actor_utils.py
  dashboard/memory_utils.py
  dashboard/tests/test_memory_utils.py
  dashboard/utils.py
Labels: dashboard

#11009 [Dashboard] Add tune API to support tune tab in new backend
  dashboard/modules/tune/__init__.py
  dashboard/modules/tune/tune_consts.py
  dashboard/modules/tune/tune_head.py
Labels: dashboard

#11013 [Dashboard] Add support for new backend to existing front-end
  dashboard/client/src/api.ts
  dashboard/client/src/pages/dashboard/Dashboard.tsx
  dashboard/client/src/pages/dashboard/logical-view/Actor.tsx
  dashboard/client/src/pages/dashboard/logical-view/ActorDetailsPane.tsx
  dashboard/client/src/pages/dashboard/logical-view/LogicalView.tsx
  dashboard/client/src/pages/dashboard/memory/Memory.tsx
  dashboard/client/src/pages/dashboard/memory/MemorySummary.tsx
  dashboard/client/src/pages/dashboard/memory/MemoryTable.tsx
  dashboard/client/src/pages/dashboard/memory/MemoryTableRow.tsx
  dashboard/client/src/pages/dashboard/node-info/NodeInfo.tsx
  dashboard/client/src/pages/dashboard/node-info/NodeRowGroup.tsx
  dashboard/client/src/pages/dashboard/node-info/NodeWorkerRow.tsx
  dashboard/client/src/pages/dashboard/node-info/TotalRow.tsx
  dashboard/client/src/pages/dashboard/node-info/dialogs/errors/Errors.tsx
  dashboard/client/src/pages/dashboard/node-info/dialogs/logs/Logs.tsx
  dashboard/client/src/pages/dashboard/node-info/features/CPU.tsx
  dashboard/client/src/pages/dashboard/node-info/features/Errors.tsx
  dashboard/client/src/pages/dashboard/node-info/features/GPU.tsx
  dashboard/client/src/pages/dashboard/node-info/features/GRAM.tsx
  dashboard/client/src/pages/dashboard/node-info/features/Logs.tsx
  dashboard/client/src/pages/dashboard/node-info/features/ObjectStoreMemory.tsx
  dashboard/client/src/pages/dashboard/node-info/features/RAM.tsx
  dashboard/client/src/pages/dashboard/node-info/features/Uptime.tsx
  dashboard/client/src/pages/dashboard/node-info/features/types.tsx
  dashboard/client/src/pages/dashboard/ray-config/RayConfig.tsx
  dashboard/client/src/pages/dashboard/state.ts
  dashboard/client/src/pages/dashboard/tune/Tune.tsx
  dashboard/client/src/pages/dashboard/tune/TuneErrors.tsx
  dashboard/client/src/pages/dashboard/tune/TuneTable.tsx
  dashboard/client/src/pages/dashboard/tune/TuneTensorBoard.tsx
Labels: dashboard

#11021 [Object spilling] Update object directory and reload spilled objects automatically
  python/ray/_raylet.pyx
  python/ray/experimental/__init__.py
  python/ray/experimental/object_spilling.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_object_spilling.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_object_manager.cc
  src/ray/gcs/gcs_server/gcs_object_manager.h
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/redis_accessor.cc
  src/ray/gcs/redis_accessor.h
  src/ray/gcs/test/redis_object_info_accessor_test.cc
  src/ray/object_manager/object_directory.cc
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/test/object_manager_stress_test.cc
  src/ray/object_manager/test/object_manager_test.cc
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/reconstruction_policy.cc
  src/ray/raylet/reconstruction_policy_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @author-action-required

#11183 [Test] Make test_serialization a medium size test.
  python/ray/tests/BUILD
Labels: @author-action-required

#11012 [Dashboard] Add API support for the logical view and machine view in new backend
  .travis.yml
  dashboard/datacenter.py
  dashboard/memory_utils.py
  dashboard/modules/logical_view/__init__.py
  dashboard/modules/logical_view/logical_view_head.py
  dashboard/modules/logical_view/test_logical_view_head.py
  dashboard/modules/reporter/test_reporter.py
  dashboard/modules/stats_collector/stats_collector_consts.py
  dashboard/modules/stats_collector/stats_collector_head.py
  dashboard/modules/stats_collector/test_stats_collector.py
Labels: dashboard

#11173 [Core/GCS] Use optional return instead of nullptr for the`GetNode` method.
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_node_manager_test.cc
Labels: @author-action-required

#11142 [Ray SGD] Support num_steps continue training
  python/ray/util/sgd/tests/test_torch.py
  python/ray/util/sgd/torch/torch_runner.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/training_operator.py
Labels: @tests-ok

#11129 [Placement Group] Report placement group load through heartbeat.
  python/ray/tests/BUILD
  python/ray/tests/test_global_state.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/protobuf/gcs.proto
Labels: @author-action-required

#11117 Dmitri/add mypy to ci
  ci/travis/format.sh
  python/requirements_linters.txt
Labels: @author-action-required

#11039 [Core] Report worker backlog in GCS heartbeat
  python/ray/tests/test_global_state.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/task.cc
  src/ray/common/task/task.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling_queue.cc
  src/ray/raylet/scheduling_queue.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @tests-ok

#11222 [Autoscaler] Remove extra print statement
  python/ray/autoscaler/_private/resource_demand_scheduler.py
Labels: @tests-ok

#11221 Type annotations added to node_provider.py
  python/ray/autoscaler/node_provider.py
Labels: @author-action-required

#11217 [hotfix] use const ref in for-each loops to prevent warnings
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
Labels: @tests-ok

#11181 [Serve] Disable serialization for client and print helpful msg
  python/ray/serve/api.py
Labels: @author-action-required

#10980 [Serve] Serve multi node tests
  ci/long_running_tests/workloads/serve.py
  python/ray/serve/benchmarks/baselines/2020-10-07/handle.txt
  python/ray/serve/benchmarks/baselines/2020-10-07/microbenchmark.txt
  python/ray/serve/benchmarks/baselines/2020-10-07/scalability.txt
  python/ray/serve/benchmarks/cluster.yaml
  python/ray/serve/benchmarks/handle.py
  python/ray/serve/benchmarks/microbenchmark.py
  python/ray/serve/benchmarks/scalability.py
Labels: @tests-ok

#11257 Deflake test_env_with_subprocess.py
  rllib/tests/test_env_with_subprocess.py
Labels: @author-action-required

#11224 [Autoscaler] Fix commands that write unexpected files to head node
  python/ray/autoscaler/aws/example-full.yaml
  python/ray/autoscaler/aws/example-ml.yaml
Labels: @tests-ok, bug

#11263 [Placement Group] Fix placement group bugs that happen when rescheduling.
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
Labels: @author-action-required

#11265 [Core] Publish gcs server failure to drivers.
  python/ray/log_monitor.py
  python/ray/tests/conftest.py
  python/ray/tests/test_failure.py
Labels: @author-action-required

#10792 Fix spelling of occurred
  python/ray/autoscaler/_private/commands.py
  python/ray/dashboard/metrics_exporter/client.py
  python/ray/tune/function_runner.py
  python/ray/worker.py
Labels: @author-action-required

#11249 [RLlib] Add MultiAgentEnv wrapper for Kaggle's football environment
  rllib/env/wrappers/kaggle_wrapper.py
  rllib/env/wrappers/tests/test_kaggle_wrapper.py
Labels: @author-action-required

#11153 [Placement Group] Export bundle reservation check method only once.
  python/ray/util/placement_group.py
Labels: @author-action-required

#11230 [tune] reuse actors for function API
  doc/source/tune/user-guide.rst
  python/ray/tune/function_runner.py
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/tests/test_actor_reuse.py
  python/ray/tune/trainable.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
Labels: @tests-ok

#11278 [autoscaler/k8s] Replace read_namespaced_pod_status with read_namespaced_pod
  python/ray/autoscaler/_private/kubernetes/node_provider.py
  python/ray/autoscaler/_private/staroid/node_provider.py
Labels: @tests-ok

#10613 [Java] upgrade common-collections version
  streaming/java/dependencies.bzl
  streaming/java/streaming-runtime/pom.xml
Labels: java

#10921 [Dashboard] http route handler cache
  dashboard/consts.py
  dashboard/modules/log/test_log.py
  dashboard/modules/logical_view/logical_view_head.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/modules/stats_collector/stats_collector_head.py
  dashboard/modules/stats_collector/test_stats_collector.py
  dashboard/modules/test/test_head.py
  dashboard/modules/tune/tune_head.py
  dashboard/tests/conftest.py
  dashboard/tests/test_dashboard.py
  dashboard/utils.py
Labels: @tests-ok, dashboard

#11261 [Autoscaler] Account for resource backlog size
  python/ray/gcs_utils.py
  python/ray/monitor.py
  python/ray/tests/BUILD
  python/ray/tests/test_monitor.py
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#11342 [RLlib] Create ci/rllib_tests and organize a little (prep for automatic daily GPU test).
  ci/rllib_tests/regresssion_tests/compact-regression-test.yaml
  ci/rllib_tests/regresssion_tests/ray-project/cluster.yaml
  ci/rllib_tests/regresssion_tests/ray-project/project.yaml
  ci/rllib_tests/regresssion_tests/ray-project/requirements.txt
  ci/rllib_tests/regresssion_tests/run.sh
  ci/rllib_tests/stress_tests/atari_impala_xlarge.yaml
  ci/rllib_tests/stress_tests/ray-project/cluster.yaml
  ci/rllib_tests/stress_tests/ray-project/project.yaml
  ci/rllib_tests/stress_tests/ray-project/requirements.txt
  ci/rllib_tests/stress_tests/run.sh
  ci/rllib_tests/stress_tests/wait_cluster.py
  ci/rllib_tests/unit_gpu_tests/ray-project/cluster.yaml
  ci/rllib_tests/unit_gpu_tests/ray-project/requirements.txt
  ci/rllib_tests/unit_gpu_tests/run.sh
Labels: @tests-ok

#11245 [RLlib] Assert LongTensor in SAC Discrete PyTorch
  rllib/agents/sac/sac_torch_policy.py
Labels: @author-action-required

#11298 [RLlib] SAC: log_alpha not being learnt when on GPU.
  rllib/agents/sac/sac_torch_model.py
  rllib/agents/sac/tests/test_sac.py
Labels: @tests-ok

#11301 [RLlib] Allow for more than 2^31 policy timesteps.
  rllib/BUILD
  rllib/examples/env/random_env.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/tf_policy.py
  rllib/tests/test_timesteps.py
  rllib/utils/exploration/epsilon_greedy.py
  rllib/utils/exploration/gaussian_noise.py
  rllib/utils/exploration/stochastic_sampling.py
  rllib/utils/framework.py
  rllib/utils/schedules/piecewise_schedule.py
Labels: @tests-ok

#11308 [RLlib] ARS/ES eval workers not working: Issue 9933.
  rllib/agents/ars/ars.py
  rllib/agents/ars/ars_tf_policy.py
  rllib/agents/ars/tests/test_ars.py
  rllib/agents/es/es.py
  rllib/agents/es/es_tf_policy.py
  rllib/agents/es/es_torch_policy.py
  rllib/agents/es/tests/test_es.py
  rllib/agents/pg/tests/test_pg.py
  rllib/agents/trainer.py
  rllib/models/preprocessors.py
  rllib/policy/torch_policy_template.py
  rllib/tests/test_evaluators.py
Labels: @tests-ok

#11311 [RLlib] Add support for custom MultiActionDistributions.
  rllib/models/catalog.py
  rllib/tests/test_catalog.py
Labels: @tests-ok

#11356 [RLlib] Fix test_env_with_subprocess.py.
  rllib/BUILD
  rllib/tests/test_env_with_subprocess.py
  rllib/tests/test_local.py
Labels: @tests-ok

#11324 [Java] Release actor instance reference when `Ray.exitActor()` is invoked
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/RayRuntimeInternal.java
  java/runtime/src/main/java/io/ray/runtime/task/NativeTaskExecutor.java
  java/runtime/src/main/java/io/ray/runtime/task/TaskExecutor.java
  java/test/src/main/java/io/ray/test/ExitActorTest.java
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/jni_init.cc
  src/ray/core_worker/lib/java/jni_utils.h
Labels: java

#11360 [Log] dump stacktrace from glog lib
  bazel/ray_deps_setup.bzl
  src/ray/util/logging.cc
  src/ray/util/logging.h
  src/ray/util/logging_test.cc
  thirdparty/patches/glog-dump-stacktrack.patch
Labels: @author-action-required

#11243 [Autoscaler] Placement group autoscaling
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/monitor.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#11152 [Placement group] Input validation
  python/ray/tests/test_placement_group.py
  src/ray/common/placement_group.h
Labels: @author-action-required

#11354 [autoscaler]Type hints for commands.py and sdk.py.
  ci/travis/format.sh
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/sdk.py
Labels: @tests-ok

#11400 [Docker] Fix Docker Stop on Teardown
  python/ray/autoscaler/_private/commands.py
Labels: @tests-ok

#11306 [PlacementGroup]Add guarded by in placement group scheduler ut
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
Labels: @tests-ok

#11413 [Log] Ignore callstacktrace test for windows
  src/ray/util/logging_test.cc
Labels: @author-action-required

#11410 [Java] fix shutdown lock typo
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
Labels: java

#11406 Fix code_search_path failed in java
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool_test.cc
Labels: java

#11515 Try to raise ulimit for file descriptors to max allowed; warn if ulimit is still too low
  python/ray/worker.py
Labels: @author-action-required

#11381 [New scheduler] queue by shape
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#11422 [autoscaler/AWS] Updated AWS Node Provider threading logic
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/tests/BUILD
  python/ray/tests/aws/test_aws_batch_tag_update.py
Labels: @tests-ok

#11532 [hotfix] Pin node version (fix linux wheel build)
  python/build-wheel-manylinux1.sh
Labels: P0

#11458 [Autoscaler] Do not count unmanaged nodes in load metrics
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/tests/test_autoscaler.py
Labels: @tests-ok

#11405 [Autoscaler] Allow users to set the names for security groups created by ray
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/aws/example-security-group.yaml
  python/ray/autoscaler/ray-schema.json
  python/ray/tests/aws/test_autoscaler_aws.py
  python/ray/tests/aws/utils/constants.py
  python/ray/tests/test_autoscaler_yaml.py
Labels: @tests-ok

#11449 [RLlib] Fix PyTorch A3C / A2C loss function using mixed reduced sum / mean
  rllib/agents/a3c/a3c_torch_policy.py
Labels: @author-action-required

#11543 [autoscaler] Removed .cleanup() from NodeProvider and commands.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/node_provider.py
Labels: @tests-ok

#11421 [Serve] Update front page of serve doc
  doc/source/serve/index.rst
  python/ray/serve/examples/doc/quickstart_class.py
  python/ray/serve/examples/doc/quickstart_function.py
Labels: @tests-ok

#11573 [tune] fix pbt ptl example
  python/ray/tune/examples/mnist_pytorch_lightning.py
Labels: @tests-ok

#11577 Remove crashing assert in actor creation for old scheduler
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#11595 [tune] use isinstance instead of type for TBXLogger
  python/ray/tune/logger.py
Labels: @tests-ok

#11604 [core] Better error message for named actor not found
  src/ray/core_worker/core_worker.cc
Labels: @tests-ok

#11622 [Hotfix] Pin Pydantic Version
  doc/requirements-doc.txt
  python/ray/serve/tests/test_standalone.py
  python/requirements.txt
  python/setup.py
Labels: @tests-ok

#11609 [RLlib] Minor fixes (torch GPU bugs + some cleanup).
  python/ray/cloudpickle/cloudpickle_fast.py
  rllib/agents/dqn/dqn_torch_model.py
  rllib/agents/dqn/dqn_torch_policy.py
  rllib/agents/impala/tests/test_impala.py
  rllib/agents/impala/vtrace_tf_policy.py
  rllib/agents/impala/vtrace_torch_policy.py
  rllib/agents/pg/tests/test_pg.py
  rllib/agents/ppo/appo_tf_policy.py
  rllib/agents/ppo/appo_torch_policy.py
  rllib/agents/ppo/tests/test_appo.py
  rllib/agents/qmix/qmix_policy.py
  rllib/agents/sac/tests/test_sac.py
  rllib/contrib/maddpg/maddpg.py
  rllib/contrib/maddpg/maddpg_policy.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/models/catalog.py
  rllib/models/modelv2.py
  rllib/models/torch/modules/noisy_layer.py
  rllib/models/torch/torch_action_dist.py
  rllib/policy/tf_policy.py
  rllib/tests/data/cartpole/large.json
  rllib/tests/test_local.py
  rllib/tests/test_multi_agent_pendulum.py
  rllib/tests/test_rollout.py
  rllib/tests/test_rollout_worker.py
  rllib/utils/test_utils.py
Labels: @author-action-required

#11391 [Dashboard] Optimize dashboard datacenter
  dashboard/consts.py
  dashboard/datacenter.py
  dashboard/head.py
  dashboard/memory_utils.py
  dashboard/modules/log/log_head.py
  dashboard/modules/stats_collector/stats_collector_head.py
  dashboard/modules/stats_collector/tests/test_stats_collector.py
  dashboard/tests/test_dashboard.py
  dashboard/utils.py
  python/build-wheel-macos.sh
  python/ray/dashboard/dashboard.py
  python/ray/dashboard/node_stats.py
  python/ray/tests/test_metrics.py
  python/ray/tests/test_multi_tenancy.py
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
Labels: @tests-ok, dashboard

#11635 [new scheduler] Pass test_basic and add CI builds with flag on
  .bazelrc
  .travis.yml
  python/ray/memory_monitor.py
  python/ray/tests/BUILD
  src/ray/common/ray_config_def.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @tests-ok

#11476 [RLLIB] Wait for remote_workers to finish closing environments before…
  rllib/evaluation/worker_set.py
Labels: @author-action-required

#11623 [releng]: Quiet Docker Push (and explain why)
  ci/travis/build-docker-images.py
Labels: @tests-ok, P0, release-blocker

#11619 [Core] Add option to override environment variables for tasks and actors
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/remote_function.py
  python/ray/tests/test_advanced_3.py
  python/ray/worker.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/common.proto
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: @tests-ok

#11586 [New scheduler] Deflake test heartbeat
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#11650 [Dashboard] Fix null gpu utilization
  dashboard/client/src/api.ts
  dashboard/client/src/pages/dashboard/logical-view/ActorDetailsPane.tsx
  dashboard/client/src/pages/dashboard/node-info/features/GPU.tsx
  dashboard/client/src/pages/dashboard/node-info/features/GRAM.tsx
Labels: @tests-ok

#11654 [Dashboard] Make Infeasible Actor UX Less Scary
  dashboard/client/src/common/LabeledDatum.tsx
  dashboard/client/src/pages/dashboard/logical-view/ActorClassGroup.tsx
  dashboard/client/src/pages/dashboard/logical-view/ActorDetailsPane.tsx
Labels: @tests-ok, dashboard

#11694 [release] Do not tag docker latest on release builds
  ci/travis/build-docker-images.py
Labels: @tests-ok

#11693 Disable validation of cluster config on the cluster to allow for cluster configs with new properties.
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/tests/test_autoscaler.py
Labels: @tests-ok, P0, release-blocker

#11716 [autoscaler/k8s] [minor] Kubernetes rsync verbosity fixed
  python/ray/autoscaler/_private/command_runner.py
Labels: @tests-ok

#11714 [autoscaler] fix the autoscaling bug for continuously launching failed nodes
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#11379 [Object Spilling] Initial Iteration of S3 adapter.
  python/ray/external_storage.py
  python/ray/parameter.py
  python/ray/tests/test_object_spilling.py
  python/requirements.txt
Labels: @author-action-required

#11516 [Core]Fix get workrer table bug
  python/ray/__init__.py
  python/ray/includes/global_state_accessor.pxi
  python/ray/state.py
  python/ray/tests/test_global_state.py
  src/ray/core_worker/core_worker.cc
Labels: @tests-ok
