Repository ray-project/ray, pull requests merged in 2020-12, with the labels that each got.

#12465 [autoscaler] Try to improve the request_resources() documentation
  python/ray/autoscaler/sdk.py
Labels: @author-action-required

#12410 [Dashboard][Bug] Fix duplicate node total rows in dashboard
  dashboard/client/src/pages/dashboard/node-info/NodeInfo.tsx
  dashboard/tests/test_dashboard.py
Labels: @tests-ok

#12101 [Logging] Log rotation on all components
  dashboard/agent.py
  dashboard/consts.py
  dashboard/dashboard.py
  python/ray/_private/services.py
  python/ray/log_monitor.py
  python/ray/monitor.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/ray_logging.py
  python/ray/tests/test_tempfile.py
Labels: @author-action-required

#12449 [RLlib] Attention Net prep PR #2: Smaller cleanups.
  rllib/evaluation/collectors/sample_collector.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/policy/episode_env_aware_policy.py
  rllib/examples/policy/rock_paper_scissors_dummies.py
  rllib/models/modelv2.py
  rllib/models/tf/recurrent_net.py
  rllib/models/torch/recurrent_net.py
  rllib/policy/policy.py
  rllib/policy/view_requirement.py
Labels: @author-action-required, @tests-ok

#12442 [RLlib] Fix setup-dev.py error when creating a softlink for new_dashboard.
  python/ray/setup-dev.py
  rllib/policy/tf_policy.py
Labels: @tests-ok

#12235 [Core]Remove checkpoint table
  java/api/src/main/java/io/ray/api/Checkpointable.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GcsClient.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GlobalStateAccessor.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskExecutor.java
  java/runtime/src/main/java/io/ray/runtime/task/NativeTaskExecutor.java
  java/runtime/src/main/java/io/ray/runtime/task/TaskExecutor.java
  java/test/src/main/java/io/ray/test/ActorRestartTest.java
  java/test/src/main/java/io/ray/test/ExitActorTest.java
  python/ray/__init__.py
  python/ray/_raylet.pyx
  python/ray/gcs_utils.py
  python/ray/includes/libcoreworker.pxd
  python/ray/includes/unique_ids.pxd
  python/ray/includes/unique_ids.pxi
  python/ray/state.py
  python/ray/tests/test_runtime_context.py
  python/ray/worker.py
  src/ray/common/id_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskExecutor.cc
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/global_state_accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/redis_accessor.cc
  src/ray/gcs/redis_accessor.h
  src/ray/gcs/redis_gcs_client.cc
  src/ray/gcs/redis_gcs_client.h
  src/ray/gcs/tables.cc
  src/ray/gcs/tables.h
  src/ray/gcs/test/redis_actor_info_accessor_test.cc
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/raylet/actor_registration.cc
  src/ray/raylet/actor_registration.h
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: @author-action-required

#12388 [ray_client] actors v0
  python/ray/actor.py
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/api.py
  python/ray/experimental/client/client_app.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/server/server.py
  python/ray/experimental/client/worker.py
  python/ray/function_manager.py
  python/ray/signature.py
  python/ray/tests/test_experimental_client.py
  python/ray/util/inspect.py
  python/ray/utils.py
  python/ray/worker.py
  src/ray/protobuf/ray_client.proto
Labels: @author-action-required

#12548 Fix race condition between failure detection and references going out of scope
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/object_recovery_manager.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
Labels: @author-action-required

#12559 [Hotfix] Pin llvmlite for windows build
  python/requirements.txt
Labels: @tests-ok

#12555 [Windows] Fix windows build
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @tests-ok

#12186 [core] Move out-of-memory handling into the plasma store and support async object creation
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_object_manager.py
  python/ray/tests/test_object_spilling.py
  python/ray/tests/test_reference_counting.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/plasma/create_request_queue.cc
  src/ray/object_manager/plasma/create_request_queue.h
  src/ray/object_manager/plasma/plasma.fbs
  src/ray/object_manager/plasma/plasma.h
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/protocol.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/plasma/store_runner.cc
  src/ray/object_manager/plasma/store_runner.h
  src/ray/object_manager/test/create_request_queue_test.cc
  src/ray/object_manager/test/object_manager_stress_test.cc
  src/ray/object_manager/test/object_manager_test.cc
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/raylet.h
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#12584 Disable flaky test test_delete_objects_multi_node
  python/ray/tests/test_object_spilling.py
Labels: @author-action-required

#12425 [tune] fix Tensorboard file descriptor leak
  python/ray/tune/logger.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
Labels: @tests-ok

#12417 [autoscaler/k8s] Use ray node's HOME in Kubernetes command runner.
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/command_runner.py
Labels: @tests-ok

#12512 [autoscaler] Fix worker capping fifo test in new scheduler
  python/ray/tests/test_multi_tenancy.py
Labels: @author-action-required

#10762 [Java] Simplify `Ray.init()` by invoking `ray start` internally
  doc/source/installation.rst
  java/BUILD.bazel
  java/api/src/main/java/io/ray/api/runtimecontext/RuntimeContext.java
  java/runtime/pom.xml
  java/runtime/src/main/java/io/ray/runtime/DefaultRayRuntimeFactory.java
  java/runtime/src/main/java/io/ray/runtime/RayDevRuntime.java
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/context/RuntimeContextImpl.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GcsClientOptions.java
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  java/runtime/src/main/java/io/ray/runtime/util/BinaryFileUtil.java
  java/runtime/src/main/java/io/ray/runtime/util/JniUtils.java
  java/runtime/src/main/resources/ray.default.conf
  java/runtime/src/test/java/io/ray/runtime/config/RayConfigTest.java
  java/test.sh
  java/test/src/main/java/io/ray/test/BaseMultiLanguageTest.java
  java/test/src/main/java/io/ray/test/BaseTest.java
  java/test/src/main/java/io/ray/test/CrossLanguageInvocationTest.java
  java/test/src/main/java/io/ray/test/GcsClientTest.java
  java/test/src/main/java/io/ray/test/GlobalGcTest.java
  java/test/src/main/java/io/ray/test/MultiLanguageClusterTest.java
  java/test/src/main/java/io/ray/test/RayAlterSuiteListener.java
  java/test/src/main/java/io/ray/test/RaySerializerTest.java
  java/test/src/main/java/io/ray/test/RayletConfigTest.java
  java/test/src/main/java/io/ray/test/RedisPasswordTest.java
  java/test/src/main/java/io/ray/test/ReferenceCountingTest.java
  java/test/src/main/java/io/ray/test/ResourcesManagementTest.java
  java/test/src/main/java/io/ray/test/RuntimeContextTest.java
  python/ray/_private/services.py
  python/ray/scripts/scripts.py
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.h
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.h
  streaming/java/streaming-api/src/main/java/io/ray/streaming/api/context/ClusterStarter.java
  streaming/java/streaming-api/src/main/java/io/ray/streaming/api/context/StreamingContext.java
  streaming/java/streaming-api/src/main/java/io/ray/streaming/jobgraph/JobGraph.java
  streaming/java/streaming-runtime/src/main/java/io/ray/streaming/runtime/transfer/TransferHandler.java
  streaming/java/streaming-runtime/src/main/java/io/ray/streaming/runtime/util/EnvUtil.java
  streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/streamingqueue/StreamingQueueTest.java
Labels: java

#12563 [SGD] Fixes TorchTrainer scales up
  python/ray/util/sgd/tests/test_torch_failure.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/worker_group.py
Labels: @tests-ok

#12571 [tune] verbosity refactor second attempt
  python/ray/tune/progress_reporter.py
  python/ray/tune/tests/test_progress_reporter.py
  python/ray/tune/trial.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
  python/ray/tune/utils/callback.py
  python/ray/tune/utils/log.py
  rllib/train.py
Labels: @tests-ok

#12572 [tune] Add xgboost_ray integration
  python/ray/tune/integration/xgboost.py
Labels: @tests-ok

#12075 Ray debugger stepping between tasks
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/native_task_submitter.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/ray_constants.py
  python/ray/remote_function.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_ray_debugger.py
  python/ray/util/rpdb.py
  python/ray/worker.py
  python/requirements.txt
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/task_dependency_manager_test.cc
  streaming/src/test/mock_actor.cc
Labels: @author-action-required

#12450 [RLlib] Attention Net prep PR #3.
  rllib/agents/ppo/appo_tf_policy.py
  rllib/agents/ppo/ppo.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/qmix/model.py
  rllib/agents/qmix/qmix_policy.py
  rllib/contrib/maddpg/maddpg_policy.py
  rllib/evaluation/collectors/sample_collector.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/evaluation/worker_set.py
  rllib/examples/policy/episode_env_aware_policy.py
  rllib/examples/policy/rock_paper_scissors_dummies.py
  rllib/examples/two_trainer_workflow.py
  rllib/models/modelv2.py
  rllib/models/tf/recurrent_net.py
  rllib/models/torch/recurrent_net.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/policy/tests/test_compute_log_likelihoods.py
  rllib/policy/tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy_template.py
  rllib/policy/view_requirement.py
  rllib/tests/test_execution.py
  rllib/tests/test_multi_agent_env.py
  rllib/utils/exploration/tests/test_parameter_noise.py
  rllib/utils/typing.py
Labels: @author-action-required, @tests-ok

#12621 [RLlib] Fix JAX import bug.
  rllib/utils/framework.py
  rllib/utils/test_utils.py
Labels: @tests-ok

#12594 [Doc] Placement group doc small update
  doc/examples/placement-group.rst
Labels: release-blocker

#12655 [Fix-Err-msg] Fix that add_worker fails when driver exits.
  python/ray/worker.py
Labels: release-blocker

#12660 [Dashboard][Bugfix] Fix bug in display of worker logs and errors in Dashboard
  dashboard/modules/stats_collector/stats_collector_head.py
  dashboard/modules/stats_collector/tests/test_stats_collector.py
Labels: @tests-ok

#12588 [Logging] Fix log monitor issue
  dashboard/agent.py
  dashboard/dashboard.py
  python/ray/log_monitor.py
Labels: @author-action-required, release-blocker

#12557 [new scheduler] Always spill back to a feasible node if the local node is not feasible
  python/ray/tests/test_reconstruction.py
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @author-action-required

#12420 [RLlib] Batch-size for truncate_episode batch_mode should be confgurable in agent-steps (rather than env-steps), if needed.
  rllib/BUILD
  rllib/agents/a3c/a2c.py
  rllib/agents/impala/impala.py
  rllib/agents/marwil/marwil.py
  rllib/agents/ppo/ppo.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/qmix/qmix.py
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
  rllib/contrib/alpha_zero/core/alpha_zero_trainer.py
  rllib/evaluation/collectors/sample_collector.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/__init__.py
  rllib/evaluation/tests/test_rollout_worker.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/evaluation/worker_set.py
  rllib/examples/env/mock_env.py
  rllib/examples/env/multi_agent.py
  rllib/examples/two_trainer_workflow.py
  rllib/execution/rollout_ops.py
  rllib/execution/tree_agg.py
  rllib/policy/sample_batch.py
  rllib/tests/test_external_env.py
  rllib/tests/test_external_multi_agent_env.py
  rllib/tests/test_multi_agent_env.py
  rllib/tests/test_perf.py
Labels: @author-action-required, @tests-ok

#12661 [hotfix][autoscaler] Request resources refactor2
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: P0

#12585 [ray_client] Passing actors to actors
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/api.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/server/server.py
  python/ray/experimental/client/worker.py
  python/ray/tests/test_experimental_client.py
Labels: @tests-ok

#12682 [RLlib] Tf-eager policy bug fix: Duplicate model call in compute_gradients.
  rllib/policy/eager_tf_policy.py
Labels: @author-action-required

#12573 Fix race condition between failure detection and references going out of scope
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/object_recovery_manager.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
Labels: @author-action-required

#12256 Fix dashboard agent check ppid is raylet pid
  dashboard/agent.py
  dashboard/tests/test_dashboard.py
  src/ray/raylet/agent_manager.cc
Labels: @author-action-required

#12518 [New scheduler] Cluster Resource Scheduler dynamic resources (for placement groups)
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
Labels: @tests-ok

#12574 [docker] Make Ray-ml more compatible
  docker/ray-ml/Dockerfile
Labels: @tests-ok

#10573 [Multi-tenancy] Delete flag `enable_multi_tenancy` and remove old code path
  doc/source/cluster/index.rst
  doc/source/configure.rst
  doc/source/cross-language.rst
  doc/source/starting-ray.rst
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  java/test.sh
  java/test/src/main/java/io/ray/test/FailureTest.java
  java/test/src/main/java/io/ray/test/JobConfigTest.java
  java/test/src/main/java/io/ray/test/KillActorTest.java
  java/test/src/main/java/io/ray/test/MultiDriverTest.java
  python/ray/_private/services.py
  python/ray/autoscaler/aws/example-java.yaml
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/node.py
  python/ray/parameter.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_cross_language.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
  src/ray/common/ray_config_def.h
  src/ray/common/test_util.cc
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/object_manager_integration_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  streaming/java/streaming-api/src/main/java/io/ray/streaming/api/context/ClusterStarter.java
  streaming/java/streaming-runtime/src/test/java/io/ray/streaming/runtime/streamingqueue/StreamingQueueTest.java
  streaming/python/examples/wordcount.py
  streaming/python/tests/test_failover.py
  streaming/python/tests/test_hybrid_stream.py
  streaming/python/tests/test_stream.py
  streaming/python/tests/test_union_stream.py
  streaming/python/tests/test_word_count.py
Labels: @author-action-required

#12577 [serve] Create FutureResults from ControllerAPI
  python/ray/serve/BUILD
  python/ray/serve/api.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_controller.py
Labels: @tests-ok

#12578 [Utils] Add Queue async and batch methods
  python/ray/tests/test_queue.py
  python/ray/util/queue.py
Labels: @author-action-required

#12767 Remove unused ci/performance_tests
  ci/performance_tests/README.rst
  ci/performance_tests/test_performance.py
Labels: @author-action-required

#12736 [ray_client] Include multiple facets of the Ray API
  python/ray/exceptions.py
  python/ray/experimental/client/api.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/server/server.py
  python/ray/experimental/client/worker.py
  python/ray/tests/BUILD
  python/ray/tests/test_experimental_client.py
  python/ray/tests/test_experimental_client_metadata.py
  python/ray/tests/test_experimental_client_terminate.py
  src/ray/protobuf/ray_client.proto
Labels: @tests-ok

#12711 [new scheduler] Allocate resources for spilled back task to a local view of the remote node
  python/ray/tests/test_advanced_3.py
  src/ray/protobuf/gcs.proto
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @author-action-required

#12746 [Streaming] Add more documents.
  streaming/README.md
  streaming/README.rst
  streaming/assets/architecture.jpg
Labels: streaming

#12693 Fix exit_actor in asyncio mode
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/tests/test_asyncio.py
Labels: @author-action-required

#12730 Add comments to clarify purpose of new scheduler queues
  doc/source/cluster/autoscaling.rst
  src/ray/raylet/scheduling/cluster_task_manager.h
Labels: @tests-ok

#12335 [Object Manager] Pull Manager refactor
  BUILD.bazel
  src/ray/common/ray_config_def.h
  src/ray/object_manager/common.h
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/raylet/main.cc
Labels: @tests-ok

#12807 Clarify docs for atexit behavior when using ray.kill
  python/ray/actor.py
  python/ray/worker.py
Labels: @author-action-required

#12803 Hold GIL while submitting (actor) tasks
  python/ray/_raylet.pyx
Labels: @author-action-required

#12586 [New scheduler] Fix test_global_state
  python/ray/tests/test_global_state.py
  src/ray/common/task/task.cc
  src/ray/common/task/task.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @author-action-required

#12776 [tune] upgrade gpytorch, bump default pytorch to 1.7.0
  .travis.yml
  ci/travis/install-dependencies.sh
  python/ray/util/sgd/torch/examples/dcgan.py
  python/requirements_tune.txt
Labels: @tests-ok

#12538 [Placement Group] Refactor pg resource constrain in node manager
  BUILD.bazel
  python/ray/tests/test_placement_group.py
  src/ray/common/bundle_spec.cc
  src/ray/common/bundle_spec.h
  src/ray/common/task/scheduling_resources.cc
  src/ray/common/task/scheduling_resources.h
  src/ray/common/task/scheduling_resources_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/placement_group_resource_manager.h
  src/ray/raylet/placement_group_resource_manager_test.cc
  src/ray/raylet/scheduling_policy.cc
  src/ray/raylet/scheduling_policy.h
Labels: @tests-ok

#12666 [Dashboard][Bugfix] Fix GPU List Bug
  dashboard/datacenter.py
  dashboard/modules/logical_view/tests/test_logical_view_head.py
Labels: @tests-ok

#12098 Ray cluster CRD and example CR + multi-ray-cluster operator
  ci/travis/format.sh
  doc/source/cluster/autoscaling.rst
  doc/source/cluster/k8s-operator.rst
  doc/source/cluster/kubernetes.rst
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/kubernetes/__init__.py
  python/ray/autoscaler/_private/kubernetes/config.py
  python/ray/autoscaler/_private/kubernetes/node_provider.py
  python/ray/autoscaler/_private/util.py
  python/ray/autoscaler/kubernetes/operator_configs/cluster_crd.yaml
  python/ray/autoscaler/kubernetes/operator_configs/example_cluster.yaml
  python/ray/autoscaler/kubernetes/operator_configs/example_cluster2.yaml
  python/ray/autoscaler/kubernetes/operator_configs/operator.yaml
  python/ray/autoscaler/kubernetes/operator_configs/test_cluster_config.yaml
  python/ray/autoscaler/ray-schema.json
  python/ray/monitor.py
  python/ray/operator.py
  python/ray/operator/__init__.py
  python/ray/operator/operator.py
  python/ray/operator/operator_utils.py
  python/setup.py
Labels: @tests-ok

#12792 [GCS]Tell dead nodes to commit suicide
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#12839 [Logging] Use file handle instead of log rotation file-like object
  python/ray/ray_logging.py
  python/ray/workers/default_worker.py
Labels: @author-action-required

#11768 [Dashboard] Add dashboard multi-node churn test
  dashboard/BUILD
  dashboard/modules/stats_collector/tests/test_stats_collector.py
  dashboard/tests/test_dashboard.py
Labels: @tests-ok

#12811 [Serve] Support basic Starlette response types
  doc/requirements-doc.txt
  doc/source/serve/index.rst
  doc/source/serve/key-concepts.rst
  python/ray/serve/api.py
  python/ray/serve/http_proxy.py
  python/ray/serve/http_util.py
  python/ray/serve/tests/test_api.py
  python/requirements.txt
  python/setup.py
Labels: @tests-ok

#12860 [Metrics] Call GetMeasureDoubleByName to prevent override
  python/ray/tests/test_metrics_agent.py
  src/ray/stats/metric.cc
Labels: @author-action-required

#12867 Check for raylet PID as ppid in dashboard agent fate-sharing
  dashboard/agent.py
  dashboard/tests/test_dashboard.py
  src/ray/raylet/agent_manager.cc
Labels: @author-action-required

#12882 [Core] Fix for RLIMIT patch for Big Sur
  python/ray/worker.py
Labels: P0, release-blocker

#12857 [New scheduler] Object spilling
  python/ray/tests/test_object_spilling.py
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#12790 [tune] enable `points_to_eval` for all search algorithms
  python/ray/tune/examples/dragonfly_example.py
  python/ray/tune/examples/skopt_example.py
  python/ray/tune/suggest/ax.py
  python/ray/tune/suggest/bayesopt.py
  python/ray/tune/suggest/bohb.py
  python/ray/tune/suggest/dragonfly.py
  python/ray/tune/suggest/hyperopt.py
  python/ray/tune/suggest/nevergrad.py
  python/ray/tune/suggest/optuna.py
  python/ray/tune/suggest/skopt.py
  python/ray/tune/suggest/zoopt.py
  python/ray/tune/tests/test_sample.py
Labels: @tests-ok

#12876 [core] recover startup logs
  python/ray/node.py
Labels: release-blocker

#12896 Better message for too little /dev/shm memory
  python/ray/_private/services.py
Labels: fix-error-msg

#12907 Fix pull manager retry
  python/ray/tests/test_object_manager.py
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
Labels: @author-action-required

#12927 [SGD] Disable Elastic Training by default when using with Tune
  python/ray/util/sgd/torch/torch_trainer.py
Labels: @tests-ok

#12862 Fix continue for debugger
  python/ray/tests/test_ray_debugger.py
  python/ray/util/rpdb.py
Labels: @tests-ok

#12738 [New Scheduler] Fix test_failure.py by supporting infeasible tasks
  python/ray/tests/test_failure.py
  src/ray/object_manager/plasma/store.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @author-action-required

#12925 [K8s] Retry getting home directory in command runner.
  python/ray/autoscaler/_private/command_runner.py
Labels: @tests-ok

#12942 [k8s] Read gpu resources properly
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/kubernetes/config.py
Labels: @tests-ok

#12877 [tune] Fix and enable SigOpt tests
  .travis.yml
  python/ray/tune/BUILD
  python/ray/tune/examples/sigopt_example.py
  python/ray/tune/examples/sigopt_multi_objective_example.py
  python/ray/tune/examples/sigopt_prior_beliefs_example.py
  python/ray/tune/suggest/bayesopt.py
  python/ray/tune/suggest/nevergrad.py
  python/ray/tune/suggest/sigopt.py
  python/ray/tune/suggest/suggestion.py
  python/ray/tune/suggest/zoopt.py
  python/ray/tune/tests/test_tune_restore.py
Labels: @tests-ok

#12818 [ray_client]: Implement object retain/release and Data Streaming API
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/api.py
  python/ray/experimental/client/client_pickler.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/dataclient.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/server/dataservicer.py
  python/ray/experimental/client/server/server.py
  python/ray/experimental/client/server/server_pickler.py
  python/ray/experimental/client/server/server_stubs.py
  python/ray/experimental/client/worker.py
  python/ray/tests/BUILD
  python/ray/tests/test_experimental_client.py
  python/ray/tests/test_experimental_client_references.py
  src/ray/protobuf/ray_client.proto
Labels: @author-action-required

#12968 [Java] Fix output parsing in RunManager
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  python/ray/_private/services.py
  src/ray/gcs/gcs_client/service_based_gcs_client.cc
Labels: java

#12952 [Autoscaler/Core] Remove autoscaler spam
  python/ray/autoscaler/_private/load_metrics.py
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/test/gcs_node_manager_test.cc
Labels: @tests-ok

#12477 [SGD] Fix process group timeout units
  python/ray/util/sgd/torch/constants.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/worker_group.py
Labels: @author-action-required

#12932 [Queue] Add options and shutdown to Queue
  python/ray/tests/test_queue.py
  python/ray/util/queue.py
Labels: @tests-ok

#12991 Fix scheduling_resources comment errors
  src/ray/common/task/scheduling_resources.cc
  src/ray/common/task/scheduling_resources.h
Labels: @author-action-required

#12537 [serve] Refactor to full control loop design
  python/ray/serve/controller.py
Labels: @author-action-required

#12964 [ray_client] Integrate with test_basic, test_basic_2 and test_actor
  .travis.yml
  bazel/python.bzl
  python/ray/experimental/client/__init__.py
  python/ray/experimental/client/client_pickler.py
  python/ray/experimental/client/common.py
  python/ray/experimental/client/dataclient.py
  python/ray/experimental/client/server/core_ray_api.py
  python/ray/experimental/client/server/server.py
  python/ray/experimental/client/server/server_pickler.py
  python/ray/experimental/client/server/server_stubs.py
  python/ray/experimental/client/worker.py
  python/ray/test_utils.py
  python/ray/tests/BUILD
  python/ray/tests/client_test_utils.py
  python/ray/tests/conftest.py
  python/ray/tests/test_actor.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_experimental_client.py
  python/ray/tests/test_experimental_client_terminate.py
  src/ray/protobuf/ray_client.proto
Labels: @tests-ok

#12980 [autoscaler] Do not count head node with min_workers constraint.
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#12753 [RLlib] Attention Nets: tf
  rllib/BUILD
  rllib/agents/callbacks.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/postprocessing.py
  rllib/examples/attention_net.py
  rllib/examples/cartpole_lstm.py
  rllib/models/modelv2.py
  rllib/models/tests/test_attention_nets.py
  rllib/models/tf/attention_net.py
  rllib/models/tf/layers/__init__.py
  rllib/models/tf/layers/relative_multi_head_attention.py
  rllib/models/tf/layers/skip_connection.py
  rllib/models/torch/modules/skip_connection.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/rnn_sequencing.py
  rllib/policy/sample_batch.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
  rllib/policy/view_requirement.py
  rllib/tests/test_attention_net_learning.py
  rllib/tests/test_lstm.py
  rllib/utils/sgd.py
  rllib/utils/typing.py
Labels: @author-action-required

#13008 [autoscaler] Fixes max_workers bug.
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#12852 [Serve] Migrate from Flask.Request to Starlette Request
  doc/source/serve/faq.rst
  doc/source/serve/index.rst
  doc/source/serve/key-concepts.rst
  doc/source/serve/package-ref.rst
  doc/source/serve/tutorials/batch.rst
  python/ray/serve/examples/doc/quickstart_class.py
  python/ray/serve/examples/doc/quickstart_function.py
  python/ray/serve/examples/doc/snippet_model_composition.py
  python/ray/serve/examples/doc/tutorial_batch.py
  python/ray/serve/examples/doc/tutorial_deploy.py
  python/ray/serve/examples/doc/tutorial_pytorch.py
  python/ray/serve/examples/doc/tutorial_sklearn.py
  python/ray/serve/examples/doc/tutorial_tensorflow.py
  python/ray/serve/examples/echo.py
  python/ray/serve/examples/echo_actor.py
  python/ray/serve/examples/echo_actor_batch.py
  python/ray/serve/examples/echo_batching.py
  python/ray/serve/examples/echo_full.py
  python/ray/serve/handle.py
  python/ray/serve/http_util.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_backend_worker.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_persistence.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/utils.py
Labels: @tests-ok

#12990 Revert "Revert "Increase the number of unique bits for actors to avoi…
  dashboard/modules/stats_collector/tests/test_stats_collector.py
  dashboard/tests/test_memory_utils.py
  java/api/src/main/java/io/ray/api/id/ActorId.java
  java/api/src/main/java/io/ray/api/id/ObjectId.java
  java/api/src/main/java/io/ray/api/id/UniqueId.java
  java/runtime/src/test/java/io/ray/runtime/UniqueIdTest.java
  python/ray/exceptions.py
  python/ray/includes/function_descriptor.pxi
  python/ray/includes/unique_ids.pxi
  python/ray/log_monitor.py
  python/ray/ray_constants.py
  python/ray/serialization.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_multi_node.py
  python/ray/utils.py
  python/ray/worker.py
  src/ray/common/constants.h
  src/ray/common/id.h
  src/ray/core_worker/actor_manager.cc
  src/ray/gcs/redis_context.cc
  src/ray/object_manager/test/object_manager_test.cc
Labels: do-not-merge

#12029 [RLlib] Attention nets PyTorch support and cleanup (using traj. view API).
  rllib/BUILD
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/attention_net.py
  rllib/examples/custom_metrics_and_callbacks.py
  rllib/examples/env/debug_counter_env.py
  rllib/examples/models/centralized_critic_models.py
  rllib/models/torch/attention_net.py
  rllib/models/torch/modules/gru_gate.py
  rllib/models/torch/modules/relative_multi_head_attention.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy.py
Labels: @author-action-required

#13024 [core] Pull Manager exponential backoff
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/pull_manager_test.cc
Labels: @tests-ok

#12984 [release tests] test_many_tasks fix
  release/stress_tests/autoscaler-cluster.yaml
  release/stress_tests/workloads/test_many_tasks.py
Labels: @tests-ok

#12971 [Serve] Handle Bug Fixes
  doc/source/serve/advanced.rst
  python/ray/serve/api.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_handle.py
Labels: @author-action-required

#12913 [Dashboard] Add GET /logical/actors API
  dashboard/datacenter.py
  dashboard/modules/logical_view/logical_view_head.py
  dashboard/modules/logical_view/tests/test_logical_view_head.py
  dashboard/modules/stats_collector/stats_collector_head.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
Labels: @tests-ok, dashboard

#13046 [joblib] Fix flaky joblib test.
  python/ray/tests/mnist_784_100_samples.pkl
  python/ray/tests/test_joblib.py
Labels: @tests-ok

#13048 [core][new scheduler] Move tasks from ready to dispatch to waiting on argument eviction
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/task_dependency_manager.cc
  src/ray/raylet/task_dependency_manager.h
Labels: @author-action-required

#12772 [Autoscaler] New output log format
  dashboard/modules/reporter/reporter_head.py
  dashboard/tests/test_dashboard.py
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/legacy_info_string.py
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/autoscaler/_private/util.py
  python/ray/monitor.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#13006 Refactor TaskDependencyManager, allow passing bundles of objects to ObjectManager
  BUILD.bazel
  src/ray/common/common_protocol.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/object_manager_stress_test.cc
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/raylet/dependency_manager.cc
  src/ray/raylet/dependency_manager.h
  src/ray/raylet/dependency_manager_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/task_dependency_manager.cc
  src/ray/raylet/task_dependency_manager.h
  src/ray/raylet/task_dependency_manager_test.cc
Labels: @author-action-required

#13058 [C++ API] Added reference counting to ObjectRef
  cpp/include/ray/api/object_ref.h
  cpp/src/ray/test/cluster/cluster_mode_test.cc
Labels: @tests-ok

#13070 [Core] Remove cuda support in plasma store
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/plasma.h
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
Labels: @tests-ok

#13080 [Core] Remote outdated external store
  BUILD.bazel
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/plasma/external_store.cc
  src/ray/object_manager/plasma/external_store.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/plasma/store_runner.cc
  src/ray/object_manager/plasma/store_runner.h
  src/ray/plasma/store_exec.cc
Labels: @tests-ok

#13083 [RLlib] Preprocessor fixes (multi-discrete) and tests.
  rllib/BUILD
  rllib/models/modelv2.py
  rllib/models/preprocessors.py
  rllib/models/tests/test_preprocessors.py
  rllib/policy/torch_policy.py
  rllib/tests/test_catalog.py
Labels: @tests-ok

#13064 [RLlib] BC/MARWIL/recurrent nets minor cleanups and bug fixes.
  rllib/agents/dreamer/dreamer.py
  rllib/agents/impala/tests/test_impala.py
  rllib/agents/marwil/bc.py
  rllib/agents/marwil/marwil_tf_policy.py
  rllib/agents/marwil/marwil_torch_policy.py
  rllib/agents/marwil/tests/test_bc.py
  rllib/agents/ppo/ppo.py
  rllib/agents/ppo/tests/test_ddppo.py
  rllib/agents/trainer.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/custom_keras_model.py
  rllib/examples/rollout_worker_custom_workflow.py
  rllib/models/catalog.py
  rllib/models/preprocessors.py
  rllib/models/tf/recurrent_net.py
  rllib/models/torch/recurrent_net.py
  rllib/offline/io_context.py
  rllib/offline/json_reader.py
  rllib/offline/json_writer.py
  rllib/policy/sample_batch.py
  rllib/tests/test_execution.py
  rllib/tests/test_model_imports.py
  rllib/tests/test_nested_observation_spaces.py
Labels: @tests-ok

#13032 [Serve] [Doc] Front page update
  doc/source/serve/advanced.rst
  doc/source/serve/index.rst
  doc/source/serve/package-ref.rst
  python/ray/serve/examples/doc/quickstart_class.py
  python/ray/serve/examples/doc/quickstart_function.py
Labels: @tests-ok

#13019 Deprecate experimental / dynamic resources
  doc/source/advanced.rst
  python/ray/experimental/dynamic_resources.py
Labels: do-not-merge

#12523 [Serve] Use ServeHandle in HTTP proxy
  python/ray/serve/api.py
  python/ray/serve/backend_worker.py
  python/ray/serve/context.py
  python/ray/serve/handle.py
  python/ray/serve/http_proxy.py
  python/ray/serve/router.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_backend_worker.py
  python/ray/serve/tests/test_router.py
  python/ray/serve/utils.py
Labels: @tests-ok

#13089 [autoscaler] Make placement groups bypass max launch limit
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#13096 Serve metrics docs
  doc/source/serve/advanced.rst
  doc/source/serve/package-ref.rst
  python/ray/serve/__init__.py
  python/ray/serve/api.py
  python/ray/serve/backend_worker.py
  python/ray/serve/examples/doc/snippet_custom_metric.py
  python/ray/serve/examples/doc/snippet_metrics.py
  python/ray/serve/http_proxy.py
  python/ray/serve/router.py
  python/ray/serve/utils.py
Labels: @tests-ok

#13097 [RLlib] run_regression_tests.py: --framework flag (instead of --torch).
  rllib/BUILD
  rllib/tests/run_regression_tests.py
Labels: @tests-ok

#13067 [docs] Fix Sphinx.add_stylesheet deprecation
  doc/source/conf.py
Labels: @tests-ok

#12718 [RLlib] Trajectory view API docs.
  doc/source/images/rllib-batch-modes.svg
  doc/source/images/rllib-sample-collection.svg
  doc/source/images/rllib-trajectory-view-example.svg
  doc/source/index.rst
  doc/source/rllib-algorithms.rst
  doc/source/rllib-env.rst
  doc/source/rllib-models.rst
  doc/source/rllib-sample-collection.rst
  doc/source/rllib-toc.rst
  doc/source/rllib.rst
  rllib/agents/trainer.py
  rllib/evaluation/collectors/sample_collector.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/episode.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/policy/episode_env_aware_policy.py
  rllib/models/modelv2.py
  rllib/models/tf/attention_net.py
  rllib/models/tf/recurrent_net.py
  rllib/models/torch/attention_net.py
  rllib/models/torch/recurrent_net.py
  rllib/offline/input_reader.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/policy_template.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
  rllib/policy/view_requirement.py
Labels: @author-action-required

#13081 [Dashboard] Job module without job submission
  dashboard/consts.py
  dashboard/datacenter.py
  dashboard/modules/job/__init__.py
  dashboard/modules/job/job_consts.py
  dashboard/modules/job/job_head.py
  dashboard/modules/job/tests/test_job.py
Labels: @tests-ok, dashboard

#13111 [serve] Async controller
  python/ray/serve/controller.py
  python/ray/serve/tests/test_failure.py
Labels: @tests-ok
