Repository ray-project/ray, pull requests merged in 2020-08, with the labels that each got.

#9695 [Core] Gpu type detection
  python/ray/ray_constants.py
  python/ray/resource_spec.py
  python/ray/tests/test_advanced_3.py
Labels: author-action-required

#9817 [tune] stdout/stderr logging redirection
  doc/source/tune/user-guide.rst
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/result.py
  python/ray/tune/tests/test_actor_reuse.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/trainable.py
  python/ray/tune/trial_executor.py
  python/ray/tune/tune.py
  python/ray/tune/utils/util.py
Labels: tune

#9853 [tune] Fix restoration for function API PBT
  python/ray/tune/function_runner.py
  python/ray/tune/session.py
  python/ray/tune/tests/test_function_api.py
  python/ray/tune/trainable.py
Labels: release-blocker, tests ok

#9533 async grpc calls should always return void
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/grpc_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/worker/core_worker_client.h
Labels: author-action-required

#9829 [Core] Fix test_logging_to_driver
  python/ray/tests/test_advanced_3.py
Labels: P0, core, release-blocker

#9879 [doc][hotfix] fix-docs-build
  doc/requirements-doc.txt
Labels: release-blocker

#9789 [Tune] Transformer blog example
  ci/jenkins_tests/run_tune_tests.sh
  doc/requirements-doc.txt
  doc/source/conf.py
  doc/source/tune/examples/index.rst
  doc/source/tune/examples/pbt_transformers.rst
  python/ray/tune/BUILD
  python/ray/tune/examples/README.rst
  python/ray/tune/examples/pbt_transformers/__init__.py
  python/ray/tune/examples/pbt_transformers/pbt_transformers.py
  python/ray/tune/examples/pbt_transformers/test_data/RTE/dev.tsv
  python/ray/tune/examples/pbt_transformers/test_data/RTE/train.tsv
  python/ray/tune/examples/pbt_transformers/test_data/rte.zip
  python/ray/tune/examples/pbt_transformers/trainer.py
  python/ray/tune/examples/pbt_transformers/utils.py
  python/requirements_tune.txt
Labels: release-blocker

#9916 [Core] test_advanced_3.py::test_logging_to_driver (round 2)
  python/ray/tests/test_advanced_3.py
  python/ray/utils.py
  python/ray/worker.py
Labels: P0, release-blocker

#9962 Dashboard Bugfix: Windows directory structure crashes machine view
  python/ray/dashboard/client/src/pages/dashboard/node-info/features/Disk.tsx
Labels: bug

#9831 [Core] Read resources from an environment variable
  python/ray/node.py
  python/ray/tests/test_advanced_3.py
Labels: author-action-required, core

#9908 [tune] Ray Tune + Serve end-to-end integration example
  doc/BUILD
  doc/source/images/serve.png
  doc/source/tune/_tutorials/overview.rst
  doc/source/tune/_tutorials/tune-serve-integration-mnist.py
Labels: tune

#9934 rpc: Core Worker client pool
  BUILD.bazel
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/future_resolver.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/rpc/worker/core_worker_client_pool.cc
  src/ray/rpc/worker/core_worker_client_pool.h
Labels: tests-ok

#9994 [tune] reorder transformer example save
  python/ray/tune/examples/pbt_transformers/trainer.py
Labels: release-blocker

#9996 [autoscaler] hotfix logging
  python/ray/autoscaler/commands.py
Labels: release-blocker

#9699 [Autoscaler] Command Output Improvement
  python/ray/autoscaler/cli_logger.py
  python/ray/autoscaler/command_runner.py
  python/ray/autoscaler/commands.py
  python/ray/autoscaler/subprocess_output_util.py
  python/ray/autoscaler/updater.py
  python/ray/scripts/scripts.py
Labels: author-action-required

#9972 [tune] support resume for search algorithms
  python/ray/tune/suggest/__init__.py
  python/ray/tune/suggest/_mock.py
  python/ray/tune/suggest/hyperopt.py
  python/ray/tune/suggest/repeater.py
  python/ray/tune/suggest/search.py
  python/ray/tune/suggest/search_generator.py
  python/ray/tune/suggest/suggestion.py
  python/ray/tune/tests/_test_cluster_interrupt_searcher.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/trial_runner.py
  python/ray/tune/tune.py
Labels: tune

#9998 [Tune] Better error when using checkpoint_freq
  python/ray/tune/examples/cifar10_pytorch.py
  python/ray/tune/experiment.py
  python/ray/tune/tests/test_function_api.py
  python/ray/tune/tune.py
Labels: tests-ok

#9657 [EVENT] Basic Function and Definition
  BUILD.bazel
  src/ray/protobuf/BUILD
  src/ray/protobuf/event.proto
  src/ray/util/event.cc
  src/ray/util/event.h
  src/ray/util/event_test.cc
  src/ray/util/util.h
Labels: author-action-required

#9735 [Core] Preliminary implementation of ownership-based object directory
  BUILD.bazel
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/object_manager/format/object_manager.fbs
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/object_buffer_pool.h
  src/ray/object_manager/object_directory.cc
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/ownership_based_object_directory.h
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/plasma.fbs
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/protocol.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/test/object_manager_stress_test.cc
  src/ray/object_manager/test/object_manager_test.cc
  src/ray/protobuf/BUILD
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/object_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/reconstruction_policy.cc
  src/ray/raylet/reconstruction_policy.h
  src/ray/raylet/reconstruction_policy_test.cc
  src/ray/raylet/task_dependency_manager.cc
  src/ray/raylet/task_dependency_manager.h
  src/ray/raylet/task_dependency_manager_test.cc
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: author-action-required

#10049 [Hotfix] Pin opencv-python-headless==4.3.0.36
  ci/asan_tests/ray-project/requirements.txt
  doc/requirements-doc.txt
  docker/examples/Dockerfile
  python/ray/tune/requirements-dev.txt
  python/requirements.txt
  python/setup.py
Labels: tests-ok

#10054 [cli] install nightly wheels via `ray install-nightly`
  doc/source/installation.rst
  python/ray/nightly-wheels.yaml
  python/ray/scripts/scripts.py
  python/setup.py
Labels: author-action-required

#10064 Revert "[Core] Add cached memory to available memory (#10020)"
  python/ray/memory_monitor.py
Labels: tests-ok

#10073 Use the right bucket for travis logs
  ci/travis/upload_build_info.sh
Labels: tests-ok

#10044 [tune] Add OptunaSearcher wrapper around Optuna samplers
  doc/source/tune/api_docs/suggestion.rst
  doc/source/tune/examples/optuna_example.rst
  python/ray/tune/BUILD
  python/ray/tune/examples/optuna_example.py
  python/ray/tune/suggest/optuna.py
  python/ray/tune/tests/test_tune_restore.py
  python/requirements_tune.txt
Labels: tests-ok, tune

#10011 [RLlib] Model documentation enhancements.
  doc/source/rllib-examples.rst
  doc/source/rllib-models.rst
  rllib/BUILD
  rllib/agents/dqn/simple_q_model.py
Labels: author-action-required

#10081 [Tune] Update PBT Transformer Test
  python/ray/tune/BUILD
  python/ray/tune/examples/pbt_transformers/pbt_transformers.py
Labels: tests-ok, tune

#10053 [Placement Groups] Support CUDA_VISIBLE_DEVICES
  python/ray/tests/test_placement_group.py
  python/ray/worker.py
Labels: author-action-required

#10084 [Core] Add cached memory to unsued memory in Linux/BSD
  python/ray/memory_monitor.py
Labels: author-action-required

#10103 [autoscaler] Hash contents of SSH key instead of key path
  python/ray/autoscaler/util.py
Labels: author-action-required

#10118 Make sure local format.sh check protobuf
  ci/travis/format.sh
Labels: tests-ok

#9958 [Tune] Pbt Function API
  doc/source/tune/_tutorials/tune-advanced-tutorial.rst
  python/ray/tune/BUILD
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/checkpoint_manager.py
  python/ray/tune/examples/pbt_convnet_example.py
  python/ray/tune/examples/pbt_convnet_function_example.py
  python/ray/tune/tests/test_checkpoint_manager.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
Labels: tests-ok, tune

#10006 [rllib] Learning rate schedule for DDPPO.
  rllib/agents/ppo/ddppo.py
  rllib/agents/ppo/tests/test_ddppo.py
Labels: author-action-required

#10112 [RLlib] Trajectory View API (part 2.5): Actual implementations (not used yet) of a SampleCollector.
  rllib/evaluation/episode.py
  rllib/evaluation/multi_agent_sample_collector.py
  rllib/evaluation/per_policy_sample_collector.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sample_batch_builder.py
  rllib/evaluation/sample_collector.py
  rllib/evaluation/tests/test_trajectories.py
  rllib/policy/view_requirement.py
  rllib/rollout.py
Labels: author-action-required

#10121 torch policy now includes model.metrics
  rllib/examples/models/custom_loss_model.py
  rllib/policy/torch_policy.py
Labels: author-action-required

#10122 [RLlib] Fixes off-policy estimation by making action probabilities a numpy array
  rllib/offline/off_policy_estimator.py
Labels: author-action-required

#10097 [tune] Added Kubernetes syncer and sync client
  doc/source/cluster/cloud.rst
  doc/source/tune/user-guide.rst
  python/ray/autoscaler/command_runner.py
  python/ray/autoscaler/kubernetes/kubectl-rsync.sh
  python/ray/tune/BUILD
  python/ray/tune/integration/kubernetes.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_integration_kubernetes.py
  python/requirements_tune.txt
Labels: tune

#10090 [Placement Group] Support Placement Group state table.
  python/ray/experimental/__init__.py
  python/ray/experimental/placement_group.py
  python/ray/gcs_utils.py
  python/ray/includes/global_state_accessor.pxd
  python/ray/includes/global_state_accessor.pxi
  python/ray/state.py
  python/ray/tests/test_placement_group.py
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/global_state_accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/redis_accessor.cc
  src/ray/gcs/redis_accessor.h
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: author-action-required

#10133 [RLlib] Attention Net/Transformers docs improvement.
  doc/source/rllib-algorithms.rst
  doc/source/rllib-models.rst
Labels: tests-ok

#9957 [Tune] PBT Error if metric not available
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
Labels: tests-ok, tune

#9986 [Autoscaler] Pass custom resources to "ray start" multi instance autoscaling
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/aws/example-auto-instance-type.yaml
  python/ray/autoscaler/command_runner.py
  python/ray/autoscaler/node_launcher.py
  python/ray/autoscaler/updater.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/tests/BUILD
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_command_runner.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: autoscaler

#8521 [tune] Added logger_config field
  python/ray/tune/examples/mlflow_example.py
  python/ray/tune/logger.py
  rllib/agents/trainer.py
Labels: tune

#10050 [Dashboard] Fix Ray Dashboard command error messages
  python/ray/autoscaler/command_runner.py
  python/ray/scripts/scripts.py
Labels: bug, dashboard

#10149 [Python Worker] Add pid to log file name
  python/ray/log_monitor.py
  python/ray/node.py
Labels: tests-ok

#10063 [Placement Group] Placement group remove api part 1
  python/ray/_raylet.pyx
  python/ray/experimental/__init__.py
  python/ray/experimental/placement_group.py
  python/ray/includes/libcoreworker.pxd
  python/ray/state.py
  python/ray/tests/test_placement_group.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/redis_accessor.cc
  src/ray/gcs/redis_accessor.h
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: author-action-required

#10143 [RLlib] Curiosity minor fixes, do-overs, and testing.
  python/requirements.txt
  rllib/BUILD
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/trainer.py
  rllib/evaluation/sample_batch_builder.py
  rllib/models/catalog.py
  rllib/models/torch/fcnet.py
  rllib/models/torch/misc.py
  rllib/models/torch/recurrent_net.py
  rllib/models/torch/visionnet.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_template.py
  rllib/utils/exploration/curiosity.py
  rllib/utils/exploration/exploration.py
  rllib/utils/exploration/tests/test_curiosity.py
  rllib/utils/spaces/space_utils.py
  rllib/utils/typing.py
Labels: @tests-ok

#10196 [Autoscaler] Hotfix
  python/ray/autoscaler/autoscaler.py
Labels: @tests-ok, P0, autoscaler

#10170 [Tune] PBT hyperparam_mutations improvements
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
Labels: @tests-ok

#10181 [SGD][Docs] docs for training/ validation results
  doc/source/raysgd/raysgd_pytorch.rst
  doc/source/raysgd/raysgd_ref.rst
  python/ray/util/sgd/utils.py
Labels: sgd

#10115 [RLlib] First attempt at cleaning up algo code in RLlib: PG.
  doc/source/rllib-algorithms.rst
  rllib/__init__.py
  rllib/agents/pg/README.md
  rllib/agents/pg/pg.py
  rllib/agents/pg/pg_tf_policy.py
  rllib/agents/pg/pg_torch_policy.py
  rllib/agents/pg/utils.py
  rllib/agents/ppo/appo.py
  rllib/agents/ppo/ddppo.py
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
  rllib/evaluation/multi_agent_sample_collector.py
  rllib/evaluation/per_policy_sample_collector.py
  rllib/evaluation/postprocessing.py
  rllib/evaluation/worker_set.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy_template.py
Labels: @author-action-required

#10215 [Placement Group] Remove API part 2
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  python/ray/state.py
  python/ray/tests/test_placement_group.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/task_dependency_manager_test.cc
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
Labels: @author-action-required

#10207 [autoscaler] Rename instance_type => node_type, TAG_RAY_INSTANCE_TYPE => TAG_RAY_USER_NODE_TYPE
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/aws/config.py
  python/ray/autoscaler/aws/node_provider.py
  python/ray/autoscaler/azure/node_provider.py
  python/ray/autoscaler/commands.py
  python/ray/autoscaler/local/node_provider.py
  python/ray/autoscaler/node_launcher.py
  python/ray/autoscaler/node_provider.py
  python/ray/autoscaler/resource_demand_scheduler.py
  python/ray/autoscaler/tags.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_coordinator_server.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#10197 [Object spilling] Look up the location of the primary raylet from the owner's metadata
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_object_spilling.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/task_manager.cc
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: @author-action-required

#10218 Partially Use f string
  python/ray/actor.py
  python/ray/exceptions.py
  python/ray/function_manager.py
  python/ray/import_thread.py
  python/ray/log_monitor.py
  python/ray/memory_monitor.py
  python/ray/metrics_agent.py
  python/ray/monitor.py
  python/ray/node.py
  python/ray/parameter.py
  python/ray/prometheus_exporter.py
  python/ray/ray_constants.py
  python/ray/reporter.py
  python/ray/resource_spec.py
  python/ray/scripts/scripts.py
  python/ray/serialization.py
  python/ray/services.py
  python/ray/setup-dev.py
  python/ray/signature.py
  python/ray/state.py
  python/ray/test_utils.py
  python/ray/util/iter.py
  python/ray/util/multiprocessing/pool.py
  python/ray/util/sgd/tests/test_torch.py
  python/ray/util/sgd/tf/examples/cifar_tf_example.py
  python/ray/util/sgd/tf/tf_trainer.py
  python/ray/util/sgd/torch/distributed_torch_runner.py
  python/ray/util/sgd/torch/examples/benchmarks/benchmark.py
  python/ray/util/sgd/torch/examples/benchmarks/dp_benchmark.py
  python/ray/util/sgd/torch/examples/benchmarks/horovod_benchmark_apex.py
  python/ray/util/sgd/torch/examples/image_models/util.py
  python/ray/util/sgd/torch/examples/segmentation/train_segmentation.py
  python/ray/util/sgd/torch/examples/segmentation/utils.py
  python/ray/util/sgd/torch/examples/transformers/transformers_example.py
  python/ray/util/sgd/torch/examples/transformers/utils.py
  python/ray/util/sgd/torch/torch_runner.py
  python/ray/util/sgd/torch/torch_trainer.py
  python/ray/util/sgd/torch/training_operator.py
  python/ray/util/sgd/torch/utils.py
  python/ray/util/sgd/utils.py
  python/ray/utils.py
Labels: @author-action-required

#10268 [Tech Debt] Use f-string for python/ray/*.py
  python/ray/actor.py
  python/ray/cluster_utils.py
  python/ray/cross_language.py
  python/ray/exceptions.py
  python/ray/function_manager.py
  python/ray/log_monitor.py
  python/ray/remote_function.py
  python/ray/serialization.py
  python/ray/signature.py
  python/ray/state.py
  python/ray/worker.py
Labels: @author-action-required

#9212 Update memory_monitor.py
  python/ray/memory_monitor.py
Labels: @author-action-required

#10245 Prevent Local Worker creation from blocking remote worker creation by creating remote workers before local worker
  rllib/evaluation/worker_set.py
Labels: @tests-ok

#10259 [Placement Group] Wait
  python/ray/actor.py
  python/ray/experimental/placement_group.py
  python/ray/remote_function.py
  python/ray/tests/test_placement_group.py
Labels: @author-action-required

#9713 Fix links to ddpg tuned examples
  doc/source/rllib-algorithms.rst
Labels: rllib

#10233 Fix some failed streaming build
  src/ray/core_worker/core_worker.h
  streaming/src/test/mock_actor.cc
  streaming/src/test/queue_tests_base.h
Labels: @author-action-required

#10168 [rllib] Try fixing torch GPU and masking errors
  doc/source/rllib-examples.rst
  rllib/agents/dqn/dqn_torch_policy.py
  rllib/examples/models/parametric_actions_model.py
  rllib/utils/exploration/epsilon_greedy.py
  rllib/utils/torch_ops.py
Labels: @author-action-required

#10318 Remove unused scheduler states
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling_queue.cc
  src/ray/raylet/scheduling_queue.h
Labels: @author-action-required

#10199 Fix wait timeout logic
  python/ray/tests/test_basic.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
Labels: @author-action-required

#10236 [Autoscaler] Multi node commands
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/docker.py
  python/ray/autoscaler/ray-schema.json
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @author-action-required

#10172 [RLlib] Dreamer
  doc/source/rllib-algorithms.rst
  doc/source/rllib-toc.rst
  python/ray/tune/logger.py
  rllib/agents/dreamer/__init__.py
  rllib/agents/dreamer/dreamer.py
  rllib/agents/dreamer/dreamer_model.py
  rllib/agents/dreamer/dreamer_torch_policy.py
  rllib/agents/dreamer/utils.py
  rllib/agents/registry.py
  rllib/env/dm_control_wrapper.py
  rllib/examples/env/dm_control_suite.py
  rllib/policy/torch_policy.py
  rllib/tuned_examples/dreamer/dreamer-deepmind-control.yaml
Labels: @author-action-required, rllib

#10317 [metrics] Clean up actor metrics
  src/ray/raylet/node_manager.cc
  src/ray/raylet/reconstruction_policy.cc
  src/ray/raylet/reconstruction_policy.h
  src/ray/stats/metric_defs.h
Labels: @author-action-required

#10316 [metrics] Clean up object manager stats
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/stats/metric_defs.h
Labels: @author-action-required

#10314 [jenkins] Cleanup deprecated Jenkins files
  ci/jenkins_tests/entry_point.sh
  ci/jenkins_tests/miscellaneous/large_memory_test.py
  ci/jenkins_tests/miscellaneous/test_wait_hanging.py
  ci/jenkins_tests/run_doc_tests.sh
  ci/jenkins_tests/run_multi_node_tests.sh
  ci/jenkins_tests/run_sgd_tests.sh
  ci/jenkins_tests/run_tune_tests.sh
  docker/tune_test/Dockerfile
  docker/tune_test/build_from_source.Dockerfile
Labels: @author-action-required

#10309 [Core]Add runtime context for python worker
  python/ray/__init__.py
  python/ray/runtime_context.py
  python/ray/state.py
  python/ray/tests/test_runtime_context.py
Labels: @tests-ok

#10329 [Autoscaler] Proper resource demand plumbing
  python/ray/autoscaler/autoscaler.py
  python/ray/autoscaler/load_metrics.py
  python/ray/monitor.py
  python/ray/test_utils.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#10333 [api] API deprecations and cleanups for 1.0 (internal_config and Checkpointable actor)
  dashboard/tests/test_dashboard.py
  java/test/src/main/java/io/ray/test/BaseMultiLanguageTest.java
  python/ray/actor.py
  python/ray/cluster_utils.py
  python/ray/function_manager.py
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/node.py
  python/ray/parameter.py
  python/ray/ray_perf.py
  python/ray/scripts/scripts.py
  python/ray/test_utils.py
  python/ray/tests/conftest.py
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_actor_resources.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_array.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_component_failures_2.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_global_state.py
  python/ray/tests/test_metrics_agent.py
  python/ray/tests/test_multi_node_2.py
  python/ray/tests/test_multi_tenancy.py
  python/ray/tests/test_multinode_failures.py
  python/ray/tests/test_multinode_failures_2.py
  python/ray/tests/test_object_manager.py
  python/ray/tests/test_object_spilling.py
  python/ray/tests/test_reconstruction.py
  python/ray/tests/test_reference_counting.py
  python/ray/tests/test_reference_counting_2.py
  python/ray/tests/test_stress_failure.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
  src/ray/common/ray_config_def.h
  src/ray/common/test_util.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/tables.cc
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/task_dependency_manager.cc
  src/ray/raylet/task_dependency_manager.h
  src/ray/raylet/task_dependency_manager_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  streaming/java/streaming-api/src/main/java/io/ray/streaming/api/context/ClusterStarter.java
  streaming/python/tests/test_hybrid_stream.py
Labels: @author-action-required

#10288 [Serve] add type hints for controller and backend_worker
  python/ray/serve/backend_worker.py
  python/ray/serve/controller.py
Labels: @tests-ok

#10187 [Core] Expanded job ID to 4 bytes by removing object flag bytes.
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  python/ray/includes/unique_ids.pxd
  python/ray/includes/unique_ids.pxi
  src/ray/common/id.cc
  src/ray/common/id.h
  src/ray/common/id_test.cc
  src/ray/common/task/task_spec.cc
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/design_docs/id_specification.md
  src/ray/raylet/reconstruction_policy_test.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/task_dependency_manager_test.cc
Labels: @author-action-required

#10345 [Core] Improve raylet failure error msg
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#10332 [api] Clean up and document Actor name / lifetime API
  doc/source/actors.rst
  doc/source/advanced.rst
  doc/source/rllib-training.rst
  python/ray/actor.py
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_job.py
  python/ray/tests/test_placement_group.py
Labels: @author-action-required

#10366 [Autoscaler][hotfix] Remove additionalProperties from available_node_types schema
  python/ray/autoscaler/ray-schema.json
Labels: @tests-ok, P0

#10287 [Dashboard] Change default ip address for the dashboard to ipv4
  python/ray/parameter.py
  python/ray/ray_constants.py
  python/ray/tests/test_metrics.py
  python/ray/tests/test_output.py
  python/ray/worker.py
  python/setup.py
Labels: @author-action-required

#9682 [cpp worker] support cluster mode and object Put/Get works
  .bazelrc
  .travis.yml
  ci/travis/ci.sh
  cpp/BUILD.bazel
  cpp/include/ray/api.h
  cpp/include/ray/api/ray_config.h
  cpp/include/ray/core.h
  cpp/src/example/example.cc
  cpp/src/example/example_cluster_mode.cc
  cpp/src/ray/api.cc
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/abstract_ray_runtime.h
  cpp/src/ray/runtime/native_ray_runtime.cc
  cpp/src/ray/runtime/object/local_mode_object_store.cc
  cpp/src/ray/runtime/object/local_mode_object_store.h
  cpp/src/ray/runtime/object/native_object_store.cc
  cpp/src/ray/runtime/object/native_object_store.h
  cpp/src/ray/runtime/object/object_store.cc
  cpp/src/ray/runtime/object/object_store.h
  cpp/src/ray/test/cluster/cluster_mode_test.cc
  cpp/src/ray/util/process_helper.cc
  cpp/src/ray/util/process_helper.h
  cpp/src/ray/worker/default_worker.cc
  python/ray/services.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/common.cc
  src/ray/raylet/main.cc
  src/ray/raylet/worker_pool.cc
Labels: @author-action-required

#10382 Fix typo bootstraping -> bootstrapping
  python/ray/autoscaler/commands.py
Labels: @author-action-required

#10221 error message on non-integral args with ray.remote
  python/ray/tests/test_basic.py
  python/ray/worker.py
Labels: @author-action-required

#10397 [Autoscaler] Fix resource passing bug fix
  python/ray/autoscaler/command_runner.py
  python/ray/node.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_command_runner.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#10377 [api] Second round of 1.0 API changes: exceptions, num_return_vals
  doc/source/actors.rst
  doc/source/advanced.rst
  doc/source/fault-tolerance.rst
  doc/source/walkthrough.rst
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/cross_language.py
  python/ray/exceptions.py
  python/ray/experimental/array/distributed/linalg.py
  python/ray/experimental/array/remote/linalg.py
  python/ray/ray_constants.py
  python/ray/remote_function.py
  python/ray/serialization.py
  python/ray/serve/tests/test_router.py
  python/ray/state.py
  python/ray/tests/test_actor.py
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_cancel.py
  python/ray/tests/test_component_failures_2.py
  python/ray/tests/test_error_ray_not_initialized.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_memory_limits.py
  python/ray/tests/test_mini.py
  python/ray/tests/test_multinode_failures.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_queue.py
  python/ray/tests/test_reconstruction.py
  python/ray/tests/test_reference_counting.py
  python/ray/tests/test_reference_counting_2.py
  python/ray/tests/test_serialization.py
  python/ray/tests/test_stress_failure.py
  python/ray/tests/test_unreconstructable_errors.py
  python/ray/tune/ray_trial_executor.py
  python/ray/worker.py
  rllib/evaluation/rollout_worker.py
Labels: @author-action-required

#10405 [autoscaler] Add documentation for multi node type autoscaling
  doc/source/cluster/autoscaling.rst
  doc/source/cluster/launcher.rst
  doc/source/index.rst
  python/ray/autoscaler/aws/example-full.yaml
  python/ray/autoscaler/aws/example-multi-node-type.yaml
  python/ray/autoscaler/resource_demand_scheduler.py
Labels: @author-action-required

#10406 [api] Remove legacy memory management docs
  doc/source/memory-management.rst
Labels: @author-action-required

#10422 [core] Move log_to_driver back to public
  python/ray/serve/benchmarks/microbenchmark.py
  python/ray/tests/test_advanced_3.py
  python/ray/tune/examples/pbt_transformers/pbt_transformers.py
  python/ray/tune/tests/test_commands.py
  python/ray/util/sgd/torch/examples/cifar_pytorch_example.py
  python/ray/util/sgd/torch/examples/cifar_pytorch_pbt.py
  python/ray/worker.py
Labels: @author-action-required

#10303 [Dashboard] Dashboard basic modules
  bazel/python.bzl
  dashboard/BUILD
  dashboard/agent.py
  dashboard/dashboard.py
  dashboard/datacenter.py
  dashboard/head.py
  dashboard/modules/log/__init__.py
  dashboard/modules/log/log_agent.py
  dashboard/modules/log/log_head.py
  dashboard/modules/log/test_log.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/modules/reporter/test_reporter.py
  dashboard/modules/stats_collector/__init__.py
  dashboard/modules/stats_collector/stats_collector_consts.py
  dashboard/modules/stats_collector/stats_collector_head.py
  dashboard/modules/stats_collector/test_stats_collector.py
  dashboard/modules/test/test_agent.py
  dashboard/modules/test/test_consts.py
  dashboard/modules/test/test_head.py
  dashboard/tests/conftest.py
  dashboard/tests/test_dashboard.py
  dashboard/utils.py
  python/ray/services.py
  python/ray/test_utils.py
  python/ray/utils.py
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
Labels: @tests-ok, dashboard

#10323 Fix Issue #10319 - Dashboard autoscaler crash
  python/ray/dashboard/node_stats.py
Labels: @author-action-required, bug, dashboard

#10391 [Tests] Enable large test
  python/ray/tests/BUILD
  python/ray/tests/test_stress_failure.py
Labels: @author-action-required

#10225 Keeping pipelines full
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
Labels: @author-action-required

#10283 [Tune] Synchronous Mode for PBT
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
  python/ray/tune/trial_runner.py
Labels: @tests-ok

#9897 [cli] Add prompt command for CLI logger.
  python/ray/autoscaler/cli_logger.py
Labels: @author-action-required

#10192 [tune] Added external PyTorch tutorial test
  python/ray/tune/BUILD
  python/ray/tune/tests/ext_pytorch.py
Labels: @tests-ok, tune

#10413 [Placement Group] Leasing context refactoring part 2
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
Labels: @author-action-required
