Repository ray-project/ray, pull requests merged in 2021-01, with the labels that each got.

#13127 [Serve] [Doc] Add existing web server integration ServeHandle tutorial
  doc/source/serve/index.rst
  doc/source/serve/tutorials/index.rst
  doc/source/serve/tutorials/web-server-integration.rst
  python/ray/serve/api.py
  python/ray/serve/examples/doc/aiohttp/aiohttp_app.py
  python/ray/serve/examples/doc/aiohttp/aiohttp_deploy_serve.py
  python/ray/serve/examples/doc/fastapi/fastapi.py
  python/ray/serve/examples/doc/fastapi/servehandle_fastapi.py
Labels: @tests-ok

#12117 Enabling the cancellation of non-actor tasks in a worker's queue
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
Labels: @author-action-required

#13157 [Core] Remove Arrow dependencies
  BUILD.bazel
  bazel/BUILD.arrow
  bazel/ray_deps_setup.bzl
  ci/travis/bazel-format.sh
  src/ray/common/buffer.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/test/object_manager_stress_test.cc
  src/ray/object_manager/test/object_manager_test.cc
  src/ray/raylet/node_manager.cc
  thirdparty/patches/arrow-windows-export.patch
Labels: @tests-ok

#13017 [XGboost] Update Documentation
  doc/source/conf.py
  doc/source/xgboost-ray.rst
  python/ray/tune/integration/mlflow.py
Labels: @tests-ok

#13173 [SGD] Fix Docstring for `as_trainable`
  python/ray/util/sgd/torch/torch_trainer.py
Labels: @tests-ok

#13171 [tune] better signature check for `tune.sample_from`
  python/ray/tune/sample.py
  python/ray/tune/tests/test_sample.py
Labels: @tests-ok

#13174 [Tune] Fix PBT Transformers Example
  python/ray/tune/examples/pbt_transformers/pbt_transformers.py
Labels: @tests-ok

#13142 [Serve] HTTPOptions for deployment modes
  doc/source/serve/advanced.rst
  doc/source/serve/deployment.rst
  doc/source/serve/faq.rst
  python/ray/serve/BUILD
  python/ray/serve/__init__.py
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/serve/examples/doc/quickstart_class.py
  python/ray/serve/examples/doc/quickstart_function.py
  python/ray/serve/http_proxy.py
  python/ray/serve/http_state.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_config.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/utils.py
Labels: @author-action-required

#12982 [Metrics] Record per node and raylet cpu / mem usage
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/tests/test_reporter.py
  python/ray/metrics_agent.py
  python/ray/test_utils.py
  python/ray/tests/test_metrics_agent.py
  src/ray/gcs/gcs_server/gcs_server.cc
Labels: @author-action-required

#13233 [tune/serve] fix tune/serve integration example in docs
  doc/source/tune/_tutorials/tune-serve-integration-mnist.py
  python/ray/tune/utils/util.py
Labels: @tests-ok

#13054 [Release] Add 1.1.0 release test logs
  release/release_logs/1.1.0/microbenchmark.txt
  release/release_logs/1.1.0/rllib_regression_tf.txt
  release/release_logs/1.1.0/rllib_regression_torch.txt
  release/release_logs/1.1.0/stress_tests/test_dead_actors.txt
  release/release_logs/1.1.0/stress_tests/test_many_tasks.txt
  release/release_logs/1.1.0/stress_tests/test_placement_group_results.txt
Labels: @tests-ok

#13217 Start ray client server with 'ray start'
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/parameter.py
  python/ray/ray_constants.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_multi_node_2.py
  python/ray/util/client/dataclient.py
  python/ray/util/client/server/__init__.py
  python/ray/util/client/server/__main__.py
  python/ray/util/client/server/server.py
Labels: @author-action-required

#13156 [GCS]Add gcs actor schedule strategy
  src/ray/gcs/gcs_server/gcs_actor_schedule_strategy.cc
  src/ray/gcs/gcs_server/gcs_actor_schedule_strategy.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
Labels: @author-action-required

#13267 [Release] Use ray-ml image for long running test
  release/long_running_tests/cluster.yaml
Labels: @tests-ok

#13255 [Tune] Improve error message for Session Detection
  python/ray/tune/session.py
Labels: @tests-ok

#13165 [Dashboard] Add GET /log_proxy API
  dashboard/modules/log/log_agent.py
  dashboard/modules/log/log_consts.py
  dashboard/modules/log/log_head.py
  dashboard/modules/log/log_utils.py
  dashboard/modules/log/tests/test_log.py
Labels: @tests-ok, dashboard

#13164 Fix a crash problem caused by GetActorHandle in ActorManager
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_actor_NativeActorHandle.cc
  src/ray/core_worker/test/actor_manager_test.cc
Labels: @tests-ok

#13245 [Pull manager] Only pull once per retry period
  python/ray/tests/test_object_spilling.py
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/pull_manager_test.cc
Labels: @tests-ok

#13243 [Cancellation] Make Test Cancel Easier to Debug
  python/ray/tests/test_cancel.py
Labels: @author-action-required

#13305 Do not give an error if both `RAY_ADDRESS` and `address` is specified on initialization
  python/ray/worker.py
Labels: @author-action-required

#13215 [serve] Clean up EndpointState interface, move checkpointing inside of EndpointState
  python/ray/serve/api.py
  python/ray/serve/backend_state.py
  python/ray/serve/controller.py
  python/ray/serve/endpoint_state.py
  python/ray/serve/http_state.py
Labels: @tests-ok

#13261 [RLlib] Add more detailed Documentation on Model building API
  doc/source/rllib-algorithms.rst
  doc/source/rllib-models.rst
  rllib/examples/custom_model_api.py
  rllib/examples/models/custom_model_api.py
  rllib/examples/models/trajectory_view_utilizing_models.py
Labels: @author-action-required

#12785 [tune] convert search spaces: parse spec before flattening
  python/ray/tune/suggest/ax.py
  python/ray/tune/suggest/bayesopt.py
  python/ray/tune/suggest/bohb.py
  python/ray/tune/suggest/dragonfly.py
  python/ray/tune/suggest/nevergrad.py
  python/ray/tune/suggest/optuna.py
  python/ray/tune/suggest/skopt.py
  python/ray/tune/tests/test_sample.py
Labels: @tests-ok

#13328 [Serve] Support Starlette streaming response
  python/ray/serve/backend_worker.py
  python/ray/serve/http_proxy.py
  python/ray/serve/tests/test_api.py
Labels: @tests-ok

#13326 [client] Report number of currently active clients on connect
  .flake8
  python/ray/tests/test_client.py
  python/ray/util/client/__init__.py
  python/ray/util/client/dataclient.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/worker.py
  python/ray/util/client_connect.py
  src/ray/protobuf/ray_client.proto
Labels: @tests-ok

#13301 [Tune] Rename MLFlow to MLflow
  doc/source/tune/_tutorials/tune-mlflow.rst
  python/ray/tune/examples/mlflow_example.py
  python/ray/tune/examples/mlflow_ptl.py
  python/ray/tune/integration/mlflow.py
  python/ray/tune/logger.py
  python/ray/tune/tests/test_dependency.py
  python/ray/tune/tests/test_integration_mlflow.py
Labels: @tests-ok

#13359 [Dependabot] [CI] Re-configure Dependabot and disable duplicate builds
  .github/dependabot.yml
  .github/workflows/main.yml
  .travis.yml
Labels: @tests-ok

#13236 [tune] buffer trainable results
  doc/source/tune/user-guide.rst
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_trial_runner_callbacks.py
  python/ray/tune/trainable.py
  python/ray/tune/trial_runner.py
  python/ray/tune/utils/util.py
  release/tune_tests/scalability_tests/cluster.yaml
  release/tune_tests/scalability_tests/requirements.txt
  release/tune_tests/scalability_tests/run.sh
  release/tune_tests/scalability_tests/wait_cluster.py
  release/tune_tests/scalability_tests/workloads/test_result_buffering.py
Labels: @author-action-required

#13269 [Serve] Add dependency management support for driver not running in a conda env
  doc/source/serve/advanced.rst
  python/ray/serve/examples/doc/imported_backend.py
  python/ray/serve/utils.py
Labels: @tests-ok

#13319 [Serve] Backend state unit tests
  python/ray/serve/backend_state.py
  python/ray/serve/tests/test_backend_state.py
Labels: @tests-ok

#13315 [RLlib] Trajectory View API: Atari framestacking.
  rllib/agents/trainer.py
  rllib/env/atari_wrappers.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/models/catalog.py
  rllib/models/tf/visionnet.py
  rllib/models/torch/visionnet.py
  rllib/models/utils.py
  rllib/policy/policy.py
  rllib/policy/tests/test_trajectory_view_api.py
  rllib/policy/view_requirement.py
  rllib/utils/test_utils.py
Labels: @tests-ok

#13229 [Dashboard] Fix missing actor pid
  dashboard/datacenter.py
  dashboard/modules/job/job_head.py
  dashboard/modules/job/tests/test_job.py
  dashboard/modules/logical_view/tests/test_logical_view_head.py
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @tests-ok, dashboard

#13411 Plumb connection retries config through
  python/ray/util/client/__init__.py
  python/ray/util/client/worker.py
  python/ray/util/client_connect.py
Labels: @tests-ok

#12514 [autoscaler/k8s] [CI] Kubernetes test ray up, exec, down
  .travis.yml
  ci/travis/ci.sh
  python/ray/tests/BUILD
  python/ray/tests/test_cli_patterns/test_k8s_cluster_launcher.yaml
  python/ray/tests/test_k8s_cluster_launcher.py
Labels: @tests-ok

#13251 Add bazel logs upload to GHA
  .github/workflows/main.yml
  ci/travis/ci.sh
  ci/travis/get_build_info.py
  ci/travis/upload_build_info.sh
Labels: @tests-ok

#13363 [RLlib] Redo: Make TFModelV2 fully modular like TorchModelV2 (soft-deprecate register_variables, unify var names wrt torch).
  rllib/BUILD
  rllib/agents/ddpg/ddpg_tf_model.py
  rllib/agents/dqn/distributional_q_tf_model.py
  rllib/agents/sac/sac_tf_model.py
  rllib/examples/batch_norm_model.py
  rllib/examples/custom_env.py
  rllib/examples/custom_keras_model.py
  rllib/examples/models/autoregressive_action_model.py
  rllib/examples/models/batch_norm_model.py
  rllib/examples/models/centralized_critic_models.py
  rllib/examples/models/cnn_plus_fc_concat_model.py
  rllib/examples/models/custom_loss_model.py
  rllib/examples/models/eager_model.py
  rllib/examples/models/mobilenet_v2_with_lstm_models.py
  rllib/examples/models/parametric_actions_model.py
  rllib/examples/models/rnn_model.py
  rllib/examples/models/rnn_spy_model.py
  rllib/examples/models/shared_weights_model.py
  rllib/examples/models/simple_rpg_model.py
  rllib/examples/models/trajectory_view_utilizing_models.py
  rllib/models/catalog.py
  rllib/models/tests/test_distributions.py
  rllib/models/tests/test_models.py
  rllib/models/tf/attention_net.py
  rllib/models/tf/fcnet.py
  rllib/models/tf/recurrent_net.py
  rllib/models/tf/tf_modelv2.py
  rllib/models/tf/visionnet.py
  rllib/models/torch/torch_modelv2.py
  rllib/tests/test_model_imports.py
  rllib/tests/test_nested_observation_spaces.py
  rllib/utils/deprecation.py
  rllib/utils/exploration/curiosity.py
Labels: @tests-ok

#13212 [joblib] joblib strikes again but this time on windows
  python/ray/tests/test_joblib.py
Labels: @tests-ok

#13392 [kubernetes][minor] Operator garbage collection fix
  python/ray/operator/operator_utils.py
  python/ray/setup-dev.py
Labels: @tests-ok

#13391 [Core][CLI] `ray status` and `ray memory` no longer starts a new job
  python/ray/autoscaler/_private/commands.py
  python/ray/internal/internal_api.py
  python/ray/scripts/scripts.py
Labels: @tests-ok

#13417 Fix getting runtime context dict in driver
  python/ray/runtime_context.py
  python/ray/tests/test_runtime_context.py
Labels: @author-action-required

#13416 [xgb] re-enable xgboost_ray tests
  .travis.yml
  python/ray/util/xgboost/BUILD
  python/ray/util/xgboost/simple_example.py
  python/requirements/requirements_upstream.txt
Labels: @tests-ok

#13291 [Serialization] New custom serialization API
  doc/source/serialization.rst
  python/ray/serialization.py
  python/ray/tests/test_serialization.py
  python/ray/util/__init__.py
  python/ray/util/serialization.py
Labels: @tests-ok, core-api-change-approval-required

#13220 [Core] Ownership-based Object Directory: Consolidate location table and reference table.
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/test_utils.py
  python/ray/tests/test_memory_limits.py
  python/ray/tests/test_unreconstructable_errors.py
  python/ray/worker.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
Labels: @author-action-required

#13454 [GCS]Remove unused class variable
  src/ray/gcs/gcs_client/service_based_accessor.h
Labels: @author-action-required

#13470 [Object Spilling] Dedup restore objects
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#13425 [CI] Enable Dashboard tests for master
  ci/travis/determine_tests_to_run.py
  dashboard/BUILD
  dashboard/modules/job/tests/test_job.py
  dashboard/tests/test_dashboard.py
Labels: @author-action-required

#13436 [CI] Fix Windows Bazel Upload
  .github/workflows/main.yml
  ci/remote-watch.py
Labels: @tests-ok

#13356 [Doc] Update id specification doc
  release/long_running_tests/.anyscale.yaml
  src/ray/design_docs/id_specification.md
Labels: @author-action-required

#13474 [ray_client]: fix wrong reference in server_pickler
  python/ray/tests/test_actor.py
  python/ray/util/client/server/server_pickler.py
Labels: @tests-ok

#13197 sync write internal config in gcs
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
Labels: @author-action-required

#12936 Refactor node manager to eliminate `new_scheduler_enabled_`
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/node_manager.task.cc
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_interface.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/old_cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/old_cluster_resource_scheduler.h
  src/ray/raylet/test/util.h
Labels: @author-action-required

#13364 [GCS]Only publish changed field when node dead
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: @tests-ok

#13467 [RLlib] Solve PyTorch/TF-eager A3C async race condition between calling model and its value function.
  rllib/agents/a3c/a3c.py
  rllib/agents/a3c/tests/test_a2c.py
  rllib/agents/a3c/tests/test_a3c.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/torch_policy.py
  rllib/utils/exploration/tests/test_explorations.py
  rllib/utils/threading.py
Labels: @tests-ok

#12592 [Serve] Allow ObjectRef for Composition
  python/ray/serve/backend_worker.py
  python/ray/serve/handle.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_router.py
Labels: @author-action-required

#13455 [RLlib] MARWIL loss function test case and cleanup.
  rllib/agents/marwil/marwil_tf_policy.py
  rllib/agents/marwil/marwil_torch_policy.py
  rllib/agents/marwil/tests/test_marwil.py
Labels: @tests-ok

#13397 [RLlib] Deprecate `vf_share_layers` in top-level PPO/MAML/MB-MPO configs.
  doc/source/rllib-models.rst
  release/rllib_tests/regression_tests/compact-regression-tests-tf.yaml
  release/rllib_tests/regression_tests/compact-regression-tests-torch.yaml
  rllib/agents/maml/maml.py
  rllib/agents/mbmpo/mbmpo.py
  rllib/agents/ppo/ppo.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/examples/cartpole_lstm.py
  rllib/examples/custom_env.py
  rllib/examples/mobilenet_v2_with_lstm.py
  rllib/tests/test_lstm.py
  rllib/tests/test_model_imports.py
  rllib/tuned_examples/compact-regression-test.yaml
  rllib/tuned_examples/ppo/atari-ddppo.yaml
  rllib/tuned_examples/ppo/atari-ppo.yaml
  rllib/tuned_examples/ppo/cartpole-ppo.yaml
  rllib/tuned_examples/ppo/pong-ppo.yaml
  rllib/tuned_examples/ppo/repeatafterme-ppo-lstm.yaml
Labels: @tests-ok

#13082 [RLlib] Env directory cleanup and tests.
  python/requirements_rllib.txt
  rllib/BUILD
  rllib/agents/mbmpo/mbmpo.py
  rllib/agents/qmix/qmix_policy.py
  rllib/env/__init__.py
  rllib/env/atari_wrappers.py
  rllib/env/constants.py
  rllib/env/dm_control_wrapper.py
  rllib/env/dm_env_wrapper.py
  rllib/env/env_context.py
  rllib/env/group_agents_wrapper.py
  rllib/env/model_vector_env.py
  rllib/env/multi_agent_env.py
  rllib/env/pettingzoo_env.py
  rllib/env/unity3d_env.py
  rllib/env/wrappers/atari_wrappers.py
  rllib/env/wrappers/dm_control_wrapper.py
  rllib/env/wrappers/dm_env_wrapper.py
  rllib/env/wrappers/group_agents_wrapper.py
  rllib/env/wrappers/kaggle_wrapper.py
  rllib/env/wrappers/model_vector_env.py
  rllib/env/wrappers/pettingzoo_env.py
  rllib/env/wrappers/recsim_wrapper.py
  rllib/env/wrappers/tests/test_group_agents_wrapper.py
  rllib/env/wrappers/tests/test_kaggle_wrapper.py
  rllib/env/wrappers/tests/test_recsim_wrapper.py
  rllib/env/wrappers/unity3d_env.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/examples/env/dm_control_suite.py
  rllib/examples/env/multi_agent.py
  rllib/examples/multi_agent_independent_learning.py
  rllib/examples/multi_agent_parameter_sharing.py
  rllib/examples/serving/unity3d_client.py
  rllib/examples/serving/unity3d_server.py
  rllib/examples/unity3d_env_local.py
  rllib/tuned_examples/ppo/unity3d-soccer-strikers-vs-goalie-ppo.yaml
Labels: @tests-ok

#13238 [RLlib] Issue 9071 A3C w/ RNN not working due to VF assuming no RNN.
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/cql/cql_torch_policy.py
  rllib/agents/ddpg/ddpg_torch_policy.py
  rllib/agents/dqn/dqn_tf_policy.py
  rllib/agents/dqn/dqn_torch_policy.py
  rllib/agents/dreamer/dreamer_torch_policy.py
  rllib/agents/impala/impala.py
  rllib/agents/impala/vtrace_torch_policy.py
  rllib/agents/maml/maml_tf_policy.py
  rllib/agents/maml/maml_torch_policy.py
  rllib/agents/mbmpo/mbmpo_torch_policy.py
  rllib/agents/ppo/appo_tf_policy.py
  rllib/agents/ppo/appo_torch_policy.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/sac/sac.py
  rllib/agents/sac/sac_torch_policy.py
  rllib/contrib/maddpg/maddpg_policy.py
  rllib/evaluation/postprocessing.py
  rllib/tuned_examples/sac/mspacman-sac.yaml
  rllib/utils/tf_ops.py
  rllib/utils/torch_ops.py
Labels: @tests-ok

#13253 Fix passing env on windows
  src/ray/util/process.cc
Labels: bug

#13175 [Object Spilling] Remove retries and use a timer instead.
  python/ray/parameter.py
  python/ray/tests/conftest.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_object_spilling.py
  python/ray/tests/test_reference_counting_2.py
  src/ray/common/ray_config_def.h
  src/ray/object_manager/plasma/create_request_queue.cc
  src/ray/object_manager/plasma/create_request_queue.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/test/create_request_queue_test.cc
Labels: @author-action-required

#13421 [metrics] Better validation for tags
  python/ray/tests/test_metrics_agent.py
  python/ray/util/metrics.py
Labels: @author-action-required

#13533 [Tune] MLflow Credentials
  doc/source/tune/api_docs/integration.rst
  python/ray/tune/integration/mlflow.py
Labels: @tests-ok

#13543 Fix Docker Permission for Serve release test again
  python/ray/serve/benchmarks/cluster.yaml
  python/ray/serve/benchmarks/single.yaml
  release/long_running_tests/cluster.yaml
Labels: @tests-ok

#13546 [Object Spilling] Fix restoration request dedup issues.
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#13574 Revert "Pipe monitor.err logs to driver"
  python/ray/log_monitor.py
  python/ray/worker.py
Labels: @tests-ok

#13549 [tune] Allow actor reuse for new trials
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/tests/test_actor_reuse.py
  python/ray/tune/trainable.py
Labels: @tests-ok

#13456 [xgboost] Add XGBoost release tests
  release/xgboost_tests/cluster_cpu_moderate.yaml
  release/xgboost_tests/cluster_cpu_small.yaml
  release/xgboost_tests/cluster_gpu_small.yaml
  release/xgboost_tests/create_test_data.py
  release/xgboost_tests/requirements.txt
  release/xgboost_tests/run.sh
  release/xgboost_tests/wait_cluster.py
  release/xgboost_tests/workloads/_train.py
  release/xgboost_tests/workloads/distributed_api_test.py
  release/xgboost_tests/workloads/ft_small_elastic.py
  release/xgboost_tests/workloads/ft_small_non_elastic.py
  release/xgboost_tests/workloads/train_gpu.py
  release/xgboost_tests/workloads/train_moderate.py
  release/xgboost_tests/workloads/train_small.py
  release/xgboost_tests/workloads/tune_32x4.py
  release/xgboost_tests/workloads/tune_4x32.py
  release/xgboost_tests/workloads/tune_small.py
Labels: @tests-ok

#13420 [metrics] Check that all tag_keys are set when recording
  python/ray/tests/test_metrics.py
  python/ray/tests/test_metrics_agent.py
  python/ray/util/metrics.py
Labels: @author-action-required

#13561 [Autoscaler] Display node status tag in autsocaler status
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/util.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#13308 [rllib] Fix problem in preprocessing nested MultiDiscrete
  rllib/models/preprocessors.py
  rllib/models/tests/test_preprocessors.py
Labels: @tests-ok

#13309 [Core] Inline small objects in GetObjectStatus response.
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_advanced.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/future_resolver.h
  src/ray/protobuf/core_worker.proto
Labels: @author-action-required

#13437 [Kubernetes] Unit test for cluster launch and teardown using K8s Operator
  ci/travis/ci.sh
  python/ray/tests/BUILD
  python/ray/tests/test_k8s_operator_examples.py
Labels: @tests-ok

#13514 [core] Admission control for pulling objects to the local node
  .travis.yml
  BUILD.bazel
  python/ray/tests/test_object_manager.py
  python/ray/tests/test_object_spilling.py
  python/ray/tests/test_reconstruction.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_object_manager.cc
  src/ray/gcs/gcs_server/gcs_object_manager.h
  src/ray/object_manager/object_directory.cc
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/plasma/eviction_policy.h
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/plasma/store_runner.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/object_manager_stress_test.cc
  src/ray/object_manager/test/object_manager_test.cc
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/raylet/reconstruction_policy.cc
  src/ray/raylet/reconstruction_policy_test.cc
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/test/run_object_manager_tests.sh
Labels: @author-action-required

#13604 [Java] Add `fetchLocal` parameter in `Ray.wait()`
  java/api/src/main/java/io/ray/api/Ray.java
  java/api/src/main/java/io/ray/api/runtime/RayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/object/LocalModeObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/object/NativeObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectStore.java
  java/test.sh
  java/test/pom.xml
  java/test/src/main/java/io/ray/test/PlasmaFreeTest.java
  java/test/src/main/java/io/ray/test/ReferenceCountingTest.java
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.h
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskExecutor.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.h
Labels: @author-action-required, java

#13501 [Metrics] Cache metrics ports in a file at each node
  python/ray/node.py
  python/ray/tests/test_metrics_agent.py
Labels: @tests-ok

#13571 [Metrics] Fix serialization for custom metrics
  python/ray/tests/test_metrics_agent.py
  python/ray/util/metrics.py
Labels: @tests-ok

#13636 [Dependencies] Move requirements.txt to requirements directory.
  .github/dependabot.yml
  ci/travis/install-dependencies.sh
  python/requirements/requirements.txt
  python/requirements/requirements_tune.in
  python/setup.py
Labels: @tests-ok

#13458 [horovod] Horovod+Ray Pytorch Lightning Accelerator
  .travis.yml
  python/ray/tune/examples/mnist_ptl_mini.py
  python/ray/util/lightning_accelerators/BUILD
  python/ray/util/lightning_accelerators/__init__.py
  python/ray/util/lightning_accelerators/examples/ptl_horovod_ray_example.py
  python/ray/util/lightning_accelerators/horovod_ray_accelerator.py
  python/ray/util/lightning_accelerators/tests/test_horovod_ray_accelerator.py
Labels: @tests-ok

#13637 deprecate useless fields in the cluster yaml.
  dashboard/modules/reporter/reporter_head.py
  doc/examples/lm/lm-cluster.yaml
  python/ray/autoscaler/ray-schema.json
  python/ray/serve/benchmarks/cluster.yaml
  python/ray/tests/test_cli_patterns/test_ray_up_config.yaml
  python/ray/tests/test_cli_patterns/test_ray_up_docker_config.yaml
  python/ray/tests/test_coordinator_server.py
  python/ray/util/sgd/tf/examples/tf-example-sgd.yaml
  python/ray/util/sgd/torch/examples/benchmarks/README.rst
  python/ray/util/sgd/torch/examples/benchmarks/horovod-benchmark.yaml
  python/ray/util/sgd/torch/examples/example-sgd.yaml
  python/ray/util/sgd/torch/examples/image_models/cluster.yaml
  python/ray/util/sgd/torch/examples/segmentation/example.yaml
  python/ray/util/sgd/torch/examples/sgd-development.yaml
  python/ray/util/sgd/torch/examples/transformers/cluster.yaml
  release/horovod_tests/cluster.yaml
  release/long_running_distributed_tests/cluster.yaml
  release/rllib_tests/stress_tests/cluster.yaml
  release/stress_tests/autoscaler-cluster.yaml
  release/stress_tests/cluster.yaml
  release/tune_tests/scalability_tests/cluster.yaml
  release/xgboost_tests/cluster_cpu_moderate.yaml
  release/xgboost_tests/cluster_cpu_small.yaml
  release/xgboost_tests/cluster_gpu_small.yaml
Labels: @tests-ok

#13679 [RLlib] MAML: Add cartpole mass test for PyTorch.
  python/requirements_rllib.txt
  rllib/agents/maml/tests/test_maml.py
  rllib/examples/env/cartpole_mass.py
  rllib/examples/env/pendulum_mass.py
Labels: @tests-ok

#12708 [rllib] move evaluation to trainer.step() such that the result is properly logged
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
Labels: @tests-ok

#13464 Scalability Envelope Tests
  benchmarks/README.md
  benchmarks/distributed/config.yaml
  benchmarks/distributed/test_distributed.py
  benchmarks/object_store/config.yaml
  benchmarks/object_store/test_object_store.py
  benchmarks/single_node/config.yaml
  benchmarks/single_node/test_single_node.py
  release/RELEASE_PROCESS.rst
Labels: @tests-ok

#13375 [Logging] Log rotation config
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/tests/test_logging.py
  python/ray/workers/default_worker.py
  src/ray/common/ray_config_def.h
  src/ray/util/logging.cc
Labels: @author-action-required

#13649 [Object Spilling] Clean up FS storage upon sigint for ray.init().
  python/ray/external_storage.py
  python/ray/node.py
  python/ray/tests/test_object_spilling.py
  python/ray/worker.py
Labels: @author-action-required

#13695 [Serve] Fix ServeHandle serialization
  python/ray/serve/api.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_handle.py
Labels: @tests-ok

#13738 [Docker] Start in $HOME
  docker/base-deps/Dockerfile
Labels: @tests-ok

#13724 Fix high CPU usage in object manager due to O(n^2) iteration over active pulls list
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#13727 [Core/Autoscaler] Properly clean up resource backlog from
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#13746 [Object Spilling] Remove job id from the io worker log name.
  python/ray/ray_logging.py
Labels: @author-action-required

#13688 [Core] Add private on_completed callback for ObjectRef
  python/ray/_raylet.pyx
  python/ray/includes/object_ref.pxi
  python/ray/tests/test_asyncio.py
Labels: @author-action-required

#13558 [autoscaler][AWS] Make sure subnets belong to same VPC as user-specified security groups
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/aws/example-head-and-worker-security-group.yaml
  python/ray/tests/aws/test_autoscaler_aws.py
  python/ray/tests/aws/utils/constants.py
  python/ray/tests/aws/utils/stubs.py
Labels: @tests-ok

#13754 [Core] Hotfix Windows Compilation Error for ClusterTaskManager
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @tests-ok

#13640 [Serve] Add ServeHandle metrics
  doc/source/serve/advanced.rst
  python/ray/serve/handle.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_router.py
Labels: @tests-ok

#13737 [core] Pin arguments during task execution
  python/ray/tests/test_object_manager.py
  python/ray/tests/test_object_spilling.py
  src/ray/raylet/dependency_manager.cc
  src/ray/raylet/dependency_manager.h
  src/ray/raylet/dependency_manager_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/test/util.h
Labels: @author-action-required

#11667 [Dashboard] Add the new dashboard code and prompt users to try it
  dashboard/client/package-lock.json
  dashboard/client/package.json
  dashboard/client/src/App.tsx
  dashboard/client/src/api.ts
  dashboard/client/src/components/ActorTable.tsx
  dashboard/client/src/components/Loading.tsx
  dashboard/client/src/components/LogView/LogVirtualView.tsx
  dashboard/client/src/components/LogView/darcula.css
  dashboard/client/src/components/LogView/github.css
  dashboard/client/src/components/LogView/index.css
  dashboard/client/src/components/PercentageBar.tsx
  dashboard/client/src/components/SearchComponent.tsx
  dashboard/client/src/components/SpeedTools.tsx
  dashboard/client/src/components/StatesCounter.tsx
  dashboard/client/src/components/StatusChip.tsx
  dashboard/client/src/components/TitleCard.tsx
  dashboard/client/src/components/WorkerTable.tsx
  dashboard/client/src/logo.svg
  dashboard/client/src/pages/actor/index.tsx
  dashboard/client/src/pages/cmd/CMDResult.tsx
  dashboard/client/src/pages/dashboard/Dashboard.tsx
  dashboard/client/src/pages/error/404.tsx
  dashboard/client/src/pages/exception/Loading.tsx
  dashboard/client/src/pages/index/Index.tsx
  dashboard/client/src/pages/job/JobDetail.tsx
  dashboard/client/src/pages/job/hook/useJobDetail.ts
  dashboard/client/src/pages/job/hook/useJobList.ts
  dashboard/client/src/pages/job/index.tsx
  dashboard/client/src/pages/layout/index.tsx
  dashboard/client/src/pages/log/Logs.tsx
  dashboard/client/src/pages/node/NodeDetail.tsx
  dashboard/client/src/pages/node/hook/useNodeDetail.ts
  dashboard/client/src/pages/node/hook/useNodeList.ts
  dashboard/client/src/pages/node/index.tsx
  dashboard/client/src/service/actor.ts
  dashboard/client/src/service/cluster.ts
  dashboard/client/src/service/job.ts
  dashboard/client/src/service/log.ts
  dashboard/client/src/service/node.ts
  dashboard/client/src/service/util.ts
  dashboard/client/src/theme.ts
  dashboard/client/src/type/actor.ts
  dashboard/client/src/type/config.d.ts
  dashboard/client/src/type/event.d.ts
  dashboard/client/src/type/job.d.ts
  dashboard/client/src/type/node.d.ts
  dashboard/client/src/type/raylet.d.ts
  dashboard/client/src/type/worker.d.ts
  dashboard/client/src/util/converter.ts
  dashboard/client/src/util/func.tsx
  dashboard/client/src/util/hook.ts
  dashboard/client/src/util/localData.ts
Labels: dashboard

#13779 [autoscaler] Better validation for min_workers and max_workers
  python/ray/autoscaler/_private/util.py
  python/ray/tests/test_autoscaler_yaml.py
Labels: @tests-ok

#13471 [Serialization] API for unregistering serializers; code & doc cleanup
  doc/source/serialization.rst
  python/ray/actor.py
  python/ray/serialization.py
  python/ray/tests/test_serialization.py
  python/ray/util/__init__.py
  python/ray/util/serialization.py
Labels: @tests-ok, core-api-change-approval-required

#13782 [core] Add debug information for the PullManager and LocalObjectManager
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
Labels: @author-action-required

#13811 Fix windows test
  python/ray/autoscaler/_private/util.py
  python/ray/tests/test_autoscaler_yaml.py
Labels: @tests-ok
