Repository ray-project/ray, pull requests merged in 2021-02, with the labels that each got.

#13734 support dynamic library loading in C++ worker
  ci/travis/bazel-format.sh
  ci/travis/ci.sh
  cpp/BUILD.bazel
  cpp/dev_BUILD.bazel
  cpp/example/BUILD.bazel
  cpp/example/example.cc
  cpp/include/ray/api/ray_config.h
  cpp/include/ray/experimental/default_worker.h
  cpp/src/example/example.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/test/cluster/cluster_mode_test.cc
  cpp/src/ray/util/function_helper.cc
  cpp/src/ray/worker/default_worker.cc
  doc/source/index.rst
  python/ray/_private/services.py
Labels: @tests-ok

#13781 [core][object spillin] Fix bugs in admission control
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/pull_manager.cc
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#13722 [ray_client]: Add python version check and test (and some minor fixes along the way)
  python/ray/tests/test_client_init.py
  python/ray/tests/test_client_references.py
  python/ray/util/client/__init__.py
  python/ray/util/client/ray_client_helpers.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/server/server.py
Labels: @tests-ok

#13808 [AWS] Fill-in AMI if not provided
  python/ray/autoscaler/_private/aws/config.py
  python/ray/tests/aws/test_autoscaler_aws.py
Labels: @tests-ok

#13831 [Object Spilling] Skip normal ray.get path when spilling objects.
  python/ray/_raylet.pyx
  python/ray/external_storage.py
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
Labels: @author-action-required

#13442 Revert "Revert "Enable Ray client server by default (#13350)" (#13429)"
  cpp/src/ray/util/process_helper.cc
  doc/source/ray-client.rst
  python/ray/scripts/scripts.py
  python/ray/tests/test_job.py
Labels: @tests-ok

#13846 Add Ray client protocol version
  python/ray/tests/test_client_init.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/worker.py
  src/ray/protobuf/ray_client.proto
Labels: @tests-ok

#13556 [RLLIB] trainer._validate_config idempotentcy correction (issue 13427)
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/tests/test_trainer.py
Labels: @tests-ok

#13764 [RLlib] Fix get action shape
  rllib/policy/policy.py
Labels: @tests-ok

#13786 [RLlib] Trajectory view API example script (enhancements and tf2 support).
  rllib/BUILD
  rllib/examples/models/trajectory_view_utilizing_models.py
  rllib/examples/trajectory_view_api.py
  rllib/models/torch/misc.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/torch_policy.py
Labels: @tests-ok

#13733 [RLlib] Unify fcnet initializers for the value output layer (std=1.0 in torch, but 0.01 in tf).
  rllib/models/torch/fcnet.py
Labels: @tests-ok

#13633 Add podman support
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/_private/docker.py
  python/ray/autoscaler/ray-schema.json
  python/ray/tests/test_autoscaler.py
Labels: @tests-ok

#13852 [GCS]Fix bug that total_commands_queued_ is not initialized
  src/ray/gcs/pubsub/gcs_pub_sub.h
Labels: @author-action-required

#13778 Move the tune driver into a remote task
  python/ray/tune/BUILD
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/tests/test_remote.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_trial_runner_callbacks.py
  python/ray/tune/trial.py
  python/ray/tune/tune.py
Labels: @author-action-required

#13871 [Core] Put raylet ip's in resource usage report
  python/ray/tests/test_global_state.py
  src/ray/protobuf/gcs.proto
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#13639 [ray_client] convert things registered for ray into ray_client
  python/ray/_private/client_mode_hook.py
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/tests/test_client_init.py
  python/ray/util/client/api.py
  python/ray/util/client/common.py
  python/ray/util/client/options.py
  python/ray/util/client/worker.py
  python/ray/worker.py
Labels: @author-action-required

#13853 [Object Spilling] Add consumed bytes to detect thrashing.
  python/ray/internal/internal_api.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_memstat.py
  python/ray/tests/test_object_spilling.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/plasma/plasma.fbs
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/protocol.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/plasma/store_runner.cc
  src/ray/object_manager/plasma/store_runner.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#13841 [Core] Ownership-based Object Directory - Changed infinite short-poll location subscription to long-poll.
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/protobuf/core_worker.proto
Labels: @author-action-required

#13720 [autoscaler][kubernetes] Add ability to not copy cluster config to head node when calling `create_or_update_head_node`.
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/kubernetes/operator_configs/example_cluster.yaml
  python/ray/autoscaler/kubernetes/operator_configs/example_cluster2.yaml
  python/ray/ray_operator/operator.py
  python/ray/tests/BUILD
  python/ray/tests/test_k8s_operator_mock.py
Labels: @tests-ok

#13856 [GCS]Fix bug that gcs client does not set last_resource_usage_
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/raylet/node_manager.task.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_interface.h
  src/ray/raylet/scheduling/old_cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/old_cluster_resource_scheduler.h
Labels: @author-action-required

#13866 Buildkite determine-to-run support
  .buildkite/pipeline.yml
Labels: @tests-ok

#13793 [Java] fix actor restart failure when multi-worker is turned on
  java/test/src/main/java/io/ray/test/ActorRestartTest.java
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: java

#13919 [ray_client] close ray connection upon client deactivation
  ci/travis/ci.sh
  python/ray/tests/BUILD
  python/ray/tests/test_client_init.py
  python/ray/tests/test_job.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/server/server.py
  python/ray/util/client/worker.py
Labels: @author-action-required

#13584 [RLlib] Extend on_learn_on_batch callback to allow for custom metrics to be added.
  rllib/BUILD
  rllib/agents/callbacks.py
  rllib/agents/marwil/tests/test_marwil.py
  rllib/agents/sac/sac_tf_model.py
  rllib/agents/sac/sac_torch_model.py
  rllib/env/policy_client.py
  rllib/env/policy_server_input.py
  rllib/evaluation/metrics.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/custom_metrics_and_callbacks.py
  rllib/examples/serving/cartpole_client.py
  rllib/examples/serving/cartpole_server.py
  rllib/execution/metric_ops.py
  rllib/execution/train_ops.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
  rllib/tests/test_supported_multi_agent.py
  rllib/tests/test_supported_spaces.py
  rllib/utils/sgd.py
Labels: @tests-ok

#13909 [Doc] Update actor resource information
  doc/source/actors.rst
Labels: @author-action-required

#13254 [Core]Fix ray.kill doesn't cancel pending actor bug
  java/test/src/main/java/io/ray/test/KillActorTest.java
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_queue.py
  python/ray/tests/test_reference_counting.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: @author-action-required

#14002 [autoscaler/dashboard] Publish resource usage in units of bytes
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/autoscaler/_private/util.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @tests-ok

#13951 [dask-on-ray] Add multiple return DataFrame shuffle optimization.
  python/ray/tests/test_dask_optimization.py
  python/ray/util/dask/__init__.py
  python/ray/util/dask/optimizations.py
  python/ray/util/dask/scheduler.py
Labels: @author-action-required

#13970 [Autoscaler] Monitor refactor for backward compatability.
  python/ray/monitor.py
  python/ray/tests/test_multi_node_2.py
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
Labels: @tests-ok

#14017 Add tip on how to disable Ray OOM handler
  python/ray/memory_monitor.py
Labels: @tests-ok

#13944 [core] Fix bug in memory accounting
  src/ray/object_manager/plasma/store.cc
Labels: @author-action-required

#13950 [dask-on-ray] Add better Dask-on-Ray example, and detail custom shuffle optimization.
  doc/source/dask-on-ray.rst
  doc/source/index.rst
  doc/source/memory-management.rst
Labels: @author-action-required

#13836 [autoscaler] run setup commands with restart_only=True
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/updater.py
  python/ray/tests/test_autoscaler.py
Labels: @tests-ok

#14059 [Tune] Revert Pinning Tune Dependencies
  .github/dependabot.yml
  ci/travis/install-dependencies.sh
  docker/ray-ml/Dockerfile
  python/requirements.txt
  python/requirements/linux-py3.6-requirements_tune.txt
  python/requirements/linux-py3.7-requirements_tune.txt
  python/requirements/linux-py3.8-requirements_tune.txt
  python/requirements/requirements_tune.txt
Labels: @tests-ok

#14062 [hotfix] Disable dashboard agent windows
  dashboard/agent.py
Labels: @tests-ok

#14065 [Core] Ownership-based Object Directory - Disable the ownership-based object directory for all tests that use ray.objects()
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_client_references.py
  python/ray/tests/test_multi_node.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
Labels: @author-action-required

#14075 [hotfix] Fix mac build
  src/ray/core_worker/reference_count.cc
Labels: @tests-ok

#14061 Export additional metrics to Prometheus
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/tests/test_reporter.py
Labels: @tests-ok

#14001 [Serve] [Doc] Add version warning
  doc/source/serve/index.rst
Labels: @tests-ok

#13968 [Serve] Add support for variable routes
  doc/source/serve/advanced.rst
  python/ray/serve/controller.py
  python/ray/serve/endpoint_state.py
  python/ray/serve/http_proxy.py
  python/ray/serve/http_util.py
  python/ray/serve/tests/test_api.py
Labels: @tests-ok

#13798 Release process update
  release/RELEASE_CHECKLIST.md
  release/RELEASE_PROCESS.rst
  release/release_logs/1.2.0/microbenchmark.txt
  release/release_logs/1.2.0/notes.txt
  release/release_logs/1.2.0/rllib_regression_tf.txt
  release/release_logs/1.2.0/rllib_regression_torch.txt
  release/release_logs/1.2.0/scalability/distributed.txt
  release/release_logs/1.2.0/scalability/object_store.txt
  release/release_logs/1.2.0/scalability/single_node.txt
  release/release_logs/1.2.0/stress_tests/test_dead_actors.txt
  release/release_logs/1.2.0/stress_tests/test_many_tasks.txt
  release/release_logs/1.2.0/stress_tests/test_placement_group.txt
Labels: @tests-ok

#14113 Revert "Revert "Unhandled exception handler based on local ref counti…
  BUILD.bazel
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_failure.py
  python/ray/worker.py
  src/ray/common/ray_object.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
  src/ray/core_worker/store_provider/memory_store/memory_store.h
  src/ray/core_worker/test/memory_store_test.cc
Labels: @tests-ok

#14112 [autoscaler] Remove Hardcoded 8265
  python/ray/scripts/scripts.py
Labels: @tests-ok

#13904 [Object Spilling] Share the same S3 session for smart_open spilling.
  python/ray/external_storage.py
  python/ray/tests/test_object_spilling.py
Labels: @author-action-required

#14149 [Object Spilling] Fix the race condition.
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#14031 [RLlib] Issue #14022: Trajectory View API fails in MA-env where a new agent terminates right away (done=True right after initial obs).
  rllib/evaluation/sampler.py
  rllib/examples/env/multi_agent.py
  rllib/tests/test_multi_agent_env.py
Labels: @tests-ok

#14167 [ray_client]: Skip flaky test_cancel_chain on Windows
  python/ray/tests/test_client_terminate.py
Labels: @tests-ok

#14174 [ray_client]: Fix error logging from deserializing actual Exceptions
  python/ray/tests/test_client.py
  python/ray/util/client/worker.py
Labels: @tests-ok

#14034 [RLlib] Issue #13824: `compress_observations=True` crashes for all algos not using a replay buffer.
  rllib/agents/dqn/simple_q.py
  rllib/agents/dqn/tests/test_simple_q.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/evaluation/rollout_worker.py
  rllib/execution/train_ops.py
Labels: @tests-ok

#14183 [Core] Fix grpc server is started check
  python/ray/cluster_utils.py
  python/ray/tests/test_failure.py
  src/ray/common/ray_config_def.h
  src/ray/rpc/grpc_server.cc
Labels: @author-action-required

#12823 [Java] Simplify Java unit test configuration
  java/runtime/src/test/java/io/ray/runtime/config/RayConfigTest.java
  java/test/src/main/java/io/ray/test/ClassLoaderTest.java
  java/test/src/main/java/io/ray/test/CrossLanguageInvocationTest.java
  java/test/src/main/java/io/ray/test/FailureTest.java
  java/test/src/main/java/io/ray/test/GcsClientTest.java
  java/test/src/main/java/io/ray/test/GlobalGcTest.java
  java/test/src/main/java/io/ray/test/JobConfigTest.java
  java/test/src/main/java/io/ray/test/KillActorTest.java
  java/test/src/main/java/io/ray/test/NodeIpTest.java
  java/test/src/main/java/io/ray/test/RayletConfigTest.java
  java/test/src/main/java/io/ray/test/RedisPasswordTest.java
  java/test/src/main/java/io/ray/test/ReferenceCountingTest.java
  java/test/src/main/java/io/ray/test/ResourcesManagementTest.java
  java/test/src/main/java/io/ray/test/RuntimeContextTest.java
  java/test/src/main/java/io/ray/test/SystemPropertyListener.java
  java/testng.xml
Labels: java

#14176 [Tune] Raise error when PBT is used with search algorithm
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/trial_runner.py
Labels: @tests-ok

#14221 Handle unhandled exception handler == nullptr in Java
  src/ray/core_worker/core_worker.cc
Labels: @author-action-required

#14222 [core] Fix bugs in admission control again
  python/ray/state.py
  python/ray/tests/BUILD
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_scheduling.py
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/object_buffer_pool.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/pull_manager_test.cc
Labels: @author-action-required

#13860 [Core] Simplify system config passing from Raylet to workers
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GcsClient.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GlobalStateAccessor.java
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  java/runtime/src/main/resources/ray.default.conf
  java/runtime/src/test/java/io/ray/runtime/config/RayConfigTest.java
  java/test/src/main/java/io/ray/test/RayletConfigTest.java
  python/ray/_private/services.py
  python/ray/workers/default_worker.py
  src/ray/common/constants.h
  src/ray/common/ray_config.h
  src/ray/common/test_util.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.h
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.h
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/global_state_accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: @author-action-required

#14201 [autoscaler] Max worker default infinity
  doc/source/cluster/config.rst
  doc/source/cluster/kubernetes.rst
  python/ray/autoscaler/_private/kubernetes/config.py
  python/ray/autoscaler/_private/util.py
  python/ray/test_utils.py
  python/ray/tests/test_autoscaler_yaml.py
  python/ray/tests/test_cli_patterns/test_multi_node.yaml
Labels: @author-action-required

#14210 [Core] Some small fixes and improvements
  cpp/src/ray/runtime/local_mode_ray_runtime.cc
  python/ray/includes/libcoreworker.pxd
  src/ray/common/id.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/profiling.cc
  src/ray/core_worker/profiling.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/raylet/worker_pool.cc
Labels: @author-action-required

#13821 [Placement Group] Support named placement group java api & Refactor construct method
  java/api/src/main/java/io/ray/api/Ray.java
  java/api/src/main/java/io/ray/api/options/PlacementGroupCreationOptions.java
  java/api/src/main/java/io/ray/api/runtime/RayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GcsClient.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GlobalStateAccessor.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskSubmitter.java
  java/runtime/src/main/java/io/ray/runtime/task/NativeTaskSubmitter.java
  java/runtime/src/main/java/io/ray/runtime/task/TaskSubmitter.java
  java/test/src/main/java/io/ray/test/PlacementGroupTest.java
  java/test/src/main/java/io/ray/test/PlacementGroupTestUtils.java
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.h
  src/ray/core_worker/lib/java/jni_init.cc
  src/ray/core_worker/lib/java/jni_utils.h
Labels: java

#14219 [Core - Autoscaler] Upon autoscaler failure, propagate error message to all current and future drivers
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/monitor.py
  python/ray/tests/test_failure.py
  python/ray/worker.py
Labels: @author-action-required

#14202 [core] Start less worker processes
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @author-action-required, @tests-ok

#14241 Small improvements to the Ray Cluster docs
  doc/source/cluster/commands.rst
  doc/source/cluster/index.rst
  doc/source/cluster/quickstart.rst
  doc/source/cluster/ray-cluster.jpg
Labels: @author-action-required, fix-docs

#14263 [Tune] Fix test_convergence_gaussian_process in Buildkite
  python/ray/tune/tests/test_convergence_gaussian_process.py
Labels: @tests-ok

#14266 [Core] Start the non-primary Redis shard port range at a high random port.
  python/ray/_private/services.py
Labels: @tests-ok

#14240 [Object Spilling] Support multiple directories for spilling.
  doc/source/memory-management.rst
  python/ray/external_storage.py
  python/ray/tests/test_object_spilling.py
Labels: @author-action-required

#13618 [Core] Revert "Revert "Inline small objects in GetObjectStatus response. (#13309)" (#13615)"
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_advanced.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/future_resolver.h
  src/ray/protobuf/core_worker.proto
Labels: @tests-ok

#14287 [Monitor] Log some diagnosis information on startup
  python/ray/monitor.py
Labels: @author-action-required

#13858 [Placement Group] Make the creation of placement group sync
  python/ray/tests/test_placement_group.py
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
Labels: @tests-ok

#13763 [Dashboard] Select port in dashboard
  cpp/src/ray/util/process_helper.cc
  dashboard/agent.py
  dashboard/consts.py
  dashboard/dashboard.py
  dashboard/head.py
  dashboard/modules/stats_collector/tests/test_stats_collector.py
  dashboard/tests/test_dashboard.py
  python/ray/_private/services.py
  python/ray/ray_constants.py
  python/ray/test_utils.py
  python/ray/tests/test_multi_node_3.py
Labels: @tests-ok

#14280 [Tune] WandbLoggerCallback compatibility with Ray Client
  python/ray/tune/callback.py
  python/ray/tune/integration/wandb.py
  python/ray/tune/tests/test_integration_wandb.py
  python/ray/tune/trial_runner.py
Labels: @tests-ok

#13963 [Core]Pull off timers out of heartbeat in raylet
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/profiling.cc
  src/ray/core_worker/profiling.h
  src/ray/gcs/gcs_client/service_based_gcs_client.cc
  src/ray/gcs/gcs_client/service_based_gcs_client.h
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.cc
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.h
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.cc
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/util/periodical_runner.cc
  src/ray/util/periodical_runner.h
Labels: @tests-ok

#14310 Add debug_state.txt to cluster dump
  python/ray/autoscaler/_private/cluster_dump.py
  python/ray/autoscaler/_private/commands.py
  python/ray/scripts/scripts.py
Labels: @author-action-required

#14282 [Core] Locality-aware leasing: Milestone 2 - Owned refs, cached locations
  python/ray/tests/test_scheduling.py
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
Labels: @tests-ok

#14330 Use more IO workers by default
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#14256 [Serve] [Doc] Add basic Serve tutorial
  doc/source/index.rst
  doc/source/serve/advanced.rst
  doc/source/serve/core-apis.rst
  doc/source/serve/index.rst
  doc/source/serve/tutorial.rst
  doc/source/serve/tutorials/index.rst
Labels: @author-action-required

#14294 [dask-on-ray] Adds support for dask.persist() with inlined Ray futures.
  doc/source/dask-on-ray.rst
  python/ray/tests/test_dask_scheduler.py
  python/ray/util/dask/__init__.py
  python/ray/util/dask/scheduler.py
Labels: @tests-ok

#14296 [Core] Locality-aware leasing: Milestone 4 - Borrowed refs.
  python/ray/tests/test_scheduling.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/future_resolver.h
  src/ray/core_worker/lease_policy.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/protobuf/core_worker.proto
Labels: @tests-ok

#14329 [Core] Fix the issue with duplicated args
  python/ray/tests/test_advanced_3.py
  python/requirements.txt
  src/ray/object_manager/pull_manager.cc
  src/ray/raylet/dependency_manager.cc
Labels: @author-action-required

#14251 [Serve] Add logger with backend and replica tags
  doc/source/serve/deployment.rst
  doc/source/serve/package-ref.rst
  python/ray/serve/__init__.py
  python/ray/serve/api.py
  python/ray/serve/backend_worker.py
  python/ray/serve/examples/doc/backend_logger.py
  python/ray/serve/examples/doc/snippet_logger.py
  python/ray/serve/tests/test_api.py
Labels: @tests-ok
