Repository ray-project/ray, pull requests merged in 2021-04, with the labels that each got.

#15063 Fix c++ gcs test bug
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
Labels: @author-action-required

#15033 [Tests] Skip autoscaler tests on Windows
  ci/travis/ci.sh
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_command_runner.py
Labels: @author-action-required

#14790 [core] Hybrid scheduling policy.
  BUILD.bazel
  python/ray/tests/test_multi_node_3.py
  python/ray/tests/test_scheduling.py
  src/ray/common/ray_config_def.h
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/scheduling_policy.cc
  src/ray/raylet/scheduling/scheduling_policy.h
  src/ray/raylet/scheduling/scheduling_policy_test.cc
Labels: @author-action-required

#14925 [core] Fix UTIL worker issue
  python/ray/__init__.py
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/worker.py
  python/ray/workers/default_worker.py
  src/ray/core_worker/common.cc
  src/ray/core_worker/core_worker.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/util/util.h
Labels: @author-action-required, release-blocker

#15049 [core] Fix placement group GPU assignment bug
  python/ray/tests/test_placement_group.py
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/placement_group_resource_manager_test.cc
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_interface.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
Labels: @author-action-required, release-blocker

#15070 [Core] Fix the check failure from object manager.
  src/ray/object_manager/object_manager.cc
Labels: @author-action-required

#15064 [tune] Improve BOHB/ConfigSpace dependency check
  python/ray/tune/suggest/bohb.py
Labels: tune

#15000 [Serve] Set controller and HTTP proxy num_cpus=0 by default
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/serve/examples/doc/quickstart_class.py
  python/ray/serve/examples/doc/quickstart_function.py
  python/ray/serve/http_proxy.py
  python/ray/serve/http_state.py
  python/ray/serve/tests/test_standalone.py
Labels: @tests-ok

#15034 [Object Spilling] Limit number of objects to fuse
  src/ray/common/ray_config_def.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#15019 [autoscaler] Fix update/terminate race condition
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/kubernetes/node_provider.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_k8s_operator_examples.py
Labels: @tests-ok

#15071 [Core] Fix plasma store segfault
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
Labels: @author-action-required

#15059 [Core] Use static callback instead of dynamic notification listener
  BUILD.bazel
  src/ray/object_manager/common.h
  src/ray/object_manager/format/object_manager.fbs
  src/ray/object_manager/notification/object_store_notification_manager.h
  src/ray/object_manager/object_directory.cc
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/ownership_based_object_directory.h
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/connection.cc
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/plasma/store_runner.cc
  src/ray/object_manager/plasma/store_runner.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/raylet.h
Labels: @author-action-required

#15098 [flaky] Fix gcs test failure
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
Labels: @tests-ok

#15101 [kubernetes][autoscaler] Rename autoscaler K8s module
  python/ray/autoscaler/_private/_kubernetes/__init__.py
  python/ray/autoscaler/_private/_kubernetes/config.py
  python/ray/autoscaler/_private/_kubernetes/kubectl-rsync.sh
  python/ray/autoscaler/_private/_kubernetes/node_provider.py
  python/ray/autoscaler/_private/providers.py
  python/ray/ray_operator/operator_utils.py
  python/ray/tests/test_autoscaler_yaml.py
  python/ray/tests/test_k8s_cluster_launcher.py
  python/ray/tests/test_k8s_operator_mock.py
  python/setup.py
Labels: @tests-ok

#15092 [Serve] Un-revert #15000 Set controller and HTTP proxy num_cpus=0 by default
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/serve/examples/doc/quickstart_class.py
  python/ray/serve/examples/doc/quickstart_function.py
  python/ray/serve/http_proxy.py
  python/ray/serve/http_state.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_standalone.py
Labels: @tests-ok

#14906 continue hashing if data is none
  python/ray/_private/runtime_env.py
Labels: @tests-ok

#14656 [core] Internal kv support in gcs
  python/ray/__init__.py
  python/ray/_raylet.pyx
  python/ray/autoscaler/_private/monitor.py
  python/ray/experimental/internal_kv.py
  python/ray/includes/gcs_client.pxd
  python/ray/includes/gcs_client.pxi
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/BUILD
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_kv.py
  python/ray/tests/test_monitor.py
  python/ray/tests/test_multi_node_2.py
  python/ray/worker.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/gcs/accessor.cc
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/service_based_gcs_client.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/redis_context.cc
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: @tests-ok, release-blocker

#15117 [Code Cleanup] Rename to Allowlist + Denylist
  python/ray/_private/services.py
  python/ray/autoscaler/_private/cli_logger.py
  python/ray/node.py
Labels: @author-action-required

#15111 Unpack runtime env to runtime_resource
  python/ray/_private/runtime_env.py
  python/ray/_private/util_worker_handlers.py
  python/ray/tests/test_runtime_env.py
  python/ray/util/client/server/server.py
  python/ray/worker.py
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#14716 [metrics] Scheduler metrics
  python/ray/tests/test_metrics_agent.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/worker_pool.cc
  src/ray/stats/metric_defs.h
Labels: @tests-ok

#15116 [Pubsub] Generalize pubsub impl part 1
  python/ray/tests/test_reference_counting_2.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/pubsub/publisher.cc
  src/ray/core_worker/pubsub/publisher.h
  src/ray/core_worker/test/publisher_test.cc
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/pubsub/subscriber.cc
  src/ray/raylet/pubsub/subscriber.h
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/raylet/test/subscriber_test.cc
Labels: @author-action-required

#15171 [packaging] Remove stub_file deprecation path
  python/ray/experimental/packaging/load_package.py
Labels: @author-action-required

#15139 [Serve] [Doc] Add section on integrating with model registries
  doc/source/serve/ml-models.rst
Labels: @tests-ok

#15167 [serve] Change remaining tests to use deployment API
  python/ray/serve/api.py
  python/ray/serve/http_proxy.py
  python/ray/serve/tests/test_advanced.py
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/test_fastapi.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_http_routes.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_persistence.py
  python/ray/serve/tests/test_ray_client.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_standalone.py
  release/long_running_tests/workloads/serve.py
  release/long_running_tests/workloads/serve_failure.py
Labels: @author-action-required

#15184 Update ray client protocol version
  python/ray/util/client/__init__.py
Labels: @author-action-required

#15157 Prioritize worker requests for objects over queued task arguments
  python/ray/tests/test_object_manager.py
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/raylet/dependency_manager.cc
  src/ray/raylet/dependency_manager_test.cc
Labels: @author-action-required

#15185 [client][rllib] Add client_mode_hook for ray.get_gpu_ids
  python/ray/tests/BUILD
  python/ray/tests/test_client.py
  python/ray/tests/test_client_library_integration.py
  python/ray/util/client/__init__.py
  python/ray/util/client/api.py
  python/ray/worker.py
  rllib/examples/rock_paper_scissors_multiagent.py
Labels: @author-action-required

#15056 fix setproctitle break /proc/PID/environ
  python/ray/tests/test_environ.py
  src/ray/raylet/worker_pool.cc
Labels: bug

#14932 Fix unexpected error when handling the process that has exited in memory monitor.
  python/ray/_private/memory_monitor.py
Labels: bug

#15012 [RLlib] Add support for Int-Box action spaces.
  rllib/agents/es/es_tf_policy.py
  rllib/agents/es/es_torch_policy.py
  rllib/models/catalog.py
  rllib/models/tf/tf_action_dist.py
  rllib/models/torch/torch_action_dist.py
  rllib/tests/test_supported_spaces.py
  rllib/utils/exploration/random.py
Labels: @tests-ok

#15218 [RLlib] Discussion 1513: `on_episode_step()` callback called after very first reset (should not).
  rllib/evaluation/sampler.py
  rllib/examples/custom_metrics_and_callbacks.py
Labels: @tests-ok

#15236 [RLlib] Discussion 681: Metrics prepends newest episodes instead of appending.
  rllib/execution/metric_ops.py
Labels: @tests-ok

#15240 [Histogram] improve error message
  python/ray/util/metrics.py
Labels: @author-action-required

#15144 [Core] Event loop instrumentation - manual instrumentation hooks, instrumentation for deadline timer and local stream socket.
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/asio/instrumented_io_context.h
  src/ray/common/asio/periodical_runner.cc
  src/ray/common/asio/periodical_runner.h
  src/ray/common/client_connection.cc
  src/ray/common/client_connection.h
  src/ray/core_worker/profiling.cc
  src/ray/gcs/gcs_client/service_based_gcs_client.cc
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.cc
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_report_poller.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
Labels: @author-action-required

#15040 [RLlib] Support parallelizing evaluation and training (optional).
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
  rllib/examples/parallel_evaluation_and_training.py
Labels: @tests-ok

#15241 [runtime_env] Add support of exclusion
  python/ray/_private/runtime_env.py
  python/ray/experimental/packaging/load_package.py
  python/ray/tests/test_runtime_env.py
Labels: @tests-ok

#15172 [serve] Support normal args and kwargs for deployments
  python/ray/serve/api.py
  python/ray/serve/backend_worker.py
  python/ray/serve/handle.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_advanced.py
  python/ray/serve/tests/test_api_new.py
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_persistence.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/utils.py
Labels: @author-action-required

#15036 Optimize lambda copy to improve direct call performance.
  java/BUILD.bazel
  java/performance_test/pom.xml
  java/performance_test/pom_template.xml
  java/performance_test/src/main/java/io/ray/performancetest/Receiver.java
  java/performance_test/src/main/java/io/ray/performancetest/Source.java
  java/performance_test/src/main/java/io/ray/performancetest/test/ActorPerformanceTestBase.java
  java/performance_test/src/main/java/io/ray/performancetest/test/ActorPerformanceTestCase1.java
  java/test.sh
  src/ray/common/grpc_util.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/rpc/client_call.h
  src/ray/rpc/worker/core_worker_client.h
Labels: @author-action-required

#15285 [Buildkite] Fix Bazel Logs Upload
  .buildkite/copy_files.py
  .buildkite/pipeline.yml
Labels: @tests-ok

#15181 [Serialization] Pydantic -> `serialization_addons.py` and Ray Client support.
  python/ray/serialization.py
  python/ray/serialization_addons.py
  python/ray/serve/BUILD
  python/ray/serve/api.py
  python/ray/serve/tests/test_ray_client.py
  python/ray/serve/utils.py
  python/ray/tests/BUILD
  python/ray/tests/pydantic_module.py
  python/ray/tests/test_client.py
  python/ray/tests/test_pydantic_serialization.py
  python/ray/util/client/__init__.py
  python/ray/util/client/ray_client_helpers.py
Labels: @author-action-required

#15313 [core] Take care of failed killing request
  src/ray/raylet/worker_pool.cc
Labels: @tests-ok

#15310 Revert "Revert "[runtime_env] Add support of exclusion (#15241)" (#15303)" with fixing
  python/ray/_private/runtime_env.py
  python/ray/experimental/packaging/load_package.py
  python/ray/tests/test_runtime_env.py
Labels: @tests-ok

#15295 [RLlib] APEX returns incorrect default resources (PleacementGroupFactory) colocated missing replay actors.
  rllib/agents/dqn/apex.py
  rllib/agents/impala/impala.py
  rllib/agents/trainer.py
Labels: bug, release-blocker

#15338 [tune] Allow 0 CPU head bundles in for placement group factories
  python/ray/tune/tests/test_trial_runner_pg.py
  python/ray/tune/utils/placement_groups.py
Labels: release-blocker

#15325 Fix release test -- client remote put
  python/ray/_private/ray_client_microbenchmark.py
  python/ray/util/client/ray_client_helpers.py
Labels: release-blocker

#14709 [RLlib] Multi-GPU support for Torch algorithms.
  doc/source/rllib-algorithms.rst
  rllib/agents/ars/ars_tf_policy.py
  rllib/agents/es/es_tf_policy.py
  rllib/agents/es/es_torch_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/qmix/qmix_policy.py
  rllib/agents/sac/sac.py
  rllib/agents/sac/sac_torch_policy.py
  rllib/agents/sac/tests/test_sac.py
  rllib/agents/trainer.py
  rllib/examples/env/nested_space_repeat_after_me_env.py
  rllib/examples/env/repeat_after_me_env.py
  rllib/execution/train_ops.py
  rllib/models/catalog.py
  rllib/models/modelv2.py
  rllib/models/tests/test_distributions.py
  rllib/models/tf/tf_action_dist.py
  rllib/models/torch/torch_action_dist.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/policy/torch_policy.py
  rllib/utils/exploration/epsilon_greedy.py
  rllib/utils/exploration/exploration.py
  rllib/utils/exploration/random.py
  rllib/utils/exploration/stochastic_sampling.py
  rllib/utils/numpy.py
  rllib/utils/spaces/space_utils.py
  rllib/utils/tf_ops.py
  rllib/utils/torch_ops.py
Labels: @tests-ok

#15189 [Placement Group] Fix PlacementGroup ready when specify memory resource
  python/ray/tests/test_placement_group.py
  python/ray/util/placement_group.py
Labels: @author-action-required

#15334 [RLlib] Partial GPU example.
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/examples/env/gpu_requiring_env.py
  rllib/examples/env/simple_corridor.py
  rllib/examples/multi_agent_cartpole.py
  rllib/examples/partial_gpus.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
Labels: @tests-ok

#15292 [RLlib] Remove atari dependency for RLlib (in favor of detailed error message).
  python/requirements_rllib.txt
  python/setup.py
  rllib/agents/trainer.py
  rllib/env/utils.py
Labels: @tests-ok

#14703 [core] Take care of object spilling failure
  python/ray/_raylet.pyx
  python/ray/external_storage.py
  python/ray/tests/conftest.py
  python/ray/tests/test_object_spilling.py
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @tests-ok

#15411 [core] Fixing of actor creation failure
  src/ray/core_worker/core_worker.cc
  src/ray/raylet/worker_pool.cc
Labels: release-blocker

#15286 [runtime_env] Fix the some bugs related with runtime_env
  python/ray/_private/runtime_env.py
  python/ray/tests/test_runtime_env.py
  python/ray/worker.py
Labels: @tests-ok

#15420 [dev] Enable gitpod
  .gitignore
  .gitpod.yml
  .gitpod/Dockerfile
Labels: @tests-ok

#15429 ray health-check
  python/ray/ray_constants.py
  python/ray/scripts/scripts.py
  python/ray/tests/BUILD
  python/ray/tests/test_healthcheck.py
  python/ray/util/client/server/server.py
Labels: @author-action-required

#15380 [Azure][Autoscaler] Allow current user to use Docker
  python/ray/autoscaler/azure/defaults.yaml
  python/ray/autoscaler/azure/example-full-legacy.yaml
  python/ray/autoscaler/azure/example-full.yaml
  python/ray/autoscaler/azure/example-gpu-docker.yaml
Labels: @author-action-required

#15454 [RLlib] Remove all remaining tf- and MuJoCo warnings from RLlib.
  rllib/env/wrappers/dm_control_wrapper.py
  rllib/utils/framework.py
Labels: @tests-ok

#15451 [RLlib] Discussion 1759: SampleBatch._get_slice_indices stuck for R2D2 when using incorrect Trainer.
  rllib/policy/sample_batch.py
Labels: @tests-ok

#15382 [client][placement groups] Client placement group hooks, attempt #3
  python/ray/_private/client_mode_hook.py
  python/ray/tests/conftest.py
  python/ray/tests/test_client.py
  python/ray/tests/test_client_init.py
  python/ray/tests/test_placement_group.py
  python/ray/util/client/api.py
  python/ray/util/client/common.py
  python/ray/util/client/ray_client_helpers.py
  python/ray/util/client/server/server.py
  python/ray/util/client/worker.py
  python/ray/util/placement_group.py
Labels: @tests-ok

#15468 [tune] Add HEBO to search algorithm shim function
  python/ray/tune/suggest/__init__.py
Labels: @tests-ok

#15425 [Core] Add `concurrent.futures.Future` wrapper for ObjectRef
  doc/source/async_api.rst
  python/ray/includes/object_ref.pxi
  python/ray/tests/test_async.py
Labels: core-api-change-approval-required

#15361 [Core] Add "shim process" setup_worker.py that calls "conda activate" for runtime_env
  python/ray/_private/conda.py
  python/ray/_private/parameter.py
  python/ray/_private/runtime_env.py
  python/ray/_private/services.py
  python/ray/_private/utils.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/autoscaler/_private/constants.py
  python/ray/includes/common.pxd
  python/ray/job_config.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/remote_function.py
  python/ray/scripts/scripts.py
  python/ray/serve/backend_worker.py
  python/ray/serve/tests/test_util.py
  python/ray/serve/utils.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/worker.py
  python/ray/workers/setup_runtime_env.py
  python/ray/workers/setup_worker.py
  src/ray/common/constants.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/common.proto
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: @tests-ok

#15487 [CI] Run Flaky tests in macOS
  .buildkite/pipeline.yml
  .travis.yml
Labels: @author-action-required

#15120 [RLlib] Fix test_dependency_torch.
  rllib/agents/trainer.py
  rllib/examples/custom_logger.py
  rllib/tests/test_dependency_tf.py
  rllib/tests/test_dependency_torch.py
Labels: @tests-ok

#15448 [client] Add support for `ray.timeline()`
  python/ray/state.py
  python/ray/tests/test_advanced.py
  python/ray/util/client/api.py
  python/ray/util/client/server/server.py
  src/ray/protobuf/ray_client.proto
Labels: @author-action-required

#15530 [Hotfix] PyArrow version issue
  python/requirements.txt
Labels: @tests-ok

#14684 [RLlib] Support native tf.keras.Model (milestone toward obsoleting ModelV2 class).
  rllib/BUILD
  rllib/agents/ddpg/tests/test_ddpg.py
  rllib/agents/dqn/tests/test_simple_q.py
  rllib/agents/marwil/marwil_tf_policy.py
  rllib/agents/pg/tests/test_pg.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/sac/tests/test_sac.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/postprocessing.py
  rllib/examples/models/modelv3.py
  rllib/models/catalog.py
  rllib/models/modelv2.py
  rllib/models/tests/test_models.py
  rllib/models/tf/fcnet.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/rnn_sequencing.py
  rllib/policy/sample_batch.py
  rllib/policy/tests/test_sample_batch.py
  rllib/policy/tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/utils/exploration/random.py
Labels: @tests-ok

#15488 [Client] Asyncio Client, Sync gRPC Server
  python/ray/tests/BUILD
  python/ray/tests/test_asyncio.py
  python/ray/tests/test_client_library_integration.py
  python/ray/util/client/__init__.py
  python/ray/util/client/api.py
  python/ray/util/client/common.py
  python/ray/util/client/dataclient.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/server/server.py
  python/ray/util/client/worker.py
  src/ray/protobuf/ray_client.proto
Labels: @author-action-required

#15506 Fix reported dashboard ip when using 0.0.0.0
  dashboard/head.py
  dashboard/tests/test_dashboard.py
Labels: bug, dashboard

#15083 [core] Handle blocked worker crashes edge case
  python/ray/tests/test_component_failures_3.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#15524 [Serve] Nested actors should escape placement group
  python/ray/serve/backend_state.py
  python/ray/serve/tests/test_regression.py
Labels: @tests-ok

#15440 [API] Remove non-API top Level function imports
  dashboard/modules/logical_view/tests/test_logical_view_head.py
  python/ray/__init__.py
  python/ray/profiling.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/utils.py
  python/ray/test_utils.py
  python/ray/tests/BUILD
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_advanced.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_basic_3.py
  python/ray/tests/test_client_references.py
  python/ray/tests/test_client_terminate.py
  python/ray/tests/test_dashboard.py
  python/ray/tests/test_error_ray_not_initialized.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_global_state.py
  python/ray/tests/test_job.py
  python/ray/tests/test_metrics.py
  python/ray/tests/test_multi_node.py
  python/ray/tests/test_object_manager.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_reference_counting.py
  python/ray/tests/test_scheduling.py
  python/ray/tests/test_top_level_api.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
  python/ray/worker.py
Labels: @author-action-required, core-api-change-approval-required

#15476 [API] Remove Top Level, Non-Ray Modules
  python/ray/__init__.py
  python/ray/tests/test_top_level_api.py
Labels: core-api-change-approval-required

#15532 [client] Use `ensure_runtime_env_setup` in ray client.
  python/ray/util/client/server/server.py
Labels: @tests-ok

#15469 [kubernetes][autoscaler] Kubernetes operator basic fixes
  doc/source/cluster/kubernetes.rst
  python/ray/autoscaler/_private/_kubernetes/config.py
  python/ray/autoscaler/_private/_kubernetes/node_provider.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/autoscaler/kubernetes/example-full.yaml
  python/ray/autoscaler/kubernetes/operator_configs/example_cluster.yaml
  python/ray/autoscaler/kubernetes/operator_configs/example_cluster2.yaml
  python/ray/autoscaler/kubernetes/operator_configs/operator.yaml
  python/ray/autoscaler/kubernetes/operator_configs/operator_cluster_scoped.yaml
  python/ray/autoscaler/kubernetes/operator_configs/operator_namespaced.yaml
  python/ray/ray_operator/operator.py
  python/ray/ray_operator/operator_utils.py
  python/ray/tests/kubernetes_e2e/test_k8s_operator_examples.py
  python/ray/tests/kubernetes_e2e/test_k8s_operator_scaling.py
  python/ray/tests/test_k8s_operator_mock.py
Labels: @tests-ok

#15545 [Core] Prevent dedicated workers from being returned to general idle pool
  python/ray/tests/test_advanced_3.py
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: @tests-ok
