Repository ray-project/ray, pull requests merged in 2021-10, with the labels that each got.

#19025 [Lint] Update clang-tidy rules
  .clang-tidy
Labels: @tests-ok

#19000 [Scheduling] Report resource demand for infeasible 1-CPU tasks
  python/ray/tests/test_scheduling.py
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#19029 [core] Remove "plasma promotion" for serialized ObjectRefs
  python/ray/_raylet.pyx
  src/ray/core_worker/core_worker.cc
Labels: @author-action-required

#19003 [Workflow] Move arguments into workflow step context
  python/ray/workflow/execution.py
  python/ray/workflow/recovery.py
  python/ray/workflow/step_executor.py
  python/ray/workflow/workflow_access.py
  python/ray/workflow/workflow_context.py
  python/ray/workflow/workflow_storage.py
Labels: @tests-ok

#18842 [core] Update placement group retry implementation
  .bazelrc
  BUILD.bazel
  src/mock/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/mock/ray/gcs/gcs_server/gcs_resource_manager.h
  src/mock/ray/gcs/store_client/redis_store_client.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/raylet/scheduling/fixed_point.cc
  src/ray/raylet/scheduling/fixed_point.h
  src/ray/util/util.h
  src/ray/util/util_test.cc
Labels: @author-action-required

#19073 [Core][CoreWorker ThreadSafety 1/n] Ensure global_worker_ is protected by mutex
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
Labels: @author-action-required

#19034 [client] Undo PySpark's monkey patching of namedtuples for PickleStub
  python/ray/tests/BUILD
  python/ray/tests/test_client_compat.py
  python/ray/util/client/client_pickler.py
  python/requirements.txt
Labels: @tests-ok

#19090 [workflow] Avoid running workflow step multiple times.
  python/ray/workflow/execution.py
  python/ray/workflow/recovery.py
  python/ray/workflow/step_executor.py
  python/ray/workflow/tests/test_basic_workflows_2.py
Labels: @author-action-required

#18167 [core] Assign tasks to the first available worker
  .buildkite/pipeline.yml
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_basic_3.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  streaming/src/test/mock_actor.cc
Labels: @author-action-required

#19114 [client] Skip test_valid_actor_state tests on windows
  python/ray/tests/test_client_reconnect.py
Labels: @tests-ok

#19882 [Placement Group] Fix the implicit value change from uint32_t -> uint64_t for pg scheduling retry
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#19869 [Serve] [Serve Autoscaler] Base autoscaling decisions on target num replicas, not current num replicas
  python/ray/serve/autoscaling_policy.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_autoscaling_policy.py
Labels: @author-action-required

#19871 Bumped time limit in ``test_cancel::test_comprehensive``
  python/ray/tests/test_cancel.py
Labels: windows, testing

#19067 [runtime env] Move container related code to runtime env
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/container.py
  python/ray/_private/runtime_env/validation.py
  python/ray/workers/setup_worker.py
  src/ray/raylet/worker_pool.cc
Labels: @external-author-action-required

#19798 [serve] Rename BackendVersion -> DeploymentVersion
  java/serve/src/main/java/io/ray/serve/DeploymentInfo.java
  java/serve/src/main/java/io/ray/serve/RayServeReplica.java
  java/serve/src/main/java/io/ray/serve/RayServeWrappedReplica.java
  java/serve/src/main/java/io/ray/serve/util/ServeProtoUtil.java
  java/serve/src/test/java/io/ray/serve/ProxyActorTest.java
  java/serve/src/test/java/io/ray/serve/RayServeHandleTest.java
  java/serve/src/test/java/io/ray/serve/RayServeReplicaTest.java
  java/serve/src/test/java/io/ray/serve/ReplicaSetTest.java
  java/serve/src/test/java/io/ray/serve/RouterTest.java
  python/ray/serve/BUILD
  python/ray/serve/backend_state.py
  python/ray/serve/replica.py
  python/ray/serve/tests/test_backend_state.py
  python/ray/serve/tests/test_deployment_version.py
  python/ray/serve/version.py
  src/ray/protobuf/serve.proto
Labels: @author-action-required

#19912 Fix unused import warning in streaming.proto
  streaming/BUILD.bazel
  streaming/src/protobuf/streaming.proto
Labels: @tests-ok
