Repository ray-project/ray, pull requests merged in 2021-09, with the labels that each got.

#18176 Retry application-level errors
  cpp/src/ray/runtime/task/native_task_submitter.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  python/ray/_raylet.pyx
  python/ray/cross_language.py
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/test_failure_4.py
  python/ray/util/client/options.py
  python/ray/worker.py
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
Labels: @tests-ok

#17971 [core] Attach call site to ObjectRefs, print on error
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/task/native_task_submitter.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/exceptions.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/includes/object_ref.pxi
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/ray_constants.py
  python/ray/serialization.py
  python/ray/tests/test_failure_4.py
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/streaming/streaming.cc
  src/ray/streaming/streaming.h
  streaming/src/queue/transport.cc
  streaming/src/test/mock_actor.cc
  streaming/src/test/queue_tests_base.h
Labels: @author-action-required

#18155 Minor renaming and cleanups related to last rollout worker seed fix.
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/tests/test_rollout_worker.py
  rllib/utils/debug.py
Labels: @tests-ok

#18064 Abstract plasma store get request queue
  BUILD.bazel
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/connection.h
  src/ray/object_manager/plasma/get_request_queue.cc
  src/ray/object_manager/plasma/get_request_queue.h
  src/ray/object_manager/plasma/object_lifecycle_manager.h
  src/ray/object_manager/plasma/plasma.cc
  src/ray/object_manager/plasma/plasma.h
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/protocol.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/test/create_request_queue_test.cc
  src/ray/object_manager/test/get_request_queue_test.cc
Labels: @author-action-required

#18284 Avoid duplicate exports of functions
  python/ray/_private/function_manager.py
  python/ray/includes/function_descriptor.pxi
  python/ray/remote_function.py
  python/ray/tests/test_basic_3.py
Labels: @tests-ok

#18128 [workflow] object ref integration
  python/ray/experimental/workflow/common.py
  python/ray/experimental/workflow/recovery.py
  python/ray/experimental/workflow/serialization_context.py
  python/ray/experimental/workflow/tests/test_dataset.py
  python/ray/experimental/workflow/tests/test_object_deref.py
  python/ray/experimental/workflow/tests/test_storage.py
  python/ray/experimental/workflow/workflow_storage.py
Labels: @tests-ok, @author-action-required

#18208 Move RLLib GPU release test dependencies to ml docker
  .buildkite/Dockerfile
  .buildkite/Dockerfile.gpu
  ci/travis/build-docker-images.py
  ci/travis/install-dependencies.sh
  docker/ray-ml/Dockerfile
  python/requirements/rllib/requirements_rllib.txt
  python/requirements_ml_docker.txt
  release/rllib_tests/app_config.yaml
  rllib/utils/install_atari_roms.sh
Labels: @author-action-required

#18296 Retry application-level error by default for datasets
  python/ray/_raylet.pyx
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/impl/remote_fn.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.h
Labels: @tests-ok

#18218 [code oweners] Add Hao to autoscaler compatibility
  .github/CODEOWNERS
Labels: @author-action-required

#18336 Update release process doc and checklist
  release/RELEASE_CHECKLIST.md
  release/RELEASE_PROCESS.rst
Labels: @author-action-required

#18338 [tune] Queue more than more actor/placement group
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/tests/test_actor_reuse.py
Labels: @tests-ok

#18361 [Core][Datasets] Datasets schema should match the columns selection for Parquet
  python/ray/data/dataset.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#18350 Increase timeout for ProxyManager.get_channel
  python/ray/tests/test_client_proxy.py
  python/ray/util/client/server/proxier.py
Labels: @tests-ok

#18401 [Core][Plasma][GetRequestQueue] don't remove request twice
  src/ray/object_manager/plasma/get_request_queue.cc
  src/ray/object_manager/test/get_request_queue_test.cc
Labels: @author-action-required

#17575 [setup] Upstream conda patches
  python/setup.py
  src/ray/util/util.h
Labels: @tests-ok

#18288 [core] upgrade gtest
  BUILD.bazel
  bazel/ray_deps_setup.bzl
  src/mock/ray/core_worker/task_manager.h
  src/mock/ray/gcs/accessor.h
  src/ray/common/ray_config.h
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/object_manager/test/spilled_object_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/rpc/grpc_server.h
  streaming/src/test/streaming_queue_tests.cc
Labels: @tests-ok

#18406 [nightly] Add many_nodes_actor_test to nightly test
  release/.buildkite/build_pipeline.py
Labels: @tests-ok

#18444 [RLlib] Add locking to PolicyMap in case it is accessed by a RolloutWorker and the same worker's AsyncSampler at the same time.
  rllib/policy/policy_map.py
Labels: @tests-ok

#18435 [Datasets] Create directory on write if it doesn't exist.
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#17809 [Test] deflake test_runtime_env.py::test_no_spurious_worker_startup
  python/ray/tests/test_runtime_env.py
Labels: @tests-ok

#18428 [RLlib] Deepcopy env_ctx for vectorized sub-envs AND add eval-worker-option to `Trainer.add_policy()`
  rllib/agents/trainer.py
  rllib/env/env_context.py
  rllib/evaluation/rollout_worker.py
  rllib/examples/self_play_with_open_spiel.py
  rllib/execution/concurrency_ops.py
Labels: @tests-ok

#18367 [RLlib] No Preprocessors; preparatory PR #1
  rllib/BUILD
  rllib/agents/dqn/dqn_tf_policy.py
  rllib/agents/trainer.py
  rllib/env/multi_agent_env.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/examples/custom_observation_filters.py
  rllib/models/catalog.py
  rllib/models/modelv2.py
  rllib/models/preprocessors.py
  rllib/models/tf/complex_input_net.py
  rllib/models/torch/complex_input_net.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/utils/spaces/space_utils.py
Labels: @tests-ok

#17340 [Dataset] implement `from_spark`, `to_spark` and some optimizations
  python/ray/_raylet.pyx
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_raydp_dataset.py
  python/requirements/data_processing/requirements.txt
Labels: @author-action-required, size:medium

#18451 [Ray Client] [runtime env] Print error logs in driver upon connection failure
  python/ray/tests/test_client_proxy.py
  python/ray/util/client/server/proxier.py
Labels: @tests-ok

#18455 [cpp] Upgrade cpp from 14 -> 17
  .bazelrc
Labels: @tests-ok, @author-action-required

#18343 [CI] use clang for C++ tests
  .bazelrc
  .buildkite/Dockerfile
  .buildkite/pipeline.yml
  src/ray/object_manager/plasma/test/stats_collector_test.cc
Labels: @tests-ok

#18471 [runtime_env] Move URI deletion logic to the agent, remove util worker code
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/__init__.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/context.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/_private/util_worker_handlers.py
  python/ray/_raylet.pyx
  python/ray/tests/test_client.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/worker.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
  python/ray/workers/setup_runtime_env.py
  src/ray/core_worker/common.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/runtime_env_agent.proto
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/agent_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/rpc/runtime_env/runtime_env_client.h
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: @tests-ok

#18466 [RLlib] Better error messages and hints; + failure-mode tests;
  rllib/agents/trainer.py
  rllib/env/utils.py
  rllib/evaluation/rollout_worker.py
  rllib/tests/test_gpus.py
  rllib/utils/error.py
  rllib/utils/from_config.py
  rllib/utils/tests/test_errors.py
Labels: @tests-ok

#18383 [release] Also download Ray CPP wheels
  release/RELEASE_PROCESS.rst
  release/util/download_wheels.sh
Labels: @tests-ok

#18012 [GCS] Fix the Windows build of GCS actor scheduling
  BUILD.bazel
  python/ray/tests/test_advanced.py
  python/ray/tests/test_scheduling_performance.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/scheduling_resources.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/gcs_server/test/raylet_based_actor_scheduler_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
Labels: @author-action-required

#18526 Fix async actor worker process leak after calling ray.actor.exit_actor()
  python/ray/_raylet.pyx
  python/ray/tests/test_asyncio.py
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/fiber.h
  src/ray/object_manager/plasma/store.h
Labels: @tests-ok

#18293 [Serve FT] Add ability to recover from replica names
  python/ray/serve/BUILD
  python/ray/serve/backend_state.py
  python/ray/serve/backend_worker.py
  python/ray/serve/common.py
  python/ray/serve/constants.py
  python/ray/serve/controller.py
  python/ray/serve/tests/fault_tolerance_tests/test_controller_recovery.py
  python/ray/serve/tests/test_backend_state.py
  python/ray/serve/tests/test_common.py
  python/ray/serve/version.py
Labels: serve, @author-action-required

#18540 [RLlib] Multi-GPU learner thread (IMPALA) error messages/comments/code-cleanup.
  rllib/agents/impala/impala.py
  rllib/execution/multi_gpu_learner_thread.py
Labels: @tests-ok

#18452 Update API stability annotations
  python/ray/client_builder.py
  python/ray/tune/ray_trial_executor.py
Labels: @tests-ok

#18532 Don't pass in TaskID to TaskManager::MarkPendingTaskFailed since it can be got from TaskSpecification
  src/mock/ray/core_worker/task_manager.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_task_transport.cc
Labels: @tests-ok

#18504 [client] Make sure queue order matches req_id order
  python/ray/util/client/dataclient.py
Labels: release-blocker

#18292 [core][usability] Disambiguate ObjectLostErrors for better understandability
  cpp/src/ray/runtime/object/native_object_store.cc
  doc/source/troubleshooting.rst
  java/runtime/src/main/java/io/ray/runtime/object/ObjectSerializer.java
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/exceptions.py
  python/ray/includes/object_ref.pxi
  python/ray/serialization.py
  python/ray/tests/test_advanced.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_reconstruction.py
  python/ray/tests/test_reference_counting.py
  python/ray/tests/test_reference_counting_2.py
  python/ray/tests/test_traceback.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/object_recovery_manager.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/pubsub.proto
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#18508 [dashboard] add an endpoint to force kill an actor
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/tests/test_actors.py
Labels: release-blocker

#18568 Add reconfigure with exception test and ensure it can rollback
  python/ray/serve/tests/test_deploy.py
Labels: @tests-ok

#18566 Change serve tests docker image and enable micro benchmark
  python/ray/serve/benchmarks/microbenchmark.py
  release/.buildkite/build_pipeline.py
  release/serve_tests/app_config.yaml
Labels: @author-action-required

#18550 [RLlib] Fix R2D2 (torch) multi-GPU issue.
  release/rllib_tests/learning_tests/hard_learning_tests.yaml
  release/rllib_tests/multi_gpu_with_attention_learning_tests/multi_gpu_with_attention_learning_tests.yaml
  release/rllib_tests/multi_gpu_with_lstm_learning_tests/multi_gpu_with_lstm_learning_tests.yaml
  rllib/BUILD
  rllib/agents/cql/cql_tf_policy.py
  rllib/agents/dqn/r2d2_tf_policy.py
  rllib/agents/dqn/r2d2_torch_policy.py
  rllib/policy/rnn_sequencing.py
  rllib/policy/sample_batch.py
  rllib/policy/tests/test_sample_batch.py
  rllib/tuned_examples/dqn/stateless-cartpole-r2d2-fake-gpus.yaml
Labels: @tests-ok

#18484 [client] Refactors for reconnect PR
  python/ray/util/client/common.py
  python/ray/util/client/dataclient.py
  python/ray/util/client/logsclient.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/worker.py
Labels: release-blocker

#18612 [Test] Break down placement group tests
  .buildkite/windows/install/tests.ps1
  python/ray/_private/test_utils.py
  python/ray/tests/BUILD
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_placement_group_2.py
  python/ray/tests/test_placement_group_3.py
  python/ray/tests/test_placement_group_mini_integration.py
Labels: @author-action-required

#18467 [RLlib] Rename `rllib rollout` into `rllib evaluate` (backward compatible) to match Trainer API.
  rllib/BUILD
  rllib/evaluate.py
  rllib/rollout.py
  rllib/scripts.py
  rllib/tests/test_nested_observation_spaces.py
  rllib/tests/test_rllib_train_and_evaluate.py
Labels: @tests-ok

#18203 Define protobuf for RequestMetadata and HTTPRequestWrapper
  java/serve/src/main/java/io/ray/serve/Query.java
  java/serve/src/main/java/io/ray/serve/RayServeReplica.java
  java/serve/src/main/java/io/ray/serve/RayServeWrappedReplica.java
  java/serve/src/main/java/io/ray/serve/RequestMetadata.java
  java/serve/src/main/java/io/ray/serve/util/BackendConfigUtil.java
  java/serve/src/main/java/io/ray/serve/util/ServeProtoUtil.java
  java/serve/src/test/java/io/ray/serve/RayServeReplicaTest.java
  src/ray/protobuf/serve.proto
Labels: enhancement, serve

#17835 [Serve] Use BackendConfig Protobuf
  .gitignore
  BUILD.bazel
  python/ray/serve/api.py
  python/ray/serve/backend_state.py
  python/ray/serve/backend_worker.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_config.py
  python/ray/serve/tests/test_router.py
  python/setup.py
  src/ray/protobuf/BUILD
Labels: @author-action-required

#18598 Fix debug log defeat in new scheduler
  src/ray/raylet/scheduling/cluster_resource_data.cc
Labels: @author-action-required

#18184 [RLlib] Add `worker` arg (optional) to `policy_mapping_fn`.
  rllib/agents/tests/test_trainer.py
  rllib/env/wrappers/unity3d_env.py
  rllib/evaluation/episode.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/examples/hierarchical_training.py
  rllib/examples/multi_agent_cartpole.py
  rllib/examples/multi_agent_two_trainers.py
  rllib/examples/restore_1_of_n_agents_from_checkpoint.py
  rllib/examples/self_play_league_based_with_open_spiel.py
  rllib/examples/self_play_with_open_spiel.py
  rllib/examples/two_trainer_workflow.py
  rllib/tests/test_multi_agent_env.py
Labels: @tests-ok

#18644 [Datasets] Properly support fs inference on path with space.
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#18329 [client] let ray client reconnect on grpc failures
  python/ray/ray_constants.py
  python/ray/tests/BUILD
  python/ray/tests/test_client_reconnect.py
  python/ray/tests/test_dataclient_disconnect.py
  python/ray/tests/test_response_cache.py
  python/ray/util/client/__init__.py
  python/ray/util/client/common.py
  python/ray/util/client/dataclient.py
  python/ray/util/client/logsclient.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/server/server.py
  python/ray/util/client/worker.py
  src/ray/protobuf/ray_client.proto
Labels: release-blocker

#18446 [Serve] Call Callable.__del__ explicit during graceful shutdown
  python/ray/serve/backend_state.py
  python/ray/serve/backend_worker.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_fastapi.py
Labels: @author-action-required

#18622 [Build] Generate Bazel config for compiling with clang and libc++ in CI
  .bazelrc
  .buildkite/pipeline.yml
  .gitignore
  bazel/BUILD.redis
  ci/travis/check-git-clang-tidy-output.sh
  ci/travis/ci.sh
  ci/travis/install-dependencies.sh
  ci/travis/install-llvm-binaries.sh
  src/ray/object_manager/test/push_manager_test.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/fixed_point.h
Labels: @tests-ok

#18657 [Serve] Add checkpoint options and custom storage option
  python/ray/serve/api.py
  python/ray/serve/backend_state.py
  python/ray/serve/constants.py
  python/ray/serve/controller.py
  python/ray/serve/endpoint_state.py
  python/ray/serve/scripts.py
  python/ray/serve/storage/checkpoint_path.py
  python/ray/serve/storage/kv_store.py
  python/ray/serve/storage/kv_store_base.py
  python/ray/serve/tests/storage_tests/test_kv_store.py
  python/ray/serve/tests/test_standalone.py
Labels: serve

#18677 [Client] Allow Client{Object,Actor}Ref to accept a future.
  python/ray/_raylet.pxd
  python/ray/includes/object_ref.pxi
  python/ray/includes/unique_ids.pxi
  python/ray/tests/test_client.py
  python/ray/tests/test_client_references.py
  python/ray/util/client/api.py
  python/ray/util/client/client_pickler.py
  python/ray/util/client/common.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/server/server.py
  python/ray/util/client/worker.py
Labels: @tests-ok

#18180 [autoscaler] Log ips and ids when terminating nodes, code structure
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/tests/test_autoscaler.py
Labels: @author-action-required

#18752 Fix ref counting assertion check
  python/ray/tests/test_reference_counting_2.py
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count_test.cc
Labels: @author-action-required

#18743 [core] avoid scheduling on gpu nodes by default
  src/ray/common/ray_config_def.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/scheduling_policy_test.cc
Labels: @author-action-required

#18735 Revert Revert "[Placement Group] Support infeasible placement groups for Placement Group."
  python/ray/tests/test_multi_node_2.py
  src/ray/gcs/gcs_server/gcs_actor_distribution.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/gcs_resource_scheduler.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_resource_scheduler_test.cc
Labels: @tests-ok

#18749 Actor repr for log prefix should be computed after init, not before
  python/ray/_raylet.pyx
  python/ray/tests/test_output.py
Labels: @author-action-required

#18582 [nightly] Deflaky nightly test many_nodes_actor_test
  .github/workflows/main.yml
  release/nightly_tests/nightly_tests.yaml
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#18792 Improve the error message for failed task/actor imports on workers
  python/ray/_private/function_manager.py
  python/ray/ray_constants.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_output.py
Labels: @author-action-required

#18585 [test] add unit test for PR #17634
  BUILD.bazel
  src/mock/ray/gcs/gcs_server/gcs_node_manager.h
  src/mock/ray/gcs/pubsub/gcs_pub_sub.h
  src/mock/ray/gcs/store_client/in_memory_store_client.h
  src/mock/ray/gcs/store_client/redis_store_client.h
  src/mock/ray/gcs/store_client/store_client.h
  src/mock/ray/pubsub/publisher.h
  src/mock/ray/pubsub/subscriber.h
  src/mock/ray/raylet_client/raylet_client.h
  src/mock/ray/rpc/worker/core_worker_client.h
  src/mock/ray/rpc/worker/core_worker_client_pool.h
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/pubsub/gcs_pub_sub.h
Labels: @tests-ok

#18298 [Client] Use async rpc for remote call and actor creation
  python/ray/_raylet.pxd
  python/ray/includes/object_ref.pxi
  python/ray/includes/unique_ids.pxi
  python/ray/tests/test_asyncio.py
  python/ray/tests/test_client.py
  python/ray/tests/test_client_terminate.py
  python/ray/tests/test_client_warnings.py
  python/ray/tests/test_dataclient_disconnect.py
  python/ray/tests/test_placement_group_2.py
  python/ray/util/client/api.py
  python/ray/util/client/client_pickler.py
  python/ray/util/client/common.py
  python/ray/util/client/dataclient.py
  python/ray/util/client/options.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/worker.py
  src/ray/protobuf/ray_client.proto
Labels: @tests-ok

#18809 [RLlib] Reinstate trajectory view API tests.
  rllib/BUILD
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/policy/episode_env_aware_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/utils/sgd.py
Labels: @tests-ok

#18805 [RLlib] Faster remote worker space inference (don't infer if not required).
  rllib/agents/tests/test_trainer.py
  rllib/evaluation/worker_set.py
Labels: @tests-ok

#18468 [RLlib] No Preprocessors (part 2).
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/test_rollout_worker.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/custom_metrics_and_callbacks.py
  rllib/examples/policy/episode_env_aware_policy.py
  rllib/examples/preprocessing_disabled.py
  rllib/execution/replay_buffer.py
  rllib/models/catalog.py
  rllib/models/modelv2.py
  rllib/models/repeated_values.py
  rllib/models/tests/test_preprocessors.py
  rllib/models/tf/complex_input_net.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
  rllib/utils/filter.py
  rllib/utils/framework.py
  rllib/utils/tf_ops.py
Labels: @tests-ok

#18821 [core] Fix bug in ref counting protocol for nested objects
  python/ray/tests/test_reference_counting_2.py
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/protobuf/common.proto
Labels: @author-action-required

#18843 [dataset][nightly-test] add pipelined ingestion/training nightly test
  release/.buildkite/build_pipeline.py
  release/nightly_tests/dataset/dataset_test.yaml
  release/nightly_tests/dataset/pipelined_ingestion_app.yaml
  release/nightly_tests/dataset/pipelined_ingestion_compute.yaml
  release/nightly_tests/dataset/pipelined_training.py
  release/nightly_tests/dataset/pipelined_training_app.yaml
  release/nightly_tests/dataset/pipelined_training_compute.yaml
  release/nightly_tests/dataset/wait_cluster.py
Labels: @author-action-required, do-not-merge

#18813 Fix nil redis array element
  BUILD.bazel
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/test/callback_reply_test.cc
Labels: @tests-ok

#18846 [Java] Support userloggers.
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/util/LoggingUtil.java
  java/runtime/src/main/resources/ray.default.conf
  java/test/src/main/java/io/ray/test/UserLoggerTest.java
Labels: java

#18924 [docs] Don't recommend SignalActor from test_utils
  doc/source/advanced.rst
Labels: @author-action-required

#18929 [doc] Mark multi-client as an experimental feature
  doc/source/cluster/ray-client.rst
Labels: @author-action-required

#18867 Unify ArrowTensorType tables and Tensor blocks
  doc/source/data/dataset-tensor-support.rst
  doc/source/data/dataset.rst
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/numpy_datasource.py
  python/ray/data/extensions/tensor_extension.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/simple_block.py
  python/ray/data/impl/tensor_block.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#18910 [Core][CoreWorker] call shutdown in the correct thread
  src/ray/core_worker/core_worker.cc
Labels: @author-action-required

#18956 [CI] Print out the mismatched commit in ci
  release/e2e.py
Labels: @author-action-required

#18954 Revert "[nightly] Deflaky nightly test many_nodes_actor_test (#18582)"
  .github/workflows/main.yml
  python/ray/tests/BUILD
  release/nightly_tests/nightly_tests.yaml
  src/ray/common/ray_config_def.h
Labels: release-blocker, @author-action-required

#18962 Deflake test_failure_2.py::test_warning_for_infeasible_zero_cpu_actor
  python/ray/tests/test_failure_2.py
Labels: @author-action-required

#18904 Listen to 127.0.0.1 by default on mac osx
  cpp/src/ray/util/process_helper.cc
  python/ray/_private/services.py
  python/ray/scripts/scripts.py
  python/ray/serve/tests/test_standalone.py
  python/ray/tests/test_ray_debugger.py
  python/ray/tests/test_ray_init.py
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/rpc/grpc_server.cc
  src/ray/rpc/grpc_server.h
  src/ray/rpc/test/grpc_server_client_test.cc
Labels: @tests-ok

#18939 [RLlib] Allow n-step > 1 and prio. replay for R2D2 and RNNSAC.
  rllib/BUILD
  rllib/agents/dqn/dqn.py
  rllib/agents/dqn/r2d2.py
  rllib/agents/dqn/r2d2_tf_policy.py
  rllib/agents/dqn/r2d2_torch_policy.py
  rllib/agents/sac/rnnsac.py
  rllib/agents/sac/rnnsac_torch_policy.py
  rllib/agents/sac/tests/test_rnnsac.py
Labels: @tests-ok

#18862 [core] Fix bug in dependency resolution for actor handles
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/dependency_resolver.cc
Labels: @author-action-required

#18983 [Datasets] Handle empty datasets properly in most Dataset transformations.
  python/ray/data/dataset.py
  python/ray/data/impl/compute.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#18346 [dataset][usability] Dataset dependencies
  doc/source/data/dataset.rst
  python/ray/data/datasource/file_based_datasource.py
  python/setup.py
Labels: @tests-ok

#18991 [TaskPool] Cancel all transformation tasks when one task fails or when SIGINT is received
  python/ray/data/impl/compute.py
  python/ray/data/impl/progress_bar.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#18943 Revert "Revert "[Serve] [doc] Improve runtime env doc""
  .buildkite/pipeline.macos.yml
  .buildkite/pipeline.yml
  ci/travis/ci.sh
  doc/source/serve/core-apis.rst
  python/ray/serve/BUILD
  python/ray/serve/backend_state.py
  python/ray/serve/examples/doc/conda_env.py
Labels: @tests-ok

#19010 [Doc] [runtime env] Remove delta caching remark and state Client+@remote limitation
  doc/source/advanced.rst
Labels: @tests-ok

#17055 [Sort benchmark] Two-stage reduce
  python/ray/experimental/raysort/constants.py
  python/ray/experimental/raysort/main.py
  python/ray/experimental/raysort/sortlib.py
  python/ray/experimental/raysort/tracing_utils.py
  python/ray/experimental/raysort/types.py
  python/ray/tests/test_distributed_sort.py
Labels: @author-action-required

#19012 [Workflows] Use `RAY_ADDRESS` in Tests
  python/ray/workflow/tests/test_lifetime.py
Labels: @author-action-required

#18213 [runtime_env] Remove deprecated override_environment_variables and worker_env fields
  dashboard/modules/job/job_agent.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/job_config.py
  python/ray/remote_function.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_client_proxy.py
  python/ray/tests/test_multi_tenancy.py
  python/ray/tests/test_runtime_env_env_vars.py
  python/ray/util/client/options.py
  python/ray/worker.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @tests-ok
