Repository ray-project/ray, pull requests merged in 2021-08, with the labels that each got.

#17435 Dataset speed up read
  python/ray/experimental/data/datasource/binary_datasource.py
  python/ray/experimental/data/datasource/file_based_datasource.py
  python/ray/experimental/data/read_api.py
  release/e2e.py
  release/nightly_tests/dataset/dataset_test.yaml
  release/nightly_tests/dataset/inference.py
  release/nightly_tests/dataset/wait_cluster.py
Labels: @author-action-required

#17334 [Core] Rmove the GetActorIfno RPC for Current Actor When Creating Actors
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
Labels: enhancement

#17439 Support top-level tensor values in dataset
  doc/source/data/dataset-pipeline.rst
  doc/source/data/dataset.rst
  doc/source/data/package-ref.rst
  doc/source/index.rst
  python/ray/experimental/data/__init__.py
  python/ray/experimental/data/block.py
  python/ray/experimental/data/dataset.py
  python/ray/experimental/data/dataset_pipeline.py
  python/ray/experimental/data/datasource/__init__.py
  python/ray/experimental/data/datasource/binary_datasource.py
  python/ray/experimental/data/datasource/csv_datasource.py
  python/ray/experimental/data/datasource/datasource.py
  python/ray/experimental/data/datasource/file_based_datasource.py
  python/ray/experimental/data/datasource/json_datasource.py
  python/ray/experimental/data/datasource/numpy_datasource.py
  python/ray/experimental/data/datasource/parquet_datasource.py
  python/ray/experimental/data/impl/arrow_block.py
  python/ray/experimental/data/impl/block_builder.py
  python/ray/experimental/data/impl/simple_block.py
  python/ray/experimental/data/impl/tensor_block.py
  python/ray/experimental/data/read_api.py
  python/ray/experimental/data/tests/test_dataset.py
Labels: @tests-ok

#17492 [hotfix] Parquet S3 reads broken due to pyarrow.lib.ArrowInvalid: S3 subsystem not initialized
  doc/source/data/dataset.rst
  python/ray/experimental/data/datasource/parquet_datasource.py
Labels: @tests-ok

#17526 OBOD log source error properly
  src/ray/object_manager/ownership_based_object_directory.cc
Labels: @author-action-required

#17352 [autoscaler] Enforce per-node-type max workers
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @author-action-required

#17371 [RLlib] Torch algos use now-framework-agnostic MultiGPUTrainOneStep execution op (~33% speedup for PPO-torch + GPU).
  rllib/agents/ddpg/ddpg_tf_policy.py
  rllib/agents/dqn/dqn_torch_policy.py
  rllib/agents/dqn/tests/test_dqn.py
  rllib/agents/impala/vtrace_torch_policy.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/sac/sac_torch_model.py
  rllib/agents/sac/sac_torch_policy.py
  rllib/agents/sac/tests/test_sac.py
  rllib/agents/trainer.py
  rllib/execution/train_ops.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/rnn_sequencing.py
  rllib/policy/sample_batch.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy.py
  rllib/utils/torch_ops.py
Labels: @tests-ok

#17530 [RLlib] Add @Deprecated decorator to simplify deprecation of classes, methods, functions.
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/impala/__init__.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/registry.py
  rllib/agents/trainer.py
  rllib/evaluation/sample_batch_builder.py
  rllib/examples/env/multi_agent.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_template.py
  rllib/utils/__init__.py
  rllib/utils/annotations.py
  rllib/utils/deprecation.py
  rllib/utils/exploration/exploration.py
  rllib/utils/framework.py
Labels: @tests-ok

#17456 [gcs] Fix actor killing race condition
  python/ray/tests/test_basic_3.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
Labels: @tests-ok

#17547 [runtime env] [Doc] Runtime env doc and messaging improvements
  doc/source/advanced.rst
  python/ray/util/client/server/proxier.py
  python/ray/workers/setup_runtime_env.py
  src/ray/raylet/node_manager.cc
Labels: @author-action-required, usability-hotlist

#17566 [RLlib] Fix `Trainer.add_policy` for num_workers>0 (self play example scripts).
  rllib/agents/tests/test_trainer.py
  rllib/agents/trainer.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/examples/self_play_with_open_spiel.py
  rllib/policy/policy_map.py
  rllib/tests/test_multi_agent_env.py
Labels: @tests-ok

#17422 [Core] [runtime env] Avoid spurious worker startup
  python/ray/test_utils.py
  python/ray/tests/test_runtime_env.py
  src/ray/raylet/agent_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @tests-ok

#17507 [Core] [runtime env] [Test] Add runtime env release test
  release/runtime_env_tests/app_config.yaml
  release/runtime_env_tests/rte_small.yaml
  release/runtime_env_tests/runtime_env_tests.yaml
  release/runtime_env_tests/wait_cluster.py
  release/runtime_env_tests/workloads/rte_many_tasks_actors.py
Labels: @tests-ok

#17564 Skip flaky Windows reconstruction test
  python/ray/tests/test_reconstruction.py
Labels: @author-action-required

#17389 [RFC][Usability] Improve general Ray stacktrace including adding Actor repr
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/exceptions.py
  python/ray/tests/BUILD
  python/ray/tests/test_traceback.py
Labels: @author-action-required

#17529 Remove an unused profile event code from object manager.
  python/ray/tests/test_object_manager.py
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: @author-action-required

#17420 [Dependencies] Fix missing dependency UX
  dashboard/agent.py
  dashboard/dashboard.py
  dashboard/modules/reporter/reporter_agent.py
  python/ray/_private/metrics_agent.py
  python/ray/_private/prometheus_exporter.py
  python/ray/_private/services.py
  python/ray/autoscaler/_private/cli_logger.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/util.py
Labels: release-blocker

#17542 [Core] [runtime env] use per-env async lock in agent
  dashboard/modules/runtime_env/runtime_env_agent.py
Labels: @author-action-required

#17201 [Serve] Define BackendConfig protobuf and adapt it in Java
  .gitignore
  java/BUILD.bazel
  java/checkstyle.xml
  java/pom.xml
  java/serve/pom.xml
  java/serve/src/main/java/io/ray/serve/BackendConfig.java
  java/serve/src/main/java/io/ray/serve/RayServeReplica.java
  java/serve/src/main/java/io/ray/serve/RayServeWrappedReplica.java
  java/serve/src/main/java/io/ray/serve/RequestMetadata.java
  java/serve/src/main/java/io/ray/serve/util/BackendConfigUtil.java
  java/serve/src/test/java/io/ray/serve/RayServeReplicaTest.java
  java/serve/src/test/java/io/ray/serve/util/ReflectUtilTest.java
  src/ray/protobuf/BUILD
  src/ray/protobuf/serve.proto
Labels: enhancement, serve

#17639 [serve] Remove logic to automatically infer conda env name
  python/ray/serve/api.py
Labels: @author-action-required

#17489 [Serve] [Dashboard] Initial PR for exporting Serve data to cluster snapshot
  dashboard/head.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/snapshot_schema.json
  dashboard/modules/snapshot/tests/test_snapshot.py
  doc/source/serve/core-apis.rst
  python/ray/experimental/internal_kv.py
  python/ray/serve/api.py
  python/ray/serve/common.py
  python/ray/serve/config.py
  python/ray/serve/controller.py
  python/ray/serve/kv_store.py
  python/ray/serve/tests/test_kv_store.py
  python/ray/util/__init__.py
Labels: @tests-ok

#17613 [Serve] Add replica tag to request counter and error counter
  java/serve/src/main/java/io/ray/serve/RayServeReplica.java
  python/ray/serve/backend_worker.py
Labels: @tests-ok

#17660 Fix SEGSEGV introduced from the recent pubsub change.
  src/ray/pubsub/publisher.cc
Labels: @author-action-required

#17634 [gcs] Fix actor killing hang due to race condition
  python/ray/tests/test_basic_3.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
Labels: @tests-ok

#17670 Fix a bug where get_actor crashes gcs if the actor is already killed.
  python/ray/tests/test_actor_advanced.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
Labels: release-blocker

#17655 [Serve] [dashboard] Change empty serve cluster snapshot from empty list to empty dict
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/tests/test_snapshot.py
Labels: @tests-ok

#17691 [Datasets] Fix write_json so roundtrip writing + reading works.
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#17578 Export useful metrics
  BUILD.bazel
  python/ray/_private/prometheus_exporter.py
  python/ray/tests/test_metrics_agent.py
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/asio/instrumented_io_context.h
  src/ray/core_worker/core_worker.cc
  src/ray/rpc/grpc_server.cc
  src/ray/rpc/server_call.h
  src/ray/stats/metric.cc
  src/ray/stats/metric.h
  src/ray/stats/stats.h
  src/ray/stats/stats_test.cc
Labels: @tests-ok

#17735 [RLlib] Issue 17706: AttributeError: 'numpy.ndarray' object has no attribute 'items'" on certain turn-based MultiAgentEnvs with Dict obs space.
  rllib/evaluation/sampler.py
Labels: @tests-ok

#17680 Update http-servehandle.rst
  doc/source/serve/http-servehandle.rst
Labels: @author-action-required

#17688 [Cluster Launcher] Allow attach/exec on uninitialized head node
  python/ray/autoscaler/_private/commands.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_autoscaler.py
Labels: @author-action-required

#17622 Add serve external kv store
  dashboard/modules/snapshot/snapshot_head.py
  python/ray/serve/BUILD
  python/ray/serve/backend_state.py
  python/ray/serve/controller.py
  python/ray/serve/endpoint_state.py
  python/ray/serve/kv_store.py
  python/ray/serve/storage/__init__.py
  python/ray/serve/storage/kv_store.py
  python/ray/serve/storage/kv_store_base.py
  python/ray/serve/tests/storage_tests/test_kv_store.py
  python/ray/serve/tests/test_backend_state.py
  python/ray/serve/tests/test_kv_store.py
Labels: @tests-ok, serve

#17727 Add micro benchmark to releaser repo
  python/ray/serve/benchmarks/__init__.py
  python/ray/serve/benchmarks/microbenchmark.py
  release/serve_tests/compute_tpl_single_node.yaml
  release/serve_tests/serve_tests.yaml
  release/serve_tests/workloads/serve_micro_benchmark.py
Labels: serve, @author-action-required

#17716 [Datasets] Add support for reading partitioned Parquet datasets.
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#17158 [Datasets] Add local and S3 filesystem test coverage for file-based datasources.
  .buildkite/pipeline.yml
  python/ray/data/tests/conftest.py
  python/ray/data/tests/mock_server.py
  python/ray/data/tests/test_dataset.py
  python/requirements.txt
  python/requirements/data_processing/requirements.txt
Labels: @tests-ok

#17766 [Core][RFC] limit the total number of inlined bytes in task request rpc
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/includes/ray_config.pxd
  python/ray/tests/test_advanced.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
Labels: @author-action-required

#17765 [Serve] Add support for `root_url`
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/constants.py
  python/ray/serve/tests/test_standalone.py
Labels: @author-action-required

#17772 [Core]Fix the segfault
  src/ray/object_manager/plasma/store.cc
Labels: @author-action-required

#17642 Shutdown clusters when large number of nodes
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/autoscaler/node_provider.py
  python/ray/tests/aws/test_autoscaler_aws.py
Labels: @author-action-required

#17758 Make the namespace argument explicit instead of implicit in actor names
  python/ray/actor.py
  python/ray/experimental/workflow/execution.py
  python/ray/experimental/workflow/step_executor.py
  python/ray/experimental/workflow/workflow_access.py
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_list_actors.py
  python/ray/util/__init__.py
  python/ray/util/client/options.py
  python/ray/worker.py
Labels: @author-action-required, core-api-change-approval-required

#17749 [Serve] [Dashboard] Add start times and replica tags to cluster snapshot
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/snapshot_schema.json
  dashboard/modules/snapshot/tests/test_snapshot.py
  python/ray/serve/api.py
  python/ray/serve/backend_state.py
  python/ray/serve/common.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_backend_state.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/utils.py
Labels: @tests-ok

#17806 [Docker] Downgrade to CUDA 11.0
  ci/travis/build-docker-images.py
  python/requirements_ml_docker.txt
  release/RELEASE_PROCESS.rst
Labels: release-blocker

#17804 [workflow] Allow function without __module__ and __qualname__
  python/ray/experimental/workflow/common.py
  python/ray/experimental/workflow/tests/test_basic_workflows.py
Labels: @tests-ok

#17485 [RLlib] SampleBatch: Docstring- and API cleanups; Add support for nested data.
  rllib/BUILD
  rllib/evaluation/rollout_worker.py
  rllib/policy/rnn_sequencing.py
  rllib/policy/sample_batch.py
  rllib/policy/tests/test_sample_batch.py
  rllib/tests/test_rollout.py
Labels: @tests-ok

#17832 [Serve] [Doc] Delete docs for removed automatic conda activation feature
  doc/source/serve/core-apis.rst
Labels: @tests-ok

#17830 [Serve] Add deployment and replica tags to logs
  python/ray/serve/api.py
  python/ray/serve/backend_state.py
Labels: @tests-ok

#17825 [core] Remove push based resource report code path
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: @author-action-required

#17640 [RLlib] Test cases/BUILD cleanup; split "everything else" (longest running one rn) tests in 2.
  .buildkite/pipeline.yml
  rllib/BUILD
  rllib/agents/a3c/tests/test_a3c.py
  rllib/agents/es/tests/test_es.py
  rllib/agents/pg/tests/test_pg.py
  rllib/agents/ppo/tests/test_ppo.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/sample_batch.py
  rllib/policy/torch_policy.py
Labels: @tests-ok

#17705 Better example scripts: Description --no-tune and --local-mode CLI options (autoregressive_action_dist.py)
  rllib/examples/autoregressive_action_dist.py
  rllib/examples/env/correlated_actions_env.py
Labels: rllib

#17755 Revert "Revert "Export useful metrics""
  BUILD.bazel
  python/ray/_private/prometheus_exporter.py
  python/ray/tests/test_metrics_agent.py
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/asio/instrumented_io_context.h
  src/ray/core_worker/core_worker.cc
  src/ray/rpc/grpc_server.cc
  src/ray/rpc/server_call.h
  src/ray/stats/metric.cc
  src/ray/stats/metric.h
  src/ray/stats/stats.h
  src/ray/stats/stats_test.cc
Labels: @tests-ok

#17699 Fix client_test_enabled
  python/ray/test_utils.py
Labels: @author-action-required

#17841 Shutdown clusters on AWS with >1000 nodes
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/autoscaler/node_provider.py
  python/ray/tests/aws/test_autoscaler_aws.py
Labels: @author-action-required

#17884 Add codeowners for setup.py
  .github/CODEOWNERS
Labels: @author-action-required

#17902 [hotfix] [runtime env] change MacOS wheel URL from 10_13 to 10_15
  python/ray/_private/utils.py
  python/ray/tests/test_runtime_env.py
Labels: @tests-ok

#17869 [Doc] [runtime env] Add note to install ray[default]
  doc/source/advanced.rst
Labels: @author-action-required

#17821 [RLlib] Dreamer fixes and reinstate Dreamer test.
  rllib/BUILD
  rllib/agents/dreamer/dreamer.py
  rllib/agents/dreamer/dreamer_model.py
  rllib/agents/dreamer/dreamer_torch_policy.py
  rllib/agents/dreamer/tests/test_dreamer.py
  rllib/agents/dreamer/utils.py
  rllib/evaluation/sampler.py
Labels: @tests-ok

#17913 [Core] Add support for an app config override to the release test script.
  release/e2e.py
Labels: @tests-ok

#16580 [GCS] GCS Based Actor Scheduler
  BUILD.bazel
  python/ray/tests/test_advanced.py
  python/ray/tests/test_scheduling_performance.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/scheduling_resources.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/gcs_server/test/raylet_based_actor_scheduler_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
Labels: @author-action-required

#17935 Revert "[Core] Unified worker initiators (#17401)"
  cpp/src/ray/config_internal.cc
  java/test/src/main/java/io/ray/test/WorkerJvmOptionsTest.java
  python/ray/_private/services.py
  python/ray/experimental/workflow/BUILD
  python/ray/tests/mock_setup_worker.py
  python/ray/tests/test_runtime_env_fork_process.py
  python/ray/tune/BUILD
  python/ray/workers/setup_runtime_env.py
  src/ray/raylet/worker_pool.cc
Labels: @author-action-required

#17893 [CI] Add test owners
  BUILD.bazel
  ci/travis/check-bazel-team-owner.py
  ci/travis/ci.sh
  cpp/BUILD.bazel
  dashboard/BUILD
  doc/BUILD
  python/ray/data/BUILD
  python/ray/experimental/workflow/BUILD
  python/ray/serve/BUILD
  python/ray/tests/BUILD
  python/ray/tests/modin/BUILD
  python/ray/tune/BUILD
  python/ray/util/dask/BUILD
  python/ray/util/horovod/BUILD
  python/ray/util/lightgbm/BUILD
  python/ray/util/lightning_accelerators/BUILD
  python/ray/util/sgd/BUILD
  python/ray/util/sgd/v2/BUILD
  python/ray/util/xgboost/BUILD
  rllib/BUILD
  streaming/BUILD.bazel
Labels: @author-action-required

#17410 [RLlib] Add example script for how to have n remote (parallel) envs with inference happening on "main" (possibly GPU) node.
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/examples/attention_net.py
  rllib/examples/remote_envs_with_inference_done_on_main_node.py
  rllib/examples/remote_vector_env_with_custom_api.py
Labels: @tests-ok

#17898 [Serve] [Dashboard] Add end times and DELETED state for endpoints
  dashboard/modules/snapshot/tests/test_snapshot.py
  python/ray/serve/backend_state.py
  python/ray/serve/common.py
  python/ray/serve/constants.py
  python/ray/serve/controller.py
Labels: @tests-ok

#17880 Ray workflow comparison examples + add to tests
  python/ray/experimental/workflow/BUILD
  python/ray/experimental/workflow/examples/comparisons/README
  python/ray/experimental/workflow/examples/comparisons/argo/conditionals_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/conditionals_workflow.py
  python/ray/experimental/workflow/examples/comparisons/argo/dag_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/dag_workflow.py
  python/ray/experimental/workflow/examples/comparisons/argo/exit_handler_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/exit_handler_workflow.py
  python/ray/experimental/workflow/examples/comparisons/argo/hello_world_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/hello_world_workflow.py
  python/ray/experimental/workflow/examples/comparisons/argo/loops_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/loops_workflow.py
  python/ray/experimental/workflow/examples/comparisons/argo/multi_step_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/multi_step_workflow.py
  python/ray/experimental/workflow/examples/comparisons/argo/recursion_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/recursion_workflow.py
  python/ray/experimental/workflow/examples/comparisons/argo/retry_argo.yaml
  python/ray/experimental/workflow/examples/comparisons/argo/retry_workflow.py
  python/ray/experimental/workflow/examples/comparisons/brigade/TODO
  python/ray/experimental/workflow/examples/comparisons/cadence/file_processing_cadence.java
  python/ray/experimental/workflow/examples/comparisons/cadence/file_processing_workflow.py
  python/ray/experimental/workflow/examples/comparisons/cadence/sub_workflow_cadence.java
  python/ray/experimental/workflow/examples/comparisons/cadence/sub_workflow_workflow.py
  python/ray/experimental/workflow/examples/comparisons/cadence/trip_booking_cadence.java
  python/ray/experimental/workflow/examples/comparisons/cadence/trip_booking_workflow.py
  python/ray/experimental/workflow/examples/comparisons/google_cloud_workflows/concat_array_google.yaml
  python/ray/experimental/workflow/examples/comparisons/google_cloud_workflows/concat_array_workflow.py
  python/ray/experimental/workflow/examples/comparisons/google_cloud_workflows/data_cond_google.yaml
  python/ray/experimental/workflow/examples/comparisons/google_cloud_workflows/data_cond_workflow.py
  python/ray/experimental/workflow/examples/comparisons/google_cloud_workflows/sub_workflows_google.yaml
  python/ray/experimental/workflow/examples/comparisons/google_cloud_workflows/sub_workflows_workflow.py
  python/ray/experimental/workflow/examples/comparisons/metaflow/foreach_metaflow.py.txt
  python/ray/experimental/workflow/examples/comparisons/metaflow/foreach_workflow.py
  python/ray/experimental/workflow/examples/comparisons/temporal/TODO
  python/ray/experimental/workflow/examples/comparisons/temporal/periodic_temporal.java
  python/ray/experimental/workflow/storage/filesystem.py
Labels: @tests-ok

#17941 Revert "[GCS] GCS Based Actor Scheduler (#16580)"
  BUILD.bazel
  python/ray/tests/test_advanced.py
  python/ray/tests/test_scheduling_performance.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/scheduling_resources.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
Labels: do-not-merge

#17834 [core] Fix inlined nested ids
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/object/local_mode_object_store.cc
  cpp/src/ray/runtime/object/native_object_store.cc
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_reference_counting_2.py
  src/ray/common/ray_object.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/common/test_util.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/future_resolver.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/lib/java/jni_utils.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/transport/dependency_resolver.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/streaming/streaming.cc
  streaming/src/test/mock_actor.cc
  streaming/src/test/queue_tests_base.h
Labels: @author-action-required

#17930 [easy][test] change the way ray starts in nested_id tests
  python/ray/tests/test_reference_counting.py
Labels: @tests-ok

#17966 Don't start dashboard agent when missing dependencies
  dashboard/agent.py
  dashboard/dashboard.py
  dashboard/head.py
  dashboard/optional_deps.py
  dashboard/utils.py
  python/ray/_private/services.py
  src/ray/raylet/main.cc
Labels: @tests-ok

#17903 [Core] Update Bazel (to 3.4.1), gRPC, boringssl, and absl as a precursor to gRPC streaming PR.
  WORKSPACE
  bazel/ray_deps_setup.bzl
  ci/travis/install-dependencies.sh
  doc/source/development.rst
  python/setup.py
  src/ray/rpc/client_call.h
  src/ray/rpc/server_call.h
  thirdparty/patches/grpc-cython-copts.patch
  thirdparty/patches/grpc-python.patch
  thirdparty/patches/grpc-windows-python-header-path.patch
Labels: @tests-ok

#17992 [autoscaler][hotfix] Update node list after terminating unhealthy nodes
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/tests/test_autoscaler.py
Labels: @author-action-required

#18001 [CI][mac] warm up ebs, second try
  .buildkite/pipeline.macos.yml
Labels: do-not-merge

#18011 [core] fix typo of actor repr
  python/ray/actor.py
Labels: @tests-ok

#17875 [core] Run C++ tsan tests
  .bazelrc
  .buildkite/pipeline.yml
Labels: @tests-ok

#18040 [RLlib] Fix the git-bisect helper/debugging script.
  rllib/tests/git_bisect/debug_learning_failure_git_bisect.py
Labels: @tests-ok

#17977 [Serve] [dashboard] Fix formatting bugs in cluster snapshot
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/tests/test_snapshot.py
  python/ray/serve/backend_state.py
  python/ray/serve/controller.py
Labels: @tests-ok

#16922 Better constructor failure handling in ray serve
  python/ray/serve/BUILD
  python/ray/serve/api.py
  python/ray/serve/async_goal_manager.py
  python/ray/serve/backend_state.py
  python/ray/serve/constants.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_backend_state.py
  python/ray/serve/tests/test_constructor_failure.py
Labels: @tests-ok, serve

#18166 [core] Prestart workers up to available CPU limit
  python/ray/tests/test_basic_3.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_interface.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#17910 [Core] Reduce spilling threshold
  python/ray/tests/test_object_spilling_3.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
Labels: @author-action-required

#18200 [CI][Mac] increase timeout for _test_object_spilling_threshold
  python/ray/tests/test_object_spilling_3.py
Labels: @tests-ok

#18169 [core] Refactor test_many_tasks
  benchmarks/distributed/test_many_tasks.py
Labels: do-not-merge

#18066 [workflow] Workflow inside virtual actor
  python/ray/experimental/workflow/recovery.py
  python/ray/experimental/workflow/step_executor.py
  python/ray/experimental/workflow/tests/test_virtual_actor_2.py
  python/ray/experimental/workflow/virtual_actor_class.py
  python/ray/experimental/workflow/workflow_access.py
  python/requirements/data_processing/requirements.txt
Labels: @author-action-required

#18239 [CI][Test] fix off-by-one bug in test_fallback_allocation_failure
  python/ray/tests/test_plasma_unlimited.py
Labels: @tests-ok, @author-action-required

#17999 [RLlib] Replay buffers: Add config option to store contents in checkpoints.
  rllib/agents/cql/cql.py
  rllib/agents/ddpg/ddpg.py
  rllib/agents/dqn/dqn.py
  rllib/agents/dqn/r2d2.py
  rllib/agents/dqn/simple_q.py
  rllib/agents/dqn/tests/test_dqn.py
  rllib/agents/dqn/tests/test_simple_q.py
  rllib/agents/sac/sac.py
  rllib/agents/sac/tests/test_sac.py
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
  rllib/execution/replay_buffer.py
  rllib/execution/replay_ops.py
  rllib/execution/segment_tree.py
  rllib/execution/tests/test_prioritized_replay_buffer.py
  rllib/policy/policy.py
  rllib/tests/test_checkpoint_restore.py
  rllib/utils/annotations.py
  rllib/utils/test_utils.py
Labels: @tests-ok

#18122 Dataset from modin
  doc/source/data/dataset.rst
  python/ray/data/dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/requirements/data_processing/requirements.txt
Labels: @author-action-required

#18254 [RLlib] Better PolicyServer example (w/ or w/o tune) and add printing out actual listen port address in log-level=INFO.
  rllib/agents/trainer.py
  rllib/env/base_env.py
  rllib/env/policy_client.py
  rllib/env/policy_server_input.py
  rllib/examples/attention_net.py
  rllib/examples/serving/cartpole_server.py
  rllib/utils/multi_agent.py
Labels: @tests-ok

#18118 [Event] Add some error level events
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/util/event_label.h
Labels: @author-action-required
