Repository ray-project/ray, pull requests merged in 2021-05, with the labels that each got.

#14872 Add tracing to Ray
  ci/travis/ci.sh
  doc/source/index.rst
  doc/source/ray-tracing.rst
  python/ray/_private/parameter.py
  python/ray/_private/services.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/node.py
  python/ray/remote_function.py
  python/ray/scripts/scripts.py
  python/ray/serve/tests/test_regression.py
  python/ray/tests/BUILD
  python/ray/tests/enable_tracing.py
  python/ray/tests/test_asyncio.py
  python/ray/tests/test_tracing.py
  python/ray/util/tracing/__init__.py
  python/ray/util/tracing/tracing_helper.py
  python/ray/worker.py
  python/requirements.txt
Labels: @author-action-required

#15598 [runtime_env] Deprecate working_dir_uri and use uris instead
  python/ray/_private/runtime_env.py
  python/ray/tests/test_runtime_env.py
Labels: @tests-ok

#15610 [RLlib] Discussion 2021: PPO does not learn vf, iff `use_gae=False` (ignores `use_critic` setting).
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
Labels: @tests-ok

#15631 [RLlib] DD-PPO not supported on Win (add meaningful error message).
  rllib/agents/ppo/ddppo.py
Labels: @tests-ok

#15484 [docs] Add `get_actor` as top level API
  doc/source/package-ref.rst
  python/ray/worker.py
Labels: @author-action-required, core-api-change-approval-required

#15526 [autoscaler][Kubernetes] Operator subprocess error reporting, configuration fixes
  ci/travis/ci.sh
  doc/source/cluster/kubernetes.rst
  python/ray/autoscaler/_private/monitor.py
  python/ray/autoscaler/kubernetes/example-full.yaml
  python/ray/autoscaler/kubernetes/operator_configs/cluster_crd.yaml
  python/ray/autoscaler/kubernetes/operator_configs/example_cluster.yaml
  python/ray/ray_operator/operator.py
  python/ray/ray_operator/operator_utils.py
  python/ray/tests/BUILD
  python/ray/tests/kubernetes_e2e/test_k8s_operator_examples.py
  python/ray/tests/kubernetes_e2e/test_k8s_operator_scaling.py
  python/ray/tests/test_k8s_operator_unit_tests.py
Labels: @tests-ok

#15638 [core] Fix the bug where `ray.init` failed when starting with a `job_config` to create a cluster
  python/ray/tests/test_runtime_env.py
  python/ray/worker.py
Labels: @tests-ok

#15628 [tune] Reduce default number of maximum pending trials to max(16, cluster_cpus)
  doc/source/tune/user-guide.rst
  python/ray/tune/tests/test_progress_reporter.py
  python/ray/tune/trial_runner.py
Labels: tune

#14833 [core] RuntimeEnv GC in gcs
  python/ray/tests/test_runtime_env.py
  src/ray/common/runtime_env_manager.cc
  src/ray/common/runtime_env_manager.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/protobuf/gcs.proto
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#15643 [Client] Add gRPC Keep-Alive messages
  python/ray/util/client/common.py
  python/ray/util/client/server/server.py
  python/ray/util/client/worker.py
Labels: @author-action-required

#15349 [Core] Fix event loop instrumentation causing Java segfaults in tests.
  src/ray/common/ray_config_def.h
Labels: @tests-ok

#15619 [release] Move xgboost tune small + microbenchmark release test to new release automation
  python/ray/_private/ray_client_microbenchmark.py
  python/ray/_private/ray_microbenchmark_helpers.py
  python/ray/ray_perf.py
  release/microbenchmark/app_config.yaml
  release/microbenchmark/cluster.yaml
  release/microbenchmark/microbenchmark.yaml
  release/microbenchmark/run_microbenchmark.py
  release/microbenchmark/tpl_64.yaml
  release/xgboost_tests/app_config.yaml
  release/xgboost_tests/cluster_cpu_moderate.yaml
  release/xgboost_tests/cluster_cpu_small.yaml
  release/xgboost_tests/cluster_gpu_small.yaml
  release/xgboost_tests/tpl_cpu_moderate.yaml
  release/xgboost_tests/tpl_cpu_small.yaml
  release/xgboost_tests/tpl_gpu_small.yaml
  release/xgboost_tests/workloads/train_gpu.py
  release/xgboost_tests/workloads/train_moderate.py
  release/xgboost_tests/workloads/train_small.py
  release/xgboost_tests/workloads/tune_32x4.py
  release/xgboost_tests/workloads/tune_4x32.py
  release/xgboost_tests/workloads/tune_small.py
  release/xgboost_tests/xgboost_tests.yaml
Labels: @tests-ok

#15680 [tune] add `max_concurrent` option to BasicVariantGenerator
  python/ray/tune/suggest/basic_variant.py
  python/ray/tune/suggest/suggestion.py
  python/ray/tune/tests/test_trial_runner_3.py
Labels: @tests-ok, tune

#15540 [RLlib] Example script for restoring 1 agent (out of n) from a checkpoint (multi-agent).
  rllib/BUILD
  rllib/examples/custom_train_fn.py
  rllib/examples/restore_1_of_n_agents_from_checkpoint.py
Labels: @tests-ok

#15365 [RLlib] `simple_optimizer` should not be used by default for tf+MA.
  rllib/agents/ppo/tests/test_ppo.py
  rllib/agents/trainer.py
  rllib/evaluation/sample_batch_builder.py
Labels: @tests-ok

#15611 [RLlib] Discussion 2022: PPO should auto-adjust `rollout_fragment_length` if other settings do not align with `train_batch_size`.
  rllib/agents/ppo/ppo.py
Labels: @tests-ok

#15677 Add objectStore stats to dashboard API.
  dashboard/datacenter.py
  dashboard/modules/stats_collector/tests/test_stats_collector.py
Labels: @author-action-required

#15660 [dashboard] Avoid global min_workers
  dashboard/modules/reporter/reporter_head.py
Labels: @author-action-required

#14979 [C++ Worker] Support ray remote in one line
  cpp/include/ray/api/ray_remote.h
  cpp/src/ray/test/ray_remote_test.cc
Labels: @author-action-required

#15747 Downgrade unnecessary placement group pending messages to DEBUG level
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
Labels: @tests-ok

#15686 [Core] Don't consider a worker to be idle if it has in-flight object pinning RPCs.
  src/ray/core_worker/core_worker.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @tests-ok

#14981 [C++ Worker] Support overload functions for REAY_REMOTE
  cpp/include/ray/api/actor_handle.h
  cpp/include/ray/api/overload.h
  cpp/include/ray/api/ray_remote.h
  cpp/src/ray/test/ray_remote_test.cc
Labels: @author-action-required

#15657 Divide run ci script action
  .github/workflows/main.yml
Labels: @author-action-required

#15591 [RLlib] Trainer._evaluate -> Trainer.evaluate; Also make evaluation possible w/o evaluation worker set.
  rllib/BUILD
  rllib/agents/dqn/tests/test_dqn.py
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
  rllib/env/base_env.py
  rllib/env/multi_agent_env.py
  rllib/evaluation/tests/test_evaluation.py
  rllib/rollout.py
  rllib/tests/test_evaluators.py
Labels: @tests-ok

#15713 [test] Clean-Up Test-Top-Level API
  python/ray/tests/test_top_level_api.py
Labels: @author-action-required

#15687 [tune] avoid system exit error
  python/ray/tune/ray_trial_executor.py
Labels: @author-action-required

#15777 [Core] Fix global state keep initializing in busy loop
  python/ray/state.py
Labels: @author-action-required

#15658 [Core] Pass RuntimeEnv as opaque string in the task spec
  python/ray/_private/runtime_env.py
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/job_config.py
  python/ray/remote_function.py
  python/ray/workers/setup_runtime_env.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: @tests-ok

#15789 [Tests] Mark test_scheduling & test_memstat as Flaky
  python/ray/tests/BUILD
Labels: @author-action-required

#15706 [Client] ray.client.connect() and ray.ClientBuilder
  python/ray/__init__.py
  python/ray/client_builder.py
  python/ray/ray_constants.py
  python/ray/tests/BUILD
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_multi_node_2.py
  python/ray/tests/test_top_level_api.py
Labels: core-api-change-approval-required

#15794 [Flaky] Mark `test_nested_observation_spaces` as Flaky
  rllib/BUILD
Labels: @author-action-required

#15785 [RLlib] Fix 3 flakey test cases.
  .buildkite/pipeline.yml
  rllib/BUILD
  rllib/agents/ddpg/tests/test_ddpg.py
  rllib/agents/sac/tests/test_sac.py
  rllib/models/tests/test_distributions.py
  rllib/utils/test_utils.py
Labels: @author-action-required

#15763 [RLlib] Docs: Example scripts and blogs documentation update.
  doc/source/rllib-examples.rst
  rllib/examples/recsim_with_slateq.py
Labels: @tests-ok

#15740 [RLlib] Add simple curriculum learning API and example script.
  doc/source/rllib-examples.rst
  doc/source/rllib-training.rst
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
  rllib/env/apis/__init__.py
  rllib/env/apis/task_settable_env.py
  rllib/env/env_context.py
  rllib/env/meta_env.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/worker_set.py
  rllib/examples/curriculum_learning.py
  rllib/examples/env/ant_rand_goal.py
  rllib/examples/env/cartpole_mass.py
  rllib/examples/env/curriculum_capable_env.py
  rllib/examples/env/halfcheetah_rand_direc.py
  rllib/examples/env/pendulum_mass.py
Labels: @tests-ok

#15812 [Testing] Dependabot for RLlib.
  .buildkite/pipeline.yml
  .github/dependabot.yml
  ci/travis/build-docker-images.py
  ci/travis/install-dependencies.sh
  python/requirements.txt
  python/requirements/rllib/requirements_rllib.txt
  python/requirements/tune/requirements_tune.txt
  python/requirements/tune/requirements_upstream.txt
  python/requirements_rllib.txt
  rllib/BUILD
  rllib/examples/cartpole_lstm.py
Labels: @tests-ok

#15774 Namespaces
  doc/source/actors.rst
  doc/source/namespaces.rst
  doc/source/using-ray.rst
  python/ray/job_config.py
  python/ray/ray_constants.py
  python/ray/runtime_context.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_persistence.py
  python/ray/serve/tests/test_standalone.py
  python/ray/tests/conftest.py
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_client_init.py
  python/ray/tests/test_client_references.py
  python/ray/tests/test_job.py
  python/ray/tests/test_multi_node.py
  python/ray/tests/test_multi_node_3.py
  python/ray/tests/test_namespace.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_runtime_env.py
  python/ray/util/client/__init__.py
  python/ray/util/client/ray_client_helpers.py
  python/ray/util/client/server/server.py
  python/ray/util/client_connect.py
  python/ray/worker.py
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/accessor.h
  src/ray/gcs/gcs_client/service_based_accessor.cc
  src/ray/gcs/gcs_client/service_based_accessor.h
  src/ray/gcs/gcs_client/test/service_based_gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
Labels: @tests-ok, core-api-change-approval-required

#15757 Refactor raylet to allocate+write+seal one return object at a time
  cpp/src/ray/runtime/task/task_executor.cc
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_object_spilling.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
Labels: @author-action-required

#15749 [core] API for pre-run customized functions
  python/ray/__init__.py
  python/ray/test_utils.py
  python/ray/tests/test_basic.py
Labels: @tests-ok

#15782 [Core] Cache workers by runtime_env in worker pool
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_advanced_3.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  streaming/src/test/mock_actor.cc
Labels: @tests-ok

#15682 [RLlib] Fix "seed" setting to work in all frameworks and w/ all CUDA versions.
  rllib/BUILD
  rllib/evaluation/rollout_worker.py
  rllib/examples/deterministic_training.py
  rllib/examples/env/env_using_remote_actor.py
Labels: @tests-ok

#15737 [RLlib] Issue 15556: Fix R2D2 using chunks from previous episodes in the "burn-in" window.
  rllib/policy/rnn_sequencing.py
  rllib/tuned_examples/dqn/cartpole-r2d2.yaml
Labels: @tests-ok

#15735 [RLlib] Better error message when deep-learning framework not installed.
  rllib/utils/framework.py
Labels: @tests-ok

#15841 [RLlib] CQL TensorFlow support
  doc/source/rllib-algorithms.rst
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/cql/cql.py
  rllib/agents/cql/cql_tf_policy.py
  rllib/agents/cql/cql_torch_policy.py
  rllib/agents/cql/tests/test_cql.py
  rllib/agents/ddpg/ddpg_tf_policy.py
  rllib/agents/dqn/dqn_tf_policy.py
  rllib/agents/dqn/r2d2_tf_policy.py
  rllib/agents/impala/vtrace_tf_policy.py
  rllib/agents/maml/maml_tf_policy.py
  rllib/agents/marwil/marwil_tf_policy.py
  rllib/agents/ppo/appo_tf_policy.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/sac/sac_tf_policy.py
  rllib/examples/offline_rl.py
  rllib/models/tf/tf_action_dist.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/train.py
  rllib/tuned_examples/cql/pendulum-cql.yaml
Labels: @tests-ok

#15736 [RLlib] Issue 15724: Breaking example script in docs due to outdated `eager` config flag (use framework='tf' instead).
  doc/source/rllib-concepts.rst
  doc/source/rllib-toc.rst
  doc/source/rllib-training.rst
  doc/source/rllib.rst
Labels: @tests-ok

#15832 [RLlib] Examples scripts add argparse help and replace `--torch` with `--framework`.
  rllib/BUILD
  rllib/examples/attention_net.py
  rllib/examples/autoregressive_action_dist.py
  rllib/examples/batch_norm_model.py
  rllib/examples/cartpole_lstm.py
  rllib/examples/centralized_critic.py
  rllib/examples/centralized_critic_2.py
  rllib/examples/checkpoint_by_custom_criteria.py
  rllib/examples/complex_struct_space.py
  rllib/examples/custom_env.py
  rllib/examples/custom_eval.py
  rllib/examples/custom_fast_model.py
  rllib/examples/custom_keras_model.py
  rllib/examples/custom_logger.py
  rllib/examples/custom_loss.py
  rllib/examples/custom_metrics_and_callbacks.py
  rllib/examples/custom_model_api.py
  rllib/examples/custom_observation_filters.py
  rllib/examples/custom_rnn_model.py
  rllib/examples/custom_train_fn.py
  rllib/examples/eager_execution.py
  rllib/examples/env_rendering_and_recording.py
  rllib/examples/hierarchical_training.py
  rllib/examples/iterated_prisoners_dilemma_env.py
  rllib/examples/mobilenet_v2_with_lstm.py
  rllib/examples/multi_agent_cartpole.py
  rllib/examples/multi_agent_custom_policy.py
  rllib/examples/multi_agent_two_trainers.py
  rllib/examples/nested_action_spaces.py
  rllib/examples/parallel_evaluation_and_training.py
  rllib/examples/parametric_actions_cartpole.py
  rllib/examples/partial_gpus.py
  rllib/examples/recsim_with_slateq.py
  rllib/examples/restore_1_of_n_agents_from_checkpoint.py
  rllib/examples/rock_paper_scissors_multiagent.py
  rllib/examples/serve_and_rllib.py
  rllib/examples/serving/cartpole_server.py
  rllib/examples/sumo_env_local.py
  rllib/examples/trajectory_view_api.py
  rllib/examples/two_step_game.py
  rllib/examples/two_trainer_workflow.py
  rllib/examples/unity3d_env_local.py
  rllib/examples/vizdoom_with_attention_net.py
  rllib/train.py
  rllib/tuned_examples/debug_learning_failure_git_bisect.py
Labels: @tests-ok

#15783 [RLlib] Fix small memory leak in `SimpleListCollector` (already superseeded by Bam4d's PR + small fix in error message).
  rllib/evaluation/collectors/simple_list_collector.py
Labels: @tests-ok

#15892 [Nightly Dashboard] Fix the nightly shuffle test bug
  python/ray/internal/internal_api.py
Labels: @author-action-required

#14707 [RLlib] DDPG/TD3 + A3C/A2C + MARWIL/BC Annotation/Comments/Code Cleanup
  rllib/agents/a3c/a2c.py
  rllib/agents/a3c/a3c.py
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/ddpg/ddpg.py
  rllib/agents/ddpg/ddpg_tf_model.py
  rllib/agents/ddpg/ddpg_tf_policy.py
  rllib/agents/ddpg/ddpg_torch_model.py
  rllib/agents/ddpg/ddpg_torch_policy.py
  rllib/agents/dqn/dqn_tf_policy.py
  rllib/agents/marwil/bc.py
  rllib/agents/marwil/marwil.py
  rllib/agents/marwil/marwil_tf_policy.py
  rllib/agents/marwil/marwil_torch_policy.py
  rllib/policy/sample_batch.py
Labels: @tests-ok

#15897 Examples for training, saving, loading, testing an agent with SB & RLlib
  rllib/examples/sb2rllib_rllib_example.py
  rllib/examples/sb2rllib_sb_example.py
Labels: rllib

#15838 [Serve] [Core] Fix serve on Windows by disabling runtime env on Windows
  doc/source/advanced.rst
  doc/source/serve/core-apis.rst
  python/ray/_private/runtime_env.py
  python/ray/serve/api.py
  python/ray/tests/test_runtime_env_complicated.py
Labels: @tests-ok

#15860 Increase the raylet start wait timeout to accomodate plasma preallocation
  doc/source/memory-management.rst
  python/ray/_private/services.py
  python/ray/serve/tests/test_router.py
Labels: @author-action-required

#15898 [RLlib] Issue 15887: MARWIL adv norm update mismatch for tf (static-graph) vs torch versions.
  rllib/agents/marwil/marwil_tf_policy.py
  rllib/agents/marwil/marwil_torch_policy.py
  rllib/agents/marwil/tests/test_marwil.py
Labels: @tests-ok

#15762 [RLlib] APEX-DQN: Bug fix for torch and add learning test.
  rllib/BUILD
  rllib/agents/dqn/learner_thread.py
  rllib/agents/dqn/tests/test_apex_dqn.py
  rllib/execution/replay_buffer.py
  rllib/execution/segment_tree.py
  rllib/tuned_examples/dqn/atari-apex.yaml
  rllib/tuned_examples/dqn/cartpole-apex.yaml
  rllib/utils/exploration/per_worker_epsilon_greedy.py
Labels: @tests-ok

#15895 [runtime env] Put runtime env into runtime context;
  python/ray/_private/util_worker_handlers.py
  python/ray/job_config.py
  python/ray/runtime_context.py
  python/ray/tests/test_runtime_env.py
  python/ray/util/client/runtime_context.py
  python/ray/util/client/server/server.py
  python/ray/worker.py
  src/ray/protobuf/common.proto
  src/ray/protobuf/ray_client.proto
Labels: @author-action-required

#15868 [dashboard] Snapshot of cluster state
  .github/CODEOWNERS
  dashboard/modules/snapshot/__init__.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/snapshot_schema.json
  dashboard/tests/test_dashboard.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
Labels: @tests-ok

#15937 [RLlib] Entropy coeff schedule bug fix and git bisect script.
  rllib/agents/ppo/tests/test_ppo.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
  rllib/tests/git_bisect/debug_learning_failure_git_bisect.py
  rllib/tuned_examples/debug_learning_failure_git_bisect.py
Labels: @tests-ok

#15934 [client] Client builder API namespace support
  python/ray/client_builder.py
  python/ray/job_config.py
  python/ray/runtime_context.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_client_metadata.py
  python/ray/util/client/__init__.py
  python/ray/util/client/runtime_context.py
  python/ray/util/client/server/server.py
  python/ray/worker.py
  src/ray/protobuf/ray_client.proto
Labels: @author-action-required

#15431 [plasma] Reset OOM timer as objects are being spilled
  python/ray/external_storage.py
  python/ray/tests/conftest.py
  python/ray/tests/test_object_spilling.py
  src/ray/object_manager/plasma/create_request_queue.cc
  src/ray/object_manager/test/create_request_queue_test.cc
Labels: @author-action-required

#15925 [Core] Fix asyncio actor exit.
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/exceptions.py
  python/ray/tests/test_asyncio.py
Labels: @author-action-required

#15926 [client] Start Specific Server's in separate Conda environments
  python/ray/_private/services.py
  python/ray/tests/BUILD
  python/ray/tests/test_client_proxy.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/server/server.py
Labels: @author-action-required

#15958 [Core] Automatically inject ray and python version in runtime_env
  .buildkite/pipeline.yml
  python/ray/test_utils.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/workers/setup_runtime_env.py
Labels: @tests-ok

#15935 [client] Local client builder
  doc/source/namespaces.rst
  python/ray/client_builder.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_client_builder.py
Labels: @author-action-required

#16042 [Serve] Cleanup examples and tests
  ci/travis/ci.sh
  python/ray/serve/BUILD
  python/ray/serve/examples/echo.py
  python/ray/serve/examples/echo_actor.py
  python/ray/serve/examples/echo_actor_batch.py
  python/ray/serve/examples/echo_batching.py
  python/ray/serve/examples/echo_error.py
  python/ray/serve/examples/echo_full.py
  python/ray/serve/examples/echo_pipeline.py
  python/ray/serve/examples/echo_split.py
  python/ray/serve/tests/test_serve.py
Labels: @author-action-required

#15996 [client] test horovod
  python/ray/tune/BUILD
  python/ray/tune/tests/test_horovod_client.py
Labels: @tests-ok

#16038 [Client][Proxy] Track Num Clients in the proxy
  python/ray/client_builder.py
  python/ray/tests/test_client_proxy.py
  python/ray/util/client/server/proxier.py
Labels: @tests-ok

#16075 [Core] Add "env_vars" field to runtime_env
  ci/travis/ci.sh
  python/ray/_private/runtime_env.py
  python/ray/actor.py
  python/ray/job_config.py
  python/ray/remote_function.py
  python/ray/tests/BUILD
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_runtime_env_env_vars.py
  python/ray/workers/setup_runtime_env.py
Labels: @tests-ok

#15955 [core] Wait for objects to be sealed before throwing OutOfMemory
  src/ray/object_manager/plasma/create_request_queue.cc
  src/ray/object_manager/plasma/create_request_queue.h
  src/ray/object_manager/plasma/eviction_policy.cc
  src/ray/object_manager/plasma/plasma.fbs
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/test/create_request_queue_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: @author-action-required

#16058 [Docs][ClientBuilder] Add `ray.client()` and `ray.ClientBuilder` to Experimental API docs
  doc/source/package-ref.rst
  python/ray/client_builder.py
Labels: @author-action-required

#16006 [Placement Group]Fix actor scheduling with Placement Group bug.
  python/ray/tests/test_placement_group.py
  src/ray/common/task/task_spec.cc
Labels: release-blocker

#16107 Revert "Revert "[Core] Add "env_vars" field to runtime_env""
  ci/travis/ci.sh
  python/ray/_private/runtime_env.py
  python/ray/actor.py
  python/ray/job_config.py
  python/ray/remote_function.py
  python/ray/tests/BUILD
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_runtime_env_env_vars.py
  python/ray/workers/setup_runtime_env.py
Labels: @tests-ok

#15775 [core] Trigger global gc when plasma store is under pressure.
  BUILD.bazel
  python/ray/tests/test_basic_3.py
  python/ray/tests/test_global_gc.py
  src/ray/common/ray_config_def.h
  src/ray/object_manager/object_manager.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/util/throttler.h
  src/ray/util/throttler_test.cc
Labels: @author-action-required

#16051 [Plasma store] Improve the OOM logging message.
  python/ray/_raylet.pyx
  src/ray/object_manager/plasma/store.cc
Labels: @author-action-required

#16124 [Core, Flaky] Decrease the number of nodes and actors started on each node in test_actor_resources test.
  python/ray/tests/test_actor_resources.py
Labels: @tests-ok

#16073 [Core] Allow specifying runtime_env conda and pip via filepath
  python/ray/_private/runtime_env.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/workers/setup_runtime_env.py
Labels: @tests-ok

#16119 Make the spill test on unstable filesystem not so verbose
  python/ray/tests/test_object_spilling.py
Labels: @author-action-required

#16021 [Client] Add ray.client().disconnect()
  doc/source/namespaces.rst
  python/ray/client_builder.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_client_proxy.py
  python/ray/tests/test_runtime_env_complicated.py
Labels: @author-action-required, core-api-change-approval-required

#16040 [RayClient][Proxy] BugFixes
  doc/source/ray-client.rst
  python/ray/tests/test_client_proxy.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/server/server.py
Labels: @author-action-required, release-blocker
