Repository ray-project/ray, pull requests merged in 2021-12, with the labels that each got.

#20714 [Part 4] Support passing metadata to Ray error object.
  src/ray/common/ray_object.cc
  src/ray/common/ray_object.h
  src/ray/core_worker/task_manager.cc
Labels: @author-action-required

#20636 [RLlib] Trainer sub-class DDPG/TD3/APEX-DDPG (instead of `build_trainer`).
  rllib/agents/ddpg/apex.py
  rllib/agents/ddpg/ddpg.py
  rllib/agents/ddpg/td3.py
  rllib/agents/dqn/simple_q.py
  rllib/agents/trainer.py
Labels: @tests-ok

#20804 [Core][Pubsub][Importer] GCS pubsub for function manager & importer
  python/ray/_private/function_manager.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/import_thread.py
  python/ray/tests/test_basic_3.py
  python/ray/tests/test_gcs_pubsub.py
  python/ray/worker.py
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/protobuf/BUILD
  src/ray/protobuf/dependency.proto
  src/ray/protobuf/pubsub.proto
Labels: @tests-ok

#20775 [Serve] [Doc] fix custom metric link in serve doc
  doc/source/ray-metrics.rst
  doc/source/serve/deployment.rst
Labels: @tests-ok

#20639 [RLlib] Trainer sub-class QMIX/MAML/MB-MPO (instead of `build_trainer`).
  rllib/agents/dqn/dqn.py
  rllib/agents/maml/maml.py
  rllib/agents/mbmpo/mbmpo.py
  rllib/agents/qmix/qmix.py
Labels: @tests-ok

#19936 [Core]Support back pressure.
  cpp/src/ray/runtime/task/native_task_submitter.cc
  java/api/src/main/java/io/ray/api/call/BaseActorCreator.java
  java/api/src/main/java/io/ray/api/options/ActorCreationOptions.java
  java/runtime/src/main/java/io/ray/runtime/exception/PendingCallsLimitExceededException.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskSubmitter.java
  java/test/src/main/java/io/ray/test/BackPressureTest.java
  java/test/src/main/java/io/ray/test/SignalActor.java
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/exceptions.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/includes/optional.pxd
  python/ray/tests/test_advanced_4.py
  python/ray/util/client/options.py
  src/mock/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/lib/java/jni_init.cc
  src/ray/core_worker/lib/java/jni_utils.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/streaming/streaming.cc
  streaming/src/test/queue_tests_base.h
Labels: core-api-change-approval-required

#20638 [ci/release] Remove quotation marks from pip installs
  release/e2e.py
  release/golden_notebook_tests/dask_xgboost_app_config.yaml
  release/golden_notebook_tests/modin_xgboost_app_config.yaml
Labels: @author-action-required

#20889 [nighly-test] update cuj2 to reflect latest change
  release/nightly_tests/dataset/dataset_test.yaml
  release/nightly_tests/dataset/ray_sgd_training.py
  release/nightly_tests/dataset/ray_sgd_training_compute_no_gpu.yaml
Labels: @tests-ok

#20885 [runtime env] Parse local conda/pip requirements files before sending runtime env to Ray Client Server
  python/ray/_private/test_utils.py
  python/ray/job_config.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/tests/test_runtime_env_conda.py
  python/ray/tests/test_runtime_env_working_dir_2.py
  python/ray/util/client/worker.py
Labels: @tests-ok

#20844 [Jobs] Update CLI examples to use the same setup
  doc/source/ray-job-submission/overview.rst
Labels: serve, @author-action-required

#19678 [Core][Refactor CoreWorker 3/n] split static function from CoreWorkerProcess
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/core_worker_process.h
Labels: @author-action-required

#20877 [Train] Clarify `Session.get_next` docstring
  python/ray/train/session.py
Labels: python, train

#20833 [Doc] Add bazel build OOM tip to docs
  doc/source/development.rst
Labels: @tests-ok

#20754 [dataset][cuj2] add another single node ingestion example
  release/.buildkite/build_pipeline.py
  release/nightly_tests/dataset/dataset_ingest_400G_compute.yaml
  release/nightly_tests/dataset/dataset_test.yaml
  release/nightly_tests/dataset/ray_sgd_runner.py
Labels: @tests-ok

#20916 [tune] minor clean up of executor.restore().
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/trial_executor.py
Labels: P1

#20756 [Serve]Change Java LongPollClient's polling thread to singleton.
  java/serve/src/main/java/io/ray/serve/ProxyActor.java
  java/serve/src/main/java/io/ray/serve/RayServeConfig.java
  java/serve/src/main/java/io/ray/serve/Router.java
  java/serve/src/main/java/io/ray/serve/ServeController.java
  java/serve/src/main/java/io/ray/serve/UpdatedObject.java
  java/serve/src/main/java/io/ray/serve/poll/KeyType.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollClient.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollClientFactory.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollNamespace.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollRequest.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollResult.java
  java/serve/src/main/java/io/ray/serve/util/ServeProtoUtil.java
  java/serve/src/test/java/io/ray/serve/DummyServeController.java
  java/serve/src/test/java/io/ray/serve/HttpProxyTest.java
  java/serve/src/test/java/io/ray/serve/ProxyActorTest.java
  java/serve/src/test/java/io/ray/serve/ProxyRouterTest.java
  java/serve/src/test/java/io/ray/serve/RayServeHandleTest.java
  java/serve/src/test/java/io/ray/serve/RayServeReplicaTest.java
  java/serve/src/test/java/io/ray/serve/ReplicaSetTest.java
  java/serve/src/test/java/io/ray/serve/RouterTest.java
  java/serve/src/test/java/io/ray/serve/api/ClientTest.java
  java/serve/src/test/java/io/ray/serve/poll/KeyTypeTest.java
  java/serve/src/test/java/io/ray/serve/poll/LongPollClientTest.java
  java/serve/src/test/java/io/ray/serve/poll/LongPollNamespaceTest.java
Labels: serve

#20905 [Datasets] Fix boolean tensor column slicing.
  python/ray/data/extensions/tensor_extension.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#20919 [Core] upgrade grpc and boringssl
  bazel/ray_deps_setup.bzl
  thirdparty/patches/grpc-default-initialization.patch
  thirdparty/patches/grpc-windows-python-header-path.patch
Labels: @tests-ok

#19970 [core] Simple chaos testing for asio
  BUILD.bazel
  doc/source/debugging.rst
  python/ray/tests/test_chaos.py
  src/ray/common/asio/asio_chaos.cc
  src/ray/common/asio/asio_chaos.h
  src/ray/common/asio/asio_util.h
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/ray_config_def.h
  src/ray/common/test/asio_defer_test.cc
Labels: @author-action-required

#20930 [Ray Client] Pickle task options for ray client
  python/ray/tests/test_placement_group_3.py
  python/ray/util/client/__init__.py
  python/ray/util/client/common.py
  python/ray/util/client/server/server.py
  python/ray/util/placement_group.py
  src/ray/protobuf/ray_client.proto
Labels: @tests-ok

#20315 [serve] Reconfiguration bug fix
  python/ray/serve/replica.py
  python/ray/serve/tests/test_deploy.py
  python/requirements.txt
  python/setup.py
Labels: @tests-ok

#20838 [core] Remove spammy code in object directory client
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count_test.cc
  src/ray/object_manager/ownership_based_object_directory.cc
Labels: @author-action-required

#20507 [Scheduler] Support per task/actor PlacementGroupSchedulingStrategy
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/native_task_submitter.cc
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/cross_language.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/test_scheduling_2.py
  python/ray/util/client/options.py
  python/ray/util/client/worker.py
  python/ray/util/scheduling_strategies.py
  python/ray/worker.py
  python/ray/workflow/workflow_context.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  streaming/src/test/queue_tests_base.h
Labels: @tests-ok, core-api-change-approval-required

#20853 Revert "Revert "[runtime env] Allow working_dir and py_module to be Path type""
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/serve/tests/test_cli.py
  python/ray/tests/BUILD
  python/ray/tests/conftest.py
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_runtime_env_working_dir_2.py
  python/ray/tests/test_runtime_env_working_dir_remote_uri.py
Labels: @tests-ok

#20728 [Internal Observability] [Part 1] Centralize existing metrics to metric_defs.h
  .github/CODEOWNERS
  BUILD.bazel
  python/ray/tests/test_metrics_agent.py
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/grpc_based_resource_broadcaster.cc
  src/ray/gcs/redis_context.cc
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/plasma/object_lifecycle_manager.cc
  src/ray/object_manager/plasma/stats_collector.cc
  src/ray/object_manager/plasma/stats_collector.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/push_manager.cc
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/rpc/grpc_server.cc
  src/ray/rpc/server_call.h
  src/ray/stats/metric.h
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
  src/ray/stats/metric_exporter_client_test.cc
  src/ray/stats/stats.h
  src/ray/stats/stats_test.cc
Labels: @author-action-required

#20867 Initial stats framework for datasets
  doc/source/data/dataset-execution-model.rst
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/compute.py
  python/ray/data/impl/pipeline_executor.py
  python/ray/data/impl/shuffle.py
  python/ray/data/impl/simple_block.py
  python/ray/data/impl/stats.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_context_propagation.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_stats.py
Labels: @tests-ok

#20972 [Scheduler] Support per task/actor SpreadSchedulingStrategy
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/remote_function.py
  python/ray/tests/test_scheduling_2.py
  python/ray/util/scheduling_strategies.py
  python/ray/worker.py
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/scheduling_policy.cc
  src/ray/raylet/scheduling/scheduling_policy.h
  src/ray/raylet/scheduling/scheduling_policy_test.cc
Labels: @tests-ok

#20922 [1/kv-regression] Put KV into a dedicated thread pool
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
Labels: @author-action-required

#20793 [RLlib] Allow extra keys in info in multi-agent
  rllib/env/base_env.py
  rllib/evaluation/sampler.py
Labels: @tests-ok

#20850 Example containing a proposal for computing an adapted (time-dependent) GAE used by the PPO algorithm (via callback on_postprocess_trajectory)
  python/ray/train/examples/tensorflow_quick_start.py
  python/ray/train/examples/torch_quick_start.py
  rllib/examples/compute_adapted_gae_on_postprocess_trajectory.py
Labels: @tests-ok

#20964 [core] Ensure failed to register worker is killed and print better log
  python/ray/tests/test_failure_4.py
  src/ray/raylet/worker_pool.cc
  src/ray/util/process.cc
  src/ray/util/process.h
Labels: @author-action-required

#20929 [chaos-test] chaos test pipeline ingestion
  release/.buildkite/build_pipeline.py
  release/nightly_tests/chaos_test.yaml
  release/nightly_tests/dataset/pipelined_ingestion_app.yaml
Labels: @author-action-required

#20957 [Internal Observability] [Part 3] Support debug state metrics on all components.
  python/ray/tests/test_metrics_agent.py
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/plasma/object_lifecycle_manager.cc
  src/ray/object_manager/plasma/object_lifecycle_manager.h
  src/ray/object_manager/plasma/stats_collector.cc
  src/ray/object_manager/plasma/stats_collector.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/push_manager.cc
  src/ray/object_manager/push_manager.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#20958 [Internal Observability] [Part 2] Share the same code for RecordMetrics & DebugString for cluster task manager.
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
Labels: @author-action-required

#20981 [docs] Make design pattern example self contained
  doc/source/ray-design-patterns/tree-of-tasks.rst
Labels: @author-action-required

#21001 [Core][Dashboard Pubsub 2/n] Add resource reporter and actor to Python GCS pubsub
  dashboard/head.py
  dashboard/modules/node/node_head.py
  python/ray/_private/gcs_pubsub.py
  python/ray/tests/test_gcs_pubsub.py
  python/ray/worker.py
Labels: @tests-ok

#20538 [RLlib; Docs] Docs API reference pages: `rllib/execution`, `rllib/evaluation`, `rllib/models`, `rllib/offline`.
  doc/source/images/rllib/rollout_worker_class_overview.svg
  doc/source/rllib-models.rst
  doc/source/rllib-offline.rst
  doc/source/rllib-package-ref.rst
  doc/source/rllib/package_ref/evaluation.rst
  doc/source/rllib/package_ref/evaluation/policy_map.rst
  doc/source/rllib/package_ref/evaluation/rollout_worker.rst
  doc/source/rllib/package_ref/evaluation/sample_batch.rst
  doc/source/rllib/package_ref/evaluation/samplers.rst
  doc/source/rllib/package_ref/evaluation/worker_set.rst
  doc/source/rllib/package_ref/execution.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/models.rst
  doc/source/rllib/package_ref/offline.rst
  rllib/agents/trainer.py
  rllib/models/modelv2.py
  rllib/offline/io_context.py
  rllib/policy/sample_batch.py
Labels: @tests-ok

#21015 [Test] [runtime_env] Deflake test by bumping tasks_finish_quickly timeout from 1s to 2s
  python/ray/tests/test_runtime_env_complicated.py
Labels: @tests-ok

#20859 Fix driver lease request infinite loop when local raylet dies
  python/ray/exceptions.py
  python/ray/serialization.py
  python/ray/tests/test_failure_4.py
  src/mock/ray/core_worker/task_manager.h
  src/ray/common/grpc_util.h
  src/ray/common/status.cc
  src/ray/common/status.h
  src/ray/common/test/status_test.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/gcs_server_address_updater.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_task_transport_mock_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/protobuf/common.proto
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
Labels: @tests-ok

#20918 [RLlib] Experimental no-flatten option for actions/prev-actions.
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/episode.py
  rllib/evaluation/sampler.py
  rllib/examples/export/onnx_tf.py
  rllib/models/tf/tf_action_dist.py
  rllib/models/torch/torch_action_dist.py
  rllib/offline/json_reader.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/tf_policy.py
  rllib/tests/test_nested_action_spaces.py
  rllib/tests/test_nested_observation_spaces.py
Labels: @tests-ok

#21005 [ci/release] Remove hard numpy removal from app configs
  benchmarks/app_config.yaml
  release/horovod_tests/app_config_master.yaml
  release/long_running_tests/app_config.yaml
  release/long_running_tests/app_config_np.yaml
  release/ml_user_tests/horovod/app_config.yaml
  release/nightly_tests/dataset/pipelined_ingestion_app.yaml
  release/nightly_tests/dataset/pipelined_training_app.yaml
  release/sgd_tests/sgd_gpu/sgd_gpu_app_config.yaml
Labels: do-not-merge

#21013 [gcs] print log for storage setup of gcs
  src/ray/gcs/gcs_server/gcs_server.cc
Labels: @author-action-required

#20894 [Core] Support back pressure for actor tasks.
  cpp/src/ray/runtime/task/native_task_submitter.cc
  java/api/src/main/java/io/ray/api/call/BaseActorCreator.java
  java/api/src/main/java/io/ray/api/options/ActorCreationOptions.java
  java/runtime/src/main/java/io/ray/runtime/exception/PendingCallsLimitExceededException.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskSubmitter.java
  java/test/src/main/java/io/ray/test/BackPressureTest.java
  java/test/src/main/java/io/ray/test/SignalActor.java
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/exceptions.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/includes/optional.pxd
  python/ray/tests/test_advanced_4.py
  python/ray/util/client/options.py
  rllib/tests/test_gpus.py
  src/mock/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/lib/java/jni_init.cc
  src/ray/core_worker/lib/java/jni_utils.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/streaming/streaming.cc
  streaming/src/test/queue_tests_base.h
Labels: @tests-ok

#21061 [nighly-test] fix dataset nightly test reporting
  release/nightly_tests/dataset/ray_sgd_training.py
Labels: @tests-ok

#20936 [Core] Allow to configure dashboard agent grpc port.
  python/ray/_private/parameter.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_ray_init.py
Labels: @author-action-required

#20900 [Core] Shorten the GCS dead detection to 60 seconds instead of 10 minutes.
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_placement_group_2.py
  python/ray/tests/test_placement_group_3.py
  python/ray/tests/test_ray_shutdown.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/gcs_server_address_updater.cc
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
Labels: @author-action-required

#20993 [Internal Observability] Record GCS debug stats to metrics
  python/ray/tests/test_metrics_agent.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: @author-action-required

#21051 Increase in `num_tasks` for stable wait times in `test_worker_capping:test_exponential_wait`
  python/ray/tests/test_worker_capping.py
Labels: windows, testing, flaky-test

#20341 [runtime_env] Make pip installs incremental
  ci/travis/ci.sh
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/utils.py
  python/ray/_private/runtime_env/validation.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/_private/test_utils.py
  python/ray/tests/BUILD
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
  python/ray/tests/test_runtime_env_conda_and_pip_2.py
  python/ray/tests/test_runtime_env_validation.py
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/runtime_env_common.proto
Labels: @tests-ok

#20849 [Core] Properly implement some blocking RPCs with promise. Actor + KV store
  python/ray/tests/test_failure_2.py
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/core_worker/actor_creator.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/actor_creator_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/rpc/client_call.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/grpc_server.cc
Labels: @tests-ok

#21067 [tune] _cached_actor_pg can only be non empty when reuse_actors = True.
  python/ray/tune/ray_trial_executor.py
Labels: @tests-ok

#21089 [Core] fix wrong memory size reporting
  src/ray/common/task/scheduling_resources.cc
Labels: @tests-ok, @author-action-required

#21064 [CUJ#2] Update nightly test for CUJ#2
  release/nightly_tests/dataset/ray_sgd_training.py
Labels: @tests-ok

#19786 [RLlib; Docs overhaul] Overhaul of auto-API reference pages (via sphinx autoclass/automodule).
  doc/source/rllib-dev.rst
  doc/source/rllib-package-ref.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/utils.rst
  doc/source/rllib/package_ref/utils/annotations.rst
  doc/source/rllib/package_ref/utils/deprecation.rst
  doc/source/rllib/package_ref/utils/exploration.rst
  doc/source/rllib/package_ref/utils/framework.rst
  doc/source/rllib/package_ref/utils/numpy.rst
  doc/source/rllib/package_ref/utils/schedules.rst
  doc/source/rllib/package_ref/utils/tf_utils.rst
  doc/source/rllib/package_ref/utils/torch_utils.rst
  rllib/utils/__init__.py
  rllib/utils/annotations.py
  rllib/utils/deprecation.py
  rllib/utils/exploration/curiosity.py
  rllib/utils/exploration/epsilon_greedy.py
  rllib/utils/exploration/exploration.py
  rllib/utils/exploration/gaussian_noise.py
  rllib/utils/exploration/ornstein_uhlenbeck_noise.py
  rllib/utils/exploration/parameter_noise.py
  rllib/utils/exploration/per_worker_epsilon_greedy.py
  rllib/utils/exploration/per_worker_gaussian_noise.py
  rllib/utils/exploration/per_worker_ornstein_uhlenbeck_noise.py
  rllib/utils/exploration/random.py
  rllib/utils/exploration/random_encoder.py
  rllib/utils/exploration/soft_q.py
  rllib/utils/exploration/stochastic_sampling.py
  rllib/utils/schedules/constant_schedule.py
  rllib/utils/schedules/exponential_schedule.py
  rllib/utils/schedules/linear_schedule.py
  rllib/utils/schedules/piecewise_schedule.py
  rllib/utils/schedules/polynomial_schedule.py
  rllib/utils/schedules/schedule.py
Labels: @tests-ok

#21009 [Serve] Fix naming error and add Serve metric for HTTP error codes
  doc/source/serve/deployment.rst
  python/ray/serve/BUILD
  python/ray/serve/api.py
  python/ray/serve/handle.py
  python/ray/serve/http_proxy.py
  python/ray/serve/tests/test_metrics.py
Labels: @tests-ok

#21138 [release] Pin anyscale version to fix release tests
  release/requirements.txt
Labels: @tests-ok

#21035 Bump timeout value for `test_worker_capping.py::test_zero_cpu_scheduling`
  python/ray/tests/test_worker_capping.py
Labels: windows, testing

#21114 [Dask-on-Ray] Add Dask config helper, set task-based shuffle by default.
  doc/source/data/dask-on-ray.rst
  python/ray/util/dask/__init__.py
  python/ray/util/dask/examples/dask_ray_scheduler_example.py
  python/ray/util/dask/scheduler.py
  python/ray/util/dask/tests/test_dask_optimization.py
  python/ray/util/dask/tests/test_dask_scheduler.py
Labels: @tests-ok

#21148 [Dataset][nighlytest] use latest ray for running test
  release/nightly_tests/dataset/ray_sgd_training_app.yaml
  release/nightly_tests/dataset/ray_sgd_training_smoke_compute.yaml
Labels: @tests-ok

#21152 Revert "Revert "[Placement Group] Make placement group prepare resource rpc r… (#21144)"
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/common/bundle_spec.cc
  src/ray/common/bundle_spec.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/placement_group_resource_manager.h
  src/ray/raylet/placement_group_resource_manager_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @tests-ok

#21163 [runtime env] [doc] [test] Add docs and tests for `RAY_runtime_env_skip_local_gc` environment variable
  doc/source/handling-dependencies.rst
  python/ray/tests/test_runtime_env_conda_and_pip_3.py
  python/ray/tests/test_runtime_env_working_dir_2.py
Labels: @tests-ok

#20156 [Workflow]add doc for metadata
  doc/source/index.rst
  doc/source/workflows/metadata.rst
  doc/source/workflows/package-ref.rst
  python/ray/workflow/common.py
Labels: @external-author-action-required

#20984 [RLlib] POC: Run PGTrainer w/o the distr. exec API (Trainer's new training_iteration method).
  rllib/agents/maml/maml.py
  rllib/agents/mbmpo/mbmpo.py
  rllib/agents/pg/default_config.py
  rllib/agents/pg/pg_tf_policy.py
  rllib/agents/trainer.py
  rllib/evaluation/worker_set.py
  rllib/examples/rock_paper_scissors_multiagent.py
  rllib/execution/__init__.py
  rllib/execution/common.py
  rllib/execution/metric_ops.py
  rllib/execution/rollout_ops.py
  rllib/execution/train_ops.py
  rllib/policy/sample_batch.py
  rllib/tests/test_execution.py
  rllib/tests/test_gpus.py
  rllib/tests/test_ignore_worker_failure.py
  rllib/tuned_examples/pg/cartpole-pg-fake-gpus.yaml
  rllib/utils/metrics/__init__.py
  rllib/utils/test_utils.py
Labels: @tests-ok

#21049 [Internal Observability] Record Raylet Gauge
  .github/CODEOWNERS
  python/ray/tests/test_metrics_agent.py
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/push_manager.cc
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: @author-action-required

#21174 [1/gcs] gcs ha bootstrap for raylet
  .buildkite/pipeline.yml
  python/ray/_private/gcs_utils.py
  python/ray/_private/services.py
  python/ray/includes/common.pxd
  python/ray/includes/common.pxi
  python/ray/node.py
  python/ray/tests/test_advanced.py
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/raylet/main.cc
  src/ray/raylet/raylet.cc
  src/ray/raylet/raylet.h
Labels: @author-action-required

#21213 Unskipped tests in test_standalone.py
  python/ray/serve/tests/test_standalone.py
Labels: windows, testing

#20882 Isolate function exports by job in separate queues
  python/ray/_private/function_manager.py
  python/ray/_private/import_thread.py
  python/ray/ray_constants.py
  python/ray/tests/BUILD
  python/ray/tests/test_job.py
Labels: @author-action-required

#21179 [2/gcs] Bootstrap dashboard for gcs ha
  .buildkite/pipeline.yml
  dashboard/agent.py
  dashboard/consts.py
  dashboard/dashboard.py
  dashboard/head.py
  dashboard/modules/actor/actor_head.py
  dashboard/modules/event/event_agent.py
  dashboard/modules/job/job_head.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/modules/snapshot/tests/test_snapshot.py
  dashboard/tests/test_dashboard.py
  python/ray/_private/metrics_agent.py
  python/ray/_private/services.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/tests/test_metrics_agent.py
Labels: @author-action-required

#21194 [3/gcs] Bootstrap log monitor and monitor from gcs
  python/ray/_private/log_monitor.py
  python/ray/_private/services.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/cluster_utils.py
  python/ray/node.py
  python/ray/ray_operator/operator.py
  python/ray/tests/test_multi_node_2.py
Labels: @author-action-required

#20433 Unskip tests in ``test_basic_3.py``
  .buildkite/pipeline.yml
  python/ray/tests/BUILD
  python/ray/tests/test_basic_3.py
  python/ray/tests/test_basic_4.py
  python/ray/tests/test_basic_5.py
Labels: windows

#21235 Unskip `test_standalone` from ci.sh
  ci/travis/ci.sh
  python/ray/serve/tests/test_standalone.py
Labels: windows, testing

#21021 [tune] Have one canonical way of stopping trial.
  python/ray/tune/schedulers/hyperband.py
  python/ray/tune/trial_runner.py
Labels: @tests-ok

#21136 WINDOWS: enable passing/skipping tests
  ci/travis/ci.sh
  python/ray/tests/test_multiprocessing.py
Labels: windows

#21293 Revert "Round robin during spread scheduling (#19968)"
  python/ray/_private/services.py
  python/ray/data/impl/shuffle.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/util/scheduling_strategies.py
  release/nightly_tests/dataset/pipelined_training.py
  src/ray/raylet/scheduling/scheduling_policy.cc
  src/ray/raylet/scheduling/scheduling_policy.h
  src/ray/raylet/scheduling/scheduling_policy_test.cc
Labels: @tests-ok

#20966 [Core]Add RAY_REDIS_ADDRESS environment to specify external address.
  python/ray/scripts/scripts.py
  python/ray/tests/test_multi_node_3.py
Labels: testing
