Repository ray-project/ray, pull requests merged in 2021-11, with the labels that each got.

#19808 [RLlib; Docs overhaul] Docstring cleanup: Offline.
  rllib/evaluation/rollout_worker.py
  rllib/offline/d4rl_reader.py
  rllib/offline/input_reader.py
  rllib/offline/io_context.py
  rllib/offline/is_estimator.py
  rllib/offline/json_reader.py
  rllib/offline/json_writer.py
  rllib/offline/off_policy_estimator.py
  rllib/offline/output_writer.py
  rllib/offline/shuffled_input.py
  rllib/offline/wis_estimator.py
Labels: @tests-ok

#19925 [ci] Script for building M1 wheels
  python/build-wheel-macos-arm64.sh
Labels: @author-action-required

#19829 [RLlib; Docs overhaul] Docstring cleanup: rllib/utils
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/ars/ars.py
  rllib/agents/ddpg/ddpg_tf_policy.py
  rllib/agents/dqn/dqn_tf_policy.py
  rllib/agents/dqn/learner_thread.py
  rllib/agents/dqn/r2d2_tf_policy.py
  rllib/agents/dqn/simple_q_tf_policy.py
  rllib/agents/es/es.py
  rllib/agents/impala/vtrace_tf_policy.py
  rllib/agents/marwil/marwil_tf_policy.py
  rllib/agents/ppo/appo_tf_policy.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/registry.py
  rllib/agents/sac/sac_tf_policy.py
  rllib/agents/trainer.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sample_batch_builder.py
  rllib/examples/centralized_critic.py
  rllib/examples/env/multi_agent.py
  rllib/examples/models/trajectory_view_utilizing_models.py
  rllib/execution/learner_thread.py
  rllib/execution/replay_buffer.py
  rllib/models/catalog.py
  rllib/models/modelv2.py
  rllib/models/tf/attention_net.py
  rllib/models/tf/complex_input_net.py
  rllib/models/tf/recurrent_net.py
  rllib/models/torch/torch_action_dist.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/policy_map.py
  rllib/policy/sample_batch.py
  rllib/policy/tf_policy.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_template.py
  rllib/utils/annotations.py
  rllib/utils/debug.py
  rllib/utils/deprecation.py
  rllib/utils/exploration/curiosity.py
  rllib/utils/exploration/exploration.py
  rllib/utils/exploration/gaussian_noise.py
  rllib/utils/exploration/ornstein_uhlenbeck_noise.py
  rllib/utils/exploration/random.py
  rllib/utils/exploration/stochastic_sampling.py
  rllib/utils/framework.py
  rllib/utils/memory.py
  rllib/utils/metrics/window_stat.py
  rllib/utils/multi_agent.py
  rllib/utils/numpy.py
  rllib/utils/test_utils.py
  rllib/utils/tf_ops.py
  rllib/utils/tf_utils.py
  rllib/utils/threading.py
  rllib/utils/torch_ops.py
  rllib/utils/torch_utils.py
  rllib/utils/window_stat.py
Labels: @tests-ok

#19911 [core] Fix wrong local resource view in raylet
  python/ray/tests/test_placement_group_3.py
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#19870 [Runtime env] Add a test to make sure resource deadlock message is not printed when waiting for workers
  python/ray/tests/test_runtime_env.py
Labels: @author-action-required

#19431 [serve] split ReplicaStartupState.PENDING into PENDING_ALLOCATION and PENDING_INITIALIZATION
  python/ray/serve/BUILD
  python/ray/serve/backend_state.py
  python/ray/serve/replica.py
  python/ray/serve/tests/test_backend_state.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_warnings.py
Labels: @author-action-required

#19947 [serve] Rename BackendInfo -> DeploymentInfo
  python/ray/serve/api.py
  python/ray/serve/backend_state.py
  python/ray/serve/common.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_backend_state.py
  python/ray/serve/tests/test_controller.py
  src/ray/protobuf/serve.proto
Labels: @author-action-required

#19963 [Core][GCS] remove gcs object manager
  BUILD.bazel
  python/ray/includes/global_state_accessor.pxd
  python/ray/includes/global_state_accessor.pxi
  python/ray/state.py
  src/mock/ray/gcs/gcs_client/accessor.h
  src/mock/ray/gcs/gcs_client/gcs_client.h
  src/mock/ray/gcs/gcs_server/gcs_object_manager.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/global_state_accessor.h
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_init_data.cc
  src/ray/gcs/gcs_server/gcs_init_data.h
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_object_manager.cc
  src/ray/gcs/gcs_server/gcs_object_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/test/gcs_object_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/gcs/pubsub/gcs_pub_sub.h
  src/ray/protobuf/gcs_service.proto
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: @tests-ok

#19918 Listen to 127.0.0.1 if node ip is 127.0.0.1
  dashboard/agent.py
  dashboard/head.py
  dashboard/modules/reporter/reporter_agent.py
  python/ray/_private/metrics_agent.py
  python/ray/tests/test_basic_3.py
Labels: @tests-ok

#19971 [RFC] Add tsan build mode
  .bazelrc
  python/setup.py
Labels: @tests-ok

#19982 [RLlib] Fix deprecated warning for torch_ops.py (soft-replaced by torch_utils.py).
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/ars/ars.py
  rllib/agents/cql/cql_torch_policy.py
  rllib/agents/ddpg/ddpg_torch_policy.py
  rllib/agents/ddpg/tests/test_ddpg.py
  rllib/agents/dqn/dqn_torch_policy.py
  rllib/agents/dqn/r2d2_torch_policy.py
  rllib/agents/dqn/simple_q_torch_policy.py
  rllib/agents/dreamer/dreamer_torch_policy.py
  rllib/agents/es/es.py
  rllib/agents/es/es_torch_policy.py
  rllib/agents/impala/vtrace_torch.py
  rllib/agents/impala/vtrace_torch_policy.py
  rllib/agents/maml/maml_torch_policy.py
  rllib/agents/marwil/marwil_torch_policy.py
  rllib/agents/mbmpo/mbmpo.py
  rllib/agents/mbmpo/mbmpo_torch_policy.py
  rllib/agents/mbmpo/model_ensemble.py
  rllib/agents/ppo/appo_torch_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
  rllib/agents/sac/rnnsac_torch_policy.py
  rllib/agents/sac/sac_torch_policy.py
  rllib/agents/sac/tests/test_sac.py
  rllib/examples/centralized_critic.py
  rllib/examples/models/action_mask_model.py
  rllib/examples/models/parametric_actions_model.py
  rllib/examples/models/trajectory_view_utilizing_models.py
  rllib/models/torch/attention_net.py
  rllib/models/torch/complex_input_net.py
  rllib/models/torch/modules/multi_head_attention.py
  rllib/models/torch/modules/relative_multi_head_attention.py
  rllib/models/torch/recurrent_net.py
  rllib/models/utils.py
  rllib/policy/policy_template.py
  rllib/policy/torch_policy.py
  rllib/utils/exploration/curiosity.py
  rllib/utils/exploration/epsilon_greedy.py
  rllib/utils/framework.py
Labels: @tests-ok

#19930 [Core] improve the GCS address update failure error message.
  src/ray/core_worker/gcs_server_address_updater.cc
Labels: @author-action-required

#19757 [CI] Run Java CI on Mac
  .buildkite/pipeline.macos.yml
  java/runtime/src/main/java/io/ray/runtime/util/SystemUtil.java
  java/test.sh
  java/test/src/main/java/io/ray/test/RayJavaLoggingTest.java
Labels: @tests-ok

#20010 [Datasets] Add standard deviation aggregation.
  python/ray/data/aggregate.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#20035 [Datasets] Follow-up to groupby standard deviation PR
  python/ray/data/aggregate.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#19886 [Tests] Try deflaking test placement group mini integration.
  python/ray/tests/test_placement_group_mini_integration.py
Labels: @author-action-required

#20026 [scheduler] Update local object store usage
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
Labels: @tests-ok

#20009 [runtime env] Add plugin name to internal URI format and add GC for py_modules
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_validation.py
  python/ray/tests/test_runtime_env_working_dir.py
  src/ray/common/runtime_env_manager.cc
  src/ray/common/runtime_env_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#20048 [pg] Fix the test case which hangs because of scheduling dead lock
  python/ray/tests/test_placement_group_3.py
Labels: @author-action-required

#20049 [Core][Core-worker] de-escalate the error message when worker is accessed after shutdown.
  src/ray/core_worker/core_worker.cc
Labels: @author-action-required

#19933 [gcs] use gcs kv in internal kv
  dashboard/agent.py
  dashboard/head.py
  python/ray/_private/gcs_utils.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/experimental/internal_kv.py
  python/ray/tests/test_advanced.py
  python/ray/util/client/server/proxier.py
  python/ray/worker.py
Labels: @author-action-required

#19860 [job submission] Add stop API + subprocess cleanup
  ci/travis/ci.sh
  dashboard/modules/job/data_types.py
  dashboard/modules/job/job_head.py
  dashboard/modules/job/sdk.py
  dashboard/modules/job/tests/test_http_job_server.py
  python/ray/_private/job_manager/job_manager.py
  python/ray/_private/job_manager/tests/test_job_manager.py
  python/ray/tests/BUILD
  python/ray/tests/subprocess_driver_scripts/__init__.py
  python/ray/tests/subprocess_driver_scripts/override_env_var.py
  python/ray/tests/subprocess_driver_scripts/print_namespace.py
  python/ray/tests/subprocess_driver_scripts/print_runtime_env.py
  python/ray/tests/subprocess_driver_scripts/script_with_exception.py
  python/ray/tests/test_job_manager.py
Labels: @tests-ok, serve

#20016 [Tune; RLlib] Move Tune tests that use RLlib into separate buildkite job.
  .buildkite/pipeline.yml
  ci/travis/determine_tests_to_run.py
  python/ray/tune/BUILD
Labels: @tests-ok

#19907 Add configuration context to dataset
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/impl/pipeline_executor.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_context_propagation.py
Labels: @tests-ok

#19680 [Placement group] Raise an exception when invalid resources are specified with the placement group.
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_placement_group.py
  python/ray/util/placement_group.py
Labels: @author-action-required

#18294 Update Ray client docs
  doc/source/cluster/ray-client.rst
Labels: @author-action-required

#19975 Add Chaos testing fixture + test actor tasks chaos test in CI
  python/ray/tests/BUILD
  python/ray/tests/conftest.py
  python/ray/tests/test_chaos.py
  python/ray/tests/test_failure_3.py
Labels: @tests-ok

#20044 [Datasets] Multi-aggregations [1/3]: Add basic support for groupby multi-aggregations.
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/simple_block.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#19841 [Placement Group] Add stats to pg scheduling
  python/ray/state.py
  python/ray/tests/test_metrics_agent.py
  python/ray/tests/test_placement_group.py
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/protobuf/gcs.proto
  src/ray/stats/metric_defs.h
  src/ray/util/util.h
Labels: @tests-ok, @author-action-required

#20004 [scheduler] Include depth and function descriptor in scheduling class
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  python/ray/tests/test_scheduling.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/stats/metric_defs.h
Labels: @author-action-required

#20071 [tune] clean up legacy branch in update_avail_resources.
  python/ray/tune/ray_trial_executor.py
Labels: @tests-ok

#19924 [core] Set default max_pending_lease_requests_per_scheduling_category to 10
  src/ray/common/ray_config_def.h
Labels: @tests-ok

#20075 [Core][Pubsub] add worker failure message to gcs pubsub
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/protobuf/pubsub.proto
Labels: @tests-ok

#20028 [Release] Refactor User Tests
  release/.buildkite/build_pipeline.py
  release/e2e.py
  release/horovod_tests/driver_requirements.txt
  release/horovod_tests/driver_requirements_master.txt
  release/horovod_tests/horovod_tests.yaml
  release/ml_user_tests/horovod/app_config.yaml
  release/ml_user_tests/horovod/app_config_master.yaml
  release/ml_user_tests/horovod/compute_tpl.yaml
  release/ml_user_tests/horovod/driver_requirements.txt
  release/ml_user_tests/horovod/driver_setup_latest.sh
  release/ml_user_tests/horovod/driver_setup_master.sh
  release/ml_user_tests/horovod/horovod_user_test.py
  release/ml_user_tests/ml_user_tests.yaml
  release/ml_user_tests/ray-lightning/app_config.yaml
  release/ml_user_tests/ray-lightning/app_config_master.yaml
  release/ml_user_tests/ray-lightning/compute_tpl.yaml
  release/ml_user_tests/ray-lightning/driver_requirements.txt
  release/ml_user_tests/ray-lightning/driver_setup.sh
  release/ml_user_tests/ray-lightning/ray_lightning_user_test.py
  release/ml_user_tests/train/app_config.yaml
  release/ml_user_tests/train/compute_tpl.yaml
  release/ml_user_tests/train/driver_requirements.txt
  release/ml_user_tests/train/driver_setup.sh
  release/ml_user_tests/train/train_tensorflow_mnist_test.py
  release/ml_user_tests/train/train_torch_linear_test.py
  release/ml_user_tests/tune_rllib/app_config.yaml
  release/ml_user_tests/tune_rllib/compute_tpl.yaml
  release/ml_user_tests/tune_rllib/driver_requirements.txt
  release/ml_user_tests/tune_rllib/driver_setup.sh
  release/ml_user_tests/tune_rllib/run_connect_tests.py
  release/ml_user_tests/xgboost/app_config_gpu.yaml
  release/ml_user_tests/xgboost/app_config_gpu_master.yaml
  release/ml_user_tests/xgboost/tpl_gpu_small_scaling.yaml
  release/ml_user_tests/xgboost/train_gpu_connect.py
  release/ray_lightning_tests/ray_lightning_tests.yaml
  release/train_tests/train_tests.yaml
  release/xgboost_tests/xgboost_tests.yaml
  rllib/examples/tune/framework.py
Labels: @tests-ok

#20133 [test] Support different s3 url formats
  release/e2e.py
Labels: @tests-ok

#18941 [core]Simplify filesystem
  src/ray/util/filesystem.cc
  src/ray/util/filesystem.h
  src/ray/util/filesystem_test.cc
  src/ray/util/logging.cc
  src/ray/util/logging_test.cc
Labels: @author-action-required

#20121 [runtime env] Fix runtime env conda test and enable it in CI
  ci/travis/ci.sh
  python/ray/_private/runtime_env/conda.py
  python/ray/tests/conftest.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_conda.py
  python/ray/tests/test_runtime_env_working_dir.py
Labels: @tests-ok

#19946 [core] Evict lineage to bound memory usage
  java/runtime/src/main/java/io/ray/runtime/object/ObjectSerializer.java
  python/ray/exceptions.py
  python/ray/serialization.py
  python/ray/tests/test_reconstruction.py
  src/mock/ray/core_worker/task_manager.h
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/protobuf/common.proto
Labels: @author-action-required

#20059 [Core]Chaos testing nightly
  python/ray/_private/test_utils.py
  python/ray/tests/conftest.py
  python/ray/tests/test_chaos.py
  release/.buildkite/build_pipeline.py
  release/nightly_tests/chaos_test.yaml
  release/nightly_tests/chaos_test/app_config.yaml
  release/nightly_tests/chaos_test/compute_template.yaml
  release/nightly_tests/chaos_test/dask_on_ray_app_config_reconstruction.yaml
  release/nightly_tests/chaos_test/test_chaos_basic.py
Labels: @author-action-required

#20126 [Core] Fix the named actor get or create race condition
  python/ray/tests/test_actor_advanced.py
  src/mock/ray/core_worker/actor_creator.h
  src/ray/core_worker/actor_creator.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
Labels: @author-action-required

#18619 [autoscaler] AWS Autoscaler CloudWatch Integration
  python/ray/autoscaler/_private/aws/cloudwatch/__init__.py
  python/ray/autoscaler/_private/aws/cloudwatch/cloudwatch_helper.py
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/autoscaler/_private/updater.py
  python/ray/autoscaler/aws/cloudwatch/example-cloudwatch-agent-config.json
  python/ray/autoscaler/aws/cloudwatch/prometheus.yml
  python/ray/autoscaler/aws/cloudwatch/ray_prometheus_waiter.sh
  python/ray/autoscaler/aws/example-cloudwatch.yaml
  python/ray/autoscaler/ray-schema.json
  python/setup.py
Labels: @tests-ok

#20190 [mac] Listen on 127.0.0.1 if node ip is 127.0.0.1
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/tests/test_basic_3.py
  python/ray/util/client/server/proxier.py
Labels: @tests-ok

#20063 [Placement Group] [Test] Fix pg.ready hang forever when gcs restarting
  python/ray/tests/test_placement_group_3.py
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#20165 [runtime env] Enable reference counting for URIs for actors
  python/ray/tests/test_runtime_env_conda.py
  python/ray/tests/test_runtime_env_working_dir.py
  src/ray/common/runtime_env_manager.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#19463 Ray Serve Java Replica can be extended
  java/serve/src/main/java/io/ray/serve/Constants.java
  java/serve/src/main/java/io/ray/serve/DeploymentConfig.java
  java/serve/src/main/java/io/ray/serve/DeploymentInfo.java
  java/serve/src/main/java/io/ray/serve/DeploymentVersion.java
  java/serve/src/main/java/io/ray/serve/DummyBackendReplica.java
  java/serve/src/main/java/io/ray/serve/DummyReplica.java
  java/serve/src/main/java/io/ray/serve/ProxyActor.java
  java/serve/src/main/java/io/ray/serve/RayServeConfig.java
  java/serve/src/main/java/io/ray/serve/RayServeHandle.java
  java/serve/src/main/java/io/ray/serve/RayServeMetrics.java
  java/serve/src/main/java/io/ray/serve/RayServeReplica.java
  java/serve/src/main/java/io/ray/serve/RayServeReplicaImpl.java
  java/serve/src/main/java/io/ray/serve/RayServeWrappedReplica.java
  java/serve/src/main/java/io/ray/serve/ReplicaConfig.java
  java/serve/src/main/java/io/ray/serve/ReplicaContext.java
  java/serve/src/main/java/io/ray/serve/ReplicaName.java
  java/serve/src/main/java/io/ray/serve/ReplicaSet.java
  java/serve/src/main/java/io/ray/serve/Router.java
  java/serve/src/main/java/io/ray/serve/api/Serve.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollClient.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollNamespace.java
  java/serve/src/main/java/io/ray/serve/util/ServeProtoUtil.java
  java/serve/src/test/java/io/ray/serve/HttpProxyTest.java
  java/serve/src/test/java/io/ray/serve/ProxyActorTest.java
  java/serve/src/test/java/io/ray/serve/RayServeHandleTest.java
  java/serve/src/test/java/io/ray/serve/RayServeReplicaTest.java
  java/serve/src/test/java/io/ray/serve/ReplicaConfigTest.java
  java/serve/src/test/java/io/ray/serve/ReplicaNameTest.java
  java/serve/src/test/java/io/ray/serve/ReplicaSetTest.java
  java/serve/src/test/java/io/ray/serve/RouterTest.java
  java/serve/src/test/java/io/ray/serve/poll/KeyTypeTest.java
  java/serve/src/test/java/io/ray/serve/poll/LongPollClientTest.java
  java/serve/src/test/java/io/ray/serve/util/ServeProtoUtilTest.java
  src/ray/protobuf/serve.proto
Labels: serve, @external-author-action-required

#20104 [serve] Add Google Cloud Storage as a backend
  doc/source/serve/deployment.rst
  python/ray/serve/storage/checkpoint_path.py
  python/ray/serve/storage/ray_gcs_kv_store.py
  python/ray/serve/tests/storage_tests/test_kv_store.py
  python/requirements.txt
  release/serve_tests/workloads/serve_cluster_fault_tolerance_gcs.py
Labels: @external-author-action-required

#20014 [gcs] Update all redis kv usage in python except function table
  cpp/src/ray/util/process_helper.cc
  dashboard/agent.py
  dashboard/head.py
  dashboard/modules/event/event_agent.py
  dashboard/modules/job/common.py
  dashboard/modules/node/node_head.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/modules/runtime_env/runtime_env_agent.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/tests/test_dashboard.py
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  python/ray/_private/gcs_utils.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/services.py
  python/ray/_raylet.pyx
  python/ray/cluster_utils.py
  python/ray/experimental/internal_kv.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/scripts/scripts.py
  python/ray/serve/storage/kv_store.py
  python/ray/tests/BUILD
  python/ray/tests/test_actor.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_multi_node_2.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_placement_group_3.py
  python/ray/tests/test_ray_debugger.py
  python/ray/tests/test_runtime_env_packaging.py
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_runtime_env_working_dir_2.py
  python/ray/util/client/server/server.py
  python/ray/util/rpdb.py
  python/ray/worker.py
Labels: @author-action-required

#20210 [CI; Tune] Split Tune tests and examples
  .buildkite/pipeline.yml
  python/ray/tune/BUILD
Labels: @tests-ok

#20220 [Test] Fix newly added nightly tests, threaded actor + chaos testing
  release/nightly_tests/chaos_test/test_chaos_basic.py
  release/nightly_tests/stress_tests/test_threaded_actors.py
Labels: @author-action-required

#20013 [autoscaler] Use drain node api in autoscaler before terminating nodes
  doc/source/fake-autoscaler.rst
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/fake_multi_node/node_provider.py
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/autoscaler/_private/prom_metrics.py
  python/ray/cluster_utils.py
  python/ray/setup-dev.py
  python/ray/tests/BUILD
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_autoscaler_drain_node_api.py
  python/ray/tests/test_autoscaling_policy.py
  python/ray/tests/test_metrics_agent.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: @author-action-required

#20255 [Release] Commit sanity check when a url is provided
  release/e2e.py
Labels: @tests-ok

#20111 [Core][Pubsub] Implement Python GCS publisher and subscriber
  .buildkite/pipeline.yml
  dashboard/agent.py
  dashboard/dashboard.py
  dashboard/head.py
  dashboard/modules/node/node_consts.py
  dashboard/modules/node/node_head.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/log_monitor.py
  python/ray/_private/services.py
  python/ray/_private/test_utils.py
  python/ray/_private/utils.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/tests/BUILD
  python/ray/tests/test_failure.py
  python/ray/tests/test_failure_4.py
  python/ray/tests/test_gcs_pubsub.py
  python/ray/worker.py
  src/mock/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/pubsub_handler.cc
  src/ray/gcs/gcs_server/pubsub_handler.h
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/protobuf/gcs_service.proto
  src/ray/protobuf/pubsub.proto
  src/ray/pubsub/publisher.cc
  src/ray/pubsub/publisher.h
  src/ray/pubsub/test/publisher_test.cc
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: @author-action-required

#20261 Fix aiohttp 3.8.0 breaking changes (and unpin from 3.7)
  ci/asan_tests/ray-project/requirements.txt
  ci/travis/test-wheels.sh
  dashboard/optional_deps.py
  dashboard/utils.py
  python/requirements.txt
  python/requirements/requirements_default.txt
  python/setup.py
Labels: @tests-ok

#20147 [CI] make using gcc 9 explicit
  .buildkite/Dockerfile
Labels: @tests-ok

#19337 [Test] [runtime env] Retry wheel urls for up to 2h to give time for Mac wheels to build
  release/runtime_env_tests/runtime_env_tests.yaml
  release/runtime_env_tests/workloads/wheel_urls.py
Labels: @tests-ok

#20217 [RLlib] Issue: Get single step input dict incorrect.
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/policy/sample_batch.py
Labels: @tests-ok

#20175 [Core] Reduce the frequency of retry messages
  src/ray/raylet/agent_manager.cc
Labels: @author-action-required

#20263 [CI] Rebalance Tune tests a bit.
  .buildkite/pipeline.yml
Labels: @tests-ok

#20148 [Core][actor out-of-order execution 1/n] Move CoreWorkerDirectActorTaskSubmitter into a separate file
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
Labels: @author-action-required

#20212 [WINDOWS] unskip tests
  ci/travis/ci.sh
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_basic_3.py
Labels: windows

#20281 [runtime env] Revert reference counting for per-actor URIs
  python/ray/tests/test_runtime_env_conda.py
  python/ray/tests/test_runtime_env_working_dir_2.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/raylet/node_manager.cc
Labels: @tests-ok

#19773 [Tune] Remove legacy resources implementations in Runner and Executor.
  doc/source/tune/key-concepts.rst
  doc/source/tune/user-guide.rst
  python/ray/tune/integration/horovod.py
  python/ray/tune/integration/tensorflow.py
  python/ray/tune/integration/torch.py
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/schedulers/hb_bohb.py
  python/ray/tune/schedulers/hyperband.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/schedulers/resource_changing_scheduler.py
  python/ray/tune/schedulers/trial_scheduler.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_integration_wandb.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tests/test_trial_executor_inheritance.py
  python/ray/tune/tests/test_trial_runner.py
  python/ray/tune/tests/test_trial_runner_2.py
  python/ray/tune/tests/test_trial_runner_pg.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_tune_restore.py
  python/ray/tune/trainable.py
  python/ray/tune/trial.py
  python/ray/tune/trial_executor.py
  python/ray/tune/trial_runner.py
  python/ray/tune/utils/placement_groups.py
  python/ray/util/sgd/tf/tf_trainer.py
  python/ray/util/xgboost/simple_tune.py
  rllib/examples/rollout_worker_custom_workflow.py
Labels: @tests-ok

#20074 [Datasets] Multi-aggregations [2/3]: Add groupby multi-column/multi-lambda aggregation
  python/ray/data/aggregate.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/block_list.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#20287 [Core][Dashboard] Fallback to grpc.experimental.aio when importing grpc.aio
  dashboard/agent.py
  dashboard/head.py
  dashboard/modules/actor/actor_head.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/utils.py
Labels: @tests-ok

#20264 [runtime env] Enable multinode tests
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_runtime_env_working_dir_2.py
Labels: @tests-ok

#20274 [Client] connect to localhost via 127.0.0.1
  python/ray/util/client/__init__.py
  python/ray/util/client/ray_client_helpers.py
  python/ray/util/client/server/proxier.py
  python/ray/worker.py
Labels: @tests-ok

#20248 [RLlib; Documentation] Minor fixes "rllib in 60s" and per-feature sigils.
  doc/examples/overview.rst
  doc/examples/plot_example-a3c.rst
  doc/source/_static/css/custom.css
  doc/source/images/rllib/rllib-index-external-simulator.svg
  doc/source/images/rllib/sigils/rllib-sigil-distributed-learning.svg
  doc/source/images/rllib/sigils/rllib-sigil-external-simulators.svg
  doc/source/images/rllib/sigils/rllib-sigil-multi-agent.svg
  doc/source/images/rllib/sigils/rllib-sigil-offline-rl.svg
  doc/source/images/rllib/sigils/rllib-sigil-vector-envs.svg
  doc/source/rllib-algorithms.rst
  doc/source/rllib-concepts.rst
  doc/source/rllib-dev.rst
  doc/source/rllib-env.rst
  doc/source/rllib-examples.rst
  doc/source/rllib-models.rst
  doc/source/rllib-offline.rst
  doc/source/rllib-package-ref.rst
  doc/source/rllib-sample-collection.rst
  doc/source/rllib-toc.rst
  doc/source/rllib-training.rst
  doc/source/rllib/core-concepts.rst
  doc/source/rllib/index.rst
  doc/source/rllib/we_are_hiring.rst
Labels: @tests-ok

#20306 [core] Move test_reconstruction to large test suite
  python/ray/tests/BUILD
Labels: @author-action-required

#20218 [Core] Add Placement group performance test
  python/ray/_private/ray_perf.py
  release/.buildkite/build_pipeline.py
  release/nightly_tests/nightly_tests.yaml
  release/nightly_tests/placement_group_tests/pg_perf_test_compute.yaml
  release/nightly_tests/placement_group_tests/placement_group_performance_test.py
  release/nightly_tests/stress_tests/test_placement_group.py
Labels: @author-action-required

#20280 [runtime_env] Support working_dir and py_modules from HTTPS and Google Cloud Storage
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/job/tests/test_job_manager.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/validation.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/tests/test_runtime_env_packaging.py
  python/ray/tests/test_runtime_env_validation.py
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_runtime_env_working_dir_2.py
Labels: release-blocker, @author-action-required

#20299 [gcs] Make gcs client in python able to auto reconnect
  dashboard/agent.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/test_utils.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/worker.py
Labels: @author-action-required

#20160 [Core][actor out-of-order execution 4/n] refactor the actor receiver code
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/actor_scheduling_util.cc
  src/ray/core_worker/transport/actor_scheduling_util.h
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/transport/fiber_state_manager.h
  src/ray/core_worker/transport/normal_scheduling_queue.cc
  src/ray/core_worker/transport/normal_scheduling_queue.h
  src/ray/core_worker/transport/scheduling_queue.h
  src/ray/core_worker/transport/thread_pool_manager.cc
  src/ray/core_worker/transport/thread_pool_manager.h
Labels: @author-action-required

#20120 Revert "Revert "[core] Fail objects when pull/reconstruction hangs (#19789)" (#19904)"
  python/ray/tests/test_reconstruction.py
  src/ray/core_worker/gcs_server_address_updater.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/ownership_based_object_directory.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/protobuf/pubsub.proto
  src/ray/pubsub/subscriber.cc
  src/ray/raylet/node_manager.cc
  src/ray/stats/metric_exporter_client.cc
Labels: @author-action-required

#20149 [Core][actor out-of-order execution 2/n] create abstraction for the queuing logic on the client/actor submission.
  src/ray/core_worker/transport/actor_submit_queue.h
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.h
Labels: @author-action-required

#20288 [Core] Fix pg stats not imported
  python/ray/tests/test_metrics_agent.py
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/stats/metric.h
Labels: @author-action-required

#20050 Only grant or reject spillback lease request
  python/ray/node.py
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/scheduling_policy.cc
  src/ray/raylet/scheduling/scheduling_policy.h
  src/ray/raylet/scheduling/scheduling_policy_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @author-action-required

#20366 [RLlib] Issue 20269: Offline RL example not working due to new_obs not being written to file.
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/policy.py
Labels: @tests-ok

#20389 [Build] Remove debug info from Ray libraries.
  .bazelrc
Labels: @tests-ok

#17887 [core] Nested task support via task depth + backpressure
  python/ray/tests/BUILD
  python/ray/tests/test_basic_3.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_scheduling.py
  python/ray/tests/test_scheduling_2.py
  python/ray/tests/test_worker_capping.py
  src/mock/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/common/ray_config_def.h
  src/ray/common/task/scheduling_resources.cc
  src/ray/common/task/scheduling_resources.h
  src/ray/common/task/task_spec.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#20152 [gcs] Update function table to use internal kv
  cpp/src/ray/util/process_helper.cc
  dashboard/head.py
  dashboard/modules/snapshot/snapshot_head.py
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  python/ray/_private/function_manager.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/import_thread.py
  python/ray/experimental/internal_kv.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/tests/test_actor.py
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/worker.py
Labels: @author-action-required, do-not-merge

#20412 [Hotfix] Fix flaky test_basic_workflows_2
  python/ray/workflow/tests/test_basic_workflows_2.py
Labels: @author-action-required

#20390 [RLlib] Document and extend action mask example.
  rllib/examples/action_masking.py
  rllib/examples/models/action_mask_model.py
Labels: @tests-ok, rllib

#20363 [Core] Better logs job message failure
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: @author-action-required

#20251 [Regresion test] Placement group long running test
  release/.buildkite/build_pipeline.py
  release/nightly_tests/nightly_tests.yaml
  release/nightly_tests/placement_group_tests/long_running_performance_test.py
  release/nightly_tests/placement_group_tests/long_running_test_compute.yaml
Labels: do-not-merge

#20368 [xlang] Add named actor xlang tests.
  java/test/src/main/java/io/ray/test/CrossLanguageInvocationTest.java
  java/test/src/main/resources/test_cross_language_invocation.py
Labels: xlang

#20393 [Release] Fix app config for `horovod_tests`
  release/horovod_tests/app_config_master.yaml
  release/ml_user_tests/horovod/app_config_master.yaml
  release/ml_user_tests/ml_user_tests.yaml
Labels: @tests-ok

#20423 [dependencies] Use `redis[hiredis]` in setup.py
  python/setup.py
Labels: @author-action-required

#20150 [Core][actor out-of-order execution 3/n] Introducing out-of-order actor submit queue
  BUILD.bazel
  src/ray/core_worker/test/actor_submit_queue_test.cc
  src/ray/core_worker/transport/actor_submit_queue.h
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.h
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.h
Labels: @author-action-required

#20428 [DOC] Add namespace doc for Java part.
  doc/source/configure.rst
  doc/source/namespaces.rst
Labels: release-blocker

#20437 Add hiredis dependency on supported platforms
  python/setup.py
Labels: @author-action-required

#20250 [RLlib; Documentation] Some docstring cleanups; Rename RemoteVectorEnv into RemoteBaseEnv for clarity.
  rllib/BUILD
  rllib/agents/callbacks.py
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
  rllib/env/__init__.py
  rllib/env/base_env.py
  rllib/env/external_env.py
  rllib/env/external_multi_agent_env.py
  rllib/env/multi_agent_env.py
  rllib/env/remote_base_env.py
  rllib/env/remote_vector_env.py
  rllib/env/tests/test_remote_worker_envs.py
  rllib/evaluation/worker_set.py
  rllib/examples/documentation/custom_gym_env.py
  rllib/examples/remote_vector_env_with_custom_api.py
  rllib/models/tf/tf_modelv2.py
  rllib/utils/typing.py
Labels: @tests-ok

#20514 [Serve] Change multi_deployment_1k_noop_replica threshold
  release/serve_tests/workloads/multi_deployment_1k_noop_replica.py
Labels: do-not-merge

#19836 Fix race condition when starting redis
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/tests/conftest.py
  python/ray/tests/test_client_multi.py
Labels: windows

#20249 [RLlib; Documentation] RLlib README overhaul.
  README.rst
  doc/source/images/rllib/rllib-logo.png
  doc/source/images/rllib/rllib-logo.svg
  doc/source/ray-overview/index.rst
  doc/source/rllib/feature_overview.rst
  doc/source/rllib/index.rst
  rllib/BUILD
  rllib/README.md
  rllib/README.rst
  rllib/examples/documentation/rllib_on_ray_readme.py
  rllib/examples/documentation/rllib_on_rllib_readme.py
Labels: @tests-ok

#20480 [Datasets] Fix empty Dataset.iter_batches() when trying to prefetch more blocks than exist in the dataset
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#20542 [Datasets] Bump NumPy version to >= 1.19.0 for Python 3.6.
  python/setup.py
Labels: @tests-ok

#20486 [RLlib] auto API reference pages: `rllib/env` package only.
  doc/source/images/rllib/env_classes_overview.svg
  doc/source/index.rst
  doc/source/rllib-package-ref.rst
  doc/source/rllib/__WIP__.txt
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/env/base_env.rst
  doc/source/rllib/package_ref/env/external_env.rst
  doc/source/rllib/package_ref/env/multi_agent_env.rst
  doc/source/rllib/package_ref/env/vector_env.rst
  doc/source/rllib/package_ref/index.rst
Labels: @tests-ok

#19675 [Core][Refactor CoreWorker 1/n] move CoreWorkerOptions to its own file
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
Labels: @author-action-required

#20177 [Core][actor out-of-order execution 6/n] plumbing work to make it work e2e
  doc/source/fault-tolerance.rst
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/tests/test_actor_out_of_order.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
Labels: @author-action-required

#20586 [datasets] Add an env var for default progress bar behavior
  python/ray/data/impl/progress_bar.py
Labels: @author-action-required

#20443 Revert "Revert "[core] Nested task support via task depth + backpressure" (#20438)"
  python/ray/tests/BUILD
  python/ray/tests/test_basic_3.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_scheduling.py
  python/ray/tests/test_scheduling_2.py
  python/ray/tests/test_worker_capping.py
  src/mock/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/common/ray_config_def.h
  src/ray/common/task/scheduling_resources.cc
  src/ray/common/task/scheduling_resources.h
  src/ray/common/task/task_spec.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#20530 [Jobs][Ready for Review] Add documentation for ray job submission
  doc/source/index.rst
  doc/source/ray-job-submission/overview.rst
Labels: serve

#20591 Make fake node provider thread safe
  python/ray/autoscaler/_private/fake_multi_node/node_provider.py
Labels: @tests-ok

#20516 [core] Timeout object fetches that take too long
  python/ray/exceptions.py
  python/ray/serialization.py
  python/ray/tests/test_reconstruction.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/gcs_server_address_updater.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/ownership_based_object_directory.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/pubsub.proto
  src/ray/pubsub/subscriber.cc
  src/ray/raylet/node_manager.cc
  src/ray/stats/metric_exporter_client.cc
Labels: @author-action-required

#20410 [gcs] Remove rpush for storage in py
  python/ray/_private/function_manager.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/import_thread.py
  python/ray/worker.py
Labels: @author-action-required

#20424 [RLlib] Trainer sub-class for APPO (instead of using `build_trainer()`).
  rllib/agents/ppo/appo.py
  rllib/agents/tests/test_trainer.py
  rllib/agents/trainer.py
  rllib/agents/trainer_template.py
Labels: @tests-ok

#20680 [test] Update base image for nightly testing
  benchmarks/app_config.yaml
  release/long_running_tests/app_config_np.yaml
Labels: release-blocker

#20662 [gcs] Fix internal kv as the bottleneck when worker starts
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: release-blocker, @author-action-required

#20426 [Windows] only report metric reporting failure once
  src/ray/stats/metric_exporter.cc
Labels: windows

#20605 [ci][windows] Skip test_worker_capping.py::test_zero_cpu_scheduling
  python/ray/tests/test_worker_capping.py
Labels: @tests-ok

#20179 [Core] Raise an exception on Ray version mismatch
  python/ray/tests/test_failure.py
Labels: @author-action-required

#20536 [tune/rllib] Fix tune cloud tests for function and rllib trainables
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/trial_executor.py
  python/ray/tune/trial_runner.py
  release/.buildkite/build_pipeline.py
  release/tune_tests/cloud_tests/workloads/_tune_script.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
Labels: @tests-ok

#20458 [Part 1] Improve RayActorDeadError: Refactoring
  src/mock/ray/core_worker/task_manager.h
  src/ray/common/buffer.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/direct_task_transport_mock_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_task_transport.cc
Labels: @author-action-required

#20613 fix autoscaling config is not loaded when calling options()
  python/ray/serve/api.py
Labels: serve

#20635 [RLlib] Trainer sub-class A2C/A3C (instead of `build_trainer`).
  rllib/agents/a3c/a2c.py
  rllib/agents/a3c/a3c.py
  rllib/agents/trainer.py
Labels: @tests-ok

#20172 Fail calling Cluster() on windows, skip tests appropriately
  python/ray/cluster_utils.py
  python/ray/tests/conftest.py
  python/ray/tests/test_advanced.py
  python/ray/tests/test_asyncio_cluster.py
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_client_init.py
  python/ray/tests/test_component_failures_2.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_failure_4.py
  python/ray/tests/test_global_gc.py
  python/ray/tests/test_memstat.py
  python/ray/tests/test_multinode_failures.py
  python/ray/tests/test_object_manager.py
  python/ray/tests/test_object_spilling.py
  python/ray/tests/test_ray_debugger.py
  python/ray/tests/test_scheduling.py
  python/ray/tests/test_stress.py
  python/ray/tests/test_stress_failure.py
Labels: windows

#20696 Replace time based seed generation with `absl::BitGen` and `absl::Uniform`
  BUILD.bazel
  python/ray/tests/test_basic_3.py
  src/ray/util/util.h
Labels: windows

#20707 [docs] add dask compatibility for 1.9.0
  doc/source/data/dask-on-ray.rst
Labels: release-blocker

#20693 [data] Fix slow block evaluation when splitting is enabled
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/block_list.py
  python/ray/data/impl/compute.py
  python/ray/data/impl/lazy_block_list.py
  python/ray/data/impl/shuffle.py
  python/ray/data/impl/sort.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#20277 [Nightly test] Chaos test fixture
  python/ray/_private/test_utils.py
  python/ray/tests/test_chaos.py
  release/nightly_tests/chaos_test.yaml
  release/nightly_tests/chaos_test/test_chaos_basic.py
  release/nightly_tests/setup_chaos.py
Labels: @author-action-required

#20608 Clean exported symbols
  src/ray/ray_exported_symbols.lds
Labels: @tests-ok

#20701 [Part 3] Improve ActorDiedError message: Passing error info
  src/mock/ray/core_worker/task_manager.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
Labels: @author-action-required

#20537 [RLlib; Docs] Auto API reference pages overhaul: `rllib/policy` and `rllib/agents` packages.
  doc/source/images/rllib/policy_classes_overview.svg
  doc/source/images/rllib/trainer_class_overview.svg
  doc/source/rllib-package-ref.rst
  doc/source/rllib/index.rst
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/package_ref/policy/custom_policies.rst
  doc/source/rllib/package_ref/policy/policy.rst
  doc/source/rllib/package_ref/policy/tf_policies.rst
  doc/source/rllib/package_ref/policy/torch_policy.rst
  doc/source/rllib/package_ref/trainer.rst
  rllib/policy/policy_map.py
Labels: @tests-ok

#20528 [Part 2] Improve RayActorDiedError: Store why the actor is dead to the actor table.
  python/ray/_private/test_utils.py
  python/ray/serve/tests/test_standalone.py
  python/ray/state.py
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_client_terminate.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_global_state.py
  python/ray/tests/test_placement_group_2.py
  python/ray/tests/test_placement_group_3.py
  python/ray/tests/test_reference_counting.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
Labels: @author-action-required

#20180 [Core] Fix worker pool crash due to incorrect `pending_exit_idle_workers_` usage
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#20717 [Nightly Test] Readjust nightly test schedule
  benchmarks/benchmark_tests.yaml
  benchmarks/object_store.yaml
  benchmarks/object_store/test_object_store.py
  release/.buildkite/build_pipeline.py
Labels: @author-action-required

#20740 [Nightly tests] Promote some tests stable.
  release/nightly_tests/chaos_test.yaml
Labels: @author-action-required

#20722 [Internal Observability] Move debug_state.txt to the log dir + support gcs_server debug state
  python/ray/autoscaler/_private/cluster_dump.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_basic_3.py
  python/ray/tests/test_runtime_env.py
  release/long_running_distributed_tests/README.rst
  release/long_running_tests/README.rst
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/grpc_based_resource_broadcaster.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: @author-action-required

#20677 [Release] Use NCCL backend for release tests
  python/ray/train/examples/train_linear_example.py
  release/ml_user_tests/ray-lightning/app_config.yaml
  release/ml_user_tests/ray-lightning/app_config_master.yaml
  release/ml_user_tests/ray-lightning/ray_lightning_user_test.py
  release/ml_user_tests/train/train_torch_linear_test.py
Labels: @tests-ok

#20712 [Datasets] Last-mile preprocessing docs.
  doc/source/data/dataset-ml-preprocessing.rst
  doc/source/data/dataset.rst
  doc/source/index.rst
Labels: @author-action-required

#20633 [RLlib] Trainer sub-class DQN/SimpleQ/APEX-DQN/R2D2 (instead of using `build_trainer`).
  rllib/agents/ddpg/apex.py
  rllib/agents/dqn/__init__.py
  rllib/agents/dqn/apex.py
  rllib/agents/dqn/dqn.py
  rllib/agents/dqn/r2d2.py
  rllib/agents/dqn/r2d2_tf_policy.py
  rllib/agents/dqn/r2d2_torch_policy.py
  rllib/agents/dqn/simple_q.py
  rllib/agents/dqn/simple_q_tf_policy.py
  rllib/agents/dqn/simple_q_torch_policy.py
  rllib/agents/trainer.py
Labels: @tests-ok

#20777 Exit worker when parent raylet dies
  python/ray/tests/mock_setup_worker.py
  python/ray/tests/test_failure_3.py
  src/ray/common/constants.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/util/process.cc
  src/ray/util/process.h
Labels: @tests-ok

#20570 [RLlib] Trainer sub-class IMPALA (instead of using `build_trainer()`).
  rllib/agents/impala/__init__.py
  rllib/agents/impala/impala.py
Labels: @tests-ok

#20784 [Datasets] Fix boundary sampling concatenation.
  python/ray/data/dataset.py
  python/ray/data/extensions/tensor_extension.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/sort.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#20163 [workflow] workflow.wait() feature
  doc/source/workflows/advanced.rst
  python/ray/workflow/__init__.py
  python/ray/workflow/api.py
  python/ray/workflow/common.py
  python/ray/workflow/execution.py
  python/ray/workflow/recovery.py
  python/ray/workflow/step_executor.py
  python/ray/workflow/tests/test_wait.py
Labels: @author-action-required

#20657 Add chaos test for shuffle
  python/ray/_private/test_utils.py
  python/ray/cluster_utils.py
  python/ray/experimental/shuffle.py
  python/ray/tests/conftest.py
  python/ray/tests/test_chaos.py
  python/ray/tests/test_failure_4.py
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count_test.cc
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/raylet/node_manager.cc
Labels: @author-action-required
