Repository ray-project/ray, pull requests merged in 2022-03, with the labels that each got.

#22700 Fix some outdated comments
  python/ray/data/block.py
  python/ray/data/read_api.py
Labels: @tests-ok

#20763 [doc] Update docs about actor garbage collection
  doc/source/ray-core/actors.rst
Labels: @author-action-required

#22628 [Serve] Add test for controller managing Java Replica
  ci/travis/ci.sh
  java/serve/src/main/java/io/ray/serve/RayServeWrappedReplica.java
  java/serve/src/main/java/io/ray/serve/util/ExampleEchoDeployment.java
  python/ray/includes/serialization.pxi
  python/ray/serve/BUILD
  python/ray/serve/config.py
  python/ray/serve/deployment_state.py
  python/ray/serve/tests/test_cross_langauge.py
  python/ray/serve/utils.py
  python/ray/serve/version.py
Labels: @author-action-required

#22618 Add buffering to object spilling
  doc/source/ray-core/memory-management.rst
  python/ray/external_storage.py
  python/ray/tests/conftest.py
  python/ray/tests/test_object_spilling.py
Labels: @author-action-required

#22720 [RFC] Disable actor queueing warning for concurrent actors
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
Labels: @tests-ok

#22482 Never re-use task workers for actors or GPU tasks
  python/ray/data/tests/test_dataset.py
  python/ray/tests/BUILD
  python/ray/tests/test_actor.py
  python/ray/tests/test_advanced_2.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_metrics.py
  python/ray/tests/test_output.py
  python/ray/tune/BUILD
  src/ray/common/ray_config_def.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#22715 [data] Pin pipeline executor actors to the driver node
  python/ray/data/dataset_pipeline.py
  python/ray/data/impl/pipeline_executor.py
Labels: @author-action-required

#22756 Fix K8s API
  python/ray/autoscaler/_private/_kubernetes/__init__.py
  python/ray/autoscaler/_private/_kubernetes/node_provider.py
Labels: release-blocker, P0, 1.11.0rc1-pick

#22730 [runtime env] Make env_vars take effect when pip install packages
  python/ray/_private/runtime_env/pip.py
  python/ray/tests/test_runtime_env_complicated.py
Labels: @tests-ok

#22792 Ray legacy operator does not retry monitor on failure.
  .github/CODEOWNERS
  python/ray/autoscaler/_private/monitor.py
  python/ray/ray_operator/operator.py
  python/ray/tests/kubernetes_e2e/test_k8s_operator_basic.py
Labels: release-blocker, P0, 1.11.0rc1-pick

#22710 [4/X][Pipeline] JSON serialization for serve dag nodes
  python/ray/experimental/dag/__init__.py
  python/ray/experimental/dag/class_node.py
  python/ray/experimental/dag/constants.py
  python/ray/experimental/dag/dag_node.py
  python/ray/experimental/dag/function_node.py
  python/ray/experimental/dag/input_node.py
  python/ray/serve/BUILD
  python/ray/serve/constants.py
  python/ray/serve/pipeline/constants.py
  python/ray/serve/pipeline/deployment_method_node.py
  python/ray/serve/pipeline/deployment_node.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/pipeline/tests/test_deployment_node.py
  python/ray/serve/pipeline/tests/test_json_serde.py
  python/ray/serve/pipeline/tests/test_modules.py
  python/ray/serve/replica.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/utils.py
Labels: @tests-ok

#22777 [LocalResourceManager] unify (Add/Subtract)(CPU/GPU)ResourceInstances
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
  src/ray/raylet/scheduling/local_task_manager.cc
  src/ray/raylet/scheduling/scheduling_ids.h
Labels: @tests-ok

#22809 Fix flaky test_metrics on windows
  python/ray/tests/test_metrics.py
Labels: @tests-ok

#22788 [dashboard] Remove redis in dashboard
  dashboard/agent.py
  dashboard/dashboard.py
  dashboard/head.py
  dashboard/modules/actor/actor_head.py
  dashboard/modules/actor/tests/test_actor.py
  dashboard/modules/node/node_head.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/tests/test_dashboard.py
  dashboard/utils.py
  python/ray/_private/metrics_agent.py
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/tests/test_metrics_agent.py
Labels: @author-action-required

#22813 [Release Test] Send release test result to db pipeline for new test infra
  release/ray_release/reporter/db.py
  release/ray_release/scripts/run_release_test.py
Labels: @tests-ok

#22830 [Datasets] Batch across windows in DatasetPipelines.
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/impl/block_batching.py
  python/ray/data/impl/stats.py
  python/ray/data/tests/test_dataset_pipeline.py
  python/ray/data/tests/test_stats.py
Labels: @tests-ok

#22829 [CI] run Mac C++ tests with static linking
  .buildkite/pipeline.macos.yml
Labels: @tests-ok

#22793 [5/X][Pipeline][Ray DAG] Make Ray InputNode more powerful with attr accessor
  python/ray/experimental/dag/class_node.py
  python/ray/experimental/dag/dag_node.py
  python/ray/experimental/dag/function_node.py
  python/ray/experimental/dag/input_node.py
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/experimental/dag/tests/test_input_node.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/pipeline/tests/test_json_serde.py
Labels: @tests-ok

#22816 [core] Enable lineage reconstruction by default
  .bazelrc
  doc/source/ray-core/fault-tolerance.rst
  release/e2e.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
Labels: @author-action-required

#22810 Stop and join actor asyncio threads during exit
  python/ray/_raylet.pyx
  python/ray/tests/BUILD
  python/ray/tests/test_asyncio.py
  python/ray/tests/test_concurrency_group.py
  python/ray/util/client/api.py
  python/ray/util/client/options.py
  python/ray/util/client/worker.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/fiber.h
  src/ray/core_worker/test/concurrency_group_manager_test.cc
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.cc
Labels: @tests-ok

#22880 [scheduling-policy 1/n] pass check-node-liveness by constructor
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/scheduling_policy.cc
  src/ray/raylet/scheduling/scheduling_policy.h
  src/ray/raylet/scheduling/scheduling_policy_test.cc
Labels: @tests-ok

#22827 [Test] Add missing tests to bazel BUILD
  ci/travis/bazel-sharding.py
  ci/travis/check-test-run.py
  ci/travis/ci.sh
  python/ray/tests/BUILD
  python/ray/tests/test_runtime_context.py
  python/ray/tune/BUILD
  python/ray/tune/tests/test_trial_runner_2.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/utils_for_test_trial_runner.py
  python/ray/util/sgd/tests/test_ptl.py
  rllib/BUILD
Labels: @tests-ok

#22113 Fixed MRO for `DerivedActorClass`
  python/ray/actor.py
  python/ray/tests/test_actor.py
Labels: bug, QS

#22886 Make a pass fixing Dataset API issues
  doc/source/data/dataset-tensor-support.rst
  doc/source/data/examples/big_data_ingestion.ipynb
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  python/ray/data/aggregate.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/compute.py
  python/ray/data/impl/shuffle.py
  python/ray/data/impl/util.py
  python/ray/data/read_api.py
  python/ray/data/row.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#22907 [scheduling policy 3/n][rfc] Refactor SchedulingPolicy into interface and implementations
  BUILD.bazel
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.h
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.h
  src/ray/raylet/scheduling/policy/random_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/random_scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_options.h
  src/ray/raylet/scheduling/policy/scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
  src/ray/raylet/scheduling/policy/spread_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/spread_scheduling_policy.h
  src/ray/raylet/scheduling/scheduling_policy.h
Labels: @tests-ok

#22911 [core] Deflake test_plasma_unlimited
  python/ray/_private/test_utils.py
  python/ray/tests/test_plasma_unlimited.py
Labels: @author-action-required

#22913 [Serve] [1/3 Wrappers] Allow `@serve.batch` to accept args and kwargs
  python/ray/serve/batching.py
  python/ray/serve/tests/test_batching.py
Labels: @author-action-required

#22914 [Serve] [2/3 Wrappers] Add Basic HTTP Adapters
  python/ray/serve/BUILD
  python/ray/serve/http_adapters.py
  python/ray/serve/tests/test_http_adapters.py
  python/ray/serve/utils.py
Labels: @author-action-required

#22878 [6/X][Pipeline] Add HTTP ingress to serve pipeline
  python/ray/experimental/dag/__init__.py
  python/ray/experimental/dag/input_node.py
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/serve/pipeline/generate.py
  python/ray/serve/pipeline/ingress.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/pipeline/pipeline_input_node.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/pipeline/tests/test_json_serde.py
  python/ray/serve/pipeline/tests/test_modules.py
Labels: @author-action-required

#22957 [Serve] Use starlette public accessor
  python/ray/serve/api.py
Labels: @author-action-required

#22934 [7/X][Pipeline] pipeline user facing build function
  python/ray/actor.py
  python/ray/experimental/dag/class_node.py
  python/ray/experimental/dag/dag_node.py
  python/ray/experimental/dag/function_node.py
  python/ray/experimental/dag/input_node.py
  python/ray/experimental/dag/tests/test_class_dag.py
  python/ray/experimental/dag/tests/test_function_dag.py
  python/ray/experimental/dag/tests/test_input_node.py
  python/ray/remote_function.py
  python/ray/serve/BUILD
  python/ray/serve/api.py
  python/ray/serve/pipeline/api.py
  python/ray/serve/pipeline/deployment_node.py
  python/ray/serve/pipeline/generate.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/pipeline/pipeline_input_node.py
  python/ray/serve/pipeline/tests/resources/__init__.py
  python/ray/serve/pipeline/tests/resources/test_dags.py
  python/ray/serve/pipeline/tests/resources/test_modules.py
  python/ray/serve/pipeline/tests/test_build.py
  python/ray/serve/pipeline/tests/test_deployment_node.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/pipeline/tests/test_json_serde.py
Labels: @tests-ok

#22963 [ci/release] Migrate Runtime Env tests
  release/.buildkite/build_pipeline.py
  release/release_tests.yaml
Labels: @tests-ok

#22965 [ci/release] Migrate Serve tests
  release/.buildkite/build_pipeline.py
  release/release_tests.yaml
Labels: @tests-ok

#22966 [ci/release] Migrate SGD tests
  release/.buildkite/build_pipeline.py
  release/release_tests.yaml
Labels: @tests-ok

#22973 [tune] Add `Trainable.postprocess_checkpoint`
  python/ray/tune/function_runner.py
  python/ray/tune/trainable.py
Labels: @author-action-required

#23003 [docs] templates and contribution guide (fixes #21753)
  doc/source/_templates/template.ipynb
  doc/source/_templates/template.md
  doc/source/_toc.yml
  doc/source/ray-contribute/development.rst
  doc/source/ray-contribute/docs.ipynb
Labels: docs

#22843 Support local py_modules in jobs
  dashboard/modules/dashboard_sdk.py
  dashboard/modules/job/sdk.py
  dashboard/modules/job/tests/test_http_job_server.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
Labels: @tests-ok

#22823 [docs] external promo content
  doc/source/_includes/clusters/announcement.rst
  doc/source/_includes/clusters/announcement_bottom.rst
  doc/source/_includes/core/announcement.rst
  doc/source/_includes/core/announcement_bottom.rst
  doc/source/_includes/data/announcement.rst
  doc/source/_includes/data/announcement_bottom.rst
  doc/source/_includes/images/rl_summit_promo_square.png
  doc/source/_includes/images/rl_summit_promo_thin.png
  doc/source/_includes/overview/announcement.rst
  doc/source/_includes/overview/announcement_bottom.rst
  doc/source/_includes/rllib/announcement.rst
  doc/source/_includes/rllib/announcement_bottom.rst
  doc/source/_includes/rllib/we_are_hiring.rst
  doc/source/_includes/rllib_announcement.rst
  doc/source/_includes/serve/announcement.rst
  doc/source/_includes/serve/announcement_bottom.rst
  doc/source/_includes/train/announcement.rst
  doc/source/_includes/train/announcement_bottom.rst
  doc/source/_includes/tune/announcement.rst
  doc/source/_includes/tune/announcement_bottom.rst
  doc/source/cluster/index.rst
  doc/source/data/dataset.rst
  doc/source/ray-core/walkthrough.rst
  doc/source/ray-overview/index.md
  doc/source/rllib/core-concepts.rst
  doc/source/rllib/index.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-dev.rst
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/rllib-sample-collection.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/user-guides.rst
  doc/source/serve/index.rst
  doc/source/train/train.rst
  doc/source/tune/index.rst
Labels: docs

#22995 [Serve] Compatibility bridge between model wrappers and pipeline
  python/ray/serve/model_wrappers.py
  python/ray/serve/pipeline/generate.py
  python/ray/serve/pipeline/ingress.py
  python/ray/serve/pipeline/pipeline_input_node.py
  python/ray/serve/pipeline/tests/test_build.py
  python/ray/serve/tests/test_model_wrappers.py
Labels: @tests-ok

#22802 [docs] re/move old core examples
  doc/BUILD
  doc/README.md
  doc/source/_toc.yml
  doc/source/ray-core/_examples/cython/cython_examples/__init__.py
  doc/source/ray-core/_examples/cython/cython_examples/cython_blas.pyx
  doc/source/ray-core/_examples/cython/cython_examples/cython_simple.pyx
  doc/source/ray-core/_examples/cython/cython_examples/masked_log.pyx
  doc/source/ray-core/_examples/cython/cython_main.py
  doc/source/ray-core/_examples/cython/ray-project/cluster.yaml
  doc/source/ray-core/_examples/cython/ray-project/project.yaml
  doc/source/ray-core/_examples/cython/ray-project/requirements.txt
  doc/source/ray-core/_examples/cython/setup.py
  doc/source/ray-core/_examples/cython/tests/test_cython.py
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  doc/source/ray-core/examples/newsreader/ray-project/cluster.yaml
  doc/source/ray-core/examples/newsreader/ray-project/project.yaml
  doc/source/ray-core/examples/newsreader/ray-project/requirements.txt
  doc/source/ray-core/examples/newsreader/server.py
  doc/source/ray-core/examples/overview.rst
  doc/source/ray-core/examples/placement-group.rst
  doc/source/ray-core/examples/plot_example-a3c.rst
  doc/source/ray-core/examples/plot_example-lm.rst
  doc/source/ray-core/examples/plot_hyperparameter.ipynb
  doc/source/ray-core/examples/plot_lbfgs.rst
  doc/source/ray-core/examples/plot_newsreader.rst
  doc/source/ray-core/examples/plot_parameter_server.ipynb
  doc/source/ray-core/examples/plot_pong_example.ipynb
  doc/source/ray-core/examples/plot_streaming.rst
  doc/source/ray-core/examples/progress_bar.ipynb
  doc/source/ray-core/examples/streaming/articles.txt
  doc/source/ray-core/examples/streaming/ray-project/cluster.yaml
  doc/source/ray-core/examples/streaming/ray-project/project.yaml
  doc/source/ray-core/examples/streaming/ray-project/requirements.txt
  doc/source/ray-core/examples/streaming/streaming.py
  doc/source/ray-core/examples/testing-tips.rst
  doc/source/ray-core/examples/using-ray-with-pytorch-lightning.rst
  doc/source/ray-core/handling-dependencies.rst
  doc/source/ray-core/images/download_zip_url.png
  doc/source/ray-core/images/ray_repo.png
  doc/source/ray-core/placement-group.rst
  doc/source/ray-core/tips-for-first-time.rst
  doc/source/ray-core/using-ray-with-jupyter.rst
  doc/source/ray-core/using-ray-with-pytorch.rst
  doc/source/ray-core/using-ray-with-tensorflow.rst
  doc/source/ray-core/using-ray.rst
  doc/source/ray-design-patterns/index.rst
  doc/source/ray-more-libs/index.rst
  doc/source/train/examples.rst
Labels: docs

#22983 [runtime env] fix import in subprocess
  python/ray/_private/runtime_env/pip.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
Labels: @tests-ok

#22975 [Tuner part1] Add Tuner interface.
  python/ray/ml/result.py
  python/ray/ml/run_config.py
  python/ray/tune/result_grid.py
  python/ray/tune/tune_config.py
  python/ray/tune/tuner.py
Labels: @author-action-required

#23051 [test] add back deleted datasets train test file
  doc/BUILD
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  python/ray/train/trainer.py
Labels: @tests-ok

#22832 [4][resource reporting] Remove ray syncer from gcs_resource_manager
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/ray_syncer.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
Labels: @author-action-required

#22932 Migrating to flat hash map [GCS&util&common]
  BUILD.bazel
  src/mock/ray/gcs/gcs_client/accessor.h
  src/mock/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/common/runtime_env_manager.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/callback.h
  src/ray/gcs/entry_change_notification.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_init_data.cc
  src/ray/gcs/gcs_server/gcs_init_data.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_report_poller.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/stats_handler_impl.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/gcs_server/test/gcs_table_storage_test_base.h
  src/ray/gcs/gcs_server/test/raylet_based_actor_scheduler_test.cc
  src/ray/gcs/redis_context.h
  src/ray/gcs/store_client/in_memory_store_client.cc
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/redis_store_client.h
  src/ray/gcs/store_client/test/store_client_test_base.h
  src/ray/util/container_util.h
  src/ray/util/container_util_test.cc
  src/ray/util/event.cc
  src/ray/util/event.h
  src/ray/util/event_test.cc
  src/ray/util/ordered_set.h
  src/ray/util/sequencer.h
  src/ray/util/util.cc
  src/ray/util/util.h
Labels: @tests-ok

#23092 Don't symlink Serve in setup-dev
  python/ray/setup-dev.py
Labels: @tests-ok

#23079 Correct documentation in ActorPoolStrategy
  python/ray/data/impl/compute.py
Labels: @tests-ok

#22990 [ml] `TorchPredictor` interface
  python/ray/ml/predictor.py
  python/ray/ml/predictors/__init__.py
  python/ray/ml/predictors/integrations/__init__.py
  python/ray/ml/predictors/integrations/torch/__init__.py
  python/ray/ml/predictors/integrations/torch/torch_predictor.py
Labels: @author-action-required

#22762 [GCS] Non-STRICT_PACK PGs should be sorted by resource priority, size
  python/ray/tests/BUILD
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_placement_group_4.py
  python/ray/tests/test_placement_group_5.py
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/gcs_resource_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_resource_scheduler_test.cc
Labels: @author-action-required

#22857 [GCS] Fix the normal task resources at GCS
  python/ray/tests/test_advanced.py
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/local_task_manager.h
Labels: @tests-ok

#23086 Update code owners of gcs and workflow
  .github/CODEOWNERS
Labels: @author-action-required

#23108 [Nightly tests] Improve k8s testing
  benchmarks/distributed/test_many_actors.py
  benchmarks/distributed/test_many_pgs.py
  benchmarks/distributed/test_many_tasks.py
  python/ray/_private/test_utils.py
  release/benchmarks/distributed/test_many_actors.py
  release/benchmarks/distributed/test_many_pgs.py
  release/benchmarks/distributed/test_many_tasks.py
  release/benchmarks/many_nodes.yaml
  release/benchmarks/object_store.yaml
  release/ray_release/job_manager.py
Labels: @author-action-required

#23119 [Jobs] Test job submit with no specified ray address
  dashboard/modules/job/tests/subprocess_driver_scripts/override_env_var.py
  dashboard/modules/job/tests/subprocess_driver_scripts/print_namespace.py
  dashboard/modules/job/tests/subprocess_driver_scripts/print_runtime_env.py
  dashboard/modules/job/tests/test_job_manager.py
Labels: @tests-ok

#22912 [Datasets] Use multithreading to submit DatasetPipeline stages
  python/ray/data/dataset.py
  python/ray/data/impl/pipeline_executor.py
  python/ray/data/impl/progress_bar.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: @author-action-required

#23144 [runtime env] Keep existing `PYTHONPATH` when using runtime env
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/tests/test_runtime_env_working_dir.py
Labels: @tests-ok

#22401 [DOC] Added a full example how to access deployments
  doc/BUILD
  doc/source/serve/_examples/doc_code/create_deployment.py
  doc/source/serve/core-apis.rst
  doc/source/serve/doc_code/BUILD
  doc/source/serve/doc_code/create_deployment.py
  doc/source/serve/doc_code/quick_start.py
  python/ray/serve/BUILD
Labels: @tests-ok

#20752 [Object Spilling] Handle IO worker failures correctly
  python/ray/tests/test_object_spilling.py
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#23124 [Scheduler] separate scheduler code to its own build target
  BUILD.bazel
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/local_task_manager_interface.h
  src/ray/raylet/scheduling/scheduler_resource_reporter.cc
  src/ray/raylet/scheduling/scheduler_resource_reporter.h
  src/ray/raylet/scheduling/scheduler_stats.cc
  src/ray/raylet/scheduling/scheduler_stats.h
Labels: @tests-ok

#22663 [core][docs] Document port/IP binding and slurm concerns
  doc/source/cluster/slurm.rst
Labels: docs

#23120 [Doc] Add missing runtime context namespace doc
  python/ray/runtime_context.py
Labels: @tests-ok

#23143 [ML] `XGBoost`&`LightGBMPredictor` implementation
  python/ray/ml/BUILD
  python/ray/ml/predictors/integrations/lightgbm/lightgbm_predictor.py
  python/ray/ml/predictors/integrations/xgboost/xgboost_predictor.py
  python/ray/ml/tests/test_lightgbm_predictor.py
  python/ray/ml/tests/test_xgboost_predictor.py
Labels: @author-action-required

#22486 Add support for snappy text decompression #22298
  python/ray/data/datasource/binary_datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_dataset_formats.py
  python/requirements/data_processing/requirements_dataset.txt
Labels: @author-action-required

#23145 [Serve] [CI] Split Serve tests into multiple shards
  .buildkite/pipeline.yml
Labels: @author-action-required

#23189 [Remove Redis Pubsub 1/n] Remove `enable_gcs_pubsub()`
  dashboard/modules/actor/tests/test_actor.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/tests/test_dashboard.py
  python/ray/_private/function_manager.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/import_thread.py
  python/ray/_private/log_monitor.py
  python/ray/_private/test_utils.py
  python/ray/tests/test_basic_4.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_gcs_pubsub.py
  python/ray/worker.py
Labels: @tests-ok

#23217 [workflow] Implement workflow continuation unification
  python/ray/workflow/__init__.py
  python/ray/workflow/api.py
  python/ray/workflow/step_executor.py
  python/ray/workflow/tests/test_dag_to_workflow.py
  python/ray/workflow/workflow_context.py
Labels: @author-action-required

#23190 Suggestions of correct inputs to `create_storage` in error message
  python/ray/workflow/storage/__init__.py
  python/ray/workflow/tests/test_basic_workflows.py
Labels: bug, @author-action-required, windows, QS

#22368 [runtime env] Support `.whl` files in `py_modules`
  dashboard/modules/dashboard_sdk.py
  dashboard/modules/job/common.py
  dashboard/modules/job/tests/pip_install_test-0.5-py3-none-any.whl
  dashboard/modules/job/tests/test_backwards_compatibility.py
  dashboard/modules/job/tests/test_common.py
  dashboard/modules/job/tests/test_http_job_server.py
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/tests/pip_install_test-0.5-py3-none-any.whl
  python/ray/tests/test_runtime_env_packaging.py
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_runtime_env_working_dir_2.py
Labels: @tests-ok

#23253 [jobs] Add `entrypoint` field to JobInfo
  dashboard/modules/job/common.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/snapshot_schema.json
  dashboard/modules/snapshot/tests/test_job_submission.py
Labels: @author-action-required

#23187 `map` and `map_unordered` cancel previous tasks before submitting new ones
  python/ray/tests/test_actor_pool.py
  python/ray/util/actor_pool.py
Labels: bug, QS

#23219 [ml/train] `TorchTrainer` implementation
  python/ray/ml/BUILD
  python/ray/ml/constants.py
  python/ray/ml/examples/__init__.py
  python/ray/ml/examples/custom_trainer.py
  python/ray/ml/examples/pytorch/__init__.py
  python/ray/ml/examples/pytorch/torch_fashion_mnist_example.py
  python/ray/ml/examples/pytorch/torch_linear_dataset_example.py
  python/ray/ml/examples/pytorch/torch_linear_example.py
  python/ray/ml/examples/pytorch/tune_torch_linear_dataset_example.py
  python/ray/ml/tests/test_torch_trainer.py
  python/ray/ml/train/integrations/torch/torch_trainer.py
  python/ray/ml/trainer.py
Labels: @author-action-required

#23245 [ML] `XGBoost`&`LightGBMTrainer` implementation
  python/ray/ml/BUILD
  python/ray/ml/examples/lightgbm_example.py
  python/ray/ml/examples/xgboost_example.py
  python/ray/ml/predictors/integrations/lightgbm/lightgbm_predictor.py
  python/ray/ml/predictors/integrations/xgboost/xgboost_predictor.py
  python/ray/ml/tests/test_lightgbm_trainer.py
  python/ray/ml/tests/test_xgboost_predictor.py
  python/ray/ml/tests/test_xgboost_trainer.py
  python/ray/ml/train/gbdt_trainer.py
  python/ray/ml/train/integrations/lightgbm/lightgbm_trainer.py
  python/ray/ml/train/integrations/xgboost/xgboost_trainer.py
Labels: @author-action-required

#23250 [ML/Train] `TensorflowTrainer` implementation
  python/ray/ml/BUILD
  python/ray/ml/examples/tensorflow/__init__.py
  python/ray/ml/examples/tensorflow/tensorflow_linear_dataset_example.py
  python/ray/ml/examples/tensorflow/tensorflow_mnist_example.py
  python/ray/ml/examples/tensorflow/tune_tensorflow_mnist_example.py
  python/ray/ml/tests/test_tensorflow_trainer.py
  python/ray/ml/train/integrations/tensorflow/tensorflow_trainer.py
Labels: @author-action-required

#23172 [Serve] Remove legacy pipeline codebase
  doc/source/serve/package-ref.rst
  doc/source/serve/pipeline.rst
  python/ray/serve/BUILD
  python/ray/serve/examples/doc/snippet_pipeline.py
  python/ray/serve/pipeline/__init__.py
  python/ray/serve/pipeline/common.py
  python/ray/serve/pipeline/conftest.py
  python/ray/serve/pipeline/executor.py
  python/ray/serve/pipeline/node.py
  python/ray/serve/pipeline/step.py
  python/ray/serve/pipeline/test_utils.py
  python/ray/serve/pipeline/tests/test_actor_executor.py
  python/ray/serve/pipeline/tests/test_pipeline.py
  python/ray/serve/pipeline/tests/test_step.py
Labels: @author-action-required

#22749 Add random access support for Datasets (experimental feature)
  doc/source/data/dataset.rst
  doc/source/data/package-ref.rst
  doc/source/data/random-access.rst
  doc/source/data/user-guide.rst
  python/ray/data/dataset.py
  python/ray/data/random_access_dataset.py
  python/ray/data/tests/test_random_access.py
  release/nightly_tests/dataset/dataset_random_access.py
  release/release_tests.yaml
Labels: @tests-ok

#23112 Cleanup nits in code
  python/ray/_private/parameter.py
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/remote_function.py
  python/ray/worker.py
Labels: @author-action-required, do-not-merge

#23167 Collect more usage stats data
  dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: @tests-ok

#23316 [minor] Fix incorrect link to ray core user guide
  doc/source/data/advanced-pipelines.rst
  doc/source/data/images/dataset.svg
  doc/source/data/random-access.rst
  doc/source/index.md
Labels: docs

#23267 [ml] raise error when serializing Predictor
  python/ray/ml/BUILD
  python/ray/ml/predictor.py
  python/ray/ml/tests/test_predictor.py
  python/ray/ml/tests/test_tensorflow_trainer.py
Labels: @author-action-required

#23275 [ml/air] Checkpoints serialization/deserialization support
  python/ray/ml/checkpoint.py
  python/ray/ml/tests/test_checkpoints.py
Labels: @author-action-required

#22889 Initial PR for internal storage API
  python/ray/_private/parameter.py
  python/ray/_private/services.py
  python/ray/internal/storage.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/scripts/scripts.py
  python/ray/tests/BUILD
  python/ray/tests/test_storage.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
Labels: @tests-ok

#23324 [Serve] [Pipeline] Use ServeSchema for deployment prevent config got overridden
  python/ray/serve/BUILD
  python/ray/serve/api.py
  python/ray/serve/pipeline/deployment_function_node.py
  python/ray/serve/pipeline/deployment_node.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/tests/test_pipeline_deployment_config.py
Labels: serve

#23334 [serve] [release] Disable smoke test by default
  release/serve_tests/workloads/autoscaling_multi_deployment.py
  release/serve_tests/workloads/autoscaling_single_deployment.py
  release/serve_tests/workloads/multi_deployment_1k_noop_replica.py
  release/serve_tests/workloads/serve_cluster_fault_tolerance.py
  release/serve_tests/workloads/serve_cluster_fault_tolerance_gcs.py
  release/serve_tests/workloads/serve_micro_benchmark.py
  release/serve_tests/workloads/serve_test_utils.py
  release/serve_tests/workloads/single_deployment_1k_noop_replica.py
Labels: @author-action-required

#23320 [workflow] Ensure that DAGs are dereferenced like ObjectRefs in ray tasks
  python/ray/workflow/common.py
  python/ray/workflow/dag_to_workflow.py
  python/ray/workflow/recovery.py
  python/ray/workflow/step_executor.py
  python/ray/workflow/tests/test_dag_to_workflow.py
Labels: @author-action-required

#23343 [Doc] Add scheduling doc
  doc/source/ray-core/actors.rst
  doc/source/ray-core/actors/scheduling.rst
  doc/source/ray-core/tasks.rst
  doc/source/ray-core/tasks/scheduling.rst
Labels: @author-action-required

#22828 [runtime env] URI reference refactor
  dashboard/consts.py
  dashboard/modules/runtime_env/runtime_env_agent.py
  dashboard/modules/runtime_env/tests/test_runtime_env_agent.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/tests/conftest.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_2.py
  python/ray/tests/test_runtime_env_validation.py
  python/ray/util/client/server/proxier.py
  src/mock/ray/raylet/agent_manager.h
  src/ray/protobuf/runtime_env_agent.proto
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/agent_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/rpc/runtime_env/runtime_env_client.h
Labels: @tests-ok

#23380 Deflake `serve:test_runtime_env` by splitting into two files
  python/ray/serve/BUILD
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_runtime_env.py
  python/ray/serve/tests/test_runtime_env_2.py
Labels: @author-action-required

#23408 [Serve] Test that EveryNode configuration allow scale down
  python/ray/serve/tests/test_standalone2.py
Labels: @author-action-required

#23413 Restore use_gcs_for_bootstrap
  python/ray/_private/gcs_utils.py
Labels: 1.12.0rc1-pick

#23433 [core] Switch long running core tests to use SDK-based test runner
  release/release_tests.yaml
Labels: @author-action-required

#23432 [core/autoscaler] Restore use_gcs_for_bootstrap (#23413)
  python/ray/_private/gcs_utils.py
Labels: release-blocker, P0, 1.12.0rc1-pick

#23344 Add a `get_if_exists` option for simpler creation of named actors
  doc/source/ray-core/actors/named-actors.rst
  doc/source/ray-core/doc_code/get_or_create.py
  python/ray/actor.py
  python/ray/tests/BUILD
  python/ray/tests/test_get_or_create_actor.py
  src/ray/core_worker/transport/direct_task_transport.cc
Labels: core-api-change-approval-required

#23425 [Core] Account for spilled objects when reporting object store memory usage
  python/ray/tests/test_autoscaler_fake_scaledown.py
  src/ray/common/ray_config_def.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @tests-ok

#23452 [RLlib] Pin Gym Everywhere and turn off gpu for recsim tests
  release/long_running_distributed_tests/app_config.yaml
  release/rllib_tests/learning_tests/hard_learning_tests.yaml
Labels: 1.12.0rc1-pick

#23477 [docs] optuna notebook
  doc/source/tune/examples/includes/optuna_define_by_run_example.rst
  doc/source/tune/examples/includes/optuna_example.rst
  doc/source/tune/examples/includes/optuna_multiobjective_example.rst
  doc/source/tune/examples/index.rst
  doc/source/tune/examples/optuna_example.ipynb
  doc/source/tune/key-concepts.rst
  doc/source/tune/tutorials/tune-search-spaces.rst
Labels: docs

#23383 [Python Worker] load actor dependency without importer thread
  python/ray/_private/function_manager.py
  python/ray/_private/import_thread.py
  python/ray/tests/test_basic_4.py
  python/ray/tests/test_failure.py
  python/ray/worker.py
Labels: @tests-ok

#23514 [nightly tests] Cherry-pick nightly test fixes for release branch
  release/release_tests.yaml
Labels: @tests-ok, P0, 1.12.0rc1-pick

#23507 [nighly-test] try out spot instances for chaos test
  release/nightly_tests/dask_on_ray/chaos_dask_on_ray_stress_compute.yaml
  release/release_tests.yaml
Labels: @tests-ok

#23532 Fix Dataset zip for pandas
  python/ray/data/impl/pandas_block.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#23518 [1][core][cleanup] remove enable gcs bootstrap in cpp.
  .buildkite/pipeline.yml
  BUILD.bazel
  cpp/src/ray/runtime/native_ray_runtime.cc
  cpp/src/ray/util/process_helper.cc
  python/ray/includes/ray_config.pxd
  release/ray_release/cluster_manager/cluster_manager.py
  src/ray/common/ray_config_def.h
  src/ray/common/test_util.cc
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/raylet/main.cc
Labels: @author-action-required

#23544 [CI] pin click version to fix broken test.
  python/requirements.txt
  python/setup.py
Labels: do-not-merge

#22449 WINDOWS: enable and fix failures in test_runtime_env_complicated
  .buildkite/pipeline.windows.yml
  ci/travis/ci.sh
  dashboard/modules/reporter/reporter_agent.py
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/_clonevirtualenv.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/conda_utils.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/BUILD
  python/ray/tests/conftest.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/tests/test_runtime_env_conda_and_pip_2.py
  src/ray/common/ray_config_def.h
Labels: @tests-ok

#22854 Refactor scheduler data structures
  BUILD.bazel
  src/ray/common/bundle_spec.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/test/gcs_resource_scheduler_test.cc
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager_test.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/fixed_point.cc
  src/ray/raylet/scheduling/fixed_point.h
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
  src/ray/raylet/scheduling/resource_request_test.cc
  src/ray/raylet/scheduling/scheduler_resource_reporter.cc
  src/ray/raylet/scheduling/scheduling_ids.cc
  src/ray/raylet/scheduling/scheduling_ids.h
  src/ray/raylet/scheduling/scheduling_ids_test.cc
  src/ray/raylet/scheduling/scheduling_policy.cc
  src/ray/raylet/scheduling/scheduling_policy_test.cc
Labels: @author-action-required

#23536 [Doc][Serve] Add minimal docs for model wrappers and http adapters
  doc/requirements-doc.txt
  doc/source/conf.py
  doc/source/ray-air/getting-started.rst
  doc/source/serve/http-servehandle.rst
  python/ray/serve/http_adapters.py
  python/ray/serve/model_wrappers.py
  python/ray/serve/tests/test_http_adapters.py
  python/ray/serve/tests/test_model_wrappers.py
Labels: @author-action-required

#23519 [2][cleanup][gcs] Cleanup GCS client options.
  cpp/src/ray/util/process_helper.cc
  cpp/src/ray/util/process_helper.h
  python/ray/includes/common.pxd
  python/ray/includes/common.pxi
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
Labels: @author-action-required

#23469 [workflow]align the behavior of workflow's options() with remote function's options()
  python/ray/workflow/common.py
  python/ray/workflow/execution.py
  python/ray/workflow/step_function.py
  python/ray/workflow/tests/test_basic_workflows.py
  python/ray/workflow/tests/test_metadata.py
  python/ray/workflow/tests/test_virtual_actor.py
  python/ray/workflow/virtual_actor_class.py
Labels: @external-author-action-required

#23552 Bytecode check to verify imported function correctness in `test_pipeline_driver::test_loading_check`
  python/ray/serve/BUILD
  python/ray/serve/tests/test_pipeline_driver.py
Labels: windows, testing

#23568 [Cherrypick] [Doc][Serve] Add minimal docs for model wrappers and http adapters (#23536)
  doc/requirements-doc.txt
  doc/source/conf.py
  doc/source/ray-air/getting-started.rst
  doc/source/serve/http-servehandle.rst
  python/ray/serve/http_adapters.py
  python/ray/serve/model_wrappers.py
  python/ray/serve/tests/test_http_adapters.py
  python/ray/serve/tests/test_model_wrappers.py
Labels: 1.12.0rc1-pick

#23371 [GCS] [3 / n] Refactor gcs_resource_scheduler to cluster_resource_scheduler
  BUILD.bazel
  src/mock/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_actor_distribution.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_scheduler.cc
  src/ray/gcs/gcs_server/gcs_resource_scheduler.h
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/raylet/placement_group_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_2_test.cc
  src/ray/raylet/scheduling/policy/bundle_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/bundle_scheduling_policy.h
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_context.h
  src/ray/raylet/scheduling/policy/scheduling_options.h
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
  src/ray/raylet/scheduling/policy/scorer.cc
  src/ray/raylet/scheduling/policy/scorer.h
Labels: @author-action-required
