Repository ray-project/ray, pull requests merged in 2022-07, with the labels that each got.

#25896 [Core] Add retry exception allowlist for user-defined filtering of retryable application-level errors.
  .gitignore
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  doc/source/ray-core/doc_code/tasks_fault_tolerance.py
  doc/source/ray-core/tasks/fault-tolerance.rst
  python/ray/_private/ray_option_utils.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/test_failure_4.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @author-action-required, core-api-change-approval-required

#25373 [Release] Use nightly base images for release tests
  release/ray_release/buildkite/step.py
  release/ray_release/template.py
Labels: release-blocker

#26231 Revert "Revert "[AIR][Serve] Rename ModelWrapperDeployment -> PredictorDeployment""
  .isort.cfg
  doc/source/ray-air/doc_code/air_key_concepts.py
  doc/source/ray-air/examples/rl_serving_example.ipynb
  doc/source/ray-air/examples/serving_guide.ipynb
  doc/source/ray-air/examples/tfx_tabular_train_to_serve.ipynb
  doc/source/ray-air/examples/torch_image_example.ipynb
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  doc/source/ray-air/key-concepts.rst
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/user-guides.rst
  doc/source/serve/http-adapters.md
  python/ray/serve/BUILD
  python/ray/serve/__init__.py
  python/ray/serve/air_integrations.py
  python/ray/serve/tests/test_air_integrations.py
Labels: tests-ok

#26045 [docs] Update docs for building from source
  doc/source/ray-contribute/development.rst
Labels: tests-ok

#26029 [Docs] [Serve] Has a consistent landing page style
  doc/source/data/dataset.rst
  doc/source/serve/getting_started.md
  doc/source/serve/index.md
  doc/source/serve/key-concepts.md
  doc/source/serve/ml-models.md
  doc/source/serve/package-ref.md
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/pytorch.md
  doc/source/serve/tutorials/rllib.md
  doc/source/serve/tutorials/sklearn.md
  doc/source/serve/tutorials/tensorflow.md
  doc/source/serve/user-guide.md
Labels: @external-author-action-required

#26314 [runtime env] [Doc] Remove outdated info about "isolated" environments when using `"pip"`
  doc/source/ray-core/handling-dependencies.rst
Labels: tests-ok

#26251 [AIR][GPU Batch Prediction] Add basic support for GPU batch prediction
  .buildkite/pipeline.gpu.large.yml
  python/ray/air/BUILD
  python/ray/train/BUILD
  python/ray/train/batch_predictor.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/tensorflow/tensorflow_predictor.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_tensorflow_predictor.py
  python/ray/train/tests/test_torch_predictor.py
  python/ray/train/torch/torch_predictor.py
Labels: tests-ok, air

#26420 [Core] ensure uniqueness in spilled file name
  python/ray/_private/external_storage.py
  python/ray/tests/test_object_spilling.py
Labels: tests-ok

#25911 [RLlib]: Move OPE to evaluation config
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-offline.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/bc/bc.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/cql/tests/test_cql.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/marwil/tests/test_marwil.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/worker_set.py
  rllib/offline/estimators/direct_method.py
  rllib/offline/estimators/doubly_robust.py
  rllib/offline/estimators/fqe_torch_model.py
  rllib/offline/estimators/importance_sampling.py
  rllib/offline/estimators/off_policy_estimator.py
  rllib/offline/estimators/qreg_torch_model.py
  rllib/offline/estimators/weighted_importance_sampling.py
  rllib/tests/test_io.py
Labels: rllib, rllib-offline-rl

#26196 Object GC for block splitting inside the dataset splitting
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_object_gc.py
Labels: @author-action-required

#26444 [Core] Set c++ terminate handler to print stack trace
  .bazelrc
  BUILD.bazel
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/util/logging.cc
  src/ray/util/logging.h
  src/ray/util/logging_test.cc
Labels: tests-ok

#25296 [docs] Install ray from conda-forge instead of PyPi when using conda
  doc/source/ray-overview/installation.rst
Labels: docs

#26339 Re-organize algorithms so TOC matches README
  doc/source/rllib/rllib-algorithms.rst
  rllib/README.rst
Labels: rllib, docs

#26310 [Serve][Part1] Update the tests to use graph deploy
  python/ray/serve/deployment_function_node.py
  python/ray/serve/deployment_graph_build.py
  python/ray/serve/tests/test_advanced.py
  python/ray/serve/tests/test_autoscaling_metrics.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_constructor_failure.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_2.py
Labels: @author-action-required

#26534 [AIR] Use `cls` in `from_checkpoint`
  python/ray/train/batch_predictor.py
  python/ray/train/huggingface/huggingface_predictor.py
  python/ray/train/lightgbm/lightgbm_predictor.py
  python/ray/train/rl/rl_predictor.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/tensorflow/tensorflow_predictor.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_batchpredictor_runtime.py
  python/ray/train/tests/test_predictor.py
  python/ray/train/torch/torch_predictor.py
  python/ray/train/xgboost/xgboost_predictor.py
Labels: @author-action-required

#26526 [air/data] Concatenator preprocessor
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/preprocessors.rst
  python/ray/data/preprocessors/__init__.py
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/tests/test_preprocessors.py
Labels: @author-action-required

#26451 [AIR] Introduce better scoring API for `BatchPredictor`
  doc/source/ray-air/examples/torch_image_example.ipynb
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  python/ray/experimental/state/api.py
  python/ray/train/batch_predictor.py
  python/ray/train/tests/test_batch_predictor.py
Labels: @author-action-required

#26461 Enable usage stats collection for ray.init iff nightly wheels
  doc/source/cluster/usage-stats.rst
  doc/source/ray-overview/installation.rst
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
  python/ray/_private/worker.py
  python/ray/autoscaler/_private/cli_logger.py
  python/ray/autoscaler/_private/commands.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  python/ray/tests/test_cli_patterns/test_ray_start_localhost.txt
  python/ray/tests/test_cli_patterns/test_ray_up.txt
  python/ray/tests/test_cli_patterns/test_ray_up_docker.txt
  python/ray/tests/test_cli_patterns/test_ray_up_record.txt
  python/ray/tests/test_usage_stats.py
Labels: tests-ok

#26543 [data] Avoid under-parallelization regressions and add better testing for parallelism detection
  python/ray/data/_internal/util.py
  python/ray/data/context.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_auto_parallelism.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: tests-ok

#26574 [Serve] User custom class name for replica class
  python/ray/serve/replica.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_metrics.py
Labels: @author-action-required

#26587 [Datasets] Improve streaming read performance.
  python/ray/data/context.py
  python/ray/data/datasource/file_based_datasource.py
Labels: @author-action-required

#26454 [Datasets] Improve read_xxx experience of HTTP file
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/mock_http_server.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#26507 [Serve][Part2] Migrate the tests to use deployment graph api
  ci/ci.sh
  python/ray/serve/BUILD
  python/ray/serve/tests/fault_tolerance_tests/test_controller_recovery.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/test_gcs_failure.py
  python/ray/serve/tests/test_get_deployment.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_healthcheck.py
  python/ray/serve/tests/test_logging.py
  python/ray/serve/tests/test_logs.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_persistence.py
  python/ray/serve/tests/test_ray_client.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_runtime_env.py
  python/ray/serve/tests/test_runtime_env_2.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/test_standalone2.py
Labels: @author-action-required

#26394 [Datasets] Explicitly define Dataset-like APIs in DatasetPipeline class
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: tests-ok

#26585 [data] Refactor all to all op implementations into a separate file
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/stage_impl.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
Labels: tests-ok

#26397 [Core] Support max cpu allocation per node for placement group scheduling
  cpp/src/ray/runtime/task/native_task_submitter.cc
  python/ray/_raylet.pyx
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/includes/common.pxd
  python/ray/tests/test_placement_group_5.py
  python/ray/util/placement_group.py
  src/ray/common/placement_group.cc
  src/ray/common/placement_group.h
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/scheduling/cluster_resource_scheduler_2_test.cc
  src/ray/raylet/scheduling/policy/bundle_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/bundle_scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_options.h
  src/ray/raylet/scheduling/policy/scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
Labels: @author-action-required

#26363 [Datasets] Refactor `split_at_indices()` to minimize number of split tasks and data movement.
  python/ray/data/_internal/split.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_split.py
  python/ray/data/tests/test_stats.py
Labels: @author-action-required

#26614 [AIR][CUJ] Add GPU bench prediction benchmark
  release/air_tests/air_benchmarks/compute_gpu_1.yaml
  release/air_tests/air_benchmarks/workloads/gpu_batch_prediction.py
  release/release_tests.yaml
Labels: @author-action-required

#26577 [AIR/Docs] Small improvements to Train user guide
  doc/source/ray-air/checkpoints.rst
  doc/source/ray-air/key-concepts.rst
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/preprocessors.rst
  doc/source/train/user_guide.rst
Labels: air

#26631 [AIR] Update Torch benchmarks with documentation
  doc/source/ray-air/benchmarks.rst
  release/air_tests/air_benchmarks/workloads/gpu_batch_prediction.py
  release/air_tests/air_benchmarks/workloads/pytorch_training_e2e.py
Labels: air

#26634 [air] Add _max_cpu_fraction_per_node to ScalingConfig and documentation
  doc/source/data/doc_code/key_concepts.py
  doc/source/data/key-concepts.rst
  doc/source/ray-air/check-ingest.rst
  python/ray/air/config.py
  python/ray/air/tests/test_resource_changing.py
  python/ray/train/base_trainer.py
  python/ray/train/tests/test_base_trainer.py
  python/ray/tune/tests/test_tuner.py
  python/ray/util/placement_group.py
Labels: do-not-merge

#26279 [RLlib]: Fix OPE trainables
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/registry.py
  rllib/evaluation/metrics.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/worker_set.py
  rllib/execution/train_ops.py
  rllib/offline/estimators/__init__.py
  rllib/offline/estimators/direct_method.py
  rllib/offline/estimators/doubly_robust.py
  rllib/offline/estimators/feature_importance.py
  rllib/offline/estimators/fqe_torch_model.py
  rllib/offline/estimators/importance_sampling.py
  rllib/offline/estimators/off_policy_estimator.py
  rllib/offline/estimators/qreg_torch_model.py
  rllib/offline/estimators/tests/test_feature_importance.py
  rllib/offline/estimators/tests/test_ope.py
  rllib/offline/estimators/weighted_importance_sampling.py
  rllib/offline/off_policy_estimator.py
  rllib/utils/policy.py
Labels: rllib, rllib-offline-rl

#26643 [air] Add a warning if no CPUs are reserved for dataset execution
  doc/source/data/key-concepts.rst
  python/ray/air/config.py
  python/ray/train/base_trainer.py
  python/ray/train/tests/test_base_trainer.py
Labels: tests-ok

#26641 [Data][split] use split_at_indices for equal split without locality hints
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
Labels: @author-action-required

#26647 [Air][Data] Don't promote locality_hints for split
  doc/source/data/doc_code/accessing_datasets.py
  doc/source/data/doc_code/quick_start.py
  doc/source/data/examples/nyc_taxi_basic_processing.ipynb
  python/ray/train/_internal/dataset_spec.py
Labels: @author-action-required

#26649 [air] add placement group max CPU to data benchmark
  doc/source/ray-air/benchmarks.rst
  release/air_tests/air_benchmarks/workloads/data_benchmark.py
Labels: tests-ok

#26669 [Datasets] Handle any error code when encountering AWS S3 credential error
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#26159 [State Observability] Use a table format by default
  LICENSE
  dashboard/state_aggregator.py
  python/ray/_private/thirdparty/tabulate/__init__.py
  python/ray/_private/thirdparty/tabulate/tabulate.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_state_api_summary.py
Labels: @author-action-required

#26671 [RLlib]: Fix FQE Policy call
  rllib/offline/estimators/fqe_torch_model.py
  rllib/offline/estimators/tests/test_ope.py
Labels: rllib, rllib-offline-rl

#26661 [air/tuner] Add checkpoint_frequency/checkpoint_at_end arguments to CheckpointConfig
  python/ray/train/BUILD
  python/ray/train/base_trainer.py
  python/ray/train/gbdt_trainer.py
  python/ray/train/lightgbm/lightgbm_trainer.py
  python/ray/train/tests/test_base_trainer.py
  python/ray/train/tests/test_lightgbm_trainer.py
  python/ray/train/tests/test_rl_trainer.py
  python/ray/train/tests/test_torch_trainer.py
  python/ray/train/tests/test_xgboost_trainer.py
  python/ray/train/xgboost/xgboost_trainer.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/integration/lightgbm.py
  python/ray/tune/integration/xgboost.py
  python/ray/tune/tests/test_tuner.py
  python/ray/util/ml_utils/checkpoint_manager.py
Labels: air

#26662 [core] Fix bug in LocalObjectManager reporting for bytes pending spill
  src/ray/common/ray_config_def.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#26600 [air] Accessors for preprocessor in Predictor class
  python/ray/air/checkpoint.py
  python/ray/air/tests/test_checkpoints.py
  python/ray/train/batch_predictor.py
  python/ray/train/huggingface/huggingface_predictor.py
  python/ray/train/lightgbm/lightgbm_predictor.py
  python/ray/train/predictor.py
  python/ray/train/rl/rl_predictor.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/tensorflow/tensorflow_predictor.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_huggingface_predictor.py
  python/ray/train/tests/test_lightgbm_predictor.py
  python/ray/train/tests/test_predictor.py
  python/ray/train/tests/test_sklearn_predictor.py
  python/ray/train/tests/test_tensorflow_predictor.py
  python/ray/train/tests/test_torch_predictor.py
  python/ray/train/tests/test_xgboost_predictor.py
  python/ray/train/torch/torch_predictor.py
  python/ray/train/xgboost/xgboost_predictor.py
Labels: tests-ok

#26659 [runtime env] plugin refactor [5/n]: support priority
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/constants.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/tests/test_placement_group_4.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_plugin.py
Labels: tests-ok

#26498 [Doc][namespaces][C++ worker]add document for c++ worker namespace and specifying namespace while creating/getting named actors
  doc/source/ray-core/namespaces.rst
Labels: docs

#25806 Redo agent-pid -> agent-id changes
  dashboard/agent.py
  src/ray/protobuf/agent_manager.proto
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/agent_manager.h
Labels: @external-author-action-required

#26757 [air] change default strategy to PACK
  python/ray/air/config.py
  release/air_tests/air_benchmarks/workloads/data_benchmark.py
  release/air_tests/air_benchmarks/workloads/tune_torch_benchmark.py
Labels: tests-ok, air

#26792 [docs] Mark pipelined prediction as experimental for now
  doc/source/ray-air/predictors.rst
Labels: tests-ok

#26732 [Serve] [CI] Increase instance size and add debug log for `autoscaling_multi_deployment` release test
  release/release_tests.yaml
  release/serve_tests/compute_tpl_32_cpu_autoscaling.yaml
  release/serve_tests/workloads/autoscaling_multi_deployment.py
  release/serve_tests/workloads/serve_test_utils.py
Labels: tests-ok

#26730 [log_monitor] Always reopen files
  python/ray/_private/ray_constants.py
Labels: @author-action-required

#26777 [AIR] Add framework-specific checkpoints
  doc/source/ray-air/checkpoints.rst
  doc/source/ray-air/doc_code/checkpoint_usage.py
  doc/source/ray-air/doc_code/predictors.py
  doc/source/ray-air/examples/convert_existing_pytorch_code_to_ray_air.ipynb
  doc/source/ray-air/examples/huggingface_text_classification.ipynb
  doc/source/ray-air/examples/pytorch_tabular_batch_prediction.py
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/tf_tabular_batch_prediction.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/torch_image_batch_pretrained.py
  doc/source/ray-air/examples/xgboost_batch_prediction.py
  doc/source/ray-air/examples/xgboost_starter.py
  python/ray/air/checkpoint.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/train/huggingface/__init__.py
  python/ray/train/huggingface/huggingface_checkpoint.py
  python/ray/train/huggingface/utils.py
  python/ray/train/lightgbm/__init__.py
  python/ray/train/lightgbm/lightgbm_checkpoint.py
  python/ray/train/lightgbm/lightgbm_predictor.py
  python/ray/train/lightgbm/lightgbm_trainer.py
  python/ray/train/lightgbm/utils.py
  python/ray/train/rl/__init__.py
  python/ray/train/rl/rl_checkpoint.py
  python/ray/train/rl/rl_predictor.py
  python/ray/train/rl/rl_trainer.py
  python/ray/train/rl/utils.py
  python/ray/train/sklearn/__init__.py
  python/ray/train/sklearn/sklearn_checkpoint.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/sklearn/utils.py
  python/ray/train/tensorflow/__init__.py
  python/ray/train/tensorflow/tensorflow_checkpoint.py
  python/ray/train/tensorflow/tensorflow_predictor.py
  python/ray/train/tensorflow/utils.py
  python/ray/train/tests/test_huggingface_predictor.py
  python/ray/train/tests/test_lightgbm_predictor.py
  python/ray/train/tests/test_lightgbm_trainer.py
  python/ray/train/tests/test_sklearn_predictor.py
  python/ray/train/tests/test_sklearn_trainer.py
  python/ray/train/tests/test_tensorflow_predictor.py
  python/ray/train/tests/test_torch_predictor.py
  python/ray/train/tests/test_xgboost_predictor.py
  python/ray/train/tests/test_xgboost_trainer.py
  python/ray/train/torch/__init__.py
  python/ray/train/torch/torch_checkpoint.py
  python/ray/train/torch/torch_predictor.py
  python/ray/train/torch/utils.py
  python/ray/train/xgboost/__init__.py
  python/ray/train/xgboost/utils.py
  python/ray/train/xgboost/xgboost_checkpoint.py
  python/ray/train/xgboost/xgboost_predictor.py
  python/ray/train/xgboost/xgboost_trainer.py
  release/air_tests/air_benchmarks/workloads/gpu_batch_prediction.py
  release/air_tests/air_benchmarks/workloads/pytorch_training_e2e.py
  release/air_tests/air_benchmarks/workloads/xgboost_benchmark.py
Labels: @author-action-required, air

#26787 [Usage stats] Report total number of running jobs for usage stats purpose.
  dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/node.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: @author-action-required

#26688 [Ray Client] [runtime env] Skip env hook in Ray client server
  python/ray/_private/worker.py
  python/ray/tests/test_client_init.py
  python/ray/tests/test_output.py
  python/ray/util/client/__init__.py
Labels: tests-ok

#26680 [DOC RayAIR] Minor tweaks to the why ray air for clarity
  doc/source/ray-air/getting-started.rst
Labels: air

#26789 [Datasets] Add AWS CLI info into S3 credential error message
  python/ray/data/datasource/file_meta_provider.py
Labels: tests-ok

#26805 [air] Don't request CPUs by default when use_gpu=True
  python/ray/air/config.py
Labels: tests-ok

#26694 [RLLib]: Make IOContext optional for DatasetReader
  rllib/evaluation/worker_set.py
  rllib/offline/dataset_reader.py
  rllib/offline/tests/test_dataset_reader.py
Labels: rllib, rllib-offline-rl

#26682 [Serve] Promote graceful shutdown and health check
  doc/source/serve/deploying-serve.md
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_advanced.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_autoscaling_metrics.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_deployment_graph_autoscaling.py
  python/ray/serve/tests/test_healthcheck.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_schema.py
Labels: @author-action-required

#26689 [Datasets] Add `.iter_torch_batches()` and `.iter_tf_batches()` APIs.
  doc/source/ray-air/doc_code/predictors.py
  doc/source/ray-air/doc_code/tf_starter.py
  python/ray/air/_internal/tensorflow_utils.py
  python/ray/air/_internal/torch_utils.py
  python/ray/air/examples/tf/tensorflow_linear_dataset_example.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_dataset.py
  python/ray/train/_internal/dl_predictor.py
  python/ray/train/tensorflow/tensorflow_predictor.py
  python/ray/train/tests/test_tensorflow_predictor.py
  python/ray/train/tests/test_tensorflow_trainer.py
  python/ray/train/tests/test_torch_predictor.py
  python/ray/train/torch/torch_predictor.py
Labels: @author-action-required

#26804 [Serve] Separate internal API and Public API
  python/ray/serve/_private/__init__.py
  python/ray/serve/_private/api.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/handle.py
Labels: @author-action-required

#26788 [Core] stop retrying after successfully created GCS client
  python/ray/_private/node.py
Labels: tests-ok

#26834 [RFC] [Usage Stats] Expose api to record extra usage tags
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: tests-ok

#26492 [RLlib]: Fix SampleBatch.split_by_episode to use dones if episode id is not available
  rllib/policy/sample_batch.py
  rllib/policy/tests/test_sample_batch.py
Labels: rllib

#26763 [air] large tune/torch benchmark
  release/air_tests/air_benchmarks/compute_gpu_8_g4_12xl.yaml
  release/release_tests.yaml
Labels: air

#26678 [core] ray.init defaults to an existing Ray instance if there is one
  dashboard/modules/dashboard_sdk.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
  doc/source/cluster/cloud.rst
  doc/source/cluster/commands.rst
  doc/source/cluster/kuberay/quickstart.md
  doc/source/cluster/quickstart.rst
  doc/source/data/examples/big_data_ingestion.ipynb
  doc/source/ray-core/starting-ray.rst
  doc/source/ray-core/walkthrough.rst
  doc/source/ray-observability/ray-logging.rst
  doc/source/ray-observability/ray-metrics.rst
  doc/source/ray-observability/ray-tracing.rst
  doc/source/serve/deploying-serve.md
  python/ray/_private/internal_api.py
  python/ray/_private/services.py
  python/ray/_private/utils.py
  python/ray/_private/worker.py
  python/ray/client_builder.py
  python/ray/cluster_utils.py
  python/ray/experimental/state/state_cli.py
  python/ray/scripts/scripts.py
  python/ray/tests/conftest.py
  python/ray/tests/test_advanced_8.py
  python/ray/tests/test_basic_5.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_exit_observability.py
  python/ray/tests/test_get_or_create_actor.py
  python/ray/tests/test_multiprocessing.py
  python/ray/tests/test_output.py
  python/ray/tests/test_ray_init.py
  python/ray/util/client/server/server.py
  python/ray/util/multiprocessing/pool.py
  python/ray/workflow/tests/test_recovery.py
Labels: tests-ok

#26869 [data] set iter_batches default batch_size
  doc/source/data/doc_code/quick_start.py
  python/ray/air/util/check_ingest.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/preprocessors/encoder.py
  python/ray/data/preprocessors/imputer.py
  python/ray/data/preprocessors/vectorizer.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_pipeline.py
  python/ray/data/tests/test_object_gc.py
Labels: tests-ok

#26778 [Data][Split] stable version of split with hints
  python/ray/data/_internal/equalize.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_split.py
Labels: tests-ok

#26116 Ray 2.0 API deprecation
  python/ray/_private/ray_option_utils.py
  python/ray/_private/utils.py
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/runtime_context.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_runtime_context.py
  python/ray/util/actor_group.py
  python/ray/util/actor_pool.py
  python/ray/util/client_connect.py
Labels: core-api-change-approval-required, autoscaler

#26793 [RLlib] Push suggested changes from #25652 docs wording Parametric Models Action Masking
  doc/source/rllib/rllib-models.rst
Labels: rllib, docs

#26868 [Datasets] Use sampling to estimate in-memory data size for Parquet data source
  python/ray/data/context.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#25875 [core] Make ray able to connect to redis without pip redis.
  ci/ci.sh
  python/ray/_private/node.py
  python/ray/_private/ray_constants.py
  python/ray/_private/services.py
  python/ray/scripts/scripts.py
  python/ray/tests/conftest.py
  python/ray/tests/test_ray_init.py
  python/ray/tests/test_tempfile.py
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/redis_client.cc
  src/ray/gcs/redis_client.h
  src/ray/gcs/redis_context.cc
Labels: @author-action-required

#26907 [core] runtime context resource ids getter
  python/ray/_private/worker.py
  python/ray/runtime_context.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_runtime_context.py
Labels: core-api-change-approval-required

#26880 [State Observability] Warn if callsite is disabled when `ray list objects` + raise exception on missing output
  dashboard/state_aggregator.py
  dashboard/tests/test_dashboard.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/tests/test_state_api.py
Labels: @author-action-required

#26785 [Dashboard] Actor Table UI Optimize
  dashboard/client/package.json
  dashboard/client/src/common/RowStyles.tsx
  dashboard/client/src/components/ActorTable.tsx
  dashboard/client/src/pages/actor/index.tsx
  dashboard/client/src/pages/node/NodeRow.tsx
  dashboard/client/src/type/actor.ts
Labels: tests-ok

#26955 [data] set iter_batches default batch_size
  doc/source/data/doc_code/quick_start.py
  python/ray/air/util/check_ingest.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/preprocessors/encoder.py
  python/ray/data/preprocessors/imputer.py
  python/ray/data/preprocessors/vectorizer.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_pipeline.py
  python/ray/data/tests/test_object_gc.py
Labels: tests-ok

#26899 [setup-dev] Add flag to skip symlink certain folders
  doc/source/ray-contribute/development.rst
  python/ray/setup-dev.py
Labels: tests-ok

#26924 [Datasets] Automatically cast tensor columns when building Pandas blocks.
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  python/ray/air/tests/test_data_batch_conversion.py
  python/ray/air/util/data_batch_conversion.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/air/util/tensor_extensions/pandas.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/table_block.py
  python/ray/data/dataset.py
  python/ray/data/datasource/image_folder_datasource.py
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#26753 [Serve] Make the checkpoint and recover only from GCS
  doc/source/serve/deploying-serve.md
  java/serve/src/main/java/io/ray/serve/api/Serve.java
  java/serve/src/main/java/io/ray/serve/api/ServeControllerClient.java
  java/serve/src/main/java/io/ray/serve/controller/ServeController.java
  java/serve/src/test/java/io/ray/serve/BaseServeTest.java
  java/serve/src/test/java/io/ray/serve/DummyServeController.java
  java/serve/src/test/java/io/ray/serve/HttpProxyTest.java
  java/serve/src/test/java/io/ray/serve/ProxyActorTest.java
  java/serve/src/test/java/io/ray/serve/ProxyRouterTest.java
  java/serve/src/test/java/io/ray/serve/RayServeHandleTest.java
  java/serve/src/test/java/io/ray/serve/RayServeReplicaTest.java
  java/serve/src/test/java/io/ray/serve/ReplicaSetTest.java
  java/serve/src/test/java/io/ray/serve/RouterTest.java
  java/serve/src/test/java/io/ray/serve/api/ClientTest.java
  java/serve/src/test/java/io/ray/serve/api/ServeTest.java
  java/serve/src/test/java/io/ray/serve/poll/LongPollClientTest.java
  python/ray/serve/api.py
  python/ray/serve/client.py
  python/ray/serve/constants.py
  python/ray/serve/controller.py
  python/ray/serve/scripts.py
  python/ray/serve/storage/checkpoint_path.py
  python/ray/serve/storage/kv_store.py
  python/ray/serve/storage/ray_gcs_kv_store.py
  python/ray/serve/tests/storage_tests/test_kv_store.py
  python/ray/serve/tests/test_deployment_state.py
  python/ray/serve/tests/test_standalone.py
  release/serve_tests/workloads/serve_test_cluster_utils.py
Labels: @author-action-required

#26973 [train] set split locality_hints
  python/ray/train/_internal/dataset_spec.py
Labels: tests-ok

#26919 [core] Introduce a flag which allows a longer timeout for raylet when GCS restarts.
  .buildkite/pipeline.yml
  BUILD.bazel
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_placement_group_2.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.cc
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.h
  src/ray/gcs/gcs_server/gcs_resource_report_poller.cc
  src/ray/gcs/gcs_server/test/gcs_heartbeat_manager_test.cc
Labels: @author-action-required

#26905 [Core][State Observability] Add tests for getting logs with `node-id`
  python/ray/tests/test_state_api_log.py
Labels: @author-action-required

#26783 [runtime env] plugin refactor[6/n]: java api refactor
  .bazelrc
  java/BUILD.bazel
  java/api/src/main/java/io/ray/api/exception/RuntimeEnvException.java
  java/api/src/main/java/io/ray/api/options/ActorCreationOptions.java
  java/api/src/main/java/io/ray/api/options/CallOptions.java
  java/api/src/main/java/io/ray/api/runtime/RayRuntime.java
  java/api/src/main/java/io/ray/api/runtimeenv/RuntimeEnv.java
  java/api/src/main/java/io/ray/api/runtimeenv/types/RuntimeEnvName.java
  java/dependencies.bzl
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/runtimeenv/RuntimeEnvImpl.java
  java/test/src/main/java/io/ray/test/RuntimeEnvTest.java
Labels: tests-ok

#26911 [Doc] [Job submission] [Dashboard] Add tip for long runtime_env installation and improve error
  dashboard/client/src/pages/dashboard/logical-view/Actor.tsx
  doc/source/cluster/job-submission.rst
Labels: tests-ok

#26980 [AIR] Change `Categorizer` constructor signature
  python/ray/data/preprocessors/encoder.py
  python/ray/data/tests/test_preprocessors.py
Labels: @author-action-required

#26818 [Dashboard] Stop caching logs in memory. Use state observability api to fetch on demand.
  dashboard/client/src/api.ts
  dashboard/client/src/pages/dashboard/node-info/NodeInfo.tsx
  dashboard/client/src/pages/dashboard/node-info/dialogs/logs/Logs.tsx
  dashboard/client/src/pages/dashboard/node-info/features/Logs.tsx
  dashboard/datacenter.py
  dashboard/modules/actor/actor_head.py
  dashboard/modules/actor/tests/test_actor.py
  dashboard/modules/node/node_head.py
  dashboard/modules/node/tests/test_node.py
  dashboard/tests/conftest.py
Labels: @author-action-required

#26977 [AIR] Rename `limit` parameter as `max_categories`
  doc/source/ray-air/examples/tfx_tabular_train_to_serve.ipynb
  python/ray/data/preprocessors/encoder.py
  python/ray/data/tests/test_preprocessors.py
Labels: tests-ok

#26981 [AIR] Remove `CustomStatefulPreprocessor`
  doc/source/ray-air/doc_code/preprocessors.py
  doc/source/ray-air/preprocessors.rst
  python/ray/data/preprocessors/__init__.py
  python/ray/data/preprocessors/custom_stateful.py
  python/ray/data/tests/test_preprocessors.py
Labels: tests-ok

#26847 [log_monitor] Check if files need to be reopened
  python/ray/_private/log_monitor.py
  python/ray/_private/ray_constants.py
  python/ray/tests/test_logging.py
Labels: tests-ok

#26652 [Serve] Fix weird quote escaping in "waiting to be placed" error in serve status.
  python/ray/serve/deployment_state.py
Labels: serve

#26702 [Workflow] Workflow client integration
  doc/source/workflows/advanced.rst
  python/ray/_private/storage.py
  python/ray/workflow/api.py
  python/ray/workflow/exceptions.py
  python/ray/workflow/tests/conftest.py
  python/ray/workflow/tests/test_basic_workflows.py
  python/ray/workflow/tests/test_basic_workflows_2.py
  python/ray/workflow/tests/test_basic_workflows_3.py
  python/ray/workflow/tests/test_basic_workflows_4.py
  python/ray/workflow/tests/test_checkpoint.py
  python/ray/workflow/tests/test_dag_to_workflow.py
  python/ray/workflow/tests/test_events.py
  python/ray/workflow/tests/test_events_with_crash.py
  python/ray/workflow/tests/test_metadata.py
  python/ray/workflow/tests/test_object_deref.py
  python/ray/workflow/tests/test_recovery.py
  python/ray/workflow/tests/test_serialization.py
  python/ray/workflow/tests/test_serialization2.py
  python/ray/workflow/tests/test_storage.py
  python/ray/workflow/tests/test_workflow_indexing.py
  python/ray/workflow/tests/utils.py
  python/ray/workflow/workflow_access.py
  python/ray/workflow/workflow_state_from_dag.py
Labels: @author-action-required

#26754 Adding Ray Clusters (Under Construction) doc section with new structure
  doc/source/_toc.yml
  doc/source/cluster_under_construction/getting-started.rst
  doc/source/cluster_under_construction/key-concepts.rst
  doc/source/cluster_under_construction/ray-cluster.jpg
  doc/source/cluster_under_construction/ray-clusters-on-kubernetes/examples.md
  doc/source/cluster_under_construction/ray-clusters-on-kubernetes/getting-started.md
  doc/source/cluster_under_construction/ray-clusters-on-kubernetes/index.md
  doc/source/cluster_under_construction/ray-clusters-on-kubernetes/references.md
  doc/source/cluster_under_construction/ray-clusters-on-kubernetes/user-guides.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/launching-ray-cluster.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/observe-your-app.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/running-job-via-job-submission.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/scale-your-job-with-autoscaling.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/shutting-down-your-ray-cluster.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-development/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-development/todo.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-production/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-production/todo.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/getting-started.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/references/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/references/job-submission-apis.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/references/ray-cluster-configuration.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/references/ray-job-submission.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/lsf.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/slurm.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/yarn.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/configuring-autoscaling.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/installing-ray.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/large-cluster-best-practices.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/add-your-own-cloud-provider.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/aws.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/azure.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/gcp.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/manual-cluster-setup.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/monitoring-and-observing-ray-cluster.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/multi-tenancy-best-practices.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/index.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-cli.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-rest.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-sdk.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/ray-client.md
  doc/source/cluster_under_construction/ray-clusters-on-vms/user-guides/running-ray-cluster-on-prem.md
  doc/source/cluster_under_construction/we_are_hiring.rst
Labels: docs

#26975 [Datasets] Add `size` parameter to `ImageFolderDatasource`
  doc/source/data/package-ref.rst
  doc/source/ray-air/examples/torch_image_batch_pretrained.py
  python/ray/data/_internal/util.py
  python/ray/data/datasource/image_folder_datasource.py
  python/ray/data/tests/test_dataset_formats.py
  release/air_tests/air_benchmarks/workloads/gpu_batch_prediction.py
  release/air_tests/air_benchmarks/workloads/pytorch_training_e2e.py
Labels: tests-ok

#27036 Moving Ray Clusters restructuring section to be subpage under existing Ray Clusters.
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction.md
  doc/source/cluster/cluster_under_construction/getting-started.rst
  doc/source/cluster/cluster_under_construction/key-concepts.rst
  doc/source/cluster/cluster_under_construction/ray-cluster.jpg
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/getting-started.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/references.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/launching-ray-cluster.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/observe-your-app.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/running-job-via-job-submission.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/scale-your-job-with-autoscaling.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/shutting-down-your-ray-cluster.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-development/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-development/todo.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-production/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-production/todo.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/getting-started.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/job-submission-apis.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/ray-cluster-configuration.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/ray-job-submission.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/lsf.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/slurm.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/yarn.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/configuring-autoscaling.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/installing-ray.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/large-cluster-best-practices.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/add-your-own-cloud-provider.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/aws.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/azure.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/gcp.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/manual-cluster-setup.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/monitoring-and-observing-ray-cluster.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/multi-tenancy-best-practices.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-cli.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-rest.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-sdk.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/ray-client.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-ray-cluster-on-prem.md
  doc/source/cluster/cluster_under_construction/we_are_hiring.rst
Labels: docs

#27034 [Datasets] Use SPREAD scheduling strategy and turn off Parquet sampling by default
  python/ray/data/context.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#26252 Deprecate object_store_memory option
  python/ray/_private/ray_option_utils.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_placement_group_5.py
  python/ray/util/placement_group.py
Labels: core-api-change-approval-required, Ray 2.0

#26704 [Ray Air] followup to the PR (#26493) set the correct gpu id in TorchTrainer (2.0)
  python/ray/train/tests/test_gpu.py
  python/ray/train/tests/test_torch_trainer.py
  python/ray/train/tests/test_tune.py
  python/ray/train/torch/train_loop_utils.py
Labels: air

#26746 [runtime env] Add URI support for plugins
  dashboard/modules/runtime_env/runtime_env_agent.py
  dashboard/modules/runtime_env/tests/test_runtime_env_agent.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/_private/utils.py
  python/ray/_private/worker.py
  python/ray/job_config.py
  python/ray/runtime_env/runtime_env.py
  python/ray/tests/test_runtime_env_plugin.py
Labels: tests-ok

#27065 [air][data] move train_test_split to ray.data.Dataset
  doc/source/ray-air/doc_code/air_key_concepts.py
  doc/source/ray-air/doc_code/checkpoint_usage.py
  doc/source/ray-air/examples/lightgbm_example.ipynb
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/sklearn_example.ipynb
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/xgboost_batch_prediction.py
  doc/source/ray-air/examples/xgboost_example.ipynb
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/preprocessors.rst
  doc/source/train/user_guide.rst
  python/ray/air/BUILD
  python/ray/air/__init__.py
  python/ray/air/examples/pytorch/torch_linear_dataset_example.py
  python/ray/air/tests/test_dataset_utils.py
  python/ray/air/util/datasets.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_split.py
Labels: tests-ok

#26010 [workflow] http_event_provider and accompanied listener
  python/ray/workflow/common.py
  python/ray/workflow/http_event_provider.py
  python/ray/workflow/tests/conftest.py
  python/ray/workflow/tests/test_event_resume_after_crash.py
  python/ray/workflow/tests/test_http_events.py
  python/ray/workflow/tests/test_http_events_2.py
  python/ray/workflow/tests/test_http_events_3.py
  python/ray/workflow/workflow_access.py
Labels: workflow

#27006 [AIR] Add `__repr__` to AIR classes
  python/ray/air/BUILD
  python/ray/air/checkpoint.py
  python/ray/air/config.py
  python/ray/air/constants.py
  python/ray/air/tests/test_checkpoints.py
  python/ray/air/tests/test_configs.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/preprocessors/chain.py
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/preprocessors/encoder.py
  python/ray/data/preprocessors/hasher.py
  python/ray/data/preprocessors/imputer.py
  python/ray/data/preprocessors/normalizer.py
  python/ray/data/preprocessors/scaler.py
  python/ray/data/preprocessors/tokenizer.py
  python/ray/data/preprocessors/transformer.py
  python/ray/data/preprocessors/vectorizer.py
  python/ray/data/tests/test_preprocessors.py
  python/ray/train/BUILD
  python/ray/train/base_trainer.py
  python/ray/train/batch_predictor.py
  python/ray/train/huggingface/huggingface_predictor.py
  python/ray/train/lightgbm/lightgbm_predictor.py
  python/ray/train/rl/rl_predictor.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/tensorflow/tensorflow_predictor.py
  python/ray/train/tests/test_base_trainer.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_checkpoints.py
  python/ray/train/tests/test_huggingface_predictor.py
  python/ray/train/tests/test_lightgbm_predictor.py
  python/ray/train/tests/test_rl_predictor.py
  python/ray/train/tests/test_sklearn_predictor.py
  python/ray/train/tests/test_tensorflow_predictor.py
  python/ray/train/tests/test_torch_predictor.py
  python/ray/train/torch/torch_predictor.py
  python/ray/train/xgboost/xgboost_predictor.py
Labels: v2.0.0-pick

#27060 [air] Add annotation for Tune module.
  ci/lint/check_api_annotations.py
  doc/source/tune/api_docs/env.rst
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/automl/search_policy.py
  python/ray/tune/execution/cluster_info.py
  python/ray/tune/execution/insufficient_resources_manager.py
  python/ray/tune/execution/placement_groups.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/__init__.py
  python/ray/tune/experiment/config_parser.py
  python/ray/tune/experiment/experiment.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/logger/logger.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/registry.py
  python/ray/tune/resources.py
  python/ray/tune/schedulers/__init__.py
  python/ray/tune/schedulers/util.py
  python/ray/tune/search/__init__.py
  python/ray/tune/search/basic_variant.py
  python/ray/tune/search/concurrency_limiter.py
  python/ray/tune/search/repeater.py
  python/ray/tune/search/search_generator.py
  python/ray/tune/search/searcher.py
  python/ray/tune/search/util.py
  python/ray/tune/search/variant_generator.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_experiment.py
  python/ray/tune/tests/test_legacy_import.py
  python/ray/tune/tests/test_progress_reporter.py
  python/ray/tune/tests/test_syncer_callback.py
  python/ray/tune/tests/test_trial_runner_callbacks.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/tests/test_var.py
  python/ray/tune/trainable/function_trainable.py
  python/ray/tune/trainable/session.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/trainable/util.py
  python/ray/tune/tune.py
  python/ray/tune/tuner.py
  python/ray/tune/utils/__init__.py
  python/ray/tune/utils/callback.py
  python/ray/tune/utils/file_transfer.py
  python/ray/tune/utils/log.py
  python/ray/tune/utils/node.py
  python/ray/tune/utils/util.py
  release/golden_notebook_tests/workloads/torch_tune_serve_test.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
  release/tune_tests/scalability_tests/workloads/test_result_throughput_cluster.py
  rllib/train.py
Labels: v2.0.0-pick

#27141 [Ray 2.0][runtime-env] revert 2.0.0rc0 changes to runtimeenv test
  python/ray/tests/test_runtime_env.py
Labels: v2.0.0-pick

#27114 [RLlib] Deflake cartpole crashing tests. (#27097)
  rllib/tuned_examples/pg/cartpole-crashing-pg.yaml
  rllib/tuned_examples/pg/cartpole-crashing-with-remote-envs-pg.yaml
  rllib/tuned_examples/pg/multi-agent-cartpole-crashing-pg.yaml
  rllib/tuned_examples/pg/multi-agent-cartpole-crashing-with-remote-envs-pg.yaml
Labels: v2.0.0-pick

#27146 [air] fix xgboost_benchmark script by passing in args
  release/air_tests/air_benchmarks/workloads/xgboost_benchmark.py
Labels: v2.0.0-pick

#26983 [AIR][Data] Fix nyc_taxi_basic_processing notebook
  doc/source/data/examples/BUILD
  doc/source/data/examples/nyc_taxi_basic_processing.ipynb
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok, air

#27033 [docs] Fix the remaining style violations in docstrings and add lint rule
  ci/lint/format.sh
  dashboard/dashboard.py
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/external_storage.py
  python/ray/_private/metrics_agent.py
  python/ray/_private/parameter.py
  python/ray/_private/ray_logging.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/_private/services.py
  python/ray/_private/test_utils.py
  python/ray/_private/usage/usage_lib.py
  python/ray/_private/worker.py
  python/ray/autoscaler/node_provider.py
  python/ray/runtime_env/runtime_env.py
  python/ray/serve/_private/api.py
  python/ray/serve/_private/autoscaling_metrics.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/_private/router.py
  python/ray/serve/api.py
  python/ray/serve/controller.py
  python/ray/serve/handle.py
  python/ray/tests/test_advanced_2.py
  python/ray/tune/execution/placement_groups.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/util/collective/collective_group/nccl_collective_group.py
  python/ray/util/collective/collective_group/nccl_util.py
  python/ray/util/metrics.py
  rllib/models/torch/misc.py
  rllib/utils/spaces/space_utils.py
Labels: tests-ok

#27155 [rllib/release] Fix rllib connect test with Tuner() API
  release/ml_user_tests/tune_rllib/run_connect_tests.py
  rllib/examples/tune/framework.py
Labels: v2.0.0-pick

#27164 [tune/rllib/release] Load correct metadata file in rllib cloud tests
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
Labels: v2.0.0-pick

#27026 [Serve] Add `host` and `port` options to the Serve config file
  dashboard/modules/serve/serve_agent.py
  doc/source/serve/deploying-serve.md
  doc/source/serve/production.md
  python/ray/serve/schema.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_config_files/basic_graph_http.yaml
Labels: serve, v2.0.0-pick

#27019 [AIR - Datasets] Hide tensor extension from UDFs.
  doc/source/ray-air/examples/convert_existing_pytorch_code_to_ray_air.ipynb
  doc/source/ray-air/examples/torch_image_batch_pretrained.py
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  python/ray/air/_internal/tensorflow_utils.py
  python/ray/air/_internal/torch_utils.py
  python/ray/air/tests/test_data_batch_conversion.py
  python/ray/air/util/data_batch_conversion.py
  python/ray/air/util/tensor_extensions/pandas.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/context.py
  python/ray/data/datasource/image_folder_datasource.py
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_preprocessors.py
  python/ray/train/_internal/dl_predictor.py
  python/ray/train/batch_predictor.py
  python/ray/train/lightgbm/lightgbm_predictor.py
  python/ray/train/predictor.py
  python/ray/train/rl/rl_predictor.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/tests/test_predictor.py
  python/ray/train/xgboost/xgboost_predictor.py
Labels: @author-action-required, v2.0.0-pick

#27149 [Data][Split] Fix split ownership
  python/ray/data/_internal/split.py
  python/ray/data/tests/test_split.py
Labels: v2.0.0-pick

#27194 [Serve] Remove release tests for checkpoint_path
  release/release_tests.yaml
  release/serve_tests/workloads/serve_cluster_fault_tolerance.py
  release/serve_tests/workloads/serve_cluster_fault_tolerance_gcs.py
Labels: release-blocker, v2.0.0-pick

#27206 [Serve] Remove release tests for checkpoint_path (#27194)
  release/release_tests.yaml
  release/serve_tests/workloads/serve_cluster_fault_tolerance.py
  release/serve_tests/workloads/serve_cluster_fault_tolerance_gcs.py
Labels: v2.0.0-pick

#27195 cherry-pick fix split ownership (#27149) to 2.0.0 release branch
  python/ray/data/_internal/split.py
  python/ray/data/tests/test_split.py
Labels: v2.0.0-pick

#27205 Fix node rows not being removed correctly when using filters
  dashboard/client/src/pages/node/index.tsx
Labels: tests-ok, v2.0.0-pick

#27162 [rllib/release/2.0.0] Fix rllib connect test
  release/air_tests/air_benchmarks/workloads/xgboost_benchmark.py
  release/ml_user_tests/tune_rllib/run_connect_tests.py
  rllib/examples/tune/framework.py
Labels: v2.0.0-pick

#27202 Add back job_id to submit_job API to maintain backwards-compatibility
  dashboard/modules/job/common.py
  dashboard/modules/job/job_head.py
  dashboard/modules/job/tests/test_http_job_server.py
Labels: tests-ok, v2.0.0-pick

#27223 [Dashboard] Fix node rows not being removed correctly when using filters
  dashboard/client/src/pages/node/index.tsx
Labels: v2.0.0-pick

#27169 [air] Fix: Gracefully fail in file stat lookup race conditions
  python/ray/air/tests/test_remote_storage.py
  python/ray/tune/utils/file_transfer.py
Labels: v2.0.0-pick

#27180 [tune/release/2.0.0] Fix tune_cloud_aws_durable_upload_rllib_* release tests
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
Labels: v2.0.0-pick

#27226 [tune/release/2.0.0] Gracefully fail in lstat lookup
  python/ray/air/tests/test_remote_storage.py
  python/ray/tune/utils/file_transfer.py
Labels: v2.0.0-pick

#27230 [ci] Move test_storage to large test because of windows timeout. #27212
  python/ray/tests/BUILD
Labels: v2.0.0-pick

#27229 hot fix again ray lightning
  doc/requirements-doc.txt
  doc/source/custom_directives.py
Labels: P0, v2.0.0-pick

#27192 [hotfix] Fix the failure of java test (#27183)
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  python/ray/_private/runtime_env/java_jars.py
Labels: v2.0.0-pick

#27200 [autoscaler] Remove deprecated fields from schema (#27040)
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/autoscaler/_private/util.py
  python/ray/autoscaler/local/development-example.yaml
  python/ray/autoscaler/ray-schema.json
  python/ray/tests/kuberay/test_autoscaling_config.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_autoscaler_yaml.py
  python/ray/tests/test_resource_demand_scheduler.py
  python/ray/tune/examples/tune-default.yaml
Labels: v2.0.0-pick

#27156 [Datasets] Doing partition filtering in reader constructor
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#27225 [hot fix] Cherry pick/hot fix 0728 ray lightning
  doc/requirements-doc.txt
  doc/source/custom_directives.py
Labels: P0, do-not-merge, v2.0.0-pick

#27231 [Workflow] Fix flaky workflow events CI test by extending timeout
  python/ray/workflow/BUILD
Labels: v2.0.0-pick

#27244 Revert "Allow grpcio >= 1.48"
  .buildkite/pipeline.yml
  python/ray/tests/test_runtime_env.py
  python/requirements.txt
  python/setup.py
Labels: unbreak-now

#27163 [tune] Increase volume size for long running pbt failure
  release/long_running_distributed_tests/compute_tpl.yaml
  release/long_running_distributed_tests/workloads/pytorch_pbt_failure.py
Labels: v2.0.0-pick

#27191 Fix the ray version to doc version mapping
  python/ray/_private/utils.py
Labels: release-blocker, v2.0.0-pick

#27228 [air/train/release/2.0.0] Rename BaseWorkerMixin, only log info torch loop for rank 0
  doc/source/ray-air/examples/huggingface_text_classification.ipynb
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  python/ray/air/examples/tf/tensorflow_autoencoder_example.ipynb
  python/ray/train/_internal/worker_group.py
  python/ray/train/horovod/config.py
  python/ray/train/tests/test_backend.py
  python/ray/train/tests/test_trainer.py
  python/ray/train/torch/config.py
  python/ray/train/torch/train_loop_utils.py
Labels: v2.0.0-pick

#27238 Fix logger initialization
  python/ray/_private/worker.py
  python/ray/tests/test_output.py
Labels: tests-ok, v2.0.0-pick

#27264 [pick] Fix logger initialization (#27238)
  python/ray/_private/worker.py
  python/ray/tests/test_output.py
Labels: v2.0.0-pick

#27210 [air 2.0.0] Add annotation for Tune module. (#27060)
  ci/lint/check_api_annotations.py
  doc/source/tune/api_docs/env.rst
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/automl/search_policy.py
  python/ray/tune/execution/cluster_info.py
  python/ray/tune/execution/insufficient_resources_manager.py
  python/ray/tune/execution/placement_groups.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/__init__.py
  python/ray/tune/experiment/config_parser.py
  python/ray/tune/experiment/experiment.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/logger/logger.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/registry.py
  python/ray/tune/resources.py
  python/ray/tune/schedulers/__init__.py
  python/ray/tune/schedulers/util.py
  python/ray/tune/search/__init__.py
  python/ray/tune/search/basic_variant.py
  python/ray/tune/search/concurrency_limiter.py
  python/ray/tune/search/repeater.py
  python/ray/tune/search/search_generator.py
  python/ray/tune/search/searcher.py
  python/ray/tune/search/util.py
  python/ray/tune/search/variant_generator.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_experiment.py
  python/ray/tune/tests/test_legacy_import.py
  python/ray/tune/tests/test_progress_reporter.py
  python/ray/tune/tests/test_syncer_callback.py
  python/ray/tune/tests/test_trial_runner_callbacks.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/tests/test_var.py
  python/ray/tune/trainable/function_trainable.py
  python/ray/tune/trainable/session.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/trainable/util.py
  python/ray/tune/tune.py
  python/ray/tune/tuner.py
  python/ray/tune/utils/__init__.py
  python/ray/tune/utils/callback.py
  python/ray/tune/utils/file_transfer.py
  python/ray/tune/utils/log.py
  python/ray/tune/utils/node.py
  python/ray/tune/utils/util.py
  release/golden_notebook_tests/workloads/torch_tune_serve_test.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
  release/tune_tests/scalability_tests/workloads/test_result_throughput_cluster.py
  rllib/train.py
Labels: v2.0.0-pick

#27260 [Hotfix] Fix the failure of C++ tests (#27249)
  cpp/BUILD.bazel
  cpp/src/ray/test/cluster/cluster_mode_test.cc
  python/ray/_private/runtime_env/context.py
Labels: v2.0.0-pick

#27270 [RLlib] Revert 41c9ef70. (#27243)
  release/rllib_tests/learning_tests/yaml_files/a2c/a2c-breakoutnoframeskip-v4.yaml
  rllib/BUILD
  rllib/algorithms/a2c/a2c.py
  rllib/algorithms/a3c/a3c.py
  rllib/tests/test_gpus.py
  rllib/tuned_examples/a2c/cartpole-a2c-fake-gpus.yaml
Labels: release-blocker, v2.0.0-pick

#27271 [Serve] Disable Serve on macOS Round 2
  .buildkite/pipeline.macos.yml
Labels: tests-ok

#27197 [Workflow] Cleanup workflow docs
  README.rst
  doc/source/workflows/advanced.rst
  doc/source/workflows/comparison.rst
  doc/source/workflows/concepts.rst
  doc/source/workflows/events.rst
  doc/source/workflows/management.rst
  doc/source/workflows/package-ref.rst
Labels: @author-action-required

#27294 [ray2.0][ci] Deflakey gcs_heartbeat_test in windows. (#27275)
  src/ray/gcs/gcs_server/test/gcs_heartbeat_manager_test.cc
Labels: v2.0.0-pick

#27281 bump jobs version after making a backwards-incompatible change
  dashboard/modules/version.py
Labels: v2.0.0-pick

#27280 [ray2.0][ci] Fix test_gcs_ha_e2e.py (#27263)
  ci/ci.sh
Labels: v2.0.0-pick

#25755 [docs] Mention the import ordering style for python
  doc/source/ray-contribute/getting-involved.rst
Labels: stale
