Repository ray-project/ray, pull requests merged in 2022-11, with the labels that each got.

#29888 Revert "[CI] Disable Java log rotation test. (#21394)"
  java/test/src/main/java/io/ray/test/RayJavaLoggingTest.java
Labels: testing

#29794 [AIR] Avoid MLflow database integrity error
  python/ray/air/_internal/mlflow.py
Labels: tests-ok

#29862 [Core] Use inherited `__repr__` in raylet logging
  python/ray/_raylet.pyx
  python/ray/tests/test_logging.py
  python/ray/train/base_trainer.py
  python/ray/train/gbdt_trainer.py
  python/ray/tune/trainable/util.py
Labels: tests-ok

#29838 [State API] Add Node ID + Job ID + Actor ID to list tasks and list actors
  dashboard/state_aggregator.py
  python/ray/experimental/state/common.py
  python/ray/tests/test_state_api.py
  src/mock/ray/core_worker/task_manager.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
Labels: @author-action-required

#29851 [RLlib] Release tests should fail if not learning (instead of showing green).
  release/rllib_tests/learning_tests/run.py
  release/rllib_tests/multi_gpu_learning_tests/run.py
  release/rllib_tests/multi_gpu_with_attention_learning_tests/run.py
  release/rllib_tests/multi_gpu_with_lstm_learning_tests/run.py
  rllib/utils/test_utils.py
Labels: tests-ok

#29901 [core][metric] Add fallback memory and seal memory breakdown
  python/ray/tests/test_object_store_metrics.py
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/object_lifecycle_manager.cc
  src/ray/object_manager/plasma/object_lifecycle_manager.h
  src/ray/object_manager/plasma/plasma_allocator.cc
  src/ray/object_manager/plasma/plasma_allocator.h
  src/ray/object_manager/plasma/stats_collector.cc
  src/ray/object_manager/plasma/stats_collector.h
  src/ray/object_manager/plasma/test/fallback_allocator_test.cc
  src/ray/object_manager/plasma/test/object_lifecycle_manager_test.cc
  src/ray/object_manager/plasma/test/object_store_test.cc
  src/ray/object_manager/plasma/test/stats_collector_test.cc
  src/ray/stats/metric.h
  src/ray/stats/metric_defs.cc
  src/ray/stats/tag_defs.cc
  src/ray/stats/tag_defs.h
  src/ray/util/counter_map.h
  src/ray/util/counter_test.cc
Labels: @author-action-required

#29196 Revert "Revert "[Cluster Events] Add basic job events. (#29164)" (#29…
  dashboard/modules/event/tests/test_event.py
  dashboard/modules/job/job_agent.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
  python/ray/experimental/state/common.py
Labels: @author-action-required

#29973 [RLlib] Only sync policy weights on RolloutWorkers of those policies that were actually updated.
  rllib/algorithms/a2c/a2c.py
  rllib/algorithms/a3c/a3c.py
  rllib/algorithms/algorithm.py
  rllib/algorithms/apex_dqn/apex_dqn.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/dqn/learner_thread.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/simple_q/simple_q.py
  rllib/execution/learner_thread.py
  rllib/execution/multi_gpu_learner_thread.py
Labels: tests-ok

#29462 [Datasets] Replace `iter_tf_batches` with `to_tf` in docs
  doc/source/data/dataset.rst
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/doc_code/tf_starter.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/tfx_tabular_train_to_serve.ipynb
  doc/source/ray-air/trainer.rst
  python/ray/air/session.py
  python/ray/air/tests/test_keras_callback.py
  python/ray/tests/ml_py36_compat/tune_hvd_keras.py
  python/ray/train/examples/tf/tensorflow_regression_example.py
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/train/tests/test_tensorflow_trainer.py
  python/ray/train/train_loop_utils.py
Labels: tests-ok

#29882 [Datasets] Improve `map_batches` error
  python/ray/data/dataset.py
Labels: tests-ok

#29856 [RFC][CLI] Add dashboard link to ray start
  python/ray/scripts/scripts.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  python/ray/tests/test_cli_patterns/test_ray_start_localhost.txt
Labels: @author-action-required

#29974 [RLlib] Enable .py files with AlgorithmConfig objects in them to be run by our `run_regression_test.py` script.
  rllib/BUILD
  rllib/tests/run_regression_tests.py
  rllib/train.py
  rllib/utils/tests/run_memory_leak_tests.py
Labels: tests-ok

#29976 [Test] Migrate the first test to use job submission.
  release/release_tests.yaml
Labels: @author-action-required

#30001 [metrics] Document the semantics of each Prometheus metric we use in the dashboard
  dashboard/modules/metrics/grafana_dashboard_factory.py
  doc/source/ray-observability/images/graphs.png
  doc/source/ray-observability/ray-metrics.rst
Labels: tests-ok, @author-action-required

#29565 Support read/write from/to local node filesystem
  doc/source/data/creating-datasets.rst
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
Labels: tests-ok

#29986 fix dashboard json not being outputted to correct directory
  dashboard/modules/metrics/grafana_dashboard_base.json
  dashboard/modules/metrics/grafana_dashboard_factory.py
  dashboard/modules/metrics/grafana_dashboard_provisioning_template.py
  dashboard/modules/metrics/metrics_head.py
  python/ray/tests/BUILD
  python/ray/tests/test_metrics_head.py
  python/setup.py
Labels: @author-action-required

#29924 [core] Turn pull based health check manager on.
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_reference_counting_2.py
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#28683 [Jobs] Add minimal long-running release test with many jobs
  release/long_running_tests/workloads/long_running_many_jobs.py
  release/release_tests.yaml
Labels: tests-ok

#29993 [Datasets] [Arrow 7+ Support] [2/N] Add support for Arrow 7 by fixing Arrow serialization bug.
  .buildkite/pipeline.ml.yml
  ci/env/install-dependencies.sh
  python/ray/_private/utils.py
  python/ray/air/BUILD
  python/ray/air/tests/test_tensor_extension.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/data/__init__.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/transform_polars.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/_internal/arrow_serialization.py
  python/ray/data/_internal/delegating_block_builder.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/shuffle_and_partition.py
  python/ray/data/_internal/simple_block.py
  python/ray/data/_internal/split.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/grouped_dataset.py
  python/ray/data/random_access_dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_arrow_serialization.py
  python/ray/data/tests/test_batch_mapper.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_parquet.py
  python/ray/util/serialization.py
  python/ray/util/serialization_addons.py
  python/requirements.txt
  python/requirements/data_processing/requirements.txt
  python/setup.py
Labels: @author-action-required

#30019 [RLlib] Update weights restore example now that we have per-policy structure
  rllib/examples/restore_1_of_n_agents_from_checkpoint.py
Labels: tests-ok

#30011 [dashboard] [experimental] Add py-spy profiler support to Node page view
  dashboard/client/src/pages/node/NodeRow.tsx
  dashboard/client/src/pages/node/index.tsx
  dashboard/modules/reporter/profile_manager.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  doc/source/ray-observability/ray-metrics.rst
  python/ray/_private/workers/default_worker.py
  python/ray/_raylet.pyx
  python/ray/exceptions.py
  python/ray/tests/BUILD
  python/ray/tests/test_actor.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_dashboard_profiler.py
  src/ray/protobuf/reporter.proto
Labels: @author-action-required

#30090 [ci] fix mac build
  ci/build/test-wheels.sh
Labels: tests-ok

#30121 [Core][worker-pool][easy] refactor worker start up code to make it easier to understand
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: @author-action-required

#30061 [Core] set worker non recyclable if gpu is envolved by default
  doc/source/ray-core/tasks/using-ray-with-gpus.rst
  python/ray/_private/worker.py
  python/ray/dag/tests/test_function_dag.py
  python/ray/remote_function.py
  python/ray/tests/BUILD
  python/ray/tests/test_advanced_6.py
  python/ray/tests/test_basic.py
Labels: @author-action-required, do-not-merge

#28760 Fix log format for serve
  python/ray/serve/_private/api.py
  python/ray/serve/tests/test_logs.py
Labels: @external-author-action-required

#29476 [Datasets] Add ragged tensor support for `to_tf`
  python/ray/air/_internal/tensorflow_utils.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset_tf.py
Labels: tests-ok

#30053 [RLlib] Deprecate `get_algorithm_class()`.
  rllib/__init__.py
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/registry.py
  rllib/algorithms/tests/test_algorithm_export_checkpoint.py
  rllib/evaluate.py
  rllib/examples/export/cartpole_dqn_export.py
  rllib/examples/inference_and_serving/policy_inference_after_training_with_attention.py
  rllib/examples/inference_and_serving/policy_inference_after_training_with_dt.py
  rllib/examples/rnnsac_stateless_cartpole.py
  rllib/policy/tests/test_export_checkpoint_and_model.py
  rllib/tests/test_algorithm_checkpoint_restore.py
  rllib/tests/test_eager_support.py
  rllib/tests/test_supported_multi_agent.py
  rllib/utils/tests/run_memory_leak_tests.py
Labels: tests-ok

#29999 [Datasets] [Arrow 7+ Support - 3/N] Add support for Arrow 8, 9, 10, and nightly.
  .buildkite/pipeline.ml.yml
  python/ray/_private/storage.py
  python/ray/_private/utils.py
  python/ray/air/tests/test_tensor_extension.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/util.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/tests/test_storage.py
  python/requirements.txt
Labels: tests-ok

#30103 [core] Enable channelz and reflection for gRPC.
  BUILD.bazel
  src/ray/rpc/grpc_server.cc
Labels: @author-action-required

#30159 [RLlib] a few fixes to EnvRunnerV2
  rllib/evaluation/env_runner_v2.py
  rllib/evaluation/tests/test_env_runner_v2.py
Labels: tests-ok

#30021 [Dashboard Reliability] Optimize the node head CPU usage
  dashboard/agent.py
  dashboard/head.py
  dashboard/modules/node/node_consts.py
  dashboard/modules/node/node_head.py
Labels: @author-action-required

#30096 [RLlib] AlgorithmConfig: Replace more occurrences of old config dicts; Make all Algorithms use the non-dict lookup for config properties.
  doc/source/rllib/rllib-algorithms.rst
  rllib/algorithms/a2c/a2c.py
  rllib/algorithms/algorithm.py
  rllib/algorithms/alpha_star/alpha_star.py
  rllib/algorithms/alpha_star/distributed_learners.py
  rllib/algorithms/alpha_zero/alpha_zero.py
  rllib/algorithms/apex_dqn/apex_dqn.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/ars/ars.py
  rllib/algorithms/ars/ars_tf_policy.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/crr/crr.py
  rllib/algorithms/ddppo/ddppo.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/dreamer/dreamer.py
  rllib/algorithms/dt/dt.py
  rllib/algorithms/es/es.py
  rllib/algorithms/es/es_tf_policy.py
  rllib/algorithms/es/es_torch_policy.py
  rllib/algorithms/es/tests/test_es.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/qmix/qmix.py
  rllib/algorithms/simple_q/simple_q.py
  rllib/algorithms/tests/test_algorithm.py
  rllib/algorithms/tests/test_memory_leaks.py
  rllib/env/tests/test_remote_worker_envs.py
  rllib/evaluation/rollout_worker.py
  rllib/examples/custom_experiment.py
  rllib/examples/re3_exploration.py
  rllib/examples/sumo_env_local.py
  rllib/models/tests/test_preprocessors.py
  rllib/offline/estimators/feature_importance.py
  rllib/offline/tests/test_feature_importance.py
  rllib/tests/test_ray_client.py
  rllib/tests/test_supported_spaces.py
  rllib/tests/test_timesteps.py
  rllib/tuned_examples/ddppo/atari-ddppo.yaml
  rllib/tuned_examples/ddppo/pendulum-ddppo.yaml
  rllib/utils/exploration/tests/test_curiosity.py
  rllib/utils/exploration/tests/test_explorations.py
Labels: tests-ok

#29971 [Datasets] Only enable blocks bundling when batch_size is set
  python/ray/data/_internal/compute.py
  python/ray/data/dataset.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/tests/test_dataset.py
Labels: tests-ok

#30183 [RLlib] minor bug fix. Resetted exceptions are saved under env_id key.
  rllib/evaluation/env_runner_v2.py
Labels: tests-ok

#30181 [ml-release] [no_ci] fix xgboost/lightgbm tune release tests.
  python/requirements/ml/requirements_tune.txt
  release/lightgbm_tests/app_config.yaml
  release/xgboost_tests/app_config.yaml
Labels: testing

#30224 [RLlib] Make MA Batch -> SampleBatch offline estimator method a utility method
  rllib/offline/estimators/direct_method.py
  rllib/offline/estimators/doubly_robust.py
  rllib/offline/estimators/off_policy_estimator.py
  rllib/offline/feature_importance.py
  rllib/offline/offline_evaluator.py
  rllib/policy/sample_batch.py
Labels: tests-ok

#30220 [RLlib] Convert to SampleBatch in a couple of places to fit EnvRunnerV2
  rllib/algorithms/dreamer/dreamer.py
  rllib/evaluation/rollout_worker.py
  rllib/offline/estimators/tests/utils.py
Labels: tests-ok

#30172 [Datasets] Convert between block and batch correctly for map_groups
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_dataset.py
Labels: tests-ok

#30024 [RLlib] Fix Recurrent policy inference (e.g. ppo) when connectors are enabled
  rllib/algorithms/ppo/tests/test_ppo.py
  rllib/connectors/tests/test_agent.py
  rllib/evaluation/collectors/agent_collector.py
  rllib/examples/connectors/run_connector_policy.py
  rllib/examples/policy/episode_env_aware_policy.py
  rllib/examples/policy/rock_paper_scissors_dummies.py
  rllib/utils/policy.py
  rllib/utils/test_utils.py
Labels: tests-ok

#30258 [core] disable dashboard profiler tests on mac
  python/ray/tests/test_dashboard_profiler.py
Labels: tests-ok

#28917 [AIR][Predictor] Enable numpy based predictor
  doc/source/ray-air/examples/convert_existing_tf_code_to_ray_air.ipynb
  doc/source/ray-air/examples/torch_image_batch_pretrained.py
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  doc/source/ray-air/predictors.rst
  doc/source/train/doc_code/xgboost_train_predict.py
  python/ray/air/data
  python/ray/air/data_batch_type.py
  python/ray/air/tests/test_data_batch_conversion.py
  python/ray/air/util/data_batch_conversion.py
  python/ray/data/_internal/fast_repartition.py
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/preprocessor.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/random_access_dataset.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_pandas.py
  python/ray/data/tests/test_preprocessors.py
  python/ray/data/tests/test_random_access.py
  python/ray/serve/air_integrations.py
  python/ray/serve/tests/test_air_integrations.py
  python/ray/train/_internal/dl_predictor.py
  python/ray/train/batch_predictor.py
  python/ray/train/predictor.py
  python/ray/train/tests/dummy_preprocessor.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_batchpredictor_runtime.py
  python/ray/train/tests/test_huggingface_checkpoint.py
  python/ray/train/tests/test_huggingface_predictor.py
  python/ray/train/tests/test_lightgbm_predictor.py
  python/ray/train/tests/test_predictor.py
  python/ray/train/tests/test_rl_predictor.py
  python/ray/train/tests/test_sklearn_predictor.py
  python/ray/train/tests/test_tensorflow_predictor.py
  python/ray/train/tests/test_torch_predictor.py
  python/ray/train/tests/test_xgboost_predictor.py
  python/ray/train/torch/torch_predictor.py
Labels: tests-ok

#29608 [Doc] [Jobs] Define driver and unify job definitions
  doc/source/cluster/images/ray-job-diagram.svg
  doc/source/cluster/key-concepts.rst
  doc/source/cluster/running-applications/job-submission/cli.rst
  doc/source/cluster/running-applications/job-submission/index.md
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
  doc/source/cluster/running-applications/job-submission/quickstart.rst
  doc/source/cluster/running-applications/job-submission/sdk.rst
Labels: tests-ok

#30123 [Tune] Add `trial_name_creator` and `trial_dirname_creator` to `TuneConfig`
  python/ray/tune/examples/logging_example.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tune.py
  python/ray/tune/tune_config.py
Labels: tune

#30135 [RLlib] By-pass Evaluation workers when doing OPE
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/bc/bc.py
  rllib/algorithms/ddpg/ddpg.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/marwil/tests/test_marwil.py
  rllib/algorithms/tests/test_algorithm.py
  rllib/offline/dataset_reader.py
  rllib/offline/estimators/direct_method.py
  rllib/offline/estimators/doubly_robust.py
  rllib/offline/estimators/fqe_torch_model.py
  rllib/offline/estimators/importance_sampling.py
  rllib/offline/estimators/tests/test_dm_learning.py
  rllib/offline/estimators/tests/test_dr_learning.py
  rllib/offline/estimators/tests/test_ope.py
  rllib/offline/estimators/tests/test_ope_math.py
  rllib/offline/estimators/weighted_importance_sampling.py
  rllib/offline/feature_importance.py
  rllib/offline/offline_evaluation_utils.py
  rllib/offline/offline_evaluator.py
  rllib/offline/resource.py
  rllib/offline/tests/test_feature_importance.py
Labels: tests-ok

#29285 [all_tests][python] Remove calling of get_event_loop from python version >= 3.10
  ci/ci.sh
  dashboard/agent.py
  dashboard/dashboard.py
  dashboard/http_server_agent.py
  dashboard/http_server_head.py
  dashboard/modules/actor/actor_head.py
  dashboard/modules/event/event_utils.py
  dashboard/modules/job/cli.py
  dashboard/modules/job/tests/test_job_agent.py
  dashboard/modules/runtime_env/runtime_env_agent.py
  dashboard/modules/usage_stats/usage_stats_head.py
  dashboard/tests/test_dashboard.py
  doc/source/ray-core/actors/async_api.rst
  doc/source/ray-core/doc_code/actor-http-server.py
  doc/source/serve/doc_code/direct_ingress.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/test_utils.py
  python/ray/_private/utils.py
  python/ray/remote_function.py
  python/ray/serve/_private/http_proxy.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/batching.py
  python/ray/serve/benchmarks/handle.py
  python/ray/serve/benchmarks/microbenchmark.py
  python/ray/serve/controller.py
  python/ray/serve/drivers.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/test_router.py
  python/ray/tests/BUILD
  python/ray/tests/test_async.py
  python/ray/tests/test_client_reconnect.py
  python/ray/tests/test_concurrency_group.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_utils.py
  python/ray/workflow/common.py
  release/serve_tests/workloads/deployment_graph_long_chain.py
  release/serve_tests/workloads/deployment_graph_wide_ensemble.py
  release/serve_tests/workloads/serve_handle_long_chain.py
  release/serve_tests/workloads/serve_handle_wide_ensemble.py
  release/serve_tests/workloads/serve_micro_benchmark.py
  release/serve_tests/workloads/serve_protocol_benchmark.py
  release/serve_tests/workloads/serve_resnet_benchmark.py
Labels: @author-action-required

#30346 [Core] Close GCS channel after health check to fix one memory leak in `dashboard.py`
  python/ray/_private/gcs_utils.py
Labels: tests-ok

#29594 [core] Reduce log spam in task_manager when nodes newly fail
  src/ray/core_worker/transport/direct_task_transport.cc
Labels: @author-action-required

#30386 Fix various issues with test_rollout_worker.py when connector is enabled
  rllib/connectors/agent/clip_reward.py
  rllib/evaluation/tests/test_rollout_worker.py
Labels: tests-ok

#30317 Limit max # of cluster events cached
  dashboard/client/src/components/EventTable.tsx
  dashboard/modules/event/event_head.py
  dashboard/modules/event/tests/test_event.py
  dashboard/modules/job/job_manager.py
Labels: @author-action-required

#30093 [Datasets] Clean up logic of read metadata with dynamic block splitting
  python/ray/data/_internal/lazy_block_list.py
  python/ray/data/_internal/stats.py
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_dynamic_block_split.py
Labels: tests-ok

#30428 [Datasets] Marking ray-data-bulk-ingest-out-of-core-benchmark as unstable for now.
  release/release_tests.yaml
Labels: datasets

#30355 [Tune] [Train] Only convert a `BaseTrainer` to `Trainable` once in the Tuner
  python/ray/tune/impl/tuner_internal.py
Labels: tune, train

#30363 [Tune] Make `Tuner.restore` work with relative experiment paths
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tests/test_tuner_restore.py
Labels: tune

#30344 [Jobs] [CI] Add multinode and GPU release test for Jobs
  release/jobs_tests/app_config.yaml
  release/jobs_tests/compute_tpl_gpu_node.yaml
  release/jobs_tests/compute_tpl_gpu_worker.yaml
  release/jobs_tests/workloads/jobs_check_cuda_available.py
  release/jobs_tests/workloads/jobs_remote_multi_node.py
  release/jobs_tests/workloads/jobs_specify_num_gpus.py
  release/release_tests.yaml
Labels: tests-ok

#30441 [Doc] [Jobs] Document `JobDetails`, `JobType` and `DriverInfo`
  dashboard/modules/job/common.py
  dashboard/modules/job/pydantic_models.py
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
  python/ray/job_submission/__init__.py
Labels: tests-ok

#30482 [CI] [runtime env] Skip flaky `test_no_spurious_worker_startup` on windows
  python/ray/tests/test_runtime_env.py
Labels: tests-ok

#30398 [RLlib] Don't test SimpleServing with connectors
  rllib/tests/test_nested_observation_spaces.py
Labels: tests-ok

#30496 [core] Set OMP_NUM_THREADS to `num_cpus` required by task/actors by default
  doc/source/ray-core/configure.rst
  doc/source/serve/scaling-and-resource-allocation.md
  python/ray/__init__.py
  python/ray/_private/utils.py
  python/ray/_raylet.pyx
  python/ray/tests/test_basic.py
Labels: tests-ok, Ray 2.2

#30312 [core] print top-n memory usage when task OOMs, update docs
  BUILD.bazel
  doc/source/ray-contribute/stability.rst
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  src/ray/common/memory_monitor.cc
  src/ray/common/memory_monitor.h
  src/ray/common/test/memory_monitor_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_killing_policy.cc
  src/ray/raylet/worker_killing_policy.h
  src/ray/raylet/worker_killing_policy_test.cc
Labels: @author-action-required

#30509 [RLlib] To improve performance, do not wait for sync weight calls by default.
  rllib/algorithms/a3c/a3c.py
  rllib/evaluation/worker_set.py
Labels: tests-ok

#30469 [Dashboard] Remove opencensus from agent proxy export
  dashboard/modules/reporter/reporter_agent.py
  python/ray/_private/metrics_agent.py
  python/ray/tests/test_metrics_agent_2.py
Labels: @author-action-required

#24875 [core][pg] Fix pg bundles can't reschedule bug when the two nodes both dead
  python/ray/tests/BUILD
  python/ray/tests/test_placement_group_failover.py
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
Labels: release-blocker, P0, Ray 2.2

#30272 [Doc] [Jobs] Fix gaps in documentation for first-time users
  dashboard/modules/job/cli.py
  dashboard/modules/job/sdk.py
  doc/source/cluster/running-applications/job-submission/cli.rst
  doc/source/cluster/running-applications/job-submission/index.md
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
  doc/source/cluster/running-applications/job-submission/quickstart.rst
  doc/source/cluster/running-applications/job-submission/rest.rst
  doc/source/cluster/running-applications/job-submission/sdk.rst
  doc/source/ray-core/doc_code/runtime_env_example.py
  doc/source/ray-core/handling-dependencies.rst
  doc/source/ray-observability/ray-logging.rst
Labels: tests-ok, Ray 2.2

#30390 [Datasets] Change `read_tfrecords` output from Pandas to Arrow format
  doc/source/data/dataset-internals.rst
  python/ray/data/datasource/tfrecords_datasource.py
  python/ray/data/tests/test_dataset_tfrecords.py
Labels: tests-ok

#30361 [RLlib] Fix A2C release test crash (rollout_fragment_length vs train_batch_size).
  release/rllib_tests/learning_tests/yaml_files/a2c/a2c-breakoutnoframeskip-v4.yaml
  rllib/algorithms/a2c/a2c.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/pg/pg.py
  rllib/tuned_examples/a2c/atari-a2c.yaml
  rllib/tuned_examples/a2c/cartpole-a2c-fake-gpus.yaml
  rllib/tuned_examples/a2c/cartpole-a2c.yaml
  rllib/tuned_examples/a2c/cartpole_a2c.py
Labels: tests-ok

#30450 [Datasets] Marking ray-data-bulk-ingest-file-size-benchmark as unstable for now.
  release/release_tests.yaml
Labels: datasets

#30472 [core] telemetry for oom occurences
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/test/gcs_worker_manager_test.cc
Labels: tests-ok

#30526 [RLlib; RELEASE BLOCKER] Fix Policy server/client (currently broken and not caught by tests!)
  rllib/env/policy_client.py
  rllib/evaluation/rollout_worker.py
Labels: tests-ok, release-blocker, P0

#29350 Add telemetry data about prometheus and grafana
  dashboard/modules/metrics/metrics_head.py
  dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: @author-action-required

#30417 [Jobs] [Doc] Add Jobs openapi spec and REST API documentation
  dashboard/modules/job/job_head.py
  doc/requirements-doc.txt
  doc/source/cluster/running-applications/job-submission/openapi.yml
  doc/source/cluster/running-applications/job-submission/rest.rst
  doc/source/conf.py
Labels: Ray 2.2

#30419 [all_tests] Remove calling of get_event_loop from python version >= 3.10
  ci/ci.sh
  dashboard/agent.py
  dashboard/dashboard.py
  dashboard/http_server_agent.py
  dashboard/http_server_head.py
  dashboard/modules/actor/actor_head.py
  dashboard/modules/event/event_utils.py
  dashboard/modules/job/cli.py
  dashboard/modules/job/tests/test_job_agent.py
  dashboard/modules/runtime_env/runtime_env_agent.py
  dashboard/modules/usage_stats/usage_stats_head.py
  dashboard/tests/test_dashboard.py
  doc/source/ray-core/actors/async_api.rst
  doc/source/ray-core/doc_code/actor-http-server.py
  doc/source/serve/doc_code/direct_ingress.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/test_utils.py
  python/ray/_private/utils.py
  python/ray/remote_function.py
  python/ray/serve/_private/http_proxy.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/batching.py
  python/ray/serve/benchmarks/handle.py
  python/ray/serve/benchmarks/microbenchmark.py
  python/ray/serve/controller.py
  python/ray/serve/drivers.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/test_router.py
  python/ray/tests/BUILD
  python/ray/tests/test_async.py
  python/ray/tests/test_client_reconnect.py
  python/ray/tests/test_concurrency_group.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_utils.py
  python/ray/workflow/common.py
  release/serve_tests/workloads/deployment_graph_long_chain.py
  release/serve_tests/workloads/deployment_graph_wide_ensemble.py
  release/serve_tests/workloads/serve_handle_long_chain.py
  release/serve_tests/workloads/serve_handle_wide_ensemble.py
  release/serve_tests/workloads/serve_micro_benchmark.py
  release/serve_tests/workloads/serve_protocol_benchmark.py
  release/serve_tests/workloads/serve_resnet_benchmark.py
Labels: tests-ok

#30538 [core] Change OMP_NUM_THREADS by default for plot_pong_example
  doc/source/ray-core/examples/plot_pong_example.ipynb
Labels: tests-ok

#30532 [Datasets] Revert to manual buffer copying custom Arrow serializer.
  python/ray/data/_internal/arrow_serialization.py
  python/ray/data/tests/test_arrow_serialization.py
Labels: Ray 2.2

#30522 [Test] Change the workload for agent_stress_test
  release/dashboard/atari.yaml
  release/dashboard/mem_check.py
  release/dashboard/workload.py
Labels: release-blocker, Ray 2.2

#30150 [Core] Disabling object store from appearing in worker coredumps
  src/ray/common/ray_config_def.h
  src/ray/object_manager/plasma/shared_memory.cc
  src/ray/object_manager/plasma/shared_memory.h
Labels: core

#30563 [core] Fix a corner case where GCS will crash when actor is deleted
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
Labels: release-blocker

#30556 [core] Fix test_snapshot with explicit wait for conditions
  dashboard/modules/snapshot/tests/test_snapshot.py
Labels: tests-ok, v2.2.0-pick

#30595 [core] Fix a corner case where GCS will crash when actor is deleted (#30563)
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
Labels: release-blocker, Ray 2.2, v2.2.0-pick

#30553 [core] OOM killer: adjust defaults
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  release/nightly_tests/stress_tests/stress_tests_single_node_oom_app_config.yaml
  release/nightly_tests/stress_tests/test_parallel_tasks_memory_pressure.py
  release/ray_release/cluster_manager/cluster_manager.py
  release/release_tests.yaml
  src/ray/common/ray_config_def.h
Labels: tests-ok, Ray 2.2

#30602 [RLlib] Fix EnvRunnerV2 creation of fake observations
  rllib/evaluation/env_runner_v2.py
  rllib/utils/spaces/space_utils.py
Labels: tests-ok

#30592 [Core] disable obj store pages in raylet coredump
  src/ray/common/ray_config_def.h
  src/ray/object_manager/plasma/dlmalloc.cc
  src/ray/object_manager/plasma/shared_memory.cc
Labels: core

#30558 [Core][Data] fix circular import for ray.data in AsyncActors
  python/ray/_private/arrow_serialization.py
  python/ray/data/tests/test_arrow_serialization.py
  python/ray/util/serialization_addons.py
Labels: v2.2.0-pick

#30624 [Core] fix circular import for ray.data in AsyncActors for 2.2.0 branch
  python/ray/_private/arrow_serialization.py
  python/ray/data/tests/test_arrow_serialization.py
  python/ray/util/serialization_addons.py
Labels: v2.2.0-pick

#30562 [RLlib] Fix crashing remote envs example
  rllib/evaluation/env_runner_v2.py
Labels: tests-ok

#30590 [RLlib] [Connectors] Add Logic For Handling Agent Index In Policy Inference Connectors
  rllib/connectors/agent/view_requirement.py
  rllib/evaluation/env_runner_v2.py
Labels: tests-ok

#30349 [Core][WorkerPool Reuse 1/n] Consolidate worker reuse code path
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: tests-ok

#30238 [Doc][Task 1/n] move task python code into single testable file
  doc/source/ray-core/doc_code/tasks.py
  doc/source/ray-core/doc_code/tasks_and_objects.py
  doc/source/ray-core/doc_code/tasks_multiple_returns.py
  doc/source/ray-core/tasks.rst
Labels: @author-action-required

#30243 [Doc][Task 3/n] move nested-task python code into single testable file
  doc/source/ray-core/doc_code/nested-tasks.py
  doc/source/ray-core/tasks/nested-tasks.rst
Labels: @author-action-required

#30231 [core][state][telemetry] Add telemetry for top level state API usage from python.
  dashboard/modules/state/state_head.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_state_api.py
Labels: Ray 2.2, v2.2.0-pick

#30598 [AIR] Fix reserved CPU warning if no CPUs are used
  python/ray/train/BUILD
  python/ray/train/tests/test_base_trainer.py
  python/ray/tune/impl/tuner_internal.py
Labels: v2.2.0-pick

#30658 [RLlib; Release 2.2 BLOCKER] Algo train should return config dict not algo config obj
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dt/dt.py
  rllib/utils/test_utils.py
Labels: release-blocker, P0

#30693 Revert "Add c++ usage stats client"
  BUILD.bazel
  python/ray/_private/usage/usage_constants.py
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/test/usage_stats_client_test.cc
  src/ray/gcs/gcs_client/usage_stats_client.cc
  src/ray/gcs/gcs_client/usage_stats_client.h
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/test/gcs_worker_manager_test.cc
Labels: do-not-merge

#30667 [core] Upgrade absl
  bazel/ray_deps_setup.bzl
Labels: @author-action-required

#30484 [Core] Update generator documentation of not supporting Ray client
  doc/source/ray-core/tasks/generators.rst
Labels: tests-ok

#30636 [core][dashboard] Change py-spy native default to false
  dashboard/client/src/components/ActorTable.tsx
  dashboard/client/src/pages/node/NodeRow.tsx
  dashboard/modules/reporter/profile_manager.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  python/ray/tests/test_dashboard_profiler.py
  release/dashboard/workload.py
  src/ray/protobuf/reporter.proto
Labels: tests-ok, Ray 2.2, v2.2.0-pick

#30698 [AIR] Fix reserved CPU warning if no CPUs are used (#30598)
  python/ray/train/BUILD
  python/ray/train/tests/test_base_trainer.py
  python/ray/tune/impl/tuner_internal.py
Labels: v2.2.0-pick

#30712 [pick] [core][dashboard] Change py-spy native default to false (#30636)
  dashboard/client/src/components/ActorTable.tsx
  dashboard/client/src/pages/node/NodeRow.tsx
  dashboard/modules/reporter/profile_manager.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  python/ray/tests/test_dashboard_profiler.py
  release/dashboard/workload.py
  src/ray/protobuf/reporter.proto
Labels: v2.2.0-pick

#30480 [Datasets] Add documentation for dynamic block splitting
  doc/source/data/dataset-internals.rst
Labels: tests-ok, v2.2.0-pick

#30696 [Datasets] Handle all Ray errors in task compute strategy.
  python/ray/data/_internal/compute.py
Labels: v2.2.0-pick

#30727 [cherry-pick][doc] Add a session in ray core doc for tips to run large ray cluster
  doc/source/ray-core/miscellaneous.rst
  src/ray/common/ray_config_def.h
Labels: release-blocker, v2.2.0-pick

#30500 Revert "Revert "[Doc] [Jobs] Document `JobDetails`, `JobType` and `DriverInfo`""
  dashboard/agent.py
  dashboard/modules/job/common.py
  dashboard/modules/job/pydantic_models.py
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/job/tests/test_job_agent.py
  dashboard/utils.py
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
  doc/source/cluster/running-applications/job-submission/quickstart.rst
  doc/source/cluster/running-applications/job-submission/sdk.rst
  python/ray/_private/runtime_env/conda.py
  python/ray/job_submission/__init__.py
Labels: tests-ok

#30721 [Datasets] Unrevert "Fix ndarray representation of single-element ragged tensor slices. (#30514)"
  python/ray/air/tests/test_tensor_extension.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/air/util/tensor_extensions/pandas.py
  python/ray/air/util/tensor_extensions/utils.py
  python/ray/data/tests/test_transform_pyarrow.py
Labels: release-blocker, v2.2.0-pick

#30724 [Core] RetryObjectInPlasmaErrors tries to fetch all objects, not just ready ones.
  src/ray/core_worker/core_worker.cc
Labels: core, Ray 2.2

#30476 [Core] Defer SIGINT interrupt during task argument deserialization.
  python/ray/_private/utils.py
  python/ray/_raylet.pyx
  python/ray/tests/test_cancel.py
Labels: release-blocker, @author-action-required, v2.2.0-pick

#30746 [RLlib] Fix RLlib CLI: e.g. `rllib example run cartpole-ppo` fails. (#30664)
  doc/source/ray-overview/doc_test/ray_rllib.py
  doc/source/rllib/core-concepts.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-dev.rst
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/rllib-sample-collection.rst
  doc/source/rllib/rllib-training.rst
  rllib/BUILD
  rllib/common.py
  rllib/scripts.py
  rllib/tests/test_rllib_train_and_evaluate.py
  rllib/train.py
  rllib/tuned_examples/simple_q/cartpole-simpleq-test.yaml
Labels: release-blocker, v2.2.0-pick

#30756 [Cherry-pick] [Core] RetryObjectInPlasmaErrors tries to fetch all objects, not just ready ones.
  src/ray/core_worker/core_worker.cc
Labels: core, Ray 2.2, v2.2.0-pick

#30752 [Cherry-pick] [Datasets] Fix ndarray representation of single-element ragged tensor slices. (#30721)
  python/ray/air/tests/test_tensor_extension.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/air/util/tensor_extensions/pandas.py
  python/ray/air/util/tensor_extensions/utils.py
  python/ray/data/tests/test_transform_pyarrow.py
Labels: release-blocker, v2.2.0-pick

#30753 [Jobs] [Doc] Add doc sidebar that was inadvertently removed
  doc/source/cluster/running-applications/job-submission/index.md
Labels: v2.2.0-pick

#30758 [docs][2.2][Core] Update generator documentation of not supporting Ray client
  doc/source/ray-core/tasks/generators.rst
Labels: release-blocker, v2.2.0-pick

#30757 [docs][2.2][Datasets] Add documentation for dynamic block splitting
  doc/source/data/dataset-internals.rst
Labels: release-blocker, v2.2.0-pick

#30751 Better UI behavior when prometheus is not running
  dashboard/client/src/pages/job/JobDetail.tsx
  dashboard/client/src/pages/job/JobRow.tsx
  dashboard/client/src/pages/job/TaskProgressBar.tsx
Labels: v2.2.0-pick

#30682 [core] OOM killer: 2.2 readiness
  doc/source/ray-core/doc_code/ray_oom_prevention.py
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  python/ray/_raylet.pyx
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/tests/test_memory_deadlock.py
  python/ray/tests/test_memory_pressure.py
  release/nightly_tests/shuffle/shuffle_app_config_oom_disabled.yaml
  release/nightly_tests/stress_tests/stress_tests_single_node_oom_app_config.yaml
  release/nightly_tests/stress_tests/test_parallel_tasks_memory_pressure.py
  release/ray_release/cluster_manager/cluster_manager.py
  release/release_tests.yaml
  src/ray/common/memory_monitor.cc
  src/ray/common/ray_config_def.h
  src/ray/raylet/node_manager.cc
Labels: tests-ok

#30750 [Tune] Allow overwriting a trainable on Tuner restore (#30351)
  python/ray/train/tests/test_tune.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/trainable/util.py
  python/ray/tune/tuner.py
Labels: release-blocker, v2.2.0-pick

#30776 [core] OOM killer: 2.2 readiness (#30682)
  doc/source/ray-core/doc_code/ray_oom_prevention.py
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  python/ray/_raylet.pyx
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/tests/test_memory_deadlock.py
  python/ray/tests/test_memory_pressure.py
  release/nightly_tests/shuffle/shuffle_app_config_oom_disabled.yaml
  release/nightly_tests/stress_tests/stress_tests_single_node_oom_app_config.yaml
  release/nightly_tests/stress_tests/test_parallel_tasks_memory_pressure.py
  release/ray_release/cluster_manager/cluster_manager.py
  release/release_tests.yaml
  src/ray/common/memory_monitor.cc
  src/ray/common/ray_config_def.h
  src/ray/raylet/node_manager.cc
Labels: release-blocker, v2.2.0-pick

#30691 [core][state][telemetry] Add telemetry for top level state API usage …
  dashboard/modules/state/state_head.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_state_api.py
Labels: release-blocker, v2.2.0-pick

#30769 [Stats][Segfault] ensure we initialize stats before using it/spawning other threads
  src/ray/core_worker/core_worker_process.cc
Labels: @author-action-required

#30768 [Doc] [Jobs] Fix regression in jobs sidebar
  doc/source/cluster/running-applications/job-submission/index.md
Labels: release-blocker, v2.2.0-pick

#30797 [runtime_env] [CI] Use `emoji` instead of `requests` to speed up pip install in `test_runtime_env_complicated.py`
  python/ray/tests/test_runtime_env_complicated.py
Labels: tests-ok, v2.2.0-pick

#30716 [state][doc] Improve ray log doc
  doc/source/ray-observability/state/state-api.rst
  python/ray/experimental/state/state_cli.py
Labels: release-blocker, Ray 2.2, v2.2.0-pick

#30806 Revert "Revert "[Doc] [Jobs] Document `JobDetails`, `JobType` and `DriverInfo`"" (#30500)
  dashboard/agent.py
  dashboard/modules/job/common.py
  dashboard/modules/job/pydantic_models.py
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/job/tests/test_job_agent.py
  dashboard/utils.py
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
  doc/source/cluster/running-applications/job-submission/quickstart.rst
  doc/source/cluster/running-applications/job-submission/sdk.rst
  python/ray/_private/runtime_env/conda.py
  python/ray/job_submission/__init__.py
Labels: release-blocker, v2.2.0-pick

#30801 [runtime env] [CI] Use `emoji` instead of `requests` to fix CI timeout(#30797)
  python/ray/tests/test_runtime_env_complicated.py
Labels: release-blocker, v2.2.0-pick
