Repository ray-project/ray, pull requests merged in 2022-02, with the labels that each got.

#22017 [Datasets] Fix spread resource prefix tasks with no CPU requested.
  python/ray/data/impl/util.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#21590 [Serve] Remove shard_key, http_method, and http_headers
  python/ray/serve/handle.py
  python/ray/serve/http_proxy.py
  python/ray/serve/router.py
  python/ray/serve/tests/test_api.py
Labels: @author-action-required

#21997 [Test] Change `test_placement_group.py` to large test
  python/ray/tests/test_placement_group.py
  python/ray/tests/test_placement_group_4.py
Labels: @author-action-required

#21355 Consistent ray.init return value
  python/ray/client_builder.py
  python/ray/tests/test_ray_init.py
  python/ray/worker.py
Labels: @tests-ok

#22030 [Docs] Executable notebook tutorial
  doc/README.md
  doc/requirements-doc.txt
  doc/source/conf.py
  doc/source/serve/tutorials/BUILD
  doc/source/serve/tutorials/index.rst
  doc/source/serve/tutorials/rllib.md
  doc/source/serve/tutorials/rllib.rst
  python/ray/serve/BUILD
  python/ray/serve/examples/doc/tutorial_rllib.py
  python/ray/serve/tests/test_myst_doc.py
  python/requirements.txt
Labels: docs

#22015 No spreading if a node is selected for lease request due to locality
  python/ray/tests/test_scheduling.py
  src/mock/ray/core_worker/lease_policy.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/lease_policy.cc
  src/ray/core_worker/lease_policy.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/lease_policy_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: do-not-merge

#22034 [e2e] Remove unnecessary logic around copying results
  release/e2e.py
Labels: @tests-ok

#22032 [Runtime Env] Plumbing runtime env failure error message to the exception: Task [1/3]
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/conda_utils.py
  python/ray/exceptions.py
  python/ray/serialization.py
  python/ray/tests/test_runtime_env.py
  src/mock/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/agent_manager.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#21719 [core] Increment ref count when creating an ObjectRef to prevent object from going out of scope
  cpp/include/ray/api.h
  cpp/include/ray/api/actor_task_caller.h
  cpp/include/ray/api/task_caller.h
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectRefImpl.java
  python/ray/_private/test_utils.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/worker.py
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/test/task_manager_test.cc
Labels: @author-action-required

#22057 [Dask-on-Ray] Add support for Dask annotations.
  doc/source/data/dask-on-ray.rst
  python/ray/util/dask/examples/dask_ray_annotate_example.py
  python/ray/util/dask/examples/dask_ray_persist_example.py
  python/ray/util/dask/scheduler.py
  python/ray/util/dask/tests/test_dask_scheduler.py
Labels: @author-action-required

#22116 [jobs] Support ray client format of connection string address for external module
  dashboard/modules/job/sdk.py
  python/ray/tests/test_client_builder.py
Labels: @tests-ok

#22109 [Runtime Env] Support runtime env error message for actors
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/tests/test_runtime_env.py
  src/ray/gcs/gcs_server/gcs_actor_distribution.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/raylet_based_actor_scheduler_test.cc
  src/ray/gcs/pb_util.h
Labels: @author-action-required

#22065 [runtime env] Fix bug where options (e.g. `--extra-index-url`) could not be specified in `requirements.txt`
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
Labels: @author-action-required, 1.11.0rc0-pick

#22039 [serve] Implement experimental deploy_group API
  python/ray/serve/api.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_deploy.py
Labels: @author-action-required

#22058 [Good for initial review][Ray DAG API] Implement experimental ray DAG API for task/class
  python/ray/actor.py
  python/ray/experimental/dag/__init__.py
  python/ray/experimental/dag/class_node.py
  python/ray/experimental/dag/dag_node.py
  python/ray/experimental/dag/format_utils.py
  python/ray/experimental/dag/function_node.py
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/experimental/dag/test_class_dag.py
  python/ray/experimental/dag/test_function_dag.py
  python/ray/remote_function.py
Labels: @author-action-required

#22067 [Datasets] [Docs] Datasets library branding + positioning tweaks
  doc/source/data/dataset-ml-preprocessing.rst
  doc/source/data/dataset.rst
  doc/source/data/getting-started.rst
  doc/source/data/key-concepts.rst
  doc/source/data/package-ref.rst
  doc/source/data/user-guide.rst
Labels: @author-action-required

#22133 [microbenchmark] avoid noisy neighbor
  python/ray/_private/ray_microbenchmark_helpers.py
Labels: @tests-ok

#22155 Remove TaskExecutionSpec
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/common/task/task.cc
  src/ray/common/task/task.h
  src/ray/common/task/task_execution_spec.cc
  src/ray/common/task/task_execution_spec.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet_client/raylet_client.h
Labels: @tests-ok

#22160 [refactor cluster-task-manage 0/n] move internal state into a separate header
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/internal.h
Labels: @tests-ok

#22158 [Core][nightly-test] better way of calculating num features
  release/nightly_tests/dataset/ray_sgd_training.py
Labels: @tests-ok

#22112 [Docs ] Tune docs overhaul (first part)
  doc/.gitignore
  doc/BUILD
  doc/Makefile
  doc/source/_toc.yml
  doc/source/conf.py
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  doc/source/ray-core/_examples/using-ray-with-pytorch-lightning.rst
  doc/source/ray-references/faq.rst
  doc/source/raysgd/raysgd_pytorch.rst
  doc/source/raysgd/raysgd_tune.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/train/train.rst
  doc/source/train/user_guide.rst
  doc/source/tune/.gitignore
  doc/source/tune/_tutorials/README.rst
  doc/source/tune/_tutorials/overview.rst
  doc/source/tune/_tutorials/tune-sklearn.py
  doc/source/tune/api_docs/env.rst
  doc/source/tune/api_docs/integration.rst
  doc/source/tune/api_docs/logging.rst
  doc/source/tune/api_docs/overview.rst
  doc/source/tune/api_docs/scalability.rst
  doc/source/tune/api_docs/stoppers.rst
  doc/source/tune/api_docs/trainable.rst
  doc/source/tune/contrib.rst
  doc/source/tune/examples/index.rst
  doc/source/tune/faq.rst
  doc/source/tune/getting-started.rst
  doc/source/tune/images/serve_thumb.png
  doc/source/tune/images/sklearn_thumb.png
  doc/source/tune/images/tune_overview.png
  doc/source/tune/index.rst
  doc/source/tune/key-concepts.rst
  doc/source/tune/tutorials/BUILD
  doc/source/tune/tutorials/overview.rst
  doc/source/tune/tutorials/tune-advanced-tutorial.rst
  doc/source/tune/tutorials/tune-checkpoints.rst
  doc/source/tune/tutorials/tune-comet.rst
  doc/source/tune/tutorials/tune-distributed.rst
  doc/source/tune/tutorials/tune-lifecycle.rst
  doc/source/tune/tutorials/tune-metrics.rst
  doc/source/tune/tutorials/tune-mlflow.rst
  doc/source/tune/tutorials/tune-output.rst
  doc/source/tune/tutorials/tune-pytorch-cifar.rst
  doc/source/tune/tutorials/tune-pytorch-lightning.rst
  doc/source/tune/tutorials/tune-resources.rst
  doc/source/tune/tutorials/tune-serve-integration-mnist.md
  doc/source/tune/tutorials/tune-sklearn.md
  doc/source/tune/tutorials/tune-stopping.rst
  doc/source/tune/tutorials/tune-wandb.rst
  doc/source/tune/tutorials/tune-xgboost.rst
  doc/source/tune/user-guide.rst
  doc/test_myst_doc.py
  python/ray/tune/tests/example.py
  python/ray/tune/tune.py
Labels: docs

#22183 Fix nightly shuffle_data_loader by pinning down dependencies versions
  release/nightly_tests/shuffle_data_loader/shuffle_data_loader_app_config.yaml
Labels: @tests-ok

#22149 Also allow auto-closing of stale PRs
  .github/stale.yml
Labels: @author-action-required

#22146 Properly release resources of workers exiting due to max_calls
  python/ray/tests/test_basic.py
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @author-action-required

#22120 [core] Increment ref count when creating an ObjectRef to prevent object from going out of scope
  cpp/include/ray/api.h
  cpp/include/ray/api/actor_task_caller.h
  cpp/include/ray/api/task_caller.h
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectRefImpl.java
  python/ray/_private/test_utils.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/worker.py
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/test/task_manager_test.cc
Labels: @author-action-required

#21391 Unskip all but `test_redeploy_single_replica` in `test_deploy.py`
  python/ray/serve/tests/test_deploy.py
Labels: windows, testing

#22215 [refactor cluster-task-manage 1/n] separate resource reporting logic into helper class
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/internal.h
  src/ray/raylet/scheduling/scheduler_resource_reporter.cc
  src/ray/raylet/scheduling/scheduler_resource_reporter.h
Labels: @tests-ok

#22189 [e2e] Update e2e test to use redisless ray by default.
  release/e2e.py
Labels: do-not-merge

#20787 [Datasets] Support ignoring NaNs in aggregations.
  python/ray/data/aggregate.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/null_aggregate.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#22114 [RLlib] Replay Buffer API
  rllib/utils/replay_buffers/__init__.py
  rllib/utils/replay_buffers/mixin_replay_buffer.py
  rllib/utils/replay_buffers/multi_agent_replay_buffer.py
  rllib/utils/replay_buffers/prioritized_replay_buffer.py
  rllib/utils/replay_buffers/replay_buffer.py
  rllib/utils/replay_buffers/reservoir_buffer.py
Labels: @tests-ok

#22196 [Ray DAG] Add `execute()` interface to take user inputs with ENTRY_POINT tag.
  python/ray/experimental/dag/__init__.py
  python/ray/experimental/dag/class_node.py
  python/ray/experimental/dag/conftest.py
  python/ray/experimental/dag/dag_node.py
  python/ray/experimental/dag/format_utils.py
  python/ray/experimental/dag/function_node.py
  python/ray/experimental/dag/input_node.py
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/experimental/dag/tests/test_class_dag.py
  python/ray/experimental/dag/tests/test_function_dag.py
  python/ray/experimental/dag/tests/test_input_node.py
Labels: @author-action-required

#22198 [Core] Disable runtime env logs
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/log_monitor.py
  python/ray/_private/runtime_env/conda_utils.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/tests/test_runtime_env_conda_and_pip_2.py
Labels: @author-action-required

#22248 Fix a bug from many drivers.
  python/ray/_private/test_utils.py
  python/ray/_private/utils.py
  python/ray/_raylet.pyx
  python/ray/worker.py
  release/long_running_tests/workloads/many_drivers.py
Labels: @author-action-required

#22074 [RLlib] Discussion 2022: Fix batch_mode="complete_episodes" documentation inaccuracy.
  doc/source/rllib/rllib-sample-collection.rst
Labels: @tests-ok

#22245 [RLlib] Discussion 4986: OU Exploration (torch) crashes when restoring from checkpoint.
  rllib/utils/exploration/ornstein_uhlenbeck_noise.py
Labels: @tests-ok

#22247 [RLlib] Fix Unity3D built-in examples action bounds from -inf/inf to -1.0/1.0.
  rllib/env/wrappers/unity3d_env.py
Labels: @tests-ok

#22157 Update local object store usage
  python/ray/tests/test_scheduling_2.py
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
Labels: @tests-ok

#21801 [runtime env] Create virtualenv for pip runtime env.
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/conda_utils.py
  python/ray/_private/runtime_env/context.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/validation.py
  python/ray/_private/test_utils.py
  python/ray/tests/BUILD
  python/ray/tests/test_runtime_env_conda_and_pip.py
  python/ray/tests/test_runtime_env_conda_and_pip_4.py
  python/ray/tests/test_runtime_env_validation.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/server/server.py
  python/ray/workers/setup_worker.py
  python/requirements.txt
  python/setup.py
Labels: @tests-ok

#22277 [Dataset][nighlyt-test] pin pyarrow==4.0.1 for dataset related tests
  release/nightly_tests/dataset/app_config.yaml
  release/nightly_tests/dataset/pipelined_ingestion_app.yaml
  release/nightly_tests/dataset/pipelined_training_app.yaml
  release/nightly_tests/dataset/ray_sgd_training_app.yaml
  release/nightly_tests/dataset/shuffle_app_config.yaml
Labels: @tests-ok

#22222 [Doc] [Jobs] Add `ray dashboard` docs to jobs doc
  doc/source/cluster/commands.rst
  doc/source/cluster/job-submission.rst
Labels: @tests-ok

#22037 Add comment to periodic CI pipeline to update release process doc when updating test suites
  release/.buildkite/build_pipeline.py
Labels: @tests-ok

#20562 [tune] Update Lightning examples to support PTL 1.5
  python/ray/tune/examples/mnist_ptl_mini.py
  python/ray/tune/examples/mnist_pytorch_lightning.py
  python/ray/util/ray_lightning/simple_tune.py
  python/ray/util/ray_lightning/tune/__init__.py
  python/requirements/ml/requirements_tune.txt
  python/requirements/ml/requirements_upstream.txt
Labels: @author-action-required

#22323 [Datasets] Fix boolean tensor column representation and slicing.
  python/ray/data/extensions/tensor_extension.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#22355 [serve] Fix HTTP proxy controller namespace bug (#22287)
  python/ray/serve/api.py
  python/ray/serve/deployment_state.py
  python/ray/serve/http_proxy.py
  python/ray/serve/http_state.py
  python/ray/serve/replica.py
  python/ray/serve/tests/test_standalone.py
Labels: release-blocker, 1.11.0rc0-pick

#22305 [Datasets] Expose `TableRow` as public API; minimize copies/type conversions on row-based ops.
  doc/source/data/package-ref.rst
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/compute.py
  python/ray/data/impl/pandas_block.py
  python/ray/data/impl/table_block.py
  python/ray/data/row.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#20780 [runtime env] [Doc] Add two ways of installing dependencies: cluster launcher, and runtime env
  doc/source/ray-core/handling-dependencies.rst
  python/ray/actor.py
  python/ray/worker.py
Labels: @tests-ok

#22342 [runtime env] use pytest tmp_path, os.path.sep, and unskip most tests for windows
  python/ray/tests/test_runtime_env_packaging.py
Labels: @tests-ok

#22311 [runtime env] Introduce async Manager.create
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/container.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/tests/test_runtime_env_working_dir.py
Labels: @tests-ok

#22350 [RLlib] Bug fix: eval-workers in offline RL setup have no env, even though eval_config includes `env` key.
  rllib/agents/tests/test_trainer.py
  rllib/agents/trainer.py
Labels: @tests-ok

#22380 [RLlib] Add example commands for using `setup-dev.py` with RLlib for improved dev setup stability and developer experience.
  doc/source/rllib/rllib-dev.rst
Labels: @tests-ok

#22387 [Release branch] fix test_catalog.py
  rllib/models/jax/misc.py
Labels: 1.11.0rc0-pick

#22388 [Release 1.11.0] fix building Windows wheels
  BUILD.bazel
  src/ray/core_worker/test/core_worker_test.cc
Labels: 1.11.0rc0-pick

#21860 Replace `queue.Queue` with `multiprocessing.JoinableQueue`
  ci/travis/ci.sh
  python/ray/tests/test_multiprocessing.py
  python/ray/util/multiprocessing/__init__.py
Labels: windows, testing

#21809 Unskipped tests for Windows
  python/ray/tests/BUILD
  python/ray/tests/test_actor.py
  python/ray/tests/test_actor_resources.py
  python/ray/tests/test_multi_tenancy.py
  python/ray/tests/test_multinode_failures.py
  python/ray/tests/test_reference_counting.py
  python/ray/tests/test_shuffle.py
  python/ray/tests/test_traceback.py
  python/ray/tests/test_typing.py
Labels: windows, testing, flaky-test

#22364 [gcs] Fix in_memory_store not handling nullptr callback issue (#22321)
  src/ray/gcs/store_client/in_memory_store_client.cc
  src/ray/gcs/store_client/test/store_client_test_base.h
Labels: 1.11.0rc0-pick

#22365 Prep K8s operator for the Ray 1.11.0 release. (#22264)
  deploy/charts/ray/templates/raycluster.yaml
  deploy/charts/ray/values.yaml
  deploy/components/example_cluster.yaml
  python/ray/autoscaler/kubernetes/defaults.yaml
  python/ray/autoscaler/kubernetes/example-full-legacy.yaml
  python/ray/autoscaler/kubernetes/example-full.yaml
  python/ray/autoscaler/kubernetes/example-ingress.yaml
Labels: 1.11.0rc0-pick

#22359 [refactor cluster-task-manage 3/n] Separate stats reporting into its own file
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/scheduler_stats.cc
  src/ray/raylet/scheduling/scheduler_stats.h
Labels: @tests-ok

#22366 [gcs/ha] Enable HA flags by default (#21608)
  src/ray/common/ray_config_def.h
Labels: 1.11.0rc0-pick

#22394 [Pubsub] increase subscriber timeout
  src/ray/common/ray_config_def.h
Labels: @tests-ok

#22374 [data] Pre-reqs for implementing stage fusion
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/fast_repartition.py
  python/ray/data/impl/plan.py
  python/ray/data/impl/shuffle.py
  python/ray/data/impl/sort.py
  python/ray/data/impl/stats.py
Labels: @tests-ok

#22407 [Release branch] support GCS-Ray in e2e.py
  release/e2e.py
Labels: release-blocker

#21600 [doc][Java] Add doc page for java concurrency group.
  doc/source/ray-core/concurrency_group_api.rst
Labels: docs

#22431 Fix Dask on Ray 1 TB bug
  release/nightly_tests/dask_on_ray/dask_on_ray_sort.py
Labels: @author-action-required

#22427 [RLlib] Bandit documentation enhancements.
  doc/source/rllib/rllib-algorithms.rst
Labels: @tests-ok

#22496 [docs] RLlib concepts consolidation, user guide, RL conf prep
  doc/source/_includes/images/rl_summit_promo_square.png
  doc/source/_includes/images/rl_summit_promo_thin.png
  doc/source/_includes/rllib_announcement.rst
  doc/source/_includes/rllib_announcement_bottom.rst
  doc/source/_includes/rllib_we_are_hiring.rst
  doc/source/_static/css/custom.css
  doc/source/_toc.yml
  doc/source/rllib/core-concepts.rst
  doc/source/rllib/index.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-dev.rst
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/rllib-sample-collection.rst
  doc/source/rllib/rllib-toc.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/user-guides.rst
  doc/source/rllib/we_are_hiring.rst
Labels: rllib, docs

#21519 [core] Enable lineage reconstruction in CI
  .bazelrc
  python/ray/workflow/tests/test_basic_workflows_2.py
  python/ray/workflow/tests/test_basic_workflows_3.py
  python/ray/workflow/tests/test_virtual_actor_2.py
  python/ray/workflow/tests/test_virtual_actor_3.py
  release/e2e.py
Labels: @author-action-required

#22463 [1][resource reporting] Remove redis based resource broadcasting.
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_resource_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_resource_scheduler_test.cc
Labels: @author-action-required

#22492 [Core] release GIL when running `parallel_memcopy()` / `memcpy()` during serializations
  python/ray/includes/serialization.pxi
Labels: @tests-ok

#21303 Round robin during spread scheduling
  python/ray/data/impl/shuffle.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/tests/test_scheduling.py
  python/ray/tests/test_scheduling_2.py
  python/ray/util/scheduling_strategies.py
  release/nightly_tests/dataset/pipelined_training.py
  release/nightly_tests/dataset/ray_sgd_runner.py
  release/nightly_tests/dataset/ray_sgd_training.py
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/local_task_manager.cc
  src/ray/raylet/scheduling/local_task_manager.h
  src/ray/raylet/scheduling/scheduling_policy.cc
  src/ray/raylet/scheduling/scheduling_policy.h
  src/ray/raylet/scheduling/scheduling_policy_test.cc
Labels: @tests-ok

#22503 [docs] rllib conference material
  doc/source/_includes/images/rl_summit_promo_square.png
  doc/source/_includes/images/rl_summit_promo_thin.png
  doc/source/_includes/rllib_announcement.rst
  doc/source/_includes/rllib_announcement_bottom.rst
  doc/source/_includes/rllib_we_are_hiring.rst
  doc/source/_static/css/custom.css
  doc/source/_toc.yml
  doc/source/rllib/core-concepts.rst
  doc/source/rllib/index.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-dev.rst
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/rllib-sample-collection.rst
  doc/source/rllib/rllib-toc.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/user-guides.rst
  doc/source/rllib/we_are_hiring.rst
  python/ray/serve/tests/test_myst_doc.py
Labels: 1.11.0rc1-pick

#22208 Unskipped tests in `test_object_spilling`, `test_object_spilling_2`, `test_get_locations`
  python/ray/tests/conftest.py
  python/ray/tests/test_get_locations.py
  python/ray/tests/test_object_spilling.py
  python/ray/tests/test_object_spilling_2.py
Labels: windows, testing, flaky-test

#22494 [ci] Fix grpcio 1.44 break test_output
  .buildkite/pipeline.yml
  ci/asan_tests/ray-project/requirements.txt
  python/requirements.txt
  python/setup.py
Labels: @author-action-required

#22249 [Usage Stats] Implement usage stats report "Turned off by default".
  dashboard/modules/usage_stats/__init__.py
  dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/BUILD
  python/ray/tests/test_usage_stats.py
  python/setup.py
Labels: @author-action-required

#22528 [GCS-Ray] update doc and error message for GCS-Ray
  doc/source/cluster/cloud.rst
  doc/source/cluster/guide.rst
  doc/source/cluster/lsf.rst
  doc/source/ray-contribute/debugging.rst
  doc/source/ray-core/configure.rst
  doc/source/ray-core/memory-management.rst
  doc/source/ray-observability/ray-logging.rst
  doc/source/raysgd/raysgd_pytorch.rst
  doc/source/tune/tutorials/tune-distributed.rst
  python/ray/_private/utils.py
Labels: @tests-ok, 1.11.0rc1-pick

#22547 [serve] Add JSON schemas for REST API
  dashboard/modules/serve/schema.py
  dashboard/modules/serve/tests/test_schema.py
  python/ray/serve/config.py
  python/ray/serve/tests/test_config.py
Labels: @author-action-required

#22317 [core] Add task and object reconstruction status to ray memory
  dashboard/memory_utils.py
  python/ray/tests/test_memstat.py
  python/ray/tests/test_reconstruction.py
  src/mock/ray/core_worker/task_manager.h
  src/ray/common/id.cc
  src/ray/common/id.h
  src/ray/common/id_test.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/protobuf/common.proto
Labels: @author-action-required

#22558 Remove DEFAULT_SCHEDULING_STRATEGY and SPREAD_SCHEDULING_STRATEGY
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/tests/test_scheduling_2.py
  python/ray/util/scheduling_strategies.py
Labels: @tests-ok

#22572 Fix [Bug] DatasetPipeline .iter_epochs() can lead to infinite loops
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: @tests-ok

#22559 Fix [Bug] Splitting Dataset when shards < n hangs or errors
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/impl/pipeline_executor.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_split.py
Labels: @author-action-required

#22596 [GCS-Ray][1.11.0 Cherry-pick] update doc and error message for GCS-Ray
  doc/source/cluster/cloud.rst
  doc/source/cluster/guide.rst
  doc/source/cluster/lsf.rst
  doc/source/ray-contribute/debugging.rst
  doc/source/ray-core/configure.rst
  doc/source/ray-core/memory-management.rst
  doc/source/ray-observability/ray-logging.rst
  doc/source/raysgd/raysgd_pytorch.rst
  doc/source/tune/tutorials/tune-distributed.rst
  python/ray/node.py
Labels: 1.11.0rc1-pick

#22608 [ci][cherry-pick] Fix grpcio 1.44 break test_output (#22494)
  .buildkite/pipeline.yml
  ci/asan_tests/ray-project/requirements.txt
  python/requirements.txt
  python/setup.py
Labels: 1.11.0rc1-pick

#22381 [runtime env] Async pip runtime env
  LICENSE
  python/ray/_private/async_compat.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/utils.py
  python/ray/tests/test_runtime_env.py
Labels: @tests-ok

#22590 [RLlib] Issue 22444: KL-coeff not stored in persistent policy state.
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/agents/ppo/ppo_torch_policy.py
Labels: @tests-ok

#22421 [RLlib] Update bandit_envs_recommender_system
  rllib/env/wrappers/recsim.py
  rllib/examples/bandit/tune_lin_ucb_train_recommendation.py
  rllib/examples/bandit/tune_lin_ucb_train_recsim_env.py
  rllib/examples/env/bandit_envs_recommender_system.py
Labels: @tests-ok

#22617 [2/X][Pipeline] Add python generation for ClassNode
  python/ray/experimental/dag/__init__.py
  python/ray/experimental/dag/class_node.py
  python/ray/experimental/dag/constants.py
  python/ray/experimental/dag/tests/test_class_dag.py
  python/ray/serve/pipeline/constants.py
  python/ray/serve/pipeline/deployment_method_node.py
  python/ray/serve/pipeline/deployment_node.py
  python/ray/serve/pipeline/generate.py
  python/ray/serve/pipeline/tests/test_deployment_node.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/pipeline/tests/test_modules.py
Labels: @tests-ok

#22584 [Core] Bug fix about FixedPoint
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/fixed_point.h
Labels: @tests-ok

#22631 [Release] Disable failing `serve_micro_benchmark_k8s` test
  release/.buildkite/build_pipeline.py
Labels: @tests-ok

#21410 [Xlang] Allow Python to call overloaded methods with differing number of parameters
  java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java
  java/runtime/src/test/java/io/ray/runtime/functionmanager/FunctionManagerTest.java
  java/test/src/main/java/io/ray/test/CrossLanguageInvocationTest.java
  java/test/src/main/java/io/ray/test/ExampleImpl.java
  java/test/src/main/resources/test_cross_language_invocation.py
  python/ray/actor.py
  python/ray/cross_language.py
Labels: @author-action-required

#22560 [resource scheduler] unify the GetBestSchedulableNode into one public method.
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/internal.h
  src/ray/raylet/scheduling/local_task_manager.cc
  src/ray/raylet/scheduling/local_task_manager.h
Labels: @tests-ok

#22626 Revert "[runtime env] runtime env inheritance refactor (#22244)"
  doc/source/ray-core/handling-dependencies.rst
  python/ray/__init__.py
  python/ray/runtime_env.py
  python/ray/tests/test_client.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/tests/test_runtime_env_env_vars.py
  python/ray/util/client/api.py
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/core_worker_test.cc
Labels: @author-action-required

#22639 [core] Cleanup handling for nondeterministic object size during transfer
  BUILD.bazel
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/object_buffer_pool.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/test/object_buffer_pool_test.cc
Labels: @author-action-required

#22651 [Serve] [CI] Add health check grace period to deflake `single_deployment_1k_noop_replica`
  release/serve_tests/workloads/single_deployment_1k_noop_replica.py
Labels: @tests-ok

#22571 [core] Fix bug in fusion for spilled objects
  python/ray/tests/BUILD
  python/ray/tests/test_object_spilling_no_asan.py
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#22642 Add some sanity checks for memory use in dataset
  .github/CODEOWNERS
  python/ray/data/dataset.py
  python/ray/data/tests/test_optimize.py
Labels: @tests-ok

#22436 [ml] Add basic Ray ML interfaces
  python/ray/ml/__init__.py
  python/ray/ml/checkpoint.py
  python/ray/ml/predictor.py
  python/ray/ml/preprocessor.py
  python/ray/ml/result.py
Labels: @author-action-required

#22442 [release] Fix special cases in release test package (e.g. smoke test)
  release/BUILD
  release/ray_release/cluster_manager/cluster_manager.py
  release/ray_release/glue.py
  release/ray_release/scripts/build_pipeline.py
  release/ray_release/scripts/convert_legacy_config.py
  release/ray_release/scripts/run_release_test.py
  release/ray_release/tests/_test_catch_args.py
  release/ray_release/tests/test_buildkite.py
  release/ray_release/tests/test_glue.py
  release/ray_release/tests/test_run_script.py
  release/release_tests.yaml
  release/run_release_test.sh
Labels: @author-action-required

#22629 [Core] Include java worker log with log monitor
  python/ray/_private/log_monitor.py
  python/ray/tests/test_logging.py
Labels: @author-action-required

#22702 [Dataset][nighly-test] promote data ingestion test to stable
  release/nightly_tests/dataset/dataset_test.yaml
Labels: @tests-ok

#22699 [Release 1.111.0] Bump version from 1.11.0rc1 to 1.11.0
  build-docker.sh
  java/api/pom_template.xml
  java/performance_test/pom_template.xml
  java/pom.xml
  java/runtime/pom_template.xml
  java/serve/pom_template.xml
  java/test/pom_template.xml
  python/ray/__init__.py
  src/ray/common/constants.h
Labels: @tests-ok

#22506 [aws][autoscaler] fix regional default AMI's
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/aws/defaults.yaml
  python/ray/tests/aws/conftest.py
  python/ray/tests/aws/test_autoscaler_aws.py
  python/ray/tests/aws/utils/stubs.py
Labels: @tests-ok

#22680 [Doc] [Jobs] add CLI and SDK reference to docs
  dashboard/modules/job/cli.py
  dashboard/modules/job/sdk.py
  doc/source/cluster/job-submission.rst
  doc/source/cluster/jobs-package-ref.rst
  doc/source/ray-references/api.rst
Labels: @tests-ok
