Repository ray-project/ray, pull requests merged in 2022-01, with the labels that each got.

#21260 [Train] Monkeypatch environment variables in `test_json`
  python/ray/train/tests/test_callbacks.py
Labels: train

#21262 [Train] Replace `abc.ABCMeta` with `abc.ABC` in callbacks
  python/ray/train/callbacks/callback.py
  python/ray/train/callbacks/logging.py
Labels: train

#21261 [Train] Add `PrintCallback`
  doc/source/train/api.rst
  doc/source/train/user_guide.rst
  python/ray/train/callbacks/__init__.py
  python/ray/train/callbacks/print.py
  python/ray/train/tests/test_callbacks.py
Labels: train

#21374 Unskipped `test_reconfigure_with_exception` & `test_deploy_handle_validation`
  python/ray/serve/tests/test_deploy.py
Labels: windows, testing

#21219 [Actor exception message improvement] Unify the schema + improve error messages.
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
Labels: @author-action-required

#21376 [RLlib] Issue 18499: PGTrainer with training_iteration fn does not support multi-GPU.
  rllib/agents/a3c/a2c.py
  rllib/agents/cql/cql.py
  rllib/agents/dqn/dqn.py
  rllib/agents/dqn/simple_q.py
  rllib/agents/pg/default_config.py
  rllib/agents/ppo/ppo.py
  rllib/agents/trainer.py
  rllib/execution/buffers/multi_agent_replay_buffer.py
  rllib/execution/rollout_ops.py
  rllib/execution/train_ops.py
  rllib/tuned_examples/pg/cartpole-pg-fake-gpus.yaml
  rllib/utils/sgd.py
Labels: release-blocker

#21401 [Docker] Allow Branches with Double digits
  ci/travis/build-docker-images.py
Labels: @tests-ok

#21382 Unskipped test and bumped wait time to avoid race conditions
  python/ray/serve/tests/test_deploy.py
Labels: windows, testing

#21394 [Core] [Java] [Flaky] Disable Java log rotation test.
  java/test/src/main/java/io/ray/test/RayJavaLoggingTest.java
Labels: @tests-ok

#21279 [Core] Cache job_configs instead of ray_namespace.
  BUILD.bazel
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/test/gcs_test_util.h
Labels: @tests-ok

#21369 Refactor ObjectManager wait logic to WaitManager
  BUILD.bazel
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/wait_manager.cc
  src/ray/raylet/wait_manager.h
  src/ray/raylet/wait_manager_test.cc
Labels: @tests-ok

#21229 [runtime env] Fix "conda" field for M1 macs
  python/ray/_private/runtime_env/conda.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
Labels: @tests-ok

#20800 [core] Nested tasks on by default
  python/ray/tests/test_multinode_failures.py
  python/ray/workflow/tests/test_virtual_actor.py
  src/ray/common/ray_config_def.h
Labels: @tests-ok

#21350 Unskipped `test_snapshot_always_written_to_internal_kv`
  python/ray/serve/tests/test_standalone.py
Labels: windows, testing

#21423 [serve] Unskipped tests in `test_constructor_failure.py` & `test_ray_client.py`
  python/ray/serve/tests/test_constructor_failure.py
  python/ray/serve/tests/test_ray_client.py
Labels: windows, testing, flaky-test

#21422 [serve] Unskip tests in `test_fastapi.py`
  python/ray/serve/tests/test_fastapi.py
Labels: windows, testing, flaky-test

#21465 Remove dead tests related to the old scheduler
  python/ray/_private/test_utils.py
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_reference_counting.py
  python/ray/tests/test_scheduling.py
Labels: @tests-ok

#21466 [Core] allow message in deprecation annotation
  python/ray/util/annotations.py
  python/ray/worker.py
Labels: @author-action-required

#21442 [2/3][kv] Add delete by prefix support for internal kv
  python/ray/_private/gcs_utils.py
  python/ray/experimental/internal_kv.py
  python/ray/tests/test_basic_5.py
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
  src/ray/protobuf/gcs_service.proto
Labels: @author-action-required

#21451 Unskipped test in `test_kv_store.py`
  python/ray/serve/tests/storage_tests/test_kv_store.py
Labels: windows, testing, flaky-test

#21503 Unskipped test in `test_advanced_2.py`
  python/ray/tests/test_advanced_2.py
Labels: windows, testing

#20266 [autoscaler] AWS Autoscaler CloudWatch Dashboard support
  python/ray/autoscaler/_private/aws/cloudwatch/cloudwatch_helper.py
  python/ray/autoscaler/_private/aws/node_provider.py
  python/ray/autoscaler/_private/updater.py
  python/ray/autoscaler/aws/cloudwatch/example-cloudwatch-agent-config.json
  python/ray/autoscaler/aws/cloudwatch/example-cloudwatch-dashboard-config.json
  python/ray/autoscaler/aws/example-cloudwatch.yaml
  python/ray/autoscaler/ray-schema.json
Labels: @tests-ok

#21462 [Java] Use localhost instead of public ip
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  java/runtime/src/main/java/io/ray/runtime/util/NetworkUtil.java
Labels: @tests-ok

#21444 Add container utils
  BUILD.bazel
  src/ray/raylet/wait_manager.cc
  src/ray/util/container_util.h
  src/ray/util/container_util_test.cc
Labels: @tests-ok

#21183 [workflow] Skip saving outputs of "workflow.wait"
  python/ray/workflow/step_executor.py
  python/ray/workflow/tests/test_wait.py
Labels: @author-action-required

#20826 [runtime env] allow working_dir to be a zipped package
  doc/source/handling-dependencies.rst
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/tests/test_runtime_env_working_dir.py
Labels: @tests-ok

#20256 [rfc][ci] create fake docker-compose cluster environment
  .buildkite/pipeline.ml.yml
  ci/travis/build-docker-images.py
  doc/source/fake-autoscaler.rst
  python/ray/autoscaler/_private/fake_multi_node/command_runner.py
  python/ray/autoscaler/_private/fake_multi_node/docker_monitor.py
  python/ray/autoscaler/_private/fake_multi_node/example_docker.yaml
  python/ray/autoscaler/_private/fake_multi_node/node_provider.py
  python/ray/autoscaler/_private/fake_multi_node/test_utils.py
  python/ray/autoscaler/_private/providers.py
  python/ray/tune/BUILD
  python/ray/tune/tests/test_multinode_sync.py
  python/ray/util/ml_utils/dict.py
Labels: @author-action-required

#21497 Unskipped test in `test_autoscaling_policy`
  python/ray/serve/tests/test_autoscaling_policy.py
Labels: windows, testing, flaky-test

#21498 Unskipped tests in test_actor_failures
  python/ray/tests/test_actor_failures.py
Labels: windows, testing, flaky-test

#21500 Unskipped non-cluster tests in test_actor_resources.py
  python/ray/tests/test_actor_resources.py
Labels: windows, testing, flaky-test

#21510 [GCS] Fix `test_multi_node.py::test_error_isolation` with GCS pubsub
  .buildkite/pipeline.yml
  python/ray/tests/test_multi_node.py
Labels: @tests-ok

#21448 [RLlib] Issue 21044: Improve error message for "multiagent" dict checks.
  rllib/agents/trainer.py
  rllib/env/policy_client.py
  rllib/examples/multi_agent_custom_policy.py
  rllib/execution/rollout_ops.py
  rllib/utils/__init__.py
  rllib/utils/multi_agent.py
  rllib/utils/pre_checks/__init__.py
  rllib/utils/pre_checks/env.py
  rllib/utils/pre_checks/multi_agent.py
  rllib/utils/test_utils.py
  rllib/utils/tests/test_check_env.py
  rllib/utils/tests/test_check_multi_agent.py
Labels: @tests-ok

#21535 Fix SchedulingClassInfo.running_tasks memory leak
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @tests-ok

#21553 [RLlib] Issue 21552: `unsquash_action` and `clip_action` (when None) cause wrong actions computed by `Trainer.compute_single_action`.
  rllib/agents/trainer.py
  rllib/utils/test_utils.py
Labels: @tests-ok

#21484 Unskipped tests in `test_pipeline.py`
  python/ray/serve/pipeline/tests/test_pipeline.py
Labels: windows, testing

#21539 [Core] Small comment/docstring fixes in cluster task manager header.
  src/ray/raylet/scheduling/cluster_task_manager.h
Labels: @tests-ok

#21450 Unskipped tests in serve: `test_controller_recovery.py`
  python/ray/serve/tests/fault_tolerance_tests/test_controller_recovery.py
Labels: windows, testing, flaky-test

#21560 [RLlib] Discussion 4351: Conv2d default filter tests and add default setting for 96x96 image obs space.
  rllib/BUILD
  rllib/models/tests/test_conv2d_default_stacks.py
  rllib/models/utils.py
Labels: @tests-ok

#20404 [scheduler] Set default max_pending_lease_requests_per_scheduling_category to 10
  python/ray/tests/test_advanced_2.py
  python/ray/tests/test_scheduling.py
  python/ray/tests/test_worker_capping.py
  src/ray/common/ray_config_def.h
Labels: @tests-ok

#21585 Revert "Revert "[gcs] turn on grpc pubsub by default""
  .buildkite/pipeline.yml
  dashboard/agent.py
  dashboard/modules/job/tests/test_job_manager.py
  dashboard/tests/test_dashboard.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/gcs_utils.py
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/tune/tests/test_tune_restore.py
Labels: @author-action-required

#21509 [core] Add GC for function table
  BUILD.bazel
  python/ray/tests/test_advanced_4.py
  python/ray/tests/test_basic_5.py
  src/mock/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_function_manager.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_function_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
Labels: @author-action-required

#21395 [core] Avoid ObjectID collisions for re-executed tasks
  python/ray/tests/test_reconstruction.py
  src/ray/common/id.cc
  src/ray/common/id.h
  src/ray/common/id_test.cc
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/design_docs/id_specification.md
  src/ray/protobuf/common.proto
Labels: @author-action-required

#21588 [Dataset] Fix simple dataset sort generating only 1 non-empty block
  python/ray/data/impl/simple_block.py
  python/ray/data/tests/test_dataset.py
Labels: @tests-ok

#21439 [Core] dlmalloc allocate bottom-most memory chunk failed
  python/ray/tests/test_plasma_unlimited.py
  src/ray/object_manager/plasma/dlmalloc.cc
  src/ray/object_manager/plasma/test/fallback_allocator_test.cc
Labels: @tests-ok, @author-action-required

#21501 Unskipped tests in `test_actor.py`
  python/ray/tests/test_actor.py
Labels: windows, testing

#20988 [Dataset] [DataFrame 2/n] Add pandas block format implementation (partial)
  doc/examples/datasets_train/datasets_train.py
  python/ray/data/block.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/delegating_block_builder.py
  python/ray/data/impl/pandas_block.py
  python/ray/data/impl/simple_block.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#21610 Improve errors raised by ds.groupby() of unsupported key type
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#21639 [Java] Change ActorLifetime API: DEFAULT -> NON_DETACHED
  java/api/src/main/java/io/ray/api/options/ActorCreationOptions.java
  java/api/src/main/java/io/ray/api/options/ActorLifetime.java
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
Labels: release-blocker

#21607 [LOGGING][RFC] Add RAY_CHECK_OP
  src/ray/raylet/wait_manager.cc
  src/ray/util/logging.h
  src/ray/util/logging_test.cc
Labels: @tests-ok

#21680 [Core][nightly-test] install botocore with s3fs to ensure no confliction.
  release/nightly_tests/shuffle_data_loader/shuffle_data_loader_app_config.yaml
Labels: @author-action-required, do-not-merge

#21698 [Test] First core nightly test migration to k8s
  release/.buildkite/build_pipeline.py
  release/nightly_tests/dask_on_ray/dask_on_ray_stress_compute_k8s.yaml
  release/nightly_tests/nightly_tests.yaml
Labels: @author-action-required

#21364 [core] Fix race condition between object free and duplicate creation
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/test/local_object_manager_test.cc
Labels: @author-action-required

#21533 Fix monitor.py exceptions. Enable fetching GCS address from Redis with retries.
  python/ray/_private/gcs_utils.py
  python/ray/autoscaler/_private/monitor.py
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#21360 [doc] add Ray versions 1.9.1 - 1.10.0 to dask on ray compatibility table
  doc/source/data/dask-on-ray.rst
Labels: @tests-ok

#21548 [Fix][Locality] ref count should remove object locations for dead nodes
  python/ray/tests/test_failure_4.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/reference_count_test.cc
Labels: @author-action-required

#21686 Silence "cut: write error: Broken pipe" log spew
  dashboard/modules/reporter/reporter_agent.py
Labels: @author-action-required

#21593 [Internal Observability] Fix the event stats segfault 1/2
  src/ray/common/asio/periodical_runner.cc
  src/ray/common/asio/periodical_runner.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/core_worker_process.h
  src/ray/core_worker/gcs_server_address_updater.cc
  src/ray/core_worker/gcs_server_address_updater.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#21720 Fix replace_symlinks_with_junctions for windows
  python/setup.py
Labels: @tests-ok

#21659 [Jobs] Stream logs during job instead of only at the end
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
Labels: @tests-ok

#21692 [gcs/ha] Fix java related error when enable redisless ray
  .buildkite/pipeline.yml
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GcsClient.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GcsClientOptions.java
  java/runtime/src/main/java/io/ray/runtime/gcs/GlobalStateAccessor.java
  java/runtime/src/main/java/io/ray/runtime/runner/RunManager.java
  java/runtime/src/main/java/io/ray/runtime/util/SystemConfig.java
  java/test/src/main/java/io/ray/test/TestUtils.java
  python/ray/_private/services.py
  src/ray/common/test_util.cc
  src/ray/common/test_util.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.cc
  src/ray/gcs/gcs_client/gcs_client.h
  streaming/src/test/mock_actor.cc
  streaming/src/test/queue_tests_base.h
Labels: @author-action-required

#21729 [gcs/ha] Fix global_state_accessor_test to support redisless mode
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
Labels: @author-action-required

#21717 [Pubsub] fix driver warning for not keeping up with worker logs
  python/ray/_private/gcs_pubsub.py
  python/ray/worker.py
Labels: @author-action-required

#21746 [Dashboard] turn a noisy `info` log into `debug`
  dashboard/modules/node/node_head.py
Labels: @tests-ok

#21765 [Test] increase timeout for `test_traceback.py`
  python/ray/tests/BUILD
Labels: @tests-ok

#21757 [Core] [Releaser] Fix e2e.py help info for --report
  release/e2e.py
Labels: @tests-ok

#21732 [resource-reporting] refactor resource scheduler 1/n
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
Labels: @author-action-required

#21693 Using a deterministic approach to check connections in `test_job_timestamps`
  python/ray/tests/test_job.py
Labels: windows, testing, flaky-test

#21283 [Core] Support default actor lifetime.
  cpp/src/ray/runtime/task/native_task_submitter.cc
  java/api/src/main/java/io/ray/api/options/ActorCreationOptions.java
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/resources/ray.default.conf
  java/test/src/main/java/io/ray/test/DefaultActorLifetimeTest.java
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/job_config.py
  python/ray/tests/test_actor_lifetime.py
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/lib/java/jni_init.cc
  src/ray/core_worker/lib/java/jni_utils.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/protobuf/gcs.proto
Labels: core-api-change-approval-required

#21708 Unskipped `test_worker_stdout`
  python/ray/tests/test_output.py
Labels: windows, testing, flaky-test

#21224 [Core] Fix 16GB mac perf issue by limit the plasma store size to 2GB
  python/ray/_private/resource_spec.py
  python/ray/_private/services.py
  python/ray/ray_constants.py
  python/ray/tests/conftest.py
  python/ray/tests/test_object_manager.py
  python/ray/tests/test_scheduling_2.py
Labels: @author-action-required

#21551 [1/n][cross-language runtime env] runtime env protobuf refactor
  python/ray/_private/runtime_env/utils.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/protobuf/runtime_env_common.proto
Labels: @tests-ok

#20765 Add a new End-to-End tutorial in Serve that walks users through deploying a model
  doc/source/_toc.yml
  doc/source/serve/deployment.rst
  doc/source/serve/end_to_end_tutorial.rst
  doc/source/serve/http-servehandle.rst
  doc/source/serve/index.rst
  doc/source/serve/tutorial.rst
  python/ray/serve/examples/doc/e2e_class_deployment.py
  python/ray/serve/examples/doc/e2e_deployment.py
  python/ray/serve/examples/doc/e2e_deployment_full.py
  python/ray/serve/examples/doc/e2e_fastapi_client.py
  python/ray/serve/examples/doc/e2e_fastapi_deployment.py
  python/ray/serve/examples/doc/e2e_local.py
  python/ray/serve/examples/doc/e2e_router_client.py
  python/ray/serve/examples/doc/e2e_summarizer_client.py
Labels: @author-action-required

#21816 [Test] Fix dask on ray test on K8s
  release/nightly_tests/dask_on_ray/large_scale_test.py
  release/nightly_tests/nightly_tests.yaml
Labels: @author-action-required

#21824 Unskipped tests for Windows in `test_client.py`
  python/ray/tests/test_client.py
Labels: windows, testing, flaky-test

#21775 Unskip tests for Windows in `test_output`
  python/ray/tests/test_output.py
Labels: windows, testing

#21767 [RFC] [Core] Support disabling log redirection via `RAY_LOG_TO_STDERR` environment variable.
  doc/source/ray-observability/ray-logging.rst
  python/ray/_private/ray_logging.py
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/ray_constants.py
  python/ray/tests/test_logging.py
  python/ray/worker.py
  src/ray/util/logging.cc
Labels: @tests-ok

#21790 Two issues fix for GCS connecting logic in monitor.py and log_monitor.py
  python/ray/_private/gcs_pubsub.py
  python/ray/autoscaler/_private/monitor.py
Labels: @author-action-required

#21795 [autoscaler] Fix ray.autoscaler.sdk import issue
  ci/travis/format.sh
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/tests/test_dashboard.py
  python/ray/__init__.py
  python/ray/autoscaler/__init__.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/constants.py
  python/ray/autoscaler/_private/legacy_info_string.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/autoscaler/_private/updater.py
  python/ray/autoscaler/_private/util.py
  python/ray/autoscaler/sdk/__init__.py
  python/ray/autoscaler/sdk/sdk.py
  python/ray/ray_constants.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_placement_group_3.py
  python/ray/worker.py
Labels: @tests-ok

#21542 [release] Fix broken `pip_download_test.sh` script for non-M1 Macs
  release/util/pip_download_test.sh
Labels: @tests-ok

#21878 Remove work stealing
  src/mock/ray/core_worker/core_worker.h
  src/mock/ray/core_worker/transport/direct_actor_transport.h
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/actor_scheduling_util.cc
  src/ray/core_worker/transport/actor_scheduling_util.h
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/core_worker/transport/normal_scheduling_queue.cc
  src/ray/core_worker/transport/normal_scheduling_queue.h
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.h
  src/ray/core_worker/transport/scheduling_queue.h
  src/ray/protobuf/core_worker.proto
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: @tests-ok

#21859 [docs] landing page (fixes #21750)
  doc/BUILD
  doc/source/_includes/_contribute.md
  doc/source/_static/js/docsearch.js
  doc/source/_toc.yml
  doc/source/cluster/reference.rst
  doc/source/conf.py
  doc/source/data/_examples/doc_code/quick_start.py
  doc/source/data/package-ref.rst
  doc/source/images/api.svg
  doc/source/images/contribute.svg
  doc/source/images/getting_started.svg
  doc/source/images/user_guide.svg
  doc/source/index.md
  doc/source/index.rst
  doc/source/ray-core/package-ref.rst
  doc/source/ray-overview/basics.rst
  doc/source/ray-overview/images/ray_ecosystem_integration_v2.png
  doc/source/ray-overview/images/ray_framework_v2.png
  doc/source/ray-overview/images/ray_logo_bw.png
  doc/source/ray-overview/images/ray_original-bw.png
  doc/source/ray-overview/images/ray_original.png
  doc/source/ray-overview/images/ray_svg_logo.svg
  doc/source/ray-overview/images/ray_svg_logo_only.svg
  doc/source/ray-overview/index.md
  doc/source/ray-overview/index.rst
  doc/source/ray-overview/learn-more.md
  doc/source/ray-overview/ray-libraries.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/serve/_examples/doc_code/quick_start.py
  doc/source/serve/package-ref.rst
  doc/source/tune/api_docs/overview.rst
  doc/source/workflows/package-ref.rst
  doc/yarn/example.py
Labels: docs

#21867 [function table] Make sure FunctionsToRun are executed properly on all workers
  python/ray/_private/function_manager.py
  python/ray/_private/import_thread.py
  python/ray/tests/test_advanced_4.py
  python/ray/tests/test_basic_5.py
  python/ray/worker.py
  src/ray/gcs/gcs_server/gcs_function_manager.h
  src/ray/gcs/gcs_server/test/gcs_function_manager_test.cc
Labels: @author-action-required

#21772 [resource-reporting 2/n]separate local resource manager from cluster_resource_scheduler
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/placement_group_resource_manager_test.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_interface.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/fixed_point.h
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
  src/ray/raylet/scheduling/scheduling_policy.h
Labels: do-not-merge

#21899 Don't advertise cpus on gpu nodes for pipelined ingestion tests
  release/nightly_tests/dataset/pipelined_ingestion_compute.yaml
  release/nightly_tests/dataset/pipelined_training.py
Labels: @tests-ok

#21885 [autoscaler] Optimize finding the node id
  python/ray/autoscaler/node_provider.py
Labels: @author-action-required

#21649 [RLlib] Preparatory PR for multi-agent, multi-GPU learning agent (alpha-star style) #02.
  rllib/execution/buffers/mixin_replay_buffer.py
  rllib/execution/buffers/multi_agent_replay_buffer.py
  rllib/execution/buffers/replay_buffer.py
  rllib/execution/parallel_requests.py
  rllib/execution/replay_ops.py
  rllib/execution/rollout_ops.py
  rllib/execution/tests/test_mixin_multi_agent_replay_buffer.py
  rllib/models/jax/misc.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/utils/metrics/__init__.py
  rllib/utils/metrics/window_stat.py
Labels: @tests-ok

#21933 [Doc] update dask version for Ray 1.11.0
  doc/source/data/dask-on-ray.rst
Labels: @tests-ok

#21942 [Release 1.11.0rc0 Cherrypick] update supported dask version
  doc/source/data/dask-on-ray.rst
Labels: 1.11.0rc0-pick

#21944 [Release 1.11.0rc0 Cherrypick] fix pip_download_test.sh
  release/util/pip_download_test.sh
Labels: @tests-ok, 1.11.0rc0-pick

#21943 [Release 1.11.0rc0 Cherrypick] [ci/release] Increase step timeout in long running tests, fix artifacts copy
  release/alerts/long_running_tests.py
  release/run_e2e.sh
Labels: @tests-ok, 1.11.0rc0-pick

#21890 Unskipped tests for Windows
  python/ray/tests/test_client_compat.py
  python/ray/tests/test_multi_tenancy.py
Labels: windows, testing, flaky-test

#21927 [resource-reporting 3/n] further clean up LocalResourceManager
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
Labels: do-not-merge

#21853 [Core]delete shim pid flag
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/mock_setup_worker.py
  python/ray/util/client/server/server.py
  python/ray/worker.py
  python/ray/workers/default_worker.py
  python/ray/workers/setup_worker.py
  src/mock/ray/raylet/worker.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_options.h
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @author-action-required

#21955 [Release 1.11 Cherrypick] [e2e] do not terminate in `serve_failure` smoke test
  release/BUILD
  release/long_running_tests/long_running_tests.yaml
  release/long_running_tests/workloads/serve_failure.py
Labels: @tests-ok, release-blocker, 1.11.0rc0-pick

#21964 Remove work pipelining
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
Labels: @tests-ok

#21895 [Core] Extract a common method to get predefined resource index
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
Labels: @tests-ok

#21963 [data] Serialize parquet piece metadata in batches to reduce overheads
  python/ray/data/datasource/parquet_datasource.py
Labels: @author-action-required

#21970 Deflake occasional deadlock in test_dataset.py::test_basic_actors[True]
  python/ray/data/dataset.py
  python/ray/data/impl/pipeline_executor.py
  python/ray/data/impl/stats.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_pipeline_nohang.py
Labels: @tests-ok

#21894 Revert "Revert "[Dataset] [DataFrame 2/n] Add pandas block format implementation (partial) (#20988) (#21661)"
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  python/ray/data/block.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/delegating_block_builder.py
  python/ray/data/impl/pandas_block.py
  python/ray/data/impl/simple_block.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required
