Repository ray-project/ray, pull requests merged in 2022-06, with the labels that each got.

#25251 [build] Fix the `install-bazel.sh`
  ci/build/test-wheels.sh
  ci/build/upload_build_info.sh
  ci/env/install-bazel.sh
  ci/env/install-minimal.sh
  ci/lint/bazel-format.sh
  ci/lint/copyright-format.sh
  ci/run/iwyu.sh
Labels: @author-action-required

#25331 [Deployment Graph] Remove _execute_impl and json serde code for DeploymentNode IR
  python/ray/serve/pipeline/deployment_function_node.py
  python/ray/serve/pipeline/deployment_method_node.py
  python/ray/serve/pipeline/deployment_node.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/pipeline/tests/test_deployment_node.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/pipeline/tests/test_json_serde.py
Labels: tests-ok, flaky-test

#25247 [core] Support generators for tasks with multiple return values
  doc/source/ray-core/tasks.rst
  doc/source/ray-core/tasks/patterns/generators.rst
  doc/source/ray-core/tasks/patterns/index.rst
  python/ray/_raylet.pyx
  python/ray/tests/BUILD
  python/ray/tests/test_generators.py
Labels: @author-action-required, core-api-change-approval-required

#25365 [Core] fix tsan issue in `GcsRpcClient`
  src/ray/rpc/gcs_server/gcs_rpc_client.h
Labels: tests-ok

#25422 [flakey] Deflakey test_ray_shutdown.py
  python/ray/tests/test_ray_shutdown.py
  src/ray/core_worker/core_worker.cc
Labels: @author-action-required

#25466 [Docs] Document Ray downscaling behavior
  doc/source/cluster/guide.rst
Labels: P1, docs

#24910 Add doc code owners
  .github/CODEOWNERS
Labels: docs

#25418 [Core] Export additional metrics for workers and Raylet memory
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/tests/test_reporter.py
  python/ray/autoscaler/aws/cloudwatch/example-cloudwatch-agent-config.json
Labels: tests-ok

#25492 [docs] Cleanup ray init docs
  doc/source/_static/css/custom.css
  doc/source/conf.py
  python/ray/worker.py
Labels: @author-action-required

#25473 [Docs] [Clusters] Fix issues in the overview part of Cluster Deployment Guide, and fix a typo
  doc/source/cluster/guide.rst
Labels: docs

#25027 Depend on uvicorn[standard] instead of uvicorn so that it pulls in uvloop
  python/requirements.txt
  python/setup.py
Labels: @author-action-required

#24463 [WIP][Tune] Custom resources per worker added to default_resource_request
  rllib/BUILD
  rllib/agents/trainer.py
  rllib/algorithms/apex_dqn/apex_dqn.py
  rllib/algorithms/impala/impala.py
  rllib/tests/test_custom_resource.py
Labels: P1

#25498 [docs] Fix mock objects in Ray Core docs
  python/ray/util/placement_group.py
  python/ray/worker.py
Labels: @author-action-required

#25475 [air/docs] Update documentation structure
  doc/source/_toc.yml
  doc/source/index.md
  doc/source/ray-air/examples/index.rst
  doc/source/ray-air/examples/rl_online_example.ipynb
  doc/source/ray-air/examples/tfx_tabular_train_to_serve.ipynb
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/user-guides.rst
  doc/source/ray-overview/index.md
Labels: @author-action-required

#25358 [Docs] Remove `$` from pip install instructions
  doc/source/rllib/index.rst
Labels: docs

#25148 Fix SciPy pinning
  python/requirements.txt
Labels: bug, dependencies, python, QS

#25562 [Jobs] [Test] Add integration tests to cover runtime_env inheritance with working_dir and with Tune
  dashboard/modules/job/tests/subprocess_driver_scripts/per_task_runtime_env.py
  dashboard/modules/job/tests/subprocess_driver_scripts/ray_tune_basic.py
  dashboard/modules/job/tests/subprocess_driver_scripts/ray_tune_dependency.py
  dashboard/modules/job/tests/test_http_job_server.py
Labels: tests-ok

#25568 [datasets] add `Dataset.randomize_block_order`
  doc/source/data/dataset-ml-preprocessing.rst
  python/ray/data/_internal/block_list.py
  python/ray/data/_internal/lazy_block_list.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: tests-ok

#25516 [Core] Push message to driver when a Raylet dies
  dashboard/agent.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/tests/test_dashboard.py
  python/ray/ray_constants.py
  python/ray/tests/test_failure_4.py
Labels: tests-ok

#25453 Fix outdated serve warning message for sync handle
  python/ray/serve/client.py
Labels: tests-ok

#25534 [AIR] Add `predict_pandas` implementation
  python/ray/air/BUILD
  python/ray/air/__init__.py
  python/ray/air/batch_predictor.py
  python/ray/air/constants.py
  python/ray/air/data_batch_type.py
  python/ray/air/predictor.py
  python/ray/air/preprocessor.py
  python/ray/air/tests/test_batch_predictor.py
  python/ray/air/tests/test_data_batch_conversion.py
  python/ray/air/tests/test_predictor.py
  python/ray/air/util/data_batch_conversion.py
Labels: @author-action-required

#25635 [Core][Nightly test] use smaller instance for scheduling tests
  release/benchmarks/scheduling.yaml
Labels: tests-ok

#25630 [Deployment Graph] Move files out of `pipeline` folder
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/serve/BUILD
  python/ray/serve/api.py
  python/ray/serve/deployment_function_node.py
  python/ray/serve/deployment_graph.py
  python/ray/serve/deployment_graph_build.py
  python/ray/serve/deployment_method_node.py
  python/ray/serve/deployment_node.py
  python/ray/serve/json_serde.py
  python/ray/serve/pipeline/api.py
  python/ray/serve/pipeline/conftest.py
  python/ray/serve/pipeline/constants.py
  python/ray/serve/pipeline/tests/resources/__init__.py
  python/ray/serve/tests/resources/__init__.py
  python/ray/serve/tests/resources/test_dags.py
  python/ray/serve/tests/resources/test_modules.py
  python/ray/serve/tests/test_deployment_graph_build.py
  python/ray/serve/tests/test_deployment_node.py
  python/ray/serve/tests/test_json_serde.py
  python/ray/serve/tests/test_model_wrappers.py
  python/ray/serve/tests/test_pipeline_dag.py
  python/ray/serve/tests/test_pipeline_dag_plot.py
  python/ray/serve/tests/test_pipeline_deployment_config.py
  python/ray/serve/tests/test_pipeline_handle_serde.py
  python/ray/serve/tests/test_pipeline_ingress_deployment.py
Labels: tests-ok

#25611 [rfc][doc] Add clarity to stability guidelines
  doc/source/_toc.yml
  doc/source/ray-contribute/getting-involved.rst
  doc/source/ray-contribute/stability.rst
  python/ray/util/annotations.py
Labels: @author-action-required

#25528 [Ray DAG] Add documentation in `more options` section
  doc/source/ray-core/more-topics.rst
  doc/source/ray-core/ray-dag.rst
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/worker.py
Labels: tests-ok

#25709 [tune/ci] Multinode support killing nodes in Ray client mode
  python/ray/autoscaler/_private/fake_multi_node/test_utils.py
  python/ray/tune/tests/test_multinode_sync.py
Labels: tests-ok

#25727 [air] update checkpoint.py to deal with metadata in conversion.
  python/ray/air/checkpoint.py
  python/ray/air/tests/test_checkpoints.py
Labels: tests-ok

#25706 [data] Fix stage fusion between equivalent resource args (fixes BatchPredictor)
  python/ray/air/tests/test_batch_predictor.py
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_optimize.py
Labels: tests-ok

#25705 [rfc] [data] SPREAD actor pool actors evenly across the cluster by default
  python/ray/data/_internal/compute.py
Labels: tests-ok

#25693 [air] Add streaming BatchPredictor support
  doc/source/ray-air/doc_code/air_key_concepts.py
  python/ray/air/batch_predictor.py
  python/ray/air/tests/test_batch_predictor.py
Labels: tests-ok

#24677 [Core/PG/Schedule 1/2]Optimize the scheduling performance of actors/tasks with PG specified only for gcs schedule
  BUILD.bazel
  python/ray/tests/test_placement_group.py
  src/ray/common/bundle_location_index.cc
  src/ray/common/bundle_location_index.h
  src/ray/common/bundle_spec.cc
  src/ray/common/bundle_spec.h
  src/ray/common/test/bundle_location_index_test.cc
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/policy/affinity_with_bundle_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/affinity_with_bundle_scheduling_policy.h
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_context.h
  src/ray/raylet/scheduling/policy/scheduling_options.h
Labels: @author-action-required

#25750 [air] remove fully_executed from Tune.
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/doc_code/air_ingest.py
  python/ray/tune/impl/dataset_execution_registry.py
  python/ray/tune/impl/out_of_band_serialize_dataset.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/impl/utils.py
Labels: air

#25734 [datasets] Avoid unnecessary metadata serialization in Datasets shuffle
  python/ray/data/_internal/push_based_shuffle.py
  python/ray/data/_internal/shuffle.py
  python/ray/data/_internal/shuffle_and_partition.py
  python/ray/data/_internal/sort.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_sort.py
Labels: @author-action-required

#25808 [serve][docs] Replaced term 'actor_init_options' with 'ray_actor_options' in documentation
  doc/source/serve/performance.md
Labels: serve, docs

#25659 [RuntimeEnv] Fixes spaces in paths causing failures on Windows
  python/ray/_private/runtime_env/context.py
Labels: tests-ok

#24622 [runtime env] Hide URI cache behind class
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/java_jars.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_plugin.py
  python/ray/tests/test_runtime_env_working_dir.py
Labels: tests-ok

#25091 [serve] Use soft constraint for pinning controller on head node
  python/ray/serve/api.py
  python/ray/serve/controller.py
  python/ray/serve/http_proxy.py
  python/ray/serve/http_state.py
  python/ray/serve/tests/test_http_state.py
  python/ray/serve/tests/test_util.py
  python/ray/serve/utils.py
Labels: tests-ok, @author-action-required

#25781 [CI] Print linkcheck summary only in linkcheck
  doc/source/custom_directives.py
Labels: tests-ok

#25785 [Usage Stats][Hotfix] Import usage reported from workers.
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: 1.13.1-pick

#25830 [Serve] [Docs] Remove references to namespaces in the Serve documentation
  doc/source/serve/deploying-serve.md
Labels: serve, docs

#25765 [Docs] Add a `py:obj` default role to Sphinx builds.
  doc/source/conf.py
Labels: tests-ok

#25821 [Datasets] Workaround for unserializable Arrow JSON ReadOptions.
  python/ray/data/__init__.py
  python/ray/data/_internal/arrow_serialization.py
  python/ray/data/dataset.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_formats.py
Labels: @author-action-required

#25532 [Ray DAG] Move `dag` project folder out of `experimental`
  .buildkite/pipeline.yml
  doc/source/ray-core/ray-dag.rst
  doc/source/serve/doc_code/deployment_graph_control_flow_based_on_user_inputs.py
  doc/source/serve/doc_code/deployment_graph_dag_http.py
  doc/source/serve/doc_code/deployment_graph_same_class_different_args.py
  doc/source/serve/doc_code/visualize_dag_during_deployment.py
  doc/source/serve/http-adapters.md
  python/ray/actor.py
  python/ray/dag/BUILD
  python/ray/dag/__init__.py
  python/ray/dag/class_node.py
  python/ray/dag/conftest.py
  python/ray/dag/constants.py
  python/ray/dag/dag_node.py
  python/ray/dag/format_utils.py
  python/ray/dag/function_node.py
  python/ray/dag/input_node.py
  python/ray/dag/py_obj_scanner.py
  python/ray/dag/tests/conftest.py
  python/ray/dag/tests/test_class_dag.py
  python/ray/dag/tests/test_function_dag.py
  python/ray/dag/tests/test_input_node.py
  python/ray/dag/tests/test_plot.py
  python/ray/dag/utils.py
  python/ray/dag/vis_utils.py
  python/ray/remote_function.py
  python/ray/serve/api.py
  python/ray/serve/dag.py
  python/ray/serve/deployment.py
  python/ray/serve/deployment_executor_node.py
  python/ray/serve/deployment_function_executor_node.py
  python/ray/serve/deployment_function_node.py
  python/ray/serve/deployment_graph.py
  python/ray/serve/deployment_graph_build.py
  python/ray/serve/deployment_method_executor_node.py
  python/ray/serve/deployment_method_node.py
  python/ray/serve/deployment_node.py
  python/ray/serve/json_serde.py
  python/ray/serve/tests/resources/test_dags.py
  python/ray/serve/tests/test_deployment_graph_autoscaling.py
  python/ray/serve/tests/test_deployment_graph_build.py
  python/ray/serve/tests/test_json_serde.py
  python/ray/serve/tests/test_pipeline_dag_plot.py
  python/ray/workflow/api.py
  python/ray/workflow/api.pyi
  python/ray/workflow/dag_to_workflow.py
  python/ray/workflow/tests/test_dag_to_workflow.py
  release/serve_tests/workloads/deployment_graph_long_chain.py
  release/serve_tests/workloads/deployment_graph_wide_ensemble.py
Labels: tests-ok

#25835 [macOS] Only cleanup directory after upload
  ci/build/upload_build_info.sh
Labels: tests-ok

#25825 [runtime env] Make all plugins return a `List` of URIs
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/java_jars.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_plugin.py
Labels: tests-ok

#23764 [Datasets] [Hotfix] Add ray_remote_args to read_text.
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#25454 [dataset] Use polars for sorting
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/__init__.py
  python/ray/data/_internal/arrow_ops/transform_polars.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/context.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_sort.py
  python/requirements.txt
  release/nightly_tests/dataset/sort.py
Labels: tests-ok

#25336 [datasets] Use generators for merge stage in push-based shuffle
  python/ray/data/_internal/push_based_shuffle.py
  python/ray/data/_internal/stats.py
  python/ray/data/block.py
  python/ray/data/tests/test_stats.py
  python/ray/tests/test_basic_5.py
Labels: tests-ok

#25795 [dataset] Pipeline task submission during reduce stage in push-based shuffle
  python/ray/data/_internal/push_based_shuffle.py
  python/ray/data/_internal/shuffle.py
  python/ray/data/_internal/shuffle_and_partition.py
  python/ray/data/_internal/sort.py
  python/ray/data/context.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_sort.py
Labels: @author-action-required

#25803 [data] Make ActorPoolStrategy kill pool of actors if exception is raised
  python/ray/data/_internal/compute.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#25354 [Docs] Remove RL Summit announcement from RLlib docs
  doc/source/_includes/rllib/announcement_bottom.rst
Labels: docs

#25648 [Core] update protobuf to 3.19.4
  bazel/ray_deps_setup.bzl
  python/ray/tests/BUILD
  python/ray/tests/test_protobuf_compatibility.py
  python/requirements.txt
  release/requirements.txt
  release/requirements_buildkite.txt
Labels: tests-ok

#25900 [tune] catch pyarrow 8.0.0 error
  python/ray/air/_internal/remote_storage.py
Labels: tests-ok

#25899 [RLlib]: Off-Policy Evaluation fixes
  rllib/evaluation/metrics.py
  rllib/offline/estimators/direct_method.py
  rllib/offline/estimators/doubly_robust.py
  rllib/offline/estimators/fqe_torch_model.py
  rllib/offline/estimators/importance_sampling.py
  rllib/offline/estimators/off_policy_estimator.py
  rllib/offline/estimators/qreg_torch_model.py
  rllib/offline/estimators/tests/test_ope.py
  rllib/offline/estimators/weighted_importance_sampling.py
Labels: rllib, rllib-offline-rl

#24102 [Tune] W&B logging - handle tuples in configs
  python/ray/tune/integration/wandb.py
Labels: stale

#24822 [Datasets] Add file-extension-based path filter for file-based datasources.
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/csv_datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/json_datasource.py
  python/ray/data/datasource/numpy_datasource.py
  python/ray/data/datasource/parquet_base_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_formats.py
Labels: @author-action-required

#25788 [runtime env] Use async internal kv in package download and plugins
  dashboard/agent.py
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/java_jars.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/tests/test_runtime_env_working_dir.py
Labels: tests-ok

#25967 [air] RunConfig.`failure` --> `failure_config`
  python/ray/air/config.py
  python/ray/tune/impl/tuner_internal.py
Labels: air

#25646 [Serve][Doc] Autoscaling
  doc/source/_toc.yml
  doc/source/serve/autoscaling.md
  doc/source/serve/managing-deployments.md
  doc/source/serve/user-guide.md
Labels: @author-action-required

#26001 [runtime env] remove unused runtime env uris from protobuf
  python/ray/runtime_env.py
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/runtime_env_common.proto
Labels: tests-ok

#26004 [runtime env] move 'eager_intall' to 'config'
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/validation.py
  python/ray/_private/utils.py
  python/ray/runtime_env.py
  python/ray/tests/test_runtime_env_complicated.py
  src/ray/common/task/task_spec.cc
  src/ray/protobuf/runtime_env_common.proto
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool_test.cc
Labels: tests-ok, core-api-change-approval-required

#25842 [Usage stats] Record Ray native library usage from a home temp folder
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: 1.13.1-pick

#25894 [Core][State Observability] Get API using List endpoints + filtering on ids
  dashboard/modules/state/state_head.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_state_api.py
Labels: tests-ok

#26077 [runtime env] plugin refactor[1/n]
  dashboard/modules/runtime_env/runtime_env_agent.py
  python/ray/_private/runtime_env/constants.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/runtime_env.py
  python/ray/tests/conftest.py
  python/ray/tests/test_placement_group_4.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_plugin.py
Labels: tests-ok

#25889 [ci/release] Support running tests on staging
  release/BUILD
  release/ray_release/anyscale_util.py
  release/ray_release/aws.py
  release/ray_release/buildkite/step.py
  release/ray_release/cluster_manager/cluster_manager.py
  release/ray_release/command_runner/job_runner.py
  release/ray_release/command_runner/sdk_runner.py
  release/ray_release/config.py
  release/ray_release/env.py
  release/ray_release/environments/prod.env
  release/ray_release/environments/staging.env
  release/ray_release/file_manager/job_file_manager.py
  release/ray_release/file_manager/session_controller.py
  release/ray_release/job_manager.py
  release/ray_release/reporter/legacy_rds.py
  release/ray_release/schema.json
  release/ray_release/scripts/run_release_test.py
  release/ray_release/tests/test_env.py
  release/ray_release/util.py
  release/release_tests.yaml
Labels: do-not-merge

#25861 [serve] Set status message if deployment pending for too long
  python/ray/serve/deployment_state.py
  python/ray/serve/tests/test_standalone.py
Labels: enhancement, serve

#25983 [runtime env] [CI] Use `wait_for_condition` in working_dir GC test instead of hardcoded sleep
  python/ray/tests/test_runtime_env_working_dir_3.py
Labels: tests-ok

#26166 [docs] move troubleshooting section to source development page
  doc/source/ray-contribute/development.rst
  doc/source/ray-overview/installation.rst
Labels: tests-ok

#26090 [data] randomize_block_order() not compatible with stage fusion
  python/ray/data/_internal/plan.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_optimize.py
Labels: tests-ok

#24842 [Core][Enable gcs scheduler 3/n] integrate placement group with gcs scheduler
  python/ray/tests/test_metrics_agent.py
  src/ray/common/bundle_spec.cc
  src/ray/common/bundle_spec.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_resource_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: @author-action-required
