Repository ray-project/ray, pull requests merged in 2022-09, with the labels that each got.

#28225 [tune] Run SigOpt tests in CI
  .buildkite/pipeline.ml.yml
  ci/env/setup_credentials.py
  python/ray/tune/examples/sigopt_example.py
  python/ray/tune/search/sigopt/__init__.py
  python/ray/tune/search/sigopt/sigopt_search.py
  python/ray/tune/tests/test_tune_restore_warm_start.py
Labels: do-not-merge

#28246 [serve] Add additional features to DAG visualization with Gradio
  python/ray/dag/input_node.py
  python/ray/experimental/gradio_utils.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/deployment_function_executor_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/deployment_method_executor_node.py
  python/ray/serve/experimental/gradio_visualize_graph.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/test_gradio_visualization.py
Labels: serve

#27020 [Ray Job] Add support for Windows OS to JobSupervisor
  dashboard/modules/job/job_manager.py
Labels: tests-ok

#28026 [Doc] [runtime env] Clarify zip requirements for remote URIs
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/packaging.py
Labels: tests-ok

#27906 [runtime env][bug fix] lock the minimum version of virtualenv to 20.0.24
  python/requirements.txt
  python/setup.py
Labels: tests-ok

#28342 [Tune] [PB2] Correct pb2's beta_t parameter implementation
  python/ray/tune/schedulers/pb2_utils.py
Labels: tune

#28375 [RLlib] Reinstate some env tests.
  rllib/BUILD
  rllib/env/tests/test_multi_agent_env.py
  rllib/env/tests/test_multi_agent_pendulum.py
  rllib/tests/test_multi_agent_env.py
  rllib/tests/test_vector_env.py
Labels: tests-ok

#28325 [RLlib; AIR; Tune] Replace all remaining `tune.run()` with `tune.Tuner(...).fit()`.
  rllib/algorithms/a2c/a2c.py
  rllib/algorithms/a3c/a3c.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/alpha_star/alpha_star.py
  rllib/algorithms/alpha_zero/alpha_zero.py
  rllib/algorithms/apex_ddpg/apex_ddpg.py
  rllib/algorithms/apex_dqn/apex_dqn.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/ars/ars.py
  rllib/algorithms/bc/bc.py
  rllib/algorithms/ddpg/ddpg.py
  rllib/algorithms/ddppo/ddppo.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/dreamer/dreamer.py
  rllib/algorithms/es/es.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/maddpg/maddpg.py
  rllib/algorithms/maml/maml.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/mbmpo/mbmpo.py
  rllib/algorithms/pg/pg.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/qmix/qmix.py
  rllib/algorithms/r2d2/r2d2.py
  rllib/algorithms/simple_q/simple_q.py
  rllib/algorithms/slateq/slateq.py
  rllib/algorithms/td3/td3.py
  rllib/examples/custom_experiment.py
  rllib/examples/restore_1_of_n_agents_from_checkpoint.py
  rllib/examples/sumo_env_local.py
  rllib/models/tests/test_attention_nets.py
  rllib/models/tests/test_lstms.py
  rllib/tests/git_bisect/debug_learning_failure_git_bisect.py
  rllib/tests/test_custom_resource.py
  rllib/tests/test_dnc.py
  rllib/tests/test_eager_support.py
  rllib/tests/test_gpus.py
  rllib/tests/test_placement_groups.py
  rllib/tests/test_ray_client.py
  rllib/tests/test_rllib_train_and_evaluate.py
  rllib/utils/error.py
  rllib/utils/exploration/tests/test_curiosity.py
  rllib/utils/test_utils.py
Labels: @author-action-required

#27999 [Serve] [CI] Deflake `test_standalone.py` by replacing `list_named_actors` with new State API
  python/ray/serve/tests/test_standalone.py
Labels: tests-ok

#28212 [Doc] [Build] Add M1 Mac conditional dependency for tensorflow-macos
  doc/requirements-doc.txt
Labels: tests-ok, dependencies, docs, build

#28104 [Job Submission][CPP Worker] introduce CPP job submission
  cpp/BUILD.bazel
  cpp/src/ray/config_internal.cc
  cpp/src/ray/config_internal.h
  cpp/src/ray/test/examples/simple_job.cc
  cpp/src/ray/util/process_helper.cc
  cpp/test_submit_cpp_job.py
Labels: @author-action-required

#28416 [core] Remove python/ray/core from isort blacklist and run formatter
  .isort.cfg
Labels: tests-ok

#28444 [core] Raise an error on empty placement group creation
  python/ray/tests/test_placement_group.py
  python/ray/util/placement_group.py
Labels: @author-action-required

#28441 [ci/release] Fix release/ray_release/setup.py
  ci/pipeline/determine_tests_to_run.py
  release/setup.py
Labels: @author-action-required

#28490 [Telemetry][Kuberentes] Distinguish Kubernetes deployment stacks
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
  python/ray/ray_operator/operator_utils.py
  python/ray/tests/test_k8s_operator_unit_tests.py
  python/ray/tests/test_usage_stats.py
Labels: @author-action-required

#28535 [CI] [Hackathon] Add dockerfiles for decoupled bootstrapping/Library tests
  ci/docker/Dockerfile.base
  ci/docker/Dockerfile.build
  ci/docker/Dockerfile.gpu
  ci/docker/Dockerfile.ml
  ci/docker/Dockerfile.test
  ci/env/install-dependencies.sh
  doc/source/ray-core/objects/object-spilling.rst
  doc/source/tune/api_docs/stoppers.rst
  python/ray/_private/ray_constants.py
  python/ray/_private/resource_spec.py
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
  python/ray/_private/utils.py
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/constants.py
  python/ray/autoscaler/_private/fake_multi_node/example.yaml
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/autoscaler/_private/util.py
  python/ray/data/datasource/partitioning.py
  python/ray/data/read_api.py
  python/ray/ray_operator/operator_utils.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_k8s_operator_unit_tests.py
  python/ray/tests/test_metrics.py
  python/ray/tests/test_resource_demand_scheduler.py
  python/ray/tests/test_usage_stats.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/search/hyperopt/hyperopt_search.py
  python/ray/tune/stopper/stopper.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_sample.py
  python/ray/tune/tests/test_syncer_callback.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/tuner.py
  python/ray/tune/utils/resource_updater.py
  python/ray/util/placement_group.py
  python/requirements.txt
  release/requirements.txt
  release/requirements_buildkite.txt
  rllib/algorithms/dqn/dqn_tf_policy.py
  rllib/algorithms/dqn/tests/test_dqn.py
  rllib/algorithms/simple_q/simple_q_tf_policy.py
  rllib/evaluation/worker_set.py
  rllib/examples/custom_train_fn.py
  rllib/tests/test_worker_failures.py
Labels: do-not-merge

#28364 [Docs/AIR] Various fixes for AIR examples
  doc/source/ray-air/examples/feast_example.ipynb
  doc/source/ray-air/examples/rl_offline_example.ipynb
  doc/source/ray-air/examples/rl_online_example.ipynb
  doc/source/ray-air/examples/rl_serving_example.ipynb
Labels: @external-author-action-required

#28459 Add a simple `ray_tasks` metric for tracking active and completed tasks.
  python/ray/_private/prometheus_exporter.py
  python/ray/_private/test_utils.py
  python/ray/tests/BUILD
  python/ray/tests/test_task_metrics.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
  src/ray/stats/tag_defs.cc
  src/ray/stats/tag_defs.h
Labels: @author-action-required

#28431 [Datasets] Add `Optional` hint to `compute` parameter
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
Labels: tests-ok

#28187 [Tune] Fix and optimize sample search algorithm quantization logic
  doc/source/tune/api_docs/search_space.rst
  doc/source/tune/doc_code/key_concepts.py
  python/ray/tune/search/sample.py
  python/ray/tune/tests/test_sample.py
Labels: @external-author-action-required

#25844 Remove pins for some Python dependencies
  python/requirements.txt
  python/requirements/ml/requirements_rllib.txt
  python/requirements/ml/requirements_tune.txt
  python/setup.py
Labels: python

#28566 [RLlib] Add `before_sub_environment_reset` callback.
  doc/source/rllib/rllib-training.rst
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/callbacks.py
  rllib/algorithms/tests/test_callbacks.py
  rllib/evaluation/env_runner_v2.py
  rllib/evaluation/sampler.py
Labels: tests-ok

#28286 Export default configurations for grafana and prometheus
  dashboard/modules/metrics/__init__.py
  dashboard/modules/metrics/export/grafana/grafana.ini
  dashboard/modules/metrics/export/grafana/provisioning/dashboards/default.yml
  dashboard/modules/metrics/export/grafana/provisioning/dashboards/default_grafana_dashboard.json
  dashboard/modules/metrics/export/prometheus/prometheus.yml
  dashboard/modules/metrics/grafana_datasource_template.py
  dashboard/modules/metrics/metrics_head.py
  doc/source/cluster/running-applications/monitoring-and-observability.rst
  doc/source/ray-observability/ray-metrics.rst
  python/ray/tests/BUILD
  python/ray/tests/test_metrics_head.py
  python/setup.py
Labels: @author-action-required

#28655 [metrics] Add job_id label for all core worker metrics
  python/ray/tests/test_task_metrics.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/raylet/worker_pool.cc
  src/ray/stats/tag_defs.cc
  src/ray/stats/tag_defs.h
Labels: tests-ok

#28291 [core] Support generators to allow tasks to return a dynamic number of objects
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  doc/source/ray-core/doc_code/generator.py
  doc/source/ray-core/patterns/generators.rst
  doc/source/ray-core/tasks.rst
  doc/source/ray-core/tasks/generators.rst
  python/ray/__init__.py
  python/ray/_private/ray_option_utils.py
  python/ray/_private/serialization.py
  python/ray/_private/worker.py
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_generators.py
  python/ray/tests/test_reference_counting_2.py
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/ownership_based_object_directory.h
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/node_manager.proto
  src/ray/protobuf/pubsub.proto
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: tests-ok, core-interface-change-approval-required

#28511 [Tune] [PBT] Maintain consistent `Trial`/`TrialRunner` state when pausing and resuming trial
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
Labels: bug, tune

#28662 [docs] configurable ecosystem gallery
  doc/.gitignore
  doc/source/conf.py
  doc/source/custom_directives.py
  doc/source/ray-overview/eco-gallery.yml
  doc/source/ray-overview/ray-libraries.rst
Labels: enhancement, docs

#28677 [docs] Add basic parallel execution guide for Tune and cleanup order of guides
  doc/source/_toc.yml
  doc/source/tune/doc_code/tune.py
  doc/source/tune/tutorials/overview.rst
  doc/source/tune/tutorials/tune-output.rst
  doc/source/tune/tutorials/tune-run.rst
  doc/source/tune/tutorials/tune-stopping.rst
Labels: tests-ok

#27785 [RLlib] Better error message for partial space mismatch (Dict|Tuple) between env-returned values and given action/obs space.
  rllib/policy/torch_policy.py
  rllib/utils/pre_checks/env.py
  rllib/utils/tests/test_check_env.py
Labels: tests-ok, @author-action-required

#28745 [docs] add preprocessor code to quick start
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-overview/index.md
Labels: tests-ok

#28466 [core] propagate oom exception when worker is killed due to oom
  python/ray/_private/serialization.py
  python/ray/_private/test_utils.py
  python/ray/exceptions.py
  python/ray/tests/test_failure_4.py
  python/ray/tests/test_memory_pressure.py
  src/mock/ray/raylet/node_manager.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/common/memory_monitor.cc
  src/ray/common/ray_config_def.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: tests-ok

#28713 [core] [release] added wait_for_nodes for stress_test_many_tasks
  release/nightly_tests/stress_tests/test_many_tasks.py
  release/release_tests.yaml
Labels: @author-action-required

#28682 [Datasets] Use generators for block splitting
  python/ray/data/_internal/compute.py
  python/ray/data/tests/test_size_estimation.py
Labels: tests-ok

#28623 Widening range of grpcio versions allowed.
  python/ray/tests/BUILD
  python/ray/tests/test_runtime_env_working_dir_3.py
  python/ray/tests/test_scheduling.py
  python/requirements.txt
  python/setup.py
Labels: @author-action-required, core

#28637 [RLlib] `Algorithm.add_policy()` should alternatively accept an already instantiated policy object.
  rllib/algorithms/algorithm.py
  rllib/algorithms/tests/test_algorithm.py
  rllib/connectors/util.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/worker_set.py
  rllib/policy/policy_map.py
Labels: tests-ok

#28624 [metrics] Add breakdowns for when tasks may be blocked during scheduling and in user code
  python/ray/experimental/state/common.py
  python/ray/experimental/state/custom_types.py
  python/ray/tests/test_memstat.py
  python/ray/tests/test_reconstruction_2.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_state_api_summary.py
  python/ray/tests/test_task_metrics.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/protobuf/common.proto
  src/ray/stats/metric_defs.cc
Labels: tests-ok

#28746 [util] Add ray/util/counter.h to clean up metrics tracking code
  BUILD.bazel
  src/ray/util/counter_map.h
  src/ray/util/counter_test.cc
Labels: tests-ok

#28782 [Core][Dependencies] ensure all unbounded dependencies are tested
  ci/env/install-core-prerelease-dependencies.sh
  python/requirements.txt
  python/setup.py
Labels: tests-ok

#28661 [core] Make gRPC request's life cycle aligned with the handler function.
  src/mock/ray/core_worker/core_worker.h
  src/mock/ray/gcs/gcs_server/gcs_job_manager.h
  src/mock/ray/gcs/gcs_server/gcs_node_manager.h
  src/mock/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/mock/ray/gcs/gcs_server/gcs_resource_manager.h
  src/mock/ray/gcs/gcs_server/gcs_worker_manager.h
  src/mock/ray/raylet/node_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.cc
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/pubsub_handler.cc
  src/ray/gcs/gcs_server/pubsub_handler.h
  src/ray/gcs/gcs_server/runtime_env_handler.cc
  src/ray/gcs/gcs_server/runtime_env_handler.h
  src/ray/gcs/gcs_server/stats_handler_impl.cc
  src/ray/gcs/gcs_server/stats_handler_impl.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/agent_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/rpc/agent_manager/agent_manager_server.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
  src/ray/rpc/grpc_server.h
  src/ray/rpc/node_manager/node_manager_server.h
  src/ray/rpc/object_manager/object_manager_server.h
  src/ray/rpc/server_call.h
  src/ray/rpc/test/grpc_server_client_test.cc
Labels: @author-action-required

#28714 [core] add oom-specific retry to tasks and actors
  python/ray/_private/serialization.py
  python/ray/tests/test_memory_pressure.py
  src/mock/ray/core_worker/task_manager.h
  src/ray/common/ray_config_def.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/raylet/node_manager.cc
Labels: tests-ok

#28845 [RLlib] Tests for connectors are not easily identifiable as such
  rllib/BUILD
Labels: @author-action-required, do-not-merge

#28589 [RuntimeEnv, Windows] Fix working_dir, pip & conda for windows
  python/ray/_private/runtime_env/conda_utils.py
  python/ray/_private/runtime_env/context.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/_private/test_utils.py
  python/ray/tests/test_runtime_env_2.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
  python/ray/tests/test_runtime_env_conda_and_pip_3.py
  python/ray/tests/test_runtime_env_conda_and_pip_4.py
  python/ray/tests/test_runtime_env_conda_and_pip_5.py
  python/ray/tests/test_runtime_env_plugin.py
  python/ray/tests/test_runtime_env_validation.py
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_runtime_env_working_dir_2.py
  python/ray/tests/test_runtime_env_working_dir_3.py
  python/ray/tests/test_runtime_env_working_dir_remote_uri.py
Labels: tests-ok

#28418 [AIR][Numpy] Add numpy narrow waist to `Preprocessor` and `BatchMapper`
  python/ray/air/_internal/remote_storage.py
  python/ray/air/result.py
  python/ray/air/tests/test_data_batch_conversion.py
  python/ray/air/tests/test_dataset_config.py
  python/ray/air/util/data_batch_conversion.py
  python/ray/air/util/transform_pyarrow.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/preprocessor.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/tests/test_batch_mapper.py
  python/ray/data/tests/test_preprocessors.py
Labels: tests-ok, air, air-numpy

#28724 [Datasets] Add read benchmark for images
  release/nightly_tests/dataset/read_benchmark.py
  release/nightly_tests/dataset/single_node_benchmark_compute.yaml
  release/release_tests.yaml
Labels: tests-ok

#28864 [core] Dynamic generators that error return partial ObjectRefs followed by exception ObjectRef
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  doc/source/ray-core/doc_code/generator.py
  doc/source/ray-core/tasks/generators.rst
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_generators.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
Labels: tests-ok

#28509 [Tune] [PBT] Ensure that exploited in-memory checkpoint is used by trial
  python/ray/air/_internal/checkpoint_manager.py
  python/ray/tune/execution/checkpoint_manager.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/tests/test_trial_scheduler.py
Labels: tune
