Repository ray-project/ray, pull requests merged in 2022-04, with the labels that each got.

#23584 Remove predefined resources vector in ResourceRequest
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/scheduling/cluster_resource_data.h
  src/ray/raylet/scheduling/resource_request_test.cc
Labels: @author-action-required

#23562 [Dashboard] fix iterating over GPU processes
  dashboard/datacenter.py
Labels: @tests-ok

#23647 Remove unused ObjectDirectory::LookupLocations()
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/ownership_based_object_directory.h
Labels: @tests-ok

#23546 [core] Add metrics for disk and network I/O
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/tests/test_reporter.py
  src/ray/object_manager/common.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: @tests-ok

#23708 [Datasets] Disallow callable classes for task compute strategy.
  python/ray/data/dataset.py
  python/ray/data/impl/compute.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#23416 Uniformly distributed tasks among actors to utilize full concurrency
  python/ray/tests/test_multiprocessing.py
  python/ray/util/multiprocessing/pool.py
Labels: triage, QS

#23524 Split test_advanced_n.py and enabled cluster tests
  python/ray/tests/BUILD
  python/ray/tests/test_advanced.py
  python/ray/tests/test_advanced_2.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_advanced_4.py
  python/ray/tests/test_advanced_5.py
  python/ray/tests/test_advanced_6.py
  python/ray/tests/test_advanced_7.py
  python/ray/tests/test_advanced_8.py
  python/ray/tests/test_advanced_9.py
Labels: windows, testing

#23350 [Core] Placement Group: Fix Flakey Test placement_group_test_5 and Typo
  python/ray/tests/test_placement_group_5.py
  src/ray/raylet/scheduling/cluster_resource_scheduler_2_test.cc
Labels: bug

#23614 [datasets] Unify Datasets primitives on a common shuffle op
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/fast_repartition.py
  python/ray/data/impl/shuffle.py
  python/ray/data/impl/sort.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_stats.py
Labels: @author-action-required

#23679 [Test] Use spot instances for chaos tests.
  release/nightly_tests/chaos_test/compute_template.yaml
Labels: @author-action-required

#23508 [Release 1.12.0] Add release logs for 1.12.0rc1
  release/release_logs/1.12.0/benchmarks/many_actors.json
  release/release_logs/1.12.0/benchmarks/many_nodes.json
  release/release_logs/1.12.0/benchmarks/many_pgs.json
  release/release_logs/1.12.0/benchmarks/many_tasks.json
  release/release_logs/1.12.0/microbenchmark.json
  release/release_logs/1.12.0/scalability/object_store.json
  release/release_logs/1.12.0/scalability/single_node.json
  release/release_logs/1.12.0/stress_tests/stress_test_dead_actors.json
  release/release_logs/1.12.0/stress_tests/stress_test_many_tasks.json
  release/release_logs/1.12.0/stress_tests/stress_test_placement_group.json
Labels: release-blocker

#23628 [scheduler] Refactor scheduling policy interface
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_2_test.cc
  src/ray/raylet/scheduling/policy/bundle_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/bundle_scheduling_policy.h
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_context.h
  src/ray/raylet/scheduling/policy/scheduling_options.h
  src/ray/raylet/scheduling/policy/scheduling_policy.h
Labels: do-not-merge

#23777 [rllib] Clarify how MultiDiscrete is encoded
  doc/source/rllib/rllib-models.rst
Labels: rllib

#23705 Cherry pick pin gym dependency
  ci/asan_tests/ray-project/requirements.txt
  ci/travis/install-dependencies.sh
  docker/ray-ml/Dockerfile
  python/requirements.txt
  python/requirements/ml/requirements_dl.txt
  python/requirements/ml/requirements_rllib.txt
  python/requirements/ml/requirements_tune.txt
  python/requirements_ml_docker.txt
  release/long_running_distributed_tests/app_config.yaml
  release/long_running_tests/app_config.yaml
  release/long_running_tests/app_config_np.yaml
  release/rllib_tests/app_config.yaml
  release/tune_tests/cloud_tests/app_config.yaml
  release/tune_tests/cloud_tests/app_config_ml.yaml
Labels: 1.11.1-pick

#23795 [CI] Fix dashboard
  dashboard/client/package.json
Labels: 1.11.1-pick

#23776 [ci] Pin prometheus_client to fix current test outages (#23749)
  ci/asan_tests/ray-project/requirements.txt
  python/requirements.txt
  python/requirements/requirements_default.txt
  python/setup.py
Labels: 1.11.1-pick

#23806 Update ray version from 1.12.0rc1 to 1.12.0
  build-docker.sh
  java/api/pom_template.xml
  java/performance_test/pom_template.xml
  java/pom.xml
  java/runtime/pom_template.xml
  java/serve/pom_template.xml
  java/test/pom_template.xml
  python/ray/__init__.py
  release/ray_release/tests/test_wheels.py
  src/ray/common/constants.h
Labels: release-blocker

#23754 [GCS][Storage unification 1/n] store index in memory instead of storage
  src/mock/ray/gcs/store_client/store_client.h
  src/ray/gcs/gcs_server/gcs_init_data.cc
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_table_storage_test_base.h
  src/ray/gcs/store_client/in_memory_store_client.cc
  src/ray/gcs/store_client/in_memory_store_client.h
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/redis_store_client.h
  src/ray/gcs/store_client/store_client.h
  src/ray/gcs/store_client/test/in_memory_store_client_test.cc
  src/ray/gcs/store_client/test/redis_store_client_test.cc
  src/ray/gcs/store_client/test/store_client_test_base.h
Labels: tests-ok

#23836 Fix coreworker test
  python/ray/train/tests/test_callbacks.py
  python/ray/util/ml_utils/mlflow.py
  python/ray/util/ml_utils/tests/test_mlflow.py
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/mock_worker.cc
Labels: 1.11.1-pick

#15412 [RLlib] Memory leak finding toolset using tracemalloc + CI/nightly memory leak tests.
  .buildkite/pipeline.ml.yml
  rllib/BUILD
  rllib/agents/ddpg/tests/test_ddpg.py
  rllib/agents/ddpg/tests/test_td3.py
  rllib/agents/impala/vtrace_tf.py
  rllib/agents/tests/test_memory_leaks.py
  rllib/env/multi_agent_env.py
  rllib/env/vector_env.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/tests/test_rollout_worker.py
  rllib/examples/eager_execution.py
  rllib/examples/env/memory_leaking_env.py
  rllib/examples/env/multi_agent.py
  rllib/examples/env/random_env.py
  rllib/examples/policy/memory_leaking_policy.py
  rllib/examples/policy/random_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/policy/tf_policy.py
  rllib/tests/test_timesteps.py
  rllib/tuned_examples/a3c/memory-leak-test-a3c.yaml
  rllib/tuned_examples/ddpg/memory-leak-test-ddpg.yaml
  rllib/tuned_examples/dqn/memory-leak-test-dqn.yaml
  rllib/tuned_examples/impala/memory-leak-test-impala.yaml
  rllib/tuned_examples/ppo/memory-leak-test-appo.yaml
  rllib/tuned_examples/ppo/memory-leak-test-ppo.yaml
  rllib/tuned_examples/sac/memory-leak-test-sac.yaml
  rllib/utils/debug/__init__.py
  rllib/utils/debug/deterministic.py
  rllib/utils/debug/memory.py
  rllib/utils/debug/summary.py
  rllib/utils/pre_checks/env.py
  rllib/utils/test_utils.py
  rllib/utils/tests/run_memory_leak_tests.py
Labels: tests-ok

#23871 [Datasets] Make `from_numpy()` more user-friendly.
  doc/source/data/package-ref.rst
  python/ray/data/__init__.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_formats.py
Labels: @author-action-required

#23381 Node affinity scheduling strategy
  BUILD.bazel
  doc/source/ray-core/actors/scheduling.rst
  doc/source/ray-core/tasks/scheduling.rst
  python/ray/_private/ray_option_utils.py
  python/ray/_raylet.pyx
  python/ray/exceptions.py
  python/ray/includes/common.pxd
  python/ray/serialization.py
  python/ray/tests/BUILD
  python/ray/tests/test_scheduling_2.py
  python/ray/util/scheduling_strategies.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/test/task_spec_test.cc
  src/ray/core_worker/lease_policy.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/lease_policy_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/composite_scheduling_policy.h
  src/ray/raylet/scheduling/policy/node_affinity_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/node_affinity_scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_options.h
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
Labels: @author-action-required, do-not-merge

#23808 [air/wip] Add batch predictor class
  doc/source/ray-air/getting-started.rst
  python/ray/ml/batch_predictor.py
  python/ray/ml/examples/lightgbm_example.py
  python/ray/ml/examples/pytorch/torch_linear_dataset_example.py
  python/ray/ml/examples/tf/tensorflow_linear_dataset_example.py
  python/ray/ml/examples/xgboost_example.py
  python/ray/ml/tests/test_predictor.py
Labels: @author-action-required

#23370 [air] Move storage handling to pyarrow.fs.FileSystem
  python/ray/data/impl/util.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_dataset.py
  python/ray/ml/checkpoint.py
  python/ray/ml/tests/test_checkpoints.py
  python/ray/ml/tests/utils.py
  python/ray/ml/utils/remote_storage.py
  python/ray/tune/cloud.py
  python/ray/tune/sync_client.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_cloud.py
  python/ray/tune/tune.py
  python/ray/tune/utils/util.py
  python/ray/util/ml_utils/cloud.py
  python/requirements.txt
  python/requirements/ml/requirements_upstream.txt
  python/setup.py
  release/tune_tests/cloud_tests/app_config.yaml
  release/tune_tests/cloud_tests/app_config_ml.yaml
  release/tune_tests/scalability_tests/app_config.yaml
  release/tune_tests/scalability_tests/app_config_data.yaml
Labels: tests-ok

#23821 [Datasets] [Out-of-Band Serialization: 1/3] Refactor `LazyBlockList`.
  python/ray/data/dataset.py
  python/ray/data/impl/block_list.py
  python/ray/data/impl/lazy_block_list.py
  python/ray/data/impl/plan.py
  python/ray/data/impl/stats.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_optimize.py
Labels: @author-action-required

#23792 [Doc] [runtime env] [Serve] Update serve pip runtime_env doc
  doc/source/serve/core-apis.rst
  python/ray/serve/examples/doc/conda_env.py
Labels: tests-ok

#23922 [Core] Fix in-container memory limit fetching for cgroups v2
  python/ray/_private/utils.py
  python/ray/tests/test_advanced_8.py
Labels: @author-action-required

#23884 [Core] Add metadata to ray.remote keywords
  python/ray/_private/ray_option_utils.py
  python/ray/tests/test_basic.py
  python/ray/worker.py
Labels: @author-action-required

#23959 [linter] fix broken link in rllib examples
  doc/source/rllib/rllib-examples.rst
Labels: tests-ok

#23382 [Core] Add a utility to check GCS / Ray cluster health
  BUILD.bazel
  dashboard/head.py
  dashboard/modules/log/tests/test_log.py
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/utils.py
  python/ray/node.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_advanced_4.py
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.cc
  src/ray/gcs/gcs_server/gcs_heartbeat_manager.h
  src/ray/protobuf/gcs_service.proto
Labels: tests-ok

#23939 [GCS] Use gRPC instead of socket for GCS client health check
  src/ray/common/network_util.cc
  src/ray/common/network_util.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
Labels: tests-ok

#23996 [Release] Fix XGBoost Golden Notebook Tests
  release/golden_notebook_tests/dask_xgboost_app_config.yaml
  release/golden_notebook_tests/modin_xgboost_app_config.yaml
Labels: tests-ok

#23889 [AIR] Add Scaling Config validation
  python/ray/ml/config.py
  python/ray/ml/tests/test_api.py
  python/ray/ml/tests/test_trainer.py
  python/ray/ml/train/data_parallel_trainer.py
  python/ray/ml/train/gbdt_trainer.py
  python/ray/ml/trainer.py
  python/ray/ml/utils/config.py
  python/ray/tune/tests/test_tuner.py
Labels: @author-action-required

#23995 [Ray client] use `SimpleQueue` on Python 3.7 and newer in async `dataclient`
  python/ray/util/client/dataclient.py
Labels: tests-ok

#23984 Clean up deployment suffixes between pipeline build() calls
  python/ray/serve/pipeline/api.py
  python/ray/serve/pipeline/generate.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/pipeline/tests/test_json_serde.py
  python/ray/serve/tests/conftest.py
Labels: @author-action-required

#23985 [Pubsub] reduce memory usage for channels that do not require total memory cap
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/pubsub/publisher.cc
  src/ray/pubsub/publisher.h
  src/ray/pubsub/test/publisher_test.cc
Labels: tests-ok

#23223 Increase register timeout seconds
  src/ray/common/ray_config_def.h
Labels: QS

#24042 [Bugfix] fix invalid excluding of Black
  ci/lint/format.sh
  python/ray/_private/thirdparty/pathspec/__init__.py
  python/ray/_private/thirdparty/pathspec/compat.py
  python/ray/_private/thirdparty/pathspec/pathspec.py
  python/ray/_private/thirdparty/pathspec/pattern.py
  python/ray/_private/thirdparty/pathspec/patterns/gitwildmatch.py
  python/ray/_private/thirdparty/pathspec/util.py
Labels: @author-action-required

#23580 [AIR] Add distributed `torch_geometric` example
  python/ray/ml/BUILD
  python/ray/ml/examples/pytorch_geometric/__init__.py
  python/ray/ml/examples/pytorch_geometric/distributed_sage_example.py
  python/ray/train/torch.py
  python/requirements/ml/requirements_dl.txt
  python/requirements_ml_docker.txt
Labels: tests-ok

#24065 [Serve][Deployment Graph] Let .bind return ray DAGNode types and remove exposing DeploymentNode as public
  python/ray/experimental/dag/class_node.py
  python/ray/experimental/dag/dag_node.py
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/experimental/dag/tests/test_class_dag.py
  python/ray/experimental/dag/tests/test_function_dag.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/deployment_graph.py
  python/ray/serve/pipeline/api.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/test_pipeline_dag.py
Labels: tests-ok

#24098 [State API] State api limit + Removing unnecessary modules
  dashboard/head.py
  dashboard/modules/actor/actor_head.py
  dashboard/modules/job/job_head.py
  dashboard/modules/node/node_head.py
  dashboard/modules/object/__init__.py
  dashboard/modules/object/object_head.py
  dashboard/modules/placement_group/__init__.py
  dashboard/modules/placement_group/placement_group_head.py
  dashboard/modules/state/state_head.py
  dashboard/modules/task/__init__.py
  dashboard/modules/task/task_head.py
  dashboard/modules/worker/__init__.py
  dashboard/modules/worker/worker_head.py
  dashboard/state_aggregator.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/tests/test_state_api.py
Labels: @author-action-required

#23931 [Datasets] [Out-of-Band Serialization: 2/3] Refactor `ExecutionPlan` to maintain complete lineage and eagerly unlink block references.
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/impl/lazy_block_list.py
  python/ray/data/impl/plan.py
  python/ray/data/tests/test_optimize.py
Labels: @author-action-required

#24064 [grpc] Upgrade grpc to 1.45.2
  bazel/ray_deps_setup.bzl
  python/ray/tests/BUILD
  thirdparty/patches/grpc-python.patch
  thirdparty/patches/grpc-remove-distutils.patch
Labels: @author-action-required

#24115 [Serve][Deployment Graph] Add test for ray core and serve dag class method call chain
  python/ray/serve/BUILD
  python/ray/serve/tests/test_deployment_graph_classmethod.py
Labels: tests-ok, serve, platform

#24096 [Serve] Fix deployment func no args called with python
  python/ray/serve/replica.py
  python/ray/serve/tests/test_api.py
Labels: tests-ok, flaky-test

#23932 [Datasets] [Out-of-Band Serialization: 3/3] Add out-of-band serialization.
  python/ray/data/dataset.py
  python/ray/data/impl/plan.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#23978 [GCS] allow re-subscribing to updates from nodes & actors
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/pubsub/subscriber.h
Labels: tests-ok

#22165 [ray client] enable ray.get with >2 sec timeout (#21883)
  python/ray/util/client/worker.py
Labels: tests-ok

#24161 [Datasets] Add test for reading CSV files without reading the first line as the header.
  python/ray/data/tests/test_dataset_formats.py
Labels: @author-action-required

#24123 [Jobs] Change jobs start_time end_time from seconds to ms for consistency
  dashboard/modules/job/common.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/snapshot/tests/test_job_submission.py
Labels: @author-action-required

#24179 [Datasets] Add basic stats instrumentation of `split_at_indices()`.
  python/ray/data/dataset.py
  python/ray/data/impl/stats.py
  python/ray/data/tests/test_stats.py
Labels: tests-ok

#24124 [Jobs] Reenable `test_backwards_compatibility` using Ray 1.12
  dashboard/modules/job/tests/backwards_compatibility_scripts/test_backwards_compatibility.sh
  dashboard/modules/job/tests/test_backwards_compatibility.py
Labels: tests-ok

#23758 [Datasets] Implement push-based shuffle
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/impl/fast_repartition.py
  python/ray/data/impl/push_based_shuffle.py
  python/ray/data/impl/shuffle.py
  python/ray/data/impl/shuffle_and_partition.py
  python/ray/data/impl/sort.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_sort.py
Labels: @author-action-required

#24263 [Dashboard] Add environment variable flag to skip dashboard log processing
  dashboard/modules/node/node_head.py
  dashboard/modules/node/tests/test_node.py
  python/ray/ray_constants.py
Labels: tests-ok

#24195 [kuberay] Test Ray client and update autoscaler image
  .buildkite/pipeline.yml
  doc/source/cluster/kuberay.md
  python/ray/autoscaler/kuberay/ray-cluster.complete.yaml
  python/ray/tests/kuberay/scripts/gpu_actor_placement.py
  python/ray/tests/kuberay/scripts/gpu_actor_validation.py
  python/ray/tests/kuberay/scripts/scale_down.py
  python/ray/tests/kuberay/scripts/scale_up.py
  python/ray/tests/kuberay/scripts/scale_up_custom.py
  python/ray/tests/kuberay/test_autoscaling_e2e.py
  python/ray/tests/kuberay/utils.py
Labels: kuberay, infra

#24066 [AIR/Train] Make Dataset ingest configurable
  python/ray/ml/train/data_parallel_trainer.py
  python/ray/ml/trainer.py
  python/ray/train/backend.py
  python/ray/train/impl/dataset_spec.py
  python/ray/train/session.py
  python/ray/train/tests/test_backend.py
  python/ray/train/trainer.py
  python/ray/train/utils.py
Labels: tests-ok

#24194 [Datasets] Pipeline task dependency prefetching with actor compute via customizable max tasks in flight per worker.
  python/ray/data/impl/compute.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#24211 [GCS][Storage unification 3/n] Deprecate MemoryInternalKV, use StoreClientInternalKV<MemoryStoreClient> instead
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/store_client_kv.cc
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
Labels: tests-ok, @author-action-required

#24223 [DAG] add basic plotting on Ray DAGs
  python/ray/experimental/dag/__init__.py
  python/ray/experimental/dag/dag_node.py
  python/ray/experimental/dag/input_node.py
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/experimental/dag/tests/test_function_dag.py
  python/ray/experimental/dag/tests/test_plot.py
  python/ray/experimental/dag/utils.py
  python/ray/experimental/dag/vis_utils.py
  python/ray/serve/pipeline/api.py
  python/ray/serve/pipeline/generate.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/pipeline/tests/test_json_serde.py
  python/ray/serve/tests/test_pipeline_dag_plot.py
  python/ray/workflow/dag_to_workflow.py
Labels: tests-ok

#24287 [workflow] Ensure "get_if_exists" takes effect in the decorator.
  python/ray/actor.py
  python/ray/tests/test_get_or_create_actor.py
Labels: @author-action-required

#23402 [Ray Data] integrate mars with ray
  doc/source/data/dataset.rst
  doc/source/data/mars-on-ray.rst
  python/ray/data/dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_mars.py
  python/requirements/data_processing/requirements.txt
Labels: @external-author-action-required

#23952 [RFC][Dataset] Actor based prefetching
  python/ray/data/context.py
  python/ray/data/impl/block_batching.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#24022 [Datsets] Add `SimpleTensorFlowDatasource`
  doc/source/data/creating-datasets.rst
  doc/source/data/package-ref.rst
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/tensorflow_datasource.py
  python/ray/data/tests/test_dataset_formats.py
  python/requirements/data_processing/requirements_dataset.txt
Labels: release-blocker

#23179 [Datasets] Add bulk Parquet file reader API
  python/ray/data/__init__.py
  python/ray/data/datasource/binary_datasource.py
  python/ray/data/datasource/csv_datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/json_datasource.py
  python/ray/data/datasource/numpy_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_formats.py
Labels: P1, @author-action-required

#24246 [Deployment Graph] Add release test for long chain & wide fanout pattern
  release/BUILD
  release/release_tests.yaml
  release/serve_tests/app_config.yaml
  release/serve_tests/compute_tpl_single_node_32_cpu.yaml
  release/serve_tests/workloads/benchmark_utils.py
  release/serve_tests/workloads/deployment_graph_long_chain.py
  release/serve_tests/workloads/deployment_graph_wide_ensemble.py
  release/serve_tests/workloads/serve_test_cluster_utils.py
Labels: tests-ok, serve, flaky-test
