Repository ray-project/ray, pull requests merged in 2022-08, with the labels that each got.

#27312 [ci] print out test environment info for all python tests
  .buildkite/pipeline.gpu.large.yml
  .buildkite/pipeline.macos.yml
  .buildkite/pipeline.ml.yml
  .buildkite/pipeline.yml
Labels: tests-ok

#23766 Fix dashboard with prometheus-client 0.14
  python/ray/_private/prometheus_exporter.py
  python/ray/autoscaler/_private/monitor.py
Labels: stale

#27017 memory monitor
  BUILD.bazel
  src/ray/common/memory_monitor.cc
  src/ray/common/memory_monitor.h
  src/ray/common/ray_config_def.h
  src/ray/common/test/memory_monitor_test.cc
  src/ray/util/process.cc
  src/ray/util/process.h
Labels: @author-action-required

#27241 [air] update pytorch_training_e2e.py to use iter_torch_batches.
  release/air_tests/air_benchmarks/workloads/pytorch_training_e2e.py
Labels: v2.0.0-pick

#27321 [tune/cp] `tune.run` clean up
  doc/source/rllib/core-concepts.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-training.rst
  doc/source/tune/api_docs/trainable.rst
  doc/source/tune/tutorials/tune-checkpoints.rst
  doc/source/tune/tutorials/tune-distributed.rst
  doc/source/tune/tutorials/tune-output.rst
  doc/source/tune/tutorials/tune-stopping.rst
Labels: v2.0.0-pick

#26952 [docs] Reorganize the tensor data support docs; general editing
  doc/source/data/consuming-datasets.rst
  doc/source/data/creating-datasets.rst
  doc/source/data/dataset-internals.rst
  doc/source/data/dataset-tensor-support.rst
  doc/source/data/doc_code/tensor.py
  doc/source/data/key-concepts.rst
  doc/source/data/performance-tips.rst
  doc/source/data/pipelining-compute.rst
  doc/source/data/transforming-datasets.rst
  doc/source/ray-air/predictors.rst
  python/ray/air/util/tensor_extensions/pandas.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/dataset.py
  python/ray/data/examples/data/image-folder/cat/123.png
  python/ray/data/examples/data/image-folder/cat/foo.jpg
  python/ray/data/examples/data/image-folder/cat/not-an-image
  python/ray/data/examples/data/image-folder/dog/xxx.PNG
  python/ray/data/examples/data/image-folder/not-an-image
  python/ray/data/examples/data/parquet_images_mini/652597cc55e94e3e8d91776eec17774a_000000.parquet
  python/ray/data/examples/data/parquet_images_mini/652597cc55e94e3e8d91776eec17774a_000001.parquet
  python/ray/data/examples/data/parquet_images_mini/652597cc55e94e3e8d91776eec17774a_000002.parquet
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: v2.0.0-pick

#27217 [Workflow] Cleanup workflow docs
  README.rst
  doc/source/workflows/advanced.rst
  doc/source/workflows/comparison.rst
  doc/source/workflows/concepts.rst
  doc/source/workflows/events.rst
  doc/source/workflows/management.rst
  doc/source/workflows/package-ref.rst
Labels: v2.0.0-pick

#27313 [docs][kubernetes] XGBoost ML example
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/xgboost-benchmark-autoscaler.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/xgboost-benchmark.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/doc_code/xgboost_submit.py
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples/ml-example.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/getting-started.ipynb
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/index.md
  doc/source/ray-air/benchmarks.rst
  doc/source/ray-more-libs/index.rst
Labels: docs, kuberay, v2.0.0-pick

#27253 [docs/2.0.0] Fix Tune custom syncer example
  doc/source/tune/doc_code/faq.py
  python/ray/tune/tests/test_syncer.py
Labels: v2.0.0-pick

#27128 [DOC Ray AIR] minor editorial tweaks for clarity and usage
  doc/source/ray-air/preprocessors.rst
Labels: air, v2.0.0-pick

#27325 [air doc] checkpoint_freq --> checkpoint_frequency
  doc/source/tune/api_docs/trainable.rst
Labels: v2.0.0-pick

#26997 [Doc][Core][State Observability] Adding Python SDK doc and docstring
  dashboard/tests/test_dashboard.py
  doc/source/ray-observability/state/ray-state-api-reference.rst
  doc/source/ray-observability/state/state-api.rst
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_state_api.py
Labels: v2.0.0-pick

#27284 [dashboard] Add `last_activity_at` field to `/api/component_activities`
  dashboard/modules/snapshot/component_activities_schema.json
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/tests/test_snapshot.py
Labels: tests-ok, v2.0.0-pick

#27355 [docs] Reorganize the tensor data support docs; general editing (#26952)
  doc/source/data/consuming-datasets.rst
  doc/source/data/creating-datasets.rst
  doc/source/data/dataset-internals.rst
  doc/source/data/dataset-tensor-support.rst
  doc/source/data/doc_code/tensor.py
  doc/source/data/key-concepts.rst
  doc/source/data/performance-tips.rst
  doc/source/data/pipelining-compute.rst
  doc/source/data/transforming-datasets.rst
  doc/source/ray-air/predictors.rst
  python/ray/air/util/tensor_extensions/pandas.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/dataset.py
  python/ray/data/examples/data/image-folder/cat/123.png
  python/ray/data/examples/data/image-folder/cat/foo.jpg
  python/ray/data/examples/data/image-folder/cat/not-an-image
  python/ray/data/examples/data/image-folder/dog/xxx.PNG
  python/ray/data/examples/data/image-folder/not-an-image
  python/ray/data/examples/data/parquet_images_mini/652597cc55e94e3e8d91776eec17774a_000000.parquet
  python/ray/data/examples/data/parquet_images_mini/652597cc55e94e3e8d91776eec17774a_000001.parquet
  python/ray/data/examples/data/parquet_images_mini/652597cc55e94e3e8d91776eec17774a_000002.parquet
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: v2.0.0-pick

#27213 Raise the (runtime_env max size) gRPC max message size to 500MiB
  python/ray/_private/runtime_env/packaging.py
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#27370 Support placement_group=None in PlacementGroupSchedulingStrategy
  doc/source/ray-core/gotchas.rst
  python/ray/tests/test_placement_group_2.py
  python/ray/tests/test_scheduling_2.py
  python/ray/util/scheduling_strategies.py
Labels: v2.0.0-pick

#26969 [Doc] [Serve] Edit grammar/usage/organization for HTTP adapters page
  doc/source/serve/http-adapters.md
Labels: tests-ok

#27365 [release/tune/2.0.0] Fix k8s release test + node-to-node syncing
  python/ray/tune/utils/util.py
  release/tune_tests/cloud_tests/tpl_gcp_k8s_4x8.yaml
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
Labels: v2.0.0-pick

#26891 [AIR - Serve] [Hotfix] Check for tensor extension via dtype rather than a NumPy conversion
  python/ray/serve/air_integrations.py
Labels: v2.0.0-pick

#27074 Add GPU info to new dashboard
  dashboard/client/src/pages/dashboard/node-info/features/GPU.tsx
  dashboard/client/src/pages/log/Logs.tsx
  dashboard/client/src/pages/node/GPUColumn.tsx
  dashboard/client/src/pages/node/GRAMColumn.tsx
  dashboard/client/src/pages/node/NodeRow.tsx
  dashboard/client/src/pages/node/index.tsx
  dashboard/client/src/type/node.d.ts
  dashboard/client/src/type/worker.d.ts
  dashboard/client/src/util/converter.ts
Labels: v2.0.0-pick

#27232 [air] Fix BatchPredictor.predict_pipelined not working with GPU stage
  python/ray/train/BUILD
  python/ray/train/batch_predictor.py
  python/ray/train/tests/test_batch_predictor.py
Labels: v2.0.0-pick

#27398 [air] Fix BatchPredictor.predict_pipelined not working with GPU stage…
  python/ray/train/BUILD
  python/ray/train/batch_predictor.py
  python/ray/train/tests/test_batch_predictor.py
Labels: v2.0.0-pick

#27360 [docs][kubernetes] GPU user guide
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples/ml-example.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/gpu.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/gpu.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/k8s-cluster-setup.md
  doc/source/ray-core/tasks/using-ray-with-gpus.rst
Labels: docs, kuberay, v2.0.0-pick, copyediting-required

#27349 [Serve] Pick Multiple DAG Entrypoints into 2.0 Release
  python/ray/serve/drivers.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deployment_graph_driver.py
  python/ray/serve/tests/test_http_routes.py
Labels: v2.0.0-pick

#27403 [workflow] Change step to task in workflow (#27330)
  python/ray/workflow/api.py
  python/ray/workflow/common.py
  python/ray/workflow/debug_utils.py
  python/ray/workflow/http_event_provider.py
  python/ray/workflow/task_executor.py
  python/ray/workflow/tests/test_basic_workflows.py
  python/ray/workflow/tests/test_basic_workflows_2.py
  python/ray/workflow/tests/test_basic_workflows_3.py
  python/ray/workflow/tests/test_checkpoint_2.py
  python/ray/workflow/tests/test_dynamic_workflow_ref.py
  python/ray/workflow/tests/test_error_handling.py
  python/ray/workflow/tests/test_events.py
  python/ray/workflow/tests/test_http_events.py
  python/ray/workflow/tests/test_http_events_2.py
  python/ray/workflow/tests/test_logging.py
  python/ray/workflow/tests/test_metadata.py
  python/ray/workflow/tests/test_recovery.py
  python/ray/workflow/tests/test_serialization2.py
  python/ray/workflow/tests/test_storage.py
  python/ray/workflow/tests/test_storage_failure.py
  python/ray/workflow/tests/utils.py
  python/ray/workflow/workflow_access.py
  python/ray/workflow/workflow_context.py
  python/ray/workflow/workflow_executor.py
  python/ray/workflow/workflow_state.py
  python/ray/workflow/workflow_state_from_dag.py
  python/ray/workflow/workflow_state_from_storage.py
  python/ray/workflow/workflow_storage.py
Labels: v2.0.0-pick

#27348 Revert "Revert "[Serve] ServeHandle detects ActorError and drop replicas from target group (#26685)" (#27283)"
  python/ray/serve/_private/long_poll.py
  python/ray/serve/_private/router.py
  python/ray/serve/tests/test_standalone2.py
Labels: @author-action-required, v2.0.0-pick

#27334 [Doc] Test ray core doc code
  doc/BUILD
  doc/source/ray-core/doc_code/actor-http-server.py
  doc/source/ray-core/doc_code/deser.py
  doc/source/ray-core/doc_code/namespaces.py
  doc/source/ray-core/doc_code/ray-dag.py
  doc/source/ray-core/doc_code/tf_example.py
  doc/source/ray-core/doc_code/torch_example.py
  doc/source/ray-observability/doc_code/metrics_example.py
  doc/source/ray-observability/ray-metrics.rst
Labels: tests-ok

#27261 [Serve] Cherry-pick handle early detection for GCS FT
  python/ray/serve/_private/long_poll.py
  python/ray/serve/_private/router.py
  python/ray/serve/tests/test_standalone2.py
Labels: v2.0.0-pick

#27418 [ray 2.0] adjust the release test of ray lightning master
  release/ml_user_tests/ray-lightning/simple_example.py
Labels: v2.0.0-pick

#26965 [Serve] [Doc] Update key concepts for 2.0, remove deprecated APIs
  doc/source/serve/deployment-graph/deployment-graph-e2e-tutorial.md
  doc/source/serve/doc_code/create_deployment.py
  doc/source/serve/key-concepts.md
Labels: tests-ok

#27395 [ray 2.0 release] fix the release test of ray lightning master
  release/ml_user_tests/ray-lightning/simple_example.py
Labels: v2.0.0-pick

#26837 [air] add tuner user guide
  doc/source/_toc.yml
  doc/source/ray-air/doc_code/tuner.py
  doc/source/ray-air/examples/analyze_tuning_results.ipynb
  doc/source/ray-air/examples/index.rst
  doc/source/ray-air/images/tuner.svg
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/tuner.rst
  doc/source/ray-air/user-guides.rst
  doc/source/tune/key-concepts.rst
  python/ray/tune/impl/tuner_internal.py
Labels: v2.0.0-pick, copyediting-required

#27000 [Serve] Enable lightweight config update
  python/ray/serve/api.py
  python/ray/serve/controller.py
  python/ray/serve/deployment.py
  python/ray/serve/tests/test_config_files/pid.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_standalone2.py
Labels: serve, v2.0.0-pick

#27420 [Serve] Fix Graph Repeated Invocation (#27417)
  python/ray/dag/format_utils.py
  python/ray/serve/_private/deployment_executor_node.py
  python/ray/serve/_private/deployment_function_executor_node.py
  python/ray/serve/_private/deployment_method_executor_node.py
  python/ray/serve/tests/test_deployment_graph.py
Labels: v2.0.0-pick

#27376 [docs][Ray Clusters] Migrate Community Supported Cluster Launcher to new structure.
  doc/source/cluster/cluster_under_construction/doc_code/simple-trainer.py
  doc/source/cluster/cluster_under_construction/doc_code/slurm-basic.sh
  doc/source/cluster/cluster_under_construction/doc_code/slurm-launch.py
  doc/source/cluster/cluster_under_construction/doc_code/slurm-template.sh
  doc/source/cluster/cluster_under_construction/doc_code/yarn/example.py
  doc/source/cluster/cluster_under_construction/doc_code/yarn/ray-skein.yaml
  doc/source/cluster/cluster_under_construction/images/yarn-job.png
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/index.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/lsf.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/slurm-basic.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/slurm-launch.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/slurm-template.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/slurm.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/yarn.rst
Labels: docs, infra

#27399 Add GPU info to new dashboard
  dashboard/client/src/pages/dashboard/node-info/features/GPU.tsx
  dashboard/client/src/pages/log/Logs.tsx
  dashboard/client/src/pages/node/GPUColumn.tsx
  dashboard/client/src/pages/node/GRAMColumn.tsx
  dashboard/client/src/pages/node/NodeRow.tsx
  dashboard/client/src/pages/node/index.tsx
  dashboard/client/src/type/node.d.ts
  dashboard/client/src/type/worker.d.ts
  dashboard/client/src/util/converter.ts
Labels: v2.0.0-pick

#26861 [Doc] Update Serve architecture doc for 2.0
  doc/source/serve/architecture-2.0.svg
  doc/source/serve/architecture.md
  doc/source/serve/architecture.svg
  doc/source/serve/autoscaling.md
  doc/source/serve/deploying-serve.md
  doc/source/serve/managing-deployments.md
  doc/source/serve/package-ref.md
  doc/source/serve/production.md
Labels: @author-action-required

#27405 [docs] Revamp README and Ray intro doc page
  .github/CODEOWNERS
  README.rst
  doc/source/images/what-is-ray-padded.svg
  doc/source/index.md
Labels: v2.0.0-pick

#27295 [AIR] Add optional `mode` parameter and make `size` parameter optional
  doc/source/data/dataset-tensor-support.rst
  python/ray/data/datasource/image_folder_datasource.py
  python/ray/data/examples/data/image-folders/different-extensions/cat/123.png
  python/ray/data/examples/data/image-folders/different-extensions/cat/foo.jpg
  python/ray/data/examples/data/image-folders/different-extensions/cat/not-an-image
  python/ray/data/examples/data/image-folders/different-extensions/dog/xxx.PNG
  python/ray/data/examples/data/image-folders/different-extensions/not-an-image
  python/ray/data/examples/data/image-folders/different-modes/cat/cmyk.jpg
  python/ray/data/examples/data/image-folders/different-modes/cat/rgb.jpg
  python/ray/data/examples/data/image-folders/different-modes/dog/L.jpg
  python/ray/data/examples/data/image-folders/different-sizes/cat/32x32.png
  python/ray/data/examples/data/image-folders/different-sizes/cat/64x64.png
  python/ray/data/examples/data/image-folders/different-sizes/dog/16x16.png
  python/ray/data/examples/data/image-folders/simple/cat/123.png
  python/ray/data/examples/data/image-folders/simple/cat/foo.jpg
  python/ray/data/examples/data/image-folders/simple/dog/xxx.PNG
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#27316 bump jobs version after making a backwards-incompatible change
  dashboard/modules/version.py
Labels: v2.0.0-pick

#27345 Make it so pydantic is required before we launch dashboard api server
  dashboard/optional_deps.py
  python/setup.py
Labels: tests-ok, v2.0.0-pick

#27433 [Serve] Make `serve.run()` and `deployment.bind()` beta APIs
  python/ray/serve/api.py
  python/ray/serve/deployment.py
Labels: v2.0.0-pick

#27347 [docs] Improve the AIR introductory page
  doc/source/index.md
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/air-ecosystem.svg
  doc/source/ray-air/images/ray-air.svg
  doc/source/ray-air/images/why-air.png
  doc/source/ray-air/key-concepts.rst
  doc/source/train/user_guide.rst
Labels: v2.0.0-pick

#27472 [pick] [docs] Improve the AIR introductory page (#27347)
  doc/source/index.md
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/air-ecosystem.svg
  doc/source/ray-air/images/ray-air.svg
  doc/source/ray-air/images/why-air.png
  doc/source/ray-air/key-concepts.rst
  doc/source/train/user_guide.rst
Labels: v2.0.0-pick

#27474 [docs] Update colors and styling of ray diagrams
  doc/source/images/what-is-ray-padded.svg
  doc/source/ray-air/images/ray-air.svg
Labels: v2.0.0-pick

#27478 [docs] Change data tagline to "Distributed Data Preprocessing" (#27434)
  doc/source/data/dataset.rst
Labels: v2.0.0-pick

#27456 Make it so pydantic is required before we launch dashboard api server
  dashboard/optional_deps.py
  python/setup.py
Labels: v2.0.0-pick

#27463 [dashboard] Add last_activity_at field to /api/component_activities
  dashboard/modules/snapshot/component_activities_schema.json
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/tests/test_snapshot.py
Labels: v2.0.0-pick

#27461 [Doc][Core][State Observability] Adding Python SDK doc and docstring
  dashboard/tests/test_dashboard.py
  doc/source/ray-observability/state/ray-state-api-reference.rst
  doc/source/ray-observability/state/state-api.rst
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_state_api.py
Labels: v2.0.0-pick

#27491 [tune/2.0.0] change API annotations
  python/ray/tune/registry.py
  python/ray/tune/result_grid.py
  python/ray/tune/schedulers/__init__.py
  python/ray/tune/search/__init__.py
  python/ray/tune/utils/util.py
Labels: v2.0.0-pick

#27465 [air 2.0.0] update pytorch_training_e2e.py to use iter_torch_batches.
  release/air_tests/air_benchmarks/workloads/pytorch_training_e2e.py
Labels: v2.0.0-pick

#27462 [air doc] checkpoint_freq --> checkpoint_frequency (#27325)
  doc/source/tune/api_docs/trainable.rst
Labels: v2.0.0-pick

#27444 [Serve] Enable lightweight config update (#27000)
  python/ray/serve/api.py
  python/ray/serve/controller.py
  python/ray/serve/deployment.py
  python/ray/serve/tests/test_config_files/pid.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_standalone2.py
Labels: v2.0.0-pick

#27512 [Cherry-pick] [AIR - Serve] Check for tensor extension via dtype rather than a NumPy conversion
  python/ray/serve/air_integrations.py
Labels: v2.0.0-pick

#27517 [Cherry-pick] [AIR] Add optional `mode` parameter and make `size` parameter optional
  doc/source/data/dataset-tensor-support.rst
  python/ray/data/datasource/image_folder_datasource.py
  python/ray/data/examples/data/image-folders/different-extensions/cat/123.png
  python/ray/data/examples/data/image-folders/different-extensions/cat/foo.jpg
  python/ray/data/examples/data/image-folders/different-extensions/cat/not-an-image
  python/ray/data/examples/data/image-folders/different-extensions/dog/xxx.PNG
  python/ray/data/examples/data/image-folders/different-extensions/not-an-image
  python/ray/data/examples/data/image-folders/different-modes/cat/cmyk.jpg
  python/ray/data/examples/data/image-folders/different-modes/cat/rgb.jpg
  python/ray/data/examples/data/image-folders/different-modes/dog/L.jpg
  python/ray/data/examples/data/image-folders/different-sizes/cat/32x32.png
  python/ray/data/examples/data/image-folders/different-sizes/cat/64x64.png
  python/ray/data/examples/data/image-folders/different-sizes/dog/16x16.png
  python/ray/data/examples/data/image-folders/simple/cat/123.png
  python/ray/data/examples/data/image-folders/simple/cat/foo.jpg
  python/ray/data/examples/data/image-folders/simple/dog/xxx.PNG
  python/ray/data/tests/test_dataset_formats.py
Labels: v2.0.0-pick

#27519 [Cherry-pick] [AIR] Add `__repr__` to AIR classes
  python/ray/air/BUILD
  python/ray/air/checkpoint.py
  python/ray/air/config.py
  python/ray/air/constants.py
  python/ray/air/tests/test_checkpoints.py
  python/ray/air/tests/test_configs.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/preprocessors/chain.py
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/preprocessors/encoder.py
  python/ray/data/preprocessors/hasher.py
  python/ray/data/preprocessors/imputer.py
  python/ray/data/preprocessors/normalizer.py
  python/ray/data/preprocessors/scaler.py
  python/ray/data/preprocessors/tokenizer.py
  python/ray/data/preprocessors/transformer.py
  python/ray/data/preprocessors/vectorizer.py
  python/ray/data/tests/test_preprocessors.py
  python/ray/train/BUILD
  python/ray/train/base_trainer.py
  python/ray/train/batch_predictor.py
  python/ray/train/huggingface/huggingface_predictor.py
  python/ray/train/lightgbm/lightgbm_predictor.py
  python/ray/train/rl/rl_predictor.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/tensorflow/tensorflow_predictor.py
  python/ray/train/tests/test_base_trainer.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_checkpoints.py
  python/ray/train/tests/test_huggingface_predictor.py
  python/ray/train/tests/test_lightgbm_predictor.py
  python/ray/train/tests/test_rl_predictor.py
  python/ray/train/tests/test_sklearn_predictor.py
  python/ray/train/tests/test_tensorflow_predictor.py
  python/ray/train/tests/test_torch_predictor.py
  python/ray/train/torch/torch_predictor.py
  python/ray/train/xgboost/xgboost_predictor.py
Labels: tests-ok, v2.0.0-pick

#27532 [autoscaler] Fix Prometheus metric autoscaler hang bug
  python/ray/autoscaler/_private/prom_metrics.py
  python/ray/tests/test_autoscaler.py
Labels: v2.0.0-pick

#27530 [cherry-pick][air] Remove checkpoint user guide and update key concepts and docstring
  doc/source/_toc.yml
  doc/source/ray-air/checkpoints.rst
  doc/source/ray-air/doc_code/air_key_concepts.py
  doc/source/ray-air/doc_code/checkpoint_usage.py
  doc/source/ray-air/images/checkpoints.jpg
  doc/source/ray-air/key-concepts.rst
  doc/source/ray-air/user-guides.rst
  python/ray/air/checkpoint.py
Labels: v2.0.0-pick

#27529 [cherry-pick][air/train/docs] gbdt trainer user guide
  doc/BUILD
  doc/source/_toc.yml
  doc/source/train/doc_code/gbdt_user_guide.py
  doc/source/train/gbdt.rst
Labels: v2.0.0-pick

#27520 [Core][Fix] Fixing test_metrics and test_state_api timing out
  python/ray/tests/BUILD
  python/ray/tests/test_metrics.py
Labels: v2.0.0-pick

#27301 [core] Suppress the logging error when python exits and actor not del…
  python/ray/actor.py
  python/ray/tests/test_basic_5.py
Labels: v2.0.0-pick

#27308 Revert "Revert "[Job Submission][refactor 1/N] Add AgentInfo to GCSNodeInfo (…"
  dashboard/agent.py
  dashboard/consts.py
  dashboard/modules/node/node_head.py
  dashboard/modules/node/tests/test_node.py
  dashboard/tests/test_dashboard.py
  python/ray/_private/state.py
  python/ray/_private/worker.py
  python/ray/tests/BUILD
  python/ray/tests/conftest.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_ray_shutdown.py
  python/ray/tests/test_state_api.py
  src/ray/protobuf/BUILD
  src/ray/protobuf/agent_manager.proto
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/agent_manager.cc
  src/ray/raylet/agent_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/raylet.h
  src/ray/raylet/worker_pool_test.cc
Labels: tests-ok

#27514 [RLlib] Training step docs. (#27344)
  doc/source/rllib/core-concepts.rst
  doc/source/rllib/package_ref/execution.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/parallel_requests.rst
  doc/source/rllib/package_ref/train_ops.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-training.rst
  rllib/execution/parallel_requests.py
Labels: v2.0.0-pick

#27498 [serve] Update version if import_path or runtime_env in config is changed
  python/ray/serve/controller.py
  python/ray/serve/tests/test_config_files/pid.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_standalone2.py
Labels: serve, v2.0.0-pick

#26403 [serve] Integrate and Document Bring-Your-Own Gradio Applications
  .buildkite/pipeline.yml
  ci/ci.sh
  ci/env/install-serve.sh
  doc/source/serve/tutorials/gradio-integration.md
  doc/source/serve/tutorials/gradio.ipynb
  doc/source/serve/tutorials/index.md
  python/ray/serve/BUILD
  python/ray/serve/examples/doc/gradio-integration-parallel.py
  python/ray/serve/examples/doc/gradio-integration.py
  python/ray/serve/examples/doc/gradio-original.py
  python/ray/serve/gradio_integrations.py
  python/ray/serve/tests/test_gradio.py
  python/requirements.txt
  python/setup.py
Labels: serve, docs

#26914 [Serve][Doc] Moves Serve REST API and Serve CLI API into separate subpages
  doc/source/serve/package-ref.md
  doc/source/serve/rest_api.md
  doc/source/serve/serve_cli.md
Labels: serve, @author-action-required, docs

#26817 [Serve][doc] Modify and Combine Tensorflow, Pytorch, Sklearn Tutorials
  doc/source/serve/doc_code/tutorial_pytorch.py
  doc/source/serve/doc_code/tutorial_sklearn.py
  doc/source/serve/doc_code/tutorial_tensorflow.py
  doc/source/serve/getting_started.md
  doc/source/serve/index.md
  doc/source/serve/ml-models.md
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/pytorch.md
  doc/source/serve/tutorials/serve-ml-models.md
  doc/source/serve/tutorials/sklearn.md
  doc/source/serve/tutorials/tensorflow.md
  python/ray/serve/BUILD
Labels: serve, docs

#27391 [docs][Ray Clusters] New Ray Clusters getting started page.
  doc/source/cluster/cluster_under_construction/getting-started.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/add-your-own-cloud-provider.rst
Labels: docs, infra

#27367 [Datasets] [Docs] Improve `.limit()` and `.take()` docstrings
  python/ray/data/dataset.py
Labels: @author-action-required

#27504 [docs] KubeRay config guide and autoscaling discussion
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples/ml-example.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/autoscaling.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/config.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/gpu.rst
  doc/source/cluster/kubernetes.rst
Labels: docs, kuberay, copyediting-required

#27343 [Datasets] Avoid unnecessary reads when truncating a dataset with `ds.limit()`
  python/ray/data/_internal/block_list.py
  python/ray/data/_internal/lazy_block_list.py
  python/ray/data/_internal/split.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
Labels: v2.0.0-pick

#27561 [serve] Update version if import_path or runtime_env in config is cha…
  python/ray/serve/controller.py
  python/ray/serve/tests/test_config_files/pid.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_standalone2.py
Labels: v2.0.0-pick

#27560 [serve] Integrate and Document Bring-Your-Own Gradio Applications (#2…
  .buildkite/pipeline.yml
  ci/ci.sh
  ci/env/install-serve.sh
  doc/source/serve/tutorials/gradio-integration.md
  doc/source/serve/tutorials/gradio.ipynb
  doc/source/serve/tutorials/index.md
  python/ray/serve/BUILD
  python/ray/serve/examples/doc/gradio-integration-parallel.py
  python/ray/serve/examples/doc/gradio-integration.py
  python/ray/serve/examples/doc/gradio-original.py
  python/ray/serve/gradio_integrations.py
  python/ray/serve/tests/test_gradio.py
  python/requirements.txt
  python/setup.py
Labels: v2.0.0-pick

#26449 [Core] Unrevert "Add retry exception allowlist for user-defined filtering of retryable application-level errors."
  .gitignore
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  doc/source/ray-core/doc_code/tasks_fault_tolerance.py
  doc/source/ray-core/tasks/fault-tolerance.rst
  python/ray/_private/ray_option_utils.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/BUILD
  python/ray/tests/test_failure_4.py
  python/ray/tests/test_output.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: @author-action-required, v2.0.0-pick

#27489 Add query param to limit number of actors in api/snapshot
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/tests/test_snapshot.py
Labels: v2.0.0-pick

#27539 [doc] update autoscaler config (VM) page
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/configuring-autoscaling.rst
Labels: docs, infra

#27480 [docs] Improve the "Why Ray" and "Why AIR" sections of the docs
  README.rst
  doc/source/data/dataset-tensor-support.rst
  doc/source/index.md
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/ray-air.svg
  doc/source/ray-air/images/when-air.svg
  doc/source/ray-air/images/why-air-2.svg
  doc/source/ray-air/images/why-air.png
  doc/source/ray-air/images/why-air.svg
Labels: v2.0.0-pick

#27594 [pick] [docs] Improve the "Why Ray" and "Why AIR" sections of the docs
  README.rst
  doc/source/data/dataset-tensor-support.rst
  doc/source/index.md
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/ray-air.svg
  doc/source/ray-air/images/when-air.svg
  doc/source/ray-air/images/why-air-2.svg
  doc/source/ray-air/images/why-air.png
  doc/source/ray-air/images/why-air.svg
Labels: v2.0.0-pick

#27396 [core] Support external ray dashboard URL
  dashboard/head.py
  python/ray/_private/node.py
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/experimental/state/common.py
  python/ray/tests/test_ray_init.py
Labels: tests-ok, release-blocker, v2.0.0-pick

#27123 Convert job_manager to be async
  dashboard/modules/job/common.py
  dashboard/modules/job/job_head.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/state/state_head.py
  dashboard/state_aggregator.py
  python/ray/experimental/state/state_manager.py
  python/ray/tests/test_state_api.py
Labels: v2.0.0-pick

#27298 [Core] Fix reference counting bug on objects borrowed for a cancelled actor creation.
  python/ray/exceptions.py
  python/ray/tests/test_reference_counting.py
  src/ray/common/status.cc
  src/ray/common/status.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs_service.proto
Labels: @author-action-required, v2.0.0-pick

#27531 [AIR - Datasets] Fix column assignment in Concatenator for Pandas 1.2.
  python/ray/data/preprocessors/concatenator.py
  python/setup.py
Labels: v2.0.0-pick

#27593 [log_monitor] Seek when reopening a file due to inode change (#27508)
  python/ray/_private/log_monitor.py
  python/ray/tests/test_logging.py
Labels: v2.0.0-pick

#27597 Convert job_manager to be async
  dashboard/modules/job/common.py
  dashboard/modules/job/job_head.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/state/state_head.py
  dashboard/state_aggregator.py
  python/ray/experimental/state/state_manager.py
  python/ray/tests/test_state_api.py
Labels: v2.0.0-pick

#27589 Add query param to limit number of actors in api/snapshot
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/modules/snapshot/tests/test_snapshot.py
Labels: v2.0.0-pick

#26877 [serve][xlang]Support deploying Python deployment from Java.
  java/BUILD.bazel
  java/serve/src/main/java/io/ray/serve/config/DeploymentConfig.java
  java/serve/src/main/java/io/ray/serve/config/ReplicaConfig.java
  java/serve/src/main/java/io/ray/serve/deployment/Deployment.java
  java/serve/src/main/java/io/ray/serve/deployment/DeploymentCreator.java
  java/serve/src/main/java/io/ray/serve/router/ReplicaSet.java
  java/serve/src/main/resources/test_python_deployment.py
  java/serve/src/test/java/io/ray/serve/CrossLanguageDeploymentTest.java
  java/serve/src/test/java/io/ray/serve/ReplicaSetTest.java
  java/serve/src/test/resources/test_deployment_cross_language_invocation.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
  python/ray/serve/config.py
  python/ray/serve/tests/test_util.py
Labels: serve, @external-author-action-required

#27384 [Core] Install memory monitor callback to kill worker when memory usage is above threshold
  python/ray/tests/BUILD
  python/ray/tests/test_memory_pressure.py
  src/ray/common/memory_monitor.h
  src/ray/core_worker/task_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.h
Labels: core

#27587 Revert "[serve] Integrate and Document Bring-Your-Own Gradio Applications"
  .buildkite/pipeline.yml
  ci/ci.sh
  ci/env/install-serve.sh
  doc/source/serve/tutorials/gradio-integration.md
  doc/source/serve/tutorials/gradio.ipynb
  doc/source/serve/tutorials/index.md
  python/ray/serve/BUILD
  python/ray/serve/examples/doc/gradio-integration-parallel.py
  python/ray/serve/examples/doc/gradio-integration.py
  python/ray/serve/examples/doc/gradio-original.py
  python/ray/serve/gradio_integrations.py
  python/ray/serve/tests/test_gradio.py
  python/requirements.txt
  python/setup.py
Labels: tests-ok

#27411 [Serve] Use Async Handle for DAG Execution
  dashboard/modules/serve/tests/test_serve_agent.py
  doc/source/serve/doc_code/migration_example.py
  doc/source/serve/doc_code/production_fruit_example.py
  python/ray/dag/BUILD
  python/ray/dag/py_obj_scanner.py
  python/ray/dag/tests/test_py_obj_scanner.py
  python/ray/serve/BUILD
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_function_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/deployment_node.py
  python/ray/serve/_private/http_proxy.py
  python/ray/serve/_private/json_serde.py
  python/ray/serve/_private/router.py
  python/ray/serve/deployment_graph.py
  python/ray/serve/drivers.py
  python/ray/serve/handle.py
  python/ray/serve/tests/resources/test_modules.py
  python/ray/serve/tests/test_air_integrations.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_config_files/arithmetic.yaml
  python/ray/serve/tests/test_config_files/pizza.py
  python/ray/serve/tests/test_config_files/test_dag/basic_dag.py
  python/ray/serve/tests/test_config_files/test_dag/conditional_dag.py
  python/ray/serve/tests/test_config_files/test_dag/dir/subdir/a/add_and_sub.py
  python/ray/serve/tests/test_config_files/world.py
  python/ray/serve/tests/test_deployment_graph.py
  python/ray/serve/tests/test_deployment_graph_build.py
  python/ray/serve/tests/test_deployment_graph_classmethod.py
  python/ray/serve/tests/test_deployment_graph_config.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_json_serde.py
  python/ray/serve/tests/test_pipeline_dag_plot.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_standalone2.py
  python/ray/serve/tests/test_util.py
Labels: tests-ok

#27570 [cherry-pick][air/train/docs] Add trainer user guide and update trainer docs
  doc/BUILD
  doc/source/_toc.yml
  doc/source/ray-air/benchmarks.rst
  doc/source/ray-air/config-scaling.rst
  doc/source/ray-air/doc_code/config_scaling.py
  doc/source/ray-air/doc_code/hf_trainer.py
  doc/source/ray-air/doc_code/hvd_trainer.py
  doc/source/ray-air/doc_code/lightgbm_trainer.py
  doc/source/ray-air/doc_code/report_metrics_and_save_checkpoints.py
  doc/source/ray-air/doc_code/rl_trainer.py
  doc/source/ray-air/doc_code/sklearn_trainer.py
  doc/source/ray-air/doc_code/torch_trainer.py
  doc/source/ray-air/doc_code/xgboost_trainer.py
  doc/source/ray-air/images/train.svg
  doc/source/ray-air/key-concepts.rst
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/trainer.rst
  doc/source/ray-air/user-guides.rst
  doc/source/train/api.rst
  doc/source/train/examples.rst
  doc/source/train/examples/tensorflow_linear_dataset_example.rst
  doc/source/train/examples/tensorflow_regression_example.rst
  doc/source/train/examples/torch_linear_dataset_example.rst
  doc/source/train/examples/torch_linear_example.rst
  doc/source/train/examples/torch_regression_example.rst
  doc/source/train/examples/tune_linear_example.rst
  doc/source/train/examples/tune_torch_linear_dataset_example.rst
  doc/source/train/examples/tune_torch_regression_example.rst
  doc/source/train/faq.rst
  doc/source/train/gbdt.rst
  python/ray/air/BUILD
  python/ray/air/config.py
  python/ray/air/examples/pytorch/torch_linear_dataset_example.py
  python/ray/air/examples/pytorch/torch_regression_example.py
  python/ray/air/examples/pytorch/tune_torch_regression_example.py
  python/ray/air/examples/tf/tensorflow_regression_example.py
  python/ray/air/tests/test_keras_callback.py
  python/ray/train/base_trainer.py
  python/ray/train/examples/tensorflow_linear_dataset_example.py
  python/ray/train/huggingface/huggingface_trainer.py
  python/ray/train/sklearn/sklearn_trainer.py
  python/ray/train/tests/test_gpu.py
  python/ray/train/tests/test_tensorflow_trainer.py
  python/ray/util/annotations.py
Labels: v2.0.0-pick

#27632 [Link Check] Fix the broken link check from the AIR doc
  doc/source/ray-air/air-ecosystem.rst
  doc/source/ray-air/getting-started.rst
Labels: v2.0.0-pick

#27641 [releases/2.0.0] Revert "[docs] Improve the "Why Ray" and "Why AIR" sections of the docs"
  README.rst
  doc/source/data/dataset-tensor-support.rst
  doc/source/index.md
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/ray-air.svg
  doc/source/ray-air/images/when-air.svg
  doc/source/ray-air/images/why-air-2.svg
  doc/source/ray-air/images/why-air.png
  doc/source/ray-air/images/why-air.svg
Labels: v2.0.0-pick

#27563 [CI] [runtime env] Fix test_working_dir_2 timeout on Mac
  python/ray/tests/test_runtime_env_working_dir_2.py
Labels: tests-ok

#27608 [Serve] [Pick] AsyncHandle refactor for performance and GCS FT.
  dashboard/modules/serve/tests/test_serve_agent.py
  doc/source/serve/doc_code/migration_example.py
  doc/source/serve/doc_code/production_fruit_example.py
  python/ray/dag/BUILD
  python/ray/dag/py_obj_scanner.py
  python/ray/dag/tests/test_py_obj_scanner.py
  python/ray/serve/BUILD
  python/ray/serve/_private/client.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_function_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/deployment_node.py
  python/ray/serve/_private/http_proxy.py
  python/ray/serve/_private/json_serde.py
  python/ray/serve/_private/router.py
  python/ray/serve/deployment_graph.py
  python/ray/serve/drivers.py
  python/ray/serve/handle.py
  python/ray/serve/tests/resources/test_modules.py
  python/ray/serve/tests/test_air_integrations.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_config_files/arithmetic.yaml
  python/ray/serve/tests/test_config_files/pizza.py
  python/ray/serve/tests/test_config_files/test_dag/basic_dag.py
  python/ray/serve/tests/test_config_files/test_dag/conditional_dag.py
  python/ray/serve/tests/test_config_files/test_dag/dir/subdir/a/add_and_sub.py
  python/ray/serve/tests/test_config_files/world.py
  python/ray/serve/tests/test_deployment_graph.py
  python/ray/serve/tests/test_deployment_graph_build.py
  python/ray/serve/tests/test_deployment_graph_classmethod.py
  python/ray/serve/tests/test_deployment_graph_config.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_json_serde.py
  python/ray/serve/tests/test_pipeline_dag_plot.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_standalone2.py
  python/ray/serve/tests/test_util.py
Labels: tests-ok, v2.0.0-pick

#27642 [cherry-pick][releases/2.0.0] Fix Ray Air Docs Install (#27501)
  doc/source/ray-air/getting-started.rst
Labels: v2.0.0-pick

#27643 [cherry-pick][releases/2.0.0] [AIR/docs] Adding Source Libraries (#27518)
  doc/source/ray-air/getting-started.rst
Labels: v2.0.0-pick

#27523 [AIR] Change `FeatureHasher` input schema
  python/ray/data/preprocessors/hasher.py
  python/ray/data/tests/test_preprocessors.py
Labels: tests-ok, v2.0.0-pick

#27599 [docs] Remove spam banner from master docs
  doc/source/conf.py
Labels: v2.0.0-pick

#27637 [Core] Fix `'NoneType' object has no attribute 'worker'` raised from Python deallocator.
  python/ray/tests/test_ray_shutdown.py
  python/ray/util/tracing/tracing_helper.py
Labels: v2.0.0-pick

#27644 [cherry-pick][releases/2.0.0][air/docs] Update Trainer documentation (#27481)
  doc/source/_toc.yml
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/trainer.rst
  doc/source/ray-air/tuner.rst
  doc/source/train/api.rst
  doc/source/train/config_guide.rst
  doc/source/train/dl_guide.rst
  doc/source/train/doc_code/gbdt_user_guide.py
  doc/source/train/doc_code/key_concepts.py
  doc/source/train/doc_code/xgboost_train_predict.py
  doc/source/train/examples/torch_data_prefetch_benchmark/benchmark_example.rst
  doc/source/train/faq.rst
  doc/source/train/gbdt.rst
  doc/source/train/getting-started.rst
  doc/source/train/images/train-specific.svg
  doc/source/train/key-concepts.rst
  doc/source/train/train.rst
  doc/source/train/user-guides.rst
  doc/source/tune/api_docs/overview.rst
  doc/source/tune/api_docs/syncing.rst
  doc/source/tune/api_docs/trainable.rst
  python/ray/air/config.py
  python/ray/train/_internal/checkpoint.py
  python/ray/train/data_parallel_trainer.py
  python/ray/train/examples/torch_quick_start.py
  python/ray/train/horovod/horovod_trainer.py
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/train/torch/torch_trainer.py
  python/ray/tune/syncer.py
Labels: v2.0.0-pick

#27649 [serve] Skip Gradio Installation on Windows
  ci/ci.sh
  python/requirements.txt
Labels: tests-ok

#27636 [core] Support external ray dashboard URL
  dashboard/head.py
  python/ray/_private/node.py
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/experimental/state/common.py
  python/ray/tests/test_ray_init.py
Labels: v2.0.0-pick

#27567 [core] Reconstruct manually freed objects
  python/ray/_private/serialization.py
  python/ray/exceptions.py
  python/ray/tests/test_advanced.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_reconstruction_2.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/protobuf/common.proto
Labels: tests-ok, v2.0.0-pick

#27627 [core] Fix job counter not working with storage namespace
  python/ray/tests/test_advanced_9.py
  src/ray/gcs/redis_client.cc
Labels: @author-action-required, v2.0.0-pick

#27655 [air/docs] Update train gettingstarted
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/tf_tabular_starter.py
Labels: tests-ok

#27575 [AIR] Make `Concatenator` deterministic
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/tests/test_preprocessors.py
Labels: tests-ok

#27664 [core] [cherry-pick] Fix how protocol is removed for external ray dashboard URL
  python/ray/_private/node.py
  python/ray/tests/test_ray_init.py
Labels: v2.0.0-pick

#27656 [cherry-pick][releases/2.0.0][AIR] Replace references of `to_torch` with `iter_torch_batches`
  doc/source/data/advanced-pipelines.rst
  doc/source/data/dataset.rst
  doc/source/data/doc_code/accessing_datasets.py
  doc/source/data/doc_code/key_concepts.py
  doc/source/ray-air/doc_code/hvd_trainer.py
  doc/source/ray-air/examples/torch_image_example.ipynb
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  doc/source/train/dl_guide.rst
  python/ray/air/examples/custom_trainer.py
  python/ray/air/examples/pytorch/torch_regression_example.py
  python/ray/air/session.py
  python/ray/train/base_trainer.py
  python/ray/train/horovod/horovod_trainer.py
  python/ray/train/torch/torch_trainer.py
  python/ray/train/train_loop_utils.py
Labels: v2.0.0-pick

#27645 [cherry-pick][releases/2.0.0] Land "[docs] Improve the "Why Ray" and "Why AIR" sections of the docs (#27480)" again
  README.rst
  doc/source/data/dataset-tensor-support.rst
  doc/source/index.md
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/ray-air.svg
  doc/source/ray-air/images/when-air.svg
  doc/source/ray-air/images/why-air-2.svg
  doc/source/ray-air/images/why-air.png
  doc/source/ray-air/images/why-air.svg
Labels: v2.0.0-pick

#27526 [serve] Make serve agent not blocking when GCS is down.
  ci/ci.sh
  dashboard/consts.py
  dashboard/modules/event/event_agent.py
  dashboard/modules/healthz/healthz_agent.py
  dashboard/modules/healthz/utils.py
  dashboard/modules/node/node_head.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/modules/serve/serve_agent.py
  dashboard/modules/serve/tests/test_serve_agent_fault_tolerane.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/optional_utils.py
  python/ray/_private/worker.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/http_state.py
  python/ray/serve/_private/storage/kv_store.py
  python/ray/serve/_private/utils.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_http_state.py
  python/ray/serve/tests/test_standalone.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_ray_cluster_with_external_redis.py
Labels: v2.0.0-pick

#27661 [docs] Trainer user guide should come before configuring datasets for trainer guide
  doc/source/_toc.yml
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/trainer.rst
  doc/source/ray-air/user-guides.rst
Labels: v2.0.0-pick

#27653 [Datasets] Delay expensive tensor extension type import until Parquet reading.
  doc/source/data/doc_code/tensor.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/datasource/parquet_datasource.py
Labels: @author-action-required, v2.0.0-pick

#27681 [pick] [Docs] Fix table width
  doc/source/_static/css/custom.css
Labels: v2.0.0-pick

#27623 Fix a few stale Datasets documentation in AIR
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/predictors.rst
Labels: @author-action-required, copyediting-required

#27659 [cherry pick][docs] Better defaults for installing Ray
  doc/source/ray-overview/installation.rst
Labels: v2.0.0-pick

#27269 Force grpcio to be >= 1.42.0 for python 3.10
  python/setup.py
Labels: tests-ok

#27671 [air] remove rllib dependency from tensorflow_predictor
  python/ray/train/tensorflow/tensorflow_predictor.py
Labels: v2.0.0-pick

#27674 [cherry-pick][serve] Make serve agent not blocking when GCS is down. (#27526)
  ci/ci.sh
  dashboard/consts.py
  dashboard/modules/event/event_agent.py
  dashboard/modules/healthz/healthz_agent.py
  dashboard/modules/healthz/utils.py
  dashboard/modules/node/node_head.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/reporter_head.py
  dashboard/modules/serve/serve_agent.py
  dashboard/modules/serve/tests/test_serve_agent_fault_tolerane.py
  dashboard/modules/snapshot/snapshot_head.py
  dashboard/optional_utils.py
  python/ray/_private/worker.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/http_state.py
  python/ray/serve/_private/storage/kv_store.py
  python/ray/serve/_private/utils.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_http_state.py
  python/ray/serve/tests/test_standalone.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_ray_cluster_with_external_redis.py
Labels: v2.0.0-pick

#27652 [core] Fix how protocol is removed for external ray dashboard URL
  python/ray/_private/node.py
  python/ray/tests/test_ray_init_2.py
Labels: v2.0.0-pick

#27604 [autoscaler] Remove deprecated fields from schema (#27040)
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/autoscaler/_private/util.py
  python/ray/autoscaler/local/development-example.yaml
  python/ray/autoscaler/ray-schema.json
  python/ray/tests/kuberay/test_autoscaling_config.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_autoscaler_yaml.py
  python/ray/tests/test_resource_demand_scheduler.py
  python/ray/tune/examples/tune-default.yaml
Labels: v2.0.0-pick

#27683 [pick] Force grpcio to be >= 1.42.0 for python 3.10 (#27269)
  python/setup.py
Labels: v2.0.0-pick

#27665 [cherry-pick][core] Fix job counter not working with storage namespace (#27627)
  python/ray/tests/test_advanced_9.py
  src/ray/gcs/redis_client.cc
Labels: v2.0.0-pick

#27581 Add maximum number of characters in logs output for jobs status message
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
  dashboard/modules/job/tests/test_utils.py
  dashboard/modules/job/utils.py
Labels: tests-ok, v2.0.0-pick

#27693 Add maximum number of characters in logs output for jobs status message
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
  dashboard/modules/job/tests/test_utils.py
  dashboard/modules/job/utils.py
Labels: v2.0.0-pick

#27607 [kubernetes][docs] Logging guide, networking info, migration guide, fixes.
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/migration-example.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/ray-cluster.log.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/xgboost-benchmark-autoscaler.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/xgboost-benchmark.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples/ml-example.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/getting-started.ipynb
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/images/AutoscalerOperator.svg
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/references.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/autoscaling.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/config.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/k8s-cluster-setup.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/kuberay-vs-legacy.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/logging.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/user-guides/networking.md
Labels: docs, copyediting-required

#27161 [RLlib] CRR framework torch by default.
  rllib/algorithms/crr/crr.py
Labels: @author-action-required, v2.0.0-pick

#27651 [Doc] [Serve] Nits/Edits on Performance Tuning page
  doc/source/serve/managing-deployments.md
  doc/source/serve/performance.md
Labels: copyediting-required

#27536 [Serve/Doc] Update http with serve user guide
  doc/source/_toc.yml
  doc/source/serve/http-adapters.md
  doc/source/serve/http-guide.md
  doc/source/serve/package-ref.md
  doc/source/serve/user-guide.md
Labels: @author-action-required, copyediting-required

#27510 [docs][Ray Clusters] Key Concepts page
  doc/source/cluster/cluster_under_construction/images/ray-cluster.svg
  doc/source/cluster/cluster_under_construction/key-concepts.rst
  doc/source/cluster/cluster_under_construction/ray-cluster.jpg
Labels: docs, infra, copyediting-required

#27712 [cherry-pick] [docs] Minor polish on AIR getting started page (#27696)
  README.rst
  doc/source/index.md
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/why-air-2.svg
Labels: v2.0.0-pick

#27687 [docs/air] remove xgboost/lightgbm references and move AIR toc
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/examples/ml-example.md
  doc/source/conf.py
  doc/source/custom_directives.py
  doc/source/ray-air/package-ref.rst
  doc/source/ray-core/examples/dask_xgboost/dask_xgboost.ipynb
  doc/source/ray-core/examples/dask_xgboost/dask_xgboost.py
  doc/source/ray-core/examples/modin_xgboost/modin_xgboost.ipynb
  doc/source/ray-core/examples/modin_xgboost/modin_xgboost.py
  doc/source/ray-more-libs/index.rst
  doc/source/ray-more-libs/lightgbm-ray.md
  doc/source/ray-more-libs/xgboost-ray.md
  doc/source/ray-references/api.rst
  doc/source/tune/tutorials/tune-checkpoints.rst
Labels: docs, infra

#27666 [core] Allow reuse of cluster address if Ray is not running
  python/ray/scripts/scripts.py
  python/ray/tests/test_cli.py
Labels: v2.0.0-pick

#27679 [Ray Clusters][docs] Restructuring Clusters API reference
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/job-submission-apis.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/ray-cluster-configuration.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/index.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-rest.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission-sdk.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission.rst
  doc/source/cluster/cluster_under_construction/references/autoscaler-sdk-api.rst
  doc/source/cluster/cluster_under_construction/references/index.md
  doc/source/cluster/cluster_under_construction/references/job-submission-apis.rst
Labels: docs, infra

#27672 [AIR] Replace references of `to_tf` with `iter_tf_batches`
  doc/source/data/dataset.rst
  doc/source/data/doc_code/accessing_datasets.py
  doc/source/ray-air/doc_code/tf_starter.py
  doc/source/ray-air/examples/tfx_tabular_train_to_serve.ipynb
  python/ray/air/examples/tf/tensorflow_autoencoder_example.py
  python/ray/air/examples/tf/tensorflow_regression_example.py
  python/ray/air/tests/test_keras_callback.py
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/train/tensorflow/train_loop_utils.py
Labels: tests-ok, v2.0.0-pick

#27676 [RLlib] Fix test_ope flakiness
  rllib/BUILD
  rllib/examples/env/cliff_walking_wall_env.py
  rllib/examples/policy/cliff_walking_wall_policy.py
  rllib/offline/estimators/fqe_torch_model.py
  rllib/offline/estimators/tests/test_dm_learning.py
  rllib/offline/estimators/tests/test_dr_learning.py
  rllib/offline/estimators/tests/test_ope.py
  rllib/offline/estimators/tests/utils.py
Labels: rllib

#27721 Fixing doc linter: broken links in ray-tracing.rst and ray-dag.rst
  doc/source/ray-core/ray-dag.rst
  doc/source/ray-observability/ray-tracing.rst
Labels: docs

#27579 [serve][doc] Update Serve API in tutorials
  doc/source/serve/doc_code/tutorial_batch.py
  doc/source/serve/doc_code/tutorial_pytorch.py
  doc/source/serve/doc_code/tutorial_sklearn.py
  doc/source/serve/doc_code/tutorial_tensorflow.py
  doc/source/serve/handle-guide.md
  doc/source/serve/index.md
  doc/source/serve/tutorials/batch.md
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/rllib.md
  doc/source/serve/tutorials/serve-ml-models.md
  doc/source/serve/tutorials/web-server-integration.md
  python/ray/serve/examples/doc/aiohttp/aiohttp_app.py
  python/ray/serve/examples/doc/aiohttp/aiohttp_deploy_serve.py
  python/ray/serve/examples/doc/tutorial_batch.py
Labels: serve, docs

#27723 [Ray Clusters][docs] Create new Running Apps on Ray Clusters section
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/index.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-jobs/job-submission.rst
  doc/source/cluster/cluster_under_construction/references/job-submission-apis.rst
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/autoscaling.md
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/index.md
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/job-submission/cli.rst
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/job-submission/index.md
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/job-submission/job-submission-overview.rst
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/job-submission/ray-client.rst
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/job-submission/rest.rst
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/job-submission/sdk.rst
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/monitoring-and-observability.md
Labels: docs, infra

#27353 [Datasets] Better error message for partition filtering if no file found
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#27431 [Cluster-launcher doc] revamp the vm part
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/getting-started.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/getting-started.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/references/ray-cluster-cli.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/community-supported-cluster-manager/index.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/installing-ray.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/add-your-own-cloud-provider.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/aws-cloud-watch.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/aws.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/aws.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/azure.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/azure.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/gcp.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/gcp.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/index.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/launching-clusters/on-premises.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/monitoring-and-observing-ray-cluster.rst
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/multi-tenancy-best-practices.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/running-ray-cluster-on-prem.rst
  doc/source/ray-observability/index.rst
Labels: docs, infra

#27751 [cherry-pick] [docs] Minor tweaks to AIR intro icons
  doc/source/ray-air/images/why-air-2.svg
Labels: v2.0.0-pick

#27732 [Doc] Add a cluster xgboost example for vm stack
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/xgboost-benchmark-autoscaler.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-kubernetes/configs/xgboost-benchmark.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/configs/xgboost-benchmark.yaml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/launching-ray-cluster.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/observe-your-app.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/running-job-via-job-submission.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/scale-your-job-with-autoscaling.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/learn-ray-cluster-basics/shutting-down-your-ray-cluster.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/ml-example.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-development/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-development/todo.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-production/index.md
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/examples/setting-up-ray-cluster-for-production/todo.md
Labels: docs, infra, copyediting-required

#27724 [docs] Revamp docs on observability for ray cluster apps
  doc/source/_toc.yml
  doc/source/cluster/cluster_under_construction/ray-clusters-on-vms/user-guides/monitoring-and-observing-ray-cluster.rst
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/monitoring-and-observability.md
  doc/source/cluster/cluster_under_construction/running-applications-on-ray-clusters/monitoring-and-observability.rst
  doc/source/ray-observability/ray-metrics.rst
Labels: docs, infra

#27762 2.0.0rc1 cherry pick: docs linkcheck fixes
  doc/source/cluster/ray-client.rst
  doc/source/ray-core/ray-dag.rst
  doc/source/ray-observability/ray-tracing.rst
Labels: v2.0.0-pick

#27215 [AIR] Improve preprocessor documentation
  doc/source/conf.py
  doc/source/ray-air/doc_code/preprocessors.py
  doc/source/ray-air/package-ref.rst
  doc/source/ray-air/preprocessors.rst
  python/ray/data/preprocessor.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/preprocessors/chain.py
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/preprocessors/encoder.py
  python/ray/data/preprocessors/hasher.py
  python/ray/data/preprocessors/imputer.py
  python/ray/data/preprocessors/normalizer.py
  python/ray/data/preprocessors/scaler.py
  python/ray/data/preprocessors/tokenizer.py
  python/ray/data/preprocessors/transformer.py
  python/ray/data/preprocessors/vectorizer.py
Labels: v2.0.0-pick

#27765 [Dataset] Pin _StatsActor to the driver node
  python/ray/data/_internal/stats.py
  python/ray/data/dataset_pipeline.py
Labels: v2.0.0-pick

#27763 [serve] Add an internal os env to turn the head node pin off.
  python/ray/serve/_private/api.py
  python/ray/serve/_private/constants.py
  python/ray/serve/controller.py
Labels: v2.0.0-pick

#27706 [serve][docs] Document lightweight config updates
  doc/source/serve/production.md
Labels: serve, docs

#27756 [docs] Revamp clusters section on job submission
  doc/source/cluster/key-concepts.rst
  doc/source/cluster/kubernetes/getting-started.ipynb
  doc/source/cluster/kubernetes/user-guides/autoscaling.md
  doc/source/cluster/references/index.md
  doc/source/cluster/running-applications/index.md
  doc/source/cluster/running-applications/job-submission/cli.rst
  doc/source/cluster/running-applications/job-submission/index.md
  doc/source/cluster/running-applications/job-submission/job-submission-overview.rst
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
  doc/source/cluster/running-applications/job-submission/quickstart.rst
  doc/source/cluster/running-applications/job-submission/sdk.rst
  doc/source/cluster/running-applications/monitoring-and-observability.rst
  doc/source/cluster/vms/getting-started.rst
Labels: docs, infra

#27768 [cherry-pick][releases/2.0.0][AIR] Replace references of to_tf with iter_tf_batches
  doc/source/data/dataset.rst
  doc/source/data/doc_code/accessing_datasets.py
  doc/source/ray-air/doc_code/tf_starter.py
  doc/source/ray-air/examples/tfx_tabular_train_to_serve.ipynb
  python/ray/air/examples/tf/tensorflow_autoencoder_example.py
  python/ray/air/examples/tf/tensorflow_regression_example.py
  python/ray/air/tests/test_keras_callback.py
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/train/tensorflow/train_loop_utils.py
Labels: v2.0.0-pick
