Repository ray-project/ray, pull requests merged in 2022-05, with the labels that each got.

#23829 [Enable gcs actor scheduler 1/n] Raylet and GCS schedulers share cluster_task_manager
  BUILD.bazel
  python/ray/tests/test_advanced_5.py
  src/ray/gcs/gcs_server/gcs_actor_distribution.cc
  src/ray/gcs/gcs_server/gcs_actor_distribution.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_based_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/gcs_server/test/raylet_based_actor_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_resource_data.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_2_test.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
Labels: @author-action-required

#24017 Adding support to wandb service
  python/ray/tune/integration/wandb.py
  python/requirements/ml/requirements_tune.txt
Labels: tune

#24385 [RLlib] Issue 24075: Better error message for Bandit MultiDiscrete (suggest using our wrapper).
  rllib/agents/bandit/bandit_tf_policy.py
  rllib/agents/bandit/bandit_torch_policy.py
Labels: tests-ok

#24369 [core] Fix the bug in task cancel hang.
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/normal_scheduling_queue.cc
  src/ray/core_worker/transport/normal_scheduling_queue.h
  src/ray/protobuf/core_worker.proto
Labels: @author-action-required

#24416 [Dashboard][K8s] Add toggle to enable showing node disk usage on K8s
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/tests/test_reporter.py
Labels: release-blocker, 1.13.0rc1-pick

#24417 [Serve] Unify Starlette and FastAPI JSON serialization stack
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/http_util.py
  python/ray/serve/tests/test_fastapi.py
  python/ray/serve/tests/test_util.py
  python/ray/serve/utils.py
Labels: @author-action-required

#24322 [Core] Batch `PinObjectIDs` requests from Raylet client
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/pull_manager.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: tests-ok

#24440 [Release branch PR][Dashboard][K8s] Add toggle to enable showing node disk usage on K8s …
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/tests/test_reporter.py
Labels: release-blocker, 1.13.0rc1-pick

#24404 [Serve] Add short-hand for pydantic http adapter
  doc/source/serve/http-servehandle.rst
  python/ray/serve/drivers.py
  python/ray/serve/tests/test_pipeline_driver.py
Labels: tests-ok

#24409 [core] Share channel with GcsClient.
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/grpc_client.h
Labels: @author-action-required

#24451 [Core] rename `PinObjectIDs` to `PinObjectID`
  doc/source/ray-contribute/debugging.rst
  src/mock/ray/raylet/node_manager.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: tests-ok

#24452 Fix flaky test_locality_aware_leasing_borrowed_objects
  python/ray/tests/test_scheduling.py
Labels: tests-ok

#24469 [Test] Add grace period to long running actor test failure
  release/long_running_tests/workloads/actor_deaths.py
Labels: @author-action-required

#24458 [core] Update metadata in options properly
  python/ray/_private/ray_option_utils.py
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/tests/test_basic.py
Labels: @author-action-required

#24265 [Serve] Reuse existing validation functions for Ray Serve config & bug fix
  python/ray/serve/config.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/tests/test_config.py
Labels: do-not-merge

#24450 [Core] fix inaccurate Raylet log message for aborting object creation
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/pull_manager.cc
Labels: tests-ok

#24249 [workflow] Update workflow docs
  doc/source/workflows/actors.rst
  doc/source/workflows/advanced.rst
  doc/source/workflows/basics.rst
  doc/source/workflows/comparison.rst
  doc/source/workflows/concepts.rst
  doc/source/workflows/events.rst
  doc/source/workflows/management.rst
  doc/source/workflows/metadata.rst
  doc/source/workflows/package-ref.rst
  python/ray/workflow/workflow_storage.py
Labels: @author-action-required

#24549 [Serve] Ensure SimpleSchemaIngress uses FastAPI custom serializers
  python/ray/serve/drivers.py
  python/ray/serve/tests/test_pipeline_driver.py
  python/ray/serve/utils.py
Labels: @author-action-required

#24398 Test the CSV read with column types specified
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#24490 [Workflow]Enable auto-config for persistent storage when connecting to existing cluster
  python/ray/_private/services.py
  python/ray/node.py
  python/ray/tests/test_storage.py
  python/ray/worker.py
  python/ray/workflow/tests/test_lifetime.py
  python/ray/workflow/tests/test_logging.py
  python/ray/workflow/tests/test_storage.py
Labels: @external-author-action-required

#24607 [Serve] Run health check in separate thread (#24560)
  python/ray/serve/common.py
  python/ray/serve/replica.py
  python/ray/serve/tests/test_regression.py
Labels: 1.13.0rc0-pick

#24576 [RLlib] AlphaStar config objects.
  rllib/agents/alpha_star/__init__.py
  rllib/agents/alpha_star/alpha_star.py
  rllib/agents/alpha_star/league_builder.py
  rllib/agents/alpha_star/tests/test_alpha_star.py
  rllib/agents/impala/impala.py
Labels: tests-ok

#23660 [scheduler][6] Integrate ray with syncer.
  .buildkite/pipeline.yml
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/tests/test_metrics_agent.py
  src/mock/ray/common/ray_syncer/ray_syncer.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/common/ray_config_def.h
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/test/ray_syncer_test.cc
  src/ray/common/test/syncer_service_e2e_test.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_resource_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/ray_syncer.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/grpc_client.h
  src/ray/rpc/grpc_server.cc
  src/ray/rpc/grpc_server.h
  src/ray/rpc/node_manager/node_manager_client.h
Labels: @author-action-required

#24522 [Doc] Add doc for usage stats collection
  dashboard/client/src/pages/dashboard/Dashboard.tsx
  doc/source/_toc.yml
  doc/source/cluster/usage-stats-data-ref.rst
  doc/source/cluster/usage-stats.rst
  doc/source/ray-core/package-ref.rst
  doc/source/ray-references/api.rst
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
Labels: tests-ok

#24676 [Cherry-pick] Fix check failure when DisconnectClient happens before AnnounceWorker…
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: 1.13.0rc0-pick

#24680 [Doc][Cherry pick] Add doc for usage stats collection (#24522)
  dashboard/client/src/pages/dashboard/Dashboard.tsx
  doc/source/_toc.yml
  doc/source/cluster/usage-stats-data-ref.rst
  doc/source/cluster/usage-stats.rst
  doc/source/ray-core/package-ref.rst
  doc/source/ray-references/api.rst
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
Labels: 1.13.0rc0-pick

#24670 [runtime env] Add debug prints to `serve:test_runtime_env` which is flaky
  python/ray/serve/tests/test_runtime_env.py
Labels: tests-ok

#24623 [core] Adjust worker OOM scores to prioritize the raylet during memory pressure
  python/ray/tests/test_advanced_9.py
  src/ray/common/ray_config_def.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: @author-action-required

#24524 [Serve] Add deployment graph cookbook
  doc/source/_toc.yml
  doc/source/serve/deployment-graph.md
  doc/source/serve/deployment-graph/chain_nodes_same_class_different_args.md
  doc/source/serve/deployment-graph/deployment-graph-e2e-tutorial.md
  doc/source/serve/deployment-graph/deployment-graph-user-guides.md
  doc/source/serve/doc_code/deployment_graph_same_class_different_args.py
  python/ray/serve/BUILD
Labels: @author-action-required

#24330 [core] Move reconnection to RPC layer for GCS client.
  BUILD.bazel
  python/ray/_private/services.py
  python/ray/tests/test_gcs_fault_tolerance.py
  src/mock/ray/gcs/gcs_client/gcs_client.h
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/test/gcs_client_reconnection_test.cc
  src/ray/rpc/client_call.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/grpc_client.h
Labels: @author-action-required

#24700 Don't show usage stats prompt in dashboard if prompt is disabled
  dashboard/client/src/api.ts
  dashboard/client/src/pages/dashboard/Dashboard.tsx
  dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: tests-ok

#24354 [Datasets] Add docs for bulk parquet read API and file meta providers
  doc/source/data/package-ref.rst
Labels: 1.13.0rc0-pick

#24741 [Core] Revert "[Core] Batch `PinObjectIDs` requests from Raylet client (#24322)" and "[Core] rename `PinObjectIDs` to `PinObjectID` (#24451)"
  doc/source/ray-contribute/debugging.rst
  src/mock/ray/raylet/node_manager.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/pull_manager.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: tests-ok

#24613 Make sure ray.init() works after AutoscalingCluster.start()
  python/ray/cluster_utils.py
  python/ray/serve/tests/test_standalone2.py
Labels: tests-ok

#24523 [dataset] Use polars for sorting
  python/ray/data/context.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/arrow_ops/__init__.py
  python/ray/data/impl/arrow_ops/transform_polars.py
  python/ray/data/impl/arrow_ops/transform_pyarrow.py
  python/ray/data/tests/test_optimize.py
  python/ray/data/tests/test_sort.py
  python/requirements.txt
  release/nightly_tests/dataset/sort.py
Labels: @author-action-required

#24483 [docs] Add initial AIR documentation
  doc/BUILD
  doc/source/_toc.yml
  doc/source/ray-air/deployment.rst
  doc/source/ray-air/doc_code/air_key_concepts.py
  doc/source/ray-air/doc_code/pytorch_starter.py
  doc/source/ray-air/doc_code/tf_starter.py
  doc/source/ray-air/doc_code/xgboost_starter.py
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/images/ai_runtime.jpg
  doc/source/ray-air/images/air_arch_1.png
  doc/source/ray-air/images/air_arch_2.png
  doc/source/ray-air/key-concepts.rst
  doc/source/ray-air/package-ref.rst
  doc/source/ray-more-libs/index.rst
  doc/source/ray-more-libs/ray-collective.rst
  doc/source/ray-references/api.rst
Labels: @author-action-required

#24564 [runtime env] Use asyncio lock to prevent concurrent virtualenv creation
  python/ray/_private/runtime_env/pip.py
  python/ray/tests/test_runtime_env_conda_and_pip_3.py
Labels: tests-ok

#24735 [Cherry-pick] Don't show usage stats prompt in dashboard if prompt is disabled (#24700)
  dashboard/client/src/api.ts
  dashboard/client/src/pages/dashboard/Dashboard.tsx
  dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: tests-ok, 1.13.0rc0-pick

#22818 [Core] Allow failing new tasks immediately while the actor is restarting
  java/test/src/main/java/io/ray/test/ExitActorTest.java
  java/test/src/main/java/io/ray/test/FailureTest.java
  java/test/src/main/java/io/ray/test/TestUtils.java
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_basic_5.py
  python/ray/tests/test_failure_4.py
  python/ray/tests/test_placement_group_2.py
  python/ray/tests/test_reconstruction.py
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
Labels: core-api-change-approval-required

#24800 [Datasets] Add example protocol for reading canned in-package example data.
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_dataset_formats.py
Labels: @author-action-required

#24628 [core][1/2] Resubscribe when GCS restarts for raylet.
  python/ray/tests/test_gcs_fault_tolerance.py
  src/mock/ray/raylet/node_manager.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: @author-action-required

#24829 [python3.10] build python310 wheels
  python/build-wheel-macos-arm64.sh
  python/build-wheel-macos.sh
  python/build-wheel-manylinux2014.sh
  python/build-wheel-windows.sh
  python/setup.py
Labels: tests-ok

#24852 [minor] Fix `black` version check in `ci/lint/format.sh`
  ci/lint/format.sh
Labels: @author-action-required

#24704 [Datasets] Change `range_arrow()` API to `range_table()`
  doc/source/data/getting-started.rst
  doc/source/data/package-ref.rst
  doc/source/data/random-access.rst
  doc/source/data/transforming-datasets.rst
  python/ray/data/__init__.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/grouped_dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_dataset_pipeline.py
  python/ray/data/tests/test_random_access.py
  python/ray/data/tests/test_raydp_dataset.py
  python/ray/data/tests/test_sort.py
  release/nightly_tests/dataset/dataset_random_access.py
Labels: @author-action-required, datasets

#24752 [Datasets] Support tensor columns in `to_tf` and `to_torch`.
  doc/source/data/dataset-tensor-support.rst
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
  python/ray/ml/utils/torch_utils.py
Labels: @author-action-required

#24778 [ci/docs] Add doc maintainer to CODEOWNERs for doc
  .github/CODEOWNERS
Labels: @author-action-required

#24774 [ci/release] Add CODEOWNERs for Ray release test package
  .github/CODEOWNERS
Labels: @author-action-required

#24672 [Datasets] Map progress bar title; pretty repr for rows.
  python/ray/data/impl/compute.py
  python/ray/data/impl/plan.py
  python/ray/data/row.py
Labels: @author-action-required

#23346 [Datasets] Add basic data ecosystem overview, user guide links, other data processing options card.
  doc/source/data/dataset.rst
Labels: @author-action-required

#24859 [python3.10] Build py310 images
  .buildkite/pipeline.yml
  ci/build/build-docker-images.py
  docker/base-deps/Dockerfile
  docker/retag-lambda/python_versions.txt
Labels: tests-ok

#24147 [Core] Remove multiple core workers in one process 1/n.
  cpp/src/ray/util/process_helper.cc
  java/api/src/main/java/io/ray/api/Ray.java
  java/api/src/main/java/io/ray/api/runtime/RayRuntime.java
  java/performance_test/src/main/java/io/ray/performancetest/test/ActorPerformanceTestBase.java
  java/performance_test/src/main/java/io/ray/performancetest/test/ActorPerformanceTestCase1.java
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/ConcurrencyGroupImpl.java
  java/runtime/src/main/java/io/ray/runtime/DefaultRayRuntimeFactory.java
  java/runtime/src/main/java/io/ray/runtime/RayDevRuntime.java
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/runtime/src/main/java/io/ray/runtime/RayRuntimeInternal.java
  java/runtime/src/main/java/io/ray/runtime/RayRuntimeProxy.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/context/LocalModeWorkerContext.java
  java/runtime/src/main/java/io/ray/runtime/context/NativeWorkerContext.java
  java/runtime/src/main/java/io/ray/runtime/context/WorkerContext.java
  java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskSubmitter.java
  java/runtime/src/main/java/io/ray/runtime/task/TaskExecutor.java
  java/runtime/src/main/java/io/ray/runtime/util/MethodUtils.java
  java/runtime/src/main/java/io/ray/runtime/utils/parallelactor/ParallelActorContextImpl.java
  java/runtime/src/main/java/io/ray/runtime/utils/parallelactor/ParallelActorExecutorImpl.java
  java/runtime/src/main/resources/ray.default.conf
  java/runtime/src/test/java/io/ray/runtime/functionmanager/FunctionManagerTest.java
  java/serve/src/main/java/io/ray/serve/HttpProxy.java
  java/test.sh
  java/test/src/main/java/io/ray/test/ActorHandleReferenceCountTest.java
  java/test/src/main/java/io/ray/test/ClassLoaderTest.java
  java/test/src/main/java/io/ray/test/DefaultActorLifetimeTest.java
  java/test/src/main/java/io/ray/test/ExitActorTest.java
  java/test/src/main/java/io/ray/test/ExitActorTest2.java
  java/test/src/main/java/io/ray/test/FailureTest.java
  java/test/src/main/java/io/ray/test/JobConfigTest.java
  java/test/src/main/java/io/ray/test/KillActorTest.java
  java/test/src/main/java/io/ray/test/MultiThreadingTest.java
  java/test/src/main/java/io/ray/test/RuntimeEnvTest.java
  java/test/src/main/java/io/ray/test/TestUtils.java
  java/test/src/main/resources/ray.conf
  python/ray/_raylet.pyx
  python/ray/job_config.py
  python/ray/tests/test_advanced_8.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/core_worker_process.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/object_manager/common.h
  src/ray/protobuf/gcs.proto
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: Ray 2.0

#24544 [Placement group] Update the old placement group API usage to the new scheduling_strategy based API
  doc/source/ray-core/actors/scheduling.rst
  doc/source/ray-core/doc_code/original_resource_unavailable_example.py
  doc/source/ray-core/doc_code/placement_group_capture_child_tasks_example.py
  doc/source/ray-core/package-ref.rst
  doc/source/ray-core/placement-group.rst
  doc/source/ray-core/tasks/scheduling.rst
  python/ray/util/scheduling_strategies.py
Labels: @author-action-required

#24929 [Cherry-pick] Add necessary build changes to build python3.10 docker images
  .buildkite/pipeline.yml
  ci/build/build-docker-images.py
  docker/base-deps/Dockerfile
  docker/retag-lambda/python_versions.txt
Labels: 1.13.0rc0-pick

#24791 Fix pull manager deadlock due to object reconstruction
  python/ray/tests/test_object_manager.py
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/test/pull_manager_test.cc
Labels: tests-ok

#24847 [State Observability] Support output formatting
  python/ray/_private/services.py
  python/ray/experimental/state/state_cli.py
  python/ray/tests/test_state_api.py
Labels: @author-action-required

#24714 [Java][API CHANGE] Rename mode `SINGLE_PROCESS` to `LOCAL`
  java/api/src/main/java/io/ray/api/runtimecontext/RuntimeContext.java
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/DefaultRayRuntimeFactory.java
  java/runtime/src/main/java/io/ray/runtime/config/RayConfig.java
  java/runtime/src/main/java/io/ray/runtime/config/RunMode.java
  java/runtime/src/main/java/io/ray/runtime/context/RuntimeContextImpl.java
  java/runtime/src/main/resources/ray.default.conf
  java/serve/src/main/java/io/ray/serve/RayServeMetrics.java
  java/test.sh
  java/test/src/main/java/io/ray/test/LocalModeTest.java
  java/test/src/main/java/io/ray/test/MultiThreadingTest.java
  java/test/src/main/java/io/ray/test/PlasmaFreeTest.java
  java/test/src/main/java/io/ray/test/RayAlterSuiteListener.java
  java/test/src/main/java/io/ray/test/TestUtils.java
Labels: Ray 2.0

#24933 [tune] Fix `has_resources_for_trial`, leading to trials stuck in PENDING mode
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/utils/placement_groups.py
Labels: 1.13.0rc0-pick

#24951 [Pubsub] raise exception when publishing fails
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/log_monitor.py
  python/ray/_private/utils.py
Labels: tests-ok

#24989 [docs] Document log to driver = False
  doc/source/ray-observability/ray-logging.rst
Labels: @author-action-required

#24987 Revamp the Saving Datasets user guide
  doc/source/data/doc_code/saving_datasets.py
  doc/source/data/saving-datasets.rst
Labels: 1.13.0rc1-pick

#24932 [Datasets] Add FAQ to Datasets docs.
  doc/source/_toc.yml
  doc/source/data/dataset.rst
  doc/source/data/faq.rst
Labels: @author-action-required, 1.13.0rc1-pick

#24997 Update pip donwload test.sh
  release/util/pip_download_test.sh
Labels: 1.13.0rc1-pick

#24991 [python3.10] build python310 wheels for 1.13.rc1 (#24829)
  python/build-wheel-macos-arm64.sh
  python/build-wheel-macos.sh
  python/build-wheel-manylinux2014.sh
  python/setup.py
Labels: 1.13.0rc1-pick

#24949 Revamp the Datasets API docstrings
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
Labels: 1.13.0rc1-pick

#24812 [Datasets] [Tensor Story - 1/2] Automatically provide tensor views to UDFs and infer tensor blocks for pure-tensor datasets.
  doc/source/data/dataset-tensor-support.rst
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/numpy_datasource.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/block_batching.py
  python/ray/data/impl/delegating_block_builder.py
  python/ray/data/impl/output_buffer.py
  python/ray/data/impl/pandas_block.py
  python/ray/data/impl/simple_block.py
  python/ray/data/impl/table_block.py
  python/ray/data/random_access_dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
Labels: @author-action-required, 1.13.0rc1-pick

#24713 [Serve][Doc] Split core-apis to key concepts and user guide
  doc/source/_toc.yml
  doc/source/serve/deploying-serve.md
  doc/source/serve/deployment-graph.md
  doc/source/serve/deployment-graph/deployment-graph-e2e-tutorial.md
  doc/source/serve/deployment-graph/deployment-graph-user-guides.md
  doc/source/serve/doc_code/create_deployment.py
  doc/source/serve/doc_code/key-concepts-deployment-graph.py
  doc/source/serve/faq.md
  doc/source/serve/getting_started.md
  doc/source/serve/handle-guide.md
  doc/source/serve/handling-dependencies.md
  doc/source/serve/http-adapters.md
  doc/source/serve/http-guide.md
  doc/source/serve/http-servehandle.md
  doc/source/serve/index.md
  doc/source/serve/key-concepts.md
  doc/source/serve/managing-deployments.md
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/pytorch.md
  doc/source/serve/tutorials/rllib.md
  doc/source/serve/tutorials/sklearn.md
  doc/source/serve/tutorials/tensorflow.md
  doc/source/serve/user-guide.md
Labels: @author-action-required

#25038 [Datasets] Note that explicit resource allocation is experimental, fix typos
  doc/source/data/key-concepts.rst
Labels: 1.13.0rc1-pick

#25031 Revert "Revert "[Datasets] [Tensor Story - 1/2] Automatically provide tensor views to UDFs and infer tensor blocks for pure-tensor datasets.""
  doc/source/data/dataset-tensor-support.rst
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/numpy_datasource.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/block_batching.py
  python/ray/data/impl/delegating_block_builder.py
  python/ray/data/impl/output_buffer.py
  python/ray/data/impl/pandas_block.py
  python/ray/data/impl/simple_block.py
  python/ray/data/impl/table_block.py
  python/ray/data/random_access_dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/ml/utils/check_ingest.py
Labels: tests-ok

#25032 [Core][Python 3.10] fix get_module in the interactive mode.
  python/ray/includes/function_descriptor.pxi
Labels: 1.13.0rc1-pick

#24600 [Core] Lazy subscribe to actor's state
  python/ray/tests/test_actor.py
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/actor_manager_test.cc
Labels: @author-action-required

#25042 [Core][Python 3.10] fix get_module in the interactive mode. #25032
  python/ray/includes/function_descriptor.pxi
Labels: 1.13.0rc1-pick

#25036 Fix range_arrow(), which is replaced by range_table()
  doc/source/data/creating-datasets.rst
  doc/source/data/doc_code/creating_datasets.py
Labels: 1.13.0rc1-pick

#25033 Revamp the Transforming Datasets user guide
  doc/source/data/doc_code/transforming_datasets.py
  doc/source/data/saving-datasets.rst
  doc/source/data/transforming-datasets.rst
Labels: 1.13.0rc1-pick

#25049 Fix release version in tests_wheels.py
  release/ray_release/tests/test_wheels.py
Labels: 1.13.0rc1-pick

#25052 Drop python 3.6 from Windows build (#24756)
  python/build-wheel-windows.sh
Labels: 1.13.0rc1-pick

#25066 [RLlib] MAML config objects.
  rllib/algorithms/maml/__init__.py
  rllib/algorithms/maml/maml.py
  rllib/algorithms/maml/tests/test_maml.py
Labels: tests-ok

#24719 [runtime env] Add temporary URI reference to prevent URI deletion before job starts
  dashboard/modules/job/job_head.py
  dashboard/modules/job/tests/test_sdk.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/experimental/internal_kv.py
  python/ray/ray_constants.py
  python/ray/tests/test_runtime_env_working_dir_3.py
  python/ray/util/client/__init__.py
  python/ray/util/client/api.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/worker.py
  src/ray/common/runtime_env_manager.cc
  src/ray/common/runtime_env_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/runtime_env_handler.cc
  src/ray/gcs/gcs_server/runtime_env_handler.h
  src/ray/protobuf/gcs_service.proto
  src/ray/protobuf/ray_client.proto
  src/ray/raylet/agent_manager.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: @author-action-required

#24203 [Data] Add partitioning classes to Data API reference
  doc/source/data/package-ref.rst
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/partitioning.py
Labels: 1.13.0rc1-pick

#24994 [Docs] Add "Examples" block to Ray Data landing page, and consistently use bold font
  doc/source/data/dataset.rst
Labels: docs

#23684 Ignore previous tasks before submitting ones via `map` and `map_unordered`
  python/ray/tests/test_actor_pool.py
  python/ray/util/actor_pool.py
Labels: QS

#25004 Use OBOD report as the source of truth of in-memory locations of object
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/test/reference_count_test.cc
Labels: tests-ok

#24754 [Serve][Deployment Graph][Perf] Add minimal executor DAGNode
  python/ray/experimental/dag/py_obj_scanner.py
  python/ray/serve/deployment_executor_node.py
  python/ray/serve/deployment_function_executor_node.py
  python/ray/serve/deployment_method_executor_node.py
  python/ray/serve/pipeline/api.py
  python/ray/serve/pipeline/deployment_function_node.py
  python/ray/serve/pipeline/deployment_method_node.py
  python/ray/serve/pipeline/deployment_node.py
  python/ray/serve/pipeline/generate.py
  python/ray/serve/pipeline/json_serde.py
  python/ray/serve/pipeline/tests/test_deployment_node.py
  python/ray/serve/pipeline/tests/test_generate.py
  python/ray/serve/tests/test_pipeline_dag.py
Labels: tests-ok, flaky-test

#24767 [workflow] Fast workflow indexing
  python/ray/workflow/api.py
  python/ray/workflow/common.py
  python/ray/workflow/execution.py
  python/ray/workflow/tests/test_workflow_indexing.py
  python/ray/workflow/workflow_access.py
  python/ray/workflow/workflow_storage.py
Labels: @author-action-required

#25077 [tune] Add annotations/set scope for Tune classes
  doc/source/tune/api_docs/trainable.rst
  python/ray/tune/callback.py
  python/ray/tune/checkpoint_manager.py
  python/ray/tune/error.py
  python/ray/tune/function_runner.py
  python/ray/tune/insufficient_resources_manager.py
  python/ray/tune/logger.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/resources.py
  python/ray/tune/sample.py
  python/ray/tune/schedulers/async_hyperband.py
  python/ray/tune/schedulers/hb_bohb.py
  python/ray/tune/schedulers/hyperband.py
  python/ray/tune/schedulers/median_stopping_rule.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/schedulers/resource_changing_scheduler.py
  python/ray/tune/schedulers/trial_scheduler.py
  python/ray/tune/suggest/basic_variant.py
  python/ray/tune/suggest/repeater.py
  python/ray/tune/suggest/search.py
  python/ray/tune/suggest/search_generator.py
  python/ray/tune/suggest/suggestion.py
  python/ray/tune/suggest/variant_generator.py
  python/ray/tune/sync_client.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_checkpoint_manager.py
  python/ray/tune/tests/test_integration_wandb.py
  python/ray/tune/tests/test_progress_reporter.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tests/test_resource_updater.py
  python/ray/tune/tests/test_trial_runner_callbacks.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/trial.py
  python/ray/tune/trial_runner.py
  python/ray/tune/utils/log.py
  python/ray/tune/utils/placement_groups.py
  python/ray/tune/utils/resource_updater.py
  python/ray/tune/utils/serialization.py
  python/ray/tune/utils/trainable.py
  python/ray/tune/web_server.py
  rllib/agents/callbacks.py
Labels: @author-action-required

#25169 [releases/1.13.0] Update links to nightly wheels
  ci/env/install-dependencies.sh
  doc/source/cluster/config.rst
  doc/source/ray-contribute/development.rst
  doc/source/ray-core/handling-dependencies.rst
  doc/source/ray-observability/ray-metrics.rst
  doc/source/ray-overview/installation.rst
  python/ray/_private/utils.py
  python/ray/autoscaler/aws/defaults.yaml
  python/ray/autoscaler/aws/example-full-legacy.yaml
  python/ray/autoscaler/aws/example-full.yaml
  python/ray/autoscaler/aws/example-gpu-docker.yaml
  python/ray/autoscaler/azure/defaults.yaml
  python/ray/autoscaler/azure/example-full-legacy.yaml
  python/ray/autoscaler/azure/example-full.yaml
  python/ray/autoscaler/azure/example-gpu-docker.yaml
  python/ray/autoscaler/gcp/defaults.yaml
  python/ray/autoscaler/gcp/example-full.yaml
  python/ray/autoscaler/gcp/example-gpu-docker.yaml
  python/ray/autoscaler/gcp/tpu.yaml
  python/ray/autoscaler/local/example-full.yaml
  python/ray/autoscaler/local/example-minimal-automatic.yaml
  python/ray/autoscaler/local/example-minimal-manual.yaml
  python/ray/nightly-wheels.yaml
  python/ray/tests/test_cli_patterns/test_no_head.yaml
  python/ray/tests/test_cli_patterns/test_no_workers.yaml
  python/ray/tests/test_runtime_env.py
  python/ray/train/examples/horovod/horovod-cluster.yaml
  python/ray/train/examples/transformers/cluster.yaml
  release/ray_release/tests/test_wheels.py
Labels: release-blocker, @author-action-required

#25041 Remove MLDataset
  python/ray/tests/BUILD
  python/ray/tests/test_mldataset.py
  python/ray/util/data/__init__.py
  python/ray/util/data/dataset.py
  python/ray/util/data/examples/__init__.py
  python/ray/util/data/interface.py
  python/ray/util/data/parquet.py
  python/requirements/ml/requirements_upstream.txt
Labels: tests-ok, Ray 2.0

#25057 Revert "Revert "Revert "[Datasets] [Tensor Story - 1/2] Automatically provide tensor views to UDFs and infer tensor blocks for pure-tensor datasets."""
  doc/source/data/dataset-tensor-support.rst
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/numpy_datasource.py
  python/ray/data/impl/arrow_block.py
  python/ray/data/impl/block_batching.py
  python/ray/data/impl/delegating_block_builder.py
  python/ray/data/impl/output_buffer.py
  python/ray/data/impl/pandas_block.py
  python/ray/data/impl/simple_block.py
  python/ray/data/impl/table_block.py
  python/ray/data/random_access_dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/ml/utils/check_ingest.py
Labels: tests-ok

#25153 Revert "Revert "[Java] Remove RayRuntimeInternal class (#25016)" (#25…
  java/runtime/src/main/java/io/ray/runtime/AbstractRayRuntime.java
  java/runtime/src/main/java/io/ray/runtime/ConcurrencyGroupImpl.java
  java/runtime/src/main/java/io/ray/runtime/DefaultRayRuntimeFactory.java
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/runtime/src/main/java/io/ray/runtime/RayRuntimeInternal.java
  java/runtime/src/main/java/io/ray/runtime/actor/NativeActorHandle.java
  java/runtime/src/main/java/io/ray/runtime/context/RuntimeContextImpl.java
  java/runtime/src/main/java/io/ray/runtime/object/NativeObjectStore.java
  java/runtime/src/main/java/io/ray/runtime/object/ObjectRefImpl.java
  java/runtime/src/main/java/io/ray/runtime/runner/worker/DefaultWorker.java
  java/runtime/src/main/java/io/ray/runtime/task/ArgumentsBuilder.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskExecutor.java
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskSubmitter.java
  java/runtime/src/main/java/io/ray/runtime/task/NativeTaskExecutor.java
  java/runtime/src/main/java/io/ray/runtime/task/TaskExecutor.java
  java/runtime/src/main/java/io/ray/runtime/util/MethodUtils.java
  java/runtime/src/main/java/io/ray/runtime/utils/parallelactor/ParallelActorContextImpl.java
  java/runtime/src/main/java/io/ray/runtime/utils/parallelactor/ParallelActorExecutorImpl.java
  java/test/src/main/java/io/ray/test/TestUtils.java
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.h
Labels: Ray 2.0

#25171 [core] Don't adjust OOM score for IO workers
  src/ray/raylet/worker_pool.cc
Labels: do-not-merge

#25188 Clean up docstyle in data, ml, and tune packages
  python/ray/data/dataset.py
  python/ray/ml/checkpoint.py
  python/ray/ml/predictors/integrations/lightgbm/lightgbm_predictor.py
  python/ray/ml/predictors/integrations/sklearn/sklearn_predictor.py
  python/ray/ml/predictors/integrations/torch/torch_predictor.py
  python/ray/ml/predictors/integrations/xgboost/xgboost_predictor.py
  python/ray/ml/preprocessor.py
  python/ray/ml/utils/remote_storage.py
  python/ray/ml/utils/torch_utils.py
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/automl/genetic_searcher.py
  python/ray/tune/automl/search_policy.py
  python/ray/tune/automl/search_space.py
  python/ray/tune/automlboard/backend/collector.py
  python/ray/tune/automlboard/common/utils.py
  python/ray/tune/integration/mlflow.py
  python/ray/tune/integration/wandb.py
  python/ray/tune/schedulers/__init__.py
  python/ray/tune/stopper.py
  python/ray/tune/suggest/__init__.py
  python/ray/tune/trainable.py
Labels: tests-ok, @author-action-required

#24747 [core] Remove gcs addr updater in core worker.
  BUILD.bazel
  python/ray/cluster_utils.py
  python/ray/node.py
  python/ray/tests/test_scheduling_2.py
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/gcs_server_address_updater.cc
  src/ray/core_worker/gcs_server_address_updater.h
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
  src/ray/util/process.cc
  src/ray/util/util_test.cc
Labels: @author-action-required

#25257 Pin protobuf to < 4
  python/requirements.txt
  python/setup.py
Labels: release-blocker

#25192 [core] Fix bug in spilling objects that have empty data field
  python/ray/external_storage.py
  python/ray/tests/test_object_spilling_3.py
Labels: @author-action-required

#25078 [RLlib] A2/3C policy sub-classing schema.
  rllib/agents/a3c/a3c.py
  rllib/agents/a3c/a3c_tf_policy.py
  rllib/agents/a3c/a3c_torch_policy.py
  rllib/agents/a3c/tests/test_a2c.py
  rllib/agents/ppo/ppo_tf_policy.py
  rllib/policy/tf_mixins.py
  rllib/utils/typing.py
Labels: tests-ok

#24967 [RLlib] Vectorized envs: Gracefully handle sub-environments failing by restarting them (if configured so).
  rllib/BUILD
  rllib/agents/tests/test_trainer.py
  rllib/agents/trainer.py
  rllib/agents/trainer_config.py
  rllib/env/base_env.py
  rllib/env/multi_agent_env.py
  rllib/env/remote_base_env.py
  rllib/env/tests/test_env_with_subprocess.py
  rllib/env/tests/test_external_env.py
  rllib/env/tests/test_external_multi_agent_env.py
  rllib/env/vector_env.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/__init__.py
  rllib/evaluation/tests/test_envs_that_crash.py
  rllib/evaluation/worker_set.py
  rllib/examples/env/cartpole_crashing.py
  rllib/policy/policy.py
  rllib/tests/test_nested_observation_spaces.py
  rllib/tests/test_rllib_train_and_evaluate.py
  rllib/tuned_examples/pg/cartpole-crashing-pg.yaml
  rllib/tuned_examples/pg/cartpole-crashing-with_remote-envs-pg.yaml
  rllib/utils/pre_checks/env.py
Labels: tests-ok

#25255 [RLlib] MADDPG TrainerConfig objects.
  rllib/algorithms/ddpg/tests/test_ddpg.py
  rllib/algorithms/maddpg/__init__.py
  rllib/algorithms/maddpg/maddpg.py
  rllib/algorithms/maddpg/tests/test_maddpg.py
Labels: tests-ok

#25184 [State Observability] Improve existing state output
  python/ray/experimental/state/common.py
  python/ray/tests/test_state_api.py
Labels: @author-action-required

#25266 [data] Dataset pipeline window by bytes fails when read fusion disabled
  python/ray/data/impl/lazy_block_list.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: tests-ok

#25264 [data] Fix byte size calculation for non-trivial tensors
  python/ray/data/datasource/datasource.py
  python/ray/data/tests/test_dataset.py
Labels: tests-ok

#25263 [data] [API] Add max_epoch argument to iter_epochs() for AIR
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: tests-ok

#25265 [data] Fix pipeline pre-repeat caching, and improve the documentation
  doc/source/data/advanced-pipelines.rst
  python/ray/data/impl/plan.py
  python/ray/data/impl/stats.py
  python/ray/data/tests/test_stats.py
Labels: tests-ok

#25267 [data] [API] Remove unnecessary public argument in `fully_executed()`
  python/ray/data/dataset.py
  python/ray/data/impl/pipeline_executor.py
  python/ray/data/tests/test_optimize.py
Labels: tests-ok
