Repository ray-project/ray, pull requests merged in 2023-10, with the labels that each got.

#39958 Add `ray start --runtime-env-agent-port`. (#39919)
  python/ray/_private/parameter.py
  python/ray/scripts/scripts.py
Labels: v2.7.1-pick

#39756 [jobs] Add `entrypoint_memory` argument
  dashboard/modules/job/cli.py
  dashboard/modules/job/common.py
  dashboard/modules/job/job_agent.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/sdk.py
  dashboard/modules/job/tests/test_backwards_compatibility.py
  dashboard/modules/job/tests/test_cli.py
  dashboard/modules/job/tests/test_cli_integration.py
  dashboard/modules/job/tests/test_common.py
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/job/tests/test_job_manager.py
  doc/source/cluster/running-applications/job-submission/sdk.rst
  python/ray/core/generated/gcs_pb2.py
  src/ray/protobuf/gcs.proto
Labels: tests-ok

#40011 [train] Fix local storage path for windows (#39951)
  ci/ci.sh
  python/ray/train/BUILD
  python/ray/train/_internal/storage.py
  python/ray/train/tests/test_minimal.py
  python/ray/train/tests/test_windows.py
Labels: v2.7.1-pick

#38426 Prometheus health check
  dashboard/modules/metrics/metrics_head.py
Labels: @external-author-action-required

#40028 [tune] Fix `Trial.node_ip` property
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/experiment/trial.py
Labels: v2.7.1-pick

#40050 [ci][clusters] Adjust timeout for gcp_cluster_launcher_full #40036
  release/release_tests.yaml
Labels: v2.7.1-pick

#40052 [cherry-pick][tune] Fix `Trial.node_ip` property (#40028)
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/experiment/trial.py
Labels: v2.7.1-pick

#40058 Fix Cluster UI #39924
  dashboard/client/src/pages/node/NodeRow.tsx
Labels: v2.7.1-pick

#40077 [cherry-pick] Fix Overview Page UI will crash Issue
  dashboard/client/src/components/AutoscalerStatusCards.tsx
Labels: v2.7.1-pick

#36726 [RLlib contrib] TD3
  .buildkite/pipeline.ml.yml
  rllib_contrib/td3/README.md
  rllib_contrib/td3/examples/td3_pendulum_v1.py
  rllib_contrib/td3/pyproject.toml
  rllib_contrib/td3/requirements.txt
  rllib_contrib/td3/src/rllib_td3/td3/__init__.py
  rllib_contrib/td3/src/rllib_td3/td3/td3.py
  rllib_contrib/td3/tests/test_td3.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36666 [RLlib-contrib] Policy Gradient
  .buildkite/pipeline.ml.yml
  rllib_contrib/pg/README.md
  rllib_contrib/pg/examples/pg_cartpole_v1.py
  rllib_contrib/pg/pyproject.toml
  rllib_contrib/pg/requirements.txt
  rllib_contrib/pg/src/rllib_pg/pg/__init__.py
  rllib_contrib/pg/src/rllib_pg/pg/pg.py
  rllib_contrib/pg/src/rllib_pg/pg/pg_tf_policy.py
  rllib_contrib/pg/src/rllib_pg/pg/pg_torch_policy.py
  rllib_contrib/pg/src/rllib_pg/pg/utils.py
  rllib_contrib/pg/tests/test_pg.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36682 [RLlib-contrib] QMIX
  .buildkite/pipeline.ml.yml
  rllib_contrib/qmix/README.md
  rllib_contrib/qmix/examples/qmix_two_step_game.py
  rllib_contrib/qmix/pyproject.toml
  rllib_contrib/qmix/requirements.txt
  rllib_contrib/qmix/src/rllib_qmix/qmix/__init__.py
  rllib_contrib/qmix/src/rllib_qmix/qmix/mixers.py
  rllib_contrib/qmix/src/rllib_qmix/qmix/model.py
  rllib_contrib/qmix/src/rllib_qmix/qmix/qmix.py
  rllib_contrib/qmix/src/rllib_qmix/qmix/qmix_policy.py
  rllib_contrib/qmix/tests/test_qmix.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36688 [RLlib-Contrib] Simple Q
  .buildkite/pipeline.ml.yml
  rllib_contrib/simple_q/README.md
  rllib_contrib/simple_q/examples/simple_q_cartpole_v1.py
  rllib_contrib/simple_q/pyproject.toml
  rllib_contrib/simple_q/requirements.txt
  rllib_contrib/simple_q/src/rllib_simple_q/simple_q/__init__.py
  rllib_contrib/simple_q/src/rllib_simple_q/simple_q/simple_q.py
  rllib_contrib/simple_q/src/rllib_simple_q/simple_q/simple_q_tf_policy.py
  rllib_contrib/simple_q/src/rllib_simple_q/simple_q/simple_q_torch_policy.py
  rllib_contrib/simple_q/src/rllib_simple_q/simple_q/utils.py
  rllib_contrib/simple_q/tests/test_repro_simple_q.py
  rllib_contrib/simple_q/tests/test_simple_q.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36596 [RLlib-contrib] APEX DPPG
  .buildkite/pipeline.ml.yml
  rllib_contrib/TOC.md
  rllib_contrib/apex_ddpg/README.md
  rllib_contrib/apex_ddpg/examples/apex_ddpg_pendulum_v1.py
  rllib_contrib/apex_ddpg/pyproject.toml
  rllib_contrib/apex_ddpg/requirements.txt
  rllib_contrib/apex_ddpg/src/rllib_apex_ddpg/apex_ddpg/__init__.py
  rllib_contrib/apex_ddpg/src/rllib_apex_ddpg/apex_ddpg/apex_ddpg.py
  rllib_contrib/apex_ddpg/tests/test_apex_ddpg.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36710 [RLlib-contrib] SlateQ
  .buildkite/pipeline.ml.yml
  rllib_contrib/slate_q/README.md
  rllib_contrib/slate_q/examples/recommender_system_with_recsim_and_slateq.py
  rllib_contrib/slate_q/pyproject.toml
  rllib_contrib/slate_q/requirements.txt
  rllib_contrib/slate_q/src/rllib_slate_q/env/__init__.py
  rllib_contrib/slate_q/src/rllib_slate_q/env/recommender_system_envs_with_recsim.py
  rllib_contrib/slate_q/src/rllib_slate_q/slate_q/__init__.py
  rllib_contrib/slate_q/src/rllib_slate_q/slate_q/slateq.py
  rllib_contrib/slate_q/src/rllib_slate_q/slate_q/slateq_tf_model.py
  rllib_contrib/slate_q/src/rllib_slate_q/slate_q/slateq_tf_policy.py
  rllib_contrib/slate_q/src/rllib_slate_q/slate_q/slateq_torch_model.py
  rllib_contrib/slate_q/src/rllib_slate_q/slate_q/slateq_torch_policy.py
  rllib_contrib/slate_q/tests/test_slateq.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36662 [RLlib-contrib] MBMPO
  .buildkite/pipeline.ml.yml
  rllib_contrib/mbmpo/README.md
  rllib_contrib/mbmpo/examples/mbmpo_cartpole_v1_model_based.py
  rllib_contrib/mbmpo/pyproject.toml
  rllib_contrib/mbmpo/requirements.txt
  rllib_contrib/mbmpo/src/rllib_mbmpo/env/__init__.py
  rllib_contrib/mbmpo/src/rllib_mbmpo/env/mbmpo_env.py
  rllib_contrib/mbmpo/src/rllib_mbmpo/mbmpo/__init__.py
  rllib_contrib/mbmpo/src/rllib_mbmpo/mbmpo/mbmpo.py
  rllib_contrib/mbmpo/src/rllib_mbmpo/mbmpo/mbmpo_torch_policy.py
  rllib_contrib/mbmpo/src/rllib_mbmpo/mbmpo/model_ensemble.py
  rllib_contrib/mbmpo/src/rllib_mbmpo/mbmpo/utils.py
  rllib_contrib/mbmpo/tests/test_mbmpo.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36612 [RLlib-contrib] Bandit algorithms
  .buildkite/pipeline.ml.yml
  rllib_contrib/TOC.md
  rllib_contrib/bandit/README.md
  rllib_contrib/bandit/examples/bandit_linucb_interest_evolution_recsim.py
  rllib_contrib/bandit/pyproject.toml
  rllib_contrib/bandit/requirements.txt
  rllib_contrib/bandit/src/rllib_bandit/bandit/__init__.py
  rllib_contrib/bandit/src/rllib_bandit/bandit/bandit.py
  rllib_contrib/bandit/src/rllib_bandit/bandit/bandit_tf_model.py
  rllib_contrib/bandit/src/rllib_bandit/bandit/bandit_tf_policy.py
  rllib_contrib/bandit/src/rllib_bandit/bandit/bandit_torch_model.py
  rllib_contrib/bandit/src/rllib_bandit/bandit/bandit_torch_policy.py
  rllib_contrib/bandit/src/rllib_bandit/env/__init__.py
  rllib_contrib/bandit/src/rllib_bandit/env/bandit_envs_discrete.py
  rllib_contrib/bandit/src/rllib_bandit/env/bandit_envs_recommender_system.py
  rllib_contrib/bandit/tests/test_bandit.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36627 [RLlib-contrib] leela chess zero
  .buildkite/pipeline.ml.yml
  rllib_contrib/leela_chess_zero/README.md
  rllib_contrib/leela_chess_zero/examples/custom_model.py
  rllib_contrib/leela_chess_zero/examples/leela_chess_zero_connect_4.py
  rllib_contrib/leela_chess_zero/pyproject.toml
  rllib_contrib/leela_chess_zero/requirements.txt
  rllib_contrib/leela_chess_zero/src/rllib_leela_chess_zero/leela_chess_zero/__init__.py
  rllib_contrib/leela_chess_zero/src/rllib_leela_chess_zero/leela_chess_zero/leela_chess_zero.py
  rllib_contrib/leela_chess_zero/src/rllib_leela_chess_zero/leela_chess_zero/leela_chess_zero_model.py
  rllib_contrib/leela_chess_zero/src/rllib_leela_chess_zero/leela_chess_zero/leela_chess_zero_policy.py
  rllib_contrib/leela_chess_zero/src/rllib_leela_chess_zero/leela_chess_zero/mcts.py
  rllib_contrib/leela_chess_zero/tests/test_leela_chess_zero.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#40079 [Clusters] Change TPU INFO log to debug and only query TPU endpoint if TPUs are detected
  python/ray/_private/accelerator.py
Labels: tests-ok, v2.7.1-pick

#36736 [RLlib-contrib] Alpha Zero
  .buildkite/pipeline.ml.yml
  rllib_contrib/alpha_zero/README.md
  rllib_contrib/alpha_zero/examples/alpha_zero_cartpole_sparse_rewards.py
  rllib_contrib/alpha_zero/pyproject.toml
  rllib_contrib/alpha_zero/requirements.txt
  rllib_contrib/alpha_zero/src/rllib_alpha_zero/alpha_zero/__init__.py
  rllib_contrib/alpha_zero/src/rllib_alpha_zero/alpha_zero/alpha_zero.py
  rllib_contrib/alpha_zero/src/rllib_alpha_zero/alpha_zero/alpha_zero_policy.py
  rllib_contrib/alpha_zero/src/rllib_alpha_zero/alpha_zero/custom_torch_models.py
  rllib_contrib/alpha_zero/src/rllib_alpha_zero/alpha_zero/mcts.py
  rllib_contrib/alpha_zero/src/rllib_alpha_zero/alpha_zero/ranked_rewards.py
  rllib_contrib/alpha_zero/tests/test_alpha_zero.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#40109 [Clusters] Change TPU INFO log to debug and only query TPU endpoint if TPUs are detected (#40079)
  python/ray/_private/accelerator.py
Labels: release-blocker, v2.7.1-pick

#40086 [core][autoscaler][dashboard] Fix autoscaler sdk accidentally initialize ray worker leading to leaked driver #40056
  dashboard/modules/node/node_head.py
  dashboard/modules/reporter/reporter_head.py
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/v2/sdk.py
  python/ray/autoscaler/v2/tests/test_e2e.py
  python/ray/autoscaler/v2/tests/test_sdk.py
  python/ray/tests/test_placement_group_3.py
Labels: v2.7.1-pick

#36625 [RLlib-contrib] ES (evolutionary strategies).
  .buildkite/pipeline.ml.yml
  rllib_contrib/es/README.md
  rllib_contrib/es/examples/es_cartpole_v1.py
  rllib_contrib/es/pyproject.toml
  rllib_contrib/es/requirements.txt
  rllib_contrib/es/src/rllib_es/es/__init__.py
  rllib_contrib/es/src/rllib_es/es/es.py
  rllib_contrib/es/src/rllib_es/es/es_tf_policy.py
  rllib_contrib/es/src/rllib_es/es/es_torch_policy.py
  rllib_contrib/es/src/rllib_es/es/optimizers.py
  rllib_contrib/es/src/rllib_es/es/utils.py
  rllib_contrib/es/tests/test_es.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#40051 [docs] update Map of Ray diagram to include RL lib
  doc/source/images/map-of-ray.png
  doc/source/images/map-of-ray.svg
  doc/source/ray-overview/index.md
Labels: docs

#40107 [Ray 2.7.1; RLlib] Cherry pick: Dreamerv3 cont actions fix.
  rllib/algorithms/dreamerv3/tests/test_dreamerv3.py
  rllib/algorithms/dreamerv3/tf/models/components/sequence_model.py
  rllib/algorithms/dreamerv3/tf/models/world_model.py
  rllib/evaluation/worker_set.py
Labels: v2.7.1-pick

#40126 [Core] Fix segfault when cancel and generator is used with a high loa…
  python/ray/_raylet.pyx
  python/ray/tests/test_streaming_generator_3.py
Labels: v2.7.1-pick, Ray 2.7.1

#40128 [core] set longer gcs connection timeout latency #39397
  src/ray/common/ray_config_def.h
Labels: v2.7.1-pick

#40135 [Serve] Add `application` tag to `ray_serve_num_http_error_requests`
  dashboard/modules/metrics/metrics_head.py
  doc/source/serve/monitoring.md
  python/ray/serve/_private/http_proxy.py
Labels: release-blocker, P0, v2.7.1-pick

#36616 [RLlib-contrib] CRR
  .buildkite/pipeline.ml.yml
  rllib_contrib/TOC.md
  rllib_contrib/crr/README.md
  rllib_contrib/crr/examples/crr_cartpole_v1.py
  rllib_contrib/crr/pyproject.toml
  rllib_contrib/crr/requirements.txt
  rllib_contrib/crr/src/rllib_crr/crr/__init__.py
  rllib_contrib/crr/src/rllib_crr/crr/crr.py
  rllib_contrib/crr/src/rllib_crr/crr/crr_torch_model.py
  rllib_contrib/crr/src/rllib_crr/crr/crr_torch_policy.py
  rllib_contrib/crr/tests/test_crr.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36607 [RLlib-contrib] ARS
  .buildkite/pipeline.ml.yml
  rllib_contrib/TOC.md
  rllib_contrib/ars/README.md
  rllib_contrib/ars/examples/ars_cartpole_v1.py
  rllib_contrib/ars/pyproject.toml
  rllib_contrib/ars/requirements.txt
  rllib_contrib/ars/src/rllib_ars/ars/__init__.py
  rllib_contrib/ars/src/rllib_ars/ars/ars.py
  rllib_contrib/ars/src/rllib_ars/ars/ars_tf_policy.py
  rllib_contrib/ars/src/rllib_ars/ars/ars_torch_policy.py
  rllib_contrib/ars/tests/test_ars.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#36628 [RLlib-contrib] MADDPG
  .buildkite/pipeline.ml.yml
  rllib_contrib/maddpg/README.md
  rllib_contrib/maddpg/examples/two_step_game.py
  rllib_contrib/maddpg/pyproject.toml
  rllib_contrib/maddpg/requirements.txt
  rllib_contrib/maddpg/src/rllib_maddpg/maddpg/__init__.py
  rllib_contrib/maddpg/src/rllib_maddpg/maddpg/maddpg.py
  rllib_contrib/maddpg/src/rllib_maddpg/maddpg/maddpg_tf_policy.py
  rllib_contrib/maddpg/tests/test_maddpg.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#40150 pick of #40149
  release/ray_release/byod/requirements_ml_byod_3.9.in
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: v2.7.1-pick

#36620 [RLlib_contrib] DDPPO
  .buildkite/pipeline.ml.yml
  rllib_contrib/ddppo/README.md
  rllib_contrib/ddppo/examples/ddppo_pendulum_v1.py
  rllib_contrib/ddppo/pyproject.toml
  rllib_contrib/ddppo/requirements.txt
  rllib_contrib/ddppo/src/rllib_ddppo/ddppo/__init__.py
  rllib_contrib/ddppo/src/rllib_ddppo/ddppo/ddppo.py
  rllib_contrib/ddppo/tests/test_ddppo.py
  rllib_contrib/leela_chess_zero/requirements.txt
  rllib_contrib/maddpg/requirements.txt
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#39889 [Data] Standardize Data release tests
  python/ray/data/tests/block_batching/test_util.py
  release/BUILD
  release/nightly_tests/dataset/aggregate_benchmark.py
  release/nightly_tests/dataset/benchmark.py
  release/nightly_tests/dataset/compute_gpu_1_cpu_16_aws.yaml
  release/nightly_tests/dataset/compute_gpu_1_cpu_16_gce.yaml
  release/nightly_tests/dataset/compute_gpu_4x4_aws.yaml
  release/nightly_tests/dataset/compute_gpu_4x4_gce.yaml
  release/nightly_tests/dataset/compute_hetero_10x10_aws.yaml
  release/nightly_tests/dataset/data_ingest_benchmark.py
  release/nightly_tests/dataset/gpu_batch_inference.py
  release/nightly_tests/dataset/image_loader_microbenchmark.py
  release/nightly_tests/dataset/iter_batches_benchmark.py
  release/nightly_tests/dataset/iter_tensor_batches_benchmark.py
  release/nightly_tests/dataset/map_batches_benchmark.py
  release/nightly_tests/dataset/parquet_metadata_resolution.py
  release/nightly_tests/dataset/read_images_benchmark.py
  release/nightly_tests/dataset/read_parquet_benchmark.py
  release/nightly_tests/dataset/read_tfrecords_benchmark.py
  release/nightly_tests/dataset/sort.py
  release/release_tests.yaml
Labels: tests-ok

#39615 [docs][docs infra][train] move Vale rules location and add reject list
  .vale/styles/Google/WordList.yml
  .vale/styles/Vocab/Train/accept.txt
Labels: docs, train

#40187 [docs] add kuberay to wordlist
  .vale/styles/Google/WordList.yml
Labels: P1, docs

#37785 [Data] Add inverse transform functionality to LabelEncoder
  python/ray/data/preprocessors/encoder.py
  python/ray/data/tests/preprocessors/test_encoder.py
Labels: external-code-affected

#40163 [Train] Deprecate LightningTrainer
  python/ray/air/_internal/usage.py
  python/ray/train/BUILD
  python/ray/train/lightning/lightning_checkpoint.py
  python/ray/train/lightning/lightning_predictor.py
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/tests/test_lightning_checkpoint.py
  python/ray/train/tests/test_lightning_deepspeed.py
  python/ray/train/tests/test_lightning_predictor.py
  python/ray/train/tests/test_lightning_trainer.py
  python/ray/train/tests/test_lightning_trainer_restore.py
  release/lightning_tests/app_config.yaml
  release/lightning_tests/compute_tpl_aws.yaml
  release/lightning_tests/compute_tpl_gce.yaml
  release/lightning_tests/workloads/lightning_test_utils.py
  release/lightning_tests/workloads/test_trainer.py
  release/lightning_tests/workloads/test_tuner.py
  release/release_tests.yaml
Labels: tests-ok

#38771 [core][dashboard] Task backend GC policy - worker update [1/3]
  python/ray/core/generated/gcs_pb2.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/task_event_buffer_test.cc
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
Labels: @author-action-required

#40213 [docker] update docker dependencies for Ray 2.7.1
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: v2.7.1-pick

#40299 [Data] Fix documentation for union and limit
  python/ray/data/dataset.py
Labels: tests-ok

#40323 [ci] Fix mujoco #40293
  .buildkite/pipeline.ml.yml
  ci/env/install-dependencies.sh
  docker/ray-ml/install-ml-docker-requirements.sh
Labels: v2.7.1-pick

#36621 [RLlib-contrib] Dreamer(V1)
  .buildkite/pipeline.ml.yml
  rllib/BUILD
  rllib/algorithms/dreamer/tests/test_dreamer.py
  rllib/examples/env/pettingzoo_connect4.py
  rllib_contrib/bandit/examples/bandit_linucb_interest_evolution_recsim.py
  rllib_contrib/bandit/pyproject.toml
  rllib_contrib/ddpg/requirements.txt
  rllib_contrib/leela_chess_zero/examples/leela_chess_zero_connect_4.py
  rllib_contrib/leela_chess_zero/pyproject.toml
  rllib_contrib/leela_chess_zero/requirements.txt
  rllib_contrib/maddpg/examples/two_step_game.py
Labels: rllib, rllib-contrib, ray 2.8, rllib-oldstack-cleanup

#40310 [Cherry-pick][KubeRay][release] Update YAML URLs
  doc/source/cluster/kubernetes/examples/mobilenet-rayservice.md
  doc/source/cluster/kubernetes/examples/rayjob-batch-inference-example.md
  doc/source/cluster/kubernetes/examples/stable-diffusion-rayservice.md
  doc/source/cluster/kubernetes/examples/text-summarizer-rayservice.md
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
  doc/source/cluster/kubernetes/getting-started/rayservice-quick-start.md
  doc/source/cluster/kubernetes/k8s-ecosystem/ingress.md
  doc/source/cluster/kubernetes/k8s-ecosystem/prometheus-grafana.md
  doc/source/cluster/kubernetes/k8s-ecosystem/pyspy.md
  doc/source/cluster/kubernetes/k8s-ecosystem/volcano.md
  doc/source/cluster/kubernetes/troubleshooting/rayservice-troubleshooting.md
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.md
  doc/source/cluster/kubernetes/user-guides/gke-gcs-bucket.md
  doc/source/cluster/kubernetes/user-guides/kuberay-gcs-ft.md
  doc/source/cluster/kubernetes/user-guides/pod-command.md
  doc/source/cluster/kubernetes/user-guides/rayserve-dev-doc.md
  doc/source/cluster/kubernetes/user-guides/rayservice.md
  doc/source/cluster/kubernetes/user-guides/tls.md
  doc/source/serve/production-guide/kubernetes.md
Labels: v2.7.1-pick

#39710 [data] Allow setting target max block size per-op instead of per-Dataset and reduce for streaming maps
  python/ray/data/BUILD
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/interfaces/task_context.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/base_physical_operator.py
  python/ray/data/_internal/execution/operators/input_data_buffer.py
  python/ray/data/_internal/execution/operators/limit_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/map_transformer.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/execution/operators/zip_operator.py
  python/ray/data/_internal/logical/interfaces/logical_operator.py
  python/ray/data/_internal/logical/interfaces/operator.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/_internal/logical/operators/write_operator.py
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/logical/rules/split_read_output_blocks.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/_internal/planner/plan_read_op.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/planner/plan_write_op.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/_internal/planner/repartition.py
  python/ray/data/_internal/util.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_auto_parallelism.py
  python/ray/data/tests/test_block_sizing.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_splitblocks.py
  python/ray/data/tests/test_streaming_executor.py
  python/ray/data/tests/test_streaming_integration.py
  python/ray/data/tests/test_util.py
Labels: ray 2.8

#40274 [Train] Deprecate AccelerateTrainer
  doc/source/train/doc_code/accelerate_trainer.py
  doc/source/train/huggingface-accelerate.rst
  python/ray/air/_internal/usage.py
  python/ray/train/BUILD
  python/ray/train/huggingface/accelerate/accelerate_trainer.py
  python/ray/train/tests/test_huggingface.py
  python/ray/train/tests/test_torch_accelerate.py
Labels: ray 2.8

#37641 Docs: Add mobile-env to RLlib community examples
  doc/source/rllib/rllib-examples.rst
Labels: docs

#40266 [Train] Fix lightning 2.0 import path
  python/ray/train/lightning/_lightning_utils.py
Labels: tests-ok

#39998 [runtime env]: Integrating Nsight to Ray worker process
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/runtime_env/nsight.py
  python/ray/remote_function.py
  python/ray/runtime_env/runtime_env.py
  python/ray/tests/BUILD
  python/ray/tests/nsight_fake/nsys_fake.py
  python/ray/tests/nsight_fake/setup.py
  python/ray/tests/test_runtime_env_profiler.py
Labels: @author-action-required

#40174 [Train] Update checkpoint path for RayTrainReportCallbacks.
  doc/source/train/doc_code/checkpoints.py
  doc/source/train/user-guides/checkpoints.rst
  python/ray/train/huggingface/transformers/_transformers_utils.py
  python/ray/train/lightning/_lightning_utils.py
Labels: tests-ok

#40277 [Train] Deprecate TransformersTrainer
  python/ray/air/_internal/usage.py
  python/ray/train/BUILD
  python/ray/train/examples/huggingface/__init__.py
  python/ray/train/examples/huggingface/huggingface_basic_language_modeling_example.py
  python/ray/train/huggingface/transformers/transformers_checkpoint.py
  python/ray/train/huggingface/transformers/transformers_predictor.py
  python/ray/train/huggingface/transformers/transformers_trainer.py
  python/ray/train/tests/test_huggingface.py
  python/ray/train/tests/test_trainer_restore.py
  python/ray/train/tests/test_transformers_checkpoint.py
  python/ray/train/tests/test_transformers_predictor.py
  python/ray/train/tests/test_transformers_trainer.py
  python/ray/train/tests/test_transformers_trainer_steps.py
Labels: ray 2.8

#39895 [Doc] Logging: Add Fluent Bit DaemonSet and CloudWatch for persistence
  doc/source/cluster/kubernetes/user-guides/images/cloudwatch-dashboard.png
  doc/source/cluster/kubernetes/user-guides/images/cloudwatch-logs.png
  doc/source/cluster/kubernetes/user-guides/logging.md
Labels: tests-ok

#40284 [doc] Add vSphere version requirement in user guide
  doc/source/cluster/vms/user-guides/launching-clusters/vsphere.md
Labels: tests-ok

#40169 [tune] remove TuneRichReporter
  doc/source/tune/api/env.rst
  python/ray/air/constants.py
  python/ray/tune/experimental/output.py
  python/ray/tune/tune.py
Labels: tests-ok

#40275 [Data] Cap op concurrency with exponential ramp-up
  python/ray/data/BUILD
  python/ray/data/_internal/execution/backpressure_policy.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/context.py
  python/ray/data/tests/test_backpressure_policies.py
  python/ray/data/tests/test_streaming_executor.py
Labels: @author-action-required

#40437 [ci] mark dataset_shuffle_push_based_random_shuffle_100tb.aws as unstable
  release/release_tests.yaml
Labels: external-code-affected

#39965 Fix get_wheel_filename being out of date
  doc/source/ray-overview/installation.rst
  python/ray/_private/utils.py
  python/ray/tests/test_runtime_env.py
Labels: tests-ok, hacktoberfest-accepted

#40204 avoid to fetch private ip
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/autoscaler/_private/vsphere/pyvmomi_sdk_provider.py
  python/ray/autoscaler/_private/vsphere/utils.py
  python/ray/tests/vsphere/test_vsphere_node_provider.py
Labels: tests-ok

#40158 [Doc] [KubeRay] [RayJob] Add info about submitter pod template
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
Labels: tests-ok

#38792 [core][dashboard] Task backend GC policy - GCS refactor [2/3]
  dashboard/state_aggregator.py
  python/ray/_private/state_api_test_utils.py
  python/ray/core/generated/gcs_service_pb2.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_task_events_2.py
  python/ray/util/state/api.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/task_spec.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/profile_event.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs_service.proto
Labels: @author-action-required

#40453 [CI] [cluster launcher] Fix switched "latest" and "nightly" gcp tests
  python/ray/autoscaler/_private/updater.py
  python/ray/autoscaler/launch_and_verify_cluster.py
  release/release_tests.yaml
Labels: tests-ok

#39617 [docs][train]copy edits and adding links to docstrings
  python/ray/train/examples/accelerate/accelerate_torch_trainer.py
  python/ray/train/examples/pytorch/torch_fashion_mnist_example.py
  python/ray/train/examples/transformers/transformers_torch_trainer_basic.py
  python/ray/train/torch/torch_trainer.py
Labels: docs, train

#40501 [DO NOT MERGE] Workspace templates 2.7.1
  doc/source/templates/04_finetuning_llms_with_deepspeed/README.md
  doc/source/templates/04_finetuning_llms_with_deepspeed/finetune_hf_llm.py
  doc/source/templates/04_finetuning_llms_with_deepspeed/lora_configs/lora.json
  doc/source/templates/04_finetuning_llms_with_deepspeed/merge_lora_weights.py
  doc/source/templates/04_finetuning_llms_with_deepspeed/run_llama_ft.sh
  doc/source/templates/testing/docker/04_finetuning_llms_with_deepspeed/Dockerfile
  doc/source/templates/testing/docker/04_finetuning_llms_with_deepspeed/requirements.txt
  release/release_tests.yaml
Labels: do-not-merge

#40487 [vSphere Provider] Fix the bug that multiple worker types doesn't work
  python/ray/autoscaler/_private/vsphere/config.py
  python/ray/tests/vsphere/test_vsphere_node_provider.py
Labels: tests-ok

#40538 [data] Disable block slicing for shuffle ops
  python/ray/data/_internal/output_buffer.py
  python/ray/data/_internal/planner/exchange/shuffle_task_spec.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/_internal/planner/repartition.py
  release/nightly_tests/dataset/sort.py
Labels: release-blocker, v2.8.0-pick

#40582 [data] Fix sliced blocks performance issue
  python/ray/data/_internal/execution/operators/map_transformer.py
Labels: release-blocker, ray 2.8

#40595 [data] cherry pick (#40367)
  doc/source/data/images/data-dashboard.png
  doc/source/data/performance-tips.rst
Labels: v2.8.0-pick

#40602 [data] Disable block slicing for shuffle ops (#40538)
  python/ray/data/_internal/output_buffer.py
  python/ray/data/_internal/planner/exchange/shuffle_task_spec.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/_internal/planner/repartition.py
  release/nightly_tests/dataset/sort.py
Labels: ray 2.8, v2.8.0-pick

#40614 [data] Fix sliced blocks performance issue #40582
  python/ray/data/_internal/execution/operators/map_transformer.py
Labels: ray 2.8, v2.8.0-pick

#40591 [Cherry-pick][Core] Streaming generator exprimental backpressure
  BUILD.bazel
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/native_task_submitter.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  python/ray/_private/ray_option_utils.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/core/generated/common_pb2.py
  python/ray/core/generated/core_worker_pb2.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/BUILD
  python/ray/tests/test_streaming_generator_2.py
  python/ray/tests/test_streaming_generator_3.py
  python/ray/tests/test_streaming_generator_4.py
  python/ray/tests/test_streaming_generator_backpressure.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/generator_waiter.cc
  src/ray/core_worker/generator_waiter.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/generator_waiter_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: v2.8.0-pick

#40640 [serve] Lazily construct `asyncio.Event` to avoid attaching to the wrong loop
  python/ray/serve/_private/router.py
  python/ray/serve/tests/unit/test_replica_scheduler.py
Labels: v2.8.0-pick

#38553 [Core] Support Intel GPU
  python/ray/_private/accelerators/__init__.py
  python/ray/_private/accelerators/intel_gpu.py
  python/ray/_private/utils.py
  python/ray/_private/worker.py
  python/ray/tests/BUILD
  python/ray/tests/accelerators/mock_dpctl_1.py
  python/ray/tests/accelerators/mock_dpctl_2.py
  python/ray/tests/accelerators/test_intel_gpu.py
  python/ray/util/accelerators/__init__.py
  python/ray/util/accelerators/accelerators.py
Labels: external-code-affected

#40346 [cluster-launcher] fix: respect cache_stopped_node in GCP node provider
  python/ray/autoscaler/_private/gcp/node.py
  python/ray/autoscaler/_private/gcp/node_provider.py
  python/ray/tests/gcp/test_gcp_node_provider.py
Labels: tests-ok

#40655 should not fetch runtime-info of vm from cached_nodes
  python/ray/autoscaler/_private/vsphere/node_provider.py
Labels: tests-ok

#40698 get_pyvmomi_obj_by_name and get_pyvmomi_obj_by_moid are replaced by g…
  python/ray/autoscaler/_private/vsphere/gpu_utils.py
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/autoscaler/_private/vsphere/pyvmomi_sdk_provider.py
Labels: tests-ok

#40637 [serve] Add Python 3.11 tests to postmerge (or triggered via tag)
  .buildkite/_forge.rayci.yml
  .buildkite/serve.rayci.yml
  ci/docker/serve.build.Dockerfile
  ci/docker/servepython311.build.wanda.yaml
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_expected_python_version.py
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: python-3-11-support

#40709 [docs] fix from Kapa for clipped Ray logo in Ask AI button
  doc/source/_static/css/custom.css
Labels: docs, v2.8.0-pick

#40717 [Cluster launcher] [vSphere] get_pyvmomi_obj_by_name and get_pyvmomi_obj_by_moid are replaced by get_pyvmomi_obj (#40698)
  python/ray/autoscaler/_private/vsphere/gpu_utils.py
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/autoscaler/_private/vsphere/pyvmomi_sdk_provider.py
Labels: release-blocker, v2.8.0-pick

#40678 make submission id show as default over core job id. Fix download logs button not downloading full logs
  dashboard/client/src/pages/log/hooks.ts
  dashboard/client/src/pages/overview/cards/RecentJobsCard.component.test.tsx
  dashboard/client/src/pages/overview/cards/RecentJobsCard.tsx
  dashboard/client/src/service/log.ts
Labels: release-blocker, v2.8.0-pick

#40674 Remove dead dependencies
  python/requirements.txt
  python/requirements/ml/core-requirements.txt
  python/requirements/ml/data-requirements.txt
  python/requirements/ml/dl-cpu-requirements.txt
  python/requirements/ml/rllib-test-requirements.txt
  python/requirements/ml/tune-requirements.txt
  python/requirements/test-requirements.txt
Labels: tests-ok

#40708 [serve] Fix `test_batching` on Python 3.11 and split into unit/integration
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/unit/test_batching.py
Labels: python-3-11-support

#40745 [serve] Mark Serve Python 3.11 tests as `soft_fail=False`
  .buildkite/serve.rayci.yml
Labels: python-3-11-support

#40737 [vSphere Provider] is_terminated should consider the case that the VM is powered off for plugging the GPU
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/tests/vsphere/test_vsphere_node_provider.py
Labels: tests-ok

#40722 [Cherry-pick][Doc][KubeRay] Upgrade KubeRay and CRD versioning
  .vale/styles/Google/Acronyms.yml
  doc/source/_toc.yml
  doc/source/cluster/kubernetes/troubleshooting/troubleshooting.md
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/upgrade-guide.md
Labels: release-blocker, v2.8.0-pick

#40728 [docs] [cherry-pick] fix from Kapa for clipped Ray logo in Ask AI button (#40709)
  doc/source/_static/css/custom.css
Labels: docs, v2.8.0-pick

#40263 [RLlib] `MultiAgentEpisode` for Multi-Agent Reinforcement Learning with the new `EnvRunner` API.
  rllib/BUILD
  rllib/algorithms/dreamerv3/utils/env_runner.py
  rllib/algorithms/ppo/ppo.py
  rllib/env/multi_agent_episode.py
  rllib/env/single_agent_env_runner.py
  rllib/env/single_agent_episode.py
  rllib/env/testing/single_agent_gym_env_runner.py
  rllib/env/tests/test_single_agent_episode.py
  rllib/evaluation/postprocessing_v2.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
  rllib/utils/replay_buffers/tests/test_episode_replay_buffer.py
Labels: rllib, rllib-multi-agent, rllib-env, rllib-newstack

#40765 [data] Revert default block size back to 512MiB
  python/ray/data/context.py
  python/ray/data/tests/test_auto_parallelism.py
Labels: v2.8.0-pick

#40672 [Doc][KubeRay] Add a doc for RayService high-availability
  .vale/styles/Google/Acronyms.yml
  doc/source/_toc.yml
  doc/source/cluster/kubernetes/getting-started/rayservice-quick-start.md
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/rayservice-high-availability.md
  doc/source/cluster/kubernetes/user-guides/rayservice.md
Labels: tests-ok, v2.8.0-pick

#40820 [data] cast metadata size bytes to int
  python/ray/data/block.py
  python/ray/data/datasource/file_meta_provider.py
Labels: release-blocker, v2.8.0-pick

#35335 [Observabiltiy] Deduplicate error event messages
  python/ray/_private/ray_logging.py
  python/ray/_private/worker.py
  python/ray/tests/test_failure_2.py
  python/ray/tests/test_output.py
Labels: ray 2.8

#40360 [Doc][KubeRay] Doc for Helm chart RBAC
  doc/source/_toc.yml
  doc/source/cluster/kubernetes/images/rbac-clusterrole.svg
  doc/source/cluster/kubernetes/images/rbac-role-multi-namespaces.svg
  doc/source/cluster/kubernetes/images/rbac-role-one-namespace.svg
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/helm-chart-rbac.md
Labels: tests-ok
