Repository ray-project/ray, pull requests merged in 2023-07, with the labels that each got.

#37000 Pin pydantic to < 2.0.0
  python/requirements.txt
  python/setup.py
Labels: release-blocker

#37018 Pin pydantic to < 2.0.0
  python/requirements.txt
  python/setup.py
Labels: release-blocker, v2.6.0-pick

#37048 Hot fix release test infra
  release/ray_release/byod/byod_rllib_test.sh
  release/ray_release/byod/requirements_ml_byod_3.8.in
  release/ray_release/byod/requirements_ml_byod_3.8.txt
  release/release_tests.yaml
Labels: release-blocker, v2.6.0-pick

#37031 [Core]Fix internal_kv del api bug in ray client server proxy mode
  python/ray/tests/test_client.py
  python/ray/util/client/server/proxier.py
Labels: P0

#37026 [ci] remove the old upload_wheels bash func
  ci/ci.sh
Labels: tests-ok

#37025 [ci] keep buildkite upload path only
  ci/build/upload_build_info.sh
Labels: tests-ok

#37005 [core] Add metrics for object size distribution in object store
  src/ray/object_manager/plasma/stats_collector.cc
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
  src/ray/stats/tag_defs.cc
  src/ray/stats/tag_defs.h
Labels: release-blocker

#36993 [air/output] Include traceback as part of the warning log for syncing failures
  doc/source/tune/api/env.rst
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_syncer.py
  python/ray/tune/trainable/trainable.py
Labels: tests-ok

#37103 [data] Cache Dataset.schema
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_consumption.py
Labels: @author-action-required

#37110 [cherry-pick][core] Add metrics for object size distribution in object store (#37005)
  src/ray/object_manager/plasma/stats_collector.cc
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
  src/ray/stats/tag_defs.cc
  src/ray/stats/tag_defs.h
Labels: release-blocker, v2.6.0-pick

#37062 [core] Suppress harmless ObjectRefStreamEndOfStreamError when using asyncio
  python/ray/_private/serialization.py
  python/ray/_raylet.pyx
  python/ray/exceptions.py
  python/ray/tests/test_streaming_generator.py
  src/ray/core_worker/core_worker.cc
Labels: @author-action-required

#36259 [RLlib-contrib] ddpg
  .buildkite/pipeline.ml.yml
  rllib_contrib/TOC.md
  rllib_contrib/ddpg/examples/ddpg_pendulum_v1.py
  rllib_contrib/ddpg/pyproject.toml
  rllib_contrib/ddpg/readme.md
  rllib_contrib/ddpg/requirements.txt
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/__init__.py
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/ddpg.py
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/ddpg_tf_model.py
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/ddpg_tf_policy.py
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/ddpg_torch_model.py
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/ddpg_torch_policy.py
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/noop_model.py
  rllib_contrib/ddpg/src/rllib_ddpg/ddpg/utils.py
  rllib_contrib/ddpg/tests/test_ddpg.py
Labels: tests-ok

#37102 [air/release] Fix batch format in `dreambooth` example
  python/ray/air/examples/dreambooth/dataset.py
  python/ray/air/examples/dreambooth/requirements.txt
  release/air_examples/dreambooth/dreambooth_env.yaml
Labels: tests-ok, release-test

#37167 [Serve] Cherry pick #36961
  .buildkite/pipeline.ml.yml
  doc/source/serve/advanced-guides/dyn-req-batch.md
  doc/source/serve/doc_code/streaming_tutorial.py
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/streaming.md
Labels: release-blocker, v2.6.0-pick

#36842 [Data] Add option for parallelizing post-collation data batch operations in `DataIterator.iter_batches()`
  python/ray/data/_internal/block_batching/iter_batches.py
  python/ray/data/_internal/block_batching/util.py
  python/ray/data/_internal/iterator/pipelined_iterator.py
  python/ray/data/_internal/stats.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/iterator.py
  python/ray/data/tests/block_batching/test_iter_batches.py
  python/ray/data/tests/block_batching/test_util.py
  python/ray/data/tests/test_iterator.py
Labels: tests-ok

#37149 [RLlib; release blocker] DreamerV3: hotfix; remove assert
  rllib/core/learner/learner.py
Labels: tests-ok, release-blocker, P0, rllib

#37189 [air/release][cherry-pick] Fix batch format in `dreambooth` example (#37102)
  python/ray/air/examples/dreambooth/dataset.py
  python/ray/air/examples/dreambooth/requirements.txt
  release/air_examples/dreambooth/dreambooth_env.yaml
Labels: v2.6.0-pick

#37201 Cherry-pick #37103
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_consumption.py
Labels: release-blocker, v2.6.0-pick

#37200 Cherry-pick #37062
  python/ray/_private/serialization.py
  python/ray/_raylet.pyx
  python/ray/exceptions.py
  python/ray/tests/test_streaming_generator.py
  src/ray/core_worker/core_worker.cc
Labels: release-blocker, v2.6.0-pick

#37112 [wheel] yum install only once in manylinux
  python/build-wheel-manylinux2014.sh
Labels: tests-ok

#37130 [ci] only build one wheel for post wheel testing
  .buildkite/pipeline.arm64.yml
  .buildkite/pipeline.build_release.yml
Labels: tests-ok

#37157 [ci][fix] bisect needs to read from global config
  release/ray_release/scripts/ray_bisect.py
Labels: tests-ok

#37219 [2.6.0][tune] Remove temporary checkpoint directories after restore (#37173)
  python/ray/tune/tests/test_function_api.py
  python/ray/tune/trainable/function_trainable.py
  release/long_running_distributed_tests/workloads/pytorch_pbt_failure.py
Labels: v2.6.0-pick

#37176 [core][autoscaler] Fix pg id serialization with hex rather than binary for cluster state reporting #37132
  python/ray/autoscaler/v2/tests/test_sdk.py
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/protobuf/experimental/autoscaler.proto
Labels: v2.6.0-pick

#37174 [core][logging][ipython] Fix log buffering when consecutive runs with in ray log dedup window (#37134)
  python/ray/_private/ray_logging.py
Labels: v2.6.0-pick

#37119 [Data] Calculate stage execution time in `StageStatsSummary` from `BlockMetadata`
  python/ray/data/_internal/stats.py
  python/ray/data/block.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_stats.py
Labels: tests-ok

#37262 [Docs] De-flake doctests (#37162)
  doc/source/data/loading-data.rst
  doc/source/data/working-with-images.rst
  doc/source/data/working-with-pytorch.rst
  doc/source/ray-core/actors/async_api.rst
Labels: v2.6.0-pick

#37178 [AIR][Docs] Remove `BatchPredictor` from examples
  doc/source/_toc.yml
  doc/source/ray-air/doc_code/pytorch_starter.py
  doc/source/ray-air/doc_code/tf_starter.py
  doc/source/ray-air/examples/BUILD
  doc/source/ray-air/examples/convert_existing_pytorch_code_to_ray_air.ipynb
  doc/source/ray-air/examples/convert_existing_tf_code_to_ray_air.ipynb
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  doc/source/ray-air/examples/huggingface_text_classification.ipynb
  doc/source/ray-air/examples/index.rst
  doc/source/ray-air/examples/lightgbm_example.ipynb
  doc/source/ray-air/examples/opt_deepspeed_batch_inference.ipynb
  doc/source/ray-air/examples/pytorch_tabular_batch_prediction.py
  doc/source/ray-air/examples/pytorch_tabular_starter.py
  doc/source/ray-air/examples/sklearn_example.ipynb
  doc/source/ray-air/examples/tf_tabular_batch_prediction.py
  doc/source/ray-air/examples/tf_tabular_starter.py
  doc/source/ray-air/examples/torch_detection.ipynb
  doc/source/ray-air/examples/torch_image_batch_pretrained.py
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  doc/source/ray-air/examples/xgboost_batch_prediction.py
  doc/source/ray-air/examples/xgboost_example.ipynb
  doc/source/ray-air/examples/xgboost_starter.py
  doc/source/ray-air/getting-started.rst
  doc/source/ray-air/predictors.rst
  doc/source/ray-overview/examples.rst
  doc/source/ray-overview/getting-started.md
  doc/source/train/examples/lightning/lightning_cola_advanced.ipynb
  python/ray/train/examples/huggingface/huggingface_basic_language_modeling_example.py
  python/ray/train/examples/pytorch/torch_regression_example.py
  python/ray/train/examples/tf/tensorflow_autoencoder_example.py
  python/ray/train/examples/tf/tensorflow_regression_example.py
  release/release_tests.yaml
Labels: tests-ok

#37070 [ci][release-infra] use python docker image for running release tests
  release/BUILD
  release/ray_release/buildkite/step.py
  release/ray_release/scripts/build_pipeline.py
  release/ray_release/tests/test_build_pipeline.py
  release/run_release_test.sh
Labels: tests-ok

#36814 [RLlib] Fix bug in Multi-Categorical distribution. It should use logp and not log_p.
  rllib/core/models/tests/test_catalog.py
  rllib/models/torch/torch_distributions.py
Labels: tests-ok

#37117 [Core] Fix the race condition where grpc requests are handled while core worker not yet initialized
  BUILD.bazel
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/rpc/server_call.h
  src/ray/rpc/worker/core_worker_server.h
Labels: do-not-merge

#36979 [Data] Standardize Data API refs (Input/Output + Dataset Constructor)
  doc/source/data/api/input_output.rst
  python/ray/data/dataset.py
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/datasource/partitioning.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_binary.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_json.py
  python/ray/data/tests/test_metadata_provider.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_partitioning.py
  python/ray/data/tests/test_text.py
Labels: tests-ok

#37297 [ci][doc] Add windows 3.11 wheel support in doc and ci
  doc/source/ray-overview/installation.rst
  release/util/download_wheels.sh
Labels: v2.6.0-pick

#37302 [ci][doc] Add windows 3.11 wheel support in doc and ci #37297
  doc/source/ray-overview/installation.rst
  release/util/download_wheels.sh
Labels: v2.6.0-pick

#37272 [ci][configs] pass --global-config down to run_release_test.py
  release/ray_release/buildkite/step.py
  release/ray_release/scripts/build_pipeline.py
Labels: tests-ok

#37080 Migrate the rest of rllib tests to byod
  release/ray_release/byod/requirements_ml_byod_3.8.in
  release/ray_release/byod/requirements_ml_byod_3.8.txt
  release/release_tests.yaml
Labels: tests-ok

#37301 [Core] Fix the race condition where grpc requests are handled while c…
  BUILD.bazel
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/rpc/server_call.h
  src/ray/rpc/worker/core_worker_server.h
Labels: v2.6.0-pick

#37305 [tune] Hotfix failing checkpoint test (#37220)
  python/ray/tune/tests/test_function_api.py
Labels: v2.6.0-pick

#37263 [Data] Cherry-pick #37119
  python/ray/data/_internal/stats.py
  python/ray/data/block.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker, v2.6.0-pick

#37352 [Cherry-pick][Data][Train] Fix remaining issues on DatasetConfig->DataConfig migration
  doc/source/ray-air/doc_code/computer_vision.py
  doc/source/ray-air/examples/torch_detection.ipynb
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  python/ray/air/config.py
  python/ray/train/horovod/horovod_trainer.py
  python/ray/train/huggingface/accelerate/accelerate_trainer.py
  python/ray/train/huggingface/transformers/transformers_trainer.py
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/mosaic/mosaic_trainer.py
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/train/torch/torch_trainer.py
  release/air_tests/air_benchmarks/workloads/data_benchmark.py
Labels: release-blocker, v2.6.0-pick

#37277 [release] Disable NFS for many nodes release test
  release/benchmarks/distributed/many_nodes_tests/compute_config.yaml
  release/benchmarks/distributed/many_nodes_tests/compute_config_gce.yaml
Labels: release-blocker, Ray 2.6

#37281 [core][autoscaler] ray status -parsing autoscaler proto into ray status schema [2/x]
  python/ray/autoscaler/v2/BUILD
  python/ray/autoscaler/v2/schema.py
  python/ray/autoscaler/v2/tests/test_utils.py
  python/ray/autoscaler/v2/utils.py
Labels: tests-ok

#37142 [AIR] Remove head node syncing as the default storage option
  doc/source/ray-air/examples/dolly_lightning_fsdp_finetuning.ipynb
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  doc/source/templates/02_many_model_training/start.ipynb
  python/ray/air/constants.py
  python/ray/train/examples/pytorch/torch_linear_example.py
  python/ray/train/examples/tf/tensorflow_mnist_example.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_multinode_sync.py
  python/ray/tune/tests/test_syncer_callback.py
  release/air_tests/air_benchmarks/workloads/xgboost_benchmark.py
  release/air_tests/frequent_pausing/script.py
  release/air_tests/horovod/workloads/horovod_tune_test.py
  release/golden_notebook_tests/workloads/torch_tune_serve_test.py
  release/lightning_tests/workloads/test_trainer.py
  release/lightning_tests/workloads/test_tuner.py
  release/long_running_tests/workloads/apex.py
  release/long_running_tests/workloads/impala.py
  release/ml_user_tests/train/train_tensorflow_mnist_test.py
  release/ml_user_tests/train/train_torch_linear_test.py
  release/ml_user_tests/tune_rllib/run_connect_tests.py
  release/rllib_tests/smoke_tests/smoke_test_basic_multi_node_training_learner.py
  release/tune_tests/cloud_tests/workloads/_tune_script.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
  release/tune_tests/scalability_tests/workloads/test_long_running_large_checkpoints.py
  rllib/examples/tune/framework.py
  rllib/utils/test_utils.py
Labels: tests-ok, release-blocker, Ray 2.6

#37383 [cherry-pick][data][doc] Add DatasetConfig -> DataConfig migration guide
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/doc_code/air_ingest_migration.py
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  doc/source/train/api/api.rst
  python/ray/air/config.py
  python/ray/air/tests/test_new_dataset_config.py
  python/ray/air/util/check_ingest.py
  python/ray/train/__init__.py
  python/ray/train/_internal/backend_executor.py
  python/ray/train/_internal/data_config.py
  python/ray/train/data_parallel_trainer.py
  python/ray/train/horovod/horovod_trainer.py
  python/ray/train/huggingface/accelerate/accelerate_trainer.py
  python/ray/train/huggingface/transformers/transformers_trainer.py
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/mosaic/mosaic_trainer.py
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/train/tests/test_backend.py
  python/ray/train/tests/test_training_iterator.py
  python/ray/train/torch/torch_trainer.py
  python/ray/train/trainer.py
Labels: release-blocker, v2.6.0-pick

#37385 [air][cherry-pick] Disable head node syncing by default
  doc/source/ray-air/examples/dolly_lightning_fsdp_finetuning.ipynb
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  doc/source/templates/02_many_model_training/start.ipynb
  python/ray/air/constants.py
  python/ray/train/examples/pytorch/torch_linear_example.py
  python/ray/train/examples/tf/tensorflow_mnist_example.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_multinode_sync.py
  python/ray/tune/tests/test_syncer_callback.py
  release/air_tests/air_benchmarks/workloads/xgboost_benchmark.py
  release/air_tests/frequent_pausing/script.py
  release/air_tests/horovod/workloads/horovod_tune_test.py
  release/golden_notebook_tests/workloads/torch_tune_serve_test.py
  release/lightning_tests/workloads/test_trainer.py
  release/lightning_tests/workloads/test_tuner.py
  release/long_running_tests/workloads/apex.py
  release/long_running_tests/workloads/impala.py
  release/ml_user_tests/train/train_tensorflow_mnist_test.py
  release/ml_user_tests/train/train_torch_linear_test.py
  release/ml_user_tests/tune_rllib/run_connect_tests.py
  release/rllib_tests/smoke_tests/smoke_test_basic_multi_node_training_learner.py
  release/tune_tests/cloud_tests/workloads/_tune_script.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
  release/tune_tests/scalability_tests/workloads/test_long_running_large_checkpoints.py
  rllib/examples/tune/framework.py
  rllib/utils/test_utils.py
Labels: v2.6.0-pick

#37387 [Train] Fix Deepspeed device ranks check in Lightning 2.0.5
  python/ray/train/lightning/_lightning_utils.py
Labels: tests-ok, release-blocker

#37409 [Test] Change instance type to r5.8xlarge for dask_on_ray_1tb_sort (#37321)
  release/nightly_tests/dask_on_ray/1tb_sort_compute.yaml
Labels: v2.6.0-pick

#37401 [Data] Mark `dataset_shuffle_sort_1tb` release test as stable
  doc/source/data/saving-data.rst
  release/release_tests.yaml
Labels: data, release-test

#37359 [Data] Replace usages of `example://` from docs and code snippets with S3 paths
  doc/source/data/doc_code/batch_formats.py
  doc/source/data/doc_code/key_concepts.py
  doc/source/data/doc_code/tensor.py
  doc/source/data/doc_code/transforming_data.py
  doc/source/data/inspecting-data.rst
  doc/source/data/iterating-over-data.rst
  doc/source/data/key-concepts.rst
  doc/source/data/performance-tips.rst
  doc/source/data/saving-data.rst
  doc/source/data/transforming-data.rst
  doc/source/data/working-with-images.rst
  doc/source/data/working-with-pytorch.rst
  doc/source/data/working-with-tensors.rst
  doc/source/ray-air/doc_code/air_ingest_new.py
  doc/source/ray-contribute/writing-code-snippets.rst
  doc/source/ray-observability/getting-started.rst
  python/ray/data/dataset.py
  python/ray/data/datasource/partitioning.py
  python/ray/data/read_api.py
Labels: tests-ok

#37407 [core][autoscaler] Cherry picks change to autoscaler intereface
  python/ray/autoscaler/__init__.py
  python/ray/autoscaler/v2/instance_manager/config.py
  python/ray/autoscaler/v2/instance_manager/ray_installer.py
  python/ray/autoscaler/v2/tests/test_config.py
  python/ray/autoscaler/v2/tests/test_sdk.py
  src/ray/common/constants.h
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/experimental/autoscaler.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/raylet.cc
Labels: v2.6.0-pick

#37468 Support both pydantic 1.x and 2.x
  dashboard/modules/job/utils.py
  python/ray/serve/_private/version.py
  python/ray/tests/test_serialization.py
  python/ray/util/serialization_addons.py
  python/ray/util/state/common.py
Labels: release-blocker, v2.6.0-pick

#37351 [DOC] Added in new CSAT widget
  doc/source/_static/css/custom.css
  doc/source/_static/js/csat.js
  doc/source/_static/js/custom.js
  doc/source/_static/js/rate-the-docs.es.min.js
  doc/source/_templates/csat.html
  doc/source/_templates/layout.html
  doc/source/_templates/sections/footer-content.html
  doc/source/conf.py
Labels: docs

#37295 [Train][doctest] Part 2: Remove REPL-style doctest in Ray Train
  python/ray/train/lightning/lightning_checkpoint.py
  python/ray/train/mosaic/mosaic_trainer.py
  python/ray/train/tensorflow/tensorflow_checkpoint.py
  python/ray/train/tensorflow/tensorflow_predictor.py
Labels: tests-ok

#37550 [cherry-pick][data] Fix "ImportError: sys.meta_path is None, Python is likely ting down" from StreamingExecutor
  python/ray/data/context.py
Labels: release-blocker, v2.6.0-pick

#37567 [air][cherry-pick] Fix behavior of multi-node checkpointing without an external `storage_path` to hard-fail
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/syncer.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
Labels: v2.6.0-pick

#37481 [RLlib] Index tensors in slate epsilon greedy properly
  rllib/utils/exploration/slate_epsilon_greedy.py
Labels: tests-ok

#37568 [air][doc] Update docs to reflect head node syncing deprecation (#37475)
  doc/source/tune/doc_code/faq.py
  doc/source/tune/tutorials/tune-output.rst
  doc/source/tune/tutorials/tune-storage.rst
  python/ray/tune/syncer.py
Labels: v2.6.0-pick

#37487 [DOC] Added in new CSAT widget (#37351)
  doc/source/_static/css/custom.css
  doc/source/_static/js/csat.js
  doc/source/_static/js/custom.js
  doc/source/_static/js/rate-the-docs.es.min.js
  doc/source/_templates/csat.html
  doc/source/_templates/layout.html
  doc/source/_templates/sections/footer-content.html
  doc/source/conf.py
Labels: docs, v2.6.0-pick

#35773 [Core]Fix PG leakage caused by GCS restart when PG has not been successfully remove after the job died
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
Labels: @author-action-required

#37660 [serve] Cherry-pick Serve enum `to_proto` fixes for Python 3.11
  python/ray/serve/_private/common.py
Labels: v2.6.1-pick

#37651 [docs] turn on fail-on-warning for Sphinx builds
  .readthedocs.yaml
Labels: v2.6.0-pick

#37674 [docs] Cherry-pick 2.6.0 sphinx fail on warning
  .readthedocs.yaml
Labels: v2.6.0-pick

#36980 [Data][Docs] Standardize "Grouped and Global Aggregations" reference
  python/ray/data/dataset.py
Labels: tests-ok

#37584 [CI] Add ratchet for doctests
  .buildkite/pipeline.build_lint.yml
  ci/v2/lint.sh
  python/requirements/lint-requirements.txt
  python/requirements/ml/rllib-requirements.txt
  python/requirements_compiled.txt
  semgrep.yml
Labels: tests-ok

#37015 [Data][Docs] Standardize "Basic Transformations" references
  python/ray/data/dataset.py
Labels: tests-ok

#37670 [air] fix pyarrow lazy import
  python/ray/air/_internal/remote_storage.py
Labels: v2.6.1-pick

#37681 [RLlib] [RLlib] Early improvements to Catalogs and RL Modules docs + Catalogs improvements
  doc/source/rllib/doc_code/catalog_guide.py
  doc/source/rllib/doc_code/rlmodule_guide.py
  doc/source/rllib/images/rllib-concepts-rlmodules-sketch.png
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/package_ref/catalogs.rst
  doc/source/rllib/rllib-catalogs.rst
  doc/source/rllib/rllib-connector.rst
  doc/source/rllib/rllib-rlmodule.rst
  rllib/BUILD
  rllib/algorithms/ppo/ppo_catalog.py
  rllib/core/models/catalog.py
  rllib/core/models/tests/test_catalog.py
  rllib/examples/catalog/custom_action_distribution.py
  rllib/examples/catalog/mobilenet_v2_encoder.py
  rllib/examples/models/mobilenet_v2_encoder.py
  rllib/examples/rl_module/mobilenet_rlm.py
Labels: tests-ok, v2.6.1-pick

#37753 [CI] Enable doctest ratchet for Core and Train
  semgrep.yml
Labels: tests-ok

#37752 [Data] Improve error messages
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
Labels: tests-ok

#37013 [Data][Docs] Standardize "Splitting and Merging Datasets" references
  python/ray/data/dataset.py
Labels: tests-ok

#37007 [Data][Docs] Standardize "Consuming Data" references
  python/ray/data/dataset.py
Labels: tests-ok

#36982 [Data][Docs] Standardize "Sorting, Shuffling, Repartitioning" references
  doc/source/data/performance-tips.rst
  doc/source/data/saving-data.rst
  python/ray/data/dataset.py
Labels: tests-ok

#37686 Adding llm tags to relevant examples
  doc/source/ray-overview/examples.rst
Labels: docs, v2.6.1-pick

#37682 [RLlib][doc] Added torch compile docs (#37252)
  doc/source/_toc.yml
  doc/source/rllib/rllib-torch2x.rst
  rllib/benchmarks/torch_compile/README.md
Labels: v2.6.1-pick

#37718 [ci][cluster-launcher] Fix GCP multi-cluster terminate nodes race
  python/ray/autoscaler/_private/gcp/node_provider.py
  python/ray/tests/gcp/test_gcp_node_provider.py
  release/release_tests.yaml
Labels: tests-ok, release-blocker

#37672 [Data] Batch predictor deprecation updates
  doc/source/data/batch_inference.rst
  python/ray/train/batch_predictor.py
Labels: tests-ok

#37743 [Docs] De-flake doctests
  bazel/python.bzl
  doc/source/data/key-concepts.rst
  python/ray/data/read_api.py
  python/ray/train/tensorflow/tensorflow_checkpoint.py
Labels: tests-ok

#37740 [Serve] Cherry pick #37160
  doc/source/serve/doc_code/requests_best_practices.py
  doc/source/serve/http-guide.md
  doc/source/serve/production-guide/best-practices.md
Labels: release-blocker

#37793 [Data] Report benchmark metrics in nested dict form
  release/air_tests/air_benchmarks/mlperf-train/resnet50_ray_air.py
  release/nightly_tests/dataset/image_loader_microbenchmark.py
  release/nightly_tests/dataset/image_train_benchmark.py
Labels: tests-ok

#37650 [Core] Fix the accidental protobuf backward incompatible changes
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
Labels: tests-ok, release-blocker, v2.6.2-pick

#37826 [Core] Fix the accidental protobuf backward incompatible changes (#37…
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
Labels: release-blocker, v2.6.2-pick

#37690 [air] `pyarrow.fs` persistence: Introduce `StorageContext` and use it for driver syncing (1/n)
  python/ray/air/_internal/uri_utils.py
  python/ray/air/config.py
  python/ray/train/BUILD
  python/ray/train/_internal/storage.py
  python/ray/train/tests/test_new_persistence.py
  python/ray/tune/execution/experiment_state.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/experiment/experiment.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/syncer.py
  python/ray/tune/tune.py
Labels: tests-ok

#37834 [Doc] Make entire example gallery cards clickable links
  doc/source/ray-overview/examples.rst
Labels: tests-ok, docs

#37863 [autoscaler] Optimize resource constraints proto to dedup requests with the same shape
  python/ray/_raylet.pyx
  python/ray/autoscaler/v2/sdk.py
  python/ray/autoscaler/v2/tests/test_sdk.py
  python/ray/autoscaler/v2/tests/test_utils.py
  python/ray/autoscaler/v2/utils.py
  python/ray/includes/common.pxd
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/experimental/autoscaler.proto
Labels: tests-ok

#37526 [RLlib] Put notices and error out on invalid ModelV2/Policy related configs for RL Modules
  doc/source/_includes/rllib/rlm_learner_migration_banner.rst
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/package_ref/algorithm.rst
  doc/source/rllib/package_ref/catalogs.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/models.rst
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-rlmodule.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/user-guides.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/autoregressive_action_dist.py
  rllib/examples/batch_norm_model.py
  rllib/examples/custom_env.py
  rllib/examples/custom_loss.py
  rllib/examples/custom_model_loss_and_metrics.py
Labels: v2.6.1-pick

#37861 [Doc] Fix typos in `metrics.md`
  doc/source/cluster/metrics.md
Labels: tests-ok

#37610 [data] Add microbenchmark for reading and transforming images from preprocessed image files
  release/nightly_tests/dataset/app_config.yaml
  release/nightly_tests/dataset/image_loader_microbenchmark.py
  release/nightly_tests/dataset/preprocess_images.py
  release/nightly_tests/dataset/preprocessed_image_loader_microbenchmark.py
  release/nightly_tests/dataset/run_image_loader_microbenchmark.sh
  release/nightly_tests/dataset/run_preprocessed_image_loader_microbenchmark.sh
  release/release_tests.yaml
Labels: @author-action-required

#36306 [Core] Pass logs through if sphinx-doctest is running
  doc/Makefile
  doc/source/conf.py
  python/ray/__init__.py
  python/ray/_private/log.py
  python/ray/_private/ray_logging.py
  python/ray/tests/test_logging.py
Labels: release-blocker

#37875 [RLlib] Put notices and error out on invalid ModelV2/Policy related c…
  doc/source/_includes/rllib/rlm_learner_migration_banner.rst
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/package_ref/algorithm.rst
  doc/source/rllib/package_ref/catalogs.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/models.rst
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-rlmodule.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/user-guides.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/evaluation/tests/test_trajectory_view_api.py
  rllib/examples/autoregressive_action_dist.py
  rllib/examples/batch_norm_model.py
  rllib/examples/custom_env.py
  rllib/examples/custom_loss.py
  rllib/examples/custom_model_loss_and_metrics.py
Labels: tests-ok, v2.6.2-pick

#37871 [Train] Llama 2 workspace template release tests
  doc/source/templates/04_finetuning_llms_with_deepspeed/finetune_hf_llm.py
  doc/source/templates/04_finetuning_llms_with_deepspeed/prepare_nodes.py
  doc/source/templates/04_finetuning_llms_with_deepspeed/run_on_every_node.py
  doc/source/templates/testing/cluster_envs/04_finetuning_llms_with_deepspeed.yaml
  doc/source/templates/testing/compute_configs/04_finetuning_llms_with_deepspeed/aws_70b_v1.yaml
  doc/source/templates/testing/compute_configs/04_finetuning_llms_with_deepspeed/aws_70b_v2.yaml
  doc/source/templates/testing/compute_configs/04_finetuning_llms_with_deepspeed/aws_7b_or_13b.yaml
  doc/source/templates/testing/compute_configs/04_finetuning_llms_with_deepspeed/gce_7b_or_13b.yaml
  release/ray_release/byod/requirements_debian_byod.txt
  release/ray_release/byod/requirements_ml_byod_3.9.in
  release/ray_release/byod/requirements_ml_byod_3.9.txt
  release/release_tests.yaml
Labels: tests-ok

#37382 Update episode_v2.py with last_info_for
  rllib/evaluation/episode_v2.py
  rllib/examples/custom_metrics_and_callbacks.py
Labels: tests-ok

#37800 [data] Fix off-by-one bug in push-based shuffle when computing reduce task args
  python/ray/data/_internal/planner/exchange/push_based_shuffle_task_scheduler.py
  python/ray/data/_internal/push_based_shuffle.py
  python/ray/data/tests/test_sort.py
Labels: tests-ok

#37851 [air] Dreambooth finetuning workspace template
  doc/source/ray-air/examples/dreambooth_finetuning.rst
  doc/source/ray-air/examples/images/dreambooth_example.png
  doc/source/ray-air/examples/images/dreambooth_training.png
  doc/source/templates/05_dreambooth_finetuning/README.md
  doc/source/templates/05_dreambooth_finetuning/configs/Dockerfile
  doc/source/templates/05_dreambooth_finetuning/configs/compute/aws.yaml
  doc/source/templates/05_dreambooth_finetuning/configs/compute/gce.yaml
  doc/source/templates/05_dreambooth_finetuning/dreambooth/cache_model.py
  doc/source/templates/05_dreambooth_finetuning/dreambooth/dataset.py
  doc/source/templates/05_dreambooth_finetuning/dreambooth/download_example_dataset.py
  doc/source/templates/05_dreambooth_finetuning/dreambooth/flags.py
  doc/source/templates/05_dreambooth_finetuning/dreambooth/generate.py
  doc/source/templates/05_dreambooth_finetuning/dreambooth/images/dreambooth_example.png
  doc/source/templates/05_dreambooth_finetuning/dreambooth/images/dreambooth_training.png
  doc/source/templates/05_dreambooth_finetuning/dreambooth/images/lego-car/1.jpg
  doc/source/templates/05_dreambooth_finetuning/dreambooth/images/lego-car/2.jpg
  doc/source/templates/05_dreambooth_finetuning/dreambooth/images/lego-car/3.jpg
  doc/source/templates/05_dreambooth_finetuning/dreambooth/images/lego-car/4.jpg
  doc/source/templates/05_dreambooth_finetuning/dreambooth/images/lego-car/5.jpg
  doc/source/templates/05_dreambooth_finetuning/dreambooth/requirements.txt
  doc/source/templates/05_dreambooth_finetuning/dreambooth/train.py
  doc/source/templates/05_dreambooth_finetuning/dreambooth_run.sh
  doc/source/templates/05_dreambooth_finetuning/playground.ipynb
  release/air_examples/dreambooth/dreambooth
  release/air_examples/dreambooth/dreambooth_run.sh
  release/release_tests.yaml
Labels: tests-ok

#37829 [Data] Remove pre-execution DAG validation check in StreamingExecutor
  python/ray/air/tests/test_new_dataset_config.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/tests/test_actor_pool_map_operator.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_context_propagation.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok

#37909 [air] `pyarrow.fs` persistence: Pass `StorageContext` to Train workers (2/n)
  python/ray/train/_internal/backend_executor.py
  python/ray/train/_internal/session.py
  python/ray/train/_internal/storage.py
  python/ray/train/tests/test_new_persistence.py
  python/ray/train/tests/test_training_iterator.py
  python/ray/train/trainer.py
  python/ray/tune/experiment/config_parser.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/trainable/trainable.py
Labels: @author-action-required

#37903 [serve] Cherry pick fix for setting `request_timeout_s` in config files
  dashboard/modules/serve/serve_agent.py
  doc/source/serve/advanced-guides/performance.md
  doc/source/serve/production-guide/best-practices.md
  python/ray/serve/tests/test_request_timeout.py
Labels: release-blocker, v2.6.2-pick
