Repository ray-project/ray, pull requests merged in 2023-04, with the labels that each got.

#33688 Improve reusability of runtime_env.packaging.`download_and_unpack_package`
  python/ray/_private/runtime_env/packaging.py
  python/ray/tests/test_runtime_env_packaging.py
Labels: @author-action-required

#34011 [Doc] Fix the title of the LightningTrainer starter example
  doc/source/ray-more-libs/using-ray-with-pytorch-lightning.rst
  doc/source/train/examples/lightning/lightning_mnist_example.ipynb
Labels: docs

#34033 [Train] Fix the import path for LightningTrainer to be compatible with Pytorch Lightning 2.0.
  python/ray/train/lightning/lightning_trainer.py
Labels: train

#33857 [RLlib] Fix test backward compatibility test for RL Modules
  rllib/algorithms/a3c/a3c.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/alpha_zero/alpha_zero.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/tests/tf/test_appo_learner.py
  rllib/algorithms/ars/ars.py
  rllib/algorithms/crr/crr.py
  rllib/algorithms/ddppo/ddppo.py
  rllib/algorithms/dreamer/dreamer.py
  rllib/algorithms/es/es.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/tests/test_impala_learner.py
  rllib/algorithms/impala/tests/test_impala_off_policyness.py
  rllib/algorithms/leela_chess_zero/leela_chess_zero.py
  rllib/algorithms/maddpg/maddpg.py
  rllib/algorithms/maml/maml.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/pg/pg.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/sac/sac.py
  rllib/examples/multi_agent_different_spaces_for_agents.py
  rllib/policy/dynamic_tf_policy_v2.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/eager_tf_policy_v2.py
  rllib/policy/policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_v2.py
  rllib/tests/backward_compat/test_backward_compat.py
  rllib/tuned_examples/ppo/pendulum-ppo-with-rl-module.yaml
Labels: release-blocker, do-not-merge

#33906 [data] [streaming] Enable actor fault tolerance by default for streaming map operator
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok, Ray 2.5

#33952 [data] [streaming] Improve progress bar rendering on large scale jobs
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/dataset.py
Labels: tests-ok, Ray 2.5

#33853 [Rllib] Fix test restore checkpoint with nested obs space for RL Modules
  rllib/policy/tests/test_policy_checkpoint_restore.py
  rllib/utils/policy.py
Labels: tests-ok

#33870 [dashboard] Fix log proxy not loading non test/plain files.
  dashboard/modules/log/log_head.py
  dashboard/modules/log/tests/test_log.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/state_cli.py
  python/ray/tests/test_state_api_log.py
Labels: v2.4.0-pick

#32741 Global logging format changes
  ci/lint/check_api_annotations.py
  dashboard/agent.py
  doc/source/ray-observability/ray-logging.rst
  python/ray/__init__.py
  python/ray/_private/log.py
  python/ray/_private/ray_logging.py
  python/ray/_private/test_utils.py
  python/ray/_private/worker.py
  python/ray/serve/tests/test_logging.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_get_or_create_actor.py
  python/ray/tests/test_logging.py
  python/ray/tests/test_multi_node_3.py
  python/ray/tests/test_output.py
  python/ray/tests/test_runtime_env_working_dir_2.py
  python/ray/tune/automl/search_policy.py
  python/ray/tune/tests/test_commands.py
Labels: Ray 2.5

#34074 [core] Fix test_advanced_9 for windows
  python/ray/tests/test_advanced_9.py
Labels: release-blocker, Ray 2.4

#34056 [core][dashboard] Feature flag task logs recording
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/tests/test_task_events_2.py
Labels: v2.4.0-pick

#33820 [logging] Automatically use tqdm_ray.safe_print() for driver logs when tqdm_ray is instantiated
  doc/source/ray-observability/ray-logging.rst
  python/ray/data/tests/test_context_propagation.py
  python/ray/experimental/tqdm_ray.py
Labels: tests-ok, Ray 2.5

#34070 Cherry-pick Serve lightweight config update telemetry
  python/ray/serve/_private/utils.py
  python/ray/serve/controller.py
  python/ray/serve/tests/test_telemetry.py
  src/ray/protobuf/usage.proto
Labels: release-blocker, v2.4.0-pick

#33771 [data] Make actor pool config require explicit kwargs
  doc/source/data/doc_code/transforming_datasets.py
  doc/source/data/key-concepts.rst
  doc/source/data/transforming-datasets.rst
  doc/source/templates/01_batch_inference/batch_inference.ipynb
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_dataset_map.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_streaming_executor.py
  python/ray/data/tests/test_streaming_integration.py
  python/ray/experimental/tqdm_ray.py
  release/nightly_tests/dataset/map_batches_benchmark.py
Labels: tests-ok, Ray 2.5

#34062 [docs] add dask compatibility for 2.4.0
  doc/source/data/dask-on-ray.rst
Labels: release-blocker, v2.4.0-pick

#33999 [Metrics] Add the OOM failure graph
  dashboard/client/src/pages/metrics/Metrics.tsx
  dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  doc/source/ray-observability/ray-metrics.rst
Labels: v2.4.0-pick

#34030 Add objects GC in dataset iterator
  python/ray/data/_internal/dataset_iterator/dataset_iterator_impl.py
  python/ray/data/_internal/dataset_iterator/pipelined_dataset_iterator.py
  python/ray/data/_internal/dataset_iterator/stream_split_dataset_iterator.py
  python/ray/data/dataset_iterator.py
  python/ray/data/tests/test_dataset_pipeline.py
  python/ray/data/tests/test_object_gc.py
Labels: @author-action-required

#34129 Cherry pick the OOM graph PR
  dashboard/client/src/pages/metrics/Metrics.tsx
  dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  doc/source/ray-observability/ray-metrics.rst
Labels: release-blocker, v2.4.0-pick

#33779 [Part 1/n] Rename Dataset => Datastream in top level files and pydocs
  python/ray/data/__init__.py
  python/ray/data/_internal/pipeline_executor.py
  python/ray/data/_internal/plan.py
  python/ray/data/aggregate.py
  python/ray/data/block.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/grouped_dataset.py
  python/ray/data/preprocessor.py
  python/ray/data/random_access_dataset.py
  python/ray/data/read_api.py
  python/ray/data/row.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_dataset_consumption.py
  python/ray/data/tests/test_dataset_image.py
  python/ray/data/tests/test_dataset_map.py
  python/ray/data/tests/test_dataset_numpy.py
  python/ray/data/tests/test_dataset_parquet.py
  python/ray/data/tests/test_dataset_pipeline.py
  python/ray/data/tests/test_dataset_tensor.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_mongo_dataset.py
  python/ray/data/tests/test_optimize.py
  python/ray/train/batch_predictor.py
Labels: Ray 2.5

#33909 [RLlib][Docs] Added RLModule user-guide to the docs
  doc/source/_toc.yml
  doc/source/rllib/doc_code/rlmodule_guide.py
  doc/source/rllib/rllib-rlmodule.rst
Labels: tests-ok, v2.4.0-pick

#33967 [RLlib] DreamerV3: Catalog enhancements (MLP/CNN encoders/heads completed and unified accross DL frameworks).
  doc/source/rllib/package_ref/utils.rst
  rllib/BUILD
  rllib/algorithms/ppo/ppo_catalog.py
  rllib/core/models/base.py
  rllib/core/models/catalog.py
  rllib/core/models/configs.py
  rllib/core/models/specs/specs_base.py
  rllib/core/models/specs/specs_tf.py
  rllib/core/models/specs/tests/test_tensor_spec.py
  rllib/core/models/tests/test_catalog.py
  rllib/core/models/tests/test_cnn_encoders.py
  rllib/core/models/tests/test_mlp_encoders.py
  rllib/core/models/tests/test_mlp_heads.py
  rllib/core/models/tf/base.py
  rllib/core/models/tf/encoder.py
  rllib/core/models/tf/mlp.py
  rllib/core/models/tf/primitives.py
  rllib/core/models/tf/tests/test_tf_mlp_head.py
  rllib/core/models/torch/base.py
  rllib/core/models/torch/encoder.py
  rllib/core/models/torch/mlp.py
  rllib/core/models/torch/primitives.py
  rllib/core/models/torch/tests/test_torch_cnn_encoder.py
  rllib/core/models/torch/tests/test_torch_mlp_encoder.py
  rllib/core/models/torch/tests/test_torch_mlp_head.py
  rllib/models/catalog.py
  rllib/models/torch/misc.py
  rllib/models/utils.py
  rllib/utils/test_utils.py
  rllib/utils/torch_utils.py
Labels: tests-ok

#34108 [core] Improve the workflow finding Redis leader.
  python/ray/tests/test_advanced_9.py
  src/ray/gcs/redis_client.cc
  src/ray/gcs/redis_client.h
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
Labels: release-blocker, P0, Ray 2.4

#33976 [CoreWorker] Partially address Ray child process leaks by killing all child processes in the CoreWorker shutdown sequence.
  python/ray/tests/test_failure_3.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/util/process.cc
  src/ray/util/process.h
  src/ray/util/util_test.cc
Labels: @author-action-required, core, Ray 2.4, v2.4.0-pick

#34169 [data] Rename .cache() to .materialize()
  doc/source/data/api/dataset.rst
  doc/source/data/creating-datasets.rst
  doc/source/data/dataset-internals.rst
  doc/source/data/doc_code/creating_datasets.py
  doc/source/data/doc_code/tensor.py
  doc/source/data/examples/advanced-pipelines.rst
  doc/source/data/examples/nyc_taxi_basic_processing.ipynb
  doc/source/data/key-concepts.rst
  doc/source/data/transforming-datasets.rst
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/examples/torch_image_example.ipynb
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  doc/source/templates/01_batch_inference/batch_inference.ipynb
  python/ray/air/util/check_ingest.py
  python/ray/data/_internal/pipeline_executor.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/tests/preprocessors/test_concatenator.py
  python/ray/data/tests/preprocessors/test_encoder.py
  python/ray/data/tests/preprocessors/test_torch.py
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_dataset_all_to_all.py
  python/ray/data/tests/test_dataset_consumption.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_dataset_image.py
  python/ray/data/tests/test_dataset_map.py
  python/ray/data/tests/test_dataset_parquet.py
  python/ray/data/tests/test_dataset_tensor.py
  python/ray/data/tests/test_dataset_tfrecords.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_mongo_dataset.py
  python/ray/data/tests/test_optimize.py
  python/ray/data/tests/test_size_estimation.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_stats.py
  python/ray/train/tests/test_batch_predictor.py
  release/air_tests/air_benchmarks/mlperf-train/tf_utils.py
  release/nightly_tests/dataset/aggregate_benchmark.py
  release/nightly_tests/dataset/benchmark.py
  release/nightly_tests/dataset/inference.py
  release/nightly_tests/dataset/iter_batches_benchmark.py
  release/nightly_tests/dataset/iter_tensor_batches_benchmark.py
  release/nightly_tests/dataset/map_batches_benchmark.py
  release/nightly_tests/dataset/read_parquet_benchmark.py
  release/nightly_tests/dataset/sort.py
Labels: release-blocker, Ray 2.4

#34084 [core] Fix test_advanced_9 for windows (#34074)
  python/ray/tests/test_advanced_9.py
Labels: release-blocker, Ray 2.4

#34184 [pick] [data] Rename .cache() to .materialize() (#34169)
  doc/source/data/api/dataset.rst
  doc/source/data/creating-datasets.rst
  doc/source/data/dataset-internals.rst
  doc/source/data/doc_code/creating_datasets.py
  doc/source/data/doc_code/tensor.py
  doc/source/data/examples/advanced-pipelines.rst
  doc/source/data/examples/nyc_taxi_basic_processing.ipynb
  doc/source/data/key-concepts.rst
  doc/source/data/transforming-datasets.rst
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/examples/torch_image_example.ipynb
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  doc/source/templates/01_batch_inference/batch_inference.ipynb
  python/ray/air/util/check_ingest.py
  python/ray/data/_internal/pipeline_executor.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/tests/preprocessors/test_concatenator.py
  python/ray/data/tests/preprocessors/test_encoder.py
  python/ray/data/tests/preprocessors/test_torch.py
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_dataset_all_to_all.py
  python/ray/data/tests/test_dataset_consumption.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_dataset_image.py
  python/ray/data/tests/test_dataset_map.py
  python/ray/data/tests/test_dataset_parquet.py
  python/ray/data/tests/test_dataset_tensor.py
  python/ray/data/tests/test_dataset_tfrecords.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_mongo_dataset.py
  python/ray/data/tests/test_optimize.py
  python/ray/data/tests/test_size_estimation.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_stats.py
  python/ray/train/tests/test_batch_predictor.py
  release/air_tests/air_benchmarks/mlperf-train/tf_utils.py
  release/nightly_tests/dataset/aggregate_benchmark.py
  release/nightly_tests/dataset/benchmark.py
  release/nightly_tests/dataset/inference.py
  release/nightly_tests/dataset/iter_batches_benchmark.py
  release/nightly_tests/dataset/iter_tensor_batches_benchmark.py
  release/nightly_tests/dataset/map_batches_benchmark.py
  release/nightly_tests/dataset/read_parquet_benchmark.py
  release/nightly_tests/dataset/sort.py
Labels: Ray 2.4, v2.4.0-pick

#32959 [Dataset] Add `FromXXX` operators
  python/ray/data/_internal/logical/operators/from_arrow_operator.py
  python/ray/data/_internal/logical/operators/from_items_operator.py
  python/ray/data/_internal/logical/operators/from_numpy_operator.py
  python/ray/data/_internal/logical/operators/from_pandas_operator.py
  python/ray/data/_internal/logical/util.py
  python/ray/data/_internal/planner/plan_from_arrow_op.py
  python/ray/data/_internal/planner/plan_from_items_op.py
  python/ray/data/_internal/planner/plan_from_numpy_op.py
  python/ray/data/_internal/planner/plan_from_pandas_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/_internal/util.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_mars.py
  python/ray/data/tests/test_raydp_dataset.py
Labels: tests-ok

#34150 [data] [streaming] Simplify progress bar reporting and integrate with Jupyter
  doc/source/data/dataset-internals.rst
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/_internal/progress_bar.py
  python/ray/data/tests/test_streaming_executor.py
  python/ray/experimental/tqdm_ray.py
  python/ray/tune/experimental/output.py
  python/ray/tune/progress_reporter.py
  python/ray/widgets/util.py
Labels: Ray 2.4

#34181 [Cherry-pick] "[CoreWorker] Partially address Ray child process leaks by killing all child processes in the CoreWorker shutdown sequence. #33976"
  python/ray/tests/test_failure_3.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/util/process.cc
  src/ray/util/process.h
  src/ray/util/util_test.cc
Labels: core, v2.4.0-pick

#33797 [Java] make java worker log file prefix (default to java-worker) configurable
  java/runtime/src/main/java/io/ray/runtime/util/LoggingUtil.java
  java/runtime/src/main/resources/ray.default.conf
  java/runtime/src/test/java/io/ray/runtime/config/RayConfigTest.java
Labels: tests-ok

#34101 [no_early_kickoff][core][dashboard] Feature flag task logs recording (#34056)
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/tests/test_task_events_2.py
Labels: release-blocker, v2.4.0-pick

#34087 [core] Mark raylet unhealthy if GCS can't recognize it.
  python/ray/tests/test_gcs_fault_tolerance.py
  python/requirements_test.txt
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/common/ray_config_def.h
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/raylet/node_manager.cc
Labels: release-blocker, P0, Ray 2.4

#34037 [Data] Improve state initialization for `ActorPoolMapOperator`
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/tests/test_operators.py
Labels: @author-action-required

#34163 [Serve][Release][Part1] Enable tests to GCE
  release/release_tests.yaml
  release/serve_tests/compute_tpl_32_cpu_autoscaling_gce.yaml
  release/serve_tests/compute_tpl_32_cpu_gce.yaml
  release/serve_tests/compute_tpl_8_cpu_autoscaling_gce.yaml
Labels: tests-ok

#34192 [core] Fix the placement group stress test regression.
  src/ray/raylet/node_manager.cc
Labels: release-blocker, Ray 2.4

#33964 [Core] lazy import autoscaler + don't import opentelemetry unless setup hook
  python/ray/__init__.py
  python/ray/_private/test_utils.py
  python/ray/_private/worker.py
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_metrics_agent.py
  python/ray/tests/test_out_of_disk_space.py
  python/ray/tests/test_top_level_api.py
  python/ray/tests/test_usage_stats.py
  python/ray/util/joblib/ray_backend.py
  python/ray/util/multiprocessing/pool.py
  python/ray/util/tracing/tracing_helper.py
  release/benchmarks/distributed/dashboard_test.py
Labels: @author-action-required

#34178 [docs][KubeRay] Update KubeRay doc for release v0.5.0
  doc/source/cluster/kubernetes/configs/ray-cluster.log.yaml
  doc/source/cluster/kubernetes/examples/gpu-training-example.md
  doc/source/cluster/kubernetes/getting-started.ipynb
  doc/source/cluster/kubernetes/index.md
  doc/source/cluster/kubernetes/references.md
  doc/source/cluster/kubernetes/user-guides/config.md
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.md
  doc/source/cluster/kubernetes/user-guides/gpu.rst
  doc/source/cluster/kubernetes/user-guides/logging.md
  doc/source/serve/doc_code/fault_tolerance/k8s_config.yaml
  doc/source/serve/production-guide/fault-tolerance.md
  doc/source/serve/production-guide/kubernetes.md
  python/ray/autoscaler/kuberay/init-config.sh
  release/k8s_tests/run_gcs_ft_on_k8s.py
Labels: tests-ok

#34237 [core][ci] Fix test_fault_tolerance_actor_tasks_failed for test_task_events_2.py
  python/ray/tests/test_task_events_2.py
Labels: tests-ok

#34216 [2.4pick][core] Mark raylet unhealthy if GCS can't recognize it. (#34087)
  python/ray/tests/test_gcs_fault_tolerance.py
  python/requirements_test.txt
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/common/ray_config_def.h
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/raylet/node_manager.cc
Labels: release-blocker, P0, Ray 2.4, v2.4.0-pick

#34183 [2.4pick][core] Improve the workflow finding Redis leader. (#34108)
  python/ray/tests/test_advanced_9.py
  src/ray/gcs/redis_client.cc
  src/ray/gcs/redis_client.h
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
Labels: release-blocker, Ray 2.4, v2.4.0-pick

#34249 [2.4pick][core] Fix the placement group stress test regression. (#34192)
  src/ray/raylet/node_manager.cc
Labels: release-blocker, P0, Ray 2.4, v2.4.0-pick

#34228 [try 2] [doc] [data] Fix autosummary issues
  doc/source/data/api/dataset.rst
  doc/source/data/api/execution_options.rst
Labels: tests-ok

#34279 [pick] [try 2] [doc] [data] Fix autosummary issues
  doc/source/data/api/dataset.rst
  doc/source/data/api/execution_options.rst
Labels: v2.4.0-pick

#32738 [Doc] Make front page images non clickable
  doc/source/index.md
Labels: tests-ok

#34296 [Cherrypick 2.4][data] Make sure the tf and tensor iteration work in dataset pipeline
  python/ray/data/_internal/stats.py
  python/ray/data/dataset_iterator.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_dataset_pipeline.py
Labels: @author-action-required

#34320 [CherryPick] [ci/mac] Fix arm64 wheels builds (#34268)
  ci/build/test-wheels.sh
Labels: v2.4.0-pick

#34299 [core][state] Add head node flag `is_head_node` to state API and GcsNodeInfo
  python/ray/_private/node.py
  python/ray/_private/services.py
  python/ray/experimental/state/common.py
  python/ray/tests/test_state_api.py
  src/ray/protobuf/gcs.proto
  src/ray/raylet/main.cc
  src/ray/raylet/raylet.cc
  src/ray/raylet/raylet.h
Labels: tests-ok

#34261 Fix dask dependencies
  release/nightly_tests/chaos_test/dask_on_ray_app_config_reconstruction.yaml
  release/nightly_tests/dask_on_ray/dask_on_ray_app_config.yaml
  release/nightly_tests/dask_on_ray/large_scale_dask_on_ray_app_config.yaml
Labels: tests-ok, v2.4.0-pick

#34247 [Doc] Fix typo in Tune restore guide
  doc/source/tune/doc_code/fault_tolerance.py
Labels: tests-ok

#34332 [Release] Fix dask dependencies (#34261)
  release/nightly_tests/chaos_test/dask_on_ray_app_config_reconstruction.yaml
  release/nightly_tests/dask_on_ray/dask_on_ray_app_config.yaml
  release/nightly_tests/dask_on_ray/large_scale_dask_on_ray_app_config.yaml
Labels: v2.4.0-pick

#34318 [Jobs] Fix race condition in supervisor actor creation and add timeout for pending jobs (#34223)
  dashboard/consts.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/test_job_manager.py
Labels: v2.4.0-pick

#34289 [build_base] update templates
  doc/source/templates/01_batch_inference/README.md
  doc/source/templates/02_many_model_training/README.md
  doc/source/templates/03_serving_stable_diffusion/README.md
  doc/source/templates/configs/anyscale_cluster_env.yaml
  doc/source/templates/configs/compute/cpu/aws_large.yaml
  doc/source/templates/configs/compute/cpu/gcp_large.yaml
  doc/source/templates/configs/compute/gpu/aws_large.yaml
  doc/source/templates/configs/compute/gpu/gcp_large.yaml
  doc/source/templates/templates.yaml
Labels: tests-ok

#33969 [RLlib] DreamerV3: Add Conv2d-transpose support to new model Catalog.
  rllib/BUILD
  rllib/core/models/configs.py
  rllib/core/models/tests/test_catalog.py
  rllib/core/models/tests/test_cnn_encoders.py
  rllib/core/models/tests/test_cnn_transpose_heads.py
  rllib/core/models/tests/test_mlp_encoders.py
  rllib/core/models/tf/heads.py
  rllib/core/models/tf/primitives.py
  rllib/core/models/torch/heads.py
  rllib/core/models/torch/primitives.py
  rllib/core/models/torch/utils.py
  rllib/models/torch/misc.py
Labels: tests-ok

#34355 [train] Fix rendering of diff code-blocks
  doc/source/train/dl_guide.rst
Labels: tests-ok

#34377 [serve] Fix get endpoint when autoscaling config is set
  dashboard/modules/serve/tests/test_serve_agent.py
  python/ray/serve/schema.py
Labels: release-blocker, P0

#34282 [Dataset] Validate sort key in `Sort` LogicalOperator
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/planner/sort.py
  python/ray/data/_internal/stage_impl.py
  python/ray/data/_internal/util.py
  python/ray/data/aggregate.py
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok

#34384 [data] Add usage tag for which block formats are used
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/usage.py
  python/ray/data/block.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_util.py
  src/ray/protobuf/usage.proto
Labels: tests-ok

#34372 [Dataset] Reset row count when filtering on Dataset reading from Parquet
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/test_dataset_parquet.py
Labels: tests-ok

#34373 Remove python 3.6 support [1/n]
  .buildkite/pipeline.build.yml
  .buildkite/pipeline.windows.yml
  ci/build/build-docker-images.py
  ci/build/test-wheels.sh
  ci/env/install-minimal.sh
  ci/lint/clang-tidy-diff.py
  doc/source/cluster/vms/references/ray-cluster-configuration.rst
  doc/source/ray-overview/installation.rst
  docker/retag-lambda/python_versions.txt
  python/build-wheel-macos.sh
  python/build-wheel-manylinux2014.sh
  python/ray/__init__.py
  python/ray/_private/async_compat.py
  python/ray/_private/ray_constants.py
  python/ray/_private/utils.py
  python/ray/_private/workers/default_worker.py
  python/ray/autoscaler/aws/example-gpu-docker.yaml
  python/ray/autoscaler/aws/example-java.yaml
  python/ray/autoscaler/gcp/example-gpu-docker.yaml
  python/ray/nightly-wheels.yaml
  python/ray/tests/test_runtime_env.py
  python/requirements/compat/requirements_py36_compat.txt
  python/setup.py
  release/ray_release/schema.json
  release/util/download_wheels.sh
  release/util/pip_download_test.sh
Labels: @author-action-required

#34423 [train] rename _base_dataset to _base_datastream
  python/ray/train/huggingface/_huggingface_utils.py
Labels: tests-ok

#34272 [RLlib] DreamerV3: Catalog enhancements 04 - LSTM default models
  rllib/BUILD
  rllib/algorithms/appo/tests/tf/test_appo_learner.py
  rllib/algorithms/ppo/tests/test_ppo_rl_module.py
  rllib/algorithms/ppo/tf/ppo_tf_rl_module.py
  rllib/core/models/base.py
  rllib/core/models/configs.py
  rllib/core/models/tests/test_catalog.py
  rllib/core/models/tests/test_recurrent_encoders.py
  rllib/core/models/tf/encoder.py
  rllib/core/models/torch/base.py
  rllib/core/models/torch/encoder.py
  rllib/utils/test_utils.py
Labels: tests-ok

#34292 [Dataset] Validate aggregation key in `Aggregate` LogicalOperator
  python/ray/data/_internal/planner/aggregate.py
  python/ray/data/aggregate.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok

#33905 release logs for 2.4.0
  release/release_logs/2.4.0/benchmarks/many_actors.json
  release/release_logs/2.4.0/benchmarks/many_nodes.json
  release/release_logs/2.4.0/benchmarks/many_pgs.json
  release/release_logs/2.4.0/benchmarks/many_tasks.json
  release/release_logs/2.4.0/microbenchmark.json
  release/release_logs/2.4.0/scalability/object_store.json
  release/release_logs/2.4.0/scalability/single_node.json
  release/release_logs/2.4.0/stress_tests/stress_test_dead_actors.json
  release/release_logs/2.4.0/stress_tests/stress_test_many_tasks.json
  release/release_logs/2.4.0/stress_tests/stress_test_placement_group.json
  release/release_logs/compare_perf_metrics
Labels: v2.4.0-pick

#34326 [CherryPick][Serve][Doc] Update metrics & log doc (#34222)
  doc/source/serve/doc_code/monitoring/custom_metric_snippet.py
  doc/source/serve/production-guide/monitoring.md
Labels: v2.4.0-pick

#34059 [Cherrypick][Serve][Doc] Add object detection example (#33760)
  doc/BUILD
  doc/source/serve/doc_code/object_detection.py
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/object-detection.md
Labels: v2.4.0-pick

#34441 [data] [streaming] Improve handling of KeyboardInterrupt
  python/ray/data/_internal/execution/streaming_executor.py
Labels: tests-ok

#34161 [RLlib][Docs] Added RLModule user-guide to the docs (#33909)
  doc/source/_toc.yml
  doc/source/rllib/doc_code/rlmodule_guide.py
  doc/source/rllib/rllib-rlmodule.rst
Labels: v2.4.0-pick

#34297 [no_early_kickoff][core][state] Make state api return results that are strongly typed
  dashboard/state_aggregator.py
  python/ray/_private/profiling.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/exception.py
  python/ray/experimental/state/state_cli.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_state_api_summary.py
Labels: tests-ok

#34300 [core][state] Use `--err` flag to query stderr logs from worker/actors instead of `--suffix=err`
  dashboard/modules/log/log_manager.py
  dashboard/modules/state/state_head.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/tests/test_state_api_log.py
Labels: tests-ok

#34210 [Serve] gRPC Deployment schema check & minor improvements
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/deployment.py
  python/ray/serve/tests/test_api.py
Labels: tests-ok

#34339 [Data] Fix mutable dataclass attribute
  python/ray/data/_internal/execution/interfaces.py
Labels: bug

#34336 [data] Experimental strict schema mode
  python/ray/data/BUILD
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/delegating_block_builder.py
  python/ray/data/_internal/planner/map_batches.py
  python/ray/data/_internal/planner/map_rows.py
  python/ray/data/_internal/planner/plan_from_numpy_op.py
  python/ray/data/_internal/planner/write.py
  python/ray/data/_internal/table_block.py
  python/ray/data/_internal/util.py
  python/ray/data/block.py
  python/ray/data/context.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/numpy_datasource.py
  python/ray/data/datastream.py
  python/ray/data/preprocessor.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_strict_mode.py
Labels: tests-ok

#34267 [no_early_kickoff][RLlib][Docs] Add Catalog user-guide to docs (#33898)
  doc/source/_includes/rllib/rlmodules_rollout.rst
  doc/source/_toc.yml
  doc/source/rllib/doc_code/catalog_guide.py
  doc/source/rllib/images/catalog/catalog_and_rlm_diagram.svg
  doc/source/rllib/images/catalog/catalog_rlmspecs_diagram.svg
  doc/source/rllib/images/catalog/ppo_catalog_and_rlm_diagram.svg
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/package_ref/catalogs.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/rllib-catalogs.rst
  doc/source/rllib/rllib-rlmodule.rst
  doc/source/rllib/user-guides.rst
  rllib/algorithms/ppo/ppo_base_rl_module.py
  rllib/core/models/torch/primitives.py
  rllib/examples/catalog/custom_action_distribution.py
Labels: v2.4.0-pick

#34463 [ci] Remove scripts duplicates and symlinks except for format.sh
  scripts/bazel-format.sh
  scripts/bazel.py
  scripts/bazel_cache_credential.json.enc
  scripts/bazel_export_options
  scripts/bazel_sharding.py
  scripts/build-docker-images.py
  scripts/build-multinode-image.py
  scripts/check-bazel-team-owner.py
  scripts/check-git-clang-format-output.sh
  scripts/check-git-clang-tidy-output.sh
  scripts/check-test-run.py
  scripts/check_import_order.py
  scripts/check_minimal_install.py
  scripts/clang-tidy-diff.py
  scripts/copyright-format.sh
  scripts/default-copyright.txt
  scripts/determine_tests_to_run.py
  scripts/env_info.sh
  scripts/fix-windows-container-networking.ps1
  scripts/get_build_info.py
  scripts/git-clang-format
  scripts/install-bazel.sh
  scripts/install-default.sh
  scripts/install-dependencies.sh
  scripts/install-horovod.sh
  scripts/install-llvm-binaries.sh
  scripts/install-minimal.sh
  scripts/install-strace.sh
  scripts/install-toolchains.sh
  scripts/iwyu.sh
  scripts/kind.config.yaml
  scripts/pre-push
  scripts/prep-k8s-environment.sh
  scripts/py_dep_analysis.py
  scripts/py_dep_analysis_test.py
  scripts/pytest_checker.py
  scripts/run_bazel_test_with_sharding.sh
  scripts/test-wheels.sh
  scripts/test-worker-in-container.sh
  scripts/upload_build_info.sh
Labels: @author-action-required

#34517 [ci] Fix further linter errors
  build-docker.sh
  python/ray/data/block.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/datastream.py
  python/ray/tests/test_cancel.py
  release/air_examples/dreambooth/dreambooth_run.sh
  release/run_release_test.sh
Labels: tests-ok

#34470 [air] Use Ray storage URI as default storage path, if configured [no_early_kickoff]
  python/ray/_private/storage.py
  python/ray/air/_internal/checkpoint_manager.py
  python/ray/air/config.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/tune.py
Labels: @author-action-required

#34487 [Release test] [Cluster launcher] Add release test for aws `example-full.yaml`
  python/ray/autoscaler/aws/example-full.yaml
  release/release_tests.yaml
Labels: tests-ok

#34275 [docs][KubeRay] Provide some GKE instructions in KubeRay example
  doc/source/cluster/doc_code/pytorch_training_e2e_submit.py
  doc/source/cluster/kubernetes/configs/ray-cluster.gpu.yaml
  doc/source/cluster/kubernetes/examples/gpu-training-example.md
  doc/source/cluster/kubernetes/examples/ml-example.md
Labels: docs, v2.4.0-pick

#34250 [docs][KubeRay] Update KubeRay doc for release v0.5.0
  doc/source/cluster/kubernetes/configs/ray-cluster.log.yaml
  doc/source/cluster/kubernetes/examples/gpu-training-example.md
  doc/source/cluster/kubernetes/getting-started.ipynb
  doc/source/cluster/kubernetes/index.md
  doc/source/cluster/kubernetes/references.md
  doc/source/cluster/kubernetes/user-guides/config.md
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.md
  doc/source/cluster/kubernetes/user-guides/gpu.rst
  doc/source/cluster/kubernetes/user-guides/logging.md
  doc/source/serve/doc_code/fault_tolerance/k8s_config.yaml
  doc/source/serve/production-guide/fault-tolerance.md
  doc/source/serve/production-guide/kubernetes.md
  python/ray/autoscaler/kuberay/init-config.sh
  release/k8s_tests/run_gcs_ft_on_k8s.py
Labels: tests-ok, v2.4.0-pick

#34537 [no_early_kickoff][RLlib] Fix two RL docs examples (#34353)
  rllib/algorithms/algorithm_config.py
  rllib/core/models/catalog.py
Labels: v2.4.0-pick

#34546 [cherry pick][docs] for new landing page for 2.4.0
  doc/source/_includes/_contribute.md
  doc/source/_static/css/custom.css
  doc/source/_static/img/AIR.png
  doc/source/_static/img/Core.png
  doc/source/_static/img/LandingPageBG.jpg
  doc/source/_static/img/chat.png
  doc/source/_static/img/code.png
  doc/source/_static/img/colab.png
  doc/source/_static/img/download.png
  doc/source/_static/img/github-fill.png
  doc/source/_static/img/mail.png
  doc/source/_static/img/meetup.png
  doc/source/_static/img/pen.png
  doc/source/_static/img/ray_logo.png
  doc/source/_static/img/rayclusters.png
  doc/source/_static/img/slack-fill.png
  doc/source/_static/img/twitter-fill.png
  doc/source/_static/js/custom.js
  doc/source/conf.py
  doc/source/index.md
Labels: v2.4.0-pick

#34555 [data] Standardize on Arrow types for schema() in strict mode
  python/ray/data/datastream.py
  python/ray/data/tests/test_strict_mode.py
Labels: tests-ok

#34426 [Serve] [Docs] Change incorrect Serve app name in Stable Diffusion tutorial
  doc/source/serve/doc_code/stable_diffusion.py
Labels: tests-ok

#34603 [Data] [strict-mode] Remove internal TableRow abstractions and instead use Dict[str, Any] as the row format
  python/ray/data/_internal/table_block.py
  python/ray/data/datastream.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_strict_mode.py
Labels: tests-ok

#34461 [Tune] Enable `tune.ExperimentAnalysis` to pull experiment checkpoint files from the cloud if needed
  python/ray/air/_internal/checkpoint_manager.py
  python/ray/air/_internal/remote_storage.py
  python/ray/air/_internal/uri_utils.py
  python/ray/tune/BUILD
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/execution/experiment_state.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/result_grid.py
  python/ray/tune/tests/conftest.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_result_grid.py
  python/ray/tune/tests/test_syncer.py
  python/ray/tune/tests/utils/experiment.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/trainable/util.py
  python/ray/tune/tune.py
Labels: tests-ok

#34547 [Datasets] Support non-shuffle repartitioning in `Repartition` `LogicalOperator`
  python/ray/data/_internal/planner/exchange/split_repartition_task_scheduler.py
  python/ray/data/_internal/planner/repartition.py
  python/ray/data/tests/preprocessors/__init__.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok

#34676 Cherry pick doc PRs #34614 #34615 #34435 #34505 #34617 #34623 #34660
  doc/source/_static/js/custom.js
  doc/source/images/llm-stack.png
  doc/source/ray-contribute/docs.ipynb
  doc/source/ray-overview/use-cases.rst
  doc/source/serve/getting_started.md
  python/ray/tune/tests/tutorial.py
Labels: v2.4.0-pick

#34588 [Data] Require `batch_size` for GPU `map_batches` in strict mode
  python/ray/data/block.py
  python/ray/data/context.py
  python/ray/data/datastream.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_strict_mode.py
Labels: @author-action-required

#34260 [Serve] Add default app name
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_function_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/api.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_advanced.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_constructor_failure.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_controller_recovery.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deployment_graph.py
  python/ray/serve/tests/test_deployment_graph_autoscaling.py
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/test_gcs_failure.py
  python/ray/serve/tests/test_get_deployment.py
  python/ray/serve/tests/test_grpc.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_healthcheck.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_persistence.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_runtime_env.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/test_standalone2.py
Labels: tests-ok

#34705 [Data] Implement limit physical operator
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/limit_operator.py
  python/ray/data/_internal/logical/operators/limit_operator.py
  python/ray/data/_internal/stage_impl.py
  python/ray/data/datastream.py
Labels: @author-action-required

#34758 [Serve] Fix dashboard test
  dashboard/modules/serve/tests/test_serve_agent.py
Labels: tests-ok

#26900 Use PID to assign rainbow colors to console output prefixes.
  doc/source/ray-observability/images/coloring-actor-log-prefixes.png
  doc/source/ray-observability/ray-logging.rst
  python/ray/_private/worker.py
Labels: core-interface-change-approval-required

#34697 [core] Add more message when accessing a dead actor.
  BUILD.bazel
  cpp/src/ray/runtime/task/native_task_submitter.cc
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_failure_4.py
  src/ray/common/status.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
  src/ray/internal/internal.cc
  src/ray/internal/internal.h
Labels: @author-action-required

#34687 [core] Deflakey `test_placement_group_3.py` when ray syncer is turned on.
  python/ray/tests/test_placement_group_3.py
  src/mock/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_monitor_server_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_resource_manager_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/placement_group_resource_manager_test.cc
  src/ray/raylet/scheduling/cluster_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_manager_test.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_2_test.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy_test.cc
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
Labels: @author-action-required

#34467 [Core] Put pg state to kv store when pg rescheduling
  python/ray/_private/state.py
  python/ray/tests/test_placement_group_failover.py
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
Labels: @author-action-required

#33541 [no_early_kickoff][Core][Dashboard]Configurable dashboard RPC port and public IP
  dashboard/consts.py
  dashboard/dashboard.py
  dashboard/head.py
  dashboard/tests/test_dashboard.py
  doc/source/ray-core/configure.rst
  python/ray/_private/node.py
  python/ray/_private/parameter.py
  python/ray/_private/services.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_dashboard.py
Labels: @external-author-action-required

#34789 [air/tune] use ray-provided `tabulate` package
  doc/requirements-doc.txt
  doc/source/tune/api/cli.rst
  docker/examples/Dockerfile
  python/ray/_private/thirdparty/tabulate/tabulate.py
  python/ray/air/config.py
  python/ray/data/datastream.py
  python/ray/tests/ludwig/ludwig_test_utils.py
  python/ray/train/data_parallel_trainer.py
  python/ray/tune/cli/commands.py
  python/ray/tune/examples/tune-default.yaml
  python/ray/tune/examples/tune-local-default.yaml
  python/ray/tune/experimental/output.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/requirements-dev.txt
  python/ray/tune/syncer.py
  python/ray/widgets/util.py
  python/requirements.txt
  python/setup.py
Labels: @author-action-required

#34663 [air] remote_storage: Prefer fsspec filesystems over native pyarrow
  python/ray/air/_internal/remote_storage.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_syncer.py
  python/requirements/ml/requirements_tune.txt
Labels: tests-ok

#34809 [data] [streaming] Fix backpressure when reading directly from input datasource
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/tests/test_streaming_backpressure_edge_case.py
Labels: tests-ok

#34800 [Data] Fix limit operator
  python/ray/data/_internal/execution/operators/limit_operator.py
  python/ray/data/tests/test_consumption.py
Labels: @author-action-required

#33618 [docs] Remove `requirements-rtd.txt`
  ci/env/install-dependencies.sh
  doc/requirements-rtd.txt
Labels: tests-ok

#34843 [data] Fix hang in test_streaming_backpressure
  python/ray/data/_internal/execution/streaming_executor.py
Labels: tests-ok

#34811 [data] [streaming] Autoshutdown executor threads when deleted
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/datastream.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok

#34819 [Data] Cooperatively exit producer threads for `iter_batches`
  python/ray/data/_internal/block_batching/util.py
  python/ray/data/tests/block_batching/test_util.py
Labels: tests-ok, @author-action-required

#34071 [Doc] [runtime env] Clarify conditions for local `pip` and `conda` requirements files
  doc/source/ray-core/handling-dependencies.rst
Labels: tests-ok
