Repository ray-project/ray, pull requests merged in 2023-03, with the labels that each got.

#32902 [RLlib; CI] Pinned git dependency for minigrid since the pypi wheel is broken
  python/requirements/ml/requirements_rllib.txt
  rllib/algorithms/mock.py
Labels: tests-ok

#32540 Deflake test_dataset.py: split tensor tests
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_tensor.py
Labels: tests-ok

#32675 [data] [streaming] Streaming split support--- [1/2] Add streaming split op
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/tests/test_operators.py
Labels: tests-ok

#32844 [doc][xlang] Update xlang doc
  doc/source/ray-core/cross-language.rst
  doc/source/ray-core/doc_code/cross_language.py
Labels: xlang, docs

#32832 [RLlib] Fix test_repro_ppo learner when learner API is enabled
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/tests/test_impala_off_policyness.py
  rllib/algorithms/impala/tests/tf/test_impala_learner.py
  rllib/algorithms/impala/tf/impala_tf_learner.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/ppo_base_learner.py
  rllib/algorithms/ppo/tests/test_ppo_learner.py
  rllib/core/learner/learner.py
  rllib/core/learner/tests/test_learner.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/core/learner/tf/tf_learner.py
  rllib/core/learner/torch/tests/test_torch_learner.py
  rllib/core/testing/testing_learner.py
  rllib/evaluation/rollout_worker.py
  rllib/utils/metrics/__init__.py
  rllib/utils/test_utils.py
Labels: tests-ok

#32625 [core]Turn on light weight resource broadcasting.
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#32882 Streaming executor fixes #4
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_dataset.py
Labels: tests-ok

#32949 [Datasets] Fix typos in `collate_fn` error message
  python/ray/air/_internal/torch_utils.py
Labels: tests-ok

#32478 Optimize submit Ray task with many positional arguments
  python/ray/_raylet.pyx
Labels: performance

#32874 [AIR/Docs] Large model inference examples
  doc/source/_toc.yml
  doc/source/ray-air/examples/BUILD
  doc/source/ray-air/examples/gptj_batch_prediction.ipynb
  doc/source/ray-air/examples/index.rst
  doc/source/ray-air/examples/stablediffusion_batch_prediction.ipynb
Labels: @author-action-required

#32928 [data] Refactor DatasetIterator class for cleaner delegation
  python/ray/air/_internal/torch_utils.py
  python/ray/data/_internal/bulk_dataset_iterator.py
  python/ray/data/_internal/pipelined_dataset_iterator.py
  python/ray/data/dataset.py
  python/ray/data/dataset_iterator.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_dataset_iterator.py
  python/ray/train/BUILD
  python/ray/train/_internal/dataset_iterator.py
  python/ray/train/_internal/dataset_spec.py
  python/ray/train/tests/test_dataset_iterator.py
  python/ray/train/torch/train_loop_utils.py
Labels: tests-ok

#32862 [AIR] Use a configurable ray temp directory for the `TempFileLock` util
  python/ray/air/BUILD
  python/ray/air/_internal/filelock.py
  python/ray/air/tests/test_utils.py
Labels: tests-ok

#32041 [air][tune] Aim logger
  doc/source/_toc.yml
  doc/source/images/aim_example_metrics_page.png
  doc/source/images/aim_logo.png
  doc/source/images/aim_logo_full.png
  doc/source/tune/api/logging.rst
  doc/source/tune/examples/experiment-tracking.rst
  doc/source/tune/examples/tune-aim.ipynb
  python/ray/tune/logger/aim.py
  python/ray/tune/tests/test_logger.py
  python/requirements/ml/requirements_tune.txt
Labels: tests-ok

#32976 Revert "[serve] Replace Ray Client with Ray Job Submission for `serve…
  doc/source/serve/dev-workflow.md
  python/ray/serve/run_script.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/test_cli.py
Labels: v2.3.1-pick

#33015 [Cherry-pick][2.3.1] #32679
  release/ray_release/cluster_manager/minimal.py
  release/ray_release/util.py
  release/requirements.txt
  release/requirements_buildkite.txt
Labels: v2.3.1-pick

#33017 [Data] Fix quickstart by using S3
  doc/source/data/doc_code/quick_start.py
Labels: v2.3.1-pick

#33069 [RLlib] Don't import jax in long runnign release tests
  release/long_running_tests/app_config.yaml
Labels: v2.3.1-pick

#33094 [AIR] Label `Checkpoint.from_checkpoint` as developer API
  python/ray/air/checkpoint.py
Labels: tests-ok

#33101 [Datasets] Split test_dataset.py completely into test_dataset_{consumption,map,all_to_all}.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_all_to_all.py
  python/ray/data/tests/test_dataset_consumption.py
  python/ray/data/tests/test_dataset_ecosystem.py
  python/ray/data/tests/test_dataset_map.py
  python/ray/data/tests/test_dataset_parquet.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_split.py
  python/ray/data/tests/test_stats.py
  python/ray/data/tests/test_transform_pyarrow.py
Labels: tests-ok

#33103 [attempt 2] Eager import pandas in ray data for python >= 3.7
  python/ray/data/__init__.py
  python/ray/data/tests/test_dataset_image.py
Labels: tests-ok

#33095 [tune] Prefix global object registry with job ID to avoid conflicts in multi tenancy
  doc/source/tune/faq.rst
  python/ray/tune/registry.py
  python/ray/tune/tests/_test_multi_tenancy_run.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_multi_tenancy.py
Labels: @author-action-required

#33105 [Datasets] Fix the get_name() for ParquetDatasource
  python/ray/data/datasource/parquet_base_datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/test_dataset_parquet.py
  python/ray/data/tests/test_optimize.py
  python/ray/data/tests/test_stats.py
Labels: tests-ok

#32896 [Datasets] Add telemetry for Ray Data
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/logical/util.py
  src/ray/protobuf/usage.proto
Labels: tests-ok

#33104 docs serve: remove unused json resolver
  doc/source/serve/doc_code/production_fruit_example.py
Labels: tests-ok

#33102 [RLlib] RLModule -- remove from_model_config
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/tests/tf/test_impala_learner.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/ppo_base_rl_module.py
  rllib/algorithms/ppo/ppo_catalog.py
  rllib/algorithms/ppo/ppo_rl_module_config.py
  rllib/algorithms/ppo/tests/test_ppo_learner.py
  rllib/algorithms/ppo/tests/test_ppo_rl_module.py
  rllib/core/learner/learner.py
  rllib/core/learner/tests/test_learner.py
  rllib/core/learner/tests/test_learner_group_config.py
  rllib/core/learner/torch/tests/test_torch_learner.py
  rllib/core/models/catalog.py
  rllib/core/models/tests/test_catalog.py
  rllib/core/rl_module/marl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/core/rl_module/tests/test_marl_module.py
  rllib/core/rl_module/tests/test_rl_module_specs.py
  rllib/core/rl_module/tf/tests/test_tf_rl_module.py
  rllib/core/rl_module/torch/tests/test_torch_rl_module.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/core/testing/tests/test_bc_algorithm.py
  rllib/core/testing/tf/bc_module.py
  rllib/core/testing/torch/bc_module.py
  rllib/core/testing/utils.py
  rllib/models/tf/tf_distributions.py
  rllib/models/torch/torch_distributions.py
  rllib/policy/policy.py
Labels: tests-ok

#33064 [RLlib] Export RLLIB_TEST_NO_JAX_IMPORT=1 (#33023)
  release/long_running_tests/app_config.yaml
  release/rllib_tests/app_config.yaml
  rllib/utils/framework.py
Labels: v2.3.1-pick

#33082 [data] [streaming] Prerequisite refactoring for supporting streaming split operation
  python/ray/data/_internal/dataset_iterator_impl.py
  python/ray/data/_internal/execution/bulk_executor.py
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_streaming_executor.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok

#32362 [RLlib] Issue 32267: `__common__` key should be allowed in multi-agent infos dict (for infos concerning all/no agents).
  rllib/env/multi_agent_env.py
Labels: tests-ok

#32650 [RLLib] Test with CNNs in RLModule tests
  rllib/algorithms/ppo/ppo_catalog.py
  rllib/algorithms/ppo/tests/test_ppo_rl_module.py
  rllib/algorithms/ppo/tests/test_ppo_with_rl_module.py
  rllib/core/models/torch/encoder.py
  rllib/core/models/torch/primitives.py
Labels: tests-ok

#33030 [K8S] Make Ray head service headless
  doc/source/cluster/kubernetes/configs/static-ray-cluster.with-fault-tolerance.yaml
Labels: tests-ok

#31799 [Core] Make multiprocessing pool raise TypeError when provided a non-iterable in imap or imap_unordered
  python/ray/tests/test_multiprocessing.py
  python/ray/util/multiprocessing/pool.py
Labels: core, Ray 2.4

#32359 [RLlib] Forum 9306: No env on local worker (IMPALA)
  rllib/algorithms/impala/impala.py
  rllib/env/wrappers/atari_wrappers.py
Labels: tests-ok

#33136 [Doc] Add workaround to Serve docs for broken dependency
  doc/source/serve/tutorials/batch.md
  doc/source/serve/tutorials/serve-ml-models.md
Labels: tests-ok, v2.3.1-pick

#33014 [Datasets] Add logical and physical operator for zip()
  python/ray/data/_internal/execution/operators/zip_operator.py
  python/ray/data/_internal/logical/operators/n_ary_operator.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok

#33117 [Datasets] Improve performance of DefaultFileMetaProvider.
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_dataset_csv.py
  python/ray/data/tests/test_metadata_provider.py
Labels: @author-action-required

#33170 [Datasets] Remove the class `Write(AbstractUDFMap)`
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/logical/util.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
Labels: tests-ok

#33171 [Datasets] Remove the assertion for ds.stats() in test_dataset_image.py
  python/ray/data/tests/test_dataset_image.py
Labels: tests-ok

#33185 [Datasets] [Docs] Fix description of `read_parquet`
  doc/source/data/creating-datasets.rst
Labels: tests-ok

#33149 [runtime env] Add environment variable to skip parsing `.gitignore` file into `"excludes"`
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/ray_constants.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/tests/test_runtime_env_packaging.py
Labels: tests-ok

#33234 [RLlib] RLModule, Fix env runner v2 test multi agent issues
  rllib/evaluation/tests/test_env_runner_v2.py
Labels: tests-ok

#31968 [doc] more typo fixes
  doc/source/rllib/core-concepts.rst
Labels: stale

#33168 [Datasets] Make telemetry record usage by default
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/logical/util.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: @author-action-required

#33122 [data] Add TQDM implementation ray.experimental.tqdm_ray; use for Data progress bars
  python/ray/_private/worker.py
  python/ray/data/_internal/progress_bar.py
  python/ray/data/context.py
  python/ray/experimental/tqdm_ray.py
  python/ray/tests/BUILD
  python/ray/tests/test_tqdm.py
Labels: tests-ok

#33257 [Datasets] Refactor iter_rows() for DatasetIterator classes
  python/ray/data/_internal/dataset_iterator_impl.py
  python/ray/data/_internal/pipelined_dataset_iterator.py
  python/ray/data/_internal/stream_split_dataset_iterator.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset_iterator.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok

#33267 [Datasets] Fix failing Documentation tests related to updated `ExecutionPlan.__repr__`
  doc/source/data/getting-started.rst
  python/ray/data/dataset.py
  python/ray/data/dataset_iterator.py
Labels: tests-ok

#33212 [Datasets] Run `_get_read_tasks` with NodeAffinitySchedulingStrategy
  python/ray/data/_internal/remote_fn.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_formats.py
Labels: tests-ok

#33209 [ci/release] Do not terminate cluster on keyboard interrupt with --no-terminate
  release/ray_release/glue.py
Labels: @author-action-required

#33174 [Tune][wandb] Wait for `WandbLoggerCallback` actors to finish uploading to wandb on experiment end
  python/ray/air/integrations/wandb.py
  python/ray/air/tests/mocked_wandb_integration.py
  python/ray/air/tests/test_integration_wandb.py
  python/ray/train/tests/test_e2e_wandb_integration.py
Labels: tests-ok

#33294 fix: pin libffi=3.3 for base-deps
  docker/base-deps/Dockerfile
Labels: do-not-merge, v2.3.1-pick

#33161 [AIR] <Part 1> Add LightningTrainer to support Pytorch Lightning DDP training.
  doc/source/_toc.yml
  doc/source/ray-air/trainers.rst
  doc/source/ray-air/user-guides.rst
  doc/source/train/api/api.rst
  python/ray/train/BUILD
  python/ray/train/lightning/__init__.py
  python/ray/train/lightning/_lightning_utils.py
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/tests/lightning_test_utils.py
  python/ray/train/tests/test_lightning_trainer.py
Labels: train, air

#33067 [Datasets] Remove "Example: Large-scale ML Ingest"
  doc/BUILD
  doc/source/_toc.yml
  doc/source/data/big_data_ingestion.yaml
  doc/source/data/dataset.rst
  doc/source/data/examples/BUILD
  doc/source/data/examples/big_data_ingestion.ipynb
  doc/source/data/examples/index.rst
Labels: tests-ok

#32857 [Datasets] Add optional `tf_schema` parameter to `read_tfrecords` / `write_tfrecords` methods
  python/ray/data/dataset.py
  python/ray/data/datasource/tfrecords_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_tfrecords.py
Labels: tests-ok

#33338 [Conda][dependency] pin libffi=3.3 for base-deps (#33294)
  docker/base-deps/Dockerfile
Labels: v2.3.1-pick

#33222 [Datasets] Add benchmark for many file parquet reads
  release/nightly_tests/dataset/parquet_data_generator.py
  release/nightly_tests/dataset/read_parquet_benchmark.py
  release/release_tests.yaml
Labels: tests-ok

#33332 [Datasets] Force all operator/stage name to be in PascalCase
  python/ray/air/tests/test_dataset_config.py
  python/ray/data/_internal/lazy_block_list.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/stage_impl.py
  python/ray/data/_internal/stats.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_dataset_formats.py
  python/ray/data/tests/test_dataset_numpy.py
  python/ray/data/tests/test_dataset_pandas.py
  python/ray/data/tests/test_optimize.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_stats.py
Labels: tests-ok

#33126 [Data] Add support for `ignore_missing_paths`
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_binary.py
  python/ray/data/tests/test_dataset_csv.py
  python/ray/data/tests/test_dataset_image.py
  python/ray/data/tests/test_dataset_json.py
  python/ray/data/tests/test_dataset_numpy.py
  python/ray/data/tests/test_dataset_text.py
  python/ray/data/tests/test_dataset_tfrecords.py
  python/ray/data/tests/test_metadata_provider.py
Labels: @author-action-required

#31175 [core] Fix demand leak when worker failed
  python/ray/tests/kuberay/test_autoscaling_e2e.py
  python/ray/tests/test_advanced_9.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
Labels: @author-action-required

#33303 [data] [streaming] Support iterating over streaming_split() iterators multiple times
  doc/source/ray-observability/ray-logging.rst
  python/ray/data/_internal/dataset_iterator_impl.py
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/progress_bar.py
  python/ray/data/_internal/stream_split_dataset_iterator.py
  python/ray/data/tests/test_streaming_integration.py
  python/ray/experimental/tqdm_ray.py
  python/ray/tune/progress_reporter.py
Labels: tests-ok

#33302 [Datasets] Add sub progress bar support for AllToAllOperator
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/all_to_all_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/_internal/fast_repartition.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/push_based_shuffle.py
  python/ray/data/_internal/shuffle.py
  python/ray/data/_internal/sort.py
  python/ray/data/_internal/stage_impl.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_streaming_executor.py
  release/nightly_tests/dataset/test.py
Labels: tests-ok

#33337 [Dashboard] Add button to download logs to file
  dashboard/client/src/pages/log/Logs.tsx
  dashboard/client/src/service/log.ts
Labels: @author-action-required

#33370 [tune] Cleanup path-related properties in experiment classes
  python/ray/_private/test_utils.py
  python/ray/air/integrations/mlflow.py
  python/ray/air/integrations/wandb.py
  python/ray/air/tests/mocked_wandb_integration.py
  python/ray/air/tests/test_integration_mlflow.py
  python/ray/air/tests/test_integration_wandb.py
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/callback.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/config_parser.py
  python/ray/tune/experiment/experiment.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/logger/aim.py
  python/ray/tune/logger/csv.py
  python/ray/tune/logger/json.py
  python/ray/tune/logger/logger.py
  python/ray/tune/logger/tensorboardx.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/result.py
  python/ray/tune/result_grid.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_actor_reuse.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_integration_pytorch_lightning.py
  python/ray/tune/tests/test_logger.py
  python/ray/tune/tests/test_progress_reporter.py
  python/ray/tune/tests/test_result_grid.py
  python/ray/tune/tests/test_run_experiment.py
  python/ray/tune/tests/test_syncer_callback.py
  python/ray/tune/tests/test_trial_relative_logdir.py
  python/ray/tune/tests/test_trial_runner.py
  python/ray/tune/tests/test_trial_runner_2.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_tune_save_restore.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/trainable/util.py
  python/ray/tune/tune.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
Labels: tests-ok

#33281 [Core] Python worker startup benchmark
  release/benchmark-worker-startup/app_config_gpu.yaml
  release/benchmark-worker-startup/benchmark_worker_startup.py
  release/benchmark-worker-startup/only_head_node_1gpu_64cpu.yaml
  release/benchmark-worker-startup/test_single_configuration.py
  release/release_tests.yaml
Labels: core

#33321 [core][state] Task backend - Profile events capping
  src/ray/common/ray_config_def.h
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/task_event_buffer_test.cc
Labels: tests-ok

#32936 [Doc|Train] Add Pytorch ResNet finetuning starter example
  doc/BUILD
  doc/source/_toc.yml
  doc/source/train/examples/pytorch/BUILD
  doc/source/train/examples/pytorch/pytorch_resnet_finetune.ipynb
Labels: train

#32493 Enable streaming executor by default
  python/ray/data/context.py
Labels: tests-ok

#33448 [tune] Refactor TrialRunner to separate out executor calls
  python/ray/air/execution/_internal/actor_manager.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/trial.py
Labels: tests-ok

#33183 [AIR] <Part 2> Support metric logging and checkpointing for LightningTrainer
  doc/source/train/api/api.rst
  python/ray/train/BUILD
  python/ray/train/lightning/__init__.py
  python/ray/train/lightning/_lightning_utils.py
  python/ray/train/lightning/lightning_checkpoint.py
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/tests/lightning_test_utils.py
  python/ray/train/tests/test_lightning_checkpoint.py
  python/ray/train/tests/test_lightning_trainer.py
  python/ray/train/tests/test_lightning_trainer_restore.py
Labels: train, air

#33454 [Tune] Log the choice of `RunConfig` only when passed into both trainer + tuner
  python/ray/train/tests/test_tune.py
  python/ray/tune/impl/tuner_internal.py
Labels: tests-ok

#33390 [Tune] Use `on_experiment_end` hook for the final wait of `SyncCallback` sync processes
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_syncer_callback.py
  python/ray/tune/tune.py
Labels: tests-ok

#33386 [Datasets] [Docs] Remove "Datasource Compatibility" from Ray Data landing page
  doc/source/data/dataset.rst
  doc/source/ray-overview/use-cases.rst
Labels: tests-ok

#33277 [air telemetry] add air trainer type
  python/ray/air/_internal/usage.py
  python/ray/train/base_trainer.py
  src/ray/protobuf/usage.proto
Labels: tests-ok

#33422 [Datasets] Lazy import `tensorflow-metadata` when reading/writing TFRecords
  python/ray/data/datasource/tfrecords_datasource.py
Labels: tests-ok

#33455 [Metrics] Hide failed nodes by default.
  dashboard/modules/metrics/grafana_dashboard_factory.py
Labels: @author-action-required

#33328 [Metrics] Add device index to the GPU metrics
  dashboard/modules/metrics/grafana_dashboard_factory.py
  dashboard/modules/reporter/reporter_agent.py
  dashboard/modules/reporter/tests/test_reporter.py
  doc/source/ray-observability/ray-metrics.rst
Labels: @author-action-required

#33538 [RLlib] Make Alan and Praveen codeowners for build-docker-images.py
  .github/CODEOWNERS
Labels: tests-ok

#33145 [doc][tune] Add tune checkpoint user guide.
  doc/source/_toc.yml
  doc/source/tune/api/schedulers.rst
  doc/source/tune/api/trainable.rst
  doc/source/tune/doc_code/trainable.py
  doc/source/tune/doc_code/trial_checkpoint.py
  doc/source/tune/key-concepts.rst
  doc/source/tune/tutorials/tune-distributed.rst
  doc/source/tune/tutorials/tune-storage.rst
  doc/source/tune/tutorials/tune-trial-checkpoint.rst
  python/ray/tune/schedulers/resource_changing_scheduler.py
Labels: tests-ok

#33313 [Datasets] [Docs] Add section on reading compressed files with Ray Data
  doc/source/data/creating-datasets.rst
  doc/source/data/doc_code/creating_datasets.py
Labels: tests-ok

#33437 [Data] Deprecate `dataset_format`
  python/ray/data/_internal/fast_repartition.py
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/preprocessor.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/preprocessors/chain.py
  python/ray/data/preprocessors/torch.py
  python/ray/data/random_access_dataset.py
  python/ray/data/tests/preprocessors/test_chain.py
  python/ray/data/tests/preprocessors/test_preprocessors.py
  python/ray/data/tests/test_dataset_all_to_all.py
  python/ray/data/tests/test_dataset_map.py
  python/ray/data/tests/test_dataset_pandas.py
  python/ray/data/tests/test_random_access.py
  python/ray/train/batch_predictor.py
  python/ray/train/predictor.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_predictor.py
  release/nightly_tests/dataset/iter_batches_benchmark.py
  release/nightly_tests/dataset/iter_tensor_batches_benchmark.py
Labels: tests-ok

#33575 [Data] [1/n] Async `iter_batches`: Add Threadpool util
  python/ray/data/BUILD
  python/ray/data/_internal/block_batching/__init__.py
  python/ray/data/_internal/block_batching/block_batching.py
  python/ray/data/_internal/block_batching/util.py
  python/ray/data/tests/block_batching/test_block_batching.py
  python/ray/data/tests/block_batching/test_util.py
Labels: @author-action-required

#33532 [docker][ci] Downgrade `xgboost` version
  python/requirements/ml/requirements_tune.txt
Labels: tests-ok

#33555 [core][dashboard] Add repr_name as part of actor state
  dashboard/client/src/components/ActorTable.tsx
  dashboard/client/src/pages/actor/ActorDetail.tsx
  dashboard/client/src/type/actor.ts
  dashboard/modules/actor/actor_head.py
  dashboard/modules/actor/tests/test_actor.py
  dashboard/state_aggregator.py
  python/ray/_raylet.pyx
  python/ray/experimental/state/common.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_state_api_2.py
  python/ray/tests/test_state_api_summary.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/gcs.proto
Labels: @author-action-required

#33495 [Doc][Tune][Restore] Split "Tune stopping and resuming" into two user guides
  doc/source/_toc.yml
  doc/source/tune/doc_code/faq.py
  doc/source/tune/doc_code/fault_tolerance.py
  doc/source/tune/doc_code/stopping.py
  doc/source/tune/faq.rst
  doc/source/tune/tutorials/overview.rst
  doc/source/tune/tutorials/tune-fault-tolerance.rst
  doc/source/tune/tutorials/tune-stopping.rst
  doc/source/tune/tutorials/tune-trial-checkpoints.rst
Labels: tests-ok

#33601 Revert "[Datasets] Revert "Enable streaming executor by default (#324…
  python/ray/air/tests/test_dataset_config.py
  python/ray/data/context.py
  python/ray/data/dataset.py
Labels: @author-action-required

#33649 [Datasets] Fix zip stage to preserve order when executing the other side
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/stage_impl.py
  python/ray/data/tests/test_dataset_all_to_all.py
Labels: tests-ok

#33654 Fix CI for streaming executor regarding order preservation
  doc/source/data/glossary.rst
Labels: tests-ok

#33599 [Dashboard] Fix newIA not respecting the "DISABLED" flag for Grafana
  dashboard/client/src/App.tsx
  dashboard/client/src/pages/layout/MainNavLayout.tsx
  dashboard/client/src/pages/metrics/Metrics.component.test.tsx
  dashboard/client/src/pages/metrics/Metrics.tsx
  dashboard/client/src/pages/overview/OverviewPage.component.test.tsx
  dashboard/client/src/pages/overview/cards/ClusterUtilizationCard.tsx
  dashboard/client/src/pages/overview/cards/NodeCountCard.tsx
  dashboard/client/src/util/test-utils.tsx
Labels: @author-action-required

#33616 [deflakey] Try to deflakey gcs_client_test
  src/ray/gcs/gcs_server/gcs_server.cc
Labels: @author-action-required

#29622 [Core] Turn on Python test linting for Core tests.
  ci/ci.sh
  doc/BUILD
  doc/source/data/creating-datasets.rst
  doc/source/data/dask-on-ray.rst
  doc/source/data/doc_code/creating_datasets.py
  doc/source/data/doc_code/creating_datasets_untested.py
  doc/source/data/doc_code/dask_on_ray_annotate_example.py
  doc/source/data/doc_code/dask_on_ray_callbacks.py
  doc/source/data/doc_code/dask_on_ray_persist_example.py
  doc/source/data/doc_code/dask_on_ray_scheduler_example.py
  doc/source/data/doc_code/dask_on_ray_shuffle_optimization.py
  doc/source/data/doc_code/key_concepts.py
  doc/source/data/doc_code/saving_datasets.py
  doc/source/data/doc_code/transforming_datasets.py
  doc/source/ray-overview/doc_test/ray_data.py
  python/ray/tests/BUILD
  python/ray/tests/test_memory_deadlock.py
  python/ray/util/dask/BUILD
  python/ray/util/dask/examples/__init__.py
Labels: @author-action-required

#33684 [Datasets] Do not skip duplicated path in DefaultFileMetadataProvider
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/tests/test_metadata_provider.py
Labels: tests-ok

#33561 [tune-telemetry] Tag searcher and scheduler types.
  python/ray/air/_internal/usage.py
  python/ray/train/base_trainer.py
  python/ray/tune/schedulers/async_hyperband.py
  python/ray/tune/schedulers/hyperband.py
  python/ray/tune/schedulers/median_stopping_rule.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/schedulers/trial_scheduler.py
  python/ray/tune/search/basic_variant.py
  python/ray/tune/search/searcher.py
  src/ray/protobuf/usage.proto
Labels: tests-ok

#33663 [RLlib][RLModule][build_base] Disabled Centralized Critic and Curiosity tests with RLModules
  rllib/examples/centralized_critic.py
  rllib/examples/centralized_critic_2.py
  rllib/utils/exploration/tests/test_curiosity.py
Labels: do-not-merge

#33662 [RLlib][RLModule][build_base] Disabling RLModule API for LSTM / Attn
  rllib/examples/attention_net.py
  rllib/examples/cartpole_lstm.py
  rllib/examples/custom_rnn_model.py
  rllib/examples/inference_and_serving/policy_inference_after_training_with_attention.py
  rllib/examples/inference_and_serving/policy_inference_after_training_with_lstm.py
  rllib/tuned_examples/ppo/repeatafterme-ppo-lstm.yaml
Labels: tests-ok

#33687 [Datasets] Delete unused code in release test
  release/nightly_tests/dataset/test.py
Labels: tests-ok

#33605 [Data] [2/3] Async iter_batches: Add interfaces and helper functions
  python/ray/data/_internal/block_batching/block_batching.py
  python/ray/data/_internal/block_batching/interfaces.py
  python/ray/data/_internal/block_batching/iter_batches.py
  python/ray/data/_internal/block_batching/util.py
  python/ray/data/_internal/memory_tracing.py
  python/ray/data/tests/block_batching/test_block_batching.py
  python/ray/data/tests/block_batching/test_iter_batches.py
  python/ray/data/tests/block_batching/test_util.py
Labels: tests-ok

#33676 [Datasets] Streaming executor fixes
  python/ray/data/dataset.py
  python/ray/tune/tests/test_trial_runner_3.py
Labels: @author-action-required

#33626 [core] Task backend - surface task execution error details
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  python/ray/_private/ray_constants.py
  python/ray/_private/state_api_test_utils.py
  python/ray/_raylet.pyx
  python/ray/experimental/state/common.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_exit_observability.py
  python/ray/tests/test_failure_4.py
  python/ray/tests/test_memory_pressure.py
  python/ray/tests/test_task_events.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/gcs.proto
Labels: tests-ok

#33712 [Data] Optimize metadata creation for `RangeDatasource`
  python/ray/data/datasource/datasource.py
  python/ray/data/tests/test_dataset_tensor.py
Labels: @author-action-required

#33665 [Java] Prepend ":job_id:<jobid>" to java-worker-<jobid>-<pid>.log to make Java logging consistent with Python
  java/runtime/src/main/java/io/ray/runtime/util/LoggingUtil.java
Labels: tests-ok

#32747 [Datasets] [Operator Fusion - 3/N] Add operator fusion benchmark.
  release/nightly_tests/dataset/operator_fusion_benchmark.py
Labels: @author-action-required

#33144 [Docs] Fix link errors (#33086)
  doc/source/ray-overview/index.md
  doc/source/tune/examples/tune-xgboost.ipynb
Labels: v2.3.1-pick

#33146 [Doc] [Serve] Add workaround to Serve docs for broken dependency (#33136)
  doc/source/serve/tutorials/batch.md
  doc/source/serve/tutorials/serve-ml-models.md
Labels: v2.3.1-pick

#33734 [Core] Deprecate RuntimeContext.get
  python/ray/runtime_context.py
Labels: core-interface-change-approval-required

#33713 [data] [streaming] Dataset.cache() doesn't work properly for streaming executor
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_dataset_consumption.py
  python/ray/data/tests/test_dataset_parquet.py
  python/ray/data/tests/test_stats.py
Labels: tests-ok

#33478 [Data] Repurpose streaming CI to bulk CI
  .buildkite/pipeline.ml.yml
Labels: @author-action-required

#33620 [data] [3/3] [no_early_kickoff] Async iter batches e2e
  doc/source/ray-air/doc_code/air_ingest.py
  python/ray/air/util/check_ingest.py
  python/ray/data/_internal/block_batching/block_batching.py
  python/ray/data/_internal/block_batching/iter_batches.py
  python/ray/data/_internal/block_batching/util.py
  python/ray/data/_internal/dataset_iterator/__init__.py
  python/ray/data/_internal/dataset_iterator/dataset_iterator_impl.py
  python/ray/data/_internal/dataset_iterator/pipelined_dataset_iterator.py
  python/ray/data/_internal/dataset_iterator/stream_split_dataset_iterator.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/planner/map_batches.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/stats.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/dataset_iterator.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/block_batching/test_block_batching.py
  python/ray/data/tests/block_batching/test_iter_batches.py
  python/ray/data/tests/block_batching/test_util.py
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_dataset_consumption.py
  python/ray/data/tests/test_stats.py
  python/ray/train/batch_predictor.py
  release/air_tests/air_benchmarks/workloads/data_benchmark.py
  release/nightly_tests/dataset/data_ingest_benchmark.py
  release/nightly_tests/dataset/iter_tensor_batches_benchmark.py
  release/nightly_tests/dataset/multi_node_benchmark_compute.yaml
  release/release_tests.yaml
Labels: @author-action-required

#33711 [data] [streaming] Fix a few backpressure issues with streaming
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/_internal/execution/util.py
  python/ray/data/_internal/simple_block.py
  python/ray/data/tests/test_actor_pool_map_operator.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_streaming_executor.py
Labels: tests-ok

#33403 [core] Deduplicate repetitive logs across the cluster
  doc/source/ray-observability/ray-logging.rst
  python/ray/_private/ray_constants.py
  python/ray/_private/ray_logging.py
  python/ray/_private/worker.py
  python/ray/tests/BUILD
  python/ray/tests/test_log_dedup.py
  python/ray/tests/test_logging.py
  python/ray/tests/test_multi_node.py
  python/ray/tests/test_output.py
Labels: @author-action-required

#33780 [Datasets] Allow read_binary_files(output_arrow_format=True) to return Arrow format
  python/ray/data/datasource/binary_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_binary.py
Labels: tests-ok

#33572 [Core] Experimental preload_python_modules flag for preloading modules in default_worker
  BUILD.bazel
  python/ray/_private/utils.py
  python/ray/_private/workers/default_worker.py
  python/ray/tests/test_basic_5.py
  python/ray/tests/test_utils.py
  src/ray/common/ray_config.h
  src/ray/common/ray_config_def.h
  src/ray/common/test/ray_config_test.cc
  src/ray/raylet/worker_pool.cc
Labels: tests-ok, core

#33791 [Datasets] Add meta_provider parameter into read_images
  python/ray/data/datasource/image_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_image.py
Labels: tests-ok

#33595 [Doc] Revamp ray core design patterns doc [19/n]: async actor
  doc/source/ray-core/actors.rst
  doc/source/ray-core/actors/patterns/concurrent-operations-async-actor.rst
  doc/source/ray-core/actors/patterns/index.rst
  doc/source/ray-core/doc_code/pattern_async_actor.py
  doc/source/ray-core/patterns/concurrent-operations-async-actor.rst
  doc/source/ray-core/patterns/index.rst
Labels: @author-action-required

#33610 [no_early_kickoff] [Train] Recommend `Trainer.restore` on errors raised by `trainer.fit()`
  python/ray/air/BUILD
  python/ray/air/tests/test_errors.py
  python/ray/train/base_trainer.py
  python/ray/train/tests/test_base_trainer.py
  python/ray/train/tests/test_gpu.py
  python/ray/train/tests/test_huggingface_trainer.py
  python/ray/train/tests/test_huggingface_trainer_steps.py
  python/ray/train/tests/test_lightning_trainer_restore.py
  python/ray/train/tests/test_mosaic_trainer.py
  python/ray/train/tests/test_torch_trainer.py
  python/ray/train/tests/test_trainer_restore.py
  python/ray/tune/tests/test_tuner.py
Labels: tests-ok

#33642 [Tune] Don't recommend `tune.run` API in logging messages when using the `Tuner`
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tune.py
Labels: tests-ok

#33794 [Datasets] Remove join as potential improvements in doc
  doc/source/data/dataset.rst
Labels: tests-ok

#33782 [no_early_kickoff][tune] Hard deprecate Tune MLflow/W&B mixin/callbacks
  python/ray/air/tests/test_integration_mlflow.py
  python/ray/air/tests/test_integration_wandb.py
  python/ray/tune/integration/mlflow.py
  python/ray/tune/integration/wandb.py
  python/ray/tune/tests/test_actor_reuse.py
Labels: tests-ok

#33784 [no_early_kickoff][train] Hard deprecate Backend encode_data/decode_data
  python/ray/train/backend.py
Labels: tests-ok

#33814 [RLlib] Fix apex dqn deprecated add_batch call
  rllib/algorithms/apex_dqn/apex_dqn.py
Labels: release-blocker, Ray 2.4

#33863 [RLlib] Fix MultiCallbacks class: To be used only with utility function that returns a class to use in the config.
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/callbacks.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/algorithms/tests/test_callbacks.py
Labels: tests-ok

#33829 [data] Fix use of deprecated API in new batching code path
  python/ray/data/_internal/block_batching/util.py
Labels: release-blocker, Ray 2.4

#33875 [core][release] 2.4.0 release logs (copied over from 2.3.0)
  release/release_logs/2.4.0/benchmarks/many_actors.json
  release/release_logs/2.4.0/benchmarks/many_nodes.json
  release/release_logs/2.4.0/benchmarks/many_pgs.json
  release/release_logs/2.4.0/benchmarks/many_tasks.json
  release/release_logs/2.4.0/microbenchmark.json
  release/release_logs/2.4.0/scalability/object_store.json
  release/release_logs/2.4.0/scalability/single_node.json
  release/release_logs/2.4.0/stress_tests/stress_test_dead_actors.json
  release/release_logs/2.4.0/stress_tests/stress_test_many_tasks.json
  release/release_logs/2.4.0/stress_tests/stress_test_placement_group.json
Labels: release-blocker, P0, Ray 2.4

#33774 [cluster launcher] Deflake AWS cluster launcher test by adding retries
  python/ray/autoscaler/aws/tests/aws_launch_and_verify_cluster.py
  python/ray/autoscaler/aws/tests/download_ssh_key.py
  python/ray/autoscaler/aws/tests/test_aws_cluster_launcher.sh
  release/release_tests.yaml
Labels: tests-ok

#33812 Deprecate ds.lazy() since Dataset is lazy already
  python/ray/data/dataset.py
Labels: tests-ok

#33885 [CI] Disable Ray log deduplication for doctests
  ci/ci.sh
Labels: tests-ok

#33856 [core] node affinity soft chooses another node if it is not available
  doc/source/ray-core/scheduling/index.rst
  python/ray/tests/test_scheduling_2.py
  python/ray/util/scheduling_strategies.py
  src/ray/raylet/scheduling/policy/node_affinity_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
Labels: tests-ok, release-blocker, Ray 2.4

#33366 [Windows] Fix py-spy command for dashboard
  dashboard/modules/reporter/profile_manager.py
Labels: @author-action-required

#33879 [docs] Improve log dedup doc by printing the doc link
  python/ray/_private/ray_logging.py
  python/ray/tests/test_log_dedup.py
Labels: Ray 2.4

#33775 [no_early_kickoff] [AIR] Make Keras `Callback` raise `DeprecationWarning`
  doc/source/ray-air/doc_code/tf_starter.py
  doc/source/ray-air/examples/convert_existing_tf_code_to_ray_air.ipynb
  doc/source/ray-air/examples/tf_tabular_starter.py
  python/ray/air/integrations/keras.py
  python/ray/air/tests/test_keras_callback.py
  python/ray/tests/ml_py36_compat/tune_hvd_keras.py
  python/ray/train/examples/tf/tensorflow_autoencoder_example.py
  python/ray/train/examples/tf/tensorflow_mnist_example.py
  python/ray/train/examples/tf/tensorflow_regression_example.py
  release/air_tests/air_benchmarks/workloads/tensorflow_benchmark.py
Labels: tests-ok

#33834 [core] Fix non default dashboard_agent_listen_port not used when connected to the node
  dashboard/modules/job/tests/test_job_agent.py
  python/ray/_private/node.py
  python/ray/_private/ray_constants.py
  python/ray/_private/services.py
  python/ray/_private/test_utils.py
  python/ray/tests/test_ray_init_2.py
Labels: tests-ok

#33767 [air output] Add unit test to `experimental/output.py`
  python/ray/tune/BUILD
  python/ray/tune/experimental/output.py
  python/ray/tune/tests/output/__init__.py
  python/ray/tune/tests/output/conftest.py
  python/ray/tune/tests/output/test_output.py
Labels: tests-ok
