Repository ray-project/ray, pull requests merged in 2023-11, with the labels that each got.

#40848 [core] Fix autoscaler v2 for GCS FT
  python/ray/tests/test_gcs_fault_tolerance.py
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
Labels: v2.8.0-pick

#40843 [docs] [data] fixing some hyperlinks
  doc/source/data/transforming-data.rst
Labels: docs, data

#40504 [docs] [core] link to file in repo with list of accelerator types
  doc/source/ray-core/accelerator-types.rst
  python/ray/_private/worker.py
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/serve/schema.py
Labels: docs, core

#40876 [docs] Fix broken Spotify link
  doc/source/ray-air/getting-started.rst
Labels: docs

#40199 [Data] Add `Datasink`
  doc/source/data/api/input_output.rst
  python/ray/data/__init__.py
  python/ray/data/_internal/logical/operators/write_operator.py
  python/ray/data/_internal/logical/util.py
  python/ray/data/_internal/planner/plan_write_op.py
  python/ray/data/dataset.py
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/datasink.py
  python/ray/data/datasource/datasource.py
Labels: tests-ok

#40903 Add request context to serve java
  java/serve/src/main/java/io/ray/serve/context/ContextUtil.java
  java/serve/src/main/java/io/ray/serve/context/RequestContext.java
  java/serve/src/main/java/io/ray/serve/handle/DeploymentHandle.java
  java/serve/src/main/java/io/ray/serve/replica/RayServeReplicaImpl.java
  java/serve/src/main/java/io/ray/serve/router/ReplicaSet.java
  java/serve/src/main/java/io/ray/serve/router/Router.java
  java/serve/src/test/java/io/ray/serve/context/RequestContextTest.java
  java/serve/src/test/java/io/ray/serve/router/RouterTest.java
  python/ray/serve/_private/replica.py
  src/ray/protobuf/serve.proto
Labels: serve

#40918 [kuberay][autoscaler] Update KubeRay version to v1.0.0
  python/ray/autoscaler/kuberay/init-config.sh
  python/ray/tests/kuberay/test_autoscaling_e2e.py
  python/ray/tests/kuberay/test_files/ray-cluster.autoscaler-template.yaml
  release/k8s_tests/run_gcs_ft_on_k8s.py
Labels: tests-ok

#40029 [docs] Make it clear to "fork" Ray repo
  doc/source/ray-contribute/development.rst
  doc/source/ray-contribute/docs.ipynb
Labels: docs

#40894 create nodes by best effort policy
  python/ray/autoscaler/_private/vsphere/gpu_utils.py
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/tests/vsphere/test_vsphere_node_provider.py
Labels: tests-ok

#40884 [vSphere Provider] Make sdk clients singleton, and add auto connection recovery
  python/ray/autoscaler/_private/vsphere/gpu_utils.py
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/autoscaler/_private/vsphere/pyvmomi_sdk_provider.py
  python/ray/autoscaler/_private/vsphere/sdk_provider.py
  python/ray/autoscaler/_private/vsphere/utils.py
  python/ray/autoscaler/_private/vsphere/vsphere_sdk_provider.py
  python/ray/tests/vsphere/test_vsphere_node_provider.py
Labels: tests-ok

#40930 [RLlib] Fix failing RLlib test case: `rllib/evaluation/tests/test_envs_that_crash.py`.
  rllib/evaluation/tests/test_envs_that_crash.py
Labels: tests-ok

#39374 typo environement
  doc/source/rllib/rllib-offline.rst
Labels: stale

#41043 [vSphere provider] Refactor and optimize the code
  python/ray/autoscaler/_private/vsphere/config.py
  python/ray/autoscaler/_private/vsphere/gpu_utils.py
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/autoscaler/_private/vsphere/round_robin_scheduler.py
  python/ray/autoscaler/_private/vsphere/scheduler.py
  python/ray/tests/vsphere/test_vsphere_node_provider.py
Labels: tests-ok

#41051 [docs] [observability] fix broken link in doc string
  python/ray/util/state/api.py
Labels: P1, docs, observability-ux

#40798 [core][dashboard][retry] Task backend GC policy - GCS refactor [2/3]
  dashboard/state_aggregator.py
  python/ray/_private/state_api_test_utils.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_task_events_2.py
  python/ray/util/state/api.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/task_spec.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/profile_event.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs_service.proto
Labels: @author-action-required

#41200 [Doc] Fix algolia autocomplete overlap
  doc/source/_static/css/custom.css
Labels: P1, docs

#41100 [Doc] Update KubeRay version to 1.0.0 (#40937)
  doc/source/cluster/kubernetes/examples/gpu-training-example.md
  doc/source/cluster/kubernetes/examples/mobilenet-rayservice.md
  doc/source/cluster/kubernetes/examples/rayjob-batch-inference-example.md
  doc/source/cluster/kubernetes/examples/stable-diffusion-rayservice.md
  doc/source/cluster/kubernetes/examples/text-summarizer-rayservice.md
  doc/source/cluster/kubernetes/getting-started/raycluster-quick-start.md
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
  doc/source/cluster/kubernetes/getting-started/rayservice-quick-start.md
  doc/source/cluster/kubernetes/k8s-ecosystem/ingress.md
  doc/source/cluster/kubernetes/k8s-ecosystem/kubeflow.md
  doc/source/cluster/kubernetes/k8s-ecosystem/prometheus-grafana.md
  doc/source/cluster/kubernetes/k8s-ecosystem/pyspy.md
  doc/source/cluster/kubernetes/k8s-ecosystem/volcano.md
  doc/source/cluster/kubernetes/troubleshooting/rayservice-troubleshooting.md
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.md
  doc/source/cluster/kubernetes/user-guides/gke-gcs-bucket.md
  doc/source/cluster/kubernetes/user-guides/helm-chart-rbac.md
  doc/source/cluster/kubernetes/user-guides/kuberay-gcs-ft.md
  doc/source/cluster/kubernetes/user-guides/pod-command.md
  doc/source/cluster/kubernetes/user-guides/rayserve-dev-doc.md
  doc/source/cluster/kubernetes/user-guides/rayservice.md
  doc/source/cluster/kubernetes/user-guides/tls.md
  doc/source/cluster/kubernetes/user-guides/upgrade-guide.md
  doc/source/serve/production-guide/kubernetes.md
Labels: v2.8.0-pick

#41233 [vSphere Provider] Optimize the doc about frozen VM expressions
  doc/source/cluster/vms/user-guides/launching-clusters/vsphere.md
Labels: @external-author-action-required

#40951 [serve] Enrich serve status API
  dashboard/modules/serve/tests/test_serve_dashboard.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_common.py
  python/ray/serve/tests/unit/test_deployment_state.py
  src/ray/protobuf/serve.proto
Labels: release-blocker

#41201 [Serve] Scale `initial_replicas` by `target_capacity` during rollouts
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_controller.py
Labels: release-blocker

#41244 Make Ray releases tests use `pydantic>=2.5.0`
  ci/lint/format.sh
  dashboard/modules/job/tests/backwards_compatibility_scripts/test_backwards_compatibility.sh
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
  doc/source/train/examples/deepspeed/gptj_deepspeed_fine_tuning.ipynb
  doc/source/train/examples/lightning/vicuna_13b_lightning_deepspeed_finetune.ipynb
  python/ray/tests/test_serialization.py
  release/air_examples/gptj_deepspeed_finetuning/gptj_deepspeed_env.yaml
  release/air_examples/vicuna_13b_lightning_deepspeed_finetuning/vicuna_13b_deepspeed_env.yaml
  release/ray_release/byod/requirements_byod_3.8.in
  release/ray_release/byod/requirements_byod_3.8.txt
  release/ray_release/byod/requirements_ml_byod_3.8.in
  release/ray_release/byod/requirements_ml_byod_3.8.txt
  release/ray_release/byod/requirements_ml_byod_3.9.in
  release/ray_release/byod/requirements_ml_byod_3.9.txt
  release/serve_tests/workloads/serve_resnet_benchmark.py
  release/setup.py
Labels: release-blocker

#41134 [CI] [Cluster] Fix example GCP GPU/docker example cluster YAML file
  python/ray/autoscaler/gcp/example-gpu-docker.yaml
  release/release_tests.yaml
Labels: tests-ok

#41287 [Serve] Fixed `_DeploymentHandleBase` to avoid regenerating `handle` tag every time `handle.options` is invoked
  python/ray/serve/handle.py
  python/ray/serve/tests/test_handle.py
Labels: release-blocker

#40581 [Metrics] Refactored metrics exporting to properly handle high-cardinality cases
  python/ray/_private/ray_constants.py
  src/ray/common/ray_config_def.h
  src/ray/rpc/grpc_client.h
  src/ray/rpc/metrics_agent_client.h
  src/ray/stats/metric_exporter.cc
  src/ray/stats/metric_exporter.h
  src/ray/stats/metric_exporter_grpc_test.cc
  src/ray/stats/stats.h
Labels: release-blocker

#40571 [release] 2.8 release perf logs
  release/release_logs/2.8.0/benchmarks/many_actors.json
  release/release_logs/2.8.0/benchmarks/many_nodes.json
  release/release_logs/2.8.0/benchmarks/many_tasks.json
  release/release_logs/2.8.0/microbenchmark.json
  release/release_logs/2.8.0/scalability/object_store.json
  release/release_logs/2.8.0/scalability/single_node.json
  release/release_logs/2.8.0/stress_tests/stress_test_dead_actors.json
  release/release_logs/2.8.0/stress_tests/stress_test_many_tasks.json
  release/release_logs/2.8.0/stress_tests/stress_test_placement_group.json
Labels: release-blocker, P0, core

#41348 [docs][tune] remove low value tune examples and references to them
  doc/source/_toc.yml
  doc/source/ray-overview/examples.rst
  doc/source/tune/examples/BUILD
  doc/source/tune/examples/dragonfly_example.ipynb
  doc/source/tune/examples/flaml_example.ipynb
  doc/source/tune/examples/hpo-frameworks.rst
  doc/source/tune/examples/includes/dragonfly_example.rst
  doc/source/tune/examples/includes/nevergrad_example.rst
  doc/source/tune/examples/includes/sigopt_example.rst
  doc/source/tune/examples/index.rst
  doc/source/tune/examples/ml-frameworks.rst
  doc/source/tune/examples/nevergrad_example.ipynb
  doc/source/tune/examples/sigopt_example.ipynb
  doc/source/tune/examples/tune-serve-integration-mnist.ipynb
  doc/source/tune/index.rst
  doc/source/tune/key-concepts.rst
  python/ray/tune/BUILD
  python/ray/tune/examples/README.rst
  python/ray/tune/examples/dragonfly_example.py
Labels: tune, docs

#41243 [serve] Remove Deployment Graph API [3/3]
  doc/source/serve/doc_code/model_composition/deployment_graph_viz.py
  python/ray/dag/utils.py
  python/ray/serve/_private/deployment_executor_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/deployment_method_executor_node.py
  python/ray/serve/_private/deployment_method_node.py
  python/ray/serve/_private/deployment_node.py
  python/ray/serve/deployment_graph.py
  python/ray/serve/drivers.py
  python/ray/serve/http_adapters.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/common/remote_uris.py
  python/ray/serve/tests/test_config_files/pid.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_deployment_graph_autoscaling.py
  python/ray/serve/tests/test_deployment_graph_config.py
  python/ray/serve/tests/test_deployment_graph_driver.py
  python/ray/serve/tests/test_deployment_graph_handle_serde.py
  python/ray/serve/tests/test_deployment_graph_ingress_deployment.py
  python/ray/serve/tests/test_http_adapters.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_model_composition.py
  python/ray/serve/tests/test_telemetry.py
Labels: release-blocker

#41327 [data] Enable streaming output backpressure
  python/ray/data/BUILD
  python/ray/data/_internal/execution/backpressure_policy.py
  python/ray/data/_internal/execution/backpressure_policy/__init__.py
  python/ray/data/_internal/execution/backpressure_policy/backpressure_policy.py
  python/ray/data/_internal/execution/backpressure_policy/concurrency_cap_backpressure_policy.py
  python/ray/data/_internal/execution/backpressure_policy/streaming_output_backpressure_policy.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_backpressure_policies.py
  python/ray/data/tests/test_streaming_executor.py
Labels: @author-action-required

#41452 [Doc] Fix busted AI assistant CSS
  doc/source/_static/css/assistant.css
  doc/source/_static/js/assistant.js
Labels: P0, docs
