Repository ray-project/ray, pull requests merged in 2023-12, with the labels that each got.

#41421 [core] Make number of connections and thread number of object manager client tunable.
  src/ray/common/ray_config_def.h
  src/ray/raylet/main.cc
  src/ray/rpc/object_manager/object_manager_client.h
Labels: @author-action-required

#41284 [cherry-pick][docs] Fix algolia autocomplete overlap (#41200)
  doc/source/_static/css/custom.css
Labels: v2.8.0-pick

#41436 [Core][2/3] Make streaming generator public API #38784
  doc/source/ray-core/doc_code/generator.py
  doc/source/ray-core/doc_code/streaming_generator.py
  doc/source/ray-core/ray-generator.rst
  doc/source/ray-core/tasks/generators.rst
  doc/source/serve/model_composition.md
  python/ray/__init__.py
  python/ray/_private/serialization.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/lazy_block_list.py
  python/ray/data/block.py
  python/ray/remote_function.py
  python/ray/serve/_private/router.py
  python/ray/serve/handle.py
  python/ray/serve/tests/unit/test_replica_scheduler.py
  python/ray/tests/test_actor.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_runtime_context.py
  python/ray/tests/test_streaming_generator.py
  python/ray/tests/test_streaming_generator_3.py
  python/ray/tests/test_streaming_generator_4.py
  python/ray/tests/test_streaming_generator_backpressure.py
  python/ray/tests/typing_files/check_typing_good.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_manager.h
  src/ray/protobuf/common.proto
Labels: @author-action-required

#41461 [Data] Introduce `concurrency` argument to replace ComputeStrategy in map-like APIs
  doc/source/data/examples/gptj_batch_prediction.ipynb
  doc/source/data/examples/stablediffusion_batch_prediction.ipynb
  doc/source/data/transforming-data.rst
  doc/source/data/working-with-images.rst
  doc/source/data/working-with-text.rst
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_actor_pool_map_operator.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_size_estimation.py
  python/ray/data/tests/util.py
Labels: @author-action-required, ray 2.9

#41317 [Serve] Incorporate `target_capacity` changes into Serve's statuses
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/autoscaling_policy.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deploy_utils.py
  python/ray/serve/_private/deployment_info.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_controller.py
  python/ray/serve/tests/unit/test_deployment_info.py
  python/ray/serve/tests/unit/test_deployment_state.py
  src/ray/protobuf/serve.proto
Labels: release-blocker, P0

#41569 [Data] Partial fix for Dataset.context not being sealed after creation
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_context_propagation.py
  python/ray/data/tests/test_streaming_integration.py
Labels: @author-action-required

#41592 [Serve] Make capacity direction `DOWN` when `target_capacity` changes from `None` to a number
  python/ray/serve/_private/controller.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/unit/test_controller.py
Labels: release-blocker, P0

#41481 Refactor: Add a cache in pyvmomi_sdk_provider
  python/ray/autoscaler/_private/vsphere/pyvmomi_sdk_provider.py
Labels: ray 2.10

#41617 [Serve] Make capacity direction `DOWN` when `target_capacity` changes from `None` to a number
  python/ray/serve/_private/controller.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/unit/test_controller.py
Labels: release-blocker, v2.9.0-pick

#41609 [Train/Tune] Skip incrementing failure counter on preemption node died failures
  python/ray/air/BUILD
  python/ray/air/config.py
  python/ray/air/tests/test_errors.py
  python/ray/train/constants.py
  python/ray/train/data_parallel_trainer.py
  python/ray/tune/error.py
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/tests/test_trial.py
  python/ray/tune/tests/test_tuner_restore.py
Labels: v2.9.0-pick

#41603 [data][train] default ingest resource limits should exclude resources used by training
  python/ray/air/tests/test_new_dataset_config.py
  python/ray/train/_internal/data_config.py
  python/ray/train/data_parallel_trainer.py
  release/release_tests.yaml
Labels: @author-action-required

#41666 Cherry-pick #41633
  python/ray/data/_internal/execution/operators/union_operator.py
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker, v2.9.0-pick

#41681 [core] Fix test log race on async actor task (#41563)
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_state_api_log.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
Labels: release-blocker, v2.9.0-pick

#41683 [data] deflake test_stats (#41655)
  ci/ray_ci/data.tests.yml
Labels: release-blocker, v2.9.0-pick

#41664 [core] Deflak test_metrics_agent (#41599)
  python/ray/tests/test_metrics_agent.py
Labels: release-blocker, v2.9.0-pick

#41665 [Data] Cherry-pick #41634
  python/ray/tests/test_client_compat.py
Labels: release-blocker, v2.9.0-pick

#41701 Pick of 41698
  release/release_tests.yaml
Labels: release-blocker, v2.9.0-pick

#41596 [docs] [train] Example Gallery Train examples to be the same as the ones on the Train Examples page
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/ray-core/examples/overview.rst
  doc/source/ray-core/examples/plot_example-lm.rst
  doc/source/ray-overview/examples.rst
  doc/source/tune/examples/ml-frameworks.rst
Labels: docs

#41637 [data] Improve stall detection for StreamingOutputsBackpressurePolicy
  python/ray/air/tests/test_new_dataset_config.py
  python/ray/data/_internal/execution/backpressure_policy/streaming_output_backpressure_policy.py
  python/ray/data/_internal/execution/interfaces/execution_options.py
  python/ray/data/_internal/execution/interfaces/executor.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/tests/test_backpressure_policies.py
  python/ray/data/tests/test_streaming_executor.py
  python/ray/train/_internal/data_config.py
Labels: @author-action-required

#41712 [Data] Avoid serializing datasource for Parquet read tasks
  python/ray/data/datasource/parquet_datasource.py
Labels: release-blocker, ray 2.9

#41697 [Cherrypick][Serve] Fix duplicated pymodules in the serve details (#41688)
  python/ray/serve/schema.py
  python/ray/serve/tests/unit/test_schema.py
Labels: release-blocker, v2.9.0-pick

#41725 [Cherry-pick][Data] Avoid serializing datasource for Parquet read tasks (#41712)
  python/ray/data/datasource/parquet_datasource.py
Labels: release-blocker, v2.9.0-pick

#41639 [2.9.0 Release] [Doc] Update Dask-on-Ray dependencies for 2.9.0 and 2.8.0
  doc/source/ray-more-libs/dask-on-ray.rst
Labels: release-blocker, v2.9.0-pick

#41744 [Serve] Patching ActorProxyWrapper to properly handle `is_drained` RPC
  python/ray/serve/_private/proxy_state.py
  python/ray/serve/tests/test_proxy_state.py
Labels: release-blocker, ray 2.9

#41751 [Cherry-pick][Serve] allow gRPC deployment to use grpc context (#41667)
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/proxy_request_response.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/router.py
  python/ray/serve/context.py
  python/ray/serve/grpc_util.py
  python/ray/serve/handle.py
  python/ray/serve/tests/common/utils.py
  python/ray/serve/tests/test_grpc.py
  python/ray/serve/tests/test_proxy.py
  python/ray/serve/tests/unit/test_grpc_util.py
  python/ray/serve/tests/unit/test_proxy_request_response.py
Labels: release-blocker, v2.9.0-pick

#41535 [Core] Fix core worker client pool leak
  BUILD.bazel
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/common/grpc_util.h
  src/ray/common/ray_config_def.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/rpc/grpc_client.h
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_client_pool.cc
  src/ray/rpc/worker/core_worker_client_pool.h
  src/ray/rpc/worker/test/core_worker_client_pool_test.cc
Labels: @author-action-required

#41605 [core] Add an internal system concurrency group for executing compiled dag tasks
  python/ray/tests/test_concurrency_group.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/transport/concurrency_group_manager.cc
  src/ray/core_worker/transport/concurrency_group_manager.h
Labels: @author-action-required

#41711 [serve] Cherry-pick replica log format change
  dashboard/modules/serve/tests/test_serve_dashboard.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/_private/replica.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_logging.py
Labels: release-blocker, v2.9.0-pick

#41755 [Serve] Patching ActorProxyWrapper to properly handle is_drained RPC
  python/ray/serve/_private/proxy_state.py
  python/ray/serve/tests/test_proxy_state.py
Labels: release-blocker, v2.9.0-pick

#41716 Container runtime env support (#40419)
  .buildkite/core.rayci.yml
  docker/runtime_env_container/Dockerfile
  python/ray/_private/runtime_env/container.py
  python/ray/_private/runtime_env/context.py
  python/ray/runtime_env/runtime_env.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/usage.py
  python/ray/tests/BUILD
  python/ray/tests/conftest_docker.py
  python/ray/tests/runtime_env_container/test_log_file_exists.py
  python/ray/tests/runtime_env_container/test_put_get.py
  python/ray/tests/runtime_env_container/test_ray_env_vars.py
  python/ray/tests/runtime_env_container/test_serve_basic.py
  python/ray/tests/runtime_env_container/test_serve_telemetry.py
  python/ray/tests/runtime_env_container/test_shared_memory.py
  python/ray/tests/runtime_env_container/test_worker_exit_intended_system_exit_and_user_error.py
  python/ray/tests/test_runtime_env_container.py
  src/ray/protobuf/usage.proto
Labels: release-blocker, v2.9.0-pick

#41763 [Core] Speed up single_client_tasks_sync (#41743)
  python/ray/_private/accelerators/__init__.py
  python/ray/tests/accelerators/test_intel_gpu.py
Labels: release-blocker, v2.9.0-pick

#41811 [Cherry-pick][Data] Fix unused `columns` parameter in `read_parquet_bulk` (#41806)
  python/ray/data/read_api.py
  python/ray/data/tests/test_parquet.py
Labels: release-blocker, v2.9.0-pick

#41821 [Cherry-pick][Data] Add example of how to read and write custom file types
  doc/source/data/api/input_output.rst
  doc/source/data/custom-datasource-example.rst
  doc/source/data/doc_code/custom_datasource_example.py
  doc/source/data/user-guide.rst
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/file_datasink.py
Labels: v2.9.0-pick

#41758 [docs][serve][tune] Remove serve/tutorial/rllib and tune-sklearn examples
  doc/README.md
  doc/source/ray-overview/examples.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/serve/index.md
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/rllib.md
  doc/source/tune/examples/ml-frameworks.rst
  doc/source/tune/examples/tune-sklearn.ipynb
  doc/source/tune/index.rst
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_myst_doc.py
  rllib/examples/inference_and_serving/serve_and_rllib.py
Labels: tune, serve, docs

#41815 [pick][data] Optimize OpState.outqueue_num_blocks
  python/ray/data/_internal/execution/streaming_executor_state.py
Labels: release-blocker, v2.9.0-pick

#41822 Remove unnecessary test file in wheel (#41775)
  dashboard/BUILD
  dashboard/modules/test/__init__.py
  dashboard/modules/tests/test_agent.py
  dashboard/modules/tests/test_consts.py
  dashboard/modules/tests/test_head.py
  dashboard/modules/tests/test_utils.py
  dashboard/tests/__init__.py
  dashboard/tests/conftest.py
Labels: release-blocker, ray 2.9, v2.9.0-pick

#41799 [serve] Fix bug in deployment state machine
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: release-blocker, P0

#41756 [cherry-pick][core] retryable exceptions for method (#41194)
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/native_task_submitter.cc
  doc/source/ray-core/fault_tolerance/actors.rst
  java/runtime/src/main/java/io/ray/runtime/task/NativeTaskSubmitter.java
  python/ray/_private/ray_option_utils.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/function_descriptor.pxi
  python/ray/includes/libcoreworker.pxd
  python/ray/serve/tests/test_proxy_state.py
  python/ray/tests/BUILD
  python/ray/tests/test_actor_retry.py
  python/ray/tests/test_chaos.py
  release/air_tests/air_benchmarks/workloads/xgboost_benchmark.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_util.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/actor_submit_queue.h
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.h
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.h
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.h
Labels: release-blocker, v2.9.0-pick

#41757 [Cherrypick][Serve] Update system_logging_config to logging_config (#41749)
  dashboard/modules/serve/serve_rest_api_impl.py
  python/ray/serve/_private/api.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/api.py
  python/ray/serve/tests/test_callback.py
  python/ray/serve/tests/test_controller_recovery.py
  python/ray/serve/tests/test_logging.py
Labels: release-blocker, P0, ray 2.9, v2.9.0-pick

#41783 [Serve] Add gRPC context related docs
  doc/source/serve/advanced-guides/grpc-guide.md
  doc/source/serve/api/index.md
  doc/source/serve/doc_code/grpc_proxy/grpc_guide.py
  python/ray/serve/grpc_util.py
Labels: release-blocker

#41848 [Cherry-pick][Serve] Add gRPC context related docs (#41783)
  doc/source/serve/advanced-guides/grpc-guide.md
  doc/source/serve/api/index.md
  doc/source/serve/doc_code/grpc_proxy/grpc_guide.py
  python/ray/serve/grpc_util.py
Labels: release-blocker, docs, v2.9.0-pick

#41840 [serve] Fix bug in deployment state machine (#41799)
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: release-blocker, v2.9.0-pick

#41871 [Tune; RLlib] Fix tune_rllib client release test.
  release/ml_user_tests/tune_rllib/run_connect_tests.py
Labels: release-test

#41769 [core][experimental] Add experimental compiled DAG
  python/ray/_private/ray_perf.py
  python/ray/dag/BUILD
  python/ray/dag/class_node.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/test_accelerated_dag.py
  python/ray/experimental/channel.py
Labels: @author-action-required

#41813 [Doc] Make linkcheck less aggressive when run on PR branches
  .buildkite/lint.rayci.yml
  doc/Makefile
  doc/source/conf.py
  doc/source/ray-contribute/docs.ipynb
Labels: testing, docs

#41891 [Core] Update doc for Ray core accelerator support (#41849)
  doc/source/ray-core/doc_code/gpus.py
  doc/source/ray-core/doc_code/neuron_core_accelerator.py
  doc/source/ray-core/scheduling/accelerators.rst
  doc/source/ray-core/scheduling/index.rst
  doc/source/ray-core/tasks/using-ray-with-gpus.rst
  python/ray/_private/utils.py
  python/ray/runtime_context.py
  python/ray/tests/test_advanced_2.py
  python/ray/train/_internal/worker_group.py
Labels: release-blocker, v2.9.0-pick

#41540 [virtual env] release the conda version constraints
  python/requirements.txt
  python/setup.py
Labels: P1, ray 2.10

#41892 [CherryPick][Serve] Add logging config doc (#41708)
  doc/source/serve/api/index.md
  doc/source/serve/configure-serve-deployment.md
  doc/source/serve/doc_code/monitoring/logging_config.py
  doc/source/serve/monitoring.md
  doc/source/serve/production-guide/config.md
  python/ray/serve/schema.py
Labels: ray 2.9, v2.9.0-pick

#41843 [cherry-pick][Doc][Train] Improve torch, lightning quickstarts and migration guides + fix torch restoration example
  doc/source/train/distributed-tensorflow-keras.rst
  doc/source/train/distributed-xgboost-lightgbm.rst
  doc/source/train/doc_code/checkpoints.py
  doc/source/train/getting-started-pytorch-lightning.rst
  doc/source/train/getting-started-pytorch.rst
  doc/source/train/getting-started-transformers.rst
  doc/source/train/horovod.rst
  doc/source/train/huggingface-accelerate.rst
  python/ray/train/huggingface/transformers/_transformers_utils.py
  python/ray/train/lightning/_lightning_utils.py
Labels: v2.9.0-pick

#41889 Container runtime env docs (#41764)
  doc/source/serve/advanced-guides/index.md
  doc/source/serve/advanced-guides/multi-app-container.md
  doc/source/serve/doc_code/resnet50_example.py
  doc/source/serve/doc_code/whisper_example.py
Labels: release-blocker, v2.9.0-pick

#41890 [docs][cherry-pick] removal of some data, serve, and tune examples
  doc/source/ray-overview/examples.rst
Labels: release-blocker, docs, v2.9.0-pick

#41903 [core] Reduce assertion check in NodeManager on worker not found #41841
  src/ray/common/client_connection.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: release-blocker, v2.9.0-pick

#41926 [2.9][Data] Fix map_batches benchmark (#41812)
  release/nightly_tests/dataset/map_batches_benchmark.py
Labels: release-blocker, v2.9.0-pick

#41844 [cherry-pick][doc][train] Clarify error message when trying to use local storage for multi-node distributed training and checkpointing
  doc/source/train/common/torch-configure-run.rst
  doc/source/train/deepspeed.rst
  doc/source/train/distributed-xgboost-lightgbm.rst
  doc/source/train/doc_code/checkpoints.py
  doc/source/train/doc_code/gbdt_user_guide.py
  doc/source/train/doc_code/key_concepts.py
  doc/source/train/getting-started-pytorch-lightning.rst
  doc/source/train/getting-started-pytorch.rst
  doc/source/train/getting-started-transformers.rst
  doc/source/train/huggingface-accelerate.rst
  doc/source/train/user-guides/persistent-storage.rst
  doc/source/train/user-guides/results.rst
  python/ray/train/_internal/storage.py
  python/ray/train/examples/accelerate/accelerate_torch_trainer.py
  python/ray/train/examples/accelerate/accelerate_torch_trainer_no_raydata.py
  python/ray/train/examples/deepspeed/deepspeed_torch_trainer.py
  python/ray/train/examples/deepspeed/deepspeed_torch_trainer_no_raydata.py
Labels: release-blocker, @author-action-required, v2.9.0-pick

#41921 [cherry-pick][release] Fix `golden_notebook_torch_tune_serve_test` missing argument
  release/golden_notebook_tests/workloads/torch_tune_serve_test.py
Labels: release-blocker, v2.9.0-pick

#41886 [UsageStats] Record hardware usages (#41773)
  python/ray/_private/node.py
  python/ray/_private/resource_spec.py
  python/ray/_private/usage/usage_constants.py
  python/ray/_private/usage/usage_lib.py
  python/ray/_private/utils.py
  python/ray/tests/test_usage_stats.py
  python/ray/tests/test_utils.py
Labels: release-blocker, v2.9.0-pick

#41931 [Core][cherry-pick] Make PythonGcsClient to be thread safe
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
Labels: release-blocker, v2.9.0-pick

#41947 [Core] Disallow callable for job submission api (#41788)
  dashboard/modules/job/sdk.py
  python/ray/runtime_env/runtime_env.py
  python/ray/tests/test_runtime_env_setup_func.py
Labels: release-blocker, v2.9.0-pick

#41925 [core][performance] Only do PlasmaReleaseReply when client knows it's…
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/plasma.fbs
  src/ray/object_manager/plasma/plasma.h
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/protocol.h
  src/ray/object_manager/plasma/shared_memory.h
  src/ray/object_manager/plasma/store.cc
Labels: release-blocker, v2.9.0-pick

#41946 [Core] Fix check failure when sync and async tasks are mixed up #41724
  python/ray/_raylet.pyx
  python/ray/tests/test_streaming_generator_4.py
  src/ray/core_worker/core_worker.cc
Labels: release-blocker, v2.9.0-pick

#41934 [train][release-test] Fix gptj finetuning example to be less sensitive to data ordering
  doc/source/train/examples/deepspeed/gptj_deepspeed_fine_tuning.ipynb
  release/air_examples/gptj_deepspeed_finetuning/gptj_deepspeed_compute_aws.yaml
  release/air_examples/gptj_deepspeed_finetuning/gptj_deepspeed_compute_gce.yaml
Labels: release-test

#41948 [Data] Remove ActorPoolStrategy from documentation
  doc/source/data/api/dataset.rst
  doc/source/data/batch_inference.rst
  doc/source/data/data-internals.rst
  doc/source/data/examples/batch_inference_object_detection.ipynb
  doc/source/data/examples/gptj_batch_prediction.ipynb
  doc/source/data/examples/huggingface_vit_batch_prediction.ipynb
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/data/examples/stablediffusion_batch_prediction.ipynb
  doc/source/data/working-with-images.rst
  doc/source/data/working-with-pytorch.rst
  doc/source/data/working-with-text.rst
  doc/source/templates/01_batch_inference/start.ipynb
  doc/source/train/examples/lightgbm/lightgbm_example.ipynb
  doc/source/train/examples/xgboost/xgboost_example.ipynb
  python/ray/data/_internal/execution/interfaces/execution_options.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
Labels: release-blocker

#41963 [2.9][Data] Remove ActorPoolStrategy from documentation
  doc/source/data/api/dataset.rst
  doc/source/data/batch_inference.rst
  doc/source/data/data-internals.rst
  doc/source/data/examples/batch_inference_object_detection.ipynb
  doc/source/data/examples/gptj_batch_prediction.ipynb
  doc/source/data/examples/huggingface_vit_batch_prediction.ipynb
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/data/examples/stablediffusion_batch_prediction.ipynb
  doc/source/data/working-with-images.rst
  doc/source/data/working-with-pytorch.rst
  doc/source/data/working-with-text.rst
  doc/source/templates/01_batch_inference/start.ipynb
  doc/source/train/examples/lightgbm/lightgbm_example.ipynb
  doc/source/train/examples/xgboost/xgboost_example.ipynb
  python/ray/data/_internal/execution/interfaces/execution_options.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
Labels: tests-ok, release-blocker, v2.9.0-pick

#42000 [pick][data] disable StreamingOutputBackpressurePolicy
  python/ray/data/_internal/execution/backpressure_policy/__init__.py
  python/ray/data/tests/test_backpressure_policies.py
Labels: release-blocker, v2.9.0-pick

#41992 [Release] Add release logs for 2.9.0 commit 15a558e
  release/release_logs/2.9.0/benchmarks/many_actors.json
  release/release_logs/2.9.0/benchmarks/many_nodes.json
  release/release_logs/2.9.0/benchmarks/many_tasks.json
  release/release_logs/2.9.0/microbenchmark.json
  release/release_logs/2.9.0/scalability/object_store.json
  release/release_logs/2.9.0/scalability/single_node.json
  release/release_logs/2.9.0/stress_tests/stress_test_dead_actors.json
  release/release_logs/2.9.0/stress_tests/stress_test_many_tasks.json
  release/release_logs/2.9.0/stress_tests/stress_test_placement_group.json
Labels: release-blocker, P0

#41809 [Doc] Fix lint errors in docs
  doc/source/_templates/csat.html
  doc/source/ray-core/actors.rst
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/splash.html
Labels: testing, docs

#42047 [Doc] Update published Python dependencies for Ray 2.9.0 Docker images
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: release-blocker, ray 2.9

#41750 [docs][cherry-pick] Example Gallery clean up
  doc/BUILD
  doc/source/_templates/examples-sidebar.html
  doc/source/data/examples/batch_training.ipynb
  doc/source/data/examples/index.rst
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/ray-core/examples/batch_training.ipynb
  doc/source/ray-core/examples/overview.rst
  doc/source/ray-core/examples/plot_example-lm.rst
  doc/source/ray-overview/examples.rst
  doc/source/ray-overview/index.md
  doc/source/ray-overview/use-cases.rst
  doc/source/rllib/feature_overview.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-models.rst
  doc/source/serve/tutorials/streaming.md
  doc/source/tune/examples/ml-frameworks.rst
  release/rllib_tests/unit_gpu_tests/run.sh
  rllib/BUILD
  rllib/env/tests/test_env_with_subprocess.py
  rllib/examples/attention_net.py
  rllib/examples/autoregressive_action_dist.py
  rllib/examples/custom_rnn_model.py
  rllib/examples/lstm_auto_wrapping.py
  rllib/examples/vizdoom_with_attention_net.py
  rllib/models/tf/attention_net.py
  rllib/models/torch/attention_net.py
  rllib_contrib/slate_q/BUILD
Labels: release-blocker, docs, v2.9.0-pick

#41943 [core] Fault tolerance for compiled DAGs
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/test_accelerated_dag.py
  python/ray/experimental/channel.py
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/object_manager/common.cc
  src/ray/object_manager/common.h
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/test/object_buffer_pool_test.cc
Labels: @author-action-required

#42041 [serve] Add exponential backoff for `queue_len_response_deadline_s`
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/router.py
  python/ray/serve/tests/unit/test_replica_scheduler.py
Labels: v2.9.1-pick

#41873 [data] refactor `StageSummaryStats` for stage deprecation
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/fast_repartition.py
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/_internal/lazy_block_list.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/stats.py
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_splitblocks.py
  python/ray/data/tests/test_stats.py
Labels: ray 2.10

#42073 [Core] Make sure redis sync context and async context connect to the same redis instance (#42040)
  src/ray/gcs/redis_context.cc
Labels: v2.9.1-pick
