Repository ray-project/ray, pull requests merged in 2023-02, with the labels that each got.

#32110 [runtime env] Clarify error message about where to install `smart_open` for remote URI
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/packaging.py
Labels: tests-ok

#31664 [Doc] Update the doc to mention dynamic resource update is not allowed.
  doc/source/ray-core/scheduling/resources.rst
Labels: @author-action-required

#31046 Join Ray Jobs API `JobInfo` with GCS `JobTableData`
  dashboard/modules/job/common.py
  dashboard/modules/job/tests/test_common.py
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  src/mock/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
Labels: tests-ok

#32057 [core][state] Adjust worker side reporting with batches && add debugstring (remerging #31840)
  BUILD.bazel
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/task_event_buffer_test.cc
  src/ray/core_worker/test/task_manager_test.cc
Labels: tests-ok

#31868 [Core] Pick node from top k by default.
  BUILD.bazel
  python/ray/tests/test_scheduling.py
  src/ray/common/ray_config_def.h
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.h
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy_test.cc
  src/ray/raylet/scheduling/policy/scheduling_options.h
  src/ray/raylet/scheduling/policy/scheduling_policy_test.cc
Labels: tests-ok, release-blocker, @author-action-required

#32107 [core] surface OOM error when actor is killed due to OOM
  doc/source/ray-core/doc_code/ray_oom_prevention.py
  python/ray/tests/test_memory_pressure.py
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
Labels: tests-ok

#31934 [Core] automatically pick max_pending_lease_requests based on number of nodes in the cluster
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/direct_task_transport_mock_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/core_worker/transport/direct_task_transport.h
Labels: tests-ok

#32082 [Core] add ray-core as code-owner for most of the core code-path
  .github/CODEOWNERS
Labels: do-not-merge

#32179 [Release] Cherry-pick #32175
  release/air_tests/air_benchmarks/workloads/benchmark_util.py
Labels: v2.3.0-pick

#32171 [ci][job] Move test_cli_integration to large test
  dashboard/BUILD
Labels: tests-ok

#32187 [CI] Revert version number change for get_wheel tests
  python/ray/tests/test_runtime_env.py
Labels: v2.3.0-pick

#32184 [2.3][Datasets] Fix filter logic and reuse output buffer
  python/ray/data/_internal/planner/filter.py
  python/ray/data/_internal/planner/flat_map.py
  python/ray/data/_internal/planner/map_rows.py
  python/ray/data/tests/test_dynamic_block_split.py
Labels: release-blocker, v2.3.0-pick

#32158 IA polish for demo
  dashboard/client/src/App.tsx
  dashboard/client/src/common/CollapsibleSection.tsx
  dashboard/client/src/common/RowStyles.tsx
  dashboard/client/src/components/ActorTable.tsx
  dashboard/client/src/components/PlacementGroupTable.tsx
  dashboard/client/src/components/TaskTable.tsx
  dashboard/client/src/components/WorkerTable.tsx
  dashboard/client/src/pages/actor/ActorList.tsx
  dashboard/client/src/pages/actor/index.tsx
  dashboard/client/src/pages/job/AdvancedProgressBar/AdvancedProgressBar.tsx
  dashboard/client/src/pages/job/JobDetail.tsx
  dashboard/client/src/pages/job/JobDetailActorPage.tsx
  dashboard/client/src/pages/job/JobProgressBar.tsx
  dashboard/client/src/pages/job/hook/useJobProgress.ts
  dashboard/client/src/pages/node/NodeDetail.tsx
  dashboard/client/src/pages/state/task.tsx
  dashboard/client/src/service/task.ts
  dashboard/client/src/type/job.d.ts
  dashboard/client/src/type/task.ts
  dashboard/client/src/util/hook.ts
  python/ray/experimental/state/common.py
  python/ray/tests/test_state_api_summary.py
Labels: v2.3.0-pick

#31768 [core] release test for nested air (tune) oom
  release/air_tests/air_benchmarks/mlperf-train/resnet50_ray_air.py
  release/air_tests/oom/stress_tests_tune_air_oom_app_config.yaml
  release/air_tests/oom/stress_tests_tune_air_oom_compute.yaml
  release/air_tests/oom/tune_air_oom.sh
  release/release_tests.yaml
Labels: tests-ok

#32164 [Dashboard] Turn on new IA by default
  dashboard/client/src/App.tsx
  dashboard/client/src/pages/layout/MainNavLayout.tsx
  dashboard/tests/cypress/e2e/test_render.cy.js
Labels: v2.3.0-pick

#32248 [Docs] Refactor Ray Workflows API documentation
  doc/source/_toc.yml
  doc/source/ray-references/api.rst
  doc/source/workflows/api/api.rst
  doc/source/workflows/api/execution.rst
  doc/source/workflows/api/management.rst
  doc/source/workflows/package-ref.rst
Labels: release-blocker, v2.3.0-pick

#31702 Remove metrics-based progress-bar endpoints
  dashboard/client/src/service/job.ts
  dashboard/modules/metrics/metrics_head.py
  python/ray/tests/test_metrics_head.py
Labels: @author-action-required

#32252 [Docs] Refactor Python API documentation for job submission
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
Labels: release-blocker, v2.3.0-pick

#31989 [Data] Revise "Getting Started" page
  doc/source/data/doc_code/quick_start.py
  doc/source/data/getting-started.rst
Labels: tests-ok

#31941 [Tune] Add repr for ResultGrid class
  python/ray/air/result.py
  python/ray/tune/result_grid.py
  python/ray/tune/tests/test_result_grid.py
  python/ray/tune/tests/test_tuner.py
Labels: tune

#32286 [Flaky release test] Increase timeout of stress_test_many_tasks to ensure perf metrics are available
  release/release_tests.yaml
Labels: core

#31975 [Datasets] Promote `_create_strict_ragged_ndarray` to public API
  doc/source/data/api/data_representations.rst
  python/ray/air/tests/test_tensor_extension.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/air/util/tensor_extensions/utils.py
  python/ray/data/extensions/tensor_extension.py
Labels: tests-ok

#32258 [core][state] Fix task failed time when job finishes (#32161)
  python/ray/tests/test_task_events.py
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
Labels: tests-ok, v2.3.0-pick

#32302 [core] Fix the GCS memory usage high issue.
  src/ray/rpc/grpc_server.cc
Labels: release-blocker, P0, v2.3.0-pick

#32320 Cherry-pick [Telemetry] track num tasks created (#32106) to 2.3.0 release.
  python/ray/tests/test_usage_stats.py
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/protobuf/usage.proto
Labels: v2.3.0-pick

#32192 [2.3.0] Cherry-pick: IA polish for demo (#32158)
  dashboard/client/src/App.tsx
  dashboard/client/src/common/CollapsibleSection.tsx
  dashboard/client/src/common/RowStyles.tsx
  dashboard/client/src/components/ActorTable.tsx
  dashboard/client/src/components/PlacementGroupTable.tsx
  dashboard/client/src/components/TaskTable.tsx
  dashboard/client/src/components/WorkerTable.tsx
  dashboard/client/src/pages/actor/ActorList.tsx
  dashboard/client/src/pages/actor/index.tsx
  dashboard/client/src/pages/job/AdvancedProgressBar/AdvancedProgressBar.tsx
  dashboard/client/src/pages/job/JobDetail.tsx
  dashboard/client/src/pages/job/JobDetailActorPage.tsx
  dashboard/client/src/pages/job/JobProgressBar.tsx
  dashboard/client/src/pages/job/hook/useJobProgress.ts
  dashboard/client/src/pages/node/NodeDetail.tsx
  dashboard/client/src/pages/state/task.tsx
  dashboard/client/src/service/task.ts
  dashboard/client/src/type/job.d.ts
  dashboard/client/src/type/task.ts
  dashboard/client/src/util/hook.ts
  python/ray/experimental/state/common.py
  python/ray/tests/test_state_api_summary.py
Labels: v2.3.0-pick

#32300 [data] [streaming] No preserve order by default
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_streaming_integration.py
  python/ray/train/tests/test_base_trainer.py
Labels: tests-ok

#32326 Cherry pick [Core] Fix recursive cancelation crashes the worker when actor task is a child. #32259
  python/ray/tests/test_cancel.py
  src/ray/core_worker/core_worker.cc
Labels: v2.3.0-pick

#32323 [core] Fix comments and a corner case in #32302
  src/ray/rpc/grpc_server.cc
Labels: release-blocker, P0, Ray 2.3

#32330 [cherry-pick][core] Fix the GCS memory usage high issue (picks #32302)
  src/ray/rpc/grpc_server.cc
Labels: release-blocker, v2.3.0-pick

#32307 [Serve][Doc] Refactor the Ray Serve API doc
  doc/source/_toc.yml
  doc/source/ray-references/api.rst
  doc/source/serve/api/index.md
  doc/source/serve/api/python_api.md
  doc/source/serve/api/rest_api.md
  doc/source/serve/api/serve_cli.md
  doc/source/serve/package-ref.md
Labels: release-blocker, P0, docs

#32303 [core] Improving failure message when ray processes fail to start on new node
  python/ray/_private/node.py
  python/ray/_private/services.py
Labels: core

#32349 [cherry-pick][doc] Update running large scale ray cluster doc for 2.3. (#32336)
  doc/source/ray-core/miscellaneous.rst
Labels: release-blocker, Ray 2.3, v2.3.0-pick

#31166 [core] Add opt-in flag for Windows and OSX clusters, update `ray start` output to match docs
  .bazelrc
  .buildkite/pipeline.windows.yml
  doc/source/cluster/getting-started.rst
  doc/source/ray-overview/installation.rst
  python/ray/_private/ray_constants.py
  python/ray/_private/services.py
  python/ray/_private/worker.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_basic_4.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  src/ray/gcs/gcs_client/global_state_accessor.cc
Labels: tests-ok, @author-action-required

#32319 [docs]Fix wording of Many model training guidance
  doc/source/ray-overview/use-cases.rst
Labels: docs

#32355 [core][state] Task Backend - reduce lock contention on debug stats / metric recording on counters.
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/util/counter_map.h
Labels: @author-action-required

#32270 Allow overriding the UID of the default grafana dashboard exported by ray
  dashboard/client/src/App.tsx
  dashboard/client/src/pages/metrics/Metrics.component.test.tsx
  dashboard/client/src/pages/metrics/Metrics.tsx
  dashboard/client/src/pages/metrics/utils.ts
  dashboard/client/src/pages/overview/cards/ClusterUtilizationCard.tsx
  dashboard/client/src/pages/overview/cards/NodeCountCard.tsx
  dashboard/modules/metrics/grafana_dashboard_factory.py
  dashboard/modules/metrics/metrics_head.py
  python/ray/tests/test_metrics_head.py
Labels: v2.3.0-pick

#32384 [2.3.0][core][state] Task Backend - reduce lock contention on debug stats/metric recording on counters. (#32355)
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/util/counter_map.h
Labels: v2.3.0-pick

#32424 [core] cherry pick oom doc updates
  doc/source/ray-core/doc_code/ray_oom_prevention.py
  doc/source/ray-core/images/oom_killer_example.svg
  doc/source/ray-core/images/oom_killer_example_killed_one.svg
  doc/source/ray-core/images/oom_killer_example_killed_two.svg
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
Labels: release-blocker, Ray 2.3

#32388 [Job API] Handle multiple drivers with same job submission id in GCS GetAllJobInfo endpoint
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
Labels: tests-ok, v2.3.0-pick

#32411 [Datasets] Not change `map_batches()` UDF name in `Dataset.__repr__`
  doc/source/data/getting-started.rst
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_dataset.py
Labels: tests-ok

#32321 [2.3.0][Doc] Remove Ray Client references from Tune and Train docs/examples
  doc/source/tune/examples/horovod_simple.ipynb
  doc/source/tune/examples/lightgbm_example.ipynb
  doc/source/tune/examples/mxnet_example.ipynb
  doc/source/tune/examples/pbt_ppo_example.ipynb
  doc/source/tune/examples/pbt_transformers.ipynb
  doc/source/tune/examples/tune-xgboost.ipynb
  doc/source/tune/examples/tune_mnist_keras.ipynb
  doc/source/tune/tutorials/tune-stopping.rst
  python/ray/train/examples/horovod/horovod_tune_example.py
  python/ray/tune/examples/async_hyperband_example.py
  python/ray/tune/examples/ax_example.py
  python/ray/tune/examples/bayesopt_example.py
  python/ray/tune/examples/blendsearch_example.py
  python/ray/tune/examples/bohb_example.py
  python/ray/tune/examples/cfo_example.py
  python/ray/tune/examples/custom_func_checkpointing.py
  python/ray/tune/examples/dragonfly_example.py
  python/ray/tune/examples/hebo_example.py
  python/ray/tune/examples/hyperband_example.py
  python/ray/tune/examples/hyperband_function_example.py
  python/ray/tune/examples/hyperopt_conditional_search_space_example.py
  python/ray/tune/examples/lightgbm_example.py
  python/ray/tune/examples/logging_example.py
  python/ray/tune/examples/mnist_ptl_mini.py
  python/ray/tune/examples/mnist_pytorch.py
  python/ray/tune/examples/mxnet_example.py
  python/ray/tune/examples/nevergrad_example.py
  python/ray/tune/examples/optuna_define_by_run_example.py
  python/ray/tune/examples/optuna_example.py
  python/ray/tune/examples/optuna_multiobjective_example.py
  python/ray/tune/examples/pb2_example.py
  python/ray/tune/examples/pbt_example.py
  python/ray/tune/examples/pbt_function.py
  python/ray/tune/examples/pbt_memnn_example.py
  python/ray/tune/examples/pbt_transformers/pbt_transformers.py
  python/ray/tune/examples/skopt_example.py
  python/ray/tune/examples/tf_mnist_example.py
  python/ray/tune/examples/tune_basic_example.py
  python/ray/tune/examples/tune_mnist_keras.py
  python/ray/tune/examples/zoopt_example.py
Labels: v2.3.0-pick

#32434 [2.3][Datasets] Not change `map_batches()` UDF name in `Dataset.__repr__`
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_dataset.py
Labels: release-blocker, v2.3.0-pick

#32311 [Tune][Doc] Restructure API reference
  .gitignore
  doc/source/_toc.yml
  doc/source/ray-air/package-ref.rst
  doc/source/ray-references/api.rst
  doc/source/tune/api/api.rst
  doc/source/tune/api/callbacks.rst
  doc/source/tune/api/cli.rst
  doc/source/tune/api/client.rst
  doc/source/tune/api/env.rst
  doc/source/tune/api/execution.rst
  doc/source/tune/api/integration.rst
  doc/source/tune/api/internals.rst
  doc/source/tune/api/logging.rst
  doc/source/tune/api/reporters.rst
  doc/source/tune/api/result_grid.rst
  doc/source/tune/api/schedulers.rst
  doc/source/tune/api/search_space.rst
  doc/source/tune/api/sklearn.rst
  doc/source/tune/api/stoppers.rst
  doc/source/tune/api/suggestion.rst
  doc/source/tune/api/syncing.rst
  doc/source/tune/api/trainable.rst
  doc/source/tune/api_docs/execution.rst
  doc/source/tune/api_docs/integration.rst
  doc/source/tune/api_docs/result_grid.rst
  doc/source/tune/api_docs/stoppers.rst
  doc/source/tune/api_docs/syncing.rst
  doc/source/tune/examples/tune-xgboost.ipynb
  doc/source/tune/faq.rst
  doc/source/tune/getting-started.rst
  doc/source/tune/key-concepts.rst
  doc/source/tune/tutorials/tune-resources.rst
  doc/source/tune/tutorials/tune-search-spaces.rst
  doc/source/tune/tutorials/tune_get_data_in_and_out.md
  python/ray/tune/search/bayesopt/bayesopt_search.py
  python/ray/tune/search/optuna/optuna_search.py
  python/ray/tune/search/skopt/skopt_search.py
Labels: release-blocker, P0, docs

#32383 [AIR] Allow users to pass `Callable[[torch.Tensor], torch.Tensor]` to `TorchVisionTransform`
  python/ray/data/preprocessors/torch.py
  python/ray/data/tests/preprocessors/test_torch.py
Labels: tests-ok

#32209 [docs] removing docs referring ray client.
  doc/source/cluster/key-concepts.rst
  doc/source/cluster/running-applications/job-submission/index.md
  doc/source/data/modin/index.rst
  doc/source/ray-core/handling-dependencies.rst
  doc/source/ray-core/tasks/generators.rst
  doc/source/ray-more-libs/using-ray-with-pytorch-lightning.rst
  doc/source/tune/examples/tune-mlflow.ipynb
  doc/source/workflows/advanced.rst
  doc/source/workflows/management.rst
  python/ray/scripts/scripts.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  python/ray/tests/test_cli_patterns/test_ray_start_localhost.txt
Labels: v2.3.0-pick

#32394 [Datasets] Update Ray Data documentation for lazy execution by default (1st part)
  doc/source/data/creating-datasets.rst
  doc/source/data/dataset-internals.rst
  doc/source/data/dataset-ml-preprocessing.rst
  doc/source/data/doc_code/creating_datasets.py
  doc/source/data/doc_code/tensor.py
  doc/source/data/doc_code/transforming_datasets.py
  doc/source/data/key-concepts.rst
  doc/source/data/transforming-datasets.rst
Labels: tests-ok, release-blocker

#32387 [Datasets] [Docs] Update docs to reflect lazy-by-default execution model.
  doc/source/data/dataset-internals.rst
  doc/source/data/examples/nyc_taxi_basic_processing.ipynb
  doc/source/data/faq.rst
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/grouped_dataset.py
Labels: release-blocker, @author-action-required

#32443 [ci][core] Do not set flushing thread niceness for task backend #32439
  src/ray/common/constants.h
  src/ray/core_worker/task_event_buffer.cc
Labels: v2.3.0-pick

#32442 [Docs] Fix broken Tune links to overview and intergration
  doc/source/ray-contribute/docs.ipynb
Labels: docs

#32217 [core] Force kill worker whose job has exited
  python/ray/tests/BUILD
  python/ray/tests/test_node_manager.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool_test.cc
Labels: tests-ok

#32390 [Datasets] Make ray.data.from_* APIs lazy.
  doc/source/data/dataset-ml-preprocessing.rst
  doc/source/ray-air/examples/torch_image_example.ipynb
  doc/source/ray-air/examples/torch_incremental_learning.ipynb
  python/ray/data/dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
Labels: release-blocker

#32448 [CherryPick] Ray core doc changes #32153, #32191, #32331
  doc/source/ray-core/actors/patterns/fault-tolerance-actor-checkpointing.rst
  doc/source/ray-core/actors/patterns/index.rst
  doc/source/ray-core/doc_code/actor_checkpointing.py
  doc/source/ray-core/doc_code/anti_pattern_return_ray_put.py
  doc/source/ray-core/doc_code/fault_tolerance_tips.py
  doc/source/ray-core/fault-tolerance.rst
  doc/source/ray-core/fault_tolerance/actors.rst
  doc/source/ray-core/patterns/return-ray-put.rst
  doc/source/ray-core/scheduling/index.rst
Labels: v2.3.0-pick

#32277 [ActorInit] Fix Bug in Actor creation
  python/ray/_raylet.pyx
Labels: @author-action-required

#32234 [tune/train] clean up tune/train result output
  python/ray/train/_internal/session.py
  python/ray/train/constants.py
  python/ray/train/tests/test_examples.py
  python/ray/train/tests/test_gpu_examples.py
  python/ray/train/tests/test_mosaic_trainer.py
  python/ray/tune/result.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/trainable/trainable.py
  rllib/algorithms/algorithm.py
  rllib/utils/test_utils.py
Labels: tests-ok

#32437 [Datasets] Always preserve order for the BulkExecutor.
  python/ray/data/_internal/execution/bulk_executor.py
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/tests/test_bulk_executor.py
Labels: @author-action-required

#32447 [data] Fix pandas import failures by moving it to a top-level data import
  python/ray/data/__init__.py
Labels: tests-ok

#32473 [RLlib] Allow MARLModule customization from algorithm config
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/tests/test_ppo_rl_trainer.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/core/rl_module/marl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/core/rl_module/tests/test_rl_module_specs.py
  rllib/core/rl_trainer/tests/test_trainer_runner_config.py
  rllib/core/rl_trainer/trainer_runner.py
  rllib/core/testing/bc_algorithm.py
  rllib/core/testing/tests/test_bc_algorithm.py
  rllib/core/testing/tf/bc_module.py
  rllib/core/testing/torch/bc_module.py
  rllib/evaluation/rollout_worker.py
  rllib/policy/policy.py
  rllib/utils/policy.py
Labels: tests-ok

#32236 [Doc] Restructure core API docs
  doc/source/_toc.yml
  doc/source/cluster/running-applications/job-submission/jobs-package-ref.rst
  doc/source/ray-core/actors.rst
  doc/source/ray-core/actors/actor-utils.rst
  doc/source/ray-core/api.rst
  doc/source/ray-core/api/cli.rst
  doc/source/ray-core/api/core.rst
  doc/source/ray-core/api/exceptions.rst
  doc/source/ray-core/api/index.rst
  doc/source/ray-core/api/runtime-env.rst
  doc/source/ray-core/api/scheduling.rst
  doc/source/ray-core/api/utility.rst
  doc/source/ray-core/configure.rst
  doc/source/ray-core/examples/monte_carlo_pi.rst
  doc/source/ray-core/fault_tolerance/actors.rst
  doc/source/ray-core/fault_tolerance/tasks.rst
  doc/source/ray-core/objects.rst
  doc/source/ray-core/package-ref.rst
  doc/source/ray-core/patterns/closure-capture-large-objects.rst
  doc/source/ray-core/patterns/limit-pending-tasks.rst
  doc/source/ray-core/patterns/nested-tasks.rst
  doc/source/ray-core/patterns/pass-large-arg-by-value.rst
  doc/source/ray-core/patterns/pipelining.rst
  doc/source/ray-core/patterns/ray-get-loop.rst
  doc/source/ray-core/patterns/ray-get-submission-order.rst
  doc/source/ray-core/patterns/ray-get-too-many-objects.rst
  doc/source/ray-core/patterns/redefine-task-actor-loop.rst
  doc/source/ray-core/patterns/return-ray-put.rst
  doc/source/ray-core/patterns/unnecessary-ray-get.rst
  doc/source/ray-core/scheduling/index.rst
  doc/source/ray-core/scheduling/placement-group.rst
  doc/source/ray-core/scheduling/resources.rst
  doc/source/ray-core/tasks.rst
  doc/source/ray-core/tasks/using-ray-with-gpus.rst
  doc/source/ray-more-libs/joblib.rst
  doc/source/ray-observability/api/state/api.rst
  doc/source/ray-observability/api/state/cli.rst
  doc/source/ray-observability/overview.rst
  doc/source/ray-observability/state/ray-state-api-reference.rst
  doc/source/ray-observability/state/state-api.rst
  doc/source/ray-references/api.rst
  python/ray/data/block.py
  python/ray/data/datasource/partitioning.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/state_cli.py
  rllib/policy/sample_batch.py
Labels: @author-action-required

#32360 [AIR][Train][Doc] Restructure API reference
  .buildkite/pipeline.build.yml
  doc/requirements-doc.txt
  doc/source/_toc.yml
  doc/source/ray-air/api/api.rst
  doc/source/ray-air/api/checkpoint.rst
  doc/source/ray-air/api/configs.rst
  doc/source/ray-air/api/dataset-ingest.rst
  doc/source/ray-air/api/predictor.rst
  doc/source/ray-air/api/preprocessor.rst
  doc/source/ray-air/api/serve.rst
  doc/source/ray-air/api/session.rst
  doc/source/ray-air/examples/serving_guide.ipynb
  doc/source/ray-air/package-ref.rst
  doc/source/ray-references/api.rst
  doc/source/train/api.rst
  doc/source/train/api/api.rst
  doc/source/tune/api/execution.rst
  doc/source/tune/api/integration.rst
  doc/source/tune/api/result_grid.rst
  doc/source/tune/api/trainable.rst
Labels: release-blocker, P0, docs

#32409 [core] Add opt-in flag for Windows and OSX clusters, update ray start output to match docs
  .bazelrc
  .buildkite/pipeline.macos.yml
  .buildkite/pipeline.windows.yml
  doc/source/cluster/getting-started.rst
  doc/source/ray-overview/installation.rst
  java/test.sh
  java/test/src/main/java/io/ray/test/GcsClientTest.java
  python/ray/_private/ray_constants.py
  python/ray/_private/services.py
  python/ray/_private/worker.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_basic_4.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  src/ray/gcs/gcs_client/global_state_accessor.cc
Labels: tests-ok

#32535 [2.3.0][AIR][Train][Doc] Restructure API reference
  .buildkite/pipeline.build.yml
  doc/requirements-doc.txt
  doc/source/_toc.yml
  doc/source/ray-air/api/api.rst
  doc/source/ray-air/api/checkpoint.rst
  doc/source/ray-air/api/configs.rst
  doc/source/ray-air/api/dataset-ingest.rst
  doc/source/ray-air/api/predictor.rst
  doc/source/ray-air/api/preprocessor.rst
  doc/source/ray-air/api/serve.rst
  doc/source/ray-air/api/session.rst
  doc/source/ray-air/examples/serving_guide.ipynb
  doc/source/ray-air/package-ref.rst
  doc/source/ray-references/api.rst
  doc/source/train/api.rst
  doc/source/train/api/api.rst
  doc/source/tune/api/execution.rst
  doc/source/tune/api/integration.rst
  doc/source/tune/api/result_grid.rst
  doc/source/tune/api/trainable.rst
Labels: v2.3.0-pick

#31129 [docs] setting up grafana and prometheus
  doc/source/cluster/running-applications/images/graphs.png
  doc/source/cluster/running-applications/monitoring-and-observability.rst
  doc/source/ray-observability/ray-metrics.rst
Labels: release-blocker, v2.3.0-pick

#32400 [Datasets] Add glossary
  doc/source/_toc.yml
  doc/source/data/glossary.rst
Labels: tests-ok

#32563 [Cherry pick] Cherry pick dashboard visibility improvement
  README.rst
  doc/source/_toc.yml
  doc/source/data/getting-started.rst
  doc/source/ray-air/getting-started.rst
  doc/source/ray-core/ray-dashboard.rst
  doc/source/ray-core/walkthrough.rst
  doc/source/ray-observability/index.rst
  doc/source/ray-observability/monitoring-debugging/monitoring-debugging.rst
  doc/source/ray-observability/overview.rst
  doc/source/ray-overview/index.md
  doc/source/rllib/rllib-training.rst
  doc/source/serve/getting_started.md
  doc/source/train/getting-started.rst
  doc/source/tune/getting-started.rst
Labels: v2.3.0-pick

#32514 [CI/Docker] Upgrade `xgboost-ray` to latest release
  doc/source/ray-air/doc_code/air_key_concepts.py
  doc/source/ray-air/examples/analyze_tuning_results.ipynb
  doc/source/ray-air/examples/xgboost_starter.py
  python/ray/air/tests/test_resource_changing.py
  python/ray/train/tests/test_lightgbm_trainer.py
  python/ray/train/tests/test_xgboost_trainer.py
  python/requirements/ml/requirements_upstream.txt
Labels: release-blocker

#27259 [ci/release] Terminate clusters on job cancellation
  release/ray_release/buildkite/step.py
  release/ray_release/cluster_manager/full.py
  release/ray_release/glue.py
  release/ray_release/signal_handling.py
  release/ray_release/tests/test_buildkite.py
  release/run_release_test.sh
Labels: @author-action-required, do-not-merge

#32584 [docs/rllib] Add gymnasium to doc mocks
  doc/source/custom_directives.py
Labels: v2.3.0-pick

#32615 [2.3.0][docs/rllib] Add gymnasium to doc mocks (#32584)
  doc/source/custom_directives.py
Labels: v2.3.0-pick

#32606 [docs] setting up grafana and prometheus
  doc/source/cluster/running-applications/images/graphs.png
  doc/source/cluster/running-applications/monitoring-and-observability.rst
  doc/source/ray-observability/ray-metrics.rst
Labels: v2.3.0-pick

#32564 [Core][C++ Worker] Cross language call support bytes[] type
  cpp/src/ray/runtime/object/native_object_store.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/test/cluster/cluster_mode_xlang_test.cc
  cpp/src/ray/test/cluster/counter.cc
  cpp/src/ray/test/cluster/counter.h
  cpp/src/ray/test/serialization_test.cc
  cpp/test_python_call_cpp.py
  java/test/src/main/java/io/ray/test/Counter.java
  java/test/src/main/java/io/ray/test/CrossLanguageInvocationTest.java
Labels: C++ Worker

#32632 [RLlib] Made the check_learning_achieved api more general
  rllib/utils/test_utils.py
Labels: tests-ok

#32611 [docs] Ignoring flaky/broken links
  doc/source/conf.py
Labels: docs

#32498 [nightly] Start to populate metrics for many_nodes_actor_test
  release/benchmarks/distributed/many_nodes_tests/actor_test.py
Labels: @author-action-required

#32225 [Serve] Multi app deploy improvements (route check & deployment clean up)
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/client.py
  python/ray/serve/controller.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_application.py
  python/ray/serve/tests/test_application_state.py
Labels: tests-ok

#32600 [Core] Expose KV MultiGet rpc to python GCS client
  python/ray/_private/gcs_utils.py
  python/ray/tests/test_gcs_utils.py
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: tests-ok

#32502 [Doc] [runtime env] Add runtime env architecture doc
  python/ray/runtime_env/ARCHITECTURE.md
Labels: tests-ok

#32186 [Jobs] Add integration test for JobInfo GCS endpoint
  dashboard/modules/job/tests/test_job_manager.py
Labels: tests-ok

#32230 [runtime_env] Print correct default for expiration_s environment variable
  python/ray/_private/runtime_env/packaging.py
  python/ray/tests/test_runtime_env_failure.py
Labels: tests-ok

#32702 [Doc] Clarify that object_spilling_config only needs to be specified on the head node
  doc/source/ray-core/objects/object-spilling.rst
Labels: @author-action-required

#32561 [3/n] Stabilize GCS/Autoscaler interface: Expose task/actor resource demands and node resource usage
  python/ray/tests/test_monitor_service.py
  src/mock/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_monitor_server.cc
  src/ray/gcs/gcs_server/gcs_monitor_server.h
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_monitor_server_test.cc
  src/ray/protobuf/monitor.proto
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: tests-ok

#32708 [Autoscaler] Bump ebs volume size in default configs
  doc/source/cluster/vms/references/ray-cluster-configuration.rst
  doc/source/ray-core/examples/lm/lm-cluster.yaml
  python/ray/autoscaler/aliyun/defaults.yaml
  python/ray/autoscaler/aliyun/example-full.yaml
  python/ray/autoscaler/aliyun/example-linux.yaml
  python/ray/autoscaler/aws/example-full.yaml
  python/ray/autoscaler/aws/example-gpu-docker.yaml
  python/ray/autoscaler/aws/example-ml.yaml
  python/ray/serve/benchmarks/cluster.yaml
  python/ray/serve/benchmarks/single.yaml
Labels: tests-ok

#32712 [release][train] Add `FileLock` to `tensorflow_mnist_example`.
  python/ray/train/examples/tf/tensorflow_mnist_example.py
Labels: tests-ok

#32550 [core]Update boost in ray deps
  .buildkite/pipeline.windows.yml
  WORKSPACE
  bazel/ray_deps_setup.bzl
  ci/docker/test.Dockerfile
  ci/pipeline/fix-windows-bazel.ps1
  python/setup.py
  src/ray/common/test/client_connection_test.cc
  src/ray/util/util.cc
Labels: @author-action-required

#32759 [data] Streaming executor fixes #2
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#32334 [Tune] Sync trial artifacts to cloud
  doc/source/_toc.yml
  doc/source/tune/tutorials/tune-output.rst
  python/ray/air/_internal/remote_storage.py
  python/ray/train/rl/rl_trainer.py
  python/ray/tune/callback.py
  python/ray/tune/execution/experiment_state.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/logger/csv.py
  python/ray/tune/logger/json.py
  python/ray/tune/logger/tensorboardx.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_actor_reuse.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_syncer.py
  python/ray/tune/tests/test_trainable.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/utils/callback.py
  release/tune_tests/cloud_tests/workloads/_tune_script.py
  release/tune_tests/cloud_tests/workloads/run_cloud_test.py
Labels: tests-ok

#32674 Fix disk metric showing double the actual value
  dashboard/modules/reporter/reporter_agent.py
Labels: @author-action-required

#32485 [Jobs] Add end to end test for multiple drivers in a Ray Job
  dashboard/modules/job/tests/test_cli_integration.py
  dashboard/modules/job/tests/test_job_manager.py
  dashboard/modules/snapshot/tests/test_job_submission.py
Labels: tests-ok

#32744 [Datasets] [Operator Fusion - 2/N] Data layer performance/bug fixes and tweaks.
  python/ray/air/util/data_batch_conversion.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/batcher.py
  python/ray/data/_internal/block_builder.py
  python/ray/data/_internal/delegating_block_builder.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/simple_block.py
  python/ray/data/_internal/size_estimator.py
  python/ray/data/_internal/table_block.py
  python/ray/data/dataset.py
Labels: @author-action-required

#32795 [Datasets] Support different number of blocks/rows per block in zip().
  python/ray/data/_internal/equalize.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/split.py
  python/ray/data/_internal/stage_impl.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_split.py
Labels: @author-action-required

#32798 [core] Fix the race condition in the new resource broadcasting.
  release/release_tests.yaml
  src/mock/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/common/ray_syncer/ray_syncer.cc
Labels: @author-action-required

#32821 [Datasets] Fix `from_items` parallelism to create the expected number of blocks.
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#32772 [Serve] Add hash function of RunningReplicaInfo
  python/ray/serve/BUILD
  python/ray/serve/_private/common.py
  python/ray/serve/tests/test_common.py
  python/ray/serve/tests/test_deployment_state.py
Labels: tests-ok

#32470 [Doc|AIR] Add Pytorch ResNet batch prediction example
  doc/source/_toc.yml
  doc/source/ray-air/examples/BUILD
  doc/source/ray-air/examples/index.rst
  doc/source/ray-air/examples/pytorch_resnet_batch_prediction.ipynb
Labels: tests-ok, docs, air

#32436 [Doc] Add Configuring Batch Predictor section in Predictors User Guides
  doc/BUILD
  doc/source/ray-air/doc_code/predictors.py
  doc/source/ray-air/examples/BUILD
  doc/source/ray-air/examples/torch_image_batch_pretrained.py
  doc/source/ray-air/predictors.rst
  python/ray/train/batch_predictor.py
Labels: tests-ok, docs, air

#32800 [data] [streaming] Fix deque race condition and increase max tasks in flight per actor
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/streaming_executor_state.py
Labels: tests-ok

#32559 Fixed dashboard test due to bad dict.pop call
  dashboard/tests/test_dashboard.py
Labels: dashboard, testing, python

#32836 [Datasets] Streaming executor fixes #3
  .buildkite/pipeline.ml.yml
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_dataset.py
  python/ray/data/tests/test_dataset_tfrecords.py
  python/ray/data/tests/test_stats.py
Labels: @author-action-required

#32663 [runtime env] Improve runtime env logs and remove doc for `SKIP_LOCAL_GC`
  dashboard/modules/runtime_env/runtime_env_agent.py
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/uri_cache.py
Labels: tests-ok

#32670 [Cluster Launcher] Add release test for minimal aws config from docs
  doc/source/cluster/vms/getting-started.rst
  python/ray/autoscaler/aws/example-minimal.yaml
  python/ray/autoscaler/aws/tests/aws_cluster.yaml
  python/ray/autoscaler/aws/tests/aws_compute.yaml
  python/ray/autoscaler/aws/tests/aws_config.yaml
  python/ray/autoscaler/aws/tests/download_ssh_key.py
  python/ray/autoscaler/aws/tests/test_aws_cluster_launcher.sh
  release/cluster_tests/test_aws_cluster_launcher.sh
  release/release_tests.yaml
Labels: tests-ok

#32686 [core] additional telemetry for worker pool
  src/ray/raylet/worker_pool.cc
  src/ray/stats/metric_defs.h
Labels: tests-ok

#32767 [Data] Allow generator UDFs for `map_batches` and `flat_map`
  doc/source/data/doc_code/transforming_datasets.py
  doc/source/data/transforming-datasets.rst
  python/ray/data/_internal/planner/map_batches.py
  python/ray/data/block.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#32860 [Datasets] Require preserving order if plan has Zip or Sort stage
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_optimize.py
Labels: tests-ok

#32871 [AIR] Add attributes to `Result` docstring
  python/ray/air/result.py
Labels: tests-ok

#32861 [core] Fix the null function issues in ObjectManager
  src/ray/object_manager/object_manager.cc
Labels: @author-action-required

#32868 [RLlib] Fix algorithm resource bundles
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/examples/learner/ppo_tuner.py
Labels: tests-ok

#32796 Revert "Revert "[AIR/Data] Make `BatchPredictor` lazy""
  doc/source/ray-air/doc_code/air_key_concepts.py
  doc/source/ray-air/doc_code/statsmodel_predictor.py
  doc/source/ray-air/examples/pytorch_tabular_batch_prediction.py
  doc/source/ray-air/examples/tf_tabular_batch_prediction.py
  doc/source/ray-air/examples/torch_image_batch_pretrained.py
  doc/source/ray-air/examples/xgboost_batch_prediction.py
  doc/source/train/doc_code/xgboost_train_predict.py
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_dataset_image.py
  python/ray/train/batch_predictor.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/train/tests/test_batchpredictor_runtime.py
  python/ray/train/tests/test_tensorflow_checkpoint.py
  release/air_tests/air_benchmarks/workloads/gpu_batch_prediction.py
  release/air_tests/air_benchmarks/workloads/xgboost_benchmark.py
Labels: @author-action-required
