Repository ray-project/ray, pull requests merged in 2023-05, with the labels that each got.

#34813 [core] update ActorPool map/map_unordered to submit functions eagerly
  python/ray/tests/test_actor_pool.py
  python/ray/util/actor_pool.py
Labels: tests-ok

#34903 [Templates] Reintroduce requirements.txt + temporary patch fixes
  .github/CODEOWNERS
  doc/BUILD
  doc/source/templates/01_batch_inference/batch_inference.ipynb
  doc/source/templates/02_many_model_training/many_model_training.ipynb
  doc/source/templates/02_many_model_training/requirements.txt
  doc/source/templates/03_serving_stable_diffusion/requirements.txt
  doc/source/templates/03_serving_stable_diffusion/serving_stable_diffusion.ipynb
  doc/source/templates/tests/01_batch_inference/batch_inference.ipynb
  doc/source/templates/tests/02_many_model_training/many_model_training.ipynb
  doc/source/templates/tests/02_many_model_training/requirements.txt
  doc/source/templates/tests/03_serving_stable_diffusion/requirements.txt
  doc/source/templates/tests/03_serving_stable_diffusion/serving_stable_diffusion.ipynb
  release/release_tests.yaml
Labels: tests-ok

#34567 [docs] batch inference docs
  doc/source/data/api/datastream.rst
  doc/source/data/batch_inference.rst
  doc/source/data/doc_code/batch_formats.py
  doc/source/data/doc_code/hf_quick_start.py
  doc/source/data/doc_code/pytorch_quick_start.py
  doc/source/data/doc_code/tf_quick_start.py
  doc/source/data/doc_code/torch_image_batch_trained.py
  doc/source/data/images/actor_batch_prediction.png
  doc/source/data/images/actor_pool_batch_prediction.png
  doc/source/data/images/air_batch_prediction.png
  doc/source/data/images/batch_inference.png
  doc/source/data/images/batch_inference_overview.png
  doc/source/data/images/task_batch_prediction.png
  doc/source/data/images/train_predict_pipeline.png
  doc/source/data/user-guide.rst
  doc/source/ray-air/api/predictor.rst
  doc/source/ray-overview/use-cases.rst
Labels: @author-action-required

#34930 [data] [docs] Generalize fix for converting lists to np.ndarray in UDFs
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/planner/map_batches.py
  python/ray/data/tests/test_strict_mode.py
Labels: tests-ok

#33737 [doc] add doc and example for Ray TLS
  doc/source/cluster/kubernetes/configs/static-ray-cluster.tls.yaml
  doc/source/ray-core/configure.rst
Labels: tests-ok

#34975 [docs] Cherrypick fixes to links
  doc/source/index.md
Labels: v2.4.0-pick

#34772 Avoid copying data multiple times during chunking.
  python/ray/util/client/dataclient.py
Labels: tests-ok

#34730 [no_early_kickoff] Make sure all public APIs will auto-init ray
  python/ray/__init__.py
  python/ray/_private/auto_init_hook.py
  python/ray/_private/client_mode_hook.py
  python/ray/_private/state.py
  python/ray/_private/storage.py
  python/ray/_private/worker.py
  python/ray/actor.py
  python/ray/data/read_api.py
  python/ray/experimental/internal_kv.py
  python/ray/remote_function.py
  python/ray/runtime_context.py
  python/ray/tests/test_client.py
  python/ray/tests/test_client_library_integration.py
  python/ray/util/__init__.py
  python/ray/util/placement_group.py
  python/ray/workflow/api.py
  python/ray/workflow/tests/utils.py
  python/ray/workflow/workflow_state_from_dag.py
Labels: @author-action-required

#34952 [air/output] Print experiment information at experiment start
  python/ray/tune/experimental/output.py
  python/ray/tune/tune.py
Labels: tests-ok

#35000 [tune] Set config on trial restore
  python/ray/tune/experiment/trial.py
  python/ray/tune/tests/test_tune_restore.py
Labels: tests-ok

#34951 [air/output] Improve passed time display
  python/ray/tune/experimental/output.py
  python/ray/tune/tests/output/test_output.py
Labels: tests-ok

#34982 [Tune] Make `Tuner.restore(trainable=...) a required argument
  python/ray/train/tests/test_tune.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/trainable/util.py
  python/ray/tune/tuner.py
Labels: tests-ok

#34645 [core] Start the synchronization connection after receiving all nodes info.
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/test/ray_syncer_test.cc
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#35057 [Doc] Make doc code snippet testable
  doc/source/ray-core/actors.rst
  python/ray/_private/worker.py
Labels: tests-ok

#34999 [Data][Docs] Revise "ML Tensor Support"
  doc/source/data/data-tensor-support.rst
  doc/source/data/data.rst
  doc/source/data/doc_code/loading_data.py
  doc/source/data/key-concepts.rst
  doc/source/data/loading-data.rst
  doc/source/data/performance-tips.rst
  doc/source/data/user-guide.rst
  doc/source/data/working-with-tensors.rst
  python/ray/data/read_api.py
Labels: tests-ok

#34847 [Data] Allow fusing MapOperator -> AllToAllOperator
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/logical/operators/all_to_all_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/planner/exchange/shuffle_task_spec.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok

#35098 Cherrypick
  doc/requirements-doc.txt
  doc/source/_templates/layout.html
  doc/source/conf.py
  doc/source/index.md
Labels: v2.4.0-pick

#35003 [air/output] Improve leaked mentions of Tune concepts
  python/ray/train/base_trainer.py
  python/ray/tune/execution/insufficient_resources_manager.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tune.py
  python/ray/tune/tuner.py
Labels: tests-ok

#34921 [AIR][Telemetry] Environment variable usage
  python/ray/air/BUILD
  python/ray/air/_internal/usage.py
  python/ray/air/constants.py
  python/ray/air/tests/test_air_usage.py
  python/ray/train/constants.py
  python/ray/tune/constants.py
  python/ray/tune/tune.py
  src/ray/protobuf/usage.proto
Labels: tests-ok

#33542 HTTPs support for the job client
  dashboard/modules/dashboard_sdk.py
  dashboard/modules/job/cli.py
  dashboard/modules/job/cli_utils.py
  dashboard/modules/job/sdk.py
  dashboard/modules/job/tests/test_cli.py
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/job/tests/test_https_connection.py
  doc/source/cluster/running-applications/job-submission/sdk.rst
  python/requirements_test.txt
Labels: tests-ok

#33273 [Docker] [runtime env] Bump boto3 version from 1.4.8 to 1.26.82, add pyOpenSSL and cryptography
  doc/source/ray-core/examples/lm/lm-cluster.yaml
  docker/ray-deps/Dockerfile
  python/ray/autoscaler/aws/development-example.yaml
  python/ray/autoscaler/aws/example-gpu-docker.yaml
  python/ray/autoscaler/aws/example-java.yaml
Labels: tests-ok

#34727 [core] Change worker niceness in job submission environment
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/tests/subprocess_driver_scripts/check_niceness.py
  dashboard/modules/job/tests/test_job_manager.py
  python/ray/_private/ray_constants.py
Labels: @author-action-required

#35145 [RLlib] Activate RLModules and Learner together in docs
  doc/source/rllib/doc_code/catalog_guide.py
  doc/source/rllib/doc_code/rlmodule_guide.py
Labels: tests-ok

#34990 [AIR] LightningTrainer Dolly V2 FSDP Fine-tuning Example
  doc/source/_toc.yml
  doc/source/ray-air/examples/BUILD
  doc/source/ray-air/examples/dolly_lightning_fsdp_finetuning.ipynb
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  doc/source/ray-air/examples/index.rst
  doc/source/train/examples.rst
  doc/source/train/examples/lightning/lightning_cola_advanced.ipynb
  doc/source/train/examples/lightning/lightning_mnist_example.ipynb
  doc/source/tune/examples/tune-pytorch-lightning.ipynb
  release/air_examples/dolly_v2_lightning_fsdp_finetuning/dolly_v2_fsdp_compute_aws.yaml
  release/air_examples/dolly_v2_lightning_fsdp_finetuning/dolly_v2_fsdp_env.yaml
  release/air_examples/dolly_v2_lightning_fsdp_finetuning/lightning-llm-finetuning-7b.ipynb
  release/air_examples/dolly_v2_lightning_fsdp_finetuning/test_myst_doc.py
  release/release_tests.yaml
Labels: train, air

#34359 [Data] Improve notebook widget display
  python/ray/data/dataset.py
  python/ray/tests/BUILD
  python/ray/tests/test_widgets.py
  python/ray/train/data_parallel_trainer.py
  python/ray/widgets/util.py
  python/requirements/ml/requirements_ml_docker.txt
Labels: @author-action-required

#34992 [core] Reduce self alive check from 60s to 5s.
  ci/ci.sh
  python/ray/tests/test_gcs_ha_e2e.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/raylet/node_manager.cc
Labels: Ray 2.5

#35116 [core] Turn on ray syncer again.
  src/ray/common/ray_config_def.h
Labels: @author-action-required

#35025 [Client] Optimize chunk size
  python/ray/tests/test_client_reconnect.py
  python/ray/util/client/common.py
Labels: tests-ok

#35070 [serve] Stream Serve logs across different drivers
  python/ray/_private/worker.py
  python/ray/serve/_private/api.py
  python/ray/serve/context.py
  python/ray/serve/tests/test_standalone2.py
Labels: @author-action-required

#35101 [core][dashboard][state] Support task logs from state API
  dashboard/modules/log/log_agent.py
  dashboard/modules/log/log_manager.py
  dashboard/modules/state/state_head.py
  python/ray/_private/log_monitor.py
  python/ray/_private/ray_constants.py
  python/ray/_raylet.pyx
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/experimental/state/state_manager.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_state_api_log.py
  src/ray/core_worker/core_worker.h
  src/ray/protobuf/reporter.proto
Labels: tests-ok

#34896 [core][dashboard] Task backend GC policy - worker update [1/3]
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/task_event_buffer_test.cc
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/gcs.proto
Labels: tests-ok

#35163 [AIR] Remove hard-deprecated and unused code
  python/ray/train/_internal/results_preprocessors/__init__.py
  python/ray/train/_internal/results_preprocessors/aggregate/__init__.py
  python/ray/train/_internal/results_preprocessors/aggregate/aggregate_fn.py
  python/ray/train/_internal/results_preprocessors/aggregate/aggregate_preprocessor.py
  python/ray/train/_internal/results_preprocessors/aggregate/aggregate_utils.py
  python/ray/train/_internal/results_preprocessors/index.py
  python/ray/train/_internal/results_preprocessors/keys.py
  python/ray/train/_internal/results_preprocessors/preprocessor.py
  python/ray/tune/tests/test_trainable_util.py
  python/ray/tune/trainable/util.py
Labels: tests-ok

#35284 [train] Fix HuggingFace -> Transformers wrapping logic 2
  python/ray/train/huggingface/huggingface_checkpoint.py
  python/ray/train/huggingface/huggingface_predictor.py
Labels: tests-ok

#33444 [telemetry] Add libc version to ray telemetry.
  python/ray/_private/usage/usage_lib.py
  python/ray/tests/test_usage_stats.py
Labels: @author-action-required, do-not-merge

#35239 [data] Capture the context when the dataset is first created
  python/ray/data/_internal/iterator/iterator_impl.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_context_propagation.py
Labels: tests-ok, @author-action-required

#35099 [core] Make execute_after accept chrono
  src/ray/common/asio/asio_util.h
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/object_manager/plasma/store.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required

#35272 [no_early_kickoff] [data] Improve our handling of tensor returns in strict mode
  doc/source/data/faq.rst
  doc/source/data/working-with-tensors.rst
  python/ray/data/BUILD
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/numpy_support.py
  python/ray/data/_internal/planner/map_batches.py
  python/ray/data/_internal/table_block.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_numpy_support.py
  python/ray/data/tests/test_tensor.py
  python/ray/train/torch/torch_detection_predictor.py
Labels: Ray 2.5

#35283 [core][state][dashboard][log] Fix subdirectory log getting
  dashboard/modules/log/log_agent.py
  dashboard/modules/log/log_manager.py
  dashboard/modules/state/state_head.py
  python/ray/experimental/state/state_manager.py
  python/ray/tests/test_state_api_log.py
Labels: @author-action-required

#35059 [core][state][no_early_kickoff] Add "humanify" feature to StateSchema
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/tests/test_state_api.py
Labels: tests-ok

#35162 [AIR] Deprecate `ray.tune.logger.Logger` interface
  python/ray/air/integrations/mlflow.py
  python/ray/tune/integration/comet.py
  python/ray/tune/logger/csv.py
  python/ray/tune/logger/json.py
  python/ray/tune/logger/logger.py
  python/ray/tune/logger/noop.py
  python/ray/tune/logger/tensorboardx.py
  python/ray/tune/logger/unified.py
  python/ray/tune/trainable/trainable.py
Labels: tests-ok

#34983 [autoscaler v2][4/n] introducing node-provider and node-provider-config
  python/ray/autoscaler/v2/instance_manager/config.py
  python/ray/autoscaler/v2/instance_manager/node_provider.py
  python/ray/autoscaler/v2/instance_manager/ray_installer.py
Labels: do-not-merge

#35234 [Data] Improve compute validation error
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
Labels: tests-ok

#35339 [Data] Fix inference release test
  release/nightly_tests/dataset/inference.py
Labels: tests-ok

#35278 [Data] Improve `Schema` representation
  doc/source/data/loading-data.rst
  python/ray/data/dataset.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_strict_mode.py
Labels: tests-ok

#35241 [Data] [no_early_kickoff] Add `column` API to Dataset
  doc/source/data/api/dataset.rst
  python/ray/data/dataset.py
  python/ray/data/tests/test_consumption.py
Labels: @author-action-required

#32960 [Train] Don't repartition if xgboost-ray>=0.1.16
  python/ray/train/gbdt_trainer.py
  python/ray/train/lightgbm/lightgbm_trainer.py
  python/ray/train/xgboost/xgboost_trainer.py
Labels: @author-action-required

#35312 [core] Delete disconnected node view in ray syncer when connection is broken.
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/test/ray_syncer_test.cc
Labels: release-blocker

#35361 [doc] [data] Update dataset intro page and fix some typos
  doc/source/data/batch_inference.rst
  doc/source/data/data.rst
  doc/source/ray-air/examples/opt_deepspeed_batch_inference.ipynb
  doc/source/ray-air/examples/upload_to_comet_ml.ipynb
Labels: Ray 2.5

#35359 [data] Fix bugs in handling of nested ndarrays (and other complex object types)
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/numpy_support.py
  python/ray/data/block.py
  python/ray/data/tests/test_numpy_support.py
Labels: Ray 2.5

#35124 [core][state][job] Supporting job listing(getting) and logs from state API
  dashboard/modules/job/common.py
  dashboard/modules/job/job_head.py
  dashboard/modules/job/job_manager.py
  dashboard/modules/job/pydantic_models.py
  dashboard/modules/job/utils.py
  dashboard/modules/log/log_manager.py
  dashboard/modules/state/state_head.py
  dashboard/state_aggregator.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_cli.py
  python/ray/experimental/state/state_manager.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_state_api_log.py
Labels: tests-ok

#34904 [AIR][Telemetry] Experiment tracking integrations + callbacks
  python/ray/air/_internal/remote_storage.py
  python/ray/air/_internal/usage.py
  python/ray/air/integrations/mlflow.py
  python/ray/air/integrations/wandb.py
  python/ray/air/tests/test_air_usage.py
  python/ray/tune/tune.py
  python/ray/tune/utils/callback.py
  src/ray/protobuf/usage.proto
Labels: tests-ok

#35388 [air/output] Add parameter columns to status table
  python/ray/air/config.py
  python/ray/tune/experimental/output.py
  python/ray/tune/tests/output/test_output.py
  python/ray/tune/tune.py
Labels: tests-ok

#35368 [data] Improve map batches error message for strict mode migration
  doc/source/data/data.rst
  python/ray/data/_internal/planner/map_batches.py
  python/ray/data/block.py
Labels: tests-ok, Ray 2.5

#35123 [core] Serialize requests in redis store client.
  BUILD.bazel
  src/ray/gcs/redis_client.cc
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/redis_store_client.h
  src/ray/gcs/store_client/test/redis_store_client_test.cc
Labels: release-blocker

#35320 [core] Sending ReportWorkerFailure after the process died.
  BUILD.bazel
  python/ray/serve/tests/test_controller_recovery.py
  python/ray/tests/test_actor_advanced.py
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_failure_3.py
  python/ray/tests/test_usage_stats.py
  src/ray/common/asio/asio_util.h
  src/ray/common/test/asio_retry_runner_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/util/process.cc
Labels: release-blocker

#35381 [RLlib] DreamerV3: RLModule class, tf.keras model components, dreamer-model, world-model, actor, critic
  rllib/algorithms/dreamerv3/dreamerv3_rl_module.py
  rllib/algorithms/dreamerv3/tf/__init__.py
  rllib/algorithms/dreamerv3/tf/dreamerv3_tf_rl_module.py
  rllib/algorithms/dreamerv3/tf/models/__init__.py
  rllib/algorithms/dreamerv3/tf/models/actor_network.py
  rllib/algorithms/dreamerv3/tf/models/components/__init__.py
  rllib/algorithms/dreamerv3/tf/models/components/cnn_atari.py
  rllib/algorithms/dreamerv3/tf/models/components/continue_predictor.py
  rllib/algorithms/dreamerv3/tf/models/components/conv_transpose_atari.py
  rllib/algorithms/dreamerv3/tf/models/components/dynamics_predictor.py
  rllib/algorithms/dreamerv3/tf/models/components/mlp.py
  rllib/algorithms/dreamerv3/tf/models/components/representation_layer.py
  rllib/algorithms/dreamerv3/tf/models/components/reward_predictor.py
  rllib/algorithms/dreamerv3/tf/models/components/reward_predictor_layer.py
  rllib/algorithms/dreamerv3/tf/models/components/sequence_model.py
  rllib/algorithms/dreamerv3/tf/models/components/vector_decoder.py
  rllib/algorithms/dreamerv3/tf/models/critic_network.py
  rllib/algorithms/dreamerv3/tf/models/disagree_networks.py
  rllib/algorithms/dreamerv3/tf/models/dreamer_model.py
  rllib/algorithms/dreamerv3/tf/models/world_model.py
  rllib/core/rl_module/tf/tf_rl_module.py
  rllib/core/rl_module/torch/torch_rl_module.py
Labels: tests-ok

#35181 [Development] Fix unbound `BUILDKITE` variable in `install-bazel.sh`
  ci/env/install-bazel.sh
Labels: tests-ok

#35270 [train] Restructure `ray.train` HuggingFace modules
  .buildkite/pipeline.build.yml
  doc/requirements-doc.txt
  doc/source/ray-air/api/predictor.rst
  doc/source/ray-air/doc_code/accelerate_trainer.py
  doc/source/ray-air/doc_code/hf_trainer.py
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  doc/source/ray-air/examples/huggingface_text_classification.ipynb
  doc/source/ray-air/trainers.rst
  doc/source/train/api/api.rst
  doc/source/train/config_guide.rst
  doc/source/train/key-concepts.rst
  doc/source/train/train.rst
  python/ray/train/BUILD
  python/ray/train/examples/huggingface/huggingface_basic_language_modeling_example.py
  python/ray/train/examples/transformers/transformers_example.py
  python/ray/train/hf_accelerate/__init__.py
  python/ray/train/hf_transformers/__init__.py
  python/ray/train/huggingface/__init__.py
  python/ray/train/huggingface/_deprecation_msg.py
  python/ray/train/huggingface/accelerate.py
  python/ray/train/huggingface/accelerate/__init__.py
  python/ray/train/huggingface/accelerate/_accelerate_utils.py
  python/ray/train/huggingface/accelerate/accelerate_trainer.py
  python/ray/train/huggingface/huggingface_checkpoint.py
  python/ray/train/huggingface/huggingface_predictor.py
  python/ray/train/huggingface/huggingface_trainer.py
  python/ray/train/huggingface/transformers/__init__.py
  python/ray/train/huggingface/transformers/_transformers_utils.py
  python/ray/train/huggingface/transformers/transformers_checkpoint.py
  python/ray/train/huggingface/transformers/transformers_predictor.py
  python/ray/train/huggingface/transformers/transformers_trainer.py
  python/ray/train/tests/test_accelerate_trainer_gpu.py
  python/ray/train/tests/test_checkpoints.py
  python/ray/train/tests/test_huggingface.py
  python/ray/train/tests/test_minimal.py
  python/ray/train/tests/test_trainer_restore.py
  python/ray/train/tests/test_transformers_checkpoint.py
  python/ray/train/tests/test_transformers_gpu.py
  python/ray/train/tests/test_transformers_predictor.py
  python/ray/train/tests/test_transformers_trainer.py
  python/ray/train/tests/test_transformers_trainer_steps.py
Labels: tests-ok

#34640 [RLlib] Add torch compile capabilities to TorchRLModule
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group_config.py
  rllib/core/learner/torch/torch_learner.py
  rllib/core/models/tests/test_base_models.py
  rllib/core/rl_module/torch/tests/test_torch_rl_module.py
  rllib/core/rl_module/torch/torch_compile_config.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/evaluation/rollout_worker.py
  rllib/models/torch/torch_distributions.py
  rllib/policy/torch_policy_v2.py
  rllib/utils/torch_utils.py
Labels: tests-ok

#35414 [Data/Train] Fix ipython representation
  python/ray/data/dataset.py
  python/ray/tests/test_widgets.py
  python/ray/train/data_parallel_trainer.py
  python/ray/widgets/util.py
Labels: @author-action-required, Ray 2.5, v2.5.0-pick

#35249 [core] Retry failed redis request
  BUILD.bazel
  src/ray/common/ray_config_def.h
  src/ray/common/test_util.cc
  src/ray/common/test_util.h
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/test/redis_store_client_test.cc
  src/ray/gcs/store_client/test/store_client_test_base.h
Labels: release-blocker

#35404 [AIR] Move Constants from tune/results.py to air/constants.py
  python/ray/air/constants.py
  python/ray/air/integrations/mlflow.py
  python/ray/train/_internal/checkpoint.py
  python/ray/train/_internal/session.py
  python/ray/train/constants.py
  python/ray/train/tests/test_examples.py
  python/ray/train/tests/test_gpu_examples.py
  python/ray/train/tests/test_mosaic_trainer.py
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/automl/board/backend/collector.py
  python/ray/tune/cli/commands.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/experimental/output.py
  python/ray/tune/logger/aim.py
  python/ray/tune/logger/csv.py
  python/ray/tune/logger/json.py
  python/ray/tune/logger/tensorboardx.py
  python/ray/tune/progress_reporter.py
  python/ray/tune/result.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/search/optuna/optuna_search.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/execution/test_controller_checkpointing_integration.py
  python/ray/tune/tests/execution/test_controller_search_alg_integration.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_checkpoint_manager.py
  python/ray/tune/tests/test_function_api.py
  python/ray/tune/tests/test_integration_pytorch_lightning.py
  python/ray/tune/tests/test_logger.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tests/test_result_grid.py
  python/ray/tune/tests/test_searchers.py
  python/ray/tune/tests/test_syncer_callback.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_trial_runner_callbacks.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/trainable/function_trainable.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/utils/util.py
  release/train_tests/horovod/train_horovod_multi_node_test.py
Labels: tests-ok, air

#35351 [tune] Track PyTorch tutorials file in our CI
  .buildkite/pipeline.ml.yml
  doc/BUILD
  doc/external/external_code.txt
  doc/external/pytorch_tutorials_hyperparameter_tuning_tutorial.py
Labels: external-code-affected

#35462 [Doc] Fix error in "Writing code snippets"
  doc/source/ray-contribute/writing-code-snippets.rst
Labels: tests-ok

#35419 [data] Fix ragged tensor conversion with map()
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/data/_internal/numpy_support.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/table_block.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_numpy_support.py
  python/ray/data/tests/test_strict_mode.py
Labels: v2.5.0-pick

#35494 [Core] Fix the recursion error when async actor has lots of deserialization.
  python/ray/_raylet.pyx
Labels: v2.5.0-pick

#35505 Revert "Revert "[Data] Add `num_cpus` and `num_gpus` as top-level args to map functions""
  python/ray/data/dataset.py
Labels: tests-ok, v2.5.0-pick

#35515 [serve] Fix `app_builder` doc code test (#35456)
  doc/source/serve/doc_code/app_builder.py
Labels: v2.5.0-pick

#35488 [train] Restructure `ray.train` HuggingFace modules (#35270)
  .buildkite/pipeline.build.yml
  doc/requirements-doc.txt
  doc/source/ray-air/api/predictor.rst
  doc/source/ray-air/doc_code/accelerate_trainer.py
  doc/source/ray-air/doc_code/hf_trainer.py
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  doc/source/ray-air/examples/huggingface_text_classification.ipynb
  doc/source/ray-air/trainers.rst
  doc/source/ray-core/actors/async_api.rst
  doc/source/train/api/api.rst
  doc/source/train/config_guide.rst
  doc/source/train/key-concepts.rst
  doc/source/train/train.rst
  python/ray/train/BUILD
  python/ray/train/examples/huggingface/huggingface_basic_language_modeling_example.py
  python/ray/train/examples/transformers/transformers_example.py
  python/ray/train/hf_accelerate/__init__.py
  python/ray/train/hf_transformers/__init__.py
  python/ray/train/huggingface/__init__.py
  python/ray/train/huggingface/_deprecation_msg.py
  python/ray/train/huggingface/accelerate.py
  python/ray/train/huggingface/accelerate/__init__.py
  python/ray/train/huggingface/accelerate/_accelerate_utils.py
  python/ray/train/huggingface/accelerate/accelerate_trainer.py
  python/ray/train/huggingface/huggingface_checkpoint.py
  python/ray/train/huggingface/huggingface_predictor.py
  python/ray/train/huggingface/huggingface_trainer.py
  python/ray/train/huggingface/transformers/__init__.py
  python/ray/train/huggingface/transformers/_transformers_utils.py
  python/ray/train/huggingface/transformers/transformers_checkpoint.py
  python/ray/train/huggingface/transformers/transformers_predictor.py
  python/ray/train/huggingface/transformers/transformers_trainer.py
  python/ray/train/tests/test_accelerate_trainer_gpu.py
  python/ray/train/tests/test_checkpoints.py
  python/ray/train/tests/test_huggingface.py
  python/ray/train/tests/test_minimal.py
  python/ray/train/tests/test_trainer_restore.py
  python/ray/train/tests/test_transformers_checkpoint.py
  python/ray/train/tests/test_transformers_gpu.py
  python/ray/train/tests/test_transformers_predictor.py
  python/ray/train/tests/test_transformers_trainer.py
  python/ray/train/tests/test_transformers_trainer_steps.py
Labels: v2.5.0-pick

#34812 [AIR][Doc] New Example: LightningTrainer with experiment tracking tools
  doc/source/_toc.yml
  doc/source/conf.py
  doc/source/train/examples.rst
  doc/source/train/examples/lightning/BUILD
  doc/source/train/examples/lightning/lightning_cola_advanced.ipynb
  doc/source/train/examples/lightning/lightning_exp_tracking.ipynb
  doc/source/train/examples/lightning/lightning_mnist_example.ipynb
  doc/source/tune/examples/experiment-tracking.rst
  doc/source/tune/examples/tune-pytorch-lightning.ipynb
Labels: tests-ok, docs, air

#34182 Revert "Revert "Global logging format changes" (#34126)"
  .gitignore
  ci/lint/check_api_annotations.py
  dashboard/agent.py
  doc/source/ray-observability/ray-logging.rst
  python/ray/__init__.py
  python/ray/_private/log.py
  python/ray/_private/ray_logging.py
  python/ray/_private/test_utils.py
  python/ray/_private/worker.py
  python/ray/autoscaler/_private/kuberay/run_autoscaler.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_standalone.py
  python/ray/tests/kuberay/Dockerfile
  python/ray/tests/kuberay/README.md
  python/ray/tests/kuberay/rune2e.sh
  python/ray/tests/kuberay/setup/setup_kuberay.py
  python/ray/tests/kuberay/setup/teardown_kuberay.py
  python/ray/tests/kuberay/test_autoscaling_e2e.py
  python/ray/tests/kuberay/utils.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_get_or_create_actor.py
  python/ray/tests/test_logging.py
  python/ray/tests/test_multi_node_3.py
  python/ray/tests/test_output.py
  python/ray/tests/test_runtime_env_working_dir_2.py
  python/ray/tests/test_usage_stats.py
  python/ray/tests/test_widgets.py
  python/ray/train/tests/test_transformers_gpu.py
  python/ray/tune/automl/search_policy.py
  python/ray/tune/tests/test_commands.py
  python/ray/tune/tests/test_syncer.py
  python/ray/tune/tests/test_syncer_callback.py
  python/ray/tune/tests/test_tuner_restore.py
Labels: @author-action-required

#35464 [CherryPick][Serve] Http proxy & router & handle to support multiplex impl (#35399)
  python/ray/serve/_private/autoscaling_metrics.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/http_proxy.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
  python/ray/serve/context.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_multiplex.py
Labels: v2.5.0-pick

#35481 [cherry-pick][core] Retry failed redis request (#35249)
  BUILD.bazel
  src/ray/common/ray_config_def.h
  src/ray/common/test_util.cc
  src/ray/common/test_util.h
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/test/redis_store_client_test.cc
  src/ray/gcs/store_client/test/store_client_test_base.h
Labels: v2.5.0-pick

#35542 [core] Graceful handling of returning bundles when node is removed (#34726)
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
Labels: v2.5.0-pick

#35483 [Data/Train] Fix ipython representation (cherry-picking #35414)
  python/ray/data/dataset.py
  python/ray/tests/test_widgets.py
  python/ray/train/data_parallel_trainer.py
  python/ray/widgets/util.py
Labels: v2.5.0-pick

#35554 [CI] Skip `test_multiprocessing_client_mode` on windows (#35534)
  ci/ci.sh
Labels: release-blocker, v2.5.0-pick

#35532 [Core] Fix the recursion error when async actor has lots of deseriali…
  python/ray/_raylet.pyx
Labels: release-blocker, v2.5.0-pick

#35527 [Data] Add `num_cpus` and `num_gpus` as top-level args
  python/ray/data/dataset.py
Labels: release-blocker, v2.5.0-pick

#35570 [Cherry Pick] [Serve] [Docs] Cherry pick LLM doc change
  doc/source/serve/api/index.md
  doc/source/serve/index.md
  doc/source/serve/tutorials/gradio-dag-visualization.md
Labels: release-blocker, v2.5.0-pick

#35538 [CI] Build jar on manylinux2014
  .buildkite/pipeline.build.yml
  ci/ci.sh
  python/build-wheel-manylinux2014.sh
Labels: Ray 2.5

#35583 [Pick][CI] Build jar on manylinux2014
  .buildkite/pipeline.build.yml
  ci/ci.sh
  python/build-wheel-manylinux2014.sh
Labels: release-blocker, v2.5.0-pick

#35573 [RLlib] Learner API (+DreamerV3 prep): `Learner.register_metrics` API, cleanup, etc..
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/appo_learner.py
  rllib/algorithms/appo/tf/appo_tf_learner.py
  rllib/algorithms/appo/torch/appo_torch_learner.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/algorithms/impala/tests/test_impala_learner.py
  rllib/algorithms/impala/tf/impala_tf_learner.py
  rllib/algorithms/impala/torch/impala_torch_learner.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/ppo_learner.py
  rllib/algorithms/ppo/tf/ppo_tf_learner.py
  rllib/algorithms/ppo/torch/ppo_torch_learner.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group.py
  rllib/core/learner/tests/test_learner.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/core/learner/tests/test_learner_group_config.py
  rllib/core/learner/tf/tf_learner.py
  rllib/core/learner/torch/tests/test_torch_learner.py
  rllib/core/learner/torch/torch_learner.py
  rllib/core/testing/testing_learner.py
  rllib/core/testing/tests/test_bc_algorithm.py
  rllib/core/testing/tf/bc_learner.py
  rllib/core/testing/torch/bc_learner.py
  rllib/core/testing/utils.py
  rllib/tests/test_algorithm_save_load_checkpoint_learner.py
  rllib/utils/test_utils.py
  rllib/utils/tf_utils.py
  rllib/utils/torch_utils.py
Labels: tests-ok

#35575 [Docs] Remove broken link to external blogpost
  doc/source/ray-overview/learn-more.md
Labels: release-blocker

#35620 [Docs] Remove broken link to external blogpost
  doc/source/ray-overview/learn-more.md
Labels: v2.5.0-pick

#35612 [Cherrypick][Serve] Fix object detection doc test failures (#35528)
  doc/source/serve/doc_code/object_detection.py
Labels: v2.5.0-pick

#35143 [Data] Add batch inference object detection example
  doc/source/_toc.yml
  doc/source/data/batch_inference.rst
  doc/source/data/examples/BUILD
  doc/source/data/examples/batch_inference_object_detection.ipynb
  doc/test_myst_doc.py
  python/ray/data/_internal/table_block.py
Labels: @author-action-required

#35549 [core][autoscaler] GCS Autoscaler V2: Interface [1/x]
  BUILD.bazel
  src/ray/protobuf/BUILD
  src/ray/protobuf/experimental/autoscaler.proto
  src/ray/protobuf/experimental/instance_manager.proto
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: tests-ok

#35642 [RLlib] Fix Checkpointing test when using Learner API
  rllib/examples/checkpoint_by_custom_criteria.py
Labels: tests-ok

#35582 [RLlib] PPO on new API stack: Add `use_kl_loss` setting (already exists for APPO) instead of forcing users to set `kl_coeff` to 0.
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/ppo_learner.py
  rllib/algorithms/ppo/tf/ppo_tf_learner.py
  rllib/algorithms/ppo/torch/ppo_torch_learner.py
Labels: tests-ok

#35647 [core] Fix raylet memory leak in the wrong setup.
  src/ray/raylet/node_manager.cc
Labels: @author-action-required

#35389 [air/output] Switch on per default
  doc/source/ray-air/experimental-features.rst
  python/ray/air/config.py
  python/ray/tune/experimental/output.py
  python/ray/tune/tune.py
Labels: tests-ok

#35529 [RLlib] Don't add a cpu to bundle for learner when using gpu
  release/release_tests.yaml
  release/rllib_tests/multi_node_checkpointing_compute_config.yaml
  release/rllib_tests/multi_node_checkpointing_compute_config_gce.yaml
  release/rllib_tests/smoke_tests/smoke_test_basic_multi_node_training_learner.py
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/core/learner/learner.py
  rllib/examples/learner/multi_agent_cartpole_ppo.py
Labels: release-blocker, v2.5.0-pick

#35651 [RLlib] More time for PPO learner tests
  rllib/BUILD
Labels: tests-ok

#35656 Cherry-pick [1/N] Streaming Generator. Cpp interfaces and implementation (#35291)
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/test_generators.py
  src/ray/common/status.h
  src/ray/core_worker/common.cc
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/core_worker/transport/direct_actor_transport.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: tests-ok, v2.5.0-pick

#35662 [Doc] [runtime_env] Update that local `py_module` wheels are unsupported per-task/per-actor
  doc/source/ray-core/handling-dependencies.rst
Labels: @author-action-required

#35679 [RLlib] Make resource requests for multi gpu learners not request cpu IMPALA
  rllib/algorithms/impala/impala.py
Labels: tests-ok

#35673 [cherry-pick][core] Fix raylet memory leak in the wrong setup. (#35647)
  src/ray/raylet/node_manager.cc
Labels: release-blocker, v2.5.0-pick

#35688 [Data] Clarify GPT2 outputs in HuggingFace example
  doc/source/data/doc_code/hf_quick_start.py
Labels: tests-ok

#35658 [air] Store unflattened metrics in _TrackedCheckpoint
  python/ray/air/_internal/checkpoint_manager.py
  python/ray/air/tests/test_checkpoint_manager.py
  python/ray/tune/experiment/trial.py
Labels: tests-ok, v2.5.0-pick

#35669 [Train] Fix `TorchCheckpoint` encoding directories
  python/ray/air/checkpoint.py
  python/ray/train/tests/test_torch_checkpoint.py
  python/ray/train/torch/torch_checkpoint.py
Labels: v2.5.0-pick

#35718 [Core] Guarantee the ordering of put ActorTaskSpecTable and ActorTable (#35683)
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
Labels: v2.5.0-pick

#35641 [AIR][Telemetry] Record the entrypoint to AIR (`tune.run`, `Tuner.fit`, `Trainer.fit`, etc.)
  python/ray/air/_internal/usage.py
  python/ray/air/tests/test_air_usage.py
  python/ray/tests/test_usage_stats.py
  python/ray/train/base_trainer.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tune.py
  python/ray/tune/tuner.py
  src/ray/protobuf/usage.proto
Labels: tests-ok, v2.5.0-pick

#34495 [scheduler][metrics] E2e scheduling time metrics
  python/ray/tests/test_scheduling_2.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/protobuf/BUILD
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: tests-ok

#35624 [core] Fix GCS FD usage increase regression.
  python/ray/tests/test_advanced_9.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/gcs/pubsub/gcs_pub_sub.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
Labels: @author-action-required, do-not-merge

#35722 [Train] Cherry-pick #35669
  python/ray/air/checkpoint.py
  python/ray/train/tests/test_torch_checkpoint.py
  python/ray/train/torch/torch_checkpoint.py
Labels: v2.5.0-pick

#35691 Add error details for failed jobs
  dashboard/client/src/pages/job/JobDetailInfoPage.tsx
  dashboard/client/src/pages/job/JobRow.tsx
  dashboard/client/src/pages/job/index.tsx
  dashboard/client/src/pages/serve/ServeApplicationDetailPage.tsx
  dashboard/client/src/pages/serve/ServeDeploymentRow.tsx
  dashboard/client/src/pages/serve/ServeSystemActorDetailPage.tsx
Labels: release-blocker

#35719 [Serve] Cherry-pick #35646
  python/ray/serve/_private/application_state.py
  python/ray/serve/tests/test_application_state.py
Labels: release-blocker, v2.5.0-pick

#35740 [AIR][Telemetry] Cherry-pick AIR entrypoint telemetry (#35641)
  python/ray/air/_internal/usage.py
  python/ray/air/tests/test_air_usage.py
  python/ray/tests/test_usage_stats.py
  python/ray/train/base_trainer.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tune.py
  python/ray/tune/tuner.py
  src/ray/protobuf/usage.proto
Labels: v2.5.0-pick

#35708 [Cherry-pick][3/N] Streaming Generator. E2e integration (#35325)
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  cpp/src/ray/runtime/task/task_executor.cc
  cpp/src/ray/runtime/task/task_executor.h
  python/ray/_private/ray_option_utils.py
  python/ray/_private/worker.py
  python/ray/_private/workers/default_worker.py
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/includes/common.pxi
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/test_generators.py
  python/ray/tests/test_streaming_generator.py
  src/ray/common/constants.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: v2.5.0-pick

#35707 [Cherry-pick][Streaming Generator] Fix a reference leak when a stream is deleted w…
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/task_manager_test.cc
Labels: v2.5.0-pick

#34374 [RLlib]: Fix `max_concurrent` in `external_env.py`
  rllib/env/external_env.py
  rllib/env/external_multi_agent_env.py
  rllib/env/tests/test_external_env.py
  rllib/env/tests/test_external_multi_agent_env.py
Labels: external-code-affected

#35706 [2.5.0][air] Store unflattened metrics in _TrackedCheckpoint
  python/ray/air/_internal/checkpoint_manager.py
  python/ray/air/tests/test_checkpoint_manager.py
  python/ray/tune/experiment/trial.py
Labels: v2.5.0-pick

#35615 [Train] TorchCheckpoint: Specifying pickle_protocol in `torch.save()`
  python/ray/train/tests/test_torch_checkpoint.py
  python/ray/train/torch/torch_checkpoint.py
Labels: tests-ok, v2.5.0-pick

#35617 [Train] LightningTrainer always resumes from the latest AIR checkpoint during restoration.
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/tests/test_lightning_trainer_restore.py
Labels: tests-ok, v2.5.0-pick

#35738 [cherry-pick][core] Fix GCS FD usage increase regression. (#35624)
  python/ray/tests/test_advanced_9.py
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/gcs/pubsub/gcs_pub_sub.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
Labels: release-blocker, v2.5.0-pick

#35746 Cherry-pick: Add error details for failed jobs
  dashboard/client/src/pages/job/JobDetailInfoPage.tsx
  dashboard/client/src/pages/job/JobRow.tsx
  dashboard/client/src/pages/job/index.tsx
  dashboard/client/src/pages/serve/ServeApplicationDetailPage.tsx
  dashboard/client/src/pages/serve/ServeDeploymentRow.tsx
  dashboard/client/src/pages/serve/ServeSystemActorDetailPage.tsx
Labels: release-blocker, v2.5.0-pick

#35743 [CherryPick][Serve] Fix wrong log print in model multiplexing (#35702)
  python/ray/serve/_private/deployment_state.py
Labels: v2.5.0-pick

#35752 [Cherry pick] [4/N] Support async actor and async interface.
  python/ray/_private/async_compat.py
  python/ray/_private/ray_perf.py
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/includes/unique_ids.pxd
  python/ray/includes/unique_ids.pxi
  python/ray/tests/test_async.py
  python/ray/tests/test_runtime_context.py
  python/ray/tests/test_streaming_generator.py
  python/ray/util/tracing/tracing_helper.py
  src/ray/common/status.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/task_manager_test.cc
Labels: v2.5.0-pick

#35753 [Datasets] Deprecate `DatasetPipeline`
  doc/source/data/api/dataset.rst
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
Labels: tests-ok

#35756 [Data] Remove `range_arrow`
  python/ray/data/__init__.py
  python/ray/data/read_api.py
Labels: tests-ok

#35792 [Core] Fix docstring examples in `ray/_private`
  python/ray/_private/internal_api.py
  python/ray/_private/ray_logging.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/signature.py
  python/ray/_private/storage.py
  python/ray/_private/utils.py
Labels: tests-ok

#35795 [Autoscaler] Skip `get_static_node_resources_by_ip` docstring example
  python/ray/autoscaler/_private/load_metrics.py
Labels: tests-ok

#35799 [Core] Skip docstring examples in `dag/input_node.py`
  python/ray/dag/input_node.py
Labels: tests-ok

#35806 [Serve] Fix docstring examples
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/utils.py
Labels: tests-ok

#35808 [Workflows] Fix some docstrings
  python/ray/workflow/api.py
  python/ray/workflow/http_event_provider.py
Labels: tests-ok

#35805 Skip `load_package` docstring example
  python/ray/experimental/packaging/load_package.py
Labels: tests-ok

#35593 [autoscaler v2] add test for node provider
  python/ray/autoscaler/_private/node_launcher.py
  python/ray/autoscaler/v2/BUILD
  python/ray/autoscaler/v2/instance_manager/config.py
  python/ray/autoscaler/v2/instance_manager/node_provider.py
  python/ray/autoscaler/v2/tests/test_node_provider.py
  python/ray/tests/autoscaler_test_utils.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_command_runner.py
  python/ray/tests/test_resource_demand_scheduler.py
  src/ray/protobuf/experimental/instance_manager.proto
Labels: tests-ok

#35824 Fix microbenchmark (#35823)
  python/ray/_private/ray_perf.py
Labels: v2.5.0-pick

#35818 [RLlib] Fix LearnerAPI + tf2 slowness due to wrong batch -> tensor conversion.
  rllib/core/learner/learner.py
  rllib/core/learner/tf/tf_learner.py
Labels: release-blocker

#35790 [2.5.0 Pick][Train] TorchCheckpoint: Specifying pickle_protocol in `torch.save()`.
  python/ray/train/tests/test_torch_checkpoint.py
  python/ray/train/torch/torch_checkpoint.py
Labels: v2.5.0-pick

#35791 [2.5.0 Pick][Train] LightningTrainer always resumes from the latest AIR checkpoint
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/tests/test_lightning_trainer_restore.py
Labels: v2.5.0-pick

#35821 [RLlib] Cherry pick: LearnerAPI + tf2 slowness
  rllib/core/learner/learner.py
  rllib/core/learner/tf/tf_learner.py
Labels: tests-ok, release-blocker

#35794 [Cherry-pick][Streaming Generator] Fix a reference leak when pinning requests are …
  python/ray/tests/test_streaming_generator.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/task_manager_test.cc
Labels: tests-ok, v2.5.0-pick

#35784 [Serve] [Docs] Cherry-pick #35578 into 2.5.0 release
  doc/source/ray-core/handling-dependencies.rst
  doc/source/ray-core/runtime_env_auth.md
Labels: release-blocker, v2.5.0-pick

#35772 [Cherry pick] [Test] Move generators test to large (#35747)
  python/ray/tests/BUILD
Labels: tests-ok, v2.5.0-pick

#35803 [Cherry pick][Streaming Generator] Allow to raise an exception to avoid check fail…
  python/ray/_raylet.pyx
  python/ray/tests/test_streaming_generator.py
Labels: tests-ok, v2.5.0-pick

#35807 Fix `log_once` docstring
  python/ray/util/debug.py
Labels: tests-ok

#35809 [Train] Skip some Trainer docstring examples
  python/ray/train/huggingface/accelerate/accelerate_trainer.py
  python/ray/train/lightning/lightning_predictor.py
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/train/torch/torch_trainer.py
Labels: tests-ok

#35834 [RLlib] Cherry-pick-impala-cpu-change
  rllib/algorithms/impala/impala.py
Labels: v2.5.0-pick

#35819 [core][state] Record file offsets instead of logging magic token to track task log (#35572)
  dashboard/client/src/type/task.ts
  dashboard/modules/log/log_agent.py
  dashboard/modules/log/log_manager.py
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_state_api_log.py
  python/ray/tests/test_task_events_2.py
  python/ray/util/state/api.py
  python/ray/util/state/common.py
  python/ray/util/state/state_cli.py
  python/ray/util/state/state_manager.py
  src/ray/protobuf/reporter.proto
Labels: release-blocker, v2.5.0-pick

#35828 Add link to actor logs and message that task logs don't exist for async actors
  dashboard/client/src/pages/serve/ServeApplicationsListPage.component.test.tsx
  dashboard/client/src/pages/task/TaskPage.tsx
Labels: release-blocker

#35839 Add link to actor logs and message that task logs don't exist for async actors
  dashboard/client/src/pages/serve/ServeApplicationsListPage.component.test.tsx
  dashboard/client/src/pages/task/TaskPage.tsx
Labels: release-blocker, v2.5.0-pick

#35385 [RLlib] DreamerV3: Learner API classes for tf-keras, loss functions, additional update method.
  rllib/algorithms/algorithm.py
  rllib/algorithms/dreamerv3/dreamerv3_learner.py
  rllib/algorithms/dreamerv3/tf/dreamerv3_tf_learner.py
  rllib/evaluation/worker_set.py
  rllib/tuned_examples/a3c/cartpole_a3c.py
  rllib/utils/annotations.py
  rllib/utils/replay_buffers/__init__.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
  rllib/utils/replay_buffers/tests/test_episode_replay_buffer.py
  rllib/utils/tf_utils.py
Labels: tests-ok

#35770 [air/output] Fix output encoding in windows
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/experimental/output.py
Labels: tests-ok

#35286 [CI] Migrate from `sphinx.ext.doctest` to `pytest-sphinx`
  .buildkite/pipeline.build.yml
  .buildkite/pipeline.gpu_large.yml
  .buildkite/pipeline.ml.yml
  bazel/BUILD
  bazel/conftest.py
  bazel/pytest_wrapper.py
  bazel/python.bzl
  ci/ci.sh
  doc/BUILD
  python/ray/_private/BUILD
  python/ray/air/BUILD
  python/ray/autoscaler/BUILD
  python/ray/dag/BUILD
  python/ray/data/BUILD
  python/ray/experimental/BUILD
  python/ray/runtime_env/BUILD
  python/ray/scripts/BUILD
  python/ray/serve/BUILD
  python/ray/train/BUILD
  python/ray/train/tensorflow/tensorflow_trainer.py
  python/ray/tune/BUILD
  python/ray/util/BUILD
  python/ray/workflow/BUILD
  python/requirements/ml/requirements_dl.txt
  python/requirements_test.txt
  rllib/BUILD
Labels: tests-ok

#35852 [Data] Import built-in packages at module level
  python/ray/data/_internal/util.py
Labels: tests-ok

#35904 [2.5.0 release] Revert "[2.5.0 Release Disable further docker builds (#35861)"
  .buildkite/pipeline.build.yml
Labels: release-blocker

#35648 [Data][1/N] Enable optimizer: fix read and materialize
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/logical/operators/input_data_operator.py
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/_internal/planner/plan_input_data_op.py
  python/ray/data/_internal/planner/plan_read_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_randomize_block_order.py
Labels: @author-action-required

#35921 [core] Feature flag actor task logs with off by default
  dashboard/client/src/pages/task/TaskPage.tsx
  dashboard/modules/log/log_manager.py
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/tests/test_state_api_log.py
  python/ray/tests/test_task_events_2.py
Labels: tests-ok, release-blocker

#35760 [doc][core][dashboard][state] Promote state api and dashboard usage in core user guide.
  doc/source/ray-core/actors.rst
  doc/source/ray-core/actors/terminating-actors.rst
  doc/source/ray-core/fault_tolerance/tasks.rst
  doc/source/ray-core/tasks.rst
Labels: v2.5.0-pick
