Repository ray-project/ray, pull requests merged in 2023-06, with the labels that each got.

#35704 [Data] Image Classification Batch Inference with Ray Data
  doc/source/_toc.yml
  doc/source/data/examples/BUILD
  doc/source/data/examples/batch_inference_object_detection.ipynb
  doc/source/data/examples/index.rst
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/ray-air/computer-vision.rst
  doc/source/ray-air/examples/BUILD
  doc/source/ray-air/examples/index.rst
  doc/source/ray-air/examples/pytorch_resnet_batch_prediction.ipynb
Labels: tests-ok

#35854 [Data] Remove pipelined test variants
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_formats.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_split.py
  python/ray/data/tests/test_torch.py
Labels: tests-ok

#35967 [Core] Add get_worker_id() to runtime context
  python/ray/_private/ray_logging.py
  python/ray/runtime_context.py
  python/ray/serve/_private/http_proxy.py
  python/ray/serve/_private/replica.py
  python/ray/serve/controller.py
  python/ray/tests/test_actor_advanced.py
Labels: tests-ok

#35568 [Data] Optimize block prefetching
  python/ray/data/_internal/block_batching/block_batching.py
  python/ray/data/_internal/block_batching/interfaces.py
  python/ray/data/_internal/block_batching/iter_batches.py
  python/ray/data/_internal/block_batching/util.py
Labels: @author-action-required

#35999 [CI] Deflake doctest CI
  bazel/python.bzl
  doc/source/data/loading-data.rst
  doc/source/ray-core/actors/async_api.rst
  doc/source/ray-core/tips-for-first-time.rst
Labels: tests-ok

#36005 [docs] fix Post Mortem Debugging example
  doc/source/ray-observability/user-guides/debug-apps/ray-debugging.rst
Labels: tests-ok

#35983 [docs] kapa ask our docs widget
  doc/source/_static/css/custom.css
  doc/source/_templates/layout.html
Labels: v2.5.0-pick

#36010 Deflake test_worker_kv_calls (#35744)
  python/ray/_private/function_manager.py
  python/ray/_private/import_thread.py
  python/ray/_private/utils.py
  python/ray/_raylet.pyx
  python/ray/tests/test_basic_5.py
Labels: v2.5.0-pick

#35879 [RLlib] Deprecate/cleanup: AlgorithmConfig["multiagent"] access and usage in tests and examples.
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/alpha_zero/alpha_zero.py
  rllib/algorithms/apex_ddpg/apex_ddpg.py
  rllib/algorithms/apex_dqn/apex_dqn.py
  rllib/algorithms/ddpg/ddpg.py
  rllib/algorithms/dreamer/dreamer.py
  rllib/algorithms/leela_chess_zero/leela_chess_zero.py
  rllib/algorithms/maddpg/maddpg.py
  rllib/algorithms/sac/sac.py
  rllib/algorithms/simple_q/simple_q.py
  rllib/algorithms/slateq/slateq.py
  rllib/algorithms/td3/td3.py
  rllib/evaluate.py
  rllib/examples/coin_game_env.py
  rllib/examples/iterated_prisoners_dilemma_env.py
  rllib/examples/multi_agent_parameter_sharing.py
  rllib/policy/tests/test_export_checkpoint_and_model.py
  rllib/tests/test_supported_multi_agent.py
  rllib/utils/replay_buffers/utils.py
  rllib/utils/test_utils.py
  rllib/utils/tests/test_check_multi_agent.py
  rllib/utils/tests/test_checkpoint_utils.py
  rllib/utils/typing.py
Labels: tests-ok

#35995 [docs] Fixing inconsistent height of cards on landing page
  doc/source/index.md
Labels: v2.5.0-pick

#36003 [logging] Fix typo in log deduplicator
  doc/source/ray-air/check-ingest.rst
  python/ray/_private/ray_logging.py
  python/ray/tests/test_log_dedup.py
Labels: @author-action-required

#35816 Update observability doc structure and content
  doc/source/_toc.yml
  doc/source/cluster/configure-manage-dashboard.md
  doc/source/cluster/configure-manage-dashboard.rst
  doc/source/cluster/kubernetes/user-guides/logging.md
  doc/source/cluster/metrics.md
  doc/source/cluster/running-applications/index.md
  doc/source/cluster/running-applications/monitoring-and-observability.rst
  doc/source/cluster/vms/user-guides/logging.md
  doc/source/ray-observability/getting-started.rst
  doc/source/ray-observability/images/application-logging.png
  doc/source/ray-observability/images/importance-of-observability.png
  doc/source/ray-observability/images/setup-logger-application.png
  doc/source/ray-observability/images/what-is-ray-observability.png
  doc/source/ray-observability/index.md
  doc/source/ray-observability/index.rst
  doc/source/ray-observability/key-concepts.rst
  doc/source/ray-observability/user-guides/cli-sdk.rst
  doc/source/ray-observability/user-guides/configure-logging.md
  doc/source/ray-observability/user-guides/configure-logging.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-failures.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-hangs.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-memory.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-other.rst
  doc/source/ray-observability/user-guides/debug-apps/optimize-performance.rst
  python/ray/runtime_context.py
Labels: v2.5.0-pick

#36055 [Java] Upgrade TestNG to patch CVEs (#36027)
  java/dependencies.bzl
  java/pom.xml
Labels: v2.5.0-pick

#35969 Cherry pick docs PRs for contributor page, landing page, o11y
  doc/source/_toc.yml
  doc/source/cluster/configure-manage-dashboard.rst
  doc/source/cluster/images/graphs.png
  doc/source/cluster/kubernetes/user-guides/logging.md
  doc/source/cluster/running-applications/monitoring-and-observability.rst
  doc/source/data/performance-tips.rst
  doc/source/index.md
  doc/source/ray-air/getting-started.rst
  doc/source/ray-contribute/docs.ipynb
  doc/source/ray-core/api/index.rst
  doc/source/ray-core/ray-dashboard.rst
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  doc/source/ray-core/walkthrough.rst
  doc/source/ray-observability/getting-started.rst
  doc/source/ray-observability/index.rst
  doc/source/ray-observability/key-concepts.rst
  doc/source/ray-observability/monitoring-debugging/getting-help.rst
  doc/source/ray-observability/monitoring-debugging/monitoring-debugging.rst
  doc/source/ray-observability/overview.rst
  doc/source/ray-observability/ray-logging.rst
  doc/source/ray-observability/ray-metrics.rst
  doc/source/ray-observability/reference/api.rst
  doc/source/ray-observability/reference/cli.rst
  doc/source/ray-observability/reference/index.md
  doc/source/ray-observability/reference/system-metrics.rst
  doc/source/ray-observability/user-guides/add-app-metrics.rst
  doc/source/ray-observability/user-guides/cli-sdk.rst
  doc/source/ray-observability/user-guides/configure-logging.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-failures.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-hangs.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-memory.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-other.rst
  doc/source/ray-observability/user-guides/debug-apps/index.md
  doc/source/ray-observability/user-guides/debug-apps/optimize-performance.rst
  doc/source/ray-observability/user-guides/debug-apps/ray-debugging.rst
  doc/source/ray-observability/user-guides/index.md
  doc/source/ray-observability/user-guides/ray-tracing.rst
  doc/source/ray-observability/user-guides/troubleshoot-apps/index.md
  doc/source/ray-observability/user-guides/troubleshoot-apps/optimize-performance.rst
  doc/source/rllib/rllib-training.rst
  doc/source/train/getting-started.rst
  doc/source/tune/getting-started.rst
Labels: v2.5.0-pick

#36048 docs cherry pick 2.5 for the kapa hotfix
  doc/source/_static/js/custom.js
Labels: v2.5.0-pick

#35885 [Cherrypick][Serve][Doc] Multiplexing doc (#35701)
  doc/source/_toc.yml
  doc/source/serve/doc_code/multiplexed.py
  doc/source/serve/model-multiplexing.md
  doc/source/serve/production-guide/monitoring.md
  doc/source/serve/user-guide.md
Labels: v2.5.0-pick

#35934 [doc][core][dashboard][state] Promote state api and dashboard usage in core user guide. (#35760)
  doc/source/ray-core/actors.rst
  doc/source/ray-core/actors/terminating-actors.rst
  doc/source/ray-core/fault_tolerance/tasks.rst
  doc/source/ray-core/tasks.rst
Labels: v2.5.0-pick

#35226 [CI] Add env var suggestion for common call ray start fixture error on MacOS
  python/ray/tests/conftest.py
Labels: tests-ok

#36039 [data] Fix edge case in empty bundles with streaming split
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/tests/test_torch.py
Labels: tests-ok

#35959 [RLlib] Enhance policy.get_state() docstring
  rllib/policy/policy.py
Labels: tests-ok

#36031 [docs][cherry-pick] Fixing inconsistent height of cards on landing page (#35995)
  doc/source/index.md
Labels: @author-action-required, v2.5.0-pick

#36054 [Observability] Several fixes to the observability doc
  doc/source/_toc.yml
  doc/source/cluster/configure-manage-dashboard.md
  doc/source/cluster/kubernetes/user-guides/logging.md
  doc/source/cluster/metrics.md
  doc/source/ray-observability/getting-started.rst
  doc/source/ray-observability/images/dashboard-overview.png
  doc/source/ray-observability/key-concepts.rst
  doc/source/ray-observability/user-guides/cli-sdk.rst
  doc/source/ray-observability/user-guides/configure-logging.md
  doc/source/ray-observability/user-guides/debug-apps/debug-failures.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-hangs.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-memory.rst
  doc/source/ray-observability/user-guides/debug-apps/general-debugging.rst
  doc/source/ray-observability/user-guides/debug-apps/index.md
  doc/source/ray-observability/user-guides/debug-apps/optimize-performance.rst
Labels: v2.5.0-pick

#36086 [Cherrypick][Serve] Improve the replica recover scenario (#35946)
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
  python/ray/serve/config.py
  python/ray/serve/tests/test_controller_recovery.py
  python/ray/serve/tests/test_deployment_state.py
Labels: v2.5.0-pick

#35846 [core][autoscaler] GCS Autoscaler V2: Support autoscaler.sdk.request_resources [5/x]
  BUILD.bazel
  python/ray/autoscaler/_private/commands.py
  python/ray/autoscaler/v2/BUILD
  python/ray/autoscaler/v2/__init__.py
  python/ray/autoscaler/v2/sdk.py
  python/ray/autoscaler/v2/tests/conftest.py
  python/ray/autoscaler/v2/tests/test_sdk.py
  python/ray/autoscaler/v2/tests/util.py
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  python/ray/tests/BUILD
  src/ray/common/ray_config_def.h
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/experimental/autoscaler.proto
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: tests-ok

#36133 [Doc] Make doc code snippet testable [5/n] (#35562)
  doc/source/ray-observability/user-guides/cli-sdk.rst
  doc/source/ray-observability/user-guides/debug-apps/debug-other.rst
  python/ray/util/state/api.py
Labels: v2.5.0-pick

#36043 [Data] Unify "From*" operators
  python/ray/data/_internal/logical/operators/from_arrow_operator.py
  python/ray/data/_internal/logical/operators/from_items_operator.py
  python/ray/data/_internal/logical/operators/from_numpy_operator.py
  python/ray/data/_internal/logical/operators/from_operators.py
  python/ray/data/_internal/logical/operators/from_pandas_operator.py
  python/ray/data/_internal/logical/util.py
  python/ray/data/_internal/planner/plan_from_arrow_op.py
  python/ray/data/_internal/planner/plan_from_items_op.py
  python/ray/data/_internal/planner/plan_from_numpy_op.py
  python/ray/data/_internal/planner/plan_from_op.py
  python/ray/data/_internal/planner/plan_from_pandas_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_formats.py
  python/ray/data/tests/test_mars.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_pandas.py
  python/ray/data/tests/test_raydp.py
Labels: @author-action-required

#36095 [docs] Scaling with Ray before Getting started
  doc/source/index.md
Labels: v2.5.0-pick

#36148 remove data ingest, update batch and serving examples to be LLMs
  doc/source/index.md
Labels: tests-ok, v2.5.0-pick

#36173 [Docs] Picks [docs] kapa ask our docs widget
  doc/source/_static/css/custom.css
  doc/source/_templates/layout.html
Labels: release-blocker, v2.5.0-pick

#36145 [Data][Docs] Merge Data glossary with Ray glossary
  doc/source/_toc.yml
  doc/source/data/glossary.rst
  doc/source/ray-references/glossary.rst
Labels: tests-ok

#36155 [tune] Track trial failures after restore
  python/ray/tune/experiment/trial.py
  python/ray/tune/result_grid.py
Labels: tests-ok

#35859 [2.5.0 release] Add release logs
  release/release_logs/2.5.0/benchmarks/many_actors.json
  release/release_logs/2.5.0/benchmarks/many_nodes.json
  release/release_logs/2.5.0/benchmarks/many_pgs.json
  release/release_logs/2.5.0/benchmarks/many_tasks.json
  release/release_logs/2.5.0/microbenchmark.json
  release/release_logs/2.5.0/scalability/object_store.json
  release/release_logs/2.5.0/scalability/single_node.json
  release/release_logs/2.5.0/stress_tests/stress_test_dead_actors.json
  release/release_logs/2.5.0/stress_tests/stress_test_many_tasks.json
  release/release_logs/2.5.0/stress_tests/stress_test_placement_group.json
  release/release_logs/fetch_release_logs.py
Labels: release-blocker

#36184 [cherry-pick] [docs] Distributed checkpointing in user guide (#36139)
  doc/source/train/config_guide.rst
Labels: v2.5.0-pick

#35950 [Data] Implement Limit Operator Pushdown
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/one_to_one_operator.py
  python/ray/data/_internal/logical/operators/limit_operator.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/logical/operators/one_to_one_operator.py
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/logical/rules/limit_pushdown.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/planner/plan_limit_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_operators.py
Labels: tests-ok

#36151 [docs] cherry-pick remove data ingest, update batch and serving examples to be LLMs
  doc/source/index.md
Labels: v2.5.0-pick

#36183 [docs] Seventh cherry pick 2.5
  doc/source/index.md
Labels: v2.5.0-pick

#30895 [Core][deprecate run_function_on_all_workers 3/n] delete run_function_on_all_workers
  python/ray/_private/import_thread.py
  python/ray/_private/worker.py
  python/ray/data/tests/test_ecosystem.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/tests/modin/test_modin.py
  python/ray/tests/test_advanced.py
  python/ray/tests/test_basic_5.py
  python/ray/tests/test_cancel.py
  python/ray/tests/test_failure.py
  python/requirements/data_processing/requirements.txt
  python/requirements/ml/requirements_upstream.txt
  release/air_tests/air_benchmarks/xgboost_app_config.yaml
  release/xgboost_tests/app_config_gpu.yaml
Labels: @author-action-required, Ray 2.4

#36144 [Data][Docs] Revise "Loading data"
  doc/source/data/doc_code/loading_data.py
  doc/source/data/doc_code/loading_data_untested.py
  doc/source/data/loading-data.rst
  python/ray/data/read_api.py
Labels: @author-action-required

#36162 [Data][Docs] Revise Transforming data
  doc/BUILD
  doc/source/data/transforming-data.rst
Labels: tests-ok

#36161 [Data] Unify "From*" operators
  python/ray/data/_internal/logical/operators/from_arrow_operator.py
  python/ray/data/_internal/logical/operators/from_items_operator.py
  python/ray/data/_internal/logical/operators/from_numpy_operator.py
  python/ray/data/_internal/logical/operators/from_operators.py
  python/ray/data/_internal/logical/operators/from_pandas_operator.py
  python/ray/data/_internal/logical/util.py
  python/ray/data/_internal/planner/plan_from_arrow_op.py
  python/ray/data/_internal/planner/plan_from_items_op.py
  python/ray/data/_internal/planner/plan_from_numpy_op.py
  python/ray/data/_internal/planner/plan_from_op.py
  python/ray/data/_internal/planner/plan_from_pandas_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_formats.py
  python/ray/data/tests/test_mars.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_pandas.py
  python/ray/data/tests/test_raydp.py
Labels: @author-action-required

#35412 [Autoscaler] Add friendlier status message upon "No cluster status"
  python/ray/autoscaler/_private/commands.py
Labels: tests-ok

#34022 [runtime env] Use less common filename for internal `requirements.txt`
  python/ray/_private/runtime_env/pip.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
Labels: tests-ok

#34586 [no_early_kickoff] [Job] Add metadata to job CLI
  dashboard/modules/job/cli.py
  dashboard/modules/job/tests/test_cli.py
  dashboard/modules/job/tests/test_cli_integration.py
  doc/source/cluster/running-applications/job-submission/cli.rst
  python/ray/_private/utils.py
Labels: tests-ok

#32083 [autoscaler] Support TPU as Head Node
  python/ray/autoscaler/_private/gcp/config.py
  python/ray/autoscaler/_private/gcp/node.py
  python/ray/autoscaler/gcp/tpu.yaml
Labels: tests-ok

#36231 [autoscaler] fix too many values to unpack (expected 2) bug
  python/ray/autoscaler/_private/monitor.py
Labels: v2.5.0-pick

#35931 [RLlib][Docs] Enable doctests for RLLib
  rllib/BUILD
  rllib/algorithms/apex_ddpg/apex_ddpg.py
  rllib/algorithms/simple_q/simple_q.py
  rllib/core/models/catalog.py
  rllib/execution/parallel_requests.py
  rllib/utils/lambda_defaultdict.py
  rllib/utils/nested_dict.py
Labels: tests-ok

#35970 [core][autoscaler] GCS Autoscaler V2: Add placement group's gang resource requests handling [4/x]
  src/mock/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/mock/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/common/constants.h
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/experimental/autoscaler.proto
Labels: tests-ok

#36266 [Cherry-pick][Train] Don't error on eventual success when running with auto-recovery (`max_failures > 0`)
  python/ray/train/tests/test_trainer_restore.py
  python/ray/train/tests/test_tune.py
  python/ray/tune/result_grid.py
Labels: v2.5.1-pick

#36272 [data] fix lint and broken link
  doc/source/data/examples/batch_inference_object_detection.ipynb
Labels: v2.5.1-pick

#36271 [data] fix lint and broken link
  doc/source/data/examples/batch_inference_object_detection.ipynb
Labels: v2.5.0-pick

#36280 [docs] cherry-pick Cp10 2.5.1
  doc/source/_static/js/custom.js
Labels: v2.5.1-pick

#36279 [docs] cherry-pick Cp10 2.5.0
  doc/source/_static/js/custom.js
Labels: v2.5.0-pick

#36247 [docs] cherry-pick change recommended install to ray[air] 2.5.0
  doc/source/ray-overview/getting-started.md
Labels: v2.5.0-pick

#36248 [docs] cherry-pick change recommended install to ray[air] 2.5.1
  doc/source/ray-overview/getting-started.md
Labels: v2.5.1-pick

#36228 [Cluster launcher] Update availability zone in TPU yaml
  python/ray/autoscaler/gcp/tpu.yaml
Labels: tests-ok

#36334 Fix mypy error: Module "ray" does not explicitly export attribute "remote"
  python/ray/__init__.py
Labels: release-blocker, P0

#36356 Fix mypy error: Module "ray" does not explicitly export attribute "remote"
  python/ray/__init__.py
Labels: release-blocker

#36366 [AIR][Telemetry] Add back renamed `HuggingFaceTrainer` for telemetry tracking
  python/ray/air/_internal/usage.py
Labels: tests-ok

#36205 [Serve] Only update RUNNING replicas
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
  python/ray/serve/tests/test_deployment_state.py
Labels: tests-ok

#36373 [ci][py3.11] Build python wheels on mac os for 3.11 (#36185)
  ci/ci.sh
  python/build-wheel-macos-arm64.sh
  python/build-wheel-macos.sh
Labels: v2.5.1-pick

#36377 [Cherry-pick][Train] Tag `HuggingFaceTrainer` correctly
  python/ray/air/_internal/usage.py
Labels: v2.5.1-pick

#36388 [doc][python3.11] Update mac os wheels built link (#36379)
  doc/source/ray-overview/installation.rst
Labels: v2.5.1-pick

#36427 [Doc][Tune] Fix double reference in tune docs
  doc/source/train/examples/lightning/lightning_exp_tracking.ipynb
  doc/source/tune/examples/experiment-tracking.rst
Labels: tests-ok

#36290 [data] Spread map task stages by default for arg size <50MB
  doc/source/ray-air/doc_code/air_ingest_new.py
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/context.py
  python/ray/data/random_access_dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_stats.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok

#35040 [ci/docker] Move CI + Docker to Python 3.8 [build_base]
  .buildkite/pipeline.arm64.yml
  .buildkite/pipeline.build.yml
  .buildkite/pipeline.gpu_large.yml
  .buildkite/pipeline.macos.yml
  .buildkite/pipeline.ml.yml
  .buildkite/pipeline.windows.yml
  ci/build/build-docker-images.py
  ci/ci.sh
  ci/docker/base.gpu.Dockerfile
  ci/docker/base.test.Dockerfile
  ci/docker/build.Dockerfile
  ci/env/install-dependencies.sh
  doc/BUILD
  docker/base-deps/Dockerfile
  docker/retag-lambda/cuda_versions.txt
  python/ray/data/tests/test_ecosystem.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/serve/BUILD
  python/ray/tests/ml_py37_compat/BUILD
  python/ray/tests/ml_py37_compat/tune_hvd_keras.py
  python/ray/tests/ml_py37_compat/tune_hvd_torch.py
  python/ray/tests/test_cli.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  python/ray/tests/test_cli_patterns/test_ray_up.txt
  python/ray/tests/test_cli_patterns/test_ray_up_docker.txt
  python/ray/tests/test_cli_patterns/test_ray_up_record.txt
  python/ray/tune/BUILD
  python/ray/tune/tests/execution/test_controller_control_integration.py
  python/ray/tune/tests/execution/test_controller_resources_integration.py
  python/ray/tune/tests/test_client.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_convergence.py
  python/ray/tune/tests/test_ray_trial_executor.py
  python/ray/tune/tests/test_sample.py
  python/ray/tune/tests/test_searchers.py
  python/ray/tune/tests/test_trial_runner.py
  python/ray/tune/tests/test_trial_runner_2.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_tune_restore.py
  python/ray/tune/tests/test_tune_restore_warm_start.py
  python/requirements/compat/requirements_py37_compat.txt
  python/requirements/data_processing/requirements.txt
  python/requirements/ml/requirements_rllib.txt
  python/requirements/ml/requirements_train.txt
  python/requirements/ml/requirements_tune.txt
  python/requirements/ml/requirements_upstream.txt
  python/requirements_test.txt
  rllib/examples/bandit/tune_lin_ucb_train_recommendation.py
  rllib/examples/bandit/tune_lin_ucb_train_recsim_env.py
Labels: tests-ok

#36401 [Templates] Unify the batch inference template with an existing Data example
  doc/source/data/examples/index.rst
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/ray-overview/examples.rst
  doc/source/templates/01_batch_inference/README.md
  doc/source/templates/01_batch_inference/start.ipynb
Labels: tests-ok

#36475 Add "all" option for SessionName (#35408)
  dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  dashboard/modules/metrics/dashboards/default_grafana_dashboard_base.json
  python/ray/tests/test_metrics_head.py
Labels: v2.5.1-pick

#36482 [autoscaler] fix too many values to unpack (expected 2) bug (#36231)
  python/ray/autoscaler/_private/monitor.py
Labels: v2.5.0-pick

#36481 Add "all" option for SessionName (#35408)
  dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  dashboard/modules/metrics/dashboards/default_grafana_dashboard_base.json
  python/ray/tests/test_metrics_head.py
Labels: v2.5.0-pick

#36360 [release/air] Fix release test timeout for `tune_scalability_network_overhead`
  python/ray/tune/utils/release_test_util.py
  release/release_tests.yaml
  release/tune_tests/scalability_tests/tpl_100x2.yaml
  release/tune_tests/scalability_tests/tpl_20x2.yaml
  release/tune_tests/scalability_tests/tpl_gce_100x2.yaml
  release/tune_tests/scalability_tests/workloads/test_network_overhead.py
Labels: tests-ok

#36165 [Train] LightningTrainer support DeepSpeedStrategy
  python/ray/train/BUILD
  python/ray/train/data_parallel_trainer.py
  python/ray/train/lightning/_lightning_utils.py
  python/ray/train/lightning/lightning_trainer.py
  python/ray/train/tests/lightning_test_utils.py
  python/ray/train/tests/test_lightning_deepspeed.py
  python/ray/train/tests/test_lightning_trainer.py
Labels: tests-ok, train

#36242 [Data] Implement Operators for `union()`
  python/ray/data/_internal/execution/bulk_executor.py
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/base_physical_operator.py
  python/ray/data/_internal/execution/operators/limit_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/execution/operators/union_operator.py
  python/ray/data/_internal/execution/operators/zip_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/_internal/logical/operators/n_ary_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/_internal/planner/plan_limit_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_randomize_block_order.py
  python/ray/data/tests/test_streaming_executor.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok

#36276 [release/air] Fix `air_example_gptj_deepspeed_fine_tuning.gce` failing to pull model from a public s3 bucket
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  python/ray/train/huggingface/transformers/_transformers_utils.py
  release/release_tests.yaml
Labels: tests-ok, release-test

#36069 [Streaming Generator] Handle out of order report when retry
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_streaming_generator.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_manager.cc
  src/ray/protobuf/core_worker.proto
Labels: @author-action-required

#36556 [RLlib] Enable eager_tracing=True by default.
  release/rllib_tests/checkpointing_tests/test_e2e_rl_module_restore.py
  rllib/algorithms/a2c/tests/test_a2c.py
  rllib/algorithms/a3c/tests/test_a3c.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/alpha_star/tests/test_alpha_star.py
  rllib/algorithms/apex_ddpg/tests/test_apex_ddpg.py
  rllib/algorithms/apex_dqn/tests/test_apex_dqn.py
  rllib/algorithms/appo/tests/test_appo.py
  rllib/algorithms/appo/tests/test_appo_learner.py
  rllib/algorithms/appo/tests/test_appo_off_policyness.py
  rllib/algorithms/bandit/tests/test_bandits.py
  rllib/algorithms/cql/tests/test_cql.py
  rllib/algorithms/ddpg/tests/test_ddpg.py
  rllib/algorithms/dqn/tests/test_dqn.py
  rllib/algorithms/impala/tests/test_impala.py
  rllib/algorithms/impala/tests/test_impala_off_policyness.py
  rllib/algorithms/pg/tests/test_pg.py
  rllib/algorithms/ppo/tests/test_ppo.py
  rllib/algorithms/ppo/tests/test_ppo_learner.py
  rllib/algorithms/ppo/tests/test_ppo_with_rl_module.py
  rllib/algorithms/r2d2/tests/test_r2d2.py
  rllib/algorithms/sac/tests/test_sac.py
  rllib/algorithms/simple_q/tests/test_simple_q.py
  rllib/algorithms/slateq/tests/test_slateq.py
  rllib/algorithms/td3/tests/test_td3.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group_config.py
  rllib/core/learner/tests/test_learner.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/core/testing/utils.py
  rllib/examples/action_masking.py
  rllib/examples/bandit/lin_ts_train_wheel_env.py
  rllib/examples/bandit/tune_lin_ts_train_wheel_env.py
  rllib/examples/bandit/tune_lin_ucb_train_recommendation.py
  rllib/examples/bandit/tune_lin_ucb_train_recsim_env.py
  rllib/examples/checkpoint_by_custom_criteria.py
  rllib/examples/custom_logger.py
  rllib/examples/eager_execution.py
  rllib/examples/inference_and_serving/policy_inference_after_training.py
  rllib/examples/inference_and_serving/policy_inference_after_training_with_attention.py
  rllib/examples/inference_and_serving/policy_inference_after_training_with_lstm.py
  rllib/examples/learner/ppo_tuner.py
  rllib/examples/multi_agent_different_spaces_for_agents.py
  rllib/examples/parallel_evaluation_and_training.py
  rllib/examples/vizdoom_with_attention_net.py
  rllib/policy/tests/test_policy_map.py
  rllib/policy/tests/test_policy_state_swapping.py
  rllib/tests/backward_compat/checkpoints/create_checkpoints.py
  rllib/tests/backward_compat/test_backward_compat.py
  rllib/tests/run_regression_tests.py
  rllib/tests/test_algorithm_rl_module_restore.py
  rllib/train.py
  rllib/tuned_examples/ppo/cartpole-truncated-ppo.py
  rllib/tuned_examples/ppo/multi_agent_pendulum_ppo.py
  rllib/utils/test_utils.py
  rllib/utils/tests/run_memory_leak_tests.py
  rllib_contrib/a3c/tests/test_a3c.py
Labels: tests-ok

#35618 [Data] Test Data notebook examples
  doc/source/data/examples/BUILD
Labels: tests-ok

#35557 [Tune] Remove `tune/automl`
  doc/source/tune/examples/includes/genetic_example.rst
  python/ray/tune/BUILD
  python/ray/tune/automl/__init__.py
  python/ray/tune/automl/board/README.md
  python/ray/tune/automl/board/__init__.py
  python/ray/tune/automl/board/backend/__init__.py
  python/ray/tune/automl/board/backend/collector.py
  python/ray/tune/automl/board/common/__init__.py
  python/ray/tune/automl/board/common/exception.py
  python/ray/tune/automl/board/common/utils.py
  python/ray/tune/automl/board/frontend/__init__.py
  python/ray/tune/automl/board/frontend/query.py
  python/ray/tune/automl/board/frontend/urls.py
  python/ray/tune/automl/board/frontend/view.py
  python/ray/tune/automl/board/frontend/wsgi.py
  python/ray/tune/automl/board/manage.py
  python/ray/tune/automl/board/models/__init__.py
  python/ray/tune/automl/board/models/apps.py
  python/ray/tune/automl/board/models/models.py
  python/ray/tune/automl/board/run.py
  python/ray/tune/automl/board/settings.py
  python/ray/tune/automl/board/static/css/App.css
  python/ray/tune/automl/board/static/css/ExperimentList.css
  python/ray/tune/automl/board/static/css/ExperimentView.css
  python/ray/tune/automl/board/static/css/HomePage.css
  python/ray/tune/automl/board/static/css/bootstrap.min.css
  python/ray/tune/automl/board/static/css/index.css
  python/ray/tune/automl/board/static/js/ExperimentList.js
  python/ray/tune/automl/board/templates/index.html
  python/ray/tune/automl/board/templates/job.html
  python/ray/tune/automl/board/templates/trial.html
  python/ray/tune/automl/genetic_searcher.py
  python/ray/tune/automl/search_policy.py
  python/ray/tune/automl/search_space.py
  python/ray/tune/examples/genetic_example.py
  python/ray/tune/tests/test_automl_searcher.py
  python/ray/tune/tests/test_legacy_import.py
Labels: tests-ok

#36562 [release/air] Fix `air_example_gptj_deepspeed_fine_tuning.gce` failing...
  doc/source/ray-air/examples/gptj_deepspeed_fine_tuning.ipynb
  release/release_tests.yaml
Labels: v2.5.1-pick

#36477 [Data] Remove simple blocks
  python/ray/data/_internal/delegating_block_builder.py
  python/ray/data/_internal/fast_repartition.py
  python/ray/data/_internal/planner/exchange/split_repartition_task_scheduler.py
  python/ray/data/_internal/simple_block.py
  python/ray/data/block.py
  python/ray/data/tests/test_size_estimation.py
Labels: tests-ok

#36432 [Data][Docs] Standardize `from_items` API ref
  python/ray/data/read_api.py
Labels: tests-ok

#35188 [Core] Add is_running_tasks bit in JobStatus
  dashboard/BUILD
  dashboard/modules/job/tests/test_job_manager.py
  dashboard/modules/job/utils.py
  python/ray/_private/state.py
  python/ray/_private/worker.py
  src/mock/ray/core_worker/core_worker.h
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/node_manager.cc
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: @author-action-required

#36380 [ci][byod] migrate all serve tests to byod
  release/BUILD
  release/ray_release/byod/build.py
  release/ray_release/byod/byod.Dockerfile
  release/ray_release/byod/requirements_byod.in
  release/ray_release/byod/requirements_ml_byod.in
  release/ray_release/byod/requirements_ml_byod.txt
  release/ray_release/cluster_manager/cluster_manager.py
  release/ray_release/tests/test_cluster_manager.py
  release/release_tests.yaml
Labels: tests-ok

#36629 [ci][test] add unstable-release-test tag to github test failure issue
  release/ray_release/test.py
  release/ray_release/test_automation/state_machine.py
  release/ray_release/tests/test_state_machine.py
  release/ray_release/tests/test_test.py
Labels: tests-ok

#36434 [ci][byod/ml][2] migrate the rest of ml tests to byod
  release/ray_release/byod/build.py
  release/ray_release/byod/byod_horovod_master_test.sh
  release/ray_release/byod/byod_horovod_test.sh
  release/ray_release/byod/byod_ray_lightning_master_test.sh
  release/ray_release/byod/byod_ray_lightning_test.sh
  release/ray_release/byod/byod_rllib_test.sh
  release/ray_release/byod/byod_xgboost_master_test.sh
  release/ray_release/byod/byod_xgboost_test.sh
  release/ray_release/byod/byod_xgboost_tune_test.sh
  release/ray_release/byod/requirements_byod.in
  release/ray_release/byod/requirements_byod.txt
  release/ray_release/byod/requirements_debian_byod.txt
  release/ray_release/byod/requirements_ml_byod.in
  release/ray_release/byod/requirements_ml_byod.txt
  release/release_tests.yaml
Labels: tests-ok

#36560 [ci][byod] migrate many rllib tests to byod
  release/ray_release/byod/byod_rllib_test.sh
  release/release_tests.yaml
Labels: tests-ok

#36657 [ci][test] Add team name as a tag in github test failure issue
  release/ray_release/test.py
  release/ray_release/test_automation/state_machine.py
  release/ray_release/tests/test_state_machine.py
  release/ray_release/tests/test_test.py
Labels: tests-ok

#36229 [docker] Publish installed packages in docker containers (#35390)
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: v2.5.1-pick

#36609 [Dependencies] Remove `urllib3` dependency
  python/ray/autoscaler/_private/autoscaler.py
  python/requirements.txt
  python/setup.py
Labels: tests-ok

#36294 [Data] Enable execution plan optimizer for supported Ray Data APIs
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/pipeline_executor.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok, data, Ray 2.6

#36750 [ci] unmark documentation test as soft fail
  .buildkite/pipeline.build.yml
Labels: tests-ok

#35883 [Ray Core] Issue#35880 Fix the Exception error message bug which convert byte array to String
  java/runtime/src/main/java/io/ray/runtime/task/ArgumentsBuilder.java
Labels: testing

#36534 [RLlib][Torch 2.0 compile] Inference benchmarks
  .buildkite/pipeline.ml.yml
  rllib/BUILD
  rllib/benchmarks/torch_compile/README.md
  rllib/benchmarks/torch_compile/run_all_inference_bms.sh
  rllib/benchmarks/torch_compile/run_inference_bm.py
  rllib/benchmarks/torch_compile/run_ppo_with_inference_bm.py
  rllib/benchmarks/torch_compile/utils.py
Labels: tests-ok

#36687 [release/air] Fix numba/numpy incompatibility for `workspace_template_many_model_training` release test
  doc/source/templates/testing/cluster_envs/02_many_model_training.yaml
Labels: tests-ok

#36549 [ci] remove bazel_version subcommand in setup.py __api__
  WORKSPACE
  ci/env/install-dependencies.sh
  python/setup.py
Labels: tests-ok

#36708 [ci][fix] fix a few data tests that require horovod
  release/ray_release/byod/byod_data_pipelined_test.sh
  release/release_tests.yaml
Labels: tests-ok

#36730 [ci] Fix rllib_learning_tests_ddpg_tf
  release/release_tests.yaml
Labels: tests-ok

#36614 [ci] deprecated jail field in release test definition
  release/ray_release/buildkite/filter.py
  release/ray_release/buildkite/step.py
  release/ray_release/schema.json
  release/ray_release/tests/test_buildkite.py
  release/release_tests.yaml
Labels: tests-ok

#36686 [Data] Enforce strict mode batch format for `DataIterator.iter_batches()`
  python/ray/air/tests/test_legacy_dataset_config.py
  python/ray/air/tests/test_new_dataset_config.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_streaming_integration.py
Labels: tests-ok

#36705 Revert "Revert "[train] TransformersPredictor: Add support for custom pipeline class""
  python/ray/train/huggingface/transformers/transformers_predictor.py
  python/ray/train/tests/test_transformers_predictor.py
  python/ray/tune/examples/tune_mnist_keras.py
Labels: tests-ok

#36615 [ci] add a flag to not run unstable release tests
  release/ray_release/buildkite/filter.py
  release/ray_release/scripts/build_pipeline.py
Labels: tests-ok

#36672 [ci][byod] support python 3.9
  release/BUILD
  release/ray_release/byod/build.py
  release/ray_release/byod/requirements_byod_3.8.in
  release/ray_release/byod/requirements_byod_3.8.txt
  release/ray_release/byod/requirements_byod_3.9.in
  release/ray_release/byod/requirements_byod_3.9.txt
  release/ray_release/byod/requirements_ml_byod_3.8.in
  release/ray_release/byod/requirements_ml_byod_3.8.txt
  release/ray_release/byod/requirements_ml_byod_3.9.in
  release/ray_release/byod/requirements_ml_byod_3.9.txt
  release/ray_release/schema.json
  release/ray_release/test.py
  release/ray_release/tests/test_test.py
  release/release_tests.yaml
Labels: tests-ok

#36748 [data] Re-merge splitblocks
  doc/source/data/getting-started.rst
  doc/source/data/key-concepts.rst
  doc/source/data/performance-tips.rst
  doc/source/data/transforming-data.rst
  python/ray/air/tests/test_legacy_dataset_config.py
  python/ray/data/BUILD
  python/ray/data/_internal/block_list.py
  python/ray/data/_internal/execution/operators/input_data_buffer.py
  python/ray/data/_internal/lazy_block_list.py
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/planner/plan_read_op.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_auto_parallelism.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_mongo.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_randomize_block_order.py
  python/ray/data/tests/test_size_estimation.py
  python/ray/data/tests/test_splitblocks.py
  python/ray/train/tests/test_batch_predictor.py
  python/ray/tune/tests/test_tuner.py
Labels: Ray 2.6

#36648 [ci] add grouping for test jobs.
  .buildkite/pipeline.arm64.yml
  .buildkite/pipeline.gpu.yml
  .buildkite/pipeline.gpu_large.yml
  .buildkite/pipeline.macos.yml
  .buildkite/pipeline.ml.yml
Labels: tests-ok

#36484 [AIR] [Data] Add case for `Dict[str, np.array]` batches in `DummyTrainer` read bytes calculation
  python/ray/air/util/check_ingest.py
Labels: tests-ok

#36395 [Doc] Add Distributed Testing Example for `pl.Trainer.test()`
  doc/source/train/examples/lightning/lightning_mnist_example.ipynb
Labels: tests-ok

#36796 [ci] build wheels in quiet mode
  python/build-wheel-manylinux2014.sh
Labels: tests-ok

#36729 [ci] cleanup install-bazel.sh
  ci/ci.sh
  ci/env/install-bazel.sh
Labels: tests-ok

#36770 [dashboard] fix dashboard conftest visibility issue
  python/ray/tests/BUILD
Labels: tests-ok, Devprod

#36793 [ci] add shallow_since in rules_perl
  bazel/ray_deps_setup.bzl
Labels: tests-ok

#36834 [ci] rerun byod requirements update
  release/ray_release/byod/requirements_byod_3.8.in
  release/ray_release/byod/requirements_byod_3.8.txt
  release/ray_release/byod/requirements_ml_byod_3.8.txt
Labels: tests-ok

#36841 [ci] splitting pipeline.build.yml into parts
  .buildkite/pipeline.arm64.yml
  .buildkite/pipeline.build.yml
  .buildkite/pipeline.build_cpp.yml
  .buildkite/pipeline.build_py37.yml
  .buildkite/pipeline.build_redis.yml
  .buildkite/pipeline.build_release.yml
Labels: tests-ok

#36766 [core] Fix issues with worker churn in WorkerPool
  python/ray/tests/test_metrics.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_worker_capping.py
  src/ray/common/ray_config_def.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: @author-action-required, Ray 2.6

#36740 [Data] Support partial execution in `Dataset.schema()` with new execution plan optimizer
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok, data, Ray 2.6

#36788 [java] fix compile warnings
  java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java
  java/runtime/src/main/java/io/ray/runtime/utils/parallelactor/ParallelActorExecutorImpl.java
Labels: tests-ok

#36892 [ci] Add region name for boto3 erc client
  release/ray_release/byod/build.py
Labels: tests-ok

#36722 [data] Use default scheduling strategy to fix failing dataset_shuffle_push_based_sort_1tb test
  python/ray/data/_internal/remote_fn.py
Labels: @author-action-required

#36900 [air/deprecations] Deprecate some redundant syncing related parameters
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/execution/ray_trial_executor.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/tests/test_trainable.py
  python/ray/tune/tests/test_trial_runner_pg.py
  python/ray/tune/trainable/trainable.py
  python/ray/tune/tune.py
Labels: tests-ok

#36899 [air/deprecations] Deprecate initializing exp tracking integrations with a special key in the config
  python/ray/air/integrations/mlflow.py
  python/ray/air/integrations/wandb.py
  python/ray/air/tests/test_integration_mlflow.py
  python/ray/tune/integration/comet.py
Labels: tests-ok

#36439 [Data][Docs] Consolidate Data user guides
  doc/source/_toc.yml
  doc/source/data/data-internals.rst
  doc/source/data/data.rst
  doc/source/data/faq.rst
  doc/source/data/getting-started.rst
  doc/source/data/key-concepts.rst
  doc/source/data/loading-data.rst
  doc/source/data/overview.rst
  doc/source/data/performance-tips.rst
  doc/source/data/user-guide.rst
  doc/source/ray-core/key-concepts.rst
  doc/source/tune/tutorials/tune_get_data_in_and_out.md
  python/ray/data/dataset.py
Labels: tests-ok

#36907 [docker] drop python minor version
  docker/ray-ml/Dockerfile
Labels: tests-ok

#36840 [RLlib] RLlib deprecation Notices Part 2 (models/tf, models/torch, base_mode, catalog, modelv2, models/temp_spec_classes, policy/)
  rllib/algorithms/callbacks.py
  rllib/models/base_model.py
  rllib/models/catalog.py
  rllib/models/tf/attention_net.py
  rllib/models/tf/complex_input_net.py
  rllib/models/tf/fcnet.py
  rllib/models/tf/layers/gru_gate.py
  rllib/models/tf/layers/multi_head_attention.py
  rllib/models/tf/layers/noisy_layer.py
  rllib/models/tf/layers/relative_multi_head_attention.py
  rllib/models/tf/layers/skip_connection.py
  rllib/models/tf/misc.py
  rllib/models/tf/noop.py
  rllib/models/tf/primitives.py
  rllib/models/tf/recurrent_net.py
  rllib/models/tf/tf_action_dist.py
  rllib/models/tf/tf_distributions.py
  rllib/models/tf/tf_modelv2.py
  rllib/models/tf/visionnet.py
  rllib/models/torch/attention_net.py
  rllib/models/torch/complex_input_net.py
  rllib/models/torch/fcnet.py
  rllib/models/torch/mingpt.py
  rllib/models/torch/model.py
  rllib/models/torch/noop.py
  rllib/models/torch/primitives.py
  rllib/models/torch/recurrent_net.py
  rllib/models/torch/torch_action_dist.py
  rllib/models/torch/torch_modelv2.py
  rllib/models/torch/visionnet.py
  rllib/models/utils.py
  rllib/policy/dynamic_tf_policy.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/policy_template.py
  rllib/policy/tf_mixins.py
  rllib/policy/tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_mixins.py
  rllib/policy/torch_policy.py
  rllib/utils/exploration/curiosity.py
  rllib/utils/exploration/epsilon_greedy.py
  rllib/utils/exploration/exploration.py
  rllib/utils/exploration/gaussian_noise.py
  rllib/utils/exploration/ornstein_uhlenbeck_noise.py
  rllib/utils/exploration/parameter_noise.py
  rllib/utils/exploration/per_worker_epsilon_greedy.py
  rllib/utils/exploration/per_worker_gaussian_noise.py
  rllib/utils/exploration/per_worker_ornstein_uhlenbeck_noise.py
  rllib/utils/exploration/random.py
  rllib/utils/exploration/random_encoder.py
  rllib/utils/exploration/slate_epsilon_greedy.py
  rllib/utils/exploration/slate_soft_q.py
  rllib/utils/exploration/soft_q.py
  rllib/utils/exploration/stochastic_sampling.py
  rllib/utils/exploration/thompson_sampling.py
  rllib/utils/exploration/upper_confidence_bound.py
Labels: tests-ok

#36984 [tune] Remove hard-deprecated modules from structure refactor
  python/ray/tune/BUILD
  python/ray/tune/_structure_refactor.py
  python/ray/tune/checkpoint_manager.py
  python/ray/tune/cluster_info.py
  python/ray/tune/config_parser.py
  python/ray/tune/function_runner.py
  python/ray/tune/insufficient_resources_manager.py
  python/ray/tune/ray_trial_executor.py
  python/ray/tune/sample.py
  python/ray/tune/session.py
  python/ray/tune/suggest/__init__.py
  python/ray/tune/suggest/ax.py
  python/ray/tune/suggest/basic_variant.py
  python/ray/tune/suggest/bayesopt.py
  python/ray/tune/suggest/bohb.py
  python/ray/tune/suggest/dragonfly.py
  python/ray/tune/suggest/flaml.py
  python/ray/tune/suggest/hebo.py
  python/ray/tune/suggest/hyperopt.py
  python/ray/tune/suggest/nevergrad.py
  python/ray/tune/suggest/optuna.py
  python/ray/tune/suggest/search.py
  python/ray/tune/suggest/search_generator.py
  python/ray/tune/suggest/sigopt.py
  python/ray/tune/suggest/skopt.py
  python/ray/tune/suggest/suggestion.py
  python/ray/tune/suggest/util.py
  python/ray/tune/suggest/variant_generator.py
  python/ray/tune/suggest/zoopt.py
  python/ray/tune/tests/test_legacy_import.py
  python/ray/tune/trial.py
  python/ray/tune/trial_runner.py
  python/ray/tune/utils/placement_groups.py
  python/ray/tune/utils/trainable.py
Labels: tests-ok

#36973 [core] Add extra metrics for workers
  python/ray/tests/test_metrics.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/object_manager/plasma/store.h
  src/ray/object_manager/plasma/store_runner.h
  src/ray/protobuf/common.proto
Labels: release-blocker

#36951 [tune] Fix bug in execution for actor re-use
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/tests/execution/test_actor_caching.py
  python/ray/tune/tests/execution/utils.py
  python/ray/tune/tune.py
Labels: tests-ok

#35857 [core] Graceful shutdown in TaskEventBuffer destructor
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/task_event_buffer_test.cc
Labels: tests-ok

#36930 [ci][champagne/1] script to build anyscale BYOD champagne image
  release/ray_release/byod/build.py
  release/ray_release/scripts/ray_champagne.py
  release/ray_release/tests/test_byod_build.py
Labels: tests-ok

#36946 [ci] rename reference to builckite-ci-pipeline to rayci
  .github/workflows/external-code-affected.yml
Labels: tests-ok

#36782 [Doc] Update examples page
  doc/Makefile
  doc/source/_static/css/custom.css
  doc/source/_static/css/examples.css
  doc/source/_static/js/tags.js
  doc/source/_static/js/top-navigation.js
  doc/source/ray-overview/examples.rst
Labels: docs
