Repository ray-project/ray, pull requests merged in 2023-01, with the labels that each got.

#31331 [RLlib] Fix tensorflow probability imports
  rllib/algorithms/bandit/bandit_tf_model.py
  rllib/core/optim/tests/test_rl_optimizer_tf.py
  rllib/core/rl_module/tf/tests/test_tf_rl_module.py
  rllib/core/testing/tf/bc_module.py
  rllib/core/testing/tf/bc_optimizer.py
  rllib/models/specs/tests/test_tensor_spec.py
  rllib/utils/framework.py
  rllib/utils/tf_utils.py
Labels: tests-ok

#31267 Added Dict/Tuple space support in '_check_view_requirement()'.
  rllib/evaluation/collectors/agent_collector.py
Labels: tests-ok

#31376 [Core] Fixing RAY_PDB bug and adding unit test
  python/ray/_raylet.pyx
  python/ray/serve/_private/replica.py
  python/ray/tests/test_ray_debugger.py
  python/ray/util/rpdb.py
Labels: core

#31346 [ci][nightly][core] Fix stress_test_state_api_scale
  python/ray/_private/state_api_test_utils.py
  release/nightly_tests/stress_tests/test_state_api_scale.py
Labels: tests-ok

#31339 [ci][core] Remove cython version pin in release tests
  release/nightly_tests/stress_tests/state_api_app_config.yaml
  release/nightly_tests/stress_tests/stress_tests_app_config.yaml
Labels: tests-ok

#31230 [core] add option for raylet to inform whether a task should be retried
  src/mock/ray/core_worker/task_manager.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/direct_task_transport_mock_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/worker_killing_policy.cc
  src/ray/raylet/worker_killing_policy.h
  src/ray/raylet/worker_killing_policy_test.cc
Labels: tests-ok

#31181 [RLlib] Test models create for TorchPPORLModule
  rllib/BUILD
  rllib/algorithms/ppo/tests/test_ppo_rl_module.py
  rllib/algorithms/ppo/torch/ppo_torch_rl_module.py
  rllib/core/rl_module/encoder.py
Labels: tests-ok

#30844 [Docs] Update contribution guide to mention when to use REP
  doc/source/ray-contribute/getting-involved.rst
Labels: docs

#31294 [Core] Warn when --temp-dir is given on a worker node `ray start`
  python/ray/scripts/scripts.py
  python/ray/tests/test_cli.py
Labels: @author-action-required

#31391 [RLlib] Clean up deprecated concat_samples calls
  rllib/evaluation/sampler.py
  rllib/execution/buffers/mixin_replay_buffer.py
  rllib/policy/sample_batch.py
  rllib/policy/tests/test_sample_batch.py
  rllib/utils/replay_buffers/multi_agent_mixin_replay_buffer.py
  rllib/utils/replay_buffers/replay_buffer.py
Labels: tests-ok

#31195 [Core][runtime-context] Warn user when deprecated API is used
  python/ray/_private/worker.py
  python/ray/runtime_context.py
  python/ray/tests/BUILD
  python/ray/tests/test_actor_group.py
  python/ray/tests/test_annotations.py
  python/ray/tests/test_runtime_context.py
  python/ray/util/actor_group.py
  python/ray/util/annotations.py
Labels: tests-ok

#31509 [core] allow infinite oom retry
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  src/ray/common/ray_config_def.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/util/exponential_backoff.cc
  src/ray/util/exponential_backoff.h
  src/ray/util/exponential_backoff_test.cc
Labels: tests-ok

#31539 [ci][perf][core] ray.wait & ray.get ownership check improvement
  python/ray/_private/ray_perf.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
Labels: @author-action-required

#31528 [CoreWorker][deprecate run_function_on_all_workers 2/n] announcing deprecation of run_function_on_all_workers
  python/ray/_private/worker.py
Labels: @author-action-required

#31425 [Data] Refactor block batching to follow iterator pattern
  python/ray/data/_internal/batcher.py
  python/ray/data/_internal/block_batching.py
  python/ray/data/dataset.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/grouped_dataset.py
  python/ray/data/tests/test_block_batching.py
Labels: tests-ok

#31481 [core][state] Ignore tasks w/o status updates (driver generated tasks) by default from GCS
  dashboard/state_aggregator.py
  python/ray/experimental/state/state_manager.py
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/protobuf/gcs_service.proto
Labels: @author-action-required

#31570 [core][state] Add task_parent_id to TaskState
  dashboard/state_aggregator.py
  python/ray/experimental/state/common.py
  python/ray/tests/test_state_api.py
Labels: tests-ok

#31523 [Fail on pytest warnings 1/n] Marking strings with invalid escape sequences as raw strings
  pytest.ini
  python/ray/_private/runtime_env/context.py
  python/ray/air/util/tensor_extensions/pandas.py
  python/ray/data/grouped_dataset.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_placement_group.py
  release/serve_tests/workloads/deployment_graph_wide_ensemble.py
  release/serve_tests/workloads/serve_handle_wide_ensemble.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/mbmpo/mbmpo.py
  rllib/algorithms/r2d2/r2d2.py
Labels: core

#31603 [Core] [Pytest fail on warnings] Use default behavior in test annotations
  python/ray/tests/test_actor_group.py
  python/ray/tests/test_annotations.py
  python/ray/tests/test_runtime_context.py
Labels: core

#31604 [Dataset] Improve str/repr of `Dataset` to include execution plan
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#31375 [CoreWorker] lazy bind core_work's job_config through task spec.
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/abstract_ray_runtime.h
  cpp/src/ray/runtime/local_mode_ray_runtime.cc
  cpp/src/ray/runtime/local_mode_ray_runtime.h
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  java/runtime/src/main/java/io/ray/runtime/RayNativeRuntime.java
  java/test/src/main/java/io/ray/test/RayJavaLoggingTest.java
  java/test/src/main/java/io/ray/test/RuntimeContextTest.java
  python/ray/_private/gcs_utils.py
  python/ray/_private/workers/default_worker.py
  python/ray/_raylet.pyx
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_context_NativeWorkerContext.cc
  src/ray/core_worker/test/core_worker_test.cc
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/mock_worker.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
Labels: @author-action-required

#31470 [AIR] Introduce DatasetIterator for bulk and streaming ingest
  doc/source/data/api/api.rst
  doc/source/data/api/dataset.rst
  doc/source/data/api/dataset_iterator.rst
  doc/source/data/api/dataset_pipeline.rst
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/doc_code/air_ingest.py
  doc/source/ray-air/package-ref.rst
  doc/source/ray-core/_examples/datasets_train/datasets_train.py
  python/ray/air/_internal/util.py
  python/ray/air/config.py
  python/ray/air/session.py
  python/ray/air/tests/test_dataset_config.py
  python/ray/air/util/check_ingest.py
  python/ray/data/__init__.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/bulk_dataset_iterator.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/pipelined_dataset_iterator.py
  python/ray/data/_internal/table_block.py
  python/ray/data/_internal/torch_iterable_dataset.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/dataset_iterator.py
  python/ray/data/dataset_pipeline.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_dataset_iterator.py
  python/ray/train/_internal/dataset_spec.py
  python/ray/train/session.py
  release/nightly_tests/dataset/ray_sgd_runner.py
  release/nightly_tests/dataset/ray_sgd_training.py
Labels: @author-action-required

#31640 [Core] add client side health-check to detect network failures.
  python/ray/_private/utils.py
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  src/ray/common/grpc_util.h
  src/ray/common/ray_config_def.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/grpc_client.h
Labels: @author-action-required

#31632 [Core] Fix opencensus protobuf bug
  BUILD.bazel
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/metrics_agent.py
  python/ray/_private/test_utils.py
  python/ray/tests/test_memory_pressure.py
  python/ray/tests/test_metrics.py
  python/requirements_test.txt
  src/ray/protobuf/common.proto
  src/ray/protobuf/pubsub.proto
  src/ray/protobuf/reporter.proto
Labels: @author-action-required

#31524 [core][state] Task state fault tolerance - GCS marks children task failed if parent task fails. [1/x]
  python/ray/tests/test_task_events.py
  src/ray/core_worker/task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/gcs/pb_util.h
Labels: tests-ok

#31332 [RLlib] Replace ordinary pygame imports by try_imports
  rllib/algorithms/alpha_star/tests/test_alpha_star.py
  rllib/env/utils.py
  rllib/env/wrappers/open_spiel.py
  rllib/examples/connectors/self_play_with_policy_checkpoint.py
  rllib/examples/self_play_league_based_with_open_spiel.py
  rllib/examples/self_play_with_open_spiel.py
Labels: tests-ok

#31614 [core] Remove some legacy code for actor execution
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  java/runtime/src/main/java/io/ray/runtime/task/LocalModeTaskSubmitter.java
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/direct_actor_transport.cc
  src/ray/protobuf/common.proto
Labels: @author-action-required

#31649 [release][tune] [build_base] Fix `tune_scalability_durable_trainable` configuration to force experiment syncs less often
  release/tune_tests/scalability_tests/workloads/test_durable_trainable.py
Labels: tune, air, release-test

#31700 [core] Support dynamic generators for actor tasks
  doc/source/ray-core/tasks/generators.rst
  python/ray/actor.py
  python/ray/tests/test_generators.py
Labels: @author-action-required

#31045 [Tune] [Doc] Clarify `SyncConfig` docstring and checkpoint syncing user guide
  doc/source/_toc.yml
  doc/source/tune/api_docs/schedulers.rst
  doc/source/tune/faq.rst
  doc/source/tune/index.rst
  doc/source/tune/key-concepts.rst
  doc/source/tune/tutorials/overview.rst
  doc/source/tune/tutorials/tune-checkpoints.rst
  doc/source/tune/tutorials/tune-distributed.rst
  doc/source/tune/tutorials/tune-stopping.rst
  doc/source/tune/tutorials/tune-storage.rst
  doc/source/tune/tutorials/tune_get_data_in_and_out.md
  python/ray/tune/schedulers/resource_changing_scheduler.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_syncer.py
Labels: tune, air

#31711 [Dev] Add Vim sessions to gitignore
  .gitignore
Labels: @author-action-required

#31724 [Doc] Update the metrics doc to take into account of per method component memory/cpu usage.
  dashboard/modules/metrics/grafana_dashboard_factory.py
  doc/source/ray-observability/ray-metrics.rst
Labels: @author-action-required

#31695 [tiny] runtime env error message improvement
  python/ray/_private/runtime_env/packaging.py
Labels: tests-ok

#31706 [Datasets] Add support for callable classes to new execution backend.
  python/ray/data/__init__.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/tests/test_dataset.py
Labels: @author-action-required

#31715 [Datasets] Add support for dynamic block splitting to actor pool.
  python/ray/data/_internal/execution/operators/actor_pool_submitter.py
  python/ray/data/_internal/execution/operators/map_operator_state.py
  python/ray/data/_internal/execution/operators/map_task_submitter.py
  python/ray/data/_internal/execution/operators/task_pool_submitter.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_operators.py
Labels: @author-action-required

#31618 [RLlib] Introduce Connector Metrics
  rllib/connectors/action/pipeline.py
  rllib/connectors/agent/pipeline.py
  rllib/connectors/tests/test_action.py
  rllib/evaluation/env_runner_v2.py
  rllib/evaluation/metrics.py
  rllib/policy/policy.py
Labels: tests-ok

#31743 [RLlib] Reinstantiate Ape-X release test
  release/long_running_tests/workloads/apex.py
  rllib/BUILD
Labels: tests-ok

#31585 [AIR] Delegate BatchPredictor stage fusion to Datasets
  doc/source/ray-air/examples/pytorch_tabular_batch_prediction.py
  doc/source/ray-air/examples/tf_tabular_batch_prediction.py
  python/ray/train/batch_predictor.py
  python/ray/train/tests/test_batch_predictor.py
  release/BUILD
  release/air_tests/air_benchmarks/workloads/pytorch_training_e2e.py
Labels: tests-ok

#31733 [RLlib] Revert "Revert "[RLlib] Enable connectors. (#30388)" (#31495)"
  rllib/algorithms/algorithm_config.py
Labels: tests-ok

#31663 [Core] Imporve agent failure msg
  src/ray/raylet/agent_manager.cc
Labels: @author-action-required

#31772 [Core][Core-worker] add job_id in log file as source of truth
  python/ray/_private/log_monitor.py
  python/ray/_private/ray_constants.py
  python/ray/_raylet.pyx
  python/ray/tests/test_logging.py
Labels: @author-action-required

#31262 [RLlib] Trainer runner v1
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/core/rl_trainer/__init__.py
  rllib/core/rl_trainer/tests/test_trainer_runner_config.py
  rllib/core/rl_trainer/tf/tf_rl_trainer.py
  rllib/core/rl_trainer/trainer_runner.py
  rllib/core/rl_trainer/trainer_runner_config.py
  rllib/evaluation/worker_set.py
  rllib/utils/from_config.py
Labels: tests-ok

#31725 [AIR] Use specified `Preprocessor` configs when using stream API.
  python/ray/air/tests/test_dataset_config.py
  python/ray/data/preprocessor.py
  python/ray/data/preprocessors/chain.py
  python/ray/data/preprocessors/discretizer.py
  python/ray/data/tests/preprocessors/test_chain.py
  python/ray/data/tests/preprocessors/test_preprocessors.py
  python/ray/train/_internal/dataset_spec.py
  python/ray/train/batch_predictor.py
  python/ray/train/tests/test_batch_predictor.py
Labels: tests-ok

#31272 [core] oom killer policy: group by owner id
  BUILD.bazel
  src/ray/common/ray_config_def.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.h
  src/ray/raylet/worker_killing_policy.cc
  src/ray/raylet/worker_killing_policy.h
  src/ray/raylet/worker_killing_policy_group_by_owner.cc
  src/ray/raylet/worker_killing_policy_group_by_owner.h
  src/ray/raylet/worker_killing_policy_group_by_owner_test.cc
  src/ray/raylet/worker_killing_policy_test.cc
Labels: tests-ok

#31731 [Dataset] Add interface for optimizer and logical operator
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/input_data_buffer.py
  python/ray/data/_internal/logical/__init__.py
  python/ray/data/_internal/logical/interfaces.py
  python/ray/data/_internal/logical/operators/__init__.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/logical/planner.py
  python/ray/data/_internal/plan.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok

#30883 [Core] allow worker lazily bind to job_id
  doc/source/tune/examples/flaml_example.ipynb
  python/ray/_private/ray_logging.py
  python/ray/tests/test_advanced.py
  python/ray/tests/test_advanced_2.py
  python/ray/tests/test_basic_5.py
  python/ray/tests/test_failure.py
  python/ray/tests/test_failure_4.py
  python/ray/tests/test_global_state.py
  python/ray/tests/test_logging.py
  python/ray/tests/test_multi_tenancy.py
  python/ray/tests/test_output.py
  python/ray/tests/test_usage_stats.py
  python/ray/tune/tests/test_tune_restore_warm_start.py
  python/requirements/ml/requirements_tune.txt
  src/mock/ray/raylet/worker.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/stats/metric_defs.cc
Labels: tests-ok

#31836 [Core][Worker_Pool] Wait for prestarted-workers for the first job and disable run_on_all_workers flaky tests
  python/ray/tests/test_advanced.py
  python/ray/tests/test_failure_4.py
  src/ray/raylet/worker_pool.cc
Labels: @author-action-required

#31307 [docs] Update reference K8s configuration in large cluster deployment guide.
  doc/source/cluster/kubernetes/user-guides/config.md
  doc/source/cluster/vms/user-guides/large-cluster-best-practices.rst
Labels: stale

#30789 [Core][Enable gcs scheduler 7/n] Prefer actor owner's node
  release/nightly_tests/many_nodes_tests/multi_master_test.py
  release/release_tests.yaml
  src/ray/common/task/task.cc
  src/ray/common/task/task.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.h
  src/ray/raylet/scheduling/policy/scheduling_options.h
Labels: @author-action-required

#31845 [Core] Raise deprecation warning when passing non-iterables to imap and imap_unordered methods of ray.util.multiprocessing.Pool
  python/ray/tests/test_multiprocessing.py
  python/ray/util/multiprocessing/pool.py
Labels: core, Ray 2.3

#31873 [Core] temporary stop testing python grpcio prerelease package
  ci/env/install-core-prerelease-dependencies.sh
Labels: @author-action-required

#28310 [serve][docs] Document Gradio visualization
  doc/source/serve/doc_code/gradio_dag_visualize.py
  doc/source/serve/model_composition.md
  doc/source/serve/tutorials/gradio-dag-visualization.md
  doc/source/serve/tutorials/index.md
  python/ray/serve/scripts.py
Labels: tests-ok, serve, docs

#31669 [Tune] Enable experiment restore from moved cloud uri
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/execution/trial_runner.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_experiment_analysis.py
  python/ray/tune/tests/test_experiment_analysis_mem.py
  python/ray/tune/tests/test_trial_relative_logdir.py
  python/ray/tune/tests/test_trial_runner_3.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/tune.py
Labels: tune, air

#31847 [State API] Improve task api
  dashboard/state_aggregator.py
  python/ray/experimental/state/common.py
  python/ray/tests/test_exit_observability.py
  python/ray/tests/test_state_api.py
  src/mock/ray/core_worker/task_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/core_worker/transport/direct_task_transport.cc
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/raylet.cc
Labels: @author-action-required

#31863 [core] Migrate many_nodes_actor_tests to new cloud.
  release/nightly_tests/many_nodes_tests/actor_test.py
  release/nightly_tests/many_nodes_tests/compute_config.yaml
  release/ray_release/command_runner/command_runner.py
  release/ray_release/file_manager/job_file_manager.py
  release/release_tests.yaml
Labels: @author-action-required

#30460 [core][scalability] Change ray syncer from unary call to streaming call
  BUILD.bazel
  release/nightly_tests/many_nodes_tests/actor_test.py
  src/mock/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/id.cc
  src/ray/common/id.h
  src/ray/common/ray_config_def.h
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/test/ray_syncer_test.cc
  src/ray/common/test/syncer_service_e2e_test.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/protobuf/ray_syncer.proto
  src/ray/raylet/node_manager.cc
  src/ray/rpc/grpc_client.h
  src/ray/rpc/grpc_server.cc
Labels: @author-action-required

#31589 [Serve] Serve python API to support multi application
  java/serve/src/main/java/io/ray/serve/api/ServeControllerClient.java
  python/ray/serve/BUILD
  python/ray/serve/__init__.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/api.py
  python/ray/serve/controller.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_application_state.py
  python/ray/serve/tests/test_schema.py
  src/ray/protobuf/serve.proto
Labels: @author-action-required

#31958 [RLlib] AlgorithmConfig objects supported by all (internally used) `Algorithm.default_resource_request()` methods.
  rllib/algorithms/algorithm.py
  rllib/algorithms/alpha_star/alpha_star.py
  rllib/algorithms/apex_dqn/apex_dqn.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/mock.py
  rllib/examples/remote_envs_with_inference_done_on_main_node.py
Labels: tests-ok

#31917 [core] Fix gcs healthch manager crash when node is removed by node manager.
  .bazelrc
  BUILD.bazel
  src/ray/gcs/gcs_server/gcs_health_check_manager.cc
  src/ray/gcs/gcs_server/gcs_health_check_manager.h
  src/ray/gcs/gcs_server/test/gcs_health_check_manager_test.cc
Labels: @author-action-required

#31827 [1/n] Stabilize GCS/Autoscaler interface: Introduce monitor server
  BUILD.bazel
  python/ray/tests/BUILD
  python/ray/tests/test_monitor_service.py
  src/ray/gcs/gcs_server/gcs_monitor_server.cc
  src/ray/gcs/gcs_server/gcs_monitor_server.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_monitor_server_test.cc
  src/ray/protobuf/BUILD
  src/ray/protobuf/monitor.proto
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: tests-ok

#31837 [core][state] Task backend return most recently added tasks when getting all tasks
  python/ray/tests/test_state_api.py
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
Labels: tests-ok

#31935 [nightly] Update the many nodes actor workload to 1k nodes.
  release/benchmarks/distributed/many_nodes_tests/actor_test.py
  release/benchmarks/distributed/many_nodes_tests/app_config.yaml
  release/benchmarks/distributed/many_nodes_tests/compute_config.yaml
  release/benchmarks/distributed/many_nodes_tests/multi_master_test.py
  release/nightly_tests/many_nodes_tests/actor_test.py
  release/release_tests.yaml
Labels: @author-action-required

#31832 [core][state] Handle driver tasks
  dashboard/modules/state/state_head.py
  dashboard/state_aggregator.py
  python/ray/experimental/state/api.py
  python/ray/experimental/state/common.py
  python/ray/experimental/state/state_manager.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_task_events.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/protobuf/gcs_service.proto
Labels: tests-ok

#31986 [Datasets] [Autoscaling Actor Pool - 1/2] Refactor `MapOperator`, execution state, and task submitters.
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/actor_pool_submitter.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/map_operator_state.py
  python/ray/data/_internal/execution/operators/map_task_submitter.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/execution/operators/task_pool_submitter.py
  python/ray/data/_internal/execution/util.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_actor_pool_map_operator.py
  python/ray/data/tests/test_actor_pool_submitter.py
  python/ray/data/tests/test_bulk_executor.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_streaming_executor.py
Labels: @author-action-required

#32011 [Serve] Make `RandomKiller` restart in `long_running_serve_failure` test
  release/long_running_tests/workloads/serve_failure.py
Labels: tests-ok

#32014 [Ray release test infra] Change exponential_backoff_retry to use error instead of info on failure
  release/ray_release/util.py
Labels: release-test

#31856 [Dashboard] Timeline implemented by a new task backend
  dashboard/client/src/common/AlertDialog.tsx
  dashboard/client/src/components/TitleCard.tsx
  dashboard/client/src/pages/job/JobDetail.tsx
  dashboard/client/src/pages/job/TaskTimeline.tsx
  dashboard/client/src/service/task.ts
  dashboard/modules/state/state_head.py
  dashboard/state_aggregator.py
  python/ray/_private/profiling.py
  python/ray/experimental/shuffle.py
  python/ray/experimental/state/common.py
  python/ray/tests/BUILD
  python/ray/tests/test_state_api.py
  python/ray/tests/test_state_api_2.py
Labels: @author-action-required

#32002 [2/n] Stabilize GCS/Autoscaler interface: Drain and Kill Node API
  python/ray/tests/test_monitor_service.py
  src/mock/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_monitor_server.cc
  src/ray/gcs/gcs_server/gcs_monitor_server.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_monitor_server_test.cc
  src/ray/protobuf/monitor.proto
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: tests-ok

#31997 [core] Add generic `__ray_ready__` method to Actor classes
  python/ray/actor.py
  python/ray/tests/test_actor.py
Labels: core-interface-change-approval-required

#32063 [Serve] Mark `long_running_serve_failure` test as `stable`
  release/long_running_tests/workloads/serve_failure.py
  release/release_tests.yaml
Labels: tests-ok

#31949 [docs] deploying static ray cluster to K8S with external Redis for fault tolerance
  doc/source/_toc.yml
  doc/source/cluster/kubernetes/configs/static-ray-cluster-networkpolicy.yaml
  doc/source/cluster/kubernetes/configs/static-ray-cluster.with-fault-tolerance.yaml
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/static-ray-cluster-without-kuberay.md
Labels: tests-ok, @external-author-action-required

#32080 [Datasets] Add logical operator for random_shuffle()
  python/ray/data/_internal/logical/operators/all_to_all_operator.py
  python/ray/data/_internal/planner/exchange/__init__.py
  python/ray/data/_internal/planner/exchange/interfaces.py
  python/ray/data/_internal/planner/exchange/pull_based_shuffle_task_scheduler.py
  python/ray/data/_internal/planner/exchange/push_based_shuffle_task_scheduler.py
  python/ray/data/_internal/planner/exchange/shuffle_task_spec.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: tests-ok

#32101 [Datasets] Fix to pass TaskContext in generate_random_shuffle_fn()
  python/ray/data/_internal/execution/interfaces.py
  python/ray/data/_internal/execution/operators/all_to_all_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/planner/filter.py
  python/ray/data/_internal/planner/flat_map.py
  python/ray/data/_internal/planner/map_batches.py
  python/ray/data/_internal/planner/map_rows.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/_internal/planner/randomize_blocks.py
Labels: tests-ok

#32072 [Ray 2.3 release] Marking RLLib release tests as unstable if xfail
  release/release_tests.yaml
Labels: rllib

#32096 [Core] Expose Internal KV MultiGet operation
  src/mock/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/store_client_kv.cc
  src/ray/gcs/gcs_server/store_client_kv.h
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
  src/ray/gcs/store_client/store_client.h
Labels: tests-ok

#31739 [AIR] Add option for per-epoch preprocessor
  doc/source/ray-air/check-ingest.rst
  doc/source/ray-air/doc_code/air_ingest.py
  python/ray/air/config.py
  python/ray/air/tests/test_dataset_config.py
  python/ray/data/preprocessor.py
  python/ray/data/preprocessors/utils.py
  python/ray/train/_internal/dataset_spec.py
Labels: @author-action-required

#32085 [observability][autoscaler] Ensure pending nodes is reset to 0 after scaling
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/autoscaler/_private/node_launcher.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_autoscaler_e2e.py
Labels: @author-action-required
