Repository ray-project/ray, pull requests merged in 2024-01, with the labels that each got.

#42066 [RLlib] Structure and split up `AlgorithmConfig.validate()` method.
  rllib/algorithms/algorithm_config.py
Labels: tests-ok

#41825 [RLlib] Add callbacks support to SingleAgentEnvRunner.
  doc/source/rllib/rllib-advanced-api.rst
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/callbacks.py
  rllib/algorithms/tests/test_callbacks_old_stack.py
  rllib/algorithms/tests/test_callbacks_on_algorithm.py
  rllib/algorithms/tests/test_callbacks_on_env_runner.py
  rllib/env/single_agent_env_runner.py
Labels: tests-ok

#41998 [Docs] Theme revamp: primary sidebar
  .pre-commit-config.yaml
  doc/source/_static/css/custom.css
  doc/source/_static/css/examples.css
  doc/source/_static/css/splash.css
  doc/source/_templates/layout.html
  doc/source/_templates/release-header.html
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: P1, docs

#41814 [Data] Fix data test which unconditionally passes
  python/ray/data/tests/test_streaming_executor.py
Labels: testing, data

#42212 [Doc] Prevent line from wrapping for tag buttons in example gallery
  doc/source/_static/css/examples.css
Labels: P1, docs

#42127 [Doc] Update dask-on-ray table for 2.9.1
  doc/source/ray-more-libs/dask-on-ray.rst
Labels: release-blocker, v2.9.1-pick

#41009 [Doc] Add improved 'ray start --resources' help
  python/ray/scripts/scripts.py
Labels: P2, docs, core

#42216 [Serve][Doc] Fix pydantic config documentation
  doc/requirements-doc.txt
  doc/source/_templates/autosummary/class_with_inherited_members.rst
  doc/source/serve/api/index.md
Labels: v2.9.1-pick

#42241 [Cherrypick][Serve][Doc] Fix pydantic config documentation (#42216)
  doc/requirements-doc.txt
  doc/source/_templates/autosummary/class_with_inherited_members.rst
  doc/source/serve/api/index.md
Labels: v2.9.1-pick

#42234 [Cherrypick][Serve] Improve handling the websocket server disconnect scenario (#4…
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/test_proxy.py
Labels: release-blocker, v2.9.1-pick

#42268 [core][gcs] Fix task events profile events per task leak (#42248)
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
Labels: release-blocker, v2.9.1-pick

#42069 [Serve][Doc] Fix object detection code to use gpu device
  doc/source/serve/doc_code/object_detection.py
Labels: v2.9.1-pick

#41930 [Doc] Rename video examples to talk in example gallery
  doc/source/ray-overview/examples.rst
Labels: P1, docs

#41235 [RLlib] New ConnectorV2 API #04: Changes to Learner/LearnerGroup API to allow updating from Episodes.
  doc/source/rllib/package_ref/learner.rst
  doc/source/rllib/rllib-learner.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/appo/tests/test_appo_learner.py
  rllib/algorithms/bc/bc.py
  rllib/algorithms/dreamerv3/dreamerv3.py
  rllib/algorithms/dreamerv3/utils/summaries.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/tests/test_impala_learner.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/tests/test_ppo_learner.py
  rllib/algorithms/ppo/tests/test_ppo_with_rl_module.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group.py
  rllib/core/learner/tests/test_learner.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/utils/minibatch_utils.py
  rllib/utils/tests/test_minibatch_utils.py
Labels: tests-ok

#42243 [serve] remove GPT-J example
  ci/ray_ci/ml.tests.yml
  doc/source/data/examples/gptj_batch_prediction.ipynb
  doc/source/ray-air/examples/BUILD
  doc/source/ray-air/examples/gptj_serving.ipynb
  doc/source/ray-overview/examples.rst
  doc/source/splash.html
Labels: serve, docs

#42311 [Debugger] Adding debupgy as the ray debugger
  python/ray/util/__init__.py
  python/ray/util/debugpy.py
  python/ray/util/rpdb.py
Labels: v2.9.1-pick

#42296 [RLlib] New ConnectorV2 API #06: Changes in SingleAgentEpisode & SingleAgentEnvRunner.
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/ppo/tests/test_ppo_with_rl_module.py
  rllib/connectors/connector_v2.py
  rllib/connectors/env_to_module/default_env_to_module.py
  rllib/connectors/learner/default_learner_connector.py
  rllib/env/single_agent_env_runner.py
  rllib/env/single_agent_episode.py
  rllib/env/tests/test_lookback_buffer.py
  rllib/env/tests/test_single_agent_episode.py
  rllib/env/utils.py
  rllib/env/wrappers/atari_wrappers.py
  rllib/models/tf/tf_distributions.py
  rllib/models/torch/torch_distributions.py
  rllib/policy/rnn_sequencing.py
  rllib/utils/spaces/space_utils.py
Labels: rllib, rllib-newstack

#42372 [Release] Add 2.9.1 release logs
  release/release_logs/2.9.1/benchmarks/many_actors.json
  release/release_logs/2.9.1/benchmarks/many_nodes.json
  release/release_logs/2.9.1/benchmarks/many_tasks.json
  release/release_logs/2.9.1/microbenchmark.json
  release/release_logs/2.9.1/scalability/object_store.json
  release/release_logs/2.9.1/scalability/single_node.json
  release/release_logs/2.9.1/stress_tests/stress_test_dead_actors.json
  release/release_logs/2.9.1/stress_tests/stress_test_many_tasks.json
  release/release_logs/2.9.1/stress_tests/stress_test_placement_group.json
Labels: release-blocker, P0

#42231 [Doc] Theme revamp: styling changes
  doc/source/_static/css/custom.css
  doc/source/_static/css/index.css
  doc/source/_static/js/index.js
  doc/source/_static/js/splash.js
  doc/source/_templates/index.html
  doc/source/conf.py
  doc/source/custom_directives.py
  doc/source/index.rst
Labels: P1, docs

#42375 [ci][multipy/2] multipy version of core tests
  .buildkite/core.rayci.yml
  ci/ray_ci/tester.py
Labels: continuous-build

#42442 [ci][multipy/4] add python 3.8+3.11 test jobs for serve
  .buildkite/base.rayci.yml
  .buildkite/core.rayci.yml
  .buildkite/serve.rayci.yml
  ci/docker/serve.build.Dockerfile
  ci/docker/serve.build.py39.wanda.yaml
  ci/docker/serve.build.wanda.yaml
  ci/docker/servepython311.build.wanda.yaml
Labels: continuous-build

#42398 [ci][multipy/3] multipy version of data tests
  .buildkite/data.rayci.yml
  ci/docker/data.build.Dockerfile
  ci/docker/data.build.wanda.yaml
  ci/pipeline/determine_tests_to_run.py
Labels: continuous-build

#42448 [ci][multipy/4] multipy version of ml tests
  .buildkite/ml.rayci.yml
Labels: continuous-build

#42125 [docs] [train] splash page: change train_loop_per_worker to train_func and style edits
  doc/source/_templates/index.html
Labels: docs

#42272 [RLlib] New ConnectorV3 API #05: PPO runs in single-agent mode in this API stack
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/appo/tests/test_appo.py
  rllib/algorithms/appo/tf/appo_tf_learner.py
  rllib/algorithms/appo/torch/appo_torch_learner.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/algorithms/impala/tests/test_vtrace.py
  rllib/algorithms/impala/tests/test_vtrace_v2.py
  rllib/algorithms/impala/tf/impala_tf_learner.py
  rllib/algorithms/impala/tf/vtrace_tf_v2.py
  rllib/algorithms/impala/torch/impala_torch_learner.py
  rllib/algorithms/impala/torch/vtrace_torch_v2.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/ppo_learner.py
  rllib/algorithms/ppo/ppo_rl_module.py
  rllib/algorithms/ppo/tests/test_ppo.py
  rllib/algorithms/ppo/tests/test_ppo_with_rl_module.py
  rllib/algorithms/ppo/tf/ppo_tf_learner.py
  rllib/algorithms/ppo/tf/ppo_tf_rl_module.py
  rllib/algorithms/ppo/torch/ppo_torch_learner.py
  rllib/algorithms/ppo/torch/ppo_torch_rl_module.py
  rllib/core/learner/learner.py
  rllib/core/rl_module/marl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/evaluation/postprocessing_v2.py
  rllib/policy/sample_batch.py
  rllib/tests/test_supported_spaces.py
  rllib/tuned_examples/appo/cartpole-appo-fake-gpus.yaml
  rllib/tuned_examples/appo/cartpole-appo-separate-losses.py
  rllib/tuned_examples/appo/cartpole-appo-vtrace.yaml
  rllib/tuned_examples/appo/cartpole-appo-w-rl-modules-and-learner.yaml
  rllib/tuned_examples/appo/cartpole-appo.yaml
  rllib/tuned_examples/appo/stateless_cartpole_appo.py
  rllib/utils/minibatch_utils.py
  rllib/utils/postprocessing/__init__.py
  rllib/utils/postprocessing/episodes.py
  rllib/utils/postprocessing/tests/__init__.py
  rllib/utils/postprocessing/tests/test_value_predictions.py
  rllib/utils/postprocessing/value_predictions.py
  rllib/utils/postprocessing/zero_padding.py
Labels: rllib, rllib-newstack, rllib-oldstack-cleanup

#42518 [docs] [data] reformatting examples index page to standardize on format from Train
  .vale/styles/Vocab/Data/accept.txt
  doc/source/data/examples/index.rst
Labels: docs, data

#42519 Cherry-pick #41595
  doc/source/_static/css/custom.css
Labels: v2.9.1-pick

#42554 [docs] [serve] reformat page to standardize on Train format
  doc/source/ray-overview/examples.rst
  doc/source/serve/tutorials/aws-neuron-core-inference.md
  doc/source/serve/tutorials/batch.md
  doc/source/serve/tutorials/gradio-integration.md
  doc/source/serve/tutorials/index.md
  doc/source/serve/tutorials/java.md
  doc/source/serve/tutorials/object-detection.md
  doc/source/serve/tutorials/serve-ml-models.md
  doc/source/serve/tutorials/stable-diffusion.md
  doc/source/serve/tutorials/streaming.md
  doc/source/serve/tutorials/text-classification.md
Labels: serve, docs

#42710 [docs] [serve] remove note from batch and ml examples
  doc/source/serve/tutorials/batch.md
  doc/source/serve/tutorials/serve-ml-models.md
Labels: serve, docs

#42359 [Metrics] Add easy-install script for Prometheus
  dashboard/BUILD
  dashboard/consts.py
  dashboard/modules/metrics/install_and_start_prometheus.py
  dashboard/modules/metrics/metrics_head.py
  dashboard/modules/tests/test_metrics_integration.py
  doc/source/cluster/metrics.md
  python/ray/scripts/scripts.py
Labels: @author-action-required

#42705 [Serve] Fix race condition in `@serve.batch`
  python/ray/serve/batching.py
  python/ray/serve/tests/unit/test_batching.py
Labels: serve

#42601 [data][train] Fix deadlocks caused by streaming_split
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_streaming_integration.py
Labels: v2.9.2-pick

#42740 [Serve] Pin the fastapi & starlette version to avoid breaking proxy
  ci/docker/min.build.wanda.yaml
  python/ray/serve/_private/proxy.py
  python/requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  python/setup.py
Labels: v2.9.2-pick

#42755 [CP][data][train] Fix deadlocks caused by streaming_split
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_streaming_integration.py
Labels: v2.9.2-pick

#42722 [data][train] Fix locality config not being respected in DataConfig
  python/ray/air/tests/test_new_dataset_config.py
  python/ray/train/_internal/data_config.py
Labels: v2.9.2-pick

#42761 Cherry-pick #42027
  python/ray/data/_internal/planner/plan_read_op.py
  release/nightly_tests/dataset/multi_node_train_benchmark.py
Labels: v2.9.2-pick

#42798 [Doc] Add remix icon set
  doc/source/_templates/extrahead.html
Labels: P1, docs

#42574 [data] Warn on excessive driver memory usage during shuffle ops
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/data/_internal/planner/exchange/interfaces.py
  python/ray/data/_internal/planner/exchange/pull_based_shuffle_task_scheduler.py
  python/ray/data/_internal/planner/exchange/push_based_shuffle_task_scheduler.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/_internal/util.py
  python/ray/data/context.py
  python/ray/data/tests/test_sort.py
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
Labels: tests-ok

#42708 Fix `IS_PYDANTIC_2` logic for `pydantic<1.9.0`
  python/ray/_private/pydantic_compat.py
  python/ray/tests/test_minimal_install.py
Labels: v2.9.2-pick

#42774 Cherry-pick #42759
  python/ray/data/datasource/parquet_datasource.py
Labels: v2.9.2-pick

#42834 [2.9.2][Data] Skip recording memory spilled stats when get_memory_info_reply is failed
  python/ray/data/_internal/plan.py
Labels: tests-ok, v2.9.2-pick

#42508 [core] Critical Bug-fix: Fix ray memory metric calculation in CGroup V1 environment
  python/ray/_private/memory_monitor.py
  python/ray/_private/utils.py
  src/ray/common/memory_monitor.cc
  src/ray/common/memory_monitor.h
  src/ray/common/test/memory_monitor_test.cc
Labels: bug, P0, ray 2.10, v2.9.2-pick

#42874 [Cherry-pick][Serve] fix missing message body for json log formats (#42729)
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/tests/test_logging.py
Labels: v2.9.2-pick
