Repository ray-project/ray, pull requests merged in 2024-02, with the labels that each got.

#42818 [Doc] Add documentation build system troubleshooting guidelines
  doc/source/ray-contribute/docs.ipynb
Labels: P1, docs

#42911 [Serve] Stop `@serve.batch`'s batch handler when event loop closes
  python/ray/serve/batching.py
  python/ray/serve/tests/unit/test_batching.py
Labels: continuous-build

#42810 Fix gap between total time and time in user code + blocked time, rename iterator overheads
  python/ray/data/_internal/stats.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_stats.py
Labels: bug, P0

#43073 [2.9][Data] Skip `schema` call in `to_tf` if `tf.TypeSpec` is provided (#42917)
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_tf.py
Labels: v2.9.3-pick

#43114 [Serve] Config Serve's gRPC proxy to allow large payload
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/grpc_util.py
  python/ray/serve/tests/test_grpc.py
Labels: P0, ray 2.10

#43147 [CherryPick][Core] Bumping up task failure logs to warnings to make sure failures could be traced in Ray Core logs
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/transport/direct_task_transport.cc
Labels: v2.9.3-pick

#42885 [Doc] Remove pendo
  doc/source/_templates/extrahead.html
Labels: docs

#43267 [Doc] Fix color of button icon and text in dark mode button
  doc/source/_ext/queryparamrefs.py
  doc/source/_static/css/custom.css
  doc/source/_static/css/use_cases.css
  doc/source/conf.py
  doc/source/ray-overview/use-cases.rst
Labels: docs

#43438 [Doc,RLlib] Fix invalid doc syntax in LearnerGroup docstrings
  rllib/core/learner/learner_group.py
Labels: P1, rllib, docs

#43196 [RLlib] DQN Rainbow Learner with new API stack (and EnvRunner API).
  rllib/algorithms/dqn/dqn_rainbow_learner.py
  rllib/algorithms/dqn/torch/dqn_rainbow_torch_learner.py
  rllib/algorithms/sac/sac_rl_module.py
  rllib/algorithms/sac/torch/sac_torch_learner.py
  rllib/algorithms/sac/torch/sac_torch_rl_module.py
Labels: tests-ok

#43439 [Doc] Bump sphinx-click to avoid building protocol buffers for Ray CLI
  .readthedocs.yaml
  doc/Makefile
  doc/requirements-doc.txt
Labels: P1, docs

#42664 [Data] Fix BigQuery write docs formatting
  python/ray/data/dataset.py
Labels: data

#43506 [Dashboard] [Serve] Add application row with dropdown for deployment rows
  dashboard/client/src/pages/overview/cards/RecentServeCard.tsx
  dashboard/client/src/pages/serve/ServeApplicationDetailPage.tsx
  dashboard/client/src/pages/serve/ServeApplicationRow.tsx
  dashboard/client/src/pages/serve/ServeDeploymentRow.tsx
  dashboard/client/src/pages/serve/ServeDeploymentsListPage.component.test.tsx
  dashboard/client/src/pages/serve/ServeDeploymentsListPage.tsx
  dashboard/client/src/pages/serve/ServeSystemDetails.component.test.tsx
  dashboard/client/src/pages/serve/ServeSystemDetails.tsx
  dashboard/client/src/pages/serve/hook/useServeApplications.ts
Labels: ray 2.10

#42431 [core][enable_task_events] Options to disable task tracing on task/actor
  ci/ray_ci/core.tests.yml
  doc/source/ray-core/actors.rst
  doc/source/ray-core/doc_code/actors.py
  doc/source/ray-core/tasks.rst
  python/ray/_private/ray_option_utils.py
  python/ray/_private/state.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/remote_function.py
  python/ray/tests/BUILD
  python/ray/tests/test_task_events_3.py
  src/ray/common/constants.h
  src/ray/common/ray_config_def.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/profile_event.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
Labels: core-interface-change-approval-required
