Repository ray-project/ray, pull requests merged in 2024-08, with the labels that each got.

#46907 [doc][core] turn on api policy check for core
  .buildkite/lint.rayci.yml
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  doc/source/ray-core/api/exceptions.rst
Labels: go

#46906 [Core] More structured logging in core worker
  src/ray/common/id.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/util/logging.h
Labels: go

#46818 [RLlib; Offline RL] Offline recording new api stack
  rllib/algorithms/algorithm_config.py
  rllib/env/env_runner_group.py
  rllib/offline/offline_env_runner.py
  rllib/tuned_examples/bc/cartpole_recording.py
Labels: go

#46846 [core] Replace GCS stubs in dashboard to use NewGcsAioClient.
  python/ray/_private/gcs_aio_client.py
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/actor/actor_head.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/snapshot/snapshot_head.py
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
  python/ray/includes/unique_ids.pxd
  python/ray/includes/unique_ids.pxi
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/python_callbacks.h
Labels: go

#46917 [serve] Don't construct `aiohttp.ClientSession` outside of async context
  python/ray/serve/_private/benchmarks/microbenchmark.py
  python/ray/serve/_private/benchmarks/proxy_benchmark.py
Labels: go

#46912 [Core] Rename CoreWorkerDirectActorTaskSubmitter to ActorTaskSubmitter
  src/mock/ray/core_worker/transport/direct_actor_transport.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/core_worker/transport/direct_actor_transport.h
Labels: go

#46920 [doc] add a function to check if an api is deprecated
  ci/ray_ci/doc/api.py
  ci/ray_ci/doc/test_api.py
Labels: go

#46902 [dashboard] restrict aiohttp version
  ci/docker/base.test.Dockerfile
  python/requirements.txt
  python/setup.py
Labels: go

#46921 [doc] print good+bad apis in the api policy lint check
  ci/ray_ci/doc/api.py
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  ci/ray_ci/doc/test_api.py
Labels: go

#46905 [ci][tune][py312] Remove rllib dependencies from Tune unit tests
  python/ray/tune/BUILD
  python/ray/tune/registry.py
  python/ray/tune/tests/execution/test_controller_callback_integration.py
  python/ray/tune/tests/execution/test_controller_checkpointing_integration.py
  python/ray/tune/tests/execution/test_controller_control_integration.py
  python/ray/tune/tests/execution/test_controller_errors_integration.py
  python/ray/tune/tests/execution/test_controller_resources_integration.py
  python/ray/tune/tests/execution/test_controller_resume_integration.py
  python/ray/tune/tests/execution/test_controller_search_alg_integration.py
  python/ray/tune/tests/output/test_output.py
  python/ray/tune/tests/test_actor_reuse.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_commands.py
  python/ray/tune/tests/test_run_experiment.py
  python/ray/tune/tests/test_searcher_utils.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
  python/ray/tune/tests/test_tune_restore.py
  python/ray/tune/tests/test_tuner.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/tests/test_var.py
  python/ray/tune/utils/mock_trainable.py
Labels: go

#46901 Generate Versions JSON for new Version Switcher
  doc/.gitignore
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: docs, go

#46886 [wheel] cut "cpp" out of "all"
  python/setup.py
Labels: go

#46897 [RLlib; Tune] Fix WandB metric overlap after restore from checkpoint.
  python/ray/air/integrations/wandb.py
  python/ray/air/tests/mocked_wandb_integration.py
  rllib/examples/checkpoints/continue_training_from_checkpoint.py
Labels: tests-ok, go

#46900 [RLlib] Add `learner_only` flag to RLModuleConfig/Spec and simplify creation of RLModule specs from algo-config.
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dreamerv3/tf/models/actor_network.py
  rllib/algorithms/dreamerv3/tf/models/components/sequence_model.py
  rllib/algorithms/dreamerv3/tf/models/dreamer_model.py
  rllib/algorithms/dreamerv3/utils/env_runner.py
  rllib/core/learner/learner.py
  rllib/core/rl_module/multi_rl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/env/env_runner.py
  rllib/env/env_runner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/evaluation/rollout_worker.py
  rllib/examples/curiosity/inverse_dynamics_model_based_curiosity.py
  rllib/examples/learners/classes/curiosity_ppo_torch_learner.py
  rllib/examples/rl_modules/classes/inverse_dynamics_model_rlm.py
Labels: go

#46932 [RLlib] Add more control to `Algorithm.add_policy` method over which components to add the Policy to.
  rllib/algorithms/algorithm.py
  rllib/algorithms/appo/appo_learner.py
  rllib/algorithms/dqn/dqn_rainbow_learner.py
  rllib/examples/_old_api_stack/connectors/self_play_with_policy_checkpoint.py
Labels: go

#46929 [doc] fix readthedocs build
  doc/source/_templates/main-sidebar-readthedocs.html
  doc/source/conf.py
Labels: go

#46923 [Core] Rename CoreWorkerDirectTaskSubmitter to NormalTaskSubmitter
  BUILD.bazel
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/direct_task_transport_mock_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#46936 Use PyData Sphinx theme version switcher
  doc/source/_static/css/custom.css
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: go

#46699 [Data]Update Data progress bars to use row as the iteration unit
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/limit_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/execution/operators/union_operator.py
  python/ray/data/_internal/execution/operators/zip_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
Labels: triage, data, go

#46872 [core][adag] Report GPU performance results for aDAG microbenchmark
  release/microbenchmark/experimental/accelerated_dag_gpu_microbenchmark.py
  release/microbenchmark/experimental/compute_gpu_2x1_aws.yaml
  release/release_tests.yaml
Labels: go

#46899 [spark] Fix Ray-on-Spark cluster crashing bug when user cancels cell execution
  python/ray/tests/spark/test_basic.py
  python/ray/util/spark/start_ray_node.py
Labels: go

#46942 [Data] Improve warning message when read task is large
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/_internal/planner/plan_read_op.py
  python/ray/data/datasource/datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_delta_sharing.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#46943 [Data] Handle logs from tensor extensions
  python/ray/data/_internal/logging.yaml
Labels: go

#46885 Clarify behavior of `placement_group_capture_child_tasks` in docs
  doc/source/ray-core/scheduling/placement-group.rst
Labels: go

#46916 [RLlib; docs] Redo `rllib-algorithms.rst` page.
  doc/source/rllib/images/algos/appo-architecture.svg
  doc/source/rllib/images/algos/bc-architecture.svg
  doc/source/rllib/images/algos/curiosity-architecture.svg
  doc/source/rllib/images/algos/dqn-architecture.svg
  doc/source/rllib/images/algos/dreamerv3-architecture.svg
  doc/source/rllib/images/algos/icm-architecture.svg
  doc/source/rllib/images/algos/impala-architecture.svg
  doc/source/rllib/images/algos/marwil-architecture.svg
  doc/source/rllib/images/algos/ppo-architecture.svg
  doc/source/rllib/images/algos/sac-architecture.svg
  doc/source/rllib/images/ppo-arch.svg
  doc/source/rllib/images/sigils/cont-actions.svg
  doc/source/rllib/images/sigils/discr-actions.svg
  doc/source/rllib/images/sigils/multi-agent.svg
  doc/source/rllib/images/sigils/multi-gpu.svg
  doc/source/rllib/images/sigils/multi-node-multi-gpu.svg
  doc/source/rllib/images/sigils/new-api-stack.svg
  doc/source/rllib/images/sigils/old-api-stack.svg
  doc/source/rllib/images/sigils/single-agent.svg
  doc/source/rllib/index.rst
  doc/source/rllib/rllib-algorithms.rst
  rllib/BUILD
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/dqn/dqn_rainbow_catalog.py
  rllib/algorithms/dqn/torch/dqn_rainbow_torch_learner.py
  rllib/algorithms/ppo/ppo.py
  rllib/examples/curiosity/intrinsic_curiosity_model_based_curiosity.py
  rllib/examples/learners/classes/curiosity_dqn_torch_learner.py
  rllib/examples/learners/classes/curiosity_ppo_torch_learner.py
  rllib/examples/learners/classes/curiosity_torch_learner_utils.py
  rllib/examples/rl_modules/classes/intrinsic_curiosity_model_rlm.py
Labels: go

#46963 [RLlib] Streamline CI tests.
  .buildkite/rllib.rayci.yml
Labels: tests-ok

#46784 [Data] Extend API to enable passing sample weights via ray.dataset.to_tf (#45701)
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_iterator.py
  python/ray/data/tests/test_tf.py
Labels: go

#46944 [Data] Make Parquet tests more robust and expose Parquet logic
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/datasource/parquet_meta_provider.py
  python/ray/data/tests/test_formats.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_stats.py
Labels: go

#46960 [Core] Rename CoreWorkerDirectTaskReceiver to TaskReceiver
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/store_provider/memory_store/memory_store.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/concurrency_group_manager_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/normal_task_submitter.h
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
Labels: go

#46806 [serve] Deprecate passing DeploymentResponse to handle
  doc/source/serve/model_composition.md
  python/ray/serve/_private/router.py
Labels: go

#46940 [py312] ml cpu tests
  .buildkite/ml.rayci.yml
  python/ray/air/tests/test_keras_callback.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_mlflow.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_tensorboard.py
  python/ray/train/examples/pytorch/tune_torch_regression_example.py
  python/ray/train/examples/tf/tensorflow_quick_start.py
  python/ray/train/examples/tf/tensorflow_regression_example.py
  python/ray/train/examples/tf/tune_tensorflow_mnist_example.py
  python/ray/train/tests/test_backend.py
  python/ray/train/tests/test_examples.py
  python/ray/train/tests/test_tensorflow_checkpoint.py
  python/ray/train/tests/test_tensorflow_trainer.py
  python/ray/train/tests/test_training_iterator.py
  python/ray/train/tests/test_tune.py
  python/ray/tune/examples/bohb_example.py
  python/ray/tune/examples/pbt_dcgan_mnist/pbt_dcgan_mnist_trainable.py
  python/ray/tune/examples/pbt_memnn_example.py
  python/ray/tune/examples/tf_mnist_example.py
  python/ray/tune/examples/tune_mnist_keras.py
  python/ray/tune/tests/test_sample.py
  python/ray/tune/tests/test_searchers.py
  python/ray/tune/tests/test_tune_restore_warm_start.py
  python/requirements/ml/tune-requirements.txt
  python/requirements_compiled.txt
Labels: continuous-build, go

#46946 [py312] ml python 3.12 docker image
  .buildkite/ml.rayci.yml
  ci/docker/ml.build.Dockerfile
  ci/docker/ml.build.wanda.yaml
  python/ray/air/tests/test_keras_callback.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_mlflow.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_tensorboard.py
  python/ray/train/examples/pytorch/tune_torch_regression_example.py
  python/ray/train/examples/tf/tensorflow_quick_start.py
  python/ray/train/examples/tf/tensorflow_regression_example.py
  python/ray/train/examples/tf/tune_tensorflow_mnist_example.py
  python/ray/train/tests/test_backend.py
  python/ray/train/tests/test_examples.py
  python/ray/train/tests/test_tensorflow_checkpoint.py
  python/ray/train/tests/test_tensorflow_trainer.py
  python/ray/train/tests/test_training_iterator.py
  python/ray/train/tests/test_tune.py
  python/ray/tune/examples/bohb_example.py
  python/ray/tune/examples/pbt_dcgan_mnist/pbt_dcgan_mnist_trainable.py
  python/ray/tune/examples/pbt_memnn_example.py
  python/ray/tune/examples/tf_mnist_example.py
  python/ray/tune/examples/tune_mnist_keras.py
  python/ray/tune/tests/test_sample.py
  python/ray/tune/tests/test_searchers.py
  python/ray/tune/tests/test_tune_restore_warm_start.py
  python/requirements/ml/tune-requirements.txt
  python/requirements_compiled.txt
Labels: go

#46904 [Dashboard] Update aiohttp.ClientSession to only be created in async contexts
  python/ray/dashboard/head.py
  python/ray/dashboard/http_server_agent.py
  python/ray/dashboard/modules/data/data_head.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/utils.py
  python/requirements.txt
  python/setup.py
Labels: go

#46975 [data] Add a parameter to allow overriding LanceDB scanner options
  python/ray/data/_internal/datasource/lance_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_lance.py
Labels: go

#46970 [py312] ml gpu tests
  .buildkite/base.rayci.yml
  .buildkite/ml.rayci.yml
  python/ray/train/tests/test_gpu_examples.py
  python/ray/train/tests/test_tensorflow_predictor.py
Labels: continuous-build, go

#46926 [core] GcsClient: No GIL for C++ pb serialization
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
  src/ray/gcs/gcs_client/python_callbacks.h
Labels: go

#46649 [py12] build ray image
  .buildkite/_forge.rayci.yml
  .buildkite/build.rayci.yml
  .buildkite/release/build.rayci.yml
  docker/base-deps/Dockerfile
  python/requirements.txt
  python/requirements/ml/rllib-test-requirements.txt
  python/requirements_compiled.txt
  release/BUILD.bazel
  release/ray_release/byod/requirements_byod_3.12.in
  release/ray_release/byod/requirements_byod_3.12.txt
  release/ray_release/schema.json
  release/release_tests.yaml
Labels: go

#46825 [Data] Move datasource implementations to `_internal` subpackage
  doc/source/data/api/input_output.rst
  python/ray/data/__init__.py
  python/ray/data/_internal/datasource/databricks_uc_datasource.py
  python/ray/data/_internal/datasource/delta_sharing_datasource.py
  python/ray/data/_internal/datasource/huggingface_datasource.py
  python/ray/data/_internal/datasource/tfrecords_datasink.py
  python/ray/data/_internal/datasource/tfrecords_datasource.py
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/tfrecords_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_delta_sharing.py
  python/ray/data/tests/test_tfrecords.py
Labels: go

#46973 [core] fix PinExistingReturnObject segfault by passing owner_address
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_actor_failures.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
Labels: go

#46976 [data] Add failure retry logic for read_lance
  python/ray/data/_internal/datasource/lance_datasource.py
Labels: go

#46981 [Data] Remove dead code in `Dataset.split()`
  python/ray/data/dataset.py
Labels: go

#46989 [ci] upgrade release tests to python 3.12
  release/release_tests.yaml
Labels: go

#46987 [Core] Stop running dask_on_ray_100gb_sort with python 3.11
  release/release_tests.yaml
Labels: go

#46925 [doc][data] auto-gen GroupedData api
  doc/source/_templates/autosummary/class_v2.rst
  doc/source/conf.py
  doc/source/data/api/_autogen.rst
  doc/source/data/api/grouped_data.rst
  python/ray/data/grouped_data.py
Labels: go

#46985 [RLlib; docs] RLlib docs redo: New API stack Episodes (SingleAgentEpisode).
  doc/source/rllib/doc_code/sa_episode.py
  doc/source/rllib/images/episodes/sa_episode.svg
  doc/source/rllib/images/episodes/sa_episode_cut_and_lookback.svg
  doc/source/rllib/images/episodes/sa_episode_finalized.svg
  doc/source/rllib/images/episodes/sa_episode_getters.svg
  doc/source/rllib/images/episodes/sa_episode_non_finalized.svg
  doc/source/rllib/images/episodes/sa_episode_non_finalized_vs_finalized.svg
  doc/source/rllib/images/episodes/usage_of_episodes.svg
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/env/single_agent_episode.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-sample-collection.rst
  doc/source/rllib/single-agent-episode.rst
  doc/source/rllib/user-guides.rst
  rllib/connectors/common/add_states_from_episodes_to_batch.py
  rllib/connectors/common/frame_stacking.py
  rllib/env/multi_agent_episode.py
  rllib/env/single_agent_episode.py
  rllib/env/tests/test_infinite_lookback_buffer.py
  rllib/env/tests/test_multi_agent_episode.py
  rllib/env/tests/test_single_agent_episode.py
  rllib/env/utils/infinite_lookback_buffer.py
Labels: go

#46988 fix broken asyncio tests for aiohttp 3.10.0
  python/ray/dashboard/modules/job/tests/test_job_agent.py
  python/ray/tests/test_state_api.py
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#46864 [serve] Fix Router race condition
  python/ray/serve/_private/router.py
Labels: triage, serve, go

#46998 [Core] Remove actor_register_async config
  src/ray/common/ray_config_def.h
  src/ray/core_worker/actor_creator.h
Labels: go

#46974 [Data] Correctly refresh elapsed time in `ProgressBar` output
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/_internal/progress_bar.py
  python/ray/experimental/tqdm_ray.py
Labels: go

#46971 [core] change all callbacks to move to save copies.
  python/ray/includes/gcs_client.pxi
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/common/test/ray_syncer_test.cc
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/gcs/callback.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/python_callbacks.h
  src/ray/gcs/gcs_client/test/accessor_test.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/gcs/store_client/in_memory_store_client.cc
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
  src/ray/pubsub/subscriber.cc
  src/ray/pubsub/subscriber.h
  src/ray/pubsub/test/integration_test.cc
  src/ray/pubsub/test/subscriber_test.cc
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/rpc/client_call.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/worker/core_worker_client.h
Labels: go

#46991 [core] Fix raylet CHECK failure from runtime env creation failure.
  python/ray/tests/test_runtime_env_plugin.py
  src/ray/raylet/local_task_manager.cc
Labels: go

#46486 [Serve/Logs] Break serve status details across multiple lines
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: go

#47006 [dashbord] fix typo in memray command
  python/ray/dashboard/client/src/common/ProfilingLink.component.test.tsx
  python/ray/dashboard/client/src/common/ProfilingLink.tsx
Labels: go

#46999 [Core] Rename ReferenceCounter::Reference::on_delete to ReferenceCounter::Reference::on_object_primary_copy_delete
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/reference_count_test.cc
Labels: go

#44666 [Doc] Fix Typo in build-wheel-manylinux2014.sh
  python/build-wheel-manylinux2014.sh
Labels: triage, docs

#45478 [data][doc] update authenticaion to authentication
  doc/source/data/loading-data.rst
Labels: P2, docs, data, go

#46928 [data] Only dump state once on progress bar close
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/experimental/tqdm_ray.py
Labels: go

#47019 Version Switcher Part 3
  doc/source/_static/css/custom.css
  doc/source/custom_directives.py
Labels: go

#46667 [train] Updates to support `xgboost==2.1.0`
  python/ray/train/xgboost/config.py
  python/requirements/ml/core-requirements.txt
  python/requirements_compiled.txt
Labels: go

#47025 cherry pick version switcher to release 2.34.0
  doc/.gitignore
  doc/source/_static/css/custom.css
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: go

#47022 [Core] Remove unnecessary gcs rpc reply status conversion
  src/ray/gcs/gcs_client/accessor.cc
Labels: go

#47030 cherry pick version switcher to 2.30.0
  doc/.gitignore
  doc/source/_static/css/custom.css
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: go

#47018 [Core] Update ray.available_resources() docstring
  python/ray/_private/state.py
Labels: go

#47023 [core] Fix memleaks in the callback
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
  src/ray/gcs/gcs_client/python_callbacks.h
Labels: go

#47032 [Data] Change pickling log level from warning to debug
  python/ray/data/_internal/arrow_block.py
Labels: go

#47034 [Data] Upgrade Arrow version from 16 to 17
  .buildkite/core.rayci.yml
  .buildkite/data.rayci.yml
  ci/docker/data17.build.wanda.yaml
Labels: go

#47003 [core] Move UsageStatsClient to gcs_server/.
  BUILD.bazel
  src/mock/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_client/test/usage_stats_client_test.cc
  src/ray/gcs/gcs_client/usage_stats_client.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/test/usage_stats_client_test.cc
  src/ray/gcs/gcs_server/usage_stats_client.cc
  src/ray/gcs/gcs_server/usage_stats_client.h
Labels: go

#47029 [Data] Only show message regarding hiding op-level progress bar once
  python/ray/data/context.py
Labels: go

#47049 [Data] Clarify warning for reading old Parquet data
  python/ray/data/_internal/datasource/parquet_datasource.py
Labels: go

#47013 [core] Fix the old GcsClient code path.
  python/ray/dashboard/modules/actor/actor_head.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/snapshot/snapshot_head.py
  src/ray/gcs/gcs_client/gcs_client.cc
Labels: go

#46993 [observability][export-api] Make ErrorType and Language enum public
  python/ray/util/state/custom_types.py
  src/ray/protobuf/common.proto
Labels: go

#46927 [observability] [export-api] Add feature flag to write export events to file
  src/ray/common/ray_config_def.h
Labels: go

#47035 [core][dashboard] Adds Dashboard RSS metrics
  python/ray/dashboard/dashboard_metrics.py
  python/ray/dashboard/modules/metrics/metrics_head.py
Labels: go

#47074 [Core] Remove dead code
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/protobuf/core_worker.proto
Labels: go

#46865 [RLlib; Offline RL] Add support to directly read from episodes.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/marwil/marwil_catalog.py
  rllib/offline/offline_prelearner.py
Labels: go

#46969 [RLlib; Offline RL] Add C`QLLearner` and `CQLTorchLearner`.
  rllib/algorithms/cql/torch/cql_torch_learner.py
Labels: go

#47047 [RLlib] Add constant for `__env__` key.
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dreamerv3/utils/env_runner.py
  rllib/env/__init__.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/evaluation/rollout_worker.py
Labels: go

#47008 [serve] appropriately handle actor died and actor unavailable in all cases
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/replica_scheduler/common.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#47071 [RLlib] Examples folder cleanup: Add example script for Env with protobuf observation space.
  rllib/examples/connectors/classes/protobuf_cartpole_observation_decoder.py
  rllib/examples/envs/classes/cartpole_with_dict_observation_space.py
  rllib/examples/envs/classes/cartpole_with_protobuf_observation_space.py
  rllib/examples/envs/classes/utils/cartpole_observations.proto
  rllib/examples/envs/classes/utils/cartpole_observations_proto.py
  rllib/examples/envs/env_with_protobuf_observations.py
Labels: go

#47077 [RLlib] Add `ObservationPreprocessor` (ConnectorV2) and cleanup ConnectorV2 docstrings.
  rllib/connectors/common/add_observations_from_episodes_to_batch.py
  rllib/connectors/common/add_states_from_episodes_to_batch.py
  rllib/connectors/common/agent_to_module_mapping.py
  rllib/connectors/common/batch_individual_items.py
  rllib/connectors/common/module_to_agent_unmapping.py
  rllib/connectors/common/numpy_to_tensor.py
  rllib/connectors/common/tensor_to_numpy.py
  rllib/connectors/env_to_module/mean_std_filter.py
  rllib/connectors/env_to_module/observation_preprocessor.py
  rllib/connectors/env_to_module/prev_actions_prev_rewards.py
  rllib/connectors/env_to_module/write_observations_to_episodes.py
  rllib/connectors/learner/add_columns_from_episodes_to_train_batch.py
  rllib/connectors/learner/add_next_observations_from_episodes_to_train_batch.py
  rllib/connectors/learner/add_one_ts_to_episodes_and_truncate.py
  rllib/connectors/module_to_env/get_actions.py
  rllib/connectors/module_to_env/listify_data_for_vector_env.py
  rllib/connectors/module_to_env/normalize_and_clip_actions.py
  rllib/connectors/module_to_env/remove_single_ts_time_rank_from_batch.py
  rllib/connectors/module_to_env/unbatch_to_individual_items.py
Labels: go

#47051 [doc][build] Update timestamp of html target files
  ci/ray_ci/doc/cmd_update_cache_env.py
Labels: go

#47020 [doc] publish the api policy
  doc/source/ray-contribute/api-policy.rst
  doc/source/ray-contribute/index.rst
  doc/source/ray-contribute/stability.rst
Labels: go

#47088 [core] add more doc for raylet startup wait failure
  src/ray/gcs/gcs_client/global_state_accessor.cc
Labels: go

#47092 [Data] Make `test_fsspec_filesystem` less brittle
  python/ray/data/tests/test_formats.py
Labels: go

#46758 [observability][export-api] Add macro to write export events to file
  src/ray/protobuf/BUILD
  src/ray/protobuf/export_api/export_event.proto
  src/ray/protobuf/export_api/export_runtime_env.proto
  src/ray/protobuf/export_api/export_task_event.proto
  src/ray/util/BUILD
  src/ray/util/event.cc
  src/ray/util/event.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/event_test.cc
Labels: go

#46437 [Core] Fix random port conflict from dashboard agent
  python/ray/_private/node.py
Labels: dashboard, triage, core, go

#47094 [Data] Fix signature of `Rule.plan`
  python/ray/data/_internal/logical/interfaces/optimizer.py
Labels: go

#47031 [serve] eagerly create router for handles held by proxy
  doc/source/serve/doc_code/load_shedding.py
  python/ray/serve/_private/proxy_router.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_proxy_router.py
Labels: go

#47080 [Core] Move submitting actor creation task to ActorTaskSubmitter
  BUILD.bazel
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_task_transport_mock_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#47033 [serve] move `test_proxy_router` to unit test
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/unit/test_proxy_router.py
Labels: go

#47055 [data] add validation for shuffle arg
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_file_based_datasource.py
  python/ray/data/tests/test_parquet.py
Labels: go

#47099 [core] Increase raylet_start_wait_time_s default to 30s
  src/ray/common/ray_config_def.h
Labels: go

#47083 [tune] upgrade ax-platform
  python/ray/tune/examples/ax_example.py
  python/ray/tune/search/ax/ax_search.py
  python/requirements/ml/tune-requirements.txt
  python/requirements_compiled.txt
Labels: go

#47101 [ci] remove old CI readme
  ci/README.md
Labels: go

#47105 [RLlib; Offline RL] Implement twin-Q net option for CQL.
  rllib/algorithms/cql/torch/cql_torch_learner.py
  rllib/algorithms/sac/torch/sac_torch_learner.py
Labels: go

#47057 [core] remove unused GcsAio(Publisher|Subscriber) methods and subclasses.
  python/ray/_private/gcs_pubsub.py
  python/ray/tests/test_gcs_pubsub.py
Labels: go

#47109 [Core] Fix a bug where we submit the actor creation task to the wrong submitter
  src/ray/core_worker/core_worker.cc
Labels: go

#47115 [doc][build] Update all changed files timestamp to latest
  ci/ray_ci/doc/cmd_load_doc_cache.py
  ci/ray_ci/doc/cmd_update_cache_env.py
Labels: go

#47112 [serve] split `test_proxy.py` into unit and e2e tests
  python/ray/serve/tests/test_proxy.py
  python/ray/serve/tests/unit/test_proxy.py
Labels: go

#47117 [Utility] add `env_float` utility into `ray._private.ray_constants`
  python/ray/_private/ray_constants.py
Labels: go

#47120 [Data] Fix progress bars not showing % progress
  python/ray/data/_internal/execution/operators/map_operator.py
Labels: go

#47082 [data] change data17 to datal
  .buildkite/core.rayci.yml
  .buildkite/data.rayci.yml
  ci/docker/datal.build.wanda.yaml
Labels: go

#47121 [ci] change data build for all python versions to arrow 17
  ci/docker/data.build.wanda.yaml
Labels: go

#47111 [doc][rllib] add missing public api references
  doc/source/rllib/package_ref/utils.rst
Labels: go

#46821 [Core] Clarify docstring for get_gpu_ids() so that it is only called inside a task or actor
  python/ray/_private/worker.py
Labels: P0, core, go

#47119 cleanup CI setup on 2.9.3 for pinterest
  .buildkite/build.rayci.yml
  .buildkite/core.rayci.yml
  .buildkite/ml.rayci.yml
  .buildkite/serve.rayci.yml
  .rayciversion
  .readthedocs.yaml
  ci/README.md
  ci/build/build-manylinux-forge.sh
  ci/docker/manylinux.Dockerfile
  ci/docker/manylinux.wanda.yaml
  python/README-building-wheels.md
Labels: go

#47114 [doc][rllib] the rest of missing api references + lint checker
  .buildkite/lint.rayci.yml
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/package_ref/utils.rst
Labels: go

#47054 Light up Ask AI button When Seach is Open
  doc/source/_static/css/assistant.css
  doc/source/_static/js/assistant.js
Labels: P2, docs, go

#47053 [serve] immediately send ping in router when receiving new replica set
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/replica_scheduler/common.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_gcs_failure.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
Labels: go

#47095 [data] Add label to indicate if operator is backpressured
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/streaming_executor_state.py
Labels: go

#47009 [Core] Add ray[adag] option to pip install
  doc/source/conf.py
  python/requirements.txt
  python/setup.py
Labels: go

#47108 [Doc] Run pre-commit on tune docs
  doc/source/tune/api/reporters.rst
  doc/source/tune/api/suggestion.rst
  doc/source/tune/api/trainable.rst
  doc/source/tune/examples/includes/async_hyperband_example.rst
  doc/source/tune/examples/includes/hyperband_example.rst
  doc/source/tune/examples/includes/logging_example.rst
  doc/source/tune/examples/includes/mnist_pytorch.rst
  doc/source/tune/examples/includes/nevergrad_example.rst
  doc/source/tune/examples/includes/pb2_example.rst
  doc/source/tune/examples/includes/pbt_tune_cifar10_with_keras.rst
  doc/source/tune/examples/includes/xgboost_dynamic_resources_example.rst
  doc/source/tune/examples/ml-frameworks.rst
  doc/source/tune/faq.rst
  doc/source/tune/tutorials/tune-lifecycle.rst
  doc/source/tune/tutorials/tune-resources.rst
  doc/source/tune/tutorials/tune-trial-checkpoints.rst
Labels: tune, docs, go

#46397 [release tests] update anyscale service utils
  release/serve_tests/workloads/anyscale_service_utils.py
  release/serve_tests/workloads/autoscaling_load_test.py
  release/serve_tests/workloads/replica_scalability.py
Labels: go

#46911 [core][experimental] Build an operation-based execution schedule for each actor to avoid deadlocks caused by NCCL operations
  python/ray/dag/BUILD
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node_operation.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule.py
  python/ray/dag/tests/experimental/test_execution_schedule_gpu.py
Labels: go

#47085 [serve] remove warnings about ongoing requests default change
  python/ray/dashboard/modules/serve/serve_rest_api_impl.py
  python/ray/serve/api.py
Labels: go

#47144 [serve] `__init__` functions have no return values
  python/ray/serve/tests/test_constructor_failure.py
  python/ray/serve/tests/test_controller_recovery.py
Labels: go

#47133 [RLlib; Offline RL] Add tests for `OfflineSingleAgentEnvRunner`.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/offline/offline_env_runner.py
  rllib/offline/offline_prelearner.py
  rllib/offline/tests/test_offline_env_runner.py
Labels: go

#47151 [core] make a note GetThreadContext() can't be used in fiber context
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
Labels: go

#46715 docs: introduce quickstart button for image classification
  doc/source/_static/img/run-quickstart-anyscale.svg
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
Labels: go

#47072 [Data] Fix validation bug when size=0 in ActorPoolStrategy
  python/ray/data/_internal/compute.py
Labels: triage, data, go

#47110 [Data] Fix exception in async map
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/tests/test_map.py
Labels: go

#47106 [Data] Progress Bar: Sort sample in "rows" and remove the duplicate Sort sample.
  python/ray/data/_internal/logical/operators/all_to_all_operator.py
  python/ray/data/_internal/planner/aggregate.py
  python/ray/data/_internal/planner/exchange/sort_task_spec.py
  python/ray/data/_internal/planner/sort.py
  python/ray/data/_internal/progress_bar.py
Labels: go

#46889 Add iceberg datasource
  doc/source/data/api/input_output.rst
  doc/source/data/loading-data.rst
  python/ray/data/BUILD
  python/ray/data/__init__.py
  python/ray/data/_internal/datasource/iceberg_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_iceberg.py
  python/requirements/ml/data-test-requirements.txt
  python/requirements/ml/tune-test-requirements.txt
  python/requirements_compiled.txt
Labels: enhancement, P0, data, go

#47086 [observability][export-api] Add event data schema for nodes
  src/ray/protobuf/BUILD
  src/ray/protobuf/export_api/export_event.proto
  src/ray/protobuf/export_api/export_node_data.proto
  src/ray/util/event.cc
  src/ray/util/event.h
Labels: go

#47163 [autoscaler] fix import not used lint error on typing
  python/ray/autoscaler/_private/gcp/node_provider.py
Labels: go

#47168 cherry-pick docs: introduce quickstart button for image classification (#46715)
  doc/source/_static/img/run-quickstart-anyscale.svg
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
Labels: go

#47154 [RLlib; Offline RL] - Fix data path in new stack BC test.
  rllib/BUILD
Labels: go

#47155 [RLlib; Offline RL] Added `stop` method to `OfflineEnvRunner`.
  rllib/algorithms/bc/tests/test_bc.py
  rllib/offline/offline_env_runner.py
Labels: go

#47172 [RLlib; docs] Docs redo vol. 0.5: Cleanup old API stack docs (rllib-dev.rst).
  doc/source/rllib/rllib-dev.rst
  rllib/env/env_runner_group.py
Labels: go

#47147 [Jobs] Revisiting critical Job control ops to be only routed via Head node's `JobAgent`
  python/ray/_private/ray_constants.py
  python/ray/dashboard/consts.py
  python/ray/dashboard/datacenter.py
  python/ray/dashboard/modules/job/job_head.py
  python/ray/dashboard/modules/job/job_manager.py
  python/ray/dashboard/modules/job/tests/test_http_job_server.py
  python/ray/dashboard/modules/job/tests/test_job_manager.py
  python/ray/dashboard/modules/job/tests/test_sdk.py
  python/ray/dashboard/modules/job/utils.py
  python/ray/dashboard/modules/node/node_head.py
Labels: go

#47143 [observability] [export-api] Fix Ray Events to support writing events of multiple source types to different files
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/util/event.cc
  src/ray/util/event.h
  src/ray/util/tests/event_test.cc
Labels: go

#47158 [RLlib] Activate APPO/IMPALA + LSTM + multi-GPU learning tests (new API stack; bug fix)
  rllib/BUILD
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/tuned_examples/appo/stateless_cartpole_appo.py
  rllib/tuned_examples/impala/stateless_cartpole_impala.py
Labels: go

#47091 Docs update for Ray ecosystem -- Apache Airflow integration
  doc/source/images/airflow_logo_full.png
  doc/source/ray-overview/ray-libraries.rst
Labels: triage, docs, go

#47021 [RLlib] Don't sync (old API stack) connector states after worker restore.
  rllib/algorithms/algorithm.py
  rllib/algorithms/impala/impala.py
  rllib/env/env_runner_group.py
  rllib/utils/actor_manager.py
  rllib/utils/tests/test_actor_manager.py
Labels: go

#45924 [Docs][Kuberay] Documentation for Using Kuberay with TPUs
  doc/source/cluster/kubernetes/examples.md
  doc/source/cluster/kubernetes/examples/tpu-serve-stable-diffusion.md
  doc/source/cluster/kubernetes/images/diffusion_results.png
  doc/source/cluster/kubernetes/images/serve_dashboard.png
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/gcp-gke-tpu-cluster.md
  doc/source/cluster/kubernetes/user-guides/k8s-cluster-setup.md
  doc/source/cluster/kubernetes/user-guides/tpu.md
Labels: go

#47176 [data] Handle errors in SplitCoordinator when generating a new epoch
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/tests/test_streaming_integration.py
Labels: go

#47181 [core][dashboard] configurable timeouts
  python/ray/dashboard/consts.py
  python/ray/dashboard/datacenter.py
  python/ray/dashboard/modules/event/event_consts.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/node/node_consts.py
  python/ray/dashboard/modules/node/node_head.py
Labels: go

#47118 [core] Remove serialized_allocated_resource_instances from RuntimeEnv creation.
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  src/ray/common/ray_config_def.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/test/task_spec_test.cc
  src/ray/protobuf/runtime_env_agent.proto
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager_test.cc
  src/ray/raylet/runtime_env_agent_client.cc
  src/ray/raylet/runtime_env_agent_client.h
  src/ray/raylet/runtime_env_agent_client_test.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: go

#47107 [Doc] Run pre-commit on train docs
  doc/source/train/common/torch-configure-train_func.rst
  doc/source/train/getting-started-transformers.rst
  doc/source/train/horovod.rst
  doc/source/train/images/train-specific.svg
  doc/source/train/images/train-tuner.svg
  doc/source/train/images/train.svg
  doc/source/train/user-guides/checkpoints.rst
  doc/source/train/user-guides/configuration-overview.rst
  doc/source/train/user-guides/data-loading-preprocessing.rst
  doc/source/train/user-guides/fault-tolerance.rst
  doc/source/train/user-guides/results.rst
  doc/source/train/user-guides/using-gpus.rst
Labels: docs, train, go

#45893 [HPU] [Serve] [experimental] Add vllm HPU support in vllm example
  doc/source/serve/doc_code/vllm_openai_example.py
  doc/source/serve/tutorials/vllm-example.md
Labels: serve, go

#47134 [doc][ml] add one missing train public API reference + lint checker
  .buildkite/lint.rayci.yml
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  doc/source/train/api/api.rst
Labels: go

#47211 [Dashboard] Making all RPCs to GCS configured with consistent t/o
  python/ray/dashboard/modules/node/node_head.py
Labels: go

#47002 [serve] mark proxy as unready when its routers are aware of zero replicas
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/proxy_router.py
  python/ray/serve/_private/replica_scheduler/common.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_grpc.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/test_standalone_3.py
  python/ray/serve/tests/unit/test_proxy.py
  python/ray/serve/tests/unit/test_proxy_router.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#47206 [core] fix NewGcsClient initial connect timeout formula
  python/ray/_raylet.pyx
Labels: go

#47195 [RLlib; Offline RL] - Cleanup Offline RL algorithms
  rllib/algorithms/bc/tests/test_bc.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/marwil/marwil_offline_prelearner.py
  rllib/algorithms/marwil/tests/test_marwil.py
  rllib/tuned_examples/bc/cartpole_bc.py
  rllib/tuned_examples/marwil/cartpole_marwil.py
Labels: go

#47197 [RLlib] Enhance CI (increase parallelism; remove tf2-eager-tracing learning tests)
  .buildkite/rllib.rayci.yml
  ci/ray_ci/test_linux_tester_container.py
  ci/ray_ci/tester_container.py
Labels: tests-ok, go

#47084 [observability][export-api] Add event data schema for actors
  src/ray/protobuf/BUILD
  src/ray/protobuf/common.proto
  src/ray/protobuf/export_api/export_actor_data.proto
  src/ray/protobuf/export_api/export_event.proto
  src/ray/protobuf/export_api/export_node_data.proto
  src/ray/protobuf/export_api/export_task_event.proto
  src/ray/util/event.cc
  src/ray/util/event.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/proto_schema_backward_compatibility_test.cc
Labels: @author-action-required, go

#47224 [Serve] allow `get_serve_logs_dir` to run outside of Ray's context
  python/ray/serve/_private/logging_utils.py
Labels: go

#47205 [Serve] use serve logger name for logs in serve
  python/ray/serve/_private/api.py
  python/ray/serve/_private/client.py
  python/ray/serve/context.py
  python/ray/serve/gradio_integrations.py
  python/ray/serve/tests/test_standalone_3.py
Labels: go

#47229 setup default serve logger
  python/ray/serve/__init__.py
  python/ray/serve/_private/logging_utils.py
Labels: go
