Repository ray-project/ray, pull requests merged in 2024-09, with the labels that each got.

#47431 [core][experimental] Raise an exception if a DAG is compiled twice
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#46477 [Doc] Add Algolia search to docs
  doc/requirements-doc.txt
  doc/source/conf.py
Labels: docs, go

#47024 [ADAG] Support tasks with multiple return values in aDAG
  python/ray/actor.py
  python/ray/dag/__init__.py
  python/ray/dag/class_node.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/constants.py
  python/ray/dag/dag_node_operation.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule.py
  python/ray/dag/tests/test_class_dag.py
  python/ray/experimental/channel/common.py
Labels: triage, core, go

#44086 [Train] Decouple device-related modules and add Huawei NPU support to Ray Train
  python/ray/_private/ray_constants.py
  python/ray/air/_internal/device_manager/__init__.py
  python/ray/air/_internal/device_manager/cpu.py
  python/ray/air/_internal/device_manager/hpu.py
  python/ray/air/_internal/device_manager/npu.py
  python/ray/air/_internal/device_manager/nvidia_gpu.py
  python/ray/air/_internal/device_manager/torch_device_manager.py
  python/ray/air/_internal/torch_utils.py
  python/ray/train/BUILD
  python/ray/train/_internal/backend_executor.py
  python/ray/train/constants.py
  python/ray/train/tests/test_torch_device_manager.py
  python/ray/train/torch/config.py
  python/ray/train/torch/train_loop_utils.py
Labels: P2, train, go

#47452 [RLlib] Add gradient checks to avoid `nan` gradients in `TorchLearner`.
  rllib/algorithms/algorithm_config.py
  rllib/core/learner/torch/torch_learner.py
Labels: rllib, rllib-torch, go

#47453 [RLlib] Add option to use `torch.lr_scheduler` classes for learning rate schedules.
  rllib/algorithms/algorithm_config.py
  rllib/core/learner/torch/torch_learner.py
Labels: rllib, rllib-torch, go

#47422 [observability][export-api] Write node events
  BUILD.bazel
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/test/gcs_node_manager_export_event_test.cc
  src/ray/gcs/test/gcs_test_util.h
  src/ray/util/event.cc
Labels: go

#46892 Retry transient network errors in WebDatasetDatasource
  python/ray/data/_internal/datasource/webdataset_datasource.py
Labels: triage, data, go

#42121 Add support for 'container' and 'env_vars' in runtime_env
  doc/source/serve/advanced-guides/multi-app-container.md
  python/ray/_private/runtime_env/image_uri.py
  python/ray/runtime_env/runtime_env.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/test_utils.py
  python/ray/tests/conftest_docker.py
  python/ray/tests/runtime_env_container/test_job.py
  python/ray/tests/runtime_env_container/test_serve_telemetry.py
  python/ray/tests/runtime_env_container/test_with_env_vars.py
  python/ray/tests/test_runtime_env_container.py
Labels: go

#47457 [Data] Remove dead `from_*_operator` modules
  python/ray/data/_internal/logical/operators/from_arrow_operator.py
  python/ray/data/_internal/logical/operators/from_items_operator.py
  python/ray/data/_internal/logical/operators/from_numpy_operator.py
  python/ray/data/_internal/logical/operators/from_pandas_operator.py
Labels: go

#47321 [Doc][KubeRay] Update PyTorch Mnist Training doc for KubeRay 1.2.0
  doc/source/cluster/kubernetes/examples/mnist-training-example.md
Labels: P2, docs, kuberay, core, go

#47454 [RLlib] - Add example for PyTorch lr schedulers.
  rllib/BUILD
  rllib/core/learner/torch/torch_learner.py
  rllib/examples/learners/ppo_with_torch_lr_schedulers.py
Labels: rllib, rllib-torch, rllib-docs-or-examples, go

#47427 [RLlib] Examples folder cleanup: ModelV2 -> RLModule wrapper for migrating to new API stack (by config).
  rllib/BUILD
  rllib/examples/rl_modules/classes/modelv2_to_rlm.py
  rllib/examples/rl_modules/migrate_modelv2_to_new_api_stack_by_config.py
Labels: go

#47466 [serve] add streaming to microbenchmarks
  python/ray/serve/_private/benchmarks/common.py
  release/serve_tests/workloads/microbenchmarks.py
Labels: go

#47378 [Data] Skip empty JSON files in `read_json()`
  python/ray/data/_internal/datasource/json_datasource.py
  python/ray/data/tests/test_json.py
Labels: go

#47479 feat: quickstart install button
  doc/source/_static/img/quickstart-with-ray.svg
  doc/source/ray-overview/installation.rst
Labels: go

#47477 feat: introduce Ray Core quickstart button
  doc/source/ray-overview/getting-started.md
Labels: go

#47467 [Data] Remove remote call for initializing `Datasource` in `read_datasource()`
  python/ray/data/read_api.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_formats.py
  python/ray/data/tests/test_splitblocks.py
Labels: go

#47470 [release] simplify the process of getting job logs
  doc/requirements-doc.txt
  release/ray_release/anyscale_util.py
  release/ray_release/job_manager/anyscale_job_manager.py
  release/ray_release/tests/test_anyscale_job_manager.py
  release/requirements_buildkite.in
  release/requirements_buildkite.txt
Labels: go

#47482 [Core] Fix runtime env race condition when uploading the same package concurrently
  python/ray/_private/runtime_env/packaging.py
  python/ray/tests/test_runtime_env_working_dir_4.py
Labels: go

#47490 [core][dashboard] Pass in cluster ID in hex for dashboard, dash agent, rt env agent.
  python/ray/_private/gcs_aio_client.py
  python/ray/_private/node.py
  python/ray/_private/runtime_env/agent/main.py
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/services.py
  python/ray/_private/usage/usage_lib.py
  python/ray/dashboard/agent.py
  python/ray/dashboard/dashboard.py
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/job/job_manager.py
  python/ray/dashboard/modules/job/job_supervisor.py
  python/ray/dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/dashboard/tests/test_dashboard.py
Labels: go

#47489 [core][experimental] Correct `num_input_consumers` for CachedChannel
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#47487 Revert Revert "[Doc] Add Algolia search to docs"
  ci/ray_ci/doc/build_cache.py
  ci/ray_ci/doc/cmd_build.py
  doc/requirements-doc.txt
  doc/source/conf.py
Labels: go

#47407 [observability][export-api] Add event data schema for submission and driver jobs
  src/ray/protobuf/BUILD
  src/ray/protobuf/export_api/export_driver_job_event.proto
  src/ray/protobuf/export_api/export_event.proto
  src/ray/protobuf/export_api/export_submission_job_event.proto
Labels: go

#47303 [observability][export-api] Write actor events
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/util/event.cc
Labels: @author-action-required, go

#47502 [serve] remove outdated microbenchmark release test
  release/release_tests.yaml
  release/serve_tests/workloads/serve_micro_benchmark.py
Labels: go

#47345 [ADAG] Log Executable Task Events
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/constants.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: @author-action-required, go

#47495 [Core] Introduce env var RAY_LOG_TO_DRIVER
  python/ray/_private/ray_constants.py
  python/ray/_private/worker.py
  python/ray/tests/test_advanced_3.py
Labels: go

#47505 [Core] Fix test_runtime_env_working_dir_4 for Windows
  python/ray/tests/test_runtime_env_working_dir_4.py
Labels: go

#47503 feat: add get started free badge
  README.rst
Labels: go

#47193 [observability][export-api] Write task events
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/task_event_buffer_test.cc
  src/ray/gcs/pb_util.h
  src/ray/util/event.cc
Labels: go

#47510 [Core] Improve NodeManager::HandleJobStarted log message
  src/ray/raylet/node_manager.cc
Labels: go

#47512 [Core] Fix aws_cluster_launcher_full
  docker/base-deps/README.md
  docker/ray-deps/README.md
  docker/ray-ml/README.md
  docker/ray/README.md
  docker/retag-lambda/lambda_function.py
  python/ray/autoscaler/aws/tests/aws_config.yaml
  python/ray/autoscaler/gcp/tests/gce_config.yaml
  python/ray/autoscaler/launch_and_verify_cluster.py
  release/release_tests.yaml
Labels: go

#47535 fix quickstart image path
  doc/source/ray-overview/installation.rst
Labels: go

#47500 [RLlib; Off-policy] Add episode sampling to `EpisodeReplayBuffer`.
  rllib/algorithms/dqn/dqn.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
  rllib/utils/replay_buffers/prioritized_episode_buffer.py
  rllib/utils/replay_buffers/tests/test_episode_replay_buffer.py
Labels: rllib, rllib-offline-rl, go

#47141 [aDAG] Allow custom NCCL group for aDAG
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/__init__.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/conftest.py
  python/ray/experimental/channel/gpu_communicator.py
  python/ray/experimental/channel/nccl_group.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
Labels: go

#47543 [aDAG] Fix test_accelerated_dag regression
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#47456 [Data] Remove ineffective retry code in `plan_read_op`
  python/ray/data/_internal/planner/plan_read_op.py
Labels: go

#47549 [Data] Remove unused `requirements_legacy_compat.txt` requirements file
  python/requirements/compat/requirements_legacy_compat.txt
Labels: go

#47546 adding run quickstart button to ray serve stable diffusion tutorial
  doc/source/serve/tutorials/stable-diffusion.md
Labels: go

#47545 add quickstart button to model serving code snippet
  doc/source/_templates/index.html
Labels: go

#47526 [Core] Remove ray._raylet.check_health
  python/ray/_private/internal_api.py
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/scripts/scripts.py
  python/ray/tests/test_advanced_4.py
  python/ray/tests/test_cli.py
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
Labels: go

#47529 [observability][export-api] Write actor events
  BUILD.bazel
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_node_manager_export_event_test.cc
  src/ray/util/event.cc
Labels: go

#47538 [observability][export-api] Write task events
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/task_event_buffer_test.cc
  src/ray/gcs/pb_util.h
Labels: go

#47472 [tune][ci] Fix flaky `test_controller_resume_integration` test suite
  python/ray/tune/tests/execution/test_controller_resume_integration.py
Labels: go

#47532 [RLlib; Offline RL] - Replace GAE in `MARWILOfflinePreLearner` with `GeneralAdvantageEstimation` connector in learner pipeline.
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/marwil/marwil_offline_prelearner.py
  rllib/algorithms/marwil/tests/test_marwil.py
  rllib/offline/offline_prelearner.py
  rllib/tuned_examples/cql/pendulum_cql.py
  rllib/tuned_examples/marwil/cartpole_marwil.py
Labels: rllib, rllib-offline-rl, go

#47341 [Doc] Run pre-commit on data docs
  doc/source/data/api/grouped_data.rst
  doc/source/data/batch_inference.rst
  doc/source/data/custom-datasource-example.rst
  doc/source/data/data-internals.rst
  doc/source/data/examples/images/batch-training.svg
  doc/source/data/execution-configurations.rst
  doc/source/data/images/MongoDB_Logo.svg
  doc/source/data/images/air-preprocessor.svg
  doc/source/data/images/dataset-arch.svg
  doc/source/data/images/dataset-loading-1.svg
  doc/source/data/images/dataset-map.svg
  doc/source/data/images/dataset-pipeline-1.svg
  doc/source/data/images/dataset-pipeline-2-mini.svg
  doc/source/data/images/dataset-pipeline-2.svg
  doc/source/data/images/dataset-pipeline-3.svg
  doc/source/data/images/dataset-read.svg
  doc/source/data/images/dataset-repeat-1.svg
  doc/source/data/images/dataset-repeat-2.svg
  doc/source/data/images/dataset-shuffle.svg
  doc/source/data/images/dataset-spill.svg
  doc/source/data/images/preprocessors.svg
  doc/source/data/loading-data.rst
  doc/source/data/monitoring-your-workload.rst
  doc/source/data/performance-tips.rst
  doc/source/data/saving-data.rst
  doc/source/data/user-guide.rst
Labels: docs, data, go

#47566 [release auto] upgrade docker py library
  release/requirements_buildkite.in
  release/requirements_buildkite.txt
Labels: go

#47513 [data] Change fixture from `shutdown_only` to `ray_start_regular_shared` for `test_csv_read_filter_non_csv_file`
  python/ray/data/tests/test_csv.py
Labels: go

#47567 [release auto] convert release blockers to list
  ci/ray_ci/automation/weekly_green_metric.py
  release/ray_release/test_automation/state_machine.py
Labels: go

#47283 Add perf metrics for 2.35.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#47550 [Data] Remove ordering assumption and unnecessary `override_num_blocks` from `test_parquet_roundtrip`
  python/ray/data/tests/test_parquet.py
Labels: go

#47396 [Core] Reconstruct actor to run lineage reconstruction triggered actor task
  BUILD.bazel
  python/ray/tests/BUILD
  python/ray/tests/test_actor_lineage_reconstruction.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/util/state/common.py
  src/mock/ray/core_worker/actor_creator.h
  src/mock/ray/core_worker/core_worker.h
  src/mock/ray/core_worker/reference_count.h
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/core_worker/actor_creator.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/core_worker/transport/actor_submit_queue.h
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.h
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: go

#47272 [aDAG] support buffered input
  doc/source/ray-core/api/exceptions.rst
  python/ray/dag/BUILD
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/context.py
  python/ray/dag/dag_node.py
  python/ray/dag/dag_node_operation.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/exceptions.py
  python/ray/experimental/channel/__init__.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/experimental/compiled_dag_ref.py
  python/ray/tests/test_channel.py
  serve/serve_40797.log
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/raylet_client/raylet_client.cc
Labels: go

#47514 [aDAG] Clean up arg_to_consumers in _get_or_compile()
  python/ray/dag/compiled_dag_node.py
Labels: go

#47294 [RLlib; Offline RL] Store episodes in state form.
  python/requirements/ml/rllib-requirements.txt
  rllib/env/single_agent_episode.py
  rllib/env/utils/infinite_lookback_buffer.py
  rllib/offline/offline_env_runner.py
  rllib/offline/offline_prelearner.py
  rllib/offline/tests/test_offline_env_runner.py
Labels: rllib, rllib-offline-rl, go

#47480 [Core][aDag] Support multi node multi reader
  python/ray/_raylet.pyx
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_channel.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/object_manager/common.cc
  src/ray/object_manager/common.h
  src/ray/object_manager/plasma/test/mutable_object_test.cc
  src/ray/raylet_client/raylet_client.cc
Labels: go

#47533 Allow control of some serve configuration via env vars
  python/ray/serve/_private/constants.py
Labels: go

#47592 Update incremental build troubleshooting tip with style nits
  doc/source/ray-contribute/docs.md
Labels: go

#47591 [Core] Mark single_node_oom release test as unstable
  release/release_tests.yaml
Labels: go

#47418 [observability][export-api] Write driver job events
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/util/event.cc
  src/ray/util/event.h
Labels: go

#47492 [core][dashboard] push down job_or_submission_id to GCS.
  python/ray/_private/gcs_aio_client.py
  python/ray/_raylet.pyx
  python/ray/dashboard/modules/job/utils.py
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
  python/ray/tests/test_gcs_fault_tolerance.py
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/protobuf/gcs_service.proto
Labels: go

#47462 [Doc][KubeRay] Add description tables for RayCluster Status in the observability doc
  doc/source/cluster/kubernetes/user-guides/observability.md
Labels: P1, kuberay, core, go

#47595 [dashboard] fix syntax warnings on slashes
  python/ray/dashboard/modules/job/utils.py
Labels: go

#47594 [aDAG] Fix ranks ordering for custom NCCL group
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
Labels: go

#47569 [aDAG] Fix type hint for _build_execution_schedule()
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node_operation.py
Labels: go

#47575 [Data] Remove `_default_metadata_providers`
  python/ray/data/_internal/datasource/image_datasource.py
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/datasource/_default_metadata_providers.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_image.py
Labels: go

#47577 Fix windows://:task_event_buffer_test
  BUILD.bazel
  src/mock/ray/gcs/gcs_client/gcs_client.h
  src/ray/core_worker/test/task_event_buffer_export_event_test.cc
  src/ray/core_worker/test/task_event_buffer_test.cc
Labels: go

#47581 [RLlib] RLModule API: `SelfSupervisedLossAPI` for RLModules that bring their own loss (algo independent).
  rllib/algorithms/appo/appo_learner.py
  rllib/algorithms/ppo/ppo_learner.py
  rllib/algorithms/ppo/tf/ppo_tf_learner.py
  rllib/algorithms/ppo/torch/ppo_torch_learner.py
  rllib/connectors/common/batch_individual_items.py
  rllib/core/learner/learner.py
  rllib/core/models/configs.py
  rllib/core/rl_module/apis/__init__.py
  rllib/core/rl_module/apis/self_supervised_loss_api.py
  rllib/examples/connectors/classes/count_based_curiosity.py
  rllib/examples/connectors/classes/euclidian_distance_based_curiosity.py
  rllib/examples/connectors/classes/protobuf_cartpole_observation_decoder.py
  rllib/examples/curiosity/intrinsic_curiosity_model_based_curiosity.py
  rllib/examples/inference/policy_inference_after_training_w_connector.py
  rllib/examples/learners/classes/curiosity_dqn_torch_learner.py
  rllib/examples/learners/classes/curiosity_ppo_torch_learner.py
  rllib/examples/learners/classes/curiosity_torch_learner_utils.py
  rllib/examples/learners/classes/intrinsic_curiosity_learners.py
  rllib/examples/rl_modules/classes/intrinsic_curiosity_model_rlm.py
  rllib/utils/metrics/metrics_logger.py
Labels: go

#47236 [data] Change counts of metrics to rates of metrics
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
Labels: go

#47608 [RLlib] Add restart-failed-env option to new api stack.
  rllib/BUILD
  rllib/env/env_runner.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/evaluation/rollout_worker.py
  rllib/examples/fault_tolerance/__init__.py
  rllib/examples/fault_tolerance/crashing_and_stalling_env.py
  rllib/utils/test_utils.py
Labels: go

#46875 [Train] Update run status and add stack trace to `TrainRunInfo`
  python/ray/air/_internal/util.py
  python/ray/dashboard/modules/train/train_head.py
  python/ray/train/_internal/backend_executor.py
  python/ray/train/_internal/state/schema.py
  python/ray/train/_internal/state/state_manager.py
  python/ray/train/_internal/utils.py
  python/ray/train/tests/test_state.py
  python/ray/train/trainer.py
Labels: go

#47530 [GCS] Optimize `GetAllJobInfo` API for performance
  python/ray/_private/gcs_aio_client.py
  python/ray/_private/state.py
  python/ray/_private/usage/usage_lib.py
  python/ray/_raylet.pyx
  python/ray/dashboard/modules/job/utils.py
  python/ray/dashboard/modules/snapshot/snapshot_head.py
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
  python/ray/includes/global_state_accessor.pxd
  python/ray/includes/global_state_accessor.pxi
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/global_state_accessor.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/protobuf/gcs_service.proto
Labels: go

#47613 Cp 47600
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/tests/test_logging.py
Labels: go

#47600 [Serve] fix default serve logger behavior
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/tests/test_logging.py
  serve/serve_40797.log
Labels: go

#47604 [Data] Fix incorrect pending task size if outputs are empty
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
Labels: go

#47212 [core] make is_gpu, is_actor, root_detached_id fields late bind to workers.
  python/ray/serve/tests/test_metrics.py
  python/ray/tests/test_metrics_agent.py
  python/ray/tests/test_node_manager.py
  python/ray/tests/test_state_api.py
  src/mock/ray/raylet/worker.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/test/task_spec_test.cc
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: go

#47305 [core][adag] Separate the outputs of execute and execute_async to multiple refs or futures to allow clients to retrieve them one at a time (#46908)
  python/ray/_private/worker.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule_gpu.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/experimental/compiled_dag_ref.py
Labels: triage, @author-action-required, core, accelerated-dag, go

#46770 [Core]Fix load_code_from_local to support function without wrapper in local.
  python/ray/_private/function_manager.py
  python/ray/tests/test_basic_2.py
Labels: P1, core, go

#47493 [spark] Improve Ray-on-spark fault tolerance in case of Spark executor being down (e.g. spot instance termination)
  python/ray/autoscaler/_private/spark/node_provider.py
  python/ray/autoscaler/_private/spark/spark_job_server.py
  python/ray/tests/spark/test_basic.py
  python/ray/tests/spark/test_databricks_hook.py
  python/ray/util/spark/cluster_init.py
  python/ray/util/spark/databricks_hook.py
  python/ray/util/spark/start_ray_node.py
Labels: core, go

#47623 [ci] fix blocker counting
  ci/ray_ci/automation/weekly_green_metric.py
Labels: go

#47630 [serve] skip failure test on windows
  python/ray/serve/tests/test_failure.py
Labels: go

#47605 [Data] Refactor custom optimizer rules
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/logical/rules/_user_provided_optimizer_rules.py
Labels: go

#47615 [serve] reorganize replica scheduler classes
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/replica_scheduler/__init__.py
  python/ray/serve/_private/replica_scheduler/common.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/replica_scheduler/replica_scheduler.py
  python/ray/serve/_private/replica_scheduler/replica_wrapper.py
  python/ray/serve/_private/router.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#47633 [python] fix python version range
  python/setup.py
Labels: go

#47304 [rllib] remove tf2 tests on pipeline
  .buildkite/rllib.rayci.yml
Labels: go

#47601 [Core][aDAG] support multi readers in multi node when dag is created from an actor
  python/ray/dag/class_node.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/nccl_group.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/runtime_context.py
  python/ray/tests/test_channel.py
  python/ray/tests/test_nccl_channel.py
Labels: go

#47544 [core] out of band serialization exception
  doc/source/ray-core/doc_code/anti_pattern_out_of_band_object_ref_serialization.py
  doc/source/ray-core/objects/serialization.rst
  doc/source/ray-core/patterns/index.rst
  doc/source/ray-core/patterns/out-of-band-object-ref-serialization.rst
  python/ray/_private/serialization.py
  python/ray/data/_internal/planner/plan_read_op.py
  python/ray/exceptions.py
  python/ray/tests/test_serialization.py
Labels: go

#47656 [aDAG] Print invalid task node info if there is no input
  python/ray/dag/compiled_dag_node.py
Labels: go

#47564 [core][experimental] Allocate a channel for each InputAttributeNode
  python/ray/_private/ray_experimental_perf.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_multi_args_gpu.py
  python/ray/experimental/channel/__init__.py
  python/ray/experimental/channel/common.py
Labels: @author-action-required, go

#47562 [Core] Avoid status copy
  src/ray/common/status.h
Labels: go

#47553 [Data] Add `partitioning` parameter to `read_parquet`
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/datasource/partitioning.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_partitioning.py
Labels: go

#47673 [Data] Add `SERVICE_UNAVAILABLE` to list of retried transient errors
  python/ray/data/context.py
Labels: go

#47680 [Data] Fix bug where Ray Data incorrectly emits progress bar warning
  python/ray/data/_internal/progress_bar.py
  python/ray/data/tests/test_progress_bar.py
Labels: go

#47652 [serve] Additional metadata and context
  python/ray/serve/_private/common.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/replica.py
  python/ray/serve/context.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/test_controller_recovery.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/unit/test_common.py
  python/ray/serve/tests/unit/test_deployment_state.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#47639 [Core][aDAG] Set buffer size to 1 for regression
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#47686 [RLlib] Fix/remove some CI tests and many_ppo release test.
  release/long_running_tests/workloads/many_ppo.py
  rllib/BUILD
  rllib/tuned_examples/ppo/atari_ppo.py
  rllib/utils/test_utils.py
Labels: go

#47574 Add perf metrics for 2.36.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#46767 Added spaces to disallowed char for working dir
  python/ray/_private/runtime_env/packaging.py
Labels: core, go

#47501 [RLlib; Offline RL] - Enable buffering episodes.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/bc/bc.py
  rllib/algorithms/marwil/marwil.py
  rllib/offline/offline_data.py
  rllib/offline/offline_prelearner.py
  rllib/offline/tests/test_offline_data.py
  rllib/offline/tests/test_offline_prelearner.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
  rllib/utils/replay_buffers/prioritized_episode_buffer.py
Labels: rllib, rllib-offline-rl, go

#47451 [RLlib] Add gradient logging as default.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/core/learner/learner.py
  rllib/core/learner/tf/tf_learner.py
  rllib/core/learner/torch/torch_learner.py
  rllib/utils/torch_utils.py
  rllib/utils/typing.py
Labels: go

#47320 [Core][aDAG] Remove timeout for acquiring header for read/write
  src/ray/object_manager/common.cc
Labels: go

#47705 [RLlib] Enhancements for multi-node/multi-GPU training and better EnvRunner error msg.
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/utils/test_utils.py
Labels: rllib, rllib-env, rllib-gpus, rllib-newstack, go

#47701 [Core] Fix broken dashboard cluster page when there are dead nodes
  python/ray/dashboard/datacenter.py
Labels: go

#47698 [serve] small reordering of replica actor methods
  python/ray/serve/_private/replica.py
Labels: go

#47655 [serve] wrap obj ref in result wrapper in deployment response
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/replica_result.py
  python/ray/serve/_private/replica_scheduler/replica_wrapper.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#47714 [Core] Fix broken dashboard worker page
  python/ray/dashboard/datacenter.py
Labels: go

#47719 [Core] Cherry pick #47714, #47701
  python/ray/dashboard/datacenter.py
Labels: go

#47718 [serve] reorder tests BUILD file
  python/ray/serve/tests/BUILD
Labels: go

#47706 [core][experimental] Remove unused attr CompiledDAG._type_hints
  python/ray/dag/compiled_dag_node.py
Labels: go

#47515 re-phrase the streaming executor current usage string
  python/ray/data/_internal/execution/streaming_executor.py
Labels: go

#47445 [Docs][KubeRay] Update RayJob doc for backoffLimit and DELETE_RAYJOB_CR_AFTER_JOB_FINISHES
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
Labels: P1, kuberay, core, go

#47722 [serve] improve tests
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/test_healthcheck.py
  python/ray/serve/tests/test_replica_placement_group.py
Labels: go

#47721 [core][dashboard] Change file_tail_iterator to async.
  python/ray/dashboard/modules/job/job_log_storage_client.py
  python/ray/dashboard/modules/job/job_manager.py
  python/ray/dashboard/modules/job/job_supervisor.py
  python/ray/dashboard/modules/job/sdk.py
  python/ray/dashboard/modules/job/tests/test_utils.py
  python/ray/dashboard/modules/job/utils.py
Labels: go

#47696 [Data] Yield remaining results from async `map_batches`
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/tests/test_map.py
Labels: go

#47724 [Core] Cherry pick #47714, #47701
  python/ray/dashboard/datacenter.py
Labels: go

#47727 [Core] Add test case where there is dead node for /nodes?view=summary endpoint
  python/ray/dashboard/modules/node/tests/test_node.py
Labels: go

#47733 [build] python 3.12 aarch images
  .buildkite/linux_aarch64.rayci.yml
Labels: go

#47563 [Core] Use `nullptr` instead of `NULL`
  src/ray/common/status.cc
  src/ray/common/status.h
Labels: core, go

#46861 [core] Refactor how we store data in redis.
  doc/source/cluster/kubernetes/user-guides/kuberay-gcs-ft.md
  python/ray/_private/gcs_utils.py
  python/ray/_raylet.pyx
  python/ray/includes/global_state_accessor.pxd
  python/ray/includes/global_state_accessor.pxi
  python/ray/tests/test_gcs_utils.py
  src/ray/gcs/gcs_server/store_client_kv.cc
  src/ray/gcs/redis_client.cc
  src/ray/gcs/redis_client.h
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/redis_store_client.h
  src/ray/util/container_util.h
Labels: enhancement, P1, core, core-gcs, go

#47732 [train] update quick start timeout
  python/ray/train/BUILD
Labels: go

#47617 [Dashboard] Optimizing performance of Ray Dashboard
  python/ray/_private/collections_utils.py
  python/ray/dashboard/agent.py
  python/ray/dashboard/consts.py
  python/ray/dashboard/dashboard_metrics.py
  python/ray/dashboard/datacenter.py
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/actor/actor_head.py
  python/ray/dashboard/modules/event/event_agent.py
  python/ray/dashboard/modules/event/event_head.py
  python/ray/dashboard/modules/job/job_head.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/node/node_consts.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/node/tests/test_node.py
  python/ray/dashboard/modules/reporter/reporter_agent.py
  python/ray/dashboard/modules/reporter/reporter_head.py
  python/ray/dashboard/modules/state/state_head.py
  python/ray/dashboard/modules/train/train_head.py
  python/ray/tests/BUILD
  python/ray/tests/test_collections_utils.py
  python/ray/tests/test_object_store_metrics.py
  python/ray/tests/test_output.py
  release/nightly_tests/stress_tests/test_state_api_scale.py
Labels: go

#47730 [Core] Update documentation on `ray.get` on exception behavior
  python/ray/_private/worker.py
Labels: go

#47704 [core][aDAG] Fix a bug where multi arg + exception doesn't work
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/common.py
Labels: go

#47752 [data] Remove ray.kill in ActorPoolMapOperator
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/tests/test_actor_pool_map_operator.py
  python/ray/data/tests/test_map.py
Labels: go

#47764 [serve] add blocking getter to messagequeue
  python/ray/serve/_private/http_util.py
  python/ray/serve/tests/unit/test_http_util.py
Labels: go

#47754 [core][dashboard] Add Pg Id and Format Required Resources in /logical/actors Response
  python/ray/dashboard/datacenter.py
  python/ray/dashboard/modules/actor/actor_head.py
  python/ray/dashboard/modules/actor/tests/test_actor.py
Labels: go

#47772 [fake autoscaler] use check_call in fake multi node test utils
  python/ray/autoscaler/_private/fake_multi_node/docker_monitor.py
  python/ray/autoscaler/_private/fake_multi_node/node_provider.py
  python/ray/autoscaler/_private/fake_multi_node/test_utils.py
Labels: go

#47781 [fake autoscaler] skip empty compose ps lines
  python/ray/autoscaler/_private/fake_multi_node/docker_monitor.py
Labels: go

#47780 [fake autoscaler] remove version field in docker compose
  python/ray/autoscaler/_private/fake_multi_node/node_provider.py
Labels: go

#47784 [tune][fake autoscaler] change head node to 2-cpu in tests
  python/ray/tune/tests/test_multinode_sync.py
Labels: go

#47785 [ci] pin docker client version
  ci/docker/base.gpu.Dockerfile
  ci/docker/base.test.Dockerfile
Labels: go

#47778 [RLlib; docs] Remove old API stack connector docs entirely.
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/rllib-connector.rst
  doc/source/rllib/user-guides.rst
Labels: tests-ok, rllib, rllib-connector, rllib-docs-or-examples, rllib-oldstack-cleanup, go

#47786 [fake autoscaler] remove the redundant mkdir
  python/ray/autoscaler/_private/fake_multi_node/docker_monitor.py
Labels: go

#47692 [Data] Simplify and consolidate progress bar outputs
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/resource_manager.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
Labels: go

#47791 Add perf metrics for 2.37.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#47738 [Serve] add dependencies on openssl
  ci/docker/min.build.Dockerfile
  python/requirements.txt
  python/requirements_compiled.txt
  python/setup.py
Labels: go

#47796 [serve] Fix flaky autoscaling test
  python/ray/serve/tests/test_autoscaling_policy.py
Labels: go

#47748 [docker] Update latest Docker dependencies for 2.36.0 release
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#47330 [Core] Add options(...) function to @ray.remote stubs
  python/ray/_private/worker.py
Labels: P2, core, observability, go

#47802 [docker] Update latest Docker dependencies for 2.36.1 release
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#47801 [docker] Update latest Docker dependencies for 2.36.1 release
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#47468 [observability][export-api] Write submission job events
  BUILD.bazel
  python/ray/_private/event/export_event_logger.py
  python/ray/_private/ray_constants.py
  python/ray/dashboard/modules/event/tests/test_event.py
  python/ray/dashboard/modules/event/tests/test_generate_export_events.py
  python/ray/dashboard/modules/job/common.py
  python/ray/dashboard/modules/job/job_manager.py
  python/ray/dashboard/modules/job/job_supervisor.py
Labels: go

#47747 Move export events to separate folder
  python/ray/_private/event/export_event_logger.py
  python/ray/dashboard/modules/event/tests/test_event.py
  python/ray/dashboard/modules/event/tests/test_generate_export_events.py
  python/ray/tests/test_runtime_env_2.py
  src/ray/core_worker/test/task_event_buffer_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_node_manager_export_event_test.cc
  src/ray/util/event.cc
  src/ray/util/tests/event_test.cc
Labels: go

#47809 [ci] add missing python versions
  ci/ray_ci/docker_container.py
  ci/ray_ci/test_ray_docker_container.py
Labels: go

#47770 [Core] Fix the ray_tasks{State="PENDING_ARGS_FETCH"} metric counting
  python/ray/cluster_utils.py
  python/ray/tests/test_task_metrics.py
  release/benchmarks/object_store/test_object_store.py
  src/ray/raylet/dependency_manager.h
  src/ray/raylet/dependency_manager_test.cc
Labels: go

#47726 [Core] Make Object Store memory default ratio env-configurable
  python/ray/_private/ray_constants.py
  python/ray/_private/resource_spec.py
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/_private/constants.py
Labels: go

#47804 [Data] [Docs] Add docs section for Ray Data progress bars
  doc/source/data/images/dataset-progress-bar.png
  doc/source/data/monitoring-your-workload.rst
Labels: go

#46959 [Azure][Cluster] Only set evictionPolicy to Delete when spot is used
  python/ray/autoscaler/_private/_azure/azure-vm-template.json
Labels: P1, core, go

#47808 [release] stream the full anyscale log to buildkite
  release/ray_release/buildkite/step.py
  release/ray_release/cluster_manager/cluster_manager.py
  release/ray_release/glue.py
  release/ray_release/job_manager/anyscale_job_manager.py
  release/ray_release/scripts/run_release_test.py
  release/ray_release/tests/test_glue.py
Labels: go
