Repository ray-project/ray, pull requests merged in 2024-07, with the labels that each got.

#46341 [Core] Log ray version and ray commit during gcs start
  python/ray/_private/services.py
  src/ray/gcs/gcs_server/gcs_server_main.cc
Labels: go

#46320 Fix for incorrect channel read behavior after accelerated DAG teardown
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
Labels: go

#46356 [api] add oss tag to api lint check
  .buildkite/lint.rayci.yml
Labels: go

#46361 [ci] upgrade manylinux image
  ci/docker/manylinux.Dockerfile
  ci/docker/manylinux.aarch64.wanda.yaml
  ci/docker/manylinux.wanda.yaml
Labels: go

#46365 [data] un-whitelist a bunch of fixed api documentations
  .buildkite/lint.rayci.yml
  ci/pipeline/determine_tests_to_run.py
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
Labels: go

#46283 Throw an exception for unsupported cases in accelerated DAGs
  python/ray/dag/BUILD
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/context.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
Labels: go

#46370 [api] support comment lines in autosummary block
  ci/ray_ci/doc/api.py
  ci/ray_ci/doc/test_api.py
Labels: go

#46259 [ADAG] Support ADAG timeouts
  python/ray/_private/ray_experimental_perf.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/context.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/exceptions.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/compiled_dag_ref.py
  python/ray/includes/common.pxd
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_channel.py
  src/ray/common/status.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/object_manager/common.cc
  src/ray/object_manager/common.h
Labels: go

#45939 [Core] cache `is_async_func()` and `sync_to_async()`
  python/ray/_private/async_compat.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/tests/BUILD
  python/ray/tests/test_async.py
  python/ray/tests/test_async_compat.py
Labels: go

#46236 Fix broken SVG in Ask AI Dialog
  doc/source/_static/js/assistant.js
  doc/source/_templates/extrahead.html
Labels: docs, go

#46364 [data] MapOperator.num_active_tasks should exclude pending actors
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_operators.py
Labels: go

#46375 [Doc] Add setuptools dependency for building docs
  .buildkite/build.rayci.yml
  .readthedocs.yaml
  doc/requirements-doc.txt
Labels: docs, go

#46385 [doc] remove mentioning of `ray-ml` in serve guide
  doc/source/serve/production-guide/docker.md
Labels: go

#46387 Accelerated DAG: Compile fixes for Windows in MutableObjectManager
  src/ray/core_worker/experimental_mutable_object_manager.cc
Labels: go

#45345 Fix broken links in README and in ray.data.Dataset
  README.rst
  python/ray/data/dataset.py
Labels: P2, docs, data, go

#46289 [Data] Fix progress bars being displayed as partially completed in Jupyter notebooks
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/experimental/tqdm_ray.py
Labels: go

#46389 [docs] stop mentioning ray-ml on installation
  doc/source/ray-overview/installation.rst
Labels: go

#46332 Add session name to api/version to easily identify cluster session
  dashboard/modules/job/job_head.py
  dashboard/modules/job/tests/test_http_job_server.py
  dashboard/modules/serve/serve_rest_api_impl.py
  dashboard/modules/version.py
  dashboard/utils.py
Labels: go

#46386 Accelerated DAG: Compile fixes for Windows in MutableObjectManager
  src/ray/core_worker/experimental_mutable_object_manager.cc
Labels: go

#46391 Fix broken log viewer when multi-line logs are printed
  dashboard/client/src/components/LogView/LogVirtualView.tsx
Labels: go

#46243 [doc] auto-generation of class apis
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  doc/source/_templates/autosummary/class_v2.rst
  doc/source/conf.py
  doc/source/data/api/_autogen.rst
  doc/source/data/api/data_iterator.rst
  python/ray/data/iterator.py
  python/ray/util/annotations.py
Labels: go

#43470 [Core] Enable Scaling Down for Multi-Host TPU Replicas
  python/ray/autoscaler/_private/kuberay/node_provider.py
  python/ray/autoscaler/batching_node_provider.py
  python/ray/autoscaler/tags.py
  python/ray/tests/kuberay/test_files/podlist2.yaml
  python/ray/tests/kuberay/test_kuberay_node_provider.py
  python/ray/tests/test_batch_node_provider_unit.py
Labels: kuberay, P1.5, go

#45788 [release] Update Docker dependencies for 2.24.0
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#46400 [release auto] add python 3.12 wheel verify
  .buildkite/release-automation/verify-macos-wheels.sh
  .buildkite/release-automation/wheels.rayci.yml
  ci/ray_ci/automation/ray_wheels_lib.py
Labels: go

#46376 [RLlib] Introduce `Checkpointable` API for RLlib components and subcomponents.
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/core/__init__.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group.py
  rllib/core/rl_module/marl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/core/rl_module/tf/tf_rl_module.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/env/env_runner.py
  rllib/env/env_runner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/evaluation/rollout_worker.py
  rllib/policy/policy.py
  rllib/utils/checkpoints.py
  rllib/utils/typing.py
Labels: go

#46409 [owner] change lint owners to ray CI group
  .github/CODEOWNERS
Labels: go

#46401 [release auto] always release full platforms
  ci/ray_ci/automation/ray_wheels_lib.py
  ci/ray_ci/automation/test_ray_wheels_lib.py
Labels: go

#46421 [ci] remove "external code affected" helper
  .github/workflows/external-code-affected.yml
Labels: go

#46340 [core] Add convenience method `RAY_LOG(INFO).WithField(job_id)`.
  src/ray/common/id.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/util/logging.h
Labels: go

#46426 [ci] filter out .github dir changes
  ci/pipeline/determine_tests_to_run.py
Labels: go

#46416 [ray client] set core team the only owner
  .github/CODEOWNERS
Labels: go

#46410 [owner] remove iycheng from codeowners
  .github/CODEOWNERS
Labels: go

#46417 [ADAG] Fix missing states in channel pickling
  python/ray/dag/BUILD
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/experimental/channel/shared_memory_channel.py
Labels: go

#46415 [wheel] use latest manylinux build image
  ci/docker/manylinux.Dockerfile
  ci/docker/manylinux.aarch64.wanda.yaml
  ci/docker/manylinux.wanda.yaml
  python/README-building-wheels.md
Labels: go

#46321 [RLlib] Moving sampling coordination for `batch_mode=complete_episodes` to `synchronous_parallel_sample`.
  rllib/algorithms/tests/test_callbacks_on_env_runner.py
  rllib/env/single_agent_env_runner.py
Labels: bug, rllib, rllib-evaluation, rllib-samplingbackend, go

#46399 [Serve] add new sets of performance test for `max_ongoing_requests=100` and doc change
  doc/source/serve/advanced-guides/advanced-autoscaling.md
  release/serve_tests/workloads/microbenchmarks.py
Labels: bug, serve, go

#45459 [Train] Add example of pre-training Llama model on Intel Gaudi
  doc/source/train/examples.yml
  doc/source/train/examples/intel_gaudi/llama.ipynb
  doc/source/train/examples/intel_gaudi/llama_pretrain.ipynb
Labels: triage, train, go

#46456 [release-auto] smartly detect ray version and commit
  .buildkite/release-automation/set-ray-version.sh
  .buildkite/release-automation/verify-linux-wheels.sh
  .buildkite/release-automation/verify-macos-wheels.sh
  .buildkite/release-automation/wheels.rayci.yml
Labels: go

#46464 [ray client] use is / is not on type check
  python/ray/util/client/client_pickler.py
  python/ray/util/client/server/proxier.py
Labels: go

#46465 [ray client] lint: do not use comprehension
  python/ray/util/client/server/server.py
Labels: go

#46468 [RLlib] Enable complex action spaces with stateful modules.
  rllib/models/torch/torch_distributions.py
Labels: go

#46474 [RLlib] Replace all `Mapping` typehints with `Dict`.
  rllib/algorithms/sac/torch/sac_torch_learner.py
  rllib/core/models/specs/checker.py
  rllib/core/models/specs/specs_dict.py
  rllib/core/rl_module/tf/tests/test_tf_rl_module.py
  rllib/core/rl_module/torch/tests/test_torch_rl_module.py
  rllib/core/testing/tf/bc_learner.py
  rllib/core/testing/tf/bc_module.py
  rllib/core/testing/torch/bc_learner.py
  rllib/core/testing/torch/bc_module.py
  rllib/examples/learners/train_w_bc_finetune_w_ppo.py
  rllib/examples/rl_modules/classes/random_rlm.py
  rllib/models/tf/tf_distributions.py
  rllib/models/torch/torch_distributions.py
  rllib/policy/policy.py
  rllib/policy/sample_batch.py
  rllib/utils/actor_manager.py
  rllib/utils/debug/summary.py
  rllib/utils/policy.py
Labels: go

#46388 [doc] drop ray-ml reference in runtime env
  doc/source/ray-core/handling-dependencies.rst
Labels: go

#46290 docs: setup unified GTM
  doc/source/_templates/extrahead.html
  doc/source/conf.py
Labels: go

#45881 [Serve] Avoid looping over all snapshot ids for each long poll request
  python/ray/serve/_private/long_poll.py
Labels: go

#46471 [release auto] fix bash styling stuff in osx wheel verify script
  .buildkite/release-automation/verify-macos-wheels.sh
Labels: go

#46237 [Doc] Update visibility of the search button
  doc/source/_static/css/custom.css
Labels: P1, docs, go

#46466 [doc] update read_csv api comment
  python/ray/data/read_api.py
Labels: go

#46393 CI: enable jemalloc in release tests
  release/ray_release/byod/byod.Dockerfile
Labels: go

#46460 [Core] Add object back to memory store when object recovery is skipped
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
Labels: go

#45352 [Data] Change offsets to int64 and change to LargeList for ArrowTensorArray
  python/ray/air/tests/test_tensor_extension.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/data/tests/test_tensor.py
Labels: P1, data, go

#46436 [RLlib] - Enable multi-learner setup for hybrid stack BC
  rllib/algorithms/bc/bc.py
  rllib/policy/sample_batch.py
Labels: rllib, rllib-offline-rl, rllib-oldstack-cleanup, go

#46358 [core] move cluster_id to GcsClientOptions, and sends RPC to get it if absent.
  cpp/src/ray/runtime/native_ray_runtime.cc
  cpp/src/ray/util/process_helper.cc
  cpp/src/ray/util/process_helper.h
  python/ray/_private/internal_api.py
  python/ray/_private/metrics_agent.py
  python/ray/_private/node.py
  python/ray/_private/services.py
  python/ray/_private/test_utils.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/cluster_utils.py
  python/ray/includes/common.pxd
  python/ray/includes/common.pxi
  python/ray/tests/test_object_spilling.py
  src/mock/ray/gcs/gcs_client/gcs_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/io_ray_runtime_gcs_GlobalStateAccessor.cc
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/test/gcs_client_reconnection_test.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_client/test/usage_stats_client_test.cc
  src/ray/gcs/gcs_client/usage_stats_client.cc
  src/ray/gcs/gcs_client/usage_stats_client.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
  src/ray/raylet/main.cc
  src/ray/rpc/client_call.h
Labels: go

#46149 Add section on launching clusters on Kubernetes to Getting Started
  doc/source/ray-overview/getting-started.md
Labels: go

#46491 [ci] remove nvidia-disable-check
  ci/ray_ci/linux_container.py
Labels: go

#45836 docs: warn about running multiple local Ray instances
  python/ray/_private/worker.py
Labels: go

#46494 [Core] Task status should start with PENDING_ARGS_AVAIL when retry
  src/ray/core_worker/task_manager.cc
Labels: go

#46363 [Data] Prevent `from_pandas` from combining input blocks
  python/ray/data/_internal/pandas_block.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_pandas.py
Labels: go

#46488 [core] catch exception in async_callback
  python/ray/_raylet.pyx
Labels: go

#46509 [rllib] only run rllib gpu tests on rllib changes
  .buildkite/rllib.rayci.yml
  ci/pipeline/determine_tests_to_run.py
Labels: go

#46439 [Dashboard] Correct the event time of failed tasks
  src/ray/gcs/gcs_server/gcs_task_manager.cc
Labels: go

#46515 Revert "docs: warn about running multiple local Ray instances (#45836)"
  python/ray/_private/worker.py
Labels: go

#46516 [core] add "last exception" to error message when GCS connection fails in ray.init().
  python/ray/_private/node.py
Labels: go

#46458 [doc] buildifier format doc/BUILD
  doc/BUILD
Labels: go

#46405 [wheel] exclude 3rd-party `__pycache__` and `tests` dir
  python/setup.py
Labels: go

#46487 [github action] limit branches of pr sync hook
  .github/workflows/on_pull_request_synchronized.yml
Labels: go

#46518 [Core] Rename state_ts to state_ts_ns to indicate that the unit is nanosecond
  python/ray/tests/test_state_api.py
  python/ray/util/state/common.py
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/gcs.proto
Labels: go

#46490 [image] fix manual docker image building script
  build-docker.sh
  doc/source/ray-overview/installation.rst
  docker/README.md
  docker/base-deps/README.md
  docker/development/Dockerfile
  docker/examples/Dockerfile
Labels: go

#46517 Revert https://github.com/ray-project/ray/pull/46393
  release/ray_release/byod/byod.Dockerfile
Labels: go

#46520 [ci] do not block windows on release automation run
  .buildkite/linux_aarch64.rayci.yml
  .buildkite/windows.rayci.yml
Labels: go

#46484 [Release] Use with clause to make sure result json file is closed properly
  release/autoscaling_tests/run.py
  release/benchmarks/distributed/many_nodes_tests/actor_test.py
  release/benchmarks/distributed/many_nodes_tests/multi_master_test.py
  release/benchmarks/object_store/test_object_store.py
  release/benchmarks/single_node/test_single_node.py
  release/nightly_tests/placement_group_tests/long_running_performance_test.py
  release/nightly_tests/placement_group_tests/pg_run.py
  release/nightly_tests/placement_group_tests/placement_group_performance_test.py
  release/nightly_tests/stress_tests/test_state_api_scale.py
  release/nightly_tests/stress_tests/test_state_api_with_other_tests.py
Labels: go

#46431 [core][experimental] Support multiple readers for IntraProcessChannel
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
Labels: core, accelerated-dag, go

#46508 [core][experimental] Check whether the channel is closed for the shared memory write operation
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
Labels: go

#46523 fix structured logging to use explicit value
  python/ray/_private/ray_logging/filters.py
  python/ray/_private/ray_logging/formatters.py
Labels: go

#46533 [ci] fix bazel version in window flaky tests
  .buildkite/windows.rayci.yml
Labels: go

#46532 [dashboard] revert back to pushd and popd for win build
  python/build-wheel-windows.sh
Labels: go

#46540 [RLlib] Cleanup examples folder 20: Add example script for new API stack and two separate optimizers (w/ different learning rates).
  rllib/BUILD
  rllib/algorithms/sac/torch/sac_torch_learner.py
  rllib/core/learner/learner.py
  rllib/core/learner/tf/tf_learner.py
  rllib/core/learner/torch/torch_learner.py
  rllib/examples/learners/classes/separate_vf_lr_and_optimizer_learner.py
  rllib/examples/learners/custom_loss_fn_simple.py
  rllib/examples/learners/separate_vf_lr_and_optimizer.py
Labels: go

#46535 [serve] deflake test_serve_dashboard
  python/ray/dashboard/BUILD
Labels: go

#46369 [Data] Update `Dataset.count()` to avoid unnecessarily keeping `BlockRef`s in-memory
  doc/source/data/api/dataset.rst
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_formats.py
Labels: go

#46359 [core] Add more methods to GcsClient Accessors.
  python/ray/dashboard/modules/serve/tests/test_serve_dashboard.py
  python/ray/serve/_private/storage/kv_store.py
  python/ray/serve/tests/test_gcs_failure.py
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
Labels: go

#46526 [Data] Add `decord` to test dependencies
  python/requirements/ml/data-test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#46530 [doc][api] recursively get all rsts from the head file
  ci/ray_ci/doc/autodoc.py
  ci/ray_ci/doc/test_autodoc.py
Labels: go

#46544 [Data] Add `snowflake-connector-python` to test requirements
  python/requirements/ml/data-test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#46546 [Data] Remove dead `InputDataBuffer._set_num_output_blocks`
  python/ray/data/_internal/execution/operators/input_data_buffer.py
Labels: go

#46463 [data] lint fixes on unnecessary comprehension
  python/ray/data/dataset.py
  python/ray/data/tests/util.py
Labels: go

#46547 [Data] Rename `_estimated_output_blocks` to `_estimated_num_output_bundles`
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/limit_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/tests/test_operators.py
Labels: go

#46543 [doc][api] fix check for auto-generated api docs
  .buildkite/lint.rayci.yml
  ci/lint/lint.sh
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
Labels: go

#46541 [Data] Set for better performance in loop
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/planner/exchange/sort_task_spec.py
  python/ray/data/iterator.py
  python/ray/data/preprocessors/encoder.py
Labels: go

#46555 upgrade cuda
  .buildkite/ml.rayci.yml
  ci/docker/base.gpu.Dockerfile
  ci/docker/doctest.build.Dockerfile
  ci/docker/manylinux.Dockerfile
  ci/docker/manylinux.aarch64.wanda.yaml
  ci/docker/manylinux.wanda.yaml
  ci/ray_ci/container.py
  doc/BUILD
  doc/source/tune/examples/BUILD
  python/ray/tests/horovod/BUILD
  python/ray/train/BUILD
  python/ray/train/tests/test_examples.py
  python/ray/train/tests/test_gpu_examples.py
  python/ray/train/tests/test_training_iterator.py
  python/requirements/ml/dl-cpu-requirements.txt
  python/requirements/ml/dl-gpu-requirements.txt
  python/requirements_compiled.txt
  rllib/core/learner/tests/test_learner_group.py
Labels: go

#46335 [core] Add 1s timeout in RPC to CoreWorkerService.NumPendingTasks in GcsJobManager::HandleGetAllJobInfo
  python/ray/tests/test_state_api.py
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/protobuf/gcs.proto
  src/ray/rpc/worker/core_worker_client.h
Labels: go

#46549 docs: update GTM tag
  doc/source/_templates/extrahead.html
Labels: go

#46527 [Serve] Add status code to retry when request timed out
  doc/source/serve/advanced-guides/performance.md
Labels: serve, docs, go

#46475 Update starting-ray.rst to fix broken link
  doc/source/ray-core/starting-ray.rst
Labels: go

#46554 [Core] Replace lambda default arguments
  python/ray/_private/runtime_env/uri_cache.py
  python/ray/autoscaler/_private/load_metrics.py
Labels: docs, core, go

#46568 [release auto] block pre-release jobs when RAY_VERSION is specified
  .buildkite/release-automation/pre_release.rayci.yml
Labels: go

#46480 [Serve] Fix return type of `_DeploymentHandleBase._get_or_create_router`
  python/ray/serve/handle.py
Labels: go

#46432 [Data] Add unit to progress bars
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/_internal/execution/operators/base_physical_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/_internal/planner/exchange/sort_task_spec.py
  python/ray/data/_internal/progress_bar.py
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/tests/test_progress_bar.py
  python/ray/experimental/tqdm_ray.py
  python/ray/tests/test_chaos.py
  release/nightly_tests/chaos_test/test_chaos_basic.py
  release/nightly_tests/stress_tests/test_threaded_actors.py
Labels: go

#46572 [ci] deflake //python/ray/tests:test_implicit_resource
  python/ray/tests/BUILD
Labels: go

#46542 docs: update ray summit banner text
  doc/source/conf.py
Labels: go

#46560 [ci] deflake serve window tests
  .buildkite/windows.rayci.yml
  python/ray/serve/tests/BUILD
Labels: go

#46074 [core][logging] Add a unix timestamp for the structured logger
  python/ray/_private/ray_logging/constants.py
  python/ray/_private/ray_logging/formatters.py
  python/ray/_private/ray_logging/logging_config.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/tests/test_logging_2.py
Labels: go

#46493 [Data] Replace lambda mutable default arguments
  python/ray/data/_internal/aggregate.py
  python/ray/data/_internal/datasource/csv_datasink.py
  python/ray/data/_internal/datasource/json_datasink.py
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/aggregate/_aggregate.py
  python/ray/data/dataset.py
  python/ray/data/tests/conftest.py
Labels: P1, docs, data, go

#46557 [data][doc] auto-generate dataset api documentation
  doc/source/_templates/autosummary/class_v2.rst
  doc/source/conf.py
  doc/source/data/api/_autogen.rst
  doc/source/data/api/data_iterator.rst
  doc/source/data/api/dataset.rst
  python/ray/data/dataset.py
  python/ray/util/annotations.py
Labels: go

#46455 [Data] Deprecate `Dataset.get_internal_block_refs()`
  python/ray/data/_internal/execution/interfaces/ref_bundle.py
  python/ray/data/dataset.py
  python/ray/data/random_access_dataset.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_pandas.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_size_estimation.py
  python/ray/data/tests/test_split.py
  python/ray/data/tests/test_text.py
  python/ray/data/tests/test_transform_pyarrow.py
  python/ray/data/tests/test_zip.py
Labels: go

#46574 [test] runtime env pip version pinned to 24.1.2 for python 3.12 support
  python/ray/tests/test_runtime_env_conda_and_pip_4.py
  python/ray/tests/test_runtime_env_conda_and_pip_5.py
Labels: go

#46578 [test] skip test_run_in_virtualenv in py312
  python/ray/tests/test_runtime_env_conda_and_pip_4.py
Labels: go

#46203 [Docs] Fix dark mode table visibility issues
  doc/source/_static/css/custom.css
Labels: go

#46558 Update shipped dependencies for 2.32.0 pre cut
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#46587 [data] fix doc build
  doc/source/data/api/dataset.rst
Labels: go

#46585 setup-dev.py: remove outdated dashboard link
  python/ray/setup-dev.py
Labels: go

#46581 [test] disable test_runtime_env_cache_with_pip_check on python 3.12
  python/ray/tests/test_runtime_env_conda_and_pip_5.py
Labels: go

#46589 [image] upgrade to 22.04 for real
  ci/docker/ray.cpu.base.aarch64.wanda.yaml
  ci/docker/ray.cpu.base.wanda.yaml
  ci/docker/ray.cuda.base.aarch64.wanda.yaml
  ci/docker/ray.cuda.base.wanda.yaml
  ci/docker/runtime_env_container/Dockerfile
  release/ray_release/byod/byod_horovod_test.sh
Labels: go

#46345 [Docs][Kuberay] Create an example doc for Modin
  doc/source/cluster/kubernetes/examples.md
  doc/source/cluster/kubernetes/examples/modin-example.md
Labels: go

#46594 [RLlib] Fix `sample_timeout_s` setting being ignored by PPO/DQN/SAC/... on old API stack.
  rllib/algorithms/bc/bc.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/ppo/ppo.py
  rllib/execution/rollout_ops.py
Labels: go

#46595 [ci] split window serve jobs into two
  .buildkite/windows.rayci.yml
  python/ray/serve/tests/BUILD
Labels: go

#46591 [test] fix test_pip_with_env_vars for python 3.12 support
  python/ray/tests/test_runtime_env_complicated.py
Labels: go

#46602 [ci] fix horovod master test
  release/ray_release/byod/byod_horovod_master_test.sh
Labels: go

#45927 [doc] correct a typo in the parameter server example
  doc/source/ray-core/examples/plot_parameter_server.ipynb
Labels: go

#46562 [Core] Fix ObjectFetchTimedOutError
  python/ray/tests/test_reconstruction_2.py
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/protobuf/pubsub.proto
Labels: go

#46395 [Train] Update run status and actor status for train runs.
  python/ray/dashboard/modules/train/train_head.py
  python/ray/train/BUILD
  python/ray/train/_internal/backend_executor.py
  python/ray/train/_internal/state/schema.py
  python/ray/train/_internal/state/state_manager.py
  python/ray/train/tests/test_state.py
  python/ray/train/tests/test_train_head.py
  python/ray/train/trainer.py
Labels: go

#46599 small ui fixes to the serve page
  python/ray/dashboard/client/src/common/CodeDialogButton/CodeDialogButton.tsx
  python/ray/dashboard/client/src/pages/serve/ServeDeploymentsListPage.tsx
Labels: go

#46457 [doc test] tests hashes of external examples
  doc/BUILD
  doc/external/external_code.txt
  doc/external/test_hashes.py
Labels: go

#46565 [train] fix tensorflow example by using ScalingConfig
  python/ray/train/examples/tf/tensorflow_autoencoder_example.py
  python/ray/train/examples/tf/tune_tensorflow_autoencoder_example.py
Labels: go

#46498 Accelerated DAG: Support channel writes larger than the max gRPC payload size
  python/ray/dag/context.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
  src/ray/protobuf/node_manager.proto
  src/ray/raylet_client/raylet_client.cc
Labels: go

#46640 fix beyond the basics cards column width
  doc/source/_static/css/index.css
Labels: go

#46597 docs: update readme to include debugger
  README.rst
Labels: go

#46637 [ADAG] Fix missing method GetObjectBackingStore on Windows
  src/ray/core_worker/experimental_mutable_object_manager.cc
Labels: go

#46576 [Train] Replace lambda default arguments
  python/ray/train/_internal/storage.py
  python/ray/train/tests/dummy_preprocessor.py
Labels: docs, train, go

#46596 [Tune] Replace lambda default arguments
  python/ray/tune/tests/test_trial_scheduler.py
Labels: tune, docs, go

#46639 [test] skip dask tests on Python 3.12+
  python/ray/util/dask/tests/test_dask_callback.py
  python/ray/util/dask/tests/test_dask_optimization.py
  python/ray/util/dask/tests/test_dask_scheduler.py
  python/requirements/ml/data-requirements.txt
  python/requirements_compiled.txt
Labels: go

#46556 [dashboard] don't prepend "0" or "1" on non streaming logs
  python/ray/dashboard/client/src/pages/job/JobDriverLogs.component.test.tsx
  python/ray/dashboard/client/src/service/log.ts
  python/ray/dashboard/client/src/service/log.unit.test.ts
  python/ray/dashboard/modules/state/state_head.py
  python/ray/util/state/api.py
Labels: dashboard, go

#46646 [Data] Add `AWS Error UNKNOWN` to list of retried write errors
  python/ray/data/context.py
Labels: go

#46256 [RFC][python 3.12] upgrade pytorch
  .buildkite/ml.rayci.yml
  ci/docker/base.gpu.Dockerfile
  ci/docker/doctest.build.Dockerfile
  ci/docker/ml.build.Dockerfile
  ci/ray_ci/container.py
  doc/BUILD
  doc/source/tune/examples/BUILD
  python/ray/tests/horovod/BUILD
  python/ray/train/BUILD
  python/ray/train/tests/test_examples.py
  python/ray/train/tests/test_gpu_examples.py
  python/ray/train/tests/test_training_iterator.py
  python/requirements/ml/core-requirements.txt
  python/requirements/ml/data-test-requirements.txt
  python/requirements/ml/dl-cpu-requirements.txt
  python/requirements/ml/dl-gpu-requirements.txt
  python/requirements/ml/rllib-requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  release/ray_release/byod/byod_horovod_master_test.sh
  release/ray_release/byod/byod_horovod_test.sh
  release/ray_release/byod/requirements_byod_3.9.in
  release/ray_release/byod/requirements_byod_3.9.txt
  release/release_tests.yaml
  rllib/core/learner/tests/test_learner_group.py
Labels: go

#46347 [serve] configure logging for build app task
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/controller.py
  python/ray/serve/tests/unit/test_application_state.py
Labels: go

#46427 [serve] remove max_concurrent_queries
  doc/source/serve/advanced-guides/advanced-autoscaling.md
  doc/source/serve/autoscaling-guide.md
  doc/source/serve/configure-serve-deployment.md
  doc/source/serve/doc_code/load_shedding.py
  doc/source/serve/production-guide/best-practices.md
  java/serve/src/main/java/io/ray/serve/config/DeploymentConfig.java
  java/serve/src/main/java/io/ray/serve/deployment/Deployment.java
  java/serve/src/main/java/io/ray/serve/deployment/DeploymentCreator.java
  java/serve/src/main/java/io/ray/serve/router/ReplicaSet.java
  python/ray/serve/_private/application_state.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_handle_api.py
  python/ray/serve/tests/test_max_queued_requests.py
  python/ray/serve/tests/unit/test_schema.py
Labels: go

#45549 Update accelerators.rst
  doc/source/ray-core/scheduling/accelerators.rst
Labels: core, core-hardware, go

#46564 [Ray Dashboard] make memory profile href link relative path
  python/ray/dashboard/client/src/common/ProfilingLink.tsx
Labels: dashboard, triage, @external-author-action-required, observability, go

#46659 [core] remove microbenchmark from postmerge
  .buildkite/release.rayci.yml
Labels: go

#45432 fix docs: unindent blocks to allow copy pasting more easily
  doc/source/ray-overview/getting-started.md
Labels: triage, docs, go

#46638 [Data] Update outdated `ExecutionPlan` docstring
  python/ray/data/_internal/plan.py
Labels: triage, data, go

#46575 [Data] Update `ExecutionPlan.execute_to_iterator()` to return `RefBundles` instead of `(Block, BlockMetadata)`
  python/ray/data/BUILD
  python/ray/data/_internal/block_batching/iter_batches.py
  python/ray/data/_internal/iterator/iterator_impl.py
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/tests/block_batching/test_iter_batches.py
  python/ray/data/tests/block_batching/test_util.py
Labels: go

#46655 [RLlib] Rename instances of `Impala` to `IMPALA` and `Appo` to `APPO`.
  rllib/algorithms/__init__.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/appo_learner.py
  rllib/algorithms/appo/tf/appo_tf_learner.py
  rllib/algorithms/appo/torch/appo_torch_learner.py
  rllib/algorithms/impala/__init__.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/algorithms/impala/impala_torch_policy.py
  rllib/algorithms/impala/tests/test_impala.py
  rllib/algorithms/impala/tf/impala_tf_learner.py
  rllib/algorithms/impala/torch/impala_torch_learner.py
  rllib/algorithms/registry.py
  rllib/algorithms/tests/test_registry.py
  rllib/algorithms/tests/test_worker_failures.py
  rllib/tests/test_supported_multi_agent.py
  rllib/tests/test_supported_spaces.py
  rllib/tuned_examples/impala/cartpole-impala-separate-losses.py
  rllib/tuned_examples/impala/cartpole_impala.py
  rllib/tuned_examples/impala/multi_agent_cartpole_impala.py
  rllib/tuned_examples/impala/multi_agent_cartpole_impala_old_api_stack.py
  rllib/tuned_examples/impala/pendulum_impala.py
  rllib/tuned_examples/impala/pong_impala.py
  rllib/tuned_examples/impala/pong_impala_pb2_hyperopt.py
  rllib/utils/exploration/tests/test_explorations.py
  rllib/utils/tests/test_errors.py
Labels: go

#46634 [Core] Make working_dir support files created before 1980
  python/ray/_private/runtime_env/packaging.py
  python/ray/tests/test_runtime_env_working_dir_2.py
Labels: go

#46414 [serve] Update docs on max ongoing requests default change
  doc/source/serve/configure-serve-deployment.md
Labels: go

#46647 [Data] Always print traceback for internal exceptions
  python/ray/data/exceptions.py
  python/ray/data/tests/test_exceptions.py
Labels: go

#45550 [core][runtime_env] Allow full path in conda runtime env.
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/conda_utils.py
  python/ray/tests/test_runtime_env_complicated.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
Labels: triage, core, go

#46392 [serve] remove target_num_ongoing_requests_per_replica
  doc/source/serve/advanced-guides/advanced-autoscaling.md
  doc/source/serve/autoscaling-guide.md
  java/serve/src/main/java/io/ray/serve/config/AutoscalingConfig.java
  python/ray/dashboard/modules/serve/serve_rest_api_impl.py
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/deployment.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/unit/test_autoscaling_policy.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_deployment_class.py
  python/ray/serve/tests/unit/test_schema.py
  src/ray/protobuf/serve.proto
Labels: go

#46662 [py12] upgrade torch version again
  .buildkite/ml.rayci.yml
  ci/docker/base.gpu.Dockerfile
  ci/docker/doctest.build.Dockerfile
  ci/docker/ml.build.Dockerfile
  ci/ray_ci/container.py
  ci/ray_ci/macos/macos_ci.sh
  ci/ray_ci/macos/macos_ci_build.sh
  ci/ray_ci/windows/build_base.sh
  doc/BUILD
  doc/source/tune/examples/BUILD
  python/ray/tests/BUILD
  python/ray/tests/horovod/BUILD
  python/ray/train/BUILD
  python/ray/train/tests/test_examples.py
  python/ray/train/tests/test_gpu_examples.py
  python/ray/train/tests/test_training_iterator.py
  python/requirements/ml/core-requirements.txt
  python/requirements/ml/data-test-requirements.txt
  python/requirements/ml/dl-cpu-requirements.txt
  python/requirements/ml/dl-gpu-requirements.txt
  python/requirements/ml/rllib-requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  release/ray_release/byod/byod_horovod_master_test.sh
  release/ray_release/byod/byod_horovod_test.sh
  release/ray_release/byod/requirements_byod_3.9.in
  release/ray_release/byod/requirements_byod_3.9.txt
  release/release_tests.yaml
  rllib/core/learner/tests/test_learner_group.py
Labels: go

#46153 [RLlib] Single-GPU, multi-CPU (Learner), multi-GPU tests for DQN/SAC single-/multi-agent setups in new API stack.
  rllib/BUILD
  rllib/algorithms/dqn/torch/dqn_rainbow_torch_learner.py
  rllib/algorithms/sac/sac.py
  rllib/algorithms/sac/torch/sac_torch_learner.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/tuned_examples/dqn/multi_agent_cartpole_dqn.py
  rllib/tuned_examples/sac/multi_agent_pendulum_sac.py
Labels: go

#46583 Fix return type annotation for parse_placement_group_resource_str.
  python/ray/autoscaler/_private/util.py
Labels: go
