Repository ray-project/ray, pull requests merged in 2024-06, with the labels that each got.

#45497 [Core] Expose NodeDeathInfo in ActorDiedError
  dashboard/tests/test_dashboard.py
  python/ray/exceptions.py
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_draining.py
  python/ray/tests/test_node_death.py
  python/ray/tests/test_runtime_env_agent.py
  src/ray/core_worker/transport/direct_actor_task_submitter.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/protobuf/common.proto
  src/ray/protobuf/gcs.proto
Labels: go

#44572 [Core] integrate amdsmi in AMDAcceleratorManager
  python/ray/_private/accelerators/amd_gpu.py
  python/ray/_private/thirdparty/pyamdsmi/__init__.py
  python/ray/_private/thirdparty/pyamdsmi/pyamdsmi.py
  python/ray/tests/accelerators/test_amd_gpu.py
Labels: P1, @external-author-action-required, core, go

#45660 [Core] Improve log message using structured logging
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
Labels: go

#45604 [core][bugfix] Fix the C++ GcsClient Del not respecting del_by_prefix
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
Labels: go

#45663 [core] add chaos_many_tasks/actors terminate instance cases
  python/ray/_private/test_utils.py
  release/nightly_tests/chaos_test/compute_template.yaml
  release/nightly_tests/chaos_test/test_chaos_basic.py
  release/release_tests.yaml
Labels: go

#45670 [core] add non-windows guard for logging tests
  src/ray/util/tests/logging_test.cc
Labels: go

#45621 [ray] python 3.12
  .buildkite/build.rayci.yml
  .buildkite/core.rayci.yml
  .buildkite/windows.rayci.yml
  ci/env/install-dependencies.sh
  ci/ray_ci/builder_container.py
  ci/ray_ci/container.py
  python/build-wheel-macos.sh
  python/build-wheel-manylinux2014.sh
  python/ray/tests/test_mpi.py
Labels: go

#45673 [Data] Improve fractional CPU/GPU formatting
  python/ray/data/_internal/execution/streaming_executor.py
Labels: go

#45681 [RLlib] Cleanup examples folder #14: Add example script for how to resume a tune.Tuner.fit() experiment from a checkpoint.
  rllib/BUILD
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/dreamerv3/dreamerv3.py
  rllib/algorithms/dreamerv3/tf/dreamerv3_tf_learner.py
  rllib/algorithms/dreamerv3/utils/summaries.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/sac/torch/sac_torch_learner.py
  rllib/examples/checkpoints/checkpoint_by_custom_criteria.py
  rllib/examples/checkpoints/continue_training_from_checkpoint.py
  rllib/examples/checkpoints/restore_1_of_n_agents_from_checkpoint.py
  rllib/utils/metrics/metrics_logger.py
Labels: go

#45683 [RLlib] DreamerV3 reporting fix for `config.report_dream_data=True`.
  rllib/algorithms/dreamerv3/dreamerv3.py
  rllib/algorithms/dreamerv3/tf/dreamerv3_tf_learner.py
  rllib/algorithms/dreamerv3/utils/summaries.py
Labels: go

#45682 [RLlib] Enhance env-rendering callback.
  rllib/examples/envs/env_rendering_and_recording.py
Labels: go

#45686 [ci] revert python 3.12 wheel for windows + mac
  .buildkite/windows.rayci.yml
  python/build-wheel-macos.sh
Labels: go

#45668 [ci] use bazelisk to build and test on windows
  ci/docker/windows.build.wanda.yaml
  ci/ray_ci/windows/build_base.sh
  ci/ray_ci/windows/install_bazelisk.ps1
  ci/ray_ci/windows/install_tools.sh
Labels: go

#45688 [Core] Fix test_amd_gpu.py on mac
  python/ray/tests/accelerators/test_amd_gpu.py
Labels: go

#45397 [Cluster launcher] [Azure] add option for eviction policy in azure VM template
  python/ray/autoscaler/_private/_azure/azure-vm-template.json
Labels: triage, core, go

#45696 [ray] python 3.12 for macos
  python/build-wheel-macos.sh
Labels: go

#45694 [ray] python 3.12 for windows
  .buildkite/windows.rayci.yml
  python/build-wheel-windows.sh
Labels: go

#45513 [core][runtime_env] Retry on read error in rt env agent client response read
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/tests/test_runtime_env.py
  src/ray/raylet/runtime_env_agent_client.cc
Labels: go

#45705 [core] refactor worker sys path test
  python/ray/tests/test_basic_5.py
Labels: go

#45115 [Doc] Fix broken references in Ray Core documentation
  doc/source/ray-core/api/utility.rst
  doc/source/ray-core/scheduling/placement-group.rst
  doc/source/ray-more-libs/dask-on-ray.rst
  doc/source/ray-references/glossary.rst
  python/ray/_private/worker.py
  python/ray/air/integrations/mlflow.py
  python/ray/util/actor_pool.py
  python/ray/util/placement_group.py
  python/ray/util/state/api.py
Labels: go

#45646 [core][experimental] Add mocked tests for accelerated DAG NCCL channel
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/conftest.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/tests/BUILD
  python/ray/tests/test_nccl_channel.py
  python/ray/util/collective/collective_group/nccl_util.py
Labels: @author-action-required, go

#45712 [Core] Enable logging_test on Windows
  src/ray/util/tests/logging_test.cc
  src/ray/util/util.h
Labels: go

#45717 [Core] Rename ray._private.structured_logging to ray._private.ray_logging
  python/ray/__init__.py
  python/ray/_private/ray_logging/__init__.py
  python/ray/_private/ray_logging/constants.py
  python/ray/_private/ray_logging/filters.py
  python/ray/_private/ray_logging/formatters.py
  python/ray/_private/ray_logging/logging_config.py
  python/ray/_private/structured_logging/__init__.py
  python/ray/_private/worker.py
  python/ray/job_config.py
  python/ray/tests/BUILD
  python/ray/tests/test_logging_2.py
  src/ray/util/logging.h
Labels: go

#45706 [data] Refactor planner.py
  python/ray/data/_internal/execution/operators/input_data_buffer.py
  python/ray/data/_internal/logical/operators/input_data_operator.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/_internal/planner/plan_from_op.py
  python/ray/data/_internal/planner/plan_input_data_op.py
  python/ray/data/_internal/planner/plan_limit_op.py
  python/ray/data/_internal/planner/plan_read_op.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/planner/plan_write_op.py
  python/ray/data/_internal/planner/planner.py
Labels: go

#45703 [ray] python 3.12 doc
  doc/source/ray-overview/installation.rst
Labels: go

#45722 [ray] build the arm64 linux wheel for python 3.12
  .buildkite/linux_aarch64.rayci.yml
Labels: go

#45707 [ci][release] add default cluster environment variable
  release/ray_release/test.py
  release/ray_release/tests/test_cluster_manager.py
  release/ray_release/tests/test_glue.py
  release/ray_release/tests/test_test.py
Labels: go

#45728 [Data] Rename `ParquetBaseDatasource` to `ParquetBulkDatasource`
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/parquet_bulk_datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_parquet.py
Labels: go

#45727 [Data] Move Parquet metadata fetching logic to separate module
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/_default_metadata_providers.py
  python/ray/data/datasource/file_meta_provider.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/datasource/parquet_meta_provider.py
  python/ray/data/tests/test_parquet.py
Labels: go

#45323 Accelerated DAG: Support dynamic resizing of shared memory channels
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: go

#45697 [RLlib] Add "official" benchmark script for Atari PPO benchmarks (new API stack).
  release/release_tests.yaml
  rllib/BUILD
  rllib/benchmarks/ppo/benchmark_atari_ppo.py
  rllib/examples/evaluation/custom_evaluation.py
  rllib/examples/evaluation/evaluation_parallel_to_training.py
  rllib/tuned_examples/ppo/atari_ppo.py
  rllib/utils/test_utils.py
Labels: go

#45651 [RLlib] Fix calling of callback `on_episode_created` to conform to docstring (after reset).
  rllib/algorithms/callbacks.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
Labels: bug, rllib, rllib-newstack, go

#45733 [Data] Merge `DefaultParquetMetadataProvider` and `ParquetMetadataProvider`
  doc/source/data/api/input_output.rst
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/_default_metadata_providers.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/datasource/parquet_meta_provider.py
  python/ray/data/tests/test_metadata_provider.py
  python/ray/data/tests/test_parquet.py
Labels: go

#45735 [Data] Remove unnecessary logic that manually adds partition columns
  python/ray/data/datasource/parquet_datasource.py
Labels: go

#45736 [Core] Introduce DictConfigProvider interface for logging config
  doc/source/ray-core/api/core.rst
  python/ray/_private/ray_logging/constants.py
  python/ray/_private/ray_logging/default_impl.py
  python/ray/_private/ray_logging/logging_config.py
  python/ray/_private/worker.py
Labels: go

#45758 [Data] Clean up some uses of `check_num_computed` in `test_parquet.py`
  python/ray/data/tests/test_parquet.py
Labels: go

#45734 [Data] Move metadata duplication logic to Parquet metadata provider
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/datasource/parquet_meta_provider.py
  python/ray/data/tests/test_metadata_provider.py
Labels: go

#45763 [ci][release] relax the enum of byod type
  release/ray_release/schema.json
Labels: go

#45766 [Data] Explicitly specify metadata provider in `test_parquet_reader_estimate_data_size`
  python/ray/data/tests/test_parquet.py
Labels: go

#45749 [Data] Use sampled fragments to estimate Parquet reader batch size
  python/ray/data/datasource/parquet_datasource.py
Labels: go

#45767 [Data] Add `override_num_blocks` parameter to `get_parquet_metadata_provider`
  python/ray/data/datasource/_default_metadata_providers.py
  python/ray/data/read_api.py
Labels: go

#45711 Add train_head.py with API to serve train runs
  dashboard/modules/train/__init__.py
  dashboard/modules/train/train_head.py
  python/ray/train/BUILD
  python/ray/train/_internal/state/schema.py
  python/ray/train/tests/test_train_head.py
Labels: go

#45753 [RLlib] Fix release test JSON summary problem (if e.g. numpy data in result dict).
  rllib/utils/test_utils.py
Labels: go

#44758 [RLlib] PyFlyt QuadX WayPoints
  rllib/examples/quadx_waypoints.py
Labels: enhancement, P2, rllib, rllib-docs-or-examples, rllib-newstack, go

#45764 [core] make sure PYTHONSAFEPATH is disabled
  python/ray/tests/test_basic_2.py
  python/ray/tests/test_basic_5.py
Labels: go

#45698 [dashboard] Add search by Node ID
  dashboard/client/src/pages/node/hook/useNodeList.ts
  dashboard/client/src/pages/node/index.tsx
Labels: go

#45601 [ci][doc/4] init api object from sphinx autodoc
  ci/ray_ci/doc/BUILD.bazel
  ci/ray_ci/doc/api.py
  ci/ray_ci/doc/test_api.py
Labels: go

#45784 [ci] upgrade bazel version to 6.5.0
  .bazelversion
  WORKSPACE
Labels: go

#45729 Support transfer ObjectRef from JAVA application to PYTHON deployment
  java/serve/src/main/java/io/ray/serve/router/ReplicaSet.java
  java/serve/src/test/java/io/ray/serve/deployment/CrossLanguageDeploymentTest.java
  java/test/src/main/java/io/ray/test/CrossLanguageInvocationTest.java
  python/ray/serve/_private/replica.py
Labels: go

#45774 [RLlib] Cleanup examples folder #10: Add `custom_rl_module.py` example script and matching RLModule example class (tiny CNN)..
  rllib/BUILD
  rllib/algorithms/ppo/torch/ppo_torch_rl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/env/single_agent_env_runner.py
  rllib/examples/rl_modules/action_masking_rlm.py
  rllib/examples/rl_modules/classes/tiny_atari_cnn.py
  rllib/examples/rl_modules/custom_rl_module.py
  rllib/examples/rl_modules/episode_env_aware_rlm.py
  rllib/examples/rl_modules/frame_stacking_rlm.py
  rllib/examples/rl_modules/mobilenet_rlm.py
  rllib/examples/rl_modules/random_rl_module.py
Labels: go

#45787 Update Docker dependencies for 2.24.0
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#45806 [doc] change bazel version for dev workflows
  doc/source/ray-contribute/development.rst
Labels: go

#45808 [release auto] allow verify wheel of a different commit
  .buildkite/release-automation/forge.rayci.yml
  .buildkite/release-automation/verify-linux-wheels.sh
  .buildkite/release-automation/verify-macos-wheels.sh
  .buildkite/release-automation/wheels.rayci.yml
Labels: go

#45805 [cpp] use bazelisk in template example
  cpp/example/run.sh
Labels: go

#45168 [Doc] Fix broken references in rllib documentation
  doc/source/rllib/package_ref/algorithm.rst
  doc/source/rllib/package_ref/evaluation.rst
  doc/source/rllib/package_ref/models.rst
  doc/source/rllib/rllib-catalogs.rst
  doc/source/rllib/rllib-rlmodule.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/core/rl_module/marl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/env/env_runner_group.py
  rllib/policy/policy.py
  rllib/policy/torch_policy_v2.py
Labels: rllib, docs, go

#45781 [Serve] Keep `object_store_memory` an int
  python/ray/serve/schema.py
  python/ray/serve/tests/test_regression.py
Labels: go

#44955 [Core] Use exception-free json string escape for C++ structured logging
  src/ray/gcs/gcs_server/runtime_env_handler.cc
  src/ray/util/logging.cc
  src/ray/util/tests/logging_test.cc
Labels: go

#45790 [Core] Don't add core context if Ray is not initialized
  python/ray/_private/ray_logging/filters.py
  python/ray/tests/test_logging_2.py
Labels: go

#45809 [ci] fixes cuda version expansion in wanda matrix
  ci/docker/ray.cuda.base.aarch64.wanda.yaml
  ci/docker/ray.cuda.base.wanda.yaml
Labels: go

#45798 [ci] fix bazel version use in release automation
  .buildkite/release-automation/forge_arm64.Dockerfile
  .buildkite/release-automation/forge_x86_64.Dockerfile
  .buildkite/release-automation/verify-macos-wheels.sh
  release/util/sanity_check_cpp.sh
Labels: go

#45791 [core] On GCS restart, load actors whose job is dead but root detached actor is alive.
  python/ray/tests/test_gcs_fault_tolerance.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
Labels: go

#45810 [Data] Fix `override_num_blocks` typo of `read_lance`
  python/ray/data/read_api.py
Labels: go

#45613 [Tune; RLlib] Missing stopping criterion should not error (just warn).
  python/ray/tune/experiment/trial.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_trial.py
Labels: go

#45819 [RLlib] Fix DreamerV3 bug for `num_env_runners > 0` (users should use `num_envs_per_env_runner > 1` instead, though).
  rllib/algorithms/dreamerv3/dreamerv3.py
  rllib/algorithms/dreamerv3/tests/test_dreamerv3.py
  rllib/algorithms/dreamerv3/utils/env_runner.py
  rllib/env/env_runner_group.py
Labels: tests-ok, go

#45820 [RLlib] Fix test case multi-agent Pendulum PPO (--num-agents=2 arg missing in BUILD).
  rllib/BUILD
  rllib/algorithms/bc/tests/test_bc.py
Labels: tests-ok, go

#45813 [docs] add LLM to example title for easy skimming
  doc/source/serve/examples.yml
Labels: go

#45761 [Serve] create internal request id to track request objects
  doc/source/serve/monitoring.md
  python/ray/serve/_private/common.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/replica_scheduler/common.py
  python/ray/serve/context.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/test_http_headers.py
  python/ray/serve/tests/test_proxy.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
  python/ray/serve/tests/unit/test_request_metadata.py
  python/ray/serve/tests/unit/test_router.py
  python/ray/serve/tests/unit/test_user_callable_wrapper.py
  src/ray/protobuf/serve.proto
Labels: serve, go

#45830 [Databricks] Remove pricing warning when starting cluster
  python/ray/util/spark/databricks_hook.py
Labels: go

#45828 [spark] Fix error message in `_calc_mem_per_ray_node`
  python/ray/util/spark/utils.py
Labels: go

#45762 [ci][release] add `RAY_BACKEND_LOG_JSON` env for all release test
  release/ray_release/test.py
  release/ray_release/tests/test_cluster_manager.py
  release/ray_release/tests/test_glue.py
  release/ray_release/tests/test_test.py
Labels: go

#45814 [Serve] Remove `object_store_memory` from Ray Serve
  python/ray/serve/_private/config.py
  python/ray/serve/api.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_schema.py
Labels: go

#45840 [wheel] remove py38 in build wheel script
  python/build-wheel-manylinux2014.sh
Labels: go

#45811 [image] update build docker script's python version and gpu base
  build-docker.sh
Labels: go

#45842 [wheel] provide a valid default commit
  python/README-building-wheels.md
Labels: go

#45851 Update Nav Link to be "Try Ray on Anyscale"
  doc/source/_templates/navbar-anyscale.html
Labels: go

#45850 [Data] Remove deprecated APIs
  doc/source/data/api/dataset.rst
  python/ray/data/dataset.py
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/block_path_provider.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/file_datasink.py
  python/ray/data/datasource/parquet_datasink.py
  python/ray/data/preprocessors/__init__.py
  python/ray/data/preprocessors/batch_mapper.py
  python/ray/data/tests/preprocessors/test_batch_mapper.py
  python/ray/data/tests/test_partitioning.py
Labels: go

#45829 [RLlib] Add LSTM option to `run_connector_policy`example (old API stack; w/ manual `Connector.reset()` call).
  rllib/BUILD
  rllib/examples/_old_api_stack/connectors/prepare_checkpoint.py
  rllib/examples/_old_api_stack/connectors/run_connector_policy.py
Labels: tests-ok, go

#45831 [RLlib] Cleanup examples folder #14: Add example script for policy (RLModule) inference on new API stack.
  rllib/BUILD
  rllib/examples/inference/policy_inference_after_training.py
Labels: tests-ok, go

#45839 [RLlib] Fix CI test: `test_io.py`.
  rllib/tests/test_io.py
Labels: tests-ok, go

#45845 [RLlib] Cleanup examples folder #15: Add example script for policy (RLModule) inference w/ ConnectorV2.
  rllib/BUILD
  rllib/connectors/connector_pipeline_v2.py
  rllib/connectors/env_to_module/env_to_module_pipeline.py
  rllib/examples/inference/policy_inference_after_training_w_connector.py
Labels: tests-ok, go

#45786 [core][experimental] Driver on different node can read from accelerated DAG output
  python/ray/dag/compiled_dag_node.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
Labels: go

#45834 [core] fix exit handling of FiberState threads
  src/ray/core_worker/fiber.h
  src/ray/core_worker/test/fiber_state_test.cc
Labels: go

#45865 [util] fix lint issue in inspect util
  python/ray/_private/inspect_util.py
Labels: go

#45816 [lint] port check bazel team owner check to bazel
  ci/lint/BUILD.bazel
  ci/lint/check_bazel_team_owner.py
  ci/lint/lint.sh
Labels: go

#45018 [GCS] Add `total_resources` to reduce communication overhead for aggregating alive resources
  python/ray/_private/gcs_utils.py
  python/ray/_private/state.py
  python/ray/cluster_utils.py
  python/ray/data/_internal/planner/exchange/push_based_shuffle_task_scheduler.py
  python/ray/includes/global_state_accessor.pxd
  python/ray/includes/global_state_accessor.pxi
  python/ray/tests/test_global_state.py
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/global_state_accessor.h
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/gcs_server/gcs_rpc_server.h
Labels: triage, @external-author-action-required, core, go

#45866 [air] use isintance rather than `type()`
  python/ray/air/_internal/torch_utils.py
Labels: go

#45233 [Doc] Fix broken references in Ray Tune documentation
  doc/source/tune/api/execution.rst
  doc/source/tune/api/logging.rst
  doc/source/tune/examples/tune_analyze_results.ipynb
  doc/source/tune/faq.rst
  doc/source/tune/tutorials/tune-distributed.rst
  doc/source/tune/tutorials/tune-storage.rst
  python/ray/tune/experiment/trial.py
  python/ray/tune/tuner.py
Labels: go

#45489 [Data] Refactor `count()` and `schema()` to not rely on `LazyBlockList`
  python/ray/data/_internal/logical/interfaces/logical_operator.py
  python/ray/data/_internal/logical/operators/all_to_all_operator.py
  python/ray/data/_internal/logical/operators/from_operators.py
  python/ray/data/_internal/logical/operators/input_data_operator.py
  python/ray/data/_internal/logical/operators/one_to_one_operator.py
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/datasource/range_datasource.py
  python/ray/data/tests/test_dynamic_block_split.py
Labels: go

#45853 [Dashboard] Parse out json logs
  dashboard/client/src/components/LogView/LogVirtualView.tsx
Labels: enhancement, dashboard, go

#45873 [ci] lint: add maxsplit key for `re.split`
  ci/run/bazel.py
Labels: go

#45785 [cuda] remove 11.5 and 11.6, add 12.3
  .buildkite/_forge.rayci.yml
  .buildkite/build.rayci.yml
  .buildkite/linux_aarch64.rayci.yml
  .buildkite/release/build.rayci.yml
  ci/docker/ray.cuda.base.aarch64.wanda.yaml
  ci/docker/ray.cuda.base.wanda.yaml
  ci/ray_ci/automation/docker_tags_lib.py
  ci/ray_ci/automation/test_docker_tags_lib.py
  ci/ray_ci/docker_container.py
  ci/ray_ci/test_anyscale_docker_container.py
  ci/ray_ci/test_ray_docker_container.py
  docker/retag-lambda/cuda_versions.txt
Labels: go

#45852 [Data] Make `ExecutionPlan.execute` return `RefBundle` instead of `BlockList`
  python/ray/data/_internal/logical/interfaces/logical_operator.py
  python/ray/data/_internal/logical/operators/read_operator.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasource.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/datasource/parquet_datasource.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_binary.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_exceptions.py
  python/ray/data/tests/test_formats.py
  python/ray/data/tests/test_json.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_split.py
  python/ray/data/tests/test_splitblocks.py
  python/ray/data/tests/test_sql.py
  python/ray/data/tests/test_stats.py
  python/ray/data/tests/test_tensor.py
  python/ray/data/tests/test_text.py
Labels: go

#45892 [ci] avoid deadlocking bazel query and bazel run
  ci/lint/lint.sh
Labels: go

#45898 [Core] Remove dead gcs_failover_worker_reconnect_timeout config
  dashboard/modules/serve/tests/test_serve_dashboard.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_placement_group_2.py
  release/k8s_tests/ray_v1alpha1_rayservice_template.yaml
  src/ray/common/ray_config_def.h
Labels: go

#45883 [release] use bigger machine for anyscale build
  .buildkite/release/build.rayci.yml
  .buildkite/release/config.yml
  .rayciversion
Labels: go

#44733 [core] Perf: Fair dispatching of the tasks for different scheduling_class to reduce the intermediate data storage
  BUILD.bazel
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
  src/ray/raylet/local_task_manager_test.cc
Labels: triage, core, go

#45905 [Data] Hard deprecate `set_progress_bar`
  python/ray/data/_internal/progress_bar.py
  python/ray/data/tests/test_progress_bar.py
Labels: go

#45879 [finetune] change fine-tuning examples to use cuda 12.3
  .buildkite/release/build.rayci.yml
  release/release_tests.yaml
Labels: go

#45591 [core][experimental] Avoid serialization for data passed between two tasks on the same actor
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/__init__.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
Labels: @author-action-required, go

#45911 [ci] only upload bazel cache result on postmerge
  ci/ray_ci/tests.env.Dockerfile
Labels: go

#45860 [Data] Remove `in_blocks` parameter of `ExecutionPlan`
  python/ray/data/BUILD
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/logical/interfaces/logical_operator.py
  python/ray/data/_internal/logical/interfaces/logical_plan.py
  python/ray/data/_internal/logical/operators/from_operators.py
  python/ray/data/_internal/logical/operators/input_data_operator.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_logical_plan.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_split.py
Labels: go

#45864 [RLlib] Cleanup examples folder #16: Add missing docstrings to 2 connector example scripts.
  rllib/BUILD
  rllib/connectors/connector_pipeline_v2.py
  rllib/connectors/connector_v2.py
  rllib/connectors/env_to_module/__init__.py
  rllib/connectors/env_to_module/flatten_observations.py
  rllib/connectors/env_to_module/mean_std_filter.py
  rllib/connectors/env_to_module/prev_actions_prev_rewards.py
  rllib/examples/actions/__init__.py
  rllib/examples/actions/nested_action_spaces.py
  rllib/examples/checkpoints/checkpoint_by_custom_criteria.py
  rllib/examples/checkpoints/continue_training_from_checkpoint.py
  rllib/examples/checkpoints/restore_1_of_n_agents_from_checkpoint.py
  rllib/examples/connectors/flatten_observations_dict_space.py
  rllib/examples/connectors/frame_stacking.py
  rllib/examples/connectors/mean_std_filtering.py
  rllib/examples/connectors/nested_observation_spaces.py
  rllib/examples/connectors/prev_actions_prev_rewards.py
  rllib/examples/curriculum/curriculum_learning.py
  rllib/examples/inference/policy_inference_after_training.py
  rllib/examples/inference/policy_inference_after_training_w_connector.py
  rllib/examples/multi_agent/rock_paper_scissors_heuristic_vs_learned.py
  rllib/examples/multi_agent/rock_paper_scissors_learned_vs_learned.py
  rllib/examples/multi_agent/two_step_game_with_grouped_agents.py
Labels: tests-ok, go

#45906 [ci] upgrade and unify conda env to py311 24.4.0-0
  .buildkite/release-automation/forge_arm64.Dockerfile
  .buildkite/release-automation/forge_x86_64.Dockerfile
  .buildkite/release-automation/verify-macos-wheels.sh
  ci/env/install-dependencies.sh
  docker/base-deps/Dockerfile
Labels: go

#45901 [ci] deflake rllib release tests
  release/ray_release/byod/byod_rllib_dreamerv3_test.sh
  release/ray_release/byod/byod_rllib_test.sh
  release/release_tests.yaml
Labels: go

#45925 Revert "[core][experimental] Avoid serialization for data passed between two tasks on the same actor"
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/__init__.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
Labels: go

#45687 [ADAG] Introduce ObjectRef-like API for ADAG
  python/ray/_private/serialization.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/compiled_dag_ref.py
  python/ray/tests/test_channel.py
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
Labels: go

#45918 [Core] Remove dead PlacementGroupScheduleTable and ResourceUsageBatchTable
  src/mock/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/protobuf/gcs.proto
Labels: go

#42304 [runtime-env] automatically infer worker path when starting worker in container
  python/ray/_private/runtime_env/context.py
  python/ray/_private/runtime_env/image_uri.py
  python/ray/_private/test_utils.py
  python/ray/runtime_env/runtime_env.py
  python/ray/tests/runtime_env_container/test_log_file_exists.py
  python/ray/tests/runtime_env_container/test_put_get.py
  python/ray/tests/runtime_env_container/test_ray_env_vars.py
  python/ray/tests/runtime_env_container/test_serve_basic.py
  python/ray/tests/runtime_env_container/test_serve_telemetry.py
  python/ray/tests/runtime_env_container/test_shared_memory.py
  python/ray/tests/runtime_env_container/test_worker_exit_intended_system_exit_and_user_error.py
  python/ray/tests/test_runtime_env.py
Labels: go

#45854 [core] On GCS restart, destroy not forget the unused workers. Fixing PG leaks.
  python/ray/tests/test_gcs_fault_tolerance.py
  src/mock/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/test/direct_task_transport_test.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: go

#45914 [ci] remove old travis/github test config
  .bazelrc
  ci/ci.sh
  ci/env/install-bazel.sh
Labels: go

#45897 [ci] fix some shell lints in `ci.sh` script
  ci/ci.sh
Labels: go

#45624 [Core] Update TPU num_visible_chips to 4 or 8 to support v5e-8
  python/ray/_private/accelerators/tpu.py
  python/ray/autoscaler/_private/gcp/config.py
  python/ray/tests/accelerators/test_tpu.py
  python/ray/tests/gcp/test_gcp_node_provider.py
  python/ray/tests/test_autoscaler_fake_multinode.py
  python/ray/util/accelerators/__init__.py
  python/ray/util/accelerators/accelerators.py
Labels: go

#45917 [doc check] fix shell check in script
  ci/lint/lint.sh
Labels: go

#45915 [release test] lint: bind loop variable
  release/ray_release/tests/test_bisect.py
Labels: go

#45857 [doc][api/6] convert api alias to full name
  ci/ray_ci/doc/BUILD.bazel
  ci/ray_ci/doc/api.py
  ci/ray_ci/doc/mock/__init__.py
  ci/ray_ci/doc/mock/mock_module.py
  ci/ray_ci/doc/test_api.py
  ci/ray_ci/doc/test_autodoc.py
  ci/ray_ci/doc/test_module.py
Labels: go

#45937 Revert "Revert "[core][experimental] Avoid serialization for data passed between two tasks on the same actor""
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/__init__.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/tests/test_channel.py
Labels: go

#45858 [doc][api/7] handle ~ character in autodoc
  ci/ray_ci/doc/api.py
  ci/ray_ci/doc/mock/mock_module.py
  ci/ray_ci/doc/test_autodoc.py
Labels: go

#45576 [RLlib] Prioritized multi-agent episode replay buffer.
  rllib/BUILD
  rllib/algorithms/sac/sac.py
  rllib/algorithms/sac/torch/sac_torch_learner.py
  rllib/tuned_examples/dqn/multi_agent_cartpole_dqn.py
  rllib/tuned_examples/sac/multi_agent_pendulum_sac.py
  rllib/tuned_examples/sac/pendulum_sac.py
  rllib/utils/replay_buffers/__init__.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
  rllib/utils/replay_buffers/multi_agent_episode_buffer.py
  rllib/utils/replay_buffers/multi_agent_prioritized_episode_buffer.py
  rllib/utils/replay_buffers/prioritized_episode_buffer.py
  rllib/utils/replay_buffers/tests/test_multi_agent_episode_buffer.py
  rllib/utils/replay_buffers/tests/test_multi_agent_prio_episode_buffer.py
  rllib/utils/replay_buffers/tests/test_multi_agent_prioritized_replay_buffer.py
  rllib/utils/replay_buffers/tests/test_prioritized_episode_buffer.py
  rllib/utils/replay_buffers/tests/test_prioritized_episode_replay_buffer.py
  rllib/utils/replay_buffers/utils.py
Labels: rllib, rllib-multi-agent, rllib-newstack, go

#43592 [RLlib] ONNX example script: Enhance to work with torch + LSTM
  rllib/BUILD
  rllib/examples/checkpoints/onnx_torch_lstm.py
Labels: rllib, rllib-evaluation, rllib-docs-or-examples, rllib-oldstack-cleanup, go

#45956 [RLlib] Cleanup examples folder: Cleaned-up PyFlyt example.
  rllib/examples/quadx_waypoints.py
Labels: rllib, rllib-docs-or-examples, rllib-newstack, go

#45950 [core][experimental] Fix CI errors and improve __repr__
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/compiled_dag_ref.py
Labels: go

#45700 [Train] Add creation time in `TrainRunInfo` Schema
  dashboard/modules/train/train_head.py
  python/ray/train/_internal/backend_executor.py
  python/ray/train/_internal/state/schema.py
  python/ray/train/_internal/state/state_actor.py
  python/ray/train/_internal/state/state_manager.py
  python/ray/train/tests/test_state.py
Labels: go

#45959 [ci] fix bisect
  ci/ray_ci/bisect/bisector.py
  ci/ray_ci/bisect/test_bisector.py
Labels: go

#45699 [core] Weakref semantics for actor handles retrieved from self or by name
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  python/ray/_private/serialization.py
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_actor.py
  python/ray/tests/test_memstat.py
  python/ray/util/client/common.py
  python/ray/util/client/server/dataservicer.py
  python/ray/util/client/server/server.py
  python/ray/util/client/worker.py
  src/ray/common/id.h
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/lib/java/io_ray_runtime_actor_NativeActorHandle.cc
  src/ray/core_worker/test/actor_manager_test.cc
Labels: go

#45949 [Data] Add configuration to `PhysicalOperator` to allow disabling operator fusion
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/base_physical_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
Labels: go

#45951 [ADAG] Clean up channel read API
  python/ray/_private/ray_experimental_perf.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/compiled_dag_ref.py
  python/ray/tests/test_channel.py
  python/ray/tests/test_nccl_channel.py
  release/microbenchmark/experimental/accelerated_dag_gpu_microbenchmark.py
Labels: go

#46058 Revert "[ADAG] Introduce ObjectRef-like API for ADAG (#45687)"
  python/ray/_private/ray_experimental_perf.py
  python/ray/_private/serialization.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/compiled_dag_ref.py
  python/ray/tests/test_channel.py
  python/ray/tests/test_nccl_channel.py
  release/microbenchmark/experimental/accelerated_dag_gpu_microbenchmark.py
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
Labels: go

#46053 [core] move gcs_rpc_client code out of macro
  src/ray/rpc/gcs_server/gcs_rpc_client.h
Labels: go

#46048 [core] Redo StatusCode <-> Str mapping.
  src/ray/common/status.cc
  src/ray/common/status.h
Labels: go

#45903 [core][dashboard] Use executor for list_tasks
  dashboard/state_aggregator.py
  python/ray/_private/protobuf_compat.py
Labels: go

#46065 [ci] temporarily disable flaky dag tests
  python/ray/dag/BUILD
Labels: go

#46063 [ci] add core gpu flaky test
  .buildkite/core.rayci.yml
Labels: go

#46066 Revert "[core][experimental] Fix CI errors and improve __repr__ (#459…
  python/ray/dag/BUILD
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
Labels: go

#46070 [release auto] do not depend on blocker check
  .buildkite/release-automation/pre_release.rayci.yml
Labels: go

#45946 [ci] use `BUILDKITE_CACHE_READONLY` to control cache upload
  ci/ray_ci/linux_container.py
  ci/ray_ci/test_linux_tester_container.py
  ci/ray_ci/test_windows_container.py
  ci/ray_ci/tests.env.Dockerfile
  ci/ray_ci/windows/tests.env.Dockerfile
  ci/ray_ci/windows_container.py
  python/build-wheel-windows.sh
Labels: go

#45919 [Core] Cancel lease requests before returning a PG bundle
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_placement_group_5.py
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/local_task_manager_interface.h
  src/ray/util/container_util.h
  src/ray/util/tests/container_util_test.cc
Labels: go

#45945 [data][api] mark ActorPoolStrategy as an internal API
  python/ray/data/_internal/compute.py
Labels: go

#45942 [release] update anyscale dataplane tarball
  ci/build/build-anyscale-docker.sh
  release/ray_release/byod/build.py
Labels: go

#45017 [Dashboard] Fix the filtering of the `job_id` in getTasks.
  dashboard/client/src/service/task.ts
Labels: P1, dashboard, core, observability, go

#46078 [ADAG] Introduce CompiledDAGRef
  python/ray/_private/ray_experimental_perf.py
  python/ray/_private/serialization.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/dag/BUILD
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/compiled_dag_ref.py
  python/ray/tests/test_channel.py
  python/ray/tests/test_nccl_channel.py
  release/microbenchmark/experimental/accelerated_dag_gpu_microbenchmark.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
Labels: go

#46073 [wheel] windows: fix unbound varaible error
  python/build-wheel-windows.sh
Labels: go

#45708 Add perf metrics for 2.24.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: accelerated-dag, go

#45742 [doc]Make vllm example works with latest vllm version
  doc/source/serve/doc_code/vllm_openai_example.py
Labels: go

#46057 [core] change GcsClient.get_all_node_info return type to proto type.
  python/ray/_private/gcs_aio_client.py
  python/ray/_private/usage/usage_lib.py
  python/ray/_raylet.pyx
  python/ray/includes/common.pxd
  python/ray/includes/unique_ids.pxi
  python/ray/serve/_private/cluster_node_info_cache.py
  python/ray/tests/test_state_api.py
Labels: go

#46052 [Data] Remove `run_by_consumer` parameter of `ExecutionPlan`
  python/ray/data/_internal/execution/legacy_compat.py
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_split.py
Labels: go

#46091 Revert "[Core] Cancel lease requests before returning a PG bundle (#4…
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_placement_group_5.py
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/placement_group_resource_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/local_task_manager_interface.h
  src/ray/util/container_util.h
  src/ray/util/tests/container_util_test.cc
Labels: go

#46100 [Core] Cache the expensive TPUAcceleratorManager.get_current_node_num_accelerators
  python/ray/_private/accelerators/tpu.py
  python/ray/tests/accelerators/test_tpu.py
Labels: go

#45882 [Serve] Run `__del__` even if constructor is still in-progress
  python/ray/serve/_private/replica.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/unit/test_user_callable_wrapper.py
Labels: go

#46124 [core] re-enable test_accelerated_dag tests
  python/ray/dag/BUILD
Labels: go

#46105 [Serve] fix logging error on passing traceback object into exc_info
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_logging.py
Labels: bug, serve, go
