Repository ray-project/ray, pull requests merged in 2024-10, with the labels that each got.

#47664 [Core] Fixing gRPC server handlers to properly respect max inflight RPCs settings
  src/ray/common/ray_config_def.h
  src/ray/rpc/grpc_server.cc
Labels: go

#47832 [Arrow] Adding `ArrowTensorTypeV2` to support tensors larger than 2Gb
  python/ray/_private/arrow_serialization.py
  python/ray/air/BUILD
  python/ray/air/_internal/tensorflow_utils.py
  python/ray/air/tests/conftest.py
  python/ray/air/tests/test_tensor_extension.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/air/util/transform_pyarrow.py
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/extensions/__init__.py
  python/ray/data/extensions/tensor_extension.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_tensor.py
Labels: go

#47881 [Data][Docs] Add reference to parquet predicate pushdown
  python/ray/data/dataset.py
Labels: go

#47394 [Data][Doc] Add tip about how to understand map_batches format
  python/ray/data/dataset.py
Labels: triage, docs, data, go

#47898 docs: remove summit banner
  doc/source/conf.py
Labels: go

#47890 Updated link for slack
  README.rst
Labels: go

#47899 docs: add attribution to try ray on anyscale button
  doc/source/_templates/navbar-anyscale.html
Labels: go

#47861 [Core] Fix check failure: sync_reactors_.find(reactor->GetRemoteNodeID()) == sync_reactors_.end()
  python/ray/tests/conftest_docker.py
  python/ray/tests/test_network_failure_e2e.py
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/test/ray_syncer_test.cc
Labels: go

#47884 [RLlib] New API stack: (Multi)RLModule overhaul vol 01 (some preparatory cleanups).
  rllib/algorithms/algorithm.py
  rllib/connectors/connector_v2.py
  rllib/core/rl_module/marl_module.py
  rllib/tuned_examples/bc/cartpole_bc.py
  rllib/utils/metrics/__init__.py
  rllib/utils/serialization.py
  rllib/utils/test_utils.py
Labels: go

#47907 [Data] Fix event loop mismatch with async map
  python/ray/data/_internal/planner/plan_udf_map_op.py
Labels: go

#47885 [RLlib] New API stack: (Multi)RLModule overhaul vol 02 (VPG RLModule, Algo, and Learner example classes).
  rllib/examples/algorithms/__init__.py
  rllib/examples/algorithms/classes/__init__.py
  rllib/examples/algorithms/classes/vpg.py
  rllib/examples/learners/classes/vpg_learner.py
  rllib/examples/rl_modules/classes/vpg_rlm.py
  rllib/examples/rl_modules/classes/vpg_using_shared_encoder_rlm.py
Labels: go

#47889 [RLlib] New API stack: (Multi)RLModule overhaul vol 03 (Introduce generic `_forward` to further simplify the user experience).
  rllib/algorithms/appo/torch/appo_torch_learner.py
  rllib/algorithms/bc/bc_catalog.py
  rllib/algorithms/bc/bc_rl_module.py
  rllib/algorithms/bc/torch/bc_torch_rl_module.py
  rllib/algorithms/impala/torch/impala_torch_learner.py
  rllib/algorithms/marwil/marwil_rl_module.py
  rllib/algorithms/marwil/torch/marwil_torch_learner.py
  rllib/algorithms/marwil/torch/marwil_torch_rl_module.py
  rllib/algorithms/ppo/ppo_rl_module.py
  rllib/algorithms/ppo/tests/test_ppo_rl_module.py
  rllib/algorithms/ppo/tf/ppo_tf_rl_module.py
  rllib/algorithms/ppo/torch/ppo_torch_learner.py
  rllib/algorithms/ppo/torch/ppo_torch_rl_module.py
  rllib/core/columns.py
  rllib/core/learner/learner.py
  rllib/core/rl_module/apis/value_function_api.py
  rllib/core/rl_module/multi_rl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/examples/offline_rl/train_w_bc_finetune_w_ppo.py
  rllib/examples/rl_modules/classes/action_masking_rlm.py
  rllib/examples/rl_modules/classes/autoregressive_actions_rlm.py
  rllib/examples/rl_modules/classes/intrinsic_curiosity_model_rlm.py
  rllib/examples/rl_modules/classes/lstm_containing_rlm.py
  rllib/examples/rl_modules/classes/modelv2_to_rlm.py
  rllib/examples/rl_modules/classes/tiny_atari_cnn_rlm.py
  rllib/examples/rl_modules/classes/vpg_using_shared_encoder_rlm.py
  rllib/tuned_examples/dqn/multi_agent_cartpole_dqn.py
  rllib/utils/annotations.py
Labels: go

#47892 [RLlib] Remove Tf support on new API stack for PPO/IMPALA/APPO (only DreamerV3 on new API stack remains with tf now).
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/tests/test_appo_learner.py
  rllib/algorithms/appo/tf/__init__.py
  rllib/algorithms/appo/tf/appo_tf_learner.py
  rllib/algorithms/appo/tf/appo_tf_rl_module.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/tests/test_vtrace_v2.py
  rllib/algorithms/impala/tf/__init__.py
  rllib/algorithms/impala/tf/impala_tf_learner.py
  rllib/algorithms/impala/tf/vtrace_tf_v2.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/tests/test_ppo_rl_module.py
  rllib/algorithms/ppo/tf/__init__.py
  rllib/algorithms/ppo/tf/ppo_tf_learner.py
  rllib/algorithms/ppo/tf/ppo_tf_rl_module.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/algorithms/tests/test_algorithm_rl_module_restore.py
Labels: tests-ok, go

#47880 [RLlib] Fix assertion in `Simplex` space.
  rllib/utils/spaces/simplex.py
  rllib/utils/tests/test_serialization.py
Labels: rllib, rllib-env, go

#47777 [Core] Fix TPU head resource override hack for docker
  python/ray/autoscaler/_private/gcp/tpu_command_runner.py
Labels: triage, core, core-hardware, go

#47192 Clean up CODEOWNERS
  .github/CODEOWNERS
Labels: go

#47893 [core] Change debug_string from returning a string to streaming to an ostream.
  src/ray/util/container_util.h
  src/ray/util/tests/container_util_test.cc
Labels: go

#47922 [Serve / Jobs] Check if conda env exists before removing
  python/ray/dashboard/modules/job/tests/backwards_compatibility_scripts/test_backwards_compatibility.sh
Labels: go

#47927 [job] don't continue on test setup
  python/ray/dashboard/modules/job/tests/backwards_compatibility_scripts/test_backwards_compatibility.sh
Labels: go

#47921 [Core] Fix a typo in ray core gentle walkthrough
  doc/source/ray-core/examples/gentle_walkthrough.ipynb
Labels: go

#47912 [core][experimental] Avoid false positives in deadlock detection
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_detect_deadlock_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule_gpu.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
Labels: go

#47847 [serve] Stop scheduling task early when requests have been cancelled
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
Labels: go

#47947 Fix pre-commit linter errors
  python/ray/data/_internal/plan.py
  python/ray/data/tests/test_parquet.py
Labels: go

#47917 Update `lint-requirements.txt`
  .pre-commit-config.yaml
  python/requirements/lint-requirements.txt
  python/requirements_compiled.txt
Labels: go

#47901 [Train] Remove deprecated mosaic and sklearn trainer code
  python/ray/air/_internal/usage.py
  python/ray/train/BUILD
  python/ray/train/examples/mosaic_cifar10_example.py
  python/ray/train/mosaic/__init__.py
  python/ray/train/mosaic/_mosaic_utils.py
  python/ray/train/mosaic/mosaic_trainer.py
  python/ray/train/sklearn/__init__.py
  python/ray/train/sklearn/sklearn_checkpoint.py
  python/ray/train/sklearn/sklearn_predictor.py
  python/ray/train/sklearn/sklearn_trainer.py
  python/ray/train/tests/test_sklearn_predictor.py
Labels: go

#47915 [RLlib] New API stack: (Multi)RLModule overhaul vol 05 (deprecate Specs, SpecDict, TensorSpec).
  doc/source/rllib/doc_code/rlmodule_guide.py
  doc/source/rllib/rllib-rlmodule.rst
  rllib/BUILD
  rllib/algorithms/dqn/torch/dqn_rainbow_torch_noisy_net.py
  rllib/algorithms/dreamerv3/dreamerv3_rl_module.py
  rllib/algorithms/marwil/marwil_rl_module.py
  rllib/algorithms/ppo/ppo_rl_module.py
  rllib/core/models/base.py
  rllib/core/models/specs/checker.py
  rllib/core/models/specs/specs_base.py
  rllib/core/models/specs/specs_dict.py
  rllib/core/models/specs/tests/__init__.py
  rllib/core/models/specs/tests/test_check_specs.py
  rllib/core/models/specs/tests/test_spec_dict.py
  rllib/core/models/specs/tests/test_tensor_spec.py
  rllib/core/models/tests/test_base_models.py
  rllib/core/models/tests/test_cnn_transpose_heads.py
  rllib/core/models/tests/test_mlp_heads.py
  rllib/core/models/tests/test_recurrent_encoders.py
  rllib/core/models/tf/base.py
  rllib/core/models/tf/encoder.py
  rllib/core/models/tf/heads.py
  rllib/core/models/torch/base.py
  rllib/core/models/torch/encoder.py
  rllib/core/models/torch/heads.py
  rllib/core/rl_module/rl_module.py
  rllib/examples/custom_recurrent_rnn_tokenizer.py
  rllib/examples/rl_modules/classes/autoregressive_actions_rlm.py
  rllib/models/utils.py
  rllib/utils/test_utils.py
Labels: go

#47924 [Data] Fix unequal partitions when grouping by multiple keys
  python/ray/data/_internal/planner/exchange/sort_task_spec.py
  python/ray/data/tests/test_sort.py
Labels: go

#47659 [Core] Fix check failure RAY_CHECK(it != current_tasks_.end());
  .buildkite/core.rayci.yml
  python/ray/tests/test_network_failure_e2e.py
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/actor_scheduling_util.cc
  src/ray/core_worker/transport/actor_scheduling_util.h
  src/ray/core_worker/transport/normal_scheduling_queue.cc
  src/ray/core_worker/transport/normal_scheduling_queue.h
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.h
  src/ray/core_worker/transport/scheduling_queue.h
  src/ray/core_worker/transport/task_receiver.cc
Labels: go

#47906 [Data] Add `Dataset.rename_columns`
  python/ray/data/dataset.py
  python/ray/data/tests/test_map.py
Labels: go

#47959 [image] remove ray-deps image
  docker/ray-deps/Dockerfile
  docker/ray-deps/README.md
Labels: go

#47914 [RLlib] Fix small bug in 'InfiniteLookBackBuffer.get_state/from_state'.
  rllib/env/utils/infinite_lookback_buffer.py
Labels: bug, rllib, rllib-env, rllib-newstack, go

#47928 [core] Add more debug string types
  src/ray/util/container_util.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/container_util_test.cc
Labels: go

#47955 [deps] add grpcio-tools into anyscale dependencies
  python/requirements/anyscale-requirements.txt
  python/requirements_compiled.txt
Labels: go

#47965 [RLlib] Quick-fix for default RLModules in combination with a user-provided config-sub-dict (instead of a full `DefaultModelConfig`).
  rllib/algorithms/bc/torch/bc_torch_rl_module.py
  rllib/core/rl_module/multi_rl_module.py
  rllib/core/rl_module/rl_module.py
Labels: tests-ok, rllib, rllib-models, rllib-newstack, go

#47970 [RLlib] Cleanup examples folder vol. 25: Remove some old API stack examples.
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-models.rst
  rllib/BUILD
  rllib/examples/cartpole_lstm.py
  rllib/examples/custom_model_api.py
  rllib/examples/custom_model_loss_and_metrics.py
  rllib/examples/learners/ppo_tuner.py
Labels: go

#47850 [Docs][KubeRay] Add YuniKorn Gang scheduling doc
  doc/source/cluster/kubernetes/images/yunikorn-dashboard-apps-pending.png
  doc/source/cluster/kubernetes/images/yunikorn-dashboard-apps-running.png
  doc/source/cluster/kubernetes/k8s-ecosystem.md
  doc/source/cluster/kubernetes/k8s-ecosystem/yunikorn.md
Labels: docs, kuberay, go

#47703 [core][logging] Remove actor/task prefix from the logs shown on the driver process
  python/ray/_private/worker.py
  python/ray/tests/test_logging_2.py
Labels: go

#47973 [RLlib] Add framework-check to `MultiRLModule.add_module()`.
  rllib/core/rl_module/multi_rl_module.py
Labels: rllib, rllib-multi-agent, rllib-models, rllib-newstack, go

#47948 [core][logging] Redefine worker initialization status and add context to the driver's system logs
  python/ray/_private/ray_logging/logging_config.py
  python/ray/_private/worker.py
  python/ray/tests/test_logging_2.py
Labels: P0, go

#47942 [Data] Refactor `plan_write_op` and `Datasink`s
  python/ray/data/_internal/datasource/bigquery_datasink.py
  python/ray/data/_internal/datasource/mongo_datasink.py
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/_internal/datasource/sql_datasink.py
  python/ray/data/_internal/planner/plan_write_op.py
  python/ray/data/dataset.py
  python/ray/data/datasource/datasink.py
  python/ray/data/datasource/file_datasink.py
  python/ray/data/tests/test_bigquery.py
  python/ray/data/tests/test_datasink.py
  python/ray/data/tests/test_formats.py
Labels: go

#47968 Update handling-dependencies.rst, remove the redundant "is to"
  doc/source/ray-core/handling-dependencies.rst
Labels: go

#47975 [serve] Fix failing test pow 2 scheduler on windows
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
Labels: go

#47961 [data] fix reading multiple parquet files with ragged ndarrays
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/tests/test_parquet.py
Labels: go

#47694 [core] Decouple create worker vs pop worker request.
  python/ray/tests/test_basic_4.py
  python/ray/tests/test_node_manager.py
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/protobuf/common.proto
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: go

#47793 [core] Add metrics for gcs jobs
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
  src/ray/util/counter_map.h
Labels: P1, core, observability, go

#47982 upgrade grpcio version
  python/requirements/anyscale-requirements.txt
  python/requirements_compiled.txt
Labels: go

#47807 [Feat][Core] Implement single file module for runtime_env
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/tests/conftest.py
  python/ray/tests/test_runtime_env_packaging.py
  python/ray/tests/test_runtime_env_working_dir.py
Labels: core, go

#47210 [data] Basic structured logging
  python/ray/data/_internal/logging.py
  python/ray/data/_internal/logging.yaml
  python/ray/data/tests/test_logging.py
Labels: go

#47963 [Core] Fix state api filter types and expand on error messages
  python/ray/dashboard/state_aggregator.py
  python/ray/tests/test_state_api.py
  python/ray/util/state/state_cli.py
Labels: go

#48002 [Chore][Core] Address PR 47807 comments
  python/ray/_private/runtime_env/packaging.py
Labels: go

#47966 [core] Add a thread checker
  src/ray/util/BUILD
  src/ray/util/tests/BUILD
  src/ray/util/tests/thread_checker_test.cc
  src/ray/util/thread_checker.cc
  src/ray/util/thread_checker.h
Labels: go

#48005 [core] Add thread check to job mgr callback
  BUILD.bazel
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
Labels: go

#48020 [Core] Update expired redis.crt
  python/ray/tests/tls/README
  python/ray/tests/tls/ca.txt
  python/ray/tests/tls/redis.crt
Labels: go

#47857 [Docs] Replace Python version 3.8 with 3.9 in development.rst
  doc/source/ray-contribute/development.rst
Labels: go

#47900 [cherry-pick]docs: remove summit banner (#47898)
  doc/source/conf.py
Labels: go

#47871 [Ray Core] Fix the Paths in the Generated Monitoring Configs to Consider temp-dir
  doc/source/cluster/metrics.md
  python/ray/dashboard/modules/metrics/export/grafana/grafana.ini
  python/ray/dashboard/modules/metrics/grafana_dashboard_factory.py
  python/ray/dashboard/modules/metrics/grafana_dashboard_provisioning_template.py
  python/ray/dashboard/modules/metrics/grafana_datasource_template.py
  python/ray/dashboard/modules/metrics/install_and_start_prometheus.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/metrics/templates.py
  python/ray/dashboard/modules/tests/test_metrics_integration.py
  python/ray/tests/test_metrics_head.py
Labels: go

#47986 [Data] Link `PhysicalOperator` to its `LogicalOperator`
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#47720 [Serve] Refactor helper function to add grpc address
  python/ray/serve/_private/grpc_util.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/unit/test_grpc_util.py
Labels: go

#47995 [Data] Allow specifing both `num_cpus` and `num_gpus` for map APIs
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
  python/ray/data/tests/test_executor_resource_management.py
Labels: go

#48034 [serve] deflake test_failure::test_replica_actor_died
  python/ray/serve/tests/test_failure.py
Labels: go

#48030 Fix Style Changes Suggested in #47871
  doc/source/cluster/metrics.md
Labels: go

#48031 [data] removing unneeded test case
  python/ray/data/tests/test_logging.py
Labels: go

#47788 [Docs][Minor] RuntimeEnv py_modules example wrong function name
  doc/source/ray-core/handling-dependencies.rst
Labels: triage, core, core-runtime-env, go

#47932 [Fix][Core] Change grpc_server_req_process_time_ms metric type to histogram
  python/ray/tests/test_metrics_agent.py
  src/ray/stats/metric_defs.cc
Labels: go

#48036 [data] Adding in better json checking in test logging
  python/ray/data/tests/test_logging.py
Labels: go

#47985 [train][tune] fix WandbLoggerCallback to reuse actors upon restore
  python/ray/air/integrations/wandb.py
  python/ray/air/tests/test_integration_wandb.py
Labels: go

#48039 [Data] Allow specifying insertion index when registering custom plan optimization `Rule`s
  python/ray/data/_internal/logical/optimizers.py
Labels: go

#48035 [serve] deflake test gcs failure
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/test_gcs_failure.py
Labels: go

#48033 [Serve] refactor `add_grpc_address` helper
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/grpc_util.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/unit/test_grpc_util.py
Labels: go

#47887 [Feat][Core] Support ExceptionGroup
  python/ray/exceptions.py
  python/ray/tests/BUILD
  python/ray/tests/test_exceptiongroup.py
  python/ray/tests/test_failure.py
Labels: go

#48051 [Data] Fix bug with inserting custom optimization rule at index 0
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#47992 [chore][core][compiled-graph] Rename idx to local_idx or dag_idx in RayCG codebase
  python/ray/dag/tests/experimental/test_execution_schedule.py
Labels: go

#47913 [core] Add an example for `RAY_DEDUP_LOGS_SKIP_REGEX`
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/ray-observability/user-guides/configure-logging.md
Labels: go

#48056 [Data] Adding in better framework for substituting logging handlers
  python/ray/data/_internal/logging.py
Labels: go

#48007 [Core][RFC] RPC network error chaos test framework
  BUILD.bazel
  python/ray/tests/test_gcs_utils.py
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/rpc/grpc_client.h
  src/ray/rpc/rpc_chaos.cc
  src/ray/rpc/rpc_chaos.h
  src/ray/rpc/test/rpc_chaos_test.cc
Labels: go

#48096 [Data] Fix logging output from `write_xxx` APIs
  python/ray/data/datasource/datasink.py
Labels: go

#47993 [RLlib] Fix 2 broken CI tests.
  rllib/BUILD
  rllib/algorithms/tests/test_algorithm_export_checkpoint.py
  rllib/algorithms/tests/test_env_runner_failures.py
  rllib/evaluation/tests/test_envs_that_crash.py
  rllib/tuned_examples/dqn/multi_agent_cartpole_dqn.py
Labels: go

#48093 [Data] Move logging configuration to python dictionary from yaml
  python/ray/data/_internal/logging.py
  python/ray/data/_internal/logging.yaml
  python/setup.py
Labels: go

#48054 [Core] Resubmit #47871 & #48030 and Fix the Failed Test for Windows
  doc/source/cluster/metrics.md
  python/ray/dashboard/modules/metrics/export/grafana/grafana.ini
  python/ray/dashboard/modules/metrics/grafana_dashboard_factory.py
  python/ray/dashboard/modules/metrics/grafana_dashboard_provisioning_template.py
  python/ray/dashboard/modules/metrics/grafana_datasource_template.py
  python/ray/dashboard/modules/metrics/install_and_start_prometheus.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/metrics/templates.py
  python/ray/dashboard/modules/tests/test_metrics_integration.py
  python/ray/tests/test_metrics_head.py
Labels: go

#45522 [Serve] Expose Serve app source in `get_serve_instance_details`
  doc/source/serve/api/index.md
  python/ray/dashboard/BUILD
  python/ray/dashboard/modules/serve/tests/deploy_imperative_serve_apps.py
  python/ray/dashboard/modules/serve/tests/test_serve_dashboard.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/controller.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_schema.py
Labels: P1, serve, go

#48098 [Data] Remove dead `_block_size_bytes`
  python/ray/data/dataset.py
Labels: go

#47969 [RLlib] Cleanup examples folder vol. 23: Add example script for custom metrics on `EnvRunners` (using `MetricsLogger` API).
  rllib/BUILD
  rllib/examples/envs/env_rendering_and_recording.py
  rllib/examples/learners/__init__.py
  rllib/examples/metrics/custom_metrics_and_callbacks.py
  rllib/examples/metrics/custom_metrics_in_env_runners.py
  rllib/utils/metrics/metrics_logger.py
Labels: rllib, rllib-docs-or-examples, rllib-newstack, rllib-envrunners, go

#47621 [aDAG] Support all reduce collective in aDAG
  python/ray/dag/BUILD
  python/ray/dag/__init__.py
  python/ray/dag/collective_node.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/constants.py
  python/ray/dag/dag_node.py
  python/ray/dag/dag_node_operation.py
  python/ray/dag/tests/experimental/test_collective_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/gpu_communicator.py
  python/ray/experimental/channel/nccl_group.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/experimental/collective/__init__.py
  python/ray/experimental/collective/allreduce.py
  python/ray/experimental/util/__init__.py
  python/ray/experimental/util/types.py
Labels: P1, @author-action-required, core, compiled-graph, go

#48083 [RLlib; Offline RL] Validate episodes before adding them to the buffer.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/offline/offline_data.py
  rllib/offline/offline_prelearner.py
  rllib/offline/tests/test_offline_prelearner.py
  rllib/tuned_examples/ppo/stateless_cartpole_ppo.py
Labels: rllib, rllib-offline-rl, rllib-newstack, go

#48094 [image] update anyscale layer for release test
  ci/build/build-anyscale-docker.sh
  release/ray_release/byod/build.py
Labels: go

#47946 Mark restarting actors are pending actors
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/resource_manager.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_actor_pool_map_operator.py
Labels: triage, core, go

#48124 [Data] Refactor unit tests to avoid testing directly against representation
  python/ray/data/dataset.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_binary.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_json.py
  python/ray/data/tests/test_lance.py
  python/ray/data/tests/test_metadata_provider.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_tensor.py
  python/ray/data/tests/test_text.py
  python/ray/data/tests/test_zip.py
Labels: go

#48131 [Data] Add test for counting Parquet with filter
  python/ray/data/tests/test_parquet.py
Labels: go

#48118 [CI] Fix: flake8 rule B108: Found useless Tuple expression. Consider either assigning it to a variable or removing it.
  doc/source/serve/doc_code/tutorial_sklearn.py
  python/ray/dashboard/head.py
  python/ray/data/_internal/datasource/sql_datasource.py
Labels: go

#48095 [Data] [Docs] Improve docs around Parquet filter predicate / column selection pushdown
  doc/source/data/loading-data.rst
  doc/source/data/performance-tips.rst
  python/ray/data/dataset.py
Labels: go

#48139 [Data] Make `test_insert_xxx_optimization_rules` less brittle
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#48126 [Data] Add count logical operator
  python/ray/data/_internal/execution/operators/aggregate_num_rows.py
  python/ray/data/_internal/logical/operators/count_operator.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_numpy.py
Labels: go

#48038 [Data] Pass `DataContext` as constructor arg for `LogicalPlan` and `PhysicalPlan`
  python/ray/data/_internal/logical/interfaces/logical_plan.py
  python/ray/data/_internal/logical/interfaces/physical_plan.py
  python/ray/data/_internal/logical/interfaces/plan.py
  python/ray/data/_internal/logical/rules/limit_pushdown.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/logical/rules/randomize_blocks.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_logical_plan.py
  python/ray/data/tests/test_randomize_block_order.py
  python/ray/data/tests/test_split.py
Labels: go

#48130 [Data] Do not free blocks in `Dataset.split()`
  python/ray/data/dataset.py
Labels: go

#47997 [data/preprocessors] concatenator should preserve order of concatenated
  doc/source/data/doc_code/preprocessors.py
  doc/source/train/user-guides/data-loading-preprocessing.rst
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/preprocessors/chain.py
  python/ray/data/preprocessors/concatenator.py
  python/ray/data/tests/preprocessors/test_concatenator.py
  python/ray/data/tests/preprocessors/test_preprocessors.py
  python/ray/data/tests/test_tf.py
  python/ray/train/examples/tf/tensorflow_regression_example.py
  python/ray/train/tests/test_tensorflow_trainer.py
Labels: triage, data, go

#48091 [Core] fix flaky reference count test by cleaning up borrowed references if actor is killed before dependencies are not resolved
  python/ray/tests/test_reference_counting.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
Labels: go

#47702 [core][aDAG] Clean up shutdown path
  python/ray/_private/ray_experimental_perf.py
  python/ray/_private/worker.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_detect_deadlock_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule_gpu.py
  python/ray/dag/tests/experimental/test_multi_args_gpu.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
Labels: go

#48160 [Data] Make `test_numpy_roundtrip` less brittle
  python/ray/data/tests/test_numpy.py
Labels: go

#48101 [Core] Fix Additional Code Style Suggestions from #48054
  python/ray/dashboard/modules/metrics/export/prometheus/prometheus.yml
  python/ray/dashboard/modules/metrics/install_and_start_prometheus.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/metrics/templates.py
  python/ray/dashboard/modules/tests/test_metrics_integration.py
Labels: go

#48195 [Core] Remove dead code
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/test/reference_count_test.cc
Labels: go

#48203 [Data] Remove `set_progress_bars`
  doc/source/data/api/api.rst
  doc/source/data/api/utility.rst
  python/ray/data/__init__.py
  python/ray/data/_internal/progress_bar.py
  python/ray/data/tests/test_progress_bar.py
Labels: go

#48202 [core] Add more infos to each breakpoint
  python/ray/scripts/scripts.py
  python/ray/util/rpdb.py
Labels: go

#48188 [CI] Fix flake8 rule E225: Missing whitespace around operator
  release/air_tests/air_benchmarks/mlperf-train/resnet50_ray_air.py
  release/nightly_tests/stress_tests/test_placement_group.py
Labels: go

#48204 [core][compiled graphs] Fix test_torch_tensor_dag_gpu CI failure
  python/ray/_private/ray_experimental_perf.py
  python/ray/_private/worker.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_detect_deadlock_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule_gpu.py
  python/ray/dag/tests/experimental/test_multi_args_gpu.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
Labels: go

#48114 Add perf metrics for 2.38.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#48209 [Data] Fix missing `DataContext` in `Dataset.count()`
  python/ray/data/dataset.py
Labels: go

#44437 [Java] Upgrade Commons-io to 2.14
  java/dependencies.bzl
Labels: triage, Devprod, go

#48228 [Data] Refactor some file-related unit tests
  python/ray/data/tests/test_binary.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_numpy.py
Labels: go

#48173 [data/preprocessors] make one hot encoder return encoded vector
  python/ray/data/preprocessors/encoder.py
  python/ray/data/tests/preprocessors/test_encoder.py
Labels: go

#48137 [data/preprocessors] do not fail transform_batch on missing column
  python/ray/data/preprocessors/imputer.py
  python/ray/data/tests/preprocessors/test_imputer.py
Labels: go

#48029 Job manager logger file descriptor leak fixed
  python/ray/dashboard/modules/job/job_manager.py
  python/ray/dashboard/tests/test_utils.py
  python/ray/dashboard/utils.py
Labels: triage, job, go

#48238 [docker] Update latest Docker dependencies for 2.38.0 release
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#47980 [core][compiled graphs] Evolve microbenchmark suite names
  release/release_tests.yaml
Labels: go

#48227 [RLlib] Add off-policy'ness metric to new API stack.
  rllib/algorithms/algorithm.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/impala/impala.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group.py
  rllib/core/learner/torch/torch_learner.py
  rllib/env/env_runner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/utils/metrics/__init__.py
  rllib/utils/test_utils.py
Labels: tests-ok, rllib, rllib-newstack, go

#48220 [Serve] Expose ApplicationStatus class to API docs (#34966)
  doc/source/serve/api/index.md
  python/ray/dashboard/modules/serve/tests/test_serve_dashboard.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_request_timeout.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/test_telemetry.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_common.py
Labels: go

#47958 [ADAG] Add visualization of compiled graphs
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: triage, core, compiled-graph, go

#48256 [ci] correcting update high impact field of test object
  ci/ray_ci/automation/determine_microcheck_tests.py
  ci/ray_ci/automation/test_determine_microcheck_tests.py
Labels: go

#47860 [core][adag] Support asyncio.gather on multiple CompiledDAGFutures (#47684)
  python/ray/_private/ray_experimental_perf.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: triage, core, compiled-graph, go

#48259 [core] Deflake test_threaded_actor by increasing timeout
  python/ray/tests/BUILD
Labels: go

#48255 [train] change all awsv2 to aws
  doc/source/templates/04_finetuning_llms_with_deepspeed/utils.py
  doc/source/train/examples/deepspeed/gptj_deepspeed_fine_tuning.ipynb
  doc/source/train/examples/lightning/vicuna_13b_lightning_deepspeed_finetune.ipynb
Labels: go

#47872 Add IsHeadNode tag to node metrics
  python/ray/dashboard/consts.py
  python/ray/dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  python/ray/dashboard/modules/reporter/reporter_agent.py
  python/ray/dashboard/modules/reporter/tests/test_reporter.py
Labels: go

#48250 Revert "[core][compiled graphs] Fix test_torch_tensor_dag_gpu CI fail…
  python/ray/_private/ray_experimental_perf.py
  python/ray/_private/worker.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_detect_deadlock_dag.py
  python/ray/dag/tests/experimental/test_execution_schedule_gpu.py
  python/ray/dag/tests/experimental/test_multi_args_gpu.py
  python/ray/dag/tests/experimental/test_multi_node_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
Labels: go

#48243 [Data] Remove buffer capacity from ShufflingBatcher
  python/ray/data/_internal/batcher.py
Labels: go

#48273 [Data] Cast `Dataset.count()` explicitly to `int`
  python/ray/data/dataset.py
  python/ray/data/tests/test_parquet.py
Labels: go

#48115 [Core] Add demands info to GCS debug state
  src/ray/common/task/task_spec.h
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/raylet/local_task_manager.cc
Labels: go

#45677 [core][experimental] Accelerated DAG: Infer torch.Tensor shape and metadata on first DAG execution
  python/ray/_private/worker.py
  python/ray/dag/BUILD
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_mocked_nccl_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/conftest.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/tests/test_nccl_channel.py
  release/microbenchmark/experimental/accelerated_dag_gpu_microbenchmark.py
Labels: P1, performance, core, compiled-graph, go

#48279 [serve] increase test_new_router_on_gcs_failure timeout
  python/ray/serve/tests/test_gcs_failure.py
Labels: go

#48281 [Core] remove bad logs
  src/ray/core_worker/transport/actor_task_submitter.cc
Labels: go

#48223 [serve] Remove ability to specify `route_prefix` at deployment level
  doc/source/serve/doc_code/image_classifier_example.py
  doc/source/serve/doc_code/translator_example.py
  java/serve/src/main/java/io/ray/serve/api/Serve.java
  java/serve/src/main/java/io/ray/serve/api/ServeControllerClient.java
  java/serve/src/main/java/io/ray/serve/dag/Graph.java
  java/serve/src/main/java/io/ray/serve/deployment/Deployment.java
  java/serve/src/main/java/io/ray/serve/deployment/DeploymentCreator.java
  java/serve/src/test/java/io/ray/serve/deployment/CrossLanguageDeploymentTest.java
  java/serve/src/test/java/io/ray/serve/deployment/DeploymentGraphTest.java
  java/serve/src/test/java/io/ray/serve/deployment/DeploymentTest.java
  java/serve/src/test/java/io/ray/serve/docdemo/ManagePythonDeployment.java
  java/serve/src/test/java/io/ray/serve/repdemo/DeploymentDemo.java
  python/ray/serve/_private/api.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deploy_utils.py
  python/ray/serve/_private/deployment_function_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/utils.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/schema.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_cli_2.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_deployment_graph_ingress.py
  python/ray/serve/tests/test_deployment_node.py
  python/ray/serve/tests/test_fastapi.py
  python/ray/serve/tests/test_http_routes.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/test_websockets.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_deployment_class.py
  python/ray/serve/tests/unit/test_schema.py
  release/golden_notebook_tests/workloads/torch_tune_serve_test.py
Labels: go

#48213 [RLlib] Fix `ConnectorPipelineV2` restoring from checkpoint (by writing information about individual connector pieces to the `ctor_args_and_kwargs` file).
  rllib/connectors/connector_pipeline_v2.py
  rllib/connectors/connector_v2.py
  rllib/tuned_examples/ppo/cartpole_ppo.py
Labels: go

#45328 [RLlib] Upgrade to gymnasium 1.0.0 (ale_py 0.10.1, mujoco 3.2.4, pettingzoo 1.24.3 supersuit 3.9.3).
  doc/source/ray-core/examples/plot_pong_example.ipynb
  doc/source/rllib/doc_code/dreamerv3_inference.py
  doc/source/rllib/doc_code/training.py
  doc/source/rllib/rllib-examples.rst
  python/requirements.txt
  python/requirements/ml/rllib-test-requirements.txt
  python/requirements_compiled.txt
  python/setup.py
  release/ray_release/byod/requirements_byod_3.9.txt
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dreamerv3/README.md
  rllib/algorithms/dreamerv3/tests/test_dreamerv3.py
  rllib/algorithms/dreamerv3/utils/env_runner.py
  rllib/algorithms/ppo/tests/test_ppo.py
  rllib/algorithms/ppo/tests/test_ppo_old_api_stack.py
  rllib/algorithms/ppo/tests/test_ppo_rl_module.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/algorithms/tests/test_callbacks_on_env_runner.py
  rllib/benchmarks/ppo/benchmark_atari_ppo.py
  rllib/benchmarks/torch_compile/run_inference_bm.py
  rllib/benchmarks/torch_compile/run_ppo_with_inference_bm.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/env/single_agent_episode.py
  rllib/env/tests/test_single_agent_env_runner.py
  rllib/env/utils/__init__.py
  rllib/env/wrappers/atari_wrappers.py
  rllib/env/wrappers/kaggle_wrapper.py
  rllib/env/wrappers/model_vector_env.py
  rllib/env/wrappers/recsim.py
  rllib/env/wrappers/recsim_wrapper.py
  rllib/env/wrappers/uncertainty_wrappers.py
  rllib/examples/_old_api_stack/custom_keras_model.py
  rllib/examples/connectors/frame_stacking.py
  rllib/examples/curiosity/euclidian_distance_based_curiosity.py
  rllib/examples/curiosity/intrinsic_curiosity_model_based_curiosity.py
  rllib/examples/envs/env_rendering_and_recording.py
  rllib/examples/evaluation/custom_evaluation.py
  rllib/examples/metrics/custom_metrics_in_env_runners.py
  rllib/examples/ray_tune/custom_experiment.py
  rllib/examples/rl_modules/custom_cnn_rl_module.py
  rllib/models/tests/test_preprocessors.py
  rllib/tuned_examples/bc/benchmark_atari_pong_bc.py
  rllib/tuned_examples/impala/pong_impala.py
  rllib/tuned_examples/impala/pong_impala_pb2_hyperopt.py
  rllib/tuned_examples/ppo/atari_ppo.py
  rllib/utils/error.py
  rllib/utils/exploration/tests/test_curiosity.py
Labels: P1, rllib, go

#48229 [core][dashboard] Reworking dashboard_max_actors_to_cache to RAY_maximum_gcs_destroyed_actor_cached_count
  .clang-tidy
  doc/source/ray-observability/getting-started.rst
  python/ray/dashboard/modules/actor/actor_head.py
  python/ray/dashboard/tests/conftest.py
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  src/ray/common/ray_config.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/gcs/pubsub/gcs_pub_sub.h
Labels: dashboard, core, go

#48270 [CI] fix: flake8 rule B020: Found for loop that reassigns the iterable it is iterating with each iterable value.
  doc/source/custom_directives.py
  python/ray/autoscaler/v2/tests/test_instance_util.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_split.py
  python/ray/tests/test_metrics_agent_2.py
  python/ray/train/examples/horovod/horovod_cifar_pbt_example.py
  python/ray/tune/examples/custom_func_checkpointing.py
  release/air_tests/horovod/workloads/horovod_tune_test.py
  release/nightly_tests/dask_on_ray/dask_on_ray_sort.py
Labels: go

#48291 [serve] Update codeowners
  .github/CODEOWNERS
Labels: go

#48232 [serve] handle options refactor
  python/ray/serve/_private/client.py
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/proxy_router.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_gcs_failure.py
  python/ray/serve/tests/test_handle.py
  python/ray/serve/tests/test_multiplex.py
Labels: go

#48293 Fix broken requirements_boyd_3.9
  release/ray_release/byod/requirements_byod_3.9.in
  release/ray_release/byod/requirements_byod_3.9.txt
Labels: go

#48290 [serve] Reduce cardinality for the `route` metric tag
  python/ray/serve/_private/common.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/proxy_request_response.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/thirdparty/__init__.py
  python/ray/serve/_private/thirdparty/get_asgi_route_name.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_replica_request_context.py
  python/ray/serve/tests/unit/test_get_asgi_app_route.py
  python/ray/serve/tests/unit/test_user_callable_wrapper.py
Labels: go

#48234 [Observability] Added object refs Task is dependent on to `TaskInfoEntry`
  python/ray/dashboard/utils.py
  python/ray/tests/test_state_api.py
  python/ray/util/state/common.py
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
Labels: go

#48242 [Core] Add PENDING_ACTOR_TASK_ARGS_FETCH and PENDING_ACTOR_TASK_ORDERING_OR_CONCURRENCY TaskStatus
  python/ray/dashboard/client/src/pages/job/hook/useJobProgress.ts
  python/ray/dashboard/client/src/type/task.ts
  python/ray/tests/test_actor_cancel.py
  python/ray/tests/test_state_api.py
  python/ray/util/state/custom_types.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/actor_scheduling_util.cc
  src/ray/core_worker/transport/actor_scheduling_util.h
  src/ray/core_worker/transport/normal_scheduling_queue.cc
  src/ray/core_worker/transport/normal_scheduling_queue.h
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.h
  src/ray/core_worker/transport/scheduling_queue.h
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
  src/ray/protobuf/common.proto
Labels: go

#48294 Revert "Revert "[serve] Remove ability to specify `route_prefix` at deployment level" (#48292)"
  doc/source/serve/doc_code/image_classifier_example.py
  doc/source/serve/doc_code/translator_example.py
  java/serve/src/main/java/io/ray/serve/api/Serve.java
  java/serve/src/main/java/io/ray/serve/api/ServeControllerClient.java
  java/serve/src/main/java/io/ray/serve/dag/Graph.java
  java/serve/src/main/java/io/ray/serve/deployment/Deployment.java
  java/serve/src/main/java/io/ray/serve/deployment/DeploymentCreator.java
  java/serve/src/test/java/io/ray/serve/deployment/CrossLanguageDeploymentTest.java
  java/serve/src/test/java/io/ray/serve/deployment/DeploymentGraphTest.java
  java/serve/src/test/java/io/ray/serve/deployment/DeploymentTest.java
  java/serve/src/test/java/io/ray/serve/docdemo/ManagePythonDeployment.java
  java/serve/src/test/java/io/ray/serve/repdemo/DeploymentDemo.java
  python/ray/serve/_private/api.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deploy_utils.py
  python/ray/serve/_private/deployment_function_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/utils.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/schema.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_cli_2.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_deployment_graph_ingress.py
  python/ray/serve/tests/test_deployment_node.py
  python/ray/serve/tests/test_fastapi.py
  python/ray/serve/tests/test_http_routes.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/test_websockets.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_deployment_class.py
  python/ray/serve/tests/unit/test_schema.py
  release/golden_notebook_tests/workloads/torch_tune_serve_test.py
Labels: go

#48103 [ci][tune][train] Update release test compute configs to not schedule work on head node
  release/air_tests/air_benchmarks/compute_cpu_1_aws.yaml
  release/air_tests/air_benchmarks/compute_cpu_1_gce.yaml
  release/air_tests/air_benchmarks/compute_cpu_4_aws.yaml
  release/air_tests/air_benchmarks/compute_cpu_4_gce.yaml
  release/air_tests/air_benchmarks/compute_cpu_8_aws.yaml
  release/air_tests/air_benchmarks/compute_cpu_8_gce.yaml
  release/air_tests/air_benchmarks/compute_gpu_1_aws.yaml
  release/air_tests/air_benchmarks/compute_gpu_1_gce.yaml
  release/air_tests/air_benchmarks/compute_gpu_2x2_aws.yaml
  release/air_tests/air_benchmarks/compute_gpu_2x2_gce.yaml
  release/air_tests/air_benchmarks/compute_gpu_4x4_aws.yaml
  release/air_tests/air_benchmarks/compute_gpu_4x4_gce.yaml
  release/air_tests/air_benchmarks/workloads/benchmark_util.py
  release/air_tests/air_benchmarks/workloads/tensorflow_benchmark.py
  release/air_tests/air_benchmarks/workloads/torch_benchmark.py
  release/air_tests/air_benchmarks/workloads/tune_torch_benchmark.py
Labels: go

#48252 [serve] refactor router
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/replica_scheduler/__init__.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
  python/ray/serve/handle.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#48303 [serve] move deployment scheduler test
  python/ray/serve/tests/BUILD
Labels: go

#47972 [RLlib] `AutoregressiveActionsRLM` overhaul to fix flaky test and simplify.
  rllib/examples/rl_modules/autoregressive_actions_rl_module.py
  rllib/examples/rl_modules/classes/autoregressive_actions_rlm.py
Labels: bug, rllib, rllib-models, rllib-docs-or-examples, go

#48282 [core][compiled graph] remove dead code
  python/ray/dag/output_node.py
Labels: go

#48286 [RLlib] Change `config.fault_tolerance` default behavior (from `recreate_failed_env_runners=False` to `True`).
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-fault-tolerance.rst
  doc/source/rllib/rllib-training.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/tests/test_callbacks_on_algorithm.py
  rllib/algorithms/tests/test_env_runner_failures.py
  rllib/algorithms/tests/test_node_failures.py
  rllib/env/env_context.py
  rllib/env/env_runner_group.py
  rllib/evaluation/rollout_worker.py
  rllib/examples/fault_tolerance/crashing_and_stalling_env.py
  rllib/tuned_examples/appo/cartpole-crashing-and-stalling-recreate-workers-appo.py
  rllib/tuned_examples/appo/cartpole-crashing-recreate-workers-appo.py
  rllib/tuned_examples/appo/multi-agent-cartpole-crashing-and-stalling-recreate-workers-appo.py
  rllib/tuned_examples/appo/multi-agent-cartpole-crashing-recreate-workers-appo.py
  rllib/utils/actor_manager.py
  rllib/utils/tests/test_actor_manager.py
Labels: go

#47873 [serve] recursive cancellation
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/replica_result.py
  python/ray/serve/_private/router.py
  python/ray/serve/context.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_cancellation.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#48218 [serve] Simplify application build codepath
  python/ray/serve/_private/api.py
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/build_app.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/deployment_function_node.py
  python/ray/serve/_private/deployment_graph_build.py
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/scripts.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deployment_graph_handle_serde.py
  python/ray/serve/tests/test_model_composition.py
  python/ray/serve/tests/unit/test_build_app.py
  python/ray/serve/tests/unit/test_deployment_class.py
Labels: go

#47810 Fix response injection
  python/ray/dashboard/modules/state/state_head.py
  python/ray/dashboard/optional_utils.py
  python/ray/tests/test_state_api_log.py
Labels: P1, dashboard, security, go

#48322 Fix lint
  python/ray/serve/_private/router.py
Labels: go
