Repository ray-project/ray, pull requests merged in 2024-12, with the labels that each got.

#48988 [RLlib] Add comments to example files for templates.
  rllib/examples/envs/custom_gym_env.py
  rllib/tuned_examples/ppo/atari_ppo.py
Labels: rllib, rllib-docs-or-examples, rllib-newstack, go

#48309 [RLlib; Offline RL] Fix small memory leak in `OfflineSingleAgentEnvRunner`.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/examples/offline_rl/cartpole_recording.py
  rllib/offline/offline_env_runner.py
  rllib/tuned_examples/bc/cartpole_recording.py
Labels: rllib, rllib-system, rllib-offline-rl, go

#48958 [core] Ray Core / Ray Data logging configuration leads to unexpected behavior
  python/ray/_private/log.py
  python/ray/_private/ray_logging/__init__.py
  python/ray/_private/ray_logging/default_impl.py
  python/ray/_private/ray_logging/logging_config.py
  python/ray/tests/test_logging_2.py
Labels: go

#48722 [core] Make absl::StrCat import explicit to avoid build failures when using modern absl
  src/ray/object_manager/common.cc
Labels: core, go

#49016 [data] Expression support for filters
  python/ray/data/BUILD
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/planner/plan_expression/__init__.py
  python/ray/data/_internal/planner/plan_expression/expression_evaluator.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_expression_evaluator.py
  python/ray/data/tests/test_map.py
Labels: go

#48975 [core] [easy] Cleanup shared pointer for runtime env client
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/runtime_env_agent_client.cc
  src/ray/raylet/runtime_env_agent_client.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: go

#48993 [core] Cleanup shared pointer usage for plasma
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: go

#48923 [Data] Always launch one task for `read_sql`
  python/ray/data/_internal/datasource/sql_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_sql.py
Labels: go

#48677 [core] Refactors WorkerPool with Prestarts.
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/BUILD
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: go

#49012 [Data] Update batch inference release tests
  release/nightly_tests/dataset/autoscaling_cpu_compute.yaml
  release/nightly_tests/dataset/autoscaling_gpu_compute.yaml
  release/nightly_tests/dataset/autoscaling_hetero_compute.yaml
  release/nightly_tests/dataset/compute_hetero_10x10_aws.yaml
  release/nightly_tests/dataset/gpu_batch_inference.py
  release/release_data_tests.yaml
Labels: go

#48954 [core] Enable heterogeneous access for LRU cache
  src/ray/util/shared_lru.h
  src/ray/util/tests/shared_lru_test.cc
Labels: go

#48969 [Data] Raise ValueError when the data sort key is None
  python/ray/data/dataset.py
  python/ray/data/tests/test_optimize.py
Labels: go

#47988 [Core][Azure] Enable accelerated networking as a flag in azure vms
  python/ray/autoscaler/_private/_azure/azure-vm-template.json
Labels: core, core-hardware, go

#48936 [Doc] Logging: Delete the sections from `Set up logging on a DaemonSet with Fluent Bit` to `Check the CloudWatch dashboard`.
  doc/source/cluster/kubernetes/user-guides/persist-kuberay-custom-resource-logs.md
Labels: go

#48201 Add v6e TPU Head Resource Autoscaling Support
  python/ray/autoscaler/_private/kuberay/utils.py
  python/ray/tests/kuberay/test_autoscaling_config.py
Labels: go

#49021 Fix linting
  doc/source/cluster/metrics.md
  doc/source/templates/04_finetuning_llms_with_deepspeed/compute_configs/aws_70b_v1.yaml
  doc/source/templates/04_finetuning_llms_with_deepspeed/compute_configs/aws_70b_v2.yaml
  doc/source/templates/04_finetuning_llms_with_deepspeed/compute_configs/aws_7b_or_13b.yaml
  doc/source/templates/README.md
  doc/source/templates/testing/compute_configs/04_finetuning_llms_with_deepspeed/aws_70b_v1.yaml
  doc/source/templates/testing/compute_configs/04_finetuning_llms_with_deepspeed/aws_70b_v2.yaml
  doc/source/templates/testing/compute_configs/04_finetuning_llms_with_deepspeed/aws_7b.yaml
  doc/source/templates/testing/compute_configs/cpu/aws.yaml
  doc/source/templates/testing/compute_configs/gpu/aws.yaml
  doc/source/train/examples.yml
  doc/source/train/examples/aws-trainium/llama3.rst
  python/ray/autoscaler/kuberay/ray-cluster.complete.yaml
  release/air_tests/air_benchmarks/compute_gpu_4x4_aws.yaml
  release/long_running_tests/tpl_cpu_1_large.yaml
  release/long_running_tests/tpl_cpu_1_large_gce.yaml
  release/nightly_tests/dataset/shuffle_compute.yaml
  release/nightly_tests/stress_tests/placement_group_tests_compute_gce.yaml
  release/rllib_tests/1gpu_16cpus.yaml
  release/rllib_tests/1gpu_16cpus_gce.yaml
  release/rllib_tests/1gpu_32cpus.yaml
  release/tune_tests/fault_tolerance_tests/tpl_aws_16x1.yaml
  release/tune_tests/fault_tolerance_tests/tpl_gce_16x1.yaml
  release/tune_tests/scalability_tests/tpl_gce_1x32_hd.yaml
Labels: go

#49020 [data] update codeowners to use a group instead
  .github/CODEOWNERS
Labels: go

#49026 [core] Cleanup shared pointer for local task manager
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
  src/ray/raylet/local_task_manager_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: go

#48964 [core] remove PythonGcsClient as well as Python gRPC stubs to GCS.
  python/ray/_private/gcs_aio_client.py
  python/ray/_raylet.pyx
  python/ray/dashboard/modules/actor/actor_head.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/snapshot/snapshot_head.py
  python/ray/includes/common.pxd
  python/ray/includes/common.pxi
  python/ray/includes/gcs_client.pxi
  python/ray/tests/test_gcs_fault_tolerance.py
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
Labels: go

#48970 [Data] Reimplement of fix memory pandas
  python/ray/data/_internal/pandas_block.py
  python/ray/data/tests/test_pandas_block.py
Labels: data, go

#48868 [RLlib] APPO (new API stack) enhancements vol 05: Auto-sleep time AND thread-safety for MetricsLogger.
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/appo_learner.py
  rllib/algorithms/appo/appo_rl_module.py
  rllib/algorithms/appo/torch/appo_torch_learner.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/algorithms/impala/utils.py
  rllib/core/learner/learner.py
  rllib/core/learner/tf/tf_learner.py
  rllib/core/learner/torch/torch_learner.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/tuned_examples/appo/pong_appo.py
  rllib/utils/metrics/metrics_logger.py
  rllib/utils/metrics/stats.py
Labels: rllib, rllib-algorithms, rllib-newstack, go

#48643 [data] provide more messages when webdataset format is error
  python/ray/data/_internal/datasource/webdataset_datasource.py
Labels: data, go

#47981 [Core] Retryable grpc client
  BUILD.bazel
  python/ray/tests/test_streaming_generator_4.py
  src/mock/ray/raylet_client/raylet_client.h
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
  src/ray/rpc/retryable_grpc_client.cc
  src/ray/rpc/retryable_grpc_client.h
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_client_pool.cc
  src/ray/rpc/worker/core_worker_client_pool.h
  src/ray/rpc/worker/test/core_worker_client_pool_test.cc
Labels: go

#49006 [Data] Add writing benchmark
  release/nightly_tests/dataset/read_and_consume_benchmark.py
  release/release_data_tests.yaml
Labels: go

#49033 [RLlib] External Env support for new API stack: New example script and custom tcp-capable EnvRunner.
  doc/source/rllib/index.rst
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/env/utils.rst
  doc/source/rllib/rllib-examples.rst
  rllib/BUILD
  rllib/algorithms/ppo/torch/ppo_torch_learner.py
  rllib/connectors/connector_v2.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/env/env_runner.py
  rllib/env/env_runner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/policy_client.py
  rllib/env/single_agent_env_runner.py
  rllib/env/tcp_client_inference_env_runner.py
  rllib/env/utils/external_env_protocol.py
  rllib/evaluation/rollout_worker.py
  rllib/examples/envs/env_connecting_to_rllib_w_tcp_client.py
  rllib/examples/envs/env_w_protobuf_observations.py
  rllib/offline/offline_env_runner.py
  rllib/offline/tests/test_offline_env_runner.py
Labels: rllib, rllib-client-server, rllib-env, rllib-docs-or-examples, rllib-newstack, rllib-envrunners, go

#48674 [data] webdataset - flatten return args
  python/ray/data/_internal/datasource/webdataset_datasource.py
  python/ray/data/tests/test_webdataset.py
Labels: data, go

#49022 [core] Fix potential data race for random number generator
  src/ray/util/util.h
Labels: go

#48519 [core][autoscaler] Fix incorrectly terminating nodes misclassified as idle in autoscaler v1
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/load_metrics.py
  python/ray/autoscaler/_private/monitor.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_autoscaler_fake_multinode.py
  python/ray/tests/test_autoscaling_policy.py
  python/ray/tests/test_resource_demand_scheduler.py
Labels: go

#48981 [core] [no-op] Restructure ray syncer
  src/ray/common/BUILD
  src/ray/common/ray_syncer/common.h
  src/ray/common/ray_syncer/node_state.cc
  src/ray/common/ray_syncer/node_state.h
  src/ray/common/ray_syncer/ray_syncer-inl.h
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/ray_syncer/ray_syncer_bidi_reactor.h
  src/ray/common/ray_syncer/ray_syncer_bidi_reactor_base.h
  src/ray/common/ray_syncer/ray_syncer_client.cc
  src/ray/common/ray_syncer/ray_syncer_client.h
  src/ray/common/ray_syncer/ray_syncer_server.cc
  src/ray/common/ray_syncer/ray_syncer_server.h
  src/ray/common/test/ray_syncer_test.cc
Labels: go

#49009 fix docs: typo in saving-data.rst
  doc/source/data/saving-data.rst
Labels: docs, go

#48064 [data/air] handle numpy > 2.0.0 behaviour in _create_possibly_ragged_ndarray
  python/ray/air/util/tensor_extensions/utils.py
Labels: go

#49019 [train][lightgbm] Rewrite `get_network_params` implementation
  python/ray/train/lightgbm/config.py
  python/ray/train/lightgbm/v2.py
Labels: go

#49052 Add some end of file markers for Train `__init__.py` files
  python/ray/train/__init__.py
  python/ray/train/horovod/__init__.py
  python/ray/train/huggingface/transformers/__init__.py
  python/ray/train/lightgbm/__init__.py
  python/ray/train/lightning/__init__.py
  python/ray/train/tensorflow/__init__.py
  python/ray/train/torch/__init__.py
  python/ray/train/xgboost/__init__.py
Labels: go

#49025 [core][autoscaler] make logging level configurable
  python/ray/_private/ray_constants.py
  python/ray/autoscaler/_private/kuberay/run_autoscaler.py
Labels: go

#49049 [docker] Update latest Docker dependencies for 2.40.0 release
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#49043 [docker] Update latest Docker dependencies for 2.40.0 release
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#49056 Fix lint
  release/release_data_tests.yaml
Labels: go

#49023 [core] Use ref hash to avoid key copy
  src/ray/util/BUILD
  src/ray/util/map_utils.h
  src/ray/util/shared_lru.h
Labels: go

#48884 Adding image_uri to docstring of runtime_env
  python/ray/runtime_env/runtime_env.py
Labels: go

#48990 [core] [6/N] Fix shared pointer usage for gcs server
  src/mock/ray/gcs/gcs_server/gcs_actor_manager.h
  src/mock/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_init_data.cc
  src/ray/gcs/gcs_server/gcs_init_data.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/pubsub_handler.cc
  src/ray/gcs/gcs_server/pubsub_handler.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_node_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_node_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_worker_manager_test.cc
Labels: go

#49061 [core] remove redundant import
  src/ray/raylet_client/raylet_client.cc
Labels: go

#49037 [RLlib; docs] Fix RLlib main index page (code in multi-agent tab wrong).
  doc/source/rllib/index.rst
Labels: tests-ok, rllib, rllib-multi-agent, rllib-docs-or-examples, rllib-newstack, go

#49046 [RLlib; Offline RL] Offline RL example that shows how to customize an offline data pipeline.
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/examples/offline_rl/classes/__init__.py
  rllib/examples/offline_rl/classes/image_offline_data.py
  rllib/examples/offline_rl/classes/image_offline_prelearner.py
  rllib/examples/offline_rl/offline_rl_with_image_data.py
  rllib/offline/offline_prelearner.py
  rllib/offline/tests/test_offline_data.py
Labels: rllib, rllib-offline-rl, rllib-docs-or-examples, rllib-newstack, go

#49057 [release/doc] Update Dask version in doc for Ray 2.40.0
  doc/source/ray-more-libs/dask-on-ray.rst
Labels: go

#49048 [core] Remove connect at start
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
Labels: go

#49015 [RLlib; Offline Data] Give users option to customize `OfflineData`.
  rllib/algorithms/algorithm_config.py
Labels: enhancement, rllib, rllib-offline-rl, rllib-newstack, go

#49071 [RLlib] Adapted action masking example to new `RLModule` configuration scheme.
  rllib/examples/rl_modules/classes/action_masking_rlm.py
Labels: go

#49065 [core] fix more broken imports
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool.cc
Labels: go

#48793 Preserve ray/serve/generated when creating softlink for serve package
  python/ray/setup-dev.py
Labels: serve, go

#48978 Upgrade py-spy to 0.4.0 for py312 support
  python/requirements.txt
  python/requirements_compiled.txt
  python/setup.py
Labels: continuous-build, go

#48915 Add perf metrics for 2.40.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#49067 [doc] fix typo in core generators.rst
  doc/source/ray-core/tasks/generators.rst
Labels: go

#49066 [core][autoscaler] record v2 usage
  python/ray/autoscaler/v2/monitor.py
Labels: go

#47776 [core][aDAG] suppress numpy is_writable warning
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/serialization_context.py
Labels: @author-action-required, go

#48876 [Data] Add groupby benchmark
  release/nightly_tests/dataset/all_to_all_compute.yaml
  release/nightly_tests/dataset/groupby_benchmark.py
  release/release_data_tests.yaml
Labels: go

#49079 [Doc] Fix minor glitch in installation docs
  doc/source/ray-overview/installation.rst
Labels: go

#48596 [Docs][KubeRay] Add doc for using RayJob with existing RayCluster
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
Labels: go

#49031 [core] [5/N] Cleanup shared pointer for gcs actor scheduler
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: go

#49077 [core] Fix broken includes
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/util/BUILD
  src/ray/util/shared_lru.h
  src/ray/util/tests/shared_lru_test.cc
  src/ray/util/tests/size_literals_test.cc
  src/ray/util/tests/thread_checker_test.cc
  src/ray/util/thread_checker.cc
Labels: go

#48963 [core] [adag] Support all driver and actor read combinations
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/tests/test_channel.py
  python/ray/tests/test_nccl_channel.py
Labels: go

#49000 [Refactor][GCS] Merge RedisAsioClient into RedisAsyncContext
  BUILD.bazel
  src/ray/gcs/asio.cc
  src/ray/gcs/asio.h
  src/ray/gcs/redis_async_context.cc
  src/ray/gcs/redis_async_context.h
  src/ray/gcs/redis_client.cc
  src/ray/gcs/redis_client.h
  src/ray/gcs/redis_context.cc
  src/ray/gcs/test/redis_async_context_test.cc
Labels: go

#49092 Fix linting
  python/ray/autoscaler/_private/_azure/azure-vm-template.json
  release/nightly_tests/dataset/autoscaling_gpu_compute.yaml
  release/perf_metrics/metadata.json
  release/release_data_tests.yaml
Labels: go

#49093 Another cleanup for test main
  src/ray/common/test/BUILD
  src/ray/common/test/asio_defer_test.cc
  src/ray/common/test/bundle_location_index_test.cc
  src/ray/common/test/client_connection_test.cc
  src/ray/common/test/event_stats_test.cc
  src/ray/common/test/id_test.cc
  src/ray/common/test/memory_monitor_test.cc
  src/ray/common/test/ray_config_test.cc
  src/ray/common/test/resource_request_test.cc
  src/ray/common/test/resource_set_test.cc
  src/ray/common/test/status_test.cc
  src/ray/common/test/task_spec_test.cc
Labels: go

#49101 [RLlib] Move all new stack Offline RL classes to `PublicAPI(stability='alpha')`.
  rllib/offline/offline_data.py
  rllib/offline/offline_env_runner.py
  rllib/offline/offline_prelearner.py
Labels: rllib, rllib-offline-rl, rllib-newstack, go

#49090 [core] Cleanup clang-format off in prod code
  src/ray/raylet/dependency_manager.h
  src/ray/raylet/raylet.h
Labels: go

#46668 [data] move _munge_conflict to parent class
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/table_block.py
Labels: data, go

#49041 [RLlib; Offline RL] Enable offline training without specifying an environment.
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/marwil/tests/test_marwil.py
  rllib/offline/tests/test_offline_data.py
  rllib/offline/tests/test_offline_prelearner.py
  rllib/tuned_examples/bc/cartpole_bc.py
Labels: enhancement, rllib, rllib-offline-rl, rllib-newstack, go

#49086 [core][compiled-graphs] remove `actor_task_count`
  python/ray/dag/compiled_dag_node.py
Labels: go

#49055 [core][compiled graph] Fix execution schedule visualization
  python/ray/dag/dag_node_operation.py
Labels: go

#49106 [Data] Sort Data release tests
  release/release_data_tests.yaml
Labels: go

#48871 Move num_cpu note to resources page to avoid confusion
  doc/source/ray-core/configure.rst
  doc/source/ray-core/scheduling/resources.rst
Labels: go

#49085 [KubeRay] Add instructions on how to use Kustomize
  doc/source/cluster/kubernetes/getting-started/raycluster-quick-start.md
Labels: go

#49089 [core] [7/N] Cleanup gcs server shared pointer
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.cc
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/scheduler_stats.cc
Labels: go

#49110 [core] Remove useless function
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/ray_syncer/ray_syncer.h
  src/ray/gcs/gcs_server/gcs_server.cc
Labels: go

#47773 [Core][Fix] Fix "No error is raised when the "bind" args does not match the function signature"
  python/ray/_private/signature.py
  python/ray/actor.py
  python/ray/dag/class_node.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#49096 [data] Fix DataContext sealing for multiple datasets.
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/aggregate_num_rows.py
  python/ray/data/_internal/execution/operators/base_physical_operator.py
  python/ray/data/_internal/execution/operators/input_data_buffer.py
  python/ray/data/_internal/execution/operators/limit_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/execution/operators/union_operator.py
  python/ray/data/_internal/execution/operators/zip_operator.py
  python/ray/data/_internal/execution/resource_manager.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/_internal/logical/interfaces/plan.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/_internal/planner/plan_read_op.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/planner/plan_write_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/context.py
  python/ray/data/tests/test_backpressure_policies.py
  python/ray/data/tests/test_context_propagation.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_resource_manager.py
  python/ray/data/tests/test_size_estimation.py
  python/ray/data/tests/test_streaming_executor.py
  python/ray/data/tests/test_streaming_integration.py
Labels: go

#49121 Fix linting
  release/release_data_tests.yaml
Labels: go

#49018 Suppress unused function warning for 3rd party libraries
  .bazelrc
Labels: go

#49098 [RLlib] Fix `TorchMultiCategorical.to_deterministic` to return a multi-dimensional tensor instead of a list.
  rllib/models/torch/torch_distributions.py
Labels: go

#47763 Move memray dependency from default to observability
  python/setup.py
Labels: go

#49118 [core][compiled graphs] Fix the missing dependencies when num_returns is used
  python/ray/dag/dag_node_operation.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#49108 [core] [C++] Minor optimization to ray syncer
  src/ray/common/ray_syncer/ray_syncer.cc
Labels: go

#49128 [core] Fix gcs server data member order
  src/ray/gcs/gcs_server/gcs_server.h
Labels: go

#49115 [Compiled Graph] Compiled graph documentation V0
  doc/source/ray-core/compiled-graph/quickstart.rst
  doc/source/ray-core/compiled-graph/ray-compiled-graph.rst
  doc/source/ray-core/user-guide.rst
Labels: go

#48875 [data] update hudi version to 0.2.0
  python/ray/data/_internal/datasource/hudi_datasource.py
  python/requirements/ml/data-test-requirements.txt
  python/requirements_compiled.txt
Labels: data, go

#49054 [data] Fix performance degradation on iceberg data source when reading large iceberg table
  python/ray/data/_internal/datasource/iceberg_datasource.py
Labels: go

#49137 [core] Task submitter shared pointer cleanup
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/actor_manager_test.cc
Labels: go

#49112 [Core] Make periodical runner thread safe.
  python/ray/_raylet.pyx
  python/ray/serve/tests/test_callback.py
  src/ray/common/asio/periodical_runner.cc
  src/ray/common/asio/periodical_runner.h
  src/ray/common/file_system_monitor.cc
  src/ray/common/file_system_monitor.h
  src/ray/common/memory_monitor.cc
  src/ray/common/memory_monitor.h
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/test/syncer_service_e2e_test.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.cc
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
  src/ray/pubsub/publisher.h
  src/ray/pubsub/test/integration_test.cc
  src/ray/pubsub/test/publisher_test.cc
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/cluster_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
Labels: go

#49150 [core][autoscaler] Fuse scaling requests together to avoid overloading the Kubernetes API server
  python/ray/autoscaler/_private/fake_multi_node/node_provider.py
  python/ray/autoscaler/v2/instance_manager/reconciler.py
Labels: go

#49159 [core][raylet] Remove unused function TotalBacklogSize
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
Labels: go

#48315 [core][dag] Add ascii based CG visualization
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_dag_visualization.py
Labels: go

#49144 [RLlib] Deprecate `env_task_fn` API (old API stack).
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/env/apis/__init__.py
  rllib/env/apis/task_settable_env.py
  rllib/examples/_old_api_stack/remote_base_env_with_custom_api.py
  rllib/examples/envs/classes/ant_rand_goal.py
  rllib/examples/envs/classes/cartpole_mass.py
  rllib/examples/envs/classes/curriculum_capable_env.py
  rllib/examples/envs/classes/halfcheetah_rand_direc.py
  rllib/examples/envs/classes/pendulum_mass.py
Labels: tests-ok, rllib, rllib-env, rllib-oldstack-cleanup, go

#49152 [core] Remove gcs InternalConfigTable
  python/ray/tests/test_gcs_utils.py
  src/mock/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/protobuf/gcs.proto
Labels: go

#49017 [Data] Make sort and shuffle release test use an autoscaling cluster
  release/nightly_tests/dataset/sort_benchmark.py
  release/release_data_tests.yaml
Labels: go

#49116 [KubeRay] Add instructions to run distributed Ray Debugger in KubeRay
  doc/source/ray-observability/ray-distributed-debugger.rst
Labels: go

#49177 [core][compiled graphs] Fix _device_context_manager()
  python/ray/dag/compiled_dag_node.py
  python/ray/experimental/channel/common.py
Labels: go

#48828 [core] [1/N] Util functions to setup cgroup preparation
  src/ray/common/cgroup/BUILD
  src/ray/common/cgroup/cgroup_setup.cc
  src/ray/common/cgroup/cgroup_setup.h
Labels: go

#49180 [core][compiled-graphs] deflaky test_signature_mismatch
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: release-blocker, continuous-build, go

#49179 [core] Remove shared pointer of ref count out pf actor manager
  src/ray/core_worker/actor_manager.cc
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/actor_manager_test.cc
Labels: go

#48957 [core][compiled graphs] Support arbitrary torch.dtypes when passing through shared memory
  python/ray/experimental/channel/serialization_context.py
  python/ray/tests/test_channel.py
Labels: go

#48547 updated optuna_search to allow users to configure optuna storage
  python/ray/tune/search/optuna/optuna_search.py
  python/ray/tune/tests/test_searchers.py
  python/requirements/ml/tune-requirements.txt
  python/requirements_compiled.txt
Labels: go

#49191 [RLlib] Fix bugs in `MultiAgentEpisode` class (getters, `env_t_to_agent_t` system, etc..).
  rllib/env/multi_agent_env.py
  rllib/env/multi_agent_episode.py
  rllib/env/single_agent_episode.py
  rllib/env/tests/test_multi_agent_episode.py
  rllib/env/utils/infinite_lookback_buffer.py
Labels: go

#49171 [Data] Revise training benchmarks
  release/release_data_tests.yaml
Labels: go

#48117 Fix rpdb.py for windows and encoding failures, adjust tests
  python/ray/tests/test_ray_debugger.py
  python/ray/util/rpdb.py
Labels: go

#49174 Add instance variables to many default dashboard graphs
  python/ray/dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/default_grafana_dashboard_base.json
Labels: go

#49038 [Doc] Logging: Add Fluent Bit sidecar and Grafana Loki to Persist Ray logs
  doc/source/cluster/kubernetes/configs/ray-cluster.log.yaml
  doc/source/cluster/kubernetes/user-guides/images/loki-sidecar-logs.png
  doc/source/cluster/kubernetes/user-guides/persist-kuberay-custom-resource-logs.md
  doc/source/cluster/kubernetes/user-guides/persist-kuberay-operator-logs.md
Labels: core, go

#49126 [Dashboard] Display duration in milliseconds if under 1 second.
  python/ray/dashboard/client/src/common/DurationText/DurationText.component.test.tsx
  python/ray/dashboard/client/src/common/DurationText/DurationText.tsx
Labels: dashboard, observability, go

#48708 [train] reference custom resources in ScalingConfig.resources_per_worker
  doc/source/train/user-guides/using-gpus.rst
  python/ray/air/config.py
Labels: go

#49217 [CI; RLlib] Increase parallel example scripts processes from 5 to 6.
  .buildkite/rllib.rayci.yml
  .buildkite/rllib_contrib.rayci.yml
  doc/source/rllib/rllib-models.rst
  rllib/BUILD
  rllib/examples/_old_api_stack/complex_struct_space.py
  rllib/examples/_old_api_stack/connectors/adapt_connector_policy.py
  rllib/examples/_old_api_stack/custom_keras_model.py
  rllib/examples/_old_api_stack/models/batch_norm_model.py
  rllib/examples/_old_api_stack/models/custom_model_api.py
  rllib/examples/_old_api_stack/models/eager_model.py
  rllib/examples/_old_api_stack/models/modelv3.py
  rllib/examples/_old_api_stack/models/rnn_model.py
  rllib/examples/_old_api_stack/models/rnn_spy_model.py
  rllib/examples/_old_api_stack/models/trajectory_view_utilizing_models.py
  rllib/examples/_old_api_stack/policy/episode_env_aware_policy.py
  rllib/examples/_old_api_stack/policy/memory_leaking_policy.py
  rllib/examples/_old_api_stack/policy/rock_paper_scissors_dummies.py
  rllib/examples/_old_api_stack/remote_envs_with_inference_done_on_main_node.py
  rllib/examples/_old_api_stack/sb2rllib_rllib_example.py
  rllib/examples/_old_api_stack/sb2rllib_sb_example.py
  rllib/models/tests/test_models.py
  rllib/tests/test_lstm.py
Labels: rllib, rllib-oldstack-cleanup, ci-test, go

#48673 [data] webdataset - expand JSON objects into individual samples
  python/ray/data/_internal/datasource/webdataset_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_webdataset.py
Labels: data, go

#49163 [core][observability] Improve observability when the core worker fails to read data from the Raylet socket
  src/ray/common/client_connection.cc
Labels: go

#47954 [data] remove _split_list dead code
  python/ray/data/_internal/util.py
  python/ray/data/tests/test_util.py
Labels: data, go

#49208 [Data] support passing kwargs to map tasks.
  python/ray/data/_internal/execution/interfaces/task_context.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/tests/test_operators.py
Labels: go

#49205 [data] Add ExecutionCallback interface
  python/ray/data/_internal/execution/execution_callback.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/tests/test_streaming_executor.py
Labels: go

#49178 [serve] Add DEPLOY_FAILED deployment status
  python/ray/dashboard/client/src/type/serve.ts
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_healthcheck.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_deployment_state.py
  src/ray/protobuf/serve.proto
Labels: go

#49060 [Data] Add read_clickhouse API to read ClickHouse Dataset
  doc/source/data/api/input_output.rst
  python/ray/data/BUILD
  python/ray/data/__init__.py
  python/ray/data/_internal/datasource/clickhouse_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_clickhouse.py
  python/requirements/ml/data-test-requirements.txt
Labels: data, go

#49225 [serve] Add missing DEPLOY_FAILED state transitions
  python/ray/serve/_private/common.py
  python/ray/serve/tests/test_api.py
Labels: go

#49212 [core] Cleanup shared pointer for ref counter in memory store
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
  src/ray/core_worker/store_provider/memory_store/memory_store.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/core_worker/test/task_manager_test.cc
Labels: go

#49197 [Data] Add release test for TPCH Q1
  release/nightly_tests/dataset/tpch_q1.py
  release/release_data_tests.yaml
Labels: go

#49219 [core][compiled graphs] Rename RAY_ADAG to RAY_CG
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/constants.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_detect_deadlock_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
Labels: go

#49176 [core] Allow uv cache at installation
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/uv.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_uv.py
  python/ray/tests/unit/test_runtime_env_validation.py
Labels: go

#48765 [Release] Introduce --batch-size-to-kill to release chaos test framework
  python/ray/_private/test_utils.py
  release/nightly_tests/chaos_test/test_chaos_basic.py
  release/nightly_tests/dataset/autoscaling_gpu_compute.yaml
  release/nightly_tests/dataset/gpu_batch_inference.py
  release/nightly_tests/setup_chaos.py
  release/release_data_tests.yaml
Labels: go

#49233 [core] Cleanup resource id shared pointer usage in core worker
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
  src/ray/raylet_client/raylet_client.h
Labels: go

#49139 [data] Fix to_tf for List types
  python/ray/air/_internal/tensorflow_utils.py
  python/ray/data/tests/test_tf.py
Labels: data, go

#49202 [Data] PythonObjectArray missing methods causing serialization failures + tests
  python/ray/air/tests/test_object_extension.py
  python/ray/air/util/object_extensions/pandas.py
Labels: data, go

#48534 [core][compiled graph]Skip python-based deserialization upon CompiledDAGRef's destruction
  python/ray/_private/worker.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/compiled_dag_ref.py
Labels: core, go

#49080 [Docs] Add user guide for configuring authentication for Ray clusters
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/kuberay-auth.md
Labels: go

#49250 [core] [easy] [no-op] Simplify cpp raylet namespace
  src/ray/raylet_client/raylet_client.cc
Labels: go

#49194 [RLlib; Offline RL] 1. Fix multi-learner issue.
  rllib/algorithms/marwil/marwil.py
  rllib/core/learner/learner.py
  rllib/offline/offline_data.py
Labels: rllib, rllib-offline-rl, rllib-newstack, go

#49195 [RLlib; Offline RL] 2. Multiple optimizations for streaming data.
  rllib/algorithms/marwil/tests/test_marwil.py
  rllib/examples/offline_rl/classes/image_offline_prelearner.py
  rllib/offline/offline_data.py
  rllib/offline/offline_prelearner.py
  rllib/offline/tests/test_offline_prelearner.py
  rllib/tuned_examples/bc/benchmark_rlunplugged_atari_pong_bc.py
  rllib/tuned_examples/bc/cartpole_bc.py
  rllib/tuned_examples/bc/pendulum_bc.py
  rllib/tuned_examples/cql/pendulum_cql.py
  rllib/tuned_examples/marwil/cartpole_marwil.py
Labels: tests-ok, enhancement, rllib, rllib-offline-rl, rllib-newstack, go

#49248 [data] Fix NameError by ensuring DataFileContent is imported at runtime in IcebergDatasource class
  python/ray/data/_internal/datasource/iceberg_datasource.py
Labels: go

#49239 [core][compiled graphs] Clean up node visualization
  python/ray/dag/dag_node_operation.py
Labels: go

#48983 [Core] Support != Filter in GCS for Task State API
  python/ray/dashboard/state_aggregator.py
  python/ray/tests/test_state_api.py
  python/ray/util/state/api.py
  python/ray/util/state/common.py
  python/ray/util/state/state_manager.py
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/protobuf/gcs_service.proto
Labels: go

#49221 [data] add column relaxation
  python/ray/data/dataset.py
  python/ray/data/tests/test_map.py
Labels: data, go

#49213 [core][compiled-graphs] TorchTensorNcclChannel should automatically detect whether the reader is on the same actor or not
  python/ray/dag/BUILD
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_detect_deadlock_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/cached_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/experimental/channel/utils.py
  python/ray/tests/test_nccl_channel.py
Labels: go

#48991 [spark] Support databricks mlflow integration and refine error handling for Ray-on-spark worker node launching
  python/ray/autoscaler/_private/spark/spark_job_server.py
  python/ray/util/spark/cluster_init.py
  python/ray/util/spark/databricks_hook.py
Labels: go

#49265 Fix doc lint
  doc/source/cluster/kubernetes/user-guides/kuberay-auth.md
Labels: go

#49236 [core][compiled-graphs] Register custom serializers for InputAttributeNodes and pass their type hints to downstream nodes
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
Labels: go

#48560 [Core] Fix bug to support S3 pre-signed url for .whl file
  python/ray/_private/runtime_env/packaging.py
  python/ray/tests/test_runtime_env_packaging.py
Labels: core, go

#49270 [core] Remove useless hash function
  src/ray/common/id.h
  src/ray/common/test/id_test.cc
Labels: go

#49243 [core] [no-op] [easy] Rename function and add comments for check port free
  src/ray/common/network_util.cc
  src/ray/common/network_util.h
  src/ray/common/test_util.cc
  src/ray/raylet/worker_pool.cc
Labels: go

#49256 Update development.rst to correctly install nvm
  doc/source/ray-contribute/development.rst
Labels: docs, go

#49246 [core] Remove shared pointer for dependency waiter
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
Labels: go

#49280 [core] Fix task manager includes for windows build
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
Labels: go

#49122 [core] [1/N] Ray syncer set observer
  src/ray/common/ray_syncer/common.h
  src/ray/common/ray_syncer/node_state.h
  src/ray/common/ray_syncer/ray_syncer.cc
  src/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/ray_syncer/ray_syncer_bidi_reactor.h
  src/ray/common/ray_syncer/ray_syncer_bidi_reactor_base.h
  src/ray/common/test/ray_syncer_test.cc
Labels: go

#49264 [core] [easy] Minor cleanup on protobuf
  bazel/ray_deps_setup.bzl
  src/ray/protobuf/agent_manager.proto
  src/ray/protobuf/autoscaler.proto
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
  src/ray/protobuf/dependency.proto
  src/ray/protobuf/event.proto
  src/ray/protobuf/experimental/instance_manager.proto
  src/ray/protobuf/export_api/export_actor_data.proto
  src/ray/protobuf/export_api/export_driver_job_event.proto
  src/ray/protobuf/export_api/export_event.proto
  src/ray/protobuf/export_api/export_node_data.proto
  src/ray/protobuf/export_api/export_runtime_env.proto
  src/ray/protobuf/export_api/export_submission_job_event.proto
  src/ray/protobuf/export_api/export_task_event.proto
  src/ray/protobuf/gcs.proto
  src/ray/protobuf/gcs_service.proto
  src/ray/protobuf/job_agent.proto
  src/ray/protobuf/logging.proto
  src/ray/protobuf/node_manager.proto
  src/ray/protobuf/object_manager.proto
  src/ray/protobuf/pubsub.proto
  src/ray/protobuf/ray_client.proto
  src/ray/protobuf/ray_syncer.proto
  src/ray/protobuf/reporter.proto
  src/ray/protobuf/runtime_env_agent.proto
  src/ray/protobuf/runtime_env_common.proto
  src/ray/protobuf/serialization.proto
  src/ray/protobuf/serve.proto
  src/ray/protobuf/usage.proto
Labels: go

#49289 [doc] Fix lint
  doc/source/ray-contribute/development.rst
Labels: go

#49291 [core] Fix windows include
  src/ray/common/cgroup/cgroup_setup.cc
  src/ray/common/ray_syncer/ray_syncer_bidi_reactor.h
Labels: go

#49237 [core] Remove grpc client thread number
  src/ray/rpc/grpc_client.h
  src/ray/rpc/object_manager/object_manager_client.h
Labels: go

#49277 [kuberay][conformance][jobs] Add tests for `ray job status` to ensure the contract between KubeRay / Ray
  python/ray/dashboard/modules/job/tests/test_cli.py
  python/ray/dashboard/modules/job/tests/test_cli_integration.py
Labels: go
