Repository ray-project/ray, pull requests merged in 2024-03, with the labels that each got.

#43007 [serve] rename max concurrent queries
  dashboard/client/src/type/serve.ts
  doc/source/serve/advanced-guides/advanced-autoscaling.md
  doc/source/serve/advanced-guides/inplace-updates.md
  doc/source/serve/advanced-guides/performance.md
  doc/source/serve/api/index.md
  doc/source/serve/architecture.md
  doc/source/serve/autoscaling-guide.md
  doc/source/serve/configure-serve-deployment.md
  doc/source/serve/doc_code/configure_serve_deployment/model_deployment.py
  doc/source/serve/doc_code/resnet50_example.py
  doc/source/templates/03_serving_stable_diffusion/app.py
  java/serve/src/main/java/io/ray/serve/config/DeploymentConfig.java
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/benchmarks/microbenchmark.py
  python/ray/serve/_private/benchmarks/proxy_benchmark.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/config.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/replica_scheduler/common.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/version.py
  python/ray/serve/api.py
  python/ray/serve/config.py
  python/ray/serve/deployment.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/test_advanced.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_cancellation.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_deployment_version.py
  python/ray/serve/tests/test_handle_api.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_multiplex.py
  python/ray/serve/tests/test_proxy_response_generator.py
  python/ray/serve/tests/test_request_timeout.py
  python/ray/serve/tests/test_standalone_3.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_deployment_class.py
  python/ray/serve/tests/unit/test_deployment_state.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
  python/ray/serve/tests/unit/test_router.py
  python/ray/serve/tests/unit/test_schema.py
  python/ray/tests/test_streaming_generator_3.py
  src/ray/protobuf/serve.proto
Labels: release-blocker, serve, ray 2.10

#43274 [RLlib] ConnectorV2: New example script: MeanStdFilter (for both single-agent and multi-agent).
  rllib/BUILD
  rllib/connectors/common/frame_stacking.py
  rllib/connectors/connector_pipeline_v2.py
  rllib/connectors/connector_v2.py
  rllib/connectors/env_to_module/add_last_observation_to_batch.py
  rllib/connectors/env_to_module/default_env_to_module.py
  rllib/connectors/env_to_module/flatten_observations.py
  rllib/connectors/env_to_module/mean_std_filter.py
  rllib/connectors/env_to_module/prev_actions_prev_rewards.py
  rllib/connectors/module_to_env/default_module_to_env.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/evaluation/worker_set.py
  rllib/examples/connectors/connector_v2_frame_stacking.py
  rllib/examples/connectors/connector_v2_mean_std_filtering.py
  rllib/utils/filter.py
  rllib/utils/serialization.py
Labels: tests-ok

#43317 [RLlib] Issue 42152: `__common__` in multi-agent env infos dict breaks env pre-checker.
  rllib/utils/pre_checks/env.py
Labels: tests-ok, rllib

#43214 [core] If there's working_dir, don't set _py_driver_sys_path.
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/job_config.py
  python/ray/serve/tests/BUILD
  python/ray/tests/test_basic_3.py
  src/ray/core_worker/core_worker.cc
  src/ray/protobuf/common.proto
Labels: @author-action-required

#43577 [serve] compact nodes
  python/ray/serve/_private/cluster_node_info_cache.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: serve

#43398 [serve] add `target_num_replicas` to rest api response
  dashboard/modules/serve/tests/test_serve_dashboard.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/unit/test_schema.py
Labels: release-blocker, serve, ray 2.10

#43674 [serve] Fix Python 3.11 tests by passing task, not coroutine, to `asyncio.sleep`
  python/ray/serve/_private/metrics_utils.py
Labels: continuous-build

#43508 [Serve] allow serve to disable and redirect stdout to serve logger
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/tests/test_logging.py
Labels: release-blocker, P0, serve, ray 2.10

#43454 [serve] rename target num ongoing requests per replica
  dashboard/client/src/type/serve.ts
  doc/source/serve/advanced-guides/advanced-autoscaling.md
  doc/source/serve/autoscaling-guide.md
  doc/source/serve/doc_code/managing_deployments.py
  doc/source/serve/doc_code/resnet50_example.py
  doc/source/templates/03_serving_stable_diffusion/app.py
  java/serve/src/main/java/io/ray/serve/config/AutoscalingConfig.java
  java/serve/src/test/java/io/ray/serve/deployment/DeploymentTest.java
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/config.py
  python/ray/serve/api.py
  python/ray/serve/autoscaling_policy.py
  python/ray/serve/config.py
  python/ray/serve/deployment.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/unit/test_autoscaling_policy.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_deployment_class.py
  python/ray/serve/tests/unit/test_deployment_state.py
  python/ray/serve/tests/unit/test_schema.py
  src/ray/protobuf/serve.proto
Labels: release-blocker, ray 2.10

#43477 [Data] Time streaming split overhead
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker

#43241 [Data] Time ray data tasks (total time and udf time)
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/map_transformer.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/stats.py
  python/ray/data/block.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker

#43684 [data] fix progress bar total not updated for `streaming_split`
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
Labels: release-blocker

#43680 [RLlib] ConnectorV2: Fix bug in `AddColumnsFromEpisodesToTrainBatch` class (multi-agent related).
  rllib/algorithms/ppo/ppo_learner.py
  rllib/connectors/learner/add_columns_from_episodes_to_train_batch.py
  rllib/core/learner/learner.py
  rllib/utils/test_utils.py
Labels: tests-ok

#43692 [Data] Remove Ray Data read parallelism from all libraries and tests
  dashboard/modules/data/tests/test_data_head.py
  python/ray/air/tests/test_new_dataset_config.py
  python/ray/air/util/check_ingest.py
  python/ray/data/dataset.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_auto_parallelism.py
  python/ray/data/tests/test_backpressure_e2e.py
  python/ray/data/tests/test_backpressure_policies.py
  python/ray/data/tests/test_binary.py
  python/ray/data/tests/test_block_sizing.py
  python/ray/data/tests/test_consumption.py
  python/ray/data/tests/test_context_propagation.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_datasink.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_file_datasink.py
  python/ray/data/tests/test_formats.py
  python/ray/data/tests/test_huggingface.py
  python/ray/data/tests/test_image.py
  python/ray/data/tests/test_json.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_mongo.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_numpy_support.py
  python/ray/data/tests/test_object_gc.py
  python/ray/data/tests/test_optimize.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_random_access.py
  python/ray/data/tests/test_randomize_block_order.py
  python/ray/data/tests/test_size_estimation.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_split.py
  python/ray/data/tests/test_splitblocks.py
  python/ray/data/tests/test_sql.py
  python/ray/data/tests/test_stats.py
  python/ray/data/tests/test_streaming_executor_errored_blocks.py
  python/ray/data/tests/test_streaming_integration.py
  python/ray/data/tests/test_tensor.py
  python/ray/data/tests/test_text.py
  python/ray/data/tests/test_tfrecords.py
  python/ray/data/tests/test_webdataset.py
  python/ray/experimental/tqdm_ray.py
  python/ray/tune/tests/test_tuner.py
  release/air_tests/air_benchmarks/mlperf-train/resnet50_ray_air.py
  release/nightly_tests/dataset/data_ingest_benchmark.py
  release/nightly_tests/dataset/dataset_random_access.py
  release/nightly_tests/dataset/image_loader_microbenchmark.py
  release/nightly_tests/dataset/map_batches_benchmark.py
  release/nightly_tests/dataset/operator_fusion_benchmark.py
  release/nightly_tests/dataset/read_parquet_benchmark.py
  release/nightly_tests/dataset/sort.py
Labels: release-blocker

#43581 [Data] Report throughput stats
  python/ray/data/_internal/stats.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker

#43690 [Data] Remove read parallelism from Ray Data documentation
  doc/source/data/data-internals.rst
  doc/source/data/loading-data.rst
  doc/source/data/performance-tips.rst
  doc/source/data/transforming-data.rst
  python/ray/data/_internal/util.py
  python/ray/data/context.py
  python/ray/data/tests/test_auto_parallelism.py
  python/ray/data/tests/test_block_sizing.py
Labels: release-blocker

#43591 [serve] compact scheduling strategy
  python/ray/serve/_private/cluster_node_info_cache.py
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_cluster_node_info_cache.py
  python/ray/serve/tests/test_deployment_scheduler.py
  python/ray/serve/tests/test_max_replicas_per_node.py
  python/ray/serve/tests/unit/test_deployment_scheduler.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: release-blocker, serve, ray 2.10

#43735 Revert "Revert "[Data] Reduce internal Ray Data stack trace output by default""
  python/ray/_raylet.pyx
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/context.py
  python/ray/data/exceptions.py
  python/ray/data/tests/preprocessors/test_concatenator.py
  python/ray/data/tests/preprocessors/test_encoder.py
  python/ray/data/tests/preprocessors/test_torch.py
  python/ray/data/tests/test_logger.py
  python/ray/data/tests/test_map.py
  python/ray/exceptions.py
Labels: release-blocker

#43628 [Data] Additional Ray Data Dashboard Metrics
  .vale/styles/Vocab/Data/accept.txt
  dashboard/client/src/pages/metrics/Metrics.tsx
  dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  doc/source/data/monitoring-your-workload.rst
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/resource_manager.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker

#43779 [RLlib] Re-instantiate `on_episode_created` callback for multi-agent (for now).
  rllib/algorithms/algorithm_config.py
  rllib/env/multi_agent_env_runner.py
Labels: tests-ok

#43740 [data] fix memory metrics for OutputSplitter
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/operators/output_splitter.py
Labels: release-blocker

#43004 [serve] add warning for max concurrent queries default
  dashboard/modules/serve/serve_rest_api_impl.py
  doc/source/serve/advanced-guides/advanced-autoscaling.md
  doc/source/serve/configure-serve-deployment.md
  python/ray/serve/api.py
  python/ray/serve/deployment.py
Labels: release-blocker, ray 2.10

#43793 [data] fix env var for enabling resource reservation
  python/ray/data/context.py
Labels: release-blocker

#43790 [Data] Add Runtime Metrics String
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker

#43764 [Data] Normalize block types before internal multi-block operations
  python/ray/data/BUILD
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/table_block.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_zip.py
Labels: release-blocker

#43128 [core][experimental] asyncio support for accelerated DAGs
  python/ray/_raylet.pyx
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/test_accelerated_dag.py
  python/ray/experimental/channel.py
  python/ray/tests/test_channel.py
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
Labels: tests-ok, @author-action-required

#43805 [Serve] Fix deployment route prefix override by default route prefix from serve run cli
  python/ray/serve/scripts.py
  python/ray/serve/tests/test_cli_2.py
Labels: release-blocker, serve, ray 2.10

#43794 [serve] change detect compact opportunities interface
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/unit/test_deployment_scheduler.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: release-blocker, ray 2.10

#43802 [Data] Fix suboperator timing calculation
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_stats.py
Labels: release-blocker

#43813 [serve] warning about changing target ongoing requests default
  dashboard/modules/serve/serve_rest_api_impl.py
  doc/source/serve/advanced-guides/advanced-autoscaling.md
  python/ray/serve/api.py
Labels: release-blocker, ray 2.10

#43635 [serve] add support for compact strategy + max replicas per node
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/tests/test_max_replicas_per_node.py
  python/ray/serve/tests/unit/BUILD
  python/ray/serve/tests/unit/test_deployment_scheduler.py
Labels: release-blocker, serve, ray 2.10

#43814 [serve] collect autoscaling metrics on handle by default
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/unit/BUILD
  python/ray/serve/tests/unit/test_deployment_state.py
  python/ray/serve/tests/unit/test_router.py
Labels: release-blocker, ray 2.10

#43799 [Dashboard] [Serve] Rename "Serve Deployments" tab to "Serve"
  dashboard/client/src/pages/layout/MainNavLayout.tsx
Labels: ray 2.10

#43775 Fixing segfaults in Async Streaming Generator
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/tests/BUILD
  python/ray/tests/test_streaming_generator_4.py
  python/ray/tests/test_streaming_generator_regression.py
Labels: release-blocker, ray 2.10

#43496 [RLlib] Added funcitonality to add `infos` and `extra_model_outputs` to the sample output of `PrioritizedEpisodeReplayBuffer`.
  rllib/utils/replay_buffers/prioritized_episode_replay_buffer.py
  rllib/utils/replay_buffers/tests/test_prioritized_episode_replay_buffer.py
Labels: tests-ok

#43875 [Data] Fix test_pipelined_execution
  python/ray/data/_internal/stats.py
Labels: release-blocker

#43869 [ci][7up/2] remove python 3.8
  .buildkite/_forge.aarch64.rayci.yml
  .buildkite/_forge.rayci.yml
  .buildkite/base.rayci.yml
  .buildkite/build.rayci.yml
  .buildkite/core.rayci.yml
  .buildkite/data.rayci.yml
  .buildkite/ml.rayci.yml
  .buildkite/release-automation/verify-macos-wheels.sh
  .buildkite/release-automation/wheels.rayci.yml
  .buildkite/serve.rayci.yml
  .buildkite/windows.rayci.yml
  ci/build/build-docker-images.py
  ci/build/test-wheels.sh
  ci/env/install-dependencies.sh
  ci/env/install-minimal.sh
  ci/ray_ci/builder_container.py
  ci/ray_ci/macos/macos_ci.sh
  ci/ray_ci/macos/macos_ci_build.sh
  python/ray/tests/test_runtime_env_2.py
  python/ray/tests/test_task_events.py
Labels: continuous-build

#43872 [Serve] Disallow setting max_replicas_per_node and placement_group_bundles options together
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/config.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_schema.py
Labels: release-blocker

#43884 [Data] Fix test_pipelined_execution (#43875)
  python/ray/data/_internal/stats.py
Labels: release-blocker, v2.10.0-pick

#43928 [serve] fix num replicas auto bug
  python/ray/serve/_private/application_state.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
Labels: bug, release-blocker, P0, serve

#43940 [serve] fix num replicas auto bug (#43928)
  python/ray/serve/_private/application_state.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
Labels: release-blocker, serve, v2.10.0-pick

#43787 [RLlib] Evaluation do-over: Make parallel evaluation to training the default behavior and deprecate async eval option.
  doc/source/rllib/doc_code/advanced_api.py
  doc/source/rllib/rllib-advanced-api.rst
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/ppo/tests/test_ppo_with_env_runner.py
  rllib/algorithms/tests/test_algorithm.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/algorithms/tests/test_worker_failures.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/multi_agent_episode.py
  rllib/env/single_agent_env_runner.py
  rllib/evaluation/metrics.py
  rllib/evaluation/worker_set.py
  rllib/examples/connectors/connector_v2_mean_std_filtering.py
  rllib/examples/custom_eval.py
  rllib/examples/evaluation/__init__.py
  rllib/examples/evaluation/evaluation_parallel_to_training.py
  rllib/examples/parallel_evaluation_and_training.py
  rllib/tests/run_regression_tests.py
  rllib/tuned_examples/appo/cartpole-crashing-and-stalling-recreate-workers-appo.py
  rllib/tuned_examples/appo/cartpole-crashing-recreate-workers-appo.py
  rllib/tuned_examples/appo/multi-agent-cartpole-crashing-and-stalling-recreate-workers-appo.py
  rllib/tuned_examples/appo/multi-agent-cartpole-crashing-recreate-workers-appo.py
  rllib/tuned_examples/ppo/cartpole_ppo_envrunner.py
  rllib/tuned_examples/ppo/pendulum_ppo_envrunner.py
  rllib/tuned_examples/ppo/unity3d-soccer-strikers-vs-goalie-ppo.yaml
  rllib/utils/metrics/__init__.py
  rllib/utils/minibatch_utils.py
  rllib/utils/test_utils.py
  rllib/utils/tests/test_minibatch_utils.py
  rllib/utils/typing.py
Labels: rllib, rllib-evaluation, rllib-newstack, rllib-oldstack-cleanup

#43967 [Serve] Disallow setting max_replicas_per_node and placement_group_bundles options together (#43872)
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/config.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_schema.py
Labels: v2.10.0-pick

#43343 [Train] Add Intel HPU Support and Training Examples to Ray Train
  doc/source/train/examples.yml
  doc/source/train/examples/hpu/bert.ipynb
  doc/source/train/examples/hpu/resnet.ipynb
  python/ray/air/_internal/torch_utils.py
  python/ray/train/torch/config.py
Labels: train

#43975 [Core] Ignore worker lease requests from dead caller (#43920)
  python/ray/tests/test_node_manager.py
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: v2.10.0-pick

#43993 [serve] fix custom resource scheduling bug
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/tests/test_deployment_scheduler.py
  python/ray/serve/tests/unit/test_deployment_scheduler.py
Labels: release-blocker, P0, serve

#44004 [serve] fix custom resource scheduling bug (#43993)
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/tests/test_deployment_scheduler.py
  python/ray/serve/tests/unit/test_deployment_scheduler.py
Labels: release-blocker, P0

#44010 [Data] Stabilize `dataset_shuffle_push_based_random_shuffle_1tb` (#43697)
  release/nightly_tests/shuffle/datasets_large_scale_compute_small_instances.yaml
  release/nightly_tests/shuffle/datasets_large_scale_compute_small_instances_gce.yaml
Labels: release-blocker, ray 2.10, v2.10.0-pick

#43895 [Doc] Add support for community examples
  doc/source/_static/css/examples.css
  doc/source/_static/js/examples.js
  doc/source/_templates/ray-overview/examples.html
  doc/source/custom_directives.py
  doc/source/ray-contribute/getting-involved.rst
  doc/source/train/examples.yml
Labels: docs

#44013 [Serve] Update Serve Counter metric doc (#43901)
  dashboard/modules/metrics/dashboards/serve_dashboard_panels.py
  dashboard/modules/metrics/dashboards/serve_deployment_dashboard_panels.py
  dashboard/modules/metrics/dashboards/serve_grafana_dashboard_base.json
  doc/source/serve/advanced-guides/performance.md
  doc/source/serve/monitoring.md
  python/ray/serve/metrics.py
Labels: v2.10.0-pick

#44017 [Core] Revamp many_drivers release test (#43886)
  release/long_running_tests/tpl_cpu_4.yaml
  release/long_running_tests/tpl_cpu_4_gce.yaml
  release/long_running_tests/workloads/many_drivers.py
  release/release_tests.yaml
Labels: v2.10.0-pick

#44040 [RLlib] Fix MultiCallbacks `on_sample_end` signature.
  rllib/algorithms/callbacks.py
Labels: tests-ok

#44011 [Serve] Fix serve deploy not getting current directory added to sys.path (#43899)
  python/ray/_private/worker.py
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_config_files/use_current_working_directory.py
  python/ray/serve/tests/test_config_files/use_current_working_directory.yaml
Labels: release-blocker, ray 2.10, v2.10.0-pick

#44041 [Data] Revise batch inference user guide
  doc/source/data/batch_inference.rst
  doc/source/train/user-guides/results.rst
Labels: release-blocker, ray 2.10, v2.10.0-pick

#44042 [Data] Remove 'Using Preprocessors'
  doc/source/data/preprocessors.rst
  doc/source/data/user-guide.rst
  doc/source/train/distributed-xgboost-lightgbm.rst
  doc/source/train/user-guides/data-loading-preprocessing.rst
Labels: release-blocker, ray 2.10, v2.10.0-pick

#44053 [serve] Drop stale handle metrics (#44045)
  python/ray/serve/_private/autoscaling_policy.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/proxy_state.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/handle.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: release-blocker, P0, serve

#44082 [RLlib] Hot fix for `PPOTorchRLModule._compute_values` with non-shared stateful encoder and batch slicing with non-empty `info`s.
  rllib/algorithms/ppo/torch/ppo_torch_rl_module.py
  rllib/policy/sample_batch.py
Labels: rllib, rllib-newstack

#44079 [core] Streaming generator task waits for all object report acks before finishing the task
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/generator_waiter.cc
  src/ray/core_worker/generator_waiter.h
  src/ray/core_worker/test/generator_waiter_test.cc
Labels: release-blocker, ray 2.10

#44095 [2.10][Data] Update Ray Data documentation for {landing,overview,key concepts}
  doc/source/data/data-internals.rst
  doc/source/data/data.rst
  doc/source/data/examples/gptj_batch_prediction.ipynb
  doc/source/data/examples/stablediffusion_batch_prediction.ipynb
  doc/source/data/images/dataset.svg
  doc/source/data/overview.rst
  doc/source/data/quickstart.rst
  doc/source/data/user-guide.rst
  doc/source/ray-overview/getting-started.md
  doc/source/train/examples/lightning/dolly_lightning_fsdp_finetuning.ipynb
  doc/source/train/examples/lightning/vicuna_13b_lightning_deepspeed_finetune.ipynb
  doc/source/tune/tutorials/tune_get_data_in_and_out.md
Labels: v2.10.0-pick

#44097 [Data] [Docs] Cherry-pick #43992
  doc/source/data/working-with-pytorch.rst
  doc/source/data/working-with-tensors.rst
Labels: v2.10.0-pick

#44110 [RLlib; CI] Fix test case: `envs_that_crash`.
  rllib/algorithms/algorithm_config.py
  rllib/evaluation/tests/test_envs_that_crash.py
Labels: tests-ok

#44113 [RLlib] Enhance `envs_that_crash` test case with multi-agent setups (plus bug fix for `MultiAgentEnv`).
  rllib/algorithms/tests/test_worker_failures.py
  rllib/env/multi_agent_env.py
  rllib/evaluation/tests/test_envs_that_crash.py
Labels: tests-ok

#44124 [Pick][data] turn off actor locality by default
  python/ray/data/_internal/execution/interfaces/execution_options.py
Labels: v2.10.0-pick

#44123 [data] turn off actor locality by default
  python/ray/data/_internal/execution/interfaces/execution_options.py
Labels: release-blocker

#44117 update documentation for k8s production guide to include anyscale
  doc/source/serve/production-guide/kubernetes.md
Labels: ray 2.9

#44155 [cherry-pick] [docs] update documentation for k8s production guide to include anyscale
  doc/source/serve/production-guide/kubernetes.md
Labels: serve, docs, v2.10.0-pick

#44154 [Doc] Add support for community examples (#43895)
  doc/source/_static/css/examples.css
  doc/source/_static/js/examples.js
  doc/source/_templates/ray-overview/examples.html
  doc/source/custom_directives.py
  doc/source/ray-contribute/getting-involved.rst
  doc/source/train/examples.yml
Labels: docs

#44172 [Data] [Docs] Cherry-pick #44105
  doc/source/data/execution-configurations.rst
  doc/source/data/user-guide.rst
Labels: release-blocker, v2.10.0-pick

#44171 [Data] [Docs] Cherry-pick #44098
  doc/source/data/iterating-over-data.rst
  doc/source/data/performance-tips.rst
  doc/source/data/shuffling-data.rst
  doc/source/data/transforming-data.rst
  doc/source/data/user-guide.rst
Labels: release-blocker, v2.10.0-pick

#44090 [RLlib] Documentation do-over 01: Announce new API stack as alpha; add hints to all RLlib pages; describe how to use it in new page.
  doc/source/_includes/rllib/new_api_stack.rst
  doc/source/_includes/rllib/new_api_stack_component.rst
  doc/source/_includes/rllib/rlm_learner_migration_banner.rst
  doc/source/_includes/rllib/rlmodules_rollout.rst
  doc/source/rllib/doc_code/new_api_stack.py
  doc/source/rllib/index.rst
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/package_ref/algorithm.rst
  doc/source/rllib/package_ref/catalogs.rst
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/env/base_env.rst
  doc/source/rllib/package_ref/env/external_env.rst
  doc/source/rllib/package_ref/env/multi_agent_env.rst
  doc/source/rllib/package_ref/env/vector_env.rst
  doc/source/rllib/package_ref/evaluation.rst
  doc/source/rllib/package_ref/external-app.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/learner.rst
  doc/source/rllib/package_ref/models.rst
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/package_ref/policy/custom_policies.rst
  doc/source/rllib/package_ref/replay-buffers.rst
  doc/source/rllib/package_ref/rl_modules.rst
  doc/source/rllib/package_ref/utils.rst
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-catalogs.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-connector.rst
  doc/source/rllib/rllib-dev.rst
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-fault-tolerance.rst
  doc/source/rllib/rllib-learner.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-new-api-stack.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/rllib-replay-buffers.rst
  doc/source/rllib/rllib-rlmodule.rst
  doc/source/rllib/rllib-sample-collection.rst
  doc/source/rllib/rllib-saving-and-loading-algos-and-policies.rst
  doc/source/rllib/rllib-torch2x.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/user-guides.rst
Labels: tests-ok

#44189 [cherry-pick; RLlib] Cherry pick rllib docs for new API stack.
  doc/source/_includes/rllib/new_api_stack.rst
  doc/source/_includes/rllib/new_api_stack_component.rst
  doc/source/_includes/rllib/rlm_learner_migration_banner.rst
  doc/source/_includes/rllib/rlmodules_rollout.rst
  doc/source/rllib/doc_code/new_api_stack.py
  doc/source/rllib/index.rst
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/package_ref/algorithm.rst
  doc/source/rllib/package_ref/catalogs.rst
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/env/base_env.rst
  doc/source/rllib/package_ref/env/external_env.rst
  doc/source/rllib/package_ref/env/multi_agent_env.rst
  doc/source/rllib/package_ref/env/vector_env.rst
  doc/source/rllib/package_ref/evaluation.rst
  doc/source/rllib/package_ref/external-app.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/learner.rst
  doc/source/rllib/package_ref/models.rst
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/package_ref/policy/custom_policies.rst
  doc/source/rllib/package_ref/replay-buffers.rst
  doc/source/rllib/package_ref/rl_modules.rst
  doc/source/rllib/package_ref/utils.rst
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-catalogs.rst
  doc/source/rllib/rllib-concepts.rst
  doc/source/rllib/rllib-connector.rst
  doc/source/rllib/rllib-dev.rst
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-fault-tolerance.rst
  doc/source/rllib/rllib-learner.rst
  doc/source/rllib/rllib-models.rst
  doc/source/rllib/rllib-new-api-stack.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/rllib-replay-buffers.rst
  doc/source/rllib/rllib-rlmodule.rst
  doc/source/rllib/rllib-sample-collection.rst
  doc/source/rllib/rllib-saving-and-loading-algos-and-policies.rst
  doc/source/rllib/rllib-torch2x.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/user-guides.rst
Labels: rllib, docs

#44104 [serve] store target labels correctly for launching replicas
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_deployment_scheduler.py
  python/ray/serve/tests/unit/test_deployment_scheduler.py
Labels: serve, ray-2.10.1

#44220 [Data] [Doc] Revise huggingface batch example(#43972)
  doc/source/data/examples/huggingface_vit_batch_prediction.ipynb
Labels: v2.10.0-pick

#44221 [Data] [Docs] Update Loading, Transforming, Inspecting, Iterating Over, and Saving Data pages (#44093)
  ci/pipeline/determine_tests_to_run.py
  doc/source/data/custom-datasource-example.rst
  doc/source/data/inspecting-data.rst
  doc/source/data/loading-data.rst
  doc/source/data/saving-data.rst
  doc/source/data/transforming-data.rst
  doc/source/data/user-guide.rst
Labels: v2.10.0-pick

#44229 [Data] [Docs] Update data stats docs (#44164)
  doc/source/data/monitoring-your-workload.rst
  doc/source/data/user-guide.rst
Labels: v2.10.0-pick

#43198 [RLlib] DQN Rainbow on new API stack (w/ EnvRunner):`training_step` implementation.
  rllib/BUILD
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/torch/appo_torch_rl_module.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/dqn/dqn_rainbow_catalog.py
  rllib/algorithms/dqn/dqn_rainbow_learner.py
  rllib/algorithms/dqn/dqn_rainbow_rl_module.py
  rllib/algorithms/dqn/torch/dqn_rainbow_torch_learner.py
  rllib/algorithms/dqn/torch/dqn_rainbow_torch_noisy_net.py
  rllib/algorithms/dqn/torch/dqn_rainbow_torch_rl_module.py
  rllib/algorithms/dqn/torch/torch_noisy_linear.py
  rllib/algorithms/sac/sac.py
  rllib/env/single_agent_env_runner.py
  rllib/evaluation/worker_set.py
  rllib/tuned_examples/dqn/cartpole_dqn_envrunner.py
  rllib/utils/replay_buffers/prioritized_episode_replay_buffer.py
  rllib/utils/replay_buffers/utils.py
Labels: rllib, rllib-newstack

#43344 [core] Add HPU unit tests
  python/ray/tests/accelerators/test_hpu.py
Labels: core

#44249 [doc] [clusters] add link to KubeRay instructions for Prometheus set up
  doc/source/cluster/metrics.md
Labels: docs, kuberay, clusters

#44266 [cherry-pick] [docs] add link to KubeRay instructions for Prometheus set up (#44249)
  doc/source/cluster/metrics.md
Labels: docs, v2.10.0-pick

#43858 Update security docs to be more precise about Ray Client, Dashboard, Jobs
  SECURITY.md
  doc/source/ray-security/index.md
Labels: release-blocker, docs, ray 2.10

#44334 [doc string] Fixing typo in doc string; missing space
  python/ray/serve/scripts.py
Labels: serve, docs

#44251 [Doc] Update main docs page
  doc/source/_static/css/csat.css
  doc/source/_static/css/index.css
  doc/source/_templates/index.html
  doc/source/conf.py
Labels: docs
