Repository ray-project/ray, pull requests merged in 2024-11, with the labels that each got.

#48480 [Data] Remove debug log when thread finishes
  python/ray/data/_internal/util.py
Labels: go

#48483 [core] Fix builtin type and function shadowing
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/uv.py
Labels: go

#48458 [core] Add source location to status
  src/ray/common/BUILD
  src/ray/common/source_location.cc
  src/ray/common/source_location.h
  src/ray/common/source_location_test.cc
  src/ray/common/status.cc
  src/ray/common/status.h
Labels: go

#48004 [core] Replace thread checker implementation
  src/ray/util/BUILD
  src/ray/util/util.h
Labels: core, go

#48450 [rllib] fix yml linter issue
  .buildkite/linux_aarch64.rayci.yml
  .buildkite/rllib.rayci.yml
Labels: go

#48467 [serve] Reduce surface area of `create_router` interface
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/router.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_gcs_failure.py
  python/ray/serve/tests/test_multiplex.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#48492 [serve] Cleanup handle tests
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_handle_1.py
  python/ray/serve/tests/test_handle_2.py
  python/ray/serve/tests/test_handle_cancellation.py
  python/ray/serve/tests/test_http_cancellation.py
  python/ray/serve/tests/unit/test_handle_options.py
Labels: go

#48491 [serve] Return "Internal Server Error" instead of traceback on user exception
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/utils.py
  python/ray/serve/api.py
  python/ray/serve/tests/test_http_routes.py
  python/ray/serve/tests/test_logging.py
  python/ray/serve/tests/unit/test_user_callable_wrapper.py
Labels: go

#48454 [serve] move handle options to its own file
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/handle_options.py
  python/ray/serve/handle.py
  python/ray/serve/tests/unit/test_handle_options.py
Labels: go

#48498 Revert "[Observability] Added object refs Task is dependent on to `TaskInfoEntry` (#48234)"
  python/ray/dashboard/utils.py
  python/ray/tests/test_state_api.py
  python/ray/util/state/common.py
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/pb_util.h
  src/ray/protobuf/common.proto
Labels: go

#47040 [Data] Bump min version of PyArrow from 6.0 to 9.0
  .buildkite/data.rayci.yml
  ci/docker/data9.build.wanda.yaml
  ci/pipeline/determine_tests_to_run.py
  python/ray/data/tests/test_huggingface.py
  python/ray/data/tests/test_iceberg.py
  python/ray/data/tests/test_parquet.py
  python/requirements.txt
  python/setup.py
Labels: go

#48266 [Data] Fix `OutputBlockBuffer` to avoid repeatedly copying remainder block
  python/ray/data/_internal/output_buffer.py
Labels: go

#48493 [RLlib] Cleanup `evaluation` folder.
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/appo/appo_tf_policy.py
  rllib/algorithms/appo/appo_torch_policy.py
  rllib/algorithms/callbacks.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_tf_policy.py
  rllib/algorithms/impala/impala_torch_policy.py
  rllib/algorithms/marwil/marwil_tf_policy.py
  rllib/algorithms/sac/sac_tf_policy.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/algorithms/tests/test_callbacks_old_api_stack.py
  rllib/env/env_runner_group.py
  rllib/env/tests/test_multi_agent_env.py
  rllib/evaluation/__init__.py
  rllib/evaluation/collectors/sample_collector.py
  rllib/evaluation/collectors/simple_list_collector.py
  rllib/evaluation/episode.py
  rllib/evaluation/observation_function.py
  rllib/evaluation/postprocessing.py
  rllib/evaluation/rollout_worker.py
  rllib/evaluation/sample_batch_builder.py
  rllib/evaluation/sampler.py
  rllib/evaluation/tests/test_env_runner_v2.py
  rllib/evaluation/tests/test_episode.py
  rllib/evaluation/tests/test_episode_v2.py
  rllib/evaluation/tests/test_rollout_worker.py
  rllib/evaluation/worker_set.py
  rllib/examples/_old_api_stack/connectors/prepare_checkpoint.py
  rllib/examples/centralized_critic.py
  rllib/examples/centralized_critic_2.py
  rllib/examples/envs/external_envs/cartpole_server.py
  rllib/examples/envs/external_envs/unity3d_server.py
  rllib/policy/dynamic_tf_policy_v2.py
  rllib/policy/eager_tf_policy.py
  rllib/policy/eager_tf_policy_v2.py
  rllib/policy/policy.py
  rllib/policy/policy_template.py
  rllib/policy/tests/test_policy_checkpoint_restore.py
  rllib/policy/tf_policy.py
  rllib/policy/tf_policy_template.py
  rllib/policy/torch_policy.py
  rllib/policy/torch_policy_v2.py
  rllib/utils/policy.py
Labels: rllib, rllib-evaluation, rllib-oldstack-cleanup, go

#48301 Make it possible to use Ray distributed debugger without setting RAY_DEBUG
  doc/source/ray-observability/doc_code/ray-distributed-debugger.py
  doc/source/ray-observability/ray-distributed-debugger.rst
  doc/source/ray-observability/user-guides/debug-apps/index.md
  doc/source/ray-observability/user-guides/debug-apps/ray-debugging.rst
  python/ray/_raylet.pyx
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/exceptions.py
  python/ray/data/tests/test_exceptions.py
  python/ray/serve/_private/replica.py
  python/ray/tests/test_output.py
  python/ray/tests/test_ray_debugger.py
  python/ray/util/debugpy.py
  python/ray/util/rpdb.py
Labels: go

#48526 [RLlib; docs] Upgrade RLlib `examples` page (new API stack).
  doc/source/rllib/rllib-examples.rst
  rllib/examples/actions/nested_action_spaces.py
  rllib/examples/envs/custom_env_render_method.py
Labels: tests-ok, rllib, docs, rllib-docs-or-examples, rllib-newstack, rllib-oldstack-cleanup, go

#48125 [RLlib] Fix torch scheduler stepping and reporting.
  rllib/core/learner/torch/torch_learner.py
  rllib/examples/learners/ppo_with_torch_lr_schedulers.py
Labels: bug, rllib, rllib-algorithms, rllib-logging, go

#48463 [core][compiled-graphs] Don't persist input_nodes in _CollectiveOperation to avoid wrong understanding about DAGs
  python/ray/dag/collective_node.py
  python/ray/dag/dag_node.py
Labels: go

#48527 Fix test test_ray_debugger failure on macOS
  python/ray/tests/test_ray_debugger.py
Labels: go

#48513 [core][autoscaler] Set timeout for requests sent to K8s API server
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/autoscaler/_private/kuberay/node_provider.py
Labels: P0, go

#48489 [core] Fix buggy using alias
  cpp/include/ray/api/runtime_env.h
  cpp/src/ray/runtime/runtime_env.cc
  cpp/src/ray/test/cluster/cluster_mode_test.cc
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/test/task_event_buffer_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_node_manager_export_event_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/util/event.cc
  src/ray/util/event.h
  src/ray/util/process.cc
  src/ray/util/tests/event_test.cc
Labels: go

#48501 [core][observability] Add is_head to the log for node registration
  src/ray/gcs/gcs_server/gcs_node_manager.cc
Labels: go

#48496 [serve] raise RequestCancelledError when request is cancelled during assignment
  python/ray/serve/handle.py
  python/ray/serve/tests/test_handle_cancellation.py
Labels: go

#48544 [serve] Add `to_object_ref` methods to `ReplicaResult`
  python/ray/serve/_private/replica_result.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#48138 [core] Remove resources_dir from runtime env context
  python/ray/_private/runtime_env/context.py
Labels: go

#48549 [Data] Add `alexeykudinkin` as Data code owner
  .github/CODEOWNERS
Labels: go

#48503 [Data] Add `BundleQueue` abstraction
  python/ray/data/BUILD
  python/ray/data/_internal/execution/bundle_queue/__init__.py
  python/ray/data/_internal/execution/bundle_queue/bundle_queue.py
  python/ray/data/_internal/execution/bundle_queue/fifo_bundle_queue.py
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_bundle_queue.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_stats.py
Labels: go

#48553 [Data] Fix missing lines in `BundleQueue` docstring
  python/ray/data/_internal/execution/bundle_queue/bundle_queue.py
Labels: go

#48548 [train] fix StartTracebackWithWorkerRank serialization
  python/ray/air/_internal/util.py
Labels: go

#48554 [docs] fix typo in fault-tolerance production guide
  doc/source/serve/production-guide/fault-tolerance.md
Labels: go

#48543 [Core] Fix Ascend NPU discovery to support 8+ cards per node
  python/ray/_private/accelerators/npu.py
  python/ray/tests/accelerators/test_npu.py
Labels: go

#48557 Fix multiple linting issues
  .buildkite/data.rayci.yml
  doc/source/ray-observability/ray-distributed-debugger.rst
  python/ray/data/_internal/util.py
  release/ray_release/byod/requirements_byod_3.9.txt
  rllib/algorithms/dreamerv3/README.md
Labels: go

#48477 [serve] Initial version of `local_testing_mode`
  python/ray/serve/_private/common.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/local_testing_mode.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/_private/utils.py
  python/ray/serve/api.py
  python/ray/serve/handle.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/test_grpc.py
  python/ray/serve/tests/test_handle_1.py
  python/ray/serve/tests/test_handle_2.py
  python/ray/serve/tests/test_handle_cancellation.py
  python/ray/serve/tests/test_handle_streaming.py
  python/ray/serve/tests/test_http_cancellation.py
  python/ray/serve/tests/test_request_timeout.py
  python/ray/serve/tests/unit/test_local_testing_mode.py
  python/ray/serve/tests/unit/test_user_callable_wrapper.py
Labels: go

#48494 [Fix][Core] Don't raise ValueError in DeferSigint context manager
  python/ray/_private/utils.py
  python/ray/tests/test_cancel.py
Labels: go

#48490 [FIX] env RAY_DAG_retrieval_timeout not work
  python/ray/_private/worker.py
Labels: go

#48563 [RLlib] Forward fix broken release test due to old config args being used.
  release/ml_user_tests/tune_rllib/run_connect_tests.py
Labels: go

#48564 [Docs][KubeRay] Update KubeRay + Kueue guides to use newer versions of Kueue
  doc/source/cluster/kubernetes/examples/rayjob-kueue-gang-scheduling.md
  doc/source/cluster/kubernetes/examples/rayjob-kueue-priority-scheduling.md
Labels: go

#48581 [Data] Add `srinathk10` as Data code owner
  .github/CODEOWNERS
Labels: go

#48516 [RLlib] New API stack on by default for APPO and IMPALA.
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-learner.rst
  doc/source/rllib/rllib-rlmodule.rst
  rllib/BUILD
  rllib/README.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/appo_torch_policy.py
  rllib/algorithms/appo/tests/test_appo.py
  rllib/algorithms/appo/tests/test_appo_learner.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/algorithms/impala/impala_torch_policy.py
  rllib/algorithms/impala/tests/test_impala.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/tests/test_callbacks_on_algorithm.py
  rllib/algorithms/tests/test_env_runner_failures.py
  rllib/benchmarks/torch_compile/run_ppo_with_inference_bm.py
  rllib/examples/_old_api_stack/connectors/prepare_checkpoint.py
  rllib/examples/catalogs/mobilenet_v2_encoder.py
  rllib/models/tests/test_lstms.py
  rllib/policy/tests/test_policy_checkpoint_restore.py
  rllib/policy/tests/test_policy_state_swapping.py
  rllib/tests/test_dependency_tf.py
  rllib/tests/test_local.py
  rllib/tuned_examples/appo/cartpole-appo-separate-losses.py
  rllib/tuned_examples/appo/cartpole-crashing-and-stalling-recreate-workers-appo.py
  rllib/tuned_examples/appo/cartpole-crashing-recreate-workers-appo.py
  rllib/tuned_examples/appo/cartpole_appo.py
  rllib/tuned_examples/appo/multi-agent-cartpole-crashing-and-stalling-recreate-workers-appo.py
  rllib/tuned_examples/appo/multi-agent-cartpole-crashing-recreate-workers-appo.py
  rllib/tuned_examples/appo/multi-agent-cartpole-w-100-policies-appo.py
  rllib/tuned_examples/appo/multi_agent_cartpole_appo.py
  rllib/tuned_examples/appo/multi_agent_cartpole_appo_old_api_stack.py
  rllib/tuned_examples/appo/multi_agent_stateless_cartpole_appo.py
  rllib/tuned_examples/appo/stateless_cartpole_appo.py
  rllib/tuned_examples/impala/cartpole-impala-separate-losses.py
  rllib/tuned_examples/impala/cartpole_impala.py
  rllib/tuned_examples/impala/multi_agent_cartpole_impala.py
  rllib/tuned_examples/impala/multi_agent_cartpole_impala_old_api_stack.py
  rllib/tuned_examples/impala/multi_agent_stateless_cartpole_impala.py
  rllib/tuned_examples/impala/pendulum_impala.py
  rllib/tuned_examples/impala/pong_impala.py
  rllib/tuned_examples/impala/pong_impala_pb2_hyperopt.py
  rllib/tuned_examples/impala/stateless_cartpole_impala.py
  rllib/utils/exploration/tests/test_explorations.py
  rllib/utils/tests/test_errors.py
Labels: rllib, rllib-algorithms, rllib-newstack, rllib-oldstack-cleanup, go

#48588 [Data] Don't test against schema order for `test_parquet_read_partitioned_with_partition_filter`
  python/ray/data/tests/test_parquet.py
Labels: go

#48580 [Data] Remove unnecessary skipif of `test_parquet_read_partitioned_with_partition_filter`
  python/ray/data/tests/test_parquet.py
Labels: go

#48566 [core][autoscaler] Remove local dependencies on Ray for KubeRay autoscaling e2e tests
  python/ray/tests/kuberay/README.md
  python/ray/tests/kuberay/scripts/scale_up_custom.py
  python/ray/tests/kuberay/test_autoscaling_e2e.py
  python/ray/tests/kuberay/utils.py
Labels: go

#47851 [Docs][KubeRay] Add doc for kubectl plugin
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/kubectl-plugin.md
Labels: go

#48486 [core] [2/N] Implement uv processor
  python/ray/_private/runtime_env/BUILD
  python/ray/_private/runtime_env/dependency_utils.py
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/uv.py
  python/ray/_private/runtime_env/validation.py
  python/ray/_private/runtime_env/virtualenv_utils.py
  python/ray/runtime_env/runtime_env.py
  python/ray/serve/tests/BUILD
  python/ray/tests/conftest.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
  python/ray/tests/test_runtime_env_conda_and_pip_4.py
  python/ray/tests/unit/BUILD
  python/ray/tests/unit/test_runtime_env_uv.py
Labels: go

#48604 [serve] Don't run local handle tests on windows
  python/ray/serve/tests/BUILD
Labels: go

#48532 [Tune][Fix]Remove the `clear_checkpoint` function during Trial restoration error handling.
  python/ray/tune/experiment/trial.py
  python/ray/tune/tests/test_tuner_restore.py
Labels: go

#48577 [docs] typo, attempt #2
  doc/source/cluster/kubernetes/examples/rayjob-kueue-gang-scheduling.md
Labels: go

#48609 [docs][core]Accelerator link
  doc/source/ray-core/scheduling/accelerators.rst
Labels: go

#47323 [Fix][Dashboard] Fix Place Group Table table cells overflow
  python/ray/dashboard/client/src/common/RowStyles.tsx
  python/ray/dashboard/client/src/components/ActorTable.tsx
  python/ray/dashboard/client/src/components/OverflowCollapsibleCell.tsx
  python/ray/dashboard/client/src/components/PlacementGroupTable.tsx
Labels: dashboard, triage, go

#48612 Revert "[Data] Add `BundleQueue` abstraction (#48503)"
  python/ray/data/BUILD
  python/ray/data/_internal/execution/bundle_queue/__init__.py
  python/ray/data/_internal/execution/bundle_queue/bundle_queue.py
  python/ray/data/_internal/execution/bundle_queue/fifo_bundle_queue.py
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_bundle_queue.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_stats.py
Labels: go

#48594 [core][compiled graphs] Refine schedule visualization
  python/ray/dag/dag_node_operation.py
Labels: go

#48593 [core] Minor improvement for worker pool, and add comments for protobuf
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  src/ray/protobuf/runtime_env_agent.proto
  src/ray/raylet/runtime_env_agent_client.cc
  src/ray/raylet/runtime_env_agent_client.h
  src/ray/raylet/worker_pool.cc
  src/ray/util/util.cc
Labels: go

#48314 [RLlib] Fix IMPALA/APPO learning behavior: Fix EnvRunner sync bug, GPU loader thread, enable local learner w/ GPU.
  doc/source/rllib/rllib-examples.rst
  release/release_tests.yaml
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/benchmarks/ppo/benchmark_atari_ppo.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group.py
  rllib/core/learner/torch/torch_learner.py
  rllib/env/env_runner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/examples/connectors/frame_stacking.py
  rllib/examples/connectors/mean_std_filtering.py
  rllib/examples/envs/env_rendering_and_recording.py
  rllib/examples/evaluation/evaluation_parallel_to_training.py
  rllib/examples/fault_tolerance/crashing_and_stalling_env.py
  rllib/examples/gpus/fractional_gpus_per_learner.py
  rllib/examples/multi_agent/self_play_league_based_with_open_spiel.py
  rllib/examples/multi_agent/self_play_with_open_spiel.py
  rllib/examples/offline_rl/train_w_bc_finetune_w_ppo.py
  rllib/tuned_examples/appo/cartpole_appo.py
  rllib/tuned_examples/appo/multi_agent_cartpole_appo.py
  rllib/tuned_examples/appo/multi_agent_stateless_cartpole_appo.py
  rllib/tuned_examples/appo/stateless_cartpole_appo.py
  rllib/tuned_examples/bc/benchmark_atari_pong_bc.py
  rllib/tuned_examples/bc/cartpole_bc.py
  rllib/tuned_examples/bc/cartpole_recording.py
  rllib/tuned_examples/bc/pendulum_bc.py
  rllib/tuned_examples/cql/pendulum_cql.py
  rllib/tuned_examples/dqn/cartpole_dqn.py
  rllib/tuned_examples/dqn/multi_agent_cartpole_dqn.py
  rllib/tuned_examples/dreamerv3/atari_100k.py
  rllib/tuned_examples/dreamerv3/atari_200M.py
  rllib/tuned_examples/dreamerv3/dm_control_suite_vision.py
  rllib/tuned_examples/impala/cartpole_impala.py
  rllib/tuned_examples/impala/multi_agent_cartpole_impala.py
  rllib/tuned_examples/impala/multi_agent_stateless_cartpole_impala.py
  rllib/tuned_examples/impala/pendulum_impala.py
  rllib/tuned_examples/impala/pong_impala.py
  rllib/tuned_examples/impala/pong_impala_pb2_hyperopt.py
  rllib/tuned_examples/impala/stateless_cartpole_impala.py
  rllib/tuned_examples/marwil/cartpole_marwil.py
  rllib/tuned_examples/ppo/atari_ppo.py
  rllib/tuned_examples/ppo/cartpole_ppo.py
  rllib/tuned_examples/ppo/cartpole_truncated_ppo.py
  rllib/tuned_examples/ppo/multi_agent_cartpole_ppo.py
  rllib/tuned_examples/ppo/multi_agent_pendulum_ppo.py
  rllib/tuned_examples/ppo/multi_agent_stateless_cartpole_ppo.py
  rllib/tuned_examples/ppo/pendulum_ppo.py
  rllib/tuned_examples/ppo/stateless_cartpole_ppo.py
  rllib/tuned_examples/sac/halfcheetah_sac.py
  rllib/tuned_examples/sac/humanoid_sac.py
  rllib/tuned_examples/sac/multi_agent_pendulum_sac.py
  rllib/tuned_examples/sac/pendulum_sac.py
  rllib/utils/actor_manager.py
  rllib/utils/metrics/__init__.py
  rllib/utils/test_utils.py
Labels: rllib, rllib-algorithms, rllib-gpu-multi-gpu, rllib-newstack, go

#48615 [ci] fix osx wheel matching logic
  ci/build/test-wheels.sh
Labels: go

#48088 [Core] Make Placement Group Wildcard and Indexed Resource Assignments Consistent
  src/ray/common/bundle_spec.cc
  src/ray/common/bundle_spec.h
  src/ray/common/scheduling/resource_instance_set.cc
  src/ray/common/scheduling/resource_instance_set.h
  src/ray/common/test/resource_instance_set_test.cc
  src/ray/raylet/placement_group_resource_manager_test.cc
Labels: go

#48530 [Dashboard] Add memory graphs optimized for OOM debugging
  python/ray/dashboard/client/src/pages/metrics/Metrics.tsx
  python/ray/dashboard/modules/metrics/dashboards/default_dashboard_panels.py
Labels: go

#48528 [Dashboard] Improve tasks/actors metric naming and add graph for running tasks
  python/ray/dashboard/client/src/pages/metrics/Metrics.tsx
  python/ray/dashboard/modules/metrics/dashboards/default_dashboard_panels.py
Labels: go

#48302 [core][compiled-graph] Throw an exception when DAGNode is inside any type of container as a DAGNode arg
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#48631 [Data] Allow user to specify schema for `write_parquet`
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/tests/test_parquet.py
Labels: go

#48572 [Core] Stop the GRPC server before Shut down the Object Store
  src/ray/object_manager/object_manager.cc
Labels: go

#48613 [doc][core] change ml app to ml workload, and style fix
  doc/source/ray-core/scheduling/accelerators.rst
Labels: docs, core, go

#48583 [Data] Fix `to_pandas` error when multiple block types
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_pandas.py
  python/ray/data/tests/test_parquet.py
Labels: go

#48567 Add docs for `local_testing_mode`
  doc/source/serve/advanced-guides/dev-workflow.md
  doc/source/serve/doc_code/local_dev.py
Labels: go

#48635 [data] Project Operator for select_columns
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_map.py
Labels: go

#48576 [Core] Rename ClientFactoryFn to CoreWorkerClientFactoryFn
  python/ray/_raylet.pyx
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.h
  src/ray/rpc/node_manager/node_manager_client_pool.cc
  src/ray/rpc/node_manager/node_manager_client_pool.h
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_client_pool.cc
  src/ray/rpc/worker/core_worker_client_pool.h
Labels: go

#48611 [core] [3/N] Use uv as package manager
  python/ray/_private/runtime_env/BUILD
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/uv.py
  python/ray/_private/runtime_env/validation.py
  python/ray/runtime_env/runtime_env.py
  python/ray/tests/BUILD
  python/ray/tests/test_runtime_env_uv.py
Labels: go

#48541 [Core]: Fix ConnectionError on Autoscaler CR lookups in K8s clusters with custom DNS for Kubernetes API.
  python/ray/autoscaler/_private/kuberay/node_provider.py
Labels: go

#48644 [core] fix import path
  src/ray/object_manager/object_manager.cc
Labels: go

#48627 [core][compiled graphs] Enable visualization tests
  python/ray/dag/BUILD
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_dag_visualization.py
  python/requirements/test-requirements.txt
Labels: go

#48619 [core] [4/N] Package manager uv supports requirement file
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_uv.py
  python/ray/tests/unit/test_runtime_env_validation.py
Labels: go

#48639 [core] Fix function naming and error propagation
  src/ray/common/client_connection.cc
  src/ray/common/client_connection.h
  src/ray/common/function_descriptor.h
  src/ray/common/grpc_util.h
  src/ray/object_manager/plasma/store.cc
  src/ray/raylet/raylet.cc
Labels: go

#48648 [core] Fix vector assignment
  src/ray/common/client_connection.cc
Labels: go

#48658 [serve] improve router resolve request arg func
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
Labels: go

#48632 [core] [5/N] Check uv existence before installation
  python/ray/_private/runtime_env/uv.py
Labels: go

#48621 [core] Remove internal flags in driver on job submission.
  python/ray/_private/ray_constants.py
  python/ray/_private/utils.py
  python/ray/dashboard/modules/job/job_supervisor.py
  python/ray/tests/test_job.py
  src/ray/common/ray_internal_flag_def.h
Labels: go

#48262 [core] Minor cpp changes around core worker
  doc/source/ray-contribute/debugging.rst
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/dependency_resolver.cc
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
  src/ray/rpc/worker/core_worker_client.h
Labels: go

#48655 [Data] Fix usage of "id" in test_map
  python/ray/data/tests/test_map.py
Labels: go

#48665 [serve] small test change
  python/ray/serve/tests/test_batching.py
Labels: go

#48663 [core] Optimize ray check branch prediction
  src/ray/util/logging.h
  src/ray/util/macros.h
  src/ray/util/process.cc
Labels: go

#48678 [core] Fix gtest inclusion
  src/ray/object_manager/plasma/common.h
Labels: go

#45803 [RLlib] IMPALA on new API stack: Add Pong-v5 release test.
  release/release_tests.yaml
  release/rllib_tests/4gpus_96cpus.yaml
  release/rllib_tests/4gpus_96cpus_gce.yaml
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/marwil/marwil_learner.py
  rllib/connectors/common/batch_individual_items.py
  rllib/core/learner/learner.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/core/testing/utils.py
  rllib/tuned_examples/impala/pong_impala.py
Labels: tests-ok, rllib, rllib-newstack, go

#48599 [RLlib] New API stack: On by default for BC/MARWIL/CQL.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/tests/test_appo.py
  rllib/algorithms/bc/tests/test_bc_old_api_stack.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/cql/tests/test_cql_old_api_stack.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/marwil/tests/test_marwil_old_api_stack.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/sac/sac.py
  rllib/algorithms/tests/test_algorithm.py
  rllib/env/single_agent_env_runner.py
  rllib/env/tests/test_env_runner_group.py
  rllib/examples/offline_rl/offline_rl.py
  rllib/offline/estimators/tests/utils.py
  rllib/offline/tests/test_feature_importance.py
  rllib/utils/torch_utils.py
Labels: rllib, rllib-newstack, rllib-oldstack-cleanup, go

#48623 [core][autoscaler] Autoscaler v2 does not honor minReplicas/replicas count of the worker nodes and constantly terminates after idletimeout
  python/ray/autoscaler/v2/scheduler.py
  python/ray/autoscaler/v2/tests/test_scheduler.py
Labels: go

#48681 [RLlib] Add APPO Atari (Pong) release test.
  release/release_tests.yaml
  rllib/algorithms/impala/impala.py
  rllib/tuned_examples/appo/pong_appo.py
Labels: rllib, release-test, rllib-newstack, go

#48669 Fix doc lint
  rllib/README.rst
Labels: go

#48687 [RLlib] Cleanup examples folder vol 32: Enable RLlib + Serve example in CI and translate to new API stack.
  rllib/BUILD
  rllib/examples/ray_serve/classes/cartpole_deployment.py
  rllib/examples/ray_serve/ray_serve_with_rllib.py
Labels: serve, rllib, rllib-docs-or-examples, rllib-newstack, go

#48698 [RLlib] Add missing `get_ctor_args_and_kwargs` methods to all ConnectorV2 built-in classes.
  rllib/connectors/common/add_states_from_episodes_to_batch.py
  rllib/connectors/connector_v2.py
  rllib/connectors/learner/add_next_observations_from_episodes_to_train_batch.py
  rllib/connectors/learner/general_advantage_estimation.py
  rllib/examples/inference/policy_inference_after_training_w_connector.py
Labels: rllib, rllib-connectorv2, rllib-newstack, go

#48660 [core][compiled graphs] Clean up viz_str() methods
  python/ray/dag/dag_node_operation.py
Labels: go

#48634 [core] [6/N] Allow users to specify uv version to install
  python/ray/_private/runtime_env/uv.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_uv.py
  python/ray/tests/unit/test_runtime_env_validation.py
Labels: go

#48637 [core] [7/N] Add doc for runtime env setup with uv
  doc/source/ray-core/handling-dependencies.rst
Labels: go

#48688 [Data] Relax timeout on TFRecords benchmark
  release/nightly_tests/dataset/read_tfrecords_benchmark.py
  release/release_tests.yaml
Labels: go

#48667 [core] Upgrade abseil
  bazel/ray_deps_setup.bzl
Labels: go

#48691 [Data] Deprecate `read_parquet_bulk`
  python/ray/data/read_api.py
Labels: go

#48704 [Data] Remove `prefetch_batches` and `prefetch_blocks` parameters of `iter_rows`
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_consumption.py
Labels: go

#48690 [Data] Deprecate `meta_provider` parameter of read APIs
  python/ray/data/read_api.py
  python/ray/data/tests/test_image.py
Labels: go

#48606 Add perf metrics for 2.39.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#48670 [core] [8/N] Enable validation for uv installtion
  python/ray/_private/runtime_env/uv.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_uv.py
  python/ray/tests/unit/test_runtime_env_validation.py
Labels: go

#48692 [Data] Deprecate `to_torch`
  doc/source/data/api/dataset.rst
  python/ray/data/dataset.py
  python/ray/data/tests/test_torch.py
Labels: go

#48638 [core] Add a util for size literals
  BUILD.bazel
  src/ray/stats/metric_defs.cc
  src/ray/util/BUILD
  src/ray/util/size_literals.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/size_literals_test.cc
Labels: go

#48509 [Data] Fixing `DelegatingBlockBuilder` to avoid re-serializing objects multiple times
  python/ray/data/_internal/delegating_block_builder.py
Labels: go

#48671 [core] add --enable-prof-libunwind to jemalloc build
  bazel/BUILD.jemalloc
Labels: go

#48711 [core] Minor improvement for session
  src/ray/raylet/runtime_env_agent_client.cc
Labels: go

#48686 Revert "Revert "[Data] Add `BundleQueue` abstraction (#48503)" (#48612)"
  python/ray/data/BUILD
  python/ray/data/_internal/execution/bundle_queue/__init__.py
  python/ray/data/_internal/execution/bundle_queue/bundle_queue.py
  python/ray/data/_internal/execution/bundle_queue/fifo_bundle_queue.py
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_bundle_queue.py
  python/ray/data/tests/test_operators.py
  python/ray/data/tests/test_stats.py
Labels: go

#48727 [data] skip tensorflow tests for python 3.12
  python/ray/data/tests/test_consumption.py
Labels: go

#48629 [Arrow] Enabling V2 Arrow Tensor extension type by default (allowing tensors > 2Gb)
  python/ray/air/util/data_batch_conversion.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_ecosystem.py
  python/ray/data/tests/test_image.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_pandas.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_strict_mode.py
  python/ray/data/tests/test_transform_pyarrow.py
Labels: go

#48636 [Core] Make Task Exit with System Error When free_objects Receives IOError
  python/ray/_raylet.pyx
  python/ray/tests/test_output.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/raylet_client/raylet_client.cc
Labels: go

#48287 [Data] support batch_format for Sort and Aggregate
  python/ray/data/_internal/logical/operators/all_to_all_operator.py
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/logical/rules/inherit_batch_format.py
  python/ray/data/_internal/planner/aggregate.py
  python/ray/data/_internal/planner/exchange/aggregate_task_spec.py
  python/ray/data/_internal/planner/exchange/sort_task_spec.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/_internal/planner/sort.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#48478 [data] Handle nullable fields in schema across blocks for parquet files
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/tests/test_parquet.py
Labels: go

#48697 [data] cleanup: use SortKey instead of mixed typing in aggregation
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/planner/aggregate.py
  python/ray/data/_internal/planner/exchange/aggregate_task_spec.py
  python/ray/data/block.py
  python/ray/data/tests/test_all_to_all.py
Labels: go

#48731 [core] [9/N] Skip installation if already
  python/ray/_private/runtime_env/uv.py
Labels: go

#48695 [core] Fix wrong return type on get_actor in the state api
  python/ray/util/state/api.py
Labels: go

#48746 [Dashboard] Fix dashboard NodeHead._update_node_stats check failure
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/node/tests/test_node.py
Labels: go

#48661 [core] Stop waiting for dependencies when cancelling tasks
  python/ray/tests/test_cancel.py
  src/mock/ray/core_worker/task_manager.h
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.cc
Labels: go

#48734 [core] Minor cpp improvement
  cpp/src/ray/runtime/task/native_task_submitter.cc
  src/ray/common/scheduling/cluster_resource_data.h
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: go

#48473 [core][compiled graphs] Rework visualize with channel info and actor coloring
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_dag_visualization.py
Labels: go

#48750 [data] Sort with None
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/planner/exchange/sort_task_spec.py
  python/ray/data/_internal/util.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_util.py
Labels: go

#48702 [RLlib] Reverse learner queue behavior of IMPALA/APPO (consume oldest batches first, instead of newest, BUT drop oldest batches if queue full).
  rllib/BUILD
  rllib/algorithms/impala/impala_learner.py
Labels: go

#48653 [Train] fix: typo
  python/ray/train/huggingface/transformers/_transformers_utils.py
Labels: go

#48714 [Refactor] Remove unused `KubeRayNodeProvider._url` method.
  python/ray/autoscaler/_private/kuberay/node_provider.py
Labels: kuberay, go

#48745 [Data] [Dashboard] Fix `Rows Outputted` being zero on Ray Data Dashboard
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_stats.py
Labels: go

#48082 Update kubernetes.md
  doc/source/serve/production-guide/kubernetes.md
Labels: go

#48753 [core] Change m4's to m6i's for core release tests
  release/benchmarks/object_store.yaml
  release/nightly_tests/stress_tests/placement_group_tests_compute.yaml
  release/nightly_tests/stress_tests/smoke_test_compute.yaml
  release/nightly_tests/stress_tests/stress_tests_compute.yaml
  release/nightly_tests/stress_tests/stress_tests_compute_large.yaml
Labels: go

#48762 [image] remove azure packages from base image
  docker/base-deps/Dockerfile
  python/ray/autoscaler/azure/example-full.yaml
  python/ray/autoscaler/azure/example-gpu-docker.yaml
Labels: go

#48767 [core] Fix security issue for retry package
  release/BUILD.bazel
  release/ray_release/cluster_manager/minimal.py
  release/ray_release/retry.py
  release/ray_release/tests/test_retry.py
  release/requirements_buildkite.in
  release/requirements_buildkite.txt
Labels: go

#48774 [vm launcher] change nightly and latest launcher test to manual
  release/release_tests.yaml
Labels: go

#48764 [image] comply with constraint file in base image
  ci/docker/ray-ml.cpu.base.wanda.yaml
  ci/docker/ray-ml.cuda.base.wanda.yaml
  ci/docker/ray.cpu.base.aarch64.wanda.yaml
  ci/docker/ray.cpu.base.wanda.yaml
  ci/docker/ray.cuda.base.aarch64.wanda.yaml
  ci/docker/ray.cuda.base.wanda.yaml
  docker/base-deps/Dockerfile
  docker/ray-ml/Dockerfile
  docker/ray-ml/install-ml-docker-requirements.sh
  docker/ray/Dockerfile
Labels: go

#46273 [data][api] implement `HudiDataSource`
  .vale/styles/config/vocabularies/Data/accept.txt
  doc/source/data/api/input_output.rst
  python/ray/data/BUILD
  python/ray/data/__init__.py
  python/ray/data/_internal/datasource/hudi_datasource.py
  python/ray/data/examples/data/hudi-tables/0.x_cow_partitioned.zip
  python/ray/data/read_api.py
  python/ray/data/tests/test_hudi.py
  python/requirements/ml/data-test-requirements.txt
  python/requirements_compiled.txt
Labels: triage, @external-author-action-required, data, go

#48756 [ray metrics launch-prometheus] Map aarch64 to arm64 in get_system_info function for Prometheus download
  python/ray/dashboard/modules/metrics/install_and_start_prometheus.py
Labels: observability, go

#48782 [core][compiled graphs] Fix do_profile_tasks
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
Labels: go

#48487 [Arrow] Unifying Arrow conversion handling, fixing handling of >2Gb objects
  python/ray/air/BUILD
  python/ray/air/tests/test_arrow.py
  python/ray/air/tests/test_object_extension.py
  python/ray/air/util/object_extensions/arrow.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/air/util/tensor_extensions/utils.py
  python/ray/data/BUILD
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/_internal/numpy_support.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/table_block.py
  python/ray/data/_internal/util.py
  python/ray/data/block.py
  python/ray/data/context.py
  python/ray/data/extensions/__init__.py
  python/ray/data/extensions/object_extension.py
  python/ray/data/tests/preprocessors/test_encoder.py
  python/ray/data/tests/test_arrow_block.py
  python/ray/data/tests/test_arrow_serialization.py
  python/ray/data/tests/test_binary.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_numpy_support.py
  python/ray/data/tests/test_pandas_block.py
  python/ray/data/tests/test_strict_mode.py
  python/ray/data/tests/test_transform_pyarrow.py
Labels: go

#48776 [RLlib] Make opencv-python-headless default over opencv-python
  python/requirements/ml/rllib-test-requirements.txt
  rllib/utils/images.py
Labels: go

#48787 [ci] update requirements for rllib changes
  python/requirements_compiled.txt
Labels: go

#48715 [Core] Support labels for ray.remote
  python/ray/_private/ray_option_utils.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/remote_function.py
  python/ray/tests/test_advanced.py
  src/ray/common/task/task_util.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/protobuf/common.proto
  src/ray/protobuf/core_worker.proto
Labels: go

#48800 [RLlib] APPO enhancements (new API stack) vol 02: Cleanup loss function, add GAE-lambda to vtrace, make rho-clip configurable.
  rllib/algorithms/appo/appo.py
  rllib/algorithms/appo/appo_rl_module.py
  rllib/algorithms/appo/torch/appo_torch_learner.py
  rllib/algorithms/impala/vtrace_torch.py
Labels: rllib, rllib-algorithms, rllib-newstack, go

#48766 [deps] upgrade cryptography and pyopenssl
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#48777 [CLI] Remove monkey-patching of `logging.Logger.makeRecord`
  python/ray/autoscaler/_private/cli_logger.py
  python/ray/tests/test_cli_logger.py
Labels: go

#48791 [dashboard] add actor pid to dashboard
  python/ray/dashboard/client/src/pages/actor/ActorDetail.tsx
Labels: go

#48795 [core][compiled graphs] Fix test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#48785 [ci] fix misc group dependency
  .buildkite/others.rayci.yml
Labels: go

#48803 [Serve] Handle multiple changed objects per `LongPollHost.listen_for_change` RPC
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/endpoint_state.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/test_metrics.py
Labels: go

#48749 [core] Performance improvement for runtime env serialization
  python/ray/_private/utils.py
  python/ray/remote_function.py
  python/ray/tests/test_basic.py
  src/ray/raylet/raylet.h
Labels: core, go

#48721 [core] C++ improvement for `Task` class
  src/ray/common/BUILD
  src/ray/common/task/task.cc
  src/ray/common/task/task.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/raylet/local_task_manager.cc
Labels: core, go

#48814 [Core][Telemetry] Fix `total_num_cpus` and `total_num_gpus` with `autoscaler_v2`
  python/ray/_private/usage/usage_lib.py
Labels: go

#48811 [release] set golden_notebook_torch_tune_serve_test frequency to manual
  release/release_tests.yaml
Labels: go

#47896 [Serve] Add more nuanced checks for http proxy status errors
  python/ray/serve/_private/proxy.py
Labels: triage, serve, go

#48796 [doc] Add hpu resource description in ray serve docs
  doc/source/serve/getting_started.md
  doc/source/serve/resource-allocation.md
Labels: go

#48808 [core][compiled graphs] Wait for monitor thread to join before shutting down
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/context.py
Labels: go

#48790 Pass logging_config to controller global logger
  python/ray/serve/api.py
Labels: serve, go

#47335 [Core] GCS FT with redis sentinel
  doc/source/cluster/kubernetes/user-guides/kuberay-gcs-ft.md
  python/ray/_private/test_utils.py
  python/ray/tests/conftest.py
  python/ray/tests/test_gcs_fault_tolerance.py
  src/ray/gcs/redis_context.cc
Labels: P1, core, go

#48816 [core] Avoid parsing env exception
  src/ray/util/logging.cc
Labels: core, go

#48822 [serve] Add tests for HTTP status code `is_error` logic
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/test_metrics.py
Labels: go
