Repository ray-project/ray, pull requests merged in 2025-01, with the labels that each got.

#49472 Fix bazel installation for github codespace
  ci/env/install-bazel.sh
  doc/source/ray-contribute/development.rst
Labels: go

#49524 [core] Implement move semantics for status
  src/ray/common/status.h
  src/ray/common/test/status_test.cc
Labels: go

#49420 [data] fix groupby hang when value contains np.nan
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/util.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_arrow_block.py
Labels: data, go

#49388 [dashboard] Move StateHead's methods into free functions.
  python/ray/dashboard/modules/state/state_head.py
  python/ray/dashboard/state_aggregator.py
  python/ray/dashboard/state_api_utils.py
  python/ray/dashboard/utils.py
  python/ray/tests/test_state_api.py
Labels: go

#49450 [data] Update pip install for `stablediffusion_batch_prediction`
  doc/source/data/examples/stablediffusion_batch_prediction.ipynb
Labels: go

#49415 Add an util to return number of TPU chips on node
  doc/source/ray-core/api/utility.rst
  python/ray/tests/accelerators/test_tpu.py
  python/ray/util/accelerators/tpu.py
Labels: go

#49509 [core] Introduce Postable for StoreClient.
  python/ray/includes/global_state_accessor.pxd
  src/mock/ray/gcs/store_client/in_memory_store_client.h
  src/mock/ray/gcs/store_client/redis_store_client.h
  src/mock/ray/gcs/store_client/store_client.h
  src/ray/common/BUILD
  src/ray/common/asio/postable.h
  src/ray/common/test_util.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/store_client_kv.cc
  src/ray/gcs/gcs_server/store_client_kv.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/gcs_server/test/redis_gcs_table_storage_test.cc
  src/ray/gcs/store_client/in_memory_store_client.cc
  src/ray/gcs/store_client/in_memory_store_client.h
  src/ray/gcs/store_client/observable_store_client.cc
  src/ray/gcs/store_client/observable_store_client.h
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/redis_store_client.h
  src/ray/gcs/store_client/store_client.h
  src/ray/gcs/store_client/test/in_memory_store_client_test.cc
  src/ray/gcs/store_client/test/redis_store_client_test.cc
  src/ray/gcs/store_client/test/store_client_test_base.h
  src/ray/util/function_traits.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/function_traits_test.cc
Labels: go

#49244 [Data] Fix bug where `file_extensions` doesn't work with compound extensions
  python/ray/data/_internal/datasource/csv_datasource.py
  python/ray/data/_internal/datasource/json_datasource.py
  python/ray/data/datasource/path_util.py
  python/ray/data/tests/test_file_based_datasource.py
Labels: go

#49167 [Docs][KubeRay] related doc change for making helm and kustomize cons…
  doc/source/cluster/kubernetes/getting-started/raycluster-quick-start.md
Labels: docs, go

#49371 [core] [compiled graphs] Exit dagref waiting based on sigint
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/core_worker/experimental_mutable_object_provider.h
  src/ray/core_worker/test/mutable_object_provider_test.cc
  src/ray/object_manager/common.cc
  src/ray/object_manager/common.h
  src/ray/object_manager/plasma/test/mutable_object_test.cc
  src/ray/raylet/node_manager.cc
Labels: go

#49551 [core] Post for GetOrGenerateClusterId continuations.
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
Labels: go

#49549 [Data] Simplify schema of benchmark results
  release/nightly_tests/dataset/benchmark.py
  release/nightly_tests/dataset/gpu_batch_inference.py
  release/nightly_tests/dataset/groupby_benchmark.py
  release/nightly_tests/dataset/image_loader_microbenchmark.py
  release/nightly_tests/dataset/map_benchmark.py
  release/nightly_tests/dataset/multi_node_train_benchmark.py
  release/nightly_tests/dataset/read_and_consume_benchmark.py
  release/nightly_tests/dataset/read_from_uris_benchmark.py
  release/nightly_tests/dataset/read_tfrecords_benchmark.py
  release/nightly_tests/dataset/sort_benchmark.py
  release/nightly_tests/dataset/stable_diffusion_benchmark.py
  release/nightly_tests/dataset/streaming_split_benchmark.py
  release/nightly_tests/dataset/tpch_q1.py
Labels: go

#49550 [core] Add thread checker for GcsAutoscalerStateManager.
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
Labels: go

#49480 [core] Resolve the race condition between reference counting GC and actor creation
  python/ray/tests/test_get_or_create_actor.py
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
Labels: go

#49530 [core][compiled-graphs][2/N] Polish APIs: update comments for max_inflight_executions
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/context.py
  python/ray/dag/dag_node.py
Labels: go

#49465 [RLlib; docs] Docs do-over (new API stack): Update "new API stack" header include.
  doc/source/_includes/rllib/new_api_stack.rst
Labels: tests-ok, rllib, rllib-docs-or-examples, rllib-newstack, go

#49527 [RLlib] Cleanup examples folder vol. 41: Add new example on async gym vector env.
  doc/source/rllib/rllib-examples.rst
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/tests/test_callbacks_on_algorithm.py
  rllib/env/single_agent_env_runner.py
  rllib/examples/envs/async_gym_env_vectorization.py
  rllib/examples/fault_tolerance/crashing_and_stalling_env.py
  rllib/utils/test_utils.py
Labels: rllib, rllib-env, rllib-docs-or-examples, rllib-newstack, rllib-envrunners, go

#49532 [core] Don't build cpp with default dev build command
  python/setup.py
Labels: go

#48818 [RLlib; Offline RL] Documentation do-over: Offline RL.
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  doc/source/rllib/images/offline/docs_rllib_offline_bc_episode_return_mean.svg
  doc/source/rllib/images/offline/docs_rllib_offline_prelearner.svg
  doc/source/rllib/images/offline/key_layers.svg
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/offline.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/user-guides.rst
  rllib/algorithms/algorithm_config.py
  rllib/offline/offline_prelearner.py
Labels: rllib, rllib-docs-or-examples, go

#49536 [RLlib] Cleanup examples folder vol. 42: New example script on how to write custom Algorithm (VPG) from scratch.
  doc/source/rllib/rllib-examples.rst
  doc/source/rllib/rllib-rlmodule.rst
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/tests/test_algorithm_config.py
  rllib/connectors/learner/__init__.py
  rllib/connectors/learner/compute_returns_to_go.py
  rllib/core/columns.py
  rllib/core/rl_module/tests/test_multi_rl_module.py
  rllib/core/rl_module/tests/test_rl_module_specs.py
  rllib/core/rl_module/torch/tests/test_torch_rl_module.py
  rllib/examples/algorithms/classes/vpg.py
  rllib/examples/algorithms/vpg_custom_algorithm.py
  rllib/examples/learners/classes/custom_ppo_loss_fn_learner.py
  rllib/examples/learners/classes/vpg_torch_learner.py
  rllib/examples/learners/ppo_with_custom_loss_fn.py
  rllib/examples/rl_modules/classes/vpg_torch_rlm.py
  rllib/utils/metrics/metrics_logger.py
  rllib/utils/metrics/stats.py
Labels: go

#49286 feat: new landing page for ray users
  README.rst
  doc/source/_templates/index.html
  doc/source/_templates/navbar-anyscale.html
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/ray-overview/getting-started.md
  doc/source/ray-overview/installation.rst
Labels: go

#49555 [core] [easy] [no-op] Move some task spec and shared pointer cleanup
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#49296 [Data] optimize dataset.unique()
  python/ray/data/_internal/aggregate.py
  python/ray/data/_internal/null_aggregate.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
  python/ray/data/tests/test_all_to_all.py
Labels: go

#49478 [docs] add apple silicon tab in kubernetes Kuberay quickstart
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
Labels: go

#49518 [RLlib] Docs do-over (new API stack): Remove all old API stack `package_ref` docs.
  doc/source/rllib/images/rollout_worker_class_overview.svg
  doc/source/rllib/new-api-stack-migration-guide.rst
  doc/source/rllib/package_ref/algorithm.rst
  doc/source/rllib/package_ref/distributions.rst
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/env/env_runner.rst
  doc/source/rllib/package_ref/evaluation.rst
  doc/source/rllib/package_ref/external-app.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/package_ref/models.rst
  doc/source/rllib/package_ref/policy.rst
  doc/source/rllib/package_ref/policy/custom_policies.rst
  doc/source/rllib/package_ref/utils.rst
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-fault-tolerance.rst
  doc/source/rllib/rllib-new-api-stack.rst
  rllib/core/rl_module/__init__.py
  rllib/utils/checkpoints.py
  rllib/utils/policy.py
  rllib/utils/schedules/scheduler.py
  rllib/utils/tensor_dtype.py
  rllib/utils/torch_utils.py
Labels: rllib, rllib-docs-or-examples, rllib-newstack, rllib-oldstack-cleanup, go

#49462 Remove unused code snippets in ray-overview
  doc/BUILD
  doc/source/ray-overview/doc_test/README.md
  doc/source/ray-overview/doc_test/ray_core.py
  doc/source/ray-overview/doc_test/ray_data.py
  doc/source/ray-overview/doc_test/ray_rllib.py
  doc/source/ray-overview/doc_test/ray_train.py
  doc/source/ray-overview/doc_test/ray_tune.py
Labels: go

#49486 [core] Introduce ray::StatusOr.
  src/ray/common/BUILD
  src/ray/common/status_or.h
  src/ray/common/test/BUILD
  src/ray/common/test/status_or_test.cc
  src/ray/common/test/testing.h
Labels: go

#49560 [core] Move ToTimeoutPoint to util.cc
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/util/util.cc
  src/ray/util/util.h
Labels: go

#49317 [train v2+tune] Split `ray.train.*` and `ray.tune.*` API entrypoints
  doc/source/tune/api/execution.rst
  doc/source/tune/api/trainable.rst
  python/ray/air/_internal/session.py
  python/ray/air/integrations/wandb.py
  python/ray/air/session.py
  python/ray/train/_internal/session.py
  python/ray/train/base_trainer.py
  python/ray/train/constants.py
  python/ray/train/context.py
  python/ray/train/tests/test_base_trainer.py
  python/ray/train/tests/test_new_persistence.py
  python/ray/train/utils.py
  python/ray/tune/BUILD
  python/ray/tune/__init__.py
  python/ray/tune/callback.py
  python/ray/tune/context.py
  python/ray/tune/execution/class_cache.py
  python/ray/tune/impl/config.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/tests/test_api_migrations.py
  python/ray/tune/trainable/trainable_fn_utils.py
Labels: go

#49522 [train v2+tune] Add an environment variable to disable running the `TrainController` as an actor
  python/ray/train/v2/_internal/constants.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/tests/test_data_parallel_trainer.py
Labels: go

#49574 [core] [easy] [no-op] Minor optimization for dependency resolution
  src/ray/core_worker/transport/dependency_resolver.cc
  src/ray/core_worker/transport/dependency_resolver.h
Labels: go

#49513 [RLlib; docs] Docs do-over (new API stack): New `rllib-callback.rst` page.
  .vale/styles/config/vocabularies/RLlib/accept.txt
  doc/source/rllib/images/acrobot-v1.png
  doc/source/rllib/package_ref/callback.rst
  doc/source/rllib/package_ref/index.rst
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-callback.rst
  doc/source/rllib/rllib-fault-tolerance.rst
  doc/source/rllib/rllib-saving-and-loading-algos-and-policies.rst
  doc/source/rllib/user-guides.rst
  python/requirements/ml/rllib-requirements.txt
  python/requirements_compiled.txt
  rllib/callbacks/utils.py
Labels: go

#49528 [RLlib] Docs do-over (new API stack): Add scaling guide rst page.
  .vale/styles/config/vocabularies/RLlib/accept.txt
  doc/BUILD
  doc/source/rllib/images/rllib-config.svg
  doc/source/rllib/images/scaling_axes_overview.svg
  doc/source/rllib/index.rst
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-env.rst
  doc/source/rllib/rllib-training.rst
  doc/source/rllib/scaling-guide.rst
  doc/source/rllib/user-guides.rst
Labels: rllib, rllib-docs-or-examples, rllib-newstack, go

#49370 Handle pandas timestamp with nanosecs precision
  python/ray/data/_internal/numpy_support.py
  python/ray/data/tests/test_arrow_block.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_numpy_support.py
  python/ray/data/tests/test_pandas_block.py
Labels: go

#49576 [core] Exclusively run redis test
  BUILD.bazel
Labels: go

#49353 [Dashboard] add RAY_PROMETHEUS_HEADERS env for carrying additional headers to Prometheus
  python/ray/dashboard/modules/data/data_head.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/metrics/templates.py
  python/ray/dashboard/tests/test_dashboard.py
Labels: dashboard, observability, go

#49577 [core] Attempt fix GCS client ASAN
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.cc
  src/ray/gcs/redis_client.cc
  src/ray/gcs/redis_client.h
  src/ray/gcs/store_client/redis_store_client.cc
Labels: go

#49579 [core] [easy] [no-op] Fix util filename naming
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/normal_scheduling_queue.cc
  src/ray/core_worker/transport/normal_scheduling_queue.h
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.h
  src/ray/core_worker/transport/scheduling_util.cc
  src/ray/core_worker/transport/scheduling_util.h
Labels: go

#49425 fix(preprocessors): simple imputer raise error on no stats for column
  python/ray/data/preprocessors/imputer.py
  python/ray/data/tests/preprocessors/test_imputer.py
Labels: data, go

#49519 [train v2+tune] Propagate Train v2 feature flag from Tune driver to Train driver
  python/ray/tune/execution/class_cache.py
Labels: go

#49569 [core] Construct statusor data with union
  src/ray/common/status_or.h
  src/ray/common/test/status_or_test.cc
Labels: go

#49585 [core] [easy] Fix cpp example
  cpp/example/BUILD.bazel
  cpp/example/run.sh
Labels: go

#49581 [core][autoscaler] Remove worker_rpc_drain from Autoscaler V2
  python/ray/autoscaler/v2/instance_manager/config.py
  python/ray/autoscaler/v2/instance_manager/reconciler.py
  python/ray/autoscaler/v2/tests/test_reconciler.py
Labels: go

#49539 [serve] Use `pickle.dumps` for proxy->replica messages
  python/ray/serve/_private/common.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/proxy_request_response.py
  python/ray/serve/_private/replica.py
  python/ray/serve/tests/unit/test_proxy.py
Labels: go

#49580 [core][chore] `redis_password` is unused in several Ray CLI commands
  python/ray/scripts/scripts.py
Labels: go

#49354 [core] Application cgroup setup
  src/ray/common/cgroup/cgroup_setup.cc
  src/ray/common/cgroup/cgroup_setup.h
Labels: go

#49597 Fix lint
  doc/source/rllib/images/scaling_axes_overview.svg
  doc/source/rllib/rllib-callback.rst
Labels: go

#49564 feat: ray community survey banner
  doc/source/conf.py
Labels: go

#49476 [Doc] Replace Head Node ServiceMonitor with PodMonitor
  doc/source/cluster/kubernetes/images/prometheus_web_ui.png
  doc/source/cluster/kubernetes/k8s-ecosystem/prometheus-grafana.md
Labels: go

#49598 [train] bump v2/test_scheduling from small to medium
  python/ray/train/v2/BUILD
Labels: go

#49595 [serve] Clean up interface to create placement groups
  python/ray/serve/_private/common.py
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_deployment_scheduler.py
  python/ray/serve/tests/unit/test_deployment_scheduler.py
Labels: go

#49607 Another lint fix
  .buildkite/release/build.rayci.yml
Labels: go

#49380 [dashboard] Remove DataSource.events.
  python/ray/_private/state_api_test_utils.py
  python/ray/dashboard/datacenter.py
  python/ray/dashboard/modules/event/event_head.py
  python/ray/dashboard/modules/event/tests/test_event.py
  python/ray/dashboard/modules/state/state_head.py
  python/ray/dashboard/state_aggregator.py
  python/ray/dashboard/state_api_utils.py
  python/ray/tests/test_state_api.py
  python/ray/util/state/state_manager.py
Labels: go

#49611 [core] Move example BUILD
  cpp/example/BUILD
Labels: go

#49583 [core] Remove extra copies on InternalKVGets and return bool on InternalKVPut
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
  src/mock/ray/gcs/gcs_client/accessor.h
  src/mock/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/store_client_kv.cc
  src/ray/gcs/gcs_server/store_client_kv.h
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/protobuf/gcs_service.proto
Labels: go

#49588 [core] Remove unused GetProfilingStats and job_agent protbufs
  BUILD.bazel
  src/ray/protobuf/BUILD
  src/ray/protobuf/job_agent.proto
  src/ray/protobuf/reporter.proto
Labels: go

#49571 [serve] add get request metadata func
  python/ray/serve/_private/common.py
  python/ray/serve/_private/default_impl.py
  python/ray/serve/handle.py
Labels: go

#49612 [core] Introduce get_compatible_keys for ImageURIPlugin
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/runtime_env/default_impl.py
  python/ray/_private/runtime_env/image_uri.py
  python/ray/runtime_env/runtime_env.py
Labels: go

#49591 [core][compiled graphs] Add "experimental" to overlap_gpu_communication
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/context.py
  python/ray/dag/dag_node.py
Labels: go

#49697 [serve] Move default runtime_env configuration into `build_app`
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/build_app.py
  python/ray/serve/_private/deploy_utils.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_standalone_3.py
  python/ray/serve/tests/unit/test_build_app.py
Labels: go

#49701 [core] [revert] Manually revert cpp example change
  cpp/example/BUILD
  cpp/example/BUILD.bazel
  cpp/example/run.sh
Labels: go

#49573 [data] Fix map operator fusion when concurrency is set
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#49702 Fix lint
  doc/source/_templates/index.html
  doc/source/_templates/navbar-anyscale.html
  doc/source/rllib/images/offline/docs_rllib_offline_bc_episode_return_mean.svg
  doc/source/rllib/images/offline/docs_rllib_offline_prelearner.svg
  doc/source/rllib/images/offline/key_layers.svg
  doc/source/rllib/package_ref/offline.rst
  doc/source/rllib/rllib-offline.rst
  src/ray/common/asio/postable.h
Labels: go

#49687 [RLlib] Add `time between sample` metric to `MultiAgentEnvRunner`.
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
Labels: go

#49461 [core][compiled graphs] Throw unrecoverable actor exceptions at ray.get()
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_mocked_nccl_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/compiled_dag_ref.py
Labels: go

#49504 [RLlib] Docs do-over (new API stack): Re-write checkpointing rst page.
  .vale/styles/config/vocabularies/RLlib/accept.txt
  doc/source/rllib/checkpoints.rst
  doc/source/rllib/doc_code/checkpoints.py
  doc/source/rllib/doc_code/saving_and_loading_algos_and_policies.py
  doc/source/rllib/images/checkpointing/from_checkpoint.svg
  doc/source/rllib/images/checkpointing/save_and_restore.svg
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-callback.rst
  doc/source/rllib/rllib-fault-tolerance.rst
  doc/source/rllib/rllib-new-api-stack.rst
  doc/source/rllib/rllib-rlmodule.rst
  doc/source/rllib/rllib-saving-and-loading-algos-and-policies.rst
  doc/source/rllib/user-guides.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/appo/tests/test_appo.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/examples/checkpoints/change_config_during_training.py
  rllib/utils/tests/old_checkpoints/create_checkpoint.py
Labels: rllib, rllib-checkpointing-or-recovery, rllib-docs-or-examples, rllib-newstack, rllib-oldstack-cleanup, go

#48833 [core] [3/N] Check cgroupv2 mount status
  src/ray/common/cgroup/cgroup_setup.cc
  src/ray/common/cgroup/cgroup_setup.h
  src/ray/common/cgroup/test/BUILD
  src/ray/common/cgroup/test/cgroup_v2_utils_test.cc
Labels: core, go

#49566 [core] Add statusor macros
  src/ray/common/BUILD
  src/ray/common/macros.h
  src/ray/common/status_or.h
  src/ray/common/test/status_or_test.cc
Labels: go

#49613 [KubeRay] Extrace autoscaling config from Kubernetes resource requests if no resource limits provided
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/tests/kuberay/test_autoscaling_config.py
Labels: go

#49479 [core] Init DashboardHeadModules with a Config.
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/actor/actor_head.py
  python/ray/dashboard/modules/data/data_head.py
  python/ray/dashboard/modules/event/event_head.py
  python/ray/dashboard/modules/healthz/healthz_head.py
  python/ray/dashboard/modules/job/job_head.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/reporter/reporter_head.py
  python/ray/dashboard/modules/serve/serve_rest_api_impl.py
  python/ray/dashboard/modules/snapshot/snapshot_head.py
  python/ray/dashboard/modules/state/state_head.py
  python/ray/dashboard/modules/tests/test_head.py
  python/ray/dashboard/modules/train/train_head.py
  python/ray/dashboard/modules/usage_stats/usage_stats_head.py
  python/ray/dashboard/optional_utils.py
  python/ray/dashboard/utils.py
Labels: go

#48838 [core] [4/N] Parameter change for ray cluster start with physical mode
  python/ray/_private/node.py
  python/ray/_private/parameter.py
  python/ray/_private/services.py
  python/ray/scripts/scripts.py
  src/ray/raylet/main.cc
Labels: core, go

#49130 [Docs] Fix some misinformation in Ray Collective Communication Lib
  doc/source/ray-more-libs/ray-collective.rst
Labels: docs, go

#49693 [RLlib] Add `MetricsLogger` to connector- and pipeline-calls.
  rllib/algorithms/impala/impala_learner.py
  rllib/connectors/connector_pipeline_v2.py
  rllib/connectors/connector_v2.py
  rllib/connectors/env_to_module/env_to_module_pipeline.py
  rllib/connectors/learner/learner_connector_pipeline.py
  rllib/core/learner/learner.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/offline/offline_prelearner.py
  rllib/tuned_examples/bc/cartpole_bc.py
  rllib/utils/metrics/__init__.py
  rllib/utils/metrics/metrics_logger.py
Labels: rllib, rllib-connectorv2, rllib-newstack, go

#49710 Fix lint
  doc/source/rllib/images/checkpointing/from_checkpoint.svg
  doc/source/rllib/images/checkpointing/save_and_restore.svg
Labels: go

#49552 [serve] return unavailable error if deployment failed to start
  doc/source/serve/api/index.md
  java/serve/src/main/java/io/ray/serve/poll/LongPollClientFactory.java
  java/serve/src/main/java/io/ray/serve/poll/LongPollNamespace.java
  java/serve/src/main/java/io/ray/serve/router/ReplicaSet.java
  java/serve/src/main/java/io/ray/serve/router/Router.java
  java/serve/src/test/java/io/ray/serve/router/ReplicaSetTest.java
  java/serve/src/test/java/io/ray/serve/router/RouterTest.java
  python/ray/serve/_private/common.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/router.py
  python/ray/serve/exceptions.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/unit/test_router.py
  src/ray/protobuf/serve.proto
Labels: go

#49696 [Serve] Deflake `test_reconfigure_with_queries`
  python/ray/serve/tests/test_deploy.py
Labels: serve, go

#49590 Avoid platform-specific metadata for grpcio
  python/setup.py
Labels: go

#49729 [core] Fix PlasmaObjectHeader timeout_point types for windows
  src/ray/object_manager/common.cc
Labels: go

#49723 [core][compiled graphs] Add actor name to visualization
  python/ray/dag/compiled_dag_node.py
Labels: go

#49596 [core] Avoid re-parse serialized runtime env info json
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
Labels: go

#49498 [Grafana] add `Cluster` variable to enable filtering of different RayClusters on Kubernetes
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/data_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/default_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/dashboards/serve_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/serve_deployment_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/serve_deployment_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/dashboards/serve_grafana_dashboard_base.json
Labels: dashboard, go

#49726 [core] Fix default logging rotation size
  src/ray/util/logging.cc
  src/ray/util/logging.h
Labels: go

#49715 [RLlib] Fix `train_batch_size_per_learner` problems.
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/appo/appo_learner.py
Labels: rllib, rllib-newstack, go

#49714 [RLlib] Add experimental option to suppress algo config `validate()`; some code cleanups.
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/bc/bc.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/dreamerv3/dreamerv3.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/ppo/ppo.py
  rllib/connectors/learner/learner_connector_pipeline.py
  rllib/core/learner/learner.py
  rllib/core/learner/torch/torch_learner.py
  rllib/utils/metrics/metrics_logger.py
  rllib/utils/minibatch_utils.py
  rllib/utils/test_utils.py
Labels: rllib, rllib-newstack, go

#49599 [docs] Callbacks edits
  .vale/styles/config/vocabularies/RLlib/accept.txt
  doc/source/rllib/package_ref/callback.rst
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-callback.rst
  doc/source/rllib/rllib-fault-tolerance.rst
  doc/source/rllib/user-guides.rst
Labels: rllib, docs, go

#49503 [core] [3/N] Combine client registration and port announcement
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet_client/raylet_client.cc
Labels: go

#49739 [core] [no-op] Unify ray_cc* starlark function
  src/ray/common/test/BUILD
  src/ray/common/test/syncer_service_e2e_test.cc
  src/ray/util/tests/BUILD
Labels: go

#49416 [core] Setup cgroup v2 in C++
  src/ray/common/cgroup/BUILD
  src/ray/common/cgroup/cgroup_context.h
  src/ray/common/cgroup/cgroup_utils.cc
  src/ray/common/cgroup/cgroup_utils.h
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
Labels: go

#49605 [Data] Add test for reading Parquet with null data
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/tests/test_parquet.py
Labels: go

#49746 Fix lint
  doc/source/rllib/rllib-advanced-api.rst
  doc/source/rllib/rllib-callback.rst
  doc/source/rllib/rllib-fault-tolerance.rst
Labels: go

#49720 [serve] Tune Python GC threshold in proxy by default
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/proxy.py
Labels: go

#49745 [Data] Fix `iter_batches` release test
  release/nightly_tests/dataset/read_and_consume_benchmark.py
Labels: go

#49747 [core] [easy] [no-op] Remove unnecessary copt
  src/ray/util/tests/BUILD
Labels: go

#49749 [core] [easy] Check cgroup file write result
  src/ray/common/cgroup/cgroup_setup.cc
  src/ray/common/cgroup/cgroup_utils.cc
Labels: go

#49737 [core][compiled-graphs] Always call `ensure_registered_as_[reader|writer]` in `read` / `write` function
  python/ray/experimental/channel/cached_channel.py
  python/ray/experimental/channel/intra_process_channel.py
  python/ray/experimental/channel/shared_memory_channel.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
Labels: go

#49547 [core] Check if python is exiting on a core worker on non-main Python thread
  python/ray/_raylet.pyx
  python/ray/dag/tests/experimental/test_accelerated_dag.py
Labels: go

#49677 [core] Rename `get_timeout_milliseconds` to `get_check_signal_interval_milliseconds`
  python/ray/includes/ray_config.pxd
  python/ray/includes/ray_config.pxi
  src/ray/common/ray_config_def.h
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
  src/ray/core_worker/store_provider/plasma_store_provider.cc
Labels: go

#49578 [Core] Fix how to calculate the number of hosts in a TPU
  python/ray/_private/accelerators/tpu.py
  python/ray/tests/accelerators/test_tpu.py
Labels: go

#49722 [doc][core][compiled graphs] Add visualization doc
  doc/source/images/compiled_graph.png
  doc/source/images/compiled_graph_schedule.png
  doc/source/ray-core/compiled-graph/ray-compiled-graph.rst
  doc/source/ray-core/compiled-graph/visualization.rst
Labels: go

#49600 [core][cgraph] Update timeout error messages
  python/ray/dag/compiled_dag_node.py
Labels: go

#49766 [Refactor][Core] Replace redis function arguments with reference and remove redundant struct statement
  src/ray/gcs/redis_context.cc
  src/ray/gcs/redis_context.h
  src/ray/gcs/test/callback_reply_test.cc
Labels: go

#49700 [Doc][Dashboard] document about the RAY_PROMETHEUS_HEADERS env for carrying additional headers to Prometheus
  doc/source/cluster/configure-manage-dashboard.md
Labels: dashboard, docs, go

#49724 [data] Adding in `iter_rows` to public api, remove beta tags for DataIterator
  python/ray/data/iterator.py
Labels: go

#49603 [Core] Increase the Timeout Time for Condition Wait for test_object_spilling_2 in Debug Mode
  python/ray/tests/BUILD
  python/ray/tests/test_object_spilling_2.py
Labels: go

#49671 [core][autoscaler] Remove worker_rpc_drain from Autoscaler V1
  python/ray/autoscaler/_private/autoscaler.py
  python/ray/autoscaler/_private/constants.py
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/autoscaler/_private/kuberay/node_provider.py
  python/ray/tests/kuberay/test_autoscaling_config.py
  python/ray/tests/test_autoscaler.py
Labels: go

#49559 [Core] Remediation for the Flaky Test test_gcs_fault_tolerance
  python/ray/_private/test_utils.py
  python/ray/tests/conftest.py
Labels: go

#49733 [core] pipe logging in C++
  src/ray/util/BUILD
  src/ray/util/pipe_logger.cc
  src/ray/util/pipe_logger.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/pipe_logger_test.cc
  src/ray/util/tests/unix_test_utils.cc
  src/ray/util/tests/unix_test_utils.h
Labels: go

#49704 [core] Postable InternalKVInterface and GcsTableStorage.
  python/ray/includes/global_state_accessor.pxd
  src/mock/ray/gcs/gcs_server/gcs_actor_manager.h
  src/mock/ray/gcs/gcs_server/gcs_kv_manager.h
  src/mock/ray/gcs/gcs_server/gcs_node_manager.h
  src/mock/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/common/asio/postable.h
  src/ray/common/test/BUILD
  src/ray/common/test/postable_test.cc
  src/ray/common/test_util.h
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/gcs_function_manager.h
  src/ray/gcs/gcs_server/gcs_init_data.cc
  src/ray/gcs/gcs_server/gcs_init_data.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_kv_manager.cc
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/store_client_kv.cc
  src/ray/gcs/gcs_server/store_client_kv.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_node_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_function_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_node_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/gcs/gcs_server/test/gcs_table_storage_test_base.h
  src/ray/gcs/gcs_server/test/gcs_worker_manager_test.cc
  src/ray/gcs/gcs_server/test/in_memory_gcs_table_storage_test.cc
  src/ray/gcs/gcs_server/test/redis_gcs_table_storage_test.cc
  src/ray/gcs/gcs_server/test/usage_stats_client_test.cc
  src/ray/gcs/gcs_server/usage_stats_client.cc
  src/ray/gcs/gcs_server/usage_stats_client.h
  src/ray/util/function_traits.h
Labels: go

#49777 [Fix][Docs] Fix sd.ipynb syntax error
  doc/source/train/examples/intel_gaudi/sd.ipynb
Labels: go

#49771 [train] update huggingface-hub in notebook release tests
  doc/source/templates/05_dreambooth_finetuning/dreambooth/requirements.txt
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: go

#49785 [Fix] Fix ruff rule B020: Loop control variable `conns` overrides iterable it iterates
  python/ray/tests/conftest.py
Labels: go

#49776 [core] Fix profile_events use after move
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
Labels: go

#49787 [Refactor][Core] Replace new smart pointers with make_unique and make_shared
  cpp/src/ray/runtime/abstract_ray_runtime.cc
  cpp/src/ray/runtime/local_mode_ray_runtime.cc
  cpp/src/ray/runtime/native_ray_runtime.cc
  cpp/src/ray/runtime/task/task_executor.cc
  src/ray/common/cgroup/cgroup_utils.cc
  src/ray/core_worker/lib/java/io_ray_runtime_task_NativeTaskSubmitter.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/redis_context.cc
  src/ray/object_manager/plasma/connection.cc
  src/ray/util/event.cc
Labels: go

#49767 [Refactor][Core] Migrate to RunArgvAsync for GetNextJobID
  src/mock/ray/gcs/store_client/in_memory_store_client.h
  src/mock/ray/gcs/store_client/redis_store_client.h
  src/mock/ray/gcs/store_client/store_client.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/store_client/in_memory_store_client.cc
  src/ray/gcs/store_client/in_memory_store_client.h
  src/ray/gcs/store_client/observable_store_client.cc
  src/ray/gcs/store_client/observable_store_client.h
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/gcs/store_client/redis_store_client.h
  src/ray/gcs/store_client/store_client.h
Labels: go

#49680 [RLlib] - Add "burn-in" period to the training of stateful `RLModules`.
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/dqn/torch/dqn_torch_learner.py
  rllib/env/utils/infinite_lookback_buffer.py
  rllib/tuned_examples/dqn/stateless_cartpole_dqn.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
Labels: go

#49284 [RLlib] "APPO-accelerate" vol 01: Make AggregatorActors work with IMPALA/APPO.
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/appo/tests/test_appo_learner.py
  rllib/algorithms/appo/torch/appo_torch_learner.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/algorithms/impala/tests/test_impala.py
  rllib/algorithms/utils.py
  rllib/core/learner/learner.py
  rllib/core/learner/learner_group.py
  rllib/env/env_runner_group.py
  rllib/examples/multi_agent/self_play_league_based_with_open_spiel.py
  rllib/examples/multi_agent/utils/self_play_league_based_callback.py
  rllib/tuned_examples/appo/pong_appo.py
  rllib/tuned_examples/impala/heavy_cartpole_impala.py
  rllib/tuned_examples/impala/memory-leak-test-impala.yaml
  rllib/tuned_examples/impala/pendulum-impala.yaml
  rllib/utils/actor_manager.py
  rllib/utils/torch_utils.py
Labels: go

#49435 [CI][Linter] Replace `flake8` and `isort` with `ruff`
  .buildkite/lint.rayci.yml
  .flake8
  .pre-commit-config.yaml
  ci/lint/format.sh
  ci/lint/lint.sh
  doc/source/serve/doc_code/load_shedding.py
  pyproject.toml
  python/ray/_private/pydantic_compat.py
  python/ray/air/examples/custom_trainer.py
  python/ray/dashboard/modules/event/tests/test_generate_export_events.py
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/default_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/serve_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/serve_deployment_dashboard_panels.py
  python/ray/serve/tests/common/remote_uris.py
  python/ray/serve/tests/test_config_files/syntax_error.py
  python/ray/setup-dev.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_mlflow.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_model_dl.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_tensorboard.py
  python/ray/train/examples/experiment_tracking/lightning_exp_tracking_wandb.py
  python/ray/train/examples/experiment_tracking/torch_exp_tracking_mlflow.py
  python/ray/train/examples/experiment_tracking/torch_exp_tracking_wandb.py
  python/ray/train/examples/pytorch/torch_quick_start.py
  python/ray/train/examples/tf/tensorflow_quick_start.py
  python/ray/tune/examples/cifar10_pytorch.py
  python/ray/tune/examples/pbt_convnet_example.py
  python/ray/tune/requirements-dev.txt
  python/ray/tune/tests/example.py
  python/ray/tune/tests/tutorial.py
  python/requirements/lint-requirements.txt
  python/requirements_compiled.txt
Labels: go

#49706 [doc][core] Fix typo "bookkeep" and link
  doc/source/ray-core/compiled-graph/quickstart.rst
  doc/source/ray-core/compiled-graph/ray-compiled-graph.rst
Labels: go

#49786 [Core] Remove dead StateDataSourceClient.get_task_info method
  python/ray/tests/test_state_api.py
  python/ray/util/state/state_manager.py
  src/ray/protobuf/node_manager.proto
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/node_manager_server.h
Labels: go

#49750 [data] Fixes `ray.data._internal.utils:iterate_with_retry`
  python/ray/data/_internal/util.py
  python/ray/data/tests/test_util.py
Labels: data, go

#49806 [serve] Refactor replica wrapper
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/handle_options.py
  python/ray/serve/_private/replica_result.py
  python/ray/serve/_private/replica_scheduler/__init__.py
  python/ray/serve/_private/replica_scheduler/pow_2_scheduler.py
  python/ray/serve/_private/replica_scheduler/replica_scheduler.py
  python/ray/serve/_private/replica_scheduler/replica_wrapper.py
  python/ray/serve/_private/router.py
  python/ray/serve/_private/utils.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#49807 [core] Move on UpdateResourceLoadAndUsage
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
Labels: go

#49752 deprecate container, change docs to image_uri
  doc/source/ray-core/handling-dependencies.rst
  doc/source/serve/advanced-guides/multi-app-container.md
  python/ray/runtime_env/runtime_env.py
Labels: go

#49810 [Data] Decrease scale of `iter_batches` release test
  release/release_data_tests.yaml
Labels: go

#49804 [core] Add compilation warning options
  bazel/ray.bzl
Labels: go

#49815 [Refactor] Fix ruff rule B010: Do not call `setattr` with a constant attribute value. It is not any safer than normal property access.
  pyproject.toml
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/utils.py
  python/ray/serve/multiplex.py
  python/ray/tests/test_unhandled_error.py
  python/ray/util/tracing/tracing_helper.py
  rllib/examples/rl_modules/pretraining_single_agent_training_multi_agent.py
Labels: go

#49817 [Refactor] Fix ruff rule Q000 and Q001
  ci/lint/git-clang-format
  pyproject.toml
Labels: go

#49814 [Refactor] Fix ruff rule B009: Do not call `getattr` with a constant attribute value. It is not any safer than normal property access.
  pyproject.toml
  python/ray/dashboard/modules/snapshot/tests/test_component_activities.py
  python/ray/dashboard/optional_utils.py
  python/ray/tests/modin/modin_test_utils.py
  python/ray/tune/utils/util.py
  rllib/algorithms/algorithm_config.py
  rllib/tests/run_regression_tests.py
Labels: go

#49800 [RLlib] Make `Episode.to_numpy` optional at end of `EnvRunner.sample()` (renamed from `finalize()`).
  doc/source/rllib/doc_code/sa_episode.py
  doc/source/rllib/package_ref/env/multi_agent_episode.rst
  doc/source/rllib/package_ref/env/single_agent_episode.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/single-agent-episode.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dreamerv3/utils/env_runner.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/sac/sac.py
  rllib/algorithms/utils.py
  rllib/callbacks/callbacks.py
  rllib/connectors/common/add_observations_from_episodes_to_batch.py
  rllib/connectors/common/add_states_from_episodes_to_batch.py
  rllib/connectors/common/frame_stacking.py
  rllib/connectors/env_to_module/flatten_observations.py
  rllib/connectors/env_to_module/prev_actions_prev_rewards.py
  rllib/connectors/env_to_module/write_observations_to_episodes.py
  rllib/connectors/learner/add_one_ts_to_episodes_and_truncate.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/multi_agent_episode.py
  rllib/env/single_agent_env_runner.py
  rllib/env/single_agent_episode.py
  rllib/env/tcp_client_inference_env_runner.py
  rllib/env/tests/test_multi_agent_episode.py
  rllib/env/tests/test_single_agent_episode.py
  rllib/examples/envs/classes/cartpole_with_large_observation_space.py
  rllib/examples/offline_rl/classes/image_offline_prelearner.py
  rllib/offline/offline_prelearner.py
  rllib/tuned_examples/ppo/cartpole_heavy_ppo.py
  rllib/utils/metrics/__init__.py
  rllib/utils/postprocessing/episodes.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
  rllib/utils/replay_buffers/multi_agent_episode_buffer.py
  rllib/utils/replay_buffers/multi_agent_prioritized_episode_buffer.py
  rllib/utils/replay_buffers/prioritized_episode_buffer.py
Labels: rllib, rllib-newstack, rllib-envrunners, go

#49780 [core] Fix windows build for pipe logger
  BUILD.bazel
  src/ray/common/BUILD
  src/ray/object_manager/plasma/allocator.h
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/connection.h
  src/ray/object_manager/plasma/malloc.h
  src/ray/object_manager/plasma/plasma.h
  src/ray/object_manager/plasma/shared_memory.h
  src/ray/util/BUILD
  src/ray/util/compat.h
  src/ray/util/function_traits.h
  src/ray/util/pipe_logger.cc
  src/ray/util/pipe_logger.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/unix_test_utils.cc
  src/ray/util/tests/unix_test_utils.h
Labels: go

#49816 [Refactor] Fix ruff rule F401: `{name}` imported but unused; consider using `importlib.util.find_spec` to test for availability
  pyproject.toml
  python/ray/_raylet.pyi
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/tests/autoscaler_test_utils.py
Labels: go

#49813 [Refactor] Fix ruff rule E714: Test for object identity should be `is not`
  pyproject.toml
  python/ray/tests/test_component_failures_2.py
  python/ray/tests/test_multinode_failures.py
  python/ray/tests/test_multinode_failures_2.py
  release/ray_release/config.py
  rllib/utils/deprecation.py
Labels: go

#49526 [Data] Add filters parameter to read_clickhouse
  python/ray/data/_internal/datasource/clickhouse_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_clickhouse.py
Labels: data, go

#49831 [release] remove all templates tests
  release/release_tests.yaml
Labels: go

#49820 [Serve] makes resource request log in one line
  python/ray/dashboard/client/src/common/CodeDialogButton/CodeDialogButton.tsx
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: go

#49711 [core][compiled-graphs] Read input channels in a round-robin manner with a short timeout, and fail fast if a RayTaskError is found
  python/ray/dag/context.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/experimental/channel/common.py
Labels: go

#49833 [core] recheckin compilation options
  bazel/ray.bzl
Labels: go

#49841 [core] Remove pipe logger EOF indicator
  src/ray/util/pipe_logger.cc
Labels: go

#49742 [Doc] add a doc for sharing a Grafana instance across multiple KubeRay custom resources
  doc/source/cluster/kubernetes/images/grafana_ray_dashboard.png
  doc/source/cluster/kubernetes/images/grafana_ray_dashboard2.png
  doc/source/cluster/kubernetes/k8s-ecosystem/prometheus-grafana.md
Labels: go

#49828 [core] [easy] [no-op] Apply thread annotation to pipe streamer
  src/ray/util/pipe_logger.cc
Labels: go

#49855 [dashboard] Bugfix: add back DashboardHead.gcs_aio_client.
  python/ray/dashboard/head.py
Labels: go

#49840 [serve] Mark deployment handle API as stable
  python/ray/serve/handle.py
Labels: go

#49865 [core][cgraph] Only check signals every second
  src/ray/core_worker/experimental_mutable_object_manager.cc
  src/ray/object_manager/common.cc
Labels: go

#48807 [Serve] Shared `LongPollClient` for `Router`s
  python/ray/serve/_private/long_poll.py
  python/ray/serve/_private/router.py
Labels: serve, go

#49837 [docs] Make it clear ray[all] is not recommended
  doc/source/ray-overview/installation.rst
  python/setup.py
Labels: go

#49874 [tune] fix mnist example
  python/ray/tune/examples/mnist_ptl_mini.py
Labels: go

#49880 [data] Replace usage of torchvision MNIST with FashionMNIST in data tests
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_formats.py
Labels: go

#49727 [core] Only get single node info rather then all when needed
  BUILD.bazel
  python/ray/includes/global_state_accessor.pxd
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/global_state_accessor.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/protobuf/gcs_service.proto
Labels: go

#49826 [Refactor] Fix ruff rule F602: Multi-value-repeated-key-variable
  pyproject.toml
  python/ray/tests/test_resource_demand_scheduler.py
Labels: core, go

#49873 [core] [easy] [no-op] Minor optimization on task move
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
Labels: go
