Repository ray-project/ray, pull requests merged in 2025-04, with the labels that each got.

#51867 [serve.llm] Update ray serve llm docs
  doc/source/serve/llm/serving-llms.rst
Labels: go

#51847 [Refactor][Core/Dashboard] Make `datacenter.py` a private implementation for NodeHead
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/node/datacenter.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/tests/test_head.py
Labels: go

#51862 [core] Fix ray id implicit fall through
  src/ray/common/id.cc
Labels: go

#51658 fix status codes on http proxy
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/test_metrics.py
Labels: go

#51795 add a card to the right side panel to promote community engagement an…
  doc/source/_static/css/custom.css
  doc/source/_templates/community-card.html
  doc/source/conf.py
Labels: go

#51866 [core] Remove deprecated boost asio io_service and work usage
  src/ray/common/asio/asio_util.h
  src/ray/common/asio/io_service_pool.cc
  src/ray/common/file_system_monitor.cc
  src/ray/common/test/memory_monitor_test.cc
  src/ray/common/test/syncer_service_e2e_test.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_client/test/gcs_client_reconnection_test.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_health_check_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_kv_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_worker_manager_test.cc
  src/ray/gcs/store_client/redis_store_client.cc
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/test/get_request_queue_test.cc
  src/ray/raylet/main.cc
  src/ray/raylet/runtime_env_agent_client_test.cc
  src/ray/raylet/worker_pool_test.cc
  src/ray/rpc/test/grpc_bench/grpc_bench.cc
  src/ray/rpc/test/grpc_server_client_test.cc
Labels: go

#51873 [core] Remove unused util function
  python/ray/_private/logging_utils.py
Labels: go

#51877 [Refactor][Core/Dashboard] Merge HealthzHead into APIHead
  python/ray/dashboard/modules/healthz/__init__.py
  python/ray/dashboard/modules/healthz/healthz_head.py
  python/ray/dashboard/modules/snapshot/healthz_agent.py
  python/ray/dashboard/modules/snapshot/snapshot_head.py
  python/ray/dashboard/modules/snapshot/tests/test_healthz.py
  python/ray/dashboard/modules/snapshot/utils.py
Labels: go

#51879 [ci] add tags for other tests
  .buildkite/others.rayci.yml
Labels: go

#51864 [core] Enable cgroup unit tests in CI
  .buildkite/core.rayci.yml
  src/ray/common/cgroup/test/BUILD
Labels: go

#51807 [Data] Fixing `to_stats` to avoid using `asdict`
  python/ray/data/block.py
Labels: go

#51857 [core] Add more compilation options for C++ hardening
  .bazelrc
  bazel/ray.bzl
Labels: go

#50624 [core][compiled graphs] Support reduce scatter and all gather collective for GPU communicator in compiled graph
  python/ray/dag/BUILD
  python/ray/dag/collective_node.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/tests/experimental/test_collective_dag.py
  python/ray/dag/tests/experimental/test_cpu_communicator_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/communicator.py
  python/ray/experimental/channel/cpu_communicator.py
  python/ray/experimental/channel/nccl_group.py
  python/ray/experimental/collective/__init__.py
  python/ray/experimental/collective/allreduce.py
  python/ray/experimental/collective/conftest.py
  python/ray/experimental/collective/operations.py
  python/ray/experimental/util/types.py
Labels: core, go

#51814 [core] replace :ray_common with sub-dependencies
  BUILD.bazel
  src/ray/gcs/gcs_client/test/gcs_client_reconnection_test.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/gcs_server/test/usage_stats_client_test.cc
Labels: core, go

#51920 [Chore][Core/Dashboard] Remove aiosignal and related classes
  ci/build/test-wheels.sh
  ci/env/install-core-prerelease-dependencies.sh
  doc/source/conf.py
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/node/datacenter.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/utils.py
  python/requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/setup.py
Labels: go

#51858 [core] Remove unused temp dir
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
Labels: go

#51271 [doc][kuberay]: add `kubectl ray get node` example
  doc/source/cluster/kubernetes/user-guides/kubectl-plugin.md
Labels: docs, core, go

#49035 [Jobs] Add metric to track duration of jobs
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: core, jobs, clusters, go

#51929 [core] Fix cgroup test on windows
  .buildkite/windows.rayci.yml
Labels: go

#51869 [core][dashboard-agent] Surface the root cause of job submission failure to users when the dashboard agent fails to launch HTTP server
  python/ray/dashboard/agent.py
  python/ray/dashboard/modules/job/job_head.py
Labels: go

#51825 [core] split plasma_store_server_lib into smaller targets
  BUILD.bazel
  src/ray/object_manager/plasma/eviction_policy.h
  src/ray/object_manager/plasma/malloc.h
  src/ray/object_manager/plasma/object_lifecycle_manager.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store_runner.cc
  src/ray/object_manager/plasma/store_runner.h
  src/ray/object_manager/plasma/test/stats_collector_test.cc
Labels: core, go

#51886 [Data] Remove lazy fixture
  python/ray/data/tests/test_arrow_serialization.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_hudi.py
  python/ray/data/tests/test_json.py
  python/ray/data/tests/test_lance.py
  python/ray/data/tests/test_metadata_provider.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_partitioning.py
  python/ray/tests/test_runtime_env_working_dir_3.py
  python/ray/tests/test_runtime_env_working_dir_4.py
  python/ray/tests/test_runtime_env_working_dir_remote_uri.py
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: data, go

#51936 [doc] Fix working_dir file size limit
  doc/source/ray-core/handling-dependencies.rst
Labels: go

#51922 [Data][minor] fix unclickable file link in ray data error msg
  python/ray/data/exceptions.py
Labels: data, go

#51926 [deps] Remove frozenlist dependency
  ci/build/test-wheels.sh
  ci/env/install-core-prerelease-dependencies.sh
  doc/source/conf.py
  python/ray/dashboard/utils.py
  python/requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu124.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu124.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu124.txt
  python/setup.py
Labels: go

#51938 [core] Rename plasma targets
  BUILD.bazel
Labels: go

#51932 [ci] Add support for monthly release tests
  release/ray_release/buildkite/settings.py
Labels: go

#44700 [RLlib] Fix invalid call of action_sampler_fn to support Keras 3
  rllib/policy/eager_tf_policy_v2.py
Labels: triage, rllib

#51928 [data] add min_rows_per_file to lance data sink
  python/ray/data/_internal/datasource/lance_datasink.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_lance.py
Labels: data, go

#51880 [Feat][Core/Dashboard] Move record_dashboard_metrics from MetricsHead to DashboardHead and convert MetricsHead to subprocess module
  python/ray/dashboard/consts.py
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/dashboard/modules/metrics/tests/test_utils.py
  python/ray/dashboard/subprocesses/handle.py
  python/ray/dashboard/subprocesses/module.py
  python/ray/dashboard/subprocesses/tests/test_e2e.py
  python/ray/dashboard/tests/test_dashboard.py
  python/ray/dashboard/utils.py
Labels: go

#51923 [data] deanonymize map operator tasks
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
Labels: go

#51621 [RLlib] Correct the error message for invalid env registering.
  rllib/utils/error.py
Labels: rllib, go

#51961 [Data] Adding in missing emitting of metrics to prometheus
  python/ray/data/_internal/stats.py
Labels: go

#51816 [RLlib] Update algorithms source.
  rllib/algorithms/cql/README.md
  rllib/algorithms/sac/README.md
  rllib/tuned_examples/sac/atari-sac.yaml
  rllib/tuned_examples/sac/mspacman-sac.yaml
Labels: rllib, go

#51684 [docs] Tune toc
  doc/source/tune/examples/exercises.rst
  doc/source/tune/examples/experiment-tracking.rst
  doc/source/tune/examples/hpo-frameworks.rst
  doc/source/tune/examples/index.rst
  doc/source/tune/examples/ml-frameworks.rst
  doc/source/tune/examples/other-examples.rst
  doc/source/tune/examples/tune_analyze_results.ipynb
  doc/source/tune/getting-started.rst
  doc/source/tune/key-concepts.rst
  doc/source/tune/tutorials/overview.rst
Labels: docs, go

#51948 [core] Move the core worker client implementations to a separate .cc file to improve build time.
  BUILD.bazel
  src/ray/rpc/worker/core_worker_client.cc
  src/ray/rpc/worker/core_worker_client.h
Labels: go

#51954 [core][autoscaler] Don't error if rayStartParams absent
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/tests/kuberay/test_autoscaling_e2e.py
Labels: core, go

#51955 [core][autoscaler] fix Pylance type warning
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
Labels: core, go

#51616 [core] grpc stub manager
  BUILD.bazel
  src/ray/object_manager/grpc_stub_manager.h
  src/ray/rpc/object_manager/object_manager_client.h
Labels: go

#51952 [Core] Use structured binding for better readability
  src/ray/gcs/gcs_server/gcs_job_manager.cc
Labels: core, go

#51876 [Feat][Core/Dashboard] Convert NodeHead to subprocess module
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/utils.py
Labels: go

#51787 [Fix][Core/Dashboard] Remove `format=leading_1` query string from `get_logs` in StateHead
  python/ray/dashboard/client/src/pages/job/JobDriverLogs.component.test.tsx
  python/ray/dashboard/client/src/service/log.ts
  python/ray/dashboard/client/src/service/log.unit.test.ts
  python/ray/dashboard/modules/state/state_head.py
  python/ray/util/state/api.py
Labels: go

#51941 [core] Correctly spill up to max_fused_object_count
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
Labels: go

#40176 [docs] [train] copy edits to E2E ingest example
  doc/source/_toc.yml
  doc/source/ray-air/examples/training_ingest_object_classification.ipynb
Labels: docs, train

#51828 [core] split plasma_client into smaller targets
  BUILD.bazel
  src/ray/object_manager/plasma/client.cc
Labels: core, go, community-contribution

#51990 [image] update manual docker build script
  .buildkite/build.rayci.yml
  build-docker.sh
  ci/pipeline/test_rules.txt
Labels: go

#51995 [deps] remove soft fail in pip requirements compile
  .buildkite/others.rayci.yml
  python/requirements_compiled.txt
Labels: go

#51963 [Data] Clarify `concurrency` semantics in API reference
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
Labels: go

#51937 [core] Add precondition check for cgroup subtree controller
  src/ray/common/cgroup/cgroup_setup.cc
  src/ray/common/cgroup/cgroup_setup.h
  src/ray/common/cgroup/constants.h
  src/ray/common/cgroup/test/cgroup_v2_utils_privileged_test.cc
Labels: core, go

#51706 Update `--labels` and add `--labels-file` options for Label Selector API
  java/test/src/main/java/io/ray/test/NodeLabelSchedulingTest.java
  python/ray/_private/label_utils.py
  python/ray/_private/parameter.py
  python/ray/_private/utils.py
  python/ray/scripts/scripts.py
  python/ray/tests/BUILD
  python/ray/tests/test_label_utils.py
  python/ray/tests/test_node_label_scheduling_strategy.py
  python/ray/tests/test_node_labels.py
  python/ray/tests/test_utils.py
Labels: core, go, community-contribution

#51970 [data] correct name of map operator submit task
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/tests/test_dynamic_block_split.py
Labels: go

#52001 [core] Fix windows compilation
  src/ray/common/cgroup/cgroup_setup.cc
Labels: go

#52002 [serve] catch timeout error when checking if proxy is dead
  python/ray/serve/_private/proxy_state.py
Labels: go

#51997 [image] upgrade cuda 12.8.0 to cuda 12.8.1
  .buildkite/_forge.rayci.yml
  .buildkite/build.rayci.yml
  .buildkite/linux_aarch64.rayci.yml
  ci/ray_ci/docker_container.py
  ci/ray_ci/test_ray_docker_container.py
Labels: go

#51076 [data] Make Dataset.name/set_name public
  python/ray/dashboard/modules/data/tests/test_data_head.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_stats.py
Labels: data, go

#51989 [Serve][LLM] Fix ServeReplica deployment failure for DeepSeek
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
Labels: go

#51992 [Fix][Core/Dashboard] Fix wrong endpoints in metrics
  python/ray/dashboard/subprocesses/routes.py
Labels: go

#51893 [core] Add validation for redirection filepath
  src/ray/util/BUILD
  src/ray/util/internal/stream_redirection_handle.cc
  src/ray/util/internal/stream_redirection_handle.h
  src/ray/util/stream_redirection.cc
Labels: core, go

#51975 [Chore][Autoscaler] Improve resource demand scheduler documentation
  python/ray/autoscaler/_private/resource_demand_scheduler.py
Labels: core, go, community-contribution

#51980 [Feat][Core/Dashboard Convert TrainHead to subprocess module
  python/ray/dashboard/modules/train/train_head.py
  python/ray/dashboard/subprocesses/handle.py
  python/ray/dashboard/subprocesses/utils.py
Labels: go

#46344 [data] Enable RAY_DATA_ENABLE_TENSOR_EXTENSION_CASTING environment variable
  python/ray/data/context.py
Labels: data, go, community-contribution

#51906 [Core] Split `core_worker` into smaller targets to improve build performance
  BUILD.bazel
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/task_finisher.h
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/transport/dependency_resolver.h
  src/ray/core_worker/transport/scheduling_util.cc
  src/ray/core_worker/transport/task_receiver.h
Labels: enhancement, core, go, community-contribution

#52006 [core] Place scheduler bazel targets into separate directories
  BUILD.bazel
  src/ray/raylet/scheduling/BUILD.bazel
  src/ray/raylet/scheduling/cluster_resource_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/local_resource_manager.h
  src/ray/raylet/scheduling/local_task_manager_interface.h
Labels: go

#51994 [Core] Cover cpplint for ray/src/ray/common/cgroup
  src/ray/common/cgroup/cgroup_setup.cc
  src/ray/common/cgroup/fake_cgroup_setup.cc
  src/ray/common/cgroup/fake_cgroup_setup.h
  src/ray/common/cgroup/scoped_cgroup_handle.h
Labels: core, go

#52011 [core] Remove unused macro
  src/ray/raylet/main.cc
Labels: go

#52009 [core] Fix and optimize dependency
  src/ray/util/BUILD
  src/ray/util/tests/BUILD
  src/ray/util/tests/filesystem_monitor_test.cc
  src/ray/util/tests/filesystem_test.cc
  src/ray/util/tests/sample_test.cc
Labels: go

#52034 [CI] Increase the timeout of `test_basic.py` to avoid flakiness
  python/ray/tests/BUILD
Labels: go

#52035 [chore][core] Remove unnecessary anonymous namespace
  src/ray/core_worker/reference_count.cc
Labels: go

#52020 [core] Patch zlib and clang 17 compliant for mac update
  .bazelrc
  bazel/ray.bzl
  bazel/ray_deps_setup.bzl
  src/ray/core_worker/core_worker.h
  thirdparty/patches/grpc-zlib-fdopen.patch
  thirdparty/patches/prometheus-zlib-fdopen.patch
  thirdparty/patches/zlib-fdopen.patch
Labels: go

#51993 [ci] Add monthly release test frequency to schema
  release/ray_release/schema.json
Labels: go

#52037 [Serve][LLM] Check GPUType enum value rather than enum itself
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
Labels: go

#52000 Ray Train Test: Add locality_with_output, actor_locality_enabled option
  release/train_tests/benchmark/config.py
  release/train_tests/benchmark/train_benchmark.py
Labels: go

#52045 [Fix][Core/Dashboard] Don't create `__init__.py` dynamically in tests
  python/ray/dashboard/modules/tests/__init__.py
  python/ray/dashboard/tests/conftest.py
Labels: go

#52024 [Data] Remove empty `plan_from_xxx_op.py` files
  python/ray/data/_internal/planner/plan_from_arrow_op.py
  python/ray/data/_internal/planner/plan_from_items_op.py
  python/ray/data/_internal/planner/plan_from_numpy_op.py
  python/ray/data/_internal/planner/plan_from_pandas_op.py
Labels: go

#52056 [Data] Fix bug where `_resolve_paths_and_filesystem` strips protocol from HTTP paths
  python/ray/data/BUILD
  python/ray/data/datasource/path_util.py
  python/ray/data/tests/test_file_based_datasource.py
  python/ray/data/tests/test_path_util.py
Labels: go

#52023 [Data] Remove dead `input_data_factory` parameter of `InputData` operator
  python/ray/data/_internal/logical/operators/input_data_operator.py
  python/ray/data/_internal/planner/planner.py
Labels: go

#52054 [Serve][LLM] Update model_source doc
  doc/source/serve/llm/serving-llms.rst
  python/ray/llm/_internal/serve/configs/server_models.py
Labels: go

#52063 [Core] Revert "Update `--labels` and add `--labels-file` options for Label Selector API (#51706)
  java/test/src/main/java/io/ray/test/NodeLabelSchedulingTest.java
  python/ray/_private/label_utils.py
  python/ray/_private/parameter.py
  python/ray/_private/utils.py
  python/ray/scripts/scripts.py
  python/ray/tests/BUILD
  python/ray/tests/test_label_utils.py
  python/ray/tests/test_node_label_scheduling_strategy.py
  python/ray/tests/test_node_labels.py
  python/ray/tests/test_utils.py
Labels: go

#51943 [Data] Cleaning up `find_partitions` method
  python/ray/data/BUILD
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/table_block.py
  python/ray/data/_internal/util.py
  python/ray/data/block.py
  python/ray/data/tests/test_block.py
  python/ray/data/tests/test_util.py
Labels: go

#52064 [Data] Increase size of `test_hudi`
  python/ray/data/BUILD
Labels: go

#51756 [Test][KubeRay] Add doctest for RayJob Quickstart doc
  ci/k8s/run-kuberay-doc-tests.sh
  doc/source/cluster/kubernetes/doc_sanitize.cfg
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.ipynb
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
Labels: core, go, community-contribution

#52082 [docs/minor] Update Ray Data docs
  doc/source/data/api/from_other_data_libs.rst
  doc/source/data/comparisons.rst
Labels: go

#47360 Remove unnecessary string literal splits
  ci/lint/clang-tidy-diff.py
  ci/repro-ci.py
  doc/source/cluster/doc_code/slurm-launch.py
  doc/source/preprocess_github_markdown.py
  python/ray/dag/tests/experimental/test_mocked_nccl_dag.py
  python/ray/dag/vis_utils.py
  python/ray/dashboard/http_server_head.py
  python/ray/dashboard/modules/event/event_utils.py
  python/ray/dashboard/modules/job/pydantic_models.py
  python/ray/dashboard/modules/job/tests/test_job_manager.py
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_consumption.py
  python/ray/runtime_context.py
  python/ray/serve/_private/utils.py
  python/ray/serve/tests/test_logging.py
  python/ray/serve/tests/test_request_timeout.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/tests/chaos/potato_passer.py
  python/ray/tests/conftest_docker.py
  python/ray/tests/kuberay/utils.py
  python/ray/tests/test_actor_cancel.py
  python/ray/tests/test_autoscaler.py
  python/ray/tests/test_batch_node_provider_integration.py
  python/ray/tests/test_placement_group_5.py
  python/ray/tests/test_resource_demand_scheduler.py
  python/ray/tests/test_state_api.py
  python/ray/train/_internal/backend_executor.py
  python/ray/train/tests/test_datasets_train.py
  python/ray/tune/tests/test_stopper.py
  release/util/sanity_check.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/sac/sac.py
  rllib/env/tcp_client_inference_env_runner.py
  rllib/examples/_old_api_stack/connectors/self_play_with_policy_checkpoint.py
  rllib/execution/train_ops.py
  rllib/models/catalog.py
  rllib/policy/sample_batch.py
  rllib/utils/torch_utils.py
Labels: P2, dashboard, serve, @external-author-action-required, train, core, data, go, community-contribution

#52038 [core][cgraph] Updated GPU test skipping
  python/ray/dag/BUILD
  python/ray/dag/tests/experimental/test_execution_schedule_gpu.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
Labels: go

#51859 [RLlib] Meta-learning, differentiable learner.
  rllib/algorithms/algorithm_config.py
  rllib/core/learner/differentiable_learner.py
  rllib/core/learner/differentiable_learner_config.py
  rllib/core/learner/learner.py
  rllib/core/learner/torch/torch_differentiable_learner.py
  rllib/core/learner/torch/torch_meta_learner.py
  rllib/core/rl_module/apis/self_supervised_loss_api.py
  rllib/examples/learners/classes/maml_lr_differentiable_learner.py
  rllib/examples/learners/classes/maml_lr_differentiable_rlm.py
  rllib/examples/learners/classes/maml_lr_meta_learner.py
  rllib/examples/learners/maml_lr_supervised_learning.py
  rllib/utils/metrics/__init__.py
  rllib/utils/typing.py
Labels: go

#52092 [Fix][Test] Fix flaky test `test_prometheus_physical_stats_record`
  python/ray/dashboard/modules/reporter/tests/test_reporter.py
Labels: go

#52047 [Fix][Core/Dashboard] Log to stderr for subprocess modules when `RAY_LOG_TO_STDERR` is set
  doc/source/ray-observability/user-guides/configure-logging.md
  python/ray/dashboard/subprocesses/module.py
  python/ray/dashboard/subprocesses/tests/test_e2e.py
  python/ray/dashboard/subprocesses/utils.py
Labels: go

#51371 [RLlib] Throw better error if catalog can not be created for Atari environments, help atari users
  rllib/core/models/tests/test_catalog.py
  rllib/core/rl_module/rl_module.py
  rllib/examples/rl_modules/classes/mobilenet_rlm.py
  rllib/models/utils.py
Labels: rllib, go

#52068 fix flaky test test_locality_aware_backoff_skips_sleeps
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
Labels: go

#52060 Fix stacking metrics looking broken when there are null values
  python/ray/dashboard/modules/metrics/grafana_dashboard_factory.py
Labels: go

#52031 [core] split bazel target stats into another folder
  BUILD.bazel
  src/ray/common/BUILD
  src/ray/raylet/scheduling/BUILD.bazel
  src/ray/stats/BUILD.bazel
  src/ray/stats/tests/BUILD
Labels: core, go, community-contribution

#51918 [Chore][Core/Dashboard] Split the implementation of ServeHead and ServeAgent
  python/ray/dashboard/modules/serve/serve_agent.py
  python/ray/dashboard/modules/serve/serve_head.py
  python/ray/dashboard/modules/serve/serve_rest_api_impl.py
Labels: go

#52097 [data] optimize RefBundle.get_cached_location
  python/ray/data/_internal/execution/interfaces/ref_bundle.py
Labels: go

#52105 [llm] trigger llm tests on llm doc changes
  ci/pipeline/test_rules.txt
Labels: go

#52086 [core] Replace `absl::optional` with `std::optional`
  src/mock/ray/core_worker/reference_count.h
  src/mock/ray/core_worker/task_manager.h
  src/ray/common/bundle_location_index.cc
  src/ray/common/bundle_location_index.h
  src/ray/common/event_stats.cc
  src/ray/common/event_stats.h
  src/ray/common/scheduling/cluster_resource_data.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/actor_handle.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/lease_policy.cc
  src/ray/core_worker/lease_policy.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/task_event_buffer.cc
  src/ray/core_worker/task_event_buffer.h
  src/ray/core_worker/task_finisher.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/lease_policy_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/test/reference_count_test.cc
  src/ray/core_worker/test/task_event_buffer_export_event_test.cc
  src/ray/core_worker/test/task_event_buffer_test.cc
  src/ray/core_worker/transport/actor_submit_queue.h
  src/ray/core_worker/transport/normal_task_submitter.h
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.h
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.h
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc
  src/ray/gcs/gcs_server/gcs_placement_group_scheduler.h
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/test/gcs_task_manager_test.cc
  src/ray/gcs/pb_util.h
  src/ray/object_manager/chunk_object_reader.cc
  src/ray/object_manager/chunk_object_reader.h
  src/ray/object_manager/plasma/allocator.h
  src/ray/object_manager/plasma/plasma_allocator.cc
  src/ray/object_manager/plasma/plasma_allocator.h
  src/ray/object_manager/plasma/test/eviction_policy_test.cc
  src/ray/object_manager/plasma/test/object_store_test.cc
  src/ray/object_manager/plasma/test/stats_collector_test.cc
  src/ray/object_manager/spilled_object_reader.cc
  src/ray/object_manager/spilled_object_reader.h
  src/ray/pubsub/subscriber.h
  src/ray/raylet/scheduling/local_resource_manager.cc
  src/ray/raylet/scheduling/local_resource_manager.h
  src/ray/raylet/scheduling/policy/scheduling_context.h
Labels: go

#52100 [ci] drop `RAYCI_FULL_PLATFORM_RELEASE`
  .buildkite/release-automation/pre_release.rayci.yml
  ci/pipeline/test_rules.txt
Labels: go

#52096 [gcs] remove async-timeout dependency in gcs utils test on python 3.11+
  python/ray/tests/test_gcs_utils.py
Labels: go

#52101 [ci] upgrade anyscale cli
  release/requirements_buildkite.in
  release/requirements_buildkite.txt
Labels: go

#52108 [ray release] remove champagne building
  release/ray_release/scripts/ray_champagne.py
Labels: go

#52059 [data] improve dataset name observability
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/iterator/iterator_impl.py
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/_internal/plan.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_stats.py
  python/ray/train/_internal/data_config.py
  python/ray/train/tests/test_state.py
Labels: go

#51741 [Core] Runtime env working_dir validation #51380
  python/ray/_private/runtime_env/packaging.py
  python/ray/dashboard/agent.py
  python/ray/tests/test_runtime_env_packaging.py
Labels: core, go, community-contribution

#51904 [core] Avoid resubmitted actor tasks from hanging indefinitely
  doc/source/ray-core/actors/task-orders.rst
  python/ray/tests/test_actor_failures.py
  python/ray/tests/test_failure.py
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/rpc/worker/core_worker_client.cc
  src/ray/rpc/worker/core_worker_client.h
Labels: go

#52084 [ray.data.llm] Add retries and exponential backoff to `HTTPRequestStage`
  python/ray/llm/_internal/batch/processor/http_request_proc.py
  python/ray/llm/_internal/batch/stages/http_request_stage.py
  python/ray/llm/tests/batch/cpu/stages/test_http_request_stage.py
Labels: go

#52115 [ci] mark pip compile as softfail
  .buildkite/others.rayci.yml
Labels: go

#52104 [ray.data.llm] s/model/model_source for vLLMEngineProcessorConfig
  doc/source/llm/examples/batch/vllm-with-lora.ipynb
Labels: go

#52111 [doc] update clang-format link
  doc/source/ray-contribute/getting-involved.rst
Labels: go

#52109 [dashboard] fix another asyncio timeout import issue
  python/ray/dashboard/modules/tests/test_utils.py
Labels: go

#52106 [Data] Implement `__repr__` for `RetryingPyFileSystem`
  python/ray/data/_internal/util.py
Labels: data, go

#52107 [RLlib; Offline RL] Add configuration parameter `ignore_final_observation` and automatic episode ID generation.
  rllib/algorithms/algorithm_config.py
  rllib/offline/offline_prelearner.py
  rllib/offline/tests/test_offline_prelearner.py
Labels: go

#52134 [Core] Disable dashboard log rotation for windows
  python/ray/dashboard/dashboard.py
Labels: go

#52168 [deps] install wheel before pip-compile
  .buildkite/others.rayci.yml
  ci/ci.sh
Labels: go

#52170 [FIX] RayJob doc test flaky
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.ipynb
Labels: go

#52122 remove model multiplexing experimental feature documentation
  doc/source/serve/model-multiplexing.md
Labels: go

#52178 [train] change `test_telemetry` to medium size
  python/ray/train/BUILD
Labels: go

#52182 [data] increate `test_batcher` test size to medium
  python/ray/data/BUILD
Labels: go

#52127 [dashboard] pin cypress version
  python/ray/dashboard/tests/run_ui_tests.sh
Labels: go

#52183 [Data] Bump timeout on `test_tf`
  python/ray/data/BUILD
Labels: go

#52052 support user config for local testing mode
  python/ray/serve/_private/local_testing_mode.py
  python/ray/serve/tests/unit/test_local_testing_mode.py
Labels: go

#52120 [train] Add worker group setup finished log
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
Labels: go

#51265 [Train V2] Fold `v2.LightGBMTrainer` API into the public trainer class as an alternate constructor
  python/ray/train/lightgbm/lightgbm_trainer.py
  python/ray/train/lightgbm/v2.py
  python/ray/train/tests/test_lightgbm_trainer.py
  python/ray/train/v2/lightgbm/lightgbm_trainer.py
  release/train_tests/xgboost_lightgbm/train_batch_inference_benchmark.py
Labels: go

#52185 [Serve][LLM] Fix inconsistent v0/v1 config passed to vLLM
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
Labels: go

#52112 [Data] Replace `BlockAccessor.append_column` with `BlockAccessor.fill_column`
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/table_block.py
  python/ray/data/datasource/file_based_datasource.py
  python/ray/data/tests/test_arrow_block.py
  python/ray/data/tests/test_pandas_block.py
Labels: go

#52184 [Data] Increase size of `test_telemetry`
  python/ray/data/BUILD
Labels: go

#52190 [deps] upgrade wheel package to >= 0.45.1
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#52197 [core][cgraph] Fix cgraph viz link
  doc/source/ray-core/ray-dag.rst
Labels: go

#52186 [docs,serve][minor] fix incorrect indentation in ray serve Deployment docs
  python/ray/serve/deployment.py
Labels: serve, docs, go

#52173 [Fix][Core/Runtime] Revert PR 48552 and add validation for conda env folder path
  python/ray/_private/runtime_env/conda.py
  python/ray/_private/runtime_env/conda_utils.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
Labels: go

#52121 [core] Use a signal actor instead of sleep to avoid flakiness in extreme cases
  python/ray/tests/test_actor_failures.py
Labels: go

#52153 [core][refactor] Remove update_seqno
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/task_manager_test.cc
Labels: go

#52110 [data] doc: fix lancedb api doc links
  python/ray/data/read_api.py
Labels: go

#52181 [doc] link fix: pandas-modin link moved
  doc/source/ray-overview/getting-started.md
Labels: go

#52196 [release test] update release test byod deps
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu124.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu124.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu124.txt
  release/ray_release/byod/requirements_byod_3.9.txt
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: go

#52203 [serve] Update engine kwargs in lora instructions
  doc/source/serve/llm/serving-llms.rst
Labels: go

#52199 [core] Drop batch size based on getrecursionlimit on actor concurrency test
  python/ray/tests/test_asyncio.py
Labels: go

#52025 [Core] Rename dashboard agent out and err log files
  doc/source/ray-observability/user-guides/configure-logging.md
  python/ray/_private/log_monitor.py
  python/ray/_private/node.py
  python/ray/_private/runtime_env/agent/main.py
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/services.py
  python/ray/dashboard/agent.py
  python/ray/dashboard/subprocesses/module.py
  python/ray/tests/test_logging.py
  src/ray/raylet/agent_manager.h
  src/ray/raylet/node_manager.cc
Labels: go

#52187 [data] fix context inheritance for materialized datasets and iterators
  python/ray/data/_internal/iterator/iterator_impl.py
  python/ray/data/_internal/iterator/stream_split_iterator.py
  python/ray/data/_internal/plan.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_context_propagation.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_split.py
  python/ray/data/tests/test_splitblocks.py
Labels: go

#52171 Fix compatibility with GCP IAM conditions
  python/ray/autoscaler/_private/gcp/config.py
Labels: core, go, community-contribution

#52123 [Core] Place bazel targets into separate directories (gcs_server)
  BUILD.bazel
  src/ray/gcs/gcs_server/BUILD.bazel
  src/ray/gcs/gcs_server/test/BUILD.bazel
Labels: core, go, community-contribution

#52046 [core][autoscaler] test providers exist with defaults
  python/ray/autoscaler/_private/providers.py
  python/ray/tests/BUILD
  python/ray/tests/autoscaler/test_providers.py
Labels: core, go, community-contribution

#52216 [core] Print info on dashboard assertion failure
  python/ray/dashboard/modules/node/node_head.py
Labels: go

#52205 [Core] Add grpc code to the RpcError status ToString
  .buildkite/build.rayci.yml
  src/ray/common/status.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/task_event_buffer.cc
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/object_manager/object_manager.cc
  src/ray/raylet/node_manager.cc
Labels: go

#52114 [Feat][Core/Dashboard] Convert ServeHead to subprocess module
  python/ray/dashboard/modules/serve/serve_head.py
Labels: go

#51998 [core] min_spilling_size cleanup
  src/ray/common/ray_config_def.h
  src/ray/raylet/local_object_manager.cc
  src/ray/raylet/local_object_manager.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/test/local_object_manager_test.cc
Labels: go

#51004 [docs][observability] Improvements to General Debugging guide
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/ray-observability/user-guides/debug-apps/general-debugging.rst
Labels: docs, observability, go

#52209 [Core] Cover cpplint for ray/src/ray/common/asio
  src/ray/common/asio/asio_chaos.cc
  src/ray/common/asio/asio_util.h
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/asio/instrumented_io_context.h
  src/ray/common/asio/io_service_pool.h
  src/ray/common/asio/periodical_runner.cc
  src/ray/common/asio/periodical_runner.h
  src/ray/common/asio/postable.h
Labels: go, community-contribution

#52220 Remove BUILDKITE_TOKEN env var path
  release/release_logs/fetch_release_logs.py
Labels: go

#51996 [Core] Minor improvements to asio and rpc chaos framework
  BUILD.bazel
  src/ray/common/asio/asio_chaos.cc
  src/ray/common/asio/asio_chaos.h
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/test/asio_defer_test.cc
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/rpc/client_call.h
  src/ray/rpc/grpc_client.h
  src/ray/rpc/rpc_chaos.cc
  src/ray/rpc/rpc_chaos.h
  src/ray/rpc/server_call.h
  src/ray/rpc/test/rpc_chaos_test.cc
  src/ray/util/BUILD
  src/ray/util/logging.cc
  src/ray/util/tests/BUILD
Labels: go

#52217 [core] Obj store not idle log down to debug
  src/ray/raylet/scheduling/local_resource_manager.cc
Labels: go

#52207 [core][autoscaler] bump autoscaler_state_version in a fake request to deflay the test
  python/ray/autoscaler/v2/tests/test_sdk.py
Labels: go

#52016 [core] Place plasma bazel targets into separate directories
  BUILD.bazel
  bazel/ray.bzl
  src/ray/object_manager/plasma/BUILD.bazel
  src/ray/object_manager/plasma/test/BUILD.bazel
  src/ray/object_manager/plasma/test/mutable_object_test.cc
  src/ray/object_manager/plasma/test/object_lifecycle_manager_test.cc
Labels: core, go, community-contribution
