Repository ray-project/ray, pull requests merged in 2025-06, with the labels that each got.

#53196 setup-dev.py: fix invalid '-r' option in mv command
  python/ray/setup-dev.py
Labels: go

#53389 [core] Remove unused `on_worker_shutdown` callback from the core worker
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
Labels: core, go

#53305 [core] test_advanced_9 speedup
  python/ray/tests/test_advanced.py
  python/ray/tests/test_advanced_9.py
Labels: go

#53403 [docs][kuberay] update autoscaling guide
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.ipynb
  python/ray/tests/kuberay/test_files/ray-cluster.autoscaler-v2-template.yaml
Labels: go

#53303 [Doc][KuberRay] add doc for kuberay with uv
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/uv.md
Labels: go

#53434 Fix lingering socket issue in tests by replacing requests with httpx
  ci/docker/min.build.Dockerfile
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_advanced.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/test_backpressure.py
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/test_callback.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_cli_2.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_controller_recovery.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_2.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_enable_task_events.py
  python/ray/serve/tests/test_failure.py
  python/ray/serve/tests/test_fastapi.py
  python/ray/serve/tests/test_gcs_failure.py
  python/ray/serve/tests/test_gradio.py
  python/ray/serve/tests/test_http_cancellation.py
  python/ray/serve/tests/test_http_headers.py
  python/ray/serve/tests/test_http_routes.py
  python/ray/serve/tests/test_logging.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_model_composition.py
  python/ray/serve/tests/test_multiplex.py
  python/ray/serve/tests/test_ray_client.py
  python/ray/serve/tests/test_regression.py
  python/ray/serve/tests/test_replica_request_context.py
  python/ray/serve/tests/test_replica_sync_methods.py
  python/ray/serve/tests/test_request_timeout.py
  python/ray/serve/tests/test_runtime_env_2.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/test_standalone_2.py
  python/ray/serve/tests/test_standalone_3.py
  python/ray/serve/tests/test_streaming_response.py
  python/ray/serve/tests/test_telemetry_1.py
  python/ray/serve/tests/test_websockets.py
Labels: go

#53487 Fix iter_rows involving _get_max_chunk_size
  python/ray/data/_internal/arrow_block.py
Labels: go

#43184 [docs] Add antipattern for nested ray.get
  doc/source/ray-core/doc_code/anti_pattern_nested_ray_get.py
  doc/source/ray-core/patterns/index.rst
  doc/source/ray-core/patterns/nested-ray-get.rst
  doc/source/ray-core/patterns/nested-tasks.rst
  doc/source/ray-core/patterns/ray-get-loop.rst
  doc/source/ray-core/patterns/ray-get-too-many-objects.rst
Labels: stale, go

#53491 [Data] Remove assertion that actors with infinite retries can't be dead
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
Labels: go

#53507 [min test] install pytest more generally
  ci/docker/min.build.Dockerfile
Labels: go

#40779 [core] Fix windows conda activate with conda.bat as executable in conda path
  python/ray/_private/runtime_env/conda_utils.py
Labels: P1, windows, QS, core, go, community-contribution

#53340 [serve.llm][test] add type annotation for probes/models.py
  release/llm_tests/serve/probes/models.py
Labels: go

#53484 [RLlib] Resolve numerical instabilities in `MeanStdFilter`.
  rllib/utils/filter.py
Labels: go

#51890 [Serve] Add helpers to rank replicas with multiplex and locality
  python/ray/serve/_private/request_router/request_router.py
  python/ray/serve/tests/unit/test_pow_2_request_router.py
Labels: go

#53355 [Serve] Implement recording routing stats periodically
  ci/lint/pydoclint-baseline.txt
  java/serve/src/main/java/io/ray/serve/common/Constants.java
  java/serve/src/main/java/io/ray/serve/config/DeploymentConfig.java
  python/ray/serve/_private/client.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/config.py
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/request_router/replica_wrapper.py
  python/ray/serve/api.py
  python/ray/serve/deployment.py
  python/ray/serve/multiplex.py
  python/ray/serve/schema.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_controller.py
  python/ray/serve/tests/test_multiplex.py
  python/ray/serve/tests/test_record_routing_stats.py
  python/ray/serve/tests/unit/test_deployment_state.py
  src/ray/protobuf/serve.proto
Labels: go

#53534 [core] Revert error log when gcs kills actors
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
Labels: go

#53528 Replace ``miniconda3`` with ``miniforge`` for linux
  .buildkite/release-automation/forge_arm64.Dockerfile
  .buildkite/release-automation/forge_x86_64.Dockerfile
  .buildkite/release-automation/verify-linux-wheels.sh
  ci/docker/base.gpu.Dockerfile
  ci/docker/base.gpu.py39.wanda.yaml
  ci/docker/base.gpu.wanda.yaml
  ci/docker/base.test.Dockerfile
  ci/docker/base.test.aarch64.wanda.yaml
  ci/docker/base.test.py39.wanda.yaml
  ci/docker/base.test.wanda.yaml
  ci/env/install-dependencies.sh
  ci/env/install-miniforge.sh
Labels: go

#53553 Ray serve/lora doc fix
  doc/source/serve/llm/serving-llms.rst
Labels: go

#52733 [CI] Re-enable isort for python/ray/tune
  .pre-commit-config.yaml
  pyproject.toml
  python/ray/tune/analysis/experiment_analysis.py
  python/ray/tune/context.py
  python/ray/tune/examples/async_hyperband_example.py
  python/ray/tune/examples/pbt_transformers/pbt_transformers.py
  python/ray/tune/execution/class_cache.py
  python/ray/tune/execution/tune_controller.py
  python/ray/tune/experiment/experiment.py
  python/ray/tune/experiment/trial.py
  python/ray/tune/impl/config.py
  python/ray/tune/impl/tuner_internal.py
  python/ray/tune/integration/ray_train.py
  python/ray/tune/schedulers/pbt.py
  python/ray/tune/search/optuna/optuna_search.py
  python/ray/tune/syncer.py
  python/ray/tune/tests/conftest.py
  python/ray/tune/tests/execution/test_controller_checkpointing_integration.py
  python/ray/tune/tests/execution/test_controller_errors_integration.py
  python/ray/tune/tests/execution/test_controller_resume_integration.py
  python/ray/tune/tests/test_actor_reuse.py
  python/ray/tune/tests/test_api.py
  python/ray/tune/tests/test_api_checkpoint_integration.py
  python/ray/tune/tests/test_cluster.py
  python/ray/tune/tests/test_experiment.py
  python/ray/tune/tests/test_function_api.py
  python/ray/tune/tests/test_result_grid.py
  python/ray/tune/tests/test_run_experiment.py
  python/ray/tune/tests/test_telemetry.py
  python/ray/tune/tests/test_train_v2_integration.py
  python/ray/tune/tests/test_trial.py
  python/ray/tune/tests/test_trial_scheduler.py
  python/ray/tune/tests/test_trial_scheduler_pbt.py
  python/ray/tune/tests/test_tune_restore.py
  python/ray/tune/tests/test_tune_save_restore.py
  python/ray/tune/tests/test_tuner.py
  python/ray/tune/tests/test_tuner_restore.py
  python/ray/tune/tests/test_utils.py
  python/ray/tune/trainable/trainable_fn_utils.py
  python/ray/tune/tune.py
Labels: go

#53557 [core] Update very old doc message
  doc/source/ray-core/examples/monte_carlo_pi.rst
  doc/source/ray-core/walkthrough.rst
Labels: go

#53178 [core] Refactor actor method binding with `ActorMethodShell` and remove weakrefs
  python/ray/actor.py
  python/ray/dag/tests/test_output_node.py
  python/ray/data/tests/test_operators.py
  python/ray/tests/test_actor.py
  python/ray/tests/test_actor_failures.py
  python/ray/util/tracing/tracing_helper.py
Labels: go

#53544 [Core] Upgrade vendored setproctitle to 1.3.6
  ci/env/install-dependencies.sh
  python/requirements_compiled.txt
  python/setup.py
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: go

#53527 make $100 banner dismissable
  doc/source/_static/css/dismissable-banner.css
  doc/source/_static/js/dismissable-banner.js
  doc/source/conf.py
Labels: go

#53584 [core] Speed up and deflake `test_output.py`
  python/ray/tests/test_output.py
Labels: go

#53585 [core] Minor speedups in `test_failure.py`
  python/ray/tests/test_failure.py
Labels: go

#53587 [core] Skip `test_reference_counting_2.py::test_recursively_pass_returned_object_ref` on Windows
  python/ray/tests/test_reference_counting_2.py
Labels: go

#53547 Fix broken link in documentation
  doc/source/cluster/faq.rst
Labels: go

#53565 [Docs] Fix xgboost anyscale job submission
  doc/source/ray-overview/examples/e2e-audio/ci/tests.sh
  doc/source/ray-overview/examples/e2e-xgboost/README.ipynb
  doc/source/ray-overview/examples/e2e-xgboost/notebooks/01-Distributed_Training.ipynb
Labels: docs, go

#53593 Revert "[Core] Upgrade vendored setproctitle to 1.3.6 (#53544)"
  ci/env/install-dependencies.sh
  python/requirements_compiled.txt
  python/setup.py
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: go

#53231 [core][telemetry/06] record gauge metric e2e
  .buildkite/core.rayci.yml
  python/ray/dashboard/modules/reporter/reporter_agent.py
  python/ray/tests/test_metrics_agent.py
  src/ray/stats/BUILD.bazel
  src/ray/stats/metric.h
  src/ray/stats/tests/BUILD
  src/ray/stats/tests/metric_with_open_telemetry_test.cc
  src/ray/telemetry/open_telemetry_metric_recorder.cc
  src/ray/telemetry/open_telemetry_metric_recorder.h
Labels: go

#53511 [Serve][Doc] Add custom request router docs
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  doc/source/serve/advanced-guides/custom-request-router.md
  doc/source/serve/advanced-guides/index.md
  doc/source/serve/api/index.md
  doc/source/serve/doc_code/custom_request_router.py
  doc/source/serve/doc_code/custom_request_router_app.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/request_router/common.py
  python/ray/serve/_private/request_router/replica_wrapper.py
  python/ray/serve/_private/request_router/request_router.py
  python/ray/serve/_private/router.py
  python/ray/serve/tests/unit/test_pow_2_request_router.py
  python/ray/serve/tests/unit/test_router.py
Labels: go

#53616 [core] Shorten test name too long on Windows
  python/ray/tests/BUILD
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_runtime_env_working_dir_uri.py
Labels: go

#53589 [Docs] Combine audio curation tutorial into a single notebook
  doc/source/ray-overview/examples/e2e-audio/README.ipynb
  doc/source/ray-overview/examples/e2e-audio/README.md
  doc/source/ray-overview/examples/e2e-audio/ci/tests.sh
  doc/source/ray-overview/examples/e2e-audio/e2e_audio/curation.ipynb
  doc/source/ray-overview/examples/e2e-audio/index.rst
Labels: docs, go

#53627 Enhance map_batches release tests
  python/ray/data/_internal/execution/operators/map_transformer.py
  release/nightly_tests/dataset/map_benchmark.py
  release/release_data_tests.yaml
Labels: go

#53629 [ci] use new docker account for releasing
  .buildkite/copy_files.py
Labels: go

#53628 [core] Skip `test_output.py::test_autoscaler_v2_stream_events_with_filter` on Windows
  python/ray/tests/test_output.py
Labels: go

#52295 [core] Correctly fail worker lease request if a task becomes infeasible after scheduling
  src/ray/raylet/local_task_manager.cc
  src/ray/raylet/local_task_manager.h
  src/ray/raylet/local_task_manager_test.cc
Labels: go

#47565 uint8_t* data ptr not used.
  python/ray/includes/serialization.pxi
Labels: core, go, community-contribution

#53443 [llm] bump vllm to 0.9.0.1
  python/ray/llm/_internal/batch/processor/vllm_engine_proc.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_loggers.py
  python/ray/llm/tests/serve/mocks/mock_vllm_engine.py
  python/ray/util/metrics.py
  python/requirements/llm/llm-requirements.txt
  python/requirements/llm/llm-test-requirements.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu124.txt
  python/setup.py
  release/llm_tests/batch/test_batch_vllm.py
  release/llm_tests/serve/run_llm_serve_test_and_bms.py
  release/ray_release/byod/byod_llm_pd_disagg_test.sh
  release/release_tests.yaml
Labels: go

#47243 [core] Make preloading Jemalloc configurable for worker
  doc/source/ray-contribute/profiling.rst
  python/ray/_private/services.py
  python/ray/tests/test_advanced_4.py
  src/ray/raylet/main.cc
Labels: P1, core, go, community-contribution

#53662 [core] Skip test on mac build
  python/ray/tests/test_runtime_env_conda_and_pip.py
Labels: go

#53554 Add DataContext + LogicalOp Args to Dataset Export
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/logical/interfaces/logical_operator.py
  python/ray/data/_internal/metadata_exporter.py
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_state_export.py
  src/ray/protobuf/BUILD
  src/ray/protobuf/export_dataset_metadata.proto
Labels: go

#53656 [core] Creating an interface ObjectManager's for GrpcClientManager.
  BUILD.bazel
  src/ray/object_manager/BUILD.bazel
  src/ray/object_manager/grpc_client_manager.h
  src/ray/rpc/object_manager/object_manager_client.h
Labels: go

#53664 Fix map_batches release test back_to_back option
  release/nightly_tests/dataset/map_benchmark.py
  release/release_data_tests.yaml
Labels: go

#53561 [Docs] Adds second notebook to timeseries tutorial
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/ray-overview/examples/e2e-timeseries/README.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/README.md
  doc/source/ray-overview/examples/e2e-timeseries/ci/test.py
  doc/source/ray-overview/examples/e2e-timeseries/e2e_timeseries/01-Distributed-Training.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/e2e_timeseries/02-Validation.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/e2e_timeseries/__init__.py
  doc/source/ray-overview/examples/e2e-timeseries/e2e_timeseries/data_factory.py
  doc/source/ray-overview/examples/e2e-timeseries/index.rst
  doc/source/ray-overview/examples/e2e-xgboost/dist_xgboost/tests.py
  release/ray_release/byod/byod_e2e_timeseries.sh
  release/release_tests.yaml
Labels: docs, go

#53672 [Docs] Create lockfiles for various e2e tutorials
  doc/source/ray-overview/examples/e2e-audio/ci/build.sh
  doc/source/ray-overview/examples/e2e-audio/requirements.in
  doc/source/ray-overview/examples/e2e-audio/requirements.txt
  doc/source/ray-overview/examples/e2e-timeseries/requirements.in
  doc/source/ray-overview/examples/e2e-timeseries/requirements.txt
  release/ray_release/byod/byod_e2e_audio.sh
  release/ray_release/byod/byod_e2e_timeseries.sh
Labels: docs

#53675 [core] Remove deprecated `ray start` CLI options
  python/ray/scripts/scripts.py
Labels: go

#53549 BLD: Remove redundant `manylinux1` related flag in `.bazelrc`
  .bazelrc
Labels: go

#53395 [Compiled Graph] Enhance Compile Graph with Multi-Device Support
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/dag_operation_future.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/accelerator_context.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/communicator.py
  python/ray/experimental/channel/communicator_handle.py
  python/ray/experimental/channel/conftest.py
  python/ray/experimental/channel/cpu_communicator.py
  python/ray/experimental/channel/nccl_group.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/utils.py
  python/ray/experimental/collective/conftest.py
  python/ray/util/collective/util.py
Labels: go

#53688 add back run on anyscale button
  doc/source/ray-overview/examples/entity-recognition-with-llms/README.ipynb
Labels: go

#53471 [Core] Vendor setproctitle
  .bazelrc
  .pre-commit-config.yaml
  BUILD.bazel
  LICENSE
  ci/env/install-dependencies.sh
  ci/env/install-toolchains.sh
  ci/lint/check_import_order.py
  ci/lint/format.sh
  doc/source/ray-contribute/development.rst
  doc/source/ray-core/miscellaneous.rst
  python/ray/__init__.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/dashboard/subprocesses/module.py
  python/ray/exceptions.py
  python/ray/includes/setproctitle.pxd
  python/ray/includes/setproctitle.pxi
  python/ray/tests/test_actor.py
  python/ray/tests/test_advanced_3.py
  python/ray/tests/test_failure_3.py
  python/ray/util/rpdb.py
  python/requirements_compiled.txt
  python/setup.py
  release/ray_release/byod/requirements_ml_byod_3.9.txt
  src/ray/common/BUILD
  src/ray/object_manager/plasma/BUILD.bazel
  src/ray/thirdparty/BUILD.bazel
  src/ray/thirdparty/setproctitle/BUILD.bazel
  src/ray/thirdparty/setproctitle/README
  src/ray/thirdparty/setproctitle/c.h
  src/ray/thirdparty/setproctitle/darwin_set_process_name.c
  src/ray/thirdparty/setproctitle/darwin_set_process_name.h
  src/ray/thirdparty/setproctitle/setproctitle.c
  src/ray/thirdparty/setproctitle/spt.h
  src/ray/thirdparty/setproctitle/spt_config.h
  src/ray/thirdparty/setproctitle/spt_debug.c
  src/ray/thirdparty/setproctitle/spt_python.h
  src/ray/thirdparty/setproctitle/spt_setup.c
  src/ray/thirdparty/setproctitle/spt_setup.h
  src/ray/thirdparty/setproctitle/spt_status.c
  src/ray/thirdparty/setproctitle/spt_status.h
  src/ray/thirdparty/setproctitle/spt_strlcpy.c
  src/ray/util/BUILD
Labels: go

#53680 handle task cancellation error
  python/ray/serve/_private/request_router/replica_wrapper.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
Labels: go

#53483 [ci] Fix crane auth issue for nightly multi arch tagging
  .buildkite/build.rayci.yml
  ci/ray_ci/automation/docker_tags_lib.py
  ci/ray_ci/automation/generate_index.py
Labels: go

#53669 [core] Remove deprecated `storage` parameter to `ray.init`
  python/ray/_private/external_storage.py
  python/ray/_private/node.py
  python/ray/_private/parameter.py
  python/ray/_private/ray_constants.py
  python/ray/_private/services.py
  python/ray/_private/storage.py
  python/ray/_private/worker.py
  python/ray/_private/workers/default_worker.py
  python/ray/scripts/scripts.py
  python/ray/tests/BUILD
  python/ray/tests/conftest.py
  python/ray/tests/test_object_spilling_2.py
  python/ray/tests/test_storage.py
Labels: go

#53695 [core][3/N] Avoid unnecessary deserialization/serialization of ParentTaskId
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/task_manager.cc
Labels: go

#53686 [core] Migrate ray.private.pydantic_compat from _private to _common
  python/ray/_common/pydantic_compat.py
  python/ray/dashboard/modules/job/job_head.py
  python/ray/dashboard/modules/job/pydantic_models.py
  python/ray/dashboard/modules/log/log_manager.py
  python/ray/dashboard/modules/serve/serve_head.py
  python/ray/serve/_private/api.py
  python/ray/serve/_private/config.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/version.py
  python/ray/serve/config.py
  python/ray/serve/schema.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_cli_2.py
  python/ray/serve/tests/test_config_files/arg_builders.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_target_capacity.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_schema.py
  python/ray/train/_internal/state/schema.py
  python/ray/train/v2/_internal/state/schema.py
  python/ray/util/serialization_addons.py
  python/ray/util/state/common.py
Labels: go

#53319 [core] Add single-controller API for ray.util.collective and torch gloo backend
  python/ray/experimental/collective/__init__.py
  python/ray/experimental/collective/collective.py
  python/ray/experimental/collective/communicator.py
  python/ray/experimental/collective/util.py
  python/ray/tests/BUILD
  python/ray/tests/test_experimental_collective.py
  python/ray/util/collective/collective.py
  python/ray/util/collective/collective_group/base_collective_group.py
  python/ray/util/collective/collective_group/torch_gloo_collective_group.py
  python/ray/util/collective/types.py
  python/ray/util/collective/util.py
Labels: go

#53709 [core] remove dead open telemetry code
  src/ray/stats/BUILD.bazel
  src/ray/stats/opentelemetry_metrics.cc
  src/ray/stats/tests/BUILD
  src/ray/stats/tests/opentelemetry_metrics_test.cc
Labels: go

#53710 [Docs] Finalize time-series tutorial, add lockfiles
  doc/source/ray-overview/examples/e2e-audio/ci/build.sh
  doc/source/ray-overview/examples/e2e-audio/requirements.in
  doc/source/ray-overview/examples/e2e-audio/requirements.txt
  doc/source/ray-overview/examples/e2e-timeseries/e2e_timeseries/01-Distributed-Training.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/e2e_timeseries/02-Validation.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/e2e_timeseries/03-Serving.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/index.rst
  doc/source/ray-overview/examples/e2e-timeseries/requirements.in
  doc/source/ray-overview/examples/e2e-timeseries/requirements.txt
  release/ray_release/byod/byod_e2e_audio.sh
  release/ray_release/byod/byod_e2e_timeseries.sh
Labels: docs, go

#53626 [train] add trace to WorkerHealthCheckFailedError
  python/ray/train/v2/_internal/exceptions.py
Labels: go

#53718 [train][template] pytorch + train + data template uses absolute links
  doc/source/train/examples/pytorch/distributing-pytorch/README.ipynb
  doc/source/train/examples/pytorch/distributing-pytorch/README.md
Labels: go

#53668 Add perf metrics for 2.47.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#53661 [Doc] Bind the version of kuberay to v1.3.0 in related docs
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.ipynb
Labels: go

#53385 [Docs] [istio mtls] Add warning on sidecar OOM for mTLS
  doc/source/cluster/kubernetes/k8s-ecosystem/istio.md
Labels: go

#53418 [core][telemetry/07] support counter metric on worker side
  src/ray/stats/tests/metric_with_open_telemetry_test.cc
  src/ray/telemetry/open_telemetry_metric_recorder.cc
  src/ray/telemetry/open_telemetry_metric_recorder.h
  src/ray/telemetry/tests/open_telemetry_metric_recorder_test.cc
Labels: go

#53741 Fix uv tests on macos x86_64
  python/ray/tests/test_runtime_env_uv_run.py
Labels: go

#53744 Fix vLLM batch test by changing to Pixtral
  release/llm_tests/batch/test_batch_vllm.py
Labels: go

#42182 [Tune][Air] Fix MLflowLoggerCallback to enable its use with PBT (#27783)
  python/ray/air/integrations/mlflow.py
  python/ray/air/tests/test_integration_mlflow.py
Labels: tune, triage, go, community-contribution

#53717 update codeowners for ray serve
  .github/CODEOWNERS
Labels: go

#53747 [serve] Improve test_metrics
  python/ray/serve/tests/test_metrics.py
Labels: go

#53436 Replace `miniconda3` with `miniforge`
  .buildkite/release-automation/verify-macos-wheels.sh
  ci/build/test-macos-wheels.sh
  ci/env/install-miniconda.sh
  doc/source/ray-contribute/development.rst
  python/build-wheel-macos.sh
Labels: go

#53783 [core] Increase instance sizes for wheel / HA tests
  .buildkite/core.rayci.yml
  .buildkite/kuberay.rayci.yml
  .buildkite/serve.rayci.yml
Labels: go

#53706 [RLlib] Fix device check in `Learner`.
  rllib/core/learner/learner.py
Labels: go

#53777 pass route prefix to replica
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
Labels: go

#53778 [serve] Fix autoscaling metrics
  python/ray/serve/_private/autoscaling_state.py
Labels: go

#53803 [core] Deflake `test_object_spilling.py`
  python/ray/tests/test_object_spilling.py
Labels: go

#53782 [core] Move dependencies of NodeManger to main.cc for better testability
  src/mock/ray/raylet/worker_pool.h
  src/ray/raylet/local_task_manager_test.cc
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/raylet.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/test/node_manager_test.cc
  src/ray/raylet/worker_pool.h
Labels: go

#53730 ray-llm container cu124 -> cu128 update
  .buildkite/_forge.rayci.yml
  .buildkite/base.rayci.yml
  .buildkite/build.rayci.yml
  .buildkite/llm.rayci.yml
  .buildkite/release/build.rayci.yml
  ci/compile_llm_requirements.sh
  ci/docker/base.cu128.wanda.yaml
  ci/docker/base.gpu.Dockerfile
  ci/docker/llm.build.wanda.yaml
  ci/docker/ray-llm.base.wanda.yaml
  ci/ray_ci/container.py
  ci/test_compile_llm_requirements.sh
  docker/ray-llm/Dockerfile
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu124.txt
  python/requirements_compiled_ray_py311_cu128.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu128.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu128.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu128.txt
  release/ray_release/config.py
  release/release_tests.yaml
Labels: go

#53752 [data] Refactor interface for actor_pool_map_operator
  ci/lint/pydoclint-baseline.txt
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/tests/test_actor_pool_map_operator.py
Labels: go

#53753 [serve] Set route_prefix and docs_path when re-deploying app
  python/ray/serve/_private/application_state.py
Labels: go

#53458 Replace `python setup.py bdist_wheel` with `pip wheel`
  ci/build/build-manylinux-wheel.sh
  python/build-wheel-macos.sh
  python/build-wheel-windows.sh
Labels: go

#53390 [ci] First release test on GKE
  release/ray_release/environments/kuberay.env
  release/ray_release/glue.py
  release/ray_release/job_manager/kuberay_job_manager.py
  release/ray_release/scripts/run_release_test.py
  release/ray_release/test.py
  release/ray_release/util.py
  release/release_tests.yaml
  release/run_release_test.sh
  release/tune_tests/scalability_tests/kuberay.yaml
Labels: go

#53809 [serve] Revert request timeout from serve instance fixtures
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_controller.py
Labels: go

#53814 [core] deleting unused code from plasma client
  src/ray/common/client_connection.cc
  src/ray/common/client_connection.h
  src/ray/common/test/client_connection_test.cc
Labels: go

#53843 [chore] Change file mode of `rayservice-no-ray-serve-replica.md` from 755 to 644
  doc/source/cluster/kubernetes/user-guides/rayservice-no-ray-serve-replica.md
Labels: go

#53802 [core] Deflake `test_multiprocessing.py`
  python/ray/tests/test_multiprocessing.py
  python/ray/util/multiprocessing/pool.py
Labels: go

#53837 [Doc][KubeRay] Remove very old XGBoostTrainer example
  doc/source/cluster/kubernetes/configs/xgboost-benchmark-autoscaler.yaml
  doc/source/cluster/kubernetes/configs/xgboost-benchmark.yaml
  doc/source/cluster/kubernetes/examples.md
  doc/source/cluster/kubernetes/examples/ml-example.md
Labels: go

#53798 [core][gpu-objects] Support intra-process communication
  python/ray/_private/gpu_object_manager.py
  python/ray/tests/test_gpu_objects.py
Labels: go

#53839 [Doc][KubeRay] Remove very old ResNet benchmark example
  doc/source/cluster/doc_code/pytorch_training_e2e_submit.py
  doc/source/cluster/kubernetes/configs/ray-cluster.gpu.yaml
  doc/source/cluster/kubernetes/examples.md
  doc/source/cluster/kubernetes/examples/gpu-training-example.md
Labels: go

#53821 [Serve.llm][P/D] Support separate deployment config for PDProxy in Prefill disagg
  python/ray/llm/_internal/serve/deployments/prefill_decode_disagg/prefill_decode_disagg.py
Labels: go

#53860 [Data] Improve `read_text` trailing newline semantics
  python/ray/data/_internal/datasource/text_datasource.py
  python/ray/data/tests/test_text.py
Labels: go

#53838 [devx] Fix 'uv run' command line parsing
  python/ray/_private/runtime_env/uv_runtime_env_hook.py
  python/ray/tests/test_runtime_env_uv_run.py
Labels: go

#53859 [Data] Improve handling of `pandas.NA`
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/row.py
  python/ray/data/tests/test_pandas_block.py
Labels: go

#53720 [core][gpu objects] Integrate single-controller collective APIs with GPU objects
  ci/lint/pydoclint-baseline.txt
  python/ray/_private/custom_types.py
  python/ray/_private/gpu_object_manager.py
  python/ray/_private/gpu_object_manager_util.py
  python/ray/_private/worker.py
  python/ray/actor.py
  python/ray/experimental/collective/collective.py
  python/ray/tests/BUILD
  python/ray/tests/test_gpu_objects_gloo.py
  python/ray/tests/test_gpu_objects_nccl.py
  python/ray/util/collective/collective.py
  python/ray/util/collective/collective_group/torch_gloo_collective_group.py
  python/ray/util/collective/util.py
Labels: go

#53822 [train][template] Remove ineffective post build script and pip install instead
  doc/source/train/examples/pytorch/distributing-pytorch/README.ipynb
  doc/source/train/examples/pytorch/distributing-pytorch/README.md
  doc/source/train/examples/pytorch/distributing-pytorch/ci/build.sh
  release/ray_release/byod/byod_pytorch_train_data.sh
  release/release_tests.yaml
Labels: go

#53815 Fix pickle error with remote code models in vLLM Ray worker process
  python/ray/llm/_internal/serve/deployments/llm/llm_engine.py
  release/llm_tests/serve/test_llm_serve_integration.py
  release/release_tests.yaml
Labels: go

#53514 [RLlib] MetricsLogger: Fix `get/set_state` to handle tensors in `self.values`.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/dqn/torch/dqn_torch_learner.py
  rllib/examples/evaluation/evaluation_parallel_to_training.py
  rllib/utils/metrics/stats.py
Labels: go

#53874 [core][gpu-objects] Fix `test_gpu_objects_nccl.py`
  python/ray/tests/test_gpu_objects_nccl.py
Labels: go

#53704 [Serve][LLM] Simplify _prepare_engine_config()
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
Labels: go

#53865 [data] split test_all_to_all.py
  python/ray/data/BUILD
  python/ray/data/tests/test_agg_e2e.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_groupby_e2e.py
  python/ray/data/tests/test_random_e2e.py
  python/ray/data/tests/test_repartition_e2e.py
  python/ray/data/tests/test_unique_e2e.py
Labels: go

#53867 [Data] Deprecate use_polars flag
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/transform_polars.py
  python/ray/data/_internal/execution/operators/join.py
  python/ray/data/context.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_sort.py
  release/nightly_tests/dataset/sort_benchmark.py
Labels: go

#53857 [ObjectStore] Warn if object store is allocated < 50% of total memory for data workloads
  python/ray/data/_internal/execution/resource_manager.py
Labels: go

#53898 Add dashboard visualizations for TPU metrics
  python/ray/dashboard/client/src/pages/metrics/Metrics.tsx
  python/ray/dashboard/modules/metrics/dashboards/default_dashboard_panels.py
Labels: go, k8s-proj, TPU

#53852 [Core] Use fd instead of handle for windows log redirection
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/util/BUILD
  src/ray/util/compat.cc
  src/ray/util/compat.h
  src/ray/util/internal/stream_redirection_handle.cc
  src/ray/util/internal/stream_redirection_handle.h
  src/ray/util/internal/tests/stream_redirection_handle_test.cc
  src/ray/util/pipe_logger.cc
  src/ray/util/pipe_logger.h
  src/ray/util/scoped_dup2_wrapper.cc
  src/ray/util/scoped_dup2_wrapper.h
  src/ray/util/scoped_dup2_wrapper_windows.cc
  src/ray/util/spdlog_fd_sink.h
  src/ray/util/stream_redirection.cc
  src/ray/util/tests/compat_test.cc
  src/ray/util/tests/scoped_dup2_wrapper_test.cc
  src/ray/util/tests/spdlog_fd_sink_test.cc
  src/ray/util/tests/spdlog_newliner_sink_test.cc
Labels: go

#53887 [Docs][KubeRay] Fix RayJob quickstart doc step 9 error
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.ipynb
Labels: go

#53842 [Doc][KubeRay] Update KubeRay operator installation reference
  doc/source/cluster/kubernetes/examples/modin-example.md
Labels: go

#51802 [Core] Support AMD GPU MI3xx product line
  python/ray/_private/accelerators/amd_gpu.py
  python/ray/util/accelerators/accelerators.py
Labels: Devprod, go, community-contribution

#53869 [train] expose training input/output in callbacks
  python/ray/train/v2/_internal/callbacks/metrics.py
  python/ray/train/v2/_internal/callbacks/state_manager.py
  python/ray/train/v2/_internal/execution/callback.py
  python/ray/train/v2/_internal/execution/context.py
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/_internal/execution/worker_group/worker.py
  python/ray/train/v2/_internal/logging/logging.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/tests/test_accelerator_utils.py
  python/ray/train/v2/tests/test_controller.py
  python/ray/train/v2/tests/test_logging.py
  python/ray/train/v2/tests/test_metrics.py
  python/ray/train/v2/tests/test_serialization.py
  python/ray/train/v2/tests/test_state.py
  python/ray/train/v2/tests/test_worker_group.py
  python/ray/train/v2/tests/util.py
Labels: go

#53849 [cgraph] Avoid depending on torch CPU module for CPU-only actor
  python/ray/experimental/channel/accelerator_context.py
Labels: go

#53788 [train] add proper filtering to metrics
  python/ray/dashboard/modules/metrics/dashboards/train_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/train_grafana_dashboard_base.json
Labels: go

#53684 [train] Cleanups for training ingest benchmark
  release/release_tests.yaml
  release/train_tests/benchmark/benchmark_factory.py
  release/train_tests/benchmark/config.py
  release/train_tests/benchmark/dataloader_factory.py
  release/train_tests/benchmark/image_classification/factory.py
  release/train_tests/benchmark/image_classification/imagenet.py
  release/train_tests/benchmark/image_classification/jpeg/__init__.py
  release/train_tests/benchmark/image_classification/jpeg/download_input_data_from_s3.sh
  release/train_tests/benchmark/image_classification/jpeg/factory.py
  release/train_tests/benchmark/image_classification/jpeg/imagenet.py
  release/train_tests/benchmark/image_classification/jpeg/jpeg_iterable_dataset.py
  release/train_tests/benchmark/image_classification/localfs_image_classification_jpeg/__init__.py
  release/train_tests/benchmark/image_classification/localfs_image_classification_jpeg/factory.py
  release/train_tests/benchmark/image_classification/parquet/__init__.py
  release/train_tests/benchmark/image_classification/parquet/factory.py
  release/train_tests/benchmark/image_classification/parquet/imagenet.py
  release/train_tests/benchmark/image_classification/parquet/parquet_iterable_dataset.py
  release/train_tests/benchmark/ray_dataloader_factory.py
  release/train_tests/benchmark/recsys/recsys_factory.py
  release/train_tests/benchmark/runner.py
  release/train_tests/benchmark/torch_dataloader_factory.py
  release/train_tests/benchmark/train_benchmark.py
Labels: go

#53932 [Docs] Fix issues with e2e audio tutorial
  doc/source/ray-overview/examples/e2e-audio/README.ipynb
  doc/source/ray-overview/examples/e2e-audio/ci/build.sh
  doc/source/ray-overview/examples/e2e-audio/requirements.in
  doc/source/ray-overview/examples/e2e-audio/requirements.txt
  release/ray_release/byod/byod_e2e_audio.sh
Labels: docs, go

#53909 [core] Fix flaky `test_worker_exit_intended_user_exit`
  python/ray/_private/state_api_test_utils.py
  python/ray/tests/test_exit_observability.py
Labels: go

#53901 [data] fix flakey schema
  python/ray/data/BUILD
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_deduping_schema.py
Labels: go

#53890 [Data] Prevent filename collisions on write
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/logical/rules/operator_fusion.py
  python/ray/data/_internal/planner/plan_write_op.py
  python/ray/data/_internal/util.py
  python/ray/data/datasource/file_datasink.py
  python/ray/data/datasource/filename_provider.py
  python/ray/data/tests/test_csv.py
  python/ray/data/tests/test_filename_provider.py
  python/ray/data/tests/test_json.py
  python/ray/data/tests/test_numpy.py
  python/ray/data/tests/test_parquet.py
  python/ray/data/tests/test_util.py
Labels: go

#53846 [Doc][KubeRay] Add a doc for scheduler plugins
  doc/source/cluster/kubernetes/k8s-ecosystem.md
  doc/source/cluster/kubernetes/k8s-ecosystem/scheduler-plugins.md
Labels: go

#53941 [serve] add ability to track child requests
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/replica_result.py
  python/ray/serve/context.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_handle_cancellation.py
  python/ray/serve/tests/test_http_cancellation.py
Labels: go

#53955 [Data] Refactor `Planner` to avoid storing plan-specific state
  python/ray/data/_internal/logical/optimizers.py
  python/ray/data/_internal/planner/__init__.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_operator_fusion.py
  python/ray/data/tests/test_randomize_block_order.py
Labels: go

#53928 [train][template] Pip install with python block instead
  doc/source/train/examples/pytorch/distributing-pytorch/README.ipynb
  doc/source/train/examples/pytorch/distributing-pytorch/README.md
Labels: go

#53531 [core][rocm] Allow CUDA_VISIBLE_DEVICS and HIP_VISIBLE_DEVICES
  python/ray/_private/accelerators/amd_gpu.py
  python/ray/tests/accelerators/test_amd_gpu.py
Labels: go

#53965 [train][template] Remove clock emoji which does not always render well
  doc/source/train/examples/pytorch/distributing-pytorch/README.ipynb
  doc/source/train/examples/pytorch/distributing-pytorch/README.md
Labels: go

#53967 fix ga4 events
  doc/source/_static/js/csat.js
  doc/source/_static/js/custom.js
  doc/source/_templates/extrahead.html
Labels: go

#53757 Fix ray import error when both ROCR_VISIBLE_DEVICES and HIP_VISIBLE_DEVICES are set
  python/ray/_private/accelerators/amd_gpu.py
Labels: go

#53966 [core] Revert container tests to medium size instance
  .buildkite/core.rayci.yml
Labels: go

#53654 [core] Use core worker client pool in GCS
  src/mock/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_actor_scheduler.cc
  src/ray/gcs/gcs_server/gcs_actor_scheduler.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/export_api/gcs_job_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_test.cc
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc
  src/ray/rpc/worker/core_worker_client_pool.cc
  src/ray/rpc/worker/core_worker_client_pool.h
Labels: go

#53986 [core] Fix ActorClass.remote return typing and expose Actor class methods to static analysis
  doc/source/conf.py
  python/ray/_private/worker.py
  python/ray/actor.py
Labels: go

#53937 [Serve.llm][P/D] Fix health check in prefill disagg
  python/ray/llm/_internal/serve/deployments/llm/llm_server.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/prefill_decode_disagg/prefill_decode_disagg.py
  python/ray/llm/_internal/serve/deployments/routers/router.py
  python/ray/llm/tests/serve/cpu/deployments/routers/test_router.py
  release/llm_tests/serve/test_llm_serve_fault_tolerance.py
  release/llm_tests/serve/test_llm_serve_integration.py
  release/release_tests.yaml
Labels: go

#53996 [core] Remove actor task path in normal task submitter
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#53701 [Data] Add reading from Delta Lake tables and from Unity Catalog
  doc/source/data/api/input_output.rst
  python/ray/data/BUILD
  python/ray/data/__init__.py
  python/ray/data/_internal/datasource/uc_datasource.py
  python/ray/data/_internal/datasource/unity_catalog_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_delta.py
  python/requirements/ml/data-test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#53962 [data] remove operator_fusion_benchmark
  release/nightly_tests/dataset/operator_fusion_benchmark.py
Labels: go

#53975 [core] Fix flaky `test_state_api`
  python/ray/dashboard/http_server_agent.py
Labels: go

#53914 [kuberay] log actionable err msg when required TPU node selectors missing
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/tests/kuberay/test_autoscaling_config.py
Labels: go

#54012 fix gsat global
  doc/source/_templates/extrahead.html
Labels: go

#54010 fix test_request_timeout timeout mismatch issue
  python/ray/serve/tests/test_request_timeout.py
Labels: go

#54017 remove extraneous index.rst file for e2e-multimodal-ai-workloads
  doc/source/ray-overview/examples/e2e-multimodal-ai-workloads/README.ipynb
  doc/source/ray-overview/examples/e2e-multimodal-ai-workloads/index.rst
  doc/source/ray-overview/examples/index.rst
Labels: go

#54016 [docker] Update latest Docker dependencies for 2.47.1 release
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#54011 [☀️] Fix repr for ray.ObjectRef, ray.ObjectRefGenerator types
  ci/lint/check_api_annotations.py
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  python/ray/_raylet.pyx
Labels: go

#54023 remove extraneous index.rst file for e2e examples (part 2)
  doc/source/ray-overview/examples/e2e-audio/index.rst
  doc/source/ray-overview/examples/e2e-multimodal-ai-workloads/README.ipynb
  doc/source/ray-overview/examples/e2e-multimodal-ai-workloads/README.md
  doc/source/ray-overview/examples/e2e-rag/README.ipynb
  doc/source/ray-overview/examples/e2e-rag/README.md
  doc/source/ray-overview/examples/e2e-rag/index.rst
  doc/source/ray-overview/examples/e2e-timeseries/README.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/README.md
  doc/source/ray-overview/examples/e2e-timeseries/index.rst
  doc/source/ray-overview/examples/e2e-xgboost/README.ipynb
  doc/source/ray-overview/examples/e2e-xgboost/README.md
  doc/source/ray-overview/examples/e2e-xgboost/index.rst
  doc/source/ray-overview/examples/entity-recognition-with-llms/README.ipynb
  doc/source/ray-overview/examples/entity-recognition-with-llms/README.md
  doc/source/ray-overview/examples/index.rst
  doc/source/ray-overview/examples/object-detection/README.ipynb
  doc/source/ray-overview/examples/object-detection/README.md
  doc/source/ray-overview/examples/object-detection/index.rst
Labels: go

#54019 [serve] Handle request with Semaphore
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/utils.py
Labels: go

#54037 [POC] fix test_metrics
  python/ray/serve/tests/test_metrics.py
Labels: go

#53957 [serve.llm] Prefix aware router eviction thread improvements
  python/ray/llm/_internal/serve/request_router/prefix_aware/prefix_tree.py
Labels: go

#54043 [ci] update anyscale layer
  ci/build/build-anyscale-docker.sh
  release/ray_release/byod/build.py
Labels: go

#54050 [serve] Use `get_application_url` in test_metrics
  python/ray/serve/tests/test_metrics.py
Labels: go

#54058 updating compile comment
  ci/compile_llm_requirements.sh
Labels: go

#54060 [ci] add `-sSL` for curl on node install
  ci/env/install-dependencies.sh
Labels: go

#54039 [RLlib] Fix env seeding in EnvRunners and rewrite `deterministic_training` example script (was still on old stack).
  doc/source/rllib/rllib-examples.rst
  rllib/BUILD
  rllib/algorithms/dreamerv3/utils/env_runner.py
  rllib/env/env_runner.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/env/tcp_client_inference_env_runner.py
  rllib/examples/debugging/deterministic_sampling_and_training.py
  rllib/examples/debugging/deterministic_training.py
  rllib/utils/debug/deterministic.py
  rllib/utils/torch_utils.py
Labels: go

#54022 [data/preprocessors] Improve execution perf for One Hot encoding
  python/ray/data/preprocessors/encoder.py
Labels: data, go

#53938 [V2][Autoscaler] Add `cloud_instance_id` to all V2 Austoscaler termination requests
  python/ray/autoscaler/v2/instance_manager/reconciler.py
  python/ray/autoscaler/v2/scheduler.py
  python/ray/autoscaler/v2/tests/test_reconciler.py
  src/ray/protobuf/instance_manager.proto
Labels: go

#54063 [V2][Autoscaler] Fix `numOfHosts` > 1 slice termination logic
  python/ray/autoscaler/v2/instance_manager/cloud_providers/kuberay/cloud_provider.py
  python/ray/autoscaler/v2/tests/test_node_provider.py
  python/ray/tests/kuberay/test_files/podlist2.yaml
  python/ray/tests/kuberay/test_kuberay_node_provider.py
Labels: go

#54090 [core] Deflake `test_actor_unavailable_conn_broken`
  python/ray/exceptions.py
  python/ray/tests/test_unavailable_actors.py
Labels: go
