Repository ray-project/ray, pull requests merged in 2025-03, with the labels that each got.

#51012 [doc] use python3 ipython in web-crawler
  doc/source/ray-core/examples/web-crawler.ipynb
Labels: go

#51011 [doc] fix invalid escape sequence
  doc/source/conf.py
Labels: go

#50223 [core][collective] Support customizing gloo timeout
  python/ray/util/collective/__init__.py
  python/ray/util/collective/collective.py
  python/ray/util/collective/collective_group/gloo_collective_group.py
  python/ray/util/collective/tests/single_node_cpu_tests/test_gloo_group_isolation.py
  python/ray/util/collective/util.py
Labels: core, go

#50989 [core] Fix missing header on windows
  src/ray/common/cgroup/BUILD
  src/ray/common/cgroup/cgroup_context.h
  src/ray/common/cgroup/test/fake_cgroup_setup_test.cc
Labels: go

#50930 Fix mock dependency for mock/ray/common/ray_syncer/ray_syncer.h
  BUILD.bazel
  src/mock/ray/common/ray_syncer/ray_syncer.h
  src/ray/common/test/BUILD
  src/ray/common/test/ray_syncer_test.cc
Labels: enhancement, core, go

#51016 [core][1/N] Make executor to be a long-running Python thread
  python/ray/_raylet.pxd
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_concurrency_group.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/test/concurrency_group_manager_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/concurrency_group_manager.cc
  src/ray/core_worker/transport/concurrency_group_manager.h
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
Labels: go

#50886 [Core] Logic Added to Cancel Infeasible Tasks in GCS Based on Autoscaler State
  python/ray/tests/conftest.py
  python/ray/tests/test_autoscaler_e2e.py
  src/ray/common/grpc_util.h
  src/ray/common/ray_config_def.h
  src/ray/common/scheduling/resource_set.cc
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc
  src/ray/raylet/scheduling/cluster_task_manager.cc
  src/ray/util/BUILD
  src/ray/util/string_utils.h
Labels: go

#51019 Update walkthrough.rst
  doc/source/ray-core/walkthrough.rst
Labels: go

#51021 [core][chore] Remove unused function `start_worker`
  python/ray/_private/node.py
Labels: go

#51024 [core] [easy] [no-op] Remove unused function argument
  python/ray/_private/function_manager.py
Labels: go

#51022 [core][cgraph] Support torch profiling
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/constants.py
Labels: go

#51007 [serve.llm][bugfix] Fix the wrong device_capability issue in vllm on quantized models.
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
Labels: go

#51034 [core] Remove unused flatbuffer messages
  src/ray/raylet/format/node_manager.fbs
Labels: go

#51023 [core][1/N] Remove the use of `redis_max_memory`
  python/ray/_private/test_utils.py
  python/ray/tests/test_output.py
  python/ray/tests/test_stress.py
  python/ray/tests/test_stress_failure.py
  python/ray/tests/test_stress_sharded.py
  release/long_running_tests/workloads/actor_deaths.py
  release/long_running_tests/workloads/apex.py
  release/long_running_tests/workloads/impala.py
  release/long_running_tests/workloads/many_actor_tasks.py
  release/long_running_tests/workloads/many_ppo.py
  release/long_running_tests/workloads/many_tasks.py
  release/long_running_tests/workloads/many_tasks_serialized_ids.py
  release/long_running_tests/workloads/node_failures.py
  release/long_running_tests/workloads/serve.py
  release/long_running_tests/workloads/serve_failure.py
  rllib/algorithms/tests/test_node_failures.py
Labels: go

#50874 [Train V2] Hide the private functions of train context to avoid abuse
  python/ray/train/v2/_internal/execution/context.py
  python/ray/train/v2/api/context.py
  python/ray/train/v2/api/train_fn_utils.py
  python/ray/train/v2/tests/test_data_integration.py
  python/ray/train/v2/tests/test_persistence.py
Labels: go

#50999 [ci] nit: remove empty `_TAG_RULE`
  ci/pipeline/determine_tests_to_run.py
Labels: go

#51037 [doc][core][cgraph] Add doc for torch profile
  doc/source/ray-core/compiled-graph/profiling.rst
Labels: go

#51035 [core] Fix include header for windows build
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: go

#51041 [data] Pass along kwargs to prevent breaking `ArrowPythonObjectScalar`
  python/ray/air/util/object_extensions/arrow.py
Labels: go

#50987 [core] Recheckin runtime agent rotation
  BUILD.bazel
  python/ray/_private/runtime_env/agent/main.py
  python/ray/_raylet.pyx
  python/ray/includes/stream_redirection.pxd
  python/ray/tests/test_logging.py
  src/ray/gcs/gcs_server/gcs_server_main.cc
  src/ray/raylet/main.cc
  src/ray/util/logging.cc
  src/ray/util/logging.h
  src/ray/util/pipe_logger.cc
  src/ray/util/stream_redirection_options.h
Labels: go

#50960 make replica retry count configurable
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: go

#51013 [ci] reduce ci impact caused by core changes
  .buildkite/data.rayci.yml
  .buildkite/rllib.rayci.yml
  .buildkite/serve.rayci.yml
  ci/pipeline/test_conditional_testing.py
  ci/pipeline/test_rules.txt
Labels: go

#50893 [docs] Minor readability improvements to Ray Data Quickstart
  doc/source/data/quickstart.rst
Labels: docs, data, go

#50956 [llm.serving] Port rayllm release tests to OSS
  release/llm_tests/llm_auto_select_worker.yaml
  release/llm_tests/llm_hello_world.py
  release/llm_tests/llm_serving_release_tests.py
  release/llm_tests/model_config/llama_3dot1_8b_lora.yaml
  release/llm_tests/model_config/llama_3dot1_8b_quantized_tp1.yaml
  release/llm_tests/model_config/llama_3dot1_8b_tp2.yaml
  release/llm_tests/probes/__init__.py
  release/llm_tests/probes/bugs.py
  release/llm_tests/probes/config.py
  release/llm_tests/probes/config.yaml
  release/llm_tests/probes/conftest.py
  release/llm_tests/probes/images/stop_sign.jpg
  release/llm_tests/probes/messages.py
  release/llm_tests/probes/models.py
  release/llm_tests/probes/openai_client.py
  release/llm_tests/probes/query_utils.py
  release/llm_tests/probes/test_basic.py
  release/llm_tests/probes/test_exact_correctness.py
  release/llm_tests/probes/test_json_mode.py
  release/llm_tests/probes/test_models.py
  release/llm_tests/probes/util.py
  release/llm_tests/serve_llama_3dot1_8b_lora.yaml
  release/llm_tests/serve_llama_3dot1_8b_quantized_tp1.yaml
  release/llm_tests/serve_llama_3dot1_8b_tp2.yaml
  release/llm_tests/test_utils.py
  release/ray_release/byod/requirements_llm_byod_3.11.txt
  release/release_data_tests.yaml
Labels: go

#51029 [VMware][WCP provider][Part 1/n]: Remove old experimental vSphere provider
  python/ray/autoscaler/_private/providers.py
  python/ray/autoscaler/_private/vsphere/ARCHITECTURE.md
  python/ray/autoscaler/_private/vsphere/config.py
  python/ray/autoscaler/_private/vsphere/data/userdata.yaml
  python/ray/autoscaler/_private/vsphere/gpu_utils.py
  python/ray/autoscaler/_private/vsphere/node_provider.py
  python/ray/autoscaler/_private/vsphere/pyvmomi_sdk_provider.py
  python/ray/autoscaler/_private/vsphere/scheduler.py
  python/ray/autoscaler/_private/vsphere/utils.py
  python/ray/autoscaler/_private/vsphere/vsphere_sdk_provider.py
  python/ray/autoscaler/vsphere/defaults.yaml
  python/ray/autoscaler/vsphere/example-full.yaml
  python/ray/autoscaler/vsphere/example-minimal.yaml
  python/ray/autoscaler/vsphere/example-vsan-file-service.yaml
  python/ray/autoscaler/vsphere/gpu.yaml
  python/ray/tests/BUILD
  python/ray/tests/vsphere/test_vsphere_node_provider.py
  python/ray/tests/vsphere/test_vsphere_sdk_provider.py
Labels: go

#51006 make latency buckets configurable
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/replica.py
  python/ray/serve/multiplex.py
  python/ray/serve/tests/unit/test_constants.py
Labels: go

#51003 ensure deployment name does not contain #
  python/ray/serve/deployment.py
  python/ray/serve/tests/unit/test_build_app.py
Labels: go

#51042 [LLM APIs] Fast follow ups for 2.44 (1/N)
  doc/source/data/working-with-llms.rst
  doc/source/llm/examples/batch/vllm-with-structural-output.ipynb
  doc/source/serve/api/index.md
  doc/source/serve/doc_code/vllm_example.py
  doc/source/serve/index.md
  doc/source/serve/llm/api.rst
  doc/source/serve/llm/index.rst
  doc/source/serve/llm/serving-llms.rst
  python/ray/data/llm.py
  python/ray/llm/_internal/batch/processor/base.py
  python/ray/llm/_internal/batch/processor/vllm_engine_proc.py
  python/ray/llm/_internal/common/__init__.py
  python/ray/llm/_internal/common/base_pydantic.py
  python/ray/llm/_internal/serve/builders/application_builders.py
  python/ray/llm/_internal/serve/configs/openai_api_models.py
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_deployment.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
  python/ray/llm/_internal/serve/observability/usage_telemetry/usage.py
  python/ray/llm/tests/batch/gpu/processor/test_vllm_engine_proc.py
  python/ray/llm/tests/serve/builders/test_application_builders.py
  python/ray/llm/tests/serve/configs/configs/matching_configs/hf_prompt_format.yaml
  python/ray/llm/tests/serve/deployments/llm/multiplex/test_lora_deployment_base_client.py
  python/ray/llm/tests/serve/deployments/llm/multiplex/test_lora_model_loader.py
  python/ray/llm/tests/serve/deployments/llm/multiplex/test_multiplex_deployment.py
  python/ray/llm/tests/serve/deployments/llm/vllm/test_vllm_engine.py
  python/ray/llm/tests/serve/deployments/mock_vllm_engine.py
  python/ray/llm/tests/serve/mock_vllm_model.yaml
  python/ray/llm/tests/serve/mock_vllm_model_no_accelerator.yaml
  python/ray/llm/tests/serve/observability/usage_telemetry/test_usage.py
  python/ray/serve/llm/__init__.py
  python/ray/serve/llm/builders.py
  python/ray/serve/llm/configs.py
  python/ray/serve/llm/deployments.py
  python/ray/serve/tests/unit/test_llm_imports.py
  release/llm_tests/serve_llama_3dot1_8b_lora.yaml
  release/llm_tests/serve_llama_3dot1_8b_quantized_tp1.yaml
  release/llm_tests/serve_llama_3dot1_8b_tp2.yaml
Labels: go

#50985 [CI] Use UV to compile LLM requirements
  ci/compile_llm_requirements.sh
Labels: go

#51046 [train v2] Run tensorflow release test with v2 enabled
  release/release_tests.yaml
Labels: go

#50731 [core] Add a warning for non-contiguous numpy array deserialization
  python/ray/_private/numpy_serialization.py
  python/ray/tests/test_serialization.py
  python/ray/util/serialization_addons.py
Labels: core, go

#51028 [Docs] update all hpu related docs
  doc/source/serve/doc_code/intel_gaudi_inference_serve.py
  doc/source/serve/doc_code/intel_gaudi_inference_serve_deepspeed.py
  doc/source/serve/tutorials/intel-gaudi-inference.md
  doc/source/train/examples/intel_gaudi/bert.ipynb
  doc/source/train/examples/intel_gaudi/llama.ipynb
  doc/source/train/examples/intel_gaudi/llama_pretrain.ipynb
  doc/source/train/examples/intel_gaudi/resnet.ipynb
  doc/source/train/examples/intel_gaudi/sd.ipynb
Labels: docs, go

#51054 Fix typos in doc directory
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  doc/source/cluster/configure-manage-dashboard.md
  doc/source/cluster/kubernetes/configs/static-ray-cluster.tls.yaml
  doc/source/cluster/kubernetes/configs/static-ray-cluster.with-fault-tolerance.yaml
  doc/source/cluster/kubernetes/configs/xgboost-benchmark.yaml
  doc/source/cluster/kubernetes/examples/distributed-checkpointing-with-gcsfuse.md
  doc/source/cluster/kubernetes/examples/rayjob-kueue-gang-scheduling.md
  doc/source/cluster/kubernetes/user-guides/config.md
  doc/source/cluster/kubernetes/user-guides/tls.md
  doc/source/cluster/running-applications/job-submission/ray-client.rst
  doc/source/cluster/vms/examples/ml-example.md
  doc/source/custom_directives.py
  doc/source/data/loading-data.rst
  doc/source/data/saving-data.rst
  doc/source/ray-core/doc_code/anti_pattern_out_of_band_object_ref_serialization.py
  doc/source/ray-core/doc_code/anti_pattern_too_fine_grained_tasks.py
  doc/source/ray-core/doc_code/namespaces.py
  doc/source/ray-core/examples/lm/ray_train.py
  doc/source/ray-core/namespaces.rst
  doc/source/ray-core/patterns/limit-running-tasks.rst
  doc/source/ray-core/ray-dag.rst
  doc/source/ray-core/scheduling/ray-oom-prevention.rst
  doc/source/ray-more-libs/ray-collective.rst
  doc/source/ray-more-libs/raydp.rst
  doc/source/ray-observability/getting-started.rst
  doc/source/ray-observability/user-guides/cli-sdk.rst
  doc/source/ray-observability/user-guides/configure-logging.md
  doc/source/ray-observability/user-guides/debug-apps/general-debugging.rst
  doc/source/ray-observability/user-guides/debug-apps/ray-debugging.rst
  doc/source/ray-overview/getting-started.md
  doc/source/ray-overview/installation.rst
  doc/source/rllib/metrics-logger.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-learner.rst
  doc/source/rllib/rllib-offline.rst
  doc/source/rllib/rllib-replay-buffers.rst
  doc/source/serve/doc_code/model_composition/chaining_example.py
  doc/source/templates/04_finetuning_llms_with_deepspeed/README.md
  doc/source/templates/04_finetuning_llms_with_deepspeed/merge_lora_weights.py
  doc/source/train/user-guides/using-gpus.rst
  doc/source/tune/api/callbacks.rst
  doc/source/tune/faq.rst
  doc/source/tune/tutorials/tune-fault-tolerance.rst
  doc/source/tune/tutorials/tune-output.rst
  doc/source/tune/tutorials/tune-scalability.rst
Labels: go

#50499 [core] Don't build cpp api on pip install
  python/setup.py
Labels: go

#51064 [LLM APIs] Fast follow up for 2.44 (2/N)
  doc/source/serve/api/index.md
  doc/source/serve/llm/serving-llms.rst
  python/ray/llm/_internal/serve/builders/__init__.py
  python/ray/llm/_internal/serve/builders/application_builders.py
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/llm_deployment.py
  python/ray/llm/_internal/serve/deployments/llm/llm_server.py
  python/ray/llm/tests/serve/builders/test_application_builders.py
  python/ray/llm/tests/serve/deployments/llm/multiplex/test_lora_deployment_base_client.py
  python/ray/llm/tests/serve/deployments/llm/multiplex/test_multiplex_deployment.py
  python/ray/serve/llm/__init__.py
  python/ray/serve/tests/unit/test_llm_imports.py
Labels: go

#51068 [data] Adding in another kwargs
  python/ray/air/util/tensor_extensions/arrow.py
Labels: go

#50622 [train][v2] implement state export
  python/ray/_private/event/export_event_logger.py
  python/ray/dashboard/modules/event/tests/test_event.py
  python/ray/dashboard/modules/job/common.py
  python/ray/dashboard/modules/train/train_head.py
  python/ray/train/v2/BUILD
  python/ray/train/v2/_internal/logging/logging.py
  python/ray/train/v2/_internal/state/export.py
  python/ray/train/v2/_internal/state/schema.py
  python/ray/train/v2/_internal/state/state_actor.py
  python/ray/train/v2/_internal/state/state_manager.py
  python/ray/train/v2/tests/test_state.py
  python/ray/train/v2/tests/test_state_export.py
  src/ray/protobuf/BUILD
  src/ray/protobuf/export_api/export_event.proto
  src/ray/protobuf/export_api/export_train_state.proto
Labels: go

#51066 [train] Deprecate torch amp wrapper utilities
  python/ray/train/BUILD
  python/ray/train/tests/test_gpu_amp.py
  python/ray/train/torch/train_loop_utils.py
Labels: go

#51069 [core] `BoundedExecutor` is never used when an actor is async
  src/ray/core_worker/transport/task_receiver.cc
Labels: go

#41972 [data] Update loading-data.rst
  doc/source/data/loading-data.rst
Labels: P1, data, go

#51051 [core] Fix plasma client memleak
  src/ray/object_manager/plasma/client.cc
Labels: go

#51077 [core] Checkin opentelemetry C++ sdk dependency
  BUILD.bazel
  bazel/ray_deps_setup.bzl
  src/ray/stats/opentelemetry_metrics.cc
  src/ray/stats/tests/BUILD
  src/ray/stats/tests/opentelemetry_metrics_test.cc
Labels: go

#50986 [Docs][Data] Ordering of rows
  doc/source/data/transforming-data.rst
Labels: data, go

#51101 [serve] Skip locality backoff unit test on windows
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
Labels: go

#50906 Improvements to Train DeepSpeed example
  doc/source/train/deepspeed.rst
Labels: docs, train, go

#50704 various improvements to lightgbm tutorial:
  doc/source/tune/examples/lightgbm_example.ipynb
Labels: tune, docs, go

#50697 minor improvements to hyperopt tutorial
  doc/source/tune/examples/hyperopt_example.ipynb
Labels: tune, docs, go

#50581 Various enhancements to Tune Keras example:
  doc/source/tune/examples/tune_mnist_keras.ipynb
Labels: tune, docs, go

#51059 [core][2/N] Remove `redis_max_memory` from Ray core
  python/ray/_private/node.py
  python/ray/_private/parameter.py
  python/ray/_private/ray_constants.py
  python/ray/_private/resource_spec.py
  python/ray/_private/worker.py
  python/ray/scripts/scripts.py
Labels: go

#51031 [doc] Update jemalloc profiling doc
  doc/source/ray-contribute/profiling.rst
Labels: go

#50455 Various improvements to the Ray Tune XGBoost tutorial
  doc/source/tune/examples/tune-xgboost.ipynb
Labels: go

#50404 Fixed non-runnable Optuna tutorial
  doc/source/tune/examples/optuna_example.ipynb
Labels: go

#51100 [core] Enable `make_shared` in plasma client
  src/ray/common/client_connection.cc
  src/ray/common/client_connection.h
  src/ray/object_manager/plasma/connection.cc
  src/ray/object_manager/plasma/connection.h
Labels: go

#47814 [Doc] RayServe Single-Host TPU v6e Example with vLLM
  doc/source/cluster/kubernetes/examples.md
  doc/source/cluster/kubernetes/examples/tpu-single-host-rayservice.md
  doc/source/cluster/kubernetes/examples/vllm-rayservice.md
  doc/source/cluster/kubernetes/images/serve-vllm-deployment.png
Labels: go

#50896 Improvements to HF Transformers example
  doc/source/train/getting-started-transformers.rst
Labels: go

#50954 [core] Cover cpplint for `src/ray/object_manager/plasma`
  .pre-commit-config.yaml
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/common.h
  src/ray/object_manager/plasma/connection.cc
  src/ray/object_manager/plasma/connection.h
  src/ray/object_manager/plasma/create_request_queue.cc
  src/ray/object_manager/plasma/create_request_queue.h
  src/ray/object_manager/plasma/dlmalloc.cc
  src/ray/object_manager/plasma/eviction_policy.cc
  src/ray/object_manager/plasma/get_request_queue.cc
  src/ray/object_manager/plasma/get_request_queue.h
  src/ray/object_manager/plasma/object_lifecycle_manager.cc
  src/ray/object_manager/plasma/object_lifecycle_manager.h
  src/ray/object_manager/plasma/object_store.cc
  src/ray/object_manager/plasma/object_store.h
  src/ray/object_manager/plasma/plasma.cc
  src/ray/object_manager/plasma/plasma_allocator.cc
  src/ray/object_manager/plasma/plasma_allocator.h
  src/ray/object_manager/plasma/protocol.cc
  src/ray/object_manager/plasma/protocol.h
  src/ray/object_manager/plasma/shared_memory.cc
  src/ray/object_manager/plasma/shared_memory.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store_runner.cc
  src/ray/object_manager/plasma/store_runner.h
  src/ray/object_manager/plasma/test/eviction_policy_test.cc
  src/ray/object_manager/plasma/test/fallback_allocator_test.cc
  src/ray/object_manager/plasma/test/mutable_object_test.cc
  src/ray/object_manager/plasma/test/object_lifecycle_manager_test.cc
  src/ray/object_manager/plasma/test/object_store_test.cc
  src/ray/object_manager/plasma/test/stats_collector_test.cc
Labels: go

#51053 [core] Implement call once token
  src/ray/util/BUILD
  src/ray/util/invoke_once_token.h
  src/ray/util/process_cleaner.cc
  src/ray/util/tests/BUILD
  src/ray/util/tests/invoke_once_token_test.cc
Labels: go

#51067 [train v2] Use the `FailurePolicy` factory
  python/ray/train/v2/api/data_parallel_trainer.py
Labels: go

#51030 [core][cgraph][docs] Compiled Graph troubleshooting
  .vale/styles/config/vocabularies/General/accept.txt
  doc/BUILD
  doc/source/ray-core/compiled-graph/ray-compiled-graph.rst
  doc/source/ray-core/compiled-graph/troubleshooting.rst
  doc/source/ray-core/doc_code/cgraph_troubleshooting.py
Labels: go

#50316 Various improvements to Tune Pytorch CIFAR tutorial
  doc/source/tune/examples/tune-pytorch-cifar.ipynb
Labels: go

#51000 [core][cgraph][docs] Move cgraphs docs code to test
  .buildkite/core.rayci.yml
  .vale/styles/config/vocabularies/General/accept.txt
  doc/BUILD
  doc/source/ray-core/compiled-graph/overlap.rst
  doc/source/ray-core/compiled-graph/profiling.rst
  doc/source/ray-core/compiled-graph/quickstart.rst
  doc/source/ray-core/compiled-graph/ray-compiled-graph.rst
  doc/source/ray-core/doc_code/cgraph_nccl.py
  doc/source/ray-core/doc_code/cgraph_overlap.py
  doc/source/ray-core/doc_code/cgraph_profiling.py
  doc/source/ray-core/doc_code/cgraph_quickstart.py
  doc/source/ray-core/doc_code/cgraph_visualize.py
Labels: go

#51110 [bugfix] Fixed the issues with compile llm reqs script
  ci/compile_llm_requirements.sh
Labels: go

#50276 Various enhancements to the Gradio Ray Serve tutorial
  doc/source/serve/tutorials/gradio-integration.md
Labels: serve, docs, go

#50870 Improvements to PBT example
  doc/source/tune/examples/pbt_visualization/pbt.gif
  doc/source/tune/examples/pbt_visualization/pbt4.gif
  doc/source/tune/examples/pbt_visualization/pbt_visualization.ipynb
  doc/source/tune/examples/pbt_visualization/pbt_visualization_utils.py
Labels: go

#50708 [doc] Add documentation for Asynchronous HyperBand Example in Tune
  doc/source/tune/examples/includes/async_hyperband_example.rst
  python/ray/tune/examples/async_hyperband_example.py
Labels: tune, docs, go

#51114 [docs,tune] fix typo, and standardize equations across the two apis
  doc/source/tune/doc_code/key_concepts.py
  doc/source/tune/key-concepts.rst
Labels: tune, docs, go

#50878 Various improvements to the Getting Started page
  .vale/styles/Google/WordList.yml
  .vale/styles/config/vocabularies/General/accept.txt
  .vale/styles/config/vocabularies/RLlib/accept.txt
  doc/source/ray-core/walkthrough.rst
  doc/source/ray-overview/getting-started.md
  doc/source/rllib/doc_code/rllib_on_ray_readme.py
Labels: go

#51111 Revert "[core] Add a warning for non-contiguous numpy array deserialization"
  python/ray/_private/numpy_serialization.py
  python/ray/tests/test_serialization.py
  python/ray/util/serialization_addons.py
Labels: go

#51015 [RLlib; docs] Fix 4 broken html links.
  doc/source/rllib/metrics-logger.rst
  doc/source/rllib/rllib-algorithms.rst
  doc/source/rllib/rllib-env.rst
Labels: rllib, rllib-docs-or-examples, rllib-newstack, go

#51055 [core] Add comments explaining why `unique_ptr::release()` is used.
  src/ray/common/test/ray_syncer_test.cc
Labels: go

#51115 [core] delete UNORDERED_VS_ABSL_MAPS_EVALUATION
  src/ray/object_manager/test/object_buffer_pool_test.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
Labels: go

#47737 Discover TPU logs in Ray Dashboard
  python/ray/_private/log_monitor.py
  python/ray/_private/node.py
  python/ray/tests/test_logging.py
Labels: go

#51106 [serve.llm] Added benchmark release tests
  release/llm_tests/benchmark/__init__.py
  release/llm_tests/benchmark/bm.py
  release/llm_tests/benchmark/configs.py
  release/llm_tests/benchmark/load_test.py
  release/llm_tests/benchmark/locust.py
  release/llm_tests/llm_serving_release_tests.py
  release/llm_tests/test_utils.py
  release/ray_release/byod/requirements_llm_byod_3.11.txt
  release/release_data_tests.yaml
Labels: go

#51118 [ci] Revert UV pip compile for LLM requirements
  ci/compile_llm_requirements.sh
Labels: go

#51079 Fix typos in comments and strings
  src/ray/common/bundle_location_index.cc
  src/ray/common/client_connection.cc
  src/ray/common/client_connection.h
  src/ray/common/memory_monitor.h
  src/ray/common/ray_config_def.h
  src/ray/common/ray_syncer/ray_syncer_bidi_reactor_base.h
  src/ray/common/scheduling/resource_instance_set.cc
  src/ray/common/scheduling/resource_set.h
  src/ray/core_worker/common.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
  src/ray/core_worker/lib/java/jni_utils.h
  src/ray/core_worker/reference_count.cc
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/concurrency_group_manager.cc
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.h
  src/ray/internal/internal.h
  src/ray/object_manager/common.h
  src/ray/object_manager/object_reader.h
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/object_lifecycle_manager.h
  src/ray/object_manager/plasma/plasma_allocator.h
  src/ray/object_manager/push_manager.h
  src/ray/object_manager/test/get_request_queue_test.cc
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/placement_group_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_interface.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/internal.h
  src/ray/raylet/scheduling/local_resource_manager.h
  src/ray/raylet/scheduling/policy/hybrid_scheduling_policy.h
  src/ray/raylet/scheduling/policy/node_label_scheduling_policy.cc
  src/ray/raylet/scheduling/policy/scheduling_policy.h
  src/ray/raylet/scheduling/scheduler_stats.cc
  src/ray/raylet/scheduling/scheduler_stats.h
  src/ray/raylet/test/local_object_manager_test.cc
  src/ray/raylet/test/node_manager_test.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet_client/raylet_client.h
  src/ray/stats/metric.h
  src/ray/util/event.cc
  src/ray/util/logging.cc
  src/ray/util/pipe_logger.cc
  src/ray/util/process.cc
  src/ray/util/stream_redirection_utils.cc
  src/ray/util/tests/pipe_logger_test.cc
  src/ray/util/util.h
Labels: core, go

#50240 use correct mean and standard deviation norm values in image tutorials
  doc/source/templates/05_dreambooth_finetuning/dreambooth/dataset.py
  doc/source/train/getting-started-pytorch-lightning.rst
  doc/source/train/getting-started-pytorch.rst
  python/ray/train/examples/experiment_tracking/torch_exp_tracking_mlflow.py
  python/ray/train/examples/experiment_tracking/torch_exp_tracking_wandb.py
  python/ray/train/examples/pytorch/torch_fashion_mnist_example.py
  python/ray/tune/examples/pbt_dcgan_mnist/common.py
Labels: go

#50998 [Data] Fix error message for `override_num_blocks` when reading from a HuggingFace `Dataset`
  python/ray/data/read_api.py
Labels: go

#51136 [docs] change order of libraries based on popularity
  doc/source/tune/examples/ml-frameworks.rst
Labels: docs, go

#51130 [serve] Exclude redirects from request error count
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/test_metrics.py
Labels: go

#49350 [Core][Autoscaler] Refactor v2 Log Formatting
  python/ray/autoscaler/v2/tests/test_utils.py
  python/ray/autoscaler/v2/utils.py
Labels: go

#51073 [core] Fix double checked locking
  src/ray/stats/metric.cc
  src/ray/stats/metric.h
Labels: go

#50770 [data] Add dataset/operator state, progress, total metrics
  python/ray/dashboard/modules/data/tests/test_data_head.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/progress_bar.py
  python/ray/data/_internal/stats.py
Labels: go

#51139 [core][cgraph] Fix doc test cgraph_overlap
  doc/source/ray-core/doc_code/cgraph_overlap.py
  python/ray/dag/compiled_dag_node.py
Labels: go

#49918 [Fix][Core] Execute user requested actor exit in C++ side
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_actor_failures.py
  src/ray/core_worker/context.cc
  src/ray/core_worker/context.h
  src/ray/core_worker/core_worker.cc
Labels: go

#51099 [CI] Enable python-no-log-warn precommit rule
  ci/lint/lint.sh
  python/ray/_private/memory_monitor.py
  python/ray/data/_internal/datasource/image_datasource.py
Labels: go

#51142 [core] Fix path comparison on windows
  python/ray/tests/test_logging.py
Labels: go

#51063 [ray.data.llm] Add release test
  release/llm_tests/batch/llm_4xl4.yaml
  release/llm_tests/batch/run_llama.py
  release/release_data_tests.yaml
Labels: go

#51131 [core] Block before running gpu tests
  .buildkite/core.rayci.yml
Labels: go

#51132 [core][cgraph][docs] Fix cgraph gpu docs code
  doc/source/ray-core/doc_code/cgraph_nccl.py
  doc/source/ray-core/doc_code/cgraph_profiling.py
  src/ray/core_worker/experimental_mutable_object_manager.h
  src/ray/core_worker/experimental_mutable_object_provider.h
Labels: go

#49980 [doc][core] fix a wrong url in ray-dag.rst
  doc/source/ray-core/ray-dag.rst
Labels: docs, go

#51170 [serve] Fix bad `mock` import
  python/ray/serve/tests/unit/test_deployment_state.py
Labels: go

#50997 [Data] Make num_blocks in repartition optional
  python/ray/data/dataset.py
  python/ray/data/tests/test_all_to_all.py
Labels: data, go

#51038 [Core][Doc] Add Document for Python Standard Attributes
  .vale/styles/config/vocabularies/Core/accept.txt
  doc/source/ray-observability/user-guides/configure-logging.md
Labels: go

#51123 [core] Use `psutil.process_iter` to replace `psutil.pids`
  python/ray/_private/memory_monitor.py
  python/ray/_private/services.py
  python/ray/_private/test_utils.py
Labels: go

#50915 [data] Handle schema mismatch in multiple blocks into one parquet file
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/tests/test_parquet.py
Labels: data, go

#51148 [data] fix the new dataset metrics
  python/ray/data/_internal/stats.py
Labels: data, go

#51083 [train v2][doc] Add updated fault tolerance user guide
  doc/source/train/deprecated-user-guides/fault-tolerance-deprecated-api.rst
  doc/source/train/doc_code/fault_tolerance.py
  doc/source/train/doc_code/key_concepts.py
  doc/source/train/images/fault_tolerance/cluster_failure.png
  doc/source/train/images/fault_tolerance/cluster_failure_start.png
  doc/source/train/images/fault_tolerance/cluster_recovery.png
  doc/source/train/images/fault_tolerance/head_node_failure.png
  doc/source/train/images/fault_tolerance/worker_failure_start.png
  doc/source/train/images/fault_tolerance/worker_group_recovery.png
  doc/source/train/images/fault_tolerance/worker_node_failure.png
  doc/source/train/images/fault_tolerance/worker_node_replacement.png
  doc/source/train/user-guides/fault-tolerance.rst
Labels: go

#51098 [core] Pass explicit handler for `ClientConnection` errors
  src/ray/common/client_connection.cc
  src/ray/common/client_connection.h
  src/ray/common/test/client_connection_test.cc
  src/ray/object_manager/plasma/connection.cc
  src/ray/object_manager/plasma/connection.h
  src/ray/object_manager/plasma/store.cc
  src/ray/object_manager/plasma/store.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/worker_pool_test.cc
Labels: go

#51171 Remove rllib dependency from core tests
  python/ray/tests/BUILD
  python/ray/tests/test_client_library_integration.py
  python/ray/tests/test_output.py
  rllib/BUILD
  rllib/tests/test_ray_client.py
Labels: go

#51048 [train v2][doc] Add updated Train + Tune user guide
  doc/source/train/api/api.rst
  doc/source/train/deprecated-user-guides/hyperparameter-optimization-deprecated.rst
  doc/source/train/doc_code/train_tune_interop.py
  doc/source/train/doc_code/tuner.py
  doc/source/train/images/hyperparameter_optimization/train_tune_interop.png
  doc/source/train/images/hyperparameter_optimization/train_without_tune.png
  doc/source/train/user-guides/hyperparameter-optimization.rst
  doc/source/tune/tutorials/tune-run.rst
Labels: go

#51085 [train][v2] add log file paths to train state
  python/ray/train/v2/_internal/callbacks/state_manager.py
  python/ray/train/v2/_internal/execution/worker_group/worker.py
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
  python/ray/train/v2/_internal/logging/logging.py
  python/ray/train/v2/_internal/state/export.py
  python/ray/train/v2/_internal/state/schema.py
  python/ray/train/v2/_internal/state/state_manager.py
  python/ray/train/v2/tests/test_state.py
  python/ray/train/v2/tests/test_state_export.py
  python/ray/train/v2/tests/test_worker_group.py
  src/ray/protobuf/export_api/export_train_state.proto
Labels: go

#51150 Fix UV hook to support Ray Job submission
  python/ray/_private/runtime_env/uv_runtime_env_hook.py
  python/ray/tests/test_runtime_env_uv_run.py
Labels: go

#51112 [serve.llm] Trim probes and reorg the llm.serve release test folder structure
  python/requirements/llm/llm-requirements.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu124.txt
  python/setup.py
  release/llm_tests/probes/bugs.py
  release/llm_tests/serve/benchmark/__init__.py
  release/llm_tests/serve/benchmark/bm.py
  release/llm_tests/serve/benchmark/configs.py
  release/llm_tests/serve/benchmark/load_test.py
  release/llm_tests/serve/benchmark/locust.py
  release/llm_tests/serve/configs/model_config/llama_3dot1_8b_lora.yaml
  release/llm_tests/serve/configs/model_config/llama_3dot1_8b_quantized_tp1.yaml
  release/llm_tests/serve/configs/model_config/llama_3dot1_8b_tp2.yaml
  release/llm_tests/serve/configs/serve_llama_3dot1_8b_lora.yaml
  release/llm_tests/serve/configs/serve_llama_3dot1_8b_quantized_tp1.yaml
  release/llm_tests/serve/configs/serve_llama_3dot1_8b_tp2.yaml
  release/llm_tests/serve/llm_auto_select_worker.yaml
  release/llm_tests/serve/probes/__init__.py
  release/llm_tests/serve/probes/config.py
  release/llm_tests/serve/probes/config.yaml
  release/llm_tests/serve/probes/conftest.py
  release/llm_tests/serve/probes/images/stop_sign.jpg
  release/llm_tests/serve/probes/messages.py
  release/llm_tests/serve/probes/models.py
  release/llm_tests/serve/probes/openai_client.py
  release/llm_tests/serve/probes/query_utils.py
  release/llm_tests/serve/probes/test_basic.py
  release/llm_tests/serve/probes/test_exact_correctness.py
  release/llm_tests/serve/probes/test_json_mode.py
  release/llm_tests/serve/probes/test_models.py
  release/llm_tests/serve/probes/util.py
  release/llm_tests/serve/run_llm_serve_release_tests.py
  release/llm_tests/serve/test_utils.py
  release/release_data_tests.yaml
  release/release_tests.yaml
Labels: go

#51176 [Data] Add fixed-size compute for read, write, and batch inference release tests
  release/nightly_tests/dataset/fixed_size_gpu_compute.yaml
  release/release_data_tests.yaml
Labels: go

#51185 Remove tune-specific task events test
  python/ray/tests/test_task_events.py
Labels: go

#51093 [train v2] Create a default `ScalingConfig` if one is not provided to the trainer
  python/ray/train/__init__.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/tests/test_data_parallel_trainer.py
Labels: go

#51178 [core][dashboard] Lazy init `NotifyQueue`
  python/ray/dashboard/utils.py
Labels: go

#51043 [core] Remove unused AsyncDrainNode
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
Labels: go

#50778 [core] Changing default tensor serialization in compiled graphs
  python/ray/dag/BUILD
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_mocked_nccl_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_transport.py
  python/ray/experimental/channel/auto_transport_type.py
  python/ray/experimental/channel/conftest.py
  python/ray/experimental/channel/serialization_context.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/experimental/util/types.py
  python/ray/tests/test_nccl_channel.py
Labels: core, go

#51090 [core][compiled graphs] Controllably destroy CUDA events in `GPUFuture`s
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_operation_future.py
Labels: core, go

#51089 [core] Cover cpplint for `/src/ray/object_manager` (excluding `plasma`)
  .pre-commit-config.yaml
  src/ray/object_manager/chunk_object_reader.cc
  src/ray/object_manager/chunk_object_reader.h
  src/ray/object_manager/common.cc
  src/ray/object_manager/common.h
  src/ray/object_manager/memory_object_reader.cc
  src/ray/object_manager/object_buffer_pool.cc
  src/ray/object_manager/object_buffer_pool.h
  src/ray/object_manager/object_directory.h
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/object_manager/ownership_based_object_directory.cc
  src/ray/object_manager/ownership_based_object_directory.h
  src/ray/object_manager/pull_manager.cc
  src/ray/object_manager/pull_manager.h
  src/ray/object_manager/push_manager.cc
  src/ray/object_manager/push_manager.h
  src/ray/object_manager/spilled_object_reader.cc
  src/ray/object_manager/test/create_request_queue_test.cc
  src/ray/object_manager/test/get_request_queue_test.cc
  src/ray/object_manager/test/object_buffer_pool_test.cc
  src/ray/object_manager/test/ownership_based_object_directory_test.cc
  src/ray/object_manager/test/pull_manager_test.cc
  src/ray/object_manager/test/push_manager_test.cc
  src/ray/object_manager/test/spilled_object_test.cc
Labels: core, go

#51183 [core] Move `ray.experimental.tf_utils` back to `rllib`
  doc/source/ray-core/examples/lbfgs/driver.py
  doc/source/ray-core/examples/lbfgs/ray-project/cluster.yaml
  doc/source/ray-core/examples/lbfgs/ray-project/project.yaml
  doc/source/ray-core/examples/lbfgs/ray-project/requirements.txt
  python/ray/experimental/BUILD
  python/ray/experimental/tf_utils.py
  python/ray/tests/BUILD
  rllib/BUILD
  rllib/algorithms/cql/cql_tf_policy.py
  rllib/algorithms/cql/cql_torch_policy.py
  rllib/algorithms/sac/sac_tf_policy.py
  rllib/algorithms/sac/sac_torch_policy.py
  rllib/policy/tf_policy.py
  rllib/utils/tests/test_tf_utils.py
  rllib/utils/tf_utils.py
Labels: go

#51215 [core] Remove AIR util from `test_ray_init_2`
  python/ray/tests/test_ray_init_2.py
Labels: go

#51033 [core] Wait for `DisconnectClientReply` in worker shutdown sequence
  src/ray/common/test/client_connection_test.cc
  src/ray/core_worker/core_worker.cc
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/raylet_client.cc
Labels: go

#51208 [core][cgraph][doc]Fix cgraphs gpu docs code again
  doc/source/ray-core/doc_code/cgraph_nccl.py
  doc/source/ray-core/doc_code/cgraph_profiling.py
Labels: go

#50618 [core] Mask rllib directory for core tests
  .buildkite/core.rayci.yml
  ci/ray_ci/tests.env.Dockerfile
Labels: go

#51174 [core][cgraph] Clean up CompiledDAG.actor_refs
  python/ray/dag/compiled_dag_node.py
Labels: go

#51044 [doc][core][cgraph] Add bind() to API page
  doc/source/conf.py
  doc/source/ray-core/compiled-graph/compiled-graph-api.rst
  python/ray/actor.py
Labels: go

#51192 [core][autoscaler] Add Pod names to the output of `ray status -v`
  python/ray/autoscaler/v2/tests/test_utils.py
  python/ray/autoscaler/v2/utils.py
Labels: go

#51220 [core] Refactor `test_run_driver_twice` to not use tune
  python/ray/tests/test_multi_node_3.py
Labels: go

#51186 [core] Mask tune directory for core tests
  .buildkite/core.rayci.yml
  ci/ray_ci/tests.env.Dockerfile
Labels: go

#51200 [Data] Make chunk combination threshold configurable for improved per…
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
Labels: go

#51224 [core] Deflake test_object_reconstruction_pending_creation
  python/ray/tests/test_reconstruction_2.py
Labels: go

#50564 [Data] Change default batch size from 1024 to `None`
  doc/source/train/examples/pytorch/torch_detection.ipynb
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/block.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/preprocessors/imputer.py
  python/ray/data/tests/test_map.py
Labels: go

#51187 [core][refactor] Move `node_stats_to_dict` to `utils.py` to avoid importing unnecessary modules
  python/ray/dashboard/memory_utils.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/utils.py
Labels: go

#51225 [ray.llm] Refactor download utilities
  python/ray/llm/_internal/common/utils/cloud_utils.py
  python/ray/llm/_internal/common/utils/download_utils.py
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/multiplex/lora_model_loader.py
  python/ray/llm/_internal/serve/deployments/llm/multiplex/utils.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
  python/ray/llm/_internal/serve/deployments/utils/node_initialization_utils.py
  python/ray/llm/tests/BUILD
  python/ray/llm/tests/common/utils/test_cloud_utils.py
  python/ray/llm/tests/serve/deployments/llm/multiplex/test_lora_model_loader.py
Labels: go

#51026 [core][refactor] Move accelerator-specific environment variables to `ray_constants.py` to avoid redefining them
  python/ray/_private/ray_constants.py
  python/ray/air/_internal/device_manager/npu.py
  python/ray/dashboard/modules/job/job_manager.py
  python/ray/dashboard/modules/job/job_supervisor.py
  python/ray/dashboard/modules/job/tests/subprocess_driver_scripts/check_cuda_devices.py
  python/ray/train/_internal/backend_executor.py
  python/ray/train/tests/test_backend.py
  python/ray/train/v2/_internal/callbacks/accelerators.py
Labels: go

#51194 Avoid `setup-dev.py` writing to `generated/`
  python/ray/setup-dev.py
  python/ray/tests/kuberay/rune2e.sh
Labels: go

#51198 [tune] Fix `RunConfig` deprecation message in Tune being emitted in `trainer.fit` usage
  python/ray/train/tests/test_api_migrations.py
  python/ray/tune/impl/tuner_internal.py
Labels: go

#51181 Sync (most) CI linters to precommit
  .pre-commit-config.yaml
Labels: go

#51209 [core] [easy] [noop] Avoid duplicate function
  src/ray/util/tests/BUILD
  src/ray/util/tests/spdlog_fd_sink_test.cc
Labels: go

#51204 [train v2][doc] Update user guides for metrics, checkpoints, results, and experiment tracking
  doc/source/train/doc_code/checkpoints.py
  doc/source/train/doc_code/key_concepts.py
  doc/source/train/doc_code/metric_logging.py
  doc/source/train/user-guides/checkpoints.rst
  doc/source/train/user-guides/experiment-tracking.rst
  doc/source/train/user-guides/hyperparameter-optimization.rst
  doc/source/train/user-guides/monitoring-logging.rst
  doc/source/train/user-guides/results.rst
Labels: go

#51232 [core] Fix client_connection test windows by trying old port
  src/ray/common/test/client_connection_test.cc
Labels: go

#51229 [core] Skip `setproctitle` tests on non-Linux machines
  python/ray/tests/test_task_events_2.py
Labels: go

#51246 [core] Remove "serve" and "tune" dependencies from `test_runtime_env_complicated`
  python/ray/tests/test_runtime_env_complicated.py
Labels: go

#51245 Skip flaky workflow tests
  python/ray/workflow/tests/test_events_with_crash.py
Labels: go

#50924 [Data] Always pin the seed when doing file-based random shuffle
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/util/client/common.py
  python/ray/util/common.py
Labels: go

#51206 [doc][core][cgraph] Complete Compiled Graph docs
  .vale/styles/config/vocabularies/Core/accept.txt
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/ray-core/compiled-graph/quickstart.rst
  doc/source/ray-core/compiled-graph/ray-compiled-graph.rst
  doc/source/ray-core/compiled-graph/troubleshooting.rst
  doc/source/ray-core/doc_code/cgraph_nccl.py
  doc/source/ray-core/doc_code/cgraph_quickstart.py
Labels: go

#51160 [RLlib] Add timers to env step, forward pass, and complete connector pipelines runs.
  rllib/connectors/connector_pipeline_v2.py
  rllib/connectors/learner/learner_connector_pipeline.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/env/env_runner.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/utils/metrics/__init__.py
  rllib/utils/metrics/stats.py
  rllib/utils/metrics/utils.py
Labels: go

#51199 [train v2] Improve `TrainingFailedError` message
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
  python/ray/train/v2/_internal/exceptions.py
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/_internal/execution/controller/state.py
  python/ray/train/v2/api/exceptions.py
  python/ray/train/v2/api/result.py
  python/ray/train/v2/tests/test_data_parallel_trainer.py
  python/ray/train/v2/tests/test_state.py
Labels: go

#50045 [train] Fold `v2.XGBoostTrainer` API into the public trainer class as an alternate constructor
  python/ray/train/tests/test_trainer_restore.py
  python/ray/train/tests/test_xgboost_trainer.py
  python/ray/train/v2/xgboost/xgboost_trainer.py
  python/ray/train/xgboost/v2.py
  python/ray/train/xgboost/xgboost_trainer.py
  release/train_tests/xgboost_lightgbm/train_batch_inference_benchmark.py
Labels: go

#51259 Revert "Sync (most) CI linters to precommit (#51181)"
  .pre-commit-config.yaml
Labels: go

#51202 [train v2][doc] Update persistent storage guide
  doc/source/train/images/persistent_storage_artifacts.png
  doc/source/train/user-guides/persistent-storage.rst
Labels: go

#51258 [ray.serve.llm] Fix release test
  python/ray/llm/_internal/common/utils/__init__.py
  python/ray/llm/_internal/serve/configs/server_models.py
Labels: go

#51263 [doc][core][cgraph] Clean up docs
  doc/source/ray-core/compiled-graph/compiled-graph-api.rst
  doc/source/ray-core/compiled-graph/quickstart.rst
  doc/source/ray-core/compiled-graph/ray-compiled-graph.rst
  doc/source/ray-core/compiled-graph/troubleshooting.rst
Labels: go

#51210 [image] Add cuda 12.8.0 in image building matrix
  .buildkite/_forge.rayci.yml
  .buildkite/build.rayci.yml
  .buildkite/linux_aarch64.rayci.yml
  ci/ray_ci/docker_container.py
  ci/ray_ci/test_ray_docker_container.py
  docker/retag-lambda/cuda_versions.txt
Labels: go

#51235 [serve.llm] Add gen-config to oss
  python/ray/llm/_internal/serve/config_generator/__init__.py
  python/ray/llm/_internal/serve/config_generator/base_configs/templates/base_serve_config.yaml
  python/ray/llm/_internal/serve/config_generator/base_configs/templates/default_deployment_configs.yaml
  python/ray/llm/_internal/serve/config_generator/generator.py
  python/ray/llm/_internal/serve/config_generator/inputs.py
  python/ray/llm/_internal/serve/config_generator/start.py
  python/ray/llm/_internal/serve/config_generator/utils/__init__.py
  python/ray/llm/_internal/serve/config_generator/utils/constants.py
  python/ray/llm/_internal/serve/config_generator/utils/files.py
  python/ray/llm/_internal/serve/config_generator/utils/gpu.py
  python/ray/llm/_internal/serve/config_generator/utils/input_converter.py
  python/ray/llm/_internal/serve/config_generator/utils/models.py
  python/ray/llm/_internal/serve/config_generator/utils/overrides.py
  python/ray/llm/_internal/serve/config_generator/utils/prompt.py
  python/ray/llm/_internal/serve/config_generator/utils/text_completion.py
  python/ray/llm/_internal/serve/configs/constants.py
  python/ray/llm/tests/BUILD
  python/ray/llm/tests/serve/config_generator/test_input_converter.py
  python/ray/llm/tests/serve/config_generator/test_text_completion.py
  python/ray/serve/llm/gen_config.py
  python/ray/setup-dev.py
  python/requirements/llm/llm-requirements.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu124.txt
  python/setup.py
Labels: go

#51269 [Test][Core|Runtime] Fix dependencies for test_e2e_complex
  python/ray/tests/test_runtime_env_complicated.py
Labels: go

#51248 [core] Mask train directory for core tests
  .buildkite/core.rayci.yml
  ci/ray_ci/tests.env.Dockerfile
Labels: go

#51278 [train v2][doc] Deprecate the trainer resources section in the resources user guide
  doc/source/train/user-guides/using-gpus.rst
Labels: go
