Repository ray-project/ray, pull requests merged in 2025-08, with the labels that each got.

#54220 [core] Scaffolding for core worker lazy subscribing
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
Labels: go

#55124 [core] fix AddEventsRequest rename
  python/ray/dashboard/modules/aggregator/tests/test_aggregator_agent.py
Labels: go

#55105 feat: update banner
  doc/source/conf.py
Labels: go

#55020 [data] Panels for blocks / task, bytes / blocks
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
Labels: go

#55091 [wheel] hermetic wheel building
  BUILD.bazel
  bazel/BUILD.bazel
  bazel/gen_extract.py
  cpp/BUILD.bazel
  cpp/gen_ray_cpp_pkg.py
  gen_ray_pkg.py
  java/BUILD.bazel
  java/gen_ray_java_pkg.py
  java/test.sh
  python/setup.py
Labels: go

#55153 [CI] Fix spot preemption simulation in release tests
  python/ray/_private/test_utils.py
Labels: go

#55024 [data][dashboard] Add Max Bytes to Read Panel + budget
  .github/CODEOWNERS
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
Labels: go

#55165 [wheel] fix macos wheel building with strict actions
  bazel/ray_deps_setup.bzl
  thirdparty/patches/cython.patch
Labels: go

#55120 [Data][LLM] Fix broken processor/test_vllm_engine_proc.py test
  python/ray/llm/_internal/batch/stages/chat_template_stage.py
  python/ray/llm/tests/BUILD
  python/ray/llm/tests/batch/gpu/processor/test_vllm_engine_proc.py
Labels: go

#55175 [wheel] revert back cython build rule hack
  bazel/cython.BUILD
Labels: go

#55149 [core] Move RPC-related build targets out of the global `BUILD` file
  BUILD.bazel
  bazel/ray.bzl
  src/ray/common/test/BUILD.bazel
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/test/BUILD.bazel
  src/ray/gcs/BUILD.bazel
  src/ray/gcs/gcs_client/BUILD.bazel
  src/ray/gcs/gcs_server/BUILD.bazel
  src/ray/gcs/gcs_server/test/BUILD.bazel
  src/ray/gcs/pubsub/BUILD.bazel
  src/ray/gcs/test/BUILD.bazel
  src/ray/object_manager/BUILD.bazel
  src/ray/protobuf/BUILD.bazel
  src/ray/pubsub/BUILD.bazel
  src/ray/raylet/scheduling/BUILD.bazel
  src/ray/raylet_client/BUILD.bazel
  src/ray/rpc/BUILD.bazel
  src/ray/rpc/test/BUILD
  src/ray/rpc/test/core_worker_client_pool_test.cc
  src/ray/rpc/test/grpc_bench/BUILD.bazel
  src/ray/rpc/test/grpc_bench/grpc_bench.cc
  src/ray/stats/BUILD.bazel
Labels: go

#55180 [wheel] convert `:ray_pkg` references to `:gen_ray_pkg`
  BUILD.bazel
  ci/ci.sh
  ci/env/install-llvm-binaries.sh
  ci/lint/check-git-clang-tidy-output.sh
  ci/ray_ci/tests.env.Dockerfile
  doc/source/ray-contribute/development.rst
  python/ray/_private/ray_experimental_perf.py
  python/ray/_private/ray_perf.py
Labels: go

#55156 [Core] Fix `test_resource_and_label_spec` on macOS
  python/ray/tests/unit/test_resource_and_label_spec.py
Labels: core, ci-test, go, community-contribution

#55141 [RLlib] Simplify: Remove input/output specs from RLModules.
  rllib/BUILD
  rllib/algorithms/dqn/default_dqn_rl_module.py
  rllib/algorithms/dqn/dqn_catalog.py
  rllib/algorithms/impala/tests/test_vtrace_v2.py
  rllib/algorithms/ppo/ppo_catalog.py
  rllib/algorithms/sac/default_sac_rl_module.py
  rllib/algorithms/sac/sac_catalog.py
  rllib/core/distribution/distribution.py
  rllib/core/distribution/torch/torch_distribution.py
  rllib/core/models/base.py
  rllib/core/models/catalog.py
  rllib/core/models/tests/test_catalog.py
  rllib/core/models/torch/base.py
  rllib/core/rl_module/multi_rl_module.py
  rllib/core/rl_module/rl_module.py
  rllib/core/rl_module/torch/torch_rl_module.py
  rllib/core/testing/torch/bc_module.py
  rllib/env/env_context.py
  rllib/examples/catalogs/custom_action_distribution.py
  rllib/examples/multi_agent/self_play_with_open_spiel.py
  rllib/examples/multi_agent/utils/self_play_callback.py
  rllib/examples/rl_modules/classes/autoregressive_actions_rlm.py
  rllib/examples/rl_modules/classes/custom_action_distribution_rlm.py
  rllib/examples/rl_modules/classes/modelv2_to_rlm.py
  rllib/examples/rl_modules/classes/random_rlm.py
  rllib/examples/rl_modules/classes/rock_paper_scissors_heuristic_rlm.py
  rllib/models/tests/test_distributions.py
Labels: go

#55191 [core] Add Subprocess Error Logging and Extend Timeout in test_node_labels
  python/ray/tests/conftest.py
  python/ray/tests/test_node_labels.py
Labels: go

#55089 [core] Hide the exposure of TaskProfileEvent in the aggregator endpoint
  python/ray/dashboard/modules/aggregator/aggregator_agent.py
  python/ray/dashboard/modules/aggregator/tests/test_aggregator_agent.py
  src/ray/protobuf/events_base_event.proto
Labels: go

#55049 [core] install smart_open[s3] in the image
  docker/base-deps/Dockerfile
Labels: core, go, community-contribution

#54683 [Docs][minor] Delete unused numpy import on Ray Data vLLM frontpage
  doc/source/data/working-with-llms.rst
Labels: docs, data, llm, go

#55181 [wheel] do not depend on `:ray_pkg` from java
  BUILD.bazel
  java/BUILD.bazel
  java/test.sh
Labels: go

#55115 [core] Revamp GetAllNodeInfo to be more efficient and take multiple NodeID's
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
  python/ray/util/state/state_manager.py
  src/mock/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/global_state_accessor.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/gcs_service.proto
  src/ray/rpc/test/core_worker_client_pool_test.cc
  src/ray/rpc/worker/core_worker_client_pool.cc
Labels: go

#55188 [core] Delete unnecessary api out of normal task submitter
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_scheduling.py
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#55150 [core] Add a `ray sanity-check` CLI
  python/ray/scripts/scripts.py
Labels: go

#55185 [core] Dead actor creation task path in normal task submitter
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#55211 [distro] image: drops the AUTOSCALER ARG in the base image
  docker/base-deps/Dockerfile
Labels: go

#55216 [data] truncate dataset export
  python/ray/data/_internal/metadata_exporter.py
  python/ray/data/tests/test_state_export.py
Labels: go

#55064 [Core] Add default TPU Ray node labels
  python/ray/_private/accelerators/accelerator.py
  python/ray/_private/accelerators/tpu.py
  python/ray/_private/resource_and_label_spec.py
  python/ray/includes/common.pxd
  python/ray/includes/common.pxi
  python/ray/tests/accelerators/test_tpu.py
  python/ray/tests/test_node_labels.py
  src/ray/common/constants.h
Labels: core, go, community-contribution

#54809 [ci] raydepsets: adding override and append UV flag fields
  ci/raydepsets/cli.py
  ci/raydepsets/test_cli.py
  ci/raydepsets/workspace.py
Labels: go

#55224 [llm][ci] Run llm gpu tests less
  .buildkite/llm.rayci.yml
Labels: go

#55194 [wheel] add Python 3.13 classifier
  python/setup.py
Labels: docs, core, go, community-contribution

#55233 [Doc][KubeRay] fix typo in integration with Apache YuniKorn
  doc/source/cluster/kubernetes/k8s-ecosystem/yunikorn.md
Labels: docs, core, go, community-contribution

#54504 [Data] Add option for enabling out-of-order execution to optimize data processing performance
  ci/lint/pydoclint-baseline.txt
  doc/source/ray-core/actors/task-orders.rst
  python/ray/_common/ray_option_utils.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_actor_out_of_order.py
Labels: core, data, go, community-contribution

#55182 [rllib] remove rllib contrib stuff
  ci/ray_ci/rllib_contrib/rllib_contrib_ci.sh
  release/rllib_contrib/learning_tests/run.py
  release/rllib_contrib/learning_tests/yaml_files/a2c/a2c-breakout-v5.yaml
  release/rllib_contrib/learning_tests/yaml_files/a3c/a3c-pongdeterministic-v5.yaml
  release/rllib_contrib/learning_tests/yaml_files/apex/apex-breakoutnoframeskip-v5.yaml
  release/rllib_contrib/learning_tests/yaml_files/ddpg/ddpg-halfcheetah-v4.yaml
  release/rllib_contrib/learning_tests/yaml_files/es/es-humanoid-v4.yaml
  release/rllib_contrib/learning_tests/yaml_files/slateq/slateq-interest-evolution-recsim-env.yaml
  release/rllib_contrib/learning_tests/yaml_files/td3/td3-halfcheetah-v4.yaml
  release/rllib_contrib/rllib_contrib_learning_tests.yaml
Labels: go

#55206 Add GKE GPU operator compat paths to ray-llm image PATH, LD_LIBRARY_PATH
  docker/ray-llm/Dockerfile
Labels: go

#55196 [core] Remove `grpc_common_lib` target
  BUILD.bazel
  src/ray/common/BUILD.bazel
  src/ray/common/test/BUILD.bazel
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/test/BUILD.bazel
  src/ray/gcs/BUILD.bazel
  src/ray/gcs/gcs_client/BUILD.bazel
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/test/gcs_client_reconnection_test.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_client/test/global_state_accessor_test.cc
  src/ray/gcs/gcs_server/BUILD.bazel
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.h
  src/ray/gcs/gcs_server/gcs_job_manager.h
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_resource_manager.h
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/pubsub_handler.h
  src/ray/gcs/gcs_server/runtime_env_handler.h
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/gcs/pubsub/BUILD.bazel
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/gcs/test/BUILD.bazel
  src/ray/object_manager/BUILD.bazel
  src/ray/pubsub/BUILD.bazel
  src/ray/pubsub/test/BUILD.bazel
  src/ray/raylet_client/BUILD.bazel
  src/ray/rpc/BUILD.bazel
  src/ray/rpc/gcs/gcs_rpc_client.h
  src/ray/rpc/gcs/gcs_rpc_server.h
  src/ray/rpc/test/BUILD.bazel
  src/ray/rpc/test/grpc_bench/BUILD.bazel
Labels: go

#55237 [cpp] remove ray cpp local genrule
  .buildkite/core.rayci.yml
  ci/ci.sh
  cpp/BUILD.bazel
Labels: go

#55220 [llm] recover LLM release tests
  python/ray/llm/_internal/batch/stages/vllm_engine_stage.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/tests/BUILD
  release/llm_tests/serve/benchmark/benchmark_vllm.py
  release/llm_tests/serve/test_llm_serve_integration.py
Labels: go

#55210 [Core] Only listen to localhost and head node ip from proxy and client server
  python/ray/_private/services.py
  python/ray/tests/conftest.py
  python/ray/tests/test_client.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_client_init.py
  python/ray/tests/test_client_proxy.py
  python/ray/util/client/__init__.py
  python/ray/util/client/ray_client_helpers.py
  python/ray/util/client/server/proxier.py
  python/ray/util/client/server/server.py
Labels: core, go, community-contribution

#52949 [Data] Replace `_MapWorker` name with operator names
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/tests/test_dynamic_block_split.py
  python/ray/data/tests/test_map.py
Labels: data, go, unstale

#55252 [core] Move `client_connection` to `ipc/` subpackage
  src/ray/common/BUILD.bazel
  src/ray/common/network_util.cc
  src/ray/common/test/BUILD.bazel
  src/ray/ipc/BUILD.bazel
  src/ray/ipc/client_connection.cc
  src/ray/ipc/client_connection.h
  src/ray/ipc/test/BUILD.bazel
  src/ray/ipc/test/client_connection_test.cc
  src/ray/object_manager/plasma/BUILD.bazel
  src/ray/object_manager/plasma/connection.h
  src/ray/object_manager/plasma/store.cc
  src/ray/raylet/BUILD.bazel
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/raylet.cc
  src/ray/raylet/worker.h
  src/ray/raylet/worker_pool.h
  src/ray/raylet_client/BUILD.bazel
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/raylet_client/raylet_connection.h
  src/ray/rpc/BUILD.bazel
Labels: go

#54492 [train] add LightGBMTrainer user guide
  doc/source/cluster/vms/examples/ml-example.md
  doc/source/ray-overview/use-cases.rst
  doc/source/train/api/api.rst
  doc/source/train/doc_code/lightgbm_quickstart.py
  doc/source/train/examples/xgboost/BUILD.bazel
  doc/source/train/examples/xgboost/distributed-xgboost-lightgbm.ipynb
  doc/source/train/getting-started-lightgbm.rst
  doc/source/train/more-frameworks.rst
  doc/source/tune/examples/tune-xgboost.ipynb
  python/ray/train/lightgbm/lightgbm_trainer.py
  python/ray/train/lightgbm/v2.py
  python/ray/train/v2/lightgbm/lightgbm_trainer.py
  python/ray/train/v2/tests/test_lightgbm_trainer.py
Labels: go

#55245 [ci] fixes grpcio requirements difference
  python/requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu128.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu128.txt
Labels: go

#55242 [doc] remove `protobuf<3` pinning in examples
  doc/source/templates/testing/cluster_envs/04_finetuning_llms_with_deepspeed.yaml
  doc/source/templates/testing/docker/04_finetuning_llms_with_deepspeed/requirements.txt
  release/ray_release/byod/byod_finetune_llvms.sh
Labels: go

#55159 [llm] Pass usage_context to vLLM engine config
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/tests/serve/gpu/deployments/llm/vllm/test_config_congruence.py
Labels: go

#54782 [Core] Cover cpplint for ray/src/ray/common/scheduling
  .pre-commit-config.yaml
  src/ray/common/scheduling/cluster_resource_data.cc
  src/ray/common/scheduling/cluster_resource_data.h
  src/ray/common/scheduling/fixed_point.cc
  src/ray/common/scheduling/fixed_point.h
  src/ray/common/scheduling/label_selector.cc
  src/ray/common/scheduling/label_selector.h
  src/ray/common/scheduling/resource_instance_set.cc
  src/ray/common/scheduling/resource_instance_set.h
  src/ray/common/scheduling/resource_set.cc
  src/ray/common/scheduling/resource_set.h
  src/ray/common/scheduling/scheduling_ids.cc
  src/ray/common/scheduling/scheduling_ids.h
Labels: core, ci-test, go, community-contribution

#54693 [Data] Adding row-based metrics
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/tests/test_stats.py
Labels: go

#55101 [core] Rename `FetchOrReconstruct` to `AsyncGetObjects`
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/flatbuffers/node_manager.fbs
  src/ray/ipc/client_connection.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet_client/BUILD.bazel
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/raylet_client/raylet_connection.h
Labels: go

#55151 [core] Raylet retryable grpc
  src/ray/common/ray_config_def.h
  src/ray/core_worker/core_worker_process.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.h
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/gcs_server.h
  src/ray/gcs/gcs_server/test/gcs_actor_scheduler_mock_test.cc
  src/ray/raylet/main.cc
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/BUILD.bazel
  src/ray/rpc/node_manager/node_manager_client.h
  src/ray/rpc/node_manager/raylet_client_pool.cc
  src/ray/rpc/node_manager/raylet_client_pool.h
  src/ray/rpc/node_manager/test/BUILD.bazel
  src/ray/rpc/node_manager/test/raylet_client_pool_test.cc
  src/ray/rpc/test/core_worker_client_pool_test.cc
  src/ray/rpc/worker/core_worker_client.cc
  src/ray/rpc/worker/core_worker_client_pool.h
Labels: go

#55112 [core] Object recovery fallback to GetAllNodeInfo if cache doesn't have addresses of secondary locations
  cpp/src/ray/runtime/object/local_mode_object_store.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/future_resolver.cc
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/object_recovery_manager.h
  src/ray/core_worker/store_provider/memory_store/memory_store.cc
  src/ray/core_worker/store_provider/memory_store/memory_store.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/test/actor_task_submitter_test.cc
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/memory_store_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/test/reference_count_test.cc
Labels: go

#55270 [core] Don't make an ipc on get if nothing to get from plasma
  src/ray/core_worker/core_worker.cc
Labels: go

#55299 [Core] Use enum class in cython
  python/ray/includes/common.pxd
  python/ray/includes/gcs_client.pxi
Labels: go

#55235 [llm] use uv to build the python dependencies inside the image
  docker/ray-llm/Dockerfile
  python/requirements/llm/llm-requirements.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu128.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu128.txt
Labels: go

#55305 [core][common] Change spammy log line from INFO to DEBUG in syncer
  src/ray/common/ray_syncer/ray_syncer.cc
Labels: go

#55272 [Data] Added support for Anti/Semi Join types
  doc/source/data/joining-data.rst
  python/ray/data/_internal/execution/operators/join.py
  python/ray/data/_internal/logical/operators/join_operator.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_join.py
Labels: go

#54623 [Data] Update Export API metadata and refresh the dataset/operator state when there is a change
  python/ray/data/_internal/execution/dataset_state.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/metadata_exporter.py
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_state_export.py
  src/ray/protobuf/export_dataset_metadata.proto
Labels: go

#55263 [serve] Call request routed hook only when request is accepted
  python/ray/serve/_private/router.py
Labels: go

#55026 [Serve] Update get_application_urls to not return root url of client when app does not exist
  python/ray/serve/_private/common.py
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_batching.py
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_cli_2.py
  python/ray/serve/tests/test_deploy.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_metrics.py
Labels: go

#55265 [ci] raydepsets: removing test lock file
  requirements_compiled_subset_general.txt
Labels: go

#54526 [data] Handle missing 'chunks' key when Databricks UC query returns zero rows
  python/ray/data/_internal/datasource/databricks_uc_datasource.py
  python/ray/data/tests/test_sql.py
Labels: usability, data, go, community-contribution

#55311 [core] Log actor plasma restart warning only once per process
  src/ray/core_worker/core_worker.cc
  src/ray/util/logging.h
Labels: go

#55333 Revert "[Data] Update Export API metadata and refresh the dataset/operator state when there is a change (#54623)"
  python/ray/data/_internal/execution/dataset_state.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/metadata_exporter.py
  python/ray/data/_internal/stats.py
  python/ray/data/tests/test_state_export.py
  src/ray/protobuf/export_dataset_metadata.proto
Labels: go

#55298 [Core] Bind runtime env agent and dashboard agent server to specified ip instead of 0.0.0.0
  python/ray/_private/runtime_env/agent/main.py
  python/ray/dashboard/agent.py
  python/ray/dashboard/http_server_agent.py
Labels: core, go, community-contribution

#55261 Upgrade ml_user_tests to use g6.12xlarge
  release/ml_user_tests/horovod/compute_tpl_aws.yaml
  release/ml_user_tests/train/compute_tpl_aws.yaml
Labels: go

#54483 [Data] - Show debug log for when aggregators are ready once.
  python/ray/data/_internal/execution/operators/hash_shuffle.py
  python/ray/data/_internal/issue_detection/detectors/__init__.py
  python/ray/data/_internal/issue_detection/detectors/hash_shuffle_detector.py
Labels: data, observability, go

#54891 [Serve.llm] Add PDServer and PrefixCacheAffinityRouter to the public alpha APIs.
  doc/source/serve/llm/serving-llms.rst
  python/ray/llm/_internal/serve/deployments/llm/llm_server.py
  python/ray/llm/_internal/serve/deployments/prefill_decode_disagg/prefill_decode_disagg.py
  python/ray/llm/_internal/serve/request_router/prefix_aware/prefix_aware_router.py
  python/ray/llm/tests/serve/cpu/deployments/prefill_decode_disagg/test_prefill_decode_disagg.py
  python/ray/llm/tests/serve/cpu/deployments/test_prefix_aware_request_router.py
  python/ray/serve/config.py
  python/ray/serve/llm/__init__.py
  python/ray/serve/llm/deployment.py
  python/ray/serve/llm/ingress.py
  python/ray/serve/llm/request_router.py
  python/ray/serve/tests/unit/test_llm_imports.py
  release/llm_tests/serve/configs/serve_llama_3dot1_8b_quantized_tp1_1p1d.yaml
  release/llm_tests/serve/configs/serve_llama_3dot1_8b_quantized_tp1_2p6d.yaml
Labels: go

#55282 [2/n] IPv6 support: address <-> host:port conversion for CPP Part
  cpp/BUILD.bazel
  cpp/src/ray/config_internal.cc
  cpp/src/ray/test/cluster/cluster_mode_test.cc
  cpp/src/ray/util/process_helper.cc
  cpp/src/ray/util/util.cc
  src/ray/common/BUILD.bazel
  src/ray/common/network_util.cc
  src/ray/common/network_util.h
  src/ray/common/test/BUILD.bazel
  src/ray/common/test/ray_syncer_test.cc
  src/ray/common/test/syncer_service_e2e_test.cc
  src/ray/common/test_util.cc
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/reference_count.cc
  src/ray/gcs/BUILD.bazel
  src/ray/gcs/gcs_client/BUILD.bazel
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/gcs_client/test/BUILD.bazel
  src/ray/gcs/gcs_client/test/gcs_client_reconnection_test.cc
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/BUILD.bazel
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/BUILD.bazel
  src/ray/gcs/gcs_server/test/gcs_health_check_manager_test.cc
  src/ray/gcs/redis_context.cc
  src/ray/pubsub/test/BUILD.bazel
  src/ray/pubsub/test/integration_test.cc
  src/ray/raylet/BUILD.bazel
  src/ray/raylet/node_manager.cc
  src/ray/raylet/raylet.cc
  src/ray/raylet/worker_pool.cc
  src/ray/rpc/BUILD.bazel
  src/ray/rpc/gcs/gcs_rpc_client.h
  src/ray/rpc/grpc_client.h
  src/ray/rpc/grpc_server.cc
  src/ray/rpc/metrics_agent_client.h
  src/ray/rpc/node_manager/raylet_client_pool.cc
  src/ray/rpc/worker/core_worker_client_pool.cc
  src/ray/stats/BUILD.bazel
  src/ray/stats/stats.h
  src/ray/util/BUILD.bazel
  src/ray/util/network_util.cc
  src/ray/util/network_util.h
  src/ray/util/tests/BUILD.bazel
  src/ray/util/tests/network_util_test.cc
Labels: core, go, community-contribution

#55383 [ci] updating expand operation to include append and override flags
  ci/raydepsets/cli.py
Labels: go

#55352 [Ray Core] Use Ray Distributed Debugger rather than Ray Debugger
  python/ray/_private/worker.py
Labels: docs, core, observability, go, community-contribution

#55229 [core] improve the robustness of raylet metric reporting
  src/ray/raylet/main.cc
Labels: go

#55402 [Data] Fixed sorting release test to produce 1Gb blocks
  release/nightly_tests/dataset/sort_benchmark.py
Labels: go

#55363 [core] Clean up redundant node registration logs in the GCS
  src/ray/common/id.h
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_mgr.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/util/logging.h
Labels: go

#55243 [Core] Fix endless loop in `stream` attribute access of `ray._private.utils.Unbuffered`
  python/ray/_private/utils.py
Labels: core, go, community-contribution

#55382 [core] Split `buffer.h` target from `ray_object`
  src/ray/common/BUILD.bazel
  src/ray/core_worker/BUILD.bazel
  src/ray/object_manager/plasma/BUILD.bazel
  src/ray/raylet/BUILD.bazel
  src/ray/raylet_client/BUILD.bazel
Labels: go

#55361 [core] Fix flaky test_cleanup_on_driver_exit
  python/ray/tests/test_multi_node.py
Labels: go

#55412 [core] shortern test_aggregated_prometheus_metrics test name
  python/ray/tests/BUILD
  python/ray/tests/test_metric_cardinality.py
Labels: go

#55322 [Data] Deprecate `with_columns` API in favor of `with_column`
  python/ray/data/dataset.py
  python/ray/data/expressions.py
  python/ray/data/tests/test_map.py
Labels: data, go

#55420 [core] Remove unused test utils
  src/ray/common/test_util.cc
  src/ray/common/test_util.h
Labels: go

#55425 [image] add cuda 12.6 into the cuda image matrix
  .buildkite/_forge.rayci.yml
  .buildkite/build.rayci.yml
  ci/ray_ci/docker_container.py
  ci/ray_ci/test_ray_docker_container.py
Labels: go

#55427 [core][gpu-objects][1/N] Pass `tensor_transport` to `store_task_errors` even if the actor task throws an exception
  python/ray/_raylet.pyx
Labels: go

#54944 [serve] Move utility functions from constants to constants_utils + increase readability of constants
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/constants_utils.py
  python/ray/serve/tests/unit/test_constants.py
  python/ray/serve/tests/unit/test_constants_utils.py
Labels: serve, go, community-contribution

#55315 [train][tests] Reduce test flakiness by removing randomness
  python/ray/train/examples/pytorch/torch_fashion_mnist_example.py
Labels: go

#55426 [Data] Bumping latest Arrow version to 21.0
  .buildkite/data.rayci.yml
  ci/docker/data.build.Dockerfile
  ci/docker/data.build.wanda.yaml
  ci/docker/datal.build.wanda.yaml
  python/ray/data/__init__.py
Labels: go

#55397 [release] Move logic to check whether to build custom BYOD image
  release/ray_release/byod/build.py
  release/ray_release/scripts/ray_bisect.py
  release/ray_release/tests/test_byod_build.py
Labels: go

#54834 [GPU Object][Benchmark] Add gpu object microbenchmark
  release/microbenchmark/experimental/gpu_object_microbenchmark.py
  release/release_tests.yaml
Labels: go, gpu-objects

#55421 [core] Split `task_execution/` out from `transport/`
  BUILD.bazel
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/actor_manager.h
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/task_execution/BUILD.bazel
  src/ray/core_worker/task_execution/actor_scheduling_queue.cc
  src/ray/core_worker/task_execution/actor_scheduling_queue.h
  src/ray/core_worker/task_execution/concurrency_group_manager.cc
  src/ray/core_worker/task_execution/concurrency_group_manager.h
  src/ray/core_worker/task_execution/fiber.h
  src/ray/core_worker/task_execution/normal_scheduling_queue.cc
  src/ray/core_worker/task_execution/normal_scheduling_queue.h
  src/ray/core_worker/task_execution/out_of_order_actor_scheduling_queue.cc
  src/ray/core_worker/task_execution/out_of_order_actor_scheduling_queue.h
  src/ray/core_worker/task_execution/scheduling_queue.h
  src/ray/core_worker/task_execution/scheduling_util.cc
  src/ray/core_worker/task_execution/scheduling_util.h
  src/ray/core_worker/task_execution/task_receiver.cc
  src/ray/core_worker/task_execution/task_receiver.h
  src/ray/core_worker/task_execution/test/BUILD.bazel
  src/ray/core_worker/task_execution/test/concurrency_group_manager_test.cc
  src/ray/core_worker/task_execution/test/fiber_state_test.cc
  src/ray/core_worker/task_execution/test/scheduling_queue_test.cc
  src/ray/core_worker/task_execution/test/task_receiver_test.cc
  src/ray/core_worker/task_execution/test/thread_pool_test.cc
  src/ray/core_worker/task_execution/thread_pool.cc
  src/ray/core_worker/task_execution/thread_pool.h
  src/ray/core_worker/test/BUILD.bazel
  src/ray/core_worker/test/actor_manager_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/transport/normal_task_submitter.h
  src/ray/internal/internal.h
  src/ray/raylet/BUILD.bazel
  src/ray/raylet/worker_pool.cc
Labels: go

#55444 [image] add cuda 12.6 for aarch64
  .buildkite/linux_aarch64.rayci.yml
Labels: go

#55445 [ci] shorten test name of `concurrency_group_manager_test`
  src/ray/core_worker/task_execution/test/BUILD.bazel
Labels: go

#55455 [ci] raydepsets: enable isort
  ci/raydepsets/cli.py
  ci/raydepsets/test_cli.py
  ci/raydepsets/testing_utils.py
  ci/raydepsets/workspace.py
  pyproject.toml
Labels: go

#55456 [core] give `should_fetch_cluster_id_` an init value
  src/ray/gcs/gcs_client/gcs_client.h
Labels: go

#55414 [Core] Cover cpplint for ray/src/ray/common/test
  .pre-commit-config.yaml
  src/ray/common/test/bundle_location_index_test.cc
  src/ray/common/test/event_stats_test.cc
  src/ray/common/test/grpc_util_test.cc
  src/ray/common/test/id_test.cc
  src/ray/common/test/label_selector_test.cc
  src/ray/common/test/memory_monitor_test.cc
  src/ray/common/test/postable_test.cc
  src/ray/common/test/ray_config_test.cc
  src/ray/common/test/ray_syncer_test.cc
  src/ray/common/test/resource_instance_set_test.cc
  src/ray/common/test/resource_request_test.cc
  src/ray/common/test/resource_set_test.cc
  src/ray/common/test/scheduling_ids_test.cc
  src/ray/common/test/status_test.cc
  src/ray/common/test/syncer_service_e2e_test.cc
  src/ray/common/test/task_spec_test.cc
Labels: core, ci-test, go, community-contribution

#53461 [core] Add as_completed and map_unordered APIs
  doc/source/ray-core/api/core.rst
  python/ray/tests/BUILD
  python/ray/tests/test_util_helpers.py
  python/ray/util/__init__.py
  python/ray/util/helpers.py
Labels: usability, docs, core, go, community-contribution, unstale

#54909 Fix Ray Train Docs Code Snippet Mis-highlighting
  doc/source/train/getting-started-pytorch-lightning.rst
  doc/source/train/getting-started-pytorch.rst
  doc/source/train/getting-started-transformers.rst
  doc/source/train/getting-started-xgboost.rst
  doc/source/train/user-guides/data-loading-preprocessing.rst
  doc/source/train/user-guides/experiment-tracking.rst
Labels: go

#55403 [ci] moving workspace tests to test_workspace file
  ci/raydepsets/BUILD.bazel
  ci/raydepsets/tests/test_cli.py
  ci/raydepsets/tests/test_data/requirement_constraints_test.txt
  ci/raydepsets/tests/test_data/requirements_compiled_test.txt
  ci/raydepsets/tests/test_data/requirements_compiled_test_expand.txt
  ci/raydepsets/tests/test_data/requirements_compiled_test_update.txt
  ci/raydepsets/tests/test_data/requirements_test.txt
  ci/raydepsets/tests/test_data/test.depsets.yaml
  ci/raydepsets/tests/test_workspace.py
  ci/raydepsets/tests/utils.py
Labels: go

#55022 [data] external buffer num blocks metrics
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_stats.py
Labels: go

#53550 [RLlib] Upgrade RLlink protocol for external env/simulator training.
  doc/source/rllib/external-envs.rst
  doc/source/rllib/package_ref/env.rst
  doc/source/rllib/package_ref/env/external.rst
  doc/source/rllib/package_ref/env/utils.rst
  rllib/BUILD
  rllib/env/external/__init__.py
  rllib/env/external/env_runner_server_for_external_inference.py
  rllib/env/external/rllink.py
  rllib/env/policy_client.py
  rllib/env/policy_server_input.py
  rllib/env/tcp_client_inference_env_runner.py
  rllib/env/utils/external_env_protocol.py
  rllib/env/utils/infinite_lookback_buffer.py
  rllib/env/wrappers/unity3d_env.py
  rllib/examples/envs/classes/utils/dummy_external_client.py
  rllib/examples/envs/env_connecting_to_rllib_w_tcp_client.py
  rllib/examples/envs/external_envs/cartpole_client.py
  rllib/examples/envs/external_envs/cartpole_server.py
  rllib/examples/envs/external_envs/dummy_client_with_two_episodes.py
  rllib/examples/envs/external_envs/unity3d_client.py
  rllib/examples/envs/external_envs/unity3d_dummy_client.py
  rllib/examples/envs/external_envs/unity3d_server.py
  rllib/utils/checkpoints.py
Labels: go

#55488 Disable gemini code review summary
  .gemini/config.yaml
  .github/CODEOWNERS
Labels: go

#55222 Ray train improve worker error logging
  python/ray/train/v2/BUILD
  python/ray/train/v2/_internal/execution/worker_group/poll.py
  python/ray/train/v2/tests/test_worker_group_poll_status.py
Labels: go

#55498 [Data] Restore handling of `PyExtensionType` to maintain compatibility w/ previously written datasets
  python/ray/data/__init__.py
Labels: go

#55189 [Core]Separate Environment Variables for ray.init() and ray ctl to Reflect Different Protocols and Ports
  doc/source/cluster/running-applications/job-submission/quickstart.rst
  python/ray/_private/ray_constants.py
  python/ray/dashboard/modules/job/cli.py
  python/ray/dashboard/modules/job/sdk.py
  python/ray/dashboard/modules/job/tests/test_cli_integration.py
  python/ray/dashboard/utils.py
  python/ray/scripts/scripts.py
  python/ray/tests/test_cli_patterns/test_ray_start.txt
  python/ray/tests/test_cli_patterns/test_ray_start_windows_osx.txt
Labels: docs, core, go, community-contribution

#55400 [Data] Cleaning up `StatsManager`
  python/ray/data/_internal/stats.py
Labels: go

#55336 [Serve.llm] Adapt vLLM change, use `enable_log_requests` if `disable_log_requests` is missing
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
Labels: go

#55497 [image] check gpu image with cuda directory
  docker/base-deps/Dockerfile
Labels: go

#55313 Add `orjson` as a dependency for release test images
  release/ray_release/byod/requirements_byod_3.9.in
Labels: go

#55479 [core] deflake test_actors::test_kill_actor_gcs
  python/ray/dashboard/modules/reporter/tests/test_actors.py
Labels: go

#55514 [llm] add grpcio-tools into the depset
  ci/compile_llm_requirements.sh
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu128.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu128.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu128.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu128.txt
Labels: go

#55478 Remove ref to deleted panel in Ray Data metrics
  python/ray/dashboard/client/src/pages/metrics/Metrics.tsx
Labels: go

#55515 [core][obs-clean/01] de-static object_store_available_memory metric
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/object_manager.h
  src/ray/stats/metric_defs.h
Labels: go

#55504 [ci] raydepsets: storing build arg set name in depset
  ci/raydepsets/tests/test_cli.py
  ci/raydepsets/workspace.py
Labels: go

#55375 Switch to installing ``bazelisk`` binary instead of installing from ``npm``
  ci/build/build-manylinux-forge.sh
Labels: core, ci-test, go, community-contribution

#55489 [Data] Update streaming_exec test by removing upper bound on assertion
  python/ray/data/tests/test_streaming_executor.py
Labels: data, ci-test, go

#55509 [image] auto detect architecture type
  ci/docker/ray.cpu.base.aarch64.wanda.yaml
  ci/docker/ray.cuda.base.aarch64.wanda.yaml
  docker/base-deps/Dockerfile
Labels: go

#55508 [image] remove uninstall dask in base image
  docker/base-deps/Dockerfile
Labels: go

#55457 make get_current_servable_instance async
  python/ray/serve/_private/http_util.py
Labels: go

#55429 [data] Task metric improvements
  python/ray/dashboard/client/src/pages/metrics/Metrics.tsx
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/tests/test_stats.py
Labels: go

#55536 [ci] base image: move cpu base up
  .buildkite/_forge.rayci.yml
Labels: go

#55493 Add Operator as filter to data grafana dashboard
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/data_grafana_dashboard_base.json
Labels: go

#54821 [Data] decrease parquet metadata storage usage
  python/ray/data/datasource/parquet_meta_provider.py
Labels: data, go, community-contribution

#55522 [serve] Add concurrencies option to serve microbenchmarks
  release/serve_tests/workloads/microbenchmarks.py
Labels: go

#55538 [serve.llm] Serialize ChatCompletionRequest tool_calls ValidatorIterator object
  python/ray/llm/_internal/serve/deployments/routers/router.py
  python/ray/llm/tests/serve/cpu/deployments/routers/test_router.py
Labels: go

#55503 [data] make hash shuffling resource usage calculation faster
  python/ray/data/_internal/execution/operators/hash_shuffle.py
Labels: go

#55525 [ci] Shorten bazel directory paths to avoid failures on Windows
  WORKSPACE
  bazel/gen_extract.py
  bazel/jemalloc.BUILD
  bazel/ray_deps_build_all.bzl
  bazel/ray_deps_setup.bzl
  ci/pipeline/test_conditional_testing.py
  ci/ray_ci/windows/build_ray.sh
  ci/raydepsets/testing_utils.py
  ci/raydepsets/tests/test_cli.py
  ci/raydepsets/tests/utils.py
  doc/external/test_hashes.py
  java/BUILD.bazel
  python/ray/serve/tests/unit/test_config.py
  python/ray/tests/test_traceback.py
  release/ray_release/bazel.py
  src/ray/core_worker/task_execution/test/BUILD.bazel
  src/ray/core_worker/task_submission/test/BUILD.bazel
  thirdparty/patches/grpc-zlib-fdopen.patch
  thirdparty/patches/prometheus-zlib-fdopen.patch
Labels: go

#55013 [docs] Add documentation for using type hints in Ray Core
  doc/source/ray-core/advanced-topics.rst
  doc/source/ray-core/type-hint.md
Labels: docs, core, go

#55573 [Serve.llm] Add missing data_parallel/__init__.py
  python/ray/llm/_internal/serve/deployments/data_parallel/__init__.py
Labels: go

#55207 [Train] Implement a JaxTrainer to support SPMD with TPUs
  python/ray/_private/accelerators/tpu.py
  python/ray/_private/resource_and_label_spec.py
  python/ray/tests/accelerators/test_tpu.py
  python/ray/train/v2/BUILD
  python/ray/train/v2/_internal/callbacks/__init__.py
  python/ray/train/v2/_internal/callbacks/tpu_reservation_callback.py
  python/ray/train/v2/_internal/execution/callback.py
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
  python/ray/train/v2/api/config.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/jax/__init__.py
  python/ray/train/v2/jax/config.py
  python/ray/train/v2/jax/jax_trainer.py
  python/ray/train/v2/tests/test_jax_trainer.py
Labels: train, go, community-contribution

#55561 [release test] remove "multi" test frequency
  release/ray_release/buildkite/settings.py
  release/ray_release/schema.json
  release/ray_release/tests/test_buildkite.py
  release/ray_release/tests/test_config.py
Labels: go

#54579 [Serve.llm] Add LMCacheConnectorV1 support for kv_transfer_config
  doc/source/cluster/kubernetes/examples/rayserve-deepseek-example.md
  doc/source/cluster/kubernetes/examples/rayserve-llm-example.md
  doc/source/serve/doc_code/pd_dissagregation/lmcache/mooncake.yaml
  doc/source/serve/doc_code/pd_dissagregation/lmcache/nixl/decoder.yaml
  doc/source/serve/doc_code/pd_dissagregation/lmcache/nixl/prefiller.yaml
  doc/source/serve/doc_code/pd_dissagregation/lmcache_mooncake_example.yaml
  doc/source/serve/doc_code/pd_dissagregation/lmcache_nixl_example.yaml
  doc/source/serve/doc_code/pd_dissagregation/nixl_example.yaml
  doc/source/serve/index.md
  doc/source/serve/llm/index.md
  doc/source/serve/llm/pd-dissagregation.md
  doc/source/serve/llm/quick-start.rst
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/kv_transfer_backends/__init__.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/kv_transfer_backends/base.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/kv_transfer_backends/lmcache_connector_v1.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/kv_transfer_backends/nixl_connector.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/prefill_decode_disagg/prefill_decode_disagg.py
  python/ray/llm/tests/serve/cpu/deployments/llm/vllm/kv_transfer_backends/__init__.py
  python/ray/llm/tests/serve/cpu/deployments/llm/vllm/kv_transfer_backends/test_lmcache_connector_v1.py
  python/ray/llm/tests/serve/cpu/deployments/llm/vllm/kv_transfer_backends/test_nixl_connector.py
  python/ray/llm/tests/serve/cpu/deployments/prefill_decode_disagg/test_prefill_decode_disagg.py
  python/ray/llm/tests/serve/gpu/deployments/llm/prefill_decode_disagg/test_prefill_decode_disagg_gpu.py
  release/llm_tests/serve/configs/lmcache/decoder.yaml
  release/llm_tests/serve/configs/lmcache/prefiller.yaml
  release/llm_tests/serve/configs/serve_llama_3dot1_8b_quantized_tp1_2p6d_lmcache.yaml
  release/ray_release/byod/byod_llm_lmcache_test.sh
  release/release_tests.yaml
Labels: serve, llm, go, community-contribution

#55571 [core][ci] Kill debug wheel step
  .buildkite/build.rayci.yml
Labels: go

#55513 [image] add base-extra layer
  .buildkite/_forge.rayci.yml
  .buildkite/release/build.rayci.yml
  ci/build/build-anyscale-docker.sh
  ci/docker/ray.cpu.base-extra.wanda.yaml
  ci/docker/ray.cuda.base-extra.wanda.yaml
  ci/ray_ci/anyscale_docker_container.py
  ci/ray_ci/builder.py
  ci/ray_ci/docker_container.py
  ci/ray_ci/ray_docker_container.py
  docker/base-extra/Dockerfile
Labels: go

#55125 [DOC][Tune] fix: remove extra space in tune documentation
  doc/source/tune/key-concepts.rst
Labels: tune, docs, go, community-contribution

#55581 [train] Change DEFAULT variables from strings to bools
  python/ray/train/v2/_internal/constants.py
Labels: go

#50994 Suppress type error
  python/ray/train/constants.py
Labels: train, go, community-contribution, unstale

#55505 [Data][LLM] Add FAQ to doc, explain STRICT_PACK strategy used in data.llm
  doc/source/data/working-with-llms.rst
Labels: go

#54824 add support for async inference
  doc/source/serve/api/index.md
  python/ray/serve/schema.py
  python/ray/serve/task_consumer.py
  python/ray/serve/task_processor.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_task_processor.py
  python/ray/serve/tests/unit/test_task_consumer.py
  python/requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu128.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu128.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu128.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu128.txt
  python/setup.py
Labels: go

#55589 [serve.llm] fix: improve error handling for invalid model_id
  python/ray/llm/_internal/serve/configs/server_models.py
Labels: go

#55570 [Doc][KubeRay] Add InteractiveMode description for `ray-job-quick-start.md`
  doc/source/cluster/kubernetes/getting-started/rayjob-quick-start.md
Labels: docs, core, go, community-contribution

#55604 [ci] remove unused `use_base_extra`
  ci/ray_ci/docker_container.py
Labels: go

#55599 [Core] Add Logic to Check Label Selector in PG Scheduling
  python/ray/tests/test_bundle_label_selector.py
  src/ray/raylet/scheduling/policy/scorer.cc
Labels: go

#55218 [serve.llm][docs] Documentation for prefix cache-aware router
  doc/source/llm/doc_code/serve/prefix_aware_router/prefix_aware_example.py
  doc/source/serve/llm/index.md
  doc/source/serve/llm/prefix-aware-request-router.md
  python/ray/llm/_internal/serve/request_router/prefix_aware/prefix_aware_router.py
Labels: go

#55588 [Serve.llm] Improve PrefixCacheAffinityRouter text normalization compat
  python/ray/llm/_internal/serve/request_router/prefix_aware/prefix_aware_router.py
  python/ray/llm/tests/serve/cpu/deployments/test_prefix_aware_request_router.py
Labels: go

#55580 [ci] read gce credentials file from global config when building anyscale images
  ci/ray_ci/anyscale_docker_container.py
  ci/ray_ci/test_anyscale_docker_container.py
Labels: go

#55577 [release] Script to build custom BYOD image
  release/BUILD.bazel
  release/ray_release/scripts/custom_byod_build.py
  release/ray_release/tests/test_custom_byod_build.py
Labels: go

#55592 [core][otel] change+simplify the feature flag for open telemetry
  python/ray/_private/ray_constants.py
  python/ray/dashboard/modules/reporter/reporter_agent.py
  python/ray/dashboard/modules/reporter/tests/test_reporter.py
  python/ray/tests/BUILD
  python/ray/tests/test_metric_cardinality.py
  python/ray/tests/test_metrics_agent.py
  python/ray/util/metrics.py
  release/release_tests.yaml
  src/ray/common/ray_config_def.h
  src/ray/stats/metric.cc
  src/ray/stats/metric.h
  src/ray/stats/stats.h
  src/ray/stats/tests/BUILD.bazel
Labels: go

#55621 [core] Fix ubsan for publisher_test
  src/ray/pubsub/test/publisher_test.cc
Labels: go

#55606 [ci] pipe through `RAYCI_DISABLE_JAVA` for manylinux base image building
  ci/build/build-manylinux-forge.sh
  ci/docker/manylinux.Dockerfile
  ci/docker/manylinux.aarch64.wanda.yaml
  ci/docker/manylinux.wanda.yaml
Labels: core, ci-test, go

#55626 [ci] upgrading uv binary and updating test (2/4)
  WORKSPACE
  ci/raydepsets/tests/test_cli.py
Labels: go

#54715 [ci] Add hook to clean the Ray address file before the test run starts
  python/ray/tests/conftest.py
Labels: go

#55629 [ci] release test: use rayci to perform test init
  .buildkite/release/config.yml
  .buildkite/release/test-init.sh
  .buildkite/release/test.rayci.yml
Labels: devprod, release-test, go

#55635 [serve] Refactor the router and handle
  python/ray/serve/_private/common.py
  python/ray/serve/_private/handle_options.py
  python/ray/serve/_private/local_testing_mode.py
  python/ray/serve/_private/replica_result.py
  python/ray/serve/_private/request_router/common.py
  python/ray/serve/_private/request_router/replica_wrapper.py
  python/ray/serve/_private/request_router/request_router.py
  python/ray/serve/_private/router.py
  python/ray/serve/handle.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/test_autoscaling_policy.py
  python/ray/serve/tests/unit/test_local_testing_mode.py
  python/ray/serve/tests/unit/test_pow_2_request_router.py
  python/ray/serve/tests/unit/test_router.py
Labels: serve, go

#55464 [serve] Add a function with a Warning to migrate constants that use `or` expression.
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/constants_utils.py
  python/ray/serve/tests/unit/test_constants_utils.py
Labels: serve, go, community-contribution

#55623 [Serve] Update test_http_routes to use get_application_url
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_http_routes.py
Labels: serve, ci-test, go

#55650 [serve] pin the version of wrk used in serve ci base
  ci/docker/serve.build.Dockerfile
Labels: serve, devprod, go
