Repository ray-project/ray, pull requests merged in 2025-05, with the labels that each got.

#52616 [data] Adding in batch inference mock pipeline release test
  python/requirements/ml/rllib-test-requirements.txt
  python/requirements_compiled.txt
  release/nightly_tests/dataset/autoscalling_100_gpu_compute.yaml
  release/nightly_tests/dataset/batch_inference_mock_image_pipeline.py
  release/ray_release/byod/requirements_ml_byod_3.9.in
  release/ray_release/byod/requirements_ml_byod_3.9.txt
  release/release_data_tests.yaml
Labels: go

#52712 [ci] re-enable import sorting for ray/serve
  .isort.cfg
  .pre-commit-config.yaml
  python/ray/serve/_private/api.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/controller_avatar.py
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/grpc_util.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/_private/replica.py
  python/ray/serve/_private/replica_scheduler/replica_wrapper.py
  python/ray/serve/_private/utils.py
  python/ray/serve/batching.py
  python/ray/serve/config.py
  python/ray/serve/deployment.py
  python/ray/serve/llm/__init__.py
  python/ray/serve/llm/openai_api_models.py
  python/ray/serve/tests/test_actor_replica_wrapper.py
  python/ray/serve/tests/test_backpressure.py
  python/ray/serve/tests/test_callback.py
  python/ray/serve/tests/test_handle_2.py
  python/ray/serve/tests/test_http_cancellation.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/test_metrics.py
  python/ray/serve/tests/test_multiplex.py
  python/ray/serve/tests/test_standalone.py
  python/ray/serve/tests/test_telemetry.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/serve/tests/unit/test_constants.py
  python/ray/serve/tests/unit/test_llm_imports.py
  python/ray/serve/tests/unit/test_pow_2_replica_scheduler.py
  python/ray/serve/tests/unit/test_router.py
  python/ray/serve/tests/unit/test_run_coroutine_threadsafe.py
Labels: go

#52711 [core] Add grpc server success and fail count metric
  src/ray/rpc/server_call.h
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: go

#52713 [Serve] Fix serve test_standalone_2 & test_standalone_3
  python/ray/serve/tests/test_standalone_2.py
  python/ray/serve/tests/test_standalone_3.py
  python/ray/tests/test_job.py
Labels: go

#44709 [Core] Fix potential log loss of tail_job_logs
  python/ray/dashboard/modules/job/job_manager.py
Labels: go

#52709 [train] add initial Train Grafana dashboard
  python/ray/dashboard/modules/metrics/dashboards/train_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/train_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/grafana_dashboard_factory.py
  python/ray/dashboard/modules/metrics/metrics_head.py
Labels: go

#52502 [Data] Add `PhysicalOperator.min_max_resource_usage_bounds`
  python/ray/data/BUILD
  python/ray/data/_internal/execution/interfaces/execution_options.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/_internal/execution/resource_manager.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/tests/test_actor_pool_map_operator.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_resource_manager.py
  python/ray/data/tests/test_task_pool_map_operator.py
Labels: go

#52717 [CI] Re-enable isort for `python/ray/train`
  .pre-commit-config.yaml
  python/ray/train/__init__.py
  python/ray/train/_internal/backend_executor.py
  python/ray/train/_internal/state/export.py
  python/ray/train/_internal/state/state_actor.py
  python/ray/train/base_trainer.py
  python/ray/train/context.py
  python/ray/train/lightgbm/__init__.py
  python/ray/train/tests/conftest.py
  python/ray/train/tests/test_backend.py
  python/ray/train/tests/test_state_export.py
  python/ray/train/tests/test_telemetry.py
  python/ray/train/torch/train_loop_utils.py
  python/ray/train/v2/_internal/callbacks/accelerators.py
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/_internal/execution/worker_group/__init__.py
  python/ray/train/v2/_internal/execution/worker_group/poll.py
  python/ray/train/v2/_internal/execution/worker_group/worker.py
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
  python/ray/train/v2/_internal/migration_utils.py
  python/ray/train/v2/_internal/state/export.py
  python/ray/train/v2/_internal/state/state_actor.py
  python/ray/train/v2/api/context.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/api/result.py
  python/ray/train/v2/api/train_fn_utils.py
  python/ray/train/v2/tests/test_accelerator_utils.py
  python/ray/train/v2/tests/test_controller.py
  python/ray/train/v2/tests/test_data_integration.py
  python/ray/train/v2/tests/test_persistence.py
  python/ray/train/v2/tests/test_report_handler.py
  python/ray/train/v2/tests/test_serialization.py
  python/ray/train/v2/tests/test_state.py
  python/ray/train/v2/tests/test_state_export.py
  python/ray/train/v2/tests/test_telemetry.py
  python/ray/train/v2/tests/test_v2_api.py
  python/ray/train/v2/tests/test_worker_group.py
  python/ray/train/v2/tests/util.py
Labels: go

#52721 reclassify test as medium
  python/ray/serve/tests/BUILD
Labels: go

#52664 [Data] Adding support for hash-shuffle based repartitioning and aggregations
  python/ray/_private/state.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/air/util/transform_pyarrow.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/_internal/execution/operators/hash_aggregate.py
  python/ray/data/_internal/execution/operators/hash_shuffle.py
  python/ray/data/_internal/logical/operators/all_to_all_operator.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_sort.py
  python/ray/data/tests/test_transform_pyarrow.py
  python/ray/tests/test_global_state.py
Labels: data, go

#52720 [data] Adding in fixed size test variants for new batch inference mock pipeline release tests
  release/nightly_tests/dataset/fixed_size_100_gpu_compute.yaml
  release/release_data_tests.yaml
Labels: go

#52617 [Data] Update user docs for default column names
  doc/source/data/loading-data.rst
  doc/source/data/working-with-images.rst
  doc/source/data/working-with-text.rst
Labels: docs, community-contribution

#52612 [Data] Speed up printing the schema
  doc/source/data/working-with-tensors.rst
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_mongo.py
  python/ray/data/tests/test_parquet.py
Labels: performance, data, go, community-contribution

#52727 [ci] add oss and doc tag for doc build on CI
  .buildkite/build.rayci.yml
Labels: go

#52706 [data.dashboard][logger/03] dataset logger for worker
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/logging.py
  python/ray/data/context.py
  python/ray/data/tests/test_logging_dataset.py
Labels: go

#52607 [Serve.llm] Add Ray Serve LLM vs. vLLM benchmark to nightly test
  release/llm_tests/serve/benchmark/benchmark_vllm.py
  release/llm_tests/serve/benchmark/bm.py
  release/llm_tests/serve/benchmark/common.py
  release/llm_tests/serve/benchmark/constants.py
  release/llm_tests/serve/benchmark/firehose_utils.py
  release/llm_tests/serve/benchmark/mocks.py
  release/llm_tests/serve/configs/model_config/llama_3dot1_8b_quantized_tp1.yaml
  release/llm_tests/serve/configs/serve_llama_3dot2_1b_s3.yaml
  release/llm_tests/serve/run_llm_serve_release_tests.py
  release/llm_tests/serve/test_utils.py
  release/ray_release/command_runner/command_runner.py
  release/release_tests.yaml
Labels: go, community-contribution

#52512 [Data]: fix write_parquet to allow row_group_size
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_parquet.py
Labels: data, go, community-contribution

#52735 [Core] Unify GcsAioClient and GcsClient
  python/ray/_private/gcs_aio_client.py
  python/ray/_private/gcs_utils.py
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/runtime_env/java_jars.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/py_modules.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/_private/state_api_test_utils.py
  python/ray/_raylet.pyx
  python/ray/dashboard/agent.py
  python/ray/dashboard/head.py
  python/ray/dashboard/modules/event/event_agent.py
  python/ray/dashboard/modules/event/tests/test_generate_export_events.py
  python/ray/dashboard/modules/job/common.py
  python/ray/dashboard/modules/job/job_agent.py
  python/ray/dashboard/modules/job/job_head.py
  python/ray/dashboard/modules/job/job_manager.py
  python/ray/dashboard/modules/job/job_supervisor.py
  python/ray/dashboard/modules/job/tests/conftest.py
  python/ray/dashboard/modules/job/tests/test_http_job_server.py
  python/ray/dashboard/modules/job/tests/test_job_manager.py
  python/ray/dashboard/modules/job/utils.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/reporter/healthz_agent.py
  python/ray/dashboard/modules/reporter/reporter_agent.py
  python/ray/dashboard/modules/reporter/reporter_head.py
  python/ray/dashboard/modules/reporter/utils.py
  python/ray/dashboard/modules/state/state_head.py
  python/ray/dashboard/modules/train/train_head.py
  python/ray/dashboard/subprocesses/module.py
  python/ray/dashboard/subprocesses/tests/utils.py
  python/ray/dashboard/utils.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_gcs_utils.py
  python/ray/tests/test_memory_pressure.py
  python/ray/tests/test_runtime_env_packaging.py
  python/ray/tests/test_runtime_env_working_dir.py
  python/ray/tests/test_state_api.py
  python/ray/util/state/state_manager.py
Labels: go

#52695 [core][refactor] Unify the code path for setting the task status of retrying tasks
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
Labels: go

#52737 [core] Rename event loop fields for consistency
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.h
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
Labels: go

#52744 [core] Shorten `test_gcs_fault_tolerance.py` test name
  python/ray/tests/test_gcs_fault_tolerance.py
Labels: go

#52753 Revert "[Data] Speed up printing the schema (#52612)"
  doc/source/data/working-with-tensors.rst
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_mongo.py
  python/ray/data/tests/test_parquet.py
Labels: go

#52655 [Serve.llm] Add router replicas and batch size to llm config
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/routers/router.py
  python/ray/llm/tests/serve/cpu/configs/test_models.py
  python/ray/llm/tests/serve/cpu/deployments/llm/vllm/test_vllm_engine.py
  python/ray/llm/tests/serve/cpu/deployments/routers/test_router.py
Labels: go

#52743 [core] Deflake and speed up `test_gcs_fault_tolerance.py`
  python/ray/tests/test_gcs_fault_tolerance.py
Labels: go

#52749 [core] Deflake `test_logging.py`
  python/ray/tests/test_logging.py
Labels: go

#52756 Fix typo in Ray Tune PyTorch Lightning docs
  doc/source/tune/examples/tune-pytorch-lightning.ipynb
Labels: go

#51744 [data] support new pyiceberg version
  python/ray/data/_internal/datasource/iceberg_datasink.py
  python/ray/data/_internal/datasource/iceberg_datasource.py
  python/requirements/ml/data-test-requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
Labels: data, go, community-contribution

#52574 [Data] support num_cpus, memory, concurrency, batch_size for preprocess
  python/ray/data/preprocessor.py
  python/ray/data/preprocessors/chain.py
  python/ray/data/tests/preprocessors/test_preprocessors.py
Labels: usability, data, go, community-contribution

#52728 [Data] Added support for Joins (using hash-shuffle)
  python/ray/data/BUILD
  python/ray/data/_internal/execution/operators/join.py
  python/ray/data/_internal/logical/operators/join_operator.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/aggregate.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_join.py
Labels: go

#52740 [core] Remove `worker_context_` dependency from the task receiver
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
Labels: go

#52355 [train] add XGBoostTrainer user guide
  doc/source/train/doc_code/xgboost_quickstart.py
  doc/source/train/examples/xgboost/distributed-xgboost-lightgbm.ipynb
  doc/source/train/getting-started-xgboost.rst
  doc/source/train/train.rst
Labels: go

#52742 [CI] Combine "as" imports for isort
  pyproject.toml
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/client.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/config.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deployment_info.py
  python/ray/serve/_private/long_poll.py
  python/ray/serve/llm/__init__.py
  python/ray/serve/llm/openai_api_models.py
  python/ray/serve/tests/test_long_poll.py
  python/ray/serve/tests/unit/test_application_state.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/train/_internal/state/export.py
  python/ray/train/tests/test_horovod_trainer.py
  python/ray/train/tests/test_state_export.py
  python/ray/train/v2/_internal/state/export.py
  python/ray/train/v2/api/config.py
  python/ray/train/v2/lightning/lightning_utils.py
  python/ray/train/v2/tests/test_v2_api.py
Labels: go

#52741 [core] Remove usages of vestigial "direct" call terminology
  src/mock/ray/core_worker/core_worker.h
  src/mock/ray/raylet/worker.h
  src/mock/ray/raylet_client/raylet_client.h
  src/mock/ray/rpc/worker/core_worker_client.h
  src/ray/core_worker/context.cc
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/core_worker/transport/scheduling_util.cc
  src/ray/gcs/gcs_server/test/gcs_server_test_util.h
  src/ray/protobuf/core_worker.proto
  src/ray/raylet/format/node_manager.fbs
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
  src/ray/raylet_client/raylet_client.cc
  src/ray/raylet_client/raylet_client.h
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: go

#51884 [Test][KubeRay] Add doctests for Kuberay Autoscaling
  doc/source/cluster/kubernetes/doc_sanitize.cfg
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.ipynb
  doc/source/cluster/kubernetes/user-guides/configuring-autoscaling.md
Labels: core, go, community-contribution

#52764 [core] Further deflake `test_gcs_fault_tolerance.py`
  python/ray/tests/test_gcs_fault_tolerance.py
Labels: go

#52750 [core] Deflake `test_runtime_env_pip_and_conda_4.py`
  python/ray/tests/test_runtime_env_conda_and_pip.py
  python/ray/tests/test_runtime_env_conda_and_pip_4.py
Labels: go

#52782 feat: update banner copy
  doc/source/conf.py
Labels: go

#52251 [doc] add helpful issue link to development.rst
  doc/source/ray-contribute/development.rst
Labels: docs, go, community-contribution

#52785 [core] Skip `TestGC` on windows entirely
  python/ray/_private/test_utils.py
  python/ray/tests/test_runtime_env_working_dir_3.py
Labels: go

#52787 [core] Speed up `test_actor_retry2.py`
  python/ray/tests/BUILD
  python/ray/tests/test_actor_retry_1.py
  python/ray/tests/test_actor_retry_2.py
Labels: go

#52704 [core] Improvements for using RuntimeEnv in the Job Submission API.
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/validation.py
  python/ray/_private/runtime_env/working_dir.py
  python/ray/_private/utils.py
  python/ray/_private/worker.py
  python/ray/actor.py
  python/ray/dashboard/modules/job/sdk.py
  python/ray/dashboard/modules/job/tests/test_job_manager.py
  python/ray/dashboard/modules/job/tests/test_sdk.py
  python/ray/job_config.py
  python/ray/remote_function.py
  python/ray/runtime_env/runtime_env.py
  python/ray/tests/test_ray_init.py
  python/ray/tests/test_runtime_env.py
  python/ray/tests/test_runtime_env_validation.py
  python/ray/tests/test_runtime_env_working_dir_3.py
Labels: go

#52640 [Core] Replace PythonGcsPublisher with GcsClient
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/log_monitor.py
  python/ray/_private/process_watcher.py
  python/ray/_private/runtime_env/agent/main.py
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/utils.py
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/autoscaler/_private/monitor.py
  python/ray/dashboard/agent.py
  python/ray/dashboard/dashboard.py
  python/ray/dashboard/modules/reporter/reporter_agent.py
  python/ray/includes/common.pxd
  python/ray/includes/common.pxi
  python/ray/includes/gcs_client.pxi
  python/ray/tests/test_failure.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_gcs_pubsub.py
  python/ray/tests/test_placement_group.py
  python/ray/util/state/state_manager.py
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_client/accessor.h
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_client/gcs_client.h
  src/ray/gcs/pubsub/gcs_pub_sub.cc
  src/ray/gcs/pubsub/gcs_pub_sub.h
  src/ray/rpc/gcs_server/gcs_rpc_client.h
Labels: go

#52731 [data] Tweak mock pipeline to avoid deadlock
  release/nightly_tests/dataset/batch_inference_mock_image_pipeline.py
Labels: go

#52329 [Core] Add the Proto Message for the New Event Schemas
  src/ray/protobuf/common.proto
  src/ray/protobuf/events/base.proto
  src/ray/protobuf/events/task_events/actor_task_definition_event.proto
  src/ray/protobuf/events/task_events/actor_task_execution_event.proto
  src/ray/protobuf/events/task_events/task_definition_event.proto
  src/ray/protobuf/events/task_events/task_execution_event.proto
Labels: go

#52261 [Core] log more information about bad metric tag keys and values in metrics agent
  python/ray/_private/metrics_agent.py
  python/ray/tests/test_metrics_agent_2.py
Labels: core, go, community-contribution

#52797 [CI] Update debug wheel instance_type from medium to large
  .buildkite/build.rayci.yml
Labels: go

#52689 [release] Upgrade twine to 6.1.0 and skip python 3.13 wheel for Windows
  ci/ray_ci/automation/ray_wheels_lib.py
  ci/ray_ci/automation/test_ray_wheels_lib.py
  release/requirements_buildkite.in
  release/requirements_buildkite.txt
Labels: go

#51901 Add label selector scheduling logic to Cluster Resource Manager
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/includes/common.pxd
  python/ray/remote_function.py
  python/ray/tests/BUILD
  python/ray/tests/test_label_scheduling.py
  src/ray/common/BUILD
  src/ray/common/scheduling/cluster_resource_data.cc
  src/ray/common/scheduling/cluster_resource_data.h
  src/ray/common/scheduling/label_selector.cc
  src/ray/common/scheduling/label_selector.h
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/common/test/BUILD
  src/ray/common/test/label_selector_test.cc
  src/ray/core_worker/common.h
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/protobuf/common.proto
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_resource_scheduler.cc
  src/ray/raylet/scheduling/cluster_resource_scheduler.h
  src/ray/raylet/scheduling/cluster_resource_scheduler_test.cc
Labels: core, go, community-contribution

#51567 Update observability.md
  doc/source/cluster/kubernetes/user-guides/observability.md
Labels: core, go, community-contribution

#52518 [data.dashboard.x][05] persist task labels into task export events
  python/ray/dashboard/modules/event/tests/test_export_task.py
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/gcs/pb_util.h
  src/ray/protobuf/export_api/export_task_event.proto
Labels: go

#52783 [core] Speed up, split, and deflake `test_multiprocessing.py`
  python/ray/_private/test_utils.py
  python/ray/serve/tests/test_standalone.py
  python/ray/tests/BUILD
  python/ray/tests/conftest.py
  python/ray/tests/test_advanced_9.py
  python/ray/tests/test_gcs_fault_tolerance.py
  python/ray/tests/test_gcs_utils.py
  python/ray/tests/test_joblib.py
  python/ray/tests/test_multiprocessing.py
  python/ray/tests/test_multiprocessing_standalone.py
  python/ray/tests/test_ray_init.py
  python/ray/tests/test_redis_tls.py
  python/ray/tests/test_runtime_env_plugin.py
  python/ray/util/multiprocessing/pool.py
Labels: go

#52811 [data.llm] Made batch tests medium to resolve flakiness in batch tests
  python/ray/llm/tests/BUILD
Labels: go

#52604 [RLlib] Examples folder do-over (vol 50): Multi-agent connector pipeline mapping global obs space to different obs spaces for different modules.
  doc/source/rllib/rllib-examples.rst
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/env/vector/sync_vector_multi_agent_env.py
  rllib/examples/connectors/classes/multi_agent_with_different_observation_spaces.py
  rllib/examples/connectors/frame_stacking.py
  rllib/examples/connectors/mean_std_filtering.py
  rllib/examples/connectors/multi_agent_with_different_observation_spaces.py
  rllib/examples/envs/classes/multi_agent/double_row_corridor_env.py
  rllib/examples/multi_agent/multi_agent_cartpole.py
Labels: rllib, rllib-connectorv2, rllib-docs-or-examples, go

#52748 [data] fix working code snippets
  doc/source/data/inspecting-data.rst
  doc/source/data/working-with-tensors.rst
  doc/source/ray-contribute/writing-code-snippets.rst
  python/ray/data/_internal/plan.py
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_mongo.py
  python/ray/data/tests/test_parquet.py
Labels: go

#52718 [RLlib; Offline RL] Add GPU-inference to offline evaluation.
  rllib/BUILD
  rllib/algorithms/algorithm_config.py
  rllib/offline/offline_evaluation_runner.py
  rllib/tuned_examples/bc/cartpole_bc_with_offline_evaluation.py
  rllib/utils/runners/runner.py
Labels: go

#52665 Fix triton server doc
  doc/source/serve/tutorials/triton-server-integration.md
Labels: serve, docs, go

#52587 [Data] user column names read api doc changes
  doc/source/data/loading-data.rst
  doc/source/data/working-with-images.rst
  doc/source/data/working-with-text.rst
  python/ray/data/read_api.py
Labels: usability, data, go, community-contribution

#52700 [Fix][Core] Close unused pipe file descriptor of child processes of Raylet
  python/ray/dashboard/modules/job/tests/test_sdk.py
  src/ray/common/client_connection.cc
  src/ray/util/process.cc
  src/ray/util/process.h
Labels: go

#52766 [Serve.llm] Mitigate the serve.llm streaming overhead by properly batching stream chunks
  python/ray/llm/_internal/serve/deployments/llm/llm_server.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/routers/router.py
  python/ray/llm/_internal/serve/deployments/utils/batcher.py
  python/ray/llm/_internal/serve/deployments/utils/server_utils.py
  python/ray/llm/tests/serve/cpu/deployments/llm/test_llm_server.py
  python/ray/llm/tests/serve/cpu/deployments/llm/vllm/test_vllm_engine.py
  python/ray/llm/tests/serve/cpu/deployments/utils/test_batcher.py
Labels: go

#52730 upgrade pyarrow-hotfix to 0.7
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  python/requirements_compiled.txt
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: go

#52800 Add perf metrics for 2.46.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#52754 [Data] Disable blocking pipeline by default until Actor Pool fully scales up to min actors
  python/ray/data/_internal/compute.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/hash_shuffle.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/context.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_executor_resource_management.py
  python/ray/data/tests/test_json.py
  python/ray/data/tests/test_operators.py
Labels: go

#52807 [ray.data.llm] Lazy import engines in stages
  python/ray/llm/_internal/batch/stages/sglang_engine_stage.py
  python/ray/llm/_internal/batch/stages/vllm_engine_stage.py
  python/ray/llm/tests/batch/cpu/stages/test_chat_template_stage.py
  python/ray/llm/tests/batch/gpu/stages/test_sglang_engine_stage.py
Labels: go

#52818 [RLlib] Fix bug in `split_and_zero_pad` utility function (related to complex structures vs simple values or np.arrays).
  rllib/utils/postprocessing/zero_padding.py
Labels: go

#52780 [Dashboard] Add `flush()` after `job_id` is populated
  python/ray/dashboard/modules/job/cli.py
Labels: go

#52703 [core] Fix race condition when canceling task that hasn't started yet
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_actor_cancel.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/core_worker/transport/task_receiver.h
Labels: go

#47561 [Doc][KubeRay] Document Fields that Will Not Trigger Downtime in RayService
  doc/source/cluster/kubernetes/user-guides/rayservice.md
Labels: triage, docs, kuberay, go, community-contribution

#51052 [Misc]cupy.cuda.nccl.get_unique_id() generic modification.
  python/ray/experimental/channel/nccl_group.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
Labels: core, go, community-contribution

#52826 [docstring] fix indentation of note for Dataset.repartition
  python/ray/data/dataset.py
Labels: go

#52838 [release test] fix twine version contraint in setup.py
  release/setup.py
Labels: go

#52827 [data] fix test_logging_dataset timedout flakiness
  python/ray/data/_internal/logging.py
  python/ray/data/tests/test_logging_dataset.py
Labels: go

#52843 [core] Correctly release dynamic generator refs
  python/ray/_private/object_ref_generator.py
  python/ray/_raylet.pyx
  python/ray/tests/test_generators.py
Labels: go

#52776 [core] `RAY_task_retry_delay_ms` has already been publicly documented
  src/ray/core_worker/task_manager.cc
Labels: go

#52814 [Docs] Update Volcano Integration with The New Flag
  doc/source/cluster/kubernetes/k8s-ecosystem/volcano.md
Labels: go, community-contribution

#52833 [core][refactor] No need to resend out of order completed tasks
  src/ray/core_worker/test/actor_submit_queue_test.cc
  src/ray/core_worker/test/direct_actor_transport_test.cc
  src/ray/core_worker/transport/actor_submit_queue.h
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.h
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.h
Labels: go

#52421 [train] Add option to configure Ray Train worker actor runtime env
  python/ray/train/v2/_internal/constants.py
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
  python/ray/train/v2/api/config.py
  python/ray/train/v2/tests/test_worker_group.py
Labels: go

#52836 [spark] Fix error message for Ray-on-Spark launch
  python/ray/util/spark/cluster_init.py
Labels: go, community-contribution

#52847 [docstring][core] fixed indentation errors in docstrings
  ci/ray_ci/doc/autodoc.py
  python/ray/autoscaler/_private/resource_demand_scheduler.py
  python/ray/autoscaler/command_runner.py
  python/ray/client_builder.py
  python/ray/dag/tests/experimental/test_dag_visualization.py
  python/ray/tests/kuberay/utils.py
  python/ray/tests/test_autoscaler.py
  python/ray/util/collective/collective.py
  python/ray/workflow/http_event_provider.py
  python/ray/workflow/workflow_access.py
Labels: docs, core, go

#52852 [data] Fix backpressure for FileBasedDatasource
  python/ray/data/datasource/file_based_datasource.py
Labels: go

#52851 [data] replace np.array to np.asarray
  doc/source/data/doc_code/custom_datasource_example.py
  doc/source/data/working-with-images.rst
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/_internal/datasource/image_datasource.py
  python/ray/data/_internal/numpy_support.py
Labels: go

#52842 [docstring][llm] fixing indent errors in docstrings
  python/ray/llm/_internal/batch/stages/base.py
  python/ray/llm/_internal/batch/stages/chat_template_stage.py
Labels: docs, llm, go

#52848 [Serve.llm][Bugfix] in stream batching, first part of the stream was always consumed and not streamed back from the router
  python/ray/llm/_internal/serve/deployments/routers/router.py
  python/ray/llm/tests/serve/cpu/deployments/llm/test_llm_server.py
  python/ray/llm/tests/serve/cpu/deployments/routers/test_router.py
Labels: go

#52841 [docstring][serve] Fix indentation in doc strings.
  python/ray/serve/_private/application_state.py
  python/ray/serve/_private/common.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/grpc_util.py
  python/ray/serve/tests/test_metrics.py
Labels: serve, docs, go

#52844 [docstring][data] fix indentation errors in docstrings
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/_internal/execution/operators/map_transformer.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/numpy_support.py
  python/ray/data/_internal/stats.py
  python/ray/data/_internal/table_block.py
  python/ray/data/datasource/datasink.py
Labels: docs, data, go

#52853 [Serve.llm] Bugfix for duplication of `<bos>` token
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/tests/serve/cpu/deployments/llm/multiplex/test_multiplex_deployment.py
Labels: go

#52856 [core][refactor] Remove skip_execution
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/protobuf/common.proto
Labels: go

#52855 [docstring][train] fix indentation errors in docstrings
  python/ray/air/_internal/config.py
  python/ray/air/util/tensor_extensions/arrow.py
  python/ray/train/_internal/worker_group.py
  python/ray/train/predictor.py
  python/ray/train/v2/_internal/execution/storage.py
  python/ray/train/v2/_internal/logging/logging.py
Labels: docs, train, go

#52857 [core][chore] Correct `num_retries_left` and `num_oom_retries_left` in the log
  src/ray/core_worker/task_manager.cc
Labels: go

#52834 [RLlib] Add extra `self.stopped` check to APPO/IMPALA Learner (in case learner thread should stop while waiting for queue).
  rllib/algorithms/impala/impala_learner.py
Labels: go

#52849 [docstring][rllib] fix indentation errors in docstrings
  rllib/algorithms/dqn/default_dqn_rl_module.py
  rllib/algorithms/dqn/torch/default_dqn_torch_rl_module.py
  rllib/algorithms/impala/impala_tf_policy.py
  rllib/benchmarks/torch_compile/utils.py
  rllib/connectors/connector.py
  rllib/env/multi_agent_episode.py
  rllib/env/single_agent_episode.py
  rllib/evaluation/collectors/agent_collector.py
  rllib/execution/minibatch_buffer.py
  rllib/offline/estimators/off_policy_estimator.py
  rllib/policy/policy.py
  rllib/policy/policy_template.py
  rllib/policy/tf_policy_template.py
  rllib/utils/metrics/utils.py
  rllib/utils/replay_buffers/fifo_replay_buffer.py
  rllib/utils/replay_buffers/multi_agent_mixin_replay_buffer.py
  rllib/utils/replay_buffers/multi_agent_prioritized_replay_buffer.py
  rllib/utils/replay_buffers/multi_agent_replay_buffer.py
  rllib/utils/replay_buffers/prioritized_replay_buffer.py
Labels: rllib, docs, go

#52752 fix grafana dashboards dropdowns for data and train dashboard
  python/ray/dashboard/modules/metrics/dashboards/data_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/dashboards/train_grafana_dashboard_base.json
Labels: go

#52770 [core] `SetTaskStatus` should only be called within the same lock scope where `task_entry` is retrieved
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
Labels: go

#52806 [Data] Fix internal queues accounting for all Operators w/ an internal queue
  python/ray/data/_internal/execution/autoscaler/default_autoscaler.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/base_physical_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/output_splitter.py
  python/ray/data/_internal/execution/operators/union_operator.py
  python/ray/data/_internal/execution/operators/zip_operator.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_autoscaler.py
  python/ray/data/tests/test_map.py
  python/ray/data/tests/test_operators.py
Labels: go

#50415 [tune] Remove loguniform's base
  doc/source/tune/examples/tune-xgboost.ipynb
  python/ray/tune/search/hebo/hebo_search.py
  python/ray/tune/search/nevergrad/nevergrad_search.py
  python/ray/tune/search/sample.py
  python/ray/tune/tests/test_var.py
Labels: tune, go, community-contribution

#52875 [pydoclint] dashboard docstring minimal format errors
  python/ray/dashboard/modules/log/log_manager.py
  python/ray/dashboard/modules/reporter/reporter_head.py
Labels: go

#52548 Handle non-contiguous Tensors based GPU transfer
  python/ray/air/_internal/torch_utils.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/collate_fn.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_iterator.py
  python/ray/train/BUILD
  python/ray/train/tests/test_iter_torch_batches_gpu.py
  release/train_tests/benchmark/image_classification/factory.py
  release/train_tests/benchmark/ray_dataloader_factory.py
Labels: go

#52878 [pydoclint] train docstring minimal format errors
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
Labels: go

#52876 [pydoclint] llm docstring minimal format errors
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
Labels: go

#52877 [pydoclint] serve docstring minimal format errors
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/proxy_response_generator.py
  python/ray/serve/_private/storage/kv_store.py
  python/ray/serve/context.py
Labels: go

#52879 [pydoclint] tune docstring minimal format errors
  python/ray/tune/examples/hyperopt_conditional_search_space_example.py
  python/ray/tune/integration/pytorch_lightning.py
  python/ray/tune/registry.py
Labels: go

#52881 [pydoclint] workflow docstring minimal format errors
  python/ray/workflow/http_event_provider.py
Labels: go

#52873 [pydoclint] core/autoscaler docstring minimal format errors
  python/ray/autoscaler/_private/aws/config.py
  python/ray/autoscaler/_private/command_runner.py
  python/ray/autoscaler/_private/kuberay/utils.py
  python/ray/autoscaler/node_provider.py
  python/ray/autoscaler/sdk/sdk.py
  python/ray/autoscaler/v2/autoscaler.py
Labels: go

#52883 [pydoclint] data docstring minimal format errors
  python/ray/data/_internal/execution/interfaces/executor.py
  python/ray/data/_internal/numpy_support.py
  python/ray/data/dataset.py
  python/ray/data/preprocessor.py
Labels: go

#52882 [tune][train] update test_train_v2_integration to use correct RunConfig
  python/ray/tune/tests/test_train_v2_integration.py
Labels: go

#52880 [pydoclint] util docstring minimal format errors
  python/ray/util/client/worker.py
  python/ray/util/state/api.py
  python/ray/util/state/state_cli.py
  python/ray/util/state/state_manager.py
Labels: go

#52872 [pydoclint] core/_private docstring minimal format fixes
  python/ray/_private/external_storage.py
  python/ray/_private/node.py
  python/ray/_private/resource_isolation_config.py
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/runtime_env/mpi.py
  python/ray/_private/runtime_env/packaging.py
  python/ray/_private/runtime_env/plugin.py
  python/ray/_private/runtime_env/protocol.py
  python/ray/_private/runtime_env/uri_cache.py
  python/ray/_private/services.py
  python/ray/_private/storage.py
  python/ray/_private/test_utils.py
  python/ray/_private/usage/usage_lib.py
Labels: go

#52884 [core] Label selector enum as class to fix windows build
  src/ray/common/scheduling/cluster_resource_data.cc
  src/ray/common/scheduling/label_selector.cc
  src/ray/common/scheduling/label_selector.h
  src/ray/common/test/label_selector_test.cc
Labels: go

#52887 [core] [docs] Dynamic generator deprecation
  doc/source/ray-core/ray-generator.rst
  doc/source/ray-core/tasks.rst
  doc/source/ray-core/tasks/dynamic_generators.rst
Labels: go

#52575 [core] Implement a thread pool and call the CPython API on all threads within the same concurrency group
  python/ray/tests/test_concurrency_group.py
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/fiber.h
  src/ray/core_worker/test/BUILD.bazel
  src/ray/core_worker/test/thread_pool_test.cc
  src/ray/core_worker/transport/concurrency_group_manager.cc
  src/ray/core_worker/transport/concurrency_group_manager.h
  src/ray/core_worker/transport/thread_pool.cc
  src/ray/core_worker/transport/thread_pool.h
Labels: go

#52710 [core] Raylet Node Manager RPC Failure Documentation
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc
  src/ray/protobuf/node_manager.proto
Labels: go

#52885 ImageDatasource::_read_stream Avoid unnecessary resize and convert
  python/ray/data/_internal/datasource/image_datasource.py
Labels: go

#52910 [Data] Remove metadata line causing OOM with IterableDataset
  python/ray/data/_internal/datasource/torch_datasource.py
Labels: data, go

#52903 [data][llm] fix: remove-no-longer needed guided decoding vllm v0 constraint
  python/ray/llm/_internal/batch/stages/vllm_engine_stage.py
Labels: go

#50649 [chore] Delete unused build.sh
  build.sh
  ci/pipeline/test_rules.txt
Labels: build, go

#52890 [Doc] Update configure-manage-dashboard.md
  doc/source/cluster/configure-manage-dashboard.md
Labels: go

#52773 [NFC] Fix simple typo in `rllib/evaluation/collectors/agent_collector.py`
  rllib/evaluation/collectors/agent_collector.py
Labels: community-contribution

#52828 [Data] Cleaning up Executor shutdown sequence
  python/ray/data/_internal/execution/streaming_executor.py
Labels: go

#52912 [train][doc] Remove unused configuration-overview page
  doc/source/train/huggingface-accelerate.rst
  doc/source/train/user-guides/configuration-overview.rst
Labels: go

#52907 remove anyscale navbar on docs.ray.io
  doc/source/_templates/navbar-anyscale.html
  doc/source/conf.py
Labels: go

#52790 [core] Record grpc client failures
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/experimental_mutable_object_provider.cc
  src/ray/gcs/gcs_client/gcs_client.cc
  src/ray/gcs/gcs_server/gcs_server.cc
  src/ray/gcs/gcs_server/test/gcs_server_rpc_test.cc
  src/ray/object_manager/object_manager.cc
  src/ray/object_manager/ownership_object_directory.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/worker_pool_test.cc
  src/ray/rpc/client_call.h
  src/ray/rpc/metrics_agent_client.h
  src/ray/rpc/server_call.h
  src/ray/rpc/test/grpc_server_client_test.cc
  src/ray/stats/metric_defs.cc
  src/ray/stats/metric_defs.h
Labels: go

#52925 [release] support using any dir in the repo as working dir
  doc/BUILD
  release/BUILD.bazel
  release/ray_release/bazel.py
  release/ray_release/glue.py
  release/ray_release/template.py
Labels: go

#52342 entity recognition with LLMs
  .vale/styles/Google/vocab.txt
  .vale/styles/config/vocabularies/General/accept.txt
  ci/lint/check-documentation-style.sh
  doc/source/conf.py
  doc/source/index.rst
  doc/source/ray-overview/examples.rst
  doc/source/ray-overview/examples/entity-recognition-with-llms/README.ipynb
  doc/source/ray-overview/examples/entity-recognition-with-llms/README.md
  doc/source/ray-overview/examples/entity-recognition-with-llms/ci/aws.yaml
  doc/source/ray-overview/examples/entity-recognition-with-llms/ci/build.sh
  doc/source/ray-overview/examples/entity-recognition-with-llms/ci/gce.yaml
  doc/source/ray-overview/examples/entity-recognition-with-llms/ci/tests.sh
  doc/source/ray-overview/examples/entity-recognition-with-llms/clear_cell_nums.py
  doc/source/ray-overview/examples/entity-recognition-with-llms/configs/aws.yaml
  doc/source/ray-overview/examples/entity-recognition-with-llms/configs/gce.yaml
  doc/source/ray-overview/examples/entity-recognition-with-llms/containerfile
  doc/source/ray-overview/examples/entity-recognition-with-llms/images/data_dashboard.png
  doc/source/ray-overview/examples/entity-recognition-with-llms/images/data_llm.png
  doc/source/ray-overview/examples/entity-recognition-with-llms/images/e2e_llm.png
  doc/source/ray-overview/examples/entity-recognition-with-llms/images/loss.png
  doc/source/ray-overview/examples/entity-recognition-with-llms/images/serve_dashboard.png
  doc/source/ray-overview/examples/entity-recognition-with-llms/images/serve_llm.png
  doc/source/ray-overview/examples/entity-recognition-with-llms/images/train_dashboard.png
  doc/source/ray-overview/examples/entity-recognition-with-llms/lora_sft_ray.yaml
  doc/source/ray-overview/examples/index.rst
  doc/source/train/examples/pytorch/convert_existing_pytorch_code_to_ray_train.ipynb
  release/ray_release/byod/byod_llm_ner.sh
  release/release_tests.yaml
Labels: llm, go

#52916 Fix uv run when use with vllm's Ray backend
  python/ray/_private/runtime_env/uv_runtime_env_hook.py
  python/ray/tests/test_runtime_env_uv_run.py
Labels: go

#52823 [ray.data.llm] Unify fields in SGLang and vLLM config
  python/ray/llm/_internal/batch/processor/base.py
  python/ray/llm/_internal/batch/processor/sglang_engine_proc.py
  python/ray/llm/_internal/batch/processor/vllm_engine_proc.py
  python/ray/llm/tests/batch/gpu/processor/test_sglang_engine_proc.py
  python/ray/llm/tests/batch/gpu/processor/test_vllm_engine_proc.py
Labels: data, llm, go, community-contribution

#52821 docs: improve prometheus-grafana.md
  doc/source/cluster/kubernetes/k8s-ecosystem/prometheus-grafana.md
Labels: go, community-contribution

#52900 [Data] Add save modes to file data sinks
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/_internal/savemode.py
  python/ray/data/dataset.py
  python/ray/data/datasource/__init__.py
  python/ray/data/datasource/file_datasink.py
  python/ray/data/tests/test_parquet.py
Labels: go

#52801 [docs][tune]: fix import & replace `session.report` with `tune.report`
  doc/source/tune/doc_code/key_concepts.py
  doc/source/tune/key-concepts.rst
Labels: go, community-contribution

#52769 [core][autoscaler][v1] deflaky test_autoscaler
  python/ray/tests/test_autoscaler.py
Labels: go

#52942 [data] skip tfx-bsl tests on premerge
  .buildkite/data.rayci.yml
Labels: go

#52917 [train] bump test_torch_device_manager timeout
  python/ray/train/BUILD
Labels: go

#52943 [data] Remove unused allocated bytes panel and stat
  python/ray/dashboard/modules/metrics/dashboards/data_dashboard_panels.py
  python/ray/data/_internal/stats.py
Labels: go

#52850 Minor enhancements to Databricks Unity Datasource
  python/ray/data/_internal/datasource/databricks_uc_datasource.py
  python/ray/data/read_api.py
Labels: data, go, community-contribution

#52909 Train Tests: Disable cgroup isolation on head node for benchmarking
  release/train_tests/benchmark/compute_configs/compute_gpu_1x1_aws.yaml
  release/train_tests/benchmark/compute_configs/compute_gpu_1x1_multi_gpus_aws.yaml
Labels: go

#52747 [serve.llm] Prefix-aware scheduler [1/N] Adding Prefix-aware tree data structure
  python/ray/llm/_internal/serve/replica_scheduler/prefix_aware/prefix_tree.py
  python/ray/llm/tests/serve/cpu/deployments/test_prefix_tree.py
Labels: serve, performance, go

#52812 [Core] Use TaskAttempt as the unique id for inflight actor task
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/core_worker/test/BUILD.bazel
  src/ray/core_worker/test/actor_task_submitter_test.cc
  src/ray/core_worker/test/task_receiver_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
Labels: go

#52941 [deps] upgrade pyopenssl and cryptography
  python/requirements/ml/data-test-requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu124.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu124.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu124.txt
  release/ray_release/byod/requirements_byod_3.9.txt
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: go

#52805 [train] add TrainControllerState metrics
  python/ray/dashboard/modules/metrics/dashboards/train_dashboard_panels.py
  python/ray/train/v2/_internal/callbacks/metrics.py
  python/ray/train/v2/_internal/metrics/__init__.py
  python/ray/train/v2/_internal/metrics/base.py
  python/ray/train/v2/_internal/metrics/controller.py
  python/ray/train/v2/_internal/metrics/worker.py
  python/ray/train/v2/tests/test_metrics.py
Labels: go

#52824 [data] remove _collate_fn/_finallize_fn from public iter_batches API
  python/ray/data/dataset.py
  python/ray/data/iterator.py
  python/ray/data/tests/test_iterator.py
  rllib/utils/minibatch_utils.py
Labels: go

#52918 [data] log execution of map tasks
  python/ray/data/_internal/execution/interfaces/task_context.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/_internal/execution/operators/base_physical_operator.py
  python/ray/data/_internal/execution/operators/map_operator.py
  python/ray/data/_internal/execution/operators/task_pool_map_operator.py
  python/ray/data/tests/test_bigquery.py
  python/ray/data/tests/test_clickhouse.py
Labels: go

#52919 Train Tests: Fix custom collate fn; Add Dataset creation Time
  release/release_tests.yaml
  release/train_tests/benchmark/config.py
  release/train_tests/benchmark/factory.py
  release/train_tests/benchmark/image_classification/factory.py
  release/train_tests/benchmark/runner.py
  release/train_tests/benchmark/torch_dataloader_factory.py
  release/train_tests/benchmark/train_benchmark.py
Labels: go

#52722 [core] Metric recording improvement
  python/ray/includes/metric.pxi
  src/ray/common/asio/instrumented_io_context.cc
  src/ray/common/asio/instrumented_io_context.h
  src/ray/common/event_stats.cc
  src/ray/common/event_stats.h
  src/ray/rpc/client_call.h
  src/ray/stats/metric.cc
  src/ray/stats/metric.h
Labels: go

#52951 [deps] upgrade requests/starlette/jinja2
  python/requirements/ml/core-requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu124.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu124.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu124.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu124.txt
  release/ray_release/byod/requirements_byod_3.9.txt
  release/ray_release/byod/requirements_ml_byod_3.9.txt
Labels: go

#51639 [RLlib] MetricsLogger + Stats overhaul.
  doc/source/rllib/metrics-logger.rst
  rllib/BUILD
  rllib/algorithms/algorithm.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/sac/torch/sac_torch_learner.py
  rllib/core/learner/learner.py
  rllib/examples/evaluation/custom_evaluation.py
  rllib/examples/learners/classes/vpg_torch_learner.py
  rllib/tuned_examples/impala/heavy_cartpole_impala.py
  rllib/utils/metrics/metrics_logger.py
  rllib/utils/metrics/stats.py
  rllib/utils/metrics/tests/test_metrics_logger.py
  rllib/utils/metrics/tests/test_stats.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
Labels: rllib, rllib-logging, go

#52719 Expose vLLM Metrics to serve.llm API
  doc/source/serve/llm/images/serve_llm_dashboard.png
  doc/source/serve/llm/serving-llms.rst
  python/ray/dashboard/modules/metrics/dashboards/common.py
  python/ray/dashboard/modules/metrics/dashboards/serve_llm_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/serve_llm_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/grafana_dashboard_factory.py
  python/ray/dashboard/modules/metrics/metrics_head.py
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_loggers.py
  python/ray/llm/_internal/serve/deployments/utils/metrics_utils.py
Labels: serve, usability, go, community-contribution

#52901 Update refresh behavior to refresh on page load only
  python/ray/dashboard/modules/metrics/dashboards/default_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/dashboards/serve_deployment_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/dashboards/serve_grafana_dashboard_base.json
  python/ray/dashboard/modules/metrics/dashboards/train_grafana_dashboard_base.json
Labels: go

#47941 [Azure][Cluster] Check tags when provided
  python/ray/autoscaler/_private/_azure/node_provider.py
Labels: core, go, community-contribution

#52974 Adds pydoclint to pre-commit
  .pre-commit-config.yaml
  ci/lint/lint.sh
  ci/lint/pydoclint-baseline.txt
Labels: go

#52922 [tune] [docs] remove graphic cards
  doc/source/tune/tutorials/overview.rst
  doc/source/tune/tutorials/tune-trial-checkpoints.rst
Labels: tune, docs, go

#52972 [core][refactor] Rename `ActorCounter` to `SequenceNumber`
  cpp/src/ray/runtime/task/invocation_spec.h
  cpp/src/ray/runtime/task/local_mode_task_submitter.cc
  src/ray/common/task/task_spec.cc
  src/ray/common/task/task_spec.h
  src/ray/common/task/task_util.h
  src/ray/core_worker/actor_handle.cc
  src/ray/core_worker/test/actor_submit_queue_test.cc
  src/ray/core_worker/test/actor_task_submitter_test.cc
  src/ray/core_worker/test/task_receiver_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/protobuf/common.proto
Labels: go

#52921 [Core] Add Event Aggregator GRPC Server Definition
  BUILD.bazel
  src/ray/protobuf/BUILD
  src/ray/protobuf/common.proto
  src/ray/protobuf/events/aggregator_service/event_aggregator_service.proto
  src/ray/protobuf/events/base.proto
  src/ray/protobuf/events/task_events/actor_task_definition_event.proto
  src/ray/protobuf/events/task_events/actor_task_execution_event.proto
  src/ray/protobuf/events/task_events/task_definition_event.proto
  src/ray/protobuf/events/task_events/task_execution_event.proto
  src/ray/protobuf/gcs.proto
  src/ray/rpc/event_aggregator_client.h
Labels: go
