Repository ray-project/ray, pull requests merged in 2025-07, with the labels that each got.

#53826 [Doc][KubeRay] remove head pod trailing hash and adjust volcano output
  doc/source/cluster/kubernetes/k8s-ecosystem/volcano.md
Labels: stale, go

#54015 [docker] Update latest Docker dependencies for 2.47.1 release
  doc/source/ray-overview/installation.rst
  doc/source/ray-overview/pip_freeze_ray-ml-py39-cpu.txt
  doc/source/ray-overview/pip_freeze_ray-py39-cpu.txt
Labels: go

#54234 Revert "Revert "remove extraneous index.rst file for e2e examples (part 2)""
  doc/source/ray-overview/examples/e2e-audio/index.rst
  doc/source/ray-overview/examples/e2e-multimodal-ai-workloads/README.ipynb
  doc/source/ray-overview/examples/e2e-multimodal-ai-workloads/README.md
  doc/source/ray-overview/examples/e2e-rag/README.ipynb
  doc/source/ray-overview/examples/e2e-rag/README.md
  doc/source/ray-overview/examples/e2e-rag/index.rst
  doc/source/ray-overview/examples/e2e-timeseries/README.ipynb
  doc/source/ray-overview/examples/e2e-timeseries/README.md
  doc/source/ray-overview/examples/e2e-timeseries/index.rst
  doc/source/ray-overview/examples/e2e-xgboost/README.ipynb
  doc/source/ray-overview/examples/e2e-xgboost/README.md
  doc/source/ray-overview/examples/e2e-xgboost/index.rst
  doc/source/ray-overview/examples/entity-recognition-with-llms/README.ipynb
  doc/source/ray-overview/examples/entity-recognition-with-llms/README.md
  doc/source/ray-overview/examples/index.rst
  doc/source/ray-overview/examples/object-detection/README.ipynb
  doc/source/ray-overview/examples/object-detection/README.md
  doc/source/ray-overview/examples/object-detection/index.rst
Labels: go

#54180 move Collector class to _common
  python/ray/_private/test_utils.py
  python/ray/serve/tests/test_http_cancellation.py
Labels: go

#54247 [core] Deflake `test_node_affinity_scheduling_strategy_soft_spill_on_unavailable`
  python/ray/tests/test_scheduling_2.py
Labels: go

#54183 [core][test] deflaky test_demand_report_when_scale_up by reducing workloads
  python/ray/tests/test_scheduling_2.py
Labels: go

#53136 Fix broken Ray Workflows documentation link in README.rst
  README.rst
Labels: stale, go

#54209 [RLlib] Enhance ConnectorV2 `ObservationPreprocessor` APIs (add multi-agent support; add `episode` arg).
  doc/source/rllib/rllib-examples.rst
  rllib/BUILD
  rllib/connectors/env_to_module/observation_preprocessor.py
  rllib/env/single_agent_episode.py
  rllib/examples/connectors/classes/add_other_agents_row_index_to_xy_pos.py
  rllib/examples/connectors/classes/multi_agent_with_different_observation_spaces.py
  rllib/examples/connectors/multi_agent_observation_preprocessor.py
  rllib/examples/connectors/single_agent_observation_preprocessor.py
  rllib/examples/envs/classes/multi_agent/double_row_corridor_env.py
Labels: go

#54238 Cursor/update ray docs Twitter link to X
  README.rst
  doc/source/_templates/index.html
  doc/source/ray-contribute/involvement.rst
Labels: go

#54227 [serve] optimize code when user code is on same event loop
  .buildkite/serve.rayci.yml
  python/ray/serve/_private/local_testing_mode.py
  python/ray/serve/_private/replica.py
  python/ray/serve/tests/test_regression.py
Labels: go

#53702 [RLlib; Offline RL] Implement Offline Policy Evaluation (OPE) via Importance Sampling.
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/env/single_agent_env_runner.py
  rllib/offline/offline_evaluation_runner.py
  rllib/offline/offline_evaluation_runner_group.py
  rllib/offline/offline_policy_evaluation_runner.py
  rllib/offline/tests/test_offline_evaluation_runner_group.py
  rllib/tests/test_dependency_torch.py
  rllib/tuned_examples/bc/cartpole_bc_with_offline_evaluation.py
  rllib/utils/runners/runner_group.py
Labels: rllib, rllib-evaluation, rllib-offline-rl, go

#54176 [core] Add timeouts to `test_scheduling.py::test_hybrid_policy`
  python/ray/tests/test_scheduling.py
Labels: go

#54249 [core] Remove `test_schedule_many_actors_and_normal_tasks`
  python/ray/tests/test_advanced_5.py
Labels: go

#54173 [core] Add static type hints for Actor methods
  python/ray/actor.py
Labels: go

#49104 Update azure.md - Missing azure dependency
  doc/source/cluster/vms/user-guides/launching-clusters/azure.md
Labels: build, Devprod, go, azure, community-contribution

#54116 [core] Fix "Check failed: it->second.num_retries_left == -1"
  python/ray/tests/test_cancel.py
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/task_manager_test.cc
Labels: go

#54214 [deps] upgrade pytest-virtualenv
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#54258 [Data] Update release test datasets to us-west-2 buckets
  release/nightly_tests/dataset/batch_inference_mock_image_pipeline.py
  release/nightly_tests/dataset/streaming_split_benchmark.py
  release/release_data_tests.yaml
  release/train_tests/benchmark/image_classification/parquet/imagenet.py
  release/train_tests/benchmark/recsys/criteo.py
Labels: go

#53135 feat(runtime_env): add Azure Blob Storage support
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/protocol.py
  python/ray/tests/test_runtime_env_packaging.py
Labels: go

#54204 add a env var to disable forceful replica shutdown
  python/ray/serve/_private/deployment_state.py
  python/ray/serve/_private/replica.py
Labels: go

#54279 [Data] Refactor `test_json_read_partitioned_with_filter` to avoid actors
  python/ray/data/tests/test_json.py
Labels: go

#53882 [doc][core] fix reStructuredText formatting on Resources page
  doc/source/ray-core/scheduling/resources.rst
Labels: go

#54283 [core][refactor/01] remove MarkTaskCanceled as a condition check
  src/mock/ray/core_worker/task_manager.h
  src/ray/core_worker/task_finisher.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.cc
Labels: go

#54269 add memory buffer logger to serve
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/replica.py
  python/ray/serve/tests/test_config_files/logging_config_test.py
  python/ray/serve/tests/test_logging.py
Labels: go

#54196 [data.llm][Bugfix] Fix doc to only support int `concurrency`
  python/ray/llm/_internal/batch/processor/base.py
  python/ray/llm/_internal/batch/processor/vllm_engine_proc.py
  python/ray/llm/tests/batch/cpu/processor/test_processor_base.py
Labels: go

#54302 [setup] remove invoker in `bazel_invoke`
  python/setup.py
Labels: go

#54231 [ci] remove min install on aarch64 mac
  .buildkite/macos/macos.rayci.yml
Labels: go

#54303 [serve] speed up CI tests
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_cli.py
  python/ray/serve/tests/test_cli_2.py
  python/ray/serve/tests/test_cli_3.py
Labels: go

#54309 disable uvicorn message logger middleware
  python/ray/serve/_private/http_util.py
Labels: go

#54108 [data] adapt dask on ray to the new dask task class
  .buildkite/core.rayci.yml
  .buildkite/data.rayci.yml
  doc/source/ray-more-libs/doc_code/dask_on_ray_persist_example.py
  python/ray/data/tests/test_ecosystem_dask.py
  python/ray/util/dask/__init__.py
  python/ray/util/dask/common.py
  python/ray/util/dask/optimizations.py
  python/ray/util/dask/scheduler.py
  python/ray/util/dask/scheduler_utils.py
  python/ray/util/dask/tests/test_dask_callback.py
  python/ray/util/dask/tests/test_dask_multi_node.py
  python/ray/util/dask/tests/test_dask_optimization.py
  python/ray/util/dask/tests/test_dask_scheduler.py
  python/requirements/ml/data-requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#54312 [core] Use `SignalActor` in `test_hybrid_policy_threshold`
  python/ray/tests/test_scheduling.py
Labels: go

#54320 [core] Skip generator reconstruction test
  python/ray/tests/test_streaming_generator_2.py
Labels: go

#53634 [core] Fix gcs register actor callback check
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.cc
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/gcs/gcs_server/test/export_api/gcs_actor_manager_export_event_test.cc
  src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc
Labels: go

#54330 Fix `test_runtime_env_container`
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_cli_2.py
  python/ray/serve/tests/test_cli_3.py
Labels: go

#54317 [core][task-manager/02] consolidate TaskManager interface
  src/mock/ray/core_worker/task_manager_interface.h
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/object_recovery_manager.cc
  src/ray/core_worker/object_recovery_manager.h
  src/ray/core_worker/task_finisher.h
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/task_manager_interface.h
  src/ray/core_worker/test/actor_task_submitter_test.cc
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/direct_actor_transport_mock_test.cc
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/test/object_recovery_manager_test.cc
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/actor_task_submitter.h
  src/ray/core_worker/transport/dependency_resolver.cc
  src/ray/core_worker/transport/dependency_resolver.h
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#54318 Updated stalebot to add bounced label and exempt labels
  .github/workflows/stale_pull_request.yaml
Labels: go

#54335 [serve] deflake test_multiplex
  python/ray/serve/tests/test_multiplex.py
Labels: go

#54066 [train] Add broadcast_from_rank_zero and barrier collectives
  python/ray/train/BUILD
  python/ray/train/collective/__init__.py
  python/ray/train/collective/collectives.py
  python/ray/train/v2/BUILD
  python/ray/train/v2/_internal/execution/checkpoint/sync_actor.py
  python/ray/train/v2/_internal/execution/context.py
  python/ray/train/v2/tests/test_collective.py
  python/ray/train/v2/tests/test_persistence.py
  python/ray/train/v2/tests/test_sync_actor.py
Labels: go

#54331 [serve] configure http options in controller
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/grpc_util.py
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/test_callback.py
  python/ray/serve/tests/unit/test_http_util.py
Labels: go

#54293 [Train] Remove the subclass relationship between RunConfig and RunConfigV1
  python/ray/train/v2/api/config.py
  python/ray/train/v2/tests/test_v2_api.py
Labels: go

#54323 [wheel] mac: upgrade arm64 wheel to macos 12
  ci/ray_ci/automation/ray_wheels_lib.py
  ci/ray_ci/automation/test_pypi_lib.py
  ci/ray_ci/automation/test_ray_wheels_lib.py
  doc/source/ray-overview/installation.rst
  python/ray/_private/utils.py
  python/ray/tests/test_runtime_env_get_wheel_names.py
Labels: go

#54311 [cpp] add explicit files for deps
  cpp/BUILD.bazel
  python/setup.py
Labels: go

#53151 [core] Don't try to monitor zipped files
  python/ray/dashboard/modules/event/event_utils.py
  python/ray/dashboard/modules/event/tests/test_event.py
Labels: go

#54068 [core][refactor] move NodeManager::KillWorker to WorkerInterface::KillAsync for better testability
  src/mock/ray/raylet/worker.h
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/test/node_manager_test.cc
  src/ray/raylet/test/util.h
  src/ray/raylet/worker.cc
  src/ray/raylet/worker.h
Labels: go

#54315 [ci] sync versions of pytest and pip-tools
  ci/build/test-macos-wheels.sh
  ci/docker/min.build.Dockerfile
Labels: go

#54362 [data.llm] Decouple max_tasks_in_flight from max_concurrent_batches
  python/ray/llm/_internal/batch/processor/base.py
  python/ray/llm/_internal/batch/processor/sglang_engine_proc.py
  python/ray/llm/_internal/batch/processor/vllm_engine_proc.py
  python/ray/llm/tests/batch/gpu/processor/test_sglang_engine_proc.py
  python/ray/llm/tests/batch/gpu/processor/test_vllm_engine_proc.py
Labels: go

#54340 [train] Document ray.train.collective
  doc/source/train/api/api.rst
Labels: go

#54368 [core] Deflake `test_actor_scheduling_not_block_with_placement_group`
  python/ray/tests/test_placement_group_3.py
Labels: go

#54188 [train] Force abort on SIGINT spam and do not abort finished runs
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/tests/test_data_parallel_trainer.py
Labels: go

#54378 [core] Delete event_label
  cpp/src/ray/runtime/task/task_executor.cc
  src/ray/common/file_system_monitor.h
  src/ray/core_worker/transport/task_receiver.cc
  src/ray/gcs/gcs_server/gcs_node_manager.cc
  src/ray/raylet/node_manager.cc
  src/ray/util/BUILD
  src/ray/util/event_label.h
  src/ray/util/logging.cc
  src/ray/util/tests/event_test.cc
Labels: go

#54381 [core] Unskip `test_placement_group_strict_spread`
  python/ray/tests/test_placement_group.py
Labels: go

#54190 [Data] Revisit async UDF handling in Ray Data
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_map.py
  release/llm_tests/batch/test_batch_vllm.py
Labels: go

#54329 [data.llm] Return a batch of rows in the udf instead of row by row
  python/ray/llm/_internal/batch/stages/base.py
  python/ray/llm/tests/batch/cpu/stages/test_chat_template_stage.py
  python/ray/llm/tests/batch/cpu/stages/test_http_request_stage.py
  python/ray/llm/tests/batch/cpu/stages/test_stage_base.py
  python/ray/llm/tests/batch/cpu/stages/test_tokenize_stage.py
  python/ray/llm/tests/batch/gpu/stages/test_sglang_engine_stage.py
Labels: go

#54375 [core][GPU Objects] Disable tensordict tests in macos ci
  python/ray/tests/test_gpu_objects_gloo.py
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: go, gpu-objects

#54243 [release] Make KubeRay test run nightly
  release/ray_release/glue.py
  release/release_tests.yaml
  release/run_release_test.sh
Labels: go

#54392 [ci] upgrade rayci version to 0.16.0
  .rayciversion
Labels: go

#54390 [Data] Fixing `sort_benchmark` to avoid offsets overflows with Pyarrow
  release/nightly_tests/dataset/sort_benchmark.py
Labels: go

#54410 [ci] release tests: remove unused app configs
  release/air_tests/air_benchmarks/app_config.yaml
  release/air_tests/frequent_pausing/app_config.yaml
  release/air_tests/oom/stress_tests_tune_air_oom_app_config.yaml
  release/autoscaling_tests/app_config.yaml
  release/cluster_tests/app_config.yaml
  release/dashboard/agent_stress_app_config.yaml
  release/golden_notebook_tests/torch_tune_serve_app_config.yaml
  release/jobs_tests/app_config.yaml
  release/k8s_tests/app_config.yaml
  release/long_running_distributed_tests/app_config.yaml
  release/long_running_tests/app_config.yaml
  release/ml_user_tests/horovod/app_config.yaml
  release/ml_user_tests/train/app_config.yaml
  release/nightly_tests/chaos_test/app_config.yaml
  release/nightly_tests/dask_on_ray/dask_on_ray_app_config.yaml
  release/nightly_tests/dask_on_ray/large_scale_dask_on_ray_app_config.yaml
  release/nightly_tests/dataset/app_config.yaml
  release/nightly_tests/dataset/shuffle_app_config.yaml
  release/nightly_tests/decision_tree/decision_tree_app_config.yaml
  release/nightly_tests/placement_group_tests/app_config.yaml
  release/nightly_tests/shuffle/100tb_shuffle_app_config.yaml
  release/nightly_tests/shuffle/shuffle_app_config.yaml
  release/nightly_tests/shuffle/shuffle_with_state_api_app_config.yaml
  release/nightly_tests/stress_tests/stress_tests_single_node_oom_app_config.yaml
  release/rllib_tests/app_config.yaml
  release/rllib_tests/debug_app_config.yaml
  release/runtime_env_tests/app_config.yaml
  release/serve_tests/app_config.yaml
  release/serve_tests/gpu_app_config.yaml
  release/train_tests/horovod/app_config.yaml
  release/tune_tests/fault_tolerance_tests/app_config.yaml
Labels: go

#54357 migrate signature from _private to _common
  python/ray/_common/signature.py
  python/ray/_common/tests/BUILD
  python/ray/_common/tests/test_signature.py
  python/ray/_raylet.pyx
  python/ray/actor.py
  python/ray/remote_function.py
  python/ray/serve/batching.py
  python/ray/util/client/common.py
Labels: go

#54382 [core] Delete skip_flaky_core_test_premerge
  python/ray/_private/test_utils.py
  python/ray/tests/test_client_builder.py
  python/ray/tests/test_reference_counting.py
Labels: go

#54351 [Core] Use smart pointer in logging.cc
  src/ray/util/logging.cc
Labels: go

#54404 [core] Inject reorder_wait_seconds for scheduling queue test
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/task_receiver.cc
Labels: go

#54140 [serve] Remove usage of `ray._private.state`
  python/ray/serve/tests/conftest.py
  python/ray/serve/tests/test_cluster.py
  python/ray/serve/tests/test_deploy_app.py
  python/ray/serve/tests/test_deploy_app_2.py
  python/ray/serve/tests/test_grpc.py
  python/ray/serve/tests/test_proxy.py
  python/ray/serve/tests/test_standalone_2.py
  python/ray/serve/tests/test_standalone_3.py
Labels: go

#54417 [serve] Remove usage of `internal_api.memory_summary()`
  python/ray/serve/tests/test_advanced.py
Labels: go

#54383 [core] Skip `test_owner_assign_inner_object` on Windows
  python/ray/tests/test_object_assign_owner.py
Labels: go

#54405 [wheel] remove pyarrow <18 restriction
  python/requirements.txt
  python/setup.py
Labels: go

#54398 [ci] add workspace status script
  .bazelrc
  bazel/workspace_status.sh
Labels: go

#54429 [serve] add request metadata to can_accept_request
  python/ray/serve/_private/replica.py
Labels: go

#54376 [data] Extract backpressure-related code from ResourceManager as a policy
  ci/lint/pydoclint-baseline.txt
  python/ray/data/_internal/execution/backpressure_policy/__init__.py
  python/ray/data/_internal/execution/backpressure_policy/backpressure_policy.py
  python/ray/data/_internal/execution/backpressure_policy/concurrency_cap_backpressure_policy.py
  python/ray/data/_internal/execution/backpressure_policy/resource_budget_backpressure_policy.py
  python/ray/data/_internal/execution/interfaces/op_runtime_metrics.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/resource_manager.py
  python/ray/data/_internal/execution/streaming_executor.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_backpressure_policies.py
  python/ray/data/tests/test_resource_manager.py
  python/ray/data/tests/test_stats.py
  python/ray/data/tests/test_streaming_executor.py
Labels: go

#54444 update google tag container id
  doc/source/_templates/extrahead.html
  doc/source/ray-overview/examples/e2e-rag/notebooks/anyscale-jobs-docs/Job_schedules.html
Labels: go

#54436 [Data] Avoid OOMs with `read_json(..., lines=True)`
  python/ray/data/_internal/datasource/json_datasource.py
  python/ray/data/read_api.py
  python/ray/data/tests/test_json.py
Labels: go

#54352 Fix test_json CI failures
  python/ray/data/tests/test_json.py
Labels: go

#54441 [serve] skip test_proxy_disconnect_metrics on windows
  python/ray/serve/tests/test_metrics.py
Labels: go

#54453 [train][checkpoint] Populate checkpoint from before_init_train_context instead of workergroupcontext
  python/ray/train/v2/_internal/execution/checkpoint/checkpoint_manager.py
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
  python/ray/train/v2/tests/test_checkpoint_manager.py
Labels: go

#54437 [ci] adding uv binary v0.7.19
  WORKSPACE
Labels: go

#54407 [llm] bump vllm to 0.9.2
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_loggers.py
  python/requirements/llm/llm-requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu128.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu128.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu128.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu128.txt
  python/setup.py
  release/llm_tests/serve/test_llm_serve_integration.py
Labels: go

#54413 [Core] Use std::move in cluster task manager constructor
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: go

#54355 migrate check_library_usage_telemetry to _common
  python/ray/_common/test_utils.py
  python/ray/_private/test_utils.py
  python/ray/data/tests/test_telemetry.py
  python/ray/serve/tests/test_telemetry.py
  python/ray/train/tests/test_telemetry.py
  python/ray/train/v2/tests/test_telemetry.py
  python/ray/tune/tests/test_telemetry.py
  rllib/tests/test_telemetry.py
Labels: go

#54456 [core][autoscaler] fix: use RAY_UP_enable_autoscaler_v2 instead of RAY_enable_autoscaler_v2 for ray up
  python/ray/autoscaler/_private/commands.py
Labels: go

#54458 [serve] deflake `test_autoscaling_policy_with_metr_disab`
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_autoscaling_policy.py
Labels: go

#54248 [serve] tests for log formatter
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_logging.py
Labels: go

#54469 [Data] Prevent Op fusion for streaming repartition
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/tests/test_repartition_e2e.py
Labels: go

#54396 [core][tune] fix RayTaskError (de)serialization logic
  python/ray/exceptions.py
  python/ray/tests/test_failure.py
  python/ray/tune/tests/test_train_v2_integration.py
Labels: go

#54480 Add __init__.py for prefix tree directories
  python/ray/llm/_internal/serve/request_router/__init__.py
  python/ray/llm/_internal/serve/request_router/prefix_aware/__init__.py
Labels: go

#54476 [wheel] only call bazel once when building the wheel
  python/setup.py
Labels: go

#54455 [core] fix get_max_resources_from_cluster_config
  python/ray/_private/state.py
  python/ray/tests/test_global_state.py
Labels: go

#54440 [Serve.llm] Make llm serve endpoints compatible with vLLM serve frontend (1/N): Remove random v0 logic
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/tests/serve/cpu/deployments/llm/vllm/test_vllm_engine.py
  release/llm_tests/serve/configs/model_config/llama_3dot1_8b_lora.yaml
  release/llm_tests/serve/configs/model_config/llama_3dot1_8b_quantized_tp1.yaml
  release/llm_tests/serve/configs/serve_llama_3dot1_8b_quantized_tp1_2p6d.yaml
  release/llm_tests/serve/probes/models.py
  release/llm_tests/serve/probes/test_basic.py
  release/llm_tests/serve/run_llm_serve_test_and_bms.py
  release/release_tests.yaml
Labels: go

#53745 [core] upgrade opentelemetry-sdk
  .buildkite/build.rayci.yml
  .buildkite/serve.rayci.yml
  ci/docker/serve.build.Dockerfile
  ci/docker/servetracing.build.wanda.yaml
  python/ray/tests/BUILD
  python/requirements.txt
  python/requirements/cloud-requirements.txt
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
  python/requirements_compiled_ray_py311_cpu.txt
  python/requirements_compiled_ray_py311_cu121.txt
  python/requirements_compiled_ray_py311_cu128.txt
  python/requirements_compiled_ray_test_py311_cpu.txt
  python/requirements_compiled_ray_test_py311_cu121.txt
  python/requirements_compiled_ray_test_py311_cu128.txt
  python/requirements_compiled_rayllm_py311_cpu.txt
  python/requirements_compiled_rayllm_py311_cu121.txt
  python/requirements_compiled_rayllm_py311_cu128.txt
  python/requirements_compiled_rayllm_test_py311_cpu.txt
  python/requirements_compiled_rayllm_test_py311_cu121.txt
  python/requirements_compiled_rayllm_test_py311_cu128.txt
  python/setup.py
Labels: go

#54479 [serve] deflake test_deployment_scheduler_with_comp_sched
  python/ray/serve/_private/deployment_scheduler.py
  python/ray/serve/tests/test_deployment_scheduler.py
Labels: go

#54497 [deps] core: drop opencensus-proto test dep
  python/ray/tests/test_metrics.py
  python/requirements/test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#54470 [core] Improve status messages and add comments about stale seq_no handling
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_scheduling_queue.h
  src/ray/core_worker/transport/scheduling_util.cc
  src/ray/core_worker/transport/scheduling_util.h
  src/ray/protobuf/core_worker.proto
Labels: go

#54229 [Docs] Troubleshooting DeepSeek/multi-node GPU deployment on KubeRay
  doc/source/cluster/kubernetes/troubleshooting/troubleshooting.md
  doc/source/serve/advanced-guides/index.md
  doc/source/serve/advanced-guides/multi-node-gpu-troubleshooting.md
  doc/source/serve/tutorials/serve-deepseek.md
Labels: go

#54454 Optimize get_live_deployments
  python/ray/serve/_private/deployment_state.py
Labels: serve, go, community-contribution

#54508 [serve] fix `test_standalone_2`
  python/ray/serve/tests/test_standalone_2.py
Labels: go, continuous-build

#54443 [Serve.llm] Make llm serve endpoints compatible with vLLM serve frontend (2/N): Incremental refactor of LLMEngine
  python/ray/llm/_internal/serve/deployments/llm/llm_engine.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_models.py
Labels: alpha, go

#54490 Feat/add websocket support for di
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_websockets.py
Labels: go

#54493 [serve] deflake test_replica_metrics_fields
  python/ray/serve/tests/test_metrics.py
Labels: go

#54503 increase timeout for wait condition
  python/ray/serve/tests/test_logging.py
Labels: core, ci-test, go

#54513 [serve] deflake test_e2e_preserve_prev_replicas
  python/ray/serve/_private/test_utils.py
  python/ray/serve/tests/test_autoscaling_policy.py
Labels: go

#54034 [core] Don't order retries for in-order actors to prevent deadlock
  python/ray/tests/test_actor_retry_2.py
  src/ray/core_worker/test/actor_submit_queue_test.cc
  src/ray/core_worker/test/actor_task_submitter_test.cc
  src/ray/core_worker/test/scheduling_queue_test.cc
  src/ray/core_worker/transport/actor_scheduling_queue.cc
  src/ray/core_worker/transport/actor_scheduling_queue.h
  src/ray/core_worker/transport/actor_submit_queue.h
  src/ray/core_worker/transport/actor_task_submitter.cc
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc
  src/ray/core_worker/transport/out_of_order_actor_submit_queue.h
  src/ray/core_worker/transport/sequential_actor_submit_queue.cc
  src/ray/core_worker/transport/sequential_actor_submit_queue.h
Labels: go

#54397 [core][autoscaler] fix: enable cloud_instance_id reusing in autoscaler v2
  python/ray/autoscaler/v2/instance_manager/instance_manager.py
  python/ray/autoscaler/v2/instance_manager/node_provider.py
  python/ray/autoscaler/v2/instance_manager/reconciler.py
  python/ray/autoscaler/v2/tests/test_reconciler.py
Labels: core, go, community-contribution

#54481 [Serve.llm] Make llm serve endpoints compatible with vLLM serve frontend (3/N): Remove indirection layers of node initialization
  python/ray/llm/_internal/serve/configs/server_models.py
  python/ray/llm/_internal/serve/deployments/llm/llm_server.py
  python/ray/llm/_internal/serve/deployments/llm/vllm/vllm_engine.py
  python/ray/llm/_internal/serve/deployments/utils/node_initialization_utils.py
  python/ray/llm/tests/serve/mocks/mock_vllm_engine.py
Labels: go

#54472 [core][telemetry/08-bis] api documentation + improvements
  python/ray/_private/telemetry/open_telemetry_metric_recorder.py
  python/ray/dashboard/modules/reporter/reporter_agent.py
  python/ray/tests/test_open_telemetry_metric_recorder.py
  src/ray/stats/metric.h
  src/ray/stats/metric_defs.h
  src/ray/stats/tests/metric_with_open_telemetry_test.cc
  src/ray/telemetry/open_telemetry_metric_recorder.cc
  src/ray/telemetry/open_telemetry_metric_recorder.h
  src/ray/telemetry/tests/open_telemetry_metric_recorder_test.cc
Labels: go

#54518 [core] enable the v2 autoscaler by default when the cluster is managed by KubeRay
  python/ray/scripts/scripts.py
Labels: core, go

#54468 [core] Default state API address when in a connected worker
  python/ray/dashboard/utils.py
  python/ray/tests/test_state_api.py
Labels: go

#54465 [wheel] limit build artifacts duplicated in example directory for ray_cpp
  cpp/BUILD.bazel
Labels: core, go, community-contribution

#53911 [core][gpu-objects] garbage collection
  python/ray/_private/serialization.py
  python/ray/_raylet.pyx
  python/ray/experimental/gpu_object_manager/gpu_object_manager.py
  python/ray/experimental/gpu_object_manager/gpu_object_store.py
  python/ray/includes/libcoreworker.pxd
  python/ray/tests/test_gpu_objects_gloo.py
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/reference_count.h
  src/ray/core_worker/task_manager.cc
  src/ray/core_worker/task_manager.h
  src/ray/core_worker/test/dependency_resolver_test.cc
  src/ray/core_worker/test/task_manager_test.cc
  src/ray/core_worker/transport/dependency_resolver.cc
  src/ray/protobuf/core_worker.proto
  src/ray/rpc/worker/core_worker_client.h
  src/ray/rpc/worker/core_worker_server.h
Labels: go

#54386 `concat`: Handle mixed Tensor types for structs
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/tests/test_transform_pyarrow.py
Labels: go

#54484 [Serve.llm] Make llm serve endpoints compatible with vLLM serve frontend (4/N): Refactor LLMServer
  python/ray/llm/_internal/serve/deployments/llm/llm_server.py
  python/ray/llm/tests/serve/cpu/deployments/llm/multiplex/test_multiplex_deployment.py
  python/ray/llm/tests/serve/mocks/mock_vllm_engine.py
Labels: go

#53818 [train] TrainStateActor periodically checks controller status and sets aborted
  python/ray/train/v2/_internal/constants.py
  python/ray/train/v2/_internal/state/schema.py
  python/ray/train/v2/_internal/state/state_actor.py
  python/ray/train/v2/_internal/state/state_manager.py
  python/ray/train/v2/_internal/state/util.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/tests/conftest.py
  python/ray/train/v2/tests/test_state.py
  python/ray/train/v2/tests/test_state_export.py
  python/ray/train/v2/tests/util.py
Labels: go

#54542 document unexpected queuing behavior in handle
  python/ray/serve/_private/router.py
Labels: go

#54535 [core][autoscaler] add the missing readonly/example.yaml to the build
  BUILD.bazel
  python/ray/autoscaler/_private/providers.py
  python/ray/autoscaler/_private/readonly/defaults.yaml
  python/ray/scripts/scripts.py
  python/setup.py
Labels: core, go, community-contribution

#54531 [Serve.llm] Make llm serve endpoints compatible with vLLM serve frontend (5/N): Change source of dashboards from ray serve llm metrics to vllm metrics
  python/ray/dashboard/modules/metrics/dashboards/serve_llm_dashboard_panels.py
  python/ray/dashboard/modules/metrics/dashboards/serve_llm_grafana_dashboard_base.json
  python/ray/llm/_internal/serve/configs/server_models.py
Labels: go

#54543 [serve] reorganize how we handle the http receive task
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/replica.py
  python/ray/serve/tests/unit/test_http_util.py
  python/ray/serve/tests/unit/test_user_callable_wrapper.py
Labels: go

#54522 use wait_condition for verifying http response
  python/ray/serve/tests/test_logging.py
Labels: serve, core, ci-test, go, community-contribution

#54547 [DOC][Core] fix typo in Anti-pattern.
  doc/source/ray-core/patterns/out-of-band-object-ref-serialization.rst
Labels: docs, core, go, community-contribution

#54277 [RLlib] Switch Offline Data iteration to `iter_torch_batches`.
  rllib/algorithms/bc/bc.py
  rllib/algorithms/cql/cql.py
  rllib/algorithms/marwil/marwil.py
  rllib/core/learner/learner.py
  rllib/offline/offline_evaluation_runner.py
  rllib/tuned_examples/bc/benchmark_rlunplugged_atari_pong_bc.py
  rllib/utils/minibatch_utils.py
Labels: rllib, rllib-offline-rl, go

#54185 [RLlib] - Increased default timesteps on two experiments.
  rllib/examples/algorithms/vpg_custom_algorithm.py
  rllib/examples/metrics/custom_metrics_in_algorithm_training_step.py
Labels: rllib, go

#54582 [RLlib, CI] Remove old API stack Unity3D test case.
  rllib/BUILD
  rllib/env/wrappers/tests/test_unity3d_env.py
Labels: go

#53551 [core] Support pip_install_options for pip
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/pip.py
  python/ray/_private/runtime_env/uv.py
  python/ray/_private/runtime_env/validation.py
  python/ray/tests/test_runtime_env_conda_and_pip.py
  python/ray/tests/unit/test_runtime_env_validation.py
Labels: core, go, community-contribution, unstale

#54537 Fix backpressure gRPC error code
  python/ray/serve/_private/grpc_util.py
  python/ray/serve/tests/test_backpressure.py
  python/ray/serve/tests/unit/test_grpc_util.py
Labels: go

#54445 [data] Allocate GPU resources in ResourceManager
  python/ray/data/_internal/execution/resource_manager.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/tests/test_resource_manager.py
  python/ray/data/tests/test_streaming_executor.py
Labels: go

#54585 [serve] update receive proxy in replica
  python/ray/serve/_private/http_util.py
  python/ray/serve/_private/replica.py
Labels: go

#54578 migrate ray_option_utils from private to common
  python/ray/_common/constants.py
  python/ray/_common/ray_option_utils.py
  python/ray/_common/tests/BUILD
  python/ray/_common/tests/test_ray_option_utils.py
  python/ray/_private/resource_spec.py
  python/ray/_private/state.py
  python/ray/_private/worker.py
  python/ray/actor.py
  python/ray/autoscaler/v2/tests/test_e2e.py
  python/ray/llm/_internal/batch/observability/usage_telemetry/usage.py
  python/ray/llm/_internal/serve/observability/usage_telemetry/usage.py
  python/ray/remote_function.py
  python/ray/serve/_private/config.py
  python/ray/serve/_private/default_impl.py
  python/ray/serve/_private/utils.py
  python/ray/serve/tests/test_serve_ha.py
  python/ray/serve/tests/test_util.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_basic_5.py
  python/ray/tune/utils/resource_updater.py
  python/ray/util/client/api.py
  python/ray/util/client/options.py
Labels: go

#54594 [serve] add timeout to test_cancel_on_http_timeout_during_execution
  python/ray/serve/tests/test_request_timeout.py
Labels: go

#54588 [batch.llm] Fix mocks for unrun tests
  python/ray/llm/tests/batch/gpu/stages/test_vllm_engine_stage.py
Labels: go

#54206 [core] Normal task submitter cleanup
  src/ray/core_worker/test/normal_task_submitter_test.cc
  src/ray/core_worker/transport/normal_task_submitter.cc
  src/ray/core_worker/transport/normal_task_submitter.h
Labels: go

#54592 Address the case where min_rows_per_group exceeds arrow's default for write_dataset
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/tests/test_parquet.py
Labels: go

#54606 [Serve] Update HEALTHY_MESSAGE constant location
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/tests/unit/test_proxy.py
Labels: go

#54569 Feat/remove cpu profiler
  ci/lint/pydoclint-baseline.txt
  python/ray/serve/_private/constants.py
  python/ray/serve/_private/controller.py
  python/ray/serve/_private/logging_utils.py
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/replica.py
Labels: go

#54289 MCP Ray Serve End to End Example
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/ray-overview/examples/index.rst
  doc/source/ray-overview/examples/mcp-ray-serve/01 Deploy_custom_mcp_in_streamable_http_with_ray_serve.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/02 Build_mcp_gateway_with_existing_ray_serve_apps.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/03 Deploy_single_mcp_stdio_docker_image_with_ray_serve.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/04 Deploy_multiple_mcp_stdio_docker_images_with_ray_serve.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/05 (Optional) Build_docker_image_for_mcp_server.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/Dockerfile
  doc/source/ray-overview/examples/mcp-ray-serve/README.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/README.md
  doc/source/ray-overview/examples/mcp-ray-serve/brave_mcp_ray_serve.py
  doc/source/ray-overview/examples/mcp-ray-serve/build-mcp-docker-image/Dockerfile
  doc/source/ray-overview/examples/mcp-ray-serve/build-mcp-docker-image/podman_commands.txt
  doc/source/ray-overview/examples/mcp-ray-serve/build-mcp-docker-image/requirements.txt
  doc/source/ray-overview/examples/mcp-ray-serve/build-mcp-docker-image/weather.py
  doc/source/ray-overview/examples/mcp-ray-serve/ci/aws.yaml
  doc/source/ray-overview/examples/mcp-ray-serve/ci/build.sh
  doc/source/ray-overview/examples/mcp-ray-serve/ci/gce.yaml
  doc/source/ray-overview/examples/mcp-ray-serve/ci/nb2py.py
  doc/source/ray-overview/examples/mcp-ray-serve/ci/tests.sh
  doc/source/ray-overview/examples/mcp-ray-serve/configs/aws.yaml
  doc/source/ray-overview/examples/mcp-ray-serve/configs/gce.yaml
  doc/source/ray-overview/examples/mcp-ray-serve/mcp-gateway-with-existing-ray-apps/config_anyscale.yaml
  doc/source/ray-overview/examples/mcp-ray-serve/mcp-gateway-with-existing-ray-apps/config_serve.yaml
  doc/source/ray-overview/examples/mcp-ray-serve/mcp-gateway-with-existing-ray-apps/image_classifier.py
  doc/source/ray-overview/examples/mcp-ray-serve/mcp-gateway-with-existing-ray-apps/mcp_gateway.py
  doc/source/ray-overview/examples/mcp-ray-serve/mcp-gateway-with-existing-ray-apps/text_translator.py
  doc/source/ray-overview/examples/mcp-ray-serve/multi_mcp_ray_serve.py
  doc/source/ray-overview/examples/mcp-ray-serve/translator_mcp_ray.py
  doc/source/ray-overview/examples/mcp-ray-serve/weather_mcp_ray.py
  release/ray_release/byod/byod_mcp-ray-serve.sh
  release/release_tests.yaml
Labels: go

#54590 [Data] Actor location tracker
  python/ray/data/_internal/execution/node_trackers/actor_location.py
  python/ray/data/_internal/execution/operators/actor_pool_map_operator.py
  python/ray/data/tests/test_actor_pool_map_operator.py
Labels: go

#54486 [Data] Fixed chained inplace assignment to prevent FutureWarning from Pandas
  python/ray/data/preprocessors/imputer.py
Labels: data, go, community-contribution

#54637 [Core] Remove duplicate code
  python/ray/autoscaler/_private/monitor.py
Labels: go

#54270 [Core] Fix missing brace and add pytest for AMDGPUAcceleratorManager.get_visible_accelerator_ids_env_var
  python/ray/_private/accelerators/amd_gpu.py
  python/ray/tests/accelerators/test_amd_gpu.py
Labels: core, ci-test, go, community-contribution

#54641 [ci] raydepsets: moving uv binary
  ci/raydepsets/cli.py
  ci/raydepsets/test_cli.py
Labels: go

#54647 Add perf metrics for 2.48.0
  release/perf_metrics/benchmarks/many_actors.json
  release/perf_metrics/benchmarks/many_nodes.json
  release/perf_metrics/benchmarks/many_pgs.json
  release/perf_metrics/benchmarks/many_tasks.json
  release/perf_metrics/metadata.json
  release/perf_metrics/microbenchmark.json
  release/perf_metrics/scalability/object_store.json
  release/perf_metrics/scalability/single_node.json
  release/perf_metrics/stress_tests/stress_test_dead_actors.json
  release/perf_metrics/stress_tests/stress_test_many_tasks.json
  release/perf_metrics/stress_tests/stress_test_placement_group.json
Labels: go

#54313 [RLlib; docs] Docs do-over (new API stack): `ConnectorV2` documentation (part II).
  doc/source/rllib/connector-v2.rst
  doc/source/rllib/env-to-module-connector.rst
  doc/source/rllib/images/connector_v2/pipeline_batch_phases_multi_agent.svg
  doc/source/rllib/images/connector_v2/pipeline_batch_phases_single_agent.svg
  doc/source/rllib/images/connector_v2/pipeline_batch_phases_single_agent_w_states.svg
  doc/source/rllib/rl-modules.rst
  doc/source/rllib/user-guides.rst
Labels: tests-ok, rllib, rllib-connectorv2, rllib-docs-or-examples, go

#53856 [core] adding additional stats to the dump object store usage api.
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker.h
  src/ray/core_worker/store_provider/plasma_store_provider.cc
  src/ray/core_worker/store_provider/plasma_store_provider.h
  src/ray/object_manager/plasma/BUILD.bazel
  src/ray/object_manager/plasma/client.cc
  src/ray/object_manager/plasma/client.h
  src/ray/object_manager/plasma/store.cc
Labels: go

#54593 [ci] updating pre commit config - updating buildifier paths
  .pre-commit-config.yaml
  ci/lint/generate_compile_commands/BUILD.bazel
  ci/pipeline/BUILD.bazel
  ci/ray_ci/BUILD.bazel
  ci/ray_ci/automation/BUILD.bazel
  ci/ray_ci/bisect/BUILD.bazel
  ci/ray_ci/doc/BUILD.bazel
  ci/ray_ci/pipeline/BUILD.bazel
  cpp/BUILD.bazel
  release/BUILD.bazel
  src/ray/core_worker/BUILD.bazel
  src/ray/core_worker/lib/java/BUILD.bazel
  src/ray/core_worker/test/BUILD.bazel
  src/ray/object_manager/BUILD.bazel
  src/ray/object_manager/plasma/BUILD.bazel
  src/ray/pubsub/BUILD.bazel
  src/ray/raylet/scheduling/BUILD.bazel
  src/ray/raylet_client/BUILD.bazel
  src/ray/rpc/test/grpc_bench/BUILD.bazel
  src/ray/stats/BUILD.bazel
  src/ray/telemetry/BUILD.bazel
Labels: go

#54645 fix controller recovery test on windows
  python/ray/serve/tests/test_controller_recovery.py
  python/ray/serve/tests/test_failure.py
Labels: go

#54556 [core][gpu-objects] Avoid triggering a KeyError by the GPU object GC callback for intra-actor communication
  python/ray/_private/serialization.py
  python/ray/experimental/gpu_object_manager/gpu_object_store.py
  python/ray/tests/test_gpu_objects_gloo.py
Labels: go

#54692 [java] move copy_pom_file rule up
  java/BUILD.bazel
Labels: go

#54667 [Data] Prefetch data for `PandasJSONDatasource`
  python/ray/data/_internal/datasource/json_datasource.py
Labels: go

#54414 [RLlib] Fix `TorchMultiCategorical.to_deterministic` when having different number of categories and logits with time dimension.
  rllib/models/tests/test_distributions.py
  rllib/models/torch/torch_distributions.py
Labels: rllib, rllib-models, go

#54636 Fix MCP example name + sidebar navigation
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/ray-overview/examples/mcp-ray-serve/03 Deploy_single_mcp_stdio_docker_image_with_ray_serve.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/04 Deploy_multiple_mcp_stdio_docker_images_with_ray_serve.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/README.ipynb
  doc/source/ray-overview/examples/mcp-ray-serve/README.md
Labels: go

#54697 deflake test metrics 2
  python/ray/serve/tests/BUILD
Labels: go

#53568 [Data] User guide for aggregations
  doc/source/data/aggregations.rst
  doc/source/data/data-internals.rst
  doc/source/data/transforming-data.rst
  doc/source/data/user-guide.rst
Labels: data, go, unstale

#54664 [Core] minor fixes in GCS actor manager
  src/ray/gcs/gcs_server/gcs_actor_manager.h
  src/ray/util/event.cc
  src/ray/util/event.h
Labels: core, go, community-contribution

#54432 [Core] Avoid copy deque in cluster task manager
  src/ray/raylet/scheduling/cluster_task_manager.cc
Labels: core, go, community-contribution
