Repository ray-project/ray, pull requests merged in 2025-02, with the labels that each got.

#50119 [LLM Batch][3/N] Prepare Image stages
  ci/docker/llm.build.Dockerfile
  python/ray/llm/_internal/batch/stages/__init__.py
  python/ray/llm/_internal/batch/stages/base.py
  python/ray/llm/_internal/batch/stages/prepare_image_stage.py
  python/ray/llm/tests/batch/processor/BUILD
  python/ray/llm/tests/batch/stages/BUILD
  python/ray/llm/tests/batch/stages/test_prepare_image_stage.py
Labels: go

#50044 [core] Use boost iostream in pipe logger for cross-platform
  src/ray/util/BUILD
  src/ray/util/pipe_logger.cc
  src/ray/util/pipe_logger.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/pipe_logger_test.cc
  src/ray/util/tests/stream_redirection_utils_test.cc
Labels: go

#50144 [core] Spdlog FD sink
  python/ray/_private/ray_logging/logging_config.py
  src/ray/util/BUILD
  src/ray/util/spdlog_fd_sink.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/spdlog_fd_sink_test.cc
Labels: go

#50158 [image] Add cuda 12.5.1 in image building matrix
  .buildkite/_forge.rayci.yml
  .buildkite/build.rayci.yml
  .buildkite/linux_aarch64.rayci.yml
  ci/ray_ci/docker_container.py
  ci/ray_ci/test_ray_docker_container.py
  docker/retag-lambda/cuda_versions.txt
Labels: go

#50168 [core][compiled graph] Add checks for release_buffer
  python/ray/dag/compiled_dag_node.py
  python/ray/experimental/channel/common.py
Labels: go

#50025 [dashboard] Remove DataSource.agents with internal kv get.
  python/ray/dashboard/datacenter.py
  python/ray/dashboard/modules/job/job_head.py
  python/ray/dashboard/modules/job/tests/test_http_job_server.py
  python/ray/dashboard/modules/job/tests/test_sdk.py
  python/ray/dashboard/modules/job/utils.py
  python/ray/dashboard/modules/log/log_manager.py
  python/ray/dashboard/modules/node/node_head.py
  python/ray/dashboard/modules/node/tests/test_node.py
  python/ray/dashboard/modules/reporter/reporter_head.py
  python/ray/dashboard/modules/state/state_head.py
  python/ray/dashboard/modules/tests/test_head.py
  python/ray/dashboard/tests/test_dashboard.py
  python/ray/tests/test_memory_pressure.py
  python/ray/tests/test_state_api.py
  python/ray/tests/test_state_api_log.py
  python/ray/util/state/state_manager.py
Labels: go

#50174 [core] [easy] [no-op] Use scoped temporary directory for pipe logger test
  src/ray/util/tests/BUILD
  src/ray/util/tests/pipe_logger_test.cc
Labels: go

#50162 [RLlib] APPO accelerate vol 02: Various enhancements.
  doc/source/rllib/rllib-learner.rst
  rllib/algorithms/algorithm.py
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/algorithms/utils.py
  rllib/core/learner/learner_group.py
  rllib/core/learner/tests/test_learner_group.py
  rllib/policy/sample_batch.py
  rllib/utils/actor_manager.py
  rllib/utils/metrics/__init__.py
  rllib/utils/test_utils.py
  rllib/utils/torch_utils.py
Labels: rllib, rllib-system, rllib-newstack, go

#50175 [core] Cleanup utils targets dependency continue
  BUILD.bazel
  src/ray/common/BUILD
  src/ray/util/BUILD
  src/ray/util/tests/BUILD
Labels: go

#50194 [ci] remove `RAY_CI_BRANCH_BUILD` in cond test script
  ci/pipeline/determine_tests_to_run.py
Labels: go

#50173 [core] Use spdlog fd sink within pipe logger
  src/ray/util/BUILD
  src/ray/util/pipe_logger.cc
  src/ray/util/pipe_logger.h
  src/ray/util/tests/pipe_logger_test.cc
Labels: go

#50202 [Data] Mark aggregation functions as public APIs
  doc/source/data/api/aggregate.rst
  doc/source/data/api/api.rst
  doc/source/data/api/grouped_data.rst
  doc/source/data/doc_code/preprocessors.py
  python/ray/data/_internal/aggregate.py
  python/ray/data/_internal/planner/exchange/aggregate_task_spec.py
  python/ray/data/aggregate.py
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
  python/ray/data/preprocessors/discretizer.py
  python/ray/data/preprocessors/imputer.py
  python/ray/data/preprocessors/scaler.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/train/tests/test_datasets_train.py
  release/nightly_tests/dataset/tpch_q1.py
Labels: go

#50190 [ci] remove condition testing deps from base ci images
  ci/docker/base.build.aarch64.wanda.yaml
  ci/docker/base.build.py39.wanda.yaml
  ci/docker/base.build.wanda.yaml
  ci/docker/base.gpu.py39.wanda.yaml
  ci/docker/base.gpu.wanda.yaml
  ci/docker/base.ml.py39.wanda.yaml
  ci/docker/base.ml.wanda.yaml
Labels: go

#50170 [core] Compatibile function for file descriptor
  src/ray/util/BUILD
  src/ray/util/compat.cc
  src/ray/util/compat.h
  src/ray/util/stream_redirection_utils.cc
  src/ray/util/tests/BUILD
  src/ray/util/tests/compat_test.cc
Labels: go

#50092 [Data] Raise future warning if invalid Parquet extensions
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_parquet.py
Labels: data, go

#50203 [Data] Upgrade Arrow latest tests to Arrow 19
  .buildkite/data.rayci.yml
  ci/docker/datal.build.wanda.yaml
Labels: go

#50191 [ci] remove other deprecated modes in cond test script
  ci/ci_tags_from_change.sh
  ci/pipeline/determine_tests_to_run.py
Labels: go

#49604 [Data] Add test for case where partition values are encoded in file
  python/ray/data/_internal/datasource/parquet_datasource.py
  python/ray/data/tests/test_parquet.py
Labels: go

#50219 [RLlib] Fix `default_resource_request` (aggregator actors missing in placement group iff local Learner).
  rllib/algorithms/algorithm.py
Labels: go

#50196 [ci] extract common ci configs into ci-base
  .bazelrc
Labels: go

#50172 [RLlib] Fix `on_workers/env_runners_recreated` duplicate callback.
  rllib/algorithms/algorithm.py
  rllib/algorithms/appo/default_appo_rl_module.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/core/learner/learner_group.py
  rllib/env/env_runner_group.py
  rllib/env/multi_agent_env_runner.py
  rllib/env/single_agent_env_runner.py
  rllib/utils/actor_manager.py
Labels: rllib, rllib-checkpointing-or-recovery, go

#50210 [Data] Fixing incorrect assertion inside `make_async_gen`
  python/ray/data/_internal/util.py
  python/ray/data/tests/block_batching/test_util.py
Labels: go

#50225 [Data] Deflake `test_filter_e2e`
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#50185 [core] Final PR to cleanup utils target dependency
  BUILD.bazel
  cpp/BUILD.bazel
  cpp/src/ray/util/process_helper.cc
  src/ray/common/BUILD
  src/ray/common/task/task_spec.h
  src/ray/common/test_util.cc
  src/ray/core_worker/core_worker.cc
  src/ray/gcs/gcs_client/accessor.cc
  src/ray/object_manager/pull_manager.h
  src/ray/raylet/main.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/scheduling/cluster_resource_manager.h
  src/ray/raylet/scheduling/cluster_task_manager.h
  src/ray/util/BUILD
  src/ray/util/macros.h
  src/ray/util/tests/BUILD
  src/ray/util/util.cc
  src/ray/util/util.h
Labels: go

#50198 [ci] add unit test for conditional testing script
  .buildkite/cicd.rayci.yml
  ci/pipeline/BUILD.bazel
  ci/pipeline/determine_tests_to_run.py
  ci/pipeline/test_conditional_testing.py
Labels: go

#50228 [Data] Update Parquet file extensions
  python/ray/data/_internal/datasource/parquet_datasource.py
Labels: go

#50214 [core] Re-revert fd compatibility PR
  src/ray/util/BUILD
  src/ray/util/compat.cc
  src/ray/util/compat.h
  src/ray/util/stream_redirection_utils.cc
  src/ray/util/tests/BUILD
  src/ray/util/tests/compat_test.cc
Labels: go

#49895 [tune] Update rllib `ray.train` and `ray.air` usage
  doc/source/rllib/checkpoints.rst
  doc/source/rllib/doc_code/replay_buffer_demo.py
  doc/source/rllib/key-concepts.rst
  doc/source/rllib/rllib-offline.rst
  python/ray/train/_internal/storage.py
  python/ray/tune/trainable/trainable.py
  rllib/algorithms/algorithm.py
  rllib/algorithms/appo/appo.py
  rllib/algorithms/cql/torch/cql_torch_learner.py
  rllib/algorithms/dqn/dqn.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/marwil/marwil.py
  rllib/algorithms/ppo/ppo.py
  rllib/algorithms/tests/test_callbacks_on_env_runner.py
  rllib/benchmarks/torch_compile/run_ppo_with_inference_bm.py
  rllib/examples/_old_api_stack/connectors/self_play_with_policy_checkpoint.py
  rllib/examples/_old_api_stack/parametric_actions_cartpole.py
  rllib/examples/_old_api_stack/parametric_actions_cartpole_embeddings_learnt_by_model.py
  rllib/examples/centralized_critic.py
  rllib/examples/checkpoints/continue_training_from_checkpoint.py
  rllib/examples/checkpoints/restore_1_of_n_agents_from_checkpoint.py
  rllib/examples/curriculum/curriculum_learning.py
  rllib/examples/debugging/deterministic_training.py
  rllib/examples/envs/external_envs/cartpole_server.py
  rllib/examples/envs/greyscale_env.py
  rllib/examples/envs/unity3d_env_local.py
  rllib/examples/evaluation/custom_evaluation.py
  rllib/examples/evaluation/evaluation_parallel_to_training.py
  rllib/examples/inference/policy_inference_after_training_with_attention.py
  rllib/examples/inference/policy_inference_after_training_with_lstm.py
  rllib/examples/learners/ppo_load_rl_modules.py
  rllib/examples/multi_agent/rock_paper_scissors_heuristic_vs_learned.py
  rllib/examples/multi_agent/self_play_league_based_with_open_spiel.py
  rllib/examples/multi_agent/self_play_with_open_spiel.py
  rllib/examples/offline_rl/custom_input_api.py
  rllib/examples/offline_rl/pretrain_bc_single_agent_evaluate_as_multi_agent.py
  rllib/examples/ray_tune/custom_experiment.py
  rllib/examples/ray_tune/custom_logger.py
  rllib/examples/ray_tune/custom_progress_reporter.py
  rllib/examples/replay_buffer_api.py
  rllib/policy/policy.py
  rllib/tests/test_custom_resource.py
  rllib/tests/test_placement_groups.py
  rllib/tuned_examples/bc/cartpole_bc.py
  rllib/tuned_examples/bc/pendulum_bc.py
  rllib/tuned_examples/dqn/benchmark_dqn_atari.py
  rllib/tuned_examples/dqn/benchmark_dqn_atari_rllib_preprocessing.py
  rllib/tuned_examples/ppo/benchmark_ppo_mujoco.py
  rllib/tuned_examples/ppo/benchmark_ppo_mujoco_pb2.py
  rllib/tuned_examples/sac/benchmark_sac_mujoco.py
  rllib/tuned_examples/sac/benchmark_sac_mujoco_pb2.py
  rllib/utils/checkpoints.py
  rllib/utils/test_utils.py
Labels: go

#50209 [core] Use cross-platform syscall implementation
  src/ray/util/pipe_logger.h
  src/ray/util/spdlog_fd_sink.h
Labels: go

#50224 [cherry-pick] remove ray community survey banner (#50100)
  doc/source/conf.py
Labels: go

#50160 [Core] Implement py_executable support for runtime environments to enable better UV support
  doc/source/ray-core/handling-dependencies.rst
  python/ray/_private/runtime_env/agent/runtime_env_agent.py
  python/ray/_private/runtime_env/py_executable.py
  python/ray/runtime_env/runtime_env.py
  python/ray/tests/BUILD
  python/ray/tests/test_runtime_env_py_executable.py
  python/ray/tests/test_runtime_env_uv_run.py
Labels: go

#50215 [Data][Part 1] Refactoring `AllToAllOperator` support of different shuffling strategies
  python/ray/data/BUILD
  python/ray/data/_internal/logical/operators/all_to_all_operator.py
  python/ray/data/_internal/planner/aggregate.py
  python/ray/data/_internal/planner/plan_all_to_all_op.py
  python/ray/data/_internal/planner/random_shuffle.py
  python/ray/data/_internal/planner/repartition.py
  python/ray/data/_internal/planner/sort.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
  python/ray/data/tests/conftest.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_sort.py
  python/ray/tests/conftest.py
Labels: go

#50238 [chore] make `max_grpc_message_size` consistent
  python/ray/_private/ray_constants.py
  python/ray/_private/runtime_env/packaging.py
Labels: go

#50242 [Data] Reduce `test_zip` permutations
  python/ray/data/tests/test_zip.py
Labels: go

#50201 [core] cache test results for cpp/cicd tests
  .buildkite/cicd.rayci.yml
  .buildkite/core.rayci.yml
  ci/ray_ci/test_linux_tester_container.py
  ci/ray_ci/tester.py
  ci/ray_ci/tester_container.py
Labels: go

#50247 [core] [easy] [no-op] Unnecessary code cleanup
  src/ray/util/tests/BUILD
  src/ray/util/tests/pipe_logger_test.cc
Labels: go

#50129 [data/docs] Key Concepts Page
  .vale/styles/config/vocabularies/Data/accept.txt
  doc/source/data/data.rst
  doc/source/data/images/dataset-arch-with-blocks.svg
  doc/source/data/images/get_execution_plan.svg
  doc/source/data/images/streaming-topology.svg
  doc/source/data/key-concepts.rst
Labels: data, go

#50231 [Data] Added support for type promotions
  python/ray/_private/ray_constants.py
  python/ray/_private/utils.py
  python/ray/data/BUILD
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/_internal/batcher.py
  python/ray/data/_internal/execution/interfaces/execution_options.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/streaming_executor_state.py
  python/ray/data/_internal/logical/operators/n_ary_operator.py
  python/ray/data/_internal/pandas_block.py
  python/ray/data/_internal/planner/exchange/sort_task_spec.py
  python/ray/data/_internal/util.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_execution_optimizer.py
  python/ray/data/tests/test_transform_pyarrow.py
  python/ray/serve/_private/utils.py
Labels: go

#50249 [RLlib] APPO accelerate vol 03: Remove "infos" column from train batch by default.
  rllib/algorithms/impala/impala_learner.py
  rllib/connectors/learner/__init__.py
  rllib/connectors/learner/add_columns_from_episodes_to_train_batch.py
  rllib/connectors/learner/add_infos_from_episodes_to_train_batch.py
  rllib/offline/tests/test_offline_prelearner.py
Labels: tests-ok, go

#50023 [core][compiled graphs] Support experimental_compile(_default_communicator=comm)
  python/ray/dag/collective_node.py
  python/ray/dag/compiled_dag_node.py
  python/ray/dag/dag_node.py
  python/ray/dag/tests/experimental/test_collective_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/experimental/channel/common.py
  python/ray/experimental/channel/torch_tensor_nccl_channel.py
  python/ray/experimental/channel/torch_tensor_type.py
  python/ray/experimental/collective/conftest.py
  python/ray/util/collective/collective.py
Labels: go

#49933 [Grafana] Removes legends label `{{replica}}` for `serve_deoloyment_dashboard` for better observability
  python/ray/dashboard/modules/metrics/dashboards/serve_deployment_dashboard_panels.py
Labels: dashboard, observability, go

#50104 [data] add LanceDB sink
  doc/source/data/api/input_output.rst
  python/ray/data/_internal/datasource/lance_datasink.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_lance.py
  python/requirements/ml/data-test-requirements.txt
  python/requirements_compiled.txt
Labels: go

#50169 [LLM Batch] Support out-of-order UDF outputs
  python/ray/llm/_internal/batch/stages/base.py
  python/ray/llm/_internal/batch/stages/chat_template_stage.py
  python/ray/llm/_internal/batch/stages/http_request_stage.py
  python/ray/llm/_internal/batch/stages/prepare_image_stage.py
  python/ray/llm/_internal/batch/stages/tokenize_stage.py
  python/ray/llm/tests/batch/processor/test_base.py
  python/ray/llm/tests/batch/stages/test_base.py
  python/ray/llm/tests/batch/stages/test_chat_template_stage.py
  python/ray/llm/tests/batch/stages/test_http_request_stage.py
  python/ray/llm/tests/batch/stages/test_prepare_image_stage.py
  python/ray/llm/tests/batch/stages/test_tokenize_stage.py
Labels: go

#49887 User guide for persistent GCS w/ redis and kuberay
  doc/source/cluster/kubernetes/user-guides.md
  doc/source/cluster/kubernetes/user-guides/kuberay-gcs-ft.md
  doc/source/cluster/kubernetes/user-guides/kuberay-gcs-persistent-ft.md
Labels: go

#48212 Update KubeRay Autoscaler to use NumOfHosts for min/max workers
  python/ray/autoscaler/_private/kuberay/autoscaling_config.py
  python/ray/tests/kuberay/test_autoscaling_config.py
Labels: kuberay, go

#50127 Update tune-storage.rst
  doc/source/tune/tutorials/tune-storage.rst
Labels: tune, go

#50208 [docs] pip install instruction is missing "ray[serve]"
  doc/source/serve/tutorials/serve-ml-models.md
Labels: docs, go

#50251 [CI] Remove tailing white space [2/N]
  release/air_tests/air_benchmarks/mlperf-train/file_size_benchmark.sh
  release/air_tests/air_benchmarks/mlperf-train/oom_benchmark.sh
  release/benchmarks/object_store/config.yaml
  release/benchmarks/single_node/config.yaml
  release/jobs_tests/compute_tpl_gce_gpu_node.yaml
  release/jobs_tests/compute_tpl_gce_gpu_worker.yaml
  release/long_running_distributed_tests/README.rst
  release/long_running_distributed_tests/compute_tpl_gce.yaml
  release/long_running_tests/README.rst
  release/long_running_tests/app_config.yaml
  release/nightly_tests/dataset/run_image_loader_microbenchmark.sh
  release/nightly_tests/dataset/stable_diffusion_benchmark_compute_gce.yaml
  release/ray_release/byod/byod_agent_stress_test.sh
  release/ray_release/byod/byod_data_pipelined_test.sh
  release/ray_release/byod/byod_dataset_shuffle.sh
  release/ray_release/byod/byod_dolly_test.sh
  release/ray_release/byod/byod_horovod_master_test.sh
  release/ray_release/byod/byod_horovod_test.sh
  release/ray_release/byod/byod_ray_lightning_master_test.sh
  release/ray_release/byod/byod_ray_lightning_test.sh
  release/ray_release/byod/byod_rllib_dreamerv3_test.sh
  release/ray_release/byod/byod_rllib_test.sh
  release/ray_release/byod/byod_stable_diffusion.sh
  release/ray_release/byod/byod_vicuna_test.sh
  release/ray_release/byod/requirements_debian_byod.txt
Labels: go

#50250 [CI] Remove tailing white space [1/N]
  .buildkite/README.md
  .buildkite/base.rayci.yml
  .buildkite/bisect/bisect.rayci.yml
  .buildkite/hooks/post-command
  .buildkite/llm.rayci.yml
  .buildkite/ml.rayci.yml
  .buildkite/release-automation/pre_release.rayci.yml
  .buildkite/release-automation/wheels.rayci.yml
  .buildkite/serve.rayci.yml
  .buildkite/serverless.rayci.yml
  .github/PULL_REQUEST_TEMPLATE.md
  bazel/BUILD.redis
  cpp/symbols/ray_api_exported_symbols_linux.lds
  doc/azure/azure-ray-template.json
  java/java-release-guide.md
  python/build-wheel-macos.sh
  python/ray/_private/thirdparty/pathspec/LICENSE
  python/ray/autoscaler/_private/readonly/example.yaml
  python/ray/autoscaler/_private/vsphere/ARCHITECTURE.md
  python/ray/autoscaler/gcp/example-tpu-pod-topology.yaml
  python/ray/runtime_env/ARCHITECTURE.md
  python/ray/serve/tests/test_config_files/duplicate_app_names.yaml
  python/ray/serve/tests/test_config_files/duplicate_app_routes.yaml
  python/ray/util/client/ARCHITECTURE.md
  python/ray/workflow/examples/comparisons/argo/conditionals_argo.yaml
  python/requirements/ml/dl-cpu-requirements.txt
Labels: go

#50236 fix anyscale template utm tracking
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
  doc/source/ray-overview/getting-started.md
  doc/source/serve/tutorials/stable-diffusion.md
Labels: go

#50204 Add contraction
  doc/source/ray-security/index.md
Labels: go

#50232 add missing xgboost pip requirement
  doc/source/train/examples/xgboost/xgboost_example.ipynb
Labels: go

#50258 Reduce combinations in test_split_at_indices_coverage_complete
  python/ray/data/tests/test_split.py
Labels: go

#49426 [data/preprocessors] allow scalers to be used in append mode
  python/ray/data/preprocessors/scaler.py
  python/ray/data/tests/preprocessors/test_scaler.py
Labels: data, go

#50243 [core] De-glob bazel dependencies
  BUILD.bazel
Labels: go

#50183 [refactor] Move custom_types from `util/state` to `_private/`
  python/ray/_private/custom_types.py
  python/ray/experimental/state/custom_types.py
  python/ray/util/state/common.py
Labels: go

#50019 [train] Add training + data ingestion benchmark fixtures + image classification example
  release/release_tests.yaml
  release/train_tests/benchmark/compute_configs/compute_gpu_4x4_aws.yaml
  release/train_tests/benchmark/compute_configs/compute_gpu_4x4_gce.yaml
  release/train_tests/benchmark/config.py
  release/train_tests/benchmark/dataloader_factory.py
  release/train_tests/benchmark/factory.py
  release/train_tests/benchmark/image_classification/factory.py
  release/train_tests/benchmark/image_classification/imagenet.py
  release/train_tests/benchmark/train_benchmark.py
Labels: go

#49402 fix: docs cluster setup links
  doc/source/ray-more-libs/joblib.rst
  doc/source/ray-more-libs/multiprocessing.rst
Labels: docs, go

#50192 [serve][doc] update serve vllm openai example for latest vllm version
  doc/source/serve/doc_code/vllm_openai_example.py
Labels: go

#50155 Update troubleshooting.md
  doc/source/cluster/kubernetes/troubleshooting/troubleshooting.md
Labels: docs, go

#50274 [Docs] Mention Anyscale platform provids e2e fault tolerance
  doc/source/serve/production-guide/fault-tolerance.md
Labels: docs, go

#50273 [doc][core][cgraph] Use with_tensor_transport API
  doc/source/ray-core/compiled-graph/overlap.rst
  doc/source/ray-core/compiled-graph/quickstart.rst
Labels: go

#50271 [core][cgraph] Fix flaky test_dag_exception_chained
  python/ray/dag/compiled_dag_node.py
Labels: go

#50269 [Data] Make `memory` an explicit map parameter
  doc/source/data/transforming-data.rst
  python/ray/data/dataset.py
  python/ray/data/grouped_data.py
  python/ray/data/tests/test_map.py
Labels: go

#50291 [Data] Adding support for type promotion when concatenating blocks
  python/ray/data/BUILD
  python/ray/data/_internal/arrow_block.py
  python/ray/data/_internal/arrow_ops/transform_pyarrow.py
  python/ray/data/_internal/datasource/parquet_datasink.py
  python/ray/data/tests/test_all_to_all.py
  python/ray/data/tests/test_transform_pyarrow.py
Labels: go

#50261 [Utils] [CORE-658] ray.util.Queue Empty and Full exceptions extend queue.Empty and Full
  python/ray/_private/test_utils.py
  python/ray/tests/test_queue.py
  python/ray/util/queue.py
Labels: go

#50289 [core][cgraph] Increase test_torch_tensor_dag_gpu timeout
  python/ray/dag/BUILD
Labels: go

#50241 [core] [easy] [no-op] Minor optimization to avoid heap allocation
  src/ray/util/BUILD
  src/ray/util/container_util.h
  src/ray/util/pipe_logger.cc
  src/ray/util/tests/container_util_test.cc
Labels: go

#49218 [core] Update `num_objects` to wait for in plasma store provider loop
  src/ray/core_worker/core_worker.cc
Labels: core, go

#50302 [doc][core][cgraph] Use ray[cgraph] rather than ray[cg] in docs
  doc/source/ray-core/compiled-graph/quickstart.rst
Labels: go

#50282 [core] Add debug source for core worker
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_options.h
  src/ray/core_worker/lib/java/io_ray_runtime_RayNativeRuntime.cc
Labels: go

#50279 [core] Introduces MutexProtected for reader and writer locks
  BUILD.bazel
  src/ray/core_worker/core_worker_process.cc
  src/ray/core_worker/core_worker_process.h
  src/ray/util/BUILD
  src/ray/util/counter_map.h
  src/ray/util/mutex_protected.h
Labels: go

#50295 [Data] Remove dead code from `plan_udf_map_op`
  python/ray/data/_internal/planner/plan_udf_map_op.py
Labels: go

#50252 [CI] Remove tailing white space [3/N]
  .pre-commit-config.yaml
  release/gcloud_docker_login.sh
  release/run_release_test.sh
  release/runtime_env_tests/rte_gce_small.yaml
  release/serve_tests/compute_tpl_32_cpu_autoscaling_gce.yaml
  release/serve_tests/compute_tpl_32_cpu_gce.yaml
  release/serve_tests/compute_tpl_gpu_node_gce.yaml
  release/tune_tests/scalability_tests/tpl_gce_16x2.yaml
  release/tune_tests/scalability_tests/tpl_gce_16x64.yaml
  release/tune_tests/scalability_tests/tpl_gce_20x2.yaml
  rllib/algorithms/appo/README.md
  rllib/algorithms/cql/README.md
  rllib/algorithms/dqn/README.md
  rllib/algorithms/ppo/README.md
  rllib/algorithms/sac/README.md
  rllib/benchmarks/torch_compile/README.md
  rllib/tuned_examples/cql/halfcheetah-bc.yaml
  rllib/tuned_examples/cql/halfcheetah-cql.yaml
  rllib/tuned_examples/cql/hopper-bc.yaml
  rllib/tuned_examples/cql/hopper-cql.yaml
  rllib/tuned_examples/cql/pendulum-cql.yaml
Labels: go

#50299 [train] Disable `local_shuffle_buffer_size` in train data ingest benchmark
  release/train_tests/benchmark/config.py
  release/train_tests/benchmark/dataloader_factory.py
  release/train_tests/benchmark/factory.py
  release/train_tests/benchmark/image_classification/factory.py
  release/train_tests/benchmark/train_benchmark.py
Labels: go

#50314 [llm] change llm build to python 3.11
  .buildkite/base.rayci.yml
  .buildkite/llm.rayci.yml
  ci/docker/llm.build.Dockerfile
  ci/docker/llm.build.wanda.yaml
Labels: go

#50265 Minor clarifications to the Pytorch ResNet batch prediction tutorial
  doc/source/data/examples/pytorch_resnet_batch_prediction.ipynb
Labels: docs, data, go

#50297 [LLM Serving] add skeleton public api to ray.serve.llm
  doc/source/serve/api/index.md
  python/ray/serve/llm.py
  python/ray/serve/tests/unit/test_llm_imports.py
Labels: go

#50181 [train] refactor WorkerGroup state
  python/ray/train/v2/_internal/callbacks/datasets.py
  python/ray/train/v2/_internal/callbacks/user_callback.py
  python/ray/train/v2/_internal/execution/callback.py
  python/ray/train/v2/_internal/execution/checkpoint/report_handler.py
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/_internal/execution/failure_handling/default.py
  python/ray/train/v2/_internal/execution/failure_handling/failure_policy.py
  python/ray/train/v2/_internal/execution/scaling_policy/fixed.py
  python/ray/train/v2/_internal/execution/scaling_policy/scaling_policy.py
  python/ray/train/v2/_internal/execution/worker_group/__init__.py
  python/ray/train/v2/_internal/execution/worker_group/poll.py
  python/ray/train/v2/_internal/execution/worker_group/state.py
  python/ray/train/v2/_internal/execution/worker_group/worker.py
  python/ray/train/v2/_internal/execution/worker_group/worker_group.py
  python/ray/train/v2/tests/test_accelerator_utils.py
  python/ray/train/v2/tests/test_controller.py
  python/ray/train/v2/tests/test_data_integration.py
  python/ray/train/v2/tests/test_failure_policy.py
  python/ray/train/v2/tests/test_report_handler.py
  python/ray/train/v2/tests/test_worker_group.py
Labels: go

#50311 [serve] Properly propagate backpressure error
  python/ray/serve/_private/proxy.py
  python/ray/serve/_private/replica.py
  python/ray/serve/exceptions.py
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_backpressure.py
Labels: go

#49791 [Doc] Add Data-Juicer Integration to ecosystem and corresponding example to example gallery
  .vale/styles/Google/WordList.yml
  .vale/styles/config/vocabularies/General/accept.txt
  doc/source/custom_directives.py
  doc/source/data/examples.yml
  doc/source/data/examples/data_juicer_distributed_data_processing.md
  doc/source/images/data_juicer.png
  doc/source/ray-core/starting-ray.rst
  doc/source/ray-overview/ray-libraries.rst
Labels: docs, go

#50267 cleaned up tutorial: less verbose outputs, added notes
  doc/source/data/examples/batch_inference_object_detection.ipynb
Labels: docs, data, go

#50326 [ci][train] increase doc test parallelism from 1 to 2
  .buildkite/ml.rayci.yml
Labels: go

#50321 [train v2] Add telemetry for trainer usage
  python/ray/air/_internal/usage.py
  python/ray/air/tests/test_air_usage.py
  python/ray/train/v2/api/data_parallel_trainer.py
  src/ray/protobuf/usage.proto
Labels: go

#50325 Fix test_map_rows_e2e
  python/ray/data/tests/test_execution_optimizer.py
Labels: go

#50303 [data/docs] Revamp main page for data
  doc/source/data/batch_inference.rst
  doc/source/data/comparisons.rst
  doc/source/data/data.rst
  doc/source/data/key-concepts.rst
  doc/source/ray-overview/getting-started.md
  doc/source/train/user-guides/data-loading-preprocessing.rst
Labels: go

#50322 [train v2] Enable deprecation messages which link to a migration guide
  python/ray/train/constants.py
  python/ray/train/tests/test_trainer_restore.py
  python/ray/train/v2/api/data_parallel_trainer.py
  python/ray/train/v2/api/result.py
  python/ray/train/v2/lightgbm/lightgbm_trainer.py
  python/ray/train/v2/tests/test_v2_api.py
Labels: go

#50320 [core] Remove unused field: stdout and stderr file for core worker
  python/ray/_private/worker.py
  python/ray/_raylet.pyx
  python/ray/includes/libcoreworker.pxd
  src/ray/core_worker/core_worker.cc
  src/ray/core_worker/core_worker_options.h
Labels: go

#50327 [llm] add related requirement files
  ci/compile_llm_requirements.sh
  ci/docker/llm.build.Dockerfile
  ci/docker/llm.build.wanda.yaml
  python/requirements/base-test-requirements.txt
  python/requirements/llm/llm-requirements.txt
  python/requirements/llm/llm-test-requirements.txt
  python/requirements_compiled_ray_py311.txt
  python/requirements_compiled_ray_test_py311.txt
  python/requirements_compiled_rayllm_py311.txt
  python/requirements_compiled_rayllm_test_py311.txt
Labels: go

#50339 [deps] add llm extra requirement declaration
  python/requirements/llm/llm-requirements.txt
  python/setup.py
Labels: go

#49959 [RLlib] Offpolicy add metrics to multi-agent replay buffers.
  rllib/algorithms/algorithm.py
  rllib/algorithms/dreamerv3/dreamerv3.py
  rllib/offline/tests/test_offline_prelearner.py
  rllib/tuned_examples/dqn/multi_agent_cartpole_dqn.py
  rllib/utils/metrics/__init__.py
  rllib/utils/replay_buffers/episode_replay_buffer.py
  rllib/utils/replay_buffers/multi_agent_episode_buffer.py
  rllib/utils/replay_buffers/multi_agent_prioritized_episode_buffer.py
  rllib/utils/replay_buffers/prioritized_episode_buffer.py
Labels: go

#49004 fix all invalid escape sequences
  ci/lint/clang-tidy-diff.py
  ci/pipeline/determine_tests_to_run.py
  pyproject.toml
  python/ray/_private/log_monitor.py
  python/ray/dag/tests/experimental/test_accelerated_dag.py
  python/ray/dag/tests/experimental/test_torch_tensor_dag.py
  python/ray/dashboard/modules/log/log_manager.py
  python/ray/data/grouped_data.py
  python/ray/data/preprocessors/hasher.py
  python/ray/data/tests/test_stats.py
  python/ray/serve/tests/test_api.py
  python/ray/serve/tests/test_handle_streaming.py
  python/ray/serve/tests/test_logging.py
  python/ray/serve/tests/unit/test_config.py
  python/ray/tests/test_basic.py
  python/ray/tests/test_job.py
  python/ray/tests/test_traceback.py
  python/ray/workflow/examples/function_chain.py
  release/air_tests/air_benchmarks/mlperf-train/metric_utils.py
  release/k8s_tests/solution.py
  release/util/get_contributors.py
  rllib/algorithms/impala/torch/vtrace_torch_v2.py
  rllib/core/learner/learner_group.py
  rllib/models/tf/tf_distributions.py
  rllib/models/torch/torch_distributions.py
  rllib/offline/estimators/doubly_robust.py
Labels: data, go

#50283 [Dashboard] Job page add filters
  python/ray/dashboard/client/src/pages/job/hook/useJobList.ts
  python/ray/dashboard/client/src/pages/job/index.tsx
Labels: dashboard, go

#50355 [llm] change llm base from ml base to test base
  .buildkite/llm.rayci.yml
  ci/docker/llm.build.Dockerfile
  ci/docker/llm.build.wanda.yaml
Labels: go

#49708 Update transforming-data.rst
  doc/source/data/transforming-data.rst
Labels: go

#49456 [doc] [easy] Update `compute` to `concurrency` in the code examples.
  doc/source/_templates/index.html
Labels: docs, go

#49545 Update development.rst
  doc/source/ray-contribute/development.rst
Labels: docs, core, go

#50176 [Autoscaler] Make AUTOSCALER_MAX_RESOURCE_DEMAND_VECTOR_SIZE configurable
  python/ray/autoscaler/_private/constants.py
Labels: core, go

#50334 [core] De-glob all cc targets
  BUILD.bazel
Labels: go

#50350 [core] Make get runtime context thread-safe
  python/ray/runtime_context.py
Labels: go

#50360 [core] re-enable tests_events_with_crash
  .buildkite/core.rayci.yml
  python/ray/workflow/BUILD
Labels: go

#49678 Update services.py: remove one duplicated params: `--runtime-env-agen…
  python/ray/_private/services.py
Labels: core, go

#50364 [core] [easy] [no-op] No using clause at header file
  src/ray/gcs/gcs_client/test/gcs_client_test.cc
  src/ray/gcs/gcs_server/gcs_init_data.cc
  src/ray/gcs/gcs_server/gcs_job_manager.cc
  src/ray/gcs/gcs_server/gcs_placement_group_manager.cc
  src/ray/gcs/gcs_server/gcs_table_storage.cc
  src/ray/gcs/gcs_server/gcs_table_storage.h
  src/ray/gcs/gcs_server/gcs_worker_manager.cc
  src/ray/gcs/gcs_server/gcs_worker_manager.h
  src/ray/gcs/gcs_server/store_client_kv.cc
  src/ray/gcs/redis_context.h
Labels: go

#50371 [ci] reduce rllib affected condition
  ci/pipeline/determine_tests_to_run.py
Labels: go

#50353 [RLlib] APPO/IMPALA accelerate (vol 7): Fix various performance issues, mostly in `Learner` class.
  rllib/algorithms/appo/utils.py
  rllib/algorithms/impala/impala.py
  rllib/algorithms/impala/impala_learner.py
  rllib/connectors/common/frame_stacking.py
  rllib/connectors/common/numpy_to_tensor.py
  rllib/connectors/connector_pipeline_v2.py
  rllib/core/learner/torch/torch_learner.py
  rllib/utils/numpy.py
  rllib/utils/spaces/space_utils.py
Labels: rllib, rllib-algorithms, rllib-newstack, go

#50288 [CI] Fix shellcheck warning in pre-commit
  .pre-commit-config.yaml
  ci/lint/lint.sh
  ci/ray_ci/macos/macos_ci_build.sh
  ci/ray_ci/rllib_contrib/rllib_contrib_ci.sh
  setup_hooks.sh
Labels: go

#49003 fix type checking of lazy imports
  python/ray/__init__.py
Labels: core, go

#50359 [ci] simplify gpu ci base
  ci/docker/base.build.Dockerfile
  ci/docker/base.gpu.Dockerfile
  ci/docker/base.gpu.py39.wanda.yaml
  ci/docker/base.gpu.wanda.yaml
  ci/docker/docgpu.build.wanda.yaml
  ci/docker/llm.build.Dockerfile
  ci/docker/ml.build.Dockerfile
  ci/docker/ml.build.wanda.yaml
  ci/docker/mllightning2gpu.build.wanda.yaml
  ci/env/install-dependencies.sh
Labels: go

#50337 [CI] Remove tailing white space [N/N]
  .pre-commit-config.yaml
  ci/build/upload_build_info.sh
  ci/docker/serve.build.py39.wanda.yaml
  ci/env/install-miniconda.sh
  ci/lint/lint.sh
  ci/ray_ci/core.tests.yml
  ci/ray_ci/oss_config.yaml
  ci/ray_ci/rllib.tests.yml
  ci/ray_ci/windows/build_base.sh
  ci/ray_ci/windows/build_ray.sh
  src/ray/design_docs/actor_states.rst
  src/ray/design_docs/id_specification.md
Labels: go

#50368 [RLlib] APPO/IMPALA accelerate (vol 08): Call `metrics.reduce()` fewer times in IMPALALearner.
  rllib/algorithms/algorithm_config.py
  rllib/algorithms/impala/impala_learner.py
  rllib/connectors/connector_pipeline_v2.py
  rllib/utils/__init__.py
Labels: go

#50296 [Data] Rebasing `ShufflingBatcher` onto `try_combine_chunked_columns`
  python/ray/data/BUILD
  python/ray/data/_internal/batcher.py
Labels: go

#50382 [train] disable tensorflow test for python 3.12+
  python/ray/air/tests/test_air_usage.py
Labels: go

#50383 [llm] extend llm CI tests to gpu
  .buildkite/base.rayci.yml
  .buildkite/llm.rayci.yml
  ci/docker/llm.build.wanda.yaml
Labels: go

#50333 [core] spdlog newliner sink
  src/ray/util/BUILD
  src/ray/util/spdlog_newliner_sink.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/spdlog_newliner_sink_test.cc
Labels: go

#50385 [Cherry-pick] Cherry-picking #50210 to 2.42.1
  python/ray/data/_internal/util.py
  python/ray/data/tests/block_batching/test_util.py
Labels: go

#50310 [core] Add grace period for core worker to initialize in IO worker
  python/ray/_private/external_storage.py
Labels: go

#50388 [train v2] Expose `WorkerGroupState` to the `ScalingPolicy`
  python/ray/train/v2/_internal/execution/controller/controller.py
  python/ray/train/v2/_internal/execution/scaling_policy/fixed.py
  python/ray/train/v2/_internal/execution/scaling_policy/scaling_policy.py
  python/ray/train/v2/_internal/execution/worker_group/state.py
  python/ray/train/v2/tests/test_controller.py
Labels: go

#50389 [ci] cleanup upload build info
  ci/build/upload_build_info.sh
  ci/ray_ci/ray_docker_container.py
  ci/ray_ci/test_ray_docker_container.py
Labels: go

#50356 [doc] compile api annotation check into single job
  .buildkite/lint.rayci.yml
  ci/lint/lint.sh
  ci/ray_ci/doc/cmd_check_api_discrepancy.py
Labels: go

#50392 [Data] Fix invalid escape sequences in `grouped_data.py` docstrings
  python/ray/data/grouped_data.py
Labels: go

#50341 [Refactor] fix ruff rule B035: static-key-dict-comprehension
  pyproject.toml
  python/ray/tests/aws/utils/stubs.py
Labels: go

#50369 [core] Implement tag based shared pointer factory function
  src/ray/common/client_connection.cc
  src/ray/common/client_connection.h
Labels: go

#49955 Fix with_docker_exec by using the provided docker_cmd
  python/ray/autoscaler/_private/docker.py
Labels: core, go

#50395 [serve] Fix flaky `test_backpressure_model_composition`
  python/ray/serve/tests/test_backpressure.py
Labels: go

#50179 Add repartition by targer number of rows per block
  python/ray/data/_internal/datasource/avro_datasource.py
  python/ray/data/_internal/execution/interfaces/physical_operator.py
  python/ray/data/_internal/execution/operators/map_transformer.py
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/_internal/output_buffer.py
  python/ray/data/_internal/planner/plan_udf_map_op.py
  python/ray/data/_internal/planner/planner.py
  python/ray/data/context.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_all_to_all.py
Labels: go

#50292 [docs] fix version picker selected version
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: go

#50396 [core] Implement scoped env setter
  src/ray/util/BUILD
  src/ray/util/scoped_env_setter.cc
  src/ray/util/scoped_env_setter.h
  src/ray/util/tests/BUILD
  src/ray/util/tests/scoped_env_setter_test.cc
Labels: go

#50374 [chore] Avoid re-import `ray._private.utils` in reporter agent
  python/ray/dashboard/modules/reporter/reporter_agent.py
Labels: go

#50365 [core] Optimize GCS build time
  BUILD.bazel
  python/ray/includes/global_state_accessor.pxd
  src/ray/gcs/gcs_server/gcs_function_manager.h
  src/ray/gcs/gcs_server/gcs_init_data.h
  src/ray/gcs/gcs_server/gcs_kv_manager.h
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.cc
  src/ray/gcs/gcs_server/gcs_redis_failure_detector.h
  src/ray/gcs/gcs_server/gcs_task_manager.cc
  src/ray/gcs/gcs_server/gcs_task_manager.h
  src/ray/gcs/gcs_server/store_client_kv.h
  src/ray/gcs/store_client/observable_store_client.h
  src/ray/gcs/store_client/store_client.h
  src/ray/util/tests/spdlog_newliner_sink_test.cc
Labels: go

#50245 [Data] Support class constructor args for filter()
  python/ray/data/_internal/logical/operators/map_operator.py
  python/ray/data/dataset.py
  python/ray/data/tests/test_map.py
Labels: data, go

#47103 docs: fix link in getting-started.md
  doc/source/ray-overview/getting-started.md
Labels: P2, docs, go

#50345 [data/docs] Rewrote docstring for AggregateFn, including a usage example
  python/ray/data/aggregate.py
Labels: docs, go

#50363 [chore] Remove `from grpc.experimental import aio as aiogrpc`
  python/ray/_private/gcs_pubsub.py
  python/ray/_private/utils.py
  python/ray/dashboard/agent.py
  python/ray/dashboard/head.py
Labels: go

#50425 Fix `test_ray_debugger` on windows
  python/ray/tests/test_ray_debugger.py
Labels: go

#50270 [LLM Batch][4/N] vLLM engine stage
  .buildkite/llm.rayci.yml
  doc/source/conf.py
  python/ray/llm/_internal/batch/stages/__init__.py
  python/ray/llm/_internal/batch/stages/vllm_engine_stage.py
  python/ray/llm/_internal/utils.py
  python/ray/llm/tests/batch/BUILD
  python/ray/llm/tests/batch/cpu/processor/test_http_request_proc.py
  python/ray/llm/tests/batch/cpu/processor/test_processor_base.py
  python/ray/llm/tests/batch/cpu/stages/test_chat_template_stage.py
  python/ray/llm/tests/batch/cpu/stages/test_http_request_stage.py
  python/ray/llm/tests/batch/cpu/stages/test_prepare_image_stage.py
  python/ray/llm/tests/batch/cpu/stages/test_stage_base.py
  python/ray/llm/tests/batch/cpu/stages/test_tokenize_stage.py
  python/ray/llm/tests/batch/gpu/stages/test_vllm_engine_stage.py
  python/ray/llm/tests/batch/processor/BUILD
  python/ray/llm/tests/batch/stages/BUILD
Labels: go

#50280 [Core] Ignore stale ReportWorkerBacklogRequest
  BUILD.bazel
  src/mock/ray/raylet/local_task_manager.h
  src/mock/ray/raylet/worker_pool.h
  src/ray/raylet/local_task_manager.h
  src/ray/raylet/local_task_manager_test.cc
  src/ray/raylet/node_manager.cc
  src/ray/raylet/node_manager.h
  src/ray/raylet/scheduling/cluster_task_manager_test.cc
  src/ray/raylet/scheduling/local_task_manager_interface.h
  src/ray/raylet/test/node_manager_test.cc
  src/ray/raylet/worker_pool.cc
  src/ray/raylet/worker_pool.h
  src/ray/raylet/worker_pool_test.cc
Labels: go

#50427 [docs] fix version picker selected version (#50292)
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: go

#50409 [core] Redact redis password in log
  python/ray/util/client/server/server.py
Labels: core, go

#50429 cherrypick version picker changes 2.41.0
  doc/source/_static/css/custom.css
  doc/source/conf.py
  doc/source/custom_directives.py
Labels: go

#50442 [core] [easy] Add error message in filesystem status
  src/ray/util/filesystem.cc
Labels: go

#50451 [serve] Remove serve-related logic from Ray core tests
  python/ray/serve/tests/BUILD
  python/ray/serve/tests/test_telemetry.py
  python/ray/serve/tests/test_telemetry_serve_used.py
  python/ray/tests/test_client_library_integration.py
  python/ray/tests/test_streaming_generator_3.py
  python/ray/tests/test_usage_stats.py
Labels: go

#50331 Merge Ray Train XGboost tutorials
  doc/source/data/examples.yml
  doc/source/ray-overview/use-cases.rst
  doc/source/train/distributed-xgboost-lightgbm.rst
  doc/source/train/doc_code/gbdt_user_guide.py
  doc/source/train/examples.yml
  doc/source/train/examples/xgboost/distributed-xgboost-lightgbm.ipynb
  doc/source/train/examples/xgboost/xgboost_example.ipynb
  doc/source/train/more-frameworks.rst
Labels: go

#50332 [Data] Persist ParquetDatasource metadata.
  python/ray/data/_internal/datasource/parquet_datasource.py
Labels: data, go

#50464 [Data] Improve warning message if required dependency isn't installed
  python/ray/data/_internal/util.py
Labels: go

#50459 [Data] Deflake `test_map_batches_async_generator`
  python/ray/data/tests/test_map.py
Labels: go

#50466 [tune] Remove a print statement in internal code
  python/ray/tune/trainable/trainable.py
Labels: go

#50248 [core] Fix std::flush with `istream::readsome`
  src/ray/common/ray_config_def.h
  src/ray/util/BUILD
  src/ray/util/pipe_logger.cc
  src/ray/util/spdlog_newliner_sink.h
  src/ray/util/stream_redirection_utils.cc
  src/ray/util/tests/BUILD
  src/ray/util/tests/pipe_logger_test.cc
  src/ray/util/tests/spdlog_newliner_sink_test.cc
  src/ray/util/tests/stream_redirection_exit_test.cc
Labels: go

#50461 [core] 1/N. ray.wait(_, num_returns=1) performance improvements
  src/ray/core_worker/core_worker.cc
Labels: go, jira-core

#50457 Add instructions for creating anchor links in ipynb notebooks
  doc/source/ray-contribute/docs.md
Labels: go

#50468 [bazel] do not save date; save content digest instead
  bazel/ray.bzl
Labels: go
